# GTA — Genel kültür: Tarih (Atatürk İlkeleri ve İnkılap Tarihi), Deneme 6–10, 11–15. sorular
K = 'Canli_7_24_Genel_Kultur_Kitabi.txt'
Q = [
# ===================== DENEME 6 (2021) =====================
dict(id='D6-011', cikmis='2021/11', konu='Millî Mücadele’ye hazırlık – Sivas Kongresi', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Sivas Kongresi (Kararların uygulanması)',
 cek='Sivas sonrası Temsil Heyetinin yürütme işlevine örnek: Ali Fuat Paşa’nın Batı Anadolu millî kuvvetleri komutanlığına atanması.',
 kok=['Aşağıdakilerden hangisi, Sivas Kongresi’nden sonra yetki alanı ülke çapında genişleyen Temsil Heyetinin yürütmeye ilişkin bir işlev üstlenmesine örnek gösterilen gelişmedir?'],
 d='Ali Fuat Paşa’nın Batı Anadolu’daki millî kuvvetlerin komutanlığına atanması',
 c=['Hıyanet-i Vataniye Kanunu’nun Meclis yönetimine karşı faaliyetler için kabulü',
    'Üyeleri Meclis içinden seçilen İstiklal Mahkemelerinin kanunla kurulması',
    'Tekâlif-i Milliye emirleriyle ordunun ihtiyaçları için yükümlülük getirilmesi',
    'Sovyet Rusya ile karşılıklı desteği öngören Moskova Antlaşması’nın imzalanması'],
 tuzak=False,
 g='Sivas Kongresi’nden sonra Temsil Heyetinin yetkisi ülke çapında genişlemiş; Ali Fuat Paşa’nın Batı Anadolu’daki millî kuvvetlerin komutanlığına atanması, heyetin yürütmeye ilişkin işlev üstlenmesinin örneği olmuştur. Hıyanet-i Vataniye Kanunu ve İstiklal Mahkemeleri, 23 Nisan 1920’de açılan Meclisin otoritesini korumak için kurduğu araçlardır; Moskova Antlaşması ise TBMM Hükûmeti ile Sovyet Rusya arasında yapılmıştır. (MD Genel Kültür Kitabı – Tarih: Sivas Kongresi)',
 kanit=K + ' | Temsil Heyetinin yetkisi ülke çapında genişledi. Ali Fuat Paşa’nın Batı Anadolu’daki millî kuvvetlerin komutanlığına atanması, heyetin yürütmeye ilişkin işlev üstlenmesine örnektir. || ' + K + ' | Sovyet Rusya ile TBMM Hükûmeti arasındaki anlaşma karşılıklı desteği'),

dict(id='D6-012', cikmis='2021/12', konu='Ateşkes ve barış – Mudanya Ateşkesi', tip='T1', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Mudanya: askerî sonuçtan siyasete',
 cek='Mudanya ile Doğu Trakya yeni cephe savaşı yürütülmeden, takvimli Yunan çekilmesi ve jandarma yerleşimiyle Türkiye’ye devredildi.',
 kok=['11 Ekim 1922 tarihli Mudanya Ateşkesi ile ilgili aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Doğu Trakya, yeni bir geniş cephe savaşının ardından Yunan kuvvetlerinden geri alınmıştır.',
 c=['Yunan kuvvetlerinin Doğu Trakya’dan çekilmesi ve bölgenin devri için takvim belirlenmiştir.',
    'Bölgeye Türk jandarmasının yerleştirilmesi gibi geçiş düzenlemeleri yapılmıştır.',
    'Boğazlar, kapitülasyonlar ve borçlar gibi konular barış konferansına bırakılmıştır.',
    'Türk ordusunun Batı Anadolu’daki başarısı görüşmelerin temel güç dayanağı olmuştur.'],
 tuzak=False,
 g='Mudanya Ateşkesi ile Yunan kuvvetlerinin Doğu Trakya’dan çekilmesi ve bölge yönetiminin Türkiye’ye devri için takvim belirlenmiş, böylece yeni bir geniş cephe savaşı yürütülmeden siyasi sonuç elde edilmiştir. Türk jandarmasının yerleştirilmesi gibi geçiş düzenlemeleri yapılmış; Boğazlar, kapitülasyonlar ve borçlar ise barış konferansına kalmıştır. (MD Genel Kültür Kitabı – Tarih: Mudanya Ateşkesi)',
 kanit=K + ' | Yunan kuvvetlerinin Doğu Trakya’dan çekilmesi ve bölge yönetiminin Türkiye’ye devri için takvim belirlendi. Türk jandarmasının yerleştirilmesi gibi geçiş düzenlemeleri yapıldı. Böylece yeni bir geniş cephe savaşı yürütülmeden siyasi sonuç elde edildi.'),

dict(id='D6-013', cikmis='2021/13', konu='Misak-ı Millî ve Meclis – Birinci ve İkinci Meclis', tip='T4', z='Z',
 madde='Genel Kültür Kitabı – Tarih: Birinci Meclis nasıl çalıştı?; Otorite ve anayasal düzen (1921 Anayasası)',
 cek='Birinci Meclis 1921 Teşkilât-ı Esasiye’yi kabul etti; Lozan onayı ve Cumhuriyet ilanı İkinci Meclisin işidir.',
 kok=['Aşağıdakilerden hangisi, Birinci Dönem TBMM’nin gerçekleştirdiği işlerden biridir?'],
 d='1921 Teşkilât-ı Esasiye Kanunu’nun kabul edilmesi',
 c=['1924 Anayasası’nın Meclis tarafından kabul edilmesi',
    'Lozan Barış Antlaşması’nın Mecliste onaylanması',
    'Cumhuriyetin yönetim biçimi olarak ilan edilmesi',
    'Tevhid-i Tedrisat Kanunu’nun kabul edilmesi'],
 tuzak=False,
 g='Birinci Meclis Millî Mücadele’yi yürütmüş ve 20 Ocak 1921’de egemenliğin millete ait olduğunu belirten Teşkilât-ı Esasiye Kanunu’nu kabul etmiştir. Lozan’ı onaylayan ve Cumhuriyeti ilan eden İkinci Meclistir; 1924 Anayasası Cumhuriyet ilanından sonra, Tevhid-i Tedrisat Kanunu da 3 Mart 1924’te kabul edildiğinden bunlar da Birinci Meclisin işleri değildir. (MD Genel Kültür Kitabı – Tarih: Birinci Meclis ve 1921 Anayasası)',
 kanit=K + ' | Birinci Meclis mücadeleyi yürüttü; Lozan’ı onaylayan ve Cumhuriyeti ilan eden ise İkinci Meclis oldu. || ' + K + ' | 20 Ocak 1921’de kabul edilen Teşkilât-ı Esasiye Kanunu, egemenliğin millete ait olduğunu || ' + K + ' | 1924 Anayasası: Cumhuriyet ilanından sonra kabul edilen yeni anayasa.'),

dict(id='D6-014', cikmis='2021/14', konu='Eğitim ve kültür inkılapları – Tarih çalışmaları', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Tarih, dil ve bilim çalışmaları',
 cek='1931’de kurulan, Türk Tarih Kurumunun kökeni olan kurumun amacı Türk tarihini geniş zaman-coğrafyada bilimsel olarak araştırmaktır.',
 kok=['Atatürk döneminde 1931’de kurulan ve Türk Tarih Kurumunun kökeni olan kurumun kuruluş amacı aşağıdakilerden hangisidir?'],
 d='Türk tarihini daha geniş zaman ve coğrafya içinde bilimsel çalışmalarla araştırmak',
 c=['Yetişkinlere yeni harfleri yaygın biçimde öğreterek okuryazarlığı artırmak',
    'Türkçenin söz varlığını araştırıp bilim ve eğitimde Türkçe terimler üretmek',
    'Eğitim kurumlarını Millî Eğitim Bakanlığına bağlayarak ortak denetim ve program oluşturmak',
    'Türklerin haklarını yayın ve bilgilendirme yoluyla dünya kamuoyuna anlatmak'],
 tuzak=False,
 g='1931’de kurulan ve Türk Tarih Kurumunun kökeni olan kurumla Türk tarihini daha geniş zaman ve coğrafya içinde araştırmak ve bilimsel çalışmalarla tarih bilgisini geliştirmek amaçlanmıştır. Türkçenin söz varlığını araştırmak 1932’de oluşturulan dil kurumunun, yetişkinlere yeni harfleri öğretmek Millet Mekteplerinin, eğitim kurumlarını tek bakanlığa bağlamak ise Tevhid-i Tedrisat’ın konusudur. (MD Genel Kültür Kitabı – Tarih: Tarih, dil ve bilim çalışmaları)',
 kanit=K + ' | Türk Tarih Kurumunun kökeni olan kurum 1931’de kuruldu. Türk tarihini daha geniş zaman ve coğrafya içinde araştırmak, bilimsel çalışmalarla tarih bilgisini geliştirmek amaçlandı. || ' + K + ' | Türk Dil Kurumunun kökeni olan kurum 1932’de oluşturuldu. Türkçenin söz varlığını araştırmak'),

dict(id='D6-015', cikmis='2021/15', konu='Atatürk ilkeleri – İnkılapçılık', tip='T6', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Laiklik ve inkılapçılık',
 cek='İnkılapçılık: kurumların çağın ihtiyaçlarına göre yenilenmesi ve reformların geliştirilmesi; her eskiyi reddetmek değildir.',
 kok=['“Kurumların çağın ihtiyaçlarına göre yenilenmesini ve yapılan reformların geliştirilmesini ifade eder. Geçmişteki her uygulamayı yalnız eski olduğu için reddetmek veya her yeniliği sorgulamadan kabul etmek değildir; ölçüt, toplumun ihtiyaçlarına cevap veren akılcı ve uygulanabilir düzenlemeler oluşturmaktır.”',
      'Yukarıda tanımlanan Atatürk ilkesi aşağıdakilerden hangisidir?'],
 d='İnkılapçılık',
 c=['Halkçılık', 'Devletçilik', 'Milliyetçilik', 'Cumhuriyetçilik'],
 tuzak=False,
 g='Kurumların çağın ihtiyaçlarına göre yenilenmesini ve yapılan reformların geliştirilmesini ifade eden ilke inkılapçılıktır; bu ilke her eskiyi reddetmek ya da her yeniliği sorgusuz kabul etmek demek değildir. Halkçılık kanun önünde eşitlik ve ayrıcalıksız toplum, cumhuriyetçilik ise yönetme yetkisinin hanedana değil millete dayanması üzerinde durur. (MD Genel Kültür Kitabı – Tarih: Atatürk ilkeleri)',
 kanit=K + ' | Kurumların çağın ihtiyaçlarına göre yenilenmesini ve yapılan reformların geliştirilmesini ifade eder. Geçmişteki her uygulamayı yalnız eski olduğu için reddetmek veya her yeniliği sorgulamadan kabul etmek değildir.'),

# ===================== /DENEME 6 =====================

# ===================== DENEME 7 (2022) =====================
dict(id='D7-011', cikmis='2022/11', konu='Millî Mücadele’ye hazırlık – Erzurum ve Sivas kongreleri', tip='T1', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Erzurum Kongresi; Sivas Kongresi',
 cek='Erzurum kararları: vatanın bütünlüğü, ortak savunma, millî irade, geçici yönetim, manda reddi; cemiyetlerin birleştirilmesi Sivas Kongresi’nindir.',
 kok=['Aşağıdakilerden hangisi, 23 Temmuz-7 Ağustos 1919 tarihleri arasında toplanan Erzurum Kongresi’nde alınan kararlardan biri [[değildir]]?'],
 d='Millî cemiyetlerin Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti adıyla birleştirilmesi',
 c=['Vatanın parçalanamayacağının ve bölünmez bir bütün olduğunun kabul edilmesi',
    'İstanbul yönetimi ülkeyi koruyamazsa geçici bir yönetim oluşturulmasının benimsenmesi',
    'Yabancı bir devletin manda ve himayesinin kabul edilmeyerek kongrece reddedilmesi',
    'İşgale karşı ortak savunma yürütülmesinin ve millî iradenin esas alınmasının kabulü'],
 tuzak=False,
 g='Erzurum Kongresi’nde vatanın parçalanamayacağı, işgale karşı ortak savunma yürütüleceği ve millî iradenin esas alınacağı kabul edilmiş; İstanbul yönetimi ülkeyi koruyamazsa geçici yönetim oluşturulması benimsenmiş, manda ve himaye reddedilmiştir. Millî cemiyetlerin Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti adı altında ortak çatıya bağlanması ise Sivas Kongresi’nin ayırt edici katkısıdır. (MD Genel Kültür Kitabı – Tarih: Erzurum ve Sivas kongreleri)',
 kanit=K + ' | Vatanın parçalanamayacağı, işgale karşı ortak savunma yürütüleceği ve millî iradenin esas alınacağı kabul edildi. İstanbul yönetimi ülkeyi koruyamazsa geçici bir yönetim oluşturulması düşüncesi benimsendi. || ' + K + ' | Sivas’ın ayırt edici katkısı, millî örgütlenmeyi ortak çatıya bağlamasıdır.'),

dict(id='D7-012', cikmis='2022/12', konu='Misak-ı Millî ve Meclis – Sevr Antlaşması', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Sevr: imza ile yürürlük farklıdır',
 cek='Sevr: toprak paylaşımı, Boğazlarda uluslararası denetim, ordu sınırlaması öngördü; onay tamamlanmadı, Ankara reddetti, yürürlüğe girmedi.',
 kok=['Osmanlı temsilcilerince imzalanan; toprakların paylaşılmasını, Boğazlar üzerinde uluslararası denetimi ve ordunun ciddi biçimde sınırlandırılmasını öngören, ancak gerekli onay düzeni tamamlanmadığı ve Ankara yönetimi metni reddettiği için yürürlüğe girmeyen antlaşma aşağıdakilerden hangisidir?'],
 d='Sevr Antlaşması',
 c=['Mondros Ateşkesi', 'Gümrü Antlaşması', 'Lozan Antlaşması', 'Kars Antlaşması'],
 tuzak=False,
 g='10 Ağustos 1920’de imzalanan Sevr; toprakların paylaşılması, Boğazlar üzerinde uluslararası denetim ve ordunun sınırlandırılması gibi hükümler içermiş, ancak onay düzeni tamamlanmadığı ve Ankara yönetimi metni reddettiği için yürürlüğe girmemiştir. Gümrü Antlaşması’nın da onay süreci tamamlanmamıştır; fakat o, TBMM Hükûmetinin ilk uluslararası antlaşmasıdır. Mondros ise çatışmaları durdurmayı düzenleyen ateşkestir. (MD Genel Kültür Kitabı – Tarih: Sevr Antlaşması)',
 kanit=K + ' | Sevr; toprakların paylaşılması, Boğazlar üzerinde uluslararası denetim, ordunun ciddi biçimde sınırlandırılması || ' + K + ' | Gerekli onay düzeni tamamlanmadı; Ankara yönetimi metni reddetti. || ' + K + ' | Bu nedenle Sevr, yürürlüğe girmiş bir barış düzeni olarak anlatılmamalıdır.'),

dict(id='D7-013', cikmis='2022/13', konu='Millî Mücadele’ye hazırlık – Havza Genelgesi', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Samsun’dan Havza’ya (Havza Genelgesi, 28 Mayıs)',
 cek='Havza Genelgesi (28 Mayıs 1919): miting ve protesto, telgraf çekilmesi istendi; gösterilerde azınlıklara saldırıdan kaçınılması vurgulandı.',
 kok=['Millî Mücadele döneminde işgallere karşı mitingler ve protestolar düzenlenmesini, İstanbul’a ve yabancı temsilciliklere telgraflar gönderilmesini isteyen ve gösterilerde azınlıklara yönelik saldırılardan kaçınılmasını vurgulayan çağrı aşağıdakilerden hangisidir?'],
 d='Havza Genelgesi',
 c=['Amasya Genelgesi', 'Erzurum Kongresi', 'Sivas Kongresi', 'Misak-ı Millî'],
 tuzak=False,
 g='28 Mayıs 1919 tarihli Havza Genelgesi ile işgallere karşı mitingler ve protestolar düzenlenmesi, İstanbul’a ve yabancı temsilciliklere telgraflar gönderilmesi istenmiş; gösterilerde azınlıklara yönelik saldırılardan kaçınılması vurgulanmıştır. Amasya Genelgesi mücadelenin gerekçe ve yöntemini açıklayıp Sivas’ta kongre toplanmasını istemiş, Misak-ı Millî ise barış için millî talepleri ortaya koymuştur. (MD Genel Kültür Kitabı – Tarih: Samsun’dan Havza’ya)',
 kanit=K + ' | İşgallere karşı mitingler ve protestolar düzenlenmesi, İstanbul’a ve yabancı temsilciliklere telgraflar gönderilmesi istendi. || ' + K + ' | Gösterilerde azınlıklara yönelik saldırılardan kaçınılması da vurgulandı.'),

dict(id='D7-014', cikmis='2022/14', konu='Atatürk ilkeleri – Devletçilik', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Halkçılık ve devletçilik; 1930’larda devletçilik ve sanayi',
 cek='Devletçiliğin amacı: özel girişimin yetersiz kaldığı alanlarda kamu yatırımıyla ekonomik bağımsızlığı güçlendirmek ve kalkınmayı hızlandırmak.',
 kok=['Atatürk ilkelerinden devletçilik, özel girişimin sermaye, teknik bilgi ve altyapı bakımından yetersiz kaldığı alanlarda devletin üretim ve yatırım yapmasıdır.',
      'Bu ilkenin uygulanmasıyla ulaşılmak istenen amaç aşağıdakilerden hangisidir?'],
 d='Ekonomik bağımsızlığı güçlendirmek ve kalkınmayı hızlandırmak',
 c=['Özel mülkiyeti ve özel girişimi bütünüyle ortadan kaldırmak',
    'Ekonominin bütün ayrıntılarını kapsayan merkezî bir yönetim modeli kurmak',
    'Devlet ve hukuk düzenini dinî otoriteden ayırmak',
    'Yönetme yetkisini hanedan yerine millet temsilcilerine dayandırmak'],
 tuzak=False,
 g='Devletçilikte amaç, özel girişimin yetersiz kaldığı alanlarda kamu yatırımıyla ekonomik bağımsızlığı güçlendirmek ve kalkınmayı hızlandırmaktır. Atatürk dönemindeki devletçilik özel mülkiyetin ve özel girişimin bütünüyle kaldırılması değildir; Birinci Beş Yıllık Sanayi Planı da ekonominin bütün ayrıntılarını kapsayan merkezî bir yönetim modeliyle eş tutulmamalıdır. (MD Genel Kültür Kitabı – Tarih: Halkçılık ve devletçilik)',
 kanit=K + ' | Özel girişimin sermaye, teknik bilgi ve altyapı bakımından yetersiz kaldığı alanlarda devletin üretim ve yatırım yapmasıdır. || ' + K + ' | Amaç, ekonomik bağımsızlığı güçlendirmek ve kalkınmayı hızlandırmaktı. || ' + K + ' | Atatürk dönemindeki devletçilik, özel mülkiyetin ve özel girişimin bütünüyle kaldırılması değildir.'),

dict(id='D7-015', cikmis='2022/15', konu='Ateşkes ve barış – Lozan’da çözülen ve kalan konular', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Lozan’da çözülen ve kalan konular; Montrö ve Boğazlar rejimi; 1921’de savaş ve diplomasi',
 cek='Lozan’da kapitülasyonlar kaldırıldı; Musul 1926, Boğazlar Komisyonunun kaldırılması 1936 Montrö, Hatay 1939, Kars-Ardahan Moskova düzenlemesidir.',
 kok=['Aşağıdakilerden hangisi, 24 Temmuz 1923’te imzalanan Lozan Barış Antlaşması ile çözüme bağlanan konulardan biridir?'],
 d='Kapitülasyonların kaldırılması',
 c=['Musul meselesinin çözülmesi', 'Hatay’ın Türkiye’ye katılması', 'Boğazlar Komisyonunun kaldırılması', 'Kars ve Ardahan’ın Türkiye’de kalması'],
 tuzak=False,
 g='Lozan’da kapitülasyonlar kaldırılmış ve bu, ülke içindeki adli ve ekonomik egemenlik açısından temel kazanım olmuştur. Musul Lozan’da kesin çözülemeyip 1926 Ankara Antlaşması’na uzanmış, Uluslararası Boğazlar Komisyonu 1936 Montrö Sözleşmesi’yle kaldırılmış, Hatay 1939’da Türkiye’ye katılmıştır; Kars ve Ardahan’ın Türkiye’de kalması ise Moskova Antlaşması’nın düzenlemesidir. (MD Genel Kültür Kitabı – Tarih: Lozan’da çözülen ve kalan konular)',
 kanit=K + ' | Kapitülasyonlar kaldırıldı. Osmanlı borçlarının ilgili devletler arasında || ' + K + ' | Musul: Lozan’da kesin çözülemedi; 1926 Ankara Antlaşması’na uzandı. || ' + K + ' | Uluslararası Boğazlar Komisyonu kaldırıldı || ' + K + ' | Kars ve Ardahan Türkiye’de kaldı'),

# ===================== /DENEME 7 =====================

# ===================== DENEME 8 (2023) =====================
dict(id='D8-011', cikmis='2023/11', konu='Mondros ve işgaller – İstanbul’un iki işgal tarihi', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: İşgaller ve toplumsal tepki; İstanbul’dan Ankara’daki Meclise',
 cek='16 Mart 1920: İstanbul’un resmî işgali, baskın ve tutuklamalar; 13 Kasım 1918 ise İtilaf donanmasının gelişi ve fiilî denetimdir.',
 kok=['16 Mart 1920 tarihinde aşağıdaki gelişmelerden hangisi yaşanmıştır?'],
 d='İstanbul’un resmen işgal edilerek baskın ve tutuklamalar yapılması',
 c=['İtilaf donanmasının İstanbul’a gelerek fiilî askerî denetim kurması',
    'Yunan ordusunun İzmir’e çıkarak Batı Anadolu’da işgale başlaması',
    'Son Osmanlı Meclis-i Mebusanının İstanbul’da toplanması',
    'Büyük Millet Meclisinin Ankara’da açılarak çalışmaya başlaması'],
 tuzak=False,
 g='16 Mart 1920’de İstanbul’un resmî işgali genişletilmiş, baskınlar ve tutuklamalar yapılmış; Meclis-i Mebusan güven içinde çalışamaz hâle gelmiştir. İtilaf donanmasının gelişi ve fiilî askerî denetim 13 Kasım 1918’de, Yunan ordusunun İzmir’e çıkması 15 Mayıs 1919’da, Büyük Millet Meclisinin açılması ise 23 Nisan 1920’de gerçekleşmiştir. (MD Genel Kültür Kitabı – Tarih: İşgaller ve toplumsal tepki)',
 kanit=K + ' | 13 Kasım 1918: İtilaf donanmasının gelişi ve fiilî askerî denetim. 16 Mart 1920: Resmî işgalin genişletilmesi, baskınlar ve tutuklamalar. || ' + K + ' | İstanbul’un resmen işgali sırasında baskınlar ve tutuklamalar yapıldı'),

dict(id='D8-012', cikmis='2023/12', konu='Atatürk’ün hayatı – Mesleki eğitim ve ilk görev', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Yetiştiği çevre ve eğitim (Mesleki eğitim basamakları)',
 cek='Mustafa Kemal 1905’te kurmay yüzbaşı olarak mezun oldu; ilk görev yeri Şam’daki 5. Ordu; 1902 teğmenlik ve Akademiye geçiş.',
 kok=['Mustafa Kemal’in Harp Akademisinden kurmay yüzbaşı olarak mezun olduğu yıl ile ilk görev yeri aşağıdakilerin hangisinde doğru olarak verilmiştir?'],
 d='1905 – Şam',
 c=['1902 – Şam', '1905 – Sofya', '1899 – İstanbul', '1911 – Trablusgarp'],
 tuzak=False,
 g='Mustafa Kemal 1905’te Harp Akademisinden kurmay yüzbaşı olarak mezun olmuş, ilk görev yeri Şam’daki 5. Ordu olmuştur. 1902 teğmen rütbesiyle mezuniyet ve Harp Akademisine geçiş yılı, 1899 İstanbul Harp Okuluna giriş yılıdır; Sofya’daki askerî ataşelik ise ilk görev yeri değildir. (MD Genel Kültür Kitabı – Tarih: Atatürk’ün hayatı)',
 kanit=K + ' | 1899: İstanbul Harp Okuluna giriş. 1902: Teğmen rütbesiyle mezuniyet ve Harp Akademisine geçiş. 1905: Kurmay yüzbaşı olarak mezuniyet; ilk görev yeri Şam’daki 5. Ordu.'),

dict(id='D8-013', cikmis='2023/13', konu='Atatürk ilkeleri – Cumhuriyetçilik', tip='T1', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Cumhuriyetçilik ve milliyetçilik',
 cek='Cumhuriyetçilikle bağlantılı: saltanatın kaldırılması, Cumhuriyetin ilanı, TBMM’nin açılması, siyasi katılım; dil-tarih çalışmaları milliyetçiliktir.',
 kok=['Aşağıdakilerden hangisi, Atatürk ilkelerinden cumhuriyetçilikle doğrudan ilişkilendirilen uygulamalardan biri [[değildir]]?'],
 d='Dil ve tarih alanında araştırma kurumlarının kurulması',
 c=['Saltanatın kaldırılarak hanedanın siyasi egemenliğinin sona ermesi',
    'Büyük Millet Meclisinin millet temsilcileriyle açılması',
    'Cumhuriyetin devletin yönetim biçimi olarak ilan edilmesi',
    'Kadınların siyasi katılım haklarının genişletilmesi'],
 tuzak=False,
 g='Cumhuriyetçilik, yönetme yetkisinin hanedana değil millete dayanmasını esas alır; saltanatın kaldırılması, Cumhuriyetin ilanı ve siyasi katılım haklarının genişlemesi bu ilkeyle bağlantılıdır. TBMM’nin açılması yönetimin millet temsilcilerine dayanması nedeniyle, kadınların siyasi hakları da temsil boyutuyla cumhuriyetçilikle ilişkilidir. Dil ve tarih çalışmaları ise ortak kültürel birikimi araştırma yönüyle milliyetçilikle bağlantılıdır. (MD Genel Kültür Kitabı – Tarih: Atatürk ilkeleri)',
 kanit=K + ' | Saltanatın kaldırılması, Cumhuriyetin ilanı ve siyasi katılım haklarının genişlemesi bu ilkeyle bağlantılıdır. || ' + K + ' | TBMM’nin açılması: Yönetimin millet temsilcilerine dayanması nedeniyle cumhuriyetçilikle ilişkilidir. Dil ve tarih çalışmaları: Ortak kültürel birikimi araştırma yönüyle milliyetçilikle bağlantılıdır. || ' + K + ' | kadınların siyasi hakları halkçılık ve cumhuriyetçilikle birlikte açıklanabilir.'),

dict(id='D8-014', cikmis='2023/14', konu='Millî Mücadele cepheleri – İnönü savaşları', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: İnönü savaşları',
 cek='Birinci İnönü (6-10 Ocak 1921), Batı Cephesi’nde “düzenli ordunun ilk zaferi” olarak anılır; İkinci İnönü yeni saldırıyı durdurdu.',
 kok=['Batı Cephesi’nde yeni kurulan düzenli ordunun Yunan ilerleyişini durdurarak kazandığı ve “düzenli ordunun ilk zaferi” olarak anılan muharebe aşağıdakilerden hangisidir?'],
 d='Birinci İnönü Muharebesi',
 c=['İkinci İnönü Muharebesi', 'Sakarya Meydan Muharebesi', 'Kütahya-Eskişehir Muharebeleri', 'Başkomutanlık Meydan Muharebesi'],
 tuzak=False,
 g='6-10 Ocak 1921’deki Birinci İnönü Muharebesi’nde İsmet Bey komutasındaki kuvvetler Yunan ilerleyişini durdurmuş; “düzenli ordunun ilk zaferi” ifadesi Batı Cephesi’ndeki bu yeni yapılanma için kullanılmıştır. İkinci İnönü’de Yunan ordusunun yeni saldırısı durdurulmuş, Kütahya-Eskişehir muharebeleri ise geri çekilmeyle sonuçlanmıştır. (MD Genel Kültür Kitabı – Tarih: İnönü savaşları)',
 kanit=K + ' | Birinci İnönü, 6-10 Ocak 1921 İsmet Bey komutasındaki kuvvetler Yunan ilerleyişini durdurdu. || ' + K + ' | “Düzenli ordunun ilk zaferi” ifadesi burada Batı Cephesi’ndeki yeni yapılanma için kullanılır'),

dict(id='D8-015', cikmis='2023/15', konu='Dış politika – Hatay meselesi', tip='T4', z='Z',
 madde='Genel Kültür Kitabı – Tarih: Hatay: aşamalı bir çözüm',
 cek='Hatay: 1937 özel statü, 1938 seçim sonrası Hatay Devleti’nin kurulması, 29 Haziran 1939 Hatay Meclisinin katılma kararı.',
 kok=['Hatay meselesinin çözüm sürecinde 1938 yılında gerçekleşen gelişme aşağıdakilerden hangisidir?'],
 d='Seçim süreci sonrasında Hatay Devleti’nin kurulması',
 c=['Hatay Meclisinin Türkiye’ye katılma kararı alması',
    'Bölgeye ilişkin özel statü düzenlemelerinin yapılması',
    'Lozan’da Hatay’ın Türkiye dışında bırakılması',
    'Ankara Antlaşması’yla İskenderun’a özel hükümler getirilmesi'],
 tuzak=False,
 g='Hatay meselesinde 1937’de özel statü düzenlemeleri yapılmış, 1938’de yerel siyasi düzen ve seçim süreci sonrasında Hatay Devleti kurulmuştur. Hatay Meclisinin Türkiye’ye katılma kararı 29 Haziran 1939’da, Atatürk’ün ölümünden sonra alınmıştır; İskenderun bölgesine özel hükümler ise 1921 Ankara Antlaşması’yla getirilmiştir. (MD Genel Kültür Kitabı – Tarih: Hatay meselesi)',
 kanit=K + ' | 1937: özel statü. 1938: Hatay Devleti. 1939: Türkiye’ye katılma. || ' + K + ' | Yerel siyasi düzen ve seçim süreci sonrasında Hatay Devleti kuruldu. || ' + K + ' | Hatay Meclisi 29 Haziran 1939’da Türkiye’ye katılma kararı aldı.'),

# ===================== /DENEME 8 =====================

# ===================== DENEME 9 (2024) =====================
dict(id='D9-011', cikmis='2024/11', konu='Dış politika – Montrö ve Boğazlar rejimi', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Montrö ve Boğazlar rejimi',
 cek='Montrö (20 Temmuz 1936) Boğazlar Komisyonunu kaldırdı, Türkiye’nin asker bulundurma imkânını güçlendirdi; Lozan’daki Boğazlar düzenini değiştirdi.',
 kok=['Avrupa’da silahlanmanın ve savaş riskinin artması üzerine Türkiye’nin konferans ve müzakere yoluyla elde ettiği; Uluslararası Boğazlar Komisyonunu kaldıran ve Türkiye’nin bölgede asker bulundurma imkânını güçlendiren 1936 tarihli düzenleme aşağıdakilerden hangisidir?'],
 d='Montrö Sözleşmesi',
 c=['Lozan Barış Antlaşması', 'Ankara Antlaşması', 'Balkan Antantı', 'Sadabat Paktı'],
 tuzak=False,
 g='20 Temmuz 1936 tarihli Montrö Sözleşmesi ile Uluslararası Boğazlar Komisyonu kaldırılmış, Türkiye’nin bölgede asker bulundurma ve güvenliği sağlama imkânı güçlenmiştir. Boğazlar meselesi daha önce Lozan’da düzenlenmiş, askerden arındırma ve uluslararası komisyon Türkiye’nin güvenlik yetkilerini sınırlamıştı; Balkan Antantı ve Sadabat Paktı ise bölgesel güvenlik ve saldırmazlık düzenlemeleridir. (MD Genel Kültür Kitabı – Tarih: Montrö ve Boğazlar rejimi)',
 kanit=K + ' | 20 Temmuz 1936 tarihli sözleşme, Lozan’daki Boğazlar düzenini yeni güvenlik şartlarına göre değiştirdi. || ' + K + ' | Uluslararası Boğazlar Komisyonu kaldırıldı; Türkiye’nin bölgede asker bulundurma ve güvenliği sağlama imkânı güçlendi. || ' + K + ' | Türkiye değişikliği tek taraflı fiilî müdahaleyle değil, konferans ve müzakere yoluyla aradı.'),

dict(id='D9-012', cikmis='2024/12', konu='I. Dünya Savaşı – Bloklar ve taraflar', tip='T1', z='Z',
 madde='Genel Kültür Kitabı – Tarih: Savaş neden dünya savaşına döndü? (Bloklar sabit kalmadı)',
 cek='İtalya, Üçlü İttifak üyesi olmasına rağmen 1915’te İtilaf yanında savaşa girdi; savaş öncesi blok ile savaştaki taraf farklıdır.',
 kok=['I. Dünya Savaşı’nda devletlerin taraf durumlarına ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='İtalya, savaş öncesindeki ittifakına bağlı kalarak İttifak Devletleri yanında savaştı.',
 c=['Osmanlı Devleti ve Bulgaristan, İttifak tarafında daha sonra yer alan devletlerdir.',
    'Japonya ve ABD, savaş içinde İtilaf Devletleri tarafında yer alan devletler arasındadır.',
    'Rusya’nın savaştan çekilmesi ve ABD’nin katılması güç dengesini değiştirdi.',
    'Başlangıçta İtilaf tarafında İngiltere, Fransa ve Rusya bulunuyordu.'],
 tuzak=False,
 g='İtalya, savaş öncesindeki Üçlü İttifak içinde yer almasına rağmen 1915’te İtilaf Devletleri yanında savaşa girmiştir; savaş öncesi blok ile savaş sırasındaki taraf aynı değildir. İttifak tarafında Almanya ve Avusturya-Macaristan ile daha sonra Osmanlı Devleti ve Bulgaristan; İtilaf tarafında ise başlangıçta İngiltere, Fransa ve Rusya, savaş içinde de Japonya, İtalya ve ABD yer almıştır. (MD Genel Kültür Kitabı – Tarih: I. Dünya Savaşı)',
 kanit=K + ' | İtalya, savaş öncesindeki Üçlü İttifak içinde yer almasına rağmen 1915’te İtilaf Devletleri yanında savaşa girdi. || ' + K + ' | İttifak tarafı: Almanya, Avusturya-Macaristan; daha sonra Osmanlı Devleti ve Bulgaristan. İtilaf tarafı: Başlangıçta İngiltere, Fransa ve Rusya; savaş içinde Japonya, İtalya ve ABD gibi devletler de bu tarafta yer aldı.'),

dict(id='D9-013', cikmis='2024/13', konu='Millî Mücadele cepheleri – Sakarya Meydan Muharebesi', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Tekâlif-i Milliye ve Sakarya; Geri çekilme ve başkomutanlık',
 cek='Sakarya (23 Ağustos-13 Eylül 1921): derinlikte savunma, Yunan geri çekilmesi, Ankara’ya yönelik yakın askerî tehdidin giderilmesi.',
 kok=['Kütahya-Eskişehir muharebelerinden sonra yapılan; savunmanın tek bir çizgiye tutunmak yerine derinlik içinde sürdürüldüğü, sonunda Yunan kuvvetlerinin geri çekildiği ve Ankara üzerindeki yakın askerî tehdidin giderildiği muharebe aşağıdakilerden hangisidir?'],
 d='Sakarya Meydan Muharebesi',
 c=['Başkomutanlık Meydan Muharebesi', 'İkinci İnönü Muharebesi', 'Birinci İnönü Muharebesi', 'Büyük Taarruz'],
 tuzak=False,
 g='23 Ağustos-13 Eylül 1921 arasında 22 gün 22 gece süren Sakarya Meydan Muharebesi’nde savunma derinlik içinde sürdürülmüş, Yunan kuvvetleri geri çekilmiş ve Ankara üzerindeki yakın askerî tehdit giderilmiştir. Büyük Taarruz ve 30 Ağustos Başkomutanlık Meydan Muharebesi 1922’de Yunan ana kuvvetlerini yenilgiye uğratan taarruz harekâtıdır; İnönü savaşları ise Kütahya-Eskişehir’den önce yapılmıştır. (MD Genel Kültür Kitabı – Tarih: Tekâlif-i Milliye ve Sakarya)',
 kanit=K + ' | Savunma, yalnız tek bir çizgiye tutunmak yerine derinlik içinde sürdürülerek ordunun direnci korundu. Sonunda Yunan kuvvetleri geri çekildi; Ankara üzerindeki yakın askerî tehdit giderildi. || ' + K + ' | Kütahya-Eskişehir yenilgisi ile Sakarya zaferi arasındaki bağ'),

dict(id='D9-014', cikmis='2024/14', konu='Atatürk ilkeleri – İlkelerin içeriği', tip='T1', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Cumhuriyetçilik ve milliyetçilik; Halkçılık ve devletçilik; Laiklik ve inkılapçılık',
 cek='Laiklik dinî otoriteden ayrılma ve din-vicdan özgürlüğüdür; kişisel inançları terke zorlama olarak tanımlanamaz.',
 kok=['Atatürk ilkelerine ilişkin aşağıdaki ifadelerden hangisi [[yanlıştır]]?'],
 d='Laiklik, devletin dinî otoriteden ayrılmasıyla birlikte bireylerin kişisel inançlarını terk etmeye zorlanmasını da kapsar.',
 c=['Halkçılık, kanun önünde eşitliği esas alır ve belirli bir sınıfın veya zümrenin devlet üzerindeki üstünlüğünü reddeder.',
    'Milliyetçilik, ortak tarih, kültür ve birlikte yaşama iradesine dayanır; bir ırkın üstünlüğünü savunmakla özdeş değildir.',
    'Cumhuriyetçilik, devlet başkanının verasetle belirlenmesi yerine temsil ve seçim mekanizmalarının öne çıkmasını esas alır.',
    'Bir kamu fabrikası devletçilikle ilişkili olduğu gibi istihdam yaratması ve bölgeye hizmet götürmesiyle halkçılıkla da bağlantı kurabilir.'],
 tuzak=False,
 g='Laiklik, devlet ve hukuk düzeninin dinî otoriteden ayrılması ve din ve vicdan alanında özgürlüğün güvence altında olmasıyla ilişkilidir; laikliği insanların kişisel inançlarını terk etmeye zorlanması şeklinde tanımlamak doğru değildir. Milliyetçiliğin ırk üstünlüğüyle özdeş olmadığı ve bir kamu fabrikasının hem devletçilik hem halkçılıkla bağlantı kurabileceği ifadeleri doğrudur. (MD Genel Kültür Kitabı – Tarih: Atatürk ilkeleri)',
 kanit=K + ' | Laikliği insanların kişisel inançlarını terk etmeye zorlanması şeklinde tanımlamak doğru değildir. || ' + K + ' | Bir ırkın üstünlüğünü savunma veya başka ülkelerin topraklarını ele geçirme hedefiyle özdeş değildir. || ' + K + ' | İstihdam yaratması ve bölgeye hizmet götürmesi halkçılıkla da bağlantı kurabilir.'),

dict(id='D9-015', cikmis='2024/15', konu='Misak-ı Millî ve Meclis – Kronoloji', tip='T1', z='Z',
 madde='Genel Kültür Kitabı – Tarih: Amasya Görüşmeleri ve Ankara; Misak-ı Millî’nin çerçevesi; İstanbul’dan Ankara’daki Meclise; Otorite ve anayasal düzen',
 cek='Hıyanet-i Vataniye Kanunu 29 Nisan 1920’de, TBMM açıldıktan sonra kabul edildi; Amasya Görüşmeleri, Ankara’ya geliş, Misak-ı Millî, seçim çağrısı öncedir.',
 kok=['Aşağıdakilerden hangisi, Büyük Millet Meclisinin 23 Nisan 1920’de Ankara’da açılmasından önce yaşanan gelişmelerden biri [[değildir]]?'],
 d='Hıyanet-i Vataniye Kanunu’nun Mecliste kabul edilmesi',
 c=['Temsil Heyetinin Ankara’ya gelerek çalışmaya başlaması',
    'Amasya’da Bahriye Nazırı Salih Paşa ile görüşülmesi',
    'Misak-ı Millî’nin Meclis-i Mebusanda kabul edilmesi',
    'Ankara’da yeni bir meclis için seçim çağrısı yapılması'],
 tuzak=False,
 g='Hıyanet-i Vataniye Kanunu 29 Nisan 1920’de, yani Meclisin açılmasından sonra kabul edilmiştir. Amasya Görüşmeleri Ekim 1919’da, Temsil Heyetinin Ankara’ya gelişi 27 Aralık 1919’da, Misak-ı Millî’nin kabulü 28 Ocak 1920’de, Ankara’da yeni meclis için seçim çağrısı ise 19 Mart’ta yapılmıştır. (MD Genel Kültür Kitabı – Tarih: Misak-ı Millî ve Meclis)',
 kanit=K + ' | 29 Nisan 1920’de kabul edilen kanun, Meclis yönetimine karşı faaliyetlerle mücadelede hukuki dayanak oluşturdu. || ' + K + ' | Ankara’ya geliş, 27 Aralık 1919 || ' + K + ' | Mustafa Kemal, 19 Mart’ta Ankara’da olağanüstü yetkilere sahip bir meclisin toplanması için seçim çağrısı yaptı. || ' + K + ' | Amasya Genelgesi Haziran 1919’da yayımlandı; Amasya Görüşmeleri Ekim 1919’da yapıldı.'),

# ===================== /DENEME 9 =====================

# ===================== DENEME 10 (2025 B) =====================
dict(id='D10-011', cikmis='2025/11', konu='Millî Mücadele cepheleri – Sakarya sonrası antlaşmalar', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Sakarya sonrası iki antlaşma; Doğu ve Güney cepheleri',
 cek='Ankara Antlaşması (20 Ekim 1921) Fransa ile: güneyde çatışmaların sona ermesi, Fransız çekilmesi, Suriye sınırı; Kars doğu komşularıyla.',
 kok=['Sakarya Meydan Muharebesi’nden sonra TBMM Hükûmeti ile Fransa arasında imzalanan; güneyde çatışmaların sona ermesini ve Fransız kuvvetlerinin belirlenen alanlardan çekilmesini sağlayan antlaşma aşağıdakilerden hangisidir?'],
 d='Ankara Antlaşması',
 c=['Kars Antlaşması', 'Moskova Antlaşması', 'Gümrü Antlaşması', 'Sevr Antlaşması'],
 tuzak=False,
 g='20 Ekim 1921 tarihli Ankara Antlaşması Fransa ile yapılmış; güneyde çatışmaların sona ermesini ve Fransız kuvvetlerinin belirlenen alanlardan çekilmesini sağlamış, Suriye sınırının ana çerçevesini çizmiştir. Aynı dönemde 13 Ekim 1921’de imzalanan Kars Antlaşması Sovyet Ermenistanı, Azerbaycanı ve Gürcistanı ile doğu sınırına ilişkindir; Moskova Antlaşması ise Sovyet Rusya ile yapılmıştır. (MD Genel Kültür Kitabı – Tarih: Sakarya sonrası iki antlaşma)',
 kanit=K + ' | Fransa ile yapılan anlaşma, güneyde çatışmaların sona ermesini ve Fransız kuvvetlerinin belirlenen alanlardan çekilmesini sağladı. || ' + K + ' | TBMM Hükûmeti ile Sovyet Ermenistanı, Azerbaycanı ve Gürcistanı arasında, Sovyet Rusya’nın katılımıyla imzalandı.'),

dict(id='D10-012', cikmis='2025/12', konu='Ekonomik inkılaplar – Düzenlemeler ve kurumlar', tip='T1', z='Z',
 madde='Genel Kültür Kitabı – Tarih: Ekonomik bağımsızlığın temelleri; 1930’larda devletçilik ve sanayi',
 cek='Sümerbank (1933) sanayi yatırımlarının kurulması ve finansmanı; madencilik-enerji yatırımları Etibank (1935); Aşar 1925’te kaldırıldı.',
 kok=['Atatürk döneminde ekonomik alanda yapılan düzenlemeler ve kurulan kurumlarla ilgili aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='1933’te kurulan Sümerbank, madencilik ve enerjiyle ilgili yatırımlar amacıyla oluşturulmuştur.',
 c=['Aşar vergisinin 1925’te kaldırılması, tarım üreticisinin yükünü hafifletmeyi amaçlamıştır.',
    '1927 Teşvik-i Sanayi Kanunu, özel girişimi ve yerli sermayeyi güçlendirme yaklaşımının örneğidir.',
    'Birinci Beş Yıllık Sanayi Planı ile ithal edilen bazı ürünlerin yurt içinde üretilmesi hedeflenmiştir.',
    'Kabotaj Kanunu, Türkiye kıyıları arasındaki yük ve yolcu taşımacılığında millî yetkiyi güçlendirmiştir.'],
 tuzak=False,
 g='Sümerbank 1933’te sanayi yatırımlarının kurulması ve finansmanında önemli rol üstlenmiştir; madencilik ve enerjiyle ilgili yatırımlar 1935’te kurulan Etibank’ın alanıdır. Aşar vergisinin kaldırılması ve Teşvik-i Sanayi Kanunu tarım üreticisini ve özel girişimi desteklemeye, Birinci Beş Yıllık Sanayi Planı ise bazı ithal ürünlerin yurt içinde üretilmesine yöneliktir. (MD Genel Kültür Kitabı – Tarih: Ekonomik inkılaplar)',
 kanit=K + ' | Sümerbank, 1933: Sanayi yatırımlarının kurulması ve finansmanında önemli rol. Etibank, 1935: Madencilik ve enerjiyle ilgili yatırımlar. || ' + K + ' | Aşar vergisinin 1925’te kaldırılması, tarım üreticisinin yükünü hafifletmeyi amaçladı. || ' + K + ' | İthal edilen bazı ürünlerin yurt içinde üretilmesi hedeflendi.'),

dict(id='D10-013', cikmis='2025/13', konu='Millî Mücadele cepheleri – 1921’de savaş ve diplomasi', tip='T1', z='Z',
 madde='Genel Kültür Kitabı – Tarih: 1921’de savaş ve diplomasi; Doğu ve Güney cepheleri; Tekâlif-i Milliye ve Sakarya; Sakarya sonrası iki antlaşma',
 cek='1921 gelişmeleri: Londra Konferansı, Moskova ve Kars antlaşmaları, Tekâlif-i Milliye; Gümrü 2-3 Aralık 1920’de imzalandı.',
 kok=['Aşağıdakilerden hangisi, 1921 yılında gerçekleşen gelişmelerden biri [[değildir]]?'],
 d='Gümrü Antlaşması’nın imzalanması',
 c=['Londra Konferansı’nın toplanması', 'Moskova Antlaşması’nın imzalanması', 'Kars Antlaşması’nın imzalanması', 'Tekâlif-i Milliye emirlerinin yayımlanması'],
 tuzak=False,
 g='Gümrü Antlaşması 2-3 Aralık 1920 gecesi imzalandığından 1921 gelişmeleri arasında yer almaz. Londra Konferansı 21 Şubat-12 Mart 1921’de toplanmış, Moskova Antlaşması 16 Mart’ta ve Kars Antlaşması 13 Ekim 1921’de imzalanmış, Tekâlif-i Milliye emirleri ise 7-8 Ağustos 1921’de yayımlanmıştır. (MD Genel Kültür Kitabı – Tarih: 1921’de savaş ve diplomasi)',
 kanit=K + ' | 2-3 Aralık 1920 gecesi imzalanan Gümrü Antlaşması || ' + K + ' | 21 Şubat-12 Mart 1921’de toplanan konferansta || ' + K + ' | Moskova Antlaşması, 16 Mart || ' + K + ' | Kars Antlaşması, 13 Ekim 1921 || ' + K + ' | 7-8 Ağustos 1921: on emir'),

dict(id='D10-014', cikmis='2025/14', konu='Atatürk’ün hayatı – Eserleri', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Atatürk’ün eserleri (Bilgi üretimi ve dil); Tarih, dil ve bilim çalışmaları',
 cek='Atatürk’ün Geometri kitabı, bilim ve eğitimde kavramların anlaşılır Türkçe ile öğretilmesi çabasının somut örneğidir.',
 kok=['Mustafa Kemal Atatürk’ün kaleme aldığı Geometri kitabı, aşağıdakilerden hangisinin somut örneği olarak gösterilir?'],
 d='Bilim ve eğitimde kavramların anlaşılır Türkçe ile öğretilmesi çabasının',
 c=['Askerlik alanındaki mesleki tecrübenin yazıya aktarılması çabasının',
    '1919-1927 arasındaki mücadelenin belgelere dayanılarak anlatılmasının',
    'Yetişkinlere yeni harflerin yaygın biçimde öğretilmesi kampanyasının',
    'Türk tarihinin daha geniş zaman ve coğrafya içinde araştırılması çabasının'],
 tuzak=False,
 g='Kitaba göre Geometri kitabı, bilimsel kavramların anlaşılır Türkçe ile öğretilmesi çabasını gösterir ve bilim ile eğitimde Türkçe terimler üretilmesine yönelik ilginin somut örneklerindendir. Mesleki tecrübeyi Atatürk’ün askerlik üzerine çalışmaları, 1919-1927 arasındaki mücadeleyi belgelere dayanarak Nutuk yansıtır; yeni harflerin yetişkinlere öğretilmesi Millet Mekteplerinin, Türk tarihinin geniş zaman ve coğrafyada araştırılması ise Türk Tarih Kurumunun kökeni olan kurumun konusudur. (MD Genel Kültür Kitabı – Tarih: Tarih, dil ve bilim çalışmaları)',
 kanit=K + ' | Atatürk’ün askerlik üzerine çalışmaları mesleki tecrübeyi, Geometri kitabı ise bilimsel kavramların anlaşılır Türkçe ile öğretilmesi çabasını gösterir. || ' + K + ' | Geometri kitabı bu ilginin somut örneklerindendir.'),

dict(id='D10-015', cikmis='2025/15', konu='Millî Mücadele’ye hazırlık – Erzurum Kongresi', tip='T4', z='OÜ',
 madde='Genel Kültür Kitabı – Tarih: Erzurum Kongresi (Mustafa Kemal’in konumu)',
 cek='Mustafa Kemal 8-9 Temmuz 1919 gecesi askerlik görevinden ayrıldı; Erzurum Kongresi’ne millî hareketteki konumuyla katılıp başkan seçildi.',
 kok=['Erzurum Kongresi’ne resmî askerî makamına dayanarak değil, millî hareket içindeki konumuyla katılan Mustafa Kemal’in askerlik görevinden ayrıldığı tarih aşağıdakilerden hangisidir?'],
 d='8-9 Temmuz 1919',
 c=['23 Temmuz 1919', '4 Eylül 1919', '27 Aralık 1919', '10 Ağustos 1920'],
 opts=['8-9 Temmuz 1919', '23 Temmuz 1919', '4 Eylül 1919', '27 Aralık 1919', '10 Ağustos 1920'],
 tuzak=False,
 g='Mustafa Kemal 8-9 Temmuz 1919 gecesi askerlik görevinden ayrılmış, 23 Temmuz’da toplanan Erzurum Kongresi’ne millî hareket içindeki konumuyla katılarak başkan seçilmiştir. 4 Eylül 1919 Sivas Kongresi’nin, 27 Aralık 1919 Temsil Heyetinin Ankara’ya gelişinin, 10 Ağustos 1920 ise Sevr’in imza tarihidir. (MD Genel Kültür Kitabı – Tarih: Erzurum Kongresi)',
 kanit=K + ' | Mustafa Kemal, 8-9 Temmuz 1919 gecesi askerlik görevinden ayrıldı. Erzurum Kongresi’ne artık resmî askerî makamına dayanarak değil, millî hareket içindeki konumuyla katıldı ve başkan seçildi. || ' + K + ' | 23 Temmuz-7 Ağustos 1919 || ' + K + ' | 4-11 Eylül 1919 || ' + K + ' | 10 Ağustos 1920’de imzalanan Sevr'),

# ===================== /DENEME 10 =====================
]
