# Görev K15 — Bağlayıcı bilgi, tarife, YYS, OKSB (Deneme 6–10)
Q = [
# ===================== DENEME 6 =====================
dict(id='D6-025', cikmis='2021/25', konu='Yetkilendirilmiş Yükümlü', tip='T1', z='Z',
 madde='Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği m.4/2, 4/3, 4/5, 4/6, 14/1-e',
 cek='YYS devir/birleşmede devralanın başvurusunda üç yıl faaliyet şartı aranmaz; sona eren şirketin ceza kararı ve beyan sayıları birlikte değerlendirilir.',
 kok=['Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliğine göre, yetkilendirilmiş yükümlü statüsü için aranan en az üç yıldır fiilen faaliyette bulunma şartının şirket devri, birleşmesi ve bölünmesi hâllerinde uygulanmasına ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Sertifika sahibi şirketin devir veya birleşme suretiyle tüzel kişiliğinin sona ermesi hâlinde, devralan tüzel kişinin başvurusunda üç yıllık faaliyet şartı aranmaz ve sona eren şirketin ceza kararı ile beyan sayıları değerlendirmeye alınmaz.',
 c=['Sertifika sahibi olsun veya olmasın en az üç yıldır faaliyette bulunan bir şirketin malvarlığının bir bölümünün, aralarında şirket ilişkisi bulunan yeni bir şirkete bölünme suretiyle devrinde, devralanın başvurusunda üç yıl şartı aranmaz.',
    'İki veya daha fazla şirketin devralınması ya da yeni kurulan bir şirket şeklinde birleşilmesi sonrasında yapılan sertifika başvurusunda, birleşen veya devralınan her bir şirketin en az üç yıldır faaliyette bulunması gerekir.',
    'Devir, birleşme ve bölünmeye ilişkin istisnalar saklı kalmak kaydıyla, başvuru tarihi itibarıyla üç yıldan daha az süredir fiilen faaliyette bulunan kişinin sertifika başvurusu ön inceleme yapılmaksızın reddedilir.',
    'Sertifika sahibi şirketin sertifika sahibi başka bir şirketle yeni bir tüzel kişilik altında birleşmesi hâlinde yeniden sertifika başvurusunda bulunulmaz; ancak durum sertifikayı düzenleyen bölge müdürlüğüne bildirilir.'],
 tuzak=True,
 g='Sertifika sahibi şirketin devir veya birleşme suretiyle sona ermesinde devralanın başvurusunda üç yıllık faaliyet şartı aranmaz; ancak sona eren şirketin ceza kararı ve beyan sayıları, başvuru sahibinin verileriyle birlikte değerlendirilir, değerlendirme dışı bırakılmaz. Bölünmede şirket ilişkisi koşuluyla üç yıl şartının aranmaması ile iki veya daha fazla şirketin devralınması ya da birleşmesinde her bir şirketin üç yıl faaliyette bulunması gerektiği yönündeki ifadeler mevzuata uygundur. (MD GİKY 4/2, 4/3, 4/5, 4/6, 14/1-e)',
 kanit='3-YYS.txt | En az 3 yıldır fiilen faaliyette bulunma şartı aranmaz. Ancak tüzel kişiliği sona eren şirketin; || 3-YYS.txt | sertifika talebinde bulunan kişi adına düzenlenmiş ceza kararları ve beyan sayılarıyla birlikte değerlendirilir. || 3-YYS.txt | Her bir şirketin en az 3 yıldır faaliyette bulunması gerekir.'),

dict(id='D6-027', cikmis='2021/27', konu='Tarife', tip='T8', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.15/3, 15/4',
 cek='Tercihli tarife (GK 15/3-d,e,f) beyan sahibinin talebiyle uygulanır; koşullar sağlanırsa talep işlemlerin tamamlanmasından veya teslimden sonra da yapılabilir.',
 kok=['(K) Ltd. Şti., Türkiye\'nin tercihli bir tarife uygulaması öngören serbest ticaret anlaşması imzaladığı (X) ülkesi menşeli sanayi makinelerini ithal etmiştir. Eşya, beyan tarihinde anlaşmadaki tercihli tarife uygulamasından yararlanma koşullarını taşımaktadır. Ancak firma, eşyanın tercihli menşeini kanıtlayan menşe ispat belgesini beyan sırasında henüz temin edemediğinden serbest dolaşıma giriş beyannamesinde Türk Gümrük Tarife Cetvelindeki gümrük vergi oranlarını esas almış; vergiler ödenmiş, gümrük işlemleri tamamlanmış ve eşya firmaya teslim edilmiştir. Teslimden iki ay sonra usulüne uygun menşe ispat belgesini temin eden (K), gümrük idaresine başvurarak beyan ettiği eşyaya söz konusu tercihli tarife uygulamasının uygulanmasını talep etmiştir.',
      '4458 sayılı Gümrük Kanununun gümrük tarifesine ilişkin hükümleri çerçevesinde, (K)\'nin talebi hakkında aşağıdakilerden hangisi doğrudur?'],
 d='Gerekli koşullar yerine getirilmişse tercihli tarife talebi, gümrük işlemlerinin tamamlanmasından veya eşyanın tesliminden sonra da yapılabileceğinden (K)\'nin talebi bu gerekçeyle reddedilemez.',
 c=['Tercihli tarife uygulanması yalnızca gümrük beyannamesinin tescili sırasında talep edilebileceğinden, gümrük işlemleri tamamlanıp eşya teslim edildikten sonra yapılan (K)\'nin talebi gümrük idaresince dikkate alınmaz.',
    'Tercihli tarife talebi gümrük işlemlerinin tamamlanmasından sonra da yapılabilir; ancak eşya teslim edildikten sonra bu talepte bulunulamayacağından (K)\'nin talebi kabul edilmez.',
    'Anlaşmalarda yer alan tercihli tarife uygulamaları beyan sahibinin talebi aranmaksızın gümrük idaresince kendiliğinden uygulandığından, (K)\'nin ayrıca bir talepte bulunmasına gerek bulunmamaktadır.',
    'Beyan sahibine tarife seçme hakkı yalnızca Türkiye\'nin tek taraflı olarak tanıdığı tercihli tarife uygulamaları için tanındığından, anlaşmaya dayanan tercih bakımından (K)\'nin talebi reddedilir.'],
 tuzak=False,
 g='Kanuna göre anlaşmalara dayalı tercihli tarife, tek taraflı tercihli tarife ve şartlı muafiyet veya indirim uygulamalarının koşullarını taşıyan eşyada beyan sahibi, Türk Gümrük Tarife Cetvelindeki oranlar yerine bu uygulamaları isteyebilir ve gerekli koşullar yerine getirilmişse bu talep gümrük işlemlerinin tamamlanmasından veya eşyanın tesliminden sonra da yapılabilir. Talebin beyanname tesciliyle ya da teslimden öncesiyle sınırlı olduğunu ileri süren ifadeler bu hükme aykırıdır; tercih hakkı tek taraflı tercihlerle sınırlı olmayıp anlaşmalara dayalı tercihli tarifeleri de kapsar. (MD GK 15/3, 15/4)',
 kanit='9-TAR.POZ.AYIRMA.txt | beyan sahibi (c) bendinde belirtilen tarife yerine (d), (e) ve (f) bentleri hükümlerinin uygulanmasını isteyebilir. Gerekli koşulların yerine getirilmesi halinde, söz konusu talep gümrük işlemlerinin tamamlanmasından veya eşyanın tesliminden sonra da yapılabilir.'),

dict(id='D6-038', cikmis='2021/38', konu='Bağlayıcı Bilgi (BTB/BMB)', tip='T2', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.9/6; Gümrük Yönetmeliği m.29/1, 29/2, 29/3',
 cek='BMB Gümrükler Genel Müdürlüğünce verilir, bir kalem eşya için istenir; DGÖ değil DTÖ Menşe Kuralları değişikliğiyle geçersizleşir; bildirimde itiraz yolu belirtilir.',
 kok=['4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliğine göre bağlayıcı menşe bilgisine ilişkin şu ifadeler veriliyor:',
      'I. Kişinin yazılı talebi üzerine Gümrükler Genel Müdürlüğünce verilen ve eşyanın tercihli veya tercihli olmayan menşeinin tespitine ilişkin idari karardır.',
      'II. Dünya Gümrük Örgütünün nomanklatür ve izahnameye ilişkin kararlarındaki bir değişikliğe uymaması hâlinde geçerliliğini kaybeder.',
      'III. Başvurusu, aynı tarife pozisyonu alt açılımında bulunan ve aynı yasal ya da tercihli vergi oranına tabi olan bir kalem eşya için yapılır.',
      'IV. İtiraz yolu öngörülmediğinden, başvuru sahibine yapılan bildirimde itiraz yoluna ilişkin açıklamaya yer verilmez.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I ve III', c=['Yalnız I', 'II ve III', 'I, II ve III', 'I, III ve IV'],
 opts=['Yalnız I', 'I ve III', 'II ve III', 'I, II ve III', 'I, III ve IV'],
 tuzak=False,
 g='Bağlayıcı menşe bilgisi Gümrükler Genel Müdürlüğünce verilen idari karardır ve başvurusu yalnızca bir kalem eşya için yapılır; bu nedenle I ve III doğrudur. Dünya Gümrük Örgütü kararlarındaki değişikliğe uymama bağlayıcı tarife bilgisinin geçersizlik nedenidir; bağlayıcı menşe bilgisinde ölçüt Dünya Ticaret Örgütü Menşe Kuralları Anlaşmasındaki değişikliktir (II yanlış). Bildirimde Kanunda öngörülen itiraz yolunun açık olduğu belirtilir (IV yanlış). (MD GK 9/6; GY 29/1-3)',
 kanit='7-BİLGİ.txt | Bağlayıcı Menşe Bilgisi, kişinin yazılı talebi üzerine Müsteşarlık (Gümrükler Genel Müdürlüğü) tarafından verilen ve eşyanın tercihli veya tercihli olmayan menşeinin tespitine ilişkin idari karardır. || 7-BİLGİ.txt | Dünya Ticaret Örgütünün uymakla yükümlü bulunduğumuz Menşe Kuralları Anlaşmasına || 7-BİLGİ.txt | Bağlayıcı Menşe Bilgisine karşı Kanunun 242 nci maddesi hükümleri çerçevesinde itiraz yolunun açık olduğu belirtilir.'),

dict(id='D6-082', cikmis='2021/82', konu='Yetkilendirilmiş Yükümlü', tip='T3', z='OÜ',
 madde='Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği m.27/1, 30/1, 31/1',
 cek='Kamu alacağını ödememe ihlali askı sonrası üç yıl içinde ikinci kez tekrarlanırsa kısmi teminat yetkisi borç ödendikten sonra iki yıl askıya alınır.',
 kok=['Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliğine göre, ödeme ihlali üç yıl içinde tekrarlanırsa kısmi teminat yetkisi **ne kadar süre** askıya alınır?'],
 d='2 yıl', c=['3 ay', '6 ay', '1 yıl', '3 yıl'], opts=['3 ay', '6 ay', '1 yıl', '2 yıl', '3 yıl'],
 tuzak=False,
 g='Kesinleşmiş gümrük vergisi, faiz ve para cezasını süresinde ödememe ihlalinin, sertifikanın bu nedenle askıya alınmasının sona erdirilmesini takip eden üç yıl içinde ikinci kez tekrarlanması hâlinde kısmi teminat yetkisi, borcun ödenmesini müteakip iki yıl süreyle askıya alınır. Üç yıl tekrarın arandığı süredir; üç ay ve altı ay ise eksik beyanda bulunma yetkisinin askıya alınmasında öngörülen sürelerdir. (MD GİKY 30/1, 31/1)',
 kanit='3-YYS.txt | Kesinleşmiş gümrük vergisi ve/veya ceza borcunun ödenmesini müteakip, 2 yıl süreyle askıya alınır.'),

# ===================== DENEME 7 =====================
dict(id='D7-043', cikmis='2022/43', konu='Tarife', tip='T5', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.15/5; Gümrük Yönetmeliği m.32/1-i, l',
 cek='Hacimle sınırlı tarife uygulamaları: tarife kotasında ithalat hacmi sınırına ulaşılınca, tarife tavanında Cumhurbaşkanı Kararı ile sona erer.',
 kok=['4458 sayılı Gümrük Kanununa göre, tercihli tarife uygulamaları ile şartlı muafiyet veya indirim uygulamalarından belirli bir ithalat hacmi ile sınırlandırılmış olanlar; tarife kotalarının söz konusu olduğu durumlarda …… , tarife tavanlarının söz konusu olduğu durumlarda ise …… sona erer.',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='tespit edilen ithalat hacmi sınırına ulaşıldığında – Cumhurbaşkanı Kararı ile',
 c=['Cumhurbaşkanı Kararı ile – tespit edilen ithalat hacmi sınırına ulaşıldığında',
    'tespit edilen ithalat hacmi sınırına ulaşıldığında – Ticaret Bakanlığı kararı ile',
    'belirlenen dönemin sonunda – tespit edilen ithalat hacmi sınırına ulaşıldığında',
    'Ticaret Bakanlığı kararı ile – belirlenen uygulama döneminin sonunda'],
 tuzak=False,
 g='Kanuna göre belirli bir ithalat hacmiyle sınırlandırılmış tarife uygulamaları, tarife kotalarında tespit edilen ithalat hacmi sınırına ulaşıldığında, tarife tavanlarında ise Cumhurbaşkanı Kararı ile sona erer. Sıralamanın ters verildiği seçenek çapraz tuzaktır; tarife tavanının sona ermesi Bakanlık kararına veya dönem sonuna bağlanmamıştır. (MD GK 15/5; GY 32/1-i, l)',
 kanit='9-TAR.POZ.AYIRMA.txt | a) Tarife kotalarının söz konusu olduğu durumlarda, tespit edilen ithalat hacmi sınırına ulaşıldığında, b) Tarife tavanlarının söz konusu olduğu durumlarda ise Cumhurbaşkanı Kararı ile, Sona erer.'),

dict(id='D7-071', cikmis='2022/71', konu='Bağlayıcı Bilgi (BTB/BMB)', tip='T1', z='OÜ',
 madde='Gümrük Genel Tebliği (Tarife) (Seri No: 14) m.7/1, 8/2, 8/3, 10/2',
 cek='BTB kapsamına girmediği sonradan anlaşılan başvuru, ancak başvuru sahibi talep ederse tarife bilgisi (Seri No: 11) hükümlerine göre değerlendirilir.',
 kok=['Gümrük Genel Tebliği (Tarife) (Seri No: 14)\'e göre, BTB başvurusuna ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Başvuru konusu eşyanın BTB kapsamına girmediği sonradan anlaşılırsa mevcut başvuru, başvuru sahibinin talebi aranmaksızın Gümrük Genel Tebliği (Tarife) (Seri No: 11) hükümlerine göre değerlendirilir.',
 c=['BTB başvurusu, BTB Programına veri girişi yapılması suretiyle elektronik olarak veya başvuru formu örneğine uygun bir formla yazılı olarak yetkilendirilmiş bölge müdürlüğüne yapılır.',
    'Başvurunun form ile yazılı olarak yapılması hâlinde, ekindeki tüm belgeler ve eşyanın teşhisini sağlayacak fotoğraflar kâğıt nüshasıyla birlikte ayrıca dijital ortamda da başvuru yapılan bölge müdürlüğüne sunulur.',
    'Üzerlerinde veya ambalajlarında ayniyetini tespite yarayacak bilgileri bulunmayan eşyaya dair başvurular, ayniyet tespitinin fiziki olarak da mümkün olmaması hâlinde reddedilebilir.',
    'Başvuru sahipleri başvurularının işlem durumu hakkında BTB Programından bilgi edinebilir; elektronik ortamda yapılan başvuruların reddedilmesi durumunda başvuru sahibine ayrıca tebligat yapılmaz.'],
 tuzak=False,
 g='Tebliğe göre başvuru konusu eşyanın BTB kapsamına girmediğinin sonradan anlaşılması hâlinde mevcut başvurunun Seri No: 11 hükümlerine göre değerlendirilmesi, başvuru sahibince talep edilmesi şartına bağlıdır; idarece re\'sen yapılmaz. Elektronik başvuruların reddinde ayrıca tebligat yapılmaması ve ayniyet tespiti fiziken de mümkün olmayan eşyaya ilişkin başvuruların reddedilebilmesi Tebliğe uygundur. (MD Tarife Seri No:14 m.7/1, 8/2, 8/3, 10/2)',
 kanit='7-BİLGİ.txt | Başvuru konusu eşyanın BTB kapsamına girmediğinin sonradan anlaşılması ve başvuru sahibince talep edilmesi halinde, mevcut BTB başvurusu'),

dict(id='D7-093', cikmis='2022/93', konu='Yetkilendirilmiş Yükümlü', tip='T3', z='OÜ',
 madde='Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği m.14/1-ç, 156/1, 156/3',
 cek='YYS sertifikası iptal edilen kişinin iptal işlemini müteakip üç yıl içinde yaptığı yeni sertifika başvurusu ön incelemesiz reddedilir.',
 kok=['Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliğine göre, sertifikası iptal edilenin yeni başvurusu **hangi süre içinde** yapılırsa reddedilir?'],
 d='İptal işlemini müteakip 3 yıl içinde',
 c=['İptal işlemini müteakip 2 yıl içinde', 'İptal işlemini müteakip 1 yıl içinde', 'İptal kararının tebliğinden itibaren 6 ay içinde', 'Sertifikanın düzenlendiği tarihten itibaren 5 yıl içinde'],
 tuzak=False,
 g='Yanlış veya eksik bilgiye ya da sahte belgeye dayanılarak verildiği anlaşılması gibi nedenlerle sertifikası iptal edilen kişilerin, iptal işlemini müteakip üç yıl içinde yaptıkları yeni sertifika başvuruları ön inceleme yapılmaksızın reddedilir. İki yıl, onaylanmış kişi statü belgesi iptal edilen kişilere statü verilmeyecek süredir; beş yıl ise sertifika koşullarının izlenme periyodudur. (MD GİKY 14/1-ç, 156/1, 156/3)',
 kanit='3-YYS.txt | sertifikası daha önce iptal edilmiş kişiler tarafından yeni sertifika başvurusunun, iptal işlemini müteakip 3 yıl içerisinde yapılmış olması. || 3-YYS.txt | 3 yıl içerisinde yapılan sertifika başvuruları reddedilir.'),

dict(id='D7-094', cikmis='2022/94', konu='Onaylanmış Kişi', tip='T1', z='Z',
 madde='Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) m.17/1, 18/2, 19/1, 21/1, 21/2',
 cek='OKS eksik beyanında götürü teminatı olmayandan vergi farkı kadar teminat istenir; eksik belgenin faks veya fotokopisi ibraz edilirse teminat aranmaz.',
 kok=['Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)\'ne göre, statü belgesi sahiplerinin yararlandığı eksik beyan usulüne ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Götürü teminat yetkisi bulunmayan statü belgesi sahiplerinden, eksik belgelerin faks veya fotokopisi ibraz edilmiş olsa dahi normal oranlarla indirimli oranlar arasındaki fark için teminat istenir.',
 c=['Fatura, A.TR dolaşım belgesi, menşe ispat belgeleri ile ödeme şekli gereği ibrazı gereken navlun makbuzu ve sigorta poliçesi, beyannameye eklenmeksizin beyanda bulunulabilecek belgeler arasında sayılmıştır.',
    'İndirimli veya sıfır oranında gümrük vergisi için gereken belgelerin eksikliğinde, yeterli nedenlerin bulunması koşuluyla gümrük müdürlüğünce üç ayı geçmeyecek şekilde ek süre verilebilir.',
    'Türkiye Gümrük Bölgesine getirilen eşyanın bir rejime tabi tutulmasına ilişkin tüm belgelerinin tam olması koşuluna bağlanan usul ve düzenlemelerde eksik beyan usulünden faydalanılamaz.',
    'Götürü teminattan yararlanan statü belgesi sahiplerinin indirimli oran veya muafiyet belgesinin eksikliği nedeniyle yaptığı eksik beyanda vergi tahakkuku beyana göre yapılır.'],
 tuzak=False,
 g='Götürü teminattan yararlanmayan statü belgesi sahiplerinden normal oranlar ile indirimli veya sıfır oranlar ya da muafiyet arasındaki fark için teminat istenir; ancak eksik belgelerin faks veya fotokopisi ibraz edilirse teminat aranmaz ve beyana göre işlem yapılır. Götürü teminattan yararlananlarda tahakkukun beyana göre yapılması ve indirimli oran belgeleri için üç ayı geçmeyen ek süre verilebilmesi Tebliğe uygundur. (MD OKS Tebliği 17/1, 18/2, 19/1, 21/1-2)',
 kanit='4-OKSB.txt | Söz konusu eksik belgelerin faks veya fotokopisinin ibrazı halinde teminat aranmayıp beyana göre işlem yapılır.'),

dict(id='D7-095', cikmis='2022/95', konu='Onaylanmış Kişi', tip='T4', z='OÜ',
 madde='Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) m.43/1, 45/1, 46/1',
 cek='Mavi hatta işlem gören eşyanın ihracat vergileri statü belgesi sahibinin banka hesabından elektronik ortamda ödenir; çıkış ödemeden sonra yapılır.',
 kok=['Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)\'ne göre, mavi hatta işlem gören eşyanın ihracat vergileri nasıl ödenir?'],
 d='Statü belgesi sahibinin banka hesabından elektronik ortamda ödenir.',
 c=['Gümrük müşavirinin banka hesabından elektronik ortamda ödenir.',
    'Götürü teminattan düşülerek eşyanın çıkışından sonra ayrıca tahsil edilir.',
    'Gümrük muhasebe birimine nakden ve eşyanın çıkışından önce ödenir.',
    'Eşyanın çıkışından sonra sonradan kontrol kapsamında tahsil edilir.'],
 tuzak=False,
 g='Mavi hatta işlem görmüş beyanname kapsamı eşyaya ilişkin tahakkuk eden ihracat vergilerinin, onaylanmış kişi statü belgesine sahip kişinin banka hesabından elektronik ortamda ödenmesi zorunludur ve eşyanın çıkış işlemleri bu vergilerin ödenmesi ya da teminata bağlanmasının ardından yapılır. Bu nedenle ödemenin gümrük müşavirinin hesabından yapılması veya vergilerin çıkıştan sonra sonradan kontrol kapsamında tahsil edilmesi mümkün değildir. (MD OKS Tebliği 45/1, 46/1)',
 kanit='4-OKSB.txt | tahakkuk eden ihracat vergilerinin, onaylanmış kişi statü belgesine sahip kişinin banka hesabından elektronik ortamda || 4-OKSB.txt | ihracat vergilerinin ödenmesi ya da teminata bağlanmasının ardından eşyanın çıkış işlemleri yapılır.'),
]
