# Görev K14 — İhracat, geri gelen eşya, posta ve hızlı kargo, kumanya, gümrüksüz satış mağazaları
Q = [
# ===================== DENEME 6 =====================
dict(id='D6-030', cikmis='2021/30', konu='Geri Gelen Eşya', tip='T3', z='OÜ',
 madde='Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1) m.9/4; 4458 sayılı Gümrük Kanunu m.168/1',
 cek='Ticari kiralama yoluyla geçici ihraçta üç yıllık süre, bitiminden önce başvurulursa gümrük müdürlüğünce kiralama sözleşmesindeki süre kadar uzatılabilir.',
 kok=['Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1)’e göre, ticari kiralama yoluyla yapılan ihracatta süre **ne kadar** uzatılabilir?'],
 d='Süre bitmeden başvurulursa kiralama sözleşmesinde belirlenen süre kadar',
 c=['Süre bitmeden başvurulursa gümrük müdürlüğünce en çok iki ay kadar',
    'Süre bitiminden sonra başvurulsa dahi gümrük müdürlüğünce yeteri kadar',
    'Süre bitmeden başvurulursa bir defaya mahsus olmak üzere en çok üç ay',
    'Kiralama sözleşmesine bakılmaksızın üç yıllık kanuni süreyi aşmayacak kadar'],
 tuzak=False,
 g='Ticari kiralama yoluyla yapılan ihracatta süre Gümrük Kanunundaki üç yıllık süreyi aşamaz; ancak bu süre, bitiminden önce başvurulmak kaydıyla ilgili gümrük müdürlüğünce ticari kiralama sözleşmesinde belirlenen süre kadar uzatılabilir. Süre bitiminden sonra başvurulsa dahi yeteri kadar ek süre verilmesi, mücbir sebeple geri getirilemeyen taşıtlara ilişkin kuraldır; iki aylık uzatma ise geçici depolamaya konulmaksızın ihraç edilen eşyanın beyanname kapatma süresine aittir. (MD Hariçte İşleme-Geçici İhracat Tebliği 9/4; GK 168/1)',
 kanit='36-ihracat.txt | Ticari kiralama yoluyla yapılacak ihracatta süre, Gümrük Kanununun 168 inci maddesinde belirtilen 3 yıllık süreyi aşamaz. Ancak bu süre, bitiminden önce başvurulmak kaydıyla, ilgili gümrük müdürlüğünce ticari kiralama sözleşmesinde belirlenen süre kadar uzatılabilir.'),

dict(id='D6-059', cikmis='2021/59', konu='Posta/Hızlı Kargo', tip='T2', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.173/2, 173/3, 174, 175/2',
 cek='Posta çantaları ve koliler giriş kapısından gözetimle posta idaresine sevk edilir; çıkışta mühür ve kap sağlamlığı tespit edilir; bekleme süresi uluslararası posta anlaşmalarına tabidir.',
 kok=['4458 sayılı Gümrük Kanununun posta gümrük işlemlerine ilişkin hükümlerine göre aşağıdaki ifadeler veriliyor:',
      'I. Gelen bütün posta çantaları ve koliler ilk giriş kapısından itibaren gümrük gözetimi altında posta idarelerine sevk edilir ve buralarda muayene edilir.',
      'II. Gönderilecek posta çantaları ve kolilerin ihracına, gümrük mühür veya işaretlerinin varlığı ve kapların sağlamlığı tespit edildikten sonra izin verilir.',
      'III. Posta eşyasının posta idaresinin sorumluluğunda konulduğu yerlerdeki bekleme süresi, geçici depolama süreleri esas alınarak belirlenir.',
      'IV. Ticari mahiyette olmayan eşyada uluslararası kabul görmüş belgeler ibraz edilse dahi ayrıca gümrük beyannamesi verilmesi zorunludur.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I ve II', c=['I ve IV', 'II ve III', 'I, II ve III', 'I, II ve IV'],
 opts=['I ve II', 'I ve IV', 'II ve III', 'I, II ve III', 'I, II ve IV'],
 tuzak=False,
 g='Gelen posta çantaları ve koliler ilk giriş kapısından itibaren gümrük gözetiminde posta idarelerine sevk edilip orada muayene edilir; gönderilecek olanların ihracına ise mühür veya işaretler ile kap sağlamlığı tespit edildikten sonra çıkış gümrüğünden izin verilir, bu nedenle I ve II doğrudur. Posta eşyasının konulduğu genel antrepo sayılan yerlerdeki bekleme süresi Türkiye’nin taraf olduğu uluslararası posta anlaşmalarına tabi olduğundan III; ticari mahiyette olmayan eşyada uluslararası kabul görmüş belgeler beyanname hükmünde olup ayrıca beyanname aranmadığından IV yanlıştır. (MD GK 173/2-3, 174, 175/2)',
 kanit='40-posta ve hızlı kargo.txt | Türkiye Gümrük Bölgesine gelen bütün posta çantaları ve koliler ilk giriş kapısından itibaren gümrük gözetimi altında posta idarelerine sevk edilir || 40-posta ve hızlı kargo.txt | Eşyanın buralarda bekleme süresi, Türkiye\'nin taraf olduğu uluslararası posta anlaşmaları hükümlerine tabidir. || 40-posta ve hızlı kargo.txt | ibraz edilen uluslararası kabul görmüş belgeler beyanname hükmünde olup, ayrıca beyanname aranmaz.'),

dict(id='D6-064', cikmis='2021/64', konu='Geri Gelen Eşya', tip='T8', z='Z',
 madde='Gümrük Yönetmeliği m.453/4, 453/5',
 cek='Geçici ihracatın süreler bittikten sonra kesin ihracata dönüştürülmesinde de kesin ihracat beyannamesi ve ihracat mevzuatına uyum kaydıyla izin verilip rejim sonlandırılır.',
 kok=['(K) Makine Sanayi A.Ş., mülkiyeti kendisine ait bir iş makinesini yurt dışında yerleşik (L) firmasına kiralamak üzere ticari kiralama yoluyla geçici ihracat kapsamında Türkiye Gümrük Bölgesinden çıkarmıştır. Gümrük müdürlüğünce kiralama sözleşmesinde belirlenen süre kadar yapılan uzatma da dahil olmak üzere geçici ihracat için verilen bütün süreler dolmuş; makine bu süreler içinde yurda geri getirilmemiş, firma mücbir sebep veya beklenmeyen hâle dayanan yeni bir süre uzatımı talebinde de bulunmamıştır. Sürelerin bitiminden iki ay sonra (L) firması kiraladığı makineyi satın almak istemiş, bunun üzerine (K) firması geçici ihracatın kesin ihracata dönüştürülmesi için geçici ihracat işlemlerinin yapıldığı gümrük idaresine başvurmuştur. Makine ihracat vergisine tabi değildir ve ihracatına ilişkin herhangi bir yasak veya kısıtlama bulunmamaktadır.',
      'Gümrük Yönetmeliğine göre, (K) firmasının talebi üzerine yapılacak işlem aşağıdakilerden hangisidir?'],
 d='Kesin ihracata ilişkin gümrük beyannamesinin düzenlenmesi ve ihracat rejimine ilişkin tüm mevzuat hükümlerine uyulmuş olması kaydıyla dönüştürmeye izin verilir ve geçici ihracat rejimi sonlandırılır.',
 c=['Süreler dolduktan sonra yapılan dönüştürme talebi kabul edilmez; makinenin yurda getirilmesi hâlinde usulsüzlük cezası uygulanarak ve gümrük vergileri tahsil edilerek serbest dolaşıma giriş rejimi hükümleri uygulanır.',
    'Süreler dolduktan sonra yapılan talep ancak özel ve zorunlu durum olarak Bakanlıkça incelenip sonuçlandırılabilir; olumlu karar verilinceye kadar geçici ihracat beyannamesi açık tutularak ek süre işletilir.',
    'Sürelerin bitiminde makinenin geri getirilmediği tespit edildiğinden makine gümrüğe terk edilmiş sayılır ve tasfiye hükümlerine göre işlem yapılmak üzere durum ilgili gümrük idaresine bildirilir.',
    'Dönüştürme yalnızca sürelerin bitiminden önce istenebildiğinden geçici ihracat beyannamesi iptal edilir ve makinenin satışı için firma adına yeni bir kesin ihracat işlemi başlatılması istenir.'],
 tuzak=False,
 g='Geçici ihracatın, verilen sürelerin bitiminden sonra kesin ihracata dönüştürülmek istenmesi hâlinde de süre bitiminden önceki dönüştürmeye ilişkin hüküm uygulanır; kesin ihracata ilişkin gümrük beyannamesi düzenlenmesi ve ihracat rejimine ilişkin tüm mevzuata uyulması kaydıyla izin verilerek rejim sonlandırılır. Usulsüzlük cezası, vergi tahsili ve serbest dolaşıma giriş, süresini aşarak yurda geri getirilen eşyaya ilişkin sonuçtur; makine geri getirilmediğinden bu hüküm uygulanmaz. Süre aşımı eşyayı gümrüğe terk edilmiş saymaz ve talebin kabulü özel ve zorunlu durum değerlendirmesine bağlı değildir. (MD GY 453/4-5)',
 kanit='37-geri gelen eşya.txt | geçici ihracatın kesin ihracata dönüştürülmek istenmesi halinde, kesin ihracata ilişkin gümrük beyannamesinin düzenlenmesi ve ihracat rejimine ilişkin tüm mevzuat hükümlerine uyulmuş olması kaydıyla geçici ihracata konu eşyanın kati ihracata dönüştürülmesine izin verilerek ilgili rejim sonlandırılır. || 37-geri gelen eşya.txt | Geçici ihracatın dördüncü fıkrada belirtilen sürelerin bitiminden sonra kesin ihracata dönüştürülmek istenmesi halinde dördüncü fıkra hükümleri uygulanır.'),

dict(id='D6-065', cikmis='2021/65', konu='Posta/Hızlı Kargo', tip='T1', z='OÜ',
 madde='Gümrük Yönetmeliği m.456/1, 457/2, 458/3, 460/3, 462/3',
 cek='Posta kolilerinin ayrımında ticari nitelikte olmayan eşya için koli alıcısına tebligat yapılmaksızın muayene ve tahakkuk yapılır; haber kağıdı ticari eşya içindir.',
 kok=['Gümrük Yönetmeliğine göre, posta kolilerinin gümrük işlemlerine ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Kolilerin ayrımı sonucunda ticari nitelikte olmadığı anlaşılan eşya için de koli alıcısına, giriş işlemlerinin yapılabilmesi amacıyla en kısa zamanda gümrük idaresine başvurması gerektiği haber kağıdıyla bildirilir ve muayene ile tahakkuk işlemlerine ancak alıcının bu başvurusu üzerine başlanabilir.',
 c=['Posta idareleri gelen kolilere ait listeleri kolilerin birikmesini beklemeden düzenleyip iki nüshasını imza karşılığında gümrük idaresine verir; bu listeler her posta için ayrı ayrı veya bir günde gelen bütün koliler için tek bir liste olarak düzenlenebilir.',
    'Ticari nitelikte olmayan eşyanın Déclaration en Douane’larında yazılı değerler gümrük idaresince uygun bulunduğu takdirde aynen kabul olunur; uygun görülmeyenler ile kıymeti gösterilmeyen eşyada ise gümrük kıymeti hükümlerine göre tespit edilen kıymet vergi tahakkukuna esas tutulur.',
    'Gümrük veznesi bulunmayan posta idarelerinde kolilere ait tahakkuk ettirilmiş vergiler posta idaresince tahsil edilir ve gümrük adına tahsil edilen paralar en geç bir hafta içinde, tahakkuk belgelerine dayanan bir liste ile gümrük veznesine alındı karşılığında ödenir.',
    'Muayene ile görevli memurlar kendilerine havale edilen listelerde gösterilen kolilerdeki eşyayı inceleyerek ticari ve ticari olmayan eşyayı ayırır; posta idaresince verilen listeler ekleriyle birlikte muayene, tahakkuk ve ayrım işlemlerinde göz önünde tutulmak üzere bu memurlara havale edilir.'],
 tuzak=True,
 g='Ayrım sonucunda ticari nitelikte olmayan eşya için koli alıcısına haber kağıdıyla tebligat yapılmaksızın muayene ve tahakkuk işlemleri yapılır; haber kağıdıyla gümrüğe başvurma bildirimi yalnız ticari nitelikteki eşya için öngörülmüştür. Listelerin birikme beklenmeden iki nüsha verilmesi, Déclaration en Douane değerlerinin uygun bulunursa aynen kabulü ve posta idaresince tahsil edilen vergilerin en geç bir hafta içinde gümrük veznesine ödenmesi Yönetmelikteki hükümlerdir. (MD GY 456/1, 457, 458, 460/3, 462)',
 kanit='40-posta ve hızlı kargo.txt | ticari nitelikte olmayan eşya için ikinci fıkraya göre koli alıcısına tebligat yapılmaksızın, muayene ve tahakkuk işlemleri yapılır. || 40-posta ve hızlı kargo.txt | Posta idaresi gümrük adına tahsil ettiği paraları en geç bir hafta içinde, tahakkuk belgelerine dayanan bir liste ile gümrük veznesine alındı karşılığında öder.'),

dict(id='D6-067', cikmis='2021/67', konu='Posta/Hızlı Kargo', tip='T6', z='OÜ',
 madde='Posta ve Hızlı Kargo Yoluyla Taşınan Eşyanın Gümrük İşlemlerine İlişkin Tebliğ (Seri No: 1) m.3/1-ç, 3/1-d, 9/1-a, 10/2',
 cek='Kişisel yazılı mesaj, kartpostal ve ticari değer taşımayan basılı materyal şeklindeki gönderiler Tebliğde “doküman” olarak tanımlanır.',
 kok=['Posta ve Hızlı Kargo Yoluyla Taşınan Eşyanın Gümrük İşlemlerine İlişkin Tebliğ (Seri No: 1)’de “Bir kişiden diğer bir kişiye gönderilen kişisel yazılı mesaj, kartpostal ile herhangi bir ticari değer taşımayan basılı materyal şeklindeki gönderiler” olarak tanımlanan kavram aşağıdakilerden hangisidir?'],
 d='Doküman',
 c=['Gönderi', 'Koli', 'Mektup postası', 'Basılmış metin'],
 tuzak=False,
 g='Tebliğde kişisel yazılı mesaj, kartpostal ve ticari değer taşımayan basılı materyal şeklindeki gönderiler “doküman” olarak tanımlanmış; bu gönderiler belge kontrolüne tabi ayrı bir kategoride tek kalemde topluca beyan edilir. “Gönderi” ise içerisinde ticari veya gayri ticari nitelikte eşya bulunan paket, koli, poşet ve benzerini ifade eder; koli de bu kapsamdaki bir gönderi türüdür. (MD Posta ve Hızlı Kargo Tebliği 3/1-ç, d; 10/2)',
 kanit='40-posta ve hızlı kargo.txt | ç) Doküman: Bir kişiden diğer bir kişiye gönderilen kişisel yazılı mesaj, kartpostal ile herhangi bir ticari değer taşımayan basılı materyal şeklindeki gönderileri, || 40-posta ve hızlı kargo.txt | d) Gönderi: Bir kişiden diğer bir kişiye gönderilen, içerisinde ticari veya gayri ticari nitelikte eşya bulunan paket, koli, poşet ve benzerini,'),

dict(id='D6-068', cikmis='2021/68', konu='İhracat', tip='T5', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.150/1, 151',
 cek='İhracat, ticaret politikası önlemleri ve gerektiğinde ihracat vergileri dahil çıkış hükümleriyle gerçekleşir; fiilen ihraç sayılan eşya üzerindeki gümrük kontrolü sona erer.',
 kok=['4458 sayılı Gümrük Kanununa göre; ihracat, ticaret politikası önlemleri ve gerektiği takdirde …… de dahil olmak üzere çıkış işlemlerine ilişkin hükümlerin uygulanmasıyla gerçekleştirilir. İhraç eşyasının fiilen ihraç edilmiş sayıldığı durumda, ihraç eşyası üzerindeki …… sona erer.',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='ihracat vergileri – gümrük kontrolü',
 c=['ithalat vergileri – gümrük kontrolü', 'ihracat vergileri – gümrük gözetimi', 'ithalat vergileri – gümrük gözetimi', 'ihracat iadeleri – gümrük yükümlülüğü'],
 tuzak=False,
 g='Kanuna göre ihracat, ticaret politikası önlemleri ve gerektiği takdirde ihracat vergileri de dahil olmak üzere çıkış işlemlerine ilişkin hükümlerin uygulanmasıyla gerçekleştirilir; tescildeki durum ve niteliğini koruyarak Türkiye Gümrük Bölgesini terk eden eşya fiilen ihraç edilmiş sayılır ve bu durumda eşya üzerindeki gümrük kontrolü sona erer. İthalat vergileri ihraç eşyasına ilişkin çıkış hükümleri arasında yer almaz; Kanun fiili ihracatla sona eren unsuru gümrük gözetimi olarak değil gümrük kontrolü olarak belirlemiştir. (MD GK 150/1, 151)',
 kanit='36-ihracat.txt | İhracat, ticaret politikası önlemleri ve gerektiği takdirde ihracat vergileri de dahil olmak üzere çıkış işlemlerine ilişkin hükümlerin uygulanmasıyla gerçekleştirilir. || 36-ihracat.txt | Bu durumda, ihraç eşyası üzerindeki gümrük kontrolü[132] sona erer.'),

dict(id='D6-069', cikmis='2021/69', konu='Akaryakıt-Kumanya', tip='T1', z='OÜ',
 madde='Gümrük Yönetmeliği m.477/1, 477/3, 478/2, 479/1, 480/1',
 cek='Şüphe veya ihbar olmadıkça yakıt, yağ ve kumanya muayeneye tabi tutulmaz; yalnız gümrük idaresinin gözetiminde gemiye yüklenir.',
 kok=['Gümrük Yönetmeliğine göre, deniz ve hava taşıtlarına verilecek yakıt ve kumanyaya ilişkin gümrük işlemleri ile Türk bandıralı gemilerin yakıt ve kumanya kayıtları hakkında aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Deniz ve hava taşıtlarına verilecek yakıt, yağ ve kumanya, şüphe veya ihbar bulunup bulunmadığına bakılmaksızın her teslimde gümrük idaresince muayeneye tabi tutulur ve muayene sonucunda düzenlenen tutanakla birlikte ancak bu işlemler tamamlandıktan sonra gümrük idaresinin gözetimi altında gemiye yüklenebilir.',
 c=['Deniz ve hava taşıtı kaptanları, acenteleri, bunker veya liman bayileri taşıtın gideceği yer ile talep edilen yakıt miktarını gümrük idaresine yazılı olarak bildirir; talep kaptan ve işletme dışındaki kişilerce yapılırsa kaptan veya işletmece verilen yakıt siparişine dair belge aranır.',
    'Gerekli şartları ispat eden belgeleri teminatla birlikte ilgili gümrüğe ibraz edip taahhütnameyi dolduran bunker ve liman bayileri gemilere yağ ve yakıt verilmesine ilişkin işlemleri yürütebilir; ancak her başvurularında kaptan veya gemi acentesinin talep veya izin yazısını ibraz etmeleri şarttır.',
    'Türkiye Gümrük Bölgesi dışına sefer yapan Türk bandıralı gemilerde tutulan yakıt ve kumanya defterinin sayfaları gümrük idaresince önceden tespit edilerek onanır; deftere yakıt ve kumanyanın tarife istatistik pozisyonu, miktarı ile beyanname ve faturanın numara ve tarihi yazılır.',
    'Türk bandıralı gemiler yabancı limanlardan gelişlerinde yakıt ve kumanyaları için bir liste düzenleyerek bu listeyi ilk uğrayacakları Türk limanında geminin kontrolünü yapacak gümrük idaresine verir ve ilgili memurlar listeyi yakıt ve kumanya defteri ile karşılaştırır.'],
 tuzak=True,
 g='Yönetmeliğe göre şüphe veya ihbar olmadıkça yakıt, yağ ve kumanya muayeneye tabi tutulmaz ve sadece gümrük idaresinin gözetimi altında gemiye yüklenir; her teslimde muayene zorunluluğu öngörülmemiştir. Yakıt talebinin yazılı bildirimi, bayilerin her başvuruda kaptan veya acente yazısını ibraz etmesi, defter sayfalarının önceden onanması ve yabancı limandan dönüşte ilk Türk limanında liste verilmesi Yönetmelikteki hükümlerdir. (MD GY 477/1-3, 478/2, 479, 480)',
 kanit='42-kumanya.txt | Şüphe veya ihbar olmadıkça, yakıt, yağ ve kumanya muayeneye tabi tutulmaz ve sadece gümrük idaresinin gözetimi altında gemiye yüklenir. || 42-kumanya.txt | Bu firmaların gemilere yağ ve yakıt verilmesine ilişkin her başvurularında ilgili kaptan veya gemi acentesinin talep veya izin yazısını gümrük idaresine ibrazı şarttır.'),

dict(id='D6-090', cikmis='2021/90', konu='Posta/Hızlı Kargo', tip='T7', z='OÜ',
 madde='Posta ve Hızlı Kargo Yoluyla Taşınan Eşyanın Gümrük İşlemlerine İlişkin Tebliğ (Seri No: 1) m.3/1-a, 6/1, 6/2, 6/4, 7/1',
 cek='Operatör yetkisi başvurusu işlemlerin yapılacağı gümrük müdürlüğünün bağlı olduğu bölge müdürlüğüne yapılır; yetki Ticaret Bakanlığınca verilir.',
 kok=['Posta ve Hızlı Kargo Yoluyla Taşınan Eşyanın Gümrük İşlemlerine İlişkin Tebliğ (Seri No: 1)’e göre, hızlı kargo taşımacılığı yapan şirketlerin dolaylı temsil yoluyla işlem yapma yetkisi için başvuruda bulunacağı makam ile bu yetkiyi verecek makam **sırasıyla** aşağıdakilerden hangisidir?'],
 d='Gümrük ve Dış Ticaret Bölge Müdürlüğü – Ticaret Bakanlığı',
 c=['İşlemlerin yapılacağı gümrük müdürlüğü – Ticaret Bakanlığı',
    'Ticaret Bakanlığı – Gümrük ve Dış Ticaret Bölge Müdürlüğü',
    'İşlemlerin yapılacağı gümrük müdürlüğü – Bölge Müdürlüğü',
    'Sivil Havacılık Genel Müdürlüğü – Gümrük ve Dış Ticaret Bölge Müdürlüğü'],
 tuzak=False,
 g='Başvuru, yetki kapsamı işlemlerin yapılacağı gümrük müdürlüğünün bağlı olduğu Gümrük ve Dış Ticaret Bölge Müdürlüğüne yapılır; bölge müdürlüğü heyetle yerinde tespit yaparak dosyayı on beş gün içinde Bakanlığa gönderir, yetki ise Bakanlıkça (Ticaret Bakanlığı) verilir. Gümrük müdürlüğü başvuru mercii değildir; Sivil Havacılık Genel Müdürlüğü yalnız hava kargo acentesi yetkisini veren kurumdur. (MD Posta ve Hızlı Kargo Tebliği 6/1-2, 6/4, 7/1)',
 kanit='40-posta ve hızlı kargo.txt | Başvuru, 5 inci maddede belirtilen belgelerle birlikte, yetki kapsamı işlemlerin yapılacağı gümrük müdürlüğünün bağlı olduğu Gümrük ve Dış Ticaret Bölge Müdürlüğüne yapılır. || 40-posta ve hızlı kargo.txt | aranan koşulların varlığının tespit edilmesi halinde kişiye Bakanlıkça yetki verilir.'),
# ===================== DENEME 8 =====================
dict(id='D8-052', cikmis='2023/52', konu='İhracat', tip='T10', z='Z',
 madde='Posta ve Hızlı Kargo Yoluyla Taşınan Eşyanın Gümrük İşlemlerine İlişkin Tebliğ (Seri No: 1) m.10/5, 10/6, 10/7, 10/14, 18/2',
 cek='Basitleştirilmiş beyanla ihracatta sınır brüt 600 kg-30.000 Avro, birlik onayı aranmaz, düzeltme 24 saat; eşya kodu asgari altılı, kırmızı hat geçici depolamaya alınır.',
 kok=['Posta ve Hızlı Kargo Yoluyla Taşınan Eşyanın Gümrük İşlemlerine İlişkin Tebliğ (Seri No: 1) kapsamında operatörlerce basitleştirilmiş gümrük beyannamesi ile yürütülen ihracat işlemlerine ilişkin aşağıdaki eşleştirmeler veriliyor:',
      '1. Operatör tarafından bu Tebliğ hükümleri çerçevesinde beyan edilebilecek ihracat rejimine konu eşyanın azami miktar ve değeri – Brüt 600 kilogram ve 30.000 Avro',
      '2. Bu Tebliğ kapsamında yapılan ihracatta ihracatçı birliği onayı – Aranmaz',
      '3. Basitleştirilmiş gümrük beyannamesinde ihracat eşyası için eşya kodu alanına girilecek bilgi – Asgari sekizli tarife alt pozisyonu',
      '4. Teşvik, sübvansiyon, parasal iade veya ayniyet tespitine konu olmayan gönderilerde taşıma aracı hareket gümrük idaresini terk ettikten sonra beyanda düzeltme yapılabilecek süre – Yirmi dört saat',
      '5. Kırmızı hatta işlem gören taşıma senedi kapsamı ihracat eşyası – Geçici depolama yerine alınmaksızın ihraç edilebilir',
      'Yukarıdaki eşleştirmelerden hangileri doğrudur?'],
 d='1, 2 ve 4', c=['1 ve 2', '1 ve 4', '1, 2 ve 5', '2, 3 ve 4'],
 opts=['1 ve 2', '1 ve 4', '1, 2 ve 4', '1, 2 ve 5', '2, 3 ve 4'],
 tuzak=False,
 g='Operatör brüt 600 kilogramı ve 30.000 Avro’yu geçmeyen ihracat eşyasını beyan edebilir, Tebliğ kapsamındaki ihracatta ihracatçı birliği onayı aranmaz ve taşıma aracı hareket gümrük idaresini terk ettikten sonraki yirmi dört saat içinde beyanda düzeltme yapılabilir; bu nedenle 1, 2 ve 4 doğrudur. Eşya kodu alanına sekizli değil asgari altılı tarife alt pozisyonu girildiğinden 3; kırmızı hatta işlem gören taşıma senedi kapsamı eşya mutlak surette geçici depolama yerine alınarak muayene edildiğinden 5 yanlıştır. (MD Posta ve Hızlı Kargo Tebliği 10/5-7, 10/14, 18/2)',
 kanit='40-posta ve hızlı kargo.txt | miktarı brüt 600 kilogramı[7] ve değeri 30.000 Avro\'yu[8] geçmeyen ihracat rejimine konu eşyanın beyanı bu Tebliğ hükümleri çerçevesinde operatör tarafından yapılır. || 40-posta ve hızlı kargo.txt | Bu Tebliğ hükümleri kapsamında yapılan ihracatta ihracatçı birliği onayı aranmaz. || 40-posta ve hızlı kargo.txt | Taşıma aracı hareket gümrük idaresini terk ettikten sonraki yirmi dört saat içinde beyanda düzeltme yapılabilir. || 40-posta ve hızlı kargo.txt | Kırmızı hatta işlem gören taşıma senedi kapsamı eşya mutlak surette geçici depolama yerine alınarak muayene işlemi tamamlanır.'),

dict(id='D8-053', cikmis='2023/53', konu='Geri Gelen Eşya', tip='T3', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.241/3-ı, 241/4, 241/5, 241/6; Gümrük Yönetmeliği m.453/1',
 cek='Geçici çıkarılan eşyanın verilen süreyi aştıktan sonra geri getirilmesinde usulsüzlük cezası temel tutarın iki katı uygulanır.',
 kok=['4458 sayılı Gümrük Kanununa göre, geçici çıkarılıp verilen süre aşılarak geri getirilen eşyada usulsüzlük cezası temel tutarın **kaç katıdır**?'],
 d='2 kat', c=['3 kat', '4 kat', '6 kat', '8 kat'],
 opts=['2 kat', '3 kat', '4 kat', '6 kat', '8 kat'],
 tuzak=False,
 g='Geçici olarak Türkiye Gümrük Bölgesi dışına çıkarılan eşyanın verilen süreyi aştıktan sonra geri getirilmesi, usulsüzlük cezasının birinci fıkradaki miktarın iki katı olarak uygulandığı hâller arasında sayılmıştır. Dört kat ve altı kat oranları geçici ithalat eşyasının süre bitiminden sonra iki ay veya taşıtlarda üç ay içinde yeniden ihracı gibi başka hâllere, sekiz kat ise önceden belirlenmiş yollar dışında seyretme gibi ihlallere aittir. (MD GK 241/3-ı; GY 453/1)',
 kanit='48-cezalar.txt | Usulsüzlük cezası aşağıdaki hallerde 1 inci fıkrada belirtilen miktarın iki katı olarak uygulanır: || 48-cezalar.txt | ı) Geçici olarak Türkiye Gümrük Bölgesi dışına çıkarılan eşyanın verilen süreyi aştıktan sonra geri getirilmesi,'),

dict(id='D8-059', cikmis='2023/59', konu='Geri Gelen Eşya', tip='T7', z='Z',
 madde='Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1) m.19',
 cek='Geçici İhracat Tebliğinde öngörülmeyen durumları inceleyip sonuçlandırmaya Bakanlık (Gümrükler Genel Müdürlüğü) yetkilidir.',
 kok=['Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1)’de öngörülmeyen durumları sonuçlandırmaya kim yetkilidir?'],
 d='Ticaret Bakanlığı (Gümrükler Genel Müdürlüğü)',
 c=['Ticaret Bakanlığı (İhracat Genel Müdürlüğü)', 'Geçici ihracatın yapıldığı gümrük müdürlüğü', 'Gümrük ve Dış Ticaret Bölge Müdürlüğü', 'İhracatçı Birlikleri Genel Sekreterliği'],
 tuzak=True,
 g='Tebliğe göre ekonomik gereklilikler ve dış ticaret politikaları dikkate alınarak Tebliğde öngörülmeyen durumları inceleyerek sonuçlandırmaya Bakanlığın Gümrükler Genel Müdürlüğü yetkilidir (metinde dönemin adıyla Gümrük ve Ticaret Bakanlığı geçmektedir). İhracat Genel Müdürlüğü ihracı yasak ve ön izne bağlı mallara ilişkin dış ticaret düzenlemesinde yetkilidir; gümrük müdürlüğü ise Tebliğde düzenlenen süre uzatımı gibi işlemleri yürütür, düzenlenmemiş hâlleri sonuçlandırmaz. (MD Hariçte İşleme-Geçici İhracat Tebliği 19)',
 kanit='36-ihracat.txt | Ekonomik gereklilikler ve dış ticaret politikaları dikkate alınarak bu Tebliğde öngörülmeyen durumları inceleyerek sonuçlandırmaya Gümrük ve Ticaret Bakanlığı (Gümrükler Genel Müdürlüğü) yetkilidir.'),
# ===================== DENEME 9 =====================
dict(id='D9-049', cikmis='2024/49', konu='İhracat', tip='T10', z='Z',
 madde='Gümrük Yönetmeliği m.154/5, 158/4, 158/5, 160/3',
 cek='İhracat basitleştirilmiş usulü: 44 no.lu kutuya Basitleştirilmiş İhracat yazılır; F tipi antrepo eşyasına izin yok, B tipinde eksik beyan veya ticari-idari belge kullanılabilir.',
 kok=['Gümrük Yönetmeliğinin ihracat rejiminde basitleştirilmiş usullere ve ekonomik etkili bir gümrük rejimine tabi tutulmuş eşyanın ihracat rejimine girişine ilişkin hükümlerine göre aşağıdaki eşleştirmeler veriliyor:',
      '1. İhracat rejiminde eksik beyan usulüyle verilen gümrük beyannamesinin 44 numaralı kutusuna yazılacak ifade – “Basitleştirilmiş İhracat”',
      '2. F tipi antrepo rejimi uygulanan eşyanın ihracat rejimine girişi – Basitleştirilmiş usullerin tamamına izin verilir',
      '3. B tipi antrepo rejimi uygulanan eşyanın ihracat rejimine girişi – Eksik beyan veya ticari ya da idari belgeyle beyan verilmesi şeklinde beyan usulü uygulanabilir',
      '4. Basitleştirilmiş beyanın ilgili rejime geçiş için gereken bütün bilgi ve belgeleri içermesi – Tamamlayıcı beyan aranmaz',
      '5. Tamamlayıcı beyan ile basitleştirilmiş usule göre gerçekleşen beyanın bir bütün olarak hüküm ifade etmeye başladığı tarih – Tamamlayıcı beyanın verildiği tarih',
      'Yukarıdaki eşleştirmelerden hangileri doğrudur?'],
 d='1, 3 ve 4', c=['Yalnız 1', '1 ve 3', '3 ve 4', '1, 2 ve 4'],
 opts=['Yalnız 1', '1 ve 3', '3 ve 4', '1, 2 ve 4', '1, 3 ve 4'],
 tuzak=False,
 g='Eksik beyanda beyannamenin 44 numaralı kutusuna “Basitleştirilmiş İhracat” ifadesi yazılır, B tipi antrepo rejimi uygulanan eşyanın ihracat rejimine girişinde eksik beyan veya ticari ya da idari belgeyle beyan usulü uygulanabilir ve gerekli bütün bilgi ve belgeleri içeren basitleştirilmiş beyanda tamamlayıcı beyan aranmaz; bu nedenle 1, 3 ve 4 doğrudur. F tipi antrepo rejimi uygulanan eşyanın ihracat rejimine girişinde basitleştirilmiş usule izin verilmediğinden 2; tamamlayıcı beyan ile basitleştirilmiş beyan, basitleştirilmiş beyannamenin veya belgenin tescil edildiği ya da tescil hükmündeki kaydın yapıldığı tarihten itibaren hüküm ifade ettiğinden 5 yanlıştır. (MD GY 154/5, 158/4-5, 160/3)',
 kanit='17-BEYAN.txt | Gümrük beyannamesinin 44 numaralı kutusuna Basitleştirilmiş İhracat ifadesi yazılır. || 17-BEYAN.txt | a) F tipi antrepo rejimi uygulanan eşyanın ihracat rejimine girişinde basitleştirilmiş usule izin verilmez. || 17-BEYAN.txt | b) B tipi antrepo rejimi uygulanan eşyanın ihracat rejimine girişinde eksik beyan veya ticari veya idari belgeyle beyan verilmesi şeklinde beyan usulü uygulanabilir. || 17-BEYAN.txt | basitleştirilmiş işlemlere ilişkin beyannamenin ya da ticari veya idari bir belgenin tescil edildiği ya da tescil hükmünde olan kayıt işleminin yapıldığı tarihten itibaren hüküm ifade eder. || 17-BEYAN.txt | daha önce gümrük beyannamesi verildiği hallerde tamamlayıcı beyan aranmaz.'),

dict(id='D9-055', cikmis='2024/55', konu='İhracat', tip='T2', z='OÜ',
 madde='Gümrük Yönetmeliği m.418/1, 158/2, 477/2, 476/1',
 cek='Yakıt, yağ ve kumanya dışında dış seferdeki deniz ve hava taşıtlarına serbest dolaşımdaki işletme ve donatım eşyası teslimi ihracat hükmündedir.',
 kok=['Gümrük Yönetmeliğine göre, dış seferdeki deniz ve hava taşıtlarına yapılan teslimlere ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Yakıt, yağ ve kumanya dışında, serbest dolaşımda bulunan işletme ve donatım eşyasının bu taşıtlara teslimi ihracat hükmündedir.',
      'II. Bir ay içinde bu taşıtlara basitleştirilmiş usulle yapılan ve ihracat sayılan teslimlere ilişkin tamamlayıcı beyan, izleyen ayın ilk üç günü içinde yapılır.',
      'III. Kaptanlar, gemi acenteleri ve kumanyacılık firmaları, geminin gideceği yer ile gemiye verilecek kumanyanın cins ve miktarını belirten kumanya listelerini gümrük idaresine bildirir.',
      'IV. Henüz serbest dolaşıma girmemiş yakıt ve yağlar, kaçakçılıkla mücadele eden birimlere bu kapsamda verilemez.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I ve III', c=['Yalnız I', 'I ve IV', 'II ve III', 'I, III ve IV'],
 opts=['Yalnız I', 'I ve III', 'I ve IV', 'II ve III', 'I, III ve IV'],
 tuzak=False,
 g='Yakıt, yağ ve kumanya dışında dış seferdeki taşıtlara serbest dolaşımdaki işletme ve donatım eşyası teslimi ihracat hükmündedir ve kumanya listeleri kaptan, acente veya kumanyacılık firmalarınca gümrük idaresine bildirilir; bu nedenle I ve III doğrudur. Bu taşıtlara yapılan ve ihracat sayılan teslimlerde tamamlayıcı beyan izleyen ayın ilk üç günü değil ilk yedi iş günü içinde verildiğinden II; kaçakçılıkla mücadele eden birimlere bu kapsamda yakıt ve yağ verildiğinden IV yanlıştır. (MD GY 418, 158/2, 476/1, 477/2)',
 kanit='36-ihracat.txt | dış seferde bulunan ya da dış sefere çıkacak olan deniz ve hava taşıtlarına serbest dolaşımda bulunan işletme ve donatım eşyası teslimi ihracat hükmündedir. || 17-BEYAN.txt | ihracat sayılan teslimlere ilişkin tamamlayıcı beyan izleyen ayın ilk yedi iş günü içinde yapılır. || 42-kumanya.txt | Kaçakçılıkla mücadele eden birimlere bu kapsamda yakıt ve yağ verilir.'),

dict(id='D9-071', cikmis='2024/71', konu='Geri Gelen Eşya', tip='T4', z='OÜ',
 madde='Gümrük Yönetmeliği m.453/3',
 cek='Üç yıllık süre ve ek süreler bitiminde geri getirilmediği tespit edilen geçici ihracat eşyasında ihracat vergilerine tabi eşyadan bu vergiler tahsil edilir.',
 kok=['Gümrük Yönetmeliğine göre, Gümrük Kanununda öngörülen üç yıllık süre ile varsa gümrük idaresince verilen ek süreler bitiminde geri getirilmediği tespit edilen geçici ihracat eşyası hakkında yapılacak işlem aşağıdakilerden hangisidir?'],
 d='İhracat vergilerine tabi eşyadan bu vergiler tahsil edilir.',
 c=['İthalat vergileri usulsüzlük cezasıyla birlikte tahsil edilir.',
    'Eşya kesin ihraç edilmiş sayılarak beyanname kapatılır.',
    'Eşya gümrüğe terk edilmiş sayılır ve tasfiye hükümlerine göre işlem yapılır.',
    'Yükümlüye eşyayı otuz gün içinde getirmesi tebliğ edilir.'],
 tuzak=False,
 g='Geçici ihracat eşyasının üç yıllık süre ile varsa verilen ek süreler bitiminde geri getirilmediği tespit edilirse ihracat vergilerine tabi eşyadan bu vergiler tahsil edilir. Usulsüzlük cezası ve gümrük vergilerinin tahsili ancak eşyanın daha sonra serbest dolaşıma sokulmak istenmesi hâlinde gündeme gelir; geçici ihracatın kesin ihracata dönüşmesi ise kendiliğinden olmayıp kesin ihracat beyannamesi düzenlenmesine bağlıdır. (MD GY 453/3-4)',
 kanit='37-geri gelen eşya.txt | Geçici ihracat eşyasının, Kanunun 168 inci maddesinin birinci fıkrasında belirtilen üç yıllık süre ile varsa gümrük idaresince verilen ek süreler bitiminde geri getirilmediğinin tespit edilmiş olması halinde; ihracat vergilerine tabi eşyadan bu vergiler tahsil edilir. Ancak, eşyanın daha sonra serbest dolaşıma sokulmak istenmesi halinde, birinci fıkra hükümleri uygulanır.'),

dict(id='D9-097', cikmis='2024/97', konu='İhracat', tip='T4', z='OÜ',
 madde='Gümrük Yönetmeliği m.417/1, 417/2',
 cek='İhracat amaçlı geçici depolamada süresinde kaldırılmayan eşya için tebligat yapılır; tebliğden itibaren otuz günde çıkarılmazsa terk sayılır, tasfiye edilir, beyanname iptal edilir.',
 kok=['Gümrük Yönetmeliğine göre, ihracat amacıyla geçici depolama yerine konulan eşyaya ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='Bir aylık süre ve verilen ek süre içinde gümrük işlemleri bitirilerek yerinden kaldırılmayan eşya için yükümlüye tebligat yapılır; tebliğden itibaren otuz gün içinde çıkarılmayan eşya gümrüğe terk edilmiş sayılarak tasfiye edilir ve varsa tescilli beyanname iptal edilir.',
 c=['Bir aylık süre ve verilen ek süre içinde gümrük işlemleri bitirilerek kaldırılmayan eşya için yükümlüye tebligat yapılır; tebliğden itibaren on beş gün içinde çıkarılmayan eşya gümrüğe terk edilmiş sayılır, ancak tescil edilmiş beyanname geçerliliğini korur.',
    'Bir aylık süre içinde kaldırılmayan eşya için ek süre ancak beyanname tescil edilmişse verilebilir ve bu ek süre gümrük ve dış ticaret bölge müdürlüklerince en çok altı aya kadar uzatılabilir.',
    'Bir aylık süre ve verilen ek süre içinde kaldırılmayan eşya, yükümlüye tebligata gerek kalmaksızın gümrüğe terk edilmiş sayılır; eşyaya ilişkin tescilli beyanname ise iptal edilmeyip eşyanın sonraki ihracı için gümrük idaresince kullanılmaya devam edilir.',
    'Bir aylık süre ve ek süre içinde kaldırılmayan eşyanın ihracat beyannamesi re’sen kapatılarak eşya serbest dolaşıma girmiş sayılır ve yükümlüden yalnızca usulsüzlük cezası tahsil edilir.'],
 tuzak=True,
 g='İhracat amacıyla geçici depolama yerine konulan eşya için bir aylık süre ve verilen ek süre içinde işlemleri bitirilerek kaldırılmayan eşyada yükümlüye tebligat yapılır; tebliğden itibaren otuz gün içinde çıkarılmayan eşya gümrüğe terk edilmiş sayılır, tasfiye hükümlerine göre işlem yapılır ve tescilli beyanname varsa iptal edilir. Ek süre beyanname tescil edilip edilmediğine bakılmaksızın talep üzerine gümrük müdürlüklerince en çok üç aya kadar verilir; terk sayılma tebligatsız gerçekleşmez ve beyanname geçerliliğini korumaz. (MD GY 417/1-2)',
 kanit='36-ihracat.txt | Bir aylık süre ve verilen ek süre içinde gümrük işlemleri bitirilerek yerinden kaldırılmayan eşya için gümrük yükümlüsüne tebligat yapılarak, tebliğ tarihinden itibaren otuz gün içinde eşyanın geçici depolama yerinden çıkarılması; aksi takdirde, bu eşyanın gümrüğe terk edilmiş sayılacağı bildirilir. || 36-ihracat.txt | Bu eşyaya ilişkin olarak tescil edilmiş beyanname varsa iptal edilir.'),
]
