# Görev K13 — Gümrük müşavirliği, YGM, disiplin cezaları (Deneme 6–10)
Q = [
# ===================== DENEME 6 (2021) =====================
dict(id='D6-037', cikmis='2021/37', konu='Gümrük Müşavirliği', tip='T1+T2', z='Z',
 madde='Gümrük Yönetmeliği m.563/5, 563/6',
 cek='GM tüzel kişiliğinde dolaylı temsil için AŞ yönetim kurulu üyeleri ve limited şirket müdürleri ortak olmalı; ortak dışı kişilere yalnız sınırlı temsil yetkisi.',
 kok=['Gümrük Yönetmeliğine göre, gümrük müşavirlerince kurulan tüzel kişiliklere ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Tüzel kişiliğin dolaylı temsilci olarak iş takip edebilmesi için limited şirketlerde şirket müdürlerinin şirket ortağı olması gerekir.',
      'II. Tüzel kişiliği temsil ve ilzam etmek üzere şirket ortağı dışındaki üçüncü kişilere sınırlandırılmamış temsil yetkisi verilebilir.',
      'III. Dolaylı temsil yoluyla iş takip edecek anonim şirketlerde yönetim kurulu üyelerinin şirket ortağı olması aranmaz.',
      'IV. Şirketler, hizmet karşılığı elde edecekleri gelirler için hesabına beyanda bulundukları kişi veya kuruluşlara şirketleri adına fatura kesmek zorundadır.',
      'Yukarıdaki ifadelerden hangileri [[yanlıştır]]?'],
 d='II ve III', c=['Yalnız II', 'Yalnız III', 'I ve III', 'II, III ve IV'],
 opts=['Yalnız II', 'Yalnız III', 'I ve III', 'II ve III', 'II, III ve IV'],
 tuzak=False,
 g='Yönetmeliğe göre gümrük müşavirlerince kurulan tüzel kişiliklerin dolaylı temsilci olarak iş takip edebilmesi için anonim şirketlerde yönetim kurulu üyelerinin, limited şirketlerde şirket müdürlerinin şirket ortağı olması gerekir; bu nedenle I doğru, III yanlıştır. Şirket ortağı dışındaki üçüncü kişilere ancak sınırlandırılmış temsil yetkisi verilebileceğinden II yanlıştır; şirketlerin hizmet karşılığı şirketleri adına fatura kesme zorunluluğuna ilişkin IV ise doğrudur. (MD GY 563/5-6)',
 kanit='2-TEMSİL.txt | Gümrük müşavirlerince kurulan tüzel kişiliklerin Kanunun 5 inci maddesine göre dolaylı temsilci olarak iş takip edebilmeleri için anonim şirketlerde yönetim kurulu üyelerinin, limited şirketlerde şirket müdürlerinin şirket ortağı olması gerekir. || 2-TEMSİL.txt | Tüzel kişiliği temsil ve ilzam etmek üzere atanan şirket ortağı dışındaki üçüncü kişilere ancak sınırlandırılmış temsil yetkisi verilebilir. || 2-TEMSİL.txt | Şirketler gördükleri hizmet karşılığında elde edecekleri gelirleri için gümrük beyannamesinde hesabına beyanda bulundukları kişi veya kuruluşlara şirketleri adına fatura kesmek'),

dict(id='D6-048', cikmis='2021/48', konu='YGM', tip='T4', z='Z',
 madde='Yetkilendirilmiş Gümrük Müşavirliği Tebliği m.17/2-b, d; 18/1-2; 24/1-h',
 cek='Önemli olay yaşanmadığı bildirilen günlük rapor için gümrük idaresince onay veya ret işlemi yapılmaz.',
 kok=['Yetkilendirilmiş Gümrük Müşavirliği Tebliğine göre, AN6 ve AN8 tespit işlemleri kapsamında yetkilendirilmiş gümrük müşavirince sunulan günlük rapora ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='Önemli bir olay yaşanmadığı bildirilen günlük rapor için gümrük idaresince onay veya ret işlemi yapılmaz.',
 c=['Günlük rapor, tespit işleminin yapıldığı ayı takip eden ayın ilk yedi iş günü içinde sunulur.',
    'Zorunlu durumlarda günlük raporun ertesi günün sonuna kadar sunulmasına gümrük müdürlüğünce izin verilebilir.',
    'Günlük raporun idareyi yanıltıcı düzenlenmesi hâlinde aylık tek bir usulsüzlük cezası uygulanır.',
    'Sayım tutanaklarıyla uyumsuz bulunan günlük rapor, düzeltilmek üzere en fazla üç defa iade edilebilir.'],
 tuzak=False,
 g='Tebliğe göre günlük raporda herhangi bir önemli olay yaşanmadığının bildirilmesi durumunda gümrük idaresince onay veya ret işlemi yapılmaz. Günlük rapor tespit işleminin yapıldığı günün sonuna kadar sunulur; zorunlu durumlarda ertesi günün sonuna kadar sunulmasına gümrük müdürlüğü değil Gümrük ve Dış Ticaret Bölge Müdürlüğü izin verebilir. Uyumsuz raporlar en fazla iki defa iade edilebilir; yanıltıcı günlük raporda ise her bir rapor için usulsüzlük cezası uygulanır. (MD YGM Tebliği 17/2-d; 18/1-2; 24/1-h)',
 kanit='31-YGM.txt | Günlük raporda herhangi bir önemli olay yaşanmadığının bildirilmesi durumunda gümrük idaresince onay veya ret işlemi yapılmaz. || 31-YGM.txt | Bu raporlar, hata veya uyumsuzluğun düzeltilmesi amacıyla en fazla iki defa iade edilebilir. || 31-YGM.txt | en geç tespit işleminin yapıldığı günü takip eden günün sonuna kadar sunulmasına Gümrük ve Dış Ticaret Bölge Müdürlüğünce izin verilebilir.'),

dict(id='D6-057', cikmis='2021/57', konu='YGM', tip='T1', z='OÜ',
 madde='Yetkilendirilmiş Gümrük Müşavirliği Tebliği m.4',
 cek='YGM Tebliğinde vekil, vekâlet bildirgesinde vekil gösterilen yetkilendirilmiş gümrük müşaviridir; gümrük müşavir yardımcısı vekil olamaz.',
 kok=['Yetkilendirilmiş Gümrük Müşavirliği Tebliğinde yer alan tanımlara göre, Tebliğde geçen kavramlara ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Vekil, Tebliğ kapsamında vekâlet bildirgesinde vekil olarak gösterilmiş olan gümrük müşavir yardımcısıdır.',
 c=['Tespit sözleşmesi, yetkilendirilmiş gümrük müşaviri ile yükümlü arasında özel hukuk hükümlerine istinaden yapılır.',
    'Rehber, Gümrükler Genel Müdürlüğünce yayımlanan yetkilendirilmiş gümrük müşavirliği rehberidir.',
    'Yükümlü, tespit işlemlerini yaptırmak üzere yetkilendirilmiş gümrük müşaviri ile sözleşme imzalayan kişidir.',
    'Yetki numarası, yetkilendirilmiş gümrük müşavirinin tespit ve raporlama işlemlerinde kullandığı numaradır.'],
 tuzak=False,
 g='Tebliğde vekil, yetkilendirilmiş gümrük müşavirinden istenilen vekâlet bildirgesinde vekil olarak gösterilmiş yetkilendirilmiş gümrük müşaviri olarak tanımlanmıştır; gümrük müşavir yardımcısı vekil olamaz. Tespit sözleşmesinin yükümlü ile özel hukuk hükümlerine istinaden yapılması ve rehberin Genel Müdürlükçe yayımlanması tanımlarla uyumludur. (MD YGM Tebliği 4)',
 kanit='31-YGM.txt | Vekil: Bu Tebliğ kapsamında yetkilendirilmiş gümrük müşavirinden istenilen vekâlet bildirgesinde vekil olarak gösterilmiş yetkilendirilmiş gümrük müşavirini,'),

dict(id='D6-076', cikmis='2021/76', konu='Gümrük Müşavirliği', tip='T8', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.225/2; Gümrük Yönetmeliği m.561/4-a, b',
 cek='Özel hukuk tüzel kişisi personeline doğrudan temsilde staj ve sınav aranmaz; SGK bordrosu, temsil belgesi ve Ticaret Sicil Tasdiknamesi olmadan BİLGE kodu verilmez.',
 kok=["(K) Dış Ticaret Limited Şirketi, kanuni temsilcisi olmayan sigortalı çalışanı (L)'yi, şirkete ait eşyanın beyanname imzalama ve tahakkukun tebellüğü dâhil tüm gümrük işlemlerini doğrudan temsil yoluyla takip etmek üzere görevlendirmiştir. (L), Türkiye Cumhuriyeti vatandaşı ve iktisat fakültesi mezunu olup Kanunda gümrük müşavir yardımcıları için sayılan diğer kişisel şartları da taşımaktadır; ancak bir gümrük müşavirinin yanında staj yapmamış ve gümrük müşavir yardımcılığı sınavına girmemiştir. (L), gümrük işlemleri için gerekli BİLGE kullanıcı kodunu almak üzere ilgili gümrük idaresine başvurmuştur.",
      'Gümrük Yönetmeliğine göre bu durumla ilgili aşağıdakilerden hangisi doğrudur?'],
 d="(L)'den staj ve sınav şartları aranmaz; ancak aylık sigorta primleri bordrosu, şirketi temsile yetkili olduğunu gösteren temsil belgesi ve Ticaret Sicil Tasdiknamesi ibraz edilmeden kendisine kullanıcı kodu verilmez.",
 c=["(L) şirketin kanuni temsilcisi olmadığından doğrudan temsil yoluyla iş takibi yapamaz; şirkete ait eşyanın gümrük işlemleri ancak gümrük müşaviri eliyle dolaylı temsil yoluyla takip edilerek sonuçlandırılabilir.",
    "(L)'den staj şartı aranmaz; ancak doğrudan temsil yoluyla iş takibi yapabilmesi için gümrük müşavir yardımcılığı sınavında başarılı olması ve izin belgesi alması zorunludur.",
    "(L), şirket çalışanı olarak yalnızca şirketin taşıdığı eşyanın transit işlemlerini doğrudan temsil yoluyla takip edebilir; beyanname imzalama, tahakkukun tebellüğü ve itiraz gibi işlemleri yapamaz.",
    "(L)'den özel hukuk tüzel kişisi personeli olduğu için Kanunda sayılan şartlar aranmaz; şirketin verdiği noter tasdikli vekâletnamenin ibrazı kullanıcı kodu için yeterlidir."],
 tuzak=True,
 g='Yönetmeliğe göre özel hukuk tüzel kişilerinin doğrudan temsil yoluyla iş takibi yapacak, kanuni temsilci dışındaki personelinde Kanunda sayılan şartlardan yalnız staj ve sınav şartları aranmaz; tüm işlemlerin takibinde SGK aylık sigorta primleri bordrosu, temsil belgesi ve Ticaret Sicil Tasdiknamesinin ibrazı zorunludur ve bu belgeler ibraz edilmezse kullanıcı kodu verilmez. Şirket personeli doğrudan temsil yoluyla iş takip edebileceğinden yalnız dolaylı temsilin mümkün olduğu ifadesi; staj gibi sınav şartı da aranmadığından sınav ve izin belgesinin zorunlu olduğu ifadesi yanlıştır. (MD GK 225/2; GY 561/4-a, b)',
 kanit='2-TEMSİL.txt | Gümrük idarelerinde özel hukuk tüzel kişilerinin doğrudan temsil yoluyla iş takibi yapacak kanuni temsilcileri hariç diğer kişilerde, Kanunun 227 nci maddesinin birinci fıkrasının (g) ve (h) dışındaki bentlerinde sayılan şartlar aranır. || 2-TEMSİL.txt | Belgelerin ibraz edilmemesi veya eksik ibraz edilmesi halinde ilgililere kullanıcı kodu verilmez veya bloke konulur.'),

dict(id='D6-077', cikmis='2021/77', konu='Gümrük Müşavirliği', tip='T5', z='OÜ',
 madde='Gümrük Yönetmeliği m.573/1',
 cek='Sınavı kazananlar belgelerle ilgili Gümrük Müşavirleri Derneğine başvurur; belgelerin teslimini müteakip fotoğraflı izin belgesini Müsteşarlık düzenler.',
 kok=['Gümrük Yönetmeliğine göre; “Sınavda başarı gösteren gümrük müşavirleri ve gümrük müşavir yardımcıları Müsteşarlıkça talep edilen belgelerle birlikte ilgili …… başvurur. Bu belgelerin teslimini müteakip …… tarafından fotoğraflı İzin Belgesi düzenlenir.”',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='Gümrük Müşavirleri Derneğine / Müsteşarlık',
 c=['Gümrük Müşavirleri Derneğine / Başmüdürlük', 'Gümrük ve Muhafaza Başmüdürlüğüne / Müsteşarlık',
    'Gümrük ve Muhafaza Başmüdürlüğüne / Dernek', 'Sınav Kuruluna / Müsteşarlık'],
 tuzak=False,
 g='Yönetmeliğe göre sınavda başarı gösterenler talep edilen belgelerle birlikte ilgili Gümrük Müşavirleri Derneğine başvurur; belgelerin Dernekçe Müsteşarlığa teslimini müteakip fotoğraflı İzin Belgesini Müsteşarlık düzenler. Başvurunun başmüdürlüğe yapıldığını ya da izin belgesinin başmüdürlük veya dernekçe düzenlendiğini içeren eşleşmeler bu nedenle yanlıştır. (MD GY 573/1)',
 kanit='2-TEMSİL.txt | Sınavda başarı gösteren gümrük müşavirleri ve gümrük müşavir yardımcıları Müsteşarlıkça talep edilen belgelerle birlikte ilgili Gümrük Müşavirleri Derneğine başvurur. || 2-TEMSİL.txt | Bu belgelerin Dernek tarafından Müsteşarlığa teslimini müteakip Müsteşarlık tarafından fotoğraflı İzin Belgesi düzenlenir.'),

dict(id='D6-083', cikmis='2021/83', konu='Gümrük Müşavirliği', tip='T1', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.227/1-f, h; 227/2-a, b',
 cek='Gümrük idaresinde 15 yıl çalışıp ayrılanlar staj koşulu aranmaksızın GMY sınavına girer; sınav ve staj birlikte yalnız 3 yılı muayene memurluğu vb. geçenlerde aranmaz.',
 kok=['4458 sayılı Gümrük Kanununa göre gümrük müşavir yardımcısı olabilme koşullarına ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Gümrük idaresinde en az on beş yıl çalışıp istifa ederek veya emekli olarak ayrılan memurlardan diğer koşulları taşıyanlar, sınav koşulu aranmaksızın yalnızca staj yaparak gümrük müşavir yardımcısı olabilirler.',
 c=['Gümrük idaresinde en az on beş yıl çalışıp bunun üç yılını gümrük muayene memuru, gümrük başmemuru veya gümrük müdür yardımcısı görevlerinde geçirerek ayrılanlar sınav ve staj koşulu aranmaksızın gümrük müşavir yardımcısı olabilirler.',
    'Hukuk, iktisat, maliye, işletme, muhasebe, bankacılık, kamu yönetimi, siyasal bilgiler veya endüstri mühendisliği dallarında eğitim veren fakültelerden en az lisans seviyesinde mezun olanlar öğrenim koşulunu sağlar.',
    'Diğer öğretim kurumlarından lisans seviyesinde mezun olduktan sonra Kanunda sayılan bilim dallarından lisansüstü seviyede diploma alanlar da gümrük müşavir yardımcılığı için öğrenim koşulunu sağlamış sayılır.',
    'Gümrük mevzuatı ve gümrüğe ilişkin iktisadi, ticari ve mali konuları kapsayan sınavda başarılı olmak, gümrük müşavir yardımcısı olabilmek için Kanunda aranan koşullar arasında sayılmıştır.'],
 tuzak=False,
 g='Kanuna göre gümrük idaresinde en az on beş yıl çalışıp istifa veya emeklilikle ayrılanlar staj koşulu aranmaksızın gümrük müşavir yardımcısı sınavına girebilir; muaf tutulan staj olup sınav koşulu devam eder. Sınav ve staj koşulunun birlikte aranmaması ise on beş yılın üç yılını gümrük muayene memuru, gümrük başmemuru veya gümrük müdür yardımcısı olarak geçirenlere özgüdür. Lisans ve lisansüstü öğrenim yollarına ilişkin ifadeler Kanundaki öğrenim koşuluyla uyumludur. (MD GK 227/1-f, h; 227/2)',
 kanit='2-TEMSİL.txt | Gümrük idaresinde en az onbeş yıl çalışıp da görevlerinden istifa ederek veya emekli olarak ayrılan memurlardan 1 inci fıkradaki koşulları taşıyanlar, staj koşulu aranmaksızın gümrük müşavir yardımcısı sınavına girebilirler. || 2-TEMSİL.txt | sınav ve staj koşulu aranmaksızın gümrük müşavir yardımcısı olabilirler.'),

dict(id='D6-084', cikmis='2021/84', konu='Gümrük Müşavirliği', tip='T8', z='OÜ',
 madde='Gümrük Yönetmeliği m.563/2',
 cek='GM bilgi-belgelerinde değişiklik yoksa durum her yılın ikinci ayı içinde yazıyla dernekler vasıtasıyla bağlı bulunulan başmüdürlüğe bildirilir.',
 kok=["(L), İzmir'de faaliyet gösteren (K) Gümrük Müşavirliği Limited Şirketinin ortağı olan ve dolaylı temsil yoluyla iş takibi yapan bir gümrük müşaviridir. Şirketin unvanı 2025 yılı mart ayında değişmiş; (L) bu değişikliği öngörülen süre içinde ilgili gümrük müşavirleri derneğine bildirmiş, dernek de söz konusu bilgi ve belgeleri ilgili başmüdürlüğe göndermiştir. Bu tarihten sonra 2025 yılının geri kalanında ve 2026 yılının başında (L)'nin izin belge numarası, şirket adı, şirketi temsile yetkili kişiler ve ticaret sicil gazetesi bilgilerinde herhangi bir değişiklik olmamıştır. (L), bilgi ve belgelerinde değişiklik bulunmadığı için 2026 yılında herhangi bir bildirimde bulunmasına gerek olmadığını düşünmektedir.",
      "Gümrük Yönetmeliğine göre, (L)'nin 2026 yılına ilişkin bildirim yükümlülüğü bakımından aşağıdakilerden hangisi doğrudur?"],
 d='Durumu yılın ikinci ayı içinde dernek vasıtasıyla bağlı bulunduğu başmüdürlüğe yazıyla bildirmelidir.',
 c=['Değişiklik bulunmadığından herhangi bir bildirimde bulunmasına gerek bulunmamaktadır.',
    'Durumu yılın ilk ayı içinde doğrudan Gümrükler Genel Müdürlüğüne elektronik ortamda yazıyla bildirmelidir.',
    'Durumu yılın son ayı içinde dernek vasıtasıyla bağlı bulunduğu başmüdürlüğe yazıyla bildirmelidir.',
    'Durumu yılın ilk haftası içinde yalnızca gümrük müşavirleri derneğine yazıyla bildirmelidir.'],
 tuzak=False,
 g='Yönetmeliğe göre gümrük müşavirlerinin izin belge numarası, şirket adı, temsile yetkili kişiler ve ticaret sicil gazetesi gibi bilgilerinde değişiklik olmayan hâllerde de durum her yılın ikinci ayı içerisinde bir yazı ile gümrük müşavirleri dernekleri vasıtasıyla bağlı bulunulan başmüdürlüğe bildirilir. Bu nedenle değişiklik bulunmadığı için bildirime gerek olmadığı düşüncesi yanlıştır; bir haftalık süre ise değişiklik hâlinde derneğe yapılacak bildirime ilişkindir. (MD GY 563/2)',
 kanit='2-TEMSİL.txt | Değişiklik olmayan hallerde ise durum her yılın ikinci ayı içerisinde bir yazı ile gümrük müşavirleri dernekleri vasıtasıyla bağlı bulunulan başmüdürlüğe bildirilir.'),

dict(id='D6-085', cikmis='2021/85', konu='Gümrük Müşavirliği', tip='T7', z='OÜ',
 madde='Gümrük Yönetmeliği m.565',
 cek='İzin belgesini kaybeden GM/GMY, kayıp ilanlı gazete ve belgelerle ilgili Gümrük Müşavirleri Derneğine dilekçeyle bildirir; yeni belge işlemleri dernekçe yürütülür.',
 kok=['Gümrük Yönetmeliğine göre, izin belgesini kaybeden gümrük müşaviri bu durumu hangi merciye ve ne şekilde bildirir?'],
 d='İlgili Gümrük Müşavirleri Derneğine, kayıp ilanını içeren gazete ile birlikte dilekçeyle',
 c=['Bağlı bulunduğu başmüdürlüğe, kayıp ilanını içeren gazete ile birlikte dilekçeyle',
    'Çalıştığı gümrük müdürlüğüne, kayıp tutanağı ve izin belgesinin örneği ile birlikte yazıyla',
    'Gümrükler Genel Müdürlüğüne, kayıp ilanını içeren gazete ile birlikte elektronik ortamda',
    'Sınav Kuruluna, kayıp ilanını içeren gazete ile birlikte dilekçeyle'],
 tuzak=False,
 g='Yönetmeliğe göre izin belgesini kaybeden gümrük müşavirleri veya yardımcıları, kayıp ilanını içeren gazete ve gerekli belgelerle birlikte ilgili Gümrük Müşavirleri Derneğine dilekçe ile bildirimde bulunur; yeniden izin belgesi düzenlenmesine ilişkin işlemler de dernekler aracılığıyla yürütülür. Başmüdürlüğe veya Gümrükler Genel Müdürlüğüne doğrudan bildirim öngörülmemiştir. (MD GY 565)',
 kanit='2-TEMSİL.txt | izin belgelerini kaybetmeleri halinde, kayıp ilanını içeren gazete ve gerekli belgelerle birlikte ilgili Gümrük Müşavirleri Derneklerine bu durumu dilekçe ile bildirirler. || 2-TEMSİL.txt | Yeniden izin belgesi düzenlenmesi ile ilgili işlemler Dernekler aracılığıyla yürütülür.'),

dict(id='D6-086', cikmis='2021/86', konu='Gümrük Müşavirliği', tip='T3', z='Z',
 madde='Gümrük Müşavirliği ve Yetkilendirilmiş Gümrük Müşavirliği Asgari Ücret Tarifesine İlişkin Tebliğ m.5/1-b, c',
 cek='Aynı şirketten hizmet alan DTSŞ gibi firmaların ihracatında yıllık 1.000 beyanname aşılınca sonrakilere %35, 2.500 aşılınca %50 indirim uygulanabilir.',
 kok=['Gümrük Müşavirliği ve Yetkilendirilmiş Gümrük Müşavirliği Asgari Ücret Tarifesine İlişkin Tebliğe göre, aynı gümrük müşavirliği şirketinden hizmet alınması şartıyla, dış ticaret sermaye şirketlerinin ihracat işlemleri için Asgari Ücret Tarifesinde **%50** oranında indirim hangi durumda uygulanabilir?'],
 d="Bir takvim yılında beyanname sayısı 2.500'ü aştığında, bundan sonraki beyannameler için",
 c=["Bir takvim yılında beyanname sayısı 1.000'i aştığında, bundan sonraki beyannameler için",
    "Bir takvim yılında beyanname sayısı 2.000'i aştığında, bundan sonraki beyannameler için",
    "Bir önceki takvim yılında beyanname sayısı 2.500'ü aşmışsa, takip eden yılın başından itibaren",
    "Bir önceki takvim yılında beyanname sayısı 1.000'i aşmışsa, takip eden yılın başından itibaren"],
 tuzak=False,
 g="Tebliğe göre aynı gümrük müşavirliği şirketinden hizmet alınması şartıyla dış ticaret sermaye şirketi gibi firmaların ihracat işlemlerinde, bir takvim yılında beyanname sayısı 1.000'i aştığında sonraki beyannameler için %35, 2.500'ü aştığında sonraki beyannameler için %50 indirim uygulanabilir. Bir önceki takvim yılındaki ihracat beyanname sayısına bağlı indirim 1.000 için %25, 2.500 için %35'tir; 2.000 eşiği ise ithalat beyannamelerine ilişkindir. (MD Asgari Ücret Tebliği 5/1-c)",
 kanit="51-disiplin cezaları.txt | Bir takvim yılında (b) bendinde belirtilen firmaların ihracat işlemleri için beyanname sayısı 1.000'i aştığında bundan sonraki beyannameler için % 35 oranında; beyanname sayısı 2.500'ü aştığında bundan sonraki beyannameler için % 50 oranında indirim uygulanabilir. || 51-disiplin cezaları.txt | Bir önceki takvim yılında, bir firma tarafından tescil ettirilen ihracat beyanname sayısının 1000'i aşmış olması halinde, Asgari Ücret Tarifesinde % 25 oranında; 2.500'ü aşmış olması halinde % 35 oranında indirim"),

dict(id='D6-087', cikmis='2021/87', konu='YGM', tip='T5', z='OÜ',
 madde='Yetkilendirilmiş Gümrük Müşavirliği Tebliği m.11/1-c, d, ğ',
 cek='YGM tespit kodları: GKAİ ibra tespiti GK1, DİR izin süre uzatımına esas tespit DR1, beyannamede düzeltme ön incelemesi BD1.',
 kok=['Yetkilendirilmiş Gümrük Müşavirliği Tebliğine göre; gümrük kontrolü altında işleme rejimi kapsamında ibra işleminin tespiti …… kodlu, dâhilde işleme rejimi kapsamındaki eşyaya verilen izinlerle ilgili süre uzatımlarına esas teşkil edecek işlemlerin tespiti …… kodlu, Gümrük Kanunu uyarınca beyannamede yapılacak düzeltme işlemlerinin rehberde yer alan usul ve esaslar dikkate alınarak ön incelemesi ise …… kodlu tespit işlemi kapsamındadır.',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='GK1 – DR1 – BD1',
 c=['GK2 – DR1 – BD1', 'GK1 – DR2 – BD1', 'GK1 – DR1 – ZD1', 'GC1 – DR2 – BD1'],
 tuzak=False,
 g='Tebliğe göre gümrük kontrolü altında işleme rejiminde ibra işleminin tespiti GK1, dâhilde işleme izinlerinin süre uzatımına esas işlemlerin tespiti DR1, beyannamede yapılacak düzeltme işlemlerinin ön incelemesi BD1 kodludur. GK2 ithal edilen ürünün nihai ürün içindeki miktarının, DR2 eşyanın işlem görmüş ürün bünyesinde kullanılıp kullanılmadığının tespitine, ZD1 ise çok zor durum tespitine ilişkindir. (MD YGM Tebliği 11/1-c, d, ğ)',
 kanit='31-YGM.txt | GK1, gümrük kontrolü altında işleme rejimi kapsamında ibra işleminin tespitini, || 31-YGM.txt | DR1, dâhilde işleme rejimi kapsamındaki eşyaya verilen izinlerle ilgili süre uzatımlarına esas teşkil edecek işlemlerin tespitini, || 31-YGM.txt | BD1, Gümrük Kanununun 73 üncü maddesinin ikinci fıkrası uyarınca beyannamede yapılacak düzeltme işlemlerinin, rehberde yer alan usul ve esaslar dikkate alınarak ön incelemesini kapsar.'),

# ===================== DENEME 7 (2022) =====================
dict(id='D7-063', cikmis='2022/63', konu='Gümrük Müşavirliği', tip='T2', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.227/1-d',
 cek='GMY engel suç listesinde terörün finansmanı ve ihaleye fesat karıştırma vardır; listede olmayan kasten yaralama (iki yıl hapis) ve hakaret engel değildir.',
 kok=['4458 sayılı Gümrük Kanununda gümrük müşavir yardımcısı olabilecek kişilerin hüküm giymemiş olması gereken suçlara ilişkin olarak aşağıdaki durumlar veriliyor:',
      'I. Terörün finansmanı suçundan hüküm giymiş olmak',
      'II. Kasten yaralama suçundan iki yıl hapis cezasına hüküm giymiş olmak',
      'III. Resmî ihale ve alım satımlara fesat karıştırma suçundan hüküm giymiş olmak',
      'IV. Hakaret suçundan adli para cezasına hüküm giymiş olmak',
      'Yukarıdaki durumlardan hangileri gümrük müşavir yardımcısı olmaya engel teşkil eder?'],
 d='I ve III', c=['II ve IV', 'III ve IV', 'I, II ve III', 'I, III ve IV'],
 opts=['I ve III', 'II ve IV', 'III ve IV', 'I, II ve III', 'I, III ve IV'],
 tuzak=False,
 g='Kanunda gümrük müşavir yardımcısı olmaya engel suçlar sınırlı olarak sayılmış olup terörün finansmanı ile resmî ihale ve alım satımlara fesat karıştırma bu suçlar arasındadır; bu nedenle I ve III engel teşkil eder. Kasten yaralama ve hakaret listede yer almadığı gibi verilen cezalar ağır hapis veya beş yıldan fazla hapis cezası da olmadığından II ve IV engel değildir. (MD GK 227/1-d)',
 kanit='2-TEMSİL.txt | resmi ihale ve alım satımlara fesat karıştırma, suçtan kaynaklanan malvarlığı değerlerini aklama, terörün finansmanı, Devlet sırlarını açığa vurma || 2-TEMSİL.txt | ağır hapis veya beş yıldan fazla hapis ya da kaçakçılık'),

dict(id='D7-064', cikmis='2022/64', konu='Disiplin', tip='T3', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu geçici m.6/9',
 cek='Tedbiren izin belgesi alınması gerekçesiyle birlikte, izin belgesinin alınmasını izleyen günde Bakanlığa bildirilir.',
 kok=['4458 sayılı Gümrük Kanununa göre, mevzuata aykırı hareketleri görülen gümrük müşavirinin izin belgesinin tedbir mahiyetinde geçici olarak alınması durumu, gerekçesiyle birlikte ne zaman ve nereye bildirilir?'],
 d='İzin belgesinin alınmasını izleyen günde Bakanlığa',
 c=['İzin belgesinin alınmasını izleyen günde başmüdürlüğe',
    'İzin belgesinin alındığı hafta içinde Bakanlığa',
    'İzin belgesinin alınmasından itibaren bir hafta içinde Bakanlığa',
    'İzin belgesinin alınmasından itibaren otuz gün içinde Bakanlığa'],
 tuzak=False,
 g='Kanuna göre mevzuata aykırı hareketleri görülen gümrük müşavirleri ve yardımcılarının izin belgeleri Bakanlık müfettişleri ile gümrük ve dış ticaret bölge müdürlerince tedbir mahiyetinde geçici olarak alınabilir ve bu durum gerekçesiyle birlikte izin belgesinin alınmasını izleyen günde Bakanlığa bildirilir. Bildirim başmüdürlüğe yapılmaz; bir haftalık veya otuz günlük bir süre de öngörülmemiştir. (MD GK Geçici 6/9)',
 kanit='51-disiplin cezaları.txt | Bu durum, gerekçesiyle birlikte izin belgesinin alınmasını izleyen günde Bakanlığa bildirilir.'),

dict(id='D7-067', cikmis='2022/67', konu='YGM', tip='T6', z='OÜ',
 madde='Yetkilendirilmiş Gümrük Müşavirliği Tebliği m.11/1-a',
 cek='Antreponun devir işlemlerinin mevzuata uygunluğunun incelenmesi AN5 kodlu YGM tespit işlemidir.',
 kok=['Yetkilendirilmiş Gümrük Müşavirliği Tebliğine göre, “Gümrük Yönetmeliği çerçevesinde antreponun devir işlemlerinin mevzuata uygunluğunun incelenmesi” şeklinde tanımlanan tespit işleminin kodu aşağıdakilerden hangisidir?'],
 d='AN5', c=['AN1', 'AN3', 'AN4', 'AN9'],
 tuzak=False,
 g='Tebliğe göre Gümrük Yönetmeliği çerçevesinde antreponun devir işlemlerinin mevzuata uygunluğunun incelenmesi AN5 kodlu tespit işlemidir. AN1 antreponun açılmasına, AN3 tadilatlara, AN4 adres değişikliğine ilişkin başvuru dosyalarının ön incelemesini; AN9 ise antrepo rejimine tabi eşyanın elleçleme işlemlerinin tespitini ifade eder. (MD YGM Tebliği 11/1-a)',
 kanit='31-YGM.txt | AN5, Gümrük Yönetmeliğinin 523 üncü maddesi çerçevesinde antreponun devir işlemlerinin mevzuata uygunluğunun incelenmesini,'),

dict(id='D7-087', cikmis='2022/87', konu='Gümrük Müşavirliği', tip='T2', z='Z',
 madde='Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2) m.5/2-3, 6/3',
 cek='Dolaylı temsilci sorumlu ise ek tahakkuk her birine ayrı ve tüzel kişiliğe de tebliğ edilir; OKS/YYS veya teslimden önce tebliğde temsilciye tebligat yapılmaz.',
 kok=["Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2)'ye göre, dolaylı temsilci gümrük müşavirinin sorumluluğunun tespit edildiği durumlarda yapılacak tebligata ilişkin aşağıdaki ifadeler veriliyor:",
      'I. Ek tahakkuk, müştereken ve müteselsilen sorumlu yükümlülerin her birine ayrı ayrı tebliğ edilir.',
      'II. Gümrük müşaviri tüzel kişilik bünyesinde faaliyet gösteriyorsa gelir eksiği ilgili tüzel kişiliğe de tebliğ edilir.',
      'III. Asıl yükümlünün yetkilendirilmiş yükümlü sertifikası varsa dolaylı temsile yetkili kişilere de ayrıca tebligat yapılır.',
      'IV. Ek tahakkuk eşyanın tesliminden sonra asıl yükümlüye tebliğ edilmişse dolaylı temsilciye ayrıca tebligat yapılmaz.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I ve II', c=['Yalnız I', 'Yalnız II', 'I ve IV', 'I, II ve IV'],
 opts=['Yalnız I', 'Yalnız II', 'I ve II', 'I ve IV', 'I, II ve IV'],
 tuzak=False,
 g='Tebliğe göre aynı vergilerden birden çok yükümlünün müştereken ve müteselsilen sorumlu olduğu tespit edildiğinde ek tahakkuk her birine ayrı ayrı tebliğ edilir; gümrük müşaviri tüzel kişilik bünyesinde faaliyet gösteriyorsa gelir eksiği o tüzel kişiliğe de tebliğ edilir, bu nedenle I ve II doğrudur. Asıl yükümlünün onaylanmış kişi statü belgesine veya yetkilendirilmiş yükümlü sertifikasına sahip olması ya da ek tahakkukun eşyanın tesliminden önce asıl yükümlüye tebliğ edilmiş olması hâlinde dolaylı temsilciye ayrıca tebligat yapılmaz; III ve IV yanlıştır. (MD Tahsilat Tebliği 5/2-3; 6/3)',
 kanit='45-tebliğ.txt | Aynı gümrük vergilerinin ödenmesinden birden çok yükümlünün müştereken ve müteselsilen sorumlu olduğunun tespiti halinde, ek tahakkuk bu kişilerin her birine ayrı ayrı tebliğ edilir. || 45-tebliğ.txt | gümrük müşavirinin bir tüzel kişilik bünyesinde faaliyet göstermesi halinde, gelir eksiği ilgili tüzel kişiliğe de tebliğ edilir. || 45-tebliğ.txt | Eşyanın tesliminden önce ek tahakkukun asıl yükümlüye tebliğ edilmiş olması, || 45-tebliğ.txt | hallerinde dolaylı temsile yetkili kişilere ayrıca tebligat yapılmaz.'),

dict(id='D7-100', cikmis='2022/100', konu='Gümrük Müşavirliği', tip='T1+T2', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.5, 225/1-2',
 cek='Dolaylı temsilde temsilci kendi adına, başkası hesabına hareket eder; yetkisiz temsil beyan eden kendi adına ve hesabına hareket ediyor sayılır.',
 kok=['4458 sayılı Gümrük Kanununa göre, gümrük idarelerinde temsil ve iş takibine ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Gerçek kişinin doğrudan temsil yoluyla iş takibi, geçerli vekâletnameye istinaden ticari miktar ve mahiyet arz etmeyen eşyanın ve özel kullanıma mahsus taşıt araçlarının gümrük işlemleri ile ilgili olarak mümkündür.',
      'II. Dolaylı temsil durumunda temsilci, başkasının adına ancak kendi hesabına hareket eder.',
      'III. Devlet, belediye, il özel idareleri ve diğer kamu tüzel kişilerinin amir ve memurları tüm gümrük işlemlerini doğrudan temsil yoluyla takip edebilirler.',
      'IV. Temsil yetkisine sahip olmadığı hâlde başka bir kişi adına hareket ettiğini beyan eden kişi, adına hareket ettiğini beyan ettiği kişinin hesabına hareket ediyor sayılır.',
      'V. Transit taşımacılık yapan veya arızi olarak beyanda bulunan kişiler hariç olmak üzere, temsilci Türkiye Gümrük Bölgesinde yerleşik bulunan kişilerdir.',
      'Yukarıdaki ifadelerden hangileri [[yanlıştır]]?'],
 d='II ve IV', c=['Yalnız II', 'I ve IV', 'II ve III', 'II, IV ve V'],
 opts=['Yalnız II', 'I ve IV', 'II ve III', 'II ve IV', 'II, IV ve V'],
 tuzak=False,
 g='Kanuna göre dolaylı temsilde temsilci kendi adına ancak başkasının hesabına hareket eder; başkasının adına ve hesabına hareket etmek doğrudan temsildir, bu nedenle II yanlıştır. Temsil yetkisi olmadığı hâlde başkası adına veya hesabına hareket ettiğini beyan eden kişi kendi adına ve kendi hesabına hareket ediyor sayılacağından IV de yanlıştır. Gerçek kişinin doğrudan temsille iş takibine, kamu görevlilerinin doğrudan temsiline ve temsilcinin yerleşikliğine ilişkin I, III ve V doğrudur. (MD GK 5; 225/1-2)',
 kanit='2-TEMSİL.txt | Dolaylı temsil durumunda ise kendi adına, ancak başkasının hesabına hareket eder. || 2-TEMSİL.txt | başka bir kişi adına ya da hesabına hareket ettiğini beyan eden kişi, kendi adına ve kendi hesabına hareket ediyor sayılır. || 2-TEMSİL.txt | Gerçek kişinin doğrudan temsil yoluyla iş takibi, geçerli vekaletnameye istinaden ticari miktar ve mahiyet arz etmeyen eşyanın ve özel kullanıma mahsus taşıt araçlarının gümrük işlemleri ile ilgili olarak mümkündür.'),

# ===================== DENEME 8 (2023) =====================
dict(id='D8-023', cikmis='2023/23', konu='YGM', tip='T3', z='OÜ',
 madde='Yetkilendirilmiş Gümrük Müşavirliği Tebliği m.22/1-c',
 cek='YGM tespit raporlarını, eklerini, günlük rapor ve tespit sözleşmelerini istenildiğinde ibraz etmek üzere beş yıl süreyle muhafaza eder.',
 kok=['Yetkilendirilmiş Gümrük Müşavirliği Tebliğine göre, tespit raporları ve dayanağı belgeler ne kadar süreyle muhafaza edilir?'],
 d='İstenildiğinde ibraz edilmek üzere beş yıl süreyle',
 c=['İstenildiğinde ibraz edilmek üzere üç yıl süreyle', 'İstenildiğinde ibraz edilmek üzere on yıl süreyle',
    'Yetki belgesinin geçerlilik süresi boyunca', 'Tespit sözleşmesinin yürürlükte kaldığı süre boyunca'],
 tuzak=False,
 g='Tebliğe göre yetkilendirilmiş gümrük müşavirleri; hazırladıkları tespit raporlarını ve eklerini, bunlara dayanak olan günlük rapor ve tespit sözleşmelerini ve tespit işleminde kullanılan diğer bilgi ve belgeleri istenildiğinde ibraz etmek üzere beş yıl süreyle muhafaza etmekten sorumludur. Muhafaza süresi yetki belgesinin veya tespit sözleşmesinin süresine bağlanmamış olup üç ya da on yıllık bir süre de öngörülmemiştir. (MD YGM Tebliği 22/1-c)',
 kanit='31-YGM.txt | Hazırlanan her türlü tespit raporunu ve eklerini, bunlara dayanak olan günlük rapor ve tespit sözleşmelerini, tespit işleminde kullanılan diğer tüm bilgi ve belgeleri istenildiğinde ibraz etmek üzere beş yıl süreyle muhafaza etmek,'),

dict(id='D8-024', cikmis='2023/24', konu='Disiplin', tip='T2', z='Z',
 madde='4458 sayılı Gümrük Kanunu geçici m.6/4, 6/6, 6/7, 6/9',
 cek='Adli kovuşturmada disiplin cezası TCK zamanaşımına göre verilir; görev suçlarında TCK memur hükümleri uygulanır; tedbiren alma yetkisi müfettiş ve bölge müdüründedir.',
 kok=['4458 sayılı Gümrük Kanununa göre, gümrük müşavirleri hakkında uygulanacak disiplin ve ceza hükümlerine ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Aykırılık aynı zamanda adli kovuşturma konusu ise disiplin cezası Türk Ceza Kanunundaki zamanaşımı hükümlerine göre verilebilir.',
      'II. Üç yıllık dönemde iki veya daha fazla disiplin cezasını gerektiren davranışta bulunana her yeni suçu için daha hafif ceza uygulanır.',
      'III. Görevleri sebebiyle işledikleri suçlardan dolayı Türk Ceza Kanununun Devlet memurlarına ait hükümleri uyarınca cezalandırılırlar.',
      'IV. İzin belgelerini tedbiren geçici olarak almaya Bakanlık müfettişleri ile gümrük ve dış ticaret bölge müdürleri yetkilidir.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I, III ve IV', c=['I ve III', 'III ve IV', 'I, II ve III', 'I, II ve IV'],
 opts=['I ve III', 'III ve IV', 'I, II ve III', 'I, II ve IV', 'I, III ve IV'],
 tuzak=False,
 g='Kanuna göre aykırılık aynı zamanda adli kovuşturma konusu ise disiplin cezası Türk Ceza Kanununda öngörülen zamanaşımı hükümlerine göre verilebilir (I); meslek mensupları görevleri sırasında veya sebebiyle işledikleri suçlardan dolayı Türk Ceza Kanununun Devlet memurlarına ait hükümleri uyarınca cezalandırılır (III); izin belgelerini tedbiren almaya Bakanlık müfettişleri ile gümrük ve dış ticaret bölge müdürleri yetkilidir (IV). Üç yıllık dönemde iki veya daha fazla disiplin cezasını gerektiren davranışta bulunana her yeni suçu için bir öncekinden daha ağır ceza uygulanabileceğinden II yanlıştır. (MD GK Geçici 6/4, 6/6, 6/7, 6/9)',
 kanit='51-disiplin cezaları.txt | Mevzuata aykırı işlem ve eylemlerin aynı zamanda bir adli kovuşturma konusu olması halinde, bu aykırılık için Türk Ceza Kanununda öngörülen zamanaşımı hükümlerine göre disiplin cezası verilebilir. || 51-disiplin cezaları.txt | Üç yıllık bir dönem içinde iki veya daha fazla disiplin cezasını gerektiren davranışta bulunan meslek mensubuna, her yeni suçu için bir öncekinden daha ağır ceza uygulanabilir. || 51-disiplin cezaları.txt | Türk Ceza Kanununun Devlet memurlarına ait hükümleri uyarınca cezalandırılır. || 51-disiplin cezaları.txt | Bakanlık müfettişleri ve gümrük ve dış ticaret bölge müdürleri tarafından gerek görülmesi hâlinde tedbir mahiyetinde'),

dict(id='D8-025', cikmis='2023/25', konu='Disiplin', tip='T8', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu geçici m.6/3',
 cek='Sahte belgeyle yanlış beyan GM bilgisi dışında ama araştırmayla öğrenilebilir ise ilk defasında kınama, tekerrüründe geçici alıkoyma cezası verilir.',
 kok=["Gümrük müşaviri (L)'nin, (K) firması hesabına dolaylı temsil yoluyla verdiği serbest dolaşıma giriş beyannamesine eklenen faturanın sahte olduğu sonradan anlaşılmıştır. Merkez denetim elemanlarınca düzenlenen raporda; sahte belgeye dayanılarak yanlış beyanda bulunulduğu, bu durumun (L)'nin bilgisi dışında olduğu, ancak bir araştırma sonucunda gerçek durumun öğrenilebileceği tespit edilmiştir. (L) hakkında daha önce bu nitelikte bir tespit bulunmamaktadır.",
      "4458 sayılı Gümrük Kanununa göre (L) hakkında uygulanacak disiplin cezasına ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="(L)'ye ilk defasında kınama cezası verilir; sahte belgeye dayalı yanlış beyan durumunun tekerrür etmesi hâlinde ise (L) hakkında geçici olarak mesleki faaliyetten alıkoyma cezası uygulanır.",
 c=["(L)'ye ilk defasında yazılı olarak uyarma cezası verilir; sahte belgeye dayalı yanlış beyan durumunun tekerrür etmesi hâlinde ise (L) hakkında kınama cezası uygulanır.",
    "(L)'nin bilgisi dışında gerçekleşen yanlış beyan nedeniyle (L) hakkında disiplin cezası uygulanamaz; ancak aynı durumun tekerrürü hâlinde (L)'ye ilk defa olarak kınama cezası verilir.",
    "(L)'ye ilk defasında geçici olarak mesleki faaliyetten alıkoyma cezası verilir; bu durumun tekerrür etmesi hâlinde ise (L) hakkında doğrudan meslekten çıkarma cezası uygulanır.",
    "(L)'ye sahte belgeye dayanılmış olması nedeniyle doğrudan meslekten çıkarma cezası verilir ve izin belgesi geri alınarak bu mesleği bir daha icra etmesine izin verilmez."],
 tuzak=True,
 g='Kanuna göre sahte belgelere dayanılarak yanlış beyanda bulunulduğunun, bu durumun gümrük müşavirinin bilgisi dışında olduğunun, ancak bir araştırma sonucunda gerçek durumun öğrenilebileceğinin merkez denetim elemanlarınca rapora bağlandığı durumlarda ilk defasında kınama, tekerrüründe geçici olarak mesleki faaliyetten alıkoyma cezası verilir. İlk defasında uyarma, tekrarında kınama sıralaması mesleki kurallara aykırı fiillere; meslekten çıkarma ise kaçakçılık suçundan mahkûmiyeti kesinleşenlere ilişkindir. (MD GK Geçici 6/3)',
 kanit='51-disiplin cezaları.txt | Sahte belgelere dayanılarak yanlış beyanda bulunulduğunun, ancak bu durumun gümrük müşavirinin bilgisi dışında olduğunun, bununla birlikte, bir araştırma sonucunda gerçek durumun öğrenilebileceğinin || 51-disiplin cezaları.txt | ilgili gümrük müşavirine ilk defasında kınama cezası verilir. Bu hususun tekerrür etmesi halinde geçici olarak mesleki faaliyetten alıkoyma cezası uygulanır.'),

dict(id='D8-026', cikmis='2023/26', konu='YGM', tip='T3', z='OÜ',
 madde='Gümrük Yönetmeliği m.576/3-d',
 cek='Bakanlık sayfasında yayımlanan YGM adres, telefon, e-posta bilgilerindeki değişiklik yedi gün içinde güncellenmek üzere Bakanlığa bildirilir.',
 kok=['Gümrük Yönetmeliğine göre, Bakanlık internet sayfasında yayımlanan yetkilendirilmiş gümrük müşavirine ait faaliyet adresi, telefon ve e-posta bilgilerinde değişiklik olması durumunda bildirim hangi süre içinde ve nereye yapılır?'],
 d='Yedi gün içerisinde, bilgilerin sistem aracılığıyla güncellenmesi için Bakanlığa',
 c=['Bir ay içerisinde, bilgilerin sistem aracılığıyla güncellenmesi için Bakanlığa',
    'On iş günü içerisinde, bilgilerin sistem aracılığıyla güncellenmesi için Bakanlığa',
    'Yedi gün içerisinde, gümrük müşavirleri derneği vasıtasıyla bağlı bulunulan başmüdürlüğe',
    'Her yılın ikinci ayı içerisinde, gümrük müşavirleri derneği vasıtasıyla başmüdürlüğe'],
 tuzak=False,
 g='Yönetmeliğe göre yetkilendirilmiş gümrük müşavirinin adı-soyadı, tüzel kişi ticaret unvanı, faaliyet adresi, telefon ve e-posta bilgileri Bakanlık internet sayfasında yayımlanır; bu bilgilerde değişiklik olması durumunda yedi gün içerisinde, bilgilerin sistem aracılığıyla güncellenmesi için Bakanlığa bildirimde bulunulur. Dernek vasıtasıyla başmüdürlüğe bildirim ve yılın ikinci ayı kuralı gümrük müşavirlerinin bilgi ve belgelerine ilişkindir; on iş günlük süre ise Yükümlü Kayıt ve Takip Sistemindeki güncellemeye aittir. (MD GY 576/3-d)',
 kanit='31-YGM.txt | Bu bilgilerde herhangi bir değişiklik olması durumunda, yedi gün içerisinde bilgilerin sistem aracılığıyla güncellenmesi için Bakanlığa bildirimde bulunulur.'),

dict(id='D8-027', cikmis='2023/27', konu='Disiplin', tip='T1', z='Z',
 madde='4458 sayılı Gümrük Kanunu geçici m.6/2-3; Gümrük Yönetmeliği m.578/3; Asgari Ücret Tarifesine İlişkin Tebliğ m.5/1-g',
 cek='Geçici olarak mesleki faaliyetten alıkoyma cezasında mesleki sıfat saklı kalır; ceza süresince sıfatın kaldırılması öngörülmez.',
 kok=['Gümrük mevzuatına göre meslek mensuplarına uygulanacak disiplin cezalarına ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Geçici olarak mesleki faaliyetten alıkoyma cezası, ceza süresince meslek mensubunun mesleki sıfatının da kaldırılması şartıyla mesleki faaliyetten alıkonulmasını ifade eden disiplin cezasıdır.',
 c=['Görevini bağımsızlık, tarafsızlık ve dürüstlükle yapmayan veya kusurlu olarak yapan ya da mesleğin genel prensiplerine aykırı harekette bulunan meslek mensupları için geçici olarak mesleki faaliyetten alıkoyma cezası uygulanır.',
    'Disiplin cezaları, gümrük müşavirliği hizmetlerinin gereği gibi yürütülmesi amacıyla durumun niteliğine ve ağırlık derecesine göre mesleğin vakar ve onuruna aykırı hareket eden meslek mensuplarına verilir.',
    'Yetkilendirilmiş gümrük müşavirinin yetki belgesinin geri alınması, ayrıca Gümrük Kanunu uyarınca meslek mensubu hakkında disiplin cezası verilmesine engel teşkil etmez.',
    'Asgari Ücret Tarifesi altında hizmet veren gümrük müşavirine, disiplin cezası hükümleri saklı kalmak kaydıyla her beyanname itibarıyla usulsüzlük cezası uygulanır ve aynı ceza yükümlüye de ayrıca uygulanır.'],
 tuzak=False,
 g='Kanuna göre geçici olarak mesleki faaliyetten alıkoyma, mesleki sıfatı saklı kalmak şartıyla meslek mensubunun mesleki faaliyetten alıkonulmasıdır; ceza süresince mesleki sıfatın kaldırılması söz konusu değildir. Bağımsızlık, tarafsızlık ve dürüstlük ilkelerine aykırılıkta geçici alıkoyma uygulanacağı, yetki belgesinin geri alınmasının disiplin cezasına engel olmadığı ve asgari ücret altında hizmette disiplin hükümleri saklı kalmak üzere usulsüzlük cezası uygulanacağı ifadeleri mevzuata uygundur. (MD GK Geçici 6/2-3; GY 578/3; Asgari Ücret Tebliği 5/1-g)',
 kanit='51-disiplin cezaları.txt | Geçici olarak mesleki faaliyetten alıkoyma: Mesleki sıfatı saklı kalmak şartıyla || 31-YGM.txt | Yetkilendirilmiş gümrük müşavirlerinin yetki belgesinin geri alınması, ayrıca Kanunun geçici 6 ncı maddesi uyarınca disiplin cezası verilmesine engel teşkil etmez. || 51-disiplin cezaları.txt | disiplin cezası hükümleri saklı kalmak kaydıyla, her beyanname itibarıyla işlemi yapan gümrük müşavirine ve yükümlülere ayrı ayrı olmak üzere'),

dict(id='D8-028', cikmis='2023/28', konu='Disiplin', tip='T3', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu geçici m.6/5',
 cek='Yetkili disiplin kurulu savunma için on günden az olmayan süre verir; bu sürede savunma yapmayan savunma hakkından vazgeçmiş sayılır.',
 kok=['4458 sayılı Gümrük Kanununa göre, yetkili disiplin kurulunun meslek mensubuna savunması için vereceği süre **en az** kaç gündür?'],
 d='10 gün', c=['7 gün', '15 gün', '30 gün', '60 gün'], opts=['7 gün', '10 gün', '15 gün', '30 gün', '60 gün'],
 tuzak=False,
 g='Kanuna göre meslek mensubu hakkında savunması alınmadan disiplin cezası verilemez; yetkili disiplin kurulunun on günden az olmamak üzere verdiği süre içinde savunma yapmayanlar savunma hakkından vazgeçmiş sayılır. Yedi gün bu alt sınırın altında kalır; on beş, otuz ve altmış günlük süreler ise savunma için öngörülmemiştir. (MD GK Geçici 6/5)',
 kanit='51-disiplin cezaları.txt | Yetkili disiplin kurulunun on günden az olmamak üzere verdiği süre içinde savunma yapmayanlar, savunma hakkından vazgeçmiş sayılırlar.'),

dict(id='D8-032', cikmis='2023/32', konu='YGM', tip='T5', z='Z',
 madde='Yetkilendirilmiş Gümrük Müşavirliği Tebliği m.13/1-ı',
 cek='Genel antrepoda AN7, AN8, AN9; özel antrepoda AN6, AN7, AN9 tespit işlemlerinin aynı YGM tarafından yapılması zorunludur.',
 kok=['Yetkilendirilmiş Gümrük Müşavirliği Tebliğine göre; “Genel antrepolarda …… tespit işlemleri, özel antrepolarda ise …… tespit işlemlerinin aynı yetkilendirilmiş gümrük müşavirince yapılması zorunludur.”',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='AN7, AN8 ve AN9 – AN6, AN7 ve AN9',
 c=['AN6, AN7 ve AN9 – AN7, AN8 ve AN9', 'AN7, AN8 ve AN9 – AN6, AN8 ve AN9',
    'AN6, AN8 ve AN9 – AN6, AN7 ve AN9', 'AN7, AN8 ve AN9 – AN6, AN7, AN8 ve AN9'],
 tuzak=False,
 g='Tebliğe göre genel antrepolarda AN7, AN8 ve AN9, özel antrepolarda ise AN6, AN7 ve AN9 tespit işlemlerinin aynı yetkilendirilmiş gümrük müşavirince yapılması zorunludur; bunlar dışındaki tespitler için yükümlü aynı veya başka bir müşavirle sözleşme yapabilir. AN8 genel antrepoya, AN6 özel antrepoya eşya giriş çıkışına ilişkin olduğundan bu kodların yer değiştirildiği eşleşmeler yanlıştır. (MD YGM Tebliği 13/1-ı)',
 kanit='31-YGM.txt | Genel antrepolarda AN7, AN8 ve AN9 tespit işlemleri, özel antrepolarda ise AN6, AN7 ve AN9 tespit işlemlerinin aynı yetkilendirilmiş gümrük müşavirince yapılması zorunludur.'),

dict(id='D8-082', cikmis='2023/82', konu='YGM', tip='T1+T2', z='Z',
 madde='Gümrük Yönetmeliği m.575/3-a, c, d, e',
 cek="YGM yanındaki yardımcının hukuki ve mali sorumluluğu YGM'ye aittir; işlerini başkasına yaptıran yardımcı iki yıl YGM yanında çalıştırılamaz.",
 kok=['Gümrük Yönetmeliğine göre, yetkilendirilmiş gümrük müşaviri yanında çalışan gümrük müşavir yardımcılarına ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Yaptıkları işlemlerden doğacak hukuki ve mali sorumluluk, şahsi sorumlulukları saklı kalmak üzere kendilerine aittir.',
      'II. Yapmaları gereken işleri başkasına yaptırdığı tespit edilenler beş yıl süreyle yetkilendirilmiş gümrük müşaviri yanında çalıştırılamaz.',
      'III. Çalıştıkları müşavir adına antrepo giriş-çıkış işlemleri ve elleçlemelere ilişkin sayım tutanaklarını imzalayabilirler.',
      'IV. Hizmet veremedikleri zorunlu durumlarda, otuz günle sınırlı olmak şartıyla müşavirin ortak olduğu firmada çalışan başka bir yardımcı görevlendirilebilir.',
      'Yukarıdaki ifadelerden hangileri [[yanlıştır]]?'],
 d='I ve II', c=['I ve IV', 'II ve III', 'I, II ve III', 'I, II ve IV'],
 opts=['I ve II', 'I ve IV', 'II ve III', 'I, II ve III', 'I, II ve IV'],
 tuzak=False,
 g='Yönetmeliğe göre yetkilendirilmiş gümrük müşaviri yanında çalışan gümrük müşavir yardımcılarının yaptıkları işlemlerden doğacak hukuki ve mali sorumluluk, şahsi sorumlulukları saklı kalmak üzere yanlarında çalıştıkları yetkilendirilmiş gümrük müşavirine aittir; I yanlıştır. İşlerini başkasına yaptırdığı tespit edilenler beş yıl değil iki yıl süreyle yetkilendirilmiş gümrük müşaviri yanında çalıştırılamaz; II de yanlıştır. Sayım tutanaklarını imzalama ve zorunlu durumlarda otuz günle sınırlı görevlendirmeye ilişkin III ve IV doğrudur. (MD GY 575/3)',
 kanit='31-YGM.txt | Yaptıkları işlemlerden doğacak şahsi sorumlulukları saklı kalmak üzere, hukuki ve mali sorumluluk yanlarında çalıştıkları yetkilendirilmiş gümrük müşavirine aittir. || 31-YGM.txt | Yapmaları gereken iş ve işlemleri başkasına yaptıramaz. Bu şekilde davrandığı tespit edilenler 2 yıl süreyle || 31-YGM.txt | Hizmet veremediği zorunlu durumlarda otuz gün süre ile sınırlı olmak şartıyla yetkilendirilmiş gümrük müşavirinin ortak olduğu firmada çalışan bir başka gümrük müşavir yardımcısı görevlendirilebilir.'),

dict(id='D8-089', cikmis='2023/89', konu='Gümrük Müşavirliği', tip='T5', z='OÜ',
 madde='Gümrük Yönetmeliği m.561/2; 4458 sayılı Gümrük Kanunu m.225/1',
 cek='Posta ve hızlı kargo eşyasının işlemleri posta idaresi veya hızlı kargo şirketlerince vekâletname ibraz edilmeksizin dolaylı temsilci olarak sonuçlandırılabilir.',
 kok=['Gümrük Yönetmeliğine göre; “Posta yolu ve hızlı kargo taşımacılığına konu, miktar ve değeri Kanuna göre belirlenen eşyanın gümrük işlemleri, posta idaresi ya da hızlı kargo taşımacılığı yapan şirketlerce …… ibraz edilmeksizin, …… olarak sonuçlandırılabilir.”',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='vekâletname – dolaylı temsilci',
 c=['vekâletname – doğrudan temsilci', 'temsilname – dolaylı temsilci',
    'temsil yetki belgesi – doğrudan temsilci', 'gümrük beyannamesi – gümrük müşaviri'],
 tuzak=False,
 g='Yönetmeliğe göre posta yolu ve hızlı kargo taşımacılığına konu, miktar ve değeri Kanuna göre belirlenen eşyanın gümrük işlemleri, posta idaresi ya da hızlı kargo taşımacılığı yapan şirketlerce vekâletname ibraz edilmeksizin dolaylı temsilci olarak sonuçlandırılabilir. Bu şirketler doğrudan temsilci sıfatıyla hareket etmez; ibrazı aranmayan belge de temsilname değil vekâletnamedir. (MD GY 561/2; GK 225/1)',
 kanit='2-TEMSİL.txt | Posta yolu ve hızlı kargo taşımacılığına konu, miktar ve değeri Kanunun 225 inci maddesine göre belirlenen eşyanın gümrük işlemleri, posta idaresi ya da hızlı kargo taşımacılığı yapan şirketlerce vekaletname ibraz edilmeksizin, dolaylı temsilci olarak sonuçlandırılabilir.'),

dict(id='D8-094', cikmis='2023/94', konu='Gümrük Müşavirliği', tip='T3', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu geçici m.6/1-b',
 cek='GK 227 ve 228 koşullarını sınavın açıldığı yıl başında sağlayanlar o yıl açılan GM veya GMY sınavına müracaat edebilir.',
 kok=['4458 sayılı Gümrük Kanununa göre, gümrük müşavir yardımcılığı sınavına müracaat koşulları hangi tarihte sağlanmış olmalıdır?'],
 d='Koşullar, sınavın açıldığı yıl başında sağlanmış olmalıdır.',
 c=['Koşullar, sınav başvurusunun son gününde sağlanmış olmalıdır.', 'Koşullar, sınav tarihinde sağlanmış olmalıdır.',
    'Koşullar, sınav ilanının yapıldığı tarihte sağlanmış olmalıdır.', 'Koşullar, sınav sonucunun duyurulduğu günde sağlanmış olmalıdır.'],
 tuzak=False,
 g='Kanuna göre gümrük müşavirliği ve gümrük müşavir yardımcılığı için belirtilen koşulları sınavın açıldığı yıl başında sağlamış olanlar, o yıl açılan sınavlara müracaat edebilir. Koşulların başvurunun son günü, sınav tarihi veya sınav ilanının yapıldığı tarih itibarıyla sağlanması esası benimsenmemiştir. (MD GK Geçici 6/1-b)',
 kanit='51-disiplin cezaları.txt | 227 ve 228 inci maddelerde belirtilen koşulları sınavın açıldığı yıl başında sağlamış olanlar, o yıl açılan gümrük müşavirliği veya gümrük müşavir yardımcılığı sınavlarına müracaat edebilirler.'),
]
