# K07 — Dahilde işleme, şartlı muafiyet/EEGR, gümrük kontrolü altında işleme, hariçte işleme
Q = [
# ---------------- DENEME 6 ----------------
dict(id='D6-021', cikmis='2021/21', konu='Dahilde İşleme', tip='T4', z='OÜ',
 madde='Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) m.8/1-4',
 cek='Şartlı muafiyet sisteminde teminat oranı Bakanlıkça vergi tutarının iki katına kadar artırılabilir; hazine tahvil-bonosu da teminattır.',
 kok=['Dahilde İşleme Rejimi Tebliğine göre şartlı muafiyet sistemindeki teminata ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='Teminat oranı Bakanlıkça, bu ithalattan doğan vergi tutarının iki katına kadar artırılabilir.',
 c=['Teminat yalnızca para veya bankalarca verilen teminat mektubu şeklinde kabul edilebilir.',
    'Teminat, ithal eşyası işlem görmüş ürün olarak ihraç edilmeden önce firmaya iade olunur.',
    'Yurt içi alımlarda teminat, ithalatta alınması gereken vergi üzerinden alınır.',
    'Teminat, Vergi Usul Kanununda belirtilen esaslar çerçevesinde alınır.'],
 tuzak=True,
 g='Tebliğe göre şartlı muafiyet sistemi çerçevesindeki ithalatta uygulanan teminat oranı, Bakanlıkça (İhracat Genel Müdürlüğü) bu ithalattan doğan vergi tutarının iki katına kadar artırılabilir. Teminat yalnız para ve teminat mektubuyla sınırlı değildir; hazine tahvil ve bonoları da teminat olarak kabul edilir ve teminat 6183 sayılı Kanun esaslarına göre alınır. Yurt içi alımlarda teminat, ithalat vergisi üzerinden değil Bakanlık ve/veya ilgili kuruluşlarca belirlenen tutar üzerinden alınır. (MD DİR Tebliği 8)',
 kanit='32-DAHİLDE İŞLEME.txt | bu ithalattan doğan vergi tutarının 2 (iki) katına kadar artırılabilir || 32-DAHİLDE İŞLEME.txt | c- Hazine tahvil ve bonoları || 32-DAHİLDE İŞLEME.txt | yurt içi alımlarda ise Bakanlık ve/veya ilgili kuruluşlarca belirlenen tutar üzerinden teminat alınır'),

dict(id='D6-043', cikmis='2021/43', konu='Şartlı Muafiyet/EEGR', tip='T1', z='Z',
 madde='Gümrük Yönetmeliği m.319/1-5',
 cek='Hariçte işlemeyi müteakip serbest dolaşımda standart değişim dahil tamir gören eşyaya ticaret politikası önlemleri uygulanmaz; girişte öngörülen önlem EEGR eşyasına uygulanır.',
 kok=['Gümrük Yönetmeliğinin ekonomik etkili gümrük rejimlerine ilişkin ortak hükümlerine göre, ticaret politikası önlemlerinin uygulanmasıyla ilgili aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Standart değişim sistemi de dahil olmak üzere tamir gören eşyanın hariçte işlemeyi müteakip serbest dolaşıma girişinde, serbest dolaşıma giriş rejiminde uygulanan ticaret politikası önlemleri uygulanır.',
 c=['Eşyanın serbest dolaşıma girişi sırasında ticaret politikası önlemlerinin uygulanması öngörülüyorsa, bu önlemler eşyanın ekonomik etkili bir gümrük rejimine girişinde ya da rejime tabi olduğu süre zarfında uygulanmaz.',
    'Eşyanın Türkiye Gümrük Bölgesine girişinde ticaret politikası önlemlerinin uygulanması öngörülüyorsa, söz konusu önlemler eşyanın ekonomik etkili gümrük rejimlerine tabi tutulması durumunda da uygulanır.',
    'Gümrük kontrolü altında işleme sonucunda elde edilen işlenmiş ürünlerin serbest dolaşıma giriş rejimine tabi tutulması halinde, işlem görmüş ürüne ilişkin ticaret politikası önlemleri uygulanır.',
    'İhracatta ticaret politikası önlemleri öngörülmüşse, bu önlemler antrepo rejimine tabi tutulmuş serbest dolaşımdaki eşyanın Türkiye Gümrük Bölgesi dışına çıkarılması sırasında da uygulanır.'],
 tuzak=False,
 g='Yönetmeliğe göre serbest dolaşıma giriş rejiminde uygulanan ticaret politikası önlemleri; Türk menşeini koruyan, standart değişim sistemi dahil tamir gören ve daha ileri düzeyde işleme faaliyetine tabi tutulan eşyaya, hariçte işlemeyi müteakip serbest dolaşıma girişte veya yeniden ithalde uygulanmaz. Buna karşılık önlemin Türkiye Gümrük Bölgesine girişte öngörüldüğü hallerde önlem ekonomik etkili rejime tabi eşyaya da uygulanır; gümrük kontrolü altında işlemede ise işlem görmüş ürüne ilişkin önlemler uygulanır. (MD GY 319)',
 kanit='19-ŞARTLI M VE E.E.G.R.txt | b) Standart değişim sistemi de dahil olmak üzere tamir gören, || 19-ŞARTLI M VE E.E.G.R.txt | eşyaya, hariçte işlemeyi müteakip serbest dolaşıma girişi veya yeniden ithali halinde uygulanmaz.'),

dict(id='D6-044', cikmis='2021/44', konu='GKAİR', tip='T5', z='OÜ',
 madde='Gümrük Yönetmeliği m.370/1-2',
 cek='GKAİR, işlenmiş ürünün vergisinin bünyesindeki ithal ürünün vergisinden düşük olduğu işlemlerde ve teknik düzenlemelere uygunluk için işlenecek eşyada uygulanır.',
 kok=['Gümrük Yönetmeliğine göre gümrük kontrolü altında işleme rejimi, işlenmiş ürünün ithalat vergisinin, bünyesindeki ithal ürünün vergisinden …… olduğu işlemler için uygulanır. Rejim, serbest dolaşıma girişte aranan bazı …… uygunluğun sağlanması için işlenmesi gereken eşyada da uygulanır.',
      'Yukarıdaki boşluklara **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='Daha düşük – teknik düzenlemelere',
 c=['Daha yüksek – teknik düzenlemelere', 'Daha düşük – ticaret politikası önlemlerine',
    'Daha yüksek – ticaret politikası önlemlerine', 'Daha düşük – menşe kurallarına'],
 tuzak=False,
 g='Yönetmeliğe göre gümrük kontrolü altında işleme rejimi, işlenmiş ürünün ithalat vergisinin bünyesindeki ithal ürünün vergisinden daha düşük olduğu işlemler için uygulanır; rejimin ekonomik anlamı bu vergi farkından gelir. Rejim ayrıca serbest dolaşıma girişte aranan bazı teknik düzenlemelere uygunluğun sağlanması için işlenmesi gereken eşyada da kullanılır; ticaret politikası önlemleri ve menşe kuralları bu hükümde yer almaz. (MD GY 370)',
 kanit='33-GKAİR.txt | işlenmiş ürünün ithalat vergisinin, bünyesinde bulundurduğu ithal ürünün vergisinden daha düşük olduğu işlemler için uygulanır || 33-GKAİR.txt | serbest dolaşıma girişinde aranılan bazı teknik düzenlemelere uygunluğunun sağlanması için'),

dict(id='D6-052', cikmis='2021/52', konu='Hariçte İşleme', tip='T4', z='Z',
 madde='Gümrük Yönetmeliği m.308/1-k (karşılaştırma: m.315, 325, 353)',
 cek='Rejimin kapatılma süresi: geri ödemede iade ve HİR sonrası muafiyet süresi dahil, eşyanın yeni işlem veya kullanıma tabi tutulmasının zorunlu olduğu süre.',
 kok=['Gümrük Yönetmeliğinde ekonomik etkili gümrük rejimleri için yapılan tanımlara göre, “rejimin kapatılma süresi” aşağıdakilerden hangisinde doğru olarak tanımlanmıştır?'],
 d='Geri ödeme sisteminde vergilerin iadesi veya hariçte işleme sonrası serbest dolaşıma girişte tam ya da kısmi muafiyet için geçen süre de dahil olmak üzere, rejim kapsamındaki eşyanın gümrükçe onaylanmış yeni bir işlem veya kullanıma tabi tutulmasının zorunlu olduğu süredir.',
 c=['Geri ödeme sisteminde vergilerin iadesi veya hariçte işleme sonrası serbest dolaşıma girişte tam ya da kısmi muafiyet için geçen süre hariç olmak üzere, rejim kapsamındaki eşyanın gümrükçe onaylanmış yeni bir işlem veya kullanıma tabi tutulmasının zorunlu olduğu süredir.',
    'İzin belgesinde öngörülen süre içinde veya en geç bu sürenin sona erdiği tarihten itibaren, rejimin kapatılması için denetleyici gümrük idaresine başvuru yapılmasının zorunlu olduğu ve şartlı muafiyetli dahilde işlemede üç ay olarak uygulanan süredir.',
    'İzin belgesinin tarihinden başlayıp izin belgesi süresinin bittiği ayın son günü sona eren, mücbir sebep ve beklenmeyen hallerde veya izin sahibinin ileri sürdüğü haklı gerekçelere bağlı olarak uzatılabilen ve rejim kapsamındaki ithalat ile ihracatın içinde yapılması gereken izin geçerlilik süresidir.',
    'İznin verilmesine ilişkin kararın veya başvurunun reddedilme nedenlerinin, başvurunun kayda girdiği tarihten itibaren antrepo rejiminde altmış gün, diğer rejimlerde otuz gün içinde başvuru sahibine bildirilmesi gereken süredir.'],
 tuzak=False,
 g='Yönetmelikteki tanıma göre rejimin kapatılma süresi, geri ödeme sisteminde vergilerin iadesi ve hariçte işleme sonrası serbest dolaşıma girişte muafiyet için geçen süre de dahil olmak üzere, rejim kapsamındaki eşyanın gümrükçe onaylanmış yeni bir işlem veya kullanıma tabi tutulmasının zorunlu olduğu süredir. Kapatma için denetleyici gümrük idaresine başvuru süresi ile izin belgesinin geçerlilik süresi ayrı hükümlerde düzenlenen farklı sürelerdir; tanımdaki süreler de hariç tutulmaz, dahil edilir. (MD GY 308/1-k; GY 325; GY 353)',
 kanit='19-ŞARTLI M VE E.E.G.R.txt | k) Rejimin kapatılma süresi: Geri ödeme sisteminin kullanıldığı dahilde işleme sonrası ithalat vergilerinin iadesi için veya hariçte işleme sonrası serbest dolaşıma girişte ithalat vergilerinin tam veya kısmi muafiyeti için geçen süre de dahil olmak üzere || 19-ŞARTLI M VE E.E.G.R.txt | gümrükçe onaylanmış yeni bir işlem veya kullanıma tabi tutulmasının zorunlu olduğu süreyi'),

dict(id='D6-089', cikmis='2021/89', konu='Dahilde İşleme', tip='T4', z='Z',
 madde='Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) m.33/1-4, 33/9',
 cek='Üçüncü ülke girdili olup Topluluğa ihraç edilen harp araç, gereç, teçhizatı ve yedek parçaları için telafi edici vergi aranmaz.',
 kok=['Dahilde İşleme Rejimi Tebliğine göre telafi edici verginin ödenmesine ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='Elde edilmesinde üçüncü ülke menşeli eşya kullanılan ve Topluluğa üye ülkelere ihraç edilen her türlü harp araç, gereç ve teçhizatı ile bunların yapım, bakım ve onarımında kullanılacak yedek parçalar için telafi edici vergi aranmaz.',
 c=['1/2007 sayılı Türkiye-AT Ortaklık Konseyi Kararı kapsamı dışında Topluluğa ihraç edilen işlenmiş tarım ürünlerinde, bünyede üçüncü ülke menşeli işlenmiş tarım ürünü kullanılmışsa bu ürünün tamamına ilişkin vergi ödenir.',
    'Pan-Avrupa Menşe Kümülasyonuna taraf ülkelerden menşe ispat belgesi veya tedarikçi beyanı eşliğinde ithal edilen eşyadan elde edilen ürünün tekrar kümülasyona taraf bir ülkeye ihracında, ithalat rejiminde belirtilen oranda vergi tahsil edilir.',
    'Ülkemizde doğmuş ve büyütülmüş canlı hayvanlar da dahil olmak üzere tarım ürünlerinin menşe ispat belgesiyle Topluluğa ihracatında, üçüncü ülke menşeli girdilere ilişkin vergi tahsil edilir.',
    'Şartlı muafiyet kapsamındaki sanayi ürünlerinin A.TR dolaşım belgesiyle Topluluğa ihracatında, üçüncü ülke menşeli girdilerin vergisi, kaynak ülkelerle yapılan anlaşmalardaki lehte hükümlere bakılmaksızın ödenir.'],
 tuzak=False,
 g='Tebliğe göre elde edilmesinde üçüncü ülke menşeli eşya kullanılan ve Avrupa Topluluğuna üye ülkelere ihraç edilen harp araç, gereç ve teçhizatı ile yedek parçaları için telafi edici vergi aranmaz. Pan-Avrupa Menşe Kümülasyonu kapsamında tekrar kümülasyona taraf ülkeye yapılan ihracatta verginin tahsili aranmaz; 1/2007 sayılı Karar dışındaki işlenmiş tarım ürünlerinde yalnız sanayi payına ilişkin vergi ödenir. Tarım ürünlerinde canlı hayvanlar istisnadır; sanayi ürünlerinde ise anlaşmalardaki lehte hükümler saklıdır. (MD DİR Tebliği 33/1-4, 33/9)',
 kanit='32-DAHİLDE İŞLEME.txt | Elde edilmesinde üçüncü ülke menşeli eşya kullanılan ve Avrupa Topluluğuna üye ülkelere ihraç edilen her türlü harp araç, gereç, teçhizat, makine, cihaz ve sistemleri ile bunların yapım, bakım ve onarımlarında kullanılacak yedek parçalar için telafi edici vergi aranmaz'),
]
