# Görev K02 — Gümrük kıymeti (Deneme 6–10)
Q = [
# ---------------- DENEME 6 ----------------
dict(id='D6-029', cikmis='2021/29', konu='Gümrük Kıymeti', tip='T9', z='Z',
 madde='Gümrük Yönetmeliği m.44/1, m.49/1, m.49/2; 4458 sayılı Gümrük Kanunu m.25/1, m.28/b',
 cek='Sıra değişikliği talebi uygun bulununca hesaplanmış kıymet: malzeme, imalat, mutat kâr-genel gider, giriş limanına kadar nakliye; yurt içi nakliye-montaj eklenmez.',
 kok=['Gümrük Yönetmeliğine göre kıymet tespit yöntemlerinin uygulama sırası ve hesaplanmış kıymetin unsurları dikkate alındığında; (K) firması, ilişkili olmadığı yurt dışındaki (L) firmasından özel üretim bir makine ithal etmektedir. Eşyanın gümrük kıymeti satış bedeli yöntemine göre belirlenememiş, aynı ve benzer eşyaya ait bir satış bedeli de bulunamamıştır. Beyan sahibinin, hesaplanmış kıymet yönteminin indirgeme yönteminden önce uygulanmasına ilişkin yazılı talebi gümrük idaresince uygun bulunmuş; gerekli bilgi ve belgeler, doğruluklarını ispata hazır olunduğu üretici ülke makamlarından alınan belgeyle tevsik edilerek ibraz edilmiştir. Dosyadaki veriler şöyledir: makinenin üretiminde kullanılan malzemelerin bedeli 40.000 TL, imalat işlemlerinin bedeli 25.000 TL; ihraç ülkesindeki üreticilerin Türkiye\'ye ihraç ettikleri aynı sınıf veya cins eşyanın satışında mutat olan kâr ve genel giderlere eşit tutar 15.000 TL; makinenin giriş limanına kadar nakliyesine ilişkin yükleme, elleçleme, nakliye ve sigorta giderleri toplamı 5.000 TL; giriş limanından (K)\'nin fabrikasına kadar yapılan nakliye gideri 2.000 TL; ithalattan sonra fabrikada yapılacak kurma ve montaj gideri 4.000 TL. Aynı makinelerin Türkiye\'deki satışlarına dayanılarak indirgeme yöntemiyle bulunan kıymet ise 90.000 TL\'dir.',
      'Buna göre, eşyanın gümrük kıymeti **kaç TL**\'dir?'],
 d='85.000', c=['80.000', '87.000', '89.000', '90.000'],
 opts=['80.000', '85.000', '87.000', '89.000', '90.000'],
 tuzak=False,
 g='Beyan sahibinin yazılı talebi gümrük idaresince uygun bulunduğundan hesaplanmış kıymet yöntemi indirgeme yönteminden önce uygulanır; kıymet malzeme (40.000), imalat (25.000), mutat kâr ve genel gider (15.000) ile giriş limanına kadarki yükleme, elleçleme, nakliye ve sigorta (5.000) toplamı olan 85.000 TL\'dir. 90.000 TL sıra değişikliğinin yok sayılıp indirgeme yönteminin uygulanması, 87.000 TL ve 89.000 TL ise giriş limanından sonraki nakliyenin ya da ithalat sonrası montaj giderinin eklenmesi sonucudur; 80.000 TL giriş limanına kadarki giderlerin atlanmasıyla bulunur. (MD GY 44/1, 49/2; GK 25/1, 28/b)',
 kanit='12-KIYMET VE KAPLAR.txt | beyan sahibinin yazılı talebinin gümrük idaresince uygun bulunması şartıyla, aşağıda yer alan yöntemlerden indirgeme yöntemi ile hesaplanmış kıymet yönteminin uygulama sırası değiştirilebilir || 12-KIYMET VE KAPLAR.txt | a) İthal eşyasının üretiminde kullanılan malzeme ve yapılan imalat veya diğer imal işlemlerinin bedel veya kıymetleri, || 12-KIYMET VE KAPLAR.txt | c) İthal eşyasının giriş liman veya yerine kadar nakliyesi ile ilgili olarak yapılan yükleme, boşaltma, elleçleme giderleri ile nakliye ve sigorta giderleri.'),

dict(id='D6-031', cikmis='2021/31', konu='Gümrük Kıymeti', tip='T9', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.24/3-a, m.28/c ve son paragraf; Gümrük Yönetmeliği m.45/1-a, m.45/1-g',
 cek='Satıcının yükümlülüğü için üçüncü kişiye ödeme ve yazılı finansman anlaşmasız vade farkı fiyata dahil; düşüldüğü tevsik edilmeyen dahili vergi fiyattan çıkarılmaz.',
 kok=['4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliğine göre fiilen ödenen veya ödenecek fiyatın belirlenmesine ilişkin olarak; (K) firması, ilişkili olmadığı (L) firmasından satın aldığı eşyayı serbest dolaşıma giriş rejimi kapsamında beyan etmiştir. Eşyanın faturası 60.000 TL olup bu bedelin içinde, ihracat ülkesinde ödenen 4.000 TL tutarında bir dahili vergi de yer almaktadır; söz konusu verginin fiyatta alıcı lehine düzeltme yapılarak düşüldüğü veya düşüleceği gümrük idaresine tevsik edilmemiştir. Satış sözleşmesi gereği ve satışın koşulu olarak (K), (L)\'nin bir hammadde tedarikçisine olan 6.000 TL tutarındaki borcunu doğrudan bu tedarikçiye ödemiştir. Ayrıca mal bedelinin peşin ödenmemesi nedeniyle (K), (L)\'ye 1.500 TL vade farkı ödemiştir; taraflar arasında yazılı olarak yapılmış bir finansman anlaşması bulunmamaktadır. Satış bedeli yönteminin uygulanmasına engel başka bir durum bulunmamaktadır.',
      'Buna göre, eşyanın fiilen ödenen veya ödenecek fiyatı **kaç TL**\'dir?'],
 d='67.500', c=['60.000', '61.500', '63.500', '66.000'],
 opts=['60.000', '61.500', '63.500', '66.000', '67.500'],
 tuzak=False,
 g='Fiilen ödenen fiyat, satış koşulu olarak satıcının bir yükümlülüğünü karşılamak üzere üçüncü kişiye yapılan ödemeleri de kapsar; yazılı finansman anlaşmasına dayanmayan vade farkı da fiyatın içindedir. Düşüldüğü tevsik edilmeyen dahili vergi fiyattan çıkarılamayacağından fiyat 60.000 + 6.000 + 1.500 = 67.500 TL\'dir. 63.500 TL dahili verginin düşülmesi, 66.000 TL vade farkının, 61.500 TL ise tedarikçiye yapılan ödemenin atlanmasıyla bulunur. (MD GK 24/3-a, 28/c; GY 45/1-a, 45/1-g)',
 kanit='12-KIYMET VE KAPLAR.txt | alıcının satıcıya veya satıcının bir yükümlülüğünü karşılamak üzere üçüncü bir kişiye yaptığı veya yapacağı tüm ödemeleri kapsar || 12-KIYMET VE KAPLAR.txt | Mal bedelinin peşin ödenmemesi nedeniyle satıcıya ya da satıcı yararına her ne ad altında olursa olsun yapılan ödemelerden … fiilen ödenen ya da ödenecek fiyatın içindedir || 12-KIYMET VE KAPLAR.txt | finansman anlaşmasının yazılı olarak yapılmış olması || 12-KIYMET VE KAPLAR.txt | bu meblağın fiyatta alıcı lehine düzeltme yapılarak düşüldüğünün veya düşüleceğinin gümrük idaresine tevsiki ve idarece uygun bulunması halinde, gümrük kıymetine dahil edilmez'),

dict(id='D6-035', cikmis='2021/35', konu='Gümrük Kıymeti', tip='T6', z='OÜ',
 madde='Gümrük Yönetmeliği m.43/1-ç',
 cek='Birim fiyatın belirlenmesine imkân veren, ileri ve geriye doğru tespiti mümkün ilk tarih "aynı veya yakın bir tarih" olarak tanımlanır.',
 kok=['Gümrük Yönetmeliğinin gümrük kıymetine ilişkin tanımları arasında yer alan bir kavram şöyle tanımlanmıştır:',
      '“İthal edilen eşya ya da aynı veya benzer eşyaya ait birim fiyatın belirlenmesine imkân verecek, ileri ve geriye doğru tespiti mümkün olan ilk tarih”',
      'Yukarıda tanımlanan kavram aşağıdakilerden hangisidir?'],
 d='Aynı veya yakın tarih',
 c=['Yükümlülüğün başladığı tarih', 'Beyanname tescil tarihi', 'Ödemenin yapılacağı tarih', 'Eşyanın ithal tarihi'],
 tuzak=False,
 g='Gümrük Yönetmeliği, birim fiyatın belirlenmesine imkân verecek şekilde ileri ve geriye doğru tespiti mümkün olan ilk tarihi “aynı veya yakın bir tarih” olarak tanımlar. Yükümlülüğün başladığı tarih yabancı paraların Türk lirasına çevrilmesinde esas alınan kur tarihidir; ödemenin yapılacağı tarih ise bedeli henüz ödenmemiş eşyada kıymete esas bedelin belirlendiği tarihtir. (MD GY 43/1-ç)',
 kanit='12-KIYMET VE KAPLAR.txt | ç) Aynı veya yakın bir tarih: İthal edilen eşya ya da aynı veya benzer eşyaya ait birim fiyatın belirlenmesine imkan verecek ileri ve geriye doğru tespiti mümkün olan ilk tarihi'),

dict(id='D6-039', cikmis='2021/39', konu='Gümrük Kıymeti', tip='T7', z='OÜ',
 madde='Gümrük Yönetmeliği m.48/4',
 cek='İndirgemede ithal hâliyle satış yoksa, ithalatçının talebiyle işlem görmüş eşyanın müstakil alıcılara en büyük miktardaki satış birim fiyatı esas alınır.',
 kok=['Gümrük Yönetmeliğine göre, indirgeme yönteminde işlenmiş eşyanın satış birim fiyatı kimin talebi üzerine esas alınır?'],
 d='İthalatçının', c=['Satıcının', 'Gümrük idaresinin', 'İhracatçının', 'Müstakil alıcının'],
 tuzak=False,
 sapma='Kıymet bölümündeki süre/eşik hükümleri (90 gün, bir yıl, %5, %10-%3, 26. gün) çıkmışta veya hafızada; T3 yerine aynı bölümde T7',
 g='İthal edildiği hal ve durumda satılan eşya bulunmadığında, ithal edildikten sonra işlenen veya değişikliğe tabi tutulan eşyanın müstakil alıcılara en büyük miktardaki satışına ait birim fiyat ancak ithalatçının talebi üzerine esas alınır; bu fiyattan işlemeden doğan ilave kıymet ve olağan indirimler düşülür. Bu tercih gümrük idaresine veya ihracatçıya bırakılmamıştır. (MD GY 48/4)',
 kanit='12-KIYMET VE KAPLAR.txt | İthal edildiği hal ve durumda satılan kıymeti belirlenecek eşya ya da aynı veya benzer eşya yoksa; ithalatçının talebi üzerine ithal edildikten sonra işlenen veya değişikliğe tabi tutulan kıymeti belirlenecek eşyanın'),

# ---------------- DENEME 7 ----------------
dict(id='D7-044', cikmis='2022/44', konu='Gümrük Kıymeti', tip='T4', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.24/2-a',
 cek='İlişkili satışta idare, ilişkinin fiyatı etkilediği kanısına varırsa bunu beyan sahibine yazılı bildirir; süresinde cevap hakkı saklıdır.',
 kok=['4458 sayılı Gümrük Kanununa göre, alıcı ile satıcı arasında ilişki bulunan satışlarda satış bedelinin gümrük kıymeti olarak kabulüne ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='İdare, ilişkinin fiyatı etkilediği kanısına varırsa bu hususları beyan sahibine yazılı olarak bildirir.',
 c=['İlişkinin varlığı, satış bedelinin reddedilmesi için tek başına yeterli bir neden oluşturur ve bedel kabul edilmez.',
    'İdare, ilişkinin fiyatı etkilediği kanısına varırsa satış bedelini beyan sahibine bildirmeksizin reddeder.',
    'İdarenin ilişkinin fiyatı etkilediğine dair bildirimine karşı beyan sahibine cevap hakkı tanınmamıştır.',
    'Satışa ilişkin koşullar incelenmeksizin, ilişkili kişiler arasındaki satış bedeli doğrudan kabul edilir.'],
 tuzak=False,
 g='Kanuna göre ilişkinin varlığı satış bedelinin reddi için tek başına yeterli değildir; satış koşulları incelenir ve gümrük idaresi ilişkinin fiyatı etkilediği kanısına varırsa bunu beyan sahibine yazılı olarak bildirir, beyan sahibinin süresi içinde cevap hakkı saklıdır. Bildirimsiz ret ve cevap hakkının bulunmadığına ilişkin ifadeler bu usule aykırıdır; satış koşulları incelenmeden bedelin doğrudan kabul edileceği de öngörülmemiştir. (MD GK 24/2-a)',
 kanit='12-KIYMET VE KAPLAR.txt | Gümrük idaresi, beyan sahibi veya diğer kaynaklardan elde ettiği bilgilere dayanarak, söz konusu ilişkinin fiyatı etkilediği kanısına varırsa, bu hususları beyan sahibine yazılı olarak bildirir. Süresi içinde verilmek şartıyla beyan sahibinin cevap hakkı saklıdır.'),

dict(id='D7-047', cikmis='2022/47', konu='Gümrük Kıymeti', tip='T9', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.27/1-c, m.27/5-b; Gümrük Yönetmeliği m.56/4, m.56/6; Gümrük Genel Tebliği (Gümrük Kıymeti) (Seri No: 2) m.6/3, m.10',
 cek='Royalti: satış koşulu tasarım ücretinin eşyayla ilgili kısmı eklenir; satıcının istemediği üçüncü kişi royaltisi ve satış koşulu olmayan tekrar satış hakkı eklenmez.',
 kok=['4458 sayılı Gümrük Kanunu, Gümrük Yönetmeliği ve Gümrük Genel Tebliği (Gümrük Kıymeti) (Seri No: 2) hükümlerine göre royalti ve lisans ücretlerinin gümrük kıymetine ilavesine ilişkin olarak; (K) firması, ilişkili olmadığı (L) firmasından satın aldığı makine parçalarını serbest dolaşıma giriş rejimi kapsamında beyan etmiştir. Satış bedeli yöntemine esas fatura bedeli 80.000 TL olup nakliye, sigorta ve diğer giderler bu bedele dahildir. Fatura bedeline dahil olmayan ödemeler şunlardır: (K), parçalarda kullanılan tescilli tasarım için satış sözleşmesi gereği ve satışın koşulu olarak (L)\'ye 5.500 TL lisans ücreti ödemiştir; sözleşmeye göre bu tutarın 1.500 TL\'lik kısmı ithalattan sonra Türkiye\'de verilecek eğitim hizmetinin karşılığıdır. (K), parçaların üretiminde kullanılan imalat prosesinin hak sahibi olan ve üçüncü bir ülkede yerleşik (M) firmasına 6.000 TL royalti ödemektedir; ne (L) ne de (L) ile ilişkili bir kişi (K)\'den bu ödemeyi yapmasını istemiştir. (K) ayrıca parçaları Türkiye\'de tekrar satma hakkı için (L)\'ye 2.500 TL ödemiştir; bu ödeme Türkiye\'ye ihraç amacıyla yapılan satışta bir satış koşulu değildir.',
      'Buna göre, eşyanın gümrük kıymeti **kaç TL**\'dir?'],
 d='84.000', c=['85.500', '86.500', '90.000', '92.500'],
 opts=['84.000', '85.500', '86.500', '90.000', '92.500'],
 tuzak=False,
 g='Satış koşulu olarak ödenen tasarım lisans ücretinin yalnızca nesnel ve ölçülebilir verilere göre ithal eşyasıyla ilgisi kurulan 4.000 TL\'lik kısmı eklenir ve kıymet 84.000 TL olur. Üçüncü kişiye ödenen royalti, satıcı veya onunla ilişkili bir kişi bu ödemeyi istemediği için satış koşulu sayılmaz (alacaklının yerleşik olduğu ülke ise dikkate alınmaz); satış koşulu olmayan tekrar satış hakkı ödemesi de fiyata ilave edilmez. 85.500 TL lisans ücretinin tamamının, 90.000 TL ve 92.500 TL ise üçüncü kişi royaltisinin ve tekrar satış hakkı ödemesinin eklenmesiyle bulunur. (MD GK 27/1-c, 27/5-b; GY 56/4; Kıymet Tebliği 6/3, 10)',
 kanit='12-KIYMET VE KAPLAR.txt | toplam ücretin sadece nesnel ve ölçülebilir verilere dayanılarak eşya ile ilgisi kurulup hesaplanabilen kısmı ithal edilen eşyanın gümrük kıymetine dahil edilir || 12-KIYMET VE KAPLAR.txt | birinci fıkrada öngörülen koşullar, satıcı veya satıcı ile ilişkili olan bir kişinin alıcıdan bu ödemeyi yapmasını istememesi durumunda yerine getirilmiş sayılmaz || 12-KIYMET VE KAPLAR.txt | Türkiye\'ye ihraç amacıyla satışında bir satış koşulu olmaması kaydıyla, dağıtım veya tekrar satış hakları için alıcının yaptığı ödemeler'),

dict(id='D7-048', cikmis='2022/48', konu='Gümrük Kıymeti', tip='T1', z='OÜ',
 madde='Gümrük Yönetmeliği m.43/1-b, m.46/1, m.46/2, m.46/5',
 cek='Görünüşteki küçük farklılıklar, diğer hususlarda tanıma uyan eşyanın aynı eşya sayılmasını önlemez.',
 kok=['Gümrük Yönetmeliğine göre “aynı eşya” ve aynı eşyanın satış bedeli yöntemine ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Gümrük kıymetinin tespitinde görünüşteki küçük farklılıklar, diğer hususlarda tanıma uyan eşyanın aynı eşya sayılmasını önler ve bu eşya aynı eşya olarak dikkate alınmaz.',
 c=['Aynı eşya, fiziksel özellik, kalite ve tanındığı özellikleri dahil olmak üzere her hususta aynı olan ve kıymeti belirlenecek eşya ile aynı ülkede üretilmiş bulunan eşyadır.',
    'Bu yöntemde kıymet, Türkiye\'ye ihraç amacıyla satılarak kıymeti belirlenecek eşya ile aynı veya yakın bir tarihte ihraç edilen aynı eşyanın satış bedeli esas alınarak belirlenir.',
    'Bu yöntemde kullanılacak satış bedeli, önceden kıymeti satış bedeli yöntemine göre belirlenmiş ve ticari düzey, miktar ile nakliye farklarına göre düzeltilmiş gümrük kıymetidir.',
    'Ticari düzey veya miktar farkı nedeniyle yapılacak düzeltme kıymet artışına da azalışına da yol açsa, makul olduğunun ve doğruluğunun kesin delillerle ispatı gerekir.'],
 tuzak=False,
 g='Yönetmelikteki tanıma göre görünüşteki küçük farklılıklar, diğer hususlarda tanıma uyan eşyanın aynı eşya sayılmasını önlemez; ifade bu hükmü tersine çevirmektedir. Aynı eşyanın satış bedelinin önceden satış bedeli yöntemiyle belirlenmiş ve düzeltilmiş kıymet olduğu ile düzeltmenin artış veya azalışa yol açmasından bağımsız olarak kesin delille ispat edilmesi gerektiği doğrudur. (MD GY 43/1-b, 46/1, 46/2, 46/5)',
 kanit='12-KIYMET VE KAPLAR.txt | görünüşteki küçük farklılıklar diğer hususlarda tanıma uyan eşyanın aynı eşya sayılmasını önlemez || 12-KIYMET VE KAPLAR.txt | aynı eşyanın satış bedeli, önceden kıymeti satış bedeli yöntemine göre belirlenmiş ve bu maddenin ikinci ve üçüncü fıkralarına göre düzeltilmiş gümrük kıymetidir || 12-KIYMET VE KAPLAR.txt | Kıymet artış veya azalışına da yol açsa, düzeltmenin yapılabilmesi için makul olduğunun ve doğruluğunun kesin delillerle ispatı gerekir.'),

dict(id='D7-049', cikmis='2022/49', konu='Gümrük Kıymeti', tip='T6', z='Z',
 madde='Gümrük Yönetmeliği m.45/1-f; 4458 sayılı Gümrük Kanunu m.24/1-b',
 cek='Satış veya fiyatın kıymeti belirlenebilir koşul ya da edime bağlı olması hâlinde bu kıymet satıcıya yapılan dolaylı ödeme sayılır.',
 kok=['Gümrük Yönetmeliğinde satış bedeli yöntemine ilişkin bir kavram şöyle tanımlanmıştır:',
      '“Satış veya fiyatın kıymeti belirlenebilir bir koşul veya edim konusu olması hâlinde, alıcının kendi hesabına yaptığı faaliyetlerle veya ilave unsurlarla ilgili olmamak kaydıyla, fiyatın parçası sayılan koşul veya edim kıymeti”',
      'Yukarıda tanımlanan kavram aşağıdakilerden hangisidir?'],
 d='Satıcıya yapılan dolaylı ödeme',
 c=['Satıcıya intikal eden hasıla', 'Alıcı lehine fiyat düzeltmesi', 'Kendi hesabına yapılan faaliyet', 'Satın alma komisyonu'],
 tuzak=False,
 g='Satış veya fiyat kıymeti belirlenebilir bir koşul veya edim konusu olduğunda, bu kıymet alıcı tarafından satıcıya yapılan dolaylı bir ödeme sayılır ve fiilen ödenen fiyatın parçası kabul edilir; kıymeti tespit edilemez koşul ise satış bedeli yönteminin uygulanmasını engeller. Alıcının pazarlama dahil kendi hesabına yaptığı faaliyetler dolaylı ödeme sayılmaz; satıcıya intikal eden hasıla ise ayrı bir ilave unsurdur. (MD GY 45/1-f; GK 24/1-b)',
 kanit='12-KIYMET VE KAPLAR.txt | satış veya fiyatın, kıymeti belirlenmekte olan eşya bakımından kıymeti belirlenebilir mahiyette bir koşul veya edim konusu olması durumunda || 12-KIYMET VE KAPLAR.txt | bu kıymet alıcı tarafından satıcıya yapılan dolaylı bir ödeme sayılır ve fiilen ödenen veya ödenecek fiyatın bir parçası kabul edilir'),

dict(id='D7-050', cikmis='2022/50', konu='Gümrük Kıymeti', tip='T8', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.26/1, m.26/2-b, c, d, e; Gümrük Yönetmeliği m.46/5, m.50',
 cek='Son yöntemde aynı eşyanın hesaplanmış kıymet hükümlerine göre belirlenmiş kıymeti kullanılabilir; bunun dışındaki maliyet bedeli esas alınmaz.',
 kok=['4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliğine göre son yönteme ilişkin olarak; (K) firmasının ithal ettiği özel üretim pompaların gümrük kıymeti, beyan edilen kıymete ilişkin makul şüpheler giderilemediği için satış bedeli yöntemine göre belirlenememiştir. Aynı veya benzer eşyaya ait, önceden satış bedeli yöntemine göre belirlenmiş bir kıymet bulunmamakta; pompalar Türkiye\'de ithal edildiği hâliyle satılmadığından indirgeme yöntemi de uygulanamamaktadır. Üretici, maliyet verilerini paylaşmadığından (K)\'nin ithalatı için hesaplanmış kıymet yöntemi de işletilememiştir. Gümrük idaresinin kayıtlarında ise başka bir ithalatçı tarafından aynı üreticiden yakın tarihte ithal edilen aynı pompaların kıymetinin, hesaplanmış kıymet yöntemine göre belirlendiği görülmektedir. Bunun yanında, aynı pompaların üretici tarafından bildirilen ancak hesaplanmış kıymet hükümlerine göre belirlenmemiş maliyet bedeli, ihraç ülkesindeki iç piyasa fiyatı ve Türkiye\'den başka bir ülkeye ihraç edilen pompaların fiyatı da bilinmektedir. Gümrük idaresi, ayrıca birbirine yakın iki alternatif kıymet tespit etmiştir.',
      'Bu olayda, gümrük idaresinin son yönteme göre yapacağı kıymet tespitine ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='Aynı pompaların başka bir ithalatta hesaplanmış kıymet yöntemiyle belirlenen kıymeti, Türkiye\'de mevcut veri olarak Kanun prensiplerine uygun bir yöntemle kıymet tespitinde esas alınabilir.',
 c=['Aynı pompaların üretici tarafından bildirilen ve hesaplanmış kıymet hükümlerine göre belirlenmemiş maliyet bedeli, Türkiye\'de mevcut veri sayıldığından kıymet tespitinde esas alınabilir.',
    'Gümrük idaresince tespit edilen birbirine yakın iki alternatif kıymetten yüksek olanı, Türkiye\'de mevcut verilere dayandığı sürece son yönteme göre gümrük kıymeti olarak kabul edilebilir.',
    'Pompaların ihraç ülkesindeki iç piyasa fiyatı, ihracatçı tarafından belgelendirildiği sürece Kanun prensiplerine uygun bir yöntemle kıymet tespitinde esas alınabilecek veriler arasında yer alır.',
    'Aynı pompaların Türkiye\'den başka bir ülkeye ihraç edildiği fiyat, Türkiye\'de mevcut verilerden elde edildiği için Kanun prensiplerine uygun bir yöntemle kıymet tespitinde esas alınabilir.'],
 tuzak=False,
 g='Son yönteme göre kıymet, Kanun ve 1994 GATT VII nci Madde ile Uygulama Anlaşması prensiplerine uygun yöntemlerle Türkiye\'de mevcut veriler esas alınarak belirlenir; Kanun yalnızca aynı veya benzer eşyanın hesaplanmış kıymet hükümlerine göre bulunan kıymeti dışındaki maliyet bedelini yasakladığından hesaplanmış kıymetle belirlenmiş kıymet kullanılabilir. Hesaplanmış kıymet hükümlerine göre belirlenmemiş maliyet bedeli, iki alternatiften yüksek olanını kabul eden sistem, ihraç ülkesi iç piyasa fiyatı ve Türkiye\'den başka ülkeye ihraç fiyatı ise son yöntemde esas alınamaz. (MD GK 26/1, 26/2; GY 46/5, 50)',
 kanit='12-KIYMET VE KAPLAR.txt | d) Aynı veya benzer eşyanın, 25 inci maddenin 2 nci fıkrasının (d) bendi hükümlerine göre hesaplanmış kıymeti dışındaki maliyet bedeli, || 12-KIYMET VE KAPLAR.txt | Prensip ve genel hükümlerine uygun yöntemlerle ve Türkiye\'de mevcut veriler esas alınarak belirlenir. || 12-KIYMET VE KAPLAR.txt | b) Gümrük idaresinin iki alternatif kıymetten yüksek olanının kabul etmesini öngören bir sistem,'),

dict(id='D7-051', cikmis='2022/51', konu='Gümrük Kıymeti', tip='T3', z='Z',
 madde='Gümrük Yönetmeliği m.53/4, m.53/7; Gümrük Genel Tebliği (Gümrük Kıymeti) (Seri No: 2) m.11/5',
 cek='Süresinde verilmeyen tamamlayıcı beyan nedeniyle geç ödenen vergilere beyannamenin tescil tarihinden itibaren gecikme zammı oranında gecikme faizi uygulanır.',
 kok=['Gümrük Yönetmeliğine göre, istisnai kıymetle beyanda geç verilen tamamlayıcı beyanın vergilerine gecikme faizi nasıl uygulanır?'],
 d='Beyannamenin tescil tarihinden itibaren gecikme zammı oranında',
 c=['Tamamlayıcı beyanın verildiği tarihten itibaren gecikme zammı oranında',
    'Beyannamenin tescil tarihinden itibaren kanuni faiz oranında',
    'Tamamlayıcı beyan süresinin bittiği tarihten itibaren tecil faizi oranında',
    'Yükümlülüğün başladığı tarihten itibaren kanuni faiz oranında'],
 tuzak=False,
 g='İstisnai kıymetle beyanda tamamlayıcı beyanın süresinde verilmemesi nedeniyle zamanında ödenmeyen vergiler için, serbest dolaşıma giriş beyannamesinin tescil tarihinden itibaren 6183 sayılı Kanuna göre belirlenen gecikme zammı oranında gecikme faizi tahsil edilir. Tamamlayıcı beyanın verildiği tarih faizin değil, bu beyana isabet eden vergilerde zamanaşımının başlangıcıdır; kanuni faiz ve tecil faizi bu hükümde öngörülmemiştir. (MD GY 53/4, 53/7)',
 kanit='12-KIYMET VE KAPLAR.txt | eşyanın serbest dolaşıma girişine ilişkin beyannamenin tescil tarihinden itibaren 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanun hükümlerine göre belirlenen gecikme zammı oranında gecikme faizi tahsil edilir || 12-KIYMET VE KAPLAR.txt | zamanaşımı tamamlayıcı beyanın verildiği tarihten itibaren başlar'),

dict(id='D7-052', cikmis='2022/52', konu='Gümrük Kıymeti', tip='T1+T2', z='Z',
 madde='Gümrük Yönetmeliği m.45/1-c, m.45/1-ç, m.45/1-d',
 cek='Kısmi alımda orantılı fiyat kısmi kayıp ve hasarda da uygulanır; sonradan fiyat düzeltmesinde kusurun fiyatta dikkate alınmamış olması gerekir.',
 kok=['Gümrük Yönetmeliğine göre satış bedeli yönteminde fiilen ödenen fiyatın belirlenmesine ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Beyan edilen eşya, tek işlemde satın alınan daha büyük miktardaki aynı eşyanın bir kısmı ise fiyat, toplam fiyatın beyan edilen miktarın toplam miktara oranı kadarıdır.',
      'II. Bu orantılı fiyat hesabı sevkiyatın kısmi kaybında uygulanır; eşyanın serbest dolaşıma girişten önce hasara uğramasında uygulanmaz.',
      'III. Eşyanın serbest dolaşıma giriş rejimi için beyan edilmesi, Türkiye\'ye ihraç amacıyla satıldığının kabulü için yeterlidir.',
      'IV. Serbest dolaşıma girişten sonra garanti nedeniyle alıcı lehine yapılan fiyat düzeltmesi, kusurun satış fiyatında dikkate alınmış olması şartıyla kıymette dikkate alınır.',
      'Yukarıdaki ifadelerden hangileri [[yanlıştır]]?'],
 d='II ve IV', c=['Yalnız II', 'Yalnız IV', 'I ve II', 'II ve III'],
 opts=['Yalnız II', 'Yalnız IV', 'I ve II', 'II ve III', 'II ve IV'],
 tuzak=False,
 g='Kısmi alımda toplam fiyatın miktar oranında paylaştırılması doğrudur ve bu işlem sevkiyatın kısmi kaybında olduğu gibi eşyanın serbest dolaşıma girişten önce hasara uğramasında da uygulanır; bu nedenle II yanlıştır. Sonradan yapılan fiyat düzeltmesinin dikkate alınabilmesi için kusurun satış fiyatının belirlenmesinde dikkate alınmamış olması gerektiğinden IV de yanlıştır; serbest dolaşıma giriş beyanının ihraç amaçlı satış için yeterli sayılmasına ilişkin III doğrudur. (MD GY 45/1-c, 45/1-ç, 45/1-d)',
 kanit='12-KIYMET VE KAPLAR.txt | Bu işlem, sevkıyatın kısmi kaybı veya kıymeti belirlenecek eşyanın serbest dolaşıma girişten önce hasara uğraması halinde de uygulanır. || 12-KIYMET VE KAPLAR.txt | eşyada mevcut kusurun satış sırasında satış fiyatının belirlenmesinde dikkate alınmamış olduğunun || 12-KIYMET VE KAPLAR.txt | satış konusu eşyanın serbest dolaşıma giriş rejimi için beyan edilmesi, bunların Türkiye\'ye ihraç amacıyla satıldığının kabul edilmesi için yeterli sayılır'),

dict(id='D7-053', cikmis='2022/53', konu='Gümrük Kıymeti', tip='T1', z='Z',
 madde='Gümrük Yönetmeliği m.49/1, m.49/3, m.49/4, m.52/2; 4458 sayılı Gümrük Kanunu m.25/2-d',
 cek='Hesaplanmış kıymette genel giderler, malzeme ve imalat bedelleri dışında kalan üretim ve ihraç amaçlı satışla ilgili giderlerdir; malzeme-imalat bunlara dahil değildir.',
 kok=['4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliğine göre, hesaplanmış kıymet yönteminin uygulanmasına ve bu yöntemde kıymete dahil edilen unsurlara ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Hesaplanmış kıymete dahil edilen genel giderler, malzeme ve imalat işlemlerinin bedelleri de dahil olmak üzere eşyanın üretimi ve ihraç amaçlı satışı ile ilgili tüm doğrudan veya dolaylı giderleri ifade eder.',
 c=['Yöntemin uygulanabilmesi için ithalatçının gerekli bilgi ve belgeleri ibraz etmesi ve bunların doğruluğunu ispata hazır olduğunu üretici ülke makamlarından alacağı belgeyle tevsik etmesi gerekir.',
    'İdarece ithalatçının ibraz ettiği bilgiler dışında bilgi kullanılmışsa, talep üzerine beyan sahibi gizlilik hükmüne uyulmak kaydıyla bilginin kaynağı ve yapılan hesaplama hakkında bilgilendirilir.',
    'Kâr ve genel gider unsuru, Türkiye\'ye ihraç edilmek üzere ihraç ülkesindeki üreticilerce üretilen aynı sınıf veya cins eşyanın satışında mutat olan kâr ve genel giderlere eşit tutardır.',
    'Finansman anlaşması uyarınca alıcının üstlendiği faiz giderlerinin kıymete dahil edilmemesine ilişkin hüküm, gerekli uyarlamalar yapılarak hesaplanmış kıymet yönteminde de uygulanır.'],
 tuzak=True,
 g='Yönetmelikte genel giderler, malzeme ve imalat bedellerinin dışında kalan ve eşyanın üretimi ile ihraç amaçlı satışıyla ilgili doğrudan veya dolaylı giderler olarak tanımlanır; malzeme ve imalat bedellerinin genel giderlere dahil olduğu ifadesi yanlıştır. Üretici ülke makamlarından alınacak belgeyle tevsik şartı ve idarenin kullandığı bilginin kaynağı hakkında talep üzerine bilgilendirme yükümlülüğü Yönetmelikte aynen yer alır; faiz giderine ilişkin hüküm de satış bedeli dışındaki yöntemlerde uygulanır. (MD GY 49/1, 49/3, 49/4, 52/2; GK 25/2-d)',
 kanit='12-KIYMET VE KAPLAR.txt | İkinci fıkranın (b) bendinde sayılan genel giderler, ikinci fıkranın (a) bendinde sayılan giderlerin dışında kalan ve eşyanın üretimi ve ihraç amaçlı satışı ile ilgili doğrudan veya dolaylı giderleri ifade eder. || 12-KIYMET VE KAPLAR.txt | bu bilgi ve belgelerin doğruluğunu ispata hazır olduğunu üretici ülke makamlarından alacağı belge ile tevsik etmesi gerekir || 12-KIYMET VE KAPLAR.txt | gerekli uyarlamalar yapılarak, gümrük kıymetinin satış bedeli yöntemi dışındaki yöntemlere göre belirlendiği durumlarda da uygulanır'),

dict(id='D7-055', cikmis='2022/55', konu='Gümrük Kıymeti', tip='T6', z='OÜ',
 madde='Gümrük Yönetmeliği m.43/1-f',
 cek='Advalorem sisteme göre gümrük vergisinin hesaplanmasına esas teşkil edecek eşya kıymeti, ithal eşyasının gümrük kıymetidir.',
 kok=['Gümrük Yönetmeliğinin gümrük kıymetine ilişkin tanımlar bölümünde yer alan bir kavram şöyle tanımlanmıştır:',
      '“İthal eşyası üzerinden advalorem sisteme göre gümrük vergisinin hesaplanmasına esas teşkil edecek eşya kıymeti”',
      'Yukarıda tanımlanan kavram aşağıdakilerden hangisidir?'],
 d='Gümrük kıymeti', c=['Gümrüklenmiş değer', 'İstisnai kıymet', 'Emsal kıymet', 'Hesaplanmış kıymet'],
 tuzak=False,
 g='Yönetmelik, ithal eşyası üzerinden advalorem sisteme göre gümrük vergisinin hesaplanmasına esas teşkil edecek eşya kıymetini ithal eşyasının gümrük kıymeti olarak tanımlar. Gümrüklenmiş değer, ithal eşyasında CIF kıymet ile gümrük vergileri toplamını ifade eder; hesaplanmış kıymet ise kıymet tespit yöntemlerinden biridir. (MD GY 43/1-f)',
 kanit='12-KIYMET VE KAPLAR.txt | f) İthal eşyasının gümrük kıymeti: İthal eşyası üzerinden advalorem sisteme göre gümrük vergisinin hesaplanmasına esas teşkil edecek eşya kıymetini, || 1-TANIMLAR.txt | ithal eşyası için eşyanın CIF kıymeti ile gümrük vergileri toplamını'),

dict(id='D7-098', cikmis='2022/98', konu='Gümrük Kıymeti', tip='T2', z='Z',
 madde='Gümrük Yönetmeliği m.43/1-c, m.43/4, m.47/3, m.47/5',
 cek='Aynı üreticinin benzer eşyası yoksa farklı üreticininki dikkate alınır; aynı sınıf/cins ifadesi aynı-benzer eşyayı kapsar; nakliye farkı düzeltilir.',
 kok=['Gümrük Yönetmeliğine göre benzer eşyanın satış bedeli yöntemine ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Kıymeti belirlenecek eşya ile aynı kişi tarafından üretilmiş benzer eşya yoksa, farklı kişi tarafından üretilmiş benzer eşya dikkate alınır.',
      'II. Nakliye ve sigorta giderleri satış bedeline dahil ise, mesafe ve nakliyat türünden doğan ciddi farklılıklar için satış bedelinde düzeltme yapılmaz.',
      'III. Belli bir sanayi sektöründe üretilen bir grup veya dizi eşyayı ifade eden “aynı sınıf veya cins eşya” deyimi, benzer eşyayı da kapsar.',
      'IV. Kullanılacak benzer eşya bedeli, önceden kıymeti herhangi bir yönteme göre belirlenmiş ve düzeltme yapılmaksızın alınan gümrük kıymetidir.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I ve III', c=['I ve IV', 'II ve IV', 'I, II ve III', 'I, III ve IV'],
 opts=['I ve III', 'I ve IV', 'II ve IV', 'I, II ve III', 'I, III ve IV'],
 tuzak=False,
 g='Aynı kişi tarafından üretilmiş benzer eşya yoksa farklı kişinin ürettiği benzer eşya dikkate alınır ve “aynı sınıf veya cins eşya” deyimi aynı veya benzer eşyayı da kapsar; I ve III doğrudur. Nakliye ve sigortanın satış bedeline dahil olduğu hâllerde mesafe ve nakliyat türünden doğan ciddi farklılıklar için düzeltme yapıldığından II, kullanılacak bedel önceden satış bedeli yöntemine göre belirlenip düzeltilmiş kıymet olduğundan IV yanlıştır. (MD GY 43/1-c, 43/4, 47/3, 47/5)',
 kanit='12-KIYMET VE KAPLAR.txt | Kıymeti belirlenecek eşya ile aynı kişi tarafından üretilmiş aynı veya benzer eşya bulunmadığı takdirde, farklı kişi tarafından üretilmiş eşya dikkate alınır. || 12-KIYMET VE KAPLAR.txt | mesafe ve nakliyatın türünden doğan ciddi farklılıklar göz önüne alınarak satış bedelinde düzeltme yapılır || 12-KIYMET VE KAPLAR.txt | benzer eşyanın satış bedeli, önceden kıymeti satış bedeli yöntemine göre belirlenmiş ve bu maddenin ikinci ve üçüncü fıkralarına göre düzeltilmiş gümrük kıymetidir || 12-KIYMET VE KAPLAR.txt | Belli bir sanayi sektöründe üretilen bir grup veya bir dizi eşya kapsamına giren eşyayı (bu ifade aynı veya benzer eşyayı da kapsar)'),

dict(id='D7-099', cikmis='2022/99', konu='Gümrük Kıymeti', tip='T1', z='OÜ',
 madde='Gümrük Yönetmeliği m.55/1',
 cek='Taraflardan yalnızca birinin üçüncü kişiyi kontrol etmesi ilişki sayılmaz; her ikisinin üçüncü kişice kontrolü veya birlikte üçüncü kişiyi kontrolü ilişkidir.',
 kok=['Gümrük Yönetmeliğine göre, gümrük kıymetinin belirlenmesinde alıcı ile satıcı arasındaki ilişkinin varlığının kabul edileceği durumlara ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Taraflardan yalnızca birinin bir üçüncü kişiyi doğrudan veya dolaylı olarak kontrol etmesi hâlinde de kıymetin belirlenmesinde alıcı ile satıcı arasında ilişki bulunduğu kabul edilir.',
 c=['Alıcı ile satıcı arasındaki ilişkinin varlığı yalnızca Yönetmelikte sayılan durumlardan birinin bulunması hâlinde kabul edilir; bu durumlar dışında kalan ticari bağlar ilişki sayılmaz.',
    'Alıcı ile satıcının her ikisinin de doğrudan veya dolaylı olarak aynı üçüncü bir kişi tarafından kontrol edilmesi hâlinde, aralarında doğrudan bir bağ bulunmasa da ilişki kabul edilir.',
    'Alıcı ile satıcının birlikte, bir üçüncü kişiyi doğrudan veya dolaylı olarak kontrol etmeleri hâlinde gümrük kıymetinin belirlenmesinde aralarında ilişki bulunduğu kabul edilir.',
    'Alıcı ile satıcının birbirlerinin memuru veya idarecileri olmaları hâlinde, aralarında bir sermaye bağı bulunmasa dahi gümrük kıymetinin belirlenmesinde ilişkinin varlığı kabul edilir.'],
 tuzak=False,
 g='Yönetmelik ilişkinin varlığını yalnızca saydığı durumlarda kabul eder; bu durumlar arasında her ikisinin bir üçüncü kişi tarafından kontrol edilmesi ve her ikisinin birlikte bir üçüncü kişiyi kontrol etmesi vardır, ancak taraflardan yalnızca birinin üçüncü bir kişiyi kontrol etmesi sayılmamıştır. Memur veya idareci olma ilişkisi ise sermaye bağından bağımsız olarak ayrı bir ilişki hâlidir. (MD GY 55/1)',
 kanit='12-KIYMET VE KAPLAR.txt | alıcı ile satıcı arasındaki ilişkinin varlığı yalnızca aşağıdaki durumlarda kabul edilir || 12-KIYMET VE KAPLAR.txt | e) Her ikisinin de doğrudan veya dolaylı olarak bir üçüncü kişi tarafından kontrol edilmesi, || 12-KIYMET VE KAPLAR.txt | f) Her ikisinin birlikte, bir üçüncü kişiyi doğrudan veya dolaylı olarak kontrol etmesi,'),
]
