# K12 — Kaçakçılıkla mücadele (5607 ve ikincil düzenlemeleri)
Q = [
# ---------------- DENEME 6 ----------------
dict(id='D6-091', cikmis='2021/91', konu='Kaçakçılık', tip='T4', z='OÜ',
 madde='Kaçakçılık Türleri ile İlgili Mahkûmiyet Hükmü Kesinleşenlerin Kamuoyuna İlan Edilmesine Dair Yönetmelik m.3/1-b, 4/2, 5 (mülga), 6/2, 7/4',
 cek='İlan edilecek hükümlülere dair kararı Gümrükler Muhafaza Genel Müdürlüğü verir, Bakan onayıyla icra edilir; Komisyon usulü kaldırılmıştır.',
 kok=['Kaçakçılık Türleri ile İlgili Mahkûmiyet Hükmü Kesinleşenlerin Kamuoyuna İlan Edilmesine Dair Yönetmeliğe göre aşağıdakilerden hangisi doğrudur?'],
 d='Mahkûmiyet hükmü kesinleşenlerden belirlenen ölçütlere göre ilan edileceklere dair karar Gümrükler Muhafaza Genel Müdürlüğünce verilir ve Bakan onayı ile icra edilir.',
 c=['Kamuoyuna ilan edilecek hükümlüler, Bakanlık bünyesinde oluşturulan ve yılda dört defa toplanan Komisyon tarafından belirlenir ve Komisyonun bu kararı Bakan onayı ile icra edilir.',
    'İlk derece mahkemesince verilen mahkûmiyet kararı, kanun yolu incelemesinin sonucu beklenmeksizin Bakanlık resmî internet sitesinde üç ay süreyle kamuoyuna ilan edilebilir.',
    'Diğer eşya türlerinde ilana esas alınan gümrüklenmiş değer tutarı, her yıl Ticaret Bakanlığınca belirlenen yeniden değerleme oranında artırılarak ilan kararında esas alınır.',
    'İlan metninde hükümlünün adı soyadı ile yakalanan eşyanın cinsi ve miktarına ilişkin bilgiler yer alır; ancak ilanın yayımlanma süresine ilan metninde yer verilmez.'],
 tuzak=False,
 g='Yönetmeliğe göre mahkûmiyet hükmü kesinleşenlerden ilan edileceklere dair karar Gümrükler Muhafaza Genel Müdürlüğünce verilir ve Bakan onayı ile icra edilir; bu kararı veren Komisyona ilişkin hüküm yürürlükten kaldırılmıştır. İlan için mahkûmiyet hükmünün kesinleşmesi gerektiğinden ilk derece kararının ilanı mümkün değildir; yeniden değerleme oranını Hazine ve Maliye Bakanlığı belirler ve ilan metninde yayımlanma süresi de yer alır. (MD İlan Yön. 3/1-b, 4/2, 6/2, 7/4)',
 kanit='kacakcilik_turleri_ile_ilgili_mahkumiyet_hukmu_kesinlesenlerin_kamuoyuna_ilan_edilmesine_dair_yonetmelik.txt | ilan edileceklere dair karar Genel Müdürlükçe verilir ve Bakan Onayı ile icra edilir || kacakcilik_turleri_ile_ilgili_mahkumiyet_hukmu_kesinlesenlerin_kamuoyuna_ilan_edilmesine_dair_yonetmelik.txt | Genel Müdürlük: Gümrükler Muhafaza Genel Müdürlüğünü'),

dict(id='D6-092', cikmis='2021/92', konu='Kaçakçılık', tip='T6', z='Z',
 madde='5607 Sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği m.3/1-ğ, 3/1-ı; 5607 sayılı Kanun m.2/1-b, 15',
 cek='Kaçak akaryakıtın değeri: ihraçta FOB, ithalde CIF kıymeti veya varsa mahkemece belirlenen değerdir; gümrük vergileri eklenmez.',
 kok=['Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliğinde “5607 sayılı Kanun uyarınca elkonulan akaryakıtın ihraç eşyası olması halinde FOB kıymetini, ithal eşyası olması halinde CIF kıymetini veya varsa mahkemece belirlenmiş değerini” ifade ettiği belirtilen kavram aşağıdakilerden hangisidir?'],
 d='Kaçak akaryakıtın değeri',
 c=['Akaryakıtın gümrüklenmiş değeri', 'Akaryakıtın kaim değeri', 'Akaryakıtın rayiç bedeli', 'Tahmini satış bedeli'],
 tuzak=False,
 g='Yönetmelik, elkonulan akaryakıtın ihraç eşyası olması hâlinde FOB, ithal eşyası olması hâlinde CIF kıymetini veya varsa mahkemece belirlenmiş değerini “kaçak akaryakıtın değeri” olarak tanımlar. Gümrüklenmiş değer ve ona eşit sayılan kaim değer CIF veya FOB kıymetine gümrük vergilerinin eklenmesiyle bulunur; rayiç bedel ise temin edildiği yer ve tarihteki normal alım ve satım bedelidir. (MD Akaryakıt Yön. 3/1-ğ, 3/1-ı; 5607 2/1-b, 15)',
 kanit='kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Kanun uyarınca elkonulan akaryakıtın ihraç eşyası olması halinde FOB kıymetini, ithal eşyası olması halinde CIF kıymetini veya varsa mahkemece belirlenmiş değerini'),

dict(id='D6-093', cikmis='2021/93', konu='Kaçakçılık', tip='T1', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.19/2, 19/3, 19/4, 22/1, 22/2',
 cek='Görevliler operasyon gerektiren olaylardan haberdar olunca görevlerine başlar, aynı anda mahallin en büyük mülkî amirine bilgi verir; izin alınmaz.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa göre kaçakçılığı önleme, izleme ve araştırmakla görevli olanların yetki ve yükümlülüklerine ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Kaçakçılığı önleme, izleme ve soruşturmakla görevli olanlar, operasyon gerektiren kaçakçılık olaylarından haberdar olduklarında kanunî görevlerine başlayabilmek için önceden mahallin en büyük mülkî amirinin iznini almak zorundadır.',
 c=['Görevlilerin bu Kanun kapsamındaki suçlarla ilgili bilgi ve belge talepleri, kamu veya özel, gerçek veya tüzel kişilerce, savunma hakkına ilişkin hükümler saklı kalmak kaydıyla eksiksiz olarak karşılanmak zorundadır.',
    'Kaçakçılık suçlarını ihbar edenlerin kimliği, izinleri olmadıkça veya ihbarın niteliği haklarında suç oluşturmadıkça açıklanamaz ve bu kişiler hakkında tanıkların korunmasına ilişkin hükümler uygulanır.',
    'Kaçakçılığı önleme, izleme ve araştırmakla yükümlü olanlar, gümrük bölgesindeki her nevi deniz araçlarına yanaşıp yük ve belgelerini incelemeye yetkili olup yanaşmaya izin vermeyerek kaçan araçlara durması ihtar olunur.',
    'Belirlenen kapı ve yollar dışından gümrük bölgesine girmek isteyen kişinin “dur” uyarısına uymaması hâlinde, uyarı havaya ateş edilmek suretiyle yinelenir.'],
 tuzak=True,
 g='Kanuna göre görevliler, operasyon gerektiren kaçakçılık olaylarından haberdar olduklarında kanunî görevlerini yapmaya başlar ve aynı zamanda mahallin en büyük mülkî amirine de bilgi verir; mülkî amirden önceden izin alınması öngörülmemiştir. Bilgi ve belge taleplerinin savunma hakkı saklı kalmak kaydıyla eksiksiz karşılanması ile muhbir kimliğinin açıklanmaması Kanunda aynen yer alan hükümlerdir. (MD 5607 19/2-4, 22/1-2)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | operasyon gerektiren kaçakçılık olaylarından haberdar olduklarında kanunî görevlerini yapmaya başlar ve aynı zamanda mahallin en büyük mülkî amirine de bilgi verirler'),

dict(id='D6-094', cikmis='2021/94', konu='Kaçakçılık', tip='T2', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.20/1, 20/2',
 cek='Tutanağın ilgililere okunduğu veya verildiği husus tutanağa yazılarak imza ettirilir; imzadan kaçınma nedenleri tutanağa geçirilir.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa göre kaçakçılık fiillerinin izlenmesine ilişkin tutanaklarla ilgili aşağıdaki ifadeler veriliyor:',
      'I. Tutanakta tarih, yer ve düzenleyenlerin unvan ve isimlerinin yanı sıra hâkim kararının tarih ve sayısına da yer verilir.',
      'II. İşlemde hazır bulunan ilgililerin tutanağı imzalamaktan kaçınması hâlinde tutanak hükümsüz sayılır ve yeniden düzenlenir.',
      'III. Tutanağın ilgilileri ilgilendiren kısımları, onanmak üzere kendilerine okunur veya okumaları için kendilerine verilir.',
      'IV. Tutanağın ilgilileri ilgilendiren kısımlarının okunduğu veya okumaları için kendilerine verildiği husus tutanağa yazılmaz; yalnızca ilgililerin imzası alınır.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I ve III', c=['Yalnız I', 'II ve IV', 'I, III ve IV', 'II, III ve IV'],
 opts=['Yalnız I', 'I ve III', 'II ve IV', 'I, III ve IV', 'II, III ve IV'],
 tuzak=False,
 g='Tutanakta tarih, yer, düzenleyenlerin unvan ve isimleri ile hâkim kararının tarih ve sayısı bulunur; ilgilileri ilgilendiren kısımlar onanmak üzere okunur veya okumaları için verilir, bu nedenle I ve III doğrudur. İmzadan kaçınma hâlinde tutanak hükümsüz sayılmaz, kaçınmanın nedenleri tutanağa geçirilir; okuma veya verme işlemi de tutanağa yazılarak ilgililere imza ettirilir, bu nedenle II ve IV yanlıştır. (MD 5607 20/1-2)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Bu husus tutanağa yazılarak ilgililere imza ettirilir. İmzadan kaçınma halinde nedenleri tutanağa geçirilir'),

dict(id='D6-095', cikmis='2021/95', konu='Kaçakçılık', tip='T7', z='Z',
 madde='5607 Sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği m.5/4, 16/1, 16/2',
 cek='İl özel idarelerinde kaçak akaryakıt tahsis kararlarını genel sekreter ya da görevlendireceği yardımcısı onaylar.',
 kok=['Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliğine göre, il özel idarelerinde kaçak akaryakıtın tahsis kararlarını kim onaylar?'],
 sapma='kök, yönetmeliğin tam adı nedeniyle 120 karakteri aşıyor',
 d='Genel sekreter ya da görevlendireceği yardımcısı',
 c=['Vali ya da görevlendireceği bir vali yardımcısı', 'Tahsis komisyonu başkanı ya da görevlendireceği üye', 'Defterdar ya da görevlendireceği defterdar yardımcısı', 'Yatırım izleme ve koordinasyon başkanı ya da yardımcısı'],
 tuzak=False,
 g='Yönetmeliğe göre tahsis kararı en az üç kişiden oluşan tahsis komisyonunca alınır ve il özel idarelerinde genel sekreter ya da görevlendireceği yardımcısı tarafından onaylanır. Valinin onayı, il özel idaresine teslimi mümkün olmayan akaryakıtın başka depolara konulmasında aranır; yatırım izleme ve koordinasyon başkanlığı ise il özel idaresi bulunmayan yerlerde görev yapar. (MD Akaryakıt Yön. 5/4, 16/1-2)',
 kanit='kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Tahsis kararları il özel idarelerinde genel sekreter, ya da görevlendireceği yardımcısı tarafından onaylanır'),

dict(id='D6-096', cikmis='2021/96', konu='Kaçakçılık', tip='T1', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.3/10, 3/16, 3/18, 3/20, 3/21',
 cek='Akaryakıt, tütün ve alkol artırım fıkrasının uygulanması suretiyle verilecek ceza üç yıldan az olamaz (asgari sınır beş yıl değildir).',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa göre tütün mamulleri, alkollü içkiler ve akaryakıta ilişkin kaçakçılık fiillerine uygulanacak cezalarla ilgili aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Kaçakçılık suçunun konusunu oluşturan eşyanın akaryakıt, tütün mamulleri veya alkollü içki olması hâlinde cezalar yarısından iki katına kadar artırılır; ancak bu artırım sonucunda verilecek ceza beş yıldan az olamaz.',
 c=['Tütün mamulleri ve alkollü içkilerin ambalajlarına kamu kurumlarınca uygulanan bandrol, etiket veya hologramın taklitlerini imal eden kişi, üç yıldan altı yıla kadar hapis ve yirmi bin güne kadar adlî para cezası ile cezalandırılır.',
    'Ticari amaçla makaron veya yaprak sigara kâğıdını, içine kıyılmış tütün, parçalanmış tütün ya da tütün harici herhangi bir madde doldurulmuş olarak satan kişiye üç yıldan altı yıla kadar hapis cezası verilir.',
    'Tarım ve Orman Bakanlığından yetki belgesi almadan veya bildirimde bulunmadan tütün ticareti yapan kişiye, adlî para cezası öngörülmeksizin iki yıldan beş yıla kadar hapis cezası verilir.',
    'Bandrolsüz tütün mamullerini ticari amaçla bulunduran kişi bakımından ürünlerin kaçak olarak yurda sokulduğunun anlaşılması hâlinde, akaryakıt, tütün ve alkole ilişkin artırım hükmüne istinaden cezaya hükmolunur.'],
 tuzak=False,
 g='Kanuna göre kaçakçılık suçunun konusunu akaryakıt, tütün, tütün mamulleri, makaron, yaprak sigara kâğıdı, etil alkol, metanol veya alkollü içkilerin oluşturması hâlinde cezalar yarısından iki katına kadar artırılır; ancak bu artırımla verilecek ceza beş yıldan değil üç yıldan az olamaz. Taklit bandrol imali için üç yıldan altı yıla kadar hapis ve yirmi bin güne kadar adlî para cezası, yetki belgesi almadan tütün ticareti için iki yıldan beş yıla kadar hapis cezası öngörüldüğünden bu ifadeler doğrudur. (MD 5607 3/10, 3/16, 3/18, 3/20, 3/21)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | fıkralara göre verilecek cezalar yarısından iki katına kadar artırılır, ancak bu fıkranın uygulanması suretiyle verilecek ceza üç yıldan az olamaz || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | almadan veya bildirimde bulunmadan tütün ticareti yapanlara iki yıldan beş yıla kadar hapis cezası verilir'),

dict(id='D6-097', cikmis='2021/97', konu='Kaçakçılık', tip='T2', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.9/1, 9/2, 10/1',
 cek='Gümrük salonu ve kapılarında kuşkulanılan kişiler gümrük görevlilerince aranabilir, bulunan kaçak eşyaya derhal el konulur; diğer aramalar CMK uyarınca yapılır.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa göre arama ve elkoymaya ilişkin şu ifadeler veriliyor:',
      'I. Kaçak eşya, silah, patlayıcı ve uyuşturucu bulunduğundan şüphe edilen kap, ambalaj ve taşıma araçları ile kişilerin üzerinde yapılacak arama ve elkoymalar Ceza Muhakemesi Kanunu uyarınca yapılır.',
      'II. Gümrük salonları ve kapılarında kaçak eşya sakladığından kuşkulanılan kişilerin üzeri, eşyası ve araçları gümrük görevlilerince aranabilir.',
      'III. Gümrük salonlarında yapılan arama sonucunda tespit edilen kaçak eşyaya, Cumhuriyet savcısının yazılı emri alınmadıkça el konulamaz.',
      'IV. Bu Kanunda tanımlanan suçların işlenmesinde kullanılan taşıtlara Ceza Muhakemesi Kanunu hükmüne göre el konulur.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I, II ve IV', c=['Yalnız II', 'I ve II', 'II ve IV', 'II, III ve IV'],
 opts=['Yalnız II', 'I ve II', 'II ve IV', 'I, II ve IV', 'II, III ve IV'],
 tuzak=False,
 g='Kanuna göre şüpheli kap, ambalaj, taşıma araçları ve kişiler üzerindeki arama ve elkoymalar Ceza Muhakemesi Kanunu uyarınca yapılır; gümrük salonları ve kapılarında kaçak eşya sakladığından kuşkulanılan kişiler gümrük görevlilerince aranabilir ve suçlarda kullanılan taşıtlara Ceza Muhakemesi Kanunu hükmüne göre el konulur, bu nedenle I, II ve IV doğrudur. Gümrük salonlarındaki arama sonucunda tespit edilen kaçak eşyaya savcı emri beklenmeksizin derhal el konulduğundan III yanlıştır. (MD 5607 9/1-2, 10/1)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | gümrük kontrolü amacıyla gümrük görevlilerince aranabilir. Yapılan arama sonucunda tespit edilen kaçak eşyaya derhal elkonulur || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | sayılı Ceza Muhakemesi Kanunu uyarınca yerine getirilir'),

dict(id='D6-098', cikmis='2021/98', konu='Kaçakçılık', tip='T1', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.10/3, 10/4, 13/1, 13/2, 16/1',
 cek='Etkin pişmanlık nedeniyle cezaya hükmolunmaması veya kamu davasının düşmesi, suç konusu eşyanın müsaderesine engel teşkil etmez.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa göre müsadere ve taşıtların tasfiyesine ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Etkin pişmanlık nedeniyle fail hakkında cezaya hükmolunmaması veya kamu davasının düşmesine karar verilmesi hâlinde, suç konusu eşya hakkında müsadere hükümleri uygulanmaz ve eşya sahibine iade edilir.',
 c=['Bu Kanundaki suçlarla ilgili olarak Türk Ceza Kanununun eşya ve kazanç müsaderesine ilişkin hükümleri uygulanır; ancak kaçak eşya taşınan aracın müsaderesi Kanunda sayılan koşullardan birine bağlıdır.',
    'Alıkonulmayan taşıt, gümrük idaresince yapılan tebligattan itibaren doksan gün içinde masraflar karşılanarak sahibince teslim alınmazsa kovuşturma sonucu beklenmeksizin tasfiye edilir.',
    'Taşıt satış suretiyle tasfiye edilirse, satış gelirinden muhafaza ve satış masrafları karşılandıktan sonra kalan miktar kovuşturma sonucuna göre işlem yapılmak üzere emanet hesabına alınır.',
    'Bu Kanunda tanımlanan suçların konusunu oluşturması dolayısıyla müsadere yaptırımının uygulanabileceği eşya sahibine iade edilemez ve bu eşya hakkında Kanundaki usule göre tasfiye işlemi yapılır.'],
 tuzak=True,
 g='Kanuna göre etkin pişmanlık nedeniyle fail hakkında cezaya hükmolunmaması veya kamu davasının düşmesine karar verilmesi, suç konusu eşya ile ilgili müsadere hükümlerinin uygulanmasına engel teşkil etmez; bu nedenle eşyanın sahibine iadesi söz konusu olmaz. Alıkonulmayan taşıtın tebligattan itibaren doksan gün içinde teslim alınmaması hâlinde tasfiyesi ve satış gelirinden masraflar düşüldükten sonra kalan miktarın emanet hesabına alınması Kanunda aynen yer alır. (MD 5607 10/3-4, 13/1-2, 16/1)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Etkin pişmanlık nedeniyle fail hakkında cezaya hükmolunmaması veya kamu davasının düşmesine karar verilmesi, sadece suç konusu eşya ile ilgili olarak müsadere hükümlerinin uygulanmasına engel teşkil etmez'),

dict(id='D6-099', cikmis='2021/99', konu='Kaçakçılık', tip='T2', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.4/9, 16/A-6, 23/5, 24',
 cek='Kaçak akaryakıt tasfiyesi yönetmeliğini EPDK görüşüyle Ticaret ve İçişleri Bakanlıkları müştereken çıkarır; ilan, ikramiye ve laboratuvar yönetmeliklerinde makam farklıdır.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununda öngörülen yönetmeliklere ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Kaçak akaryakıtın tasfiyesine ilişkin yönetmelik, Enerji Piyasası Düzenleme Kurumunun görüşü alınarak Ticaret Bakanlığı ve İçişleri Bakanlığınca müştereken çıkarılır.',
      'II. Kamuoyuna ilanın süresi ve nasıl yapılacağı İçişleri Bakanlığınca çıkarılan yönetmelikle belirlenir.',
      'III. Müşterek operasyonlarda ikramiye ödenmesine ilişkin usul ve esaslar yalnızca İçişleri Bakanlığınca çıkarılan yönetmelikle düzenlenir.',
      'IV. Kriminal laboratuvarların çalışma usul ve esasları Adalet Bakanlığınca çıkarılan yönetmelikle belirlenir.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='Yalnız I', c=['Yalnız III', 'I ve II', 'I ve III', 'II ve IV'],
 opts=['Yalnız I', 'Yalnız III', 'I ve II', 'I ve III', 'II ve IV'],
 tuzak=False,
 g='Kaçak akaryakıtın tasfiyesine ilişkin yönetmelik, Enerji Piyasası Düzenleme Kurumunun görüşü alınarak Ticaret Bakanlığı ve İçişleri Bakanlığınca müştereken çıkarılır; bu nedenle yalnız I doğrudur. İlan yönetmeliği Gümrük ve Ticaret Bakanlığınca, ikramiye yönetmeliği Maliye ve Millî Savunma bakanlıklarının görüşü alınarak Gümrük ve Ticaret Bakanlığı ile İçişleri Bakanlığınca müştereken, kriminal laboratuvar yönetmeliği ise Gümrük Müsteşarlığınca çıkarılır. (MD 5607 4/9, 16/A-6, 23/5, 24)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Enerji Piyasası Düzenleme Kurumunun görüşü alınarak Ticaret Bakanlığı ve İçişleri Bakanlığı || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | Maliye ve Millî Savunma bakanlıklarının görüşü alınarak Gümrük ve Ticaret Bakanlığı ve İçişleri Bakanlığı tarafından müştereken çıkarılan || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | Bu laboratuvarların çalışma usûl ve esasları Gümrük Müsteşarlığınca çıkarılacak yönetmelikle belirlenir'),

dict(id='D6-100', cikmis='2021/100', konu='Kaçakçılık', tip='T9', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.3/2, 4/4, 5/1',
 cek='Meslek kolaylığıyla işlenen suçta ceza yarı oranında artırılır; haber alındıktan sonra yardım edene ceza üçte iki indirilir: 36→54→18 ay.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanunu kapsamında yürütülen bir kovuşturmada, gümrük müşaviri (K)’nın mesleğinin sağladığı kolaylıklardan yararlanarak, (L) firmasının yetkilisi (M) ile birlikte, firmaya ait eşyanın aldatıcı işlem ve davranışlarla gümrük vergileri kısmen ödenmeksizin ülkeye sokulması fiiline iştirak ettiği anlaşılmıştır. Hâkim, (K) için temel hapis cezasını 3 yıl olarak belirlemiştir. (K), fiilin resmî makamlarca haber alınmasından sonra fiilin bütünüyle ortaya çıkmasına hizmet ve yardım etmiştir.',
      'Buna göre, Kanunda öngörülen artırım ve indirim uygulandığında (K) hakkında verilecek hapis cezası **kaç ay** olur?'],
 d='18 ay', c=['12 ay', '16 ay', '27 ay', '54 ay'], opts=['12 ay', '16 ay', '18 ay', '27 ay', '54 ay'],
 tuzak=False,
 g='Suç meslek ve sanatın sağladığı kolaylıklardan yararlanılarak işlendiğinden 36 aylık temel ceza yarı oranında artırılarak 54 aya çıkar; haber alındıktan sonra fiilin bütünüyle ortaya çıkmasına yardım edildiğinden bu ceza üçte iki oranında indirilerek 18 ay olur. Artırım uygulanmadan yapılan hesap 12 aya, artırımın üçte bir oranında yapılması 16 aya, indirimin yarı oranında yapılması 27 aya, indirimin hiç uygulanmaması ise 54 aya götürür; fiil iki kişiyle işlendiğinden üç kişiye bağlı artırım da söz konusu değildir. (MD 5607 4/4, 5/1)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | meslek ve sanatın sağladığı kolaylıklardan yararlanmak suretiyle işlenmesi halinde, verilecek ceza yarı oranında artırılır || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | fiilin bütünüyle ortaya çıkmasına hizmet ve yardım eden kişiye verilecek ceza üçte iki oranında indirilir'),

# ---------------- DENEME 7 ----------------
dict(id='D7-021', cikmis='2022/21', konu='Kaçakçılık', tip='T10', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.2/1-c, 23/2; 5607 Sayılı Kaçakçılıkla Mücadele Kanununa Göre İkramiye Ödenmesi Hakkında Yönetmelik m.4/1-c, 4/1-ç, 4/1-d, 4/1-e',
 cek='İkramiye Yönetmeliğinde CIF kıymet FOB + nakliye + sigortadır, gümrük vergisi içermez; el koyma ikramiyesine teknik ve istihbari katkı sağlayanlar da hak kazanır.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanunu ile bu Kanuna göre çıkarılan İkramiye Ödenmesi Hakkında Yönetmelikte yer alan bazı kavramlar ve tanımları aşağıda eşleştirilmiştir:',
      '1. Kaçak akaryakıt – 5607 sayılı Kanun hükümleri uyarınca kaçak olarak kabul edilen akaryakıt',
      '2. CIF kıymet – FOB kıymet üzerine Türkiye’deki giriş liman veya yerine kadar yapılan nakliye ve sigorta giderleri ile gümrük vergilerinin ilavesi ile oluşan kıymet',
      '3. FOB kıymet – Eşya için fiilen ödenen veya ödenecek ya da ödenebilecek bedel',
      '4. El koyma ikramiyesine hak kazanan – Kaçakçılığı önleme, izleme ve soruşturmakla görevli olanlardan yalnızca yakalama işlemine bizzat ve fiilen katılanlar',
      '5. Akaryakıt – Benzin, gaz yağı, jet yakıtı, motorin, fuel-oil, sıvılaştırılmış petrol gazları, doğal gaz gibi akaryakıt ürünleri ile akaryakıt yerine kullanılan petrol türevleri, bunların karışımları ve akaryakıt yerine kullanılan diğer ürünler',
      'Yukarıdaki eşleştirmelerden hangilerinde tanım [[yanlış]] verilmiştir?'],
 d='2 ve 4', c=['Yalnız 2', '1 ve 5', '2, 4 ve 5', '3, 4 ve 5'],
 opts=['Yalnız 2', '1 ve 5', '2 ve 4', '2, 4 ve 5', '3, 4 ve 5'],
 tuzak=False,
 g='İkramiye Ödenmesi Hakkında Yönetmelikte CIF kıymet, FOB kıymet üzerine Türkiye’deki giriş liman veya yerine kadar yapılan nakliye ve sigorta giderlerinin eklenmesiyle bulunur; gümrük vergileri bu kıymete dahil değildir. El koyma ikramiyesine yalnız yakalamaya bizzat katılanlar değil, iletişimin tespiti, teknik araçla izleme, bilgi toplama, analiz, fiziki takip veya planlama çalışmalarıyla katkı sağlayan görevliler de hak kazanır; bu nedenle 2 ve 4 yanlıştır. Kaçak akaryakıt, FOB kıymet ve akaryakıt tanımları mevzuattakiyle aynıdır. (MD 5607 2/1-c, 23/2; İkramiye Yön. 4/1-c, ç, d, e)',
 kanit="5607_sayili_kacakcilikla_mucadele_kanununa_gore_ikramiye_odenmesi_hakkinda_yonetmelik.txt | CIF kıymet: FOB kıymet üzerine Türkiye'deki giriş liman veya yerine kadar yapılan nakliye ve sigorta giderlerinin ilavesi ile oluşan kıymeti || 5607_sayili_kacakcilikla_mucadele_kanununa_gore_ikramiye_odenmesi_hakkinda_yonetmelik.txt | yakalama işlemine bizzat ve fiilen katılanlar ile yapılan soruşturmada iletişimin tespiti"),

dict(id='D7-022', cikmis='2022/22', konu='Kaçakçılık', tip='T8', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.5/2, 5/3, 13/2',
 cek='Suç örgüt faaliyeti çerçevesinde işlenmişse gümrüklenmiş değerin iki katını ödeyene etkin pişmanlık indirimi uygulanmaz.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanunu kapsamında yürütülen bir soruşturmada, (K)’nın üyesi olduğu suç örgütünün faaliyeti çerçevesinde, eşyayı aldatıcı işlem ve davranışlarla gümrük vergilerini kısmen ödemeksizin ülkeye soktuğu tespit edilmiştir. Daha önce kaçakçılık suçundan mahkûmiyeti bulunmayan (K), soruşturma evresi sona ermeden suç konusu eşyanın gümrüklenmiş değerinin iki katı kadar parayı Devlet Hazinesine ödemiştir.',
      'Buna göre, (K)’nın yaptığı ödemenin hukuki sonucuna ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='Suç bir örgütün faaliyeti çerçevesinde işlendiğinden, gümrüklenmiş değerin iki katının ödenmesine bağlanan etkin pişmanlık indirimi (K) hakkında uygulanmaz; bu nedenle ödeme, Kanunda öngörülen indirim sonucunu doğurmaz.',
 c=['Ödeme soruşturma evresi sona ermeden yapıldığından, (K) hakkında bu Kanunda tanımlanan kaçakçılık suçlarından dolayı verilecek ceza yarı oranında indirilir ve bu husus Cumhuriyet savcısınca ihtar edilir.',
    'Ödeme hüküm verilinceye kadar yapılmış sayılacağından, (K) hakkında kaçakçılık suçundan dolayı verilecek ceza üçte bir oranında indirilir ve bu husus kovuşturma evresinde hâkim tarafından sanığa ihtar edilir.',
    '(K), gümrüklenmiş değerin iki katını ödediğinden etkin pişmanlık göstermiş sayılır; hakkında cezaya hükmolunmaz ve suç konusu eşya hakkında müsadere hükümleri de uygulanmaz.',
    'Örgüt faaliyeti nedeniyle etkin pişmanlık indirimi uygulanmasa da, yapılan ödeme nedeniyle suç konusu eşya müsadere edilmez ve el konulan eşya (K)’ya iade edilir.'],
 tuzak=True,
 g='Kanuna göre gümrüklenmiş değerin iki katının ödenmesine bağlanan etkin pişmanlık indirimi, mükerrirler hakkında veya suçun bir örgütün faaliyeti çerçevesinde işlenmesi hâlinde uygulanmaz; bu nedenle (K)’nın ödemesi indirim sağlamaz. Soruşturma evresindeki ödemede yarı oranında indirim ancak bu engel bulunmadığında söz konusu olur; etkin pişmanlık ayrıca suç konusu eşyanın müsaderesine de engel teşkil etmez. (MD 5607 5/2-3, 13/2)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | İkinci fıkra hükmü, mükerrirler hakkında veya suçun bir örgütün faaliyeti çerçevesinde işlenmesi hâlinde uygulanmaz'),

dict(id='D7-023', cikmis='2022/23', konu='Kaçakçılık', tip='T8', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.12/1, 12/2',
 cek='Yükleme veya taşıma belgelerinde gösterilerek getirilen yasak eşya, teminat altında ve güvenlik tedbiriyle geldiği yere veya başka ülkeye iade ve sevk olunur.',
 kok=['Yabancı bir limanda yüklenen ve İzmir Alsancak Limanına gelen (K) Denizcilik firmasına ait gemide, ithali kanun gereği yasak olan eşya bulunmaktadır. Eşya, gemiye ait yükleme ve taşıma belgelerinde cinsi ve miktarı açıkça gösterilerek gümrüğe getirilmiş; eşyanın gizlenmesine, belgelerde farklı gösterilmesine veya gümrük işlemlerine tabi tutulmaksızın ülkeye sokulmasına yönelik herhangi bir girişimde bulunulmamıştır. Gümrük idaresince yapılan incelemede, eşyanın toplum ve çevre sağlığı yönünden tehlikeli veya zararlı nitelik taşımadığı ve atık madde olmadığı da tespit edilmiştir. Alıcı (L) firması, eşyanın ithal yasağına tabi olduğunu gemi limana yanaştıktan sonra öğrenmiş ve eşyanın Türkiye’ye girişinin mümkün olmadığı kendisine bildirilmiştir.',
      'Buna göre, 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca söz konusu eşya hakkında yapılacak işlem aşağıdakilerden hangisidir?'],
 d='Teminat altında ve güvenlik tedbirleri alınarak geldiği yere veya diğer bir ülkeye iade ve sevk olunur.',
 c=['Soruşturma başlatılmakla birlikte, gümrük yetkililerince teminat aranmaksızın getirildiği ülkeye iade edilir.',
    'Eşyaya el konularak ilgililer hakkında soruşturma başlatılır ve eşya müsadere edilmek üzere tasfiye idaresine teslim edilir.',
    'Eşya gümrüğe terk edilmiş sayılarak tasfiye idaresince Gümrük Kanunu hükümlerine göre satış yoluyla tasfiye edilir.',
    'Eşyaya el konulur ve yasak eşya niteliği nedeniyle numune alınarak el koyan idarece derhal imha edilir.'],
 tuzak=False,
 g='Kanuna göre yabancı ülkelerden gelen yasak eşya, yükleme veya taşıma belgelerinde belirtilerek gümrüğe getirilirse teminat altında ve gerekli güvenlik tedbirleri alınarak geldiği yere veya diğer bir ülkeye iade ve sevk olunur. Soruşturma başlatılarak eşyanın derhal getirildiği ülkeye iadesi, kaçakçılık fiilinin konusunu toplum ve çevre sağlığı yönünden tehlikeli ve zararlı eşya ile atık maddelerin oluşturduğu hâllere özgüdür; olayda kaçakçılık fiili bulunmadığından el koyma, müsadere veya imha da söz konusu değildir. (MD 5607 12/1-2)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Yabancı ülkelerden gelen yasak eşya, yükleme veya taşıma belgelerinde belirtilerek gümrüğe getirilirse, teminat altında ve gerekli güvenlik tedbirleri alınarak geldiği yere veya diğer bir ülkeye iade ve sevk olunur'),

dict(id='D7-024', cikmis='2022/24', konu='Kaçakçılık', tip='T4', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.3/7, 3/8, 3/12, 3/13, 3/17',
 cek='Bandrol ve benzeri işaretleri hakkı olmadan sahte evrakla temin eden kişiye üç-altı yıl hapis ve yirmi bin güne kadar adlî para cezası verilir.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununda tanımlanan kaçakçılık suçları ve bu suçlar için öngörülen cezalara ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='Tütün mamulleri ve alkollü içkilere uygulanan bandrol veya benzeri işaretleri, alma veya kullanma hakkı olmadığı hâlde sahte evrakla temin eden kişi, üç yıldan altı yıla kadar hapis ve yirmi bin güne kadar adlî para cezası ile cezalandırılır.',
 c=['İthali kanun gereği yasak olan eşyayı ülkeye sokan kişi, fiil daha ağır bir cezayı gerektiren suç oluşturmadığı takdirde, iki yıldan beş yıla kadar hapis ve on bin güne kadar adlî para cezası ile cezalandırılır.',
    'İhracı kanun gereği yasak olan eşyayı ülkeden çıkaran kişi, fiil daha ağır cezayı gerektiren başka bir suç oluşturmadığı takdirde, iki yıldan altı yıla kadar hapis ve yirmi bin güne kadar adlî para cezası ile cezalandırılır.',
    'Boru hatlarından, depolarından veya kuyulardan kanunlara aykırı şekilde alınan ürünleri satışa arz eden, satan veya bulunduran kişi, bir yıldan üç yıla kadar hapis ve beş bin güne kadar adlî para cezası ile cezalandırılır.',
    'Enerji Piyasası Düzenleme Kurumundan izin alınmadan solvent, madenî yağ veya baz yağdan akaryakıt üreten kişi, bir yıldan beş yıla kadar hapis ve on bin güne kadar adlî para cezası ile cezalandırılır.'],
 tuzak=True,
 g='Kanuna göre bandrol, etiket, hologram, pul, damga veya benzeri işaretleri alma veya kullanma hakkı olmadığı hâlde sahte evrak veya dokümanlarla temin edenler üç yıldan altı yıla kadar hapis ve yirmi bin güne kadar adlî para cezası ile cezalandırılır. İthali yasak eşyayı ülkeye sokmanın cezası iki yıldan altı yıla kadar hapis ve yirmi bin güne kadar, ihracı yasak eşyayı çıkarmanın cezası ise bir yıldan üç yıla kadar hapis ve beş bin güne kadar adlî para cezasıdır; boru hattı ürünleri ile izinsiz akaryakıt üretiminde ceza iki yıldan beş yıla kadar hapis ve yirmi bin güne kadar adlî para cezasıdır. (MD 5607 3/7, 3/8, 3/12, 3/13, 3/17)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | bunları alma veya kullanma hakkı olmadığı halde sahte evrak veya dokümanlarla veya herhangi bir biçimde ilgili kurum ve kuruluşları yanıltarak temin edenler || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | kullananlar üç yıldan altı yıla kadar hapis ve yirmi bin güne kadar adlî para cezası ile cezalandırılır'),

dict(id='D7-025', cikmis='2022/25', konu='Kaçakçılık', tip='T2', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.19/1, 21, 23/7',
 cek='Kontrollü teslimatı Gümrük Müsteşarlığı, Emniyet, Jandarma ve Sahil Güvenlik yürütür; mülkî amirler ve Kara Kuvvetleri hudut birlikleri sayılmamıştır.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanunu çerçevesinde yapılacak kontrollü teslimat işlemleri bakımından aşağıdaki kurum ve birimler veriliyor:',
      'I. Mülkî amirler',
      'II. Emniyet Genel Müdürlüğü',
      'III. Sahil Güvenlik Komutanlığı',
      'IV. Kara Kuvvetleri Komutanlığı hudut birlikleri',
      'Yukarıdakilerden hangileri, Kanuna göre kontrollü teslimat işlemlerini yürütecek birimler arasında sayılmıştır?'],
 d='II ve III', c=['Yalnız II', 'I, II ve III', 'I, III ve IV', 'II, III ve IV'],
 opts=['Yalnız II', 'II ve III', 'I, II ve III', 'I, III ve IV', 'II, III ve IV'],
 tuzak=False,
 g='Kanuna göre bu Kanun çerçevesinde yapılacak kontrollü teslimat işlemleri Gümrük Müsteşarlığı, Emniyet Genel Müdürlüğü, Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı tarafından yürütülür; bu nedenle II ve III doğrudur. Mülkî amirler kaçakçılığı önleme, izleme ve araştırmakla yükümlü olmakla birlikte kontrollü teslimatı yürütecekler arasında sayılmamış; Kara Kuvvetleri Komutanlığı hudut birlikleri personeline ise yalnızca ikramiye ödenmesi öngörülmüştür. (MD 5607 19/1, 21, 23/7)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | çerçevesinde Gümrük Müsteşarlığı, Emniyet Genel Müdürlüğü, Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı tarafından yürütülür'),

dict(id='D7-026', cikmis='2022/26', konu='Kaçakçılık', tip='T7', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.17/2',
 cek='5607 davaları, Adalet Bakanlığının teklifi üzerine Hâkimler ve Savcılar Kurulunca belirlenen asliye ceza mahkemelerinde görülür; sahtecilik bağlantısında ağır ceza görevlidir.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa göre, bu Kanun kapsamına giren suçlar dolayısıyla açılan ve resmî belgede sahtecilik suçuyla bağlantılı olmayan davalar hangi mahkemelerde görülür?'],
 d='Adalet Bakanlığının teklifi üzerine Hâkimler ve Savcılar Kurulunca belirlenen asliye ceza mahkemelerinde',
 c=['Adalet Bakanlığının teklifi üzerine Hâkimler ve Savcılar Kurulunca belirlenen ağır ceza mahkemelerinde',
    'Ticaret Bakanlığının teklifi üzerine Adalet Bakanlığınca belirlenen asliye ceza mahkemelerinde',
    'Hâkimler ve Savcılar Kurulunun teklifi üzerine Adalet Bakanlığınca belirlenen ceza mahkemelerinde',
    'Suçun işlendiği yerdeki gümrük idaresinin bulunduğu yer asliye ceza mahkemelerinde'],
 tuzak=True,
 g='Kanuna göre bu Kanun kapsamına giren suçlar dolayısıyla açılan davalar, Adalet Bakanlığının teklifi üzerine Hâkimler ve Savcılar Kurulunca belirlenen asliye ceza mahkemelerinde görülür. Ağır ceza mahkemesi ancak bu suçlarla bağlantılı olarak resmî belgede sahtecilik suçunun işlenmesi hâlinde görevlidir; mahkemelerin belirlenmesinde teklif yetkisi Ticaret Bakanlığına değil Adalet Bakanlığına, belirleme yetkisi ise Kurula aittir. (MD 5607 17/2)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Adalet Bakanlığının teklifi üzerine Hâkimler ve Savcılar Kurulunca belirlenen asliye ceza mahkemelerinde görülür || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | resmî belgede sahtecilik suçunun işlenmesi halinde, görevli mahkeme ağır ceza mahkemesidir'),

dict(id='D7-027', cikmis='2022/27', konu='Kaçakçılık', tip='T1', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.3/4, 3/5, 3/6, 3/9, 6/4',
 cek='İhraç beyanı ile fiilen ihraç edilen eşya arasındaki yüzde onu aşmayan fark kaçakçılık sayılmaz; yalnız Gümrük Kanununa göre işlem yapılır.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa göre aşağıdakilerden hangisi kaçakçılık suçu kapsamında [[değildir]]?'],
 d='İhraç edilen eşya ile beyannamede gösterilen eşya arasında yüzde onu aşmayan fark bulunması',
 c=['Geçici ithalat rejimiyle getirilen eşyayı hile ile yurt dışına çıkarmış gibi işlem yapmak',
    'Kaçak eşyayı, fiile iştirak etmeksizin bu özelliğini bilerek ve ticari amaçla saklamak',
    'Gümrük vergilerinden muaf ithal edilen eşyayı bu özelliğini bilerek satın almak veya kabul etmek',
    'Yolcunun beyanına aykırı olarak eşyası arasında ticari mahiyette eşya çıkması'],
 tuzak=False,
 g='Kanuna göre beyanname ve eki belgelerde gösterilen ile gerçekte ihraç edilen eşya arasında yüzde onu aşmayan bir fark bulunması hâlinde yalnızca 4458 sayılı Gümrük Kanunu hükümlerine göre işlem yapılır; bu durum kaçakçılık suçu oluşturmaz. Geçici ithalat eşyasını hile ile yurt dışına çıkarmış gibi işlem yapmak ve muaf eşyayı bilerek satın almak Kanunda kaçakçılık suçu olarak sayılmış, yolcunun beyanına aykırı ticari mahiyetteki eşyası için de kaçakçılık suçlarına ilişkin hükümlerin uygulanacağı öngörülmüştür. (MD 5607 3/4-6, 3/9, 6/4)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | yüzde onu aşmayan bir fark bulunması halinde, sadece 27/10/1999 tarihli ve 4458 sayılı Gümrük Kanunu hükümlerine göre işlem yapılır || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | eşyanın ticarî mahiyette veya ithali veya ihracının yasak olması halinde'),

# ---------------- DENEME 8 ----------------
dict(id='D8-022', cikmis='2023/22', konu='Kaçakçılık', tip='T1', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.4/6, 19/1, 22/1, 23/7, 24',
 cek='Kaçakçılığı önlemekle görevli olup suçun işlenmesine kasten göz yuman kişi yardım eden değil, işlenen suçun müşterek faili olarak sorumludur.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa göre kaçakçılıkla mücadelede görev alan kurum ve personele ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Kaçakçılık fiillerini önlemek, izlemek ve araştırmakla görevli olup da bu Kanunda tanımlanan suçların işlenmesine kasten göz yuman kişi, işlenen suça yardım eden sıfatıyla sorumlu tutulur.',
 c=['Mülkî amirler, Gümrük Müsteşarlığı personeli ile Emniyet Genel Müdürlüğü, Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığına bağlı personel, Kanunla yaptırım altına alınan fiilleri önleme, izleme ve araştırmakla yükümlüdür.',
    'Kara Sınırlarının Korunması ve Güvenliği Hakkında Kanun uyarınca görev verilen Kara Kuvvetleri Komutanlığı hudut birlikleri personeline de Kanunda düzenlenen usul ve esaslara göre ikramiye ödenir.',
    'Kaçakçılık fiillerinin önlenmesi, izlenmesi ve araştırılması çerçevesinde görev yapmak üzere Gümrük Müsteşarlığınca kriminal laboratuvarlar kurulur ve bunların çalışma esasları yönetmelikle belirlenir.',
    'Memurların silah kullanmalarından dolayı haklarında soruşturma veya kovuşturma açılması hâlinde, bağlı bulundukları kurumca avukat sağlanır ve avukatlık ücreti kurumlarınca karşılanır.'],
 tuzak=False,
 g='Kanuna göre kaçakçılık fiillerini önlemek, izlemek ve araştırmakla görevli olup da suçların işlenmesine kasten göz yuman kişi, işlenen suçun yardım edeni olarak değil müşterek faili olarak sorumlu tutulur. Görevli kurumların sayımı, hudut birlikleri personeline ikramiye ödenmesi, kriminal laboratuvarların kurulması ve silah kullanan memurlara kurumlarınca avukat sağlanması Kanunda aynen yer alan hükümlerdir. (MD 5607 4/6, 19/1, 22/1, 23/7, 24)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Kaçakçılık fiillerini önlemek, izlemek ve araştırmakla görevli olup da bu Kanunda tanımlanan suçların işlenmesine kasten göz yuman kişi, işlenen suçun müşterek faili olarak sorumlu tutulur'),

dict(id='D8-045', cikmis='2023/45', konu='Kaçakçılık', tip='T9', z='Z',
 madde='5607 Sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliği m.3/1-ğ, 11/1-b, 12/1, Ek-8; 5607 sayılı Kanun m.2/1-b',
 cek='El konulan eşyanın muhafaza ücreti CIF değeri üzerinden günlük binde bir, altı aydan sonra yarısıdır; eşya değerinin yüzde on beşini aşamaz.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca ithal eşyası olduğu tespit edilen bir parti tekstil ürününe kaçak şüphesiyle el konulmuş ve eşya, gümrük idaresinin depolama kapasitesini aşması nedeniyle valinin onayıyla özel bir şirkete ait depoda muhafaza edilmiştir. Kaçak eşyaya mahsus tespit tutanağında eşyanın CIF değeri 200.000 TL, eşyaya ilişkin gümrük vergileri toplamı 50.000 TL olarak gösterilmiş; mahkemece eşyanın değerine ilişkin herhangi bir bedel belirlenmemiştir. Eşya, soğuk hava deposu gibi özel tesis ve tertibat gerektirmemektedir. Eşya, satış haricindeki bir yöntemle tasfiye edilerek ilgilisine teslim edilmiş olup depoda toplam 240 gün muhafaza edilmiştir; bu sürenin 180 günü ilk altı aylık döneme, 60 günü ise altı aydan sonraki döneme isabet etmektedir.',
      'Buna göre, Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliği uyarınca depo sahibine ödenecek muhafaza ücreti **kaç TL** olur?'],
 d='30.000 TL', c=['37.500 TL', '42.000 TL', '48.000 TL', '52.500 TL'],
 opts=['30.000 TL', '37.500 TL', '42.000 TL', '48.000 TL', '52.500 TL'],
 tuzak=False,
 g='Yönetmeliğe göre mahkemece bedel belirlenmemişse tespit tutanağındaki CIF değeri (200.000 TL) eşyanın değeri olarak esas alınır; günlük binde bir oranla ilk 180 gün için 36.000 TL, altı aydan sonraki 60 gün için yarı oranla 6.000 TL olmak üzere 42.000 TL hesaplanır. Muhafaza ücreti eşya değerinin yüzde on beşini (30.000 TL) ve her hâlde 100.000 TL’yi geçemeyeceğinden ödenecek tutar 30.000 TL’dir. Gümrüklenmiş değerin (250.000 TL) esas alınması 37.500 TL veya 52.500 TL, üst sınırın ya da yarı oranın göz ardı edilmesi ise 42.000 TL veya 48.000 TL sonucunu verir. (MD Elkonulan Eşya Yön. 3/1-ğ, 11/1-b, 12/1, Ek-8)',
 kanit="5607_sayili_kacakcilikla_mucadele_kanununa_gore_elkonulan_esya_ve_alikonulan_tasitlara_iliskin_uygulama_yonetmeligi.txt | bedel belirlenmemiş ise kaçak eşyaya mahsus tespit tutanağında yer alan ihraç eşyası için FOB, ithal eşyası için CIF değerini || 5607_sayili_kacakcilikla_mucadele_kanununa_gore_elkonulan_esya_ve_alikonulan_tasitlara_iliskin_uygulama_yonetmeligi.txt | eşyanın değeri üzerinden günlük binde biri || 5607_sayili_kacakcilikla_mucadele_kanununa_gore_elkonulan_esya_ve_alikonulan_tasitlara_iliskin_uygulama_yonetmeligi.txt | eşya değerinin yüzde onbeşini ve her halükarda 100.000 TL'yi geçemez"),

dict(id='D8-051', cikmis='2023/51', konu='Kaçakçılık', tip='T10', z='Z',
 madde='Kaçakçılık Türleri ile İlgili Mahkûmiyet Hükmü Kesinleşenlerin Kamuoyuna İlan Edilmesine Dair Yönetmelik m.6; 5607 Sayılı Kaçakçılıkla Mücadele Kanununa Göre İkramiye Ödenmesi Hakkında Yönetmelik m.12/1; Elkonulan Akaryakıt Uygulama Yönetmeliği m.8; Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliği m.7/3',
 cek='İlan eşikleri İlan Yönetmeliğinde, kontrollü teslimatta ikramiye talep eden birim İkramiye Yönetmeliğinde; akaryakıt muhafaza ücreti ve tütün numunesi ilgili uygulama yönetmeliklerinde düzenlenir.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa dayanılarak çıkarılan yönetmelikler ile bu yönetmeliklerde düzenlenen konular aşağıda eşleştirilmiştir:',
      '1. Kamuoyuna ilan edilecek kaçakçılık fiillerinde aranacak asgari miktar ve değerler – 5607 Sayılı Kaçakçılıkla Mücadele Kanununa Göre İkramiye Ödenmesi Hakkında Yönetmelik',
      '2. Kaçak akaryakıtın muhafaza süresi ve muhafaza ücretinin hesaplanması – Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği',
      '3. Kontrollü teslimat yakalamalarında ikramiye talebinde bulunacak birim – Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği',
      '4. El konulan bandrolsüz tütün mamulleri ve alkollü içkilerden alınacak numune miktarları – Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliği',
      'Yukarıdaki eşleştirmelerden hangilerinde konu ile yönetmelik [[yanlış]] eşleştirilmiştir?'],
 d='1 ve 3', c=['Yalnız 1', '2 ve 4', '1, 2 ve 3', '1, 3 ve 4'],
 opts=['Yalnız 1', '1 ve 3', '2 ve 4', '1, 2 ve 3', '1, 3 ve 4'],
 tuzak=False,
 g='Kamuoyuna ilan için aranacak miktar ve değerler Kaçakçılık Türleri ile İlgili Mahkûmiyet Hükmü Kesinleşenlerin Kamuoyuna İlan Edilmesine Dair Yönetmelikte, kontrollü teslimat yakalamalarında ikramiye talebini yapacak birim ise İkramiye Ödenmesi Hakkında Yönetmelikte düzenlenmiştir; bu nedenle 1 ve 3 yanlıştır. Kaçak akaryakıtın muhafaza süresi ve ücreti Akaryakıt Uygulama Yönetmeliğinde, bandrolsüz tütün mamulleri ve alkollü içkilerden alınacak numune miktarı ise Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliğinde yer alır. (MD İlan Yön. 6; İkramiye Yön. 12/1; Akaryakıt Yön. 8; Elkonulan Eşya Yön. 7/3)',
 kanit='kacakcilik_turleri_ile_ilgili_mahkumiyet_hukmu_kesinlesenlerin_kamuoyuna_ilan_edilmesine_dair_yonetmelik.txt | İlana esas olacak miktar veya değerler || 5607_sayili_kacakcilikla_mucadele_kanununa_gore_ikramiye_odenmesi_hakkinda_yonetmelik.txt | Kontrollü teslimat yakalamalarında ikramiye talebi, kontrollü teslimata son verilen yerdeki birim tarafından yapılır || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Kaçak akaryakıtın muhafaza süresi ve ücret tarifesi'),

dict(id='D8-073', cikmis='2023/73', konu='Kaçakçılık', tip='T9', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.3/3, 4/7',
 cek='Kaçakçılık konusu eşya çevre veya toplum sağlığını tehdit ediyorsa, daha ağır suç yoksa hapis cezası on yıldan az olamaz: 36 ay → 120 ay.',
 kok=['Yabancı bir ülkeden karayoluyla getirilen ve transit rejimi çerçevesinde Kapıköy Gümrük Müdürlüğünden Mersin Gümrük Müdürlüğüne sevk edilen, toplum ve çevre sağlığını tehdit edecek nitelikteki kimyasal maddelerden oluşan serbest dolaşımda bulunmayan eşya, taşıyıcı firma yetkilisi (K) tarafından rejim hükümlerine aykırı olarak gümrük bölgesinde bırakılmıştır. Fiil tek başına ve herhangi bir suç örgütünün faaliyeti çerçevesinde olmaksızın işlenmiş; (K) kaçakçılığı önleme, izleme ve araştırmakla görevli değildir ve fiil daha ağır cezayı gerektiren başka bir suç oluşturmamaktadır. (K) hakkında 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca açılan davada hâkim, transit rejimine aykırılık suçu için temel hapis cezasını 3 yıl olarak belirlemiştir. Olayda etkin pişmanlık veya başka bir indirim nedeni bulunmamaktadır.',
      'Buna göre, (K) hakkında hükmedilecek hapis cezası **en az kaç ay** olmalıdır?'],
 d='120 ay', c=['36 ay', '54 ay', '72 ay', '108 ay'], opts=['36 ay', '54 ay', '72 ay', '108 ay', '120 ay'],
 tuzak=False,
 g='Kaçakçılık suçunun konusunu oluşturan eşyanın çevre veya toplum sağlığını tehdit edecek nitelikte olması hâlinde, fiil daha ağır cezayı gerektiren bir suç oluşturmadığı takdirde verilecek hapis cezası on yıldan az olamaz; bu nedenle 3 yıllık temel ceza 10 yıla (120 ay) yükseltilir. 36 ay eşyanın niteliğine bağlı bu asgari sınırın gözetilmemesi, 54 ay olayda bulunmayan yarı oranındaki artırımın uygulanması, 72 ve 108 ay ise olayda bulunmayan örgüt hâline özgü kat artırımının uygulanmasıyla bulunan hatalı sonuçlardır. (MD 5607 3/3, 4/7)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | çevre veya toplum sağlığını tehdit edecek nitelikte olması halinde, fiil daha ağır cezayı gerektiren bir suç oluşturmadığı takdirde, verilecek hapis cezası on yıldan az olamaz'),

# ---------------- DENEME 9 ----------------
dict(id='D9-065', cikmis='2024/65', konu='Kaçakçılık', tip='T5', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.3/1, 3/2, 3/3',
 cek='Eşyayı gümrük işlemlerine tabi tutmaksızın ülkeye sokana bir-beş yıl hapis ve on bin güne kadar adlî para cezası verilir.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununun kaçakçılık suçlarını düzenleyen hükmünde yer alan aşağıdaki cümle veriliyor:',
      '“Eşyayı, gümrük işlemlerine tabi tutmaksızın ülkeye sokan kişi, …… kadar hapis ve …… güne kadar adlî para cezası ile cezalandırılır.”',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='Bir yıldan beş yıla – on bin',
 c=['Bir yıldan üç yıla – beş bin', 'İki yıldan beş yıla – on bin', 'Bir yıldan beş yıla – beş bin', 'İki yıldan altı yıla – yirmi bin'],
 tuzak=False,
 g='Kanuna göre eşyayı gümrük işlemlerine tabi tutmaksızın ülkeye sokan kişi bir yıldan beş yıla kadar hapis ve on bin güne kadar adlî para cezası ile cezalandırılır. İki yıldan beş yıla kadar hapis eşyayı aldatıcı işlem ve davranışlarla gümrük vergileri ödenmeksizin ülkeye sokma suçunun, bir yıldan üç yıla kadar hapis ve beş bin gün ise transit eşyasını rejime aykırı olarak gümrük bölgesinde bırakma gibi suçların cezasıdır. (MD 5607 3/1-3)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Eşyayı, gümrük işlemlerine tabi tutmaksızın ülkeye sokan kişi, bir yıldan beş yıla kadar hapis ve on bin güne kadar adlî para cezası ile cezalandırılır'),

dict(id='D9-066', cikmis='2024/66', konu='Kaçakçılık', tip='T9', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.3/1, 3/23',
 cek='Eşyanın değeri hafifse ceza yarısına kadar indirilir; azami indirimle 36 aylık temel ceza 18 aya iner.',
 kok=['(K), yurt dışından getirdiği ticari nitelikteki eşyayı aracının yakıt deposunda oluşturduğu bölmeye gizleyerek Gürbulak Gümrük Kapısından gümrük işlemlerine tabi tutmaksızın ülkeye sokmuş; eşya daha sonra (K)’ya ait depoda yapılan aramada ele geçirilmiştir. (K) hakkında 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca açılan davada hâkim, temel hapis cezasını 3 yıl olarak belirlemiş; suç konusu eşyanın değerinin hafif olduğunu tespit ederek Kanunun bu durum için öngördüğü indirimi en üst oranda uygulamaya karar vermiştir. Fiil gümrük kapısından işlendiği için gümrük kapıları dışından sokmaya ilişkin artırım söz konusu değildir; olayda başkaca nitelikli hâl, etkin pişmanlık veya indirim nedeni de bulunmamaktadır.',
      'Buna göre, (K) hakkında hükmedilecek hapis cezası **kaç ay** olur?'],
 d='18 ay', c=['24 ay', '36 ay', '48 ay', '54 ay'], opts=['18 ay', '24 ay', '36 ay', '48 ay', '54 ay'],
 tuzak=False,
 g='Kanuna göre eşyanın değerinin hafif olması hâlinde verilecek cezalar yarısına kadar indirilir; hâkim indirimi en üst oranda uyguladığından 36 aylık temel ceza 18 aya iner. Cezanın üçte bir oranında indirilmesi 24 aya, indirimin hiç uygulanmaması 36 aya götürür; 48 ay olayda bulunmayan gümrük kapıları dışından sokma artırımının üçte bir oranında, 54 ay ise fahiş değere ilişkin artırımın yarı oranında uygulanmasıyla bulunan hatalı sonuçlardır. (MD 5607 3/1, 3/23)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Eşyanın değerinin hafif olması hâlinde verilecek cezalar yarısına kadar'),

dict(id='D9-067', cikmis='2024/67', konu='Kaçakçılık', tip='T1', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.236/1, 236/4, 236/5',
 cek='Antrepo sayımında noksan eşya çıkarsa vergilerin yanı sıra gümrüklenmiş değerin iki katı idari para cezası verilir; idari yaptırım dışlanmaz.',
 kok=['4458 sayılı Gümrük Kanununa göre gümrük antrepoları, gümrük idaresince eşya konulmasına izin verilen yerler ve gümrüksüz satış mağazalarına ilişkin aykırılıklarda uygulanacak yaptırımlarla ilgili aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Gümrük antrepolarında yapılan sayımlarda kayıtlara göre eşyanın bir kısmının noksan olduğunun anlaşılması hâlinde, eşya kaçak sayılarak yalnızca 5607 sayılı Kanun hükümlerine göre işlem yapılır ve idari para cezası uygulanmaz.',
 c=['Teminat alınmış olsa bile, gümrük işlemlerine başlanmadan veya gümrük idaresinin izni alınmadan gümrük antrepolarından eşya çıkarılması hâlinde, gümrük vergilerinin yanı sıra gümrüklenmiş değerin iki katı idari para cezası verilir.',
    'Gümrüksüz satış mağazalarından hak sahibi olmayanlara satış yapılması hâlinde, satışa konu eşyaya ait ithalat vergilerinin yanı sıra bu vergilerin üç katı tutarında para cezası verilir.',
    'Antrepo beyannamesinde beyan edilenden belirgin şekilde farklı cinste çıkan eşyanın gümrük vergileri toplamı beyan edilen eşyanınkinden fazla ise, farklı çıkan eşyanın gümrük vergilerinin iki katı idari para cezası verilir.',
    'Antrepo beyannamesinde beyan edilenden belirgin şekilde farklı cinste çıkan eşyanın ithali, beyan edilen eşyadan farklı olarak lisans veya izne tabi ise, gümrüklenmiş değerinin iki katı idari para cezası verilir.'],
 tuzak=False,
 g='Kanuna göre gümrük antrepolarında yapılan sayımlarda kayıtlara göre eşyanın bir kısmının noksan olduğunun anlaşılması hâlinde, bu eşyanın gümrük vergilerinin yanı sıra gümrüklenmiş değerinin iki katı idari para cezası verilir; idari para cezasının uygulanmayacağına ilişkin bir hüküm yoktur. İzinsiz eşya çıkarılması, gümrüksüz satış mağazasından hak sahibi olmayana satış ve antrepo beyannamesine göre farklı cinste eşya çıkması hâllerine ilişkin diğer ifadeler Kanundaki yaptırımlarla aynıdır. (MD GK 236/1, 236/4, 236/5)',
 kanit='48-cezalar.txt | yapılan sayımlarda kayıtlara göre eşyanın bir kısmının noksan olduğunun anlaşılması hallerinde, bu eşyanın gümrük vergilerinin yanı sıra gümrüklenmiş değerinin iki katı idari para cezası verilir || 48-cezalar.txt | hak sahibi olmayanlara satış yapılması halinde satışa konu eşyaya'),

# ---------------- DENEME 10 ----------------
dict(id='D10-087', cikmis='2025/87', konu='Kaçakçılık', tip='T4', z='OÜ',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.2/1-b, 5/2, 10/5, 15, 23/1-c',
 cek='Sahipsiz yakalanan kaçak eşyanın ikramiyeye esas değerini, mahallin en büyük mülkî amirinin görevlendirdiği üç kişilik heyet belirler.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununa göre kaçak eşyanın değerinin belirlenmesine ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='Sahipsiz yakalanan kaçak eşyanın ikramiyeye esas değeri, mahallin en büyük mülkî amirinin görevlendireceği Maliye Bakanlığı, Gümrük Müsteşarlığı ve sanayi ve ticaret odası temsilcilerinden oluşan üç kişilik heyetçe belirlenir.',
 c=['Müsadere yaptırımının konusunu oluşturan eşyanın kaim değerinden, eşyanın ithal eşyası olması hâlinde gümrük vergileri dikkate alınmaksızın, uluslararası kıymet sözleşmesine göre belirlenen CIF kıymeti anlaşılır.',
    'Etkin pişmanlık kapsamında soruşturma evresi sona erinceye kadar Devlet Hazinesine ödenmesi gereken tutar, suç konusu eşyanın gümrük vergileri hariç tutularak bulunan CIF kıymetinin iki katı olarak hesaplanır.',
    'İkramiye ödemelerinde giriş kaçağı eşyanın FOB kıymeti, çıkış kaçağı eşyanın ise CIF kıymeti esas alınarak muhbir ve el koyma ikramiyesine hak kazananlara ödenecek tutar hesaplanır.',
    'Alıkonulan taşıtın sahibine iadesi için gümrük idaresine verilecek teminatın hesabında, sigortası bulunmayan kara taşıtlarında da taşıtın kasko değeri esas alınır.'],
 tuzak=True,
 g='Kanuna göre ikramiye ödemelerinde sahipsiz yakalanan eşyanın değeri, mahallin en büyük mülkî amirinin görevlendireceği Maliye Bakanlığı, Gümrük Müsteşarlığı ve sanayi ve ticaret odası temsilcilerinden oluşan üç kişilik heyet tarafından belirlenir. Kaim değer ve etkin pişmanlık tutarında esas alınan değer CIF kıymeti değil gümrüklenmiş değerdir; ikramiyede giriş kaçağında CIF, çıkış kaçağında FOB kıymeti esas alınır ve sigortasız taşıtlarda teminat piyasa değerine göre belirlenir. (MD 5607 2/1-b, 5/2, 10/5, 15, 23/1-c)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Sahipsiz yakalanan eşyanın değeri, mahallin en büyük mülkî amirinin görevlendireceği Maliye Bakanlığı, Gümrük Müsteşarlığı ve sanayi ve ticaret odası temsilcilerinden oluşan üç kişilik heyet tarafından belirlenir'),

dict(id='D10-088', cikmis='2025/88', konu='Kaçakçılık', tip='T2', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.3/11, 3/12, 3/14, 3/15, 4/8',
 cek='Marker yerine kullanılan kimyasal terkipler de suç kapsamındadır; markersiz akaryakıt kaçak sokulmuşsa artırım fıkrası uygulanır; lisansa aykırı tank bulundurmak tek başına suçtur.',
 kok=['5607 sayılı Kaçakçılıkla Mücadele Kanununda akaryakıt ve ulusal markere ilişkin suçlarla ilgili şu ifadeler veriliyor:',
      'I. Ulusal marker yerine kullanılmak amacıyla üretilen kimyasal terkipler, ulusal markerin kimyasal özelliklerini taşımasa bile ulusal markere ilişkin suç hükmüne tabidir.',
      'II. Marker içermeyen akaryakıtın kaçak olarak yurda sokulduğu anlaşılırsa, akaryakıt kaçakçılığında cezanın artırılmasını öngören hükme göre cezaya hükmolunur.',
      'III. Lisansa aykırı olarak seyyar tank bulundurmak, ancak bu tankla kaçak akaryakıt satışı yapılırsa suç oluşturur.',
      'IV. Enerji Piyasası Düzenleme Kurumundan izin alınmadan solventten akaryakıt üretme suçu, akaryakıt yerine kullanılan diğer ürünler yönünden uygulanmaz.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I ve II', c=['Yalnız I', 'Yalnız II', 'I ve IV', 'I, II ve III'],
 opts=['Yalnız I', 'Yalnız II', 'I ve II', 'I ve IV', 'I, II ve III'],
 tuzak=False,
 g='Ulusal markerin kimyasal özelliklerini taşımasa bile onun yerine kullanılmak amacıyla üretilen kimyasal terkipler hakkında da ulusal markere ilişkin hüküm uygulanır; marker içermeyen akaryakıtın kaçak olarak yurda sokulduğunun anlaşılması hâlinde ise akaryakıt kaçakçılığındaki artırım hükmüne göre cezaya hükmolunur, bu nedenle I ve II doğrudur. Lisansa aykırı tank, düzenek veya ekipman bulundurmak tek başına suçtur, bunlarla satış yapılması ise cezayı iki kat artıran ayrı bir hâldir; izinsiz akaryakıt üretimine ilişkin hüküm akaryakıt yerine kullanılan diğer ürünler yönünden de uygulandığından III ve IV yanlıştır. (MD 5607 3/11-12, 3/14-15, 4/8)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Ulusal markerin kimyasal özelliklerini taşımasa bile, bu madde yerine kullanılmak amacıyla üretilen kimyasal terkipler hakkında da bu fıkra hükmü uygulanır || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | Akaryakıt yerine kullanılan diğer ürünler yönünden de bu fıkra uyarınca cezaya hükmolunur || 5607_sayili_kacakcilikla_mucadele_kanunu.txt | marker içermeyen veya seviyesi geçersiz olan akaryakıtın kaçak olarak yurda sokulduğunun anlaşılması hâlinde, onuncu fıkra hükmüne istinaden cezaya hükmolunur'),

dict(id='D10-089', cikmis='2025/89', konu='Kaçakçılık', tip='T6', z='OÜ',
 madde='5607 Sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliği m.3/1-a, 3/1-ğ, 3/1-l; 5607 sayılı Kanun m.10/5',
 cek='Elkonulan Eşya Yönetmeliğinde rayiç bedel: malın temin edildiği yer ve tarihteki piyasadaki alım ve satım bedelidir.',
 kok=['5607 Sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliğinde “Bir mal, iş veya hizmetin temin edildiği yer ve tarihteki piyasadaki alım ve satım bedeli” olarak tanımlanan kavram aşağıdakilerden hangisidir?'],
 d='Rayiç bedel',
 c=['Satış bedeli', 'Kasko değeri', 'Eşyanın değeri', 'Kaim değer'],
 tuzak=False,
 g='Yönetmelik, bir mal, iş veya hizmetin temin edildiği yer ve tarihteki piyasadaki alım ve satım bedelini “rayiç bedel” olarak tanımlar. Eşyanın değeri varsa mahkemece belirlenen bedeli, yoksa tespit tutanağındaki ithal eşyası için CIF, ihraç eşyası için FOB değerini ifade eder; kasko değeri ise alıkonulan kara taşıtlarında teminata esas alınan değerdir. (MD Elkonulan Eşya Yön. 3/1-a, 3/1-ğ, 3/1-l; 5607 10/5)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanununa_gore_elkonulan_esya_ve_alikonulan_tasitlara_iliskin_uygulama_yonetmeligi.txt | Rayiç bedel: Bir mal, iş veya hizmetin temin edildiği yer ve tarihteki piyasadaki alım ve satım bedelini'),
]
