Q = [
# ===================== DENEME 6 =====================
dict(id='D6-042', cikmis='2021/42', konu='Serbest Dolaşıma Giriş', tip='T1', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.184/1-b, 184/2-b, 186/2, 187/2, 191/A',
 cek='Nihai kullanım koşuluna uyulmadığının sonradan tespitinde yükümlülük, tespit tarihinde değil eşyanın ilgili rejime tabi tutulduğu tarihte başlar.',
 kok=['4458 sayılı Gümrük Kanununa göre, nihai kullanımı nedeniyle indirimli veya sıfır ithalat vergi oranından yararlanarak serbest dolaşıma giren eşyaya ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Koşullardan birine uyulmadığının sonradan tespiti hâlinde gümrük yükümlülüğü, uyulmadığının tespit edildiği tarihte başlar.',
 c=['Eşyanın gümrük idaresinin izniyle ihraç edilmesi hâlinde ithalat nedeniyle gümrük yükümlülüğü doğmuş sayılmaz.',
    'Gümrük vergileri tahakkuk ettiğinde, serbest dolaşıma girişte ödenen vergiler tahakkuk eden tutardan indirilir.',
    'Koşullardan birine uyulmaması, rejimin yanlış uygulanması sonucunu doğurmuşsa ithalat nedeniyle yükümlülük doğar.',
    'Hileli davranış veya ihmal bulunmaz ve diğer şartlar ispatlanırsa indirimli oran, yükümlülük doğsa da uygulanır.'],
 tuzak=True,
 g='Kanuna göre nihai kullanım nedeniyle indirimli veya sıfır vergi oranı uygulanmasına ilişkin bir koşula uyulmadığının sonradan tespiti hâlinde gümrük yükümlülüğü, tespit tarihinde değil eşyanın ilgili rejime tabi tutulduğu tarihte başlar. Eşyanın izinle ihraç edilmesi hâlinde yükümlülük doğmuş sayılmaz; yükümlülük doğduğunda ise girişte ödenen vergiler tahakkuk eden tutardan indirildiğinden bu ifadeler doğrudur. (MD GK 191/A, 184/2-b, 186/2, 187/2)',
 kanit='44-yükümlülük.txt | kullanımı nedeniyle indirimli ya da sıfır ithalat vergi oranı uygulanmasına ilişkin bir koşula uyulmadığının sonradan tespiti halinde, ilgili rejime tabi tutulduğu tarihte || 44-yükümlülük.txt | Nihai kullanımı nedeniyle indirimli veya sıfır ithalat vergi oranından yararlanarak serbest dolaşıma giren eşyanın, gümrük idarelerinin izni ile ihraç veya yeniden ihraç edilmesi halinde de ithalat nedeni ile bir gümrük yükümlülüğü doğmuş sayılmaz || 44-yükümlülük.txt | serbest dolaşıma giriş sırasında ödenen gümrük vergileri tutarı, tahakkuk eden gümrük vergileri tutarından indirilir'),

dict(id='D6-050', cikmis='2021/50', konu='Beyan', tip='T3', z='OÜ',
 madde='Gümrük Yönetmeliği m.121/4; 4458 sayılı Gümrük Kanunu m.73/2',
 cek='Eşyanın tesliminden sonra yükümlü talebiyle beyannamede düzeltme, kural olarak beyannamenin tescil tarihinden itibaren üç yıl içinde yapılabilir.',
 kok=['Gümrük Yönetmeliğine göre eşyanın tesliminden sonra beyannamede düzeltme, tescilden itibaren **ne kadar süre** içinde talep edilebilir?'],
 d='3 yıl', c=['6 ay', '1 yıl', '2 yıl', '5 yıl'], opts=['6 ay', '1 yıl', '2 yıl', '3 yıl', '5 yıl'],
 tuzak=False,
 g='Cezai hükümler saklı kalmak kaydıyla, beyanname tescil tarihinden itibaren üç yıllık süre içinde yükümlünün talebi üzerine eşyanın tesliminden sonra da beyannamede düzeltme yapılmasına izin verilir; dahilde işleme rejimi için bu süre daha uzun belirlenebilir. Bir yıl kusurlu eşyada geri verme başvurusu, beş yıl ise belge saklama süresi olup bu düzeltme için öngörülmemiştir. (MD GY 121/4; GK 73/2)',
 kanit='17-BEYAN.txt | beyanname tescil tarihinden itibaren üç yıllık süre içinde yükümlünün talebi üzerine Kanunun 73 üncü maddesinin ikinci fıkrası uyarınca beyannamede düzeltme yapılmasına izin verilir || 17-BEYAN.txt | gümrük idareleri, kendi yetkileri doğrultusunda veya beyan sahibinin talebi üzerine, yönetmelikle belirlenen usul ve esaslar çerçevesinde, beyannamenin düzeltilmesini eşyanın tesliminden sonra da yapabilirler'),

dict(id='D6-051', cikmis='2021/51', konu='Beyan', tip='T10', z='Z',
 madde='Gümrük Yönetmeliği m.114/3, 180/2-c, 196/2-b; Gümrük Genel Tebliği (Varış Öncesi Gümrük İşlemleri) (Seri No: 1) m.13/1',
 cek='Hat sonuçları: yeşil hatta belge eklenmez; mavi hatta kontrol çıkıştan sonra; kırmızı hat tam muayenede tahlil kolaylığı yok; varış öncesi sarı-yeşilde geçici depolama kaydı yok.',
 kok=['Gümrük Yönetmeliği ile Gümrük Genel Tebliği (Varış Öncesi Gümrük İşlemleri) (Seri No: 1)\'de, bilgisayar sistemince belirlenen beyanın kontrol türlerine (hatlara) bağlanan sonuçlara ilişkin aşağıdaki eşleştirmeler verilmiştir:',
      '1. Yeşil hat – Muayene türü bu hat olarak belirlenen gümrük beyannamelerine, tercihli tarife belgeleri gibi eklenmesi zorunlu belgeler eklenmez.',
      '2. Mavi hat – Onaylanmış kişi statüsüne sahip kişilerin bu hatta işlem gören ihracat beyannamelerine ilişkin beyanın kontrolü, eşyanın çıkış işlemlerinin tamamlanmasından önce gerçekleştirilir.',
      '3. Kırmızı hat – Kontrol türünün bu hat tam muayene olarak belirlenmesi hâlinde, daha önce yapılmış tahlile itibar edilerek eşyanın yeniden tahlile gönderilmemesi kolaylığından yararlanılamaz.',
      '4. Sarı hat – Varış öncesi gümrükleme izni kapsamında bu hatta işlem gören gümrük beyannamesi kapsamı eşyanın BİLGE sisteminde geçici depolama giriş-çıkış kaydı yapılmaz.',
      'Yukarıdaki eşleştirmelerden hangileri doğrudur?'],
 d='1, 3 ve 4', c=['Yalnız 1', '1 ve 3', '3 ve 4', '1, 2 ve 4'], opts=['Yalnız 1', '1 ve 3', '3 ve 4', '1, 2 ve 4', '1, 3 ve 4'],
 tuzak=False,
 g='Yeşil hatta zorunlu belgeler beyannameye eklenmez; kırmızı hat tam muayene belirlenirse önceki tahlile itibar kolaylığından yararlanılamaz; varış öncesi izin kapsamında sarı ve yeşil hatta geçici depolama giriş-çıkış kaydı yapılmaz; bu nedenle 1, 3 ve 4 doğrudur. Mavi hatta ihracat beyannamelerine ilişkin beyanın kontrolü, çıkış işlemlerinin tamamlanmasından önce değil, tamamlanmasını müteakip yapıldığından 2 yanlıştır. (MD GY 114/3, 180/2-c, 196/2-b; Varış Öncesi Gümrük İşlemleri Tebliği 13/1)',
 kanit='17-BEYAN.txt | Muayene türü yeşil hat olarak belirlenen gümrük beyannamelerine birinci fıkrada belirtilen belgeler eklenmez || 17-BEYAN.txt | Mavi hatta işlem gören ihracat beyannamelerine ilişkin beyanın kontrolü, eşyanın çıkış işlemlerinin tamamlanmasını müteakip Bakanlıkça belirlenen usul ve esaslar dâhilinde gerçekleştirilir || 17-BEYAN.txt | Ancak bilgisayar sistemi tarafından beyanın kontrolü türünün kırmızı hat tam muayene olarak belirlenmesi halinde, yükümlünün bu kolaylıktan yararlanmasına izin verilmez || 18-Ser.Dol.Giriş Rejimi.txt | Sarı ve yeşil hatta işlem gören gümrük beyannamesi kapsamı eşyanın BİLGE sisteminde geçici depolama giriş-çıkış kaydı yapılmaz'),

dict(id='D6-066', cikmis='2021/66', konu='Gümrük Vergileri', tip='T2', z='Z',
 madde='4458 sayılı Gümrük Kanunu m.15/2, 15/7, 17, 23',
 cek='Tercihli olmayan menşe, tercihli tarife uygulamaları hariç Türk Gümrük Tarifesinin uygulanması amacıyla belirlenir; kıymet tarife ve tarife dışı düzenlemeler için belirlenir.',
 kok=['4458 sayılı Gümrük Kanununda yer alan gümrük tarifesi, eşyanın tercihli olmayan menşei ve gümrük kıymetine ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Eşya ticaretine ilişkin özel hükümlerle belirlenmiş diğer önlemler, gerektiği takdirde eşyanın tarife pozisyonuna göre uygulanır.',
      'II. Eşyanın tercihli olmayan menşei, tercihli tarife uygulamaları da dâhil olmak üzere Türk Gümrük Tarifesinin uygulanması amacıyla belirlenir.',
      'III. Eşyanın gümrük kıymeti, Gümrük Tarifesinin ve eşya ticaretine ilişkin belirli konularda getirilen tarife dışı düzenlemelerin uygulanması amacıyla belirlenen kıymettir.',
      'IV. Türk Gümrük Tarife Cetveli, izahnamesi ve eşya fihristi Resmî Gazetede yayımlanır ve bu metinler idari ve kazai uygulamalarda esas tutulur.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I, III ve IV', c=['I ve III', 'III ve IV', 'I, II ve III', 'I, II ve IV'], opts=['I ve III', 'III ve IV', 'I, II ve III', 'I, II ve IV', 'I, III ve IV'],
 tuzak=False,
 g='Diğer önlemlerin tarife pozisyonuna göre uygulanması, gümrük kıymetinin tarife ve tarife dışı düzenlemelerin uygulanması amacıyla belirlenmesi ile tarife cetveli, izahname ve fihristin Resmî Gazetede yayımlanarak idari ve kazai uygulamalarda esas tutulması Kanuna uygundur; I, III ve IV doğrudur. Tercihli olmayan menşe, Türk Gümrük Tarifesinin uygulanması amacıyla belirlenirken anlaşmalardan ve tek taraflı tanınan tercihli tarife uygulamaları hariç tutulduğundan II yanlıştır. (MD GK 15/2, 15/7, 17, 23)',
 kanit='9-TAR.POZ.AYIRMA.txt | Eşya ticaretine ilişkin özel hükümlerle belirlenmiş diğer önlemler, gerektiği takdirde, söz konusu eşyanın tarife pozisyonuna göre uygulanır || 10-MENŞEİ.txt | 15 inci maddenin 3 üncü fıkrasının (d) ve (e) bentlerinde öngörülen uygulamalar hariç olmak üzere, Türk Gümrük Tarifesinin uygulanması || 12-KIYMET VE KAPLAR.txt | Eşyanın gümrük kıymeti, Gümrük Tarifesinin ve eşya ticaretine ilişkin belirli konularda getirilen tarife dışı düzenlemelerin uygulanması amacıyla || 9-TAR.POZ.AYIRMA.txt | Bu şekilde yayımlanan metinler idari ve kazai uygulamalarda esas tutulur'),

dict(id='D6-071', cikmis='2021/71', konu='Beyan', tip='T7', z='OÜ',
 madde='Gümrük Yönetmeliği m.194/2',
 cek='Yükümlü talebiyle veya kontrol sonucunda beyannamede yapılacak değişiklikler gümrük idare amirinin oluru ile gümrük müdürlüklerince yapılır; teslimden sonra da geçerlidir.',
 kok=['Gümrük Yönetmeliğine göre, yükümlü talebi üzerine beyannamelerde yapılacak değişiklikler hangi usulle ve kimce yapılır?'],
 d='Gümrük idare amirinin oluru ile gümrük müdürlüklerince',
 c=['Gümrük idare amirinin oluru ile bölge müdürlüklerince',
    'Bölge müdürlüğünün onayı ile gümrük müdürlüklerince',
    'Genel Müdürlüğün onayı ile bölge müdürlüklerince',
    'Bakanlığın onayı ile gümrük müdürlüklerince'],
 tuzak=True,
 g='Yükümlü talebi üzerine veya beyanın kontrolü sonucunda beyannamelerde yapılacak değişiklikler gümrük idare amirinin oluru ile gümrük müdürlüklerince yapılır ve bu hüküm eşyanın tesliminden sonraki düzeltmeler için de geçerlidir. Değişiklik için bölge müdürlüğü veya Bakanlık onayı aranmadığı gibi işlem bölge müdürlüklerince de yapılmaz. (MD GY 194/2)',
 kanit='17-BEYAN.txt | beyannamelerde yapılacak değişiklikler gümrük idare amirinin oluru ile gümrük müdürlüklerince yapılır. Bu hüküm, eşyanın tesliminden sonra yapılacak düzeltmeler için de geçerlidir'),
# ===================== DENEME 7 =====================
dict(id='D7-037', cikmis='2022/37', konu='Nihai Kullanım', tip='T1+T2', z='Z',
 madde='Gümrük Yönetmeliği m.208/5, 208/7; Gümrük Genel Tebliği (Nihai Kullanım) (Seri No: 1) m.7/2, 10/1',
 cek='Nihai kullanım iptalinde vergi derhal ödenir; denetleyici idare iptal belgelerini beş iş gününde gönderir; tahsis sürecinde en az bir denetim yapılır.',
 kok=['Gümrük Yönetmeliği ve Gümrük Genel Tebliği (Nihai Kullanım) (Seri No: 1)\'e göre nihai kullanım iznine ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Gümrük idarelerince eşyanın nihai kullanıma tahsis sürecinde en az bir defa denetim yapılır.',
      'II. Denetleyici ve izni veren gümrük idaresinin farklı olması hâlinde iznin iptalini gerektiren duruma ilişkin bilgi ve belgeler, tespiti takip eden on iş günü içinde izni veren idareye gönderilir.',
      'III. Geriye dönük izin verilebilmesi için eşya üzerinde gümrük gözetiminin sona ermemiş olması şartı aranır.',
      'IV. İznin iptali durumunda izin hak sahibi, nihai kullanıma tahsis edilmemiş eşyaya ilişkin gümrük vergisini iptal tarihinden itibaren otuz gün içinde öder.',
      'Yukarıdaki ifadelerden hangileri [[yanlıştır]]?'],
 d='II ve IV', c=['Yalnız II', 'Yalnız IV', 'I ve II', 'II ve III'], opts=['Yalnız II', 'Yalnız IV', 'I ve II', 'II ve III', 'II ve IV'],
 tuzak=False,
 g='İptal bilgi ve belgeleri, denetleyici idarece durumun tespitini takip eden on değil beş iş günü içinde izni veren idareye gönderilir; iznin iptalinde ise tahsis edilmemiş eşyanın gümrük vergisi otuz gün içinde değil derhal ödenir; bu nedenle II ve IV yanlıştır. Tahsis sürecinde en az bir defa denetim yapılması ve geriye dönük izin için gümrük gözetiminin sona ermemiş olması şartı mevzuata uygundur. (MD GY 208/5, 208/7; Nihai Kullanım Tebliği 7/2, 10/1)',
 kanit='18-Ser.Dol.Giriş Rejimi.txt | Gümrük idareleri tarafından eşyanın nihai kullanıma tahsis sürecinde en az bir defa denetim yapılır || 18-Ser.Dol.Giriş Rejimi.txt | izin iptalini gerektiren durumun tespitini takip eden beş iş günü içinde iznin iptalini teminen izni veren gümrük idaresine gönderilir || 18-Ser.Dol.Giriş Rejimi.txt | geriye dönük izin verilebilmesi için eşya üzerinde gümrük gözetiminin sona ermemiş olması şartı aranır || 18-Ser.Dol.Giriş Rejimi.txt | İznin iptali durumunda izin hak sahibi nihai kullanıma tahsis edilmemiş eşya ile ilgili gümrük vergisini derhal ödemek zorundadır'),

dict(id='D7-038', cikmis='2022/38', konu='Gümrük Vergileri', tip='T2', z='OÜ',
 madde='İthalat Rejimi Kararı (3350 sayılı CK) m.10/1, 10/3, 10/4',
 cek='Ek mali yükümlülük, yükümlülüğün doğduğu tarihteki miktar ve oranlarla alınır ve gümrük vergisi usulüne tabidir; muaf ithalat EMY dışındadır, TKF atıfları EMY sayılır.',
 kok=['İthalat Rejimi Kararına göre, ithalatta uygulanan ek mali yükümlülüğe ilişkin aşağıdaki ifadeler veriliyor:',
      'I. Ek mali yükümlülük ödenerek ithal edilecek eşya, gümrük yükümlülüğünün doğduğu tarihte geçerli miktar ve oranlar kadar ek mali yükümlülüğe tabidir.',
      'II. Gümrük Kanununun gümrük vergisi muafiyetlerine ilişkin hükümleri çerçevesinde muaf olarak gerçekleştirilen ithalat da ek mali yükümlülüğe tabidir.',
      'III. Ek mali yükümlülük hakkında gümrük vergisinin tabi olduğu usul ve hükümler uygulanır.',
      'IV. İthalat işlemlerine ilişkin mevzuatta toplu konut fonu ve ilave toplu konut fonuna yapılan atıflar, ek mali yükümlülüğe yapılmış sayılmaz.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I ve III', c=['Yalnız I', 'Yalnız III', 'I, II ve III', 'I, III ve IV'], opts=['Yalnız I', 'Yalnız III', 'I ve III', 'I, II ve III', 'I, III ve IV'],
 tuzak=False,
 g='Ek mali yükümlülük, gümrük yükümlülüğünün doğduğu tarihte geçerli miktar ve oranlarla uygulanır ve hakkında gümrük vergisinin tabi olduğu usul ve hükümler uygulanır; I ve III doğrudur. Gümrük Kanunu uyarınca gümrük vergilerinden muaf olarak yapılan ithalat ek mali yükümlülüğe tabi değildir; ithalat mevzuatında toplu konut fonu ve ilave toplu konut fonuna yapılan atıflar ise ek mali yükümlülüğe yapılmış sayıldığından II ve IV yanlıştır. (MD İRK 10/1, 10/3, 10/4)',
 kanit='ck_2020-03350_ithalat_rejimi_karari.txt | Ek mali yükümlülük ödenerek ithal edilecek eşya, gümrük yükümlülüğünün doğduğu tarihte geçerli miktar ve oranlar kadar ek mali yükümlülüğe tabidir || ck_2020-03350_ithalat_rejimi_karari.txt | çerçevesinde gümrük vergilerinden muaf olarak gerçekleştirilecek ithalat, ek mali yükümlülüğe tabi değildir || ck_2020-03350_ithalat_rejimi_karari.txt | Ek mali yükümlük hakkında, gümrük vergisinin tabi olduğu usul ve hükümler uygulanır || ck_2020-03350_ithalat_rejimi_karari.txt | İthalat işlemlerine ilişkin mevzuatta yer alan toplu konut fonu ve ilave toplu konut fonuna yapılan atıflar, ek mali yükümlülüğe yapılmış sayılır'),

dict(id='D7-039', cikmis='2022/39', konu='Serbest Dolaşıma Giriş', tip='T1', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.210, 213/3; Gümrük Yönetmeliği m.502/1, 505/3; Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2) m.31/6',
 cek='Beyandan önce denenmek üzere teslim edilen eşyada vergiler, kusurun deneme sırasında anlaşılamadığı kanıtlanmadıkça geri verilmez veya kaldırılmaz.',
 kok=['4458 sayılı Gümrük Kanunu, Gümrük Yönetmeliği ve Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2)\'ye göre gümrük vergilerinin geri verilmesi veya kaldırılmasına ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Gümrük beyanından önce denenmek üzere geçici olarak teslim edilen eşyanın vergileri, kusur veya aykırılık deneme sırasında anlaşılmış olsa dahi, eşya ilk kullanım dışında kullanılmamışsa geri verilir veya kaldırılır.',
 c=['Kanunda geçen geri verme deyimi ödenmiş olan gümrük vergilerinin tamamen veya kısmen geri ödenmesini, kaldırma deyimi ise henüz ödenmemiş olan gümrük vergilerinin tamamen veya kısmen alınmamasına karar verilmesini ifade eder.',
    'Geri verme veya kaldırma başvurusu; vergileri ödeyen veya ödemekle yükümlü olan kişi, bunların temsilcileri ya da hak ve yükümlülükleri devralan kişi tarafından başvuru formu ile elektronik olarak yapılır.',
    'Mavi ve yeşil hatta işlem görmüş beyannamelere ilişkin geri verme başvurularında yükümlü nezdinde ayrıca inceleme veya tespit gerekirse, bu tespit işlemleri yetkilendirilmiş gümrük müşavirlerine yaptırılabilir.',
    'Nakden veya mahsup suretiyle geri verilmesine karar verilen gümrük vergileri, yükümlülerin dahili vergiler açısından gider kalemi olması nedeniyle yükümlünün bağlı bulunduğu vergi dairesine bildirilir.'],
 tuzak=False,
 g='Kanuna göre gümrük beyanından önce denenmek üzere geçici olarak teslim edilen eşyanın vergileri, kusurlu veya sözleşmeye aykırı olduğunun deneme sırasında anlaşılamadığı kanıtlanmadıkça geri verilmez veya kaldırılmaz; kusur deneme sırasında anlaşılmışsa ilk kullanım dışında kullanılmamış olması sonucu değiştirmez. Geri verme ve kaldırma tanımları, başvurunun ödeyen, yükümlü, temsilci veya hak ve yükümlülükleri devralan kişilerce formla elektronik olarak yapılması ve mavi ile yeşil hatta tespitin yetkilendirilmiş gümrük müşavirine yaptırılabilmesi mevzuata uygundur. (MD GK 210, 213/3; GY 502/1, 505/3; Tahsilat Tebliği 31/6)',
 kanit='47-geri verme kaldırma.txt | Gümrük beyanından önce denenmek üzere geçici olarak teslim edilen eşyanın vergileri, eşyanın kusurlu veya sözleşme hükümlerine aykırı olduğu hususlarının deneme sırasında anlaşılamadığı kanıtlanmadıkça geri verilmez veya kaldırılmaz || 47-geri verme kaldırma.txt | ödenmiş olan gümrük vergilerinin tamamen veya kısmen geri ödenmesi || 47-geri verme kaldırma.txt | henüz ödenmemiş olan gümrük vergilerinin tamamen veya kısmen alınmamasına karar verilmesi || 47-geri verme kaldırma.txt | bu vergileri ve cezaları ödeyen veya ödemekle yükümlü olan kişi veya bunların temsilcileri veya hak ve yükümlülükleri devralan kişi tarafından Ek-78\'de yer alan Geri Verme veya Kaldırma Başvurusu Formu ile elektronik olarak || 47-geri verme kaldırma.txt | yükümlü nezdinde ayrıca bir inceleme veya tespit yapılmasına gerek bulunması durumunda, buna ilişkin tespit işlemleri yetkilendirilmiş gümrük müşavirlerine yaptırılabilir || 47-geri verme kaldırma.txt | yükümlünün bağlı bulunduğu vergi dairesine bildirilir'),
dict(id='D7-040', cikmis='2022/40', konu='Serbest Dolaşıma Giriş', tip='T4', z='OÜ',
 madde='2009/15481 sayılı Bakanlar Kurulu Kararı (4458 sayılı Gümrük Kanununun Bazı Maddelerinin Uygulanması Hakkında Karar) m.13/1-a, 13/1-ç, 13/1-d, 14/1',
 cek='TGB\'ye getirilmeden serbest dolaşıma girecek Türk bayraklı geminin işlemleri, kayıtlı olduğu liman başkanlığına en yakın gümrük idaresinde yapılır.',
 kok=['2009/15481 sayılı “4458 sayılı Gümrük Kanununun Bazı Maddelerinin Uygulanması Hakkında Karar”a göre, Türk Bayrağı çekilmiş gemilerin Türkiye Gümrük Bölgesine getirilmeksizin serbest dolaşıma giriş işlemlerinde bir arada bulunması gereken hususlardan biri aşağıdakilerden hangisidir?'],
 d='Serbest dolaşıma giriş işlemlerinin geminin kayıtlı olduğu liman başkanlığına en yakın gümrük idaresinde yapılması',
 c=['Gümrük işlemlerinin Bayrak Şahadetnamesinin düzenlendiği tarihten itibaren otuz gün içinde sonuçlandırılması',
    'Geminin bu usulle serbest dolaşıma giriş işlemlerine tabi tutulmasının Ulaştırma Bakanlığınca da uygun bulunması',
    'Bayrak Şahadetnamesinin işlemlerin yapılacağı gümrük idaresinin bağlı olduğu bölge müdürlüğüne gönderilmesi',
    'Bayrak Şahadetnamesinin geminin bağlama limanındaki liman başkanlığından alınması'],
 tuzak=True,
 g='Kararda gemilerin serbest dolaşıma giriş işlemlerinin, geminin kayıtlı olduğu liman başkanlığına en yakın gümrük idaresinde yapılması aranır. Otuz günlük süre Bayrak Şahadetnamesinin düzenlendiği tarihten değil liman başkanlığının sicil kaydı bildiriminden itibaren işler; Bayrak Şahadetnamesi yurt dışı temsilciliklerimizden alınır; Ulaştırma Bakanlığının uygun bulması ise hava taşıtlarına ilişkin bir şarttır. (MD 2009/15481 s. Karar 13/1-a, 13/1-ç, 13/1-d, 14/1-c)',
 kanit='18-Ser.Dol.Giriş Rejimi.txt | Eşyanın serbest dolaşıma giriş işlemlerinin geminin kayıtlı olduğu liman başkanlığına en yakın gümrük idaresinde yapılması || 18-Ser.Dol.Giriş Rejimi.txt | Yurt dışı temsilciliklerimizden Bayrak Şahadetnamesinin alınması || 18-Ser.Dol.Giriş Rejimi.txt | Liman başkanlıklarının geminin Türk Uluslararası Gemi Siciline kaydının yapıldığının bildirimini müteakip gümrük işlemlerinin otuz gün içinde sonuçlandırılması || 18-Ser.Dol.Giriş Rejimi.txt | Hava taşıtının Türkiye Gümrük Bölgesine getirilmeksizin serbest dolaşıma giriş işlemlerine tabi tutulması hususunun Ulaştırma Bakanlığınca da uygun bulunması'),

dict(id='D7-045', cikmis='2022/45', konu='Beyan', tip='T7', z='OÜ',
 madde='Gümrük Yönetmeliği m.172/3, 172/4',
 cek='Sözlü beyan formu, yükümlünün verdiği bilgilere göre gümrük personeli tarafından sisteme girilir veya doldurulur.',
 kok=['Gümrük Yönetmeliğine göre, sözlü beyana ilişkin form kim tarafından ve neye göre sisteme girilir veya doldurulur?'],
 d='Gümrük personeli tarafından, yükümlünün verdiği bilgilere göre',
 c=['Yükümlü veya temsilcisi tarafından, eşyaya ait belgelere göre',
    'Gümrük müşaviri tarafından, yükümlünün verdiği vekâlete göre',
    'Taşıyıcı tarafından, taşıma belgesindeki bilgilere göre',
    'Geçici depolama yeri işleticisi tarafından, giriş kayıtlarına göre'],
 tuzak=False,
 g='Sözlü beyana ilişkin form, yükümlünün verdiği bilgilere göre gümrük personeli tarafından sisteme girilir ya da doldurulur; yükümlü veya temsilcisinin imzası ise formun ilgili kutusuna alınır. Formun yükümlü, temsilci veya gümrük müşavirince kendi belgelerine göre doldurulması öngörülmemiştir. (MD GY 172/3, 172/4)',
 kanit='17-BEYAN.txt | Sözlü beyana ilişkin form yükümlünün verdiği bilgilere göre gümrük personeli tarafından sisteme girilir ya da doldurulur'),

dict(id='D7-077', cikmis='2022/77', konu='Beyan', tip='T4', z='Z',
 madde='Gümrük Yönetmeliği m.121/1, 121/2, 121/3; 4458 sayılı Gümrük Kanunu m.63',
 cek='Teslime kadar düzeltme; kırmızı hat belirlenmesinden ve bilgilerin yanlışlığının tespitinden önce mümkündür; sarı hat düzeltmeyi engellemez.',
 kok=['Gümrük Yönetmeliği ve 4458 sayılı Gümrük Kanununa göre, eşyanın teslimine kadar beyannamede yapılacak düzeltmelere ilişkin aşağıdakilerden hangisi doğrudur?'],
 d='Eşyanın teslimine kadar, bilgisayar sistemince kontrol türünün kırmızı hat olarak belirlenmesinden ve beyan edilen eşyaya ilişkin bilgilerin yanlış olduğunun tespitinden önce beyannamede düzeltmeye izin verilir.',
 c=['Beyan edilen eşyaya ilişkin bilgilerin yanlış olduğunun tespit edilmesinden sonra yapılan düzeltme talepleri kabul edilerek sistemde gerekli düzeltmeler yapılır ve bu durumda beyan sahibi hakkında ayrıca işlem yapılmaz.',
    'Kanunda geçen başka bir eşya ifadesinden yalnızca tarife alt pozisyonu değişen eşya anlaşılır; vergi oranı veya ticaret politikası önlemine ilişkin hak ve menfaatleri farklılaşan eşya bu kapsama girmez.',
    'Bilgisayar sistemince beyanın kontrolü türünün sarı hat olarak belirlenmesiyle birlikte, beyan edilen bilgilerin yanlış olduğu tespit edilmemiş olsa dahi beyannamede düzeltme yapılmasına izin verilmez.',
    'Beyan sahibinin talebi üzerine yapılacak düzeltme başka bir eşyanın beyanı sonucunu doğursa dahi, eşyanın muayene edileceği bildirilmeden önce yapılmışsa gümrük idarelerince kabul edilir.'],
 tuzak=False,
 g='Eşyanın teslimine kadar düzeltmeye, kontrol türünün kırmızı hat olarak belirlenmesinden ve bilgilerin yanlış olduğunun tespitinden önce izin verilir; sarı hat belirlenmesi tek başına düzeltmeyi engellemez. Yanlışlığın tespitinden sonraki talepler kabul edilmeyip tespit edilen farklılıklara ilişkin işlemler uygulanır; başka bir eşya ifadesi vergi oranı veya ticaret politikası önlemine ilişkin hak ve menfaatleri farklılaşan eşyayı da kapsar ve düzeltme hiçbir aşamada başka bir eşyanın beyanı sonucunu doğuramaz. (MD GY 121/1-3; GK 63)',
 kanit='17-BEYAN.txt | Eşyanın teslimine kadar; || 17-BEYAN.txt | Eşyanın muayenesi için bilgisayar sistemi tarafından beyanın kontrolü türünün kırmızı hat olarak belirlenmesinden || 17-BEYAN.txt | Beyan edilen eşyaya ilişkin bilgilerin yanlış olduğunun tespit edilmesinden, || 17-BEYAN.txt | önce beyannamede düzeltme yapılmasına izin verilir || 17-BEYAN.txt | düzeltme talepleri kabul edilmeyerek 192 ve 193 üncü maddeler uygulanır || 17-BEYAN.txt | Başka bir eşyanın beyanı sonucunu doğurmaması kaydıyla'),

dict(id='D7-078', cikmis='2022/78', konu='Beyan', tip='T1', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.60/5; Gümrük Yönetmeliği m.148/1, 148/3, 165/1',
 cek='Serbest dolaşıma girişte beyanname yerine ticari veya idari belge usulü, CIF kıymeti 500 Avro\'yu geçmeyen eşyayı sürekli ithal edenlere altı ay süreyle tanınır.',
 kok=['4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliğine göre, beyanname kabul edilen resmî yazılar ile beyanname yerine ticari veya idari belge kullanılmasına ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='CIF kıymeti 1.000 Avro\'yu geçmeyen eşyayı aynı gümrük idaresinden sürekli ve periyodik olarak ithal edenlerin beyanname yerine ticari veya idari belge üzerinden tescil ve işlem yapılmasına yönelik yazılı talepleri altı ay süreyle geçerli olmak üzere kabul edilir.',
 c=['Cumhurbaşkanının zat ve ikametgâhına ait eşya hakkında Cumhurbaşkanlığından gönderilecek resmî yazılar beyanname kabul edilir ve eşyanın gümrük işlemleri bu yazılara dayanılarak yürütülür.',
    'Diplomatik muaflık ve ayrıcalıklardan yararlananların kendi adlarına veya elçilik adına gelecek eşya için misyon şeflerinden gönderilen yazılar, karşılıklı olmak şartıyla beyanname kabul edilir.',
    'Serbest dolaşıma girişte beyanname yerine ticari veya idari belge ile beyan usulünde, gümrük idaresince bilgisayar ortamında düzenlenen tutanağa dayanılarak eşya gümrüklü sahadan çıkarılır; tamamlayıcı beyanda tutanak tarihi tescil tarihi olarak kaydedilir.',
    'Aynı tarife pozisyonunda sınıflandırılmış eşyayla ilgili sürekli olarak gümrük antrepo rejim beyanında bulunanların ticari veya idari belge ile işlem talepleri, yetkilendirilmiş yükümlü veya onaylanmış kişi koşulları aranmaksızın kabul edilir.'],
 tuzak=True,
 g='Serbest dolaşıma girişte beyanname yerine ticari veya idari belge usulünden, belirli eşya ve akvaryum balıkları dışında CIF kıymeti 1.000 değil 500 Avro\'yu geçmeyen eşyayı aynı gümrük idaresinden sürekli ve periyodik ithal edenler altı ay süreyle yararlanır; 1.000 Avro sözlü beyana ilişkin sınırdır. Cumhurbaşkanlığı ve karşılıklılık şartıyla misyon şeflerinden gelen yazıların beyanname kabul edilmesi ile tutanak tarihinin tescil tarihi olarak kaydedilmesi mevzuata uygundur. (MD GK 60/5; GY 148/1, 148/3, 165/1, 169/6)',
 kanit='17-BEYAN.txt | CIF kıymeti 500 Avro\'yu geçmeyen diğer eşyayı aynı gümrük idaresinden sürekli ve periyodik olarak ithal edenlerin || 17-BEYAN.txt | altı ay süreyle geçerli olmak üzere kabul edilir || 17-BEYAN.txt | Cumhurbaşkanının zat ve ikametgâhına ait eşya hakkında Cumhurbaşkanlığından gönderilecek yazılar || 17-BEYAN.txt | karşılıklı olmak şartıyla misyon şeflerinden veya muaflık hakkı tanınmış heyet başkanlarınca gönderilen yazılar || 17-BEYAN.txt | Eşya, bu tutanağa dayanarak gümrüklü sahadan çıkarılır || 17-BEYAN.txt | tutanak tarihine referans verilerek bu tarih tescil tarihi olarak kaydedilir || 17-BEYAN.txt | Aynı tarife pozisyonunda sınıflandırılmış eşyayla ilgili sürekli olarak gümrük antrepo rejim beyanında bulunan kişilerin'),
# ===================== DENEME 8 =====================
dict(id='D8-040', cikmis='2023/40', konu='Beyan', tip='T1', z='OÜ',
 madde='Gümrük Yönetmeliği m.132/1-2, 132/5, 134/1, 135/1, 137/3',
 cek='Mühürleri sağlam olmayan kurye kaplarına gümrük mührü tatbik edilir, tutanakla tespit edilip kuryenin sorumluluğunda Esenboğa Gümrük Müdürlüğüne sevk edilir.',
 kok=['Gümrük Yönetmeliğine göre, kurye mektupları ve kurye kaplarına ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Ağızları resmî mühürle mühürlenmemiş veya mühürleri bozulmuş kaplara gümrüğün mührü tatbik edilir ve durum tutanakla tespit edildikten sonra kaplar, en yakın gümrük müdürlüğünde açılarak muayene edilir.',
 c=['Resmî ve gizli evrak götürüp getiren kuryelere teslim olunacak evrak için her defasında bir kurye mektubu düzenlenir; bu mektup ilgili makamın resmî mührü ile mühürlenerek yetkili kimselerce imzalanır.',
    'Görevli gümrük memurları, kurye kaplarını dıştan muayene ve inceleyerek mektupların uygun ve resmî mühürle mühürlenmiş olduğunu gördüklerinde kapları açmaksızın etiket yapıştırarak veya işaret koyarak geçirir.',
    'Türk kuryeleri diplomatik pasaport ile seyahat eder; yabancı kuryelerin ise diplomatik, servis veya özel pasaport ya da elçiliklerimizden verilen Lesse Passeyi taşımaları gerekir.',
    'Olağanüstü ve zorunlu hâllerde vapur kaptanları veya uçak pilotları eliyle gönderilen kurye kaplarında bu kişilere tanınan geçici kuryelik vasfı, kendilerine başka herhangi bir hak doğurmaz.'],
 tuzak=False,
 g='Mühürleri sağlam olmayan veya kurye mektubuna uymayan kaplara gümrüğün mührü tatbik edilir, durum tutanakla tespit edilir ve kaplar açılıp muayene edilmeksizin kuryenin sorumluluğu altında Esenboğa Gümrük Müdürlüğüne sevk edilir. Her defasında kurye mektubu düzenlenmesi ve mektuplara uygun mühürlü kapların açılmaksızın işaret konularak geçirilmesi Yönetmeliğe uygundur. (MD GY 132/1-2, 132/5, 134/1, 135/1, 137/3)',
 kanit='17-BEYAN.txt | kaplara gümrüğün mührü tatbik edilir ve durum bir tutanakla tespit edildikten sonra kuryenin sorumluluğu altında Esenboğa Gümrük Müdürlüğüne sevk edilir || 17-BEYAN.txt | teslim olunacak evrak için her defasında bir Kurye Mektubu düzenlenir || 17-BEYAN.txt | bunları açıp kapsamını muayene etmeksizin, üzerlerine etiket yapıştırarak veya işaret koyarak geçirilmelerine izin verir || 17-BEYAN.txt | geçici kuryelik vasfı, sadece bunların taşıdıkları kurye kaplarına şamil olup, kendilerine başka herhangi bir hak doğurmaz'),

dict(id='D8-049', cikmis='2023/49', konu='Gümrük Vergileri', tip='T1', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.3/9, 3/10',
 cek='Tarım politikası veya işlenmiş tarım ürünlerine özel düzenlemelerle ihracatta alınan vergi ve mali yükler ithalat değil ihracat vergisidir.',
 kok=['4458 sayılı Gümrük Kanunundaki ithalat ve ihracat vergileri tanımlarına göre aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='İşlenmiş tarım ürünlerine özel düzenlemeler çerçevesinde ihracatta alınan vergiler ithalat vergisidir.',
 c=['Eşyanın ithalinde ödenecek gümrük vergisi ve eş etkili vergiler ithalat vergileri kapsamındadır.',
    'Tarım politikası çerçevesinde ithalatta alınacak vergiler ve diğer mali yükler ithalat vergisidir.',
    'Eşyanın ihracatında ödenecek gümrük vergisi ile eş etkili mali yükler ihracat vergileri kapsamındadır.',
    'Tarım ürünlerinin işlenmesiyle elde edilen ürünlere özel düzenlemelerle ithalatta alınan yükler ithalat vergisidir.'],
 tuzak=False,
 g='Tarım politikası veya tarım ürünlerinin işlenmesi sonucu elde edilen bazı ürünlere uygulanan özel düzenlemeler çerçevesinde ihracatta alınan vergi ve mali yükler ihracat vergileri tanımına girer, ithalat vergisi sayılmaz. Aynı düzenlemeler çerçevesinde ithalatta alınanlar ile ithalde ödenen gümrük vergisi ve eş etkili vergiler ise ithalat vergileridir. (MD GK 3/9, 3/10)',
 kanit='1-TANIMLAR.txt | Eşyanın ithalinde ödenecek gümrük vergisi ile diğer eş etkili vergiler ve mali yükleri || 1-TANIMLAR.txt | Tarım politikası veya tarım ürünlerinin işlenmesi sonucu elde edilen bazı ürünlere uygulanan özel düzenlemeler çerçevesinde ihracatta alınacak vergileri ve diğer mali yükleri || 1-TANIMLAR.txt | Eşyanın ihracatında ödenecek gümrük vergisi ile diğer eş etkili vergiler ve mali yükleri'),

dict(id='D8-084', cikmis='2023/84', konu='Beyan', tip='T1', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.61/1-3, 62/1-2',
 cek='Yerleşik olma koşulu transit, geçici ithalat ve idarece uygun bulunan arızi beyanda bulunan kişilere uygulanmaz.',
 kok=['4458 sayılı Gümrük Kanununa göre, gümrük beyannamesini verebilecek kişiler ile beyannamenin tesciline ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Yerleşik olma koşulu transit ya da geçici ithalat beyanında bulunan kişilere uygulanmaz; ancak gümrük idarelerinin uygun bulması koşuluyla arızi olarak beyanda bulunan kişiler bakımından bu koşul aranmaya devam eder.',
 c=['Gümrük beyannamesi, ilgili eşyayı ve rejim hükümlerinin uygulanması için gerekli belgeleri yetkili gümrük idarelerine verme yetkisine sahip olan veya verilmesini sağlayabilen kişiler tarafından verilebilir.',
    'Beyannamenin tescilinin belirli bir kişi için özel yükümlülükler getirmesi hâlinde beyanın bu kişi tarafından ya da hesabına yapılması ve beyan sahibinin Türkiye Gümrük Bölgesinde yerleşik olması gerekir.',
    'Şartlara uygun beyannameler, ait oldukları eşyanın gümrüğe sunulmuş olması hâlinde tescil edilir ve aksine hüküm bulunmadıkça rejim hükümlerinin uygulanmasında tescil tarihi esas alınır.',
    'Tescil edilmiş beyanname, ait olduğu eşyanın vergileri ve para cezalarından dolayı taahhüt niteliğinde beyan sahibini bağlar ve gümrük vergileri tahakkukuna esas tutulur.'],
 tuzak=True,
 g='Kanuna göre yerleşik olma koşulu; transit veya geçici ithalat beyanında bulunanlara ve gümrük idarelerinin uygun bulması koşuluyla arızi olarak beyanda bulunan kişilere uygulanmaz. Beyannamenin eşya gümrüğe sunulmuşsa tescil edilmesi, tescil tarihinin rejim hükümlerinde esas alınması ve tescilli beyannamenin taahhüt niteliğinde beyan sahibini bağlaması Kanuna uygundur. (MD GK 61/1-3, 62/1-2)',
 kanit='17-BEYAN.txt | yerleşik olma koşulu, transit ya da geçici ithalat beyanında bulunan veya gümrük idarelerinin uygun bulması koşuluyla arızi olarak beyanda bulunan kişilere uygulanmaz || 17-BEYAN.txt | ait oldukları eşyanın gümrüğe sunulmuş olması halinde tescil edilir || 17-BEYAN.txt | taahhüt niteliğinde beyan sahibini bağlar ve gümrük vergileri tahakkukuna esas tutulur'),

dict(id='D8-090', cikmis='2023/90', konu='Beyan', tip='T2', z='Z',
 madde='Gümrük Yönetmeliği m.177/1, 178/1, 178/3, 179/1',
 cek='Başka bir tasarruf yoluyla beyan: yeşil hattan geçiş; kişisel-sportif eşyada geçici ithalat beyanı sayılır; ihracata bağlı haktan yararlanan ve kısıtlamalı eşyada uygulanmaz.',
 kok=['Gümrük Yönetmeliğinde düzenlenen başka bir tasarruf yoluyla beyana ilişkin aşağıdaki ifadeler veriliyor:',
      'I. İki hat sisteminin çalıştığı gümrük idarelerinde eşyanın yeşil veya “beyana tabi eşyam yoktur” hattından geçirilmesi başka bir tasarruf yoluyla beyandır.',
      'II. Yolcuların ithalat vergilerinden tam muafiyetle getirdiği kişisel ve sportif amaçlı eşyaya ilişkin bu yolla yapılan beyan, geçici ithalat rejimine ilişkin beyan olarak kabul edilir.',
      'III. Bu beyan usulü, ihracata bağlı hak ve menfaatlerden yararlanan veya yasaklama ya da kısıtlamaya tabi eşya için de uygulanır.',
      'IV. Beyan gerçekleştiği hâlde koşulların yerine getirilmediğinin yapılan inceleme sonucunda anlaşılması durumunda cezai işlem yapılır.',
      'Yukarıdaki ifadelerden hangileri doğrudur?'],
 d='I, II ve IV', c=['Yalnız II', 'I ve II', 'II ve IV', 'I, II ve III'], opts=['Yalnız II', 'I ve II', 'II ve IV', 'I, II ve III', 'I, II ve IV'],
 tuzak=False,
 g='Yeşil veya “beyana tabi eşyam yoktur” hattından geçiş başka bir tasarruf yoluyla beyandır; yolcuların tam muafiyetle getirdiği kişisel ve sportif eşyada bu beyan geçici ithalat beyanı sayılır ve koşulların sağlanmadığı sonradan anlaşılırsa cezai işlem yapılır; I, II ve IV doğrudur. Bu usul ihracata bağlı hak ve menfaatlerden yararlanan, vergileri geri verilen veya yasaklama ve kısıtlamaya tabi eşya için uygulanmadığından III yanlıştır. (MD GY 177/1, 178/1, 178/3, 179/1)',
 kanit='17-BEYAN.txt | iki hat sisteminin çalıştığı gümrük idarelerinde yeşil veya "beyana tabi eşyam yoktur" hattından geçirilmesi || 17-BEYAN.txt | ithal vergilerinden tam muafiyet suretiyle yolcular tarafından ithal edilen kişisel ve sportif amaçlı eşyaya 178 inci madde uyarınca yapılan beyan, geçici ithalat rejimine ilişkin beyan olarak kabul edilir || 17-BEYAN.txt | ihracata bağlı hak ve menfaatlerden yararlanan, gümrük vergilerinin geri verildiği veya yasaklama, kısıtlama veya diğer özel bir işleme tabi eşya için uygulanmaz || 17-BEYAN.txt | koşulların yerine getirilmediğinin yapılan inceleme sonucunda anlaşılması durumunda, cezai işlem yapılır'),

dict(id='D8-093', cikmis='2023/93', konu='Beyan', tip='T1', z='OÜ',
 madde='Gümrük Yönetmeliği m.180/1, 180/3, 182/5, 183/1, 186/3, 187/1',
 cek='Beyanın kontrol türü ve görevli memur idare amirince değil bilgisayar sistemince risk kriterlerine göre belirlenir; YYS beyannameleri öncelikli kontrol edilir.',
 kok=['Gümrük Yönetmeliğinde düzenlenen beyanın kontrolü, muayene ve belge kontrolüne ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Beyanın kontrol türü ile kontrolle görevli memur, risk kriterlerine göre gümrük idare amirince belirlenir; yetkilendirilmiş yükümlü sertifikası sahipleri adına tescilli beyannamelerin kontrolleri öncelikli yapılır.',
 c=['Laboratuvar tahliline konu edilen eşyanın tahlilini gerçekleştiren kişiler, tahlil sonucuna bağlı olarak yapılan gümrük tarife istatistik pozisyonu belirlenmesinden müteselsilen sorumlu tutulur.',
    'Belge kontrolünde görevli memur, beyannamedeki bilgileri ve eklerini inceler; tarife, kıymet, miktar ve yasaklayıcı veya kısıtlayıcı önlemlere ilişkin belge kontrollerini de yaptıktan sonra uygun bulursa sistemde onay verir.',
    'Eşyanın muayenesi gümrük idarelerince izin verilen yerlerde veya antrepolarda yapılır; ancak gümrük idare amirleri beyan sahibinin talebi üzerine eşyanın bu yerler dışında herhangi bir yerde muayene edilmesine izin verebilir.',
    'Dökme hâldeki eşya ile çabuk bozulacak sebze ve meyve gibi ihracat eşyasının, gümrüğe sunulmadan deniz ve kara taşıtlarına yükletilirken muayenesi yapılabilir.'],
 tuzak=False,
 g='Beyanın kontrol türü ve kontrolle görevli memur, gümrük idare amirince değil bilgisayar sistemi tarafından risk kriterlerine göre belirlenir; yetkilendirilmiş yükümlü sertifikası sahiplerine ait beyannamelerin öncelikli kontrolü ise doğrudur. Belge kontrolünde tarife, kıymet, miktar ve önlemlere ilişkin kontrollerin yapılarak sistemde onay verilmesi ile idare amirinin talep üzerine muayenenin izin verilen yerler dışında yapılmasına izin verebilmesi Yönetmeliğe uygundur. (MD GY 180/1, 180/3, 182/5, 183/1, 186/3, 187/1)',
 kanit='17-BEYAN.txt | Beyanın kontrol türü ve kontrolle görevli memur, bilgisayar sistemi tarafından risk kriterlerine göre belirlenir || 17-BEYAN.txt | Yetkilendirilmiş yükümlü sertifikası sahipleri adına tescilli beyannamelere ilişkin kontroller öncelikli olarak yapılır || 17-BEYAN.txt | Laboratuvar tahliline konu edilen eşyanın tahlilini gerçekleştirenler tahlil sonucuna bağlı olarak yapılan GTİP belirlenmesinden müteselsilen sorumludur || 17-BEYAN.txt | tarife, kıymet, miktar, yasaklayıcı ve kısıtlayıcı önlemler söz konusu ise, buna ilişkin belge kontrollerini de yaptıktan sonra uygun bulursa || 17-BEYAN.txt | gümrük idare amirleri beyan sahibinin talebi üzerine eşyanın, bu yerler dışında herhangi bir yerde muayene edilmesine izin verebilir || 17-BEYAN.txt | gümrüğe sunulmadan deniz ve kara taşıtlarına yükletilirken muayenesi yapılabilir'),
# ===================== DENEME 9 =====================
dict(id='D9-043', cikmis='2024/43', konu='Serbest Dolaşıma Giriş', tip='T1', z='Z',
 madde='Gümrük Genel Tebliği (Serbest Dolaşıma Giriş) (Seri No: 16) m.3/1, 4/1, 4/3, 5/2, 5/3',
 cek='LNG\'de özet beyan verilir ve eşya gümrüğe sunulur; gümrüğe sunulmaksızın serbest dolaşıma giriş boru hattı/elektrik teli eşyasına özgüdür.',
 kok=['Gümrük Genel Tebliği (Serbest Dolaşıma Giriş) (Seri No: 16)\'ya göre LNG ithalatına ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Eşya için özet beyan verilmez ve eşya gümrüğe sunulmaksızın, yetkili gümrük idaresinin izniyle serbest dolaşıma giriş rejimine tabi tutulur.',
 c=['Beyan sahibince yurt dışı analiz raporu ile proforma fatura veya satış sözleşmesi sunulur ve beyanname bu verilerle tescil edilir.',
    'Fatura veya diğer belgeler, en geç beyannamenin tescil edildiği ayı takip eden ayın yirmi altıncı gününe kadar ibraz edilir.',
    'Serbest dolaşıma giriş beyannamesi, Kanunda belirtilen süreler içinde ve eşyanın boşaltılmasına başlanmadan önce tescil edilir.',
    'Belgelere göre miktar veya kıymet farkı bulunursa beyannamede düzeltme yapılır; vergiler belge ibraz süresi içinde ödenir.'],
 tuzak=True,
 g='Deniz yoluyla sıvı hâlde getirilen LNG için Kanun uyarınca özet beyan verilir ve eşya gümrüğe sunulur; gümrüğe sunulmaksızın serbest dolaşıma giriş, boru hatları veya elektrik telleriyle taşınan eşyaya ilişkin farklı bir tebliğde düzenlenmiştir. Beyannamenin boşaltmaya başlanmadan önce tescili ile fatura ve diğer belgelerin tescil ayını takip eden ayın yirmi altıncı gününe kadar ibrazı Tebliğe uygundur. (MD SDG Tebliği Seri No: 16 m.3/1, 4/1, 4/3, 5/2, 5/3)',
 kanit='18-Ser.Dol.Giriş Rejimi.txt | Bu Tebliğ kapsamındaki eşya için 4458 sayılı Kanunun 35/A maddesi uyarınca özet beyan verilir ve 4458 sayılı Kanunun 39 uncu maddesi uyarınca eşya gümrüğe sunulur || 18-Ser.Dol.Giriş Rejimi.txt | eşyanın boşaltılmasına başlanmadan önce tescil edilir || 18-Ser.Dol.Giriş Rejimi.txt | en geç beyannamenin tescil edildiği ayı takip eden ayın yirmi altıncı gününe (yirmi altıncı gün dahil) kadar gümrük idaresine ibraz edilir || 18-Ser.Dol.Giriş Rejimi.txt | tahakkuk ettirilen gümrük vergileri ikinci fıkrada belirtilen süre içerisinde ödenir || 18-Ser.Dol.Giriş Rejimi.txt | Gümrük Kanununun 40 ıncı maddesi uyarınca gümrüğe sunulmaksızın serbest dolaşıma giriş rejimine tabi tutulmasına yetkili gümrük idaresince izin verilir'),

dict(id='D9-045', cikmis='2024/45', konu='Beyan', tip='T2', z='OÜ',
 madde='Gümrük Yönetmeliği m.148/1, 156/1, 160/3-a',
 cek='İhracatta statü koşulu aranmadan ticari/idari belgeyle işlem: aynı idareden sürekli kitap ihracı ve gemilere kumanya verme; F tipi antrepo eşyasında basitleştirme yok.',
 kok=['Gümrük Yönetmeliğine göre;',
      'I. Aynı idareden sürekli ve periyodik kitap ihracı',
      'II. Aynı idareden sürekli ve periyodik gemilere kumanya verilmesi',
      'III. F tipi antrepodan ihracat',
      'IV. Aynı idareden sürekli akvaryum balığı ihracı',
      'yukarıdaki işlemlerden hangilerinde beyanname yerine ticari veya idari belgeyle işlem talebi, yetkilendirilmiş yükümlü veya onaylanmış kişi koşulu aranmadan kabul edilir?'],
 d='I ve II', c=['I ve IV', 'II ve IV', 'I, II ve III', 'I, II ve IV'], opts=['I ve II', 'I ve IV', 'II ve IV', 'I, II ve III', 'I, II ve IV'],
 tuzak=False,
 g='Aynı gümrük idaresinden sürekli ve periyodik olarak kitap ve basılı yayın ihraç edenler ile gemilere kumanya, yağ ve yakıt verme şeklinde ihracat yapanların ticari veya idari belgeyle işlem talepleri statü koşulları aranmaksızın kabul edilir; I ve II doğrudur. F tipi antrepo rejimi uygulanan eşyanın ihracat rejimine girişinde basitleştirilmiş usule izin verilmez; akvaryum balıkları ise ihracatta değil, serbest dolaşıma girişte bu usulden yararlanan eşya arasında sayılmıştır. (MD GY 148/1, 156/1, 160/3-a)',
 kanit='17-BEYAN.txt | Aynı gümrük idaresinden sürekli ve periyodik olarak kitap ve diğer basılı yayın ihraç edenler ile gemilere kumanya, yağ, yakıt ve diğer malzeme verme şeklinde ihracat gerçekleştirenlerin || 17-BEYAN.txt | F tipi antrepo rejimi uygulanan eşyanın ihracat rejimine girişinde basitleştirilmiş usule izin verilmez || 17-BEYAN.txt | eşya ve akvaryum balıkları ile CIF kıymeti 500 Avro\'yu geçmeyen diğer eşyayı aynı gümrük idaresinden sürekli ve periyodik olarak ithal edenlerin'),
# ===================== DENEME 10 =====================
dict(id='D10-035', cikmis='2025/35', konu='Gümrük Vergileri', tip='T1', z='Z',
 madde='5607 sayılı Kaçakçılıkla Mücadele Kanunu m.2/1-a; 4458 sayılı Gümrük Kanunu m.3/8-b, 3/11, 181/1-b, 188/1-2, 192',
 cek='5607 sayılı Kanunda gümrük vergileri; gümrük idaresi veya başka idarelerce ithale ya da ihraca bağlı uygulanan vergiler ile diğer mali yükümlülüklerdir.',
 kok=['4458 sayılı Gümrük Kanunu ile 5607 sayılı Kaçakçılıkla Mücadele Kanununda yer alan gümrük vergileri ve gümrük yükümlülüğüne ilişkin hükümlere göre aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='5607 sayılı Kanunda gümrük vergileri, yalnızca gümrük idaresince eşyanın ithali veya ihracına bağlı uygulanan vergi ve mali yükümlülükleri ifade eder; başka idarelerce uygulananlar bu tanıma girmez.',
 c=['4458 sayılı Kanunda gümrük yükümlülüğü deyimi yükümlünün gümrük vergilerini ödemesi zorunluluğunu, yükümlü deyimi ise gümrük yükümlülüğünü yerine getirmekle sorumlu bütün kişileri ifade eder.',
    'İthalat vergilerine tabi eşyanın ithalat vergilerinden kısmi muafiyet suretiyle geçici ithali için verilecek gümrük beyannamesinin tescil tarihinde de ithalatta gümrük yükümlülüğü başlar.',
    'İhracat vergilerine tabi eşyanın bir gümrük beyannamesi kapsamında Türkiye Gümrük Bölgesi dışına ihraç edilmesi hâlinde gümrük yükümlülüğü doğar ve bu yükümlülük beyannamenin tescili tarihinde başlar.',
    '4458 sayılı Kanuna göre aynı gümrük vergilerinin ödenmesinden birden çok yükümlünün sorumlu olduğu hâllerde, bunlar söz konusu vergilerin ödenmesinden müştereken ve müteselsilen sorumludur.'],
 tuzak=False,
 g='5607 sayılı Kanunda gümrük vergileri; yalnız gümrük idaresince değil, gümrük idaresi veya başka idarelerce eşyanın ithali veya ihracına bağlı olarak uygulanan vergiler ile diğer mali yükümlülükleri ifade eder. Kısmi muafiyetli geçici ithalatta yükümlülüğün beyanname tescil tarihinde başlaması ile birden çok yükümlünün müştereken ve müteselsilen sorumluluğu Kanuna uygundur. (MD 5607 s.K. 2/1-a; GK 3/8-b, 3/11, 181/1-b, 188, 192)',
 kanit='5607_sayili_kacakcilikla_mucadele_kanunu.txt | Gümrük idaresi veya başka idarelerce, eşyanın ithali veya ihracına bağlı olarak uygulanan vergiler ile diğer malî yükümlülükleri || 1-TANIMLAR.txt | yükümlünün gümrük vergilerini ödemesi zorunluluğunu || 44-yükümlülük.txt | İthalat vergilerine tabi eşyanın ithalat vergilerinden kısmi muafiyet suretiyle geçici ithali, || 44-yükümlülük.txt | Gümrük yükümlülüğü, söz konusu gümrük beyannamesinin tescili tarihinde başlar || 44-yükümlülük.txt | bunlar söz konusu vergilerin ödenmesinden müştereken ve müteselsilen sorumludurlar'),

dict(id='D10-037', cikmis='2025/37', konu='Gümrük Vergileri', tip='T1', z='Z',
 madde='Tasfiye Yönetmeliği m.31/1-a, 31/1-b, 31/1-c, 31/1-ç',
 cek='Tasfiyede maktu vergi ve mali yükler ile bunlara isabet eden KDV gümrüklenmiş değere dahildir; ihaleye esas bedele dahil edilmez, ayrıca tahsil edilir.',
 kok=['Tasfiye Yönetmeliğine göre, tasfiyelik eşyanın bedelinin tespitine ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Maktu alınan vergi ve mali yükler ile bunlara isabet eden katma değer vergisi gümrüklenmiş değere dahil edilmez ve ayrıca tahsil edilir.',
 c=['Tasfiye edilebilir hâle gelmiş eşyanın bedelinin tespitinde gümrüklenmiş değer esas alınır.',
    'Kaçak eşyanın bedeli, varsa mahkemece belirlenen bedele, yoksa tespit tutanağındaki bedele, o da yoksa rayiç değere göre belirlenir.',
    'Perakende satılacak eşyanın bedeli, serbest piyasa koşulları gözetilerek işletme müdürlüklerince belirlenir.',
    'İmha edilecek eşyanın nitelik, nicelik ve değeri, istatistiğe esas olarak tespit ve tahakkuk belgesinde veya imha kararında gösterilir.'],
 tuzak=True,
 g='Maktu olarak alınması gereken vergi ve mali yükler ile bunlara isabet eden katma değer vergisi gümrüklenmiş değere dahildir; dahil edilmeyen, ihaleye esas bedeldir ve bu vergiler ayrıca tahsil edilir. Bedel tespitinde gümrüklenmiş değerin esas alınması ve kaçak eşyada mahkeme bedeli, tespit tutanağı bedeli ve rayiç değer sırasının izlenmesi Yönetmeliğe uygundur. (MD Tasfiye Yönetmeliği 31/1-a, b, c, ç)',
 kanit='43-tasfiye.txt | Maktu olarak alınması gereken vergiler ve mali yükler ile bunlara isabet eden Katma Değer Vergisi gümrüklenmiş değere dahil olmakla birlikte ihaleye esas bedele dahil edilmez. Bu vergiler ayrıca tahsil edilir || 43-tasfiye.txt | Tasfiye edilebilir hale gelmiş olan eşyanın bedelinin tespitinde gümrüklenmiş değer esas alınır || 43-tasfiye.txt | istatistik bilgilerine esas olmak üzere tespit ve tahakkuk belgesinde veya imha kararında gösterilir || 43-tasfiye.txt | Kaçak eşyanın bedeli, varsa mahkemece belirlenen bedel, bedel belirlenmemiş ise kaçak eşyaya ait tespit tutanağındaki bedel, yoksa rayiç değer esas alınarak belirlenir'),

dict(id='D10-040', cikmis='2025/40', konu='Serbest Dolaşıma Giriş', tip='T2', z='Z',
 madde='Gümrük Yönetmeliği m.509/1; 4458 sayılı Gümrük Kanunu m.77/1, 121/1-b, 121/2, 187/1',
 cek='İzinli imha atıkları, nihai kullanım tahribat atıkları ve geri ödeme sisteminde yeniden ihraç için antrepoya konulan ürünler serbest dolaşımda olmayan eşya sayılır.',
 kok=['Gümrük mevzuatına göre;',
      'I. Geri verme kararından sonra, izinli imhadan kalan atık ve artıklar',
      'II. Nihai kullanım nedeniyle sıfır vergiyle serbest dolaşıma giren eşya',
      'III. Yükümlülük doğmayan tahribattan kalan nihai kullanım atıkları',
      'IV. Geri ödeme sistemiyle giren eşyadan elde edilip yeniden ihraç için antrepoya konulan ürünler',
      'yukarıdakilerden hangileri serbest dolaşımda olmayan eşya sayılır?'],
 d='I, III ve IV', c=['I ve III', 'III ve IV', 'I, II ve III', 'I, II ve IV'], opts=['I ve III', 'III ve IV', 'I, II ve III', 'I, II ve IV', 'I, III ve IV'],
 tuzak=False,
 g='Gümrük idaresinin izni ve denetiminde imhadan doğan atık ve artıklar geri verme kararından sonra, nihai kullanım eşyasının yükümlülük doğmadığı kabul edilen tahribatından kalan atık ve artıklar ile geri ödeme sistemi çerçevesinde serbest dolaşıma giren eşyadan elde edilip daha sonra yeniden ihraç edilmek üzere gümrük antrepo rejimine tabi tutulan işlem görmüş ürünler, bu işlem bakımından serbest dolaşımda olmayan eşya sayılır; I, III ve IV doğrudur. Nihai kullanım nedeniyle indirimli veya sıfır vergiyle giren eşya ise serbest dolaşıma girmiş eşya olup yalnız gümrük gözetimi altında kaldığından II yanlıştır. (MD GY 509/1; GK 77/1, 121/1-b, 121/2, 187/1)',
 kanit='47-geri verme kaldırma.txt | Eşyanın gümrük idaresinin izniyle ve denetimi altında imha edilmesiyle ortaya çıkan atık ve artıklar geri verme veya kaldırma kararı alındıktan sonra, serbest dolaşımda olmayan eşya olarak kabul edilir || 44-yükümlülük.txt | söz konusu fıkrada belirtilen tahribattan kaynaklanan atık ve artıklar serbest dolaşımda olmayan eşya sayılır || 32-DAHİLDE İŞLEME.txt | Daha sonra yeniden ihraç edilmek üzere transit rejimi, gümrük antrepo rejimi, geçici ithalat rejimi veya şartlı muafiyet sistemine tabi dahilde işleme rejimine tabi tutulduğunu || 32-DAHİLDE İŞLEME.txt | İşlem görmüş ürünler veya değişmemiş eşya, 1 inci fıkranın (b) bendinde belirtilen gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulma bakımından, serbest dolaşımda olmayan eşya sayılır || 18-Ser.Dol.Giriş Rejimi.txt | nedeniyle indirimli veya sıfır vergi oranından yararlanarak serbest dolaşıma girmiş eşyanın gümrük gözetimi'),

dict(id='D10-049', cikmis='2025/49', konu='Nihai Kullanım', tip='T5', z='OÜ',
 madde='Gümrük Genel Tebliği (Nihai Kullanım) (Seri No: 1) m.11/1',
 cek='Nihai kullanım yeri izni veren idarenin ili dışındaysa denetleyici idare bu yere en yakın idaredir; izin belgesi ilk iş günü içinde gönderilir.',
 kok=['Gümrük Genel Tebliği (Nihai Kullanım) (Seri No: 1)\'e göre, eşyanın nihai kullanıma tahsis edileceği yer izni veren gümrük idaresinin bulunduğu il sınırları dışındaysa denetleyici idare, bu yere …… gümrük idaresidir; izni veren idare, izin belgesi ve eklerini iznin verilmesini takip eden …… denetleyici idareye gönderir.',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='en yakın – ilk iş günü içinde',
 c=['en yakın – beş iş günü içinde', 'en yakın – on beş gün içinde', 'ihtisas gümrüğü olan – ilk iş günü içinde', 'bağlı bulunduğu – beş iş günü içinde'],
 tuzak=False,
 g='İzni veren gümrük idaresi kural olarak denetleyici idaredir; ancak eşyanın tahsis edileceği yer il sınırları dışındaysa denetleyici idare bu yere en yakın gümrük idaresidir ve izni veren idare izin belgesi ile eklerini iznin verilmesini takip eden ilk iş günü içinde gönderir. Beş iş günü, iznin iptalini gerektiren durumun tespitinde bilgi ve belgelerin gönderilme süresidir; ihtisas gümrüğü ise denetleyici idarenin belirlenmesinde ölçüt değil, bu istisnaya yol açan zorunlu durumlardan biridir. (MD Nihai Kullanım Tebliği 11/1, 7/2)',
 kanit='18-Ser.Dol.Giriş Rejimi.txt | yerin izni veren gümrük idaresinin bulunduğu il sınırları dışında olması durumunda, denetleyici gümrük idaresi || 18-Ser.Dol.Giriş Rejimi.txt | kullanılacağı yere en yakın gümrük idaresidir || 18-Ser.Dol.Giriş Rejimi.txt | izin belgesi ve ekli belgeleri iznin verilmesini takip eden ilk iş günü içinde gönderir'),

dict(id='D10-051', cikmis='2025/51', konu='Serbest Dolaşıma Giriş', tip='T4', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.104/3; Gümrük Yönetmeliği m.151/3-4, 345/2',
 cek='Antrepodan kayıt yoluyla serbest dolaşıma girişte vergiler antrepo rejimine tabi tutulma tarihindeki unsurlarla; yükümlü talep ederse tescil tarihindeki hâl ve unsurlarla hesaplanır.',
 kok=['4458 sayılı Gümrük Kanununa göre, antrepodan kayıt yoluyla serbest dolaşıma girişte vergilerin hesaplanmasına ilişkin hangisi doğrudur?'],
 d='Kural olarak antrepo rejimine tabi tutulma tarihindeki unsurlar esas alınır; yükümlü talep ederse tescil tarihindeki hâl ve unsurlara göre işlem yapılır.',
 c=['Kural olarak beyannamenin tescil tarihindeki unsurlar esas alınır; yükümlü talep ederse antrepo rejimine tabi tutulma tarihindeki unsurlar uygulanır.',
    'Antrepo rejimine tabi tutulma tarihindeki unsurlar esas alınır; yükümlü talep ederse eşyanın antrepodan fiilen çıktığı tarihteki unsurlar uygulanır.',
    'Antrepo rejimine tabi tutulma tarihindeki oranlar, nitelik, kıymet ve miktarın beyanname tescilinde tespit edilmesi şartıyla uygulanır.',
    'Eşyanın antrepodan teslim alındığı tarihteki oranlar esas alınır; yükümlünün başka bir tarihi talep etme hakkı bulunmaz.'],
 tuzak=True,
 g='Antrepo rejimine tabi ithal eşyası gümrüğe sunulmaksızın ve beyanname verilmeden kayıt yoluyla serbest dolaşıma girmek üzere teslim edildiğinde gümrük vergileri, eşyanın antrepo rejimine tabi tutulduğu tarihteki oranlar ve vergilendirme unsurlarına göre hesaplanır; yükümlü talep ederse serbest dolaşıma giriş beyannamesinin tescil tarihindeki hâl, nitelik ve unsurlara göre işlem yapılır. Kural tescil tarihi değildir; nitelik, kıymet ve miktarın da tescilde değil antrepo rejimine tabi tutulma tarihinde tespit edilmiş olması gerekir. (MD GK 104/3; GY 151/3-4, 345/2)',
 kanit='28-antrepo rejimi.txt | gümrük vergileri, eşyanın antrepo rejimine tabi tutulduğu tarihte yürürlükte bulunan vergi oranları ve diğer vergilendirme unsurlarına dayanarak hesaplanır || 28-antrepo rejimi.txt | eşyanın nitelik, gümrük kıymeti ve miktarı gibi vergilendirme unsurlarının, eşyanın antrepo rejimine tabi tutulduğu tarihte tespit edilmesi şartına bağlıdır || 28-antrepo rejimi.txt | yükümlünün serbest dolaşıma giriş beyannamesinin tescil tarihinde eşyanın bulunduğu hal ve niteliği ile diğer vergilendirme unsurlarına göre işlem yapılması yönünde talepte bulunması halinde, bu yönde işlem yapılır'),

dict(id='D10-055', cikmis='2025/55', konu='Serbest Dolaşıma Giriş', tip='T5', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.3/6-a',
 cek='Şartlı muafiyet düzenlemelerine tabi eşyadan elde edilen ve özel ekonomik değer taşımadığı tespit edilen eşya serbest dolaşımda bulunan eşyadır.',
 kok=['4458 sayılı Gümrük Kanununa göre, …… düzenlemelerine tabi tutulan eşyadan elde edilen ve tabi olduğu rejim hükümleri uyarınca …… taşımadığı tespit edilen eşya da serbest dolaşımda bulunan eşya kapsamındadır.',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='şartlı muafiyet – özel ekonomik değer',
 c=['geçici ithalat – özel ekonomik değer', 'standart değişim – özel ekonomik değer', 'şartlı muafiyet – ticari değer ve nitelik', 'geri ödeme – özel ekonomik değer'],
 tuzak=False,
 g='Kanundaki tanıma göre serbest dolaşımda bulunan eşya; tümüyle Türkiye Gümrük Bölgesinde elde edilen ve ithal girdi içermeyen veya şartlı muafiyet düzenlemelerine tabi tutulan eşyadan elde edilen ve rejim hükümlerine göre özel ekonomik değer taşımadığı tespit edilen eşyayı da kapsar. Tanımda geri ödeme, geçici ithalat veya standart değişim düzenlemelerine yer verilmediği gibi ölçüt ticari değer ve nitelik değil özel ekonomik değerdir. (MD GK 3/6-a)',
 kanit='1-TANIMLAR.txt | şartlı muafiyet düzenlemelerine tabi tutulan eşyadan elde edilen ve tabi olduğu rejim hükümleri uyarınca özel ekonomik değer taşımadığı tespit edilen'),

dict(id='D10-056', cikmis='2025/56', konu='Nihai Kullanım', tip='T1', z='OÜ',
 madde='Gümrük Yönetmeliği m.209/5, 209/6',
 cek='Montajda kullanılan araç parçaları, montajın tamamlanmasıyla değil tahsis edildikleri araçlar diğer kişilere devredildiğinde nihai kullanıma geçmiş sayılır.',
 kok=['Gümrük Yönetmeliğine göre, nihai kullanımı nedeniyle indirimli veya sıfır vergi oranına tabi olup mükerrer kullanılabilen eşyanın nihai kullanıma geçmiş sayılmasına ilişkin aşağıdakilerden hangisi [[yanlıştır]]?'],
 d='Montajda kullanılan araç parçaları, bunların tahsis edildiği araçların montajının tamamlandığı tarihte, söz konusu araçların diğer kişilere devredilmesi beklenmeksizin nihai kullanıma geçmiş sayılır.',
 c=['Havayolları tarafından değişim sözleşmeleri şartları gereğince ya da kendi ihtiyaçları nedeniyle uçakların bakım ve onarımı için kullanılan malzeme, öngörülen kullanıma ilk tahsis edilişlerinde nihai kullanıma geçmiş sayılır.',
    'Sivil hava taşıtlarının yapım, bakım, tadilatı veya donanımına yönelik eşya, izin hak sahibinden başka bir kişiye devredildiğinde ya da bakım ve onarımı müteakip üçüncü şahıslarca tekrar sahibinin kullanımına verildiğinde nihai kullanıma geçmiş sayılır.',
    'Doğrudan güverte teslimi yapılan donatım amaçlı eşya teslimatın gerçekleştiği, sivil hava taşıtları ise bu amaç için öngörülen resmî kayıtlara tescil edildikleri tarihte nihai kullanıma geçmiş sayılır.',
    'Mükerrer kullanılabilen eşyanın nihai kullanıma geçtiğinin tespiti durumunda, kullanıma ilk tahsis tarihinden itibaren öngörülen süre beklenmeksizin teminat izin hak sahibine iade edilebilir.'],
 tuzak=False,
 g='Montajda kullanılan araç parçaları, montajın tamamlanmasıyla değil, tahsis edildikleri araçlar diğer kişilere devredildiğinde nihai kullanıma geçmiş sayılır. Havayollarının bakım-onarım malzemesinin ilk tahsiste, sivil hava taşıtlarının resmî kayıtlara tescil tarihinde nihai kullanıma geçmiş sayılması ve bu tespitte teminatın süre beklenmeksizin iadesi Yönetmeliğe uygundur. (MD GY 209/5, 209/6)',
 kanit='18-Ser.Dol.Giriş Rejimi.txt | Montajda kullanılan araç parçaları, bunların tahsis edildiği araçlar diğer kişilere devredildiğinde || 18-Ser.Dol.Giriş Rejimi.txt | uçakların bakım ve onarımı için kullanılan malzeme, öngörülen kullanıma ilk tahsis edilişlerinde || 18-Ser.Dol.Giriş Rejimi.txt | Sivil hava taşıtları, bu amaç için öngörülen resmi kayıtlara tescil edildikleri tarihte || 18-Ser.Dol.Giriş Rejimi.txt | Doğrudan güverte teslimi yapılan donatım amaçlı eşyanın teslimatı gerçekleştiğinde || 18-Ser.Dol.Giriş Rejimi.txt | 209 uncu maddede belirtilen süre beklenmeksizin teminat iade edilebilir'),

dict(id='D10-060', cikmis='2025/60', konu='Beyan', tip='T5', z='OÜ',
 madde='4458 sayılı Gümrük Kanunu m.69/3',
 cek='Yükümlülük doğuran beyannamede vergiler ödenmedikçe veya teminata bağlanmadıkça eşya teslim edilmez; kural kısmi muafiyetli geçici ithalata uygulanmaz.',
 kok=['4458 sayılı Gümrük Kanununa göre; “Beyannamenin tescilinin bir gümrük yükümlülüğü doğurması hâlinde, gümrük vergileri ödenmedikçe veya …… bağlanmadıkça beyanname kapsamı eşya teslim edilemez. Ancak, bu hüküm …… muafiyete tabi …… rejimine uygulanamaz.”',
      'Yukarıda boş bırakılan yerlere **sırasıyla** aşağıdakilerden hangisi gelmelidir?'],
 d='teminata – kısmi – geçici ithalat',
 c=['teminata – tam – geçici ithalat', 'teminata – kısmi – dahilde işleme', 'taahhütnameye – kısmi – geçici ithalat', 'kefalete – tam – dahilde işleme'],
 tuzak=False,
 g='Beyannamenin tescili bir gümrük yükümlülüğü doğuruyorsa gümrük vergileri ödenmedikçe veya teminata bağlanmadıkça eşya teslim edilemez; bu hüküm kısmi muafiyete tabi geçici ithalat rejimine uygulanmaz. Taahhütname veya kefalet bu hükümde öngörülmemiş, istisna da tam muafiyet ya da dahilde işleme için değil kısmi muafiyetli geçici ithalat için getirilmiştir. (MD GK 69/3)',
 kanit='17-BEYAN.txt | Beyannamenin tescilinin bir gümrük yükümlülüğü doğurması halinde, gümrük vergileri ödenmedikçe veya teminata bağlanmadıkça beyanname kapsamı eşya teslim edilemez. Ancak, bu hüküm kısmi muafiyete tabi geçici ithalat rejimine uygulanamaz'),

dict(id='D10-070', cikmis='2025/70', konu='Beyan', tip='T4', z='Z',
 madde='Gümrük Yönetmeliği m.170/1-c, 170/1-d, 170/1-e, 170/1-f, 172/5-b',
 cek='İhracatta karşı taraf halkının pazarlarımızdan ihtiyaçları için alıp götürdüğü eşyada sözlü beyan formu düzenlenmez; sınır halkının satmak üzere götürdüğünde düzenlenir.',
 kok=['Gümrük Yönetmeliğine göre, ihracında beyanın sözlü olarak yapıldığı aşağıdaki eşyadan hangisi, sözlü beyan formu düzenlenmeyecek eşya arasında yer alır?'],
 d='Sınırın diğer tarafındaki halkın pazarlarımızdan kendi ihtiyaçları için alıp götürecekleri eşya',
 c=['Türkiye sınır bölgesi halkının sınırın diğer tarafındaki pazarlara satmak üzere götürecekleri hayvanlar',
    'Bilim adamlarının mesleklerini icra için götürdükleri ticari kıymette olmayan numuneler',
    'Türkiye\'de vefat eden yabancıların kanuni mirasçılarına intikal eden kişisel eşya',
    'İçinde ölünün kül ve kemikleri bulunan vazo ile birlikte gönderilen çelenk ve çiçekler'],
 tuzak=False,
 g='İhracatta sözlü beyana tabi eşyadan karşı taraf halkının pazarlarımızdan kendi ihtiyaçlarını karşılamak amacıyla alıp götürecekleri eşya için sözlü beyan formu düzenlenmez. Aynı bentte yer alan Türkiye sınır bölgesi halkının diğer taraftaki pazarlara satmak üzere götürdüğü eşya ve hayvanlar ile bilim adamlarının numuneleri, mirasçılara intikal eden eşya ve cenazeye ilişkin kaplar sözlü beyana tabi olmakla birlikte form düzenlenmeyecek hâller arasında sayılmamıştır. (MD GY 170/1, 172/5-b)',
 kanit='17-BEYAN.txt | (d) bendinde belirtilen karşı taraf halkının pazarlarımızdan kendi ihtiyaçlarını karşılamak amacıyla alıp götürecekleri eşya || 17-BEYAN.txt | Türkiye sınır bölgesi halkının sınırın diğer taraf bölgesindeki köy, kasaba ve pazarlara satmak üzere birlikte götürecekleri kendi eşya ve hayvanları || 17-BEYAN.txt | İçinde ölü veya ölünün kül ve kemikleri bulunan tabut, vazo ve diğer kaplar ile çelenk ve çiçekler'),
]
