// 12. Konu — Gümrük Kıymeti ve Kaplar (kaynak: 12-KIYMET VE KAPLAR.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '12',
  konu: 'Gümrük Kıymeti ve Kaplar',
  kaynak: '12-KIYMET VE KAPLAR.docx (GK m.23–32; GY m.43–59; Gümrük Genel Tebliği (Gümrük Kıymeti) Seri No: 2 m.3–12)',
  bolumler: [
    { baslik: 'Gümrük Kıymeti ve Satış Bedeli Yöntemi (GK m.23–24; GY m.45)', sorular: [
      ['Eşyanın gümrük kıymeti hangi amaçla belirlenir?',
        '**Gümrük Tarifesinin** ve eşya ticaretine ilişkin belirli konularda getirilen **tarife dışı düzenlemelerin** uygulanması amacıyla.', 'GK m.23; GY m.44/1', '',
        'Eşyanın gümrük kıymeti, Gümrük Tarifesinin ve eşya ticaretine ilişkin belirli konularda getirilen tarife dışı düzenlemelerin uygulanması amacıyla'],
      ['İthal eşyasının gümrük kıymeti nedir; satış bedeli nasıl tanımlanır?',
        'Eşyanın **satış bedeli**dir: Türkiye\'ye ihraç amacıyla yapılan satışta **27 ve 28. maddelere** göre düzeltilmiş, **fiilen ödenen veya ödenecek fiyat**.', 'GK m.24/1', '',
        ['İthal eşyasının gümrük kıymeti, eşyanın satış bedelidir.', 'Satış bedeli, Türkiye\'ye ihraç amacıyla yapılan satışta 27 ve 28 inci maddelere göre gerekli düzeltmelerin de yapıldığı, fiilen ödenen veya ödenecek fiyattır.']],
      ['Alıcının eşyayı elden çıkarma veya kullanımına konulan hangi kısıtlamalar satış bedelinin esas alınmasını engellemez?',
        '**TC mevzuatı ve yetkili kıldığı mercilerce** konulan, **tekrar satış coğrafi bölgesini sınırlayan** ve **kıymeti önemli ölçüde etkilemeyen** kısıtlamalar; bunlar dışında hiçbir kısıtlama olmamalıdır.', 'GK m.24/1-a', '2022',
        ['Türkiye Cumhuriyeti mevzuatı ve bunların yetkili kıldığı merciler tarafından konulmuş olan', 'Eşyanın tekrar satılabileceği coğrafi bölgeyi sınırlayan', 'Eşyanın kıymetini önemli bir ölçüde etkilemeyen', 'Kısıtlamalar dışında, hiçbir kısıtlamaya tabi olmamalıdır.']],
      ['Tekrar satış hasılatının bir bölümü satıcıya intikal ediyorsa satış bedeli esas alınabilir mi?',
        'Evet, ancak intikal eden kısım **27. maddeye göre fiyata ilave edilebilmelidir** (hasılanın satıcıya intikal eden kısmı m.27/1-d ile eklenir).', 'GK m.24/1-c; 27/1-d', '',
        ['ithal eşyasının fiilen ödenen veya ödenecek fiyatına 27 nci madde hükümlerine göre ilave yapılabilmelidir', 'hâsılanın, doğrudan veya dolaylı olarak satıcıya intikal eden kısmı']],
      ['Alıcı ile satıcı arasındaki ilişki satış bedelinin reddi için yeterli midir?',
        '**Tek başına yeterli değildir**; satış koşulları incelenip ilişkinin **fiyatı etkilemediği** belirlenirse satış bedeli kabul edilir. İdare fiyatı etkilediği kanısındaysa beyan sahibine **yazılı bildirir** (cevap hakkı saklı).', 'GK m.24/2-a', '2022',
        ['alıcı ile satıcı arasında bir ilişkinin varlığı, satış bedelinin reddedilmesi için tek başına yeterli bir neden oluşturmaz', 'bu ilişkinin fiyatı etkilemediği belirlenirse, satış bedeli kabul edilir', 'bu hususları beyan sahibine yazılı olarak bildirir', 'Süresi içinde verilmek şartıyla beyan sahibinin cevap hakkı saklıdır.']],
      ['İlişkili kişiler arası satışta beyan sahibi satış bedelinin hangi emsal kıymetlere çok yakın olduğunu ispatlayabilir?',
        'Aynı/benzer eşyanın **ilişkisiz** alıcı-satıcılar arasındaki Türkiye\'ye ihraç satış bedeli; aynı/benzer eşyanın **m.25/2-c** (indirgeme) ve **m.25/2-d** (hesaplanmış kıymet) ile belirlenen kıymeti.', 'GK m.24/2-b', '',
        ['Türkiye\'ye ihraç amacıyla satılan aynı veya benzer eşyanın birbiriyle hiçbir ilişkisi bulunmayan satıcılar ve alıcılar arasında satışındaki satış bedeli', 'Aynı veya benzer eşyanın, 25 inci maddenin 2 nci fıkrasının (c) bendi hükümlerine göre belirlenen gümrük kıymeti', 'Aynı veya benzer eşyanın, 25 inci maddenin 2 nci fıkrasının (d) bendi hükümlerine göre belirlenen gümrük kıymeti']],
      ['Emsal kıymetler kimin girişimiyle, hangi amaçla kullanılır; satış bedelinin yerine geçebilir mi?',
        '**Beyan sahibinin girişimi** ile ve **yalnız kıyaslama** amacıyla; bunlara dayanarak satış bedelinin **yerini alacak kıymet tespit edilemez**.', 'GK m.24/2-c', '',
        ['beyan sahibinin girişimi ile ve yalnız kıyaslama amacıyla kullanılır', 'eşyanın satış bedelinin yerini alacak bir kıymet tespit edilemez']],
      ['Fiilen ödenen veya ödenecek fiyat nedir; ödemeler hangi şekillerde yapılabilir?',
        'Alıcının satıcıya veya satıcı yararına yaptığı/yapması gereken **ödemelerin toplamı**; **para transferi**, **akreditif**, **ciro edilebilir kıymetli evrak** ile ya da doğrudan/dolaylı.', 'GK m.24/3-a', '',
        ['ithal eşyası için alıcının, satıcıya veya satıcı yararına yaptığı veya yapması gereken ödemelerin toplamıdır', 'Ödemeler, para transferi şeklinde olabileceği gibi, akreditif veya ciro edilebilir bir kıymetli evrak kullanılarak ya da doğrudan veya dolaylı yapılabilir.']],
      ['Alıcının pazarlama dahil kendi hesabına yaptığı faaliyetlerin giderleri fiyata eklenir mi?',
        '**Hayır**; satıcı yararına veya satıcıyla anlaşmayla yapılsa da **dolaylı ödeme sayılmaz**, fiyata **ilave edilmez** (m.27 ilaveleri hariç).', 'GK m.24/3-b', '2021, 2022',
        ['alıcının pazarlama dahil kendi hesabına yaptığı faaliyetler, satıcı yararına veya satıcı ile yapılan bir anlaşma yoluyla da olsa, satıcıya yapılan dolaylı bir ödeme olarak değerlendirilmez', 'Bu tür işlemlere ilişkin giderler, ithal eşyasının gümrük kıymetinin tespiti sırasında fiilen ödenen veya ödenecek fiyata ilave edilmez.']],
      ['Kıymet belirlenirken eşya bedeli henüz ödenmemişse hangi bedel esas alınır?',
        '**Ödemenin gerçekleşeceği tarihte ödenecek bedel.**', 'GY m.45/1-b', '',
        'ödemenin gerçekleşeceği tarihte ödenecek olan bedel kıymet tespitine esas alınır'],
      ['Serbest dolaşıma girişten sonra satıcının kusur/garanti nedeniyle alıcı lehine yaptığı fiyat düzeltmesi hangi sürede yapılmışsa dikkate alınır?',
        'Beyannamenin tescilinden itibaren **bir yıl** içinde; GK **m.211** çerçevesinde işlem yapılır.', 'GY m.45/1-ç', '',
        ['beyannamenin tescilinden itibaren bir yıl içinde yapılmış olması gerekir', 'fiyatta yapılan düzeltme satış bedeli yöntemine göre gümrük kıymetinin tespitinde dikkate alınır ve Kanunun 211 inci maddesi çerçevesinde işlem yapılır']],
      ['Türkiye\'ye ihraç amacıyla satış kabulü için ne yeterlidir; ardıl satışlarda hangi satış esas alınır?',
        'Eşyanın **serbest dolaşıma giriş rejimi için beyan edilmesi** yeterlidir; ardıl satışlarda TGB\'ye girişe yol açan **son satış** veya serbest dolaşımdan önce TGB\'de gerçekleşen satış.', 'GY m.45/1-d', '',
        ['satış konusu eşyanın serbest dolaşıma giriş rejimi için beyan edilmesi, bunların Türkiye\'ye ihraç amacıyla satıldığının kabul edilmesi için yeterli sayılır', 'eşyanın Türkiye Gümrük Bölgesine girmesine yol açan son satış veya eşyanın serbest dolaşıma giriş rejimine tabi tutulmasından önce Türkiye Gümrük Bölgesinde gerçekleşen satış']],
    ] },
    { baslik: 'Diğer Yöntemler, Sıralama ve Son Yöntem (GK m.25–26; GY m.44, 46–50)', sorular: [
      ['Gümrük kıymeti yöntemleri ve uygulama sırası nedir?',
        '**Satış bedeli** → **aynı eşyanın** satış bedeli → **benzer eşyanın** satış bedeli → **indirgeme** → **hesaplanmış kıymet** → **son yöntem**.', 'GK m.24–26; GY m.44–50', '2023, 2024',
        ['45 ila 50 nci maddelerde yer alan yöntemlerin sırasıyla uygulanması yoluyla tayin ve tespit olunan kıymettir', 'Satış bedeli yöntemi', 'Aynı eşyanın satış bedeli yöntemi', 'Benzer eşyanın satış bedeli yöntemi', 'İndirgeme yöntemi', 'Hesaplanmış kıymet yöntemi', '45 ila 49 inci maddelerde yer alan yöntemlere göre belirlenemeyen ithal eşyasının gümrük kıymeti Kanunun 26 ncı maddesinde belirtilen esaslar çerçevesinde belirlenir']],
      ['Üst yöntemle kıymet belirlenebiliyorsa alt yönteme geçilebilir mi?',
        '**Hayır**; ancak bir yönteme göre belirlenemeyen kıymet için **sıra dahilinde** izleyen yönteme geçilir.', 'GK m.25/1; GY m.44/1', '',
        ['Bir yönteme göre belirlenemeyen kıymet için sıra dahilinde olmak üzere izleyen yönteme geçilir.', 'Eşyanın gümrük kıymeti bir üst maddede yer alan yöntem hükümlerine göre belirlenebildiği sürece bir alt madde hükümleri uygulanamaz.']],
      ['Hangi yöntemlerin uygulama sırası, hangi şartla değiştirilebilir?',
        '**İndirgeme** ile **hesaplanmış kıymet** yöntemlerinin; **beyan sahibinin yazılı talebinin** gümrük idaresince **uygun bulunması** şartıyla.', 'GK m.25/1; GY m.44/1', '2021',
        'beyan sahibinin yazılı talebinin gümrük idaresince uygun bulunması şartıyla, aşağıda yer alan yöntemlerden indirgeme yöntemi ile hesaplanmış kıymet yönteminin uygulama sırası değiştirilebilir'],
      ['Beyan edilen kıymetin doğruluğu konusunda idarenin makul şüpheleri giderilmezse ne olur?',
        'Kıymet **satış bedeli yöntemine göre tespit edilemez**; sıradaki **diğer yöntemlere** göre belirlenir.', 'GY m.44/5', '',
        ['gümrük idaresinin makul şüpheleri giderilmediği takdirde eşyanın gümrük kıymeti satış bedeli yöntemine göre tespit edilemez', 'Bu durumda gümrük kıymeti birinci fıkrada belirtilen usul çerçevesinde diğer yöntemlere göre belirlenir.']],
      ['Aynı (veya benzer) eşya yönteminde hangi satış bedeli kullanılır; böyle satış yoksa ne yapılır?',
        '**Aynı ticari düzey** ve **yaklaşık aynı miktarda** satılan eşyanın satış bedeli; yoksa düzey/miktar farkları için **düzeltme** yapılır ve düzeltmenin makul ve doğru olduğu **kesin delillerle ispat** edilir.', 'GY m.46/2; 47/2', '',
        ['kıymeti belirlenecek eşya ile aynı ticari düzey ve yaklaşık aynı miktarda satılan aynı eşyanın satış bedeli kullanılır', 'düzeltmenin yapılabilmesi için makul olduğunun ve doğruluğunun kesin delillerle ispatı gerekir']],
      ['Aynı veya benzer eşya yönteminde birden fazla satış bedeli tespit edilirse hangisi kullanılır?',
        '**En düşük olanı.**', 'GY m.46/4; 47/4', '',
        'birden fazla satış bedeli tespit edilirse, ithal eşyasının gümrük kıymetini belirlemek üzere bunlardan en düşük olanı kullanılır'],
      ['İndirgeme yönteminde hangi birim fiyat esas alınır?',
        'Eşyanın ya da aynı/benzer eşyanın **ithal edildiği hal ve durumda**, yurt içindeki satıcıdan **müstakil alıcılara**, ithal tarihiyle aynı/yakın tarihte yapılan **en büyük miktardaki satışına** ait birim fiyat.', 'GK m.25/2-c; GY m.48/1', '',
        ['Türkiye\'de ithal edildiği hal ve durumda satılmışsa', 'yurt içindeki satıcıdan müstakil alıcılara kıymeti belirlenecek eşyanın ithal tarihi ile aynı veya yakın bir tarihte yapılan en büyük miktardaki satışına ait birim fiyat esas alınır']],
      ['İndirgeme yönteminde birim fiyattan hangi indirimler yapılır?',
        'Mutat **komisyon veya kâr** ve pazarlama dahil **genel giderler**; **Türkiye sınırları içindeki** mutat nakliye-sigorta giderleri; Türkiye\'de ödenecek **gümrük vergileri ve dahili vergiler**.', 'GY m.48/2', '',
        ['mutat olarak ödenen veya ödenmesi kararlaştırılan komisyon veya kar ve söz konusu eşyanın pazarlanmasına ilişkin doğrudan ya da dolaylı giderler dahil olmak üzere genel giderler', 'Türkiye sınırları içinde gerçekleşen mutat nakliye ve sigorta giderleri ile bunlarla ilgili diğer giderler.', 'Eşyanın ithali veya satışı nedeniyle Türkiye\'de ödenecek gümrük vergileri ile diğer dahili vergiler.']],
      ['İndirgeme yönteminde ithal tarihiyle aynı/yakın tarihte satış yoksa hangi satış esas alınır?',
        'İthal tarihinden itibaren **doksan gün** içinde, ithal edildiği hal ve durumda Türkiye\'de yapılan **ilk satışın** birim fiyatı.', 'GY m.48/3', '2021',
        'ithal tarihinden itibaren doksan gün içinde ithal edildiği hal ve durumda Türkiye\'de yapılan ilk satışına ait birim fiyat esas alınır'],
      ['İndirgemede "en büyük miktardaki satışa ait birim fiyat" ne demektir?',
        'İthalden sonraki **ilk ticari düzeyde** müstakil alıcılara farklı fiyatlarla yapılan satışlardan **en yüksek sayıda birimin satıldığı fiyat**.', 'GY m.48/5', '',
        'ithal edildikten sonraki ilk ticari düzeyde satıcıdan müstakil alıcılara, farklı fiyatlarda yapılan satışlardan en yüksek sayıda birimin satıldığı fiyat anlamına gelir'],
      ['Hesaplanmış kıymet hangi unsurların toplamıdır?',
        '**Malzeme ve imalat** bedelleri + aynı sınıf/cins eşyada **mutat kâr ve genel giderler** + giriş liman/yerine kadar **yükleme, boşaltma, elleçleme, nakliye ve sigorta** giderleri.', 'GK m.25/2-d; GY m.49/2', '2022',
        ['İthal eşyasının üretiminde kullanılan malzeme ve yapılan imalat veya diğer imal işlemlerinin bedel veya kıymetleri', 'kıymeti belirlenecek eşya ile aynı sınıf veya cins eşyanın satışında mutat olan kar ve genel giderlere eşit bir tutar', 'İthal eşyasının giriş liman veya yerine kadar nakliyesi ile ilgili olarak yapılan yükleme, boşaltma, elleçleme giderleri ile nakliye ve sigorta giderleri.']],
      ['Hesaplanmış kıymet yönteminin uygulanması için ithalatçıdan ne istenir?',
        'Bilgi ve belgeleri ibraz etmesi ve doğruluğunu ispata hazır olduğunu **üretici ülke makamlarından alacağı belge** ile tevsik etmesi.', 'GY m.49/1', '',
        'ithalatçının gerekli bilgi ve belgeleri gümrük idaresine ibraz etmesi ve bu bilgi ve belgelerin doğruluğunu ispata hazır olduğunu üretici ülke makamlarından alacağı belge ile tevsik etmesi gerekir'],
      ['Son yöntemde gümrük kıymeti hangi prensiplere göre belirlenir?',
        '1994 GATT **VII. Maddesinin Uygulanmasına İlişkin Anlaşma**, 1994 GATT **VII. Maddesi** ve **bu bölüm** hükümlerinin prensip ve genel hükümlerine uygun yöntemlerle, **Türkiye\'de mevcut veriler** esas alınarak.', 'GK m.26/1; GY m.50', '2025',
        ['1994 Gümrük Tarifeleri ve Ticaret Genel Anlaşmasının VII nci Maddesinin Uygulanmasına İlişkin Anlaşmanın', 'Prensip ve genel hükümlerine uygun yöntemlerle ve Türkiye\'de mevcut veriler esas alınarak belirlenir.']],
      ['Son yöntemde esas alınamayacak kıymetler nelerdir?',
        'Türkiye\'de üretilen eşyanın **Türkiye içi satış fiyatı**; iki alternatiften **yüksek olanı** öngören sistem; ihraç ülkesi **iç piyasa fiyatı**; hesaplanmış kıymet dışındaki **maliyet bedeli**; **başka ülkeye ihraç** edilen eşyanın fiyatı; **asgari** gümrük kıymetleri; **keyfi veya fiktif** kıymetler.', 'GK m.26/2', '2022',
        ['Türkiye\'de üretilen eşyanın Türkiye içindeki satış fiyatı', 'Gümrük idaresinin iki alternatif kıymetten yüksek olanının kabul etmesini öngören bir sistem', 'Eşyanın ihraç ülkesindeki iç piyasa fiyatı', 'hesaplanmış kıymeti dışındaki maliyet bedeli', 'Türkiye\'den başka bir ülkeye ihraç edilen eşyanın fiyatı', 'Asgari gümrük kıymetleri', 'Keyfi veya fiktif kıymetler']],
    ] },
    { baslik: 'Tanımlar ve Alıcı-Satıcı İlişkisi (GY m.43, 55)', sorular: [
      ['"Aynı eşya" nasıl tanımlanır?',
        '**Fiziksel özellik, kalite ve tanındığı özellikleri** dahil her hususta aynı olan ve **aynı ülkede üretilmiş** eşya; görünüşteki küçük farklılıklar engel değildir.', 'GY m.43/1-b', '2022',
        'Aynı eşya: Fiziksel özellik, kalite ve tanındığı özellikleri dahil olmak üzere her hususta aynı olan ve aynı ülkede üretilmiş eşyayı (görünüşteki küçük farklılıklar diğer hususlarda tanıma uyan eşyanın aynı eşya sayılmasını önlemez)'],
      ['Aynı veya benzer eşyanın aynı üretici tarafından üretilmiş olması şart mıdır?',
        '**Hayır**; aynı kişinin ürettiği eşya yoksa **farklı kişinin ürettiği** eşya dikkate alınır. Ancak yalnızca **aynı ülkede** üretilen eşya aynı/benzer eşya sayılır.', 'GY m.43/3–4', '2022',
        ['aynı kişi tarafından üretilmiş aynı veya benzer eşya bulunmadığı takdirde, farklı kişi tarafından üretilmiş eşya dikkate alınır', 'Yalnızca kıymeti belirlenecek eşya ile aynı ülkede üretilen eşya']],
      ['"Benzer eşya" nedir; benzerliğin belirlenmesinde hangi faktörler göz önüne alınır?',
        'Her hususta aynı olmasa da **aynı işlevi** gören, **ticari olarak ikame** edilebilen, benzer özellik/unsurları olan ve **aynı ülkede üretilmiş** eşya; faktörler: **kalite, tanındığı özellikler, ticari marka**.', 'GY m.43/1-d', '2022, 2024',
        'Benzer eşya: Her hususta aynı olmamakla birlikte aynı işlevi görmelerini ve ticari olarak birbirlerini ikame edebilmelerini mümkün kılan, benzer özellik ve benzer unsurları bulunan ve aynı ülkede üretilmiş olan eşyayı (eşyanın kalitesi, tanındığı özellikleri, bir ticari markasının bulunması, eşyanın benzerliğinin belirlenmesinde göz önüne alınacak faktörler arasında yer alır)'],
      ['"Aynı sınıf veya cins eşya" nedir?',
        '**Belli bir sanayi sektöründe** üretilen bir grup veya dizi eşya kapsamındaki eşya (aynı/benzer eşyayı da kapsar).', 'GY m.43/1-c', '',
        'Aynı sınıf veya cins eşya: Belli bir sanayi sektöründe üretilen bir grup veya bir dizi eşya kapsamına giren eşyayı (bu ifade aynı veya benzer eşyayı da kapsar)'],
      ['"Giriş limanı veya yeri" taşıma şekline göre neresidir?',
        'Deniz: Türkiye\'deki **boşaltma** limanı (belgeyle tevsik edilirse **aktarma** limanı); kara/demiryolu: **ilk varılan hudut gümrüğü**; diğer yollar: **kara sınırının geçildiği nokta**.', 'GY m.43/1-e', '',
        'Giriş limanı veya yeri: Deniz yolu ile gelen eşyada Türkiye\'deki boşaltma veya ilgili limandaki gümrük idaresince düzenlenen belgeyle tevsik edilmek kaydıyla aktarma limanını, karayolu ve demiryolu ile gelen eşyada kara taşıtlarının ilk vardıkları hudut gümrüğünü, diğer bir yolla gelen eşyada gümrük bölgesinin kara sınırının geçildiği noktayı'],
      ['Kıymet mevzuatında "pazarlama" nedir?',
        'Eşyanın satışı için **reklam ve promosyon** faaliyetleri ve ilgili **garantiler**; alıcının üstlendiği bu faaliyetler satıcıyla anlaşma gereği yapılsa da **kendi hesabına** sayılır.', 'GY m.43/1-g', '',
        ['Pazarlama: Eşyanın satışı için yapılan reklam ve promosyon faaliyetleri ile bunlarla ilgili garantileri', 'kendi hesabına üstlenilmiş sayılması gerektiğini']],
      ['Royalti ve lisans ücreti tanımında hangi adlar sayılır?',
        '**Patent, dizayn, know-how, model, marka, tescilli tasarım, telif hakkı ve imalat prosesleri** gibi adlar altında yapılan ödemeler.', 'GY m.43/1-ğ; Tebliğ (Kıymet Seri No: 2) m.3/1-a', '2022',
        'patent, dizayn, know-how, model, marka, tescilli tasarım, telif hakkı ve imalat prosesleri gibi adlar adı altında yapılan ödemeleri'],
      ['"Aynı ailenin üyeleri" kapsamına kimler girer?',
        'Karı-koca, anne-baba, çocuk, kardeşler, büyükanne-büyükbaba, torun, amca, dayı, hala, teyze, **yeğen**, eşlerin anne-babası, **gelin ve damat**, eşlerin kardeşleri ve kardeşlerin eşleri.', 'GY m.43/1-a', '',
        'Aynı ailenin üyeleri: Karı, koca, anne, baba, çocuk, erkek ve kız kardeş (öz ya da anne veya babadan biri öz), büyükbaba, büyükanne, torun, amca, dayı, hala, teyze, yeğen, eşlerin anne ve babası, çocukların eşleri (gelin ve damat), eşlerin kardeşleri ve kardeşlerin eşleri'],
      ['Alıcı ile satıcı arasında ilişki hangi hallerde kabul edilir?',
        '**Yalnızca**: birbirinin **memuru/idarecisi**; **yasal ortak**; **işçi-işveren**; oy hakkı veren pay/sermayenin **en az %5\'i** aynı kişilerde; biri diğerini **kontrol**; ikisi de **üçüncü kişinin kontrolünde**; ikisi birlikte üçüncü kişiyi kontrol; **aynı ailenin üyeleri**.', 'GY m.55/1', '2022, 2023, 2024',
        ['alıcı ile satıcı arasındaki ilişkinin varlığı yalnızca aşağıdaki durumlarda kabul edilir', 'Birbirlerinin memuru veya idarecileri olmaları', 'Birbirlerinin yasal ortakları olmaları', 'İşçi ve işveren ilişkisi içinde bulunmaları', 'sermaye paylarının en az % 5\'i doğrudan veya dolaylı olarak aynı kişilere ait olması', 'Birinin diğerini dolaylı veya dolaysız olarak kontrol etmesi', 'Her ikisinin de doğrudan veya dolaylı olarak bir üçüncü kişi tarafından kontrol edilmesi', 'Her ikisinin birlikte, bir üçüncü kişiyi doğrudan veya dolaylı olarak kontrol etmesi', 'Aynı ailenin üyeleri olmaları']],
      ['Tek acente, tek distribütör veya tek bayi ilişkisi tek başına ilişki sayılır mı?',
        '**Hayır**; m.55/1 kıstaslarına uymuyorlarsa **ilişki içinde olmadıkları kabul edilir**.', 'GY m.55/2', '2022',
        'Tek acente, tek distribütör veya tek bayii olarak birbiri ile iş ilişkisi içinde bulunan kişilerin yukarıdaki kıstaslara uymamaları durumunda, ilişki içinde olmadıkları kabul edilir.'],
    ] },
    { baslik: 'Fiyata Eklenen ve Eklenmeyen Unsurlar (GK m.27–28; GY m.51–52)', sorular: [
      ['Alıcının üstlendiği ve fiyata dahil edilmemiş hangi giderler (m.27/1-a) fiyata eklenir?',
        '**Satın alma komisyonları dışındaki** komisyonlar ve tellaliye; eşya ile **tek eşya muamelesi gören kapların** maliyeti; işçilik ve malzeme dahil **ambalaj** bedeli.', 'GK m.27/1-a', '2022',
        ['Satın alma komisyonları dışındaki komisyonlar ve tellâliye', 'Gümrük işlemleri sırasında söz konusu eşya ile tek eşya muamelesi gören kapların maliyeti', 'İşçilik ve malzeme giderleri dahil ambalaj bedeli']],
      ['Alıcının bedelsiz/düşük bedelle sağladığı hangi mal ve hizmetlerin uygun payı (m.27/1-b) fiyata eklenir?',
        'Eşyaya katılan **malzeme, aksam, parça**; üretimde kullanılan **araç, gereç, kalıp**; üretimde **tüketilen maddeler**; **Türkiye dışında** gerçekleştirilen mühendislik, geliştirme, sanat-çizim, plan ve taslak hizmetleri.', 'GK m.27/1-b', '2023, 2024',
        ['İthal eşyasına katılan malzeme, aksam, parça ve benzerleri', 'İthal eşyasının üretimi sırasında kullanılan araç, gereç, kalıp ve benzeri aletler', 'İthal eşyasının üretimi sırasında tüketilen maddeler', 'İthal eşyasının üretimi için gereken ve Türkiye dışında gerçekleştirilen mühendislik, geliştirme, sanat ve çizim çalışmaları, plan ve taslak hazırlama hizmetleri']],
      ['Alıcının bedelsiz sağladığı plan ve taslak hizmetleri Türkiye\'de yapılmışsa kıymete eklenir mi?',
        '**Hayır**; m.27/1-b-iv yalnızca **Türkiye dışında** gerçekleştirilenleri sayar ve m.27\'de öngörülenler dışında **hiçbir ilave yapılamaz**.', 'GK m.27/1-b-iv, 27/3', '2023',
        ['Türkiye dışında gerçekleştirilen mühendislik, geliştirme, sanat ve çizim çalışmaları, plan ve taslak hazırlama hizmetleri', 'fiilen ödenen veya ödenecek fiyata bu maddede öngörülenler dışında hiçbir ilave yapılamaz']],
      ['Türkiye\'deki giriş yerine kadar hangi giderler fiyata eklenir?',
        'Giriş liman veya yerine kadar yapılan **nakliye ve sigorta** giderleri ile bu nakliyeyle ilgili **yükleme ve elleçleme** giderleri.', 'GK m.27/1-e', '2024, 2025',
        'ithal eşyası için Türkiye\'deki giriş liman veya yerine kadar yapılan nakliye ve sigorta giderleri ile eşyanın giriş liman veya yerine kadar nakliyesi ile ilgili olarak yapılan yükleme ve elleçleme giderleri'],
      ['Fiyata yapılacak ilavelerde hangi veriler esas alınır?',
        '**Nesnel ve ölçülebilir** veriler.', 'GK m.27/2', '',
        'ilaveler için nesnel ve ölçülebilir veriler esas alınır'],
      ['"Satın alma komisyonu" nedir; gümrük kıymetine dahil edilir mi?',
        'İthalatçının temsilcisine, eşyanın satın alınmasında **yurt dışında verdiği temsil hizmeti** karşılığı ödediği ücret; kıymete **dahil edilmez**.', 'GK m.27/4; 28/e', '2022',
        ['ithalatçının temsilcisine kıymeti belirlenecek eşyanın satın alınmasında yurtdışında verdiği temsil hizmeti karşılığında ödediği ücret anlaşılır', 'e) Satın alma komisyonları;']],
      ['Türkiye\'de çoğaltma hakkı ile dağıtım/tekrar satış hakları için yapılan ödemeler fiyata eklenir mi?',
        '**Hayır**; çoğaltma hakkı ödemeleri ile **satış koşulu olmayan** dağıtım/tekrar satış hakkı ödemeleri m.27/1-c (royalti) kapsamında değerlendirilmez, **eklenmez**.', 'GK m.27/5', '2024',
        ['Türkiye\'de çoğaltılması hakkı için yapılan ödemeler', 'Türkiye\'ye ihraç amacıyla satışında bir satış koşulu olmaması kaydıyla, dağıtım veya tekrar satış hakları için alıcının yaptığı ödemeler', '1 inci fıkranın (c) bendi kapsamında değerlendirilmez ve fiilen ödenen veya ödenecek fiyata ilave edilmez']],
      ['Hangi giderler, fiyattan ayırt edilebilmeleri koşuluyla gümrük kıymetine dahil edilmez?',
        'Giriş yerine **varıştan sonraki** nakliye-sigorta; ithalattan sonraki **inşa, kurma, montaj, bakım, teknik yardım**; finansman anlaşmasına bağlı **faiz**; Türkiye\'de **çoğaltma hakkı** ödemeleri; **satın alma komisyonları**; Türkiye\'de ödenecek **ithalat vergileri**.', 'GK m.28', '2024',
        ['İthal eşyasının fiilen ödenen veya ödenecek fiyatından ayırt edilebilmeleri koşuluyla aşağıdaki giderler gümrük kıymetine dahil edilmez', 'giriş yerine varışından sonra yapılan nakliye ve sigorta giderleri', 'ithalattan sonra yapılan inşa, kurma, montaj, bakım veya teknik yardıma ilişkin giderler', 'bir finansman anlaşması uyarınca alıcı tarafından üstlenilen faiz giderleri', 'İthal eşyasının Türkiye\'de çoğaltılması hakkı için yapılan ödemeler', 'Eşyanın ithali veya satışı nedeniyle Türkiye\'de ödenecek ithalat vergileri']],
      ['Faiz giderlerinin kıymete dahil edilmemesi için hangi şartlar aranır?',
        'Finansman anlaşması **yazılı** olmalı; alıcı gerektiğinde eşyanın **beyan edilen fiyattan satıldığını** ve faiz oranının finansmanın sağlandığı ülkede **o tarihte geçerli faiz seviyesini aşmadığını** kanıtlamalı. Finansmanı kimin sağladığına **bakılmaz**.', 'GK m.28 (son fıkra)', '',
        ['finansmanın satıcı veya bir başka kişi tarafından sağlanmış olmasına bakılmaz', 'finansman anlaşmasının yazılı olarak yapılmış olması', 'Eşyanın, fiilen ödenen veya ödenecek fiyat olarak beyan edilen fiyattan satıldığını', 'Söz konusu faiz oranının, finansmanın sağlandığı ülkede o tarihte bu tür bir işlem için geçerli olan faiz oranı seviyesini aşmadığını']],
      ['Araştırma ve ilk dizayn taslak giderleri kıymete dahil edilir mi?',
        '**Hayır**, dahil edilmez.', 'GY m.51/2', '',
        'araştırma ve ilk dizayn taslak giderleri gümrük kıymetine dahil edilmez'],
      ['Nakliye ücretsizse veya alıcı tarafından sağlanmışsa giriş yerine kadarki nakliye gideri nasıl tespit edilir?',
        '**Aynı taşıma türünde normal olarak uygulanan fiyat tarifesine** göre.', 'GY m.51/3', '',
        'nakliyenin ücretsiz olması veya alıcı tarafından sağlanması durumunda, gümrük kıymetine dahil edilecek giriş liman veya yerine kadarki nakliye gideri, aynı taşıma türünde normal olarak uygulanan fiyat tarifesine göre tespit edilir'],
      ['Posta ve kargo ücretleri gümrük kıymetine dahil midir?',
        '**İthal ülkesinde alınan ilave** ücretler hariç, **teslim yerine kadar** alınan tüm posta ve kargo ücretleri dahildir.', 'GY m.51/4', '',
        'İthal ülkesinde alınan ilave posta ve kargo ücretleri hariç olmak üzere, eşyanın teslim yerine kadar alınan tüm posta ve kargo ücretleri gümrük kıymetine dahildir.'],
      ['Tek eşya muamelesi gören kaplar tekrarlanan ithalatlarda kullanılacaksa maliyetleri nasıl yansıtılır?',
        'Beyan sahibinin **talebi** ve belgelerin sunulması kaydıyla **genel kabul görmüş muhasebe prensipleri** çerçevesinde **paylaştırılır**.', 'GY m.51/5', '',
        'tekrarlanan ithalatlarda kullanılacak olması halinde, beyan sahibinin talebi üzerine ve gerekli belgelerin sunulması kaydıyla, mezkur maliyetler genel kabul görmüş muhasebe prensipleri çerçevesinde uygun şekilde paylaştırılır'],
      ['Navlun makbuzu/sigorta poliçesi ibraz edilemezse ne yapılır; yükümlü talep ederse hangi oranlar eklenebilir?',
        'Dilekçeyle bildirilerek **emsal** navlun/sigorta eklenir; vergi kaybı yoksa ve talep edilirse **FOB kıymetinin %10\'u navlun**, **%3\'ü sigorta** olarak eklenebilir.', 'GY m.51/9', '',
        ['emsal navlun ve/veya sigorta gideri fiilen ödenen veya ödenecek fiyata eklenir', 'Vergi kaybı söz konusu olmaması ve yükümlünün talep etmesi halinde, ithal eşyasının FOB kıymetinin % 10 unun navlun ve % 3 ünün sigorta bedeli olarak']],
      ['71.08 pozisyonundaki eşyada sigorta poliçesi veya navlun faturası ibraz edilemezse ne yapılır?',
        'Vergi kaybı olmaması kaydıyla işlemler **faturada belirtilen teslim şekli** esas alınarak tamamlanır.', 'GY m.51/9', '',
        '71.08 tarife pozisyonunda yer alan eşyanın sigorta poliçesi veya navlun faturasının ibraz edilememesi halinde, vergi kaybı olmaması kaydıyla, işlemler eşyanın faturasında belirtilen teslim şekli esas alınarak tekemmül ettirilir'],
    ] },
    { baslik: 'Royalti ve Lisans Ücretleri (GY m.56; Gümrük Kıymeti Tebliği Seri No: 2)', sorular: [
      ['Royalti/lisans ücretinin fiyata eklenmesi için hangi iki koşul birlikte aranır?',
        'Ödeme **kıymeti belirlenecek eşya ile ilgili** olmalı ve bu eşyanın **satış koşulu** olarak yapılmalı; ikisini birlikte taşıyan ücret eklenir.', 'GY m.56/1; Tebliğ (Kıymet Seri No: 2) m.5', '',
        ['Ödeme kıymeti belirlenecek eşya ile ilgili olmalıdır.', 'Ödeme bu eşyanın satış koşulu olarak yapılmalıdır.', 'Bu şartların her ikisini bir arada taşıyan royalti veya lisans ücretinin']],
      ['Marka kullanımına ilişkin royalti hangi durumlarda fiyata eklenir?',
        'Aynı durumda yeniden satılan veya ithalden sonra **sadece önemsiz işlemden** geçen eşyaya ilişkinse; eşya ücretin ödendiği **marka altında pazarlanıyorsa**; alıcı eşyayı **ilişkisiz diğer satıcılardan temin etme özgürlüğüne sahip değilse**. Tebliğe göre **en az birinin** varlığı gerekli ve yeterli.', 'GY m.56/3; Tebliğ (Kıymet Seri No: 2) m.8', '',
        ['aynı durumda yeniden satılan veya ithal edildikten sonra sadece önemsiz işlemden geçen eşyaya ilişkin ise', 'ithalattan önce veya sonra yapıştırılan ve royalti veya lisans ücretinin ödendiği marka altında pazarlanıyorsa', 'satıcı ile ilişkisi olmayan diğer satıcılardan temin etme özgürlüğüne sahip değilse', 'aşağıdaki şartlardan en az birinin mevcudiyeti gerekli ve yeterlidir']],
      ['Royalti tutarı ithal eşyasının fiyatına bağlı olarak belirleniyorsa ne varsayılır?',
        'Aksine kanıt yoksa ödemenin **kıymeti belirlenecek eşya ile ilgili** olduğu varsayılır.', 'GY m.56/5', '',
        'Bir royalti veya lisans ücretinin miktarı ithal edilen eşyanın fiyatına bağlı olarak belirleniyor ise, aksi yönde bir kanıt bulunmadığı sürece, bu royalti veya lisans ücretinin ödenmesinin kıymeti belirlenecek eşya ile ilgili olduğu varsayılır.'],
      ['Royaltiyi alacak kişinin yerleşik olduğu ülke dikkate alınır mı?',
        '**Hayır**, dikkate alınmaz.', 'GY m.56/6; Tebliğ (Kıymet Seri No: 2) m.10', '',
        'royalti ve lisans ücretini alacak olan kişinin yerleşik olduğu ülke dikkate alınmaz'],
      ['Royaltiye ilişkin nesnel ve ölçülebilir veri yoksa kıymet nasıl belirlenir?',
        'Satış bedeli (m.24) yöntemiyle **belirlenemez**; GK **m.25 ve 26**\'ya göre tespit edilir.', 'Tebliğ (Kıymet Seri No: 2) m.4/2', '',
        ['Bu tür verilerin olmadığı anlaşıldığında satış bedeli 24 üncü madde hükümlerine göre belirlenemez.', 'Gümrük Kanununun 25 ve 26 ncı maddelerine göre tespit edilir']],
      ['Royaltinin "satış koşulu" olması ne demektir; Tebliğde sayılan hususlardan kaçının bulunması yeterlidir?',
        'Ödemenin alım-satımın gerçekleşmesinde **vazgeçilmez ve esaslı bir unsur** olması (belirleyici unsur: alıcı eşyayı **royalti ödemeden alabilir mi**); sayılan hususlardan **en az birinin** bulunması yeterlidir.', 'Tebliğ (Kıymet Seri No: 2) m.7', '',
        ['ihracatçı ve ithalatçı arasındaki alım-satımın gerçekleşmesinde vazgeçilmez ve esaslı bir unsur olmasını ifade eder', 'alıcının söz konusu eşyaları royalti veya lisans ödemesi yapmadan alıp alamayacağıdır', 'Söz konusu şartlardan en az birinin bulunması halinde royalti veya lisans ödemesi eşyanın satış koşuludur.']],
      ['Tutarı ithalattan sonra belli olacak royalti nasıl beyan edilir; satış hasılatı veya kâr üzerinden hesaplanan royaltide tamamlayıcı beyan ne zamana kadar verilir?',
        'GY m.53 çerçevesinde **istisnai kıymetle** beyan edilebilir; hasılat/kâr üzerinden hesaplananlarda (talep ve idarenin uygun bulmasıyla **FOB bedeli** esas alınarak paylaştırma) tamamlayıcı beyan, ödemenin tahakkuk ettiği ayı takip eden ayın **yirmi altıncı günü akşamına** kadar verilir.', 'Tebliğ (Kıymet Seri No: 2) m.11/2–3', '',
        ['Gümrük Yönetmeliğinin 53 üncü maddesi çerçevesinde istisnai kıymetle beyanda bulunulabilir', 'eşyanın FOB bedeli esas alınarak sözleşme gereği net veya brüt satış hasılatı veya kârına uygulanacak royalti oranına göre yapılacak uygun bir paylaştırma sonucunda hesaplanır', 'royalti veya lisans ücreti ödemesinin tahakkuk ettiği ayı takip eden ayın yirmi altıncı günü akşamına kadar verilir']],
      ['Gümrüğe beyan edilmeyen royaltinin KDV\'si 1 veya 2 no.lu KDV Beyannamesiyle ödenirse ne uygulanır?',
        'Her bir beyan için GK **m.241** uyarınca **usulsüzlük cezası**.', 'Tebliğ (Kıymet Seri No: 2) m.11/6', '',
        'sadece KDV\'ye tabi her bir beyan için Gümrük Kanununun 241 inci maddesi uyarınca usulsüzlük cezası uygulanır'],
    ] },
    { baslik: 'Bilgi Taşıyıcıları, Döviz Kuru ve İstisnai Kıymet (GK m.29–31; GY m.53–54, 57)', sorular: [
      ['Veri/komut yüklü bilgi taşıyıcılarının gümrük kıymetinde ne esas alınır?',
        'Yalnızca **taşıyıcı ortamın** maliyeti/kıymeti; ayırt edilebilmesi koşuluyla **veri veya komutların** kıymeti dahil edilmez.', 'GK m.29; GY m.54/1', '2023',
        ['sadece taşıyıcı ortamın kendisinin maliyeti veya kıymeti esas alınır', 'gümrük kıymeti, veri veya komutların maliyet veya kıymetini içermez']],
      ['"Taşıyıcı ortam" ve "veri veya komutlar" deyimleri neleri kapsamaz?',
        'Taşıyıcı ortam: **entegre devreler, yarı iletkenler** ve benzerlerini; veri/komutlar: **ses, sinematografik veya video kayıtlarını** kapsamaz.', 'GY m.54/2', '2023',
        ['Taşıyıcı ortam deyimi, entegre devreler, yarı iletkenler ve bu tür devre veya cihazlarla bütünlük oluşturan benzeri araç ve aletleri', 'Veri veya komutlar deyimi, ses, sinematografik veya video kayıtlarını, kapsamaz']],
      ['Fatura ve belgelerdeki yabancı paralar hangi kur üzerinden TL\'ye çevrilir?',
        '**Gümrük yükümlülüğünün başladığı tarihte** yürürlükte olan **TCMB döviz satış kurları**; kıymetin **TL olarak beyanı** zorunludur.', 'GK m.30; GY m.57/1', '2021, 2022, 2024',
        ['Eşyanın gümrük vergisine esas alınacak kıymetinin Türk Lirası olarak beyanı zorunludur.', 'gümrük yükümlülüğünün başladığı tarihte yürürlükte olan T.C. Merkez Bankası döviz satış kurları üzerinden Türk Lirasına çevrilir']],
      ['Belgelerdeki yabancı para konvertibl değilse hangi kur esas alınır?',
        'Merkez Bankasının **Alım Satıma Konu Olmayan Dövizlere İlişkin Bilgi Amaçlı Kurlar Listesi**.', 'GY m.57/2', '',
        'Merkez Bankasının Alım Satıma Konu Olmayan Dövizlere İlişkin Bilgi Amaçlı Kurlar Listesi esas alınarak işlem yapılır'],
      ['İstisnai kıymetle beyanda (basitleştirilmiş usul) hangi eşya kapsama girer?',
        'Konsinye teslim edilen **çabuk bozulabilir** eşya; kıymet unsurları yükümlülük başladıktan **sonra belli olacak** eşya; fiyatın **sonradan gözden geçirilmesini** öngören sözleşmeli eşya; **boru hattı/elektrik teliyle** taşınan sürekli akıştaki eşya; gaza dönüştürülüp boru hattına verilen **LNG**. Usul **beyan sahibinin talebi** üzerine uygulanır.', 'GK m.31/2; GY m.53/1', '',
        ['Konsinye şekilde teslim edilen çabuk bozulabilir eşyanın', 'gümrük yükümlülüğünün başladığı tarihten sonra belli olacak eşyanın', 'fiyatın sonradan gözden geçirilmesini öngören hükümler içeren eşyanın', 'Boru hatları veya elektrik telleri ile taşınan ve depolama imkanı olmayan sürekli akış halinde olan eşyanın', 'sıvılaştırılmış doğal gazın (LNG)', 'beyan sahibinin talebi üzerine, gümrük idaresince basitleştirilmiş usuller uygulanır']],
      ['İstisnai kıymetle beyanda hangi koşullar aranmaz; yükümlüden hangi belge istenir?',
        'GY **22–24. maddelerdeki** genel ve özel koşullar aranmaz; (b), (c), (ç) hallerinde sözleşmelerin **örneği ve onaylı çevirisi** sunulur.', 'GY m.53/2', '',
        ['22 ila 24 üncü maddelerdeki genel ve özel koşullar aranmaz', 'sözleşmelerin örneği ve onaylı çevirisini gümrük idarelerine sunmaları gerekir']],
      ['İstisnai kıymette vergi tahakkuku neye göre yapılır; tamamlayıcı beyanla kıymet değişirse ne olur?',
        '**Mevcut belgelerdeki kıymet** esas alınır; kıymet yükselirse **ek tahakkuk**, düşerse şartlarla GK **m.211** çerçevesinde işlem yapılır.', 'GY m.53/3', '',
        ['vergi tahakkuku mevcut belgelerde belirtilen kıymet esas alınarak yapılır', 'gözden geçirilmiş kıymetin daha yüksek olması halinde ek vergi tahakkuku yapılır']],
      ['Tamamlayıcı beyana isabet eden ithalat vergilerinde zamanaşımı ne zaman başlar?',
        '**Tamamlayıcı beyanın verildiği tarihten** itibaren.', 'GY m.53/4', '',
        'zamanaşımı tamamlayıcı beyanın verildiği tarihten itibaren başlar'],
      ['Tescil anında bilinmesi mümkün olmayan kıymet veya KDV matrah unsurları ne zamana kadar beyan edilir?',
        'Unsurun **muhasebe kayıtlarına intikal ettirildiği ayı takip eden ayın yirmi altıncı günü akşamına** kadar; vergiler de aynı sürede ödenir.', 'GY m.53/5', '',
        'en geç söz konusu kıymet veya matrah unsurunun muhasebe kayıtlarına intikal ettirildiği ayı takip eden ayın yirmi altıncı günü akşamına kadar beyanda bulunulur ve vergileri de aynı süre içinde ödenir'],
      ['İstisnai kıymete ilişkin tamamlayıcı beyan süresinde verilmezse ne uygulanır?',
        'Beyannamenin **tescil tarihinden** itibaren **6183 sayılı Kanuna** göre gecikme zammı oranında **gecikme faizi** tahsil edilir ve GK **m.241/1** uyarınca işlem yapılır.', 'GY m.53/7', '',
        ['eşyanın serbest dolaşıma girişine ilişkin beyannamenin tescil tarihinden itibaren 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanun hükümlerine göre belirlenen gecikme zammı oranında gecikme faizi tahsil edilir', 'Kanunun 241 inci maddesinin birinci fıkrası uyarınca işlem yapılır']],
    ] },
    { baslik: 'Eşyanın Ağırlığı ve Kapları (GK m.32; GY m.58–59)', sorular: [
      ['Brüt ve net ağırlık nasıl tanımlanır?',
        '**Brüt**: eşyanın kendi ağırlığı + **tüm ambalaj maddeleri ve kapların** ağırlığı; **net** (veya sadece ağırlık): **eşyanın kendi ağırlığı**.', 'GK m.32/1', '2023',
        ['Brüt ağırlığa atıfta bulunulan hallerde, eşyanın kendi ağırlığı ile tüm ambalaj maddeleri ve kapların ağırlıkları toplamı', 'Net ağırlığa veya sadece ağırlığa atıfta bulunulan hallerde, eşyanın kendi ağırlığı']],
      ['Brüt ağırlık üzerinden vergiye tabi eşya ambalajsız gelirse nasıl vergilendirilir?',
        '**Bulunduğu haldeki ağırlığı** üzerinden.', 'GK m.32/2', '',
        'Brüt ağırlığı üzerinden vergiye tabi eşya ambalajsız geldiği takdirde, söz konusu eşya bulunduğu haldeki ağırlığı üzerinden vergiye tabi tutulur.'],
      ['Değişik vergi oranlı ve brüt ağırlıktan vergiye tabi eşya aynı ambalajda gelirse ne yapılır?',
        'Eşya **net ağırlıkları** üzerinden tartılır, ambalaj ağırlığı **orantılı olarak** net ağırlıklara eklenir.', 'GK m.32/3', '',
        'eşya, net ağırlıkları üzerinden tartılır ve ambalaj ağırlığı orantılı olarak net ağırlıklara ilave edilir'],
      ['Ambalajlar hangi hallerde ayrı beyan edilip kendi tarife pozisyonlarına göre vergilendirilir?',
        '**Alışılagelen** maddelerden olmaması veya gereğinden farklı yapılması; faturada kıymetinin **ayrı gösterilmesi ve bağımsız ticari eşya** niteliği; **ithalat vergilerinden kaçınma** amacıyla getirilmesi.', 'GK m.32/5', '',
        ['Alışılagelen ve bilinen maddelerden olmaması veya gereğinden farklı bir şekilde yapılması', 'Ait oldukları eşyanın faturasında kıymetlerinin ayrı gösterilmesi ve aynı zamanda bağımsız bir ticari eşya niteliğinde olması', 'İthalat vergilerinden kaçınma amacıyla ambalaj olarak getirilmesi']],
      ['Ayrı beyan edilen ambalajın vergi oranı içindeki eşyanınkine eşit veya düşükse vergi nasıl hesaplanır?',
        'Ambalajın vergisi **eşyanın tabi olduğu oran** üzerinden ve **eşya ile birlikte** hesaplanır.', 'GK m.32/5', '',
        'ambalaj maddelerinin gümrük vergisi eşyanın tabi bulunduğu vergi oranları üzerinden ve eşya ile birlikte hesaplanır'],
      ['Kutu, kılıf ve mahfazalar ağırlık ve kıymet üzerinden vergiye tabi eşyada nasıl vergilendirilir?',
        'Ağırlık esasında: alışılagelen ambalaj değilse ve oranları eşyanınkinden **yüksekse kendi pozisyonlarına** göre; kıymet esasında: **bağımsız ticari eşya değilse** ve kıymeti eşyaya **dahilse vergilendirilmez**.', 'GK m.32/6', '',
        ['içindeki eşyanın vergi oranından daha yüksek bulunduğu takdirde, kendilerine ait tarife pozisyonlarına göre vergiye tabi tutulur', 'başlı başına bir ticari eşya niteliğinde olmaması ve kıymetinin eşyanın kıymetine dahil bulunması şartıyla gümrük vergisine tabi tutulmaz']],
      ['Örnekleme ile muayenede tartılan kaplarda beyana göre fazlalık bulunursa ne yapılır?',
        'Tartılmamış aynı cins kaplara **fazlalığın ortalaması** esas alınarak ilave yapılır; beyan sahibi kabul etmezse **bütün kaplar tartılır**.', 'GK m.32/7-a', '',
        ['aynı cins ve türden eşyanın tartılmamış kaplarına da bu fazlalığın ortalaması esas alınarak ilaveler yapılır', 'Beyan sahibi, bu şekilde yapılan işlemi kabul etmez ise gümrük idaresi tarafından bütün kaplar tartılır.']],
      ['Tartılan kaplarda beyana göre eksiklik saptanırsa vergiler hangi miktar üzerinden hesaplanır?',
        'Eksikliğin **doğal özellik, hasar, noksan gönderme veya çalınmadan** kaynaklandığı kanıtlanırsa **bulunan miktar** üzerinden; idarenin ve beyan sahibinin bütün kapları tarttırma hakkı saklıdır.', 'GK m.32/7-b', '',
        ['eşyanın doğal özelliklerinden veya hasara uğramasından veya noksan gönderildiğinden veya çalınmasından ileri geldiğinin kanıtlanması halinde, ithalat vergileri bulunan miktar üzerinden hesaplanır', 'gümrük idaresinin veya beyan sahibinin bütün kapları tarttırmak hakları saklıdır']],
      ['Tarife pozisyonu tayini için tartımda iç ambalajlarından ayrılabilen ve ayrılamayan eşya nasıl tartılır?',
        'Ayrılabilenler **net**, ayrılamayanlar **ambalajı ile birlikte** tartılır.', 'GY m.58/1', '',
        'ilk iç ambalajlarından ayrılabilenler net olarak, iç ambalajlarından ayrılamayanlar ise ambalaj ile birlikte tartılır'],
      ['Deniz taşıtlarının tonajı nasıl tayin edilir; tereddütte kime sorulur?',
        '**Belgelerinde yazılı miktarlar** esas alınır; istiap hacmi tonilatosu gösterilmemiş veya tereddütlü ise **yetkili liman makamlarına** sorulur.', 'GY m.59/1', '',
        ['Deniz taşıtlarının tonajlarını tayin için, belgelerinde yazılı miktarlar nazara alınır.', 'bu durum yetkili liman makamlarından sorulur']],
    ] },
  ],
  tuzaklar: [
    '**Satın alma komisyonu** (ithalatçının yurt dışındaki temsilcisine ödenen) kıymete **eklenmez**; bunun dışındaki **komisyon ve tellaliye**, alıcı üstlenmişse **eklenir**.',
    'Sıra değişikliği yalnızca **indirgeme ↔ hesaplanmış kıymet** arasında ve **beyan sahibinin yazılı talebi + idarenin uygun bulması** ile mümkündür. Son yöntemde **asgari, keyfi/fiktif** kıymet ve **iki kıymetten yüksek olanı** esas alınamaz.',
    '**Aynı/benzer eşya**: **aynı ülkede** üretilmiş olmak şarttır; **aynı üretici** şart değildir. Benzer eşyada **kalite, tanınırlık ve ticari marka** göz önüne alınacak faktörlerdir.',
    'Nakliye-sigorta: **giriş yerine kadar** olanlar **eklenir**, giriş yerine **varıştan sonrakiler** eklenmez. İndirgeme yönteminde ise **Türkiye içindeki** nakliye-sigorta birim fiyattan **indirilir**.',
    'Alıcının sağladığı mühendislik/plan/taslak hizmetleri yalnızca **Türkiye dışında** yapılmışsa eklenir; **araştırma ve ilk dizayn taslak** giderleri eklenmez; alıcının **pazarlama** dahil kendi hesabına faaliyetleri eklenmez.',
    'İlişki halleri **yalnızca** GY m.55/1\'de sayılanlardır (oy hakkı veren payların **en az %5\'i**); **tek acente/distribütör/bayi** olmak tek başına ilişki değildir; ilişkinin varlığı satış bedelinin reddi için **tek başına yeterli değildir**.',
    'Kur: **gümrük yükümlülüğünün başladığı tarihteki TCMB döviz satış** kuru; konvertibl olmayan dövizde **bilgi amaçlı kurlar listesi**. Bilgi taşıyıcılarında **yalnız taşıyıcı ortam** esas alınır; ses/sinema/video kayıtları "veri veya komut" sayılmaz.',
    'Süre ve oranlar: indirgemede **90 gün**; fiyat düzeltmesi **1 yıl**; tamamlayıcı beyan **izleyen ayın 26\'sı akşamı**; navlun/sigorta belgesi yoksa talep üzerine **FOB\'un %10\'u navlun, %3\'ü sigorta**.',
  ],
};
