// 40. Konu — Posta ve Hızlı Kargo Taşımacılığı (kaynak: 40-posta ve hızlı kargo.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '40',
  konu: 'Posta ve Hızlı Kargo Taşımacılığı',
  kaynak: '40-posta ve hızlı kargo.docx (Genelge 2011/39 yolcu hükümleri; Posta ve Hızlı Kargo Yoluyla Taşınan Eşyanın Gümrük İşlemlerine İlişkin Tebliğ (Seri No: 1) m.1–22; Genelge 2022/9 I–VI; GK m.173–175; GY m.455–475)',
  bolumler: [
    { baslik: 'Yolcu Beraberi Eşya ve Yolcu İşlemleri (Genelge 2011/39)', sorular: [
      ['Nakil vasıtaları sürücüleri ve hizmetlileri yolcu sayılır mı?',
        '**Hayır**, yolcu sayılmaz.', 'Genelge (2011/39)', '',
        'Ancak, nakil vasıtaları sürücüleri ve hizmetlileri yolcu sayılmayacaktır.'],
      ['Ek-9 "A) Tüketim Maddeleri" bölümündeki sigara miktarına ek olarak yolcu kaç adet sigara daha alabilir?',
        '**200 adet** sigara daha.', 'Genelge (2011/39) Kişisel Eşya', '2023',
        'Bu bölümdeki sigara miktarına ek olarak yolcuların 200 adet sigara daha alabilmeleri mümkündür.'],
      ['Ek-9 listesindeki "evcil hayvanlar" ibaresi hangi hayvanlarla sınırlıdır?',
        '**Kedi, köpek ve kuş.**', 'Genelge (2011/39) Kişisel Eşya', '2023',
        'evcil hayvanlar ibaresi kedi, köpek ve kuş ile sınırlıdır'],
      ['Yolcu beraberi hediyelik eşya muafiyetinde Ek-9 listesindeki eşya ile liste dışı eşya için sınır nedir?',
        'Liste kapsamı eşya **kıymetine bakılmaksızın listedeki miktar** kadar; liste dışı eşyada toplam kıymet **430 Avro**\'yu aşmamalı.', 'Genelge (2011/39) Hediyelik Eşya', '2023',
        ['listede yer alan eşya için eşyanın kıymetine bakılmaksızın listede belirtilen miktar kadar getirilebilecektir', 'Liste kapsamı dışında kalan eşya için ise, getirilen eşyaya muafiyet uygulanabilmesi için eşyanın toplam kıymetinin 430 Avro\'yu aşmaması gerekmektedir.']],
      ['Tütün ve alkollü ürünlere ilişkin muafiyetten kimler yararlanamaz?',
        '**18 yaşın altındaki** yolcular.', 'Genelge (2011/39) Hediyelik Eşya', '',
        'tütün ve tütün ürünleri ile alkollü ürünlere ilişkin muafiyet hakkından, 18 yaşın altındaki yolcular faydalanamayacaktır'],
      ['Yolcular yurt dışına beraberlerinde ne kadar döviz ve Türk parası çıkarabilir?',
        '**5.000 ABD Doları** veya eşitine kadar efektif ve en çok **5.000 ABD Doları** karşılığı Türk parası. (Türk parası ve dövizi **getirmek serbesttir**.)', 'Genelge (2011/39); 32 sayılı Karar', '',
        ['Yolcuların Türk Parasını ve dövizi beraberlerinde Türkiye\'ye getirmeleri serbesttir.', 'Yolcular, 5.000 ABD Doları veya eşitine kadar efektifi ve en çok 5.000 ABD Doları karşılığı Türk parasını beraberlerinde yurt dışına çıkarabilirler.']],
      ['Giriş ve çıkışın her ikisi kara yoluyla yapılırsa kişisel ve hediyelik eşya muafiyetinden yararlanma şartı nedir?',
        'Yolcunun gittiği ülkede **üç gün** kalması.', 'Genelge (2011/39) İstisnalar/1', '',
        'yolcunun gittiği ülkede üç gün kalması şarttır'],
      ['Yolcu beraberi cep telefonu muafiyeti nasıl uygulanır?',
        'Sadece **yolcu beraberi kişisel eşya** statüsünde; yabancı misyon mensupları hariç her yolcu için **iki takvim yılında bir adet**, kıymetine bakılmaksızın. **Hediyelik eşya** statüsünde getirilemez.', 'Genelge (2011/39) Sınırlamalar/1', '',
        ['sadece yolcu beraberi kişisel eşya statüsünde olması gerekmektedir', 'yabancı misyon mensupları hariç, her bir yolcunun iki takvim yılında bir adet ile sınırlı olmak üzere ve telefonun kıymetine bakılmaksızın', 'yolcu beraberi hediyelik eşya statüsünde veya posta/hızlı kargo taşımacılığı yoluyla muafen veya vergileri ödenerek cep telefonu getirilmesi mümkün bulunmamaktadır']],
      ['Yolcu beraberi hediyelik eşya kapsamında hayvansal ve bitkisel ürünlerde muafiyet sınırları nelerdir?',
        'Kutulu su ürünleri, hayvansal ürünler, konserveler, pastırma-sucuk **5 kg**; taze ve kuru meyve-sebze **3 kg**; diğer bitkisel ürünler **1 kg**. Fazlası **ticari** kabul edilir.', 'Genelge (2011/39) Sınırlamalar/2', '',
        ['pastırma ve sucuk gibi işlenmiş hayvansal ürünlerin beş kilogramına kadar', 'taze ve kuru meyve ve sebzelerin üç kilogramına, diğer bitkisel ürünlerin ise bir kilogramına kadar muafiyet tanınır', 'ticari miktar ve mahiyette olduğu kabul edilip']],
      ['Beyandan ve denetlemeden müstesna olanlardan bazıları kimlerdir?',
        '**Cumhurbaşkanı**, yabancı devlet başkanları ve aileleri, yabancı devletlerin Türkiye\'deki **elçi ve aileleri**, resmi heyetler, Müsteşarlıkça bildirilen kişiler, milletlerarası resmi kuruluşların Türkiye\'de ikamet eden **misyon şefleri** vb.', 'Genelge (2011/39) Yolcu İşlemleri/2', '',
        ['Aşağıda yazılı kimseler beyandan ve denetlemeden müstesna olup', 'a) Cumhurbaşkanı,', 'Yabancı devletlerin Türkiye\'deki elçi ve aileleri', 'Milletlerarası resmi kuruluşların Türkiye\'de ikamet eden misyon şefleri']],
      ['Kararın 58 ve 62. maddelerindeki yolcu işlemi süreleri aşılırsa süre uzatımı nasıl yapılır?',
        'Mücbir sebep/beklenmeyen hal **tevsiki** şartıyla, **bir defayla sınırlı**, **en fazla 3 aya kadar**; yetkili **Gümrük ve Muhafaza Başmüdürlüğü**.', 'Genelge (2011/39) Süre Uzatımı', '',
        ['bir defayla sınırlı olmak üzere', 'Başmüdürlükçe en fazla 3 aya kadar süre uzatımına ilgili Gümrük ve Muhafaza Başmüdürlüğü yetkili kılınmıştır']],
    ] },
    { baslik: 'Posta Gümrük İşlemleri (GK m.173–175)', sorular: [
      ['Posta yoluyla hangi eşya gümrük idaresinin kontrolüne ve muayenesine tabidir; istisnası nedir?',
        'TGB\'ye **gelen**, Türkiye\'den **gönderilen** veya Türkiye\'ye **iade edilen** eşya, **posta çantaları ve koliler**; **içinde eşya bulunmadığı anlaşılan mektuplar** hariç.', 'GK m.173/1', '2021',
        ['Posta yoluyla Türkiye Gümrük Bölgesine gelen, Türkiye\'den gönderilen veya Türkiye\'ye iade edilen eşya, posta çantaları ve koliler gümrük idaresinin kontrolüne', 'İçinde eşya bulunmadığı anlaşılan mektuplar bu hükmün dışındadır.']],
      ['TGB\'ye gelen posta çantaları ve koliler nerede muayene edilir?',
        '**İlk giriş kapısından** itibaren gümrük gözetiminde **posta idarelerine** sevk edilir ve orada muayene edilir.', 'GK m.173/2', '',
        'Türkiye Gümrük Bölgesine gelen bütün posta çantaları ve koliler ilk giriş kapısından itibaren gümrük gözetimi altında posta idarelerine sevk edilir ve buralarda gümrük muayenesine tabi tutulur.'],
      ['Posta gönderilerinin gümrük kontrolünün kapsamı ve yöntemi nasıl belirlenir?',
        '**Ulaştırma Bakanlığı** ve Gümrük Müsteşarlığının bağlı olduğu **Bakanlıkça müştereken** hazırlanacak **yönetmelikle**.', 'GK m.173/4', '',
        'kapsamı ve yöntemi, Ulaştırma Bakanlığı ve Gümrük Müsteşarlığının bağlı olduğu Bakanlıkça müştereken hazırlanacak bir yönetmelikle belirlenir'],
      ['Posta yoluyla gelen veya giden eşya nereye konulur; bekleme süresi neye tabidir?',
        '**Genel antrepo sayılan** yerlere, **posta idaresinin sorumluluğu** ve **gümrük gözetimi** altında; bekleme süresi **uluslararası posta anlaşmalarına** tabidir.', 'GK m.174', '',
        ['genel antrepo sayılan yerlere, posta idaresinin sorumluluğu ve gümrük idaresinin gözetimi altında konulur', 'Eşyanın buralarda bekleme süresi, Türkiye\'nin taraf olduğu uluslararası posta anlaşmaları hükümlerine tabidir.']],
      ['Posta yoluyla gelen ticari mahiyette olmayan eşyada ayrıca beyanname aranır mı?',
        '**Hayır**; ibraz edilen **uluslararası kabul görmüş belgeler beyanname hükmündedir**. Ticari eşya ise GK **m.58–71** uyarınca beyan edilir.', 'GK m.175', '',
        ['ibraz edilen uluslararası kabul görmüş belgeler beyanname hükmünde olup, ayrıca beyanname aranmaz', '58 ilâ 71 inci madde hükümleri uyarınca gümrük idarelerine beyan edilir']],
    ] },
    { baslik: 'Posta Kolileri (GY m.455–463)', sorular: [
      ['Posta kolileri gümrüğe nasıl beyan olunur?',
        'Posta idarelerinde **sıra numarası izleyen**, **ek-72**\'deki örneğe uygun **liste** ile.', 'GY m.455/1', '2021',
        'Posta kolileri gümrük işlemlerinin yapılacağı posta idarelerinde gümrüğe sıra numarası izleyen, ek-72\'deki örneğe uygun liste ile beyan olunur.'],
      ['Koli listelerinde hangi hususlar gösterilir?',
        'Her **yılbaşından** itibaren teselsül eden **sıra numarası**; kolinin **çıkış ülkesi/şehri** ve çıkış numarası; yollama kağıdına göre **sayısı, marka ve numarası**; gösterilmesi gereken **belgelerin sayı ve türleri**; kolinin **geldiği yol**. (Koliyi muayene eden memura ait bilgi listede **yer almaz**.)', 'GY m.455/2', '2021',
        ['Her yılbaşından itibaren teselsül ettirilen sıra numarası,', 'Kolinin çıkış ülkesi veya şehri ve çıkış numarası,', 'Kolinin yollama kağıdına göre sayısı, marka ve numarası,', 'd) Kolinin geldiği yol.']],
      ['Posta idaresi koli listelerini gümrüğe ne zaman ve kaç nüsha verir?',
        '**Vakit geçirmeden**, kolilerin birikmesini beklemeden; **iki nüsha**, imza karşılığında. Her posta için ayrı veya bir günde gelen tüm koliler için **tek liste** olabilir.', 'GY m.456/1', '',
        ['vakit geçirmeden ve kolilerin birikmesini beklemeden düzenler ve iki nüshasını imza karşılığında gümrük idaresine verir', 'bir günde gelen bütün koliler için tek bir liste de düzenlenebilir']],
      ['Ticari nitelikteki koli eşyası için alıcıya nasıl bildirim yapılır?',
        'Gümrükçe **iki nüsha ayrıntılı liste** düzenlenir; posta idaresi buna dayanarak alıcıya **haber kağıdı** ile bildirir. Ticari olmayan eşyada **tebligat yapılmaksızın** muayene ve tahakkuk yapılır.', 'GY m.458', '',
        ['Gümrüklerce ticari nitelikteki eşya için iki nüsha ayrıntılı liste düzenlenir.', 'bir haber kağıdı ile bildirir', 'koli alıcısına tebligat yapılmaksızın, muayene ve tahakkuk işlemleri yapılır']],
      ['Posta yoluyla gelen eşyada beyan nasıl yapılır?',
        'Ticari olmayan hediyelik, numunelik, zat ve aile ihtiyacı eşyada **Déclaration en Douane** beyanname kabul edilir; Déclaration en Douane yoksa **sözlü beyan formu**; ticari eşyada **gümrük beyannamesi**. Gazete, kitap, broşür, periyodik dergilerin işlemleri **Müsteşarlıkça** belirlenir.', 'GY m.459', '',
        ['Déclaration en Douane\'lar gümrük idaresince beyanname olarak kabul edilir', 'Déclaration en Douane olmadan gelen ve ticari nitelik arz etmeyen eşya içeren koliler için sözlü beyan formu düzenlenir.', 'Ticari nitelik arz eden eşya için gümrük beyannamesi düzenlenir.', 'gazete, kitap, broşür ile periyodik dergiler için yapılacak gümrük işlemleri Müsteşarlıkça belirlenir']],
      ['Posta kolileri kimin huzurunda muayene edilir; ticari olmayan eşyanın muayenesi nasıl yapılır?',
        'Kolileri muhafaza eden **posta idaresi memurlarının huzurunda**; ticari olmayan eşyada **örnekleme yöntemi** ile (ticari eşyada GY m.180–196).', 'GY m.460/1–2', '',
        ['muhafaza ile görevli posta idaresi memurlarının huzurunda muayene eder', 'örnekleme yöntemi ile yapılır']],
      ['İşlemleri biten koli için hangi belgeler düzenlenir?',
        'Vergiler veznede tahsil edilerek **Vezne Alındısı** verilir; ayrıca **ek-73**\'teki **Teslim Kağıdı** düzenlenir.', 'GY m.461/1–2', '',
        ['karşılığında Vezne Alındısı verilir', 'kolinin gümrükle ilişiği kalmadığına dair ek-73\'te yer alan bir Teslim Kağıdı da düzenlenir']],
      ['Gümrük veznesi bulunmayan posta idarelerinde vergiler nasıl tahsil edilir ve gümrüğe ne zaman ödenir?',
        '**Posta idaresi** tahsil eder; paralar **en geç bir hafta içinde**, tahakkuk belgelerine dayanan liste ile gümrük veznesine ödenir.', 'GY m.462', '',
        ['kolilere ait tahakkuk ettirilmiş vergiler posta idaresi tarafından tahsil edilir', 'Posta idaresi gümrük adına tahsil ettiği paraları en geç bir hafta içinde']],
    ] },
    { baslik: 'Posta Haberleşme Gönderileri ve Ortak Hükümler (GY m.466–474)', sorular: [
      ['Yeşil etiketli mektuplar ve küçük paketleri kapsayan çantalar kimce açılır?',
        '**Gümrük gözetiminde posta idaresince**; vergiye tabi olanlar ayrılır ve posta idaresince düzenlenen **liste** ile gümrüğe bildirilir.', 'GY m.466', '',
        ['gümrük gözetiminde posta idaresince açılır ve vergiye tabi olanlar ile olmayanlar ayrılır', 'Vergiye tabi olan posta haberleşme gönderileri, posta idaresince düzenlenen liste ile gümrük idaresine bildirilir.']],
      ['Mektup postası dışındaki eşya başka bir gümrük idaresine nasıl sevk edilir?',
        '**Transit rejimi** hükümleri çerçevesinde; **her araç için ayrı** transit beyannamesi; posta çuvalları mühürlü ise **taşıt ayrıca mühürlenmez**.', 'GY m.468/1', '2021',
        ['Mektup postası dışında kalan eşyanın başka bir gümrük idaresine sevk edilmek istenilmesi halinde, eşya transit rejimi hükümleri çerçevesinde sevk edilir.', 'her araç için ayrı bir transit beyannamesi düzenlenir', 'Posta çuvalları mühürlü ise ayrıca taşıt aracı mühürlenmez.']],
      ['Aynı il içindeki havalimanından Posta İşleme Merkezine sevk hangi belgeyle yapılabilir?',
        '**Posta Teslim Bordrosu (CN-38 veya CN-41)** ile, posta idaresinin sorumluluğunda.', 'GY m.468/2', '',
        'Posta Teslim Bordrosu (CN-38 veya CN-41) ile posta idaresinin sorumluluğu altında sevk edilmesi mümkündür'],
      ['Posta yoluyla yurt dışına gönderilecek ticari eşya genel antrepoda ne kadar bekletilebilir?',
        'Antrepo beyannamesinin tescilinden itibaren **bir ay**; süre geçince **GY m.417**\'ye göre işlem yapılır.', 'GY m.469/2', '',
        ['Eşya, buralarda antrepo beyannamesinin tescil tarihinden itibaren bir ay bekletilebilir.', 'Bu sürenin geçmesi üzerine 417 nci maddeye göre işlem yapılır.']],
      ['Posta gümrüğündeki ölçü aletleri, büro, telefon, aydınlatma ve ısıtma ihtiyaçlarını kim karşılar?',
        '**Posta idaresi**, **bedelsiz** olarak.', 'GY m.469/3', '',
        'posta idaresi herhangi bir bedel karşılığında olmaksızın sağlamakla yükümlüdür'],
      ['Posta yoluyla gelen eşyada beyan ile tespit arasındaki farklılıklarda ceza nasıl uygulanır?',
        'Ticari olmayan eşyada Déclaration en Douane\'a göre farklılıklarda **ceza aranmaz**; ticari eşyada **GK m.234**\'e göre işlem yapılır.', 'GY m.474', '',
        ['ticari nitelikte olmayan eşyaya ilişkin Déclaration en Douane\'larda kayıtlı bilgilere nazaran tespit edilen farklılıklardan dolayı ceza aranmaz', 'Kanunun 234 üncü maddesi hükümlerine göre işlem yapılır']],
    ] },
    { baslik: 'Tebliğ: Tanımlar ve Operatör Yetkisi (Tebliğ Seri No: 1 m.1–7)', sorular: [
      ['Posta ve Hızlı Kargo Tebliği ile hızlı kargo şirketlerine ve posta idaresine hangi yetki tanınır?',
        'GK **m.225/1** uyarınca, Kararın **126.** maddesindeki eşyanın gümrük beyanı dahil tüm işlemlerini **dolaylı temsil** yoluyla takip etme yetkisi.', 'Tebliğ (Posta-Kargo Seri No: 1) m.1', '',
        ['4458 sayılı Gümrük Kanununun 225 inci maddesinin birinci fıkrası uyarınca dolaylı temsil yetkisi tanınması', 'Kararın 126 ncı maddesinde belirtilen eşyanın gümrük beyanı dahil tüm gümrük işlemlerinin bu kişiler tarafından dolaylı temsil yoluyla takip edilip sonuçlandırılmasına']],
      ['Tebliğde "doküman" ve "gönderi" nasıl tanımlanır?',
        'Doküman: kişisel yazılı mesaj, kartpostal ve **ticari değer taşımayan basılı materyal**; gönderi: içinde ticari veya gayri ticari **eşya bulunan** paket, koli, poşet vb.', 'Tebliğ (Posta-Kargo Seri No: 1) m.3/1-ç, d', '',
        ['kişisel yazılı mesaj, kartpostal ile herhangi bir ticari değer taşımayan basılı materyal şeklindeki gönderileri', 'içerisinde ticari veya gayri ticari nitelikte eşya bulunan paket, koli, poşet ve benzerini']],
      ['Operatör kimdir; posta idaresi hangi kuruluştur?',
        'Operatör: hızlı kargo gönderilerinin işlemlerini **dolaylı temsil** yoluyla yapmaya yetkili **tüzel kişi**; posta idaresi: **Posta ve Telgraf Teşkilatı AŞ**.', 'Tebliğ (Posta-Kargo Seri No: 1) m.3/1-h, ı', '',
        ['gümrük beyanı dahil tüm gümrük işlemlerini dolaylı temsil yoluyla yapmaya yetkili tüzel kişileri', 'Posta idaresi: Posta ve Telgraf Teşkilatı Anonim Şirketini']],
      ['Hava yolu ve kara yolu hızlı kargo operatörü olmak için hangi yetkilendirme gerekir?',
        'Hava yolu: **Sivil Havacılık Genel Müdürlüğünce** "**hava kargo acentesi**" yetkisi; kara yolu: Ulaştırma ve Altyapı Bakanlığınca **uluslararası kara yolu taşımacılık belgesi**.', 'Tebliğ (Posta-Kargo Seri No: 1) m.4/1-a, b', '',
        ['Sivil Havacılık Genel Müdürlüğünce "hava kargo acentesi" olarak yetkilendirilmiş olması', 'uluslararası kara yolu taşımacılık belgesi ile yetkilendirilmiş olması']],
      ['Operatörün gümrük müşaviri istihdamına ilişkin koşul nedir?',
        'Bünyesinde **asgari iki gümrük müşaviri** istihdam etmek ya da asgari iki GM ile veya iki GM görevlendirecek bir **müşavirlik şirketiyle sözleşme** yapmak. Sayıyı düzenlemeye **Bakanlık** yetkilidir.', 'Tebliğ (Posta-Kargo Seri No: 1) m.4/1-c, 4/4', '',
        ['şirket bünyesinde asgari iki gümrük müşaviri istihdam ediyor olması veya asgari iki gümrük müşaviri ile sözleşme yapmış olması', 'gümrük müşaviri sayısına ilişkin düzenleme yapmaya Bakanlık yetkilidir']],
      ['Operatörden istenen teminat mektubu tutarı nedir?',
        'Yalnızca hava yolu veya yalnızca kara yolu için **10.000.000 TL**; her iki yetki birlikte **20.000.000 TL**.', 'Tebliğ (Posta-Kargo Seri No: 1) m.4/1-f', '',
        ['yalnızca hava yolu veya yalnızca kara yolu ile hızlı kargo taşımacılığında yetki kullanılmak istenmesi durumunda 10.000.000', 'her iki yetkinin birlikte kullanılmak istenmesi durumunda ise 20.000.000']],
      ['Posta idaresi için hangi başvuru koşulları ve belgeler aranır?',
        'Yalnızca **(c) gümrük müşaviri** ve **(e) teknik altyapı** koşulları; diğer koşullar aranmaz. Belgelerden yalnızca **Ek-1 başvuru formu** istenir.', 'Tebliğ (Posta-Kargo Seri No: 1) m.4/2, 5/3', '',
        ['Posta idaresi için birinci fıkranın (c) ve (e) bentleri', 'dışındaki koşullar aranmaz', 'Posta idaresi için birinci fıkrada belirtilen belgeler aranmaz; Ek-1\'de yer alan başvuru formu ile başvuruda bulunulur.']],
      ['Operatör başvurusu nereye yapılır ve hangi sürelerde sonuçlanır?',
        'İşlemlerin yapılacağı gümrük müdürlüğünün bağlı olduğu **Gümrük ve Dış Ticaret Bölge Müdürlüğüne**; heyet yerinde tespit eder, başvurudan itibaren **15 gün** içinde Bakanlığa gönderilir; **Bakanlık 15 gün** içinde karara bağlar.', 'Tebliğ (Posta-Kargo Seri No: 1) m.6', '',
        ['yetki kapsamı işlemlerin yapılacağı gümrük müdürlüğünün bağlı olduğu Gümrük ve Dış Ticaret Bölge Müdürlüğüne yapılır', 'başvuru tarihinden itibaren on beş gün içinde Bakanlığa gönderilir', 'Talep, Bakanlıkça on beş gün içinde karara bağlanır.']],
      ['Operatör bünyesinde istihdam edilen gümrük müşavirine hangi kısıtlamalar vardır?',
        'Tebliğ hükümleri **dışında** müşavirlik faaliyetinde **bulunamaz**; bir GM aynı anda **yalnızca bir** hızlı kargo firması ile sözleşme yapabilir.', 'Tebliğ (Posta-Kargo Seri No: 1) m.7/2', '',
        ['firma bünyesinde istihdam edilenler bu Tebliğ hükümleri dışında gümrük müşavirliği faaliyetinde bulunamazlar', 'Bir gümrük müşaviri, bu Tebliğ hükümleri kapsamında işlem yapmak üzere aynı anda yalnızca bir hızlı kargo firması ile sözleşme yapabilir.']],
      ['Operatörler yetkiyi kullanırken vekâletname ibraz eder mi?',
        '**Hayır**, aranmaz; alıcı/göndericinin teslim-tesellüm belgelerini **imzalaması**, yetkinin kendi hesabına kullanıldığının kabulü anlamına gelir.', 'Tebliğ (Posta-Kargo Seri No: 1) m.7/3', '',
        ['Operatörlerce yetki kullanılırken vekâletname ibrazı aranmaz.', 'bu yetkinin kendileri hesabına kullanıldığının kabul edildiği anlamına gelir']],
    ] },
    { baslik: 'Tebliğ: Tasnif, Beyan ve Kontrol (Tebliğ Seri No: 1 m.9–11)', sorular: [
      ['Yurt dışından gelen gönderiler hangi kategorilere ayrılır?',
        'Barkod ve X-ray kontrolünden sonra **dört** kategori: belge kontrolüne tabi **doküman**; 126/1-a kapsamında **belge kontrolüne** tabi; 126/1-a kapsamında **gümrükçe muayeneye** tabi; 126/1-a **kapsamı dışında** kalan gönderiler.', 'Tebliğ (Posta-Kargo Seri No: 1) m.9/1', '',
        ['otomatik barkod okuyucu ve X-ray kontrolünden geçirildikten sonra otomatik olarak aşağıdaki dört kategoriye ayrılır', 'Belge kontrolüne tabi doküman.', 'Kararın 126 ncı maddesinin birinci fıkrasının (a) bendi kapsamı dışında kalan gönderiler.']],
      ['Operatör basitleştirilmiş gümrük beyannamesi verirse ayrıca özet beyan zorunlu mudur?',
        'Özet beyandan **vazgeçilebilir**; BGB özet beyan asgari bilgilerini içerir ve **tescil edilinceye kadar özet beyan statüsündedir**.', 'Tebliğ (Posta-Kargo Seri No: 1) m.10/1', '',
        ['özet beyan verilmesinden vazgeçilebilir', 'aynı Kanunun 61 inci maddesi uyarınca tescil edilinceye kadar özet beyan statüsündedir']],
      ['Teşvik, sübvansiyon, parasal iade veya ayniyet tespitine konu olmayan ihracat gönderilerinin beyanı ne zamana kadar yapılır; düzeltme süresi nedir?',
        'Taşıma aracı **hareket gümrük idaresini terk edinceye kadar**; terkten sonraki **yirmi dört saat** içinde düzeltme yapılabilir.', 'Tebliğ (Posta-Kargo Seri No: 1) m.10/6', '',
        ['taşıma aracı hareket gümrük idaresini terk edinceye kadar yapılır', 'Taşıma aracı hareket gümrük idaresini terk ettikten sonraki yirmi dört saat içinde beyanda düzeltme yapılabilir.']],
      ['Operatör hangi ihracat eşyasını basitleştirilmiş usulde beyan eder?',
        'Miktarı **brüt 600 kg** ve değeri **30.000 Avro**\'yu geçmeyen eşya.', 'Tebliğ (Posta-Kargo Seri No: 1) m.10/7; Genelge (2022/9) I/3.1', '',
        ['Kararın 126 ncı maddesi kapsamında miktarı brüt 600 kilogramı', 've değeri 30.000 Avro\'yu']],
      ['Hızlı kargo eşyasının gümrük işlemleri hangi gümrük müdürlüklerinde yapılır?',
        'Hava yolu: **havalimanı gümrük müdürlükleri**; kara yolu: **Bakanlıkça (Gümrükler Genel Müdürlüğü)** belirlenen müdürlükler.', 'Tebliğ (Posta-Kargo Seri No: 1) m.10/8', '',
        ['hava yolu ile hızlı kargo taşımacılığına konu eşyanın gümrük işlemleri havalimanı gümrük müdürlüklerinden gerçekleştirilir', 'Kara yolu ile hızlı kargo taşımacılığına konu eşyanın gümrük işlemlerini gerçekleştirmeye yetkili gümrük müdürlükleri Bakanlıkça (Gümrükler Genel Müdürlüğü) belirlenir.']],
      ['Kara yolu hızlı kargo eşyasında hangi rejim uygulanır; asıl sorumlu kimdir?',
        '**Transit rejimi**; asıl sorumlu **operatör**dür (getirilen eşyada ulusal transit, gönderilen eşyada hem ulusal hem ortak transit). TIR Sözleşmesi saklıdır.', 'Tebliğ (Posta-Kargo Seri No: 1) m.10/9', '',
        ['Kara yolu ile hızlı kargo taşımacılığı kapsamında taşınan eşya için transit rejimi çerçevesinde işlem yapılır.', 'yurda getirilen eşyada ulusal transit rejiminde, gönderilen eşyada ise hem ulusal hem ortak transit rejiminde asıl sorumlu operatördür']],
      ['126/1-a-(1) ve (3) kapsamında aynı kişi adına bir takvim ayında en fazla kaç taşıma senedi serbest dolaşıma girebilir; aşılırsa ne olur?',
        '**Beş** taşıma senedi (aynı/farklı cins fark etmez); aşan kısım **sonraki aya devredilemez**, **126/1-(b)** kapsamında işlem yapılır.', 'Tebliğ (Posta-Kargo Seri No: 1) m.10/10', '',
        ['aynı kişi adına bir takvim ayında en fazla beş taşıma senedi muhteviyatı eşyanın', 'aşan miktarın bir sonraki aya devredilerek basitleştirilmiş gümrük beyannamesine konu edilmesine izin verilmez ve Kararın 126 ncı maddesinin birinci fıkrasının (b) bendi kapsamında işlem tesis edilir']],
      ['Teslim tarihi ve alıcının T.C./vergi kimlik no veya cep telefonu bilgisi gümrüğe ne zaman iletilir?',
        'Eşyanın alıcıya **teslimini takip eden üç iş günü** içinde, **elektronik ortamda**.', 'Tebliğ (Posta-Kargo Seri No: 1) m.10/12', '',
        'eşyanın alıcısına teslimini takip eden üç iş günü içerisinde gümrük müdürlüğüne elektronik ortamda iletilir'],
      ['Özet beyandan BGB\'ye eklenecek taşıma senedi sayısının sınırı nedir?',
        'Her operatör için, talepten **bir önceki günün** ithalat BGB kapsamı toplam taşıma senedi sayısının **%20**\'si.', 'Tebliğ (Posta-Kargo Seri No: 1) m.10/16', '',
        'ekleme talebinin yapıldığı günden bir önceki ithalat basitleştirilmiş gümrük beyannamesi kapsamı toplam taşıma senedi sayısının % 20\'sini geçemez'],
      ['Tebliğ kapsamında konsinye gönderilen eşyanın kesin satışı ne zamana kadar yapılmalıdır?',
        'İhraç tarihinden itibaren **bir yıl** içinde; süre **uzatılmaz**. Satılamazsa eşyanın **geri getirilmesi** gerekir.', 'Tebliğ (Posta-Kargo Seri No: 1) m.10/18–19', '',
        ['ihraç tarihinden itibaren bir yıl içinde kesin satışının yapılması gerekir ve bu süre uzatılmaz', 'eşyanın gümrük mevzuatı çerçevesinde geri getirilmesi gerekir']],
      ['Eşyanın cins, tanım ve değerinin doğru beyanı kimin sorumluluğundadır; aykırılıkta ne olur?',
        '**Operatörün**; aksi halde **5607 sayılı Kaçakçılıkla Mücadele Kanunu** ve ilgili mevzuata göre cezai işlem. (Gönderiler **risk analizine** dayalı kontrol edilir.)', 'Tebliğ (Posta-Kargo Seri No: 1) m.11', '',
        ['Eşyanın cins ve tanımı ile değerinin doğru ve eksiksiz olarak beyan edilmesi operatörün sorumluluğundadır.', '5607 sayılı Kaçakçılıkla Mücadele Kanunu ve ilgili diğer mevzuat hükümleri çerçevesinde cezai işlem tesis edilir', 'Yetki kapsamındaki gönderiler, risk analizine dayalı kontrol ve muayeneye tabi tutulur.']],
    ] },
    { baslik: 'Kıymet, Vergiler ve Müeyyide (Tebliğ Seri No: 1 m.12–21; Genelge 2022/9 II, V)', sorular: [
      ['Posta veya hızlı kargo ile gelen eşyanın kıymeti nasıl belirlenir?',
        'İbraz edilen **fatura, satış fişi** veya **bedelin ödendiğine ilişkin belgeye** göre; belge ibraz edilemez ya da kıymet düşük bulunursa **gümrük idaresince** belirlenir.', 'Tebliğ (Posta-Kargo Seri No: 1) m.12/1; Genelge (2022/9) II', '2025',
        ['Eşyanın kıymeti, ibraz edilen faturaya, satış fişine veya eşya bedelinin ödendiğine ilişkin belgeye göre belirlenir.', 'Bu tür belge ibraz edilememesi veya ibraz edilen belgede kayıtlı kıymetin düşük bulunması halinde, eşyanın kıymeti gümrük idaresince belirlenir.']],
      ['Türkiye\'deki giriş liman veya yerine kadar yapılan nakliye giderleri posta/hızlı kargo eşyasının kıymetine eklenir mi?',
        '**Evet**, eşyanın kıymetine **ilave edilir**.', 'Tebliğ (Posta-Kargo Seri No: 1) m.12/1; Genelge (2022/9) II', '2025',
        'Türkiye\'deki giriş liman veya yerine kadar yapılan nakliye giderleri, eşyanın kıymetine ilave edilir'],
      ['Navlun gideri fatura veya belgelerde ayrı gösterilmemişse ne yapılır?',
        '**3 avro** tutarında **emsal navlun gideri** fiilen ödenen/ödenecek fiyata eklenir (navlun dahil olmayan teslimde makbuz ibrazı imkânsızsa da aynı).', 'Genelge (2022/9) II', '',
        ['Navlun giderinin bu belgelerde ayrı gösterilmediği durumlarda, 3 (üç) avro tutarında emsal navlun gideri fiilen ödenen veya ödenecek fiyata eklenir.', 'navlun makbuzu ibrazının imkansız olduğu veya kabul edilebilir nitelikte bulunmadığı hallerde']],
      ['Operatörce tahsil edilen gümrük vergileri ne zaman ödenir?',
        'Eşyanın **operatöre teslimini** takip eden **yedi gün** içinde; posta idaresinde süre eşyanın **alıcısına tesliminden** başlar.', 'Tebliğ (Posta-Kargo Seri No: 1) m.12/2', '',
        ['eşyanın operatöre teslimini takip eden yedi gün içerisinde ödenir', 'Posta idaresi için söz konusu süre, Gümrük Yönetmeliğinin 462 nci maddesinin üçüncü fıkrası gereğince, eşyanın alıcısına tesliminden itibaren başlar.']],
      ['BGB ile ihraç edilip geri gelen eşya muafen serbest dolaşıma nasıl girer?',
        '600 kg / 30.000 Avro sınırları dâhilinde; yararlanılan **hak ve menfaatlerin iade edildiğini** gösteren belge ibraz edilir; KDV/ÖTV iadesi veya istisnasından yararlanılmışsa **KDV ve ÖTV tahsil edilir**.', 'Tebliğ (Posta-Kargo Seri No: 1) m.13/1–2', '',
        ['10 uncu maddenin yedinci fıkrasında bahsi geçen ağırlık ve kıymet sınırlamaları dâhilinde işlem yapılır', 'ihracat nedeniyle yararlanılan hak ve menfaat varsa bunların iade edildiğini gösteren belgenin gümrük müdürlüğüne ibrazı gerekir', 'katma değer vergisi ve özel tüketim vergisi tahsil edilir']],
      ['Operatörler gönderilere ilişkin ticari belgeleri ne kadar süre saklar?',
        'Elektronik veya kağıt ortamında **beş yıl**.', 'Tebliğ (Posta-Kargo Seri No: 1) m.15', '',
        'operatörlerce elektronik ortamda veya kağıt ortamında beş yıl süreyle saklanır'],
      ['Operatör başvuru koşullarından birini kaybederse ne olur?',
        'Koşul **yeniden sağlanıncaya kadar** yetkiden **faydalanmasına izin verilmez**.', 'Tebliğ (Posta-Kargo Seri No: 1) m.17/1', '',
        'bu koşul veya koşullar yeniden sağlanıncaya kadar operatörün bu Tebliğ kapsamındaki yetkiden faydalanmasına izin verilmez'],
      ['Tebliğe aykırı hareket eden operatöre hangi müeyyide uygulanır; nasıl değerlendirilir?',
        'Daha ağır yaptırım gerekmiyorsa **GK m.241/1**; **her bir taşıma senedi bazında ayrı**. Ancak (a) ve (c) beyanlarında birden fazla senette **aynı mahiyette** veri alanı düzeltmesinde **yalnızca BGB için** uygulanır. (Kararın onuncu kısmına aykırılıkta Karar **m.128**.)', 'Tebliğ (Posta-Kargo Seri No: 1) m.17/2–5; Genelge (2022/9) V/2', '',
        ['Kanunun 241 inci maddesinin birinci fıkrası uyarınca işlem yapılır', 'basitleştirilmiş gümrük beyanı kapsamı her bir taşıma senedi bazında ayrı değerlendirilir', 'Kanunun 241 inci maddesinin birinci fıkrası yalnızca basitleştirilmiş gümrük beyannamesi için uygulanır', 'Kararın onuncu kısmına aykırı hareket ettiği tespit edilen operatörler hakkında Kararın 128 inci maddesi uyarınca işlem yapılır.']],
      ['Tebliğ kapsamında yapılan ihracatta ihracatçı birliği onayı aranır mı?',
        '**Hayır**, aranmaz.', 'Tebliğ (Posta-Kargo Seri No: 1) m.18/2', '',
        'Bu Tebliğ hükümleri kapsamında yapılan ihracatta ihracatçı birliği onayı aranmaz.'],
      ['Posta/hızlı kargo eşyasında fikri ve sınai mülkiyet hakkı ihlali tespit edilirse ne yapılır?',
        'İşlemler **durdurulur**, **GK m.57** uyarınca işlem başlatılır.', 'Genelge (2022/9) V/1', '',
        'eşyaya ilişkin gümrük işlemleri durdurularak Gümrük Kanununun 57 nci maddesi uyarınca işlem başlatılması gerekmektedir'],
    ] },
    { baslik: 'Beyan Türleri (Genelge 2022/9 I)', sorular: [
      ['Kararın 126. maddesi kapsamı eşyanın beyanı kaç şekilde yapılır?',
        '**İki** şekilde: **basitleştirilmiş gümrük beyannamesi** ve **normal usulde detaylı beyan**.', 'Genelge (2022/9) I', '',
        'Kararın 126 ncı maddesi kapsamı eşyanın beyanı, basitleştirilmiş gümrük beyannamesi ve normal usulde detaylı beyan olmak üzere iki şekilde yapılır.'],
      ['İthalatta hangi eşya basitleştirilmiş gümrük beyannamesi ile beyan edilir?',
        '1500 Avro\'yu geçmeyen kişisel **kitap/basılı yayın**; yolcunun gelişinden **1 ay önce veya 3 ay sonra** gelen kişisel eşya (Ek-9 B); 1500 Avro\'yu geçmeyen **ilaç ve takviye edici gıda**; istisna belgeli kurumların eğitim-bilim-kültür eşyası; **numunelik eşya ve modeller**; inceleme-analiz-test eşyası; kamu kurumlarına kitap; **diplomatik eşya**.', 'Genelge (2022/9) I/1.1', '',
        ['Kıymeti 1500 Avro\'yu geçmeyen kişisel kullanıma mahsus kitap veya benzeri basılı yayın.', 'yolcunun gelişinden 1 ay önce veya 3 ay sonraki süreler içerisinde', 'Kararın 62 nci maddesi kapsamı kıymeti 1500 Avro\'yu geçmeyen ilaç cinsi eşya ile takviye edici gıdalar', 'Elçilik, konsolosluk veya milletlerarası kuruluşlar adına gelen diplomatik eşya.']],
      ['BGB ile beyan edilen (126/1-a) eşyaya diğer mevzuattan kaynaklanan kısıtlamalar uygulanır mı; detaylı beyanda durum nedir?',
        'BGB eşyasında Karar **m.112** uyarınca sınırlayıcı ve kısıtlayıcı hükümler **uygulanmaz**. Detaylı beyanda ise m.112 **uygulanmaz**; genel hükümlere göre vergiler ödenerek işlem yapılır.', 'Genelge (2022/9) I/1.2, 2.5; Tebliğ (Posta-Kargo Seri No: 1) m.18/1', '',
        ['Kararın 112 nci maddesi uyarınca diğer mevzuattan kaynaklanan sınırlayıcı ve kısıtlayıcı hükümler uygulanmaz', 'Eşyanın serbest dolaşıma giriş beyanında Kararın 112 nci maddesi uygulanmaz; gümrük ve dış ticaret mevzuatının genel hükümleri uyarınca vergileri ödenerek']],
      ['Bir basitleştirilmiş gümrük beyannamesine en fazla kaç taşıma senedi eklenebilir?',
        'İthalatta **500**, ihracatta **2.500** adet.', 'Genelge (2022/9) I/1.3, 3.2', '',
        ['ithalat işlemleri için maksimum 500 (beş yüz) adet', 'ihracat işlemleri için maksimum 2.500 (iki bin beş yüz) adet ile sınırlıdır']],
      ['Operatörler BGB eşyası için hangi ücretleri alamaz?',
        'Müşavirlik, ordino, terminal vb. adlarla **ilave ücret** ve bildirimin alıcıya yapıldığı tarihten itibaren **ilk üç gün** için **ardiye ücreti**.', 'Genelge (2022/9) I/1.4', '',
        ['gümrük müşavirliği, ordino, terminal ve benzeri isimler altında ilave ücret ile', 'ilk üç gün için ardiye ücreti alamaz']],
      ['Normal usulde detaylı beyan (126/1-b) hangi eşya için yapılır; BİLGE\'de hangi kod seçilir?',
        'Bir **gerçek kişiye** gelen, değeri **1500 Avro**\'yu aşmayan, **ticari miktar ve mahiyet arz etmeyen** eşya; **"BS20"** kodu. Operatörden **YKTS kaydı aranmaz**.', 'Genelge (2022/9) I/2.1–2.4; Tebliğ (Posta-Kargo Seri No: 1) m.10/13', '',
        ['bir gerçek kişiye gelen, değeri', '1500 Avro\'yu aşmayan, ticari miktar ve mahiyet arz etmeyen eşyanın serbest dolaşıma giriş beyanı normal usulde detaylı beyan ile yapılır', 'Detaylı Beyan modülünden "BS20" kodu seçilir', 'Operatörden, Yükümlü Takip ve Kayıt Sistemine (YKTS) kayıt olma koşulu aranmaz.']],
      ['Konsinye ihracat BGB\'sinde hangi kodlar kullanılır?',
        '**KNSY** muafiyet kodu ve **1000** rejim kodu; asgari altılı tarife alt pozisyonu; başka muafiyet kodu beyan edilemez; **proforma fatura** eklenir.', 'Genelge (2022/9) I/3.4', '',
        ['Konsinye ihracat için düzenlenen basitleştirilmiş gümrük beyannamesinde KNSY muafiyet kodu seçilir.', 'a) 1000 rejim kodu kullanılır.', 'ç) Proforma fatura eklenir.']],
    ] },
    { baslik: 'Yasaklama ve Kısıtlamaya Tabi Eşya (Genelge 2022/9 IV)', sorular: [
      ['Posta/hızlı kargo ile gelen nakit para ve çek nasıl işlem görür?',
        '**BGB\'ye konu edilemez**, teslim edilmeyip **rezerve odasında** muhafaza edilir; nakitte alıcıdan açıklama alınıp **Nakit Açıklama Tutanağı** düzenlenir, sonra **sözlü beyanla** teslim edilir; çek de **sözlü beyanla** teslim edilir.', 'Genelge (2022/9) IV/1', '',
        ['basitleştirilmiş gümrük beyannamesine konu edilemez ve alıcısına teslim edilmeyerek rezerve odasında muhafaza altına alınır', '"Nakit Açıklama Tutanağı" elektronik ortamda düzenlenir', 'Posta veya hızlı kargo taşımacılığı yoluyla yurda getirilen çek sözlü beyan düzenlenerek alıcısına teslim edilir.']],
      ['Şahsi tedavi amaçlı ilaç posta/hızlı kargo ile hangi şartla getirilebilir?',
        '**Rapor, doktor raporu veya reçete** ibrazıyla; memur kesin kanaat getirirse **belge aranmaksızın**; hasta yakını adına gelirse **her iki şahsın yazılı beyanı** ile.', 'Genelge (2022/9) IV/2', '',
        ['gümrük idaresine belge (sağlık kuruluşundan alınan rapor, doktor raporu veya reçete) ibraz edilmesi koşuluna bağlı olarak, girişine izin verilir', 'belge aranmaksızın eşyanın girişine izin verilebilir', 'her iki şahıstan da alınacak yazılı beyana istinaden yurda girişine izin verilir']],
      ['Takviye edici gıda ve sporcu gıdalarında rapor/reçetenin geçerlilik süresi nedir?',
        'Eşyanın teslim tarihi itibarıyla **son bir yıl** içinde düzenlenmiş olması yeterli; **her gönderi için yeni** rapor/reçete aranmaz. (Karar m.62 kapsamında ithali **mümkündür**.)', 'Genelge (2022/9) IV/3', '',
        ['son bir yıl içerisinde düzenlenmiş olması yeterli olup, her gönderi için yeni bir rapor ve reçete aranmasına gerek bulunmamaktadır', 'Kararın 62 nci maddesi kapsamında ithali mümkün bulunmaktadır']],
      ['Kozmetik ürünleri ile alkol, tütün ve elektronik sigara posta/hızlı kargo ile muafen ithal edilebilir mi?',
        '**Hayır.** Kozmetik Karar **m.62/1**, alkol-tütün-e-sigara (aksam ve solüsyon dahil) Karar **m.62 ve 86** kapsamında ithal edilemez.', 'Genelge (2022/9) IV/4, 11', '',
        ['kozmetik ürünlerinin Kararın 62 nci maddesinin birinci fıkrası kapsamında ithali mümkün bulunmamaktadır', 'Kararın 62 nci ve 86 ncı maddeleri kapsamında posta veya hızlı kargo taşımacılığı yoluyla ithali mümkün bulunmamaktadır']],
      ['Ayakkabı, oyuncak ve saraciye ürünleri 126/1-a-(3) kapsamında beyan edilebilir mi?',
        '**Hayır**; ancak Genelgenin yayımından önce yüklenmiş veya TGB\'ye girmiş eşyaya bu hüküm uygulanmaz.', 'Genelge (2022/9) IV/5', '',
        ['Ayakkabılar, oyuncaklar ile saraciye ürünlerinin (gerçek ve suni deriden yapılmış çantalar ve bavullar) Kararın 126 ncı maddesinin birinci fıkrasının (a) bendinin (3) numaralı alt bendi kapsamında beyanı mümkün bulunmamaktadır.', 'Genelgenin yayımlandığı tarihten önce yüklemesi yapılmış olan veya Türkiye Gümrük Bölgesine giren eşyaya bu hüküm uygulanmaz']],
      ['Cep telefonu posta/hızlı kargo ile getirilebilir mi; istisnası nedir?',
        'Muafen veya vergi ödenerek **hiçbir surette** getirilemez. İstisna: IMEI\'si Türkiye\'de kayıtlı, yurt dışında kalan telefonun **3 aylık** süre içinde geri gönderilmesi → muafen teslim, **"YLC0"** muafiyet kodu.', 'Genelge (2022/9) IV/12', '',
        ['Cep telefonunun posta veya hızlı kargo taşımacılığı yoluyla muafen veya vergileri ödenerek hiçbir surette getirilmesi mümkün bulunmamaktadır.', 'Kararın 58 inci maddesinin ikinci fıkrasında belirtilen 3 aylık süre içerisinde', '"YLC0" muafiyet kodu kullanılarak beyan yapılır']],
      ['Silah dışındaki patlayıcı, bıçak vb. (2020/11 sayılı Tebliğ kapsamı) eşya posta/hızlı kargo ile nasıl getirilir?',
        'Kıymet, miktar veya ağırlık istisnası olmaksızın **Emniyet Genel Müdürlüğünden** uygunluk yazısı ile. (Kayıt ve ruhsatı olmayan **silah ve tüfekler yasaktır**.)', 'Genelge (2022/9) IV/13', '',
        ['söz konusu eşyanın posta veya hızlı kargo taşımacılığı yoluyla da getirilmesi yasaktır', 'Emniyet Genel Müdürlüğünden alınacak genel güvenlik ve asayiş yönünden uygunluk yazısının ibrazı gerekmektedir']],
      ['430 Avro\'luk yolcu beraberi hediyelik eşya muafiyeti posta/hızlı kargo eşyasına uygulanır mı?',
        '**Hayır**, uygulanmaz.', 'Genelge (2022/9) IV/15', '',
        'Kararın 61 inci maddesinde düzenlenen 430 Avro tutarındaki yolcu beraberi hediyelik eşya muafiyeti, posta veya hızlı kargo taşımacılığı yoluyla getirilen eşyaya uygulanmamaktadır.'],
    ] },
  ],
  tuzaklar: [
    'Posta gümrük kontrolüne **gelen, gönderilen ve iade edilen** eşya, posta çantaları ve koliler tabidir; yalnızca **içinde eşya bulunmadığı anlaşılan mektuplar** hariçtir.',
    'Mektup postası dışındaki eşyanın başka gümrüğe sevki → **transit rejimi** (her araç için ayrı beyanname); aynı ildeki havalimanından Posta İşleme Merkezine → **CN-38/CN-41** bordrosu.',
    'Koli listesinde: **sıra no (her yılbaşından teselsül)**, çıkış ülkesi/şehri, sayı-marka-numara, belgelerin sayı ve türü, **geldiği yol**. Muayene memuruna ait bilgi listede **yoktur**.',
    'Kıymet: fatura/satış fişi/ödeme belgesi; belge yok veya kıymet düşükse **gümrük idaresi** belirler. Giriş yerine kadar nakliye giderleri kıymete **ilave edilir**; navlun ayrı gösterilmemişse **3 avro** emsal navlun.',
    'Sayılar: BGB\'ye taşıma senedi ithalatta **500**, ihracatta **2.500**; aynı kişiye ayda **5** taşıma senedi (devredilmez); ihracat sınırı **brüt 600 kg / 30.000 Avro**; özet beyandan ekleme **%20**; teminat **10 milyon / 20 milyon TL**; operatörde asgari **2 gümrük müşaviri**.',
    'Süreler: teslim bilgisi **3 iş günü**; vergilerin ödenmesi **7 gün**; ihracat beyanında düzeltme **24 saat**; başvuru bölge müdürlüğünde **15 gün** + Bakanlıkta **15 gün**; belge saklama **5 yıl**; posta idaresinin tahsil ettiği vergiyi yatırma **1 hafta**; konsinye kesin satış **1 yıl** (uzatılmaz).',
    '**430 Avro** hediyelik eşya muafiyeti posta/hızlı kargoya **uygulanmaz**; cep telefonu posta/kargo ile **hiçbir surette** getirilemez (IMEI kayıtlı telefonun 3 ay içinde geri gönderimi hariç – **YLC0**). Yolcu beraberi cep telefonu: **iki takvim yılında bir adet**.',
    'Karar m.112: BGB (126/1-a) eşyasında diğer mevzuattan kısıtlamalar **uygulanmaz**; detaylı beyan (126/1-b) eşyasına m.112 **uygulanmaz** → genel hükümler. Ticari olmayan posta eşyasında Déclaration en Douane farklılığına **ceza aranmaz**, ticari eşyada **GK m.234**.',
  ],
};
