// 17. Konu — Gümrük Beyanı (kaynak: 17-BEYAN.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '17',
  konu: 'Gümrük Beyanı',
  kaynak: '17-BEYAN.docx (GK m.58–73; GY m.112–203)',
  bolumler: [
    { baslik: 'Beyan Yükümlülüğü ve Beyan Şekilleri (GK m.58–59, 62; GY m.112)', sorular: [
      ['İhracat, hariçte işleme, transit veya antrepo rejimi için beyan edilen serbest dolaşımdaki eşya ne zamana kadar gümrük gözetiminde kalır?',
        'Beyannamenin **tescilinden itibaren** TGB\'den **çıkıncaya**, **imha edilinceye** ya da beyanname **iptal edilinceye** kadar.', 'GK m.58/2', '2025',
        'İhracat, hariçte işleme, transit veya antrepo rejimi için beyan edilen serbest dolaşımda bulunan eşya, gümrüğe verilen beyannamenin tescilinden itibaren Türkiye Gümrük Bölgesinden çıkıncaya veya imha edilinceye ya da gümrük beyannamesi iptal edilinceye kadar gümrük gözetimi altında kalır.'],
      ['Gümrük beyanı hangi şekillerde yapılabilir?',
        '**Yazılı**, **bilgisayar veri işleme tekniği** yoluyla, **sözlü** ve eşya sahibinin rejime tabi tutma isteğini ifade ettiği **herhangi bir tasarruf** yoluyla.', 'GK m.59/1', '2023',
        ['Gümrük beyanı; a) Yazılı olarak, b) Bilgisayar veri işleme tekniği yoluyla, c) Sözlü olarak,', 'Eşya sahibinin bu eşyayı bir gümrük rejimine tabi tutma isteğini ifade ettiği herhangi bir tasarruf yoluyla']],
      ['GY\'ye göre beyanın hangi yolla yapılması esastır; elektronik imzayla yapılamayacak istisnai halleri kim belirler?',
        'Beyanın **bilgisayar veri işleme tekniği** yoluyla yapılması esastır; istisnai halleri **Bakanlık** belirler.', 'GY m.112/2', '',
        'Beyanın, bilgisayar veri işleme tekniği yoluyla yapılması esastır. Ancak, beyanın elektronik imzayla yapılamayacağı istisnai haller Bakanlıkça belirlenir.'],
      ['Beyanname tescili belirli bir kişi için özel yükümlülük getiriyorsa beyan sahibinde ne aranır; bu şartın istisnaları nelerdir?',
        'Beyanın o kişi tarafından/hesabına yapılması ve beyan sahibinin **TGB\'de yerleşik** olması; yerleşiklik şartı **transit** veya **geçici ithalat** beyanında bulunanlara ve idarenin uygun bulmasıyla **arızi** beyanda bulunanlara uygulanmaz.', 'GK m.62/2', '',
        ['bu beyanın söz konusu kişi tarafından ya da bu kişi hesabına yapılması ve beyan sahibinin Türkiye Gümrük Bölgesinde yerleşik olması gerekir', 'yerleşik olma koşulu, transit ya da geçici ithalat beyanında bulunan veya gümrük idarelerinin uygun bulması koşuluyla arızi olarak beyanda bulunan kişilere uygulanmaz']],
    ] },
    { baslik: 'Yazılı Beyan, Tescil ve Beyanın Bağlayıcılığı (GK m.60–61; GY m.113–114)', sorular: [
      ['Kazıntılı ve silintili beyannameler kabul edilir mi; hatalı yazı nasıl düzeltilir?',
        '**Kabul edilmez.** Hatalı yazı okunacak şekilde **çizilir**, yanına doğrusu yazılır, **beyan sahibince imzalanır** ve tescil sırasında **resmi mühürle** mühürlenir.', 'GK m.60/3', '',
        ['Kazıntılı ve silintili beyannameler gümrük idarelerince kabul edilmez.', 'beyannameler hatalı yazının üzeri okunacak şekilde çizilerek yanına doğrusu yazılıp beyan sahibi tarafından imzalanarak ve tescil sırasında resmi mühürle mühürlenerek düzeltilir']],
      ['Hangi hallerde yetkili makamlardan gönderilen resmi yazılar beyanname kabul edilir?',
        '**Cumhurbaşkanının zat ve ikametgâhına** ait eşya için Cumhurbaşkanlığı yazıları; diplomatik muafiyetlilerin kendi/elçilik adına gelen eşyası için **karşılıklılık şartıyla** misyon şefi/heyet başkanı yazıları ve **kurye mektupları**.', 'GK m.60/5', '',
        ['Cumhurbaşkanının zat ve ikametgâhına ait eşya hakkında Cumhurbaşkanlığından gönderilecek yazılar.', 'Diplomatik muaflık ve ayrıcalıklardan yararlananların ancak kendi adlarına veya elçilik adına gelecek eşya için karşılıklı olmak şartıyla misyon şeflerinden', 'kurye çantalarına ait kurye mektupları']],
      ['Beyanname hangi şartla tescil edilir?',
        'GK m.60\'a uygun beyanname, ait olduğu eşyanın **gümrüğe sunulmuş olması** halinde tescil edilir.', 'GK m.61/1', '',
        '60 ıncı maddede belirtilen şartlara uygun beyannameler, ait oldukları eşyanın gümrüğe sunulmuş olması halinde tescil edilir.'],
      ['Aksine hüküm yoksa rejim hükümlerinin uygulanmasında esas alınacak tarih hangisidir?',
        'Beyannamenin **tescil edildiği tarih**.', 'GK m.61/2', '',
        'eşyanın beyan edildiği gümrük rejimine ilişkin tüm hükümlerin uygulanmasında esas alınacak tarih, beyannamenin (..) tescil edildiği tarihtir'],
      ['Tescil edilmiş beyanname beyan sahibini nasıl bağlar?',
        'Eşyanın vergileri ve para cezalarından dolayı **taahhüt niteliğinde** bağlar ve **gümrük vergileri tahakkukuna esas** tutulur.', 'GK m.61/3', '',
        'ait olduğu eşyanın vergileri ve para cezalarından dolayı taahhüt niteliğinde beyan sahibini bağlar ve gümrük vergileri tahakkukuna esas tutulur'],
      ['Beyannamede imzası bulunanlar neden sorumludur; doğrudan temsilde sorumluluk kime aittir; beyanname devredilebilir mi?',
        'Cezai hükümler açısından bilgiler ve ekli belgelerin **doğruluğu** ile rejim yükümlülüklerine uyulmasından sorumludurlar; doğrudan temsilde sorumluluk **adına hareket edilene** aittir. Beyanname **devredilemez**; eşyanın satılması yükümlülükten **kurtarmaz**.', 'GY m.113/1', '',
        ['Beyannamede imzası bulunan kişiler cezai hükümlerin uygulanması açısından beyannamede belirtilen bilgiler ile beyannameye ekli belgelerin doğruluğu', 'Doğrudan temsil durumunda bu sorumluluk adına hareket edilenlere aittir.', 'Beyanın bağlayıcı olması nedeniyle beyanname başkasına devredilemez; eşyanın başkalarına satılması beyan sahiplerini yükümlülüklerinden kurtarmaz.']],
      ['Muayene türü yeşil hat belirlenen beyannamelere belge eklenir mi; YYS sahiplerinde belgeler nereye kaydedilir?',
        'Yeşil hatta belgeler **eklenmez**; yeşil hattan yararlanan **YYS** sahiplerinin beyannamelerinde belgeler **44 no.lu kutuya** kaydedilir.', 'GY m.114/3', '',
        ['Yeşil hattan yararlanma hakkı bulunan yetkilendirilmiş yükümlü sertifikası sahibi kişiler adına tescil edilen gümrük beyannamelerinin 44 no.lu kutusuna birinci fıkrada belirtilen belgeler kaydedilir.', 'Muayene türü yeşil hat olarak belirlenen gümrük beyannamelerine birinci fıkrada belirtilen belgeler eklenmez.']],
    ] },
    { baslik: 'Ticari ve Taşıma Belgeleri (GY m.116–118)', sorular: [
      ['Ayrıntılı fatura nedir?',
        'Kıymeti üzerinden vergiye tabi, **birden fazla kapta** gelen ve **çeşitli cins ve kıymette** olan eşyadan, her kapta aynı cins ve kıymette ne miktar eşya bulunduğunu gösteren, **satıcı veya gönderici** tarafından düzenlenen belge.', 'GY m.116/1', '',
        ['Ayrıntılı fatura, kıymetleri üzerinden vergiye tabi olup da birden ziyade kap içinde gelen ve aynı zamanda çeşitli cins ve kıymette olan eşyadan, her kapta aynı cins ve kıymette ne miktar eşya bulunduğunu gösteren', 'satıcı veya gönderici tarafından mahallinde düzenlenmiş bir belgedir']],
      ['Çeki listesi nedir; kim hazırlayabilir?',
        'Bir fatura kapsamı eşyanın çeşitli cins ve ağırlıktaki kaplara konulması halinde **her kapta ne miktar eşya bulunduğunu** gösteren belge; satıcı/gönderici veya **beyan sahibi** hazırlayabilir.', 'GY m.117/1–2', '2021, 2022',
        ['Çeki listesi, bir fatura kapsamı eşyanın çeşitli cins ve nev\'ide ve çeşitli ağırlıktaki kaplara konulması halinde, her kapta ne miktar eşya bulunduğunu göstermek amacıyla düzenlenen bir belgedir.', 'beyan sahibi tarafından da hazırlanabilir']],
      ['Deniz yolu taşımalarında taşıma belgesi nedir; kim tarafından kime verilir?',
        '**Konşimento**; geminin **kaptanı, donatanı veya mümessili** tarafından **yükletene** verilir.', 'GY m.118/1', '',
        'Deniz yoluyla yapılan taşımalarda geminin kaptanı veya donatanı veya mümessili tarafından yükletene taşıma belgesi olarak konşimento verilir.'],
      ['Hava, kara ve demiryolu taşımalarında hangi taşıma belgeleri kullanılır?',
        'Hava: **hava konşimentosu**; kara: **yük senedi (CMR)**; demiryolu: **CIM ve CIV** belgeleri.', 'GY m.118/2–4', '2023',
        ['Hava taşımalarında, aynı anlamda ve benzeri bilgileri kapsayan hava konşimentosu kullanılır.', 'Kara nakliyatında taşıyıcılar tarafından konşimento yerine düzenlenen belgeye yük senedi (CMR)', 'Demiryolu ile yapılan taşımalarda ise benzeri bilgileri içeren CIM ve CIV belgeleri gibi uluslararası kabul görmüş taşıma belgeleri kullanılır.']],
    ] },
    { baslik: 'Beyannamenin Düzeltilmesi ve Teslim Sonrası Kontrol (GK m.63, 73; GY m.121)', sorular: [
      ['Beyannamede düzeltmeye hangi koşulla izin verilir?',
        '**Başka bir eşyanın beyanı sonucunu doğurmaması** kaydıyla, **beyan sahibinin talebi** üzerine; bir veya daha fazla bilgi düzeltilebilir.', 'GK m.63', '',
        'Başka bir eşyanın beyanı sonucunu doğurmaması kaydıyla, beyan sahibinin talebi üzerine beyannamede yer alan bir veya daha fazla bilginin düzeltilmesine, gümrük idarelerince izin verilir.'],
      ['GK m.63\'e göre hangi durumlardan sonra beyannamede düzeltmeye izin verilmez?',
        'Beyan sahibine eşyanın **muayene edileceğinin bildirilmesinden**, bilgilerin **yanlış olduğunun tespitinden** ve **GK m.73 saklı** kalmak üzere eşyanın **teslim edilmesinden** sonra.', 'GK m.63', '2022',
        ['Beyan sahibine eşyanın muayene edileceğinin bildirilmesinden,', 'Söz konusu bilgilerin yanlış olduğunun tespit edilmesinden,', '73 üncü madde hükümleri saklı kalmak üzere, eşyanın teslim edilmesinden,']],
      ['GK m.63\'teki "başka bir eşya" ifadesinden ne anlaşılır?',
        '**Tarife alt pozisyonu değişen** eşya; değişmiyorsa vergi/ek mali yükümlülüğün **oran veya miktarına** ya da **ticaret politikası önlemine** ilişkin hak ve menfaatlerde farklılık gösteren eşya.', 'GY m.121/1', '',
        'tarife alt pozisyonu değişen, değişmemesi durumunda ise her türlü vergi ile ek mali yükümlülüğün ad valorem usulde oran veya spesifik usulde miktarına ve/veya ticaret politikası önlemine ilişkin faydalanılacak hak ve menfaatlerde farklılık gösteren eşya anlaşılır'],
      ['GY\'ye göre eşyanın teslimine kadar beyannamede düzeltme hangi anlardan önce yapılabilir?',
        'Bilgisayar sisteminin beyanın kontrol türünü **kırmızı hat** olarak belirlemesinden ve bilgilerin **yanlış olduğunun tespitinden** önce.', 'GY m.121/2', '',
        ['Eşyanın muayenesi için bilgisayar sistemi tarafından beyanın kontrolü türünün kırmızı hat olarak belirlenmesinden,', 'önce beyannamede düzeltme yapılmasına izin verilir']],
      ['Kırmızı hat belirlenen eşyada yanlışlık tespit edilmeden önce yapılan düzeltme talebi nasıl değerlendirilir; tespitten sonra?',
        'GK **m.234/3**\'ten yararlanma talebi sayılır ve sistemde düzeltilir; tespitten **sonraki** talepler **kabul edilmez**, **m.192 ve 193** uygulanır.', 'GY m.121/3', '',
        ['talep Kanunun 234 üncü maddesinin üçüncü fıkrasından yararlanma talebi olarak değerlendirilerek sistemde gerekli düzeltmeler yapılır', 'düzeltme talepleri kabul edilmeyerek 192 ve 193 üncü maddeler uygulanır']],
      ['Eşyanın tesliminden sonra (GK m.73/2) yükümlü talebiyle beyannamede düzeltme hangi süre içinde yapılabilir?',
        'Beyanname tescil tarihinden itibaren **üç yıl** içinde; **dahilde işleme** için daha uzun süre belirlemeye **Müsteşarlık** yetkili.', 'GY m.121/4', '',
        ['beyanname tescil tarihinden itibaren üç yıllık süre içinde yükümlünün talebi üzerine Kanunun 73 üncü maddesinin ikinci fıkrası uyarınca beyannamede düzeltme yapılmasına izin verilir', 'dahilde işleme rejimi için bu sürenin üç yıldan daha uzun belirlenmesine Müsteşarlık yetkilidir']],
      ['Eşyanın tesliminden sonraki kontrol neleri kapsar; yanlış veya eksik bilgi saptanırsa ne olur?',
        'İthal/ihraç ve sonraki ticari işlemlere ilişkin **ticari belge ve veriler** kontrol edilir; mümkünse eşya da **muayene** edilir. Saptama halinde ceza hükümleri saklı kalarak beyan **yeni bulgulara göre düzeltilir**.', 'GK m.73/1, 3', '',
        ['eşyanın ithal veya ihraç işlemlerini veya sonraki ticari işlemlere ilişkin ticari belge ve verileri kontrol edebilirler', 'Mümkün olduğu takdirde eşya muayene de edilebilir.', 'beyanı yeni bulgulara göre düzeltmek için gerekli işlemleri yaparlar']],
    ] },
    { baslik: 'Beyannamenin İptali (GK m.64; GY m.124–129)', sorular: [
      ['Gümrük idareleri tescilli bir beyannameyi hangi hallerde iptal edebilir?',
        'Beyan sahibinin talebi ve eşyanın **yanlışlıkla** o rejime tabi tutulduğunu ya da rejime tabi tutulmasının **özel nedenlerle artık mümkün olmadığını** kanıtlayan belgeleri ibrazı halinde; gerektiğinde **yeni rejim beyanına** izin verilir.', 'GK m.64/1', '',
        'eşyanın yanlışlıkla beyanname konusu gümrük rejimine tabi tutulmasına veya beyan edildiği rejime tabi tutulmasının özel nedenlerle artık mümkün olmadığına ilişkin kanıtlayıcı belgeleri ibraz etmesi halinde, tescil edilmiş bir beyannameyi iptal ederek, gerektiğinde yeni bir rejim beyanında bulunulmasına izin verebilirler'],
      ['Eşyanın muayene edileceği bildirilmişse beyannamenin iptali talep edilebilir mi?',
        'Muayenenin **sonucu alınmadan** iptal talebi **kabul edilmez**.', 'GK m.64/1', '',
        'gümrük idarelerince beyan sahibine eşyanın muayene edileceğinin bildirilmiş olduğu hallerde, muayenenin sonucu alınmadan beyannamenin iptaline ilişkin talep kabul edilmez'],
      ['Eşyanın tesliminden sonra beyanname iptal edilebilir mi; iptal cezai hükümlere engel olur mu?',
        '**Yönetmelikle belirlenen haller dışında** iptal edilemez; iptal, cezai hükümlerin uygulanmasına **engel oluşturmaz**.', 'GK m.64/4–5', '',
        ['Yönetmelikle belirlenen haller dışında, eşyanın tesliminden sonra beyannameler iptal edilemez.', 'Beyannamenin iptali, yürürlükteki cezai hükümlerin uygulanmasına engel oluşturmaz.']],
      ['Eşyanın yanlış rejimde beyanı nedeniyle teslimden sonra iptal için hangi şartların tamamı kanıtlanmalıdır?',
        'Eşyanın herhangi bir kullanımının istenilen rejime **engel olmaması**; tescil sırasında istenilen rejimin **bütün yükümlülüklerinin** yerine getirilmiş olması; eşyanın istenilen rejime **gecikmeksizin** girişinin mümkün olması.', 'GY m.124/1', '',
        ['Beyanname konusu eşyanın herhangi bir kullanımının beyan edilmek istenilen gümrük rejimine tabi tutulmasına engel olmaması,', 'Beyannamenin tescil edildiği sırada beyan edilmek istenilen gümrük rejimine ilişkin bütün yükümlülüklerin yerine getirilmiş olması,', 'Eşyanın beyan edilmek istenilen rejime gecikmeksizin girişinin mümkün olması.']],
      ['Yanlış rejim nedeniyle iptal talebi hangi süre içinde yapılır; yeni rejim beyannamesi hangi tarihten geçerlidir?',
        'Tescilden itibaren **üç ay** içinde (**mücbir sebep/beklenmeyen hal** kanıtlanırsa süre aşımında da kabul edilebilir); yeni beyanname **ilk beyannamenin tescil tarihinden** itibaren geçerlidir.', 'GY m.124/2–3', '2021',
        ['Beyannamenin iptaline ilişkin taleplerin beyannamenin tescil edildiği tarihten itibaren üç ay içerisinde yapılması gerekir.', 'mücbir sebep ve beklenmeyen hallerin varlığı ve kanıtlanması halinde üç aylık sürenin aşılması durumunda da başvuruyu kabul edebilir', 'Beyan edilmek istenilen gümrük rejimine ilişkin beyanname, ilk beyannamenin tescil edildiği tarihten itibaren geçerli olur.']],
      ['İhracat veya HİR beyannamesinin iptali için beyan sahibi neleri kanıtlamalıdır; iptalin sonucu nedir?',
        'GY **m.417 süreleri** içinde müracaatla: eşyanın **gümrük bölgesini terk etmediği**, tescilde sunulan belgelerin ibrazı, sağlanan **hak ve menfaatlerin iadesi** (veya yararlandırılmaması tedbiri), gerekirse eşyanın GOİK\'e tabi tutulması. İptal, **ihracat lisansı** ve tevsik belgelerine ilişkin işlemlerin de iptali sonucunu doğurur.', 'GY m.127/1–2', '',
        ['417 nci maddede belirtilen süreler içerisinde müracaat etmesi', 'Beyanname konusu eşyanın gümrük bölgesini terk etmediğinin ihracata ilişkin işlemlerin yapıldığı gümrük idaresine belgelenmesi,', 'İhracat nedeniyle beyan sahibine sağlanan bütün hak ve menfaatlerin iade edildiğinin', 'Beyannamenin iptali, ihracat lisansına veya beyanın tevsiki için ibraz edilen bütün belgelere ilişkin olarak yapılan işlemlerin de iptali sonucunu doğurur.']],
      ['Posta veya hızlı kargoyla gelen eşyanın tesliminden sonra iadesinde beyanname hangi şartla iptal edilir?',
        'Tescilden itibaren **üç ay** içinde başvuru ve eşyanın **gerçek tedarikçisine** ya da onun tayin ettiği adrese **geri gönderilmesi** şartıyla.', 'GY m.129/1', '',
        'beyan sahibinin beyannamenin tescil edildiği tarihten itibaren üç ay içerisinde başvuruda bulunması ve eşyanın gerçek tedarikçisine ya da tedarikçisi tarafından tayin edilen adrese geri gönderilmesi şartıyla beyanname iptal edilir'],
    ] },
    { baslik: 'Eşyanın Teslimi ve İşlem Süreleri (GK m.69–70; GY m.122, 130)', sorular: [
      ['Beyannamenin tescili gümrük yükümlülüğü doğuruyorsa eşya ne zaman teslim edilir; istisnası nedir?',
        'Gümrük vergileri **ödenmedikçe veya teminata bağlanmadıkça** teslim edilmez; bu hüküm **kısmi muafiyetli geçici ithalata** uygulanmaz.', 'GK m.69/3', '',
        ['gümrük vergileri ödenmedikçe veya teminata bağlanmadıkça beyanname kapsamı eşya teslim edilemez', 'bu hüküm kısmi muafiyete tabi geçici ithalat rejimine uygulanamaz']],
      ['Beyan sahibinden kaynaklanan sebeplerle GK m.46 süreleri içinde muayeneye başlanamaz, belgeler verilmez veya vergiler ödenmezse ne olur?',
        'Eşya **muayene edilir**, durum **tutanağa** bağlanır ve eşya **GK m.177–180**\'e göre **tasfiye** edilir.', 'GK m.70/1', '',
        'Muayene sonucunda gümrük idarelerince alınacak para cezasını veya diğer takipleri gerektiren veya gerektirmeyen durumlar bir tutanağa bağlanır ve daha sonra eşya 177 ila 180 inci madde hükümlerine göre tasfiye edilir.'],
      ['Gümrük antreposundaki eşya için GOİK tayinine ilişkin beyanname verildiğinde işlemler ne kadar sürede bitirilmelidir?',
        'Beyannamenin tescil tarihinden itibaren **otuz gün** içinde; bitirilemezse **m.70/1** (muayene, tutanak, tasfiye) uygulanır.', 'GK m.70/2', '2021, 2023',
        'gümrük işlemlerinin beyannamenin tescil tarihinden itibaren otuz gün içinde bitirilmesi gerekir. Bu süre içinde işlemleri bitirilemeyen eşya ile ilgili olarak 1 inci fıkra hükümleri uygulanır.'],
      ['Bölünmüş beyanname: farklı kalemlerden birinin çekilmesi isteği ne zaman kabul edilir; en son kısım için ne yapılır?',
        'Eşyanın **muayenesi yapıldıktan** ve ceza gerektiren durum varsa bunun **duyurulmasından sonra**; çekilecek kısım için **ayrı beyanname** alınır, **en son kısım** için beyanname aranmaz, tahakkuk **asıl beyanname** üzerinden yapılır.', 'GY m.122/1–4', '',
        ['bu istek, eşyanın muayenesi yapıldıktan ve para cezasına hükmedilmesini gerektirir bir durumun olması halinde bunun eşya sahip veya temsilcilerine duyurulmasından sonra kabul olunur', 'gümrükten çekilmek istenilen kısım için beyan sahiplerinden sistemdeki asıl beyannameye uygun olarak ayrı bir beyanname alınır', 'Eşyanın en son kısmı için sahiplerinden ayrıca beyanname aranmayıp vergi tahakkukları asıl beyanname üzerinden yapılır']],
      ['Hızlı kargo eşyasının serbest dolaşım beyannamesinin incelemesi ne kadar sürede tamamlanamazsa eşya teslim edilir?',
        'Beyannamenin verilmesinden itibaren **altı saat** içinde; muayenenin zorunlu görüldüğü bildirilmişse bu süre kısıtlaması **uygulanmaz**.', 'GY m.130/2', '',
        ['beyannamesinin gümrük idaresine verilmesinden itibaren altı saat içerisinde bu beyannamenin incelenmesinin tamamlanamaması halinde de eşya teslim edilir', 'bu fıkrada belirtilen süre kısıtlaması uygulanmaz']],
      ['Tahlile tabi eşya, tahlil sonucu beklenmeden hangi şartlarla teslim edilir?',
        'Beyan edilen GTİP\'in vergi oranı ile fasıldaki **en yüksek vergi oranı** arasındaki fark **teminata** bağlanır, **ek-17 taahhütname** alınır, **şahit numune** alınır ve eşya **yediemin** olarak teslim edilir. Ticaret politikası önlemi veya telafisi imkânsız sonuç şüphesinde uygulamamaya **gümrük idare amiri** yetkilidir.', 'GY m.130/3', '',
        ['beyan edilen fasıldaki en yüksek vergi oranı arasındaki farka karşılık gelen tutarın teminata bağlanarak', 'eşyadan bir adet şahit numune alınarak gümrük idaresince uygun görülen yerde muhafaza edilmek kaydıyla yediemin olarak teslim edilir', 'bu fıkra hükmünün uygulanmamasına gümrük idare amiri yetkilidir']],
    ] },
    { baslik: 'Beyanname Yerine Kullanılan Belgeler ve Kurye (GY m.118, 131–135)', sorular: [
      ['Gümrük beyannamesi yerine kullanılan belgeler nelerdir; bunlar beyanname mahiyetinde midir?',
        'Elçilik Mektubu, Kurye Mektubu, **TIR Karnesi**, **ATA Karnesi**, **Kumanya Listesi**, **Özel Fatura**, Déclaration en Douane, **CPD Karnesi**, Yolcu Beraberi Numune, Sergi ve Fuar Eşyası Beyan Formu, **Sözlü Beyan Formu** gibi belgeler; beyanname yerine kullanılır ancak **beyanname mahiyetinde değildir**.', 'GY m.131/1', '2022, 2023, 2024',
        'Elçilik Mektubu, Kurye Mektubu, TIR Karnesi, ATA Karnesi, Kumanya Listesi, Özel Fatura, Déclaration en Douane, CPD Karnesi, Yolcu Beraberi Numune, Sergi ve Fuar Eşyası Beyan Formu ve Sözlü Beyan Formu gibi belgeler gümrük beyannamesi yerine kullanılır, ancak bu belgeler gümrük idarelerine verilen beyannameler mahiyetinde değildir.'],
      ['CIM taşıma belgesi, menşe şahadetnamesi veya A.TR dolaşım belgesi beyanname yerine kullanılan belgelerden midir?',
        '**Hayır**; m.131\'de sayılan belgeler arasında yer almazlar (CIM, GY m.118/4\'e göre bir **demiryolu taşıma belgesidir**).', 'GY m.131/1; m.118/4', '2022, 2023, 2024',
        ['Kumanya Listesi, Özel Fatura, Déclaration en Douane, CPD Karnesi', 'Demiryolu ile yapılan taşımalarda ise benzeri bilgileri içeren CIM ve CIV belgeleri gibi uluslararası kabul görmüş taşıma belgeleri kullanılır.']],
      ['Kurye kapları gümrükte nasıl işlem görür?',
        'Dıştan muayene edilir; kurye mektubu uygun ve **resmi mühürle** mühürlü ise kaplar **açılmadan**, etiket/işaret konularak geçirilir.', 'GY m.134/1', '',
        ['kurye mektuplarının uygun ve resmi mühür ile mühürlenmiş olduğunu gördükleri takdirde', 'bunları açıp kapsamını muayene etmeksizin, üzerlerine etiket yapıştırarak veya işaret koyarak geçirilmelerine izin verir']],
      ['Mühürleri sağlam olmayan veya kurye mektubuna uymayan dışarıdan gelen kurye kaplarına ne yapılır?',
        '**Gümrük mührü** tatbik edilir, **tutanak** tutulur, kuryenin sorumluluğunda **Esenboğa Gümrük Müdürlüğüne** sevk edilir; mahalli gümrük amiri **Müsteşarlığa** bildirir.', 'GY m.135/1', '',
        ['kaplara gümrüğün mührü tatbik edilir ve durum bir tutanakla tespit edildikten sonra kuryenin sorumluluğu altında Esenboğa Gümrük Müdürlüğüne sevk edilir', 'Keyfiyet en seri şekilde mahalli gümrük amiri tarafından Müsteşarlığa bildirilir']],
    ] },
    { baslik: 'Basitleştirilmiş Usuller (GK m.71; GY m.140–166)', sorular: [
      ['GK m.71\'e göre gümrük idareleri hangi basitleştirilmiş usullere izin verebilir?',
        '(a) Bazı belgelerin eklenmemesi/bilgilerin yazılmaması (**eksik beyan**), (b) beyanname yerine **ticari veya idari belge**, (c) rejime geçişin **kayıt yoluyla** yapılması; (c)\'de beyan sahibi eşyayı **gümrüğe sunma yükümlülüğünden muaf** tutulabilir.', 'GK m.71/1', '',
        ['60 ıncı maddede sözü edilen beyannameye eklenmesi gereken belgelerden bazılarının eklenmemesine ve kaydedilmesi gereken bazı bilgilerin beyannameye yazılmamasına,', 'Sözü edilen beyanname yerine, eşyanın ilgili gümrük rejimine tabi tutulması talebi ile birlikte, ticari veya idari bir belgenin verilmesine,', 'Eşyanın ilgili rejime geçişinin kayıt yoluyla yapılmasına,', '(c) bendinin uygulanmasında beyan sahibi eşyayı gümrüğe sunma yükümlülüğünden muaf tutulabilir.']],
      ['Basitleştirilmiş usulde tamamlayıcı beyan hangi nitelikte olur; tamamlayıcı beyanlar ne zamandan hüküm ifade eder?',
        '**Genel, dönemsel veya özet** nitelikte; basitleştirilmiş beyanla **ayrılmaz bir bütündür** ve basitleştirilmiş işleme ilişkin beyannamenin **tescil tarihinden** itibaren hüküm ifade eder. Kayıt işlemi, beyanname tesciliyle **aynı hukuki sonucu** doğurur.', 'GK m.71/2–3', '',
        ['Beyan sahibi genel, dönemsel veya özet niteliğinde bir tamamlayıcı beyanda bulunur.', 'ayrılmaz bir bütündür ve basitleştirilmiş işleme ilişkin beyannamelerin tescil tarihinden itibaren hüküm ifade ederler', 'kayıt işlemi, 60 ıncı maddede sözü edilen beyannamenin tescili ile aynı hukuki sonucu doğurur']],
      ['Eksik beyan usulünden kimler yararlanabilir; ticari veya idari belge usulünde bu statüler aranır mı?',
        'Eksik beyan: **YYS sertifikası** veya **onaylanmış kişi statü belgesi** sahiplerinden koşulları sağlayanlar; ticari/idari belge usulünde YYS/OKS koşulları **aranmaz**.', 'GY m.140/1–2', '',
        ['eksik beyan usulünden yetkilendirilmiş yükümlü sertifikasına veya onaylanmış kişi statü belgesine sahip gerçek ve tüzel kişilerden', 'beyanname yerine ticari veya idari belge verilmesi usulünden yararlanmak için yapılan talepler yetkilendirilmiş yükümlü veya onaylanmış kişi statüsüne ilişkin koşullar aranmaksızın kabul edilir']],
      ['Kayıt yoluyla rejime giriş usulünden kimler yararlanabilir; hangi koşula bağlıdır?',
        'Yalnızca **YYS sertifikası** sahipleri; **ihracat rejimi hariç**, kapsamı ve miktarı Bakanlıkça belirlenecek **teminat** verilmesi koşuluna bağlıdır.', 'GY m.140/3–4', '',
        ['eşyanın kayıt yoluyla rejime girişi usulünden yetkilendirilmiş yükümlü sertifikasına sahip kişiler yararlandırılabilir', 'ihracat rejimi hariç olmak üzere, kapsamı ve miktarı Bakanlıkça belirlenecek teminatın verilmesi koşuluna bağlıdır']],
      ['Serbest dolaşıma girişte eksik beyanın tamamlanma süresi nedir; indirimli/sıfır oran belgeleri için ek süre ne kadardır?',
        'Tescilden itibaren **bir ayı** geçemez; indirimli/sıfır oran belgesi için verilecek ek süre **üç ayı** geçemez; eksiklik **gümrük kıymetiyle** ilgiliyse daha uzun süre belirlenebilir. Süresinde tamamlanmazsa vergiler **ertelenmez**.', 'GY m.144/1–3, 5', '',
        ['söz konusu tescil tarihinden itibaren bir ayı geçemez', 'İndirimli veya sıfır oranında ithalat vergisinin uygulanması için gereken belgelerin eksikliği durumunda', 'Bu şekilde verilecek ek süre üç ayı geçemez.', 'Tamamlanacak eksik beyanın gümrük kıymeti ile ilgili olması ve daha uzun bir süre gerekmesi', 'söz konusu beyanname kapsamı eşyanın ödenmesi gereken vergileri ertelenmez']],
      ['Eksik belgeler süresinde sunulmazsa noksan alınan gümrük vergileri ne zaman ödenir?',
        '**6183 s. Kanun m.51** gecikme zammı oranında faizle birlikte, yükümlüye tebliğini takiben **on beş gün** içinde.', 'GY m.145/2', '',
        '6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanunun 51 inci maddesine göre tespit edilen gecikme zammı oranında faizin yükümlüye tebliğ edildiği tarihi takiben onbeş gün içinde ödenmesi zorunludur'],
      ['Özelliği olan eşyanın tesliminde basitleştirilmiş usul için YYS/OKS koşulu aranır mı; bu eşyaya örnekler nelerdir?',
        '**Aranmaz.** Örn. TAEK uygunluk yazılı **radyoaktif maddeler**, **aşılar**, **canlı hayvanlar**, yurt dışında yayımlanan **gazete ve dergiler**, **dökme ve havaleli** eşya, **boru hattı/elektrik teliyle** taşınan sürekli akış halindeki eşya.', 'GY m.147/1–2', '',
        ['yetkilendirilmiş yükümlü veya onaylanmış kişi statüsüne ilişkin koşullar aranmaksızın ilgili gümrük idaresince değerlendirilip kabul edilebilir', 'Türkiye Atom Enerjisi Kurumunun uygunluk yazısının ibrazı şartıyla radyoaktif maddeler,', 'Yurt dışında periyodik olarak yayımlanan gazete ve dergiler', 'Boru hatları veya elektrik telleri ile taşınan ve depolama imkanı olmayan sürekli akış halinde olan eşya.']],
      ['Serbest dolaşıma girişte beyanname yerine ticari veya idari belge usulünden kimler, ne kadar süreyle yararlanır?',
        'm.147/2\'nin (b), (c), (d), (f), (g), (ğ) bentlerindeki eşya, **akvaryum balıkları** ve **CIF kıymeti 500 Avro**\'yu geçmeyen eşyayı aynı idareden **sürekli ve periyodik** ithal edenler; yazılı talep YYS/OKS aranmaksızın **altı ay** geçerli olmak üzere kabul edilir.', 'GY m.148/1', '',
        ['eşya ve akvaryum balıkları ile CIF kıymeti 500 Avro\'yu geçmeyen diğer eşyayı aynı gümrük idaresinden sürekli ve periyodik olarak ithal edenlerin', 'altı ay süreyle geçerli olmak üzere kabul edilir']],
      ['Serbest dolaşıma girişte basitleştirilmiş usulde tamamlayıcı beyan ne zaman verilir?',
        'Bir ay içindeki işlemler için **izleyen ayın ilk üç günü** içinde; m.53/1 kıymet unsurlarını içeriyorsa tahakkuk ayını izleyen ayın **yirmi altıncı günü akşamına** kadar (vergiler de aynı sürede ödenir).', 'GY m.150/2–3', '',
        ['tamamlayıcı beyanın, izleyen ayın ilk üç günü içinde verilmesi zorunludur', 'eksik kıymet unsurunun mahiyet ve tutar itibariyle tahakkuk ettiği ayı takip eden ayın yirmi altıncı günü akşamına kadar verilir']],
      ['Antrepo tiplerine göre serbest dolaşıma girişte basitleştirilmiş usul nasıl uygulanır?',
        '**F tipi**: izin verilmez; **B tipi**: yalnız **eksik belgeyle beyan** ve **ticari/idari belge**; **D tipi**: **kayıt yoluyla** yapılabilir.', 'GY m.151/2', '',
        ['F tipi antrepoda bulunan eşyanın serbest dolaşıma girişinde basitleştirilmiş usule izin verilmez.', 'B tipi antrepoda bulunan eşyanın serbest dolaşıma girişinde sadece eksik belgeyle beyan ve beyanname yerine ticari veya idari bir belge verilmesi şeklinde beyan yöntemi uygulanabilir.', 'D tipi antrepoda bulunan eşyanın serbest dolaşıma girişi kayıt yoluyla yapılabilir.']],
      ['İhracat rejiminde eksik beyanın tamamlanma süresi nedir?',
        'Tescilden itibaren **bir ayı** geçemez; gerekli hallerde uzatılabilir, ek süre **üç ayı** geçemez. Süresinde tamamlanmazsa vergiler **ertelenmez**.', 'GY m.155/1–2', '2025',
        ['eksik olan bilgi veya belgelerin tamamlanması için beyan sahibine tanınan süre, beyannamenin tescil tarihinden itibaren bir ayı geçemez. Gerekli görülen durumlarda bu süre uzatılabilir. Bu şekilde verilecek ek süre üç ayı geçemez.']],
      ['Posta idaresi ve hızlı kargo şirketlerinin faturası eklenmemiş ihracat beyanı hangi şartla kabul edilir; tamamlayıcı beyan süresi nedir?',
        'Beyan için gerekli bilgileri içeren **e-irsaliyenin** beyannameye eklenmesi kaydıyla; tamamlayıcı beyan beyanı takiben **yedi iş günü** içinde.', 'GY m.153/3; m.158/6', '',
        ['beyan için gerekli bilgileri içeren e-irsaliyenin beyannameye eklenmesi kaydıyla kabul edebilir', 'basitleştirilmiş usule göre verilen beyanı takiben yedi iş günü içerisinde tamamlayıcı beyan verilir']],
      ['İhracat rejiminde basitleştirilmiş usulde tamamlayıcı beyan ne zaman verilir?',
        'Bir ay içindeki işlemler için **izleyen ayın ilk üç günü**; deniz taşıtları ve hava gemilerine GK m.176 kapsamında yapılan **ihracat sayılan teslimlerde** izleyen ayın **ilk yedi iş günü**.', 'GY m.158/2', '',
        ['Bir ay içinde gerçekleştirilen basitleştirilmiş işlemlere ilişkin tamamlayıcı beyanın izleyen ayın ilk üç günü içinde yapılması gerekir.', 'ihracat sayılan teslimlere ilişkin tamamlayıcı beyan izleyen ayın ilk yedi iş günü içinde yapılır']],
      ['Gümrük antrepo rejiminde eksik beyan ve kayıt yoluyla giriş hangi antrepo tiplerinde uygulanmaz?',
        'Eksik beyan **F tipi**ne alınmada uygulanmaz; kayıt yoluyla giriş (yalnız **YYS** sahiplerine) **B ve F tipi**ne alınmada uygulanmaz.', 'GY m.162/2; m.166', '',
        ['Eksik beyan usulü, eşyanın F tipi antrepolara alınmasında uygulanmaz.', 'Yetkilendirilmiş yükümlü sertifikasına sahip kişilere gümrük idarelerince eşyanın antrepo rejimine girişinin kayıt yoluyla yapılmasına izin verilebilir.', 'Bu usul, eşyanın B ve F tipi antrepolara alınmasında uygulanmaz.']],
    ] },
    { baslik: 'Sözlü Beyan ve Başka Bir Tasarruf Yoluyla Beyan (GY m.169–179)', sorular: [
      ['Serbest dolaşıma girişte sözlü beyana tabi ticari nitelikte olmayan eşyaya örnekler nelerdir?',
        'Yolcu, turist ve nakil vasıtası hizmetlilerinin kişisel eşyası; **sınır bölgesi halkının elde ve sırtta** taşınabilecek kendi ihtiyaç eşyası; işlem görmüş ticari değeri olmayan **defter, evrak, belge**; yarışmalarda ödül olarak **bağış** yoluyla gönderilen eşya vb.', 'GY m.169/1', '',
        ['Sınır bölgesi halkının elde ve sırtta taşınabilecek miktarda kendi ihtiyaçlarına mahsus eşyası,', 'Resmi daire ve müesseselerle özel müessese ve şahıslara ait işlem görmüş ticari değeri olmayan her türlü defter, evrak, belge,', 'mükâfat olarak verilmek üzere bağış yoluyla gönderilen eşya']],
      ['Ticari amaçla serbest dolaşıma girecek eşya hangi şartlarla sözlü beyan edilir?',
        'Gümrük kıymetinin sevkiyat ve beyan başına **1000 Avro**\'yu geçmemesi; sevkiyatın **düzenli benzer sevkiyatların parçası olmaması** ve bağımsız taşıyıcıyla taşınan **daha büyük bir nakliyatın parçası olmaması**.', 'GY m.169/6', '',
        'gümrük kıymetinin sevkiyat ve beyan başına 1000 Avro\'yu geçmemesi ve sevkiyatının düzenli haldeki benzer sevkiyatların bir parçası olmaması ve daha büyük bir nakliyatın bir parçası olup da bağımsız bir taşıyıcı tarafından taşınmaması kaydıyla bu eşya gümrük idaresine sözlü beyan edilir'],
      ['Türkiye\'de vefat eden yabancıların ülkelerindeki kanuni mirasçılarına intikal eden kişisel ve ev eşyasının ihracında beyan nasıl yapılır?',
        '**Sözlü** olarak.', 'GY m.170/1-f', '2022',
        ['Aşağıda yazılı eşyanın ihracında beyan sözlü olarak yapılır.', 'Türkiye\'de vefat eden yabancıların ülkelerindeki kanuni mirasçılarına intikal eden kişisel eşya ve ev eşyası.']],
      ['İçinde ölü veya ölünün kül ve kemikleri bulunan tabut, vazo ve kaplar ile çelenk ve çiçeklerin ihracında beyan nasıl yapılır?',
        '**Sözlü** olarak.', 'GY m.170/1-e', '2025',
        ['Aşağıda yazılı eşyanın ihracında beyan sözlü olarak yapılır.', 'İçinde ölü veya ölünün kül ve kemikleri bulunan tabut, vazo ve diğer kaplar ile çelenk ve çiçekler,']],
      ['Yurt dışına devamlı görev veya yerleşme için gidenlerin kişisel ve ev eşyası hangi süre içinde gönderilirse ihracatta sözlü beyana tabidir?',
        'Beraberde götürülen ya da gidişten **iki ay evvel** veya **altı ay sonra** gönderilen eşya (görevi/işi sona eren yabancılar dahil).', 'GY m.170/1-b', '',
        'beraberlerinde götürecekleri veya gidişlerinden iki ay evvel veya altı ay sonra gönderecekleri kişisel ve ev eşyası'],
      ['Geçici ithalatta sözlü beyana tabi eşya hangi formla beyan edilir; formun tescili ne hükümdedir?',
        '**Ek-22 Sözlü Beyan Formu**; tescili **geçici ithalat rejimi kullanım izni** hükmündedir. (Örn. **paletler**, yolcuların kişisel ve sportif amaçlı eşyası.)', 'GY m.171/1–2', '',
        ['Geçici ithalatta sözlü beyana tabi eşya, ek-22\'de yer alan Sözlü Beyan Formu kullanılarak beyan edilir. Söz konusu formun tescili, geçici ithalat rejimi kullanım izni hükmündedir.', 'Yolcular tarafından getirilen kişisel ve sportif amaçlı eşya,', 'gemi adamlarının ihtiyaç malzemesi, f) Paletler,']],
      ['Sözlü beyana tabi eşyada gümrük idaresi hangi durumda yazılı beyan isteyebilir?',
        'İşlemler **temsilci** tarafından yürütülürken sözlü beyanın **doğru ve tam** olduğu konusunda **tereddüt** oluşursa.', 'GY m.173/1', '',
        'Sözlü beyana tabi eşyanın gümrük işlemlerinin bir temsilci tarafından yürütüldüğü durumlarda, yapılan sözlü beyanın doğru ve tam olduğu konusunda tereddütlerin oluşması halinde, gümrük idareleri bu kapsamdaki eşya için yazılı beyanda bulunulmasını isteyebilir.'],
      ['Serbest dolaşıma girişte başka bir tasarruf yoluyla beyan kabul edilen eşya nelerdir?',
        'BKK ile belirlenen ticari mahiyette olmayan **yolcu beraberi eşya**; sınır çiftçilerinin komşu ülkedeki mülk ürünleri ve getirilen **tohum, gübre**; 32 Sayılı Karar ile belirlenen yolcu beraberi **standart işlenmemiş altın**.', 'GY m.175/1', '',
        ['Bakanlar Kurulu Kararı ile belirlenen ticari mahiyette olmayan yolcu beraberi eşya,', 'toprak ve ekinlerin işlenmesi amacına yönelik tohum, gübre ve diğer ürünler', 'Türk Parası Kıymetini Koruma Hakkında 32 Sayılı Karar ile belirlenen yolcu beraberinde yurda getirilen standart işlenmemiş altın.']],
      ['Başka bir tasarruf yoluyla beyan nasıl gerçekleşir; gerçekleşince ne kabul edilir?',
        'İki hat sisteminde **yeşil / "beyana tabi eşyam yoktur"** hattından geçiş, hat sistemi yoksa beyan yapılmaksızın geçiş veya **EK 22/A** formu; eşyanın **sunulduğu**, beyannamenin **tescil edildiği** ve eşyanın **teslim edildiği** kabul edilir.', 'GY m.178/1–2', '',
        ['iki hat sisteminin çalıştığı gümrük idarelerinde yeşil veya "beyana tabi eşyam yoktur" hattından geçirilmesi', 'EK 22/A\'da yer alan formla', 'eşyanın Kanunun 61 inci maddesinin birinci fıkrası çerçevesinde gümrük idaresine sunulduğu, buna ilişkin beyannamenin tescil edildiği ve eşyanın teslim edildiği kabul edilir']],
      ['Hangi eşya başka bir tasarruf yoluyla beyan hükümlerinden (m.175–177) yararlanamaz?',
        '**İhracata bağlı hak ve menfaatlerden** yararlanan, gümrük vergileri **geri verilen** veya **yasaklama, kısıtlama** ya da diğer özel işleme tabi eşya.', 'GY m.179/1', '',
        'ihracata bağlı hak ve menfaatlerden yararlanan, gümrük vergilerinin geri verildiği veya yasaklama, kısıtlama veya diğer özel bir işleme tabi eşya için uygulanmaz'],
    ] },
    { baslik: 'Beyanın Kontrolü ve Muayene (GK m.65–67; GY m.180–192)', sorular: [
      ['Gümrük idareleri beyanın doğruluğunu araştırmak için neler yapabilir?',
        'Beyanname ve ekli belgeleri **kontrol** edip **diğer belgeleri** isteyebilir; eşyayı **muayene** edebilir ve ayrıntılı muayene veya **tahlil** amacıyla **numune** alabilir.', 'GK m.65/1', '2022',
        ['Beyanname ile ilgili ve beyannameye ekli belgeleri kontrol edebilir ve beyannamenin içerdiği bilgilerin doğruluğunu araştırmak amacı ile beyan sahibinden diğer belgeleri de vermesini isteyebilir,', 'Eşyayı muayene edebilir ve ayrıntılı muayene veya tahlil amacıyla numune alabilirler.']],
      ['Muayenesi yapılmış ve işlemleri tamamlanmış eşyanın ikinci muayenesini kimler yapabilir?',
        '**Gümrük müfettişleri, müfettiş yardımcıları, kontrolörler, stajyer kontrolörler** ve **gümrük idare amirleri**; **her zaman** yapabilir, işlemleri her aşamada denetleyebilirler.', 'GK m.65/3', '',
        ['Kontrol amacıyla gümrük müfettişleri, gümrük müfettiş yardımcıları, kontrolörler, stajyer kontrolörler ve gümrük idare amirleri muayenesi yapılmış ve işlemleri tamamlanmış eşyanın ikinci muayenesini her zaman yapabilirler.', 'gümrük işlemlerini her aşamada denetlemeye yetkilidirler']],
      ['Beyanın kontrol türü ve görevli memur nasıl belirlenir; kontrol hatları nelerdir?',
        '**Bilgisayar sistemi**, risk kriterlerine göre belirler. **Kırmızı**: muayene + belge kontrolü; **Sarı**: muayenesiz belge kontrolü; **Mavi**: onaylanmış kişi statüsündekilerin **ihracatı**, çıkış öncesi kontrol yok (kontrol çıkıştan sonra); **Yeşil**: belge kontrolü ve muayene yok.', 'GY m.180/1–2', '2021, 2023',
        ['Beyanın kontrol türü ve kontrolle görevli memur, bilgisayar sistemi tarafından risk kriterlerine göre belirlenir.', 'Kırmızı hat; eşyanın muayenesi ile birlikte belge kontrolünün de yapıldığı hattır.', 'Sarı hat; muayeneye gerek görülmeksizin eşyaya ait beyanname ve eklerinin doğruluğunun ve birbiriyle uygunluğunun kontrol edildiği hattır.', 'Mavi hat; Bakanlıkça belirlenen onaylanmış kişi statüsüne sahip kişilerin ihracatta yararlandığı, eşyanın çıkış işlemlerinin tamamlanmasından önce belge kontrolüne veya muayeneye tabi tutulmadığı hattır.', 'Yeşil hat; eşyanın belge kontrolüne veya muayeneye tabi tutulmadığı hattır.']],
      ['Muayene neyi kapsar; tam ve kısmi muayene nedir?',
        'Kapların **cins, marka, numara ve adetleri**, vergiye esas **ağırlık ve ölçüler**, **GTİP, menşe ve kıymet** beyanının doğruluğu. Tam muayene eşyanın **tamamının**; kısmi muayene eşyayı **temsil edecek yeterli miktarın** fiziken kontrolüdür.', 'GY m.182/1–2', '',
        ['Muayene, kapların cins, marka, numara ve adetlerini, eşyanın vergiye esas olan ağırlık ve diğer ölçüleri ile gümrük tarife istatistik pozisyonu, menşe ve kıymetine ilişkin beyanın doğruluğunun tespitini kapsar.', 'Tam muayene, eşyanın tamamının; kısmi muayene, eşyayı temsil edecek şekilde yeterli miktarının fiziken kontrol edilmesidir.']],
      ['Tam veya kısmi muayene yönteminden hangisinin kullanılacağını kim belirler?',
        '**Bilgisayar sistemi**; sistemce belirlenmediğinde **muayene ile görevli memur** eşyanın **niteliğine göre** belirler.', 'GY m.182/1', '2023',
        ['Bu yöntemlerden hangisinin kullanılacağı bilgisayar sistemi tarafından belirlenir.', 'muayene şeklinin sistem tarafından belirlenmediği durumlarda bu husus muayene ile görevli memurlar tarafından eşyanın niteliğine göre belirlenir']],
      ['Tek kalemlik beyannamede kısmi muayene sonuçları nasıl uygulanır?',
        'Eşyanın **tümüne** uygulanır; beyan sahibi sonuçların kalan kısım için geçerli olmadığı düşüncesindeyse **tamamının muayenesini** talep edebilir.', 'GK m.67/1', '',
        ['muayene sonuçları söz konusu beyanname kapsamı eşyanın tümüne uygulanır', 'eşyanın tamamının muayenesini talep edebilir']],
      ['Birden fazla kalemli beyannamede bir kalemin eksiği diğerinin fazlasına mahsup edilebilir mi; hangi eşya bir kalem sayılır?',
        '**Mahsup edilemez**; her kalem **ayrı beyan** sayılır. Tarife pozisyonunun **aynı alt açılımında** bulunan ve **aynı kanuni veya tercihli vergi oranına** tabi eşya bir kalem sayılır.', 'GK m.67/2', '',
        ['her kaleme ilişkin bilgiler ayrı bir beyan sayılır. Bir kalemin eksik veya fazlası, diğer kalemin fazla veya eksiğine mahsup edilemez.', 'aynı tarife pozisyonunun alt açılımında bulunan ve aynı kanuni veya tercihli vergi oranına tabi olan eşya bir kalem sayılır']],
      ['Belge kontrolünde ciddi farklılık görüp muayeneyi gerekli gören memur ne yapar?',
        'Havale tarih ve saatinden itibaren **en geç yirmi dört saat** içinde **idare amirine** bildirir; amir uygun görürse beyanname **muayene memuruna** havale edilir.', 'GY m.183/2', '',
        ['sistem tarafından kendisine havale edilen tarih ve saat itibariyle en geç yirmidört saat içinde bu hususu idare amirine bildirir', 'ilgili amir beyannameyi muayene ile görevli memura havale eder']],
      ['Hangi eşya muayeneye tabi tutulmaz?',
        '**Cumhurbaşkanının zat ve ikametgâhı** için gelen eşya; gizliliği bildirilen GK m.167/3 eşyası; **yabancı devlet başkanları** ve ailesi/refakatçi memurlarının eşyası; yabancı **diplomatik temsilcilik ve konsoloslukların** resmi eşyası; gizli evrak içeren **mühürlü kurye çantaları**.', 'GY m.185/1', '',
        ['Cumhurbaşkanının zat ve ikametgâhı için gelen eşya,', 'Yabancı devlet başkanları ve aileleri efradı ile refakatlerinde memur olanların getirdikleri', 'İçinde gizli evrak bulunan mühürlü kurye çantaları.']],
      ['Eşyanın muayenesi nerede yapılır; başka yerde muayeneye kim izin verebilir?',
        'İdarece izin verilen yerlerde veya **antrepolarda**; beyan sahibinin talebiyle başka bir yerde muayeneye **gümrük idare amirleri** izin verebilir.', 'GY m.187/1', '',
        ['Eşyanın muayenesi, bunların gümrük idarelerince konulmasına izin verilen yerlerde veya antrepolarda yapılır.', 'gümrük idare amirleri beyan sahibinin talebi üzerine eşyanın, bu yerler dışında herhangi bir yerde muayene edilmesine izin verebilir']],
      ['Muayene ve numune alma giderlerini kim karşılar; beyan sahibi muayenede bulunmak zorunda mıdır?',
        'Giderler **beyan sahibine** aittir. Beyan sahibi muayenede **bulunabilir**; idare uygun görürse hazır bulunmasını veya **temsil edilmesini zorunlu** tutabilir.', 'GK m.66/2–3', '',
        ['numunelerin ambalajlanmasına ve gönderilmesine ilişkin giderleri beyan sahibi tarafından karşılanır', 'Beyan sahibi eşyanın muayenesi ve numune alınması sırasında hazır bulunabilir.', 'beyan sahibinin söz konusu muayenede veya numune alımında hazır bulunmasını veya temsil edilmesini zorunlu tutabilirler']],
      ['Muayenede bulunan eksiklik veya fazlalık eşyanın tabiatı icabı ek-11 oranlarında ise ne yapılır?',
        'İşlemler **tespit edilen miktar** üzerinden yapılır ve **ceza uygulanmaz**.', 'GY m.192/2', '',
        'işlemler gümrük idaresince tespit edilen miktar üzerinden yapılır ve ceza uygulanmaz'],
      ['Beyannameyi kontrol edenler, muayene ve ikinci muayeneyi yapanlar ile tahlili yapanlar nasıl sorumludur?',
        'Kontrol/muayeneden, vergilerin hesaplanmasından veya muafiyet uygulamasından duruma göre **tek başlarına veya müteselsilen** sorumludurlar; tahlili yapanlar GTİP belirlenmesinden **müteselsilen** sorumludur.', 'GK m.65/4; GY m.186/3', '',
        ['duruma göre tek başlarına veya müteselsilen sorumludurlar', 'Laboratuvar tahliline konu edilen eşyanın tahlilini gerçekleştirenler tahlil sonucuna bağlı olarak yapılan GTİP belirlenmesinden müteselsilen sorumludur.']],
    ] },
    { baslik: 'Diğer Kurumlarca Yapılan Kontroller (GY m.181)', sorular: [
      ['Diğer kurumların ithalat kontrolleri hangi aşamada yapılır?',
        'Risk durumuna göre TGB\'ye **girişte**, beyanname **tescili öncesinde** veya gümrük yükümlülüğünün **sona ermesinden sonra** — bu aşamalardan **yalnızca birinde** ve **gümrük idaresinin koordinasyonunda**.', 'GY m.181/1', '',
        'Türkiye Gümrük Bölgesine girişinde veya gümrük beyannamesinin tescil işlemi öncesinde ya da gümrük yükümlülüğünün sona ermesinden sonraki aşamalardan yalnızca birinde ve gümrük idaresinin koordinasyonunda yapılır'],
      ['Kontrolde insan, hayvan, bitki ve çevre sağlığı için tehlikeli/zararlı bulunan eşyaya ne yapılır?',
        'Yükümlüsünce **derhal yurtdışı** edilir; TGB\'de **imha edilemez** ve gümrük idaresine **terk edilemez**.', 'GY m.181/4-d', '',
        ['yükümlüsü tarafından derhal yurtdışı edilir', 'bu nitelikteki eşya Türkiye Gümrük Bölgesinde imha edilemeyeceği gibi gümrük idarelerine de terk edilemez']],
      ['Gümrük yükümlülüğü sona erdikten sonra kontrol edilecek eşya geçici depolama yeri veya antrepoda en fazla ne kadar tutulabilir?',
        'Yükümlülüklerin yerine getirildiği tarihi takip eden günden itibaren **en fazla üç iş günü**; bu sürede bildirim yapılmazsa talep üzerine gümrük gözetimi sona erdirilir.', 'GY m.181/5-b', '',
        ['yükümlülüklerin yerine getirildiği tarihi takip eden günden itibaren en fazla üç iş günü tutulabilir', 'ithalatçı veya temsilcisinin talebi doğrultusunda gümrük gözetimi sona erdirilir']],
      ['İthalinin yasak olduğu bildirilen GK m.235/1-a eşyası hangi süre içinde mahrecine iade veya transit edilir; edilmezse ne olur?',
        'Bildirimden itibaren **otuz gün** içinde; edilmezse ihraç kaydıyla satış veya imha yoluyla tasfiye edilmek üzere **gümrük idaresine terk** edilir.', 'GY m.181/11', '',
        ['ithalinin yasak olduğunun yükümlüye bildirildiği tarihten itibaren otuz gün içinde mahrecine iade', 'ihraç kaydıyla satış ya da masrafları sahibince karşılanmak koşuluyla imha suretiyle tasfiye edilmek üzere bulunduğu gümrük idaresine terk edilir']],
    ] },
    { baslik: 'Laboratuvar Tahlili ve Numune (GK m.66; GY m.196–203)', sorular: [
      ['Hangi hallerde laboratuvar tahlili yapılır?',
        '(a) TGTC **27** (bazı pozisyonlar hariç), **28, 29**. fasıllar ve 32.08, 34.03, 38.11, **39.01–39.15** pozisyonlarındaki eşyanın **dökme** gelmesi; (b) **ek-23** listesindeki eşya; (c) GTİP\'in muayene memurunca **tespit edilememesi**; (ç) işlenmiş tarım ürünlerinin **bileşim tablosundaki** yerinin belirlenmesi.', 'GY m.196/1', '2023',
        ['Türk Gümrük Tarife Cetvelinin 27 (27.01 ila 27.05, 2709.00.90 ve 27.16 hariç), 28, 29 uncu fasılları ve 32.08, 34.03 ve 38.11 tarife pozisyonu ile 39.01 ile başlayarak 39.15 dâhil olmak üzere bu tarife pozisyonlarında yer alan eşyanın dökme olarak gelmesi', '(a) bendinde belirtilen eşya dışında, ek-23\'te yer alan listede bulunması', 'eşyanın gümrük tarife istatistik pozisyonunun muayene ile görevli memurca tespitinin mümkün olmaması', 'İşlenmiş tarım ürünlerinin bileşim tablosundaki yerinin belirlenmesinin gerekmesi']],
      ['Daha önceki tahlil raporuna itibar edilerek yeniden tahlile gönderilmemesi için rapor en fazla ne kadar eski olabilir?',
        'Süreklilik arz eden, göndericisi, alıcısı ve menşei aynı eşyada tescil tarihi itibarıyla **en fazla bir yıl** önceki rapor (44 no.lu kutuda beyan); **kırmızı hat tam muayene** belirlenirse yararlanılamaz. OKS/YYS sahiplerinin dökme **39.01–39.15** ithalatında **en fazla altı ay**.', 'GY m.196/2-b, c', '',
        ['beyanname tescil tarihi itibarıyla en fazla bir yıl öncesine dayanan tahlil raporunun tarih ve sayısının beyannamenin 44 no.lu kutusunda beyan edilmesi halinde', 'beyanın kontrolü türünün kırmızı hat tam muayene olarak belirlenmesi halinde, yükümlünün bu kolaylıktan yararlanmasına izin verilmez', 'beyanname tescil tarihi itibariyle en fazla altı ay öncesine dayanan bir tahlil raporu ibraz edilmesi halinde buna itibar edilir']],
      ['Dökme gelen (m.196/1-a) eşyanın yükümlüsü OKS veya YYS sahibiyse eşya ne zaman teslim edilir?',
        'Tahlil sonuçları **alınmadan** teslim edilir; sonuç beyana aykırıysa beyannameye **meşruhat** düşülür, gerekirse tahakkuk yeni duruma göre yapılır.', 'GY m.196/6', '',
        ['yetkilendirilmiş yükümlü sertifikasına sahip olması halinde, tahlil sonuçları alınmadan eşya teslim edilir', 'sistem üzerinde beyannameye meşruhat düşülür']],
      ['Eşya rejim beyanından önce tahlile gönderilebilir mi; sonuçlara itiraz nasıl yapılır?',
        'Evet, yükümlünün başvurusuyla **rejim beyanından önce**; itiraz **GK m.243** kapsamında. Eşyanın aynı olduğu belirlenebiliyorsa beyan aşamasında **yeniden tahlile gönderilmez**.', 'GY m.196/A', '',
        ['yükümlünün ilgili gümrük idaresine başvurması halinde rejim beyanında bulunmadan önce tahlile gönderilir', 'Kanunun 243 üncü maddesi kapsamında tahlile itiraz edilebilir', 'bu eşya beyanın kontrolü ve muayene aşamasında yeniden tahlile gönderilmez']],
      ['Numuneler hangi miktarda alınır?',
        'En az **iki tahlile** yetecek miktarda: **petrol ürünleri ve alkollerde en az 1 litre**, diğer **sıvılarda en az ½ litre**, **tozlarda en az 250 gram**.', 'GY m.199/1-a', '',
        'en az iki tahlile yetecek miktarda (orijinal ambalajlı, kıymetli, az miktarda bulunan ve benzeri durumlardaki numuneler hariç, petrol ürünlerinde ve alkollerde en az 1 litre, diğer sıvı numunelerde en az ½ litre, toz örneklerde ise en az 250 gram)'],
      ['Gümrük idaresi alınan numuneler için tazminat öder mi; tahlil masrafı kime aittir?',
        '**Ödemez** (numune usulüne uygun alınmışsa); tahlil veya inceleme masrafı **beyan sahibine** aittir.', 'GK m.66/4; GY m.199/1-b', '',
        ['gümrük idareleri, numuneler karşılığında herhangi bir tazminat ödemekle yükümlü değildir', 'Gümrük idareleri tarafından gümrük laboratuvarlarında yapılacak veya hariçte yaptırılacak tahlil veya inceleme masrafı beyan sahibi tarafından karşılanır.']],
      ['Eşya sahibi veya temsilcisi gümrük laboratuvarına doğrudan numune gönderebilir mi?',
        '**Hayır**; laboratuvarlar da bunları **kabul edemez**.', 'GY m.200/1-ç', '2022',
        'Eşya sahibi veya temsilcileri gümrük beyanına konu eşyanın tahlili için Gümrük Laboratuvarlarına doğrudan numune gönderemeyecekleri gibi, laboratuvarlar da bunları kabul edemez.'],
      ['Tahlilden arta kalan numuneler hangi sürede alınmazsa gümrüğe terk edilmiş sayılır?',
        'Tahlil sonuçlarının ilgilisine bildirilmesinden sonra **bir ay** içinde.', 'GK m.66/5', '',
        'Tahlilden arta kalan numuneler, tahlil sonuçlarının ilgilisine bildirilmesinden sonra bir ay içinde alınmadığı takdirde gümrüğe terk edilmiş sayılır.'],
      ['Tahlil raporlarına itiraz süresinin başlangıcı nedir?',
        'Birinci tahlil sonuçlarının beyan sahibine **tebliğ edildiği tarih** (BİLGE "Tebliğ Tarihi" alanı).', 'GY m.203/1', '',
        ['Birinci tahlil sonuçları ilgili memurca beyan sahiplerine tebliğ ettirilerek', 'Bu tarih, tahlil raporlarına itiraz için başlangıç sayılır.']],
    ] },
  ],
  tuzaklar: [
    'Düzeltme yasağı (GK m.63): **muayene bildirimi**, **yanlışlığın tespiti** ve **teslim** sonrası. GY\'de eşik **kırmızı hattın belirlenmesi**dir. Teslimden sonra düzeltme yalnız **GK m.73/2** ile, tescilden itibaren **3 yıl** (DİR\'de daha uzun olabilir).',
    'İptal: yanlış rejim, başka eşya ve posta/hızlı kargo iadesi → tescilden itibaren **3 ay**; muayene bildirilmişse **sonuç alınmadan** iptal talebi kabul edilmez; teslimden sonra iptal yalnız **yönetmelikte belirlenen hallerde**.',
    'Süreler: antrepoda GOİK beyannamesi işlemleri **30 gün**; hızlı kargo incelemesi **6 saat**; arta kalan numune **1 ay**; belge kontrolünde muayene ihtiyacı amire **24 saat**; diğer kurum kontrolü **3 iş günü**; yasak eşyanın iadesi **30 gün**.',
    'Eksik beyan tamamlama (serbest dolaşım, ihracat, antrepo): **1 ay**, ek süre en fazla **3 ay**. Tamamlayıcı beyan: **izleyen ayın ilk 3 günü**; gemi/uçağa ihracat sayılan teslimlerde **ilk 7 iş günü**; e-irsaliyeli posta/kargo ihracatında beyanı takiben **7 iş günü**; kıymet unsurunda izleyen ayın **26\'sı** akşamı.',
    'GY m.180\'de sayılan kontrol türleri **dört** hattır: **kırmızı** (muayene + belge), **sarı** (yalnız belge), **mavi** (OKS ihracatı, kontrol çıkıştan sonra), **yeşil** (kontrol yok); başka hat sayılmamıştır.',
    'Beyanname yerine kullanılan belgeler (TIR, ATA, CPD karnesi, kumanya listesi, özel fatura, elçilik/kurye mektubu, sözlü beyan formu vb.) **beyanname mahiyetinde değildir**. **CIM/CMR/konşimento** taşıma belgesidir; **menşe şahadetnamesi** ve **A.TR** bu sayımda yer almaz.',
    'Basitleştirilmiş usulde statü: **eksik beyan** → YYS veya OKS; **kayıt yoluyla** → yalnız **YYS** (+ ihracat hariç teminat); **ticari/idari belge** → statü **aranmaz**. Antrepoda **F tipi** → basitleştirilmiş usul yok; **B tipi** → eksik belge + ticari/idari belge; **D tipi** → kayıt yoluyla.',
    'Tutar/süre ayrımı: ticari eşyada sözlü beyan sınırı **1000 Avro**; ticari/idari belge usulünde **CIF 500 Avro** ve **6 ay** geçerlilik; yurt dışına gidenlerin eşyası **2 ay önce / 6 ay sonra**; önceki tahlil raporuna itibar **1 yıl** (OKS/YYS dökme plastikte **6 ay**).',
  ],
};
