// 41. Konu — Sınır Ticareti (kaynak: 41-sınır ticareti.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '41',
  konu: 'Sınır Ticareti',
  kaynak: '41-sınır ticareti.docx (GK m.172; Sınır Ticaretinin Düzenlenmesine İlişkin Karar (Karar Sayısı: 4874) m.1–20; Sınır Ticaret Merkezlerinin Fiziki Olarak Düzenlenmesi, Eşya ve Stok Kontrollerinin Yapılması ile Bu Merkezlere Giriş ve Çıkışlara İlişkin Usul ve Esaslara Dair Yönetmelik m.5–13; Sınır Ticaretinin Uygulanmasına İlişkin Tebliğ (İhracat: 2016/11) m.5–16)',
  bolumler: [
    { baslik: 'Kanun Hükmü (GK m.172)', sorular: [
      ['Sınır ticaretinin kapsamını belirlemeye, sınır ticaret merkezlerini kurmaya ve tek ve maktu tarife uygulamaya kim yetkilidir?',
        '**Cumhurbaşkanı**; tek ve maktu tarife, ilgili kanunlardaki **azami hadleri geçmemek** şartıyla uygulanır.', 'GK m.172/1', '2024',
        ['yapılacak sınır ticaretinin kapsamını belirlemeye, sınır ticareti yapılacak sınır ticaret merkezlerinin kurulmasına', 'ilgili kanunlarda belirtilen azami hadleri geçmemek şartıyla tek ve maktu bir tarife uygulamaya Cumhurbaşkanı']],
      ['Sınır ticaret merkezleri gümrük işlemlerinin yürütülmesinde nasıl addedilir?',
        '**Türkiye Cumhuriyeti Gümrük Bölgesi dışında** addedilir.', 'GK m.172/2', '',
        'Sınır ticaret merkezleri, gümrük işlemlerinin yürütülmesinde Türkiye Cumhuriyeti Gümrük Bölgesi dışında addedilir.'],
      ['Sınır ticaretine ilişkin gümrük işlemlerini kim belirler?',
        '**Müsteşarlık.**', 'GK m.172/3', '',
        'Sınır ticaretine ilişkin gümrük işlemleri Müsteşarlıkça belirlenir.'],
    ] },
    { baslik: 'Amaç, Kapsam ve Tanımlar (Karar (4874) m.1–4)', sorular: [
      ['Sınır Ticaretinin Düzenlenmesine İlişkin Kararın amacı nedir?',
        'Ülkemizin **Doğu ve Güneydoğu Anadolu** coğrafi bölgelerine **kara sınırı** bulunan komşu ülkeler ile sınır ticareti kapsamındaki ihracat ve ithalat kurallarını belirlemek.', 'Karar (4874) m.1', '',
        'ülkemizin Doğu ve Güneydoğu Anadolu coğrafi bölgelerine kara sınırı bulunan komşu ülkeler ile sınır ticareti kapsamında yapılacak ihracat ve ithalata ilişkin kuralların belirlenmesidir'],
      ['Karar hangi sınır illerinden yapılacak sınır ticaretini kapsar?',
        '**13 il:** Artvin, Ardahan, Kars, Iğdır, Ağrı, Van, Hakkâri, Şırnak, Mardin, Şanlıurfa, Gaziantep, Kilis ve Hatay.', 'Karar (4874) m.2', '',
        'Artvin, Ardahan, Kars, Iğdır, Ağrı, Van, Hakkâri, Şırnak, Mardin, Şanlıurfa, Gaziantep, Kilis ve Hatay sınır illerimizden yapılacak sınır ticaretine ilişkin kuralları kapsar'],
      ['Karara göre "esnaf" kimdir?',
        'Karar kapsamındaki illerde **en az bir yıldır** yerleşik olarak faaliyette bulunan ve **Esnaf ve Sanatkârlar Siciline** kayıtlı **gerçek kişiler**.', 'Karar (4874) m.4/1-b', '',
        'Bu Karar kapsamındaki illerde en az bir yıldır yerleşik olarak faaliyette bulunan ve Esnaf ve Sanatkârlar Siciline kayıtlı olan gerçek kişileri'],
      ['Karara göre "tacir" tanımında hangi şartlar aranır; hangi tüzel kişiler hariç tutulmuştur?',
        'İşletme/şirket merkezi kapsamdaki illerde olan ve **en az bir yıldır** faaliyette bulunan kişiler; **vakıf, dernek ve belediyeler**, diğer **kamu kurum ve kuruluşları** ile bunların kurdukları veya ortak oldukları şirketler **hariç**.', 'Karar (4874) m.4/1-h', '',
        ['ticari işletme merkezleri bu Karar kapsamındaki illerde olan ve en az bir yıldır faaliyette bulunan gerçek kişiler', '(vakıf, dernek ve belediyeler ile diğer kamu kurum ve kuruluşları ve bunların kurdukları ya da ortak oldukları şirketler hariç)']],
      ['İl Değerlendirme Komisyonuna kim başkanlık eder ve kimlerden oluşur?',
        '**Vali veya Vali Yardımcısı** başkanlığında; İl Jandarma Komutanlığı ya da İl Emniyet Müdürlüğü temsilcisi, İl Defterdarı, **Gümrük İl Müdürü**, Sanayi ve Teknoloji İl Müdürü, Ticaret İl Müdürü, İl Tarım ve Orman Müdürü, İl Ticaret (ve Sanayi) Odası ile Esnaf ve Sanatkârlar Odaları Birliği temsilcileri.', 'Karar (4874) m.4/1-c', '',
        ['Bu Karar kapsamındaki illerin Vali veya Vali Yardımcısı başkanlığında İl Jandarma Komutanlığı ya da İl Emniyet Müdürlüğü temsilcisi, İl Defterdarı, Gümrük İl Müdürü', 'İl Ticaret Odası veya İl Ticaret ve Sanayi Odası ile ilde bulunan Esnaf ve Sanatkârlar Odaları Birliği temsilcilerinden oluşan komisyonu']],
      ['Sınır Ticareti Belgesi ve İthalat Uygunluk Belgesi ne için düzenlenir?',
        '**Sınır Ticareti Belgesi (Ek: 2):** ihracat ve ithalat ile Sınır Ticaret Merkezinde **mağaza kiralanması** için; **İthalat Uygunluk Belgesi (Ek: 1):** ilgili gümrük kapısından ve/veya Sınır Ticaret Merkezinden **ithalat** yapılması için.', 'Karar (4874) m.4/1-d, g', '',
        ['Sınır ticareti kapsamında ihracat ve ithalat yapılması ile Sınır Ticaret Merkezinde mağaza kiralanması için düzenlenen Ek: 2\'deki belgeyi', 'İlgili gümrük kapısından ve/veya Sınır Ticaret Merkezinden ithalat yapılması için düzenlenen Ek: 1\'deki belgeyi']],
    ] },
    { baslik: 'İl Değerlendirme Komisyonu ve Sınır Ticareti Belgesi (Karar (4874) m.5–6, 8/6; Tebliğ (İhracat: 2016/11) m.6–8)', sorular: [
      ['İl Değerlendirme Komisyonu nasıl toplanır ve karar verir?',
        'Üye tam sayısının **salt çoğunluğu** ile toplanır, katılımcıların **oy çokluğu** ile karar verir.', 'Karar (4874) m.5', '',
        'İl Değerlendirme Komisyonu üye tam sayısının salt çoğunluğu ile toplanır ve katılımcıların oy çokluğu ile karar verir.'],
      ['Komisyondaki temsilciler hangi işlere ilişkin toplantılara katılamaz?',
        'Kendilerini, eşlerini, **üçüncü dereceye kadar** kan ve sihri hısımlarını ve evlatlıklarını ilgilendiren işlere; bu işlerde **oy da kullanamazlar**.', 'Karar (4874) m.5', '',
        'Komisyonda yer alan temsilciler kendilerini, eşlerini ve üçüncü dereceye kadar kan ve sihri hısımlarını ve evlatlıklarını ilgilendiren işlere ilişkin toplantılara katılamazlar ve oy kullanamazlar.'],
      ['İl Değerlendirme Komisyonunun sekretarya hizmetlerini kim yürütür; sekretaryayı kim denetler?',
        '**İl Ticaret Odası** veya **İl Ticaret ve Sanayi Odası**; sekretaryanın faaliyetleri **Valilikçe** denetlenir.', 'Karar (4874) m.5; Tebliğ (İhracat: 2016/11) m.6/1, 5', '',
        ['İl Değerlendirme Komisyonunun sekretarya hizmetleri İl Ticaret Odası veya İl Ticaret ve Sanayi Odası tarafından yerine getirilir.', 'Sekretaryanın faaliyetleri ve işlemleri Valilikçe denetlenir.']],
      ['Esnaf ve tacirin hangi işlemler için Sınır Ticareti Belgesine sahip olması şarttır?',
        '**İthalat, ihracat** ve **mağaza kiralama**.', 'Karar (4874) m.6/1', '',
        'Esnaf ve tacirin sınır ticareti kapsamında ithalat ve ihracat yapabilmesi ve mağaza kiralayabilmesi için Sınır Ticareti Belgesine sahip olması şarttır.'],
      ['Sınır Ticareti Belgesi başvurusu nereye yapılır ve belgeyi kim düzenler?',
        'Başvuru **İl Ticaret Odası / İl Ticaret ve Sanayi Odasına**; Komisyonca uygun görülenlere belgeyi **Valilik** düzenler.', 'Karar (4874) m.6/2', '',
        'Sınır Ticareti Belgesi başvuruları İl Ticaret Odası veya İl Ticaret ve Sanayi Odasına yapılır. Başvuruları İl Değerlendirme Komisyonu tarafından uygun görülenlere Valilikçe Sınır Ticareti Belgesi düzenlenir.'],
      ['Sınır Ticareti Belgesinin geçerlik süresi nedir, nasıl uzatılır?',
        '**Üç yıl**; süre bitmeden başvuru ve Komisyonun uygun görmesiyle **Valilikçe vize** edilerek **bir yıllık** sürelerle uzatılabilir.', 'Karar (4874) m.6/3', '',
        ['Sınır Ticareti Belgesi üç yıl süreyle geçerlidir.', 'belgenin geçerliliği ilgili Valilikçe vize edilmek suretiyle bir yıllık sürelerle uzatılabilir']],
      ['Sınır Ticareti Belgesi ve İthalat Uygunluk Belgesi devredilebilir mi?',
        '**Hiçbir şekilde devredilemez**; devir tespitinde belge **Valilikçe iptal** edilir ve ilgili ile sahibi/ortağı/yöneticisi olduğu firmalar adına **bir daha düzenlenmez**.', 'Karar (4874) m.6/4, 8/6', '',
        ['Sınır Ticareti Belgesi hiçbir şekilde devredilemez.', 'İthalat Uygunluk Belgesi hiçbir şekilde devredilemez.', 'firmalar adına bir daha Sınır Ticareti Belgesi düzenlenmez']],
      ['Hangi kanunlardaki suçlardan kesinleşmiş mahkûmiyeti olanlara Sınır Ticareti Belgesi düzenlenmez?',
        '**3713** Terörle Mücadele, **6415** Terörizmin Finansmanı, **5607** Kaçakçılıkla Mücadele, **5237** TCK, **6136** Ateşli Silahlar, **5682** Pasaport, **213** VUK ve **1567** sayılı Kanun; **cezasını çekmiş veya affa uğramış olsa dahi**.', 'Karar (4874) m.6/5', '',
        ['3713 sayılı Terörle Mücadele Kanunu', '5607 sayılı Kaçakçılıkla Mücadele Kanunu', 'cezalarını çekmiş ya da affa uğramış dahi olsalar Sınır Ticareti Belgesi düzenlenmez']],
      ['Tebliğe göre Sınır Ticareti Belgesi ve İthalat Uygunluk Belgesi başvuruları hangi sürelerde işlem görür?',
        'Sekretarya başvuruyu **en geç beş iş günü** içinde Komisyona iletir; Komisyon **en geç on iş günü** içinde değerlendirir.', 'Tebliğ (İhracat: 2016/11) m.7/2–3, 8/2–3', '',
        ['Sekretarya tarafından en geç beş iş günü içinde İl Değerlendirme Komisyonuna iletilir', 'İl Değerlendirme Komisyonu tarafından en geç on iş günü içinde yapılan değerlendirme sonucunda', 'en geç on iş günü içinde değerlendirilerek sonuçlandırılır']],
      ['Hizmet sektöründe faaliyet gösteren esnaf veya tacir adına Sınır Ticareti Belgesi düzenlenir mi?',
        '**Hayır**, düzenlenmez.', 'Tebliğ (İhracat: 2016/11) m.7/4', '',
        'Hizmet sektöründe faaliyet gösteren esnaf veya tacir adına Sınır Ticareti Belgesi düzenlenmez.'],
    ] },
    { baslik: 'İthalat Değer Limitleri ve İthalat Uygunluk Belgesi (Karar (4874) m.7–8; Tebliğ (İhracat: 2016/11) m.8–10)', sorular: [
      ['Her bir komşu ülke için yıllık ithalat değer limiti ne kadardır?',
        '**75 milyon $ tarım + 75 milyon $ sanayi** = yıllık toplam **150 milyon ABD Doları** kadar; daha az da belirlenebilir.', 'Karar (4874) m.7/1', '',
        ['75 milyon ABD Doları kadar tarım, 75 milyon ABD Doları kadar sanayi ürünleri olmak üzere yıllık toplam 150 milyon ABD Doları kadardır', 'Her bir komşu ülke için ithalat değer limiti 150 milyon ABD Dolarından daha az olarak da belirlenebilir.']],
      ['İthalat değer limitleri sınır illerine nasıl tahsis edilir; tahsis oranları değiştirilebilir mi?',
        'İllere **nüfusları oranında** paylaştırılır; oranlar **yıl içinde değiştirilemez** ve **sonraki yıla devredilemez**.', 'Karar (4874) m.7/1', '',
        ['ilgili sınır illerine nüfusları oranında paylaştırılması suretiyle yapılır', 'Tahsis edilen ithalat değer limiti oranları yıl içinde değiştirilemez ve bir sonraki yıla devredilemez.']],
      ['İthalat değer limitleri Valiliklere ne zaman bildirilir, esnaf ve tacire ne zaman duyurulur?',
        'Bakanlıkça **her yıl Aralık ayının sonuna kadar** Valiliklere; Valilikler bildirimi takip eden **beş iş günü** içinde oda ve birlikler aracılığıyla duyurur.', 'Karar (4874) m.7/2; Tebliğ (İhracat: 2016/11) m.9', '',
        ['Bakanlık tarafından her yıl Aralık ayının sonuna kadar ilgili Valiliklere bildirilir', 'Valilikler, Bakanlık tarafından yapılan bildirimi takip eden beş iş günü içinde']],
      ['Her bir ürün için düzenlenecek İthalat Uygunluk Belgelerinin toplam değeri hangi sınırı geçemez?',
        'İl bazında tarım ve sanayi sektörü için belirlenen yıllık ithalat değer limitinin **%5\'ini**.', 'Karar (4874) m.7/3; Tebliğ (İhracat: 2016/11) m.8/4', '',
        'ilgili sınır ili bazında tarım ve sanayi sektörü için belirlenen yıllık ithalat değer limitinin %5\'ini geçemez'],
      ['İthalat Uygunluk Belgesine kimler, nereye başvurur; belge nasıl düzenlenir?',
        'Sınır Ticareti Belgesini haiz esnaf ve tacir ile **mağaza kiralayanlar**; **İl Ticaret Odası / İl Ticaret ve Sanayi Odasına**; **her bir ürün için ayrı** belge yine bu odaca düzenlenir.', 'Karar (4874) m.8/1–2', '',
        ['Sınır Ticareti Belgesini haiz esnaf ve tacir ile mağaza kiralayanlar tarafından İthalat Uygunluk Belgesine ilişkin başvurular İl Ticaret Odası veya İl Ticaret ve Sanayi Odasına yapılır.', 'her bir ürün için ayrı bir İthalat Uygunluk Belgesi, İl Ticaret Odası veya İl Ticaret ve Sanayi Odasınca düzenlenir']],
      ['İthalat Uygunluk Belgesini kimler imzalar?',
        '**Ticaret İl Müdürü** ile İl Ticaret (ve Sanayi) Odasının **en az genel sekreter** düzeyindeki yetkilisi; belge oda tarafından mühürlenir.', 'Karar (4874) m.8/3', '',
        'İthalat Uygunluk Belgesi; Ticaret İl Müdürü ile İl Ticaret Odası veya İl Ticaret ve Sanayi Odasının en az genel sekreter düzeyindeki yetkilisi tarafından imzalanır'],
      ['İthalat Uygunluk Belgesinin geçerlik süresi nedir?',
        'Düzenlendiği tarihten itibaren **90 gün**; **uzatılamaz**. Tarım ürünlerinde (hasat dönemi, sonraki yıla sarkma) **daha kısa** süreli düzenlenebilir.', 'Karar (4874) m.8/4', '',
        ['İthalat Uygunluk Belgesinin geçerlik süresi düzenlendiği tarihten itibaren 90 gün olup, bu süre uzatılamaz.', 'bu belge daha kısa süreler için düzenlenebilir']],
      ['İthalat Uygunluk Belgesi süresinin bir kısmı mevsimsel ithalat kısıtlaması dönemine girerse bakiye süre ne olur?',
        'Bakiye süre **kazanılmış hak teşkil etmez**.', 'Karar (4874) m.8/5', '',
        'tarım ürünleri ile ilgili mevsimsel ithalat kısıtlamaları dönemine girmesi halinde bakiye süre kazanılmış hak teşkil etmez'],
      ['İthalat Uygunluk Belgesi kaç nüsha düzenlenir ve nüshalar kime verilir?',
        '**Üç nüsha:** birincisi **Sekretaryada** kalır, ikincisi ilgili **gümrük idaresine** gönderilir, üçüncüsü işlem kaydı düşülmek üzere **esnaf veya tacire** verilir.', 'Tebliğ (İhracat: 2016/11) m.8/5', '',
        ['İthalat Uygunluk Belgesi üç nüsha olarak düzenlenir.', 'Birinci nüsha Sekretaryada muhafaza edilir, ikinci nüsha ilgili gümrük idaresine gönderilir']],
      ['İl Değerlendirme Komisyonu İthalat Uygunluk Belgesi başvurularını değerlendirirken neleri esas alır?',
        'Vergi ve SGK prim borcu, **son bir yıllık** ciro ve önceki ithalat verileri; Bakanlıkça belirlenen **birim fiyatlar**; il **limitlerinin aşılmaması**; ürünün **komşu ülkede üretilip üretilmediği**; **mümkün olduğunca çok** esnaf ve tacirin yararlanması.', 'Tebliğ (İhracat: 2016/11) m.10/1', '',
        ['Talep sahiplerinin vergi ve sosyal güvenlik prim borçlarının olup olmadığı, son bir yıla ait işletme ciroları', 'İthalata konu ürünün ilgili komşu ülkede üretiminin veya imalatının yapılıp yapılmadığı', 'Uygulamadan mümkün olduğunca çok sayıda esnaf ve tacirin yararlanabilmesi']],
    ] },
    { baslik: 'İthalat ve İhracat İşlemleri (Karar (4874) m.9–12; Tebliğ (İhracat: 2016/11) m.11–12)', sorular: [
      ['Esnaf, tacir veya mağaza kiralayan sınır ticareti kapsamında ne kadar ithalat yapabilir?',
        '**30 gün içerisinde en fazla 75.000 ABD Doları** karşılığı Türk Lirası değerinde.', 'Karar (4874) m.9/1', '',
        'ilgili gümrük kapısı veya Sınır Ticaret Merkezinden 30 gün içerisinde en fazla 75.000 ABD Doları karşılığı Türk Lirası değerinde eşya ithal edilebilir'],
      ['Sınır ticareti ithalatında hangi vergi uygulanır ve nasıl hesaplanır?',
        '**Tek ve maktu vergi**; **KDV ile ÖTV oranları toplamı** olarak hesaplanır.', 'Karar (4874) m.9/2', '',
        'İthalatta tek ve maktu vergi uygulanır. Tek ve maktu vergi; katma değer vergisi ile özel tüketim vergisi oranları toplamı olarak hesaplanır.'],
      ['İthalatta menşe yönünden ne aranır; üçüncü ülke menşeli ürün ithal edilebilir mi?',
        'Eşyanın ilgili **sınır ülkesinde üretildiğine** dair o ülkenin yetkili makamlarınca düzenlenen **menşe şahadetnamesi**; **üçüncü ülke menşeli** ürünlerin ithalatına **izin verilmez**.', 'Karar (4874) m.9/3', '',
        ['eşyanın ilgili sınır ülkesinde üretildiğine veya imal edildiğine dair ithalatın yapılacağı ülkenin yetkili makamlarınca düzenlenen menşe şahadetnamesi ilgili gümrüklerce aranır', 'Üçüncü ülke menşeli ürünlerin bu Karar kapsamında ithalatına izin verilmez.']],
      ['Sanayi ürünlerinin ithalatında menşe şahadetnamesinde ayrıca ne aranır?',
        'İlgili komşu ülkedeki **Türkiye Cumhuriyeti Büyükelçiliği veya Konsolosluğunun tasdiki**.', 'Tebliğ (İhracat: 2016/11) m.12/4', '',
        'Sanayi ürünlerinin ithalatında ibraz edilen menşe şahadetnamesinde, ilgili komşu ülkedeki Türkiye Cumhuriyeti Büyükelçiliği veya Konsolosluğunun tasdiki gümrük idaresince aranır.'],
      ['Sınır ticaretiyle ithal edilen ürünler nerede satılabilir; satış belgeleri ne kadar saklanır?',
        'Sadece **Karar kapsamındaki (yetkili sınır) illerde**, buralarda yerleşik esnaf/tacire; satış faturasına **İthalat Uygunluk Belgesinin tarih ve sayısı** yazılır, fatura ve nakliye belgeleri **en az üç yıl** saklanır.', 'Karar (4874) m.9/4; Tebliğ (İhracat: 2016/11) m.12/6', '',
        ['Bu Karar kapsamında ithal edilen ürünler sadece 2 nci maddede belirtilen illerde satılabilir.', 'birer örnekleri ilgili esnaf veya tacir tarafından en az üç yıl süreyle muhafaza edilir']],
      ['Sınır ticareti kapsamında ihracatta gümrük idaresine ibrazı zorunlu belgeler nelerdir?',
        'Eşyanın **faturası** ile **ihracatçı birliğince onaylanmış gümrük beyannamesi** (Tebliğe göre ayrıca **Sınır Ticareti Belgesi**).', 'Karar (4874) m.10; Tebliğ (İhracat: 2016/11) m.12/7', '',
        ['ihracı yapılacak eşyanın faturası ile ihracatçı birliğince onaylanmış gümrük beyannamesinin yetkili gümrük idaresine tevdi edilmesi zorunludur', 'İhracat işlemlerinde, Sınır Ticareti Belgesi ile ihracı yapılacak eşyanın faturası']],
      ['Hangi ürünler sınır ticaretine konu edilemez?',
        'İhracı/ithali **yasak** veya belli kuruluşlara bırakılmış maddeler; **damping, sübvansiyon ve korunma önlemlerine** tabi ürünler; **petrol ve petrol ürünleri**; 5201 sayılı Kanun kapsamında kontrole tabi ürünler; sivil kullanım amaçlı patlayıcılar ve **amonyum nitrat** benzeri maddeler.', 'Karar (4874) m.11/1', '',
        ['damping ve sübvansiyona karşı önlemler ile korunma önlemlerine tabi ürünler; petrol ve petrol ürünleri', 'amonyum nitrat ve benzeri içerikli patlayıcı yapımında kullanılabilecek maddeler sınır ticaretine konu edilemez']],
      ['Canlı hayvan ve hayvansal ürünlerin sınır ticareti yapılabilir mi?',
        '**Hayır**; Tarım ve Orman Bakanlığınca insan, bitki ve hayvan sağlığı açısından **risk** teşkil ettiği belirlenen ürünlerin ticareti de yapılamaz.', 'Karar (4874) m.11/2', '',
        'Bu Karar kapsamında canlı hayvan ve hayvansal ürünlerin ticareti ile Tarım ve Orman Bakanlığı tarafından insan, bitki ve hayvan sağlığı açısından risk teşkil ettiği belirlenen ürünlerin ticareti yapılamaz.'],
      ['Tebliğe göre yerli üretimin korunması amacıyla hangi ürünlerin sınır ticaretiyle ithalatına izin verilmez?',
        '**Çay, şeker, fındık ve antepfıstığı** ile Bakanlıkça ithalatı durdurulan diğer ürünler; ayrıca izne tabi **veteriner ilaçları** ve veteriner biyolojik ürünleri.', 'Tebliğ (İhracat: 2016/11) m.11', '',
        ['çay, şeker, fındık ve antepfıstığı ile Bakanlık tarafından ithalatı durdurulan diğer ürünlerin sınır ticareti yoluyla ithalatına izin verilmez', 'veteriner ilaçları, veteriner biyolojik ürünleri']],
      ['Sınır ticaretiyle ithal ve ihraç edilen ürünler Teknik Düzenlemeler Rejimi denetimine tabi midir; ürün güvenliğinden kim sorumludur?',
        'Teknik Düzenlemeler Rejimi Kararına istinaden yapılan denetimlerden **muaftır**; ürün güvenliği 7223 sayılı Kanun uyarınca **ithalatçının** sorumluluğundadır. Tarım ve Orman Bakanlığı denetimine tabi ürünler ise **genel hükümlere** tabidir.', 'Karar (4874) m.12', '',
        ['Teknik Düzenlemeler Rejimi Kararına istinaden yapılan ihracat ve ithalat denetimlerinden muaftır', 'Teknik Düzenlemeler Kanunu hükümleri uyarınca ithalatçının sorumluluğundadır', 'Tarım ve Orman Bakanlığının denetimine tabi ürünlerin bu Karar kapsamında ithalatı genel hükümlere tabidir.']],
      ['Sınır ticareti ithalatında gümrük idaresince hangi hususlar aranır?',
        '**Gümrük beyannamesi** düzenlenir; **İthalat Uygunluk Belgesi** ile belgenin tarih ve sayısının **beyanname üzerine kaydedilmiş** olması ve **menşe şahadetnamesi** aranır.', 'Tebliğ (İhracat: 2016/11) m.12/1–4', '',
        ['Sınır ticareti kapsamındaki ithalat ve ihracat işlemleri için gümrük beyannamesi düzenlenir.', 'İthalat işlemlerinde İthalat Uygunluk Belgesi ilgili gümrük idaresince aranır.', 'İthalat Uygunluk Belgesinin tarih ve sayısının gümrük beyannamesi üzerine kaydedildiği hususu']],
    ] },
    { baslik: 'Yetkili Gümrük Kapıları ve Sınır Ticaret Merkezleri (Karar (4874) m.13–16)', sorular: [
      ['İran ve Irak ile sınır ticaretine yetkili gümrük kapıları hangileridir?',
        'İran: **Gürbulak** (Iğdır, Ağrı), **Kapıköy** (Van), **Esendere** (Hakkari; tabloda "Esedere"); Irak: **Habur** (Hakkari, Şırnak), **Derecik** ve **Üzümlü** (Hakkari).', 'Karar (4874) m.13', '',
        ['7 | IĞDIR | GÜRBULAK | İRAN', '9 | VAN | KAPIKÖY | İRAN', '10 | HAKKARİ | ESEDERE | İRAN', '11 | HAKKARİ | HABUR | IRAK', '12 | HAKKARİ | DERECİK | IRAK', '13 | HAKKARİ | ÜZÜMLÜ | IRAK', '14 | ŞIRNAK | HABUR | IRAK']],
      ['Gürcistan, Nahçıvan ve Suriye ile sınır ticaretine yetkili gümrük kapıları hangileridir?',
        'Gürcistan: **Sarp** (Artvin), **Türkgözü** (Ardahan), **Aktaş** (Ardahan, Kars); Nahçıvan: **Dilucu** (Kars, Iğdır); Suriye: **Nusaybin, Akçakale, Karkamış, Öncüpınar, Cilvegözü**.', 'Karar (4874) m.13', '',
        ['1 | ARTVİN | SARP | GÜRCİSTAN', '2 | ARDAHAN | TÜRKGÖZÜ | GÜRCİSTAN', '5 | KARS | AKTAŞ | GÜRCİSTAN', '6 | IĞDIR | DİLUCU | NAHÇİVAN', '15 | MARDİN | NUSAYBİN | SURİYE', '19 | HATAY | CİLVEGÖZÜ | SURİYE']],
      ['Karara göre Sınır Ticaret Merkezleri hangileridir?',
        '**Sarısu** (Ağrı–İran), **Esendere** (Hakkâri–İran), **Kapıköy** (Van–İran), **Dilucu** (Iğdır–Nahçıvan).', 'Karar (4874) m.14', '',
        ['1 | AĞRI | SARISU | IRAN', '2 | HAKKÂRİ | ESENDERE | IRAN', '3 | VAN | KAPIKOY | IRAN', '4 | IGDIR | DİLUCU | NAHÇIVAN']],
      ['Yeni Sınır Ticaret Merkezi kurulması ve mevcut merkezin kapatılması için kim teklifte bulunur?',
        'Kurma ve gümrük idaresini yetkilendirme: **İl Valisi**; kapatma ve yetkiyi kaldırma: **Strateji ve Bütçe Başkanlığı** ya da **İçişleri** veya **Milli Savunma** Bakanlıkları. Teklif **Bakanlığa** yapılır.', 'Karar (4874) m.15/1', '',
        ['gümrük idaresinin bulunduğu sınır kapılarında yeni Sınır Ticaret Merkezi kurulması için ilgili İl Valisi tarafından', 'Strateji ve Bütçe Başkanlığı ya da İçişleri veya Milli Savunma Bakanlıkları tarafından Bakanlığa teklifte bulunulur']],
      ['Başkanlık ve Bakanlıkların görüşlerinin tümü olumlu ise kurma/kapatma ve yetkilendirme talepleri kime sunulur?',
        '**Cumhurbaşkanına.**', 'Karar (4874) m.15/3', '',
        'bu hususlar Cumhurbaşkanına sunulur'],
      ['Altyapısı yetersiz veya güvenliği sağlanamayan Sınır Ticaret Merkezinin faaliyetine en fazla ne kadar ara verilebilir?',
        'Bakanlıkça geçici olarak; süre **altı ayı geçemez**. Eksiklikler giderilmezse, giderilinceye kadar faaliyete izin verilmez.', 'Karar (4874) m.15/4', '',
        'Sınır Ticaret Merkezinin faaliyetine Bakanlıkça geçici bir süre ara verilebilir. Bu süre altı ayı geçemez.'],
      ['Sınır Ticaret Merkezinin inşası, güvenliği ve işletilmesi kim tarafından yerine getirilir?',
        'İnşa, altyapı, bakım-onarım ve güvenlik **Valiliklerce**; işletme ve mağaza kiralama, Valilikçe hazırlanıp **Bakanlıkça uygun görülen yönergeler** çerçevesinde **Valilikçe**. Fiziki düzenleme ve stok kontrolü usulleri **Bakanlıkça** tespit edilir.', 'Karar (4874) m.16/1–3', '',
        ['insan ve eşya giriş ve çıkışlarının denetim altına alınması ilgili Valiliklerce yerine getirilir', 'ilgili Valilikçe hazırlanan ve Bakanlıkça uygun görülen yönergeler çerçevesinde ilgili Valilikçe yerine getirilir']],
    ] },
    { baslik: 'Müeyyideler ve Çeşitli Hükümler (Karar (4874) m.17–20)', sorular: [
      ['Gerçek dışı menşe belgesi ibraz edilerek ithal edildiği tespit edilen ürünlerde ne yapılır?',
        'Gümrük vergisi, eş etkili vergi, diğer vergi ve mali yüklerin **tamamı 6183** sayılı Kanuna göre tahsil edilir ve **GK m.234/1-a** çerçevesinde para cezası uygulanır.', 'Karar (4874) m.17/1', '',
        ['6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanun hükümlerine göre ilgililerden tahsil edilir', '4458 sayılı Kanunun 234 üncü maddesinin birinci fıkrasının (a) bendi hükmü çerçevesinde para cezası uygulanır']],
      ['Sınır ticaretiyle ithal edilip kapsam dışındaki illerde satıldığı tespit edilen ürünlerde ne yapılır?',
        '**İthalat Rejimi Kararı** uyarınca alınması gereken gümrük vergisi, eş etkili vergi ve ek mali yüklerin **tamamı** 6183 sayılı Kanuna göre tahsil edilir.', 'Karar (4874) m.17/2', '',
        'İthalat Rejimi Kararı uyarınca alınması gereken gümrük vergisi, eş etkili vergi ve ek mali yüklerin tamamı 6183 sayılı Kanun hükümlerine göre ilgiliden tahsil edilir'],
      ['İthalat Uygunluk Belgesindeki miktardan fazla ithalat yapılırsa ne olur?',
        'Fazladan ithal edilen ürünler için **gümrük mevzuatı** uyarınca işlem yapılır; ayrıca İthalat Uygunluk Belgeleri **Valilikçe iptal** edilir ve bir daha düzenlenmez. Fiil 5607 sayılı Kanunda suçsa **5607** uygulanır.', 'Karar (4874) m.17/3–4', '',
        ['fazladan ithal edilen ürünler için gümrük mevzuatı uyarınca işlem yapılır', 'İthalat Uygunluk Belgeleri ilgili Valilikçe iptal edilir', '5607 sayılı Kanunda suç olarak tanımlananlar hakkında aynı Kanun hükümlerine göre işlem yapılır']],
      ['Karar kapsamında kimler ithalat ve ihracat yapamaz?',
        '**Valilikler, belediyeler ve il özel idareleri tarafından** veya bunlar adına kurulan **vakıf, dernek ve firmalar**.', 'Karar (4874) m.18/4', '',
        'Valilikler, belediyeler ve il özel idareleri tarafından veya bunlar adına kurulan vakıf, dernek ve firmalar bu Karar kapsamında ithalat ve ihracat yapamazlar.'],
      ['Sınır ticareti kapsamında transit ticaret ve dahilde işleme rejimi işlemleri yapılabilir mi?',
        '**Hayır**, yapılamaz.', 'Karar (4874) m.18/5', '',
        'Sınır ticareti kapsamında, transit ticaret ile Dâhilde İşleme Rejimi kapsamında ithalat ve ihracat işlemleri yapılamaz.'],
      ['Sınır ticaretinin amacına uygun yürütülmesinden kim sorumludur; istatistikler nasıl bildirilir?',
        '**İlgili Valiler** sorumludur. Gümrük idareleri istatistikleri **müteakip ayın ilk haftası** içinde Valiliklere; Valilikler **Ek: 3** formla bir sonraki ayın ilk haftasında **Bakanlığa** gönderir.', 'Karar (4874) m.18/6–8', '',
        ['Sınır ticaretinin amacına uygun olarak yürütülmesi ve izlenmesinden ilgili Valiler sorumludur.', 'müteakip ayın ilk haftası içinde aylık olarak ilgili Valiliklere bildirir', 'bir sonraki ayın ilk haftasında Bakanlığa gönderir']],
      ['Karar kapsamındaki eşyaya ithalatta gözetim mevzuatı uygulanır mı?',
        '**Hayır**; Kararda yer almayan hususlarda gümrük mevzuatı ve ithalat-ihracat rejimi uygulanır, ancak **gözetim** hükümleri uygulanmaz.', 'Karar (4874) m.19', '',
        'Ancak, ithalatta gözetim uygulanmasına ilişkin mevzuat hükümleri, bu Karar kapsamındaki eşya için uygulanmaz.'],
      ['Sınır ticaretinde eşya ve ülke bazında ithalat ve ihracatı sınırlandırmaya veya durdurmaya kim yetkilidir?',
        '**Bakanlık** (Ticaret Bakanlığı).', 'Karar (4874) m.4/1-a, 20; Tebliğ (İhracat: 2016/11) m.16', '',
        'eşya ve ülke bazında ithalatı ve ihracatı sınırlandırmaya veya durdurmaya Bakanlık yetkilidir'],
    ] },
    { baslik: 'Sınır Ticaret Merkezleri Yönetmeliği (Yönetmelik (STM) m.5–13)', sorular: [
      ['Sınır Ticaret Merkezinde kurulacak kantarın asgari tartma kapasitesi nedir; nitelik ve şartlara uygunluğu kim denetler?',
        'Asgari **45 ton**; şartlara uygunluğu merkezin bağlı olduğu **gümrük idareleri** denetler.', 'Yönetmelik (STM) m.5', '',
        ['Asgari 45 ton tartma kapasitesine sahip kantar kurulması', 'Sınır Ticaret Merkezinin bağlı olduğu Gümrük idarelerince denetlenir']],
      ['Sınır Ticaret Merkezi işleticisi ve mağazaların mali sorumluluğu hangi hallerde söz konusu olmaz?',
        'Eşyanın **tabiatından doğan kayıp ve fireler** ile kusurlarından kaynaklanmayan telef, kayıp, **doğal afet, yangın, su basması, çalınma** vb. eksikliklerin gümrük idaresine **ispatı ve idarece kabulü** halinde.', 'Yönetmelik (STM) m.6/1-b', '',
        ['eşyanın tabiatından doğan kayıp ve fireler ile Sınır Ticaret Merkezi işleticilerinin ve mağazalarının kusur ve hatalarından meydana gelmeyen telef, kayıp, doğal afet, yangın, su basması, çalınma', 'gümrük idaresine ispat edilmesi ve bunun idarece de kabul edilmesi halinde sorumluluk söz konusu olmaz']],
      ['Sınır Ticaret Merkezi işleticisi ve mağaza işleticisi hangi defter ve belgeleri tutmak zorundadır?',
        'Sınır Ticaret Merkezi **eşya giriş-çıkış defteri**, **ihracat** ve **ithalat** gümrük beyannameleri, **satış belgesi**, **aylık satış listesi**.', 'Yönetmelik (STM) m.7/1', '',
        ['Sınır Ticaret Merkezi eşya giriş-çıkış defteri', 'İthalata ilişkin gümrük beyannamesi', 'Aylık satış listesi']],
      ['Sınır Ticaret Merkezi defter ve belgeleri kaç yıl saklanır; süre ne zaman başlar?',
        '**Beş yıl**; defterlerde **tasdik edildiği**, belgelerde **düzenlendiği yılın sonundan** itibaren.', 'Yönetmelik (STM) m.7/4–5', '',
        ['İlgili kişiler bu defter ve belgeleri gümrük kontrolü amacıyla beş yıl süre ile saklamak zorundadırlar.', 'Bu defter ve belgelerin saklama süresi defterlerin tasdik edildiği, belgelerin ise düzenlendiği yılın sonundan itibaren işlemeye başlar.']],
      ['Eşya giriş-çıkış defterini kim tasdik eder; deftere kayıtlar en geç ne zaman yapılır?',
        'Satış mağazasının bulunduğu yerdeki **noter**; kayıtlar **en geç üç iş günü** içinde.', 'Yönetmelik (STM) m.8/4, 10', '',
        ['satış mağazasının bulunduğu yerdeki noter veya noterlik görevini ifa ile mükellef olanlar tarafından tasdik edilir', 'Deftere kayıtların en geç üç iş günü içinde yapılması zorunludur.']],
      ['Satış belgesi kaç örnek düzenlenir; aylık satış listesi ne zamana kadar verilir?',
        'Satış belgesi **iki örnek**; aylık satış listesi **biri asıl üç örnek**, aslı **müteakip ayın üçüncü günü akşamına** kadar bağlı **gümrük müdürlüğüne** verilir.', 'Yönetmelik (STM) m.9/3, 10/3', '',
        ['Satış belgesi seri/sıra numarasına göre iki örnek olarak düzenlenir.', 'Aylık satış listeleri biri asıl üç örnek düzenlenir ve listenin aslı en geç müteakip ayın üçüncü günü akşamına kadar işleticinin/mağazanın bağlı bulunduğu gümrük müdürlüğüne verilir.']],
      ['Sınır Ticaret Merkezine ithal veya ihraç hükmüyle konulan eşyanın kalış süresi nedir; aşılırsa ne olur?',
        '**3 ay**; zorunlu nedenler süre bitmeden belgelendirilirse gümrük idaresi **ek süre** verebilir. 3 ayda çıkarılmaz ve ek süre de istenmezse **GK m.241/1** uygulanır.', 'Yönetmelik (STM) m.12', '',
        ['satış veya sergi amaçlı olarak kalış süresi 3 ay ile sınırlıdır', 'ilgili gümrük idaresi tarafından ek süre verilebilir', 'Gümrük Kanununun 241 inci maddesinin birinci fıkrası hükmü uygulanır']],
      ['Sınır Ticaret Merkezinde yapılan sayımda noksan ve fazla çıkan eşyada ne yapılır?',
        'Noksan ithal eşyası: **GK m.236**\'ya göre vergi ve cezalar işletici veya mağazadan; noksan ihraç eşyası: istisnadan yararlanan eşyanın **KDV**\'si tahsil edilir. Fazla: kayda alınır; geçerli nedene kanaat getirilmezse **GK m.236/2**.', 'Yönetmelik (STM) m.13/2–3', '',
        ['noksan çıkan ithal eşyasının Gümrük Kanununun 236 ncı maddesine göre gümrük vergileri ve cezaları, duruma göre işletici veya mağazalardan tahsil edilir', 'katma değer vergisi ve varsa özel tüketim vergisi istisnasından yararlanan eşyanın katma değer vergisi tahsil edilir', 'Gümrük Kanununun 236 ncı maddesinin ikinci fıkrasına göre işlem yapılır']],
      ['Sayım heyetine kim başkanlık eder; 3 aydan fazla kalmış ihraç eşyası nasıl işlem görür?',
        'Gümrük müdürünce tayin edilen **en az şef** seviyesinde memur; 3 aydan fazla kalan ihraç eşyası **geri gelen eşya** hükümlerine tabi tutulur.', 'Yönetmelik (STM) m.13/4–5', '',
        ['ilgili gümrük müdürü tarafından tayin edilecek en az şef seviyesinde bir memur başkanlık eder', 'gümrük mevzuatı doğrultusunda geri gelen eşya hükümlerine tabi tutulur']],
    ] },
  ],
  tuzaklar: [
    'Yetki ayrımı: kapsam, merkez kurulması ve tek ve maktu tarife → **Cumhurbaşkanı** (GK m.172); gümrük işlemleri → **Müsteşarlık**; koordinasyon, ithalat-ihracatı sınırlandırma/durdurma → **Bakanlık** (Karar m.20); STM kurma/kapatma → teklif Bakanlığa, olumlu görüşlerle **Cumhurbaşkanına** sunulur.',
    'Sınır ticaret merkezleri gümrük işlemlerinde **TGB dışında** addedilir.',
    'Belge süreleri: Sınır Ticareti Belgesi **3 yıl** (Valilik vizesiyle **birer yıl** uzatma); İthalat Uygunluk Belgesi **90 gün, uzatılamaz**. İkisi de **devredilemez**.',
    'Belgeyi düzenleyen: Sınır Ticareti Belgesi → **Valilik**; İthalat Uygunluk Belgesi → **İl Ticaret (ve Sanayi) Odası** (Ticaret İl Müdürü + en az genel sekreter imzası). Başvurular her ikisinde de odaya (Sekretarya).',
    'Limitler: ülke başına **75 + 75 = 150 milyon $**; illere **nüfus oranında**; yıl içinde **değiştirilemez, devredilemez**; ürün başına belgeler toplamı limitin **%5**\'i; kişi başı **30 günde 75.000 $**.',
    'Tek ve maktu vergi = **KDV + ÖTV oranları toplamı**. Gözetim **uygulanmaz**; Teknik Düzenlemeler Rejimi denetiminden **muaf**; **transit ticaret** ve **DİR** yapılamaz; **üçüncü ülke menşeli** ürün ithal edilemez.',
    'Sayılar: STM\'de kalış **3 ay**; STM defterleri **5 yıl**, satış faturası (Tebliğ) **en az 3 yıl**; deftere kayıt **3 iş günü**; aylık satış listesi **müteakip ayın 3. günü**; kantar **45 ton**; geçici ara verme **en fazla 6 ay**.',
    'Tebliğ süreleri: Sekretarya → Komisyon **5 iş günü**, Komisyon değerlendirmesi **10 iş günü**; Valilik duyurusu **5 iş günü**; limit bildirimi **Aralık sonu**.',
  ],
};
