// 6. Konu — Karar (kaynak: 6-KARAR.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar ('' = sorulmamış), kanıt (kaynaktan birebir kesit veya kesit listesi)]
module.exports = {
  no: '06',
  konu: 'Karar',
  kaynak: '6-KARAR.docx (4458 sayılı Gümrük Kanunu m.6–7; Gümrük Yönetmeliği m.27 ve m.586)',
  bolumler: [
    { baslik: 'Karar Talebi ve Karar Süresi (GK m.6; GY m.27/1)', sorular: [
      ['Gümrük idaresinden gümrük mevzuatının uygulanmasına ilişkin karar isteme hakkı kime tanınmıştır?',
        'Gerekli bilgi ve belgelerle başvuran **her kişi**ye.', 'GY m.27/1', '',
        'Gerekli bilgi ve belgelerle başvuran her kişi gümrük mevzuatının uygulanmasına ilişkin bir karar vermesini gümrük idaresinden isteyebilir'],
      ['Karar talep eden kişinin ibraz yükümlülüğü nedir?',
        'Kararın verilebilmesi için gerekli **bütün bilgi ve belgeleri** gümrük idarelerine ibraz etmek zorundadır.', 'GK m.6/1', '',
        'kararın verilebilmesi için gerekli bütün bilgi ve belgeleri söz konusu idarelere ibraz etmek zorundadır'],
      ['Karar alınması talebi hangi şekilde yapılmalıdır?',
        '**Yazılı** olarak.', 'GK m.6/2', '',
        'Karar alınması talebinin yazılı olarak yapılması gerekir'],
      ['Gümrük idareleri karar talebini ne kadar sürede karara bağlar?',
        'Başvurunun kendilerine **ulaştığı tarihten** itibaren **otuz gün** içinde.', 'GK m.6/2', '',
        'başvurunun kendilerine ulaştığı tarihten itibaren otuz gün içinde karar alırlar'],
      ['Verilen kararlar başvuru sahibine nasıl bildirilir?',
        '**Yazılı olarak tebliğ** edilir.', 'GK m.6/2', '',
        'Verilen kararlar başvuru sahibine yazılı olarak tebliğ edilir'],
      ['Gümrük idaresi otuz günlük karar süresine uyamazsa ne yapar?',
        'Süre aşılabilir; idare, süre **dolmadan önce** başvuru sahibine süre aşımını haklı kılan **gerekçeleri** ve karar için gerekli gördüğü **ek süreyi** belirterek bilgi verir.', 'GK m.6/2', '',
        ['gümrük idareleri tarafından bu süreye uyulması mümkün değilse, belirtilen süre aşılabilir',
         'yukarıda belirlenen sürenin dolmasından önce başvuru sahibine süre aşımını haklı kılan gerekçeler ile talep hakkında karar vermek için gerekli gördükleri ek süreyi de belirterek bilgi verirler']],
      ['Başvurunun reddine veya muhatabın aleyhine verilen yazılı kararlar nasıl alınır?',
        '**Gerekçeli** olarak ve Onikinci Kısımda belirtilen şekilde **itiraz yolu açık** olmak üzere; bu hususlar kararda belirtilir.', 'GK m.6/3', '',
        'gerek başvuruların reddine ve gerekse muhatabı kişinin aleyhine olarak verilen yazılı kararlar, Onikinci Kısımda belirtilen şekilde itiraz yolu açık olmak üzere gerekçeli olarak alınır ve bu hususlar kararda belirtilir'],
      ['Alınan kararlar gümrük idarelerince ne zaman uygulanır?',
        '**Derhal.**', 'GK m.6/4', '',
        'Alınan kararlar gümrük idareleri tarafından derhal uygulanır'],
    ] },
    { baslik: 'Lehe Kararın İptali ve Değiştirilmesi (GK m.7; GY m.27/2–4)', sorular: [
      ['Gümrük idaresinin ilgilinin lehine olan kararı hangi hâllerin bir arada bulunması durumunda iptal edilir?',
        '**Üç hâl birlikte:** (a) kararın yanlış veya eksik bilgilere dayanılarak verilmesi; (b) başvuru sahibinin bu yanlışlık veya eksikliği bilmesi veya bilmesi gerekmesi; (c) kararın doğru veya tam bilgilere dayanılarak verilmesinin mümkün olmamasının tespiti.', 'GK m.7/1', '',
        ['Gümrük idaresinin ilgilinin lehine olan kararları aşağıdaki hallerin bir arada bulunması durumunda iptal edilir',
         'Kararın yanlış veya eksik bilgilere dayanılarak verilmesi halinde',
         'Başvuru sahibinin bu yanlışlık veya eksikliği bilmesi veya bilmesi gerektiği hallerde',
         'Kararın doğru veya tam bilgilere dayanılarak verilmesinin mümkün olmamasının tespiti halinde']],
      ['İlgilinin lehine olan karar hangi hâllerde değiştirilir veya iptal edilebilir?',
        '(a) Karara esas teşkil eden bir veya birden fazla **koşulun gerçekleşmemiş veya gerçekleşemez** olması; (b) lehe kararda öngörülen bir **yükümlülüğe ilgilinin uymaması**.', 'GK m.7/2; GY m.27/2', '',
        ['ilgilinin lehine olan karar değiştirilir veya iptal edilebilir',
         'Karara esas teşkil eden bir veya birden fazla koşulun gerçekleşmemiş veya gerçekleşemez olması',
         'Lehine olan bir kararda öngörülen bir yükümlülüğe ilgilinin uymaması halinde']],
      ['Kararın iptali muhatabına nasıl bildirilir?',
        '**Tebliğ** edilir.', 'GK m.7/3', '',
        'Kararın iptali, muhatabına tebliğ edilir'],
      ['GK m.7/1 uyarınca yapılan iptal işlemi ne zaman yürürlüğe girer?',
        'İptal kararının **verildiği tarihten** itibaren.', 'GK m.7/4', '',
        '1 inci fıkra hükümlerine göre kararın iptal işlemi iptal kararının verildiği tarihten'],
      ['GK m.7/2 uyarınca verilen iptal veya değiştirme kararı ne zaman yürürlüğe girer?',
        '**Tebliğ tarihinden** itibaren.', 'GK m.7/4', '',
        '2 nci fıkra hükümlerine göre verilen iptal veya değiştirme kararı tebliğ tarihinden itibaren yürürlüğe girer'],
      ['Kararın iptalinin veya değiştirilmesinin yürürlük tarihi ertelenebilir mi?',
        'Evet; karar muhatabının **yasal çıkarlarının** gerektirdiği **istisnai hâllerde**, yönetmelikle belirlenen koşullar altında ertelenebilir.', 'GK m.7/4', '',
        'karar muhatabının yasal çıkarlarının gerektirdiği istisnai hallerde, kararın iptalinin veya değiştirilmesinin yürürlük tarihi yönetmelikle belirlenen koşullar altında ertelenebilir'],
      ['Değiştirme veya iptal kararları hangi eşyaya uygulanmaz?',
        'Bu kararların yürürlüğe girdiği tarihte, iptal edilen ya da değiştirilen kararlar uyarınca bir gümrük rejimine **tabi tutulmaya başlanmış** eşyaya.', 'GY m.27/3', '',
        'Değiştirme ya da iptal kararları, bu kararların yürürlüğe girdiği tarihte, iptal edilen ya da değiştirilen kararlar uyarınca bir gümrük rejimine tabi tutulmaya başlanmış eşya için uygulanmaz'],
      ['Rejime tabi tutulmaya başlanmış bu eşya için gümrük idaresi ne isteyebilir?',
        '**Belirlenecek bir dönem** içinde eşyanın **gümrükçe onaylanmış bir işleme ya da kullanıma** tabi tutulmasını.', 'GY m.27/4', '',
        'gümrük idareleri belirlenecek bir dönem içinde bu eşyanın gümrükçe onaylanmış bir işleme ya da kullanıma tabi tutulmasını isteyebilir'],
    ] },
    { baslik: 'İtirazların Karara Bağlanması (GY m.586)', sorular: [
      ['İtirazlar ne kadar sürede karara bağlanarak ilgili kişiye tebliğ edilir?',
        '**Otuz gün** içinde.', 'GY m.586', '2023',
        'otuz gün içinde karara bağlanarak ilgili kişiye tebliğ edilir'],
      ['İtirazın karara bağlanmasında neler incelenir?',
        'Anlaşmazlığa konu **beyanname** ve her türlü belge ile eşyadan alınacak **örnek**; örnek alınamıyorsa eşyanın kendisi veya **fotoğraf, katalog, prospektüs** gibi belgeler; gerekirse ilgili gümrük idaresinin **mütalaası** da alınır.', 'GY m.586', '',
        'anlaşmazlığa konu beyanname ve sair her türlü belge ile eşyadan alınacak örnek, örnek alınması mümkün olmayan hallerde eşyanın kendisi veya fotoğraf, katalog, prospektüs gibi eşyayı görmeden fikir verecek diğer belgelerin incelenmesi veya gerek duyulması halinde ilgili gümrük idaresinin mütalaası da alınmak suretiyle'],
      ['İtiraz otuz gün içinde karara bağlanamazsa hangi hüküm uygulanır?',
        'Kanunun **6. maddesinin ikinci fıkrası**: süre aşılabilir; süre dolmadan gerekçeler ve gerekli görülen ek süre başvuru sahibine bildirilir.', 'GY m.586; GK m.6/2', '',
        ['Otuz gün içerisinde karar alınamadığı durumlarda Kanunun 6 ncı maddesinin ikinci fıkrası uygulanır',
         'sürenin dolmasından önce başvuru sahibine süre aşımını haklı kılan gerekçeler ile talep hakkında karar vermek için gerekli gördükleri ek süreyi de belirterek bilgi verirler']],
    ] },
  ],
  tuzaklar: [
    '**İptal edilir ↔ iptal edilebilir:** GK m.7/1\'deki **üç hâl bir arada** bulunursa lehe karar **iptal edilir**; m.7/2\'deki hâllerde (koşulun gerçekleşmemesi/gerçekleşemez olması veya yükümlülüğe uyulmaması) karar **değiştirilir veya iptal edilebilir**.',
    '**Yürürlük:** m.7/1 iptali → iptal kararının **verildiği tarih**; m.7/2 iptal/değiştirme → **tebliğ tarihi**. İstisnai hâllerde yürürlük, yönetmelikle belirlenen koşullarla **ertelenebilir**.',
    '**Otuz gün** hem karar talebinde (başvurunun idareye **ulaştığı tarihten**) hem itirazın karara bağlanmasında geçerlidir; itirazda süre aşılırsa da **GK m.6/2** uygulanır.',
    '**Süre aşımı bildirimi** süre **dolmadan önce** yapılır ve hem **gerekçeleri** hem **ek süreyi** içerir.',
    '**Talep yazılı, karar yazılı tebliğ, uygulama derhal;** ret ve aleyhe kararlar **gerekçeli** ve **itiraz yolu açık** olarak alınır.',
    'Değiştirme/iptal kararları, yürürlük tarihinde rejime **tabi tutulmaya başlanmış** eşyaya uygulanmaz; idare bu eşya için belirlenecek dönemde **GOİK** isteyebilir.',
  ],
};
