// 32. Konu — Dahilde İşleme Rejimi (kaynak: 32-DAHİLDE İŞLEME.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '32',
  konu: 'Dahilde İşleme Rejimi',
  kaynak: '32-DAHİLDE İŞLEME.docx (GK m.108–122; GY m.349–369; Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) m.1–48)',
  bolumler: [
    { baslik: 'Rejimin Tanımı, Sistemler ve Eşdeğer Eşya (GK m.108–109, 122; GY m.349, 352, 355; Tebliğ m.3–4, 6)', sorular: [
      ['Gümrük Kanununa göre şartlı muafiyet sistemi nedir?',
        'Serbest dolaşımda olmayan eşyanın, işlem görmüş ürün üretiminde kullanılıp yeniden ihracı amacıyla gümrük vergileri ve TPÖ\'ye tabi tutulmaksızın **vergileri teminata bağlanarak geçici ithali**; ürün ihraç edilince **teminat iade** olunur (vergi tahsil edilmez).', 'GK m.108/1', '2021, 2023, 2024, 2025',
        ['Serbest dolaşımda olmayan eşya, işlem görmüş ürünlerin üretiminde kullanılmasından sonra Türkiye Gümrük Bölgesinden yeniden ihraç edilmesi amacıyla, gümrük vergileri ve ticaret politikası önlemlerine tabi tutulmaksızın ve vergileri teminata bağlanmak suretiyle', 'Eşyanın işlem görmüş ürünler şeklinde ihracı halinde, teminat iade olunur. Eşyanın bu şekilde dahilde işleme rejiminden yararlanmasına şartlı muafiyet sistemi denir.']],
      ['Gümrük Kanununa göre geri ödeme sistemi nedir?',
        '**Serbest dolaşımdaki** eşyanın işlem görmüş ürün üretiminde kullanılıp ihracında, serbest dolaşıma girişte **tahsil edilmiş ithalat vergilerinin geri verilmesi**.', 'GK m.108/2', '2024',
        ['bu eşyanın serbest dolaşıma girişi esnasında tahsil edilmiş olan ithalat vergileri, dahilde işleme rejimi kapsamında geri verilir', 'Eşyanın bu şekilde dahilde işleme rejiminden yararlanmasına geri ödeme sistemi denir.']],
      ['DİR Tebliğine göre dahilde işleme tedbirleri hangi sistemlerden oluşur?',
        '**I- Şartlı Muafiyet Sistemi** ve **II- Geri Ödeme Sistemi** (iki sistem).', 'Tebliğ (İhracat 2006/12) m.4', '2025',
        'Dahilde işleme tedbirleri: I- Şartlı Muafiyet Sistemi, II- Geri Ödeme Sistemi\'nden oluşur.'],
      ['Gümrük Yönetmeliğine göre dahilde işleme rejimi nasıl tanımlanır?',
        'Yeniden ihraç amacıyla serbest dolaşımda bulunmayan eşyanın vergileri **teminata bağlanarak geçici ithal edildiği** veya **serbest dolaşıma girişinin yapıldığı** ve ihracat gerçekleşince **teminatın veya alınan vergilerin geri verildiği** rejim.', 'GY m.349/1', '2023',
        'serbest dolaşımda bulunmayan eşyanın vergileri teminata bağlanmak suretiyle geçici ithal edildiği veya serbest dolaşıma girişinin yapıldığı ve ihracatın gerçekleşmesi halinde teminatın veya alınan vergilerin geri verildiği bir rejimdir'],
      ['Gümrük Kanununa göre "işleme faaliyetleri" nelerdir?',
        '(a) Montaj, kurma ve birleştirme dahil **işçiliğe tabi tutma**, (b) **işleme**, (c) yenileme ve düzenli hale getirme dahil **tamir**, (d) ürün içinde bulunmayan ama üretimi sağlayan/kolaylaştıran **önceden belirlenmiş bazı eşyanın kullanılması**.', 'GK m.108/3', '2025',
        ['Eşyanın montajı, kurulması ve diğer eşya ile birleştirilmesi dahil olmak üzere işçiliğe tabi tutulması,', 'b) Eşyanın işlenmesi,', 'Eşyanın yenilenmesi ve düzenli hale getirilmesi dahil olmak üzere tamir edilmesi,', 'işlem görmüş ürünler içinde bulunmayan ancak, bu ürünlerin üretilmesini sağlayan veya kolaylaştıran önceden belirlenmiş bazı eşyanın kullanılması']],
      ['İşlem görmüş ürün, asıl işlem görmüş ürün ve ikincil işlem görmüş ürün nedir?',
        'İşlem görmüş ürün: işleme sonucu elde edilen **tüm ürünler**; asıl: rejim kapsamında **elde edilmesi amaçlanan** ürün; ikincil: asıl ürün **dışındaki** ürünler.', 'GK m.108/4–6', '',
        ['"İşlem görmüş ürün" deyimi, işleme faaliyetleri sonucunda elde edilen tüm ürünler anlamına gelir.', '"Asıl işlem görmüş ürün" deyimi, dahilde işleme rejimi kapsamında elde edilmesi amaçlanan ürün anlamına gelir.', '"İkincil işlem görmüş ürün" deyimi, işleme faaliyetleri sonucunda elde edilen asıl işlem görmüş ürün dışındaki ürünler anlamına gelir.']],
      ['Gümrük Kanununa göre eşdeğer eşya nedir?',
        'İşlem görmüş ürünlerin imali için **ithal eşyasının yerine kullanılan serbest dolaşımdaki eşya**.', 'GK m.108/7', '2023',
        '"Eşdeğer eşya" deyimi, işlem görmüş ürünlerin imali için ithal eşyasının yerine kullanılan serbest dolaşımda bulunan eşya anlamına gelir.'],
      ['Eşdeğer eşya ile ithal eşyasının GTİP bakımından aynılığı hangi basamakta aranır?',
        'GY: **8-12\'li bazda** aynı GTİP + aynı ticari kalite ve teknik özellik; Tebliğ: **asgari 8\'li bazda**; **tarım ürünlerinde** tespit **münhasıran 12\'li bazda** yapılır.', 'GY m.349/2-a, 352/2; Tebliğ (İhracat 2006/12) m.3/j, 6/1', '',
        ['ithal eşyası ile sekiz-oniki\'li bazda gümrük tarife istatistik pozisyonu aynı olan', 'ithal eşyası ile asgari 8 (sekiz)\'li bazda gümrük tarife istatistik pozisyonu', 'münhasıran 12 (oniki)\'libazda gümrük tarife istatistik pozisyonuna göre yapılır']],
      ['Gümrük Kanunu eşdeğer eşya kullanımında neye izin verir; bu kullanıma hangi müdahaleler yapılabilir?',
        'Ürünlerin eşdeğer eşyadan elde edilmesine veya ithal eşyası serbest dolaşıma girmeden **önce ihracına** izin verilebilir; kullanıma **kolaylaştırma, yasaklama veya kısıtlama** getirilebilir (Tebliğe göre **Bakanlık (İhracat GM)**, süresiz veya dönemsel).', 'GK m.109; Tebliğ (İhracat 2006/12) m.6/2', '',
        ['İşlem görmüş ürünlerin eşdeğer eşyadan elde edilmesine veya eşdeğer eşyadan elde edilen işlem görmüş ürünlerin ithal eşyasının serbest dolaşıma girmesinden önce Türkiye Gümrük Bölgesi dışına ihraç edilmesine izin verilebilir.', 'yasaklama veya kısıtlama getirilebilir', 'Bakanlıkça (İhracat Genel Müdürlüğü), eşdeğer eşyanın kullanımına süresiz veya dönemsel olarak yasaklama veya kısıtlama getirilebilir.']],
      ['Eşdeğer eşya ithal eşyasından daha kaliteli olabilir mi?',
        'Kural: **aynı özellik ve nitelik**; ancak belirlenecek özel hallerde **daha kaliteli veya daha ileri imalat aşamasında** olmasına izin verilebilir.', 'GK m.109', '',
        'Eşdeğer eşyanın, ithal eşyası ile aynı özellik ve aynı nitelikleri taşıması gerekir. Ancak, belirlenecek özel hallerde eşdeğer eşyanın ithal eşyasından daha kaliteli veya daha ileri bir imalat aşamasında olmasına izin verilebilir.'],
      ['Eşdeğer eşyadan üretim yapıldığında eşyanın gümrük statüsü nasıl değerlendirilir?',
        'İthal eşyası **eşdeğer eşya**, eşdeğer eşya **ithal eşyası** sayılır; kapatma beyanının kabulünde eşdeğer eşya **serbest dolaşımda olmayan**, ithal eşyası **serbest dolaşımda** kabul edilir.', 'GK m.109; GY m.355/2', '',
        ['gümrük işlemlerinde ithal eşyası eşdeğer eşya, eşdeğer eşya ise ithal eşya olarak değerlendirilir', 'Rejimin kapatılmasına yönelik beyanın kabulünde, eşdeğer eşya ve bunlardan elde edilen ürünler serbest dolaşımda olmayan eşya, ithal eşyası serbest dolaşımda bulunan eşya kabul edilir.']],
      ['İhracat vergisine tabi eşdeğer eşyadan elde edilen ürünlerin ihracında ihracat vergisi nasıl uygulanır?',
        'Şartlı muafiyette eşdeğer eşya **ihracat vergilerinden muaf** tutulur; henüz ithal edilmemiş eşya yerine (önceden ihracat) ise ithalatın süresinde yapılmasına karşılık **ihracat vergileri kadar teminat** alınır.', 'GK m.109, 122', '',
        ['ithal eşyasının süresi içinde ithal edilmesine karşılık olarak izin hak sahibinden, ihracat vergileri kadar teminat alınır', 'söz konusu eşdeğer eşya ihracat vergilerinden muaf tutulur']],
      ['"Önceden ihracat" ile "önceden ithalat" nedir?',
        'Önceden ihracat: şartlı muafiyette ithal eşyası sisteme girmeden **önce eşdeğer eşyadan üretilen ürünün ihracı**, ithal eşyasının **sonradan ithali**; önceden ithalat: ürünün ihracından önce girdilerin **ithali**.', 'GY m.349/2-b; Tebliğ (İhracat 2006/12) m.3/bb–cc', '',
        ['ithal eşyasının bu sisteme tabi tutulmadan önce eşdeğer eşyadan üretilen işlem görmüş ürünlerin Türk Gümrük Bölgesinden ihracına ve ithal eşyasının sonradan ithaline imkan veren uygulamayı', 'Önceden ithalat: İşlem görmüş ürünün ihracından önce bu ürünün elde edilmesinde kullanılacak eşyanın ithalini']],
    ] },
    { baslik: 'İznin Verilmesi (GK m.110; GY m.350, 352)', sorular: [
      ['Dahilde işleme izni kimin talebi üzerine verilir?',
        'GK **m.80** çerçevesinde, işleme faaliyetlerini **yapan veya yaptıran** kişinin talebi üzerine.', 'GK m.110/1', '',
        'Dahilde işleme izni, 80 inci madde çerçevesinde, işleme faaliyetlerini yapan veya yaptıran kişinin talebi üzerine verilebilir.'],
      ['Dahilde işleme izni hangi şartlarla verilebilir?',
        '(a) **TGB\'de yerleşik** kişilere; (b) ithal eşyasının işlem görmüş ürünlerde **mevcudiyetinin** (veya eşdeğer eşya koşullarına uyulduğunun) **tespit edilebildiği** hallerde; (c) TGB\'deki **üreticilerin temel ekonomik çıkarları olumsuz etkilenmeden** ihracata en iyi imkânın yaratıldığı hallerde.', 'GK m.110/2', '2025',
        ['Türkiye Gümrük Bölgesinde yerleşik kişilere,', 'ithal eşyasının işlem görmüş ürünler içerisinde mevcudiyetinin veya 109 uncu madde kapsamında eşdeğer eşya için konulmuş koşullara uyulduğunun tespit edilebildiği hallerde', 'Türkiye Gümrük Bölgesindeki üreticilerin temel ekonomik çıkarlarının olumsuz etkilenmemesi şartıyla']],
      ['İzin şartlarından (c) bendindeki (ekonomik koşullar) halleri belirlemeye kim yetkilidir?',
        '**Cumhurbaşkanı.**', 'GK m.110/2', '',
        '(c) bendinde belirtilen halleri belirlemeye Cumhurbaşkanı[107] yetkilidir.'],
      ['TGB dışında yerleşik kişilere dahilde işleme izni verilebilir mi?',
        'Evet; yalnızca **ticari nitelikte olmayan** dahilde işleme amaçlı ithalat için.', 'GK m.110/3', '2024',
        'Ticari nitelikte olmayan dahilde işleme amaçlı ithalat için Türkiye Gümrük Bölgesi dışında yerleşik kişilere de izin verilmesi mümkündür.'],
      ['Gümrük Yönetmeliğine göre şartlı muafiyet ve geri ödeme sistemi izinleri hangi durumda verilir?',
        'Şartlı muafiyet: asıl ürünlerin **ihraç edilmesi amacının** bulunduğu durumlarda **işlenecek bütün eşya** için; geri ödeme: esas ürünlerin **ihraç edilmesi imkânının** bulunduğu ve GK **m.117** şartlarına uyulduğu hallerde.', 'GY m.350/1', '',
        ['Şartlı muafiyet sisteminin kullanılması izni, işlem görmüş asıl ürünlerin ihraç edilmesi amacının bulunduğu durumlarda, işlenecek bütün eşya için', 'Geri ödeme sisteminin kullanılması izni, işlem görmüş esas ürünlerin ihraç edilmesi imkanının bulunduğu ve Kanunun 117 nci maddesinde belirtilen şartlara uyulması halinde']],
      ['Üretimi sağlayan/kolaylaştıran eşya (GK m.108/3-d) kapsamında hangileri için izin verilmez?',
        'Deneme veya kusur tespiti dışındaki **yakıt ve enerji kaynakları**; deneme, ayar veya geri alma dışındaki **yağlar**; **alet ve gereç**.', 'GY m.350/2', '',
        ['İşlem görmüş ürünlerin denenmesinde veya tamire ihtiyacı olan ithal eşyanın kusurlarının tespitinde kullanılanlar haricindeki yakıt ve enerji kaynakları', 'İşlem görmüş ürünlerin denenmesi, ayarlanması veya geri alınmasında kullanılan yağlar dışındaki yağlar', 'c) Alet ve gereç, hariç olmak üzere, izin verilebilir.']],
      ['Eşdeğer eşyanın ithal eşyasından daha ileri bir üretim aşamasında olmasına hangi durumda izin verilebilir?',
        'İşlemenin **asli kısmının** izin hak sahibinin işletmesinde veya onun adına işlemenin yapıldığı yerde gerçekleşmesi durumunda (istisnai haller dışında).', 'GY m.352/3', '',
        'Eşdeğer eşyanın, işlemenin asli kısmının izin hak sahibinin işletmesinde veya onun adına işlemenin yapıldığı yerde gerçekleşmesi durumunda, istisnai haller dışında, ithal eşyasından daha ileri bir üretim aşamasında olmasına izin verilebilir.'],
    ] },
    { baslik: 'Süreler ve Rejimin İşleyişi (GK m.111–116; GY m.353–362, 364, 367)', sorular: [
      ['Dahilde işleme rejiminde süre ne zaman başlar ve ne zaman sona erer?',
        'İznin **alındığı tarihten** başlar, bitiminin rastladığı **ayın son günü** sona erer; ithalat ve ihracatın **izin belgesi süresi içinde** yapılması gerekir.', 'GK m.111/2; GY m.353', '',
        ['Süre, serbest dolaşımda bulunmayan eşya için dahilde işleme rejimine ilişkin iznin alındığı tarihten itibaren işlemeye başlar ve bitimin rastladığı ayın son günü sona erer.', 'Dahilde işleme rejimi kapsamında yapılacak ithalat ve ihracatların izin belgesi süresi içerisinde yapılması gerekir.']],
      ['Rejim süresi ve ek süreler nasıl belirlenir; süre hangi hallerde uzatılabilir?',
        'Süre ve ek süreler **Cumhurbaşkanı Kararıyla** belirlenir; **mücbir sebep, beklenmeyen haller** veya izin sahibinin **haklı gerekçeleri** ile uzatılabilir.', 'GK m.111/2; GY m.353/1', '',
        ['İzin sahibi tarafından ileri sürülen haklı gerekçelere bağlı olarak ek süre verilebilir.', 'Bu süre ve ek süreler, Cumhurbaşkanı[110] Kararıyla belirlenir.', 'Bu süreler mücbir sebep ve beklenmeyen hallerde veya izin sahibi tarafından ileri sürülen haklı gerekçelere bağlı olarak uzatılabilir.']],
      ['Önceden ihracatta ithal eşyasının rejim beyanı için süreyi kim belirler ve süre ne zaman başlar?',
        '**Cumhurbaşkanınca** belirlenir (izin belgesinde gösterilir); eşdeğer eşyadan elde edilen ürünlerin **ihracat beyannamesinin tescil tarihinden** itibaren işler; haklı gerekçeli talep üzerine uzatılabilir.', 'GK m.111/3; GY m.354', '2025',
        ['ithal eşyasının rejim beyanı için gereken süre Cumhurbaşkanınca[111] belirlenir', 'Bu süre, ilgili eşdeğer eşyadan elde edilen işlem görmüş ürünler için ihracat beyannamesinin tescil tarihinden itibaren işlemeye başlar.', 'Süre, izin hak sahibinin haklı bir gerekçeye dayanan talebi üzerine uzatılabilir.']],
      ['Verimlilik oranı nedir ve nasıl belirlenir?',
        'Belirli miktar ithal eşyasının işlenmesiyle elde edilen ürünlerin **miktarı veya yüzde oranı**; işlemenin gerçekleştiği/gerçekleşeceği **koşullar göz önünde bulundurularak** belirlenir; standart oranlar **ilgili kuruluşların görüşleri alınarak** hesaplanır.', 'GK m.108/8, 112', '',
        ['"Verimlilik oranı" deyimi, belirli miktardaki ithal eşyasının işlenmesi sonucunda elde edilen işlem görmüş ürünlerin miktarı veya yüzde oranı anlamına gelir.', 'işleme faaliyetinin gerçekleştiği ya da gerçekleşeceği koşullar göz önünde bulundurularak belirlenir', 'İlgili kuruluşların görüşleri alınarak hesaplanan standart verimlilik oranları']],
      ['DİR kapsamında gümrük yükümlülüğü doğarsa vergiler hangi tarihteki unsurlara göre hesaplanır?',
        'İthal eşyasının **dahilde işleme rejimine ilişkin beyannamesinin tescil tarihindeki** vergi oranı ve diğer vergilendirme unsurlarına göre (m.115 saklı).', 'GK m.114/1', '',
        'gümrük vergileri, ithal eşyasının dahilde işleme rejimine ilişkin beyannamenin tescil tarihindeki vergi oranı ve diğer vergilendirme unsurları göz önünde bulundurularak hesaplanır'],
      ['Listede yer alan ikincil işlem görmüş ürünler serbest dolaşıma girerse ithalat vergileri nasıl hesaplanır?',
        'Asıl ürünün **ihraç edilen kısmı oranında**, ikincil ürünlerin **serbest dolaşıma giriş beyannamesinin tescil tarihindeki** oran ve unsurlarla; hak sahibi **m.114 usulünü** talep edebilir.', 'GK m.115/1', '',
        ['asıl işlem görmüş ürünün ihraç edilen kısmı oranında ikincil işlem görmüş ürünlerin serbest dolaşıma girişine ilişkin beyannamenin tescil tarihindeki vergi oranı ve diğer vergilendirme unsurları esas alınarak hesaplanır', 'izin hak sahibi, bu ürünlere ilişkin vergilerin 114 üncü maddede belirtilen usule göre tahakkukunu talep edebilir']],
      ['İşlem görmüş ürünler veya değişmemiş eşya TGB dışına hangi amaçlarla geçici ihraç edilebilir?',
        'Gerekli izinle, HİR hükümleri çerçevesinde **daha ileri düzeyde işlenmek** veya ayniyeti tespit edilebilir olması şartıyla **sergilenmek ya da tamir** amacıyla (Tebliğe göre **serbest bölgelere** de).', 'GK m.116/1; Tebliğ (İhracat 2006/12) m.10/1', '',
        ['hariçte işleme rejimi hükümleri çerçevesinde daha ileri düzeyde işlenmek üzere veya ayniyetinin tespit edilebilir olması şartıyla sergilenmek ya da tamir amacıyla Türkiye Gümrük Bölgesi dışına geçici olarak ihraç edilebilir', 'daha ileri düzeyde işlenmek üzere Türkiye Gümrük Bölgesi dışına veya serbest bölgelere geçici olarak ihraç edilebilir']],
      ['İkincil işlem görmüş ürünlerin serbest dolaşıma girişinde gümrük vergileri neye göre tahsil edilir?',
        '**Ayniyet tespiti yapılmaksızın**, firma beyanı ve izindeki **gerçekleşme oranları** üzerinden hesaplanan miktar ve birim fiyatla; ihracatın tamamından sonra **tek seferde** beyanname de verilebilir.', 'GY m.359/1', '',
        ['gümrük vergileri ayniyet tespiti yapılmaksızın firma beyanı ve izinde öngörülen gerçekleşme oranları üzerinden hesaplanan miktar ve birim fiyat esas alınarak tahsil edilir', 'ikincil işlem görmüş ürünlerin tamamı için tek seferde serbest dolaşıma giriş beyannamesi de verilmesi mümkün bulunmaktadır']],
      ['Kapatma süresi bitiminde gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulmayan eşya ne olur?',
        'Serbest dolaşıma giriş rejimi hükümleri çerçevesinde **serbest dolaşıma girmiş kabul edilir** (GK m.114 saklı).', 'GY m.357/2', '',
        'Rejimin kapatılma süresinin bitiminde bu eşyanın gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulmaması halinde, Kanunun 114 üncü maddesi hükümleri saklı kalmak kaydıyla, serbest dolaşıma giriş rejimi hükümleri çerçevesinde serbest dolaşıma girmiş kabul edilir.'],
      ['İthal eşyası oranının hesaplanmasında miktar ve kıymet ölçme yöntemleri ne zaman uygulanır?',
        'Birinci miktar yöntemi: **tek tür** ürün; ikinci miktar yöntemi: **birden fazla ürün** ve ithal eşyasının tüm unsurları her üründe; **diğer bütün durumlarda kıymet ölçme**. Değer: Türkiye\'de **son satış fiyatı**, bilinmiyorsa **son fabrika çıkış fiyatı**.', 'GY m.361–362', '',
        ['dahilde işleme faaliyetlerinden sadece bir tür işlem görmüş ürün elde edilmesi durumunda kullanılır', 'işlem görmüş birden fazla ürün elde edilmesi ve ithal eşyasının bütün unsurlarının her işlem görmüş ürün içinde bulunması halinde uygulanır', '361 inci maddenin uygulanmadığı diğer bütün durumlarda, kıymet ölçme yöntemi uygulanır.', 'aynı veya benzer ürünlerin Türkiye\'de son satış fiyatı veya bu bilinmiyorsa, aynı şartla Türkiye\'deki son fabrika çıkış fiyatı']],
      ['Rejimi kapatan işlemlerde belgelere hangi ibareler konulur?',
        'Şartlı muafiyette "**Dahilde İşleme/Şartlı Muafiyet Sistemindeki Eşya**" (TPÖ varsa ayrıca "**Ticaret Politikası**"); geri ödemede "**Dahilde İşleme/Geri Ödeme Sistemindeki Eşya**".', 'GY m.364, 367', '',
        ['Dahilde İşleme/Şartlı Muafiyet Sistemindeki Eşya', 'bu belgelere birinci fıkrada belirtilen ibareye ek olarak Ticaret Politikası ibaresi konulur', 'Dahilde İşleme/Geri Ödeme Sistemindeki Eşya']],
    ] },
    { baslik: 'Geri Ödeme Sistemi (GK m.117–121; Tebliğ m.11–13, 43/4)', sorular: [
      ['Gümrük Kanununa göre hangi eşya için geri ödeme sistemi uygulanmaz?',
        'Kural: **her eşya** yararlanabilir. Ancak serbest dolaşıma giriş beyannamesi tescilinde **miktar kısıtlamasına** tabi, **kota** kapsamında tarife önlemi uygulanan, tarım politikası gereği **lisans/sertifika** gerektiren ve işlem görmüş ürün için **ihracat iadesi veya vergisi** bulunan eşyaya uygulanmaz.', 'GK m.117/1', '',
        ['Geri ödeme sisteminden her eşya yararlanabilir.', 'İthalat miktar kısıtlamasına tabi olan,', 'Kota kapsamında tarife önlemleri uygulanan,', 'Tarım politikası çerçevesinde ithalat veya ihracat lisansı veya sertifikası ibrazını gerektiren,', 'İşlem görmüş ürün için ihracat iadesi veya vergisi mevcut,']],
      ['Geri ödeme sisteminde serbest dolaşıma giriş beyannamesinde ne yapılır?',
        'Eşyanın **geri ödeme sistemi kapsamında olduğu belirtilir**, izin bilgileri gösterilir ve **izin belgesinin bir örneği** eklenir.', 'GK m.118', '',
        'serbest dolaşıma giriş beyannamesinde, eşyanın geri ödeme sistemi kapsamında olduğu belirtilir ve izne ilişkin bilgiler beyanname üzerinde gösterilir. Ayrıca, söz konusu izin belgesinin bir örneği beyannameye eklenir.'],
      ['Geri ödeme sisteminde önceden ihracat (ithal eşyası serbest dolaşıma girmeden eşdeğer eşyadan üretilen ürünün ihracı) uygulanabilir mi?',
        '**Hayır**, bu hüküm geri ödeme sisteminde uygulanmaz (ihracat vergisi kadar teminat hükmü de uygulanmaz).', 'GK m.119', '',
        ['Dahilde işleme rejiminde geri ödeme sisteminin uygulandığı hallerde;', 'Eşdeğer eşyadan elde edilen işlem görmüş ürünlerin ithal eşyasının serbest dolaşıma girmesinden önce Türkiye Gümrük Bölgesi dışına ihraç edilmesi hükmü,']],
      ['Geri ödeme sisteminde izin hak sahibi hangi durumları belgeleyerek vergilerin geri verilmesini isteyebilir?',
        'Ürün veya değişmemiş eşyanın **ihraç edildiğini**; yeniden ihraç için **transit, antrepo, geçici ithalat** veya **şartlı muafiyetli DİR**\'e tabi tutulduğunu; **serbest bölgeye konulduğunu**.', 'GK m.121/1', '',
        ['İhraç edildiklerini,', 'Daha sonra yeniden ihraç edilmek üzere transit rejimi, gümrük antrepo rejimi, geçici ithalat rejimi veya şartlı muafiyet sistemine tabi dahilde işleme rejimine tabi tutulduğunu,', 'Serbest bölgeye konulduğunu,', 'ithalat vergilerinin geri verilmesini veya kaldırılmasını isteyebilir']],
      ['Geri ödeme başvuru süresi nedir?',
        'GK: süre ilgili **Cumhurbaşkanı Kararında** belirtilir. Tebliğ: taahhüdün kapatılmasını müteakip **3 ay** içinde **ilgili gümrük idaresine**; geri verme kararından itibaren 3 ay içinde ödenmezse **tecil faizi** uygulanır.', 'GK m.121/3; Tebliğ (İhracat 2006/12) m.13', '',
        ['Geri ödeme başvurusunun yapılması için gereken süre ilgili Cumhurbaşkanı[119] Kararında belirtilir.', 'ihracat taahhüdünün bu Tebliğin 38 inci maddesi hükmüne göre kapatılmasını müteakip 3 (üç) ay içerisinde, ithalat sırasında ödenen vergilerin iadesi için ilgili gümrük idaresine müracaat edilmesi zorunludur', 'bu sürenin bitiminden itibaren 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanunun tecil faizine ilişkin hükümleri uygulanır']],
      ['Tebliğe göre geri ödeme sisteminde hangi vergi geri ödenmez; ithalatta TPÖ uygulanır mı?',
        '**İşletme malzemesine ilişkin KDV ve ÖTV** geri ödenmez; ithalatta **ticaret politikası önlemleri uygulanır**.', 'Tebliğ (İhracat 2006/12) m.11/1', '',
        ['ithalat esnasında alınan verginin (işletme malzemesine ilişkin katma değer vergisi ve özel tüketim vergisi hariç) geri ödenmesidir', 'Bu kapsamda ithal edilen eşya için gümrük idaresince, ticaret politikası önlemleri uygulanır']],
      ['A.TR veya menşe ispat belgesiyle AT\'ye/STA ülkesine ihraç edilecek ürünün girdileri geri ödeme kapsamında nasıl ithal edilir?',
        '**Gümrük vergisi ve varsa TKF tahsil edilir**, diğer vergiler **teminata bağlanır**.', 'Tebliğ (İhracat 2006/12) m.11/2–3', '',
        ['A.TR dolaşım belgesi eşliğinde Avrupa Topluluğuna üye ülkelere ihraç edilecek işlem görmüş ürünün', 'gümrük vergisi ile varsa toplu konut fonunun tahsil edilmesi ve bu vergilerin haricindeki vergilerin teminata bağlanması suretiyle ithalatına izin verilebilir']],
      ['Geri ödeme sisteminden yararlanmak için ne zorunludur?',
        '**Belge/izin alınması** ve eşyanın geri ödeme kapsamında olduğunun ithalatta **gümrük beyannamesine kaydedilmesi** (belge satır kodu da kaydedilir).', 'Tebliğ (İhracat 2006/12) m.11/4', '',
        'Geri ödeme sisteminden yararlanmak için, dahilde işleme izin belgesi/dahilde işleme izni alınması ve eşyanın geri ödeme sistemi kapsamında olduğunun gümrük idaresince ithalat esnasında belgeye/izne ilişkin gümrük beyannamesine kaydedilmesi zorunludur.'],
      ['Tebliğe göre geri ödeme sisteminden hangi eşya yararlandırılmaz?',
        '(AT menşeli tarım ürünleri ithalatı hariç) **miktar kısıtlamasına** tabi; tercihli tarife/özel şartlı muafiyetten **kotalar dahilinde** yararlanabilen; tarım politikası/işlenmiş tarım ürünleri düzenlemeleriyle vergiye tabi; ürünü **parasal ihracat iadesine** tabi eşya.', 'Tebliğ (İhracat 2006/12) m.12/1', '',
        ['Geri ödeme sisteminden, Avrupa Topluluğuna üye ülkeler menşeli tarım ürünleri ithalatı hariç olmak üzere;', 'İthali miktar kısıtlamalarına tabi olan,', 'Tercihli tarife ya da özel bir şartlı muafiyet düzenlemesinden kotalar dahilinde yararlanabilen,', 'İthal eşyasının serbest dolaşıma giriş beyanının kabulü sırasında, işlem görmüş ürünlerden parasal ihracat iadesine tabi olan,']],
      ['Geri ödeme sistemiyle ithal edilip süresinde ihraç edilemeyen eşyaya ilişkin alınan vergi ne olur?',
        '**İade edilmez.**', 'Tebliğ (İhracat 2006/12) m.43/4', '',
        ['Geri ödeme sistemi kapsamında ithal edilen ancak belge/izin süresi içerisinde işlem görmüş ürün olarak belge şartlarına uygun şekilde Türkiye Gümrük Bölgesi dışına veya serbest bölgelere', 'ihracatı gerçekleştirilemeyen ithal eşyasına ilişkin alınan vergi iade edilmez']],
    ] },
    { baslik: 'Tebliğ Tanımları ve Şartlı Muafiyet Uygulaması (Tebliğ m.3, 5–8)', sorular: [
      ['Dahilde işleme izin belgesi ile dahilde işleme izni arasındaki fark nedir?',
        'Belge: muafiyetli ithalata **ve/veya yurt içi alımlara** imkân veren, **Bakanlıkça** düzenlenen belge; izin: muafiyetli **ithalata** imkân veren, **gümrük idaresince** verilen izin.', 'Tebliğ (İhracat 2006/12) m.3/f–g', '2023, 2025',
        ['Dahilde işleme izin belgesi: İhraç amacıyla gümrük muafiyetli ithalata ve/veya yurt içi alımlara imkan sağlayan Bakanlıkça düzenlenen belgeyi,', 'Dahilde işleme izni: İhraç amacıyla gümrük muafiyetli ithalata imkan sağlayan ve gümrük idaresince verilen izni,']],
      ['Döviz kullanım oranı nedir?',
        'Belge/izin kapsamındaki **CIF ithal** tutarının (yurt içi alımlar hariç) **FOB ihraç** tutarına yüzde oranı.', 'Tebliğ (İhracat 2006/12) m.3/h, 38/4', '2025',
        'Döviz kullanım oranı: Dahilde işleme izin belgesi/dahilde işleme izni kapsamındaki CIF ithal (yurt içi alımlar hariç) tutarının FOB ihraç tutarına'],
      ['İşletme malzemesi nedir?',
        'Ürün bünyesinde yer almayan, **sabit tesislerin çalışabilir durumda olmasını** temin eden (**enerji ve yakıt hariç**), **yatırım malı makine-teçhizat niteliğinde olmayan** malzeme.', 'Tebliğ (İhracat 2006/12) m.3/ş', '',
        'ihracı taahhüt edilen işlem görmüş ürünün elde edilmesinde kullanılan ancak ürünün bünyesinde yer almayan ve sabit tesislerin çalışabilir durumda olmasını temin eden (enerji ve yakıt hariç), yatırım malı makine ve teçhizat niteliğinde olmayan malzemeyi'],
      ['Aracı ihracatçı ve yan sanayici nedir?',
        'Aracı ihracatçı: taahhüt edilen ihracatı belge sahibinden **tedarik ettiği şekliyle** yapan, **belge/izin sahibi olmayan** firma; yan sanayici: ihraç ürününü üreten, **belgede kayıtlı ancak belge sahibi olmayan** firma.', 'Tebliğ (İhracat 2006/12) m.3/a, mm', '',
        ['belge/izin sahibi firmadan tedarik ettiği şekliyle gerçekleştiren belge/izin sahibi olmayan firmayı', 'Yan sanayici: Dahilde işleme izin belgesinde/dahilde işleme izninde taahhüt edilen ihraç ürününün tamamını ya da bir kısmını üreten, belgede/izinde kayıtlı ancak belge/izin sahibi olmayan firmayı']],
      ['DİR Tebliğine göre menşe ispat belgeleri hangileridir?',
        '**EUR.1** dolaşım sertifikası, **EUR-MED** dolaşım sertifikası, **EUR-MED fatura beyanı** veya **fatura beyanı**.', 'Tebliğ (İhracat 2006/12) m.3/y', '2023',
        'malın menşeini belirleyen EUR.1 dolaşım sertifikası, EUR-MED dolaşım sertifikası, EUR-MED fatura beyanı veya fatura beyanını'],
      ['Tebliğe göre şartlı muafiyet sisteminde hangi eşya, kimlerce, nasıl ithal edilir?',
        'Serbest dolaşımda olmayan hammadde, yardımcı madde (**katalizör dahil**), yarı mamul, mamul, değişmemiş eşya, ambalaj ve işletme malzemesi; TGB\'de (**serbest bölgeler hariç**) yerleşik firmalarca, TPÖ\'ye tabi tutulmaksızın, vergisi teminata bağlanarak **bedelli ve/veya bedelsiz**.', 'Tebliğ (İhracat 2006/12) m.5/1', '',
        'serbest dolaşımda bulunmayan hammadde, yardımcı madde (katalizör olarak kullanılanlar dahil), yarı mamul, mamul ile değişmemiş eşya, ambalaj ve işletme malzemesinin, Türkiye Gümrük Bölgesinde (serbest bölgeler hariç) yerleşik firmalarca, ticaret politikası önlemlerine tabi tutulmaksızın, vergisi teminata bağlanmak suretiyle bedelli ve/veya bedelsiz ithal edilmesi'],
      ['Şartlı muafiyet kapsamında işletme malzemesi ithalatında hangi istisna vardır?',
        '**KDV ve ÖTV tahsil edilir** ve **TPÖ uygulanır**.', 'Tebliğ (İhracat 2006/12) m.5/2', '',
        'belge/izin kapsamında yapılacak işletme malzemesi ithalatında, katma değer vergisi ve özel tüketim vergisi tahsil edilir ve ticaret politikası önlemleri uygulanır'],
      ['Önceden ihracattan sonra yapılacak ithalat ne zamana kadar ve hangi vergi rejimiyle yapılır?',
        '**Belge süresi sonuna kadar**; **KDV dahil tüm vergiler teminata bağlanır**, TPÖ uygulanmaz; ithal edilen eşya belge sahibince **serbestçe kullanılabilir**.', 'Tebliğ (İhracat 2006/12) m.6/3–4', '',
        ['buna tekabül eden ithalat belge süresi sonuna kadar yapılabilir', 'katma değer vergisi dahil tüm vergiler (4760 sayılı Özel Tüketim Vergisi Kanunu hükümleri saklı kalmak kaydıyla) teminata bağlanır ve ticaret politikası önlemleri uygulanmaz', 'Önceden ihracat işleminden sonra buna tekabül eden oranda ithal edilen eşya, belge sahibi firma tarafından serbestçe kullanılabilir.']],
      ['Belge kapsamında girdiler yurt içinden temin edilebilir mi; hangi hükümler uygulanmaz?',
        'Evet; yurt içinden temin edilen eşya **ithal eşyası gibi** değerlendirilir; ancak **ikincil işlem görmüş ürün** ve **döviz kullanım oranı** hükümleri uygulanmaz.', 'Tebliğ (İhracat 2006/12) m.7/1, 3–4', '',
        ['bu Tebliğin 5 inci maddesi hükmüne göre ithal edilebileceği gibi, yurt içinden de temin edilebilir', 'ithal eşyası gibi değerlendirilir', 'belge kapsamında yurt içinden temin edilen eşya için, bu Tebliğin ikincil işlem görmüş ürüne ve döviz kullanım oranına ilişkin hükümleri uygulanmaz']],
      ['Şartlı muafiyet kapsamındaki teminat hangi esaslara tabidir; oranı ne kadar artırılabilir ve hangi unsurlardan oluşur?',
        '**6183 sayılı Kanun** esasları; Bakanlık (İhracat GM) vergi tutarının **2 katına kadar** artırabilir; **para, banka teminat mektubu, Hazine tahvil ve bonoları**.', 'Tebliğ (İhracat 2006/12) m.8', '',
        ['6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanunda belirtilen esaslar çerçevesinde teminata tabidir', 'bu ithalattan doğan vergi tutarının 2 (iki) katına kadar artırılabilir', 'a- Para, b- Bankalar tarafından verilen teminat mektupları, c- Hazine tahvil ve bonoları,']],
    ] },
    { baslik: 'Belge/İzin Düzenlenmesi (Tebliğ m.14–19)', sorular: [
      ['Dahilde işleme izni kapsamında hangi işlemlere konu eşyanın ithaline izin verilir?',
        'Ek-7 hariç: tekstil yardımcı maddeleri; kıymetli maden/taş işçiliği; **korunma, görünüş/satış kalitesinin iyileştirilmesi**; **montaj**, kurma, birleştirme; **tamir veya boyama**; onarım; baskı, asorti, etiketleme, **ambalajlama**, temizleme, eleme, kavurma; fideden kesme çiçek; filmaşinden çivi/siyah tel; rulo sacdan kesilmiş sac; bedelsiz ithal eşyanın işlenmesi. Kapsamı GGM görüşüyle **İhracat GM** genişletebilir.', 'Tebliğ (İhracat 2006/12) m.14', '2025',
        ['Eşyanın korunması, görünüş ya da satış kalitesinin iyileştirilmesi, yeniden dağıtım veya yeniden satış için hazırlanmasına yönelik işlemler', 'Eşyanın montajı, kurulması, diğer eşyayla birleştirilmesi, bir araya getirilmesi veya ihraç edilecek eşyanın tamamlanması dahil olmak üzere işçiliğe tabi tutulması', 'Eşyanın baskı işlemine tabi tutulması, asorti edilmesi, etiketlenmesi, ambalajlanması, temizlenmesi, elenmesi, fiziksel boyutunun değiştirilmesi, kavrulması veya kabuğundan ayrılması', 'Fide ithalatını müteakip, ihraç edilmek üzere kesme çiçek yetiştirilmesi', 'Gümrükler Genel Müdürlüğünün görüşü alınmak suretiyle, İhracat Genel Müdürlüğünce birinci fıkrada belirtilen dahilde işleme izninin kapsamı genişletilebilir.']],
      ['Belge ve izin için nereye müracaat edilir; dahilde işleme iznini kim verir?',
        'Belge: elektronik ortamda **Bakanlığa (İhracat GM)**; izin: ek-1 bilgi/belgeleriyle elektronik ortamda **gümrük idaresine**. İzin, GGM\'nin belirlediği esaslar çerçevesinde **gümrük idaresince** verilir.', 'Tebliğ (İhracat 2006/12) m.15/1, 17/3', '2023, 2025',
        ['Dahilde işleme izin belgesi almak için elektronik ortamda Bakanlığa (İhracat Genel Müdürlüğü),', 'Dahilde işleme izni almak için ek-1\'de belirtilen bilgi ve belgelerle elektronik ortamda[23] gümrük idaresine,', 'Gümrükler Genel Müdürlüğünce belirlenen uygulama esasları çerçevesinde elektronik ortamda gümrük idaresince verilir']],
      ['Belge/izin müracaatları hangi kriterlere göre değerlendirilir?',
        'İthal eşyasının kullanıldığının **tespitinin mümkün** olması; üreticilerin temel ekonomik çıkarları ile **Türk malı imajının** olumsuz etkilenmemesi; **katma değer** yaratan, kapasite kullanımını artıran faaliyet olması; firmanın **performansı**.', 'Tebliğ (İhracat 2006/12) m.16', '',
        ['İthal eşyasının işlem görmüş ürünün elde edilmesinde kullanıldığının tespitinin mümkün olması,', 'üreticilerin temel ekonomik çıkarları ile Türk malı imajının olumsuz etkilenmemesi,', 'İşleme faaliyetinin, katma değer yaratan ve kapasite kullanımını artıran bir faaliyet olması', 'Firmaların dahilde işleme izin belgeleri/dahilde işleme izinleri kapsamındaki performansları,']],
      ['Hangi eşya dahilde işleme rejimi kapsamında değerlendirilmez?',
        '**Süs hayvanları**, canlı balık (**orkinos ve larva hariç**), küçük ve büyükbaş hayvanlar, **çevre kirliliğine** neden olan eşya.', 'Tebliğ (İhracat 2006/12) m.17/2', '',
        'Süs hayvanları, canlı balık (orkinos balığı ve larva hariç), küçük ve büyükbaş hayvanlar ile çevre kirliliğine neden olan eşyalar dahilde işleme rejimi kapsamında değerlendirilmez.'],
      ['Tarım ürünlerinin bedelsiz ithalatına dahilde işleme izni kapsamında gümrük idaresince müsaade edilir mi?',
        '**Hayır**; tarım ürünlerinin bedelsiz ithalatı, **Savunma Sanayi** projeleri bedelsiz ithalatı ve **Ek-7** ürünleri izin kapsamında yapılamaz; bu talepler **belge** kapsamında **Bakanlıkça** değerlendirilir.', 'Tebliğ (İhracat 2006/12) m.17/4', '',
        ['tarım ürünlerinin bedelsiz ithalatına, Savunma Sanayi Projeleri kapsamında yapılacak bedelsiz ithalata ve Ek-7\'de belirtilen ürünlerin bedelli veya bedelsiz olarak ithalatına dahilde işleme izni kapsamında ilgili gümrük idarelerince müsaade edilmez', 'Bu çerçevedeki talepler dahilde işleme izin belgesi kapsamında Bakanlıkça değerlendirilir.']],
      ['Tarım ve işlenmiş tarım ürünleri ihracatı için imalatçı olmayan ihracatçılar adına belge/izin düzenlenir mi?',
        'Kural olarak **düzenlenmez**; **DTSŞ**, **SDŞ** ve sermayesinin en az **%51**\'i imalatçının hissedarlarına ait ihracatçılar hariç.', 'Tebliğ (İhracat 2006/12) m.17/7', '',
        'Dış ticaret sermaye şirketleri, sektörel dış ticaret şirketleri ve sermayesinin en az % 51\'i imalatçının hissedarlarına ait olan ihracatçılar hariç olmak üzere tarım ve işlenmiş tarım ürünleri ihracatı için ihracatçılar adına belge/izin düzenlenmez.'],
      ['Döviz kullanım oranı hangi hallerde aranmaz?',
        'Dahilde işleme **izninde**; belge kapsamındaki **bedelsiz ithalatta**; süre bitimi/kapatma sonrası geri gelen ürün için düzenlenen **yeni belgede**; belge kapsamındaki **yurt içi alımlarda**.', 'Tebliğ (İhracat 2006/12) m.17/8', '',
        ['Döviz kullanım oranı; a) Dahilde işleme izninde, b) Dahilde işleme izin belgesi kapsamındaki bedelsiz ithalatta,', 'd) Dahilde işleme izin belgesi kapsamındaki yurt içi alımlarda, aranmaz.']],
      ['Belge kapsamında döviz kullanım oranı azami ne kadar olabilir?',
        '**%80**\'i geçmemek üzere Bakanlıkça belirlenir; **ikincil işlem görmüş tarım ürünü** taahhüdü içeren belgelerde azami **%100**.', 'Tebliğ (İhracat 2006/12) m.17/9', '',
        ['Dahilde işleme izin belgesi kapsamında döviz kullanım oranı % 80\'i geçmemek üzere Bakanlıkça belirlenir.', 'ikincil işlem görmüş tarım ürünleri taahhüdü içeren belgelerde bu oran Bakanlıkça azami % 100 olarak tespit edilebilir']],
      ['Belge/izin kapsamında değişmemiş eşya ve işletme malzemesi ithalatının sınırı nedir?',
        'Değişmemiş eşya: ihracat taahhüdünün azami **%1**\'i; işletme malzemesi: ihracat taahhüdünün **%2**\'si (doğal taş, kıymetli maden ve taşta **%10**\'a kadar).', 'Tebliğ (İhracat 2006/12) m.17/11–12', '',
        ['Belge/izin kapsamında ihracat taahhüdünün azami % 1\'i oranında değişmemiş eşya ithalatına izin verilebilir.', 'Belge/izin kapsamında ithaline izin verilecek işletme malzemesi değeri, ihracat taahhüdünün % 2\'sini geçemez.', 'doğal taşlar ile kıymetli maden ve taş ihraç taahhüdü içeren belgede/izinde, bu oran % 10\'a kadar tespit edilebilir']],
      ['Belge ve izin ne zamana kadar revize edilebilir; izin revizesi nereye yapılır?',
        'Belge: **kapatma işlemleri sonuçlandırılıncaya kadar** (elektronik ortamda Bakanlığa); izin: taahhüt kapatma sonuçlanıncaya kadar, **ilgili gümrük idaresine**.', 'Tebliğ (İhracat 2006/12) m.19/1, 4', '',
        ['Dahilde işleme izin belgesi, belge kapatma işlemleri sonuçlandırılıncaya kadar revize edilebilir.', 'Dahilde işleme izni, taahhüt kapatma işlemleri sonuçlandırılıncaya kadar revize edilebilir.', 'revize müracaatı, ilgili firma tarafından gerekli bilgi ve belgeler ile birlikte ilgili gümrük idaresine yapılır']],
    ] },
    { baslik: 'Belge/İzin Süreleri, Ek Süre, Haklı ve Mücbir Sebep (Tebliğ m.20–27)', sorular: [
      ['Belge/izin süresi azami ne kadardır?',
        'Sektörüne göre azami **12 ay**; gemi inşa, komple tesis, üretim süreci 12 ayı aşan ürünler ve **savunma sanayi** ürünlerinde **proje süresi kadar**.', 'Tebliğ (İhracat 2006/12) m.20/1–2', '',
        ['Dahilde işleme izin belgesinin/dahilde işleme izninin süresi sektörüne göre azami 12 (oniki) aya kadar tespit edilebilir.', 'proje süresi kadar tespit edilebilir']],
      ['Ek süre, haklı sebep ve mücbir sebep müracaatları hangi sürede yapılır?',
        'Belge için belge süresi sonundan itibaren **3 ay** içinde elektronik ortamda **Bakanlığa**; izin için izin süresi sonundan itibaren **2 ay** içinde **gümrük idaresine**. Süresinde yapılmayan müracaat **değerlendirilmez**.', 'Tebliğ (İhracat 2006/12) m.21, 23, 26', '',
        ['en geç belge süresi sonundan itibaren 3 (üç) ay içerisinde elektronik ortamda Bakanlığa', 'en geç izin süresi sonundan itibaren 2 (iki) ay içerisinde ilgili gümrük idaresine', 'Birinci fıkrada belirtilen sürede yapılmayan müracaat değerlendirmeye alınmaz.']],
      ['İlk ithalat tarihi esas alınarak belge süresi ne kadar uzatılır?',
        'Azami **3 ay**; belge kapsamında **hiç ithalat yapılmasa da** azami 3 ay.', 'Tebliğ (İhracat 2006/12) m.22/1', '',
        'Dahilde işleme izin belgesi kapsamında ilk ithalatın yapıldığı tarih esas alınmak suretiyle belge süresi azami 3 (üç) ay uzatılır. Belge kapsamında hiç ithalat yapılmaması halinde de belge süresi azami 3 (üç) ay uzatılır.'],
      ['İhracat performansına dayalı ek süre hangi şartla ve ne kadar verilir?',
        'Gerçekleşen ihracatın taahhüde oranı en az **%25** ise belge **orijinal süresinin yarısı** kadar.', 'Tebliğ (İhracat 2006/12) m.22/2', '',
        ['belge ihracat taahhüdü değerine oranının en az % 25 olması halinde', 'dahilde işleme izin belgesine belge orijinal süresinin yarısı kadar ek süre verilebilir']],
      ['Belgeye haklı sebebe ilişkin ek süre hangi durumda ve ne kadar verilir?',
        'Firmanın **önceden ihracatına tekabül eden ithalatını tamamlayamaması** haline mahsus; belge süresi sonundan itibaren azami **orijinal sürenin yarısı** kadar.', 'Tebliğ (İhracat 2006/12) m.24/1', '',
        'ilgili firmanın belge kapsamındaki önceden ihracatına tekabül eden ithalatını tamamlayamaması haline mahsus olmak üzere, belge süresi sonundan itibaren azami belge orijinal süresinin yarısı kadar haklı sebebe ilişkin ek süre verilebilir'],
      ['DİR Tebliğinde sayılan mücbir sebep ile fevkalade haller nelerdir?',
        'Tabii afetler ve **yangın**; ülkemiz veya ithalatçı ülkede devletçe konulan **yasaklar, harp ve abluka**, genel salgın; firmanın faaliyetinin kamu otoritesince **kısıtlanması/durdurulması/el konulması**; **iflas, konkordato** veya iflasın ertelenmesi; şahıs firmasında **sahibinin ölümü**; **grev ve lokavt**.', 'Tebliğ (İhracat 2006/12) m.25', '2024',
        ['Deprem, sel, don, fırtına, kasırga vb. tabii afetler ve yangın', 'devletçe konulan yasaklar, harp ve abluka hali veya genel salgın hastalık', 'Yükümlü firmanın faaliyetinin kamu otoritelerince kısıtlanması, durdurulması veya firmaya el konulması', 'Yükümlü firmanın iflası veya konkordato ilan etmiş olması', 'Şahıs firmalarında firma sahibinin ölümü,', 'Grev ve lokavt (İl çalışma müdürlüklerinden alınacak yazı ile).']],
      ['Tabii afet nedeniyle ithal eşyanın yerine konulamayacak şekilde telefi veya kaybı halinde ne yapılır?',
        'Mahkeme **delil tespiti** tevsik edilirse: ihracat aranmaksızın taahhüt **kapatılır ve teminat iade** edilir **veya** telef/kayıp miktarı kadar **yeni ithalata izin** verilir.', 'Tebliğ (İhracat 2006/12) m.27/2-a', '',
        ['mahkeme tarafından yapılan delil tespitinin tevsik edilmesi halinde', 'Bu ithalata tekabül eden ihracatın gerçekleştirilmesi aranmaksızın ihracat taahhüdü kapatılır ve ithalata ilişkin teminat iade edilir veya,', 'İhracat taahhüdünün tamamlanması için telef olan veya kaybolan miktar kadar yeni ithalata izin verilir.']],
      ['Mücbir sebeple üretim tesisinin kullanılamaz hale gelmesi durumunda ithal eşyaya ne olur?',
        'Bütün hak ve mükellefiyetleriyle, rejimden yararlanma koşullarına sahip **başka bir firmaya**, gümrük gözetimi ve denetimi altında **devredilebilir**.', 'Tebliğ (İhracat 2006/12) m.27/2-b', '',
        ['Belge/izin sahibi firmanın üretim tesisinin kullanılamaz hale gelmesi durumunda', 'belge/izin kapsamında ithal edilen eşya bütün hak ve mükellefiyetleri ile birlikte, dahilde işleme rejiminden yararlanma koşullarına sahip başka bir firmaya, gümrük gözetimi ve denetimi altında']],
    ] },
    { baslik: 'İhracat, Gümrük İşlemleri ve Telafi Edici Vergi (Tebliğ m.28–36)', sorular: [
      ['İhracatın gerçekleştirilmesi ne demektir; serbest bölgeye ihracatta taahhüt nasıl kapatılır?',
        'Ürünün **TGB dışına veya serbest bölgelere** ihracı; serbest bölgeye ihracatta belge/izin süresi bitiminden itibaren **3 ay** içinde başka ülkeye satış vb. tevsik edilmelidir.', 'Tebliğ (İhracat 2006/12) m.28/1–2', '',
        ['Türkiye Gümrük Bölgesi dışına veya serbest bölgelere ihraç edilmesidir', 'serbest bölgelere gerçekleştirilen ihracata konu eşyanın en geç belge/izin süresi bitiminden itibaren 3 (üç) ay içerisinde; serbest bölgelerden başka bir ülkeye satışının yapıldığının']],
      ['Belge kapsamındaki ihracat aracı ihracatçı ile yapılabilir mi; sorumluluk nasıldır?',
        'Evet; elektronik belgede önceden **bölge müdürlüğünden izin** gerekir; ürün belge sahibinden **tedarik edildiği şekliyle** ihraç edilmeli. Sahtelik vb. tespitinde aracı ihracatçı belge sahibiyle **müştereken ve müteselsilen** sorumludur.', 'Tebliğ (İhracat 2006/12) m.29', '',
        ['başka bir ihracatçı aracılığı ile de yapılabilir. Ancak, elektronik ortamda düzenlenen dahilde işleme izin belgesi kapsamındaki işlemler için önceden ilgili bölge müdürlüğünden izin alınması gerekir.', 'belge/izin sahibi firmadan tedarik edildiği ve belge/izin ihracat taahhüdünde yer aldığı şekliyle ihracının gerçekleştirilmesi gerekir', 'aracı ihracatçı, beyanname konusu işlem görmüş ürünün elde edilmesinde kullanılan eşyanın ithalatı esnasında alınmayan vergiden, belge/izin sahibi firma ile birlikte müştereken ve müteselsilen sorumludur']],
      ['Belge/izin kapsamındaki ithalat temsilci aracılığıyla yapılabilir mi?',
        'Evet; **Borçlar Kanunu**nun doğrudan/dolaylı temsil hükümlerine göre tayin edilmiş temsilciyle (elektronik belgede önceden bölge müdürlüğü izni); usulsüzlükte temsilci belge sahibiyle **müştereken ve müteselsilen** sorumludur.', 'Tebliğ (İhracat 2006/12) m.30', '',
        ['Borçlar Kanununun doğrudan ya da dolaylı temsil hükümlerine göre tayin edilmiş olmak kaydıyla, temsilci aracılığıyla da yapılabilir', 'ithalata aracılık eden temsilci, beyanname konusu eşyanın ithalatı esnasında alınmayan vergiden belge/izin sahibi firma ile birlikte müştereken ve müteselsilen sorumludur']],
      ['İhracat esnasında önceden ithalat şartı, ekspertiz raporu ve ayniyet aranır mı?',
        'Özel şart yoksa **önceden ithalat aranmaz**; ekspertiz raporu ve ayniyet **istenmez**. İzinde ürünün ithal eşyadan elde edilmediğine dair **karine** varsa ekspertiz istenebilir.', 'Tebliğ (İhracat 2006/12) m.31/2-f, g, ğ', '',
        ['İhracat esnasında, belge özel şartında aksine bir hüküm olmadığı takdirde belge kapsamında önceden ithalatın yapılmış olması şartı aranmaz.', 'belgenin özel şartlar bölümünde aksine bir hüküm olmadıkça ayrıca ekspertiz raporu ve ayniyet istenmez', 'ithal edilen eşyadan elde edilmediğine ilişkin karinelerin bulunması halinde, bu ürün için ekspertiz raporu istenebilir']],
      ['Gözetim ve korunma önlemlerine tabi eşyanın serbest dolaşıma girebilmesi için ne gerekir; yoksa ne olur?',
        'İthal tarihindeki önlemlere göre **ithal lisansı (kota) ve/veya gözetim belgesi** zorunlu; yoksa elde edilen ürün **üçüncü ülkelere ihraç** veya gümrük gözetiminde **imha** edilmelidir.', 'Tebliğ (İhracat 2006/12) m.32/1–2', '',
        ['ithal tarihi itibarıyla yürürlükte bulunan gözetim ve korunma önlemleri çerçevesinde ithal lisanslarının (kota) ve/veya gözetim belgelerinin bulunması zorunludur', 'Aksi takdirde, bu eşyadan elde edilen işlem görmüş ürünün, üçüncü ülkelere ihracı ya da gümrük idaresi gözetiminde imhası gerekir.']],
      ['Şartlı muafiyet kapsamındaki sanayi ürünlerinin A.TR ile AT\'ye ihracatında ödenen "telafi edici vergi" nedir?',
        'Tercihli rejimle ihraç edilen ürünün elde edilmesinde kullanılan **üçüncü ülke menşeli** hammadde, yardımcı madde, yarı mamul, mamul ve değişmemiş eşyaya ilişkin **ithalat vergisi**.', 'Tebliğ (İhracat 2006/12) m.33/1', '2021, 2022',
        ['Telafi edici verginin ödenmesi', 'Şartlı muafiyet sistemi kapsamındaki sanayi ürünlerinin A.TR dolaşım belgesi eşliğinde Avrupa Topluluğuna üye ülkelere ihracatında; işlem görmüş ürünün elde edilmesinde kullanılan üçüncü ülke menşeli hammadde, yardımcı madde, yarı mamul, mamul ile değişmemiş eşyaya ilişkin vergi, kaynak ülkelerle varolan anlaşmalardaki lehte hükümler saklı kalmak kaydıyla ödenir.']],
      ['Şartlı muafiyet kapsamında AT\'ye ihracatta sanayi ürünleri ve tarım ürünleri hangi belgeyle tercihli rejimden yararlanır?',
        'Sanayi ürünleri **A.TR dolaşım belgesi** eşliğinde; tarım ürünleri anlaşmadaki menşe kuralı sağlanarak **menşe ispat belgesi** (EUR.1 vb.) düzenlenmesi kaydıyla; tarımda üçüncü ülke girdilerinin vergisi tahsil edilir.', 'Tebliğ (İhracat 2006/12) m.33/1, 3; m.3/y', '2025',
        ['Şartlı muafiyet sistemi kapsamındaki sanayi ürünlerinin A.TR dolaşım belgesi eşliğinde Avrupa Topluluğuna üye ülkelere ihracatında', 'Anlaşma ile belirlenen menşe kuralının sağlanması ve bir menşe ispat belgesinin düzenlenmesi kaydıyla', 'tarım ürünlerinin Avrupa Topluluğuna üye ülkelere ihracatında; bu ürünlerin elde edilmesinde kullanılan üçüncü ülke menşeli hammadde, yardımcı madde, yarı mamul, mamul ile değişmemiş eşyaya ilişkin vergi tahsil edilir']],
      ['Telafi edici vergi hangi tarihteki kur ve oranla hesaplanır, ne zaman ödenir?',
        '**İhracat beyannamesinin tescil tarihindeki** TCMB döviz satış kuru ve ithalat rejimindeki GV + varsa TKF ile, **ihracat esnasında**; önceden ihracatta önceden ihracat beyannamesi tescil tarihine göre hesaplanıp **ithalat esnasında** ödenir. Tahsilat **bütçeye irat** kaydedilir.', 'Tebliğ (İhracat 2006/12) m.33/7', '2024',
        ['ihracata ilişkin gümrük beyannamesinin tescil tarihindeki Türkiye Cumhuriyet Merkez Bankası döviz satış kuru ve bu tarihte ithalat rejiminde belirtilen gümrük vergisi ve varsa toplu konut fonu üzerinden hesaplanarak ihracat esnasında ödenir', 'önceden ihracata tekabül eden ithalatın yapılması esnasında ödenir', 'Tahsil edilen telafi edici vergi bütçeye irat kaydedilir.']],
      ['Üçüncü ülke girdisine ilişkin vergi Toplulukta uygulanandan yüksekse hangisi ödenir; harp araçlarında telafi edici vergi aranır mı?',
        'Tarım ürünleri ve 1/95 OKK kapsamı ürünler hariç **Toplulukta uygulanan vergi** ödenir; AT\'ye ihraç edilen **harp araç-gereçleri** ve yedek parçaları için telafi edici vergi **aranmaz**.', 'Tebliğ (İhracat 2006/12) m.33/5, 9', '',
        ['Toplulukta uygulanan vergiden yüksek olması halinde, tarım ürünleri ile 1/95 sayılı Avrupa Topluluğu-Türkiye Ortaklık Konseyi Kararı kapsamı ürünler hariç olmak üzere, Toplulukta uygulanan vergi ödenir', 'her türlü harp araç, gereç, teçhizat, makine, cihaz ve sistemleri ile bunların yapım, bakım ve onarımlarında kullanılacak yedek parçalar için telafi edici vergi aranmaz']],
      ['Belge/izin kapsamında fazla yatırılan verginin iadesi için başvuru süresi nedir?',
        'Verginin **tebliği tarihinden itibaren 3 yıl** içinde ilgili gümrük idaresine; idare geri verme kararından itibaren **3 ay** içinde iade etmek zorundadır.', 'Tebliğ (İhracat 2006/12) m.34/2–3', '',
        ['bu verginin tebliği tarihinden itibaren 3 (üç) yıl içerisinde tevsik edici bilgi ve belgelerle birlikte ilgili gümrük idaresine müracaat edilmesi gerekir', 'geri verme kararının alındığı tarihten itibaren 3 (üç) ay içerisinde fazla yatırılan vergiyi geri vermek zorundadır']],
      ['Kısmi teminat iadesi ne zaman istenir ve azami ne kadar olabilir?',
        '**Belge/izin süresi içinde** müracaat edilir; teminat **gerçekleşen ihracat oranında** iade edilir, ancak toplam verginin **%90**\'ını geçemez; bakiye kapatmadan sonra iade edilir.', 'Tebliğ (İhracat 2006/12) m.35–36', '',
        ['İthalat yapılan dahilde işleme izin belgesi ile ilgili olarak belge süresi içerisinde', 'belge/izin kapsamındaki ithalat esnasında alınan teminatlar, gerçekleşen ihracata tekabül eden oranda firmaya iade edilir', 'Kısmi teminat iadesi kapsamında geri verilen teminat tutarı, belge/izin kapsamında alınması gereken toplam verginin % 90\'ını geçemez.']],
    ] },
    { baslik: 'İhracat Taahhüdünün Kapatılması ve Genel Hükümler (Tebliğ m.37–44)', sorular: [
      ['İhracat taahhüdünün kapatılması için bilgi ve belgeler ne zamana kadar, nereye sunulur?',
        'Belge: süre sonundan itibaren **3 ay** içinde Ek-3 belgeleri **bölge müdürlüğüne**; izin: **3 ay** içinde Ek-4 belgeleri **gümrük idaresine**. Firmalara ayrıca **yazılı bildirim yapılmaz**.', 'Tebliğ (İhracat 2006/12) m.37', '',
        ['Dahilde işleme izin belgesi ihracat taahhüdünü kapatmak için en geç belge süresi sonundan itibaren üç ay içerisinde Ek-3\'te belirtilen bilgi ve belgeleri Bakanlıkça (İhracat Genel Müdürlüğü) belirlenen ilgili bölge müdürlüğüne', 'Ek-4\'te belirtilen bilgi ve belgeleri ilgili gümrük idaresine', 'bu süreler zarfında firmalara ayrıca yazılı olarak bildirimde bulunulmaz']],
      ['Kapatma belgeleri eksik veya süresinde sunulmamışsa ne yapılır?',
        'Eksikler **1 ay** içinde tamamlanmak üzere firmaya bildirilir; tamamlanmazsa taahhüt **mevcut belgelerle** (m.45 dikkate alınarak) kapatılır.', 'Tebliğ (İhracat 2006/12) m.38/1', '',
        ['bu eksiklikler 1 (bir) ay içerisinde tamamlanmak üzere ilgili bölge müdürlüğü/gümrük idaresi tarafından firmaya bildirilir', 'ihracat taahhüdü mevcut bilgi ve belgelerle, bu Tebliğin 45 inci maddesi de dikkate alınarak kapatılır']],
      ['Bir gümrük beyannamesinin belge/izin ihracat taahhüdüne sayılması için ne gerekir?',
        'Beyannamenin belge/izin **süresi içinde tescil** edilmiş olması yeterlidir (ihracatın gerçekleştiği tespit edilir); beyannamede belge/izin sayısını içeren **satır kodu** zorunludur.', 'Tebliğ (İhracat 2006/12) m.38/2–3', '',
        ['Gümrük beyannamesinin belge/izin süresi içerisinde tescil edilmiş olması bu beyannamenin belge/izin kapsamında değerlendirilebilmesi için yeterli sayılır.', 'ilgili gümrük beyannamesinde belge/izin sayısını içeren satır kodunun yer alması zorunludur']],
      ['İthal eşyanın süre içinde imhası, gümrüğe terki veya mahrecine iadesi halinde ihracat aranır mı?',
        '**Aranmaz**; bu eşyaya tekabül eden ihracatın gerçekleştirilmesi aranmaz.', 'Tebliğ (İhracat 2006/12) m.38/8', '',
        'belge/izin süresi içerisinde gümrük idaresi gözetiminde imhası, gümrüğe terk edilmesi veya mahrecine iadesi hallerinde, bu eşyaya tekabül eden ihracatın gerçekleştirilmesi aranmaz'],
      ['Müeyyideli taahhüt kapatma işlemine nasıl itiraz edilir?',
        'Belge: tebliğden itibaren **1 ay** içinde **Bakanlığa (İhracat GM)** yazılı; izin: GK **m.242** uyarınca itiraz.', 'Tebliğ (İhracat 2006/12) m.38/12', '',
        ['taahhüt hesabının müeyyideli kapatılması işlemine karşı tebliğ tarihinden itibaren 1 (bir) ay içerisinde Bakanlığa (İhracat Genel Müdürlüğü) yazılı olarak itiraz edebilirler', 'Dahilde işleme izinlerine ilişkin müeyyideli kapatma işlemlerine ise, 4458 sayılı Gümrük Kanununun 242 nci maddesi uyarınca itiraz yoluna başvurulabilir.']],
      ['Taahhüt kapatıldıktan sonra teminatları kim iade eder?',
        'Yurt içi alım teminatları: Tarım ve Orman Bakanlığınca tespit edilen **şeker fabrikaları**; şartlı muafiyet ithalat teminatları ve geri ödeme vergileri: **ilgili gümrük idaresi**.', 'Tebliğ (İhracat 2006/12) m.40', '',
        ['tespit edilen şeker fabrikalarınca', 'İthalat yapılan şartlı muafiyet sistemi çerçevesindeki dahilde işleme izin belgesi/dahilde işleme izni kapsamında alınan teminatlar ilgili gümrük idaresince']],
      ['Belge süresi içinde ihraç edilen işlem görmüş ürün geri getirilirse ne yapılır?',
        'İhracat nedeniyle yararlanılan hak ve menfaatin m.8\'e göre **teminatının alındığı** tevsik edilirse, gümrük idaresince ürünün **ithalatına ve (yeniden) ihracatına** müsaade edilir.', 'Tebliğ (İhracat 2006/12) m.42/1', '',
        'ihracat nedeniyle varsa yararlanılan hak ve menfaatin bu Tebliğin 8 inci maddesi hükmüne göre teminatının alındığının tevsiki kaydıyla, ilgili gümrük idaresince bu ürünün ithalatına ve ihracatına müsaade edilir'],
      ['İhracatı gerçekleştirilmeyen ithal eşyası nerede bulundurulmalıdır?',
        'İşlem görmüş ürün ve/veya ithal edildiği şekliyle belge sahibi ve/veya **yan sanayicinin stoklarında** bulundurulması **zorunludur**.', 'Tebliğ (İhracat 2006/12) m.43/1', '',
        'ihracatı gerçekleştirilmeyen ithal eşyasının, işlem görmüş ürün ve/veya ithal edildiği şekliyle belge/izin sahibi firma ve/veya yan sanayici firmanın stoklarında bulundurulması zorunludur'],
      ['Belge/izin hangi hallerde, kimce iptal edilir; iptal ve düzenlenen belgeler nerede ilan edilir?',
        'Talep halinde **kullanılmayan belge** iptal edilir (elektronik ortamda Bakanlığa); bilgi/belgelerin gerçek dışı veya sahte olması halinde belge **Bakanlıkça**, izin **gümrük idaresince** iptal edilir. Düzenlenen ve iptal edilen belgeler **aylık listelerle Resmî Gazete**\'de yayımlanır.', 'Tebliğ (İhracat 2006/12) m.18, 44', '',
        ['Firmanın talep etmesi halinde, kullanılmayan dahilde işleme izin belgesi iptal edilir.', 'ilgili belge Bakanlıkça, izin ise ilgili gümrük idaresince iptal edilir', 'İptal edilen dahilde işleme izin belgeleri aylık listeler halinde Resmî Gazete\'de yayımlanır.', 'düzenlenen dahilde işleme izin belgeleri aylık listeler halinde Resmî Gazete\'de yayımlanır']],
    ] },
  ],
  tuzaklar: [
    '**Şartlı muafiyet** = vergiler **tahsil edilmez, teminata bağlanır**, ihracta teminat iade edilir; **geri ödeme** = vergiler **tahsil edilir**, ihracta **geri verilir**. DİR tedbirleri yalnız bu **iki sistemden** oluşur.',
    '**Belge** → **Bakanlık (İhracat GM)** düzenler, yurt içi alıma da imkân verir; **izin** → **gümrük idaresi** verir. Ek süre/haklı/mücbir sebep müracaatı: belgede **3 ay (Bakanlık)**, izinde **2 ay (gümrük idaresi)**; taahhüt kapatma her ikisinde **3 ay**, eksik tamamlama **1 ay**.',
    '**Eşdeğer eşya** = ithal eşyası yerine kullanılan **serbest dolaşımdaki** eşya; GTİP aynılığı GY\'de **8-12\'li**, Tebliğde **asgari 8\'li**, **tarım ürünlerinde münhasıran 12\'li** bazda.',
    'Önceden ihracat süresi **ihracat beyannamesinin tescil tarihinden** başlar (süreyi **Cumhurbaşkanı** belirler). Telafi edici vergi de **ihracat beyannamesinin tescil tarihindeki** kur ve oranla, **ihracat esnasında** ödenir; ithalat beyannamesi tarihi çeldiricidir.',
    '**Döviz kullanım oranı** = **CIF ithal / FOB ihraç**; belgede azami **%80** (ikincil tarım ürünü taahhüdünde **%100**); **izinde, bedelsiz ithalatta ve yurt içi alımda aranmaz**.',
    'Oranlar: değişmemiş eşya **%1**, işletme malzemesi **%2** (doğal taş/kıymetli maden **%10**); kısmi teminat iadesi azami **%90**; performans ek süresi için ihracat **≥ %25** → orijinal sürenin **yarısı**; ilk ithalata dayalı ek süre **3 ay**; belge/izin süresi azami **12 ay**; teminat oranı vergi tutarının **2 katına** kadar artırılabilir.',
    'TGB dışında yerleşik kişilere izin yalnız **ticari nitelikte olmayan** ithalatta verilebilir; (c) bendindeki ekonomik koşulları belirlemeye **Cumhurbaşkanı** yetkilidir.',
    'Mücbir sebepler: tabii afet/yangın, **yasak-harp-abluka**/salgın, faaliyetin **kamu otoritesince kısıtlanması**, **iflas/konkordato**, şahıs firmasında **sahibinin ölümü**, **grev ve lokavt**. Geri ödemede ise önceden ihracat **uygulanmaz**; ihraç edilemeyen eşyanın alınan vergisi **iade edilmez**.',
  ],
};
