// 48. Konu — Gümrük Cezaları (kaynak: 48-cezalar.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '48',
  konu: 'Gümrük Cezaları',
  kaynak: '48-cezalar.docx (GK m.231–241; GY m.579–583)',
  bolumler: [
    { baslik: 'Genel Hükümler ve Ceza Kararları (GK m.231–233; GY m.579–581)', sorular: [
      ['Gümrük idari yaptırım kararları hangi durumda Türk Ceza Kanunundaki dava ve ceza zamanaşımı süreleri içinde uygulanır?',
        'Fiil **ceza uygulamasını gerektiren bir fiile** ilişkinse ve **zamanaşımı daha uzun** olan bu fiil nedeniyle **ceza davası açılmışsa**.', 'GK m.231/1', '',
        'İdari yaptırıma konu fiilin, ceza uygulamasını gerektiren bir fiile ilişkin olması ve zamanaşımı daha uzun bulunan bu fiil nedeniyle ceza davası açılmış olmak kaydıyla, idari yaptırım kararları Türk Ceza Kanunundaki dava ve ceza zamanaşımı süreleri içerisinde uygulanır.'],
      ['Gümrük vergileri alacağına bağlı idari para cezalarının zamanaşımı neye tabidir?',
        'Bu cezalara ilişkin **gümrük vergilerinin zamanaşımına** tabidir.', 'GK m.231/2', '2024',
        'Gümrük vergileri alacağına bağlı idari para cezalarının zamanaşımı, bu idari para cezalarına ilişkin gümrük vergilerinin zamanaşımına tabidir.'],
      ['Mülkiyetinin kamuya geçirilmesine karar verilen eşya bulunamazsa ne yapılır?',
        'Kaim değer olarak eşyanın **gümrüklenmiş değerinin** kamuya geçirilmesine karar verilir.', 'GK m.231/4', '',
        'Mülkiyetinin kamuya geçirilmesine karar verilen eşyanın bulunamaması hâlinde kaim değer olarak eşyanın gümrüklenmiş değerinin kamuya geçirilmesine karar verilir.'],
      ['Gümrük idaresi yükümlüye yazıyla yanlış izahat verirse idari para cezası ve faiz uygulanır mı?',
        '**Hayır**; idari para cezası **ve faiz uygulanmaz**. İzahat **karar niteliği taşımaz**, **itiraza konu olmaz**.', 'GK m.231/5; GY m.580/A-1, 9', '',
        ['Gümrük idaresi tarafından yükümlüye yazı ile yanlış izahat verilmiş olması hâlinde bu Kısım hükümlerine göre idari para cezası ve faiz uygulanmaz.', 'İzahat, karar niteliği taşımaz ve itiraza konu olmaz.']],
      ['Yanlış izahat hükmünden yararlanmak için izahat talebi hangi şartları taşımalıdır?',
        '**Yazılı**, gerekli ve yeterli bilgiyi içeren, **somut olaya** dayanan talep; başkalarının işlemlerine ilişkin olmamalı, **yargıya intikal etmemiş**, hakkında araştırma/inceleme/soruşturma bulunmayan ve **sonuçlanmamış** bir işlem olmalı; **tarife ve menşe tespitine** ve gümrük idaresinde yürütülen bir işleme ilişkin olmamalı.', 'GY m.580/A-2', '',
        ['Yükümlünün bu konuda yazılı talebinin bulunması.', 'Talep konusu işlemin yargıya intikal etmiş olmaması.', 'Talebin somut bir olaya dayanması.', 'Talebin tarife ve menşe tespitine ilişkin olmaması.', 'Talebin gümrük idaresinde yürütülen bir işleme ilişkin olmaması.']],
      ['İzahat talepleri nereye yapılır; verilen izahat ne zamandan itibaren hüküm ifade eder?',
        '**Gümrük ve dış ticaret bölge müdürlüklerine** yapılır; bölge müdürlüğü görüşüyle **Bakanlığa (Gümrükler Genel Müdürlüğü)** intikal ettirir. İzahat **bildirildiği tarihten itibaren** hüküm ifade eder.', 'GY m.580/A-4', '',
        ['İkinci fıkrada belirtilen talepler, gümrük ve dış ticaret bölge müdürlüklerine yapılır.', 'İzahat bildirildiği tarihten itibaren hüküm ifade eder.']],
      ['Gümrük Kanunu uyarınca idari yaptırım kararlarını kim verir?',
        'Gümrük idarelerinin **amirleri veya yardımcıları**; para cezasına, gümrük işleminin yapıldığı idarenin amiri/yardımcısınca **gerekçesi belirtilerek** karar verilir ve yükümlüye tebliğ edilir.', 'GK m.232/3; GY m.580/1', '',
        ['Bu Kanun uyarınca idari yaptırım kararları gümrük idarelerinin amirleri veya yardımcıları tarafından verilir.', 'Para cezalarına, gümrük işleminin yapıldığı gümrük idare amirleri veya yardımcıları tarafından gerekçesi de belirtilmek suretiyle karar verilir']],
      ['Gümrük vergileriyle birlikte alınması gereken para cezaları ne zaman tebliğ edilir ve ödenir?',
        'Vergilerle **aynı zamanda** karara bağlanarak tebliğ edilir ve **aynı zamanda ödenir**.', 'GK m.232/1', '',
        'gümrük vergileri ile birlikte alınması gereken para cezaları bu vergiler ile aynı zamanda karara bağlanarak tebliğ edilir ve aynı zamanda ödenir'],
      ['Birden fazla işlem veya beyannameye tek tahakkuk ve ceza kararı hangi şartla düzenlenebilir?',
        '**Konusu ve yükümlüsünün aynı** olması ve aralarında **maddi veya hukuki bağlılık** bulunması (GY\'ye göre ayrıca **gümrük idaresinin de aynı** olması).', 'GK m.232/2; GY m.580/3', '',
        ['Konusu ve yükümlüsünün aynı olması, aralarında maddi veya hukuki yönden bağlılık bulunması şartıyla; birden fazla işleme veya beyannameye ilişkin gümrük vergileri ve para cezalarına tek tahakkuk ve ceza kararı düzenlenebilir.', 'Konusu ve yükümlüsü ile gümrük idaresinin aynı olması']],
      ['Muhbirlere ne oranda ödeme yapılır; ikramiye hangi beyanname için verilir?',
        'Tahsil edilen İPC\'nin **yüzde onbeşi**, durumu **muayene ve tahlilden önce** ortaya çıkaran muhbire, **Müsteşarlık bütçesinden**; yalnız **ilk beyanname** için (yaygınlaştırmada verilmez). Ödemeden önce **taahhütname** alınır.', 'GK m.233/1; GY m.581', '',
        ['Bu Kanuna göre tahsil edilen idari para cezalarının yüzde onbeşi nispetinde bir tutar, varsa muayene ve tahlilden önce cezayı gerektiren durumun ortaya çıkarılmasını sağlayacak muhbirlere Müsteşarlık bütçesinin ilgili tertibinden ödenir.', 'gelir eksikliği tespit edilen ilk beyanname için yapılır', 'kendilerine ödenen tutarın geri verileceğine dair bir taahhütname alınır']],
      ['Fiil hem Gümrük Kanunu hem kaçakçılık veya diğer ceza kanunları kapsamına giriyorsa ne yapılır; daha ağır ceza verilirse GK cezası ne olur?',
        '**İdare amiri** diğer kanunlara göre de işlem yapılıp yapılmayacağını tespit eder. Daha ağır para cezası veya suçtan yaptırım kararı **kesinleşir ve para tahsil edilirse** GK\'ya göre verilen ceza **kaldırılır**, alınan para **geri verilir**.', 'GY m.579', '',
        ['idare amiri durumu inceleyerek olay dolayısıyla, aynı zamanda diğer kanunlara göre işlem yapılıp yapılmayacağını tespit eder', 'kararın kesinleşmesi ve hükmolunan paranın tahsili şartıyla Kanuna göre verilmiş olan ceza kaldırılır ve alınmış olan para geri verilir']],
    ] },
    { baslik: 'Vergi Kaybına Neden Olan İşlemler (GK m.234; GY m.582)', sorular: [
      ['Serbest dolaşıma giriş veya kısmi muafiyetli geçici ithalat eşyasında tarife unsurlarında ya da sayı, baş, ağırlık gibi ölçülerde aykırılık görülürse ceza nedir?',
        'Beyana ve muayeneye göre hesaplanan ithalat vergileri arasındaki fark **%5\'i aşarsa**, ithalat vergilerinden ayrı olarak **farkın üç katı** para cezası.', 'GK m.234/1-a', '2023',
        ['Serbest dolaşıma giriş rejimi veya kısmi muafiyet suretiyle geçici ithalat rejimine tabi tutulan eşyaya ilişkin olarak', 'arasındaki fark % 5\'i aştığı takdirde', 'ayrı olarak bu farkın üç katı para cezası alınır']],
      ['Beyan edilen kıymet, GK m.23–31\'e göre belirlenen kıymete göre noksan bulunursa ceza nedir?',
        'Noksanlığa ait ithalat vergilerinden başka **vergi farkının üç katı** para cezası.', 'GK m.234/1-b', '',
        ['belirlenen kıymete göre noksan bulunduğu takdirde', 'başka vergi farkının üç katı para cezası alınır']],
      ['Satış birimine göre miktar itibarıyla %5\'i geçmeyen farklar ile maddi hesap hatasından doğan noksan kıymet beyanlarında ceza nedir?',
        'Vergi farkının **yarısı** tutarında para cezası.', 'GK m.234/1-c', '',
        ['Satış birimine göre miktar itibarıyla % 5\'i geçmeyen bir fark ile maddi hesap hatasından doğan noksan kıymet beyanlarında', 'başka vergi farkının yarısı tutarında para cezası alınır']],
      ['DİR, GKAİR ve tam muafiyetli geçici ithalat eşyasında aynı farklılıklar tespit edilirse ceza nedir?',
        'Vergi farkının **yarısı** tutarında idari para cezası.', 'GK m.234/2', '',
        ['Dahilde işleme rejimi, gümrük kontrolü altında işleme rejimi ve tam muafiyet suretiyle geçici ithalat rejimi hükümlerine tabi eşyaya ilişkin olarak', 'vergi farkının yarısı tutarında idari para cezası verilir']],
      ['GK m.234 ve m.235/1–2\'deki aykırılıkları beyan sahibi idarenin tespitinden önce bildirirse ceza nasıl uygulanır?',
        'Cezalar **yüzde on** nispetinde (oranında) uygulanır.', 'GK m.234/3; GK m.235/6', '',
        ['Yukarıda belirtilen aykırılıkların gümrük idaresince tespit edilmesinden önce beyan sahibince bildirilmesi durumunda söz konusu cezalar yüzde on', 'beyan sahibi tarafından bildirilmesi durumunda bu fıkralara göre hesaplanan cezalar yüzde on oranında uygulanır']],
      ['Genel yönetim kapsamındaki kamu idareleri için GK m.234 cezaları uygulanır mı?',
        '**Hayır**; bu hallerde **241/1** (genel usulsüzlük cezası) hükmüne göre işlem yapılır.', 'GK m.234/4', '2025',
        'Genel yönetim kapsamındaki kamu idareleri için yukarıda belirtilen cezalara ilişkin hükümler uygulanmaz. Bu gibi hallerde, 241 inci maddenin birinci fıkra hükmüne göre işlem yapılır.'],
      ['GK m.194/1 kapsamında doğan yükümlülükte ithalat vergilerinin süresinde hiç/eksik ödenmediği kontrolde tespit edilirse ne yapılır?',
        'Vergiler **faiziyle** tahsil edilir, ayrıca **vergilerin dörtte biri** tutarında para cezası verilir; yükümlü **idarenin tespitinden önce bildirirse** bu ceza **verilmez**.', 'GK m.234/5', '',
        ['bu vergilerin dörtte biri tutarında para cezasına hükmedilir', 'yükümlüsünce gümrük idaresinin tespitinden önce bildirilmesi durumunda bu cezaya hükmedilmez']],
      ['GK m.234\'ün 1–3. fıkralarına göre verilen cezaların alt sınırı nedir?',
        '**241/1**\'de belirtilen miktardan **az olamaz**.', 'GK m.234/6', '',
        'Bir ila üçüncü fıkralara göre verilen cezalar 241 inci maddenin birinci fıkrasında belirtilen miktardan az olamaz.'],
      ['GK m.234 ceza takdirinde GTİP bilgisi yetersizse ve miktar noksanlığında neye dikkat edilir?',
        'GTİP bilgisi yetersizse pozisyondaki **en düşük vergi oranı** esas alınır; miktar noksanlığında **eşyanın tabiatı veya hava etkilerinden** doğan farklar **yükümlü lehine** dikkate alınır.', 'GY m.582', '',
        ['eşyanın girdiği tarife pozisyonundaki en düşük vergi oranı esas alınır', 'eşyanın tabiatından veya hava etkilerinden doğan farklar yükümlünün lehine olarak dikkate alınır']],
    ] },
    { baslik: 'Yasak ve İzne Tabi Eşya, Yolcu ve Transit (GK m.235)', sorular: [
      ['Serbest dolaşıma giriş rejiminde eşyanın ithalinin genel düzenleyici idari işlemle yasak olduğu tespit edilirse ceza nedir?',
        'Varsa **fark gümrük vergileri** alınır, ayrıca **gümrüklenmiş değerinin dört katı** idari para cezası verilir.', 'GK m.235/1-a', '2022',
        'Eşyanın genel düzenleyici idari işlemlerle ithalinin yasaklanmış olduğunun tespiti hâlinde, varsa eşyanın fark gümrük vergilerinin alınmasının yanı sıra, gümrüklenmiş değerinin dört katı idari para cezası verilir.'],
      ['İthali lisans, izin veya uygunluk belgesine bağlı eşya, belgeye tabi değilmiş ya da belge alınmış gibi beyan edilirse ceza nedir?',
        'Varsa fark gümrük vergileri + **gümrüklenmiş değerinin iki katı** idari para cezası (gümrük vergileri tutarında değil).', 'GK m.235/1-c', '2022',
        'eşya belge veya bilgiye tabi değilmiş ya da belge veya bilgi alınmış gibi beyanda bulunulduğunun tespit edilmesi hâlinde, varsa eşyanın fark gümrük vergilerinin alınmasının yanı sıra, gümrüklenmiş değerinin iki katı idari para cezası verilir'],
      ['İthali yasak veya izne tabi eşyanın değersiz, artık veya atık madde olması halinde ceza nasıl hesaplanır?',
        'İthali **yasak** eşyada: dökme **ton başına 30.000 TL**, ambalajlı **kap başına 600 TL**; **izne tabi** eşyada: dökme **ton başına 8.000 TL**, ambalajlı **kap başına 200 TL**; her iki halde eşya **yurtdışı edilir**.', 'GK m.235/1-b, d', '',
        ['dökme halinde gelen eşya için ton başına otuz bin Türk Lirası, ambalajlı gelmesi halinde kap başına altı yüz Türk Lirası olarak hesaplanır ve eşya yurtdışı edilir', 'dökme halinde gelen eşya için ton başına sekiz bin Türk Lirası, ambalajlı gelmesi halinde kap başına iki yüz Türk Lirası olarak hesaplanır ve eşya yurtdışı edilir']],
      ['İzne tabi eşyada Bakanlıkça belirlenen süre içinde uygunluk belgesi düzenlenir veya denetim olumlu sonuçlanırsa hangi ceza verilir?',
        'Hem ithalatta hem ihracatta **241/1** uyarınca idari para cezası.', 'GK m.235/1-e; m.235/2-c', '',
        ['Bakanlıkça belirlenecek süre içerisinde, (c) bendinde belirtilen eşyanın ithalinin uygun bulunduğuna ilişkin belge veya bilginin düzenlenmesi', '241 inci maddenin birinci fıkrası uyarınca idari para cezası verilir']],
      ['İhracat rejiminde eşyanın ihracının genel düzenleyici idari işlemle yasak olduğu tespit edilirse ceza nedir?',
        '**Gümrüklenmiş değerinin iki katı** idari para cezası.', 'GK m.235/2-a', '2024',
        'Eşyanın genel düzenleyici idari işlemlerle ihracının yasaklanmış olduğunun tespiti halinde, eşyanın gümrüklenmiş değerinin iki katı idari para cezası verilir.'],
      ['İhracı izne tabi eşya, belgeye tabi değilmiş ya da belge alınmış gibi beyan edilirse ceza nedir?',
        '**Gümrüklenmiş değerinin onda biri** kadar idari para cezası.', 'GK m.235/2-b', '',
        'gümrüklenmiş değerinin onda biri kadar idari para cezası verilir'],
      ['Yolcunun kişisel ve hediyelik eşya kapsamı dışında olup beyanına aykırı çıkan eşyası için ne uygulanır?',
        'Eşyanın **gümrük vergileri iki kat** alınır ve eşya sahibine teslim edilir; vergiler ödenmezse eşya **gümrüğe terk edilmiş sayılır**.', 'GK m.235/3', '',
        ['eşyanın gümrük vergileri iki kat olarak alınır ve eşya sahibine teslim edilir', 'Gümrük vergileri ödenmediği takdirde, eşya gümrüğe terk edilmiş sayılır.']],
      ['İthali yasak eşya hakkında yükümlü talebiyle ne kadar sürede ne yapılabilir; süre geçerse ne olur?',
        '**Otuz gün** içinde **mahrecine iade** veya ilgili kurumun uygun görüşüyle doğrudan **üçüncü ülkeye transit**; yapılmazsa ihraç kaydıyla satış ya da masrafı sahibince karşılanarak **imha** suretiyle tasfiye için **gümrük idaresine terk** edilir.', 'GK m.235/4-a', '2025',
        ['yükümlü talebi doğrultusunda otuz gün içinde mahrecine iade ya da ilgili kurum ya da kuruluşun uygun görüşü ile doğrudan üçüncü ülkeye transit edilir', 'ihraç kaydıyla satış ya da masrafları sahibince karşılanmak koşuluyla imha suretiyle tasfiye edilmek üzere bulunduğu gümrük idaresine terk edilir']],
      ['Karayoluyla transit edilen serbest dolaşımda olmayan eşya, beyandan belirgin şekilde farklı cinste çıkarsa ceza nedir?',
        'Farklı eşyanın vergileri **daha yüksekse**: farklı eşyanın **gümrük vergilerinin iki katı**; farklı eşya **izne/lisansa tabiyse**: **gümrüklenmiş değerinin iki katı** idari para cezası.', 'GK m.235/5-a, b', '',
        ['beyan edilenden belirgin bir şekilde farklı cinste olduğunun tahlil, teknik inceleme ve araştırmaya gerek olmaksızın tespiti hâlinde', 'farklı çıkan eşyaya ilişkin gümrük vergilerinin iki katı idari para cezası verilir', 'farklı çıkan eşyanın gümrüklenmiş değerinin iki katı idari para cezası verilir']],
      ['Transit rejimindeki eşyada beyana göre eksik veya fazla tespit edilirse ceza nedir?',
        '**Eksik**: vergiler alınır + **gümrük vergilerinin iki katı** İPC; **fazla**: fazla eşyanın **gümrük vergileri kadar** İPC ve eşya **tasfiye** edilir.', 'GK m.235/5-c, d', '',
        ['eksik çıkan eşyaya ilişkin gümrük vergilerinin alınmasının yanı sıra eşyanın gümrük vergilerinin iki katı idari para cezası verilir', 'fazla çıkan eşyanın gümrük vergileri kadar idari para cezası verilir ve fazla çıkan eşya 177 ila 180 inci madde hükümlerine göre tasfiyeye tabi tutulur']],
    ] },
    { baslik: 'Antrepo ve Gümrüksüz Satış Mağazaları (GK m.236)', sorular: [
      ['Antrepodan izinsiz eşya çıkarılması, eşyanın değiştirilmesi veya sayımda noksan çıkması halinde ceza nedir; teminat alınmış olması sonucu değiştirir mi?',
        'Gümrük vergilerinin yanı sıra **gümrüklenmiş değerinin iki katı** İPC; **teminat alınmış olsa bile** uygulanır.', 'GK m.236/1', '',
        ['Teminat alınmış olsa bile', 'bu eşyanın gümrük vergilerinin yanı sıra gümrüklenmiş değerinin iki katı idari para cezası verilir']],
      ['Antrepo sayımında kayıtlara göre fazla eşya çıkarsa ne uygulanır?',
        'Eşya **tasfiyeye** tabi tutulur ve fazla eşyanın **ithalat veya ihracat vergileri tutarı kadar** para cezası alınır.', 'GK m.236/2', '2024',
        'bu eşyanın 177 ila 180 inci madde hükümlerine göre tasfiyeye tabi tutulmasının yanı sıra, fazla çıkan eşyaya ait ithalat veya ihracat vergileri tutarı kadar para cezası alınır'],
      ['Gümrüksüz satış mağazasından hak sahibi olmayana veya limit üstü satış yapılırsa ceza nedir?',
        'İlgili eşyanın ithalat vergileri + **bu vergilerin üç katı** para cezası.', 'GK m.236/4', '',
        'Gümrüksüz satış mağazalarından hak sahibi olmayanlara satış yapılması halinde satışa konu eşyaya, hak sahibi olmakla birlikte limit üstü satış yapılması halinde de limit üstü eşyaya ait ithalat vergilerinin yanı sıra bu vergilerin üç katı para cezası verilir.'],
      ['Antrepo beyannamesinde beyan edilenden belirgin şekilde farklı cinste eşya çıkarsa ceza nedir?',
        'Farklı eşyanın vergileri fazlaysa **vergilerinin iki katı**; farklı eşya **izne/lisansa tabiyse** **gümrüklenmiş değerinin iki katı** İPC.', 'GK m.236/5', '2022',
        ['antrepo beyannamesinde beyan edilenden belirgin bir şekilde farklı cinste eşya olduğunun tahlil, teknik inceleme ve araştırmaya gerek olmaksızın tespiti hâlinde', 'farklı çıkan eşyanın gümrüklenmiş değerinin iki katı idari para cezası verilir']],
    ] },
    { baslik: 'Özet Beyan Eksiklik ve Fazlalıkları (GK m.237; GY m.583)', sorular: [
      ['Özet beyana göre noksan çıkan kaplar için süresinde kanıt sunulamazsa ceza nasıl belirlenir?',
        'Mahrecinde yüklenmeme, yanlışlıkla başka yere çıkarılma, kaza/avarya veya çalınma kanıtlanamazsa: tarife pozisyonuna (tespit edilemezse faslın **en yüksek vergiye tabi** pozisyonuna) göre **gümrük vergileri kadar**; bu da belirlenemiyorsa **noksan her kap için 241/1** miktarı.', 'GK m.237/1–2', '',
        ['tarifede dahil olduğu faslın en yüksek vergiye tabi pozisyonuna göre hesaplanacak gümrük vergileri', '1 inci fıkraya göre ceza belirlenmesi mümkün olamıyorsa, noksan her kap için 241 inci maddenin 1 inci fıkrasında belirlenen miktarda para cezası alınır.']],
      ['Özet beyana göre fazla çıkan kapların yanlışlıkla fazla yüklendiği süresinde kanıtlanamazsa ne olur?',
        'Eşyaya **el konularak** mülkiyeti **kamuya geçirilir**, **tasfiye** edilir ve **CIF kıymeti kadar** para cezası alınır.', 'GK m.237/3', '',
        ['söz konusu eşyaya el konularak mülkiyetinin kamuya geçirilmesine karar verilir, 177 ila 180 inci madde hükümlerine göre tasfiyeye tabi tutulur', 've eşyanın CIF kıymeti kadar para cezası alınır']],
      ['Dökme eşyada hangi oranlardaki eksiklik ve fazlalıklar için takibat yapılmaz?',
        'Eşya cinsi itibarıyla **Cumhurbaşkanı** kararıyla belirlenen, **%3\'ü aşmayan** oranlar; **doğalgaz ürünlerinde** (boru hattıyla ithal edilenler hariç) **%6\'yı aşmayan** oran.', 'GK m.237/4', '',
        ['Dökme gelen eşyada yüzde üçü aşmayacak şekilde eşya cinsi itibarıyla Cumhurbaşkanı', 'Doğalgaz ürünlerinde boru hatları ile taşınarak ithal edilenler hariç bu oran % 6\'yı']],
      ['Miktarı idarece tespit edilmeyip belgelere göre beyan edilen eşyada çıkan miktar farkları nasıl değerlendirilir; GK m.234 uygulanır mı?',
        '**Özet beyan eksiklik/fazlalığı** olarak değerlendirilir; cezayı gerektiren durumda **234 uygulanmaz**, sadece **237** uygulanır.', 'GK m.237/5', '',
        ['tespit edilen miktar farklılıkları özet beyan eksiklik veya fazlalığı olarak değerlendirilir', '234 üncü madde hükümleri uygulanmayarak sadece bu madde hükümlerine göre işlem yapılır']],
      ['Özet beyan verilmeksizin TGB\'ye eşya getirildiği tespit edilirse ne uygulanır; para cezaları kimden alınır?',
        'Eşya **kamuya geçirilir**, tasfiye edilir ve **CIF kıymeti kadar** ceza verilir; bu ceza **özet beyan vermekle yükümlü** kişiden, tespit edilemezse **eşyayı TGB\'ye getiren** kişiden alınır. Noksan/fazla kap cezaları ise **özet beyanı veren** kişiden alınır.', 'GK m.237/6–7', '',
        ['Ayrıca eşyanın CIF kıymeti kadar para cezası verilir.', 'Birinci, ikinci ve üçüncü fıkralarda belirtilen para cezaları özet beyanı veren kişiden, altıncı fıkrada belirtilen para cezası ise özet beyanı vermekle yükümlü olduğu tespit edilen kişiden, bu kişinin tespit edilememesi halinde eşyayı Türkiye Gümrük Bölgesine getiren kişiden alınır.']],
      ['Kap adedi tamam olup sayı, baş, ağırlık gibi ölçülerde eksiklik veya fazlalık bulunan eşya için özet beyan takibatı yapılır mı?',
        '**Hayır**, takibat yapılmaz. (Dökme/dökme olmayan ayrımında eşyanın miktar ve niteliği ile **sayılabilir** olması esas alınır.)', 'GY m.583/1–2', '',
        ['Kap adedi itibariyle tamam çıkan ancak sayı, baş, ağırlık gibi ölçülerinde eksiklik veya fazlalık olan eşya için takibat yapılmaz.', 'eşyanın miktar ve niteliği ile sayılabilir olması esas alınır']],
    ] },
    { baslik: 'İşleme ve Geçici İthalat Rejimi İhlalleri (GK m.238)', sorular: [
      ['DİR, GKAİR ve geçici ithalat rejimi hükümlerinin ihlalinde ceza nedir?',
        'Eşyanın **gümrüklenmiş değerinin iki katı** idari para cezası.', 'GK m.238/1-a', '2025',
        ['Dahilde işleme rejimi, gümrük kontrolü altında işleme rejimi ile geçici ithalat rejimine ilişkin hükümlerin ihlali hâlinde, eşyanın gümrüklenmiş değerinin iki katı', 'idari para cezası verilir']],
      ['Tam muafiyetle geçici ithal edilen özel kullanıma mahsus taşıtlara ilişkin rejim ihlallerinde ceza nedir?',
        '**Gümrük vergileri tutarının dörtte biri.**', 'GK m.238/1-b', '',
        'Tam muafiyet suretiyle geçici olarak ithal edilen özel kullanıma mahsus taşıtlara ilişkin rejim ihlallerinde, gümrük vergileri tutarının dörtte biri'],
      ['DİR/GKAİR ihlal edilmekle birlikte eşyanın gümrük gözetiminden çıkarılmadığı tespit edilirse (veya geçici ithalat eşyası süresinde onaylanmış işleme tabi tutulmazsa) ceza nedir?',
        '**Gümrük vergileri** ile beyannamenin **tescil tarihinden tespit tarihine** kadar **6183 sayılı Kanuna göre gecikme zammı oranında faizin toplamı** kadar İPC.', 'GK m.238/1-c, d', '',
        ['gümrük gözetiminden mevzuata aykırı olarak çıkarılmamış olduğunun tespiti hâlinde', 'rejime ilişkin beyannamenin tescil tarihinden tespitin yapıldığı tarihe kadar geçen süre için 6183 sayılı Kanuna göre tespit edilen gecikme zammı oranında faizin toplamı kadar']],
      ['GK m.238/1-c ve d kapsamındaki eşya, tebligattan itibaren ne kadar sürede onaylanmış işleme tabi tutulmazsa ek ceza verilir?',
        '**Altmış gün** içinde; tabi tutulmazsa ayrıca **gümrük vergileri tutarında** İPC.', 'GK m.238/2', '',
        'yapılacak tebligat tarihinden itibaren altmış gün içinde gümrükçe onaylanmış başka bir işlem veya kullanıma tabi tutulmaması hâlinde, ayrıca gümrük vergileri tutarında idari para cezası verilir'],
      ['GK m.238/1 cezaları hangi usulsüzlük hallerinde uygulanmaz?',
        '**241/3-(h), (l), (m)**; **241/4-(g), (h)** ve **241/5-(b)** bentlerindeki durumlarda.', 'GK m.238/1', '',
        '241 inci maddenin üçüncü fıkrasının (h), (l) ve (m) bentleri, dördüncü fıkrasının (g) ve (h) bentleri ile beşinci fıkrasının (b) bendinde belirtilen durumlar hariç'],
      ['GK m.238/1 cezalarının alt sınırı nedir; genel yönetim kapsamındaki kamu idarelerine ne uygulanır?',
        'Cezalar **241/6**\'da belirtilen miktardan **az olamaz**; kamu idarelerine 238 para cezaları uygulanmaz, **241/1** uygulanır.', 'GK m.238/3–4', '',
        ['Birinci fıkraya göre verilen cezalar 241 inci maddenin altıncı fıkrasında belirtilen miktardan az olamaz.', 'Bu durumda, 241 inci maddenin birinci fıkra hükmü uygulanır.']],
    ] },
    { baslik: 'Usulsüzlük Cezaları (GK m.239–241)', sorular: [
      ['Gümrük Kanununda para cezaları hangi bölümler altında düzenlenmiştir?',
        '**İkinci Bölüm: Vergi Kaybına Neden Olan İşlemlere Uygulanacak Cezalar** (m.234–238); **Üçüncü Bölüm: Usulsüzlüklere İlişkin Cezalar** (m.239–241). Vergi kaybı bölümü dışındaki bu cezalar **usulsüzlük cezası**dır.', 'GK m.234–241 (bölüm başlıkları)', '2023',
        ['Vergi Kaybına Neden Olan İşlemlere Uygulanacak Cezalar', 'Usulsüzlüklere İlişkin Cezalar']],
      ['Vergiden muaf eşyayı belirlenen gümrük kapıları dışından izinsiz ithal/ihraç edenlere veya buna teşebbüs edenlere ceza nedir?',
        'İthalatta **CIF**, ihracatta **FOB** değerinin **onda biri** oranında para cezası.', 'GK m.239/1', '2023',
        'söz konusu eşyanın ithalata konu olması halinde, CIF değerinin, ihracata konu olması halinde ise FOB değerinin onda biri oranında para cezası alınır'],
      ['Gümrük vergileri ödenerek ihraç edilebilen eşyayı işlem yaptırmadan veya vergileri ödemeden TGB\'den çıkaranlara ceza nedir?',
        'Gümrük vergilerinin yanı sıra **bu vergilerin iki katı** İPC.', 'GK m.239/2', '',
        'eşyanın gümrük vergilerinin yanı sıra bu vergilerin iki katı idari para cezası verilir'],
      ['Genel usulsüzlük cezası (GK m.241/1) hangi şartla ve hangi tutarda uygulanır?',
        'Kanunda ayrı ceza tayin edilmiş haller saklı kalmak üzere, düzenlemede **açıkça öngörülmüş olması kaydıyla** **altmış TL** usulsüzlük cezası.', 'GK m.241/1', '',
        ['Bu Kanunda ayrı bir ceza tayin edilmiş haller saklı kalmak üzere', 'aykırı hareket edenlere söz konusu düzenlemelerde açıkça öngörülmüş olması kaydıyla altmış TL']],
      ['GK m.241/1\'deki usulsüzlük cezası tutarı nasıl güncellenir?',
        '**Her yıl**, bir önceki yıl için **213 sayılı VUK** uyarınca belirlenen **yeniden değerleme oranında** artırılır.', 'GK m.241/2', '2022, 2024, 2025',
        '1 inci fıkrada belirtilen miktar, her yıl, bir önceki yıla ilişkin olarak 213 sayılı Vergi Usul Kanunu uyarınca belirlenen yeniden değerleme oranında arttırılır'],
      ['GK m.6–7\'ye göre idarece verilen kararlara dayanak belge ve bilgilerin ilgililerce yanlış verilmesi hangi cezayı gerektirir?',
        '241/1 miktarının **iki katı** usulsüzlük cezası.', 'GK m.241/3-a', '2025',
        ['Usulsüzlük cezası aşağıdaki hallerde 1 inci fıkrada belirtilen miktarın iki katı olarak uygulanır', 'gümrük idarelerince verilen kararlara dayanak oluşturan belge ve bilgilerin, ilgili kişiler tarafından yanlış olarak verilmesi']],
      ['Vergi kaybı doğurmasa da ilişkili kişiler arasındaki satışta ilişkinin beyan edilmemesi hangi cezayı gerektirir?',
        '241/1 miktarının **iki katı** usulsüzlük cezası.', 'GK m.241/3-b', '2023, 2024',
        'Vergi kaybı doğurmamasına karşın, 24 üncü maddeye göre birbirleriyle ilişkisi bulunan kişiler arasında bir satış işlemi olması ve bu ilişkinin beyan edilmemesi'],
      ['Gemilerin geliş-gidişinde süresinde bilgi verilmemesi ve özet beyanın süresinde verilmemesi hangi cezayı gerektirir?',
        'Her ikisi de **iki kat** usulsüzlük cezası (gemi bilgisi **donatan, işleten veya acenta** tarafından verilir).', 'GK m.241/3-c, d', '',
        ['yönetmelikle belirlenecek süreler içerisinde donatan veya işleten veya acentası', 'özet beyan veya özet beyan olarak kullanılan ticari veya resmi belgenin süresi içinde verilmemesi']],
      ['İhraç eşyasında beyan ve eki belgelere göre miktar veya cinste ne kadar farklılık iki kat usulsüzlük cezası gerektirir?',
        '**%10\'dan fazla** farklılık (Kaçakçılıkla Mücadele Kanunu hükümleri saklı).', 'GK m.241/3-j', '2024',
        'ihraç eşyasının yapılan beyan ve eki belgelere göre miktar veya cinsinde % 10\'dan fazla farklılık çıkması'],
      ['Geçici ithalat eşyasının idareye bilgi verilmeden ancak süresi içinde TGB dışına çıkarıldığının belgelerle kanıtlanması hangi cezayı gerektirir?',
        '**İki kat** usulsüzlük cezası.', 'GK m.241/3-m', '2024',
        'Geçici ithalat rejimi kapsamında ithal edilen eşyanın gümrük idaresine bilgi verilmeden, ancak süresi içerisinde Türkiye Gümrük Bölgesinin dışına çıkarıldığının kabul edilebilir belgelerle kanıtlanması'],
      ['Geçerli temsil yetkisi olmadan başkası adına veya hesabına gümrükte iş takibi hangi cezayı gerektirir?',
        '241/1 miktarının **dört katı** usulsüzlük cezası.', 'GK m.241/4-a', '2023',
        ['Usulsüzlük cezası aşağıdaki hallerde 1 inci fıkrada belirtilen miktarın dört katı olarak uygulanır', 'Bir kişinin 5 inci madde hükümlerine göre geçerli bir temsil yetkisi olmadığı halde başka bir kişi adına veya hesabına gümrük idarelerinde iş takip etmesi']],
      ['Antrepodaki eşyanın idarenin izni olmaksızın GK m.102\'deki elleçlemelere tabi tutulması hangi cezayı gerektirir?',
        '**Dört kat** usulsüzlük cezası.', 'GK m.241/4-f', '2022',
        'Gümrük antrepolarında bulunan eşyanın gümrük idarelerinin izni olmaksızın 102 nci maddede belirtilen elleçlemelere tabi tutulması'],
      ['Antrepolarla ilgili diğer usulsüzlüklerde ceza katları nedir?',
        'Teknik donanım **noksanlığı** ve eşyanın konulduğu tarihte işleticice **kayda geçirilmemesi**: **iki kat**; parlayıcı/patlayıcı/tehlikeli eşyanın **genel amaçlı yerlerde depolanması**: **dört kat**.', 'GK m.241/3-f, g; m.241/4-e', '',
        ['teknik donanımlarında noksanlık bulunması', 'antrepolara konuldukları tarihte işleticiler tarafından kayıtlara geçirilmemesi', 'genel amaçlı eşya konulan yerlerde depolanması']],
      ['Karayolu taşıtının izinsiz yük/yolcu alarak yoluna devam etmesi ve özet beyanda eşya cinsinin yanlış beyan edilmesi hangi cezayı gerektirir?',
        'Her ikisi de **dört kat** usulsüzlük cezası (m.45/1\'e aykırı boşaltma ile kap türü, numara ve işaretlerin özet beyana uymaması da dört kat).', 'GK m.241/4-b, c', '',
        ['karayolu taşıtlarının gümrük idaresinin izni olmadan yük veya yolcu alarak yoluna devam etmesi', 'özet beyan veya özet beyan olarak kullanılan ticari ve resmi belgelerde kayıtlı eşyanın cinsinin yanlış beyan edilmesi']],
      ['Karayoluyla transit eşya taşıyan taşıtların GK m.91\'deki süreleri aşmasında usulsüzlük cezası kademeleri nelerdir?',
        '**24 saate kadar**: iki kat; **48 saate kadar**: dört kat; **72 saate kadar**: altı kat; **72 saatten fazla**: sekiz kat.', 'GK m.241/3-e; 4-d; 5-a; 6-c', '',
        ['süreleri yirmidört saate kadar aşması', 'süreleri kırksekiz saate kadar aşması', 'süreleri yetmişiki saate kadar aşması', 'süreleri yetmişiki saatten daha fazla bir süre ile aşması']],
      ['DİR/GKAİR ve geçici ithalat eşyasında süre bitiminden sonra işlemlerin tamamlanmasında usulsüzlük cezası kademeleri nelerdir?',
        'Süre bitimini takiben **bir ay içinde**: **iki kat**; **iki ayı aşmayan** sürede: **dört kat**; geçici ithalat **taşıtlarında üç ayı aşmayan** sürede: **altı kat**.', 'GK m.241/3-h, l; 4-g, h; 5-b', '',
        ['izin verilen süresinin bitimini takiben bir ay içerisinde rejimin gerektirdiği işlemlerinin bitirilmesi', 'verilen sürenin bitimini takiben iki ayı aşmayan sürede yeniden ihraç edilmesi', 'taşıtlara verilen sürenin bitimini takiben üç ayı aşmayan sürede yeniden ihraç edilmesi']],
      ['Taşıt araçlarının GK m.33 ve 91\'de belirtilen önceden belirlenmiş yollar (güzergâh) dışında seyretmesi hangi cezayı gerektirir?',
        '241/1 miktarının **sekiz katı** usulsüzlük cezası.', 'GK m.241/6-b', '2022',
        ['Usulsüzlük cezası aşağıdaki hallerde 1 inci fıkrada belirtilen miktarın sekiz katı olarak uygulanır', 'Taşıt araçlarının 33 üncü ve 91 inci maddede belirtilen önceden belirlenmiş yollar dışında seyretmesi']],
      ['Sekiz kat usulsüzlük cezası gerektiren diğer haller nelerdir?',
        'TGB\'ye giren **gemilerin rota değiştirmesi**, yolda durması, başka gemilerle temas etmesi vb.; m.11\'e göre istenen bilgi-belgeler ile **beş yıl saklanması gereken** belgelerin kontrolde **ibraz edilmemesi**; geçici ithalattaki **yabancı plakalı taşıtın** sahibinin bilgi vermeden **taşıtsız** yurt dışına çıkması.', 'GK m.241/6-a, d, e', '',
        ['Türkiye Gümrük Bölgesine giren gemilerin rota değiştirmesi, yolda durması, başka gemilerle temas etmesi', '13 üncü madde hükmü uyarınca beş yıl süreyle saklanması gereken belgelerin gümrük kontrolü sırasında ibraz edilmemesi', 'gümrük idaresine bilgi verilmeden taşıtsız yurt dışına çıkılması']],
      ['GK m.218/3 uyarınca Bakanlıkça belirlenen azami bedellere uyulmaması halinde ceza nedir?',
        'Her bir işlem için **beş bin TL** usulsüzlük cezası.', 'GK m.241/7', '',
        'Bakanlıkça belirlenen azami bedellere uyulmaması halinde her bir işlem için beş bin Türk lirası usulsüzlük cezası uygulanır'],
    ] },
  ],
  tuzaklar: [
    '**Gümrüklenmiş değerin dört katı** yalnız **ithali yasak** eşyada (235/1-a). İzne tabi eşyada ithalatta **iki katı** (235/1-c), ihracatta **onda biri** (235/2-b); **ihracı yasak** eşyada **iki katı** (235/2-a).',
    'GK m.234: %5\'i aşan tarife/ölçü farkı ve kıymet noksanlığı → **farkın üç katı**; %5\'i geçmeyen miktar farkı, maddi hata ve DİR/GKAİR/tam muafiyetli GİR → **yarısı**; 194/1 ödenmeme → **dörtte biri**. Tespitten önce bildirim → **yüzde on** (194/1\'de ise **hiç ceza yok**).',
    'Alt sınırlar: 234 cezaları **241/1**, 238/1 cezaları **241/6** miktarından az olamaz. Genel yönetim kapsamındaki kamu idarelerine 234 ve 238 cezaları yerine **241/1** uygulanır.',
    'Transit süre aşımı: **24 saat → 2 kat**, **48 saat → 4 kat**, **72 saate kadar → 6 kat**, **72 saatten fazla → 8 kat**. Güzergâh dışına çıkma ve gemi rota değiştirme → **8 kat**.',
    'Rejim süre aşımı: DİR/GKAİR/GİR **1 ay içinde → 2 kat**, **2 ayı aşmayan → 4 kat**; GİR **taşıtında 3 ayı aşmayan → 6 kat**. Bunlar 238/1 cezasının **dışında** tutulur.',
    'Antrepo: izinsiz çıkarma/değiştirme/sayımda **noksan** → vergiler + **gümrüklenmiş değerin iki katı**; sayımda **fazla** → tasfiye + **vergiler kadar** ceza; izinsiz **elleçleme → 4 kat**, teknik donanım noksanı/kayda geçirmeme → **2 kat** usulsüzlük.',
    'Özet beyan: noksan kap → **vergiler kadar** (belirlenemezse kap başına **241/1**); fazla kap ve özet beyansız eşya → kamuya geçirme + **CIF kıymeti kadar**; dökme eşyada **%3** (doğalgaz **%6**) tolerans. Muaf eşyanın kaçak giriş/çıkışı ise **CIF/FOB değerinin onda biri** (239/1).',
    '**İki kat** usulsüzlük: karara dayanak yanlış belge, ilişkinin beyan edilmemesi, ihraçta **%10\'dan fazla** fark, GİR eşyasının bilgi vermeden süresinde çıkışı; **dört kat**: yetkisiz temsil, izinsiz elleçleme. Muhbire **%15**; yolcu eşyasında vergiler **iki kat**; gümrüksüz satışta vergilerin **üç katı**.',
  ],
};
