// 39. Konu — Gümrük Vergisinden Muafiyetler (kaynak: 39-muafiyetler.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '39',
  konu: 'Gümrük Vergisinden Muafiyetler',
  kaynak: '39-muafiyetler.docx (GK m.167; GY m.438–443; Karar (2009/15481) m.45–112; Gümrük Muafiyeti Tebliği (Seri No: 2) m.1–42)',
  bolumler: [
    { baslik: 'Muafiyet ve İstisna Halleri (GK m.167)', sorular: [
      ['GK m.167\'nin ilk iki bendinde hangi eşya gümrük vergilerinden muaf tutulmuştur?',
        '(1) **Cumhurbaşkanının zat ve ikametgahı** için gelen eşya; (2) **mütekabiliyet esasına** göre ithal edilen **diplomatik eşya**.', 'GK m.167/1-1, 1-2', '',
        ['Cumhurbaşkanının zat ve ikametgahı için gelen eşya', 'Mütekabiliyet esasına göre ithal edilen diplomatik eşya']],
      ['GK m.167/1-3 kapsamında hangi kurumların ithalatı muaftır?',
        'Genelkurmay, MSB, kuvvet komutanlıkları, MİT, **Savunma Sanayii Başkanlığı**, Jandarma, Sahil Güvenlik ve EGM (**münhasıran asli görevleri**); **MKE A.Ş.** (faaliyet alanı) ve Müsteşarlığın **kaçakçılıkla mücadele** görevi.', 'GK m.167/1-3', '',
        ['Genelkurmay Başkanlığı, Milli Savunma Bakanlığı, kuvvet komutanlıkları, Milli İstihbarat Teşkilatı Müsteşarlığı, Savunma Sanayii Başkanlığı', 'Jandarma Genel Komutanlığı, Sahil Güvenlik Komutanlığı ve Emniyet Genel Müdürlüğünün münhasıran asli görevleri ile Makine ve Kimya Endüstrisi Anonim Şirketinin faaliyet alanı', 'Müsteşarlığın kaçakçılıkla mücadele görevi ile ilgili olarak ithal edecekleri']],
      ['GK m.167\'ye göre değeri en fazla ne kadar olan eşya gümrük vergilerinden muaftır?',
        'Değeri **150 Euro**\'yu geçmeyen eşya.', 'GK m.167/1-4', '',
        'Değeri 150[145] EURO\' yu  geçmeyen  eşya'],
      ['GK m.167/1-5\'teki "şahsi eşya" kapsamında hangi eşyalar sayılmıştır; kişisel eşya ile aynı mıdır?',
        'Alındığı tarihte **3 yaşından büyük olmayan** kullanılmış taşıt, kullanılmış **ev eşyası**, **çeyiz**, **miras** yoluyla gelen kişisel eşya, **öğrenci** eşyası, **geri getirilen** ev eşyası, yurt dışı yerleşiklerin **konut** eşyası ve **(h) yolcuların kişisel eşyası**. Kişisel eşya şahsi eşyanın **yalnızca bir bendidir**; kapsamları aynı değildir.', 'GK m.167/1-5', '2022',
        ['Gerçek kişiler tarafından serbest dolaşıma sokulacak şahsi eşyadan;', 'alındığı tarihte üç yaşından büyük olmayan kullanılmış motorlu veya motorsuz özel nakil vasıtaları', 'Yerleşim yerlerini Türkiye Gümrük Bölgesine nakleden gerçek kişilere ait her türlü kullanılmış ev eşyası', 'h) Yolcuların kendi kullanımlarına mahsus ticari mahiyette olmayan kişisel eşya']],
      ['GK m.167/1-6\'ya göre gerçek kişilerce serbest dolaşıma sokulacak "diğer eşya"dan muaf olanlar nelerdir?',
        'Değeri **430 Euro**\'yu geçmeyen yolcu beraberi **hediyelik eşya**, **şeref nişanları veya ödülleri**, **uluslararası ilişkiler** çerçevesinde alınan hediyeler.', 'GK m.167/1-6', '',
        ['Değeri 430 EURO\'yu geçmemek üzere yolcuların beraberindeki hediyelik eşya', 'Şeref nişanları veya ödülleri', 'Uluslararası ilişkiler çerçevesinde alınan hediyeler']],
      ['GK m.167/1-7\'ye göre Cumhurbaşkanınca belirlenecek kişi ve kurumlarca ticari gaye güdülmeden ithal edilen hangi eşya muaftır?',
        'Eğitim, bilim ve kültürel amaçlı eşya ile bilimsel alet-cihazlar; **tıbbi** teşhis, tedavi ve araştırma alet-cihazları; bilimsel araştırma hayvanları ve biyolojik/kimyasal maddeler; insan kaynaklı tedavi edici maddeler ve kan/doku belirteçleri; **ilaç kalite kontrolü** maddeleri; ulusal **Ar-Ge** kurumlarının faaliyetlerinde kullanılacak eşya.', 'GK m.167/1-7', '2021',
        ['Cumhurbaşkanınca[150] belirlenecek kişi, kurum ve kuruluşlar tarafından ticari gaye güdülmemek ve amacı doğrultusunda kullanılmak üzere ithal edilen eşyadan', 'Tıbbi teşhis, tedavi ve araştırma yapılmasına mahsus alet ve cihazlar', 'İlaç özelliği olan ürünlerin kalite kontrolü amacına yönelik maddeler', 'Ulusal araştırma geliştirme kurumları tarafından yürütülen veya desteklenen araştırma ve geliştirme faaliyetlerinde kullanılmak üzere ithal edilen eşya']],
      ['Bir ticari faaliyetin yürütülmesiyle bağlantılı ithalatta sermaye malları hangi halde muaftır?',
        'Yalnızca **işyeri nakli suretiyle** ithal edildiğinde (sermaye malları ve diğer malzemeler).', 'GK m.167/1-8-a', '2021',
        ['Bir ticari faaliyetin yürütülmesi ile bağlantılı ithalat;', 'İşyeri nakli suretiyle ithal edilen sermaye malları ve diğer malzemeler']],
      ['GK m.167/1-9\'a göre ulaştırmacılıkta kullanılan hangi eşya muaftır?',
        'İstif/koruma **yardımcı maddeleri**; canlı hayvan nakli için **kuru ot, yem** ve ilaçlar; ulaşım araçları ve özel konteynerlerdeki **akaryakıt ve madeni yağ**; deniz/hava araçlarının **donatım ve işletme malzemesi**; **1/7/2010**\'dan itibaren hava yolu şirketlerinin **hava taşıtları**, motorları, aksam ve parçaları.', 'GK m.167/1-9', '',
        ['Ulaşım araçları ile özel konteynerlerde mevcut bulunan akaryakıt ve madeni yağları', 'Deniz ve hava ulaşım araçlarına ait donatım ve işletme malzemesi', '1/7/2010 tarihinden itibaren geçerli olmak üzere, yolcu ve yük taşımacılığı faaliyetlerinde bulunan hava yolu şirketlerinin']],
      ['GK m.167/1-10\'a göre bilgi materyali ithalatı kapsamında hangi eşya muaftır?',
        '**Yayın hakları veya endüstriyel ve ticari patent haklarını koruyan örgütlere** gönderilen eşya, **turistik reklamcılık** malzemeleri, **ticari değeri olmayan** çeşitli belge ve eşya.', 'GK m.167/1-10', '2021',
        ['Yayın hakları veya endüstriyel ve ticari patent haklarını koruyan örgütlere gönderilen eşya', 'Turistik reklamcılık malzemeleri', 'Ticari değeri olmayan çeşitli belge ve eşya']],
      ['GK m.167/1-12\'deki "diğer eşya" nelerdir; hangi olaylar kriz hali sayılmıştır?',
        'Malul ve engellilerin eşyası; **kriz hallerinden** (tabii afet, salgın hastalık, büyük yangın, radyasyon ve hava kirliliği gibi kimyasal-teknolojik olaylar, **büyük nüfus hareketleri**) zarar görenlere gönderilen eşya; uluslararası spor müsabakaları için **eczacılık ürünleri**.', 'GK m.167/1-12', '',
        ['Malül ve engellilerin[151] kullanımına mahsus eşya', 'Tabiî  afetler, tehlikeli ve salgın hastalıklar, büyük yangınlar, radyasyon ve hava kirliliği gibi önemli nitelikteki kimyasal ve teknolojik olaylar ile büyük nüfus hareketleri gibi kriz hallerinden zarar görenlere gönderilen eşya', 'Türkiye\'de düzenlenen uluslararası spor müsabakalarında kullanılmak üzere getirilen eczacılık ürünleri']],
      ['GK m.167\'nin (3)–(12) numaralı bentleri için Cumhurbaşkanının yetkileri nelerdir?',
        'Eşyayı **geliş süreleri dahil** tanımlama, cins/nevi/miktar belirleme, muafiyet tutarlarını **sıfıra kadar indirme veya iki katına kadar çıkarma**, ticari mahiyette olmayan eşyaya **tek ve maktu tarife** uygulama.', 'GK m.167/2', '',
        ['Birinci fıkranın (3) ila (12) numaralı bentlerinde yer alan eşyayı geliş süreleri dâhil tanımlamaya', 'muafiyet ve istisna uygulanacak tutarları sıfıra kadar indirmeye veya iki katına kadar çıkartmaya', 'tek ve maktu bir tarife uygulamaya Cumhurbaşkanı[153] yetkilidir']],
    ] },
    { baslik: 'Diplomatik Muafiyetler (GY m.438–442)', sorular: [
      ['Milletlerarası resmi kuruluşların hangi personeli diplomatik muafiyetten yararlanabilir?',
        'Yalnızca **Türkiye\'de ikamet eden** misyon şefleri, diplomatik memurları ile idari ve teknik personeli.', 'GY m.438/1-c', '2021',
        'milletlerarası resmi kuruluşların Türkiye\'de ikamet eden misyon şefleri, diplomatik memurları ile idari ve teknik personeli'],
      ['GY m.438\'e göre diplomatik muafiyetten başka kimler yararlanabilir?',
        '**Yabancı devlet başkanları**, aileleri ve refakat memurları; **diplomatik pasaportu haiz** resmi ziyaret/görev delegeleri, sivil ve askeri heyetler; yabancı devletlerin temsilcilik ve konsolosluklarındaki misyon şefleri, diplomatik memurlar, **meslekten konsolosluk memurları**, idari ve teknik personel.', 'GY m.438/1', '',
        ['Yabancı devlet başkanları ve aileleri ile refakatlerine memur olanlar', 'Diplomatik pasaportu haiz olmak kaydıyla resmi bir ziyaret veya görev için Türkiye\'ye gelen delegelerle, sivil ve askeri heyetler', 'meslekten konsolosluk memurları ile idari ve teknik personel']],
      ['Diplomatik muafiyetlerde karşılıklılık şartı nasıl işler?',
        'Aynı muafiyetin yabancı devletçe de **karşılıklı** gösterilmesi şarttır; daha az gösteren devlete muafiyet **o nispette azaltılır**.', 'GY m.439/1–2', '',
        ['aynı muafiyet ve kolaylıkların yabancı devletler tarafından da karşılıklı olarak gösterilmiş bulunması şarttır', 'Daha az muafiyet ve kolaylık gösteren devletler hakkında karşılıklı uygulanacak muafiyet ve kolaylıklar o nispette azaltılır']],
      ['Diplomatik muafiyetten yararlananların beraberlerinde gelen eşyada beyan ve muayene nasıldır?',
        '**Hiçbir beyan aranmaz**, eşya **muayene edilmez**; ancak **şüphe** veya **yazılı, açık adresli ve imzalı ihbar** varsa muayene edilebilir.', 'GY m.440/1, 3', '',
        ['ilgililerinden hiç bir beyan aranılmaz ve bu eşya muayene edilmez', 'Şüphe ve yazılı, açık adresli ve imzalı ihbar olmadıkça, bu eşya muayene edilmez']],
      ['Diplomatik muafiyetle getirilen eşya ve taşıtların devir veya satışı neye tabidir?',
        '**Dışişleri Bakanlığının önceden iznine**; muafiyet hakkı olmayan yer/kişiye devirde serbest dolaşıma giriş beyannamesi alınır ve vergiler **GK m.181**\'e göre tahakkuk ve tahsil edilir.', 'GY m.441/1, 4', '',
        ['devir veya satışı Dışişleri Bakanlığının önceden iznine tabidir', 'Kanunun 181 inci maddesi hükmü gereğince gümrük vergileri tahakkuk ve tahsil olunur']],
      ['Diplomatik muafiyetle getirilen taşıt çalınırsa vergiler ne olur?',
        'Çalınma **mahkeme ilamı**, **Cumhuriyet Savcılığı** veya olay yerinin **en büyük mülki amirinden** alınan belgeyle ispatlanırsa vergiler **aranmaz**, elçilik mektubu kayıtları kapatılır.', 'GY m.442', '',
        'çalınma hadisesi, mahkeme ilamı veya Cumhuriyet Savcılığından veya olayın vuku bulduğu yerin en büyük mülki amirinden alınan belge ile ispatlandığı takdirde, bunların gümrük vergileri aranmayarak'],
    ] },
    { baslik: 'Posta-Hızlı Kargo, Kişisel ve Yolcu Beraberi Eşya (Karar (2009/15481) m.45, 58–63)', sorular: [
      ['Posta veya hızlı kargoyla gelen hangi eşyaya, hangi değere kadar muafiyet tanınır?',
        'Gönderi başına toplam **150 Avro**\'yu geçmeyen **kişisel kullanıma mahsus kitap veya benzeri basılı yayın**; kullanımın süreklilik arz ettiği tespit edilirse **sınırlama** getirilebilir.', 'Karar (2009/15481) m.45/1–2', '',
        ['bedeli gönderi başına toplam 150 Avro\'yu geçmeyen kişisel kullanıma mahsus kitap veya benzeri basılı yayına muafiyet tanınır', 'Muafiyetin aynı kişi tarafından kullanılmasının süreklilik arz ettiğinin tespiti halinde muafiyetin kullanımına sınırlama getirilebilir']],
      ['Ek-9 listesindeki kişisel eşya ne zaman getirilebilir?',
        '(A) bölümü **sadece yolcu beraberinde**; (B) bölümü yolcu beraberinde ya da gelişinden **bir ay önce** veya **üç ay sonra**.', 'Karar (2009/15481) m.58/2', '2025',
        'Ek-9\'daki listenin (A) bölümünde belirtilen eşya sadece yolcu beraberinde, (B) bölümünde belirtilen eşya ise, yolcu beraberinde ya da yolcunun gelişinden bir ay önce veya üç[27] ay sonra getirilebilir'],
      ['Yolcu beraberi kişisel ve hediyelik eşya muafiyetinden kimler yararlanamaz; hangi eşya kapsamdadır?',
        '**Transit yolcular** yararlanamaz; ticari miktar ve mahiyette olmayan, **Ek-9 dışında kalan** kişisel ve hediyelik eşya kapsamdadır.', 'Karar (2009/15481) m.59/1', '',
        'Transit yolcular hariç olmak üzere, yolcu beraberinde getirilip serbest dolaşıma sokulan, ticari miktar ve mahiyette olmayan ve Ek-9\'daki liste kapsamı dışında kalan kişisel ve hediyelik eşyaya muafiyet tanınır'],
      ['Kara hudut kapısından giren yolcular 58, 59, 62 ve 63. madde muafiyetini ayda en fazla kaç kez kullanabilir?',
        'Ayda en fazla **10 defa**.', 'Karar (2009/15481) m.59/2', '',
        '58, 59, 62 ve 63 üncü maddelerde bahsi geçen muafiyet, kara hudut kapısından giriş yapan yolcular için ayda en fazla 10 defa kullandırılır'],
      ['Ek-9\'daki tütün ve alkollü ürün muafiyeti hangi yolculara uygulanır?',
        '**18 yaşından büyüklere.**', 'Karar (2009/15481) m.60/2', '',
        'tütün ve tütün ürünleri ile alkollü ürünlere ilişkin muafiyet 18 yaşından büyükler için uygulanır'],
      ['Yolcu beraberi hediyelik eşya muafiyet limiti nedir?',
        'Yolcu başına toplam **430 Avro**; **15 yaşından küçükler** için **150 Avro**.', 'Karar (2009/15481) m.61', '2022',
        'her bir yolcu için toplam gerçek kıymeti 430 Avro\'yu geçmeyen eşya için uygulanır. Ancak, 15 yaşından küçük yolcular için bu miktar 150 Avro olarak uygulanır'],
      ['Posta/hızlı kargoyla reçeteye istinaden gerçek kişiye gelen ilaç ve takviye edici gıdada tek ve maktu vergi oranları nedir?',
        'Kıymeti **1500 Avro**\'yu geçmeyenlerde: **AB**\'den doğrudan gelirse **%30**, diğer ülkelerden **%60**; ÖTV Kanunu **(IV) sayılı liste** eşyasında bu oranlara **ilave %20**.', 'Karar (2009/15481) m.62/1', '2025',
        ['kıymeti 1500 Avro\'yu geçmeyen ilaç cinsi eşya ile takviye edici gıdaların değeri üzerinden', 'Avrupa Birliği ülkelerinden doğrudan gelmesi halinde % 30', 'Diğer ülkelerden gelmesi halinde % 60', '(IV) sayılı listede yer alan eşya olması durumunda yukarıdaki oranlara ilave % 20']],
      ['Posta/hızlı kargoyla gerçek kişiye gelen kitap ve basılı yayında 45. madde limitini aşan kısım nasıl vergilendirilir?',
        'Kıymeti **1500 Avro**\'yu geçmeyenlerde **%0** oranında tek ve maktu vergi.', 'Karar (2009/15481) m.62/2', '',
        'kişisel kullanıma mahsus kitap veya benzeri basılı yayın için 45 inci maddede belirtilen limitleri aşan eşyanın değeri üzerinden % 0 oranında tek ve maktu bir vergi uygulanır'],
      ['Posta/hızlı kargoyla tüzel kişiye gelen eşyada tek ve maktu vergi hangi kıymet sınırına kadar uygulanır?',
        'Kıymeti **22 Avro**\'yu geçmeyen, ticari miktar ve mahiyet arz etmeyen eşyaya (m.62/1 oranlarında).', 'Karar (2009/15481) m.62/3', '',
        'bir tüzel kişiye gelen ve ticari miktar ve mahiyet arz etmeyen, kıymeti 22 Avro\'yu geçmeyen eşyanın'],
      ['Hediyelik eşya limitini aşan yolcu beraberi eşyaya hangi sınıra kadar tek ve maktu vergi uygulanır?',
        'Kıymeti **1500 Avro**\'yu geçmeyen, Ek-9 dışı ve ticari olmayan eşyaya; eşyanın **tek başına** kıymeti 1500 Avro\'yu aşarsa **yürürlükteki ithalat vergisi oranları** uygulanır. Limit aşımında muafiyet yalnızca **150/430 Avro**\'luk kısma uygulanır.', 'Karar (2009/15481) m.62/4; m.63/1–2', '',
        ['Kıymeti 1500 Avro\'yu geçmemek şartıyla, yolcu beraberinde gelen Ek-9\'daki liste kapsamı dışında kalan', 'eşyanın tek başına kıymetinin 1500 Avro\'yu aşması halinde, söz konusu eşyaya yürürlükte olan ithalat vergilerine ilişkin oranlar uygulanır', 'muafiyet yalnızca toplam değeri 150 veya 430 Avro tutarındaki kısma uygulanır']],
      ['Posta/hızlı kargo limitleri dahilinde gelen eşyada ağırlık sınırı nedir; hangi eşyada sınır uygulanmaz?',
        '**Brüt 30 kg**; **diplomatik eşya** ile **58. madde kapsamı yolcu eşyasında** kıymet ve ağırlık sınırı uygulanmaz.', 'Karar (2009/15481) m.62/5–6', '',
        ['getirilen eşyanın brüt 30 kilogramı geçmemesi gerekir', 'Diplomatik eşya ve 58 inci madde kapsamı yolcu eşyasının posta veya hızlı kargo taşımacılığı yoluyla gelmesi halinde kıymet ve ağırlık sınırı uygulanmaz']],
    ] },
    { baslik: 'Kullanılmış Taşıt ve Ev Eşyası (Karar (2009/15481) m.46–49, 110; Tebliğ (Muafiyet Seri No: 2) m.4–16, 38)', sorular: [
      ['Kullanılmış özel nakil vasıtasını muafen serbest dolaşıma sokabilecek kişiler kimlerdir?',
        'TGB dışında **en az 24 ay** ikamet edip yerleşim yerini kesin nakledenler; yurt dışı milli/milletlerarası kadrolara atanıp **dönen kamu görevlileri**; **Türk vatandaşlığına geçerek** nakledenler. Son ikisinde **24 ay şartı aranmaz**.', 'Karar (2009/15481) m.46/1–2', '',
        ['Türkiye Gümrük Bölgesi dışında en az yirmidört ay ikamet ettikten sonra, yerleşim yerini Türkiye Gümrük Bölgesine kesin olarak nakleden gerçek kişiler', 'Yurt dışındaki milli veya milletlerarası kadrolara atanıp da bu görevlerinden dönen kamu görevlileri', 'Birinci fıkranın (b) ve (c) bentlerinde belirtilen kişiler için, Türkiye Gümrük Bölgesi dışında en az yirmidört ay ikamet etme şartı aranmaz']],
      ['Kullanılmış taşıt muafiyeti hangi kamu görevlilerine tanınır, hangilerine tanınmaz?',
        'Yurt dışı kadrolara **sürekli görevli** olarak atanıp dönenlere tanınır; **24 ayı aşmayan süreyle geçici** görevlendirilenlere **uygulanmaz**.', 'Tebliğ (Muafiyet Seri No: 2) m.4/1-b, 6/1', '2022',
        ['Yurt dışındaki milli veya milletlerarası kadrolara sürekli görevli olarak atanıp da bu görevlerinden dönen kamu görevlileri', 'Türkiye Gümrük Bölgesi dışında yirmi dört ayı aşmayan süreyle geçici olarak görevlendirilen kamu görevlileri için bu bölüm hükümleri uygulanmaz']],
      ['Sürekli görevle yurt dışındayken başka bir yabancı ülkeye sürekli görevle atanan kamu görevlisi taşıt ve ev eşyası muafiyetinden yararlanır mı?',
        'Taşıt muafiyeti **uygulanmaz**; ev eşyası için ise yeni ülkenin özelliği/uzaklığı nedeniyle götürülmesi külfetliyse ve **tevsik edilirse** muafiyet **uygulanır**.', 'Karar (2009/15481) m.46/4, 48/4', '',
        ['başka bir yabancı ülkeye atanması nedeniyle yerleşim yerini Türkiye Gümrük Bölgesine kesin olarak nakledemeyen kamu görevlileri için birinci fıkra kapsamı muafiyet uygulanmaz', 'durumlarının tevsik edilmesi kaydıyla, yurt dışındaki ev eşyası için muafiyet uygulanır']],
      ['Evlilik yoluyla Türk vatandaşlığına geçen kişi taşıt muafiyetinden yararlanabilir mi?',
        '**Hayır**, yararlanamaz.', 'Karar (2009/15481) m.46/3; Tebliğ (Muafiyet Seri No: 2) m.6/2', '',
        ['Evlilik yoluyla Türk vatandaşlığına geçen kişiler için bu madde hükümleri uygulanmaz', 'Evlilik suretiyle Türk vatandaşlığına geçenler bu bölümde yer alan muafiyetten faydalanamazlar']],
      ['Taşıt muafiyetinde aracın kayıt ve yaş şartları nelerdir; ticari araç getirilebilir mi?',
        'Türkiye\'ye son girişten **en az 6 ay önce** yurt dışında kişi adına **kayıtlı** olmalı; kayıt yılı itibarıyla **kayıt ve model yılı dahil 3 yıldan eski** olmamalı. **Ticari araçlara izin verilmez.**', 'Karar (2009/15481) m.47/1, 4', '',
        ['Türkiye\'ye son giriş tarihinden en az altı ay öncesinde yurt dışında bulundukları ülkede adlarına kayıtlı olması, adlarına kaydının yapıldığı yıl itibarıyla, kayıt ve model yılı dahil, üç yıldan eski olmaması şarttır', 'Motorlu ticari araçlar ve diğer ticari nakil vasıtalarının 46 ncı madde kapsamında muafen serbest dolaşıma girişine izin verilmez']],
      ['Taşıt ve ev eşyası muafiyeti kime tanınır; bu birim nasıl tespit edilir?',
        '**Aile ünitesine**; tespitte **vukuatlı nüfus kayıt örneği** esas alınır.', 'Karar (2009/15481) m.47/2, 49/1; Tebliğ (Muafiyet Seri No: 2) m.5/2', '',
        ['Motorlu veya motorsuz özel nakil vasıtası muafiyeti, aile ünitesine tanınır', 'Kullanılmış ev eşyası muafiyeti, aile ünitesine tanınır', 'Aile ünitesinin tespitinde vukuatlı nüfus kayıt örneğindeki bilgilere bakılır']],
      ['Taşıt muafiyetinde gümrük idaresine müracaat süreleri nedir?',
        '24 ay ikamet edenler ikamet nakil belgesindeki tarihten sonraki **ilk girişten**, kamu görevlileri görev bitimini müteakip **ilk girişten** itibaren **6 ay**; vatandaşlığa geçenler **nüfus kağıdı** düzenlenmesinden itibaren **6 ay**; varisler **veraset ilamından** itibaren **24 ay**.', 'Tebliğ (Muafiyet Seri No: 2) m.7/1', '',
        ['ikamet nakil belgesindeki tarihten sonraki ilk giriş tarihinden itibaren altı ay', 'görev sürelerinin bitimini müteakip Türkiye\'ye ilk giriş tarihinden itibaren altı ay', 'vatandaşlığa geçiş kararından sonra adlarına nüfus kağıdının düzenlendiği tarihten itibaren altı ay', 'veraset ilamı tarihinden itibaren yirmi dört ay']],
      ['Muafen taşıt getiren kişi yeniden muaf taşıt getirebilmek için ne kadar beklemelidir?',
        'Serbest dolaşıma giriş tarihinden itibaren **5 yıl** geçmedikçe — yurt dışında yeniden ikamet tesis edilse dahi — talep **kabul edilmez**.', 'Karar (2009/15481) m.47/5; Tebliğ (Muafiyet Seri No: 2) m.6/5', '2025',
        'serbest dolaşıma giriş tarihinden itibaren beş yıl geçmedikçe, aynı kişilerin motorlu veya motorsuz özel nakil vasıtalarının muafen serbest dolaşıma girişine ilişkin talepleri kabul edilmez'],
      ['24 ay yurt dışı ikamet sonrası yerleşim yerini nakleden kişinin taşıt muafiyetinde Türkiye\'de kalış süresine ilişkin şart nedir?',
        'Geriye doğru bir takvim yılında TGB\'de **6 aydan fazla** kalmamış olmak; bir takvim yılında **45 güne kadar** kalışlar yurt dışı ikametten sayılır; son **10 yılda en az 5 yıl** yurt dışında ikamet edenlerde bu şart aranmaz.', 'Tebliğ (Muafiyet Seri No: 2) m.5/3', '',
        ['Türkiye Gümrük Bölgesinde geriye doğru bir takvim yılında altı aydan fazla kalmamış olmaları gerekir', 'Türkiye Gümrük Bölgesinde bir takvim yılında kırk beş güne kadar kalışlar yurt dışındaki ikamet süresinden sayılır', 'Türkiye Gümrük Bölgesi dışında son on yıl içinde en az beş yıl ikamet eden gerçek kişiler için yerleşim yerine ilişkin bu süre şartı aranmaz']],
      ['Çift uyruklular ve Türk vatandaşlığından çıkma izni alanlar taşıt ve ev eşyası muafiyetinden yararlanabilir mi?',
        'Çıkma izniyle yabancı vatandaşlık kazananlar **ikisinden de yararlanamaz**. **Çift uyruklular** (24 ay ikamet ve vatandaşlığa geçiş bentleri) **taşıt** muafiyetinden **yararlanamaz**, **ev eşyası** muafiyetinden **yararlanır**; diğer hallerde çift uyrukluluk dikkate alınmaz.', 'Tebliğ (Muafiyet Seri No: 2) m.6/6–7, 12/2; Karar (2009/15481) m.110', '',
        ['Türk vatandaşlığından çıkma izni almak suretiyle yabancı bir ülke vatandaşlığını kazanan kişiler bu bölümde yer alan muafiyetten faydalanamazlar', '4 üncü maddenin birinci fıkrasının (a) ve (c) bentlerinde belirtilen kişiler, çift uyruklu olmaları halinde bu haktan faydalanamazlar', 'Ancak, çift uyruklu kişiler bu bölümde yer alan muafiyetten faydalanırlar', 'bu Kısım hükümlerinin uygulanmasında kişilerin çift uyruklu olup olmadığı dikkate alınmaz']],
      ['Kullanılmış taşıtların serbest dolaşıma giriş işlemlerinde yetkili gümrük idareleri hangileridir?',
        '**Yeşilköy, Gebze, İzmir Yolcu Salonu ve Ankara Gar** Gümrük Müdürlükleri; NATO/SOFA kapsamı ABD personeli için **İncirlik** de yetkilidir.', 'Tebliğ (Muafiyet Seri No: 2) m.38/1', '',
        ['Yeşilköy Gümrük Müdürlüğü, Gebze Gümrük Müdürlüğü, İzmir Yolcu Salonu Gümrük Müdürlüğü ve Ankara Gar Gümrük Müdürlüğü yetkilidir', 'İncirlik Gümrük Müdürlüğü de yetkilidir']],
      ['Ev eşyası muafiyetinde TGB\'de geçici olarak bulunmak 24 aylık devamlılığı bozar mı?',
        'Bir yıl içinde **6 aydan az** geçici bulunma devamlılığı **bozmaz**; ancak bu süreler **24 aya dahil edilmez**.', 'Karar (2009/15481) m.48/2', '',
        ['Türkiye Gümrük Bölgesinde bir yıl içinde altı aydan az süre ile geçici olarak bulunmak devamlılık halini bozmaz', 'bu süreler Türkiye Gümrük Bölgesi dışındaki yerleşim yerinde aranan yirmidört ay kalma süresine dahil edilmez']],
      ['Kullanılmış ev eşyası ne zaman getirilip beyan edilmelidir; meslek malzemesi muaf mıdır?',
        'Kişilerin **beraberinde**, **gelişlerinden önce** veya **6 ay sonraki** süre içinde (varisler veraset ilamından itibaren **24 ay**). Ticaret/meslek malzemeleri **taşınabilir alet ve cihazlar hariç** muaf değildir.', 'Karar (2009/15481) m.49/3–4; Tebliğ (Muafiyet Seri No: 2) m.13', '',
        ['Ev eşyasının kişilerin beraberinde veya gelişlerinden önce veya altı ay sonraki süre içerisinde getirilip serbest dolaşıma giriş beyanında bulunulması gerekir', 'Taşınabilir alet ve cihazlar hariç olmak üzere, bir ticaret veya meslek icabı kullanılacak malzemelerin bu Ayırımdaki hükümler kapsamında muaf olarak serbest dolaşıma girişine izin verilmez']],
      ['24 ay yurt dışı ikamet şartıyla ev eşyası muafiyetinden yararlanan kişi aynı muafiyetten tekrar yararlanmak için ne yapmalıdır?',
        'Yurt dışında **en az 24 ay yeniden ikamet** tesis etmelidir. (Süresi içinde **partiler halinde** getirme mükerrer kullanım sayılmaz.)', 'Tebliğ (Muafiyet Seri No: 2) m.11/2, 16/2', '',
        ['tekrar aynı muafiyetten yararlanabilmeleri için, yurt dışında en az yirmi dört ay yeniden ikamet tesis etmiş olmaları gerekir', 'eşyanın partiler halinde getirilmesi, hakkın mükerrer kullanımı olarak değerlendirilmez']],
    ] },
    { baslik: 'Çeyiz, Miras, Öğrenci ve Diğer Ev Eşyası (Karar (2009/15481) m.50–57; Tebliğ (Muafiyet Seri No: 2) m.17–18)', sorular: [
      ['Evlilik nedeniyle yurt dışından gönderilen hediyelerde muafiyet sınırı nedir?',
        'Her bir hediye **430 Avro**, toplam **3.000 Avro**\'yu aşmamalı (ticari miktar ve mahiyette olmamalı).', 'Karar (2009/15481) m.50/2', '',
        'her bir hediyenin kıymeti 430 Avro ve toplam hediye kıymeti 3.000 Avro\'yu aşmamak kaydıyla muafiyet tanınır'],
      ['Çeyiz eşyası muafiyeti hangi süre şartıyla tanınır?',
        'Nakilden önce **en az 12 ay** TGB dışında bulunma ve **evlilik belgesi** ibrazı; Türkiye\'ye gelip **en çok bir yıl içinde** Türk vatandaşıyla evlenenler de yararlanır.', 'Karar (2009/15481) m.50/3, 51/1-c', '',
        ['en az oniki ay süre ile Türkiye Gümrük Bölgesi dışında bulunan ve evlilik belgesini ibraz eden kişilere tanınır', 'Türkiye\'ye gelip en çok bir yıl içinde yine yerleşim yeri Türkiye\'de olan bir Türk vatandaşı ile evlenmiş bulunan']],
      ['Çeyiz eşyası hangi süre içinde serbest dolaşıma sokulmalıdır?',
        'Evlilik akdinden **2 ay önce** veya **4 ay sonra**; tek seferde veya partiler halinde. Akitten önce sokulursa vergiler kadar **teminat** aranır.', 'Karar (2009/15481) m.52', '',
        ['evlilik akdinden iki ay önce veya dört ay sonraki süreler içerisinde serbest dolaşıma sokmaları şarttır', 'gümrük vergilerini karşılayacak miktarda teminat aranır']],
      ['Miras yoluyla intikal eden eşyada getirme süresi nedir; hangi eşya muafiyet dışındadır?',
        'Veraset ilamından itibaren **24 ay** (tek veya birden fazla parti). **Motorlu ticari** nakil vasıtaları, meslek alet-cihazları (ölenin **taşınabilir** aletleri hariç), **hammadde ve mamul/yarı mamul stokları**, normal aile ihtiyacını aşan **canlı hayvan ve tarım ürünleri** muaf değildir.', 'Karar (2009/15481) m.53/3, 54', '',
        ['veraset ilamı tarihinden itibaren yirmidört ay içinde, tek seferde veya aynı süre içinde birden fazla partide getirilen eşya için tanınır', 'Motorlu ticari nakil vasıtaları.', 'Hammadde stokları ve mamul veya yarı mamul ürünler.', 'Normal aile ihtiyaçlarından fazla miktarlarda bulunan canlı hayvanlar ile tarım ürünleri']],
      ['Öğrencilerin eğitim malzemesi ve ev eşyası muafiyeti kaç kez kullanılabilir?',
        'Eğitim malzemesinde **her öğrenim yılında birden fazla**; ev eşyası ise öğrenim süresi boyunca **bir kez**.', 'Karar (2009/15481) m.55/3', '',
        ['Muafiyet, eğitim malzemeleri yönünden her bir öğrenim yılında bir defadan fazla tanınabilir', 'öğrenim süresi boyunca muafen bir kez ev eşyası serbest dolaşıma sokulabilir']],
      ['Geçici olarak yurt dışına çıkan kişinin geri getirdiği kullanılmış ev eşyası hangi şartla muaftır?',
        'Dönüşten itibaren **en geç 6 ay** içinde ve **bir defada** getirilmesi.', 'Karar (2009/15481) m.56/2', '',
        'Türkiye Gümrük Bölgesine dönüş tarihinden itibaren en geç altı ay içerisinde ve bir defada getirmesi şarttır'],
      ['Yurt dışında yerleşik kişilerin Türkiye\'de edindikleri konutta kullanacakları ev eşyası muafiyetinin şartları nelerdir?',
        'TGB dışında **en az 24 ay** yerleşik olma; konutun **satın alınmış** veya **en az 1 yıl** kiralanmış olması; eşyanın **kullanılmış** olması; **bir konut ve aynı kişi için bir defa**. Kira/mülkiyet şartı yoksa **tam muafiyetle geçici ithalat**.', 'Karar (2009/15481) m.57', '',
        ['en az yirmidört ay süre ile yerleşik bulunan gerçek kişiler', 'konutun en az bir yıl[26] için kiralanmış olması', 'Muafiyet, bir konut ve aynı kişi için bir defa ile sınırlıdır', 'ev eşyasının gümrük vergilerinden tam muafiyet suretiyle vergileri teminata bağlanarak geçici ithaline izin verilir']],
      ['Konut ev eşyası muafiyetinde uyruk dikkate alınır mı; yurtta ne kadar bulunmak sürekliliği bozmaz?',
        'Uyruk **dikkate alınmaz** (yurt dışında yerleşik olmak esastır); son girişten geriye bir yılda **185 güne kadar** yurtta bulunmak sürekliliği **bozmaz**.', 'Tebliğ (Muafiyet Seri No: 2) m.17/2, 18/1-a', '',
        ['kişilerin Türkiye Gümrük Bölgesi dışında yerleşik olmaları esas olup kişilerin uyruğu dikkate alınmaz', 'Türkiye\'ye son giriş tarihinden geriye doğru bir yılda yüz seksen beş güne kadar yurtta bulunmak süreklilik halini bozmaz']],
    ] },
    { baslik: 'Kamu Yararı, Bilim ve Sağlık Amaçlı Eşya (Karar (2009/15481) m.68–79; Tebliğ (Muafiyet Seri No: 2) m.22–24, 38/2)', sorular: [
      ['Kamu kurumları, hayır ve insani yardım kurumlarınca getirilen eşyada hangi araçlar muaftır; hangi eşyaya muafiyet uygulanmaz?',
        '**Ambulans, cenaze arabası, yangın söndürme ve kurtarma araçları** muaftır; **kahve ve çay** ile bunlar dışındaki **motorlu araçlara** muafiyet uygulanmaz.', 'Karar (2009/15481) m.68/1-d, 68/3', '',
        ['ambulans, cenaze arabaları, yangın söndürme araçları ile kurtarma araçları', 'Bu maddenin uygulanmasında kahve ve çay ile ambulans, cenaze arabaları[40] ve diğer kurtarma araçları hariç olmak üzere motorlu araç için muafiyet uygulanmaz']],
      ['Kurtarma ve cenaze araçlarını muafen kimler getirebilir; hangi gümrük idaresi yetkilidir?',
        'Sadece **kamu kurum ve kuruluşları** ile **Bakanlar Kurulunca belirlenen** insani yardım ve hayır kurumları; yetkili idare **Ankara Gar Gümrük Müdürlüğü**.', 'Tebliğ (Muafiyet Seri No: 2) m.22/2, 38/2', '',
        ['kurtarma ve cenaze araçları sadece kamu kurum ve kuruluşları ile Bakanlar Kurulunca belirlenen insani yardım ve hayır kurumları tarafından serbest dolaşıma sokulur', 'kurtarma ve cenaze araçlarının serbest dolaşıma giriş işlemlerinde Ankara Gar Gümrük Müdürlüğü yetkilidir']],
      ['Kurtarma ve cenaze araçları dışındaki bağış eşyasına ilişkin talebi kim karara bağlar?',
        'Gümrük müdürü veya yetkili kılacağı müdür yardımcısı başkanlığında **iki muayene memurundan** oluşan komisyon, **oybirliği** ile.', 'Tebliğ (Muafiyet Seri No: 2) m.24/2', '',
        'gümrük müdürü veya yetkili kılacağı gümrük müdür yardımcısı başkanlığında iki muayene memurundan oluşan komisyon tarafından oybirliği ile karara bağlanır'],
      ['Eğitim ve bilimsel araştırma kuruluşlarının bilimsel alet ve cihaz muafiyetinde şart nedir?',
        'Kuruluşun eğitim/bilimsel araştırma dalında faaliyette bulunduğunun gümrük idaresine **tevsiki**; m.70 dışı bilimsel alet-cihazlar **ticari olmayan amaçlarla** girerse muaftır.', 'Karar (2009/15481) m.71/2–3', '',
        ['Bu kuruluşların eğitim veya bilimsel araştırma dalında faaliyette bulunduklarının gümrük idaresine tevsiki şarttır', '70 inci maddenin kapsamı dışında kalan bilimsel alet ve cihazlar, ticari olmayan amaçlarla serbest dolaşıma girdiği takdirde gümrük vergilerinden muaftır']],
      ['Sağlık kuruluşlarına bağışlanan tıbbi alet ve cihazlarda muafiyetin şartları nelerdir?',
        '**Ticari amaçla bağışlanmamış** olması, bağışlayanın **üreticiyle ilgisinin olmaması** ve **Sağlık Bakanlığınca** uygun bulunması.', 'Karar (2009/15481) m.73/2–3', '',
        ['Ticari bir amaçla bağışlanmayan', 'Bağışlayanın üretici ile herhangi bir ilgisinin olmadığı', 'insan sağlığı yönünden Sağlık Bakanlığınca uygun bulunması gerekir']],
      ['İlaç kalite kontrolüne yönelik maddelerde muafiyetin şartı nedir?',
        '**Dünya Sağlık Örgütü** onaylı referans maddelerine ilişkin numunelerin **Sağlık Bakanlığınca izin verilen kurumlarca** ithali.', 'Karar (2009/15481) m.77', '',
        'kalite kontrolü için Dünya Sağlık Örgütü tarafından onaylanmış referans maddelerine ilişkin numunelerin, Sağlık Bakanlığınca izin verilen kurumlarca ithal edilmesi halinde gümrük vergileri aranmaz'],
      ['Ar-Ge projelerinde kullanılacak eşya muafiyeti hangi kurumun projelerine bağlıdır?',
        '**TÜBİTAK**\'ın yürüttüğü veya desteklediği projeler; eşyanın proje kapsamında olduğu **TÜBİTAK tarafından teyit** edilmeli ve amaca uygun miktarı aşmamalıdır.', 'Karar (2009/15481) m.78–79', '',
        ['Türkiye Bilimsel ve Teknolojik Araştırma Kurumu tarafından yürütülen veya desteklenen araştırma ve geliştirme projelerinde kullanılmak üzere getirilen eşyaya muafiyet tanınır', 'Türkiye Bilimsel ve Teknolojik Araştırma Kurumu tarafından teyit edilmesi gerekir']],
    ] },
    { baslik: 'Ticari Faaliyetle Bağlantılı İthalat (Karar (2009/15481) m.80–92; Tebliğ (Muafiyet Seri No: 2) m.25–28)', sorular: [
      ['İşyeri nakli muafiyetinde kullanım, çalışma ve getirilme süreleri nedir?',
        'Eşya faaliyet sona ermeden önce **en az 12 ay** fiilen kullanılmış olmalı; kişi ayrıldığı ülkede **en az 3 yıl** aynı işte çalışmış olmalı; eşya faaliyetin sona erdiği tarihten itibaren **12 ay** içinde getirilmeli.', 'Karar (2009/15481) m.81/1-a, 81/3, 82', '',
        ['yabancı ülkedeki faaliyetini sona erdirmeden önce en az oniki ay süreyle işletme tarafından fiilen kullanılmakta olan', 'Muafiyet hakkı sadece ayrıldıkları ülkede en az üç yıl süre ile aynı işte çalışan kişilere tanınır', 'faaliyetlerini sona erdirdiği tarihten itibaren oniki ay içerisinde Türkiye Gümrük Bölgesine getirilen eşya ve malzeme için uygulanır']],
      ['İşyeri nakli muafiyetinin kapsamı dışında kalan eşya nelerdir?',
        'Üretim/hizmet makinesi olmayan **ulaşım araçları** (taşınabilir laboratuvar, dış yayın birimi gibi); **canlı hayvan, yem, tohum ve fidan**; **ham/yarı mamul/mamul stoklar ve akaryakıt**.', 'Karar (2009/15481) m.81/4; Tebliğ (Muafiyet Seri No: 2) m.28', '',
        ['Üretim veya hizmet endüstrisi makinesi olmayan, taşınabilir laboratuvar veya dış yayın yapma birimleri gibi ulaşım araçları', 'Canlı hayvan, hayvan yemleri ile tohum ve fidanlar', 'Ham, yarı mamul veya mamul madde stokları ile akaryakıtlar']],
      ['İşyeri nakli muafiyetinden kimler yararlanır, kimler yararlanamaz?',
        'Benzer faaliyeti TGB\'de yürütmek için yurt dışı faaliyetini **kesin olarak sona erdiren iş yeri sahibi**; **kazanç amacı gütmeyen tüzel kişiler** ve mesleğini TGB\'de yürüteceğini ispatlayan **serbest meslek** erbabı. TGB\'deki bir işletmeyle **bağlantı kurma** amaçlı işletmeler yararlanamaz.', 'Karar (2009/15481) m.81/2, 83', '',
        ['ayrıldıkları ülkedeki faaliyetlerini kesin olarak sona erdiren iş yeri sahibine tanınır', 'Türkiye Gümrük Bölgesinde yerleşik bulunan bir işletme ile herhangi bir bağlantı kurma amaçlarına yönelik işletmeler için muafiyet uygulanmaz', 'Kazanç sağlama amacına yönelik olmayan faaliyetlerle uğraşan ve bu faaliyetini Türkiye Gümrük Bölgesine nakleden tüzel kişiler', 'Bir serbest meslek veya benzeri bir faaliyetle uğraşan gerçek kişilere de']],
      ['TGB\'deki çiftçilerin komşu ülkedeki mülklerinden elde ettikleri ürünlerde muafiyet şartları nelerdir?',
        'Hayvancılığın **Türk menşeli** veya **serbest dolaşımdaki** hayvanlarla yapılması; ürünlerin hasat/üretim sonrası **başka işlemden geçmemiş** olması; **bizzat üreticilerce** kendi mülklerinden elde edilmesi.', 'Karar (2009/15481) m.84/2–4', '',
        ['hayvancılık faaliyetlerinin Türk menşeli veya Türkiye\'de serbest dolaşım durumunda bulunan hayvanlarla yapılıyor olması şarttır', 'Muafiyet, normal olarak hasat veya üretim sonrası başka bir işlemden geçmemiş ürünlerle sınırlıdır']],
      ['Basılı reklamcılık malzemesi muafiyetinin şartları nelerdir?',
        'Müteşebbisin **adının** eşya üzerinde açıkça yer alması; sevkiyatta tek materyal veya her çeşitten birer adet (aynı çeşitten birden fazlaysa toplam brüt **1 kg**\'ı aşmaması); **gönderici ve alıcının aynı kişi olmaması**.', 'Karar (2009/15481) m.88/1', '',
        ['Eşyayı üreten, satan, kiralayan veya hizmeti sunan müteşebbisin adının eşya üzerinde açık bir şekilde yer alması', 'toplam brüt ağırlığının bir kilogramı aşmaması', 'Gönderici veya alıcısının aynı kişi olmaması']],
      ['Ticari fuar muafiyetinde hangi sergiler kapsam dışıdır; numune ve gösteri eşyası muafiyeti hangi eşyaya uygulanmaz?',
        'Yabancı ülke eşyasını satmak amacıyla **işyerinde düzenlenen özel amaçlı sergiler** kapsam dışıdır; fuar numuneleri ve makine gösterisinde kullanılan eşya muafiyeti **katı, sıvı ve gaz yakıtlara** uygulanmaz.', 'Karar (2009/15481) m.89/3, 90/5', '',
        ['yabancı bir ülke eşyasının satılması amacıyla işyeri veya bunların eklentilerinde düzenlenen özel amaçlı sergiler bu kapsama dahil değildir', '89 uncu maddenin birinci fıkrasının (a) ve (b) bentlerinde belirtilen muafiyet katı, sıvı ve gaz yakıtlar için uygulanmaz']],
      ['UEFA organizasyonları için muafen serbest dolaşıma giren eşya nasıl değerlendirilebilir?',
        '**İmha edilebilir**, **ücretsiz dağıtılabilir** veya **hayır amaçlı sembolik bedelle** satılabilir.', 'Karar (2009/15481) m.89/4', '',
        'muafen serbest dolaşıma giren eşya imha edilebilir, ücretsiz olarak dağıtılabilir ya da hayır amaçlı sembolik bedel karşılığında satılabilir'],
      ['İnceleme, analiz veya test amaçlı eşya muafiyeti hangi halde tanınır; tıbbi tetkik amaçlı biyolojik materyalde şart nedir?',
        'Eşya işlem sırasında **tamamen sarf edilmeli** veya aynı amaçla **tekrar kullanılamaz** hale gelmeli; biyolojik materyaller **Sağlık Bakanlığınca ruhsatlandırılmış Tıbbi Laboratuvarlar** ve **Genetik Hastalıklar Değerlendirme Merkezleri** adına gönderilmeli.', 'Karar (2009/15481) m.92/2, 92/6', '',
        ['inceleme, analiz veya test sırasında tamamıyla sarf edilmesi veya aynı amaçla tekrar kullanılamayacak hale gelmesi[45] halinde tanınır', 'Sağlık Bakanlığınca ruhsatlandırılmış Tıbbi Laboratuvarlar ve Genetik Hastalıklar Değerlendirme Merkezleri adına gönderilmesi gerekir']],
    ] },
    { baslik: 'Ulaştırmacılık ve Bilgi Materyali (Karar (2009/15481) m.95–99)', sorular: [
      ['Özel araç ve motosikletlerde portatif depolarla taşınan yakıtta muafiyet sınırı nedir?',
        'Araç başına **10 litre**.', 'Karar (2009/15481) m.95/1-b', '',
        'anılan araçlarda portatif depolarla taşınan araç başına on litreyi geçmeyen yakıtlara'],
      ['Motorlu ticari araçların standart depolarındaki muaf yakıt miktarı en fazla ne kadardır?',
        '**TIR çekicisi 550**; istiap haddi **15 tona kadar** (dahil) kamyon/tanker **300**; **15 ton üzeri 400**; **otobüs 300** litre.', 'Karar (2009/15481) m.96/1', '2022',
        ['TIR çekicilerinde 550 litreyi', 'İstiap haddi 15 tona kadar olan (15 ton dahil), kamyon ve tankerlerde 300 litreyi', 'İstiap haddi 15 tonun üzerinde olan kamyon ve tankerlerde ise 400 litreyi', 'Otobüslerde 300 litreyi']],
      ['Standart depo fazlası yakıtta ve gümrüğü yanıltıcı eylemde hangi vergi alınır?',
        'Litre başına **ÖTV tutarının %50 fazlası** tutarında **tek ve maktu vergi** (yanıltıcı eylemde **tüm depodan**).', 'Karar (2009/15481) m.96/3, 96/6', '',
        ['Gümrük kapılarında standart depo fazlası olarak tespit edilen petrol ürünlerinden', 'özel tüketim vergisi tutarının % 50 fazlası tutarındaki vergi, tek ve maktu vergi olarak tahsil edilir', 'gümrük idaresini yanıltıcı her türlü eylemin tespitinde, tüm depodan']],
      ['Otomobil, minibüs ve kamyonetlerde standart depo muafiyeti ayda kaç kez kullandırılır; aşılırsa ne olur?',
        '**AB ülkelerinden girenler hariç**, ayda **en fazla 4 defa**; fazla her girişte **tüm depodan** litre başına **ÖTV tutarında** tek ve maktu vergi alınır.', 'Karar (2009/15481) m.96/4', '',
        ['Avrupa Birliği ülkelerinden giriş yapanlar hariç olmak üzere', 'ayda en fazla dört defa kullandırılır', 'Bir ay içerisinde dört defadan fazla giriş yapan araçlardan her giriş için tüm depodan litre başına']],
      ['Hava yolu şirketlerinin hava taşıtı muafiyetinde koltuk kapasitesi şartı nedir?',
        'Koltuk kapasitesi **20 ve üzeri** olmalı.', 'Karar (2009/15481) m.97/3', '',
        'hava taşıtlarının koltuk kapasitesinin yirmi ve üzeri olması gerekir'],
      ['Turistik reklamcılık malzemesinde özel ticari reklam oranı en fazla ne olabilir?',
        '**%25**\'ten fazla özel ticari reklam içermemeli; ücretsiz dağıtılmalı.', 'Karar (2009/15481) m.99/1', '',
        '% 25\'ten fazla özel ticari reklam içermemesi'],
    ] },
    { baslik: 'Engellilere Ait Eşya ve Kriz Halleri (Karar (2009/15481) m.104–105, 107/5; Tebliğ (Muafiyet Seri No: 2) m.29–34, 38/3)', sorular: [
      ['Engellilerin bizzat kullanacağı özel tertibatlı araçlarda muafiyet şartları nelerdir?',
        'Sunulduğu tarihte **kayıt ve model yılı dahil 3 yıldan eski** olmamalı; **motosiklet**, **1600 cc**\'ye kadar otomobil, **160 kW**\'ı geçmeyen elektrikli otomobil; **arazi taşıtları yararlandırılmaz**.', 'Karar (2009/15481) m.104/2-a, 104/5', '2024',
        ['Gümrük idaresine sunulduğu tarih itibarıyla, kayıt ve model yılı dahil, üç yıldan eski olmamak kaydıyla', 'motosiklet ve motor silindir hacmi 1600 cc.\'ye kadar olan otomobillere ve motor gücü 160 kW\'ı geçmeyen elektrikli otomobillere', 'İkinci fıkranın (a) ve (b) bentlerinin uygulanmasında arazi taşıtları yararlandırılmaz']],
      ['El ve ayak fonksiyonlarını tamamen yitirmiş engelli için getirilen aracı kim kullanabilir; hangi araçlar kapsamdadır?',
        'Engellinin **3. dereceye kadar kan ve sıhri hısımlarından** bir sürücü veya **iş akdiyle istihdam edilen** sürücü; **87.02** pozisyonundaki **minibüsler** ve sürücü dahil **6–9 oturma yerli** uygun tavan yüksekliğindeki araçlar.', 'Karar (2009/15481) m.104/2-b', '',
        ['üçüncü dereceye kadar kan ve sıhri hısımlarından bir sürücü veya kişi ile iş akdine bağlı olarak istihdam edilen sürücü tarafından kullanılan', '87.02 tarife pozisyonu altında sınıflandırılan minibüslere', 'sürücüsü dahil altı ila dokuz oturma yeri olan']],
      ['Hangi hallerde aracın özel tertibatlı olması gerekmez?',
        'Terörle Mücadele Kanunu kapsamındaki **sol bacak engeli olan gaziler**; 104/1-b kapsamında **8703.10.18.00.00** GTİP\'li **akülü araçlar**.', 'Karar (2009/15481) m.104/3, 104/6', '',
        ['3713 sayılı Terörle Mücadele Kanunu kapsamına giren sol bacak engeli olan gaziler için vasıtaların özel tertibatlı olması gerekmez', '8703.10.18.00.00 GTİP\'te yer alan akülü araçların özel tertibatlı olması gerekmez']],
      ['Özel tertibatlı engelli aracında engel türü ve vites bakımından şart nedir?',
        'Kişinin **ortopedik engelinin** bulunması gerekir; aracın **sadece otomatik vitesli** olması muafiyet için **yeterli değildir** (104/3 hükmü saklı).', 'Tebliğ (Muafiyet Seri No: 2) m.29/1, 32/4', '',
        ['özel tertibatlı engelli aracını muafiyet kapsamında serbest dolaşıma sokacak kişinin ortopedik engelinin bulunması gerekir', 'sadece otomatik vitesli olan aracın, Kararın 104 üncü maddesi kapsamında serbest dolaşıma girişi mümkün değildir']],
      ['Özel tertibatlı engelli aracı talebini değerlendiren komisyon ne zaman toplanır, nasıl karar verir; kararın geçerliliği nedir?',
        'Yetkili gümrük müdürlüğünde **her ayın ilk salı** toplanır (Sağlık Bakanlığını temsilen **ortopedi ve travmatoloji uzmanı** dahil); olumlu karar **oybirliği** ile; karar belgesi **6 ay** geçerli.', 'Tebliğ (Muafiyet Seri No: 2) m.31/1, 3–4', '',
        ['ortopedi ve travmatoloji uzmanı bir doktordan oluşan komisyon', 'Söz konusu komisyon yetkili gümrük müdürlüğünde her ayın ilk salı günü toplanır', 'olumlu kararın Komisyon tarafından oybirliği ile verilmesi gerekir', 'karar belgesinin geçerlilik süresi düzenlendiği tarihten itibaren altı aydır']],
      ['Özel tertibatlı engelli araçları için yetkili gümrük idareleri hangileridir?',
        '**Yeşilköy, Gebze, İzmir Yolcu Salonu, Ankara Gar, Malatya, Rize ve Mersin** Gümrük Müdürlükleri.', 'Tebliğ (Muafiyet Seri No: 2) m.38/3', '',
        'özel tertibatlı engelli araçlarının serbest dolaşıma giriş işlemlerinde Yeşilköy Gümrük Müdürlüğü, Gebze Gümrük Müdürlüğü, İzmir Yolcu Salonu Gümrük Müdürlüğü, Ankara Gar Gümrük Müdürlüğü, Malatya Gümrük Müdürlüğü, Rize Gümrük Müdürlüğü ve Mersin Gümrük Müdürlüğü yetkilidir'],
      ['Engelli aracı, engelli kişi tarafından başkasına satılır veya devredilirse vergi durumu nedir?',
        'Başka **engelliye**: süre kısıtı yok, vergi yok. Engelli olmayana: **3 yıl geçmeden satılamaz**; **3–10 yıl** arası vergi tahsil edilir; **10 yıl** sonra vergi aranmaz.', 'Tebliğ (Muafiyet Seri No: 2) m.34/1-a–c; Karar (2009/15481) m.107/5-a', '',
        ['başka bir engelli kişiye herhangi bir süre kısıtı bulunmaksızın ve gümrük vergileri tahsil edilmeksizin aracın devri mümkündür', 'engelli olmayan başka bir kişiye aracın serbest dolaşıma girdiği tarihten itibaren, üç yıl geçmeden aracın satışı mümkün değildir', 'Serbest dolaşıma girdiği tarihten itibaren üç ila on yıl arasında engelli olmayan başka bir kişiye aracın satışında gümrük vergileri tahsil edilir']],
      ['Engelli kişinin vefatı halinde araçla ilgili vergi durumu nedir?',
        'Varise intikalde vergi **aranmaz** (varis veraset ilamından itibaren **6 ay** içinde başvurur); varis aracı serbest dolaşıma girişten itibaren **5 yıl içinde** engelli olmayana satarsa vergi **tahsil edilir**.', 'Tebliğ (Muafiyet Seri No: 2) m.34/1-ç; Karar (2009/15481) m.107/5-b', '',
        ['Aracın varise intikalinde gümrük vergileri aranmaz', 'veraset ilamı tarihinden itibaren altı ay içinde yetkili gümrük idaresine başvurması gerekmektedir', 'Aracın serbest dolaşıma girdiği tarihten itibaren beş yıl içerisinde engelli olmayan başka bir kişiye satışında ise gümrük vergileri tahsil edilir']],
      ['Kriz hallerinde zarar görenlere gönderilen eşyada kimler muafiyetten yararlanır; hangi eşya kapsam dışıdır?',
        '**Kamu kurum ve kuruluşları**, **kamu yararına çalışan dernekler** ve **vergi muafiyeti tanınan vakıflar**; zarar gören bölgelerin **yeniden inşasına** yönelik madde ve malzemeler kapsam dışıdır.', 'Karar (2009/15481) m.105/1, 3', '',
        ['Kamu kurum ve kuruluşları ile kamu yararına çalışan dernekler ve Bakanlar Kurulunca vergi muafiyeti tanınan vakıflar tarafından', 'Kriz hallerinden zarar gören bölgelerin yeniden inşasına yönelik madde ve malzemeler muafiyet kapsamı dışındadır']],
    ] },
    { baslik: 'Ortak Hükümler (Karar (2009/15481) m.107–112; Tebliğ (Muafiyet Seri No: 2) m.40)', sorular: [
      ['Muafen serbest dolaşıma sokulan eşyaya hangi tasarruflar yasaktır; aykırılıkta ne olur?',
        'Gümrük idaresinden **izin alınmaksızın** muafiyetten faydalanamayanlara **ödünç verilemez, teminat gösterilemez, kiralanamaz, devredilemez, satılamaz**, amaç dışı kullanılamaz; aykırılıkta vergiler **GK m.181–194**\'e göre tahsil edilir.', 'Karar (2009/15481) m.107/1, 9', '',
        ['gümrük idaresinden izin alınmaksızın muafiyetten faydalanamayan kişi, kurum ve kuruluşlara belli bir para karşılığı veya karşılıksız olarak ödünç verilemez, teminat olarak gösterilemez, kiralanamaz, devredilemez, satılamaz', 'Bu madde hükümlerine aykırı işlem yapılması halinde, eşyanın gümrük vergileri Kanunun 181 ila 194 üncü maddelerindeki esaslara göre tahsil olunur']],
      ['107. maddedeki devir-satış yasağı hangi sürelerle uygulanır?',
        '**46, 48, 50, 53, 57 ve 80**. madde eşyası için **1 yıl**; **104**. madde eşyası için **3 yıl**; m.80 eşyasında kötüye kullanma riski varsa Müsteşarlıkça **3 yıla** kadar uzatılabilir.', 'Karar (2009/15481) m.107/4', '',
        ['46, 48, 50, 53, 57 ve 80 inci maddede yer alan eşya için bir yıl', '104 üncü maddede yer alan eşya için üç yıl', 'bu süre Müsteşarlıkça üç yıla kadar uzatılabilir']],
      ['Muafen getirilen ambulans ve kurtarma araçlarının devrinde süre sınırları nelerdir?',
        'Tescilden itibaren **5 yıl** geçmedikçe muafiyetten **faydalanan** başka kuruma; **10 yıl** geçmedikçe muafiyetten **faydalanmayan** kuruma vergisiz satılamaz/devredilemez; 10 yıl sonra vergi aranmaz.', 'Karar (2009/15481) m.107/6', '',
        'beyannamenin tescil tarihinden itibaren beş yıl geçmedikçe muafiyetten faydalanan başka bir kurum ve kuruluşa; on yıl geçmedikçe muafiyetten faydalanmayan kurum ve kuruluşlara gümrük vergileri tahsil edilmeden satışı, hibesi veya devri yapılamaz'],
      ['Milli savunma ve iç güvenlik (m.67) kapsamında muafen giren motorlu nakil vasıtaları ne zaman vergisiz satılabilir?',
        'Beyannamenin tescilinden itibaren **10 yıl** geçtikten sonra.', 'Karar (2009/15481) m.107/8', '',
        '67 nci madde kapsamında serbest dolaşıma sokulan motorlu nakil vasıtalarının beyannamenin tescil tarihinden itibaren on yıl geçmedikçe gümrük vergileri tahsil edilmeden satışı yapılamaz'],
      ['Standart depo muafiyetiyle giren yakıtlar başka araçta kullanılabilir mi?',
        '**Hayır**; başka araçta kullanılamaz, **tamir süresi hariç** araçtan çıkarılamaz, depolanamaz, satılamaz, devredilemez.', 'Karar (2009/15481) m.107/7', '',
        'içerisinde ithal edildikleri ulaşım araçlarından başka bir araçta kullanılamaz, ulaşım aracı için gerekli olan tamir süresi haricinde söz konusu ulaşım aracından çıkarılamaz, depolanamaz, satılamaz ve devredilemez'],
      ['Alkol ve tütün ürünlerine muafiyet uygulanır mı?',
        '**Uygulanmaz**; ancak **58, 59 ve 60**. madde (kişisel ve yolcu beraberi eşya) hükümleri saklıdır.', 'Karar (2009/15481) m.109', '',
        '58, 59 ve 60 ıncı madde hükümleri saklı kalmak kaydıyla, alkol ve alkollü ürünler ile tütün ve tütün ürünleri için bu Kısım kapsamında muafiyet uygulanmaz'],
      ['Muafiyet hükümlerinde mücbir sebep ve beklenmeyen haller nelerdir?',
        'Mücbir sebep: **kriz halleri**, devlet yasakları/abluka/savaş, seferberlik, **terör**, kaza-hastalık-gözaltı-tutukluluk-hükümlülük, **iflas**, faaliyetin kamu otoritesince durdurulması. Beklenmeyen hal: **ulaştırma şartlarındaki** beklenmeyen değişiklikler; ilgilinin iradesi ve kusuru dışında hakkın kullanımını doğrudan etkileyen haller.', 'Karar (2009/15481) m.111', '',
        ['Devletçe konulan yasaklar, abluka veya savaş halini', 'Kaza, hastalık ve gözaltında bulunma, tutukluluk veya hükümlülük hallerini', 'Ulaştırma şartlarındaki beklenmeyen değişiklikleri']],
      ['Muafiyet hükümlerinin uygulanmasında diğer mevzuattaki tahdidi ve takyidi hükümler dikkate alınır mı?',
        '**Alınmaz**; istisnası **m.97/2** kapsamı **hava taşıtları**. Ek-9 sınırlarını aşan ve GK **m.235/3** müeyyidesi uygulanan eşya da bu hükme tabidir.', 'Karar (2009/15481) m.112', '',
        ['97 nci maddenin ikinci fikrası kapsamında serbest dolaşıma sokulan hava taşıtları hariç olmak üzere, bu Kısım hükümlerinin uygulanmasında diğer mevzuattan kaynaklanan tahdidi ve takyidi hükümler dikkate alınmaz', 'Kanunun 235 inci maddesinin üçüncü fıkrası uyarınca müeyyide uygulanan eşya birinci fıkra hükmüne tabidir']],
      ['Karar ve Tebliğdeki süreler mücbir sebeple aşılırsa kim, ne kadar uzatabilir?',
        '**Gümrük ve Ticaret Bölge Müdürlükleri**; bir defayla sınırlı, sürelerin **yarısına kadar**; m.58 yolcu işlemleri sürelerini **en fazla 6 aya** kadar.', 'Tebliğ (Muafiyet Seri No: 2) m.40/1', '',
        'bir defayla sınırlı olmak üzere söz konusu sürelerin yarısına kadar; Kararın 58 inci maddesi ile tespit edilen yolcu işlemlerine ilişkin sürelerin en fazla altı aya kadar uzatımına karar vermeye ilgili Gümrük ve Ticaret Bölge Müdürlükleri yetkilidir'],
    ] },
  ],
  tuzaklar: [
    'Değer sınırları: yolcu hediyelik eşyası **430 Avro** (**15 yaş altı 150 Avro**); posta/kargo kitap muafiyeti **150 Avro**; çeyiz hediyesi tanesi **430**, toplam **3.000 Avro**; tüzel kişiye kargo **22 Avro**; tek ve maktu vergi üst sınırı **1500 Avro**, **brüt 30 kg**.',
    'Tek ve maktu vergi (ilaç/takviye gıda): **AB\'den %30**, **diğer ülkelerden %60**, ÖTV **(IV) sayılı liste için ilave %20**; limiti aşan kitapta **%0**.',
    'Getirme süreleri: Ek-9 (A) **sadece beraberde**, (B) **1 ay önce – 3 ay sonra**; çeyiz **2 ay önce – 4 ay sonra**; taşıt/ev eşyası **6 ay**; miras **24 ay**; işyeri nakli **12 ay**; geri getirilen ev eşyası **6 ay ve bir defada**.',
    '**Çift uyruklu** (24 ay ikamet / vatandaşlığa geçiş) **taşıt** muafiyetinden **yararlanamaz**, **ev eşyası** muafiyetinden **yararlanır**. **Evlilik yoluyla** vatandaşlığa geçen taşıt muafiyetinden yararlanamaz.',
    'Taşıt muafiyeti **sürekli görevden** dönen kamu görevlisine tanınır; **24 ayı aşmayan geçici görevliye** tanınmaz. Muafen taşıt getiren **5 yıl** geçmeden yenisini getiremez; ev eşyasını tekrar için yurt dışında **yeniden 24 ay** ikamet gerekir.',
    'Standart depo: **TIR 550**, kamyon/tanker **≤15 ton 300**, **>15 ton 400**, **otobüs 300** litre (550 değil); portatif depo **10 litre**; binek/minibüs/kamyonet ayda **4 defa** (AB hariç); kara hudut yolcusu ayda **10 defa**.',
    'Engelli aracı: **3 yaş**, **1600 cc / 160 kW**, **arazi taşıtı yararlanamaz**; engelli olmayana satış **3 yıl yasak**, **3–10 yıl vergili**, **10 yıl** sonra vergisiz; varis satışında **5 yıl**.',
    'Devir yasağı süreleri: m.46, 48, 50, 53, 57, 80 eşyası **1 yıl** (işyeri nakli **3 yıla** uzatılabilir); engelli eşyası **3 yıl**; ambulans **5 yıl (muafiyetli kuruma) / 10 yıl (muafiyetsize)**; m.67 araçları **10 yıl**.',
  ],
};
