// 50. Konu — Uzlaşma (kaynak: 50-uzlaşma.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '50',
  konu: 'Uzlaşma',
  kaynak: '50-uzlaşma.docx (GK m.244; Gümrük Uzlaşma Yönetmeliği m.3–26)',
  bolumler: [
    { baslik: 'Kanun Hükmü (GK m.244)', sorular: [
      ['Uzlaşma başvurusu hangi alacaklar için ve kim tarafından yapılabilir?',
        'Gümrük idarelerince düzenlenen **ek tahakkuk ve ceza kararı** muhteviyatı alacaklar için **yükümlü veya ceza muhatabı** tarafından.', 'GK m.244/1', '',
        'Gümrük idarelerince düzenlenen ek tahakkuk ve ceza kararı muhteviyatı alacaklar için yükümlü veya ceza muhatabı tarafından uzlaşma başvurusu yapılabilir.'],
      ['Kanuna göre uzlaşmanın kapsamına hangi alacaklar girer?',
        '(a) Beyan ile idarenin tespiti arasındaki **farklılıklara** ilişkin tebliğ edilen gümrük vergileri; (b) idarenin tespitinden **önce beyan sahibince bildirilen** farklılıklara ilişkin gümrük vergileri; (c) gümrük idaresince düzenlenen **idari para cezaları**.', 'GK m.244/1', '',
        ['Beyan ile gümrük idaresi tarafından yapılan tespit sonucunda belirlenen farklılıklara ilişkin tebliğ edilen gümrük vergileri alacakları', 'Gümrük idaresi tarafından tespit edilmesinden önce beyan sahibi tarafından bildirilen farklılıklara ilişkin tebliğ edilen gümrük vergileri alacakları', 'Bu Kanun ve ilgili diğer kanunlar uyarınca gümrük idaresi tarafından düzenlenen idari para cezaları']],
      ['Uzlaşma talebi ne zaman ve hangi alacaklar için yapılır?',
        'Henüz **itiraz edilmemiş** veya itirazı **henüz sonuçlanmamış** gümrük vergileri ve idari para cezaları için, **tebliğ tarihinden itibaren on beş gün** içinde (GK m.242\'deki itiraz süresi).', 'GK m.244/1; Yönetmelik (Uzlaşma) m.11/1', '2023',
        ['henüz itiraz başvurusu yapılmamış veya itiraz edilmiş olmakla birlikte itirazı henüz sonuçlandırılmamış gümrük vergileri ve idari para cezaları için, tebliğ tarihinden itibaren onbeş gün içinde yapılır', 'Kanunun 242 nci maddesinde belirtilen onbeş günlük itiraz süresi içinde yapılır']],
      ['Uzlaşma talebinin itiraz ve dava açma süresine etkisi nedir?',
        'Süre **durur**; uzlaşma vaki olmaz, temin edilemez veya talep **reddedilirse** kaldığı yerden işler; bitimine **beş günden az** kalmışsa süre **beş güne tamamlanır**.', 'GK m.244/1; Yönetmelik (Uzlaşma) m.14/1', '',
        ['Uzlaşma talebinde bulunulması hâlinde, itiraz veya dava açma süresi durur', 'sürenin bitimine beş günden az kalmış olması hâlinde süre beş güne tamamlanır', 'Uzlaşmanın vaki olmaması, temin edilememesi veya uzlaşma talebinin reddedilmesi halinde, tebliğ tarihinden itibaren süre kaldığı yerden işlemeye devam eder.']],
      ['Uzlaşma vaki olmaz veya temin edilemezse aynı alacak için yeniden uzlaşma istenebilir mi?',
        '**Hayır**, yeniden uzlaşma talebinde bulunulamaz; **genel hükümlere** göre işlem yapılır.', 'GK m.244/1, 5; Yönetmelik (Uzlaşma) m.22/3', '',
        ['Uzlaşmanın vaki olmaması veya temin edilememesi hâlinde yeniden uzlaşma talebinde bulunulamaz.', 'Uzlaşmanın vaki olmaması veya temin edilememesi hâlinde, genel hükümlere göre işlem yapılır.']],
      ['Fiil 5607 sayılı Kanundaki kaçakçılık suçlarıyla ilişkiliyse uzlaşma uygulanır mı?',
        '**Hayır**, uzlaşma hükmü uygulanmaz; bu alacaklar için uzlaşma talebinde bulunulamaz.', 'GK m.244/2; Yönetmelik (Uzlaşma) m.6/4', '',
        ['5607 sayılı Kanunda yer alan kaçakçılık suçları ile ilişkili olması hâlinde bu madde hükmü uygulanmaz', 'kaçakçılık suçlarına ilişkin olması halinde uzlaşma talebinde bulunulamaz']],
      ['Uzlaşma komisyonlarının çalışmaları ve uzlaşma tutanaklarının niteliği nedir?',
        'Çalışmalar **gizlidir**; tutanaklar **kesindir**, gereği idarece **derhal** yerine getirilir. Yükümlü/ceza muhatabı uzlaşılan hususlar hakkında **dava açamaz**, hiçbir mercie **şikâyette bulunamaz**.', 'GK m.244/4', '',
        ['Gümrük uzlaşma komisyonlarının çalışmaları gizlidir. Uzlaşma tutanakları kesin olup gereği idarece derhal yerine getirilir.', 'üzerinde uzlaşılan ve tutanakla tespit olunan hususlar hakkında dava açamaz ve hiçbir mercie şikâyette bulunamaz']],
      ['Uzlaşılan gümrük vergileri ve cezalar ne zaman ödenir?',
        'Uzlaşma tutanağının **tebliğinden itibaren bir ay** içinde.', 'GK m.244/5; Yönetmelik (Uzlaşma) m.24/1', '',
        'Uzlaşılan gümrük vergileri ve cezalar, uzlaşma tutanağının tebliğinden itibaren bir ay içinde ödenir.'],
      ['Uzlaşılan vergilere gecikme faizi uygulanır mı?',
        'Evet; **gümrük yükümlülüğünün başladığı** tarihten **uzlaşma tutanağının imzalandığı** tarihe kadar, **6183** sayılı Kanundaki **gecikme zammı oranında** (uzlaşılan tutar üzerinden).', 'GK m.244/5; Yönetmelik (Uzlaşma) m.24/3', '',
        'Uzlaşılan vergilere ilişkin gümrük yükümlülüğünün başladığı tarihten uzlaşma tutanağının imzalandığı tarihe kadar geçen süre için 6183 sayılı Kanun hükümlerine göre belirlenen gecikme zammı oranında gecikme faizi uygulanır.'],
      ['Uzlaşılan cezalarda peşin ödeme indiriminden yararlanılabilir mi?',
        '**Hayır**; 5326 sayılı Kabahatler Kanunu **m.17** uyarınca ayrıca peşin ödeme indiriminden yararlanılamaz.', 'GK m.244/6; Yönetmelik (Uzlaşma) m.23', '',
        'üzerinde uzlaşılan cezalar hakkında 30/3/2005 tarihli ve 5326 sayılı Kabahatler Kanununun 17 nci maddesi uyarınca ayrıca peşin ödeme indiriminden yararlanılamaz'],
      ['Uzlaşma komisyonu başkan ve üyelerine verilecek ücret nasıl belirlenir?',
        '**Cumhurbaşkanı kararıyla.**', 'GK m.244/7', '',
        'Uzlaşma komisyonlarının başkan ve üyelerine, bu komisyonlardaki çalışmaları dolayısıyla verilecek ücret Cumhurbaşkanı'],
    ] },
    { baslik: 'Tanımlar ve Uzlaşmanın Kapsamı (Yönetmelik (Uzlaşma) m.3–6)', sorular: [
      ['"Uzlaşmanın vaki olmaması" ile "uzlaşmanın temin edilememesi" arasındaki fark nedir?',
        '**Vaki olmama:** komisyon teklifinin yükümlüce **kabul edilmemesi**. **Temin edilememe:** yükümlünün davete **katılmaması**, tutanağı **imzalamaması** veya **ihtirazi kayıtla** imzalamak istemesi.', 'Yönetmelik (Uzlaşma) m.3/1-g, ğ', '',
        ['Yükümlünün uzlaşma komisyonunun davetine katılmaması, komisyona geldiği halde uzlaşma tutanağını imzalamaması veya tutanağı ihtirazi kayıtla imzalamak istemesi durumunu', 'Uzlaşma komisyonu teklifinin yükümlü tarafından kabul edilmediği durumu']],
      ['Yükümlü uzlaşma talebinde hangi hususları ileri sürebilir?',
        'Eksiklik veya aykırılıkların **Kanun hükümlerine yeterince nüfuz edememekten** ya da **yanlış yorumlamaktan** kaynaklandığını; olayda **yargı kararları ile idarenin görüş farklılığı** bulunduğunu.', 'Yönetmelik (Uzlaşma) m.4/2', '',
        ['Kanun hükümlerine yeterince nüfuz edememekten veya Kanun hükümlerini yanlış yorumlamaktan kaynaklandığı', 'İhtilaf konusu olayda yargı kararları ile idarenin görüş farklılığının olduğu']],
      ['Beyanın hangi kontroller kapsamında denetlenmesi sonucu tebliğ edilen alacaklar uzlaşma kapsamındadır?',
        'İlgili gümrük idaresinin kontrolü, **ikinci muayene**, **ikincil kontrol**, **sonradan kontrol** ve **ertelenmiş kontrol**.', 'Yönetmelik (Uzlaşma) m.4/3', '',
        'İkinci muayeneye yetkili görevliler tarafından kontrolü, c) İkincil kontrol, ç) Sonradan kontrol, d) Ertelenmiş kontrol'],
      ['Uzlaşma talebi alacağın bir kısmı için yapılabilir mi?',
        'Alacakların **tamamı** için veya vergi/cezaların **tür itibariyle bir kısmı** için yapılabilir; ancak **aynı tür** vergi veya cezanın **bir kısmı** için yapılamaz.', 'Yönetmelik (Uzlaşma) m.5/2, 6/2', '',
        ['Uzlaşma talebi, yükümlüye tebliğ edilen alacakların tamamı için yapılabileceği gibi vergiler veya cezaların tür itibariyle bir kısmı için de yapılabilir.', 'aynı tür vergi veya cezanın bir kısmı için uzlaşma talebinde bulunulamaz']],
      ['Şartlı muafiyet rejimlerine ilişkin hükümlerin ihlalinden doğan alacakta ne uzlaşmaya konu edilebilir?',
        'Alacağın yükümlüye tebliğinden itibaren **15 gün** içinde, alacağa konu **para cezaları**.', 'Yönetmelik (Uzlaşma) m.5/3', '',
        'yükümlüye tebliğinden itibaren 15 gün içinde, alacağa konu para cezaları uzlaşmaya konu edilebilir'],
      ['Hangi alacaklar uzlaşmaya konu edilemez?',
        'Gümrük vergilerinin **matrahına giren** ancak aslı gümrük idarelerince takip ve tahsil **edilmeyen** vergi ve mali yükler; **tahsilat aşamasına gelmiş** alacaklar; **kaçakçılık** suçlarına ilişkin alacaklar.', 'Yönetmelik (Uzlaşma) m.6/1, 3, 4', '',
        ['Gümrük vergilerinin matrahına giren, ancak aslı gümrük idarelerince takip ve tahsil edilmeyen vergi ve benzeri mali yükler uzlaşmaya konu edilemez.', 'İlgili mevzuat uyarınca alacağın tahsilat aşamasına geldiği durumlarda söz konusu alacak uzlaşmaya konu edilemez.']],
      ['Uzlaşmaya konu alacağın 5607 sayılı Kanunun 3 üncü maddesindeki fiillerle ilişkili sayıldığı haller nelerdir?',
        'Takibat talebiyle **fezleke veya rapor** düzenlenmiş ya da adli makamlara **bildirim** yapılmış olması; **soruşturma veya kovuşturma** yapılıyor olması; mahkemece **ceza verilmiş** olması. İlişki uzlaşma sürecinin **her aşamasında** değerlendirilir.', 'Yönetmelik (Uzlaşma) m.6/5–6', '',
        ['fezleke veya rapor düzenlenmiş ya da adli makamlara bildirimde bulunulmuş olması', 'Adli mercilerce soruşturma ya da kovuşturma yapılıyor olması', 'İlişki olup olmadığı hususu, uzlaşma sürecinin her aşamasında değerlendirilir.']],
      ['Eşyanın mülkiyetinin kamuya geçirilmesine ilişkin kararlar uzlaşmaya konu olur mu?',
        '**Hayır**; ancak bu eşyaya ilişkin **gümrük vergileri ve para cezaları** uzlaşmaya konu edilebilir.', 'Yönetmelik (Uzlaşma) m.6/7', '',
        ['Eşyanın mülkiyetinin kamuya geçirilmesine ilişkin kararlar uzlaşmaya konu edilmez.', 'mülkiyetin kamuya geçirilmesine karar verilen eşya ile ilgili gümrük vergileri ve para cezaları uzlaşmaya konu edilebilir']],
    ] },
    { baslik: 'Uzlaşma Komisyonları ve Yetkileri (GK m.244/3; Yönetmelik (Uzlaşma) m.7–9)', sorular: [
      ['Uzlaşma taleplerini hangi komisyonlar değerlendirir?',
        '**Gümrük ve Dış Ticaret Bölge Müdürlüğü Uzlaşma Komisyonları** ile **Merkezi Uzlaşma Komisyonları** (gümrük uzlaşma komisyonları).', 'GK m.244/3; Yönetmelik (Uzlaşma) m.3/1-e, 7/1', '',
        ['Bu madde kapsamında yapılan uzlaşma talepleri, gümrük uzlaşma komisyonları tarafından değerlendirilir.', 'Gümrük ve Dış Ticaret Bölge Müdürlüğü Uzlaşma Komisyonları ile Merkezi Uzlaşma Komisyonlarını']],
      ['Bölge Müdürlüğü Uzlaşma Komisyonu kaç üyeden oluşur; kim başkanlık eder?',
        'Bölge Müdürünce belirlenen, **başkan dâhil üç üye**; **Bölge Müdürü** veya belirleyeceği **Bölge Müdür Yardımcısı** başkanlık eder.', 'Yönetmelik (Uzlaşma) m.7/2', '',
        ['arasından Bölge Müdürü tarafından belirlenen, Başkan dâhil, üç üyeden oluşur', 'Bölge Müdürü veya belirleyeceği Bölge Müdür Yardımcısı komisyonlara başkanlık eder']],
      ['Merkezi Uzlaşma Komisyonlarına kim başkanlık eder?',
        '**Bakan Yardımcısı** veya **Gümrükler Genel Müdürü**; komisyon yine **başkan dâhil üç üyedir**.', 'Yönetmelik (Uzlaşma) m.7/3', '',
        'Komisyonlara, Bakan Yardımcısı veya Gümrükler Genel Müdürü başkanlık eder.'],
      ['Uzlaşma komisyonları nasıl toplanır ve karar alır?',
        'Üyelerin **tamamının katılımıyla** toplanır, **oy çokluğuyla** karar alır.', 'Yönetmelik (Uzlaşma) m.7/4', '',
        'Komisyonlar üyelerinin tamamının katılımıyla toplanır ve oy çokluğuyla karar alır.'],
      ['Bölge Müdürlüğünde birden fazla uzlaşma komisyonu ne zaman oluşturulabilir?',
        'Aynı gün yapılacak görüşme sayısı **yirmi veya üzerinde** ise **en fazla iki** komisyon.', 'Yönetmelik (Uzlaşma) m.7/6', '',
        'aynı gün yapılacak uzlaşma görüşmesi sayısının yirmi veya üzerinde olması halinde, en fazla iki adet uzlaşma komisyonu oluşturulabilir'],
      ['Uzlaşma komisyonları hangi tutarın altındaki talepler için toplanamaz; istisnaları nelerdir?',
        '**10.000 TL\'den az** talepler için toplanamaz. Üç ay içinde 10.000 TL\'ye ulaşmayan talepler **takip eden ay** içinde sonuçlandırılır; kişisel kullanıma mahsus geçici ithal taşıtta ihlalin **çıkışta tespiti** halinde bu kural uygulanmaz, talep **derhal** sonuçlandırılır.', 'Yönetmelik (Uzlaşma) m.7/7–8, 18/2', '',
        ['10.000 TL\'den az olan uzlaşma talepleri için toplanamaz', 'üç ay içerisinde 10.000 TL\'ye ulaşmaması halinde, takip eden ay içinde mevcut uzlaşma talepleri sonuçlandırılır', 'Yükümlünün uzlaşma talebi derhal sonuçlandırılır.']],
      ['Bölge Müdürlüğü ve Merkezi Uzlaşma Komisyonlarının yetki sınırı nedir?',
        '**7.000.000 TL\'ye kadar (bu tutar dâhil)** Bölge Müdürlüğü Uzlaşma Komisyonları; **aşanlar** için Merkezi Uzlaşma Komisyonları.', 'Yönetmelik (Uzlaşma) m.9/1', '',
        ['konusu 7.000.000.- TL', 'kadar olanlar (bu tutar dâhil) için Gümrük ve Dış Ticaret', 'aşanlar için ise Merkezi Uzlaşma Komisyonları yetkilidir']],
      ['Komisyonların yetki tutarının tespitinde cezalar ve fer\'i alacaklar nasıl dikkate alınır?',
        'Vergi aslına bağlı olmayan cezalar ile usulsüzlük cezaları **ayrı ayrı** dikkate alınır; aynı nitelikteki cezalarda **toplam** esas alınır; **fer\'i alacaklar dikkate alınmaz**.', 'Yönetmelik (Uzlaşma) m.9/4–5', '',
        ['Vergi aslına bağlı olmayan cezalar ile usulsüzlük cezalarının ayrı ayrı dikkate alınması esastır.', 'Birinci fıkrada belirtilen tutarların tespitinde fer\'i alacaklar dikkate alınmaz.']],
    ] },
    { baslik: 'Başvuru ve Usul İncelemesi (Yönetmelik (Uzlaşma) m.10–14)', sorular: [
      ['Uzlaşma başvurusu nasıl yapılır; süre hesabında hangi tarih esas alınır?',
        '**BİLGE şifresiyle kurumsal internet sayfası** üzerinden; şifre temin edilemezse **EK-3 form** ile. Sürede formun **evrak kaydına girdiği** veya **taahhütlü postaya verildiği** tarih esastır.', 'Yönetmelik (Uzlaşma) m.10/1', '',
        ['BİLGE şifresi kullanılarak, kurumsal internet sayfası üzerinden yapılır', 'ilgili merciin evrak kaydına girdiği veya taahhütlü olarak postaya verildiği tarih esas alınır']],
      ['İştirak sebebiyle ceza uygulananlarda uzlaşma nasıl işler?',
        'Her biri talepte bulunabilir; uzlaşma **sadece başvuranlar** için hüküm ifade eder.', 'Yönetmelik (Uzlaşma) m.10/2', '',
        ['İştirak sebebiyle ceza tatbik edilenlerin her biri uzlaşma talebinde bulunabilir.', 'uzlaşma, sadece başvuruda bulunanlar için hüküm ifade eder']],
      ['Kimler uzlaşma talebinde bulunabilir?',
        '**Yükümlü**, **temsilcisi**, **özel vekâletname** verilmiş gümrük müşaviri, **veli veya vasi** ve yükümlüyle **müştereken ve müteselsilen sorumlu** gümrük müşavirleri.', 'Yönetmelik (Uzlaşma) m.12', '',
        'Yükümlünün kendisi, temsilcisi veya özel vekâletname verilmesi şartıyla gümrük müşaviri; veli ya da vasi veya aynı gümrük vergilerinin ödenmesinden yükümlü ile birlikte müştereken ve müteselsilen sorumlu olması halinde gümrük müşavirleri uzlaşma talebinde bulunabilir.'],
      ['Usul incelemesinde giderilebilir eksiklik bulunan başvuruya ne kadar süre verilir?',
        'Başvuru süresinin **sonuna kadar**; süre sonunda başvurulmuşsa **üç iş günü** ek süre. Eksiklik tamamlanmazsa talep **reddedilir**.', 'Yönetmelik (Uzlaşma) m.13/2', '',
        ['yükümlüye eksikliklerin tamamlanması için başvuru süresinin sonuna kadar süre verilir', 'üç iş günü ek süre verilir', 'Verilen sürenin sonunda eksikliklerin tamamlanmaması halinde talep reddedilir.']],
      ['Uzlaşma talebinin kabul edilmemesine ilişkin işleme karşı itiraz veya dava yolu açık mıdır?',
        '**Evet**; itiraz veya yargı yoluna açıktır, genel usullere göre dava konusu edilebilir.', 'Yönetmelik (Uzlaşma) m.13/3', '',
        'Uzlaşma talebinin kabul edilmemesine ilişkin idari işlem itiraz veya yargı yoluna açık olup genel usullere göre dava konusu edilebilir.'],
      ['Uzlaşma başvurusundan feragat ne zamana kadar ve nasıl yapılır; sonucu nedir?',
        'Uzlaşma **davetiyesi tebliğ edilmeden önce**, sekretaryaya **dilekçe** ile; feragatin kabulünün tebliğinden itibaren itiraz/dava süresi kaldığı yerden işler ve aynı alacak için **tekrar uzlaşma istenemez**.', 'Yönetmelik (Uzlaşma) m.14/2', '',
        ['kendisine uzlaşma davetiyesi yazısı tebliğ edilmeden önce', 'bir dilekçe ile başvurarak uzlaşma başvurusundan feragat edebilir', 'aynı alacak için tekrar uzlaşma talebinde bulunulamaz']],
      ['Yükümlü ile müştereken ve müteselsilen sorumlu gümrük müşavirinden biri uzlaşma, diğeri itiraz yolunu seçerse ne olur?',
        'İtiraz eden tarafın talebi **uzlaşma talebi sonuçlandıktan sonra** değerlendirilir. (İkisi de uzlaşma isterse başvurular **beraber** sonuçlandırılır.)', 'Yönetmelik (Uzlaşma) m.14/3–4', '',
        ['yükümlü ile gümrük müşavirinin uzlaşma başvurusu beraber sonuçlandırılır', 'itiraz başvurusunda bulunan tarafın talebi uzlaşma talebi sonuçlandıktan sonra değerlendirmeye alınır']],
    ] },
    { baslik: 'Uzlaşma Görüşmeleri ve Süreler (Yönetmelik (Uzlaşma) m.15–18)', sorular: [
      ['Uzlaşma görüşmelerine kimler katılabilir; katılacak kişi sayısı sınırı nedir?',
        'Esas olan **yükümlünün veya veli/vasinin bizzat** katılmasıdır; katılmazsa **temsilcisi** veya **özel yetkili gümrük müşaviri** katılıp tutanağı imzalayabilir. Yükümlü dâhil katılan kişi sayısı **üçü geçemez**.', 'Yönetmelik (Uzlaşma) m.15/1, 3', '',
        ['Uzlaşma komisyonu görüşmelerine yükümlünün veya veli ya da vasinin bizzat katılması esastır.', 'Uzlaşma komisyonlarına, yükümlü dâhil, katılacak kişi sayısı üçü geçemez.']],
      ['Uzlaşma davetiyesi yükümlüye en az ne kadar önce tebliğ edilir?',
        '**En az beş gün** önceden (EK-4), yazıyla veya e-posta ile **7201** sayılı Tebligat Kanununa göre; yükümlü isterse daha önceki bir tarih belirlenebilir.', 'Yönetmelik (Uzlaşma) m.16/1', '',
        ['EK-4\'e uygun düzenlenen uzlaşma davetiyesi ile en az beş gün önceden', 'Yükümlünün istemesi halinde beş günlük süreye bağlı kalınmaksızın daha önceki bir tarih, uzlaşma günü olarak belirlenebilir.']],
      ['Uzlaşma sağlanırsa tutanak nasıl düzenlenir?',
        '**EK-5**\'e uygun **üç nüsha**; komisyon başkan ve üyeleri ile yükümlü imzalar, yükümlüye **derhal tebliğ** edilir.', 'Yönetmelik (Uzlaşma) m.16/4', '',
        ['uzlaşma komisyonu durumu EK-5\'e uygun olarak üç nüsha düzenlenen tutanakla tespit eder', 'tutanak üzerine imza alınarak yükümlüye derhal tebliğ edilir']],
      ['Uzlaşma vaki olmazsa yükümlü komisyonun nihai teklifini sonradan kabul edebilir mi?',
        '**Evet**; GK m.242\'deki sürenin **son günü mesai saati bitimine kadar** dilekçe ile bildirirse, bu tarih itibarıyla uzlaşma **vaki olmuş sayılır**.', 'Yönetmelik (Uzlaşma) m.16/6', '',
        ['Kanunun 242 nci maddesinde belirtilen sürenin son günü mesai saati bitimine kadar komisyonun nihai teklifini kabul ettiğini bir dilekçe ile', 'bu tarih itibarıyla uzlaşma vaki olmuş sayılır']],
      ['Uzlaşma tutanaklarına geçirilen kararların gerekçesi yazılır mı?',
        '**Hayır**; sonucun tutanağa geçirilmesiyle yetinilir, gerekçe ayrıca belirtilmez.', 'Yönetmelik (Uzlaşma) m.16/8', '',
        'Tutanaklara geçirilen kararların gerekçesi ayrıca belirtilmez.'],
      ['Yükümlü uzlaşma toplantısının ertelenmesini isteyebilir mi?',
        'Evet; **makul gerekçeyle**, toplantı **başlamadan önce** bildirmek şartıyla ve **bir defaya mahsus**.', 'Yönetmelik (Uzlaşma) m.17/2', '',
        'Yükümlü tarafından makul gerekçelerle katılım sağlanamayacağının toplantı başlamadan önce komisyona bildirilmesi şartıyla ve bir defaya mahsus olmak üzere toplantı'],
      ['Uzlaşma talebi en geç ne kadar sürede sonuçlandırılır?',
        'Dilekçenin komisyon kayıtlarına girdiği tarihten itibaren **azami 45 gün**; ayrıntılı inceleme veya araştırma gerekirse bu süre aşılabilir.', 'Yönetmelik (Uzlaşma) m.18/1', '',
        'kayıtlarına girdiği tarihten itibaren azami 45 gün içinde sonuçlandırılması esastır'],
    ] },
    { baslik: 'Uzlaşmanın Sonuçları ve Teminatlı İşlemler (Yönetmelik (Uzlaşma) m.21–26)', sorular: [
      ['Uzlaşma tutanakları ve komisyon işlemleri hakkında kimler dava açamaz?',
        'Yükümlü veya ceza muhatabı **ya da idare**; dava açılamaz, şikâyet veya itiraz edilemez, idari inceleme-soruşturmaya konu edilemez, **geri verme ve kaldırma** talep edilemez.', 'Yönetmelik (Uzlaşma) m.21/3', '',
        'yükümlü veya cezanın muhatabı ya da idare tarafından dava açılamaz, hiçbir mercie şikayet veya itirazda bulunulamaz, herhangi bir idari inceleme, araştırma ve soruşturmaya konu edilemez, geri verme ve kaldırma talebinde bulunulamaz'],
      ['İtiraz hakkı ile uzlaşma hakkı aynı anda kullanılabilir mi?',
        '**Hayır**; uzlaşmaya konu alacaklar **feragat, ret, vaki olmama veya temin edilememe** halinde GK m.242 çerçevesinde itiraza konu olabilir. İtiraz **henüz sonuçlanmamışsa** tebliğden itibaren 15 gün içinde uzlaşma istenebilir.', 'Yönetmelik (Uzlaşma) m.25/1', '',
        ['Kanunun 242 nci maddesinde düzenlenen itiraz hakkı ile 244 üncü maddesinde düzenlenen uzlaşma hakkını aynı anda kullanamaz', 'İtirazın henüz sonuçlandırılmamış olması kaydıyla alacağın tebliğ tarihinden itibaren onbeş gün içinde']],
      ['Gümrüklü yer ve sahalardaki eşyaya ilişkin alacak için uzlaşma istenirse eşya yükümlüsüne teslim edilebilir mi?',
        '**Evet**; ayrıca talep edilmesi şartıyla alacaklar **teminata bağlanarak** teslim edilebilir. Uzlaşma vaki olursa uzlaşılan tutar **teminattan mahsup** edilir; nakden ödenirse teminat **iade** edilir.', 'Yönetmelik (Uzlaşma) m.26/1–2', '',
        ['ayrıca talep edilmesi şartıyla, tahakkuk eden alacaklar teminata bağlanarak eşya yükümlüsüne teslim edilebilir', 'uzlaşılan tutar teminattan mahsup edilir', 'Uzlaşılan tutarın yükümlü tarafından nakden ödenmesi halinde ise teminat iade edilir.']],
    ] },
  ],
  tuzaklar: [
    'Süreler: uzlaşma talebi tebliğden itibaren **15 gün** (GK m.242 itiraz süresi); davetiye **en az 5 gün** önce; işlemler **azami 45 gün**; ödeme tutanağın tebliğinden itibaren **1 ay**; eksiklik için ek süre **3 iş günü**.',
    'Uzlaşma talebi itiraz/dava süresini **durdurur**; süre kaldığı yerden işler, **5 günden az** kalmışsa **5 güne** tamamlanır.',
    '**Vaki olmama** = komisyon teklifinin kabul edilmemesi; **temin edilememe** = davete gelmeme, imzalamama, **ihtirazi kayıtla** imza. İkisinde de **yeniden uzlaşma istenemez**.',
    'Yetki: **7.000.000 TL\'ye kadar (dâhil)** Bölge Müdürlüğü, aşanlar **Merkezi** komisyon; **10.000 TL\'den az** talepler için komisyon toplanmaz; **fer\'i alacaklar** tutar tespitinde dikkate alınmaz.',
    'Komisyonlar **başkan dâhil 3 üye**, **tam katılımla** toplanır, **oy çokluğuyla** karar verir; görüşmeye yükümlü dâhil en fazla **3 kişi** katılır; aynı gün **20+** görüşmede en fazla **2** komisyon.',
    'Uzlaşmaya konu olmaz: **kaçakçılık** suçlarıyla ilişkili alacaklar, **tahsilat aşamasına** gelmiş alacaklar, aslı gümrükçe takip edilmeyen vergiler, **mülkiyetin kamuya geçirilmesi kararı** (ilgili vergi ve cezalar ise olur).',
    'Uzlaşılan cezalarda **peşin ödeme indirimi yok**; uzlaşılan vergilere **gecikme faizi** (yükümlülüğün başladığı tarihten tutanağın **imzalandığı** tarihe kadar) uygulanır.',
    'Uzlaşma tutanağına **dava açılamaz** (idare de açamaz); ama uzlaşma **talebinin kabul edilmemesi** işlemi itiraz ve yargı yoluna **açıktır**. İtiraz ve uzlaşma **aynı anda** kullanılamaz.',
  ],
};
