// 26. Konu — Transit Rejiminde Denizyolu Basitleştirmesi (kaynak: 26-seri no 8.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '26',
  konu: 'Transit Rejiminde Denizyolu Basitleştirmesi (Seri No: 8)',
  kaynak: '26-seri no 8.docx (Gümrük Genel Tebliği (Transit Rejimi) Seri No: 8, m.1–16)',
  bolumler: [
    { baslik: 'Amaç ve Dayanak (Tebliğ m.1–2)', sorular: [
      ['Seri No: 8 Tebliğin amacı nedir?',
        'Transit rejimi çerçevesinde eşyanın **denizyolu ile basitleştirilmiş usulde** taşınmasına ilişkin usul ve esasları düzenlemek.', 'Transit Tebliği (Seri No: 8) m.1', '',
        'transit rejimi çerçevesinde eşyanın denizyolu ile basitleştirilmiş usulde taşınmasına ilişkin olarak uygulanacak usul ve esasları düzenlemektir'],
      ['Tebliğin dayanağı olan GK ve GY maddeleri hangileridir?',
        'GK **m.84–92** ve GY **m.236**.', 'Transit Tebliği (Seri No: 8) m.2', '',
        ['4458 sayılı Gümrük Kanununun 84 ilâ 92 nci maddeleri', 'Gümrük Yönetmeliğinin 236 ncı maddesine dayanılarak hazırlanmıştır']],
    ] },
    { baslik: 'Başvuru Koşulları ve İznin Verilmesi (Tebliğ m.4–6)', sorular: [
      ['Denizyolu basitleştirme izni için başvuru sahibinin sahip olması gereken yetki belgesi nedir?',
        'Ulaştırma ve Altyapı Bakanlığınca (**Deniz ve İçsular Düzenleme Genel Müdürlüğü**) verilmiş **Gemi Acenteliği Yetki Belgesi**.', 'Transit Tebliği (Seri No: 8) m.4/1-a', '',
        'Ulaştırma ve Altyapı Bakanlığı (Deniz ve İçsular Düzenleme Genel Müdürlüğü) tarafından verilmiş olan Gemi Acenteliği Yetki Belgesine sahip olmak'],
      ['Özel koşullar hangi genel koşullara ilavedir; diğer özel koşul nedir?',
        'GY **m.230/1** koşullarına ilave; diğer özel koşul **manifesto ve konşimento kayıtlarını elektronik** tutmak ve sisteme iletim altyapısına sahip olmak.', 'Transit Tebliği (Seri No: 8) m.4/1', '',
        ['Yönetmeliğin 230 uncu maddesinin birinci fıkrasında belirtilen koşullara ilave olarak', 'Manifesto ve konşimento kayıtlarını elektronik ortamda tutmak ve bu bilgilerin gümrük idaresinin sistemine iletilebilmesi için gerekli elektronik altyapıya sahip olmak']],
      ['GY m.230/1-(ç) koşulu hangi faaliyet hacmiyle sağlanmış sayılır?',
        'Başvurunun kayda alındığı **ayın ilk gününden geriye son 1 yıl** içinde TGB deniz limanları arasında denizyoluyla **500 konteyner** kapsamı eşyanın transit edilmesi.', 'Transit Tebliği (Seri No: 8) m.4/2', '',
        'başvurunun kayda alındığı ayın ilk gününden geriye dönük son bir yıl içerisinde Türkiye Gümrük Bölgesindeki deniz limanları arasında denizyoluyla 500 konteyner kapsamı eşyanın transit edilmiş olması durumunda da, Yönetmeliğin 230 uncu maddesinin birinci fıkrasının (ç) bendindeki koşul sağlanmış olarak değerlendirilir'],
      ['GY m.232 belgelerine ek olarak hangi belgeler sunulur?',
        'Ek-1 **başvuru formu**, Ek-2 **beyan ve taahhüt metni** ve **Gemi Acenteliği Yetki Belgesinin bir örneği**.', 'Transit Tebliği (Seri No: 8) m.4/3', '',
        ['Yönetmeliğin 232 nci maddesi uyarınca ibraz edilecek belgelere ek olarak', 'Şirketi temsile yetkili kişilerce imzalanmış Ek-2\'de yer alan beyan ve taahhüt metnini', 'Gemi Acenteliği Yetki Belgesinin bir örneğini']],
      ['Denizyolu basitleştirme izni için başvuru yeri ve izin makamı neresidir?',
        '**Gümrükler Genel Müdürlüğü.**', 'Transit Tebliği (Seri No: 8) m.5', '',
        'basitleştirme izni için başvuru yeri ve izin makamı Gümrükler Genel Müdürlüğüdür'],
      ['Denizyolu basitleştirme izni hangi eşya ve taşımada kullanılır?',
        'Yurtdışından getirilen veya yurtdışı edilecek **konteynerle taşınan** eşyanın **TGB içindeki deniz limanları arasında** denizyoluyla taşınmasında.', 'Transit Tebliği (Seri No: 8) m.6/1', '',
        'yurtdışından Türkiye Gümrük Bölgesine getirilen veya Türkiye Gümrük Bölgesinden yurtdışı edilecek olan, konteynerle taşınan eşyanın Türkiye Gümrük Bölgesi içerisindeki deniz limanları arasında denizyoluyla taşınmasında kullanılmak üzere verilir'],
      ['Başvurudaki eksiklikler ne kadar sürede tamamlanır?',
        'Bildirimden itibaren en geç **60 gün**; tamamlanmazsa başvuru **yapılmamış sayılır**.', 'Transit Tebliği (Seri No: 8) m.6/3', '',
        ['bildirimin yapıldığı tarihi müteakip en geç altmış gün içinde tamamlanır', 'Bu süre içerisinde tamamlanmayan başvuru yapılmamış sayılır']],
      ['Denizyolu basitleştirme izni hangi eşyanın taşınmasında kullanılamaz?',
        'GY **m.225** kapsamındaki eşya ile GTC **22.08 ve 24.02** pozisyonlarındaki eşya.', 'Transit Tebliği (Seri No: 8) m.6/6', '',
        'Yönetmeliğin 225 inci maddesi kapsamına giren eşyanın ve Türk Gümrük Tarife Cetvelinin 22.08 ve 24.02 pozisyonlarında yer alan eşyanın taşınmasında kullanılamaz'],
    ] },
    { baslik: 'Transit Beyanı Olarak İletilecek Bilgiler (Tebliğ m.7)', sorular: [
      ['Her taşıma için idareye elektronik ortamda hangi bilgiler iletilir?',
        'Gemi acentesinin **vergi numarası**, geminin **IMO ve sefer numarası**, hareket tarihi, hareket ve varış idareleri, **konşimento numaraları**.', 'Transit Tebliği (Seri No: 8) m.7/2', '',
        ['Taşımayı gerçekleştiren gemi acentesinin vergi numarası', 'Taşımanın gerçekleştirileceği geminin IMO ve sefer numarası']],
      ['Konşimento numarası karşısında hangi kodlar kullanılır?',
        '**4 kod:** T, TD (serbest dolaşımda olmayan eşya), X, XD (ihracat eşyası); "D" eki önceki seferle taşınan eşyanın **devamı** içindir.', 'Transit Tebliği (Seri No: 8) m.7/3', '',
        ['Serbest dolaşımda olmayan eşya için "T" kodu', 'İhracata konu eşya için "X" kodu', 'daha önceki bir sefer ile taşınan eşyanın devamı niteliğindeki eşya için "TD" kodu']],
      ['İdareye ibraz edilecek listede her konşimento için asgari hangi bilgiler yer alır?',
        'Konşimentodaki alıcı ve gönderici, kap adedi, ticari tanım (gruplandırmada **"konsolide"**), brüt ağırlık ve **konteyner numarası**.', 'Transit Tebliği (Seri No: 8) m.7/5', '',
        ['a) Konşimentodaki alıcı, b) Konşimentodaki gönderici', 'eşya tanımı yerine "konsolide" ifadesi kullanılır', 'Brüt ağırlık, e) Konteyner numarası']],
    ] },
    { baslik: 'Hareket ve Varış Gümrük İdaresinde İşlemler (Tebliğ m.8–9)', sorular: [
      ['Bilgiler ne zamana kadar ve nasıl iletilir?',
        '**Geminin hareketine kadar**, izin sahibince **EDI** ile; kabulle birlikte izin sahibine **kayıt numarası** iletilir.', 'Transit Tebliği (Seri No: 8) m.8/2', '',
        ['7 nci maddenin ikinci fıkrasında yer alan bilgiler geminin hareketine kadar izin sahibi tarafından gümrük idaresinin sistemine elektronik veri değişimi sistemi ile iletilir', 'izin sahibine kayıt numarası bilgisi iletilir']],
      ['Denizyolu basitleştirmesinde rejim hak sahibi kim olur?',
        'm.7 bilgilerini sisteme **elektronik olarak ileten izin sahibi**.', 'Transit Tebliği (Seri No: 8) m.8/3', '',
        '7 nci maddede yer alan bilgileri gümrük idaresinin sistemine elektronik olarak ileten izin sahibi, taşıma işlemleri için rejim hak sahibi olur'],
      ['İletilen bilgilerde değişiklik ne zamana kadar yapılabilir?',
        '**Hareket gümrük idaresince sistemde işlemler ikmal edilinceye kadar**, kayıt numarası kullanılarak.', 'Transit Tebliği (Seri No: 8) m.8/4', '',
        'hareket gümrük idaresince sistemde gerekli işlemler ikmal edilinceye kadar, değişiklik bilgileri ilgili kayıt numarası kullanılarak'],
      ['Hareket idaresi kontrolü nasıl yapar; bilgilerin yanlış beyan edildiği anlaşılırsa ne olur?',
        'Bilgiler özet beyan/beyanname kayıtları, **elektronik manifesto** ve konşimentolarla **karşılaştırılır**; yanlışlıkta işlemler **ikmal edilmeden önce** izin sahibinin **düzeltmesine izin** verilir.', 'Transit Tebliği (Seri No: 8) m.8/5', '',
        ['giriş özet beyan ya da beyanname kayıtları, elektronik ortamdaki manifesto bilgileri ve konşimentolarla karşılaştırılması suretiyle gerçekleştirilir', 'sistemdeki işlemler ikmal edilmeden önce izin sahibinin söz konusu bilgileri düzeltmesine izin verilir']],
      ['Varış işlemi ne zaman ve neye dayanılarak yapılır?',
        '**Geminin varış limanına ulaştığının** gümrük idaresince tespiti üzerine, **kayıt numarası** üzerinden.', 'Transit Tebliği (Seri No: 8) m.9/1', '',
        'geminin varış limanına ulaştığının gümrük idaresince tespit edilmesi üzerine, 8 inci maddenin ikinci fıkrasında belirtilen kayıt numarası üzerinden varış işlemi gerçekleştirilir'],
      ['Yurtdışı edilmek üzere sevk edilen ihracat eşyasında çıkış bildirimi işlemleri ne zaman tamamlanır?',
        '**Geminin TGB\'yi terk etmesinden sonra.**', 'Transit Tebliği (Seri No: 8) m.9/2-b', '',
        'geminin Türkiye Gümrük Bölgesini terk etmesinden sonra çıkış bildirimine ilişkin işlemler tamamlanır'],
      ['Varış idaresinde tespit edilen beyana aykırılıklarda hangi hükümler uygulanır?',
        'Gümrük Yönetmeliği **m.239–242**.', 'Transit Tebliği (Seri No: 8) m.9/4', '',
        'Varış gümrük idaresinde tespit edilen beyana aykırılıklar için Yönetmeliğin 239 ilâ 242 nci maddeleri çerçevesinde işlem yapılır'],
    ] },
    { baslik: 'Askı, İptal ve İzin Sahibinin Yükümlülükleri (Tebliğ m.10–12)', sorular: [
      ['İzin koşulları karşılanmazsa hangi süreler işler?',
        'Düzeltme için **30 gün** (+**30 gün**); düzeltilmezse izin **30 gün** askıya alınır, talep üzerine **60 gün** uzatılabilir; sonra **iptal**.', 'Transit Tebliği (Seri No: 8) m.10/1–2', '',
        ['bildirim tarihinden başlamak üzere otuz gün süre verilir', 'izni otuz gün süre ile askıya alır', 'Otuz günlük askıya alma süresi izin sahibinin talebi üzerine altmış gün daha uzatılabilir']],
      ['Tebliğ hükümlerine aykırılıkta uyarı ve askı nasıl uygulanır?',
        'İlk **iki** seferde **yazılı uyarı**; bir **takvim yılında** aynı hükmün **üçüncü** ihlalinde **30 gün** askı.', 'Transit Tebliği (Seri No: 8) m.10/3', '',
        ['izin sahibi ilk iki seferde yazılı olarak uyarılır', 'aynı hükmün üçüncü kez ihlal edilmesi durumunda izin, otuz gün süreyle askıya alınır']],
      ['Yargı kararı verilen kişi nedeniyle izin hangi durumda iptal edilir?',
        'Kişinin **60 gün** içinde firma ile **ilişiği kesilmezse**.', 'Transit Tebliği (Seri No: 8) m.11/1-c', '',
        'hakkında yargı kararı verilmiş kişinin 60 gün içerisinde firma ile ilişiğinin kesilmemiş olması'],
      ['İptalin yürürlük tarihini kim erteleyebilir; iptal sonrası başvurular ne olur?',
        'Haklı talepte **izin makamı** erteleyebilir; iptali müteakip **1 yıl** içinde yapılan başvurular **reddedilir**.', 'Transit Tebliği (Seri No: 8) m.11/2–3', '',
        ['izin sahibinin haklı talepleri söz konusu olduğunda izin makamı, iptalin yürürlüğe giriş tarihini erteleyebilir', 'iptal işlemini müteakip bir yıl içerisinde yapılan izin başvuruları reddedilir']],
      ['Taşıma yapılacak deniz limanlarındaki değişiklik ne zaman bildirilir?',
        'Taşımaların başlamasından **en geç 15 gün önce** Bakanlığa.', 'Transit Tebliği (Seri No: 8) m.12/1-a', '',
        ['Basitleştirme izni kapsamında taşıma yapılacak deniz limanlarına ilişkin değişiklik', 'taşımaların başlamasının planlandığı tarihten en geç 15 gün öncesinde Bakanlığa bildirmekle']],
      ['İzin şartlarında değişiklik olursa izin sahibi ne zaman bildirim yapar?',
        'En geç **30 gün** içinde **izin makamına**.', 'Transit Tebliği (Seri No: 8) m.12/1-i', '',
        'en geç otuz gün içerisinde izin makamına durumunu bildirmekle'],
    ] },
  ],
  tuzaklar: [
    'Denizyolunda izin sahibi **kişi** (Gemi Acenteliği Yetki Belgesi sahibi); rejim hak sahibi bilgileri **elektronik ileten izin sahibi**; dayanak GK **m.84–92** ve GY **m.236**.',
    'İzin yalnız **konteynerle taşınan** eşyanın **TGB\'deki deniz limanları arasında** taşınması içindir; GY 225 kapsamı ile **22.08 ve 24.02** eşyası hariç.',
    '**500 konteyner** (kayıt ayının ilk gününden geriye **son 1 yıl**) → GY **230/1-(ç)** koşulu sağlanmış sayılır.',
    'Bilgiler **geminin hareketine kadar** iletilir; değişiklik **hareket idaresince işlemler ikmal edilinceye kadar** yapılabilir. Kodlar **4**: T, TD, X, XD. Listeye ayrıca **konteyner numarası** girer.',
    'İhracat eşyasında çıkış bildirimi işlemleri **geminin TGB\'yi terk etmesinden sonra** tamamlanır; varışta beyana aykırılık → **GY m.239–242**.',
    'Süreler: eksik belge **60 gün**; askı öncesi **30 + 30**; askı **30** (+**60**); liman değişikliği **15 gün önce**; şart değişikliği **30 gün**; ilişik kesme **60 gün**; iptalden sonra **1 yıl** içindeki başvurular reddedilir.',
  ],
};
