// 9. Konu — Gümrük Tarifesi ve Tarife Pozisyonları (kaynak: 9-TAR.POZ.AYIRMA.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '09',
  konu: 'Gümrük Tarifesi ve Tarife Pozisyonları',
  kaynak: '9-TAR.POZ.AYIRMA.docx (GK m.15–16; GY m.32; Gümrük Genel Tebliği (Gümrük Tarife Cetveli İzahnamesi) Seri No: 4 m.4–5; Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) Seri No: 6 m.4–7)',
  bolumler: [
    { baslik: 'Gümrük Tarifesi (GK m.15)', sorular: [
      ['Gümrük vergileri hangi tarihte yürürlükte olan gümrük tarifesine göre hesaplanır?',
        '**Gümrük yükümlülüğünün başladığı tarihte** yürürlükte olan tarifeye göre.', 'GK m.15/1', '',
        'Gümrük vergileri, gümrük yükümlülüğünün başladığı tarihte yürürlükte olan gümrük tarifesine göre hesaplanır.'],
      ['Eşya ticaretine ilişkin özel hükümlerle belirlenmiş diğer önlemler neye göre uygulanır?',
        'Gerektiği takdirde eşyanın **tarife pozisyonuna** göre.', 'GK m.15/2', '',
        'Eşya ticaretine ilişkin özel hükümlerle belirlenmiş diğer önlemler, gerektiği takdirde, söz konusu eşyanın tarife pozisyonuna göre uygulanır.'],
      ['GK m.15/3\'e göre Gümrük Tarifesi neleri kapsar?',
        '(a) **Türk Gümrük Tarife Cetveli**; (b) TGTC\'ye dayanan veya alt açılım ekleyen **diğer cetveller**; (c) **gümrük vergi oranları** ile tarım politikası/işlenmiş tarım ürünleri düzenlemeleriyle alınan **ithalat vergileri**; (d) anlaşmalara dayalı **tercihli tarife**; (e) **tek taraflı** tanınan tercihli tarife; (f) bazı eşyaya **şartlı muafiyet veya indirim**; (g) **diğer tarife uygulamaları**.', 'GK m.15/3', '2021',
        ['Cumhurbaşkanınca kabul edilen Türk Gümrük Tarife Cetvelini', 'Tamamen veya kısmen Türk Gümrük Tarife Cetveline dayanan veya bu cetvele alt açılımlar ekleyen', 'Gümrük vergi oranlarını', 'Tarım politikası veya tarım ürünlerinin işlenmesi sonucu elde edilen bazı ürünlere uygulanan özel düzenlemeler çerçevesinde alınan ithalat vergilerini', 'Türkiye\'nin bazı ülkeler veya ülke grupları ile yaptığı tercihli bir tarife uygulaması gerektiren anlaşmalarda yer alan tercihli tarife uygulamalarını', 'Türkiye tarafından tek taraflı olarak bazı ülkeler, ülke grupları veya toprak parçaları için tanınan tercihli tarife uygulamalarını', 'İthalat vergilerinde, bazı eşyaya şartlı olarak uygulanacak muafiyet veya indirim uygulamalarını', 'Yukarıdakilerin dışında kalan diğer tarife uygulamalarını']],
      ['Türk Gümrük Tarife Cetvelini kim kabul eder?',
        '**Cumhurbaşkanı.**', 'GK m.15/3-a; Tebliğ (İzahname Seri No: 4) m.4/ğ', '',
        ['Cumhurbaşkanınca kabul edilen Türk Gümrük Tarife Cetvelini', 'Cumhurbaşkanınca kabul edilen İstatistik Pozisyonlarına Bölünmüş Türk Gümrük Tarife Cetvelini']],
      ['Beyan sahibi (c) bendindeki tarife yerine hangi bentlerin uygulanmasını isteyebilir?',
        'Eşya koşulları taşıyorsa **(d), (e) ve (f)** bentleri; **sabit oranlı vergilendirmeye ilişkin hükümler** saklıdır.', 'GK m.15/4', '',
        'Sabit oranlı vergilendirmeye ilişkin hükümler saklı kalmak üzere, 3 üncü fıkranın (d), (e) ve (f) bentlerinde belirtilen koşulları taşıyan eşyanın ithalinde, beyan sahibi (c) bendinde belirtilen tarife yerine (d), (e) ve (f) bentleri hükümlerinin uygulanmasını isteyebilir.'],
      ['(d), (e) ve (f) bentlerinin uygulanması talebi gümrük işlemleri tamamlandıktan sonra yapılabilir mi?',
        'Evet; gerekli koşullar yerine getirilmişse **işlemlerin tamamlanmasından** veya **eşyanın tesliminden sonra** da.', 'GK m.15/4', '',
        'Gerekli koşulların yerine getirilmesi halinde, söz konusu talep gümrük işlemlerinin tamamlanmasından veya eşyanın tesliminden sonra da yapılabilir.'],
      ['İthalat hacmiyle sınırlı tarife uygulaması tarife kotalarında ne zaman sona erer?',
        'Tespit edilen **ithalat hacmi sınırına ulaşıldığında**.', 'GK m.15/5-a', '',
        'Tarife kotalarının söz konusu olduğu durumlarda, tespit edilen ithalat hacmi sınırına ulaşıldığında'],
      ['İthalat hacmiyle sınırlı tarife uygulaması tarife tavanlarında nasıl sona erer?',
        '**Cumhurbaşkanı Kararı** ile.', 'GK m.15/5-b', '',
        'Tarife tavanlarının söz konusu olduğu durumlarda ise Cumhurbaşkanı Kararı ile'],
      ['Eşyanın tarife pozisyonunun belirlenmesi deyiminden ne anlaşılır?',
        'Eşyanın girdiği **TGTC** veya (b) bendindeki **diğer cetvelin alt açılımlarının**; ya da tarife dışı önlemler için **Cumhurbaşkanı Kararıyla** oluşturulan diğer cetvelin alt açılımlarının **belirlenmesi**.', 'GK m.15/6', '',
        ['Türk Gümrük Tarife Cetvelinin veya 3 üncü fıkranın (b) bendinde öngörülen diğer cetvelin alt açılımlarının', 'özel alanlara ait eşya ticaretine ilişkin tarife dışı önlemlerin uygulanması amacıyla', 'ile oluşturulan bir diğer cetvelin alt açılımlarının', 'Belirlenmesi anlaşılır']],
      ['Gümrük Tarife Cetveli, izahnamesi ve eşya fihristi kimce hazırlanır; yayımlanan metinlerin niteliği nedir?',
        '**Müsteşarlıkça** hazırlanır, **Resmi Gazetede** yayımlanır; **idari ve kazai uygulamalarda esas** tutulur.', 'GK m.15/7', '',
        ['Gümrük Tarife Cetveli, izahnamesi ve eşya fihristi, Müsteşarlıkça hazırlanır ve Resmi Gazetede yayımlanır.', 'Bu şekilde yayımlanan metinler idari ve kazai uygulamalarda esas tutulur.']],
    ] },
    { baslik: 'Tercihli Tarife Uygulaması (GK m.16)', sorular: [
      ['Mahiyeti ve nihai kullanım şekli gerekçesiyle uygulanan tercihli tarife kimin belirlediği şartlara tabidir?',
        '**Cumhurbaşkanınca** belirlenen şartlara.', 'GK m.16/1', '',
        'bazı eşyanın yararlanabileceği tercihli tarife uygulaması, Cumhurbaşkanınca belirlenen şartlara tabidir'],
      ['Bu tercihli tarife uygulamasında bir izin gerektiğinde hangi hükümler uygulanır?',
        'GK **m.80 ve m.81**.', 'GK m.16/1', '',
        'Bir izin gerektiğinde 80 ve 81 inci madde hükümleri uygulanır.'],
      ['GK m.16\'daki "tercihli tarife uygulaması" ifadesi ne anlama gelir?',
        '**Tarife kotaları kapsamında olsa dahi**, ithalat vergilerinde bir **indirim** veya **şartlı muafiyet** uygulaması.', 'GK m.16/2', '',
        'tarife kotaları kapsamında olsa dahi, ithalat vergilerinde bir indirim veya şartlı muafiyet uygulaması anlamına gelir'],
    ] },
    { baslik: 'Bölüm, Fasıl ve Pozisyonlar (GY m.32; Tebliğ Seri No: 4 m.4; Seri No: 6 m.4)', sorular: [
      ['Türk Gümrük Tarife Cetvelinde "bölüm" nedir?',
        'Birbirine benzeyen **aynı nitelikteki** veya çoğunlukla **aynı hammaddeden** yapılan eşyayı içine alan, **fasılları içeren** gruplar.', 'GY m.32/a; Tebliğ (İzahname Seri No: 4) m.4/c', '',
        ['birbirine benzeyen aynı nitelikteki veya çoğunlukla aynı hammaddeden yapılan eşyayı içine alacak şekilde oluşturulan grupları', 'oluşturulan fasılları içeren grupları']],
      ['Bölüm başlığı ve fasıl başlığı tarifenin yorumunda bağlayıcı mıdır?',
        '**Hayır.** Bölüm başlığı bağlayıcı olmayıp **yol gösterici** niteliktedir; fasıl başlığı da **bağlayıcı olmayan** ibarelerdir.', 'GY m.32/b, e', '',
        ['tarifenin yorumu bakımından bağlayıcı olmayıp, yol gösterici nitelikte olan ibareleri', 'fasılların başında bulunan ve bağlayıcı olmayan ibareleri']],
      ['Bölüm notu ve fasıl notu cetvelde nerede yer alır?',
        'Bölüm notu **bölüm başlıklarından sonra**; fasıl notu **fasıl başlıklarından sonra**.', 'GY m.32/c, f', '',
        ['bölümlerle ilgili olarak bölüm başlıklarından sonra yer alan', 'fasıl başlıklarından sonra gelmek üzere, fasıllarla ilgili yapılan açıklamaların yer aldığı kayıtları']],
      ['Bölüm notu hangi konularda bilgi verir?',
        'Bölümdeki bazı **tabirlerin anlamı**; bir eşyaya yapılan **atfın kapsamı**; hangi eşyanın **sadece o bölümde** yer alabileceği ve bunun **şartları**; hangi eşyanın **bölüme dahil olmadığı**.', 'GY m.32/c; Tebliğ (İzahname Seri No: 4) m.4/ç', '',
        'bölümde geçen bazı tabirlerin ne anlama geldiği, ilgili bölümde bir eşyaya yapılan bir atfın hangi tür eşyayı kapsadığı, hangi eşyanın sadece ilgili bölümde yer alabileceği ve bu eşyanın bu bölümde yer alabilmesi için hangi şartların gerektiği, hangi eşyanın o bölüme dahil olmadığı hakkında bilgi veren açıklamaları'],
      ['Fasıl nedir ve Armonize Sistem Kodunda nasıl ifade edilir?',
        'Bölümlerden **daha alt düzeyde**, birbirine daha çok benzeyen eşyayı içine alan kısım; altı basamaklı AS Kodunun **ilk iki rakamı**.', 'GY m.32/d; Tebliğ (İzahname Seri No: 4) m.4/d', '',
        'Bölümlerden daha alt düzeyde ve bölümlere nazaran daha çok birbirine benzeyen aynı nitelikteki eşyayı içine alan ve altı basamaklı Armonize Sistem Kodunun ilk iki rakamını'],
      ['Tarife pozisyonu kaç rakamla ifade edilir?',
        'Fasıla ilişkin ilk iki rakamdan sonra gelen iki rakamla birlikte **dörtlü** rakamlarla.', 'GY m.32/k; Tebliğ (İzahname Seri No: 4) m.4/g', '2023',
        'fasıla ilişkin ilk iki rakamdan sonra gelen iki rakamla birlikte dörtlü rakamlarla ifade edilen grupları'],
      ['Pozisyon numarası eşyanın neyini gösterir?',
        'Eşyanın **ilgili faslın kaçıncı sırasında** olduğunu.', 'Tebliğ (Açıklama Notları Seri No: 6) m.4/ı', '',
        'eşyanın ilgili faslın kaçıncı sırasında olduğunu gösteren sayı gruplarını'],
      ['Tarife alt pozisyonu kaç rakamla ifade edilir?',
        'Pozisyon numarasını izleyen **iki rakam** ile birlikte **altılı** rakamlarla.', 'GY m.32/ı; Tebliğ (İzahname Seri No: 4) m.4/a', '',
        ['pozisyon numarasını izleyen iki rakam ile birlikte altılı rakamlarla ifade edilen grupları', 'kendinden önce gelen dört rakamla birlikte oluşan altı basamaklı sayı gruplarını']],
      ['Gümrük tarife istatistik pozisyonu kaç rakamdan oluşur?',
        '**Oniki** rakamdan.', 'GY m.32/g', '2025',
        'Gümrük tarife istatistik pozisyonu: Türk Gümrük Tarife Cetvelinde, oniki rakamdan oluşan pozisyonu'],
      ['GY m.32\'deki tanıma göre Türk Gümrük Tarife Cetvelinde hangi kanundaki gümrük vergisi oranları gösterilir?',
        '**474 sayılı** Gümrük Giriş Tarife Cetveli Hakkında Kanun; eşya **cins ve niteliklerine göre** sistematik numaralandırılarak sınıflandırılır.', 'GY m.32/n', '',
        'eşyanın cins ve niteliklerine göre sistematik bir şekilde numaralandırılarak sınıflandırıldığı ve 474 sayılı Gümrük Giriş Tarife Cetveli Hakkında Kanunda yer alan gümrük vergisi oranlarının gösterildiği'],
    ] },
    { baslik: 'Kota ve Tarife Önlemleri Tanımları (GY m.32)', sorular: [
      ['Kota nedir?',
        'Bir **takvim yılı** içinde veya **muayyen bir dönem** itibarıyla yapılmasına izin verilen ithalatın **miktar ve/veya değeri**.', 'GY m.32/h', '2024',
        'Kota: Bir takvim yılı içinde veya muayyen bir dönem itibarıyla yapılmasına izin verilen ithalatın miktar ve/veya değerini'],
      ['Tarife kotası (tarife kontenjanı) nedir?',
        'Bir mal/mal grubunun gümrük vergisi oranlarında **belirli bir miktar veya değer için indirim** yapılması ya da **muafiyet** sağlanması.', 'GY m.32/i', '2022',
        'Tarife kotası veya tarife kontenjanı: Bir mal ya da mal grubunun gümrük vergisi oranlarında belirli bir miktar veya değer için indirim yapılması ya da muafiyet sağlanmasını'],
      ['Tarife tavanı nedir?',
        'Belirli dönemde belli mallarda belirlenen değer/miktar için **ithalatta ve ihracatta** normal GV oranında **indirim**; **aşan miktar** için dönem sonuna kadar indirimin **askıya alınabilmesi**.', 'GY m.32/l', '',
        'Belirli bir dönem içinde, belli malların belirlenen değer ya da miktar için ithalatta ve ihracatta normal gümrük vergisi oranında bir indirime gidilmesi ve bunu aşan miktar için belirlenen dönemin sonuna kadar bu tarife indirimlerinin askıya alınabilmesi uygulamasını'],
      ['Tarife önlemleri nedir?',
        'Dış ticaretin serbest piyasa koşullarında gelişmesine **konulan gümrük vergileri ile engel olunması**.', 'GY m.32/j', '',
        'Tarife önlemleri: Dış ticaretin serbest piyasa koşullarında gelişmesine, konulan gümrük vergileri ile engel olunmasını'],
      ['GY m.32\'ye göre tercihli tarife nedir?',
        'İki ya da daha çok ülkenin ticaret anlaşmasıyla **karşılıklı** olarak ya da bir ülkenin belli ülke/toprak parçaları menşeli eşyaya **tek taraflı** olarak **daha düşük tarife** uygulaması.', 'GY m.32/m', '',
        'İki ya da daha çok ülkenin yaptıkları ticaret anlaşması uyarınca, aralarındaki ticarette karşılıklı olarak ya da bir ülkenin belli ülke ya da toprak parçaları menşeli eşyaya tek taraflı olarak daha düşük tarife uygulamasını'],
      ['"Eşyanın ticaretine ilişkin özel hükümlerle belirlenmiş önlemler" nedir?',
        '**Uluslararası anlaşmalardan** kaynaklanan yükümlülükler ya da **kanun, kararname, yönetmelik** vb. mevzuat çerçevesinde **ilgili kurumlarca** belirlenmiş özel düzenlemeler.', 'GY m.32/ç', '',
        'Bir eşyanın ticaretine ilişkin olarak uluslararası anlaşmalardan kaynaklanan yükümlülükler ya da kanun, kararname, yönetmelik ve benzeri mevzuat çerçevesinde, ilgili kurumlarca belirlenmiş özel düzenlemeleri'],
    ] },
    { baslik: 'İzahname ve Açıklama Notları (Tebliğ Seri No: 4 m.4–5; Seri No: 6 m.4–7)', sorular: [
      ['GYK kısaltması neyi ifade eder?',
        'TGTC\'de yer alan Tarifenin yorumuna ilişkin **Genel Yorum Kuralları**.', 'Tebliğ (İzahname Seri No: 4) m.4/f', '',
        'Genel Yorum Kuralları (GYK): Türk Gümrük Tarife Cetvelinde yer alan Tarifenin yorumuna ilişkin Genel Yorum Kurallarını'],
      ['İzahname hükümlerinin bağlayıcılığı nedir?',
        'AS Nomanklatürünün uluslararası **resmî yorumunda zorunlu ve tamamlayıcı** unsurdur; GK **m.15/7** gereğince **idari ve kazai uygulamalarda esas** tutulur.', 'Tebliğ (İzahname Seri No: 4) m.5', '',
        'Armonize Sistem Nomanklatürünün uluslararası seviyede resmî yorumunun yapılmasında zorunlu ve tamamlayıcı bir unsur olan İzahname hükümleri, 4458 sayılı Kanunun 15 inci maddesinin yedinci fıkrası gereğince idari ve kazai uygulamalarda esas tutulur.'],
      ['Armonize Sistem (AS) İzahnamesi nedir?',
        '**Uyumu sağlanmış (Armonize) Mal Tanımı ve Kodlama Sistemi Hakkında Uluslararası Sözleşme** eki AS Nomanklatürü İzahnamesi.', 'Tebliğ (Açıklama Notları Seri No: 6) m.4/ç', '',
        'Uyumu sağlanmış (Armonize) Mal Tanımı ve Kodlama Sistemi Hakkında Uluslararası Sözleşme eki Armonize Sistem Nomanklatürü İzahnamesini'],
      ['Açıklama Notları Tebliğine göre "Ek Not" nedir?',
        'AS bölüm, fasıl ve alt pozisyon notlarıyla birlikte TGTC\'nin hazırlanmasında esas alınan, pozisyon ve alt pozisyonlara açıklama getiren **Avrupa Birliği Kombine Nomanklatürü Notları**.', 'Tebliğ (Açıklama Notları Seri No: 6) m.4/f', '',
        'Armonize Sistem Bölüm, Fasıl ve Alt Pozisyon notları ile birlikte, Türk Gümrük Tarife Cetvelinin hazırlanmasında esas alınan ve pozisyon ve alt pozisyonlara ilişkin açıklamalar getiren Avrupa Birliği Kombine Nomanklatürü Notlarını'],
      ['Açıklama Notları Tebliği (Seri No: 6) hangi tebliği yürürlükten kaldırmıştır?',
        '22/3/2016 tarihli ve 29661 mükerrer sayılı Resmî Gazete\'de yayımlanan Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) **(Seri No: 3)**.', 'Tebliğ (Açıklama Notları Seri No: 6) m.5/1', '',
        '22/3/2016 tarihli ve 29661 mükerrer sayılı Resmî Gazete\'de yayımlanan Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 3) yürürlükten kaldırılmıştır.'],
      ['Açıklama Notlarına uymayan Bağlayıcı Tarife Bilgilerinin durumu nedir?',
        'GK **m.9/5** uyarınca Tebliğin **yürürlüğe girdiği tarihten itibaren geçerliliğini yitirir**.', 'Tebliğ (Açıklama Notları Seri No: 6) m.5/2', '',
        'Bu Tebliğ eki Gümrük Tarife Cetveli Açıklama Notlarına uymayan Bağlayıcı Tarife Bilgileri 4458 sayılı Gümrük Kanununun 9 uncu maddesinin beşinci fıkrası uyarınca bu Tebliğin yürürlüğe girdiği tarihten itibaren geçerliliğini yitirir.'],
      ['Açıklama Notları Tebliği ne zaman yürürlüğe girer ve kim yürütür?',
        '**Yayımı tarihinde** yürürlüğe girer; **Ticaret Bakanı** yürütür.', 'Tebliğ (Açıklama Notları Seri No: 6) m.6–7', '',
        ['Bu Tebliğ yayımı tarihinde yürürlüğe girer.', 'Bu Tebliğ hükümlerini Ticaret Bakanı yürütür.']],
    ] },
  ],
  tuzaklar: [
    'Basamaklar: **fasıl = AS kodunun ilk 2 rakamı**; **tarife pozisyonu = 4 rakam**; **alt pozisyon = 6 rakam**; **gümrük tarife istatistik pozisyonu = 12 rakam**.',
    '**Kota** = izin verilen ithalatın **miktar ve/veya değeri**; **tarife kotası (kontenjanı)** = belirli miktar/değer için **vergi indirimi veya muafiyet**; **tarife tavanı** = aşan miktar için indirimin dönem sonuna kadar **askıya alınabilmesi** (ithalatta ve ihracatta).',
    'Hacimle sınırlı uygulamanın sonu: **tarife kotası** → **ithalat hacmi sınırına ulaşıldığında**; **tarife tavanı** → **Cumhurbaşkanı Kararı ile**.',
    '**Bölüm başlığı** ve **fasıl başlığı** bağlayıcı **değildir** (bölüm başlığı yol göstericidir); **izahname** hükümleri ise **idari ve kazai uygulamalarda esas** tutulur.',
    'Vergi, **gümrük yükümlülüğünün başladığı tarihteki** tarifeye göre hesaplanır; (d), (e), (f) uygulanması talebi **işlemlerin tamamlanmasından veya teslimden sonra da** yapılabilir.',
    'TGTC\'yi kabul eden: GK m.15 ve Tebliğ (Seri No: 4)\'te **Cumhurbaşkanı**; GY m.32/n tanımında "**Bakanlar Kurulunca** kabul edilen" ibaresi geçer. Cetvel, izahname ve eşya fihristini **Müsteşarlık** hazırlar, **Resmi Gazetede** yayımlanır.',
  ],
};
