// 20. Konu — Transit Rejimi (kaynak: 20-TRANSİT REJİMİ.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '20',
  konu: 'Transit Rejimi',
  kaynak: '20-TRANSİT REJİMİ.docx (GK m.84–92; GY m.212–244)',
  bolumler: [
    { baslik: 'Kapsam ve Sona Erme (GK m.84)', sorular: [
      ['Transit rejimi hangi eşyanın taşınmasına uygulanır?',
        'İthalat vergileri ve TPÖ\'ye tabi tutulmayan **serbest dolaşıma girmemiş** eşya ile **ihracatla ilgili gümrük işlemleri tamamlanmış** eşyanın, **gümrük gözetimi altında** TGB içindeki bir noktadan diğerine taşınmasına.', 'GK m.84/1', '2021',
        ['İthalat vergileri ve ticaret politikası önlemlerine tabi tutulmayan serbest dolaşıma girmemiş,', 'İhracatla ilgili gümrük işlemleri tamamlanmış,', 'eşyanın, gümrük gözetimi altında Türkiye Gümrük Bölgesi içindeki bir noktadan diğerine taşınmasına uygulanır.']],
      ['Gümrük idareleri transit eşyanın TGB içinde hangi güzergâhlarda taşınmasına izin verir?',
        'Yabancı ülke → yabancı ülke; yabancı ülke → **Türkiye**; **Türkiye** → yabancı ülke; **iç gümrük idaresi → iç gümrük idaresi**.', 'GK m.84/2', '',
        'Yabancı bir ülkeden yabancı bir ülkeye, b) Yabancı bir ülkeden Türkiye\'ye, c) Türkiye\'den yabancı bir ülkeye, d) Bir iç gümrük idaresinden diğer bir iç gümrük idaresine,'],
      ['Kanuna göre transit rejimine tabi eşyanın taşınması hangi belge veya yollarla yapılır?',
        '**Transit rejimi beyanı**, **TIR karnesi**, transit belgesi olarak **ATA karnesi**, NATO **form 302**, **posta** yoluyla (koliler dahil); yönetmelikte belirlenen hallerde demiryolunda **CIM**, büyük konteynerde **TR Transfer Notu**, hava ve denizyolunda **manifesto**.', 'GK m.84/3', '2024',
        ['Transit rejimi beyanı kapsamında,', 'TIR karnesi kapsamında,', 'Transit belgesi olarak kullanılan ATA karnesi kapsamında,', 'Posta kolileri dâhil olmak üzere posta yoluyla,', 'demiryolu ile taşımada CIM Taşıma Belgesi, büyük konteynerler ile taşımada TR Transfer Notu, havayolu ve denizyolu ile taşımada eşya manifestosu kapsamında,']],
      ['Transit rejimi ne zaman sona erer?',
        'Eşya ve gerekli belgeler, rejim hükümlerine uygun olarak **varış gümrük idaresine sunulduğunda**.', 'GK m.84/4-a', '2024, 2025',
        'Transit rejimine tabi tutulan eşya ve gerekli belgeler, rejimi düzenleyen hükümlere uygun olarak varış gümrük idaresine sunulduğunda, transit rejimi sona erer.'],
      ['Transit rejimi ne zaman ibra edilir?',
        '**Hareket** ve **varış** gümrük idaresindeki bilgi ve belgelerin **karşılaştırılması** sonucu rejimin usulüne uygun sonlandırıldığı belirlendiğinde.', 'GK m.84/4-b', '',
        'Hareket gümrük idaresindeki bilgi ve belgeler ile varış gümrük idaresindeki bilgi ve belgelerin karşılaştırılması sonucunda, transit rejiminin usulüne uygun olarak sonlandırıldığının belirlenmesi halinde rejim ibra edilir.'],
    ] },
    { baslik: 'Teminat (GK m.85; GY m.222)', sorular: [
      ['Transitte teminat zorunlu mudur; Kanuna göre hangi taşımalarda teminat aranmaz?',
        'Teminat **zorunludur**. **Havayolu, boru hattı, demiryolu ve denizyolu** taşımalarında **yönetmelikle belirlenen haller dışında** aranmaz (**karayolu** bu istisnalar arasında **yoktur**).', 'GK m.85/1', '2021, 2022, 2024',
        ['Transit eşyası için tahakkuk edebilecek gümrük vergilerinin ödenmesini sağlamak üzere teminat verilmesi zorunludur.', 'Havayoluyla, b) Boru hattıyla, c) Demiryoluyla, d) Denizyoluyla, yapılan taşımalar için, yönetmelikle belirlenen haller dışında teminat aranmaz.']],
      ['Yönetmeliğe göre hangi taşımalarda teminat aranmaz?',
        '**Havayolu**, **boru hattı**, **denizyolu** ve **m.235 çerçevesinde basitleştirilmiş usulde demiryolu** taşımalarında.', 'GY m.222/1', '2022',
        'Havayolu, b) Boru hattı, c) Denizyolu, ç) 235 inci madde çerçevesinde basitleştirilmiş usulde demiryolu, ile yapılan taşımalarda teminat aranmaz.'],
      ['Transit rejiminde teminat hangi şekillerde verilebilir?',
        'Tek bir işlem için **bireysel teminat**; **Müsteşarlık izniyle** birden fazla işlem için **kapsamlı teminat**.', 'GK m.85/2', '',
        ['Tek bir transit işlemi için bireysel teminat,', 'Müsteşarlık tarafından izin verilmesi halinde, birden fazla transit işlemi için kapsamlı teminat,']],
      ['Kapsamlı teminat izni kimlere verilir?',
        '**TGB\'de yerleşik**, transit rejimini **düzenli kullanan** (veya yükümlülüklerini yerine getirebileceği belirlenen) ve gümrük/vergi mevzuatını **ihlal etmemiş** kişilere.', 'GK m.85/3', '',
        ['Türkiye Gümrük Bölgesinde yerleşik olan,', 'Transit rejimini düzenli olarak kullanan veya gümrük idaresince bu rejime ilişkin yükümlülüklerini yerine getirebileceği belirlenen,', 'Gümrük veya vergi mevzuatını yönetmelikte belirlenen surette ihlal etmemiş olan,']],
      ['İndirilmiş tutarda kapsamlı teminat veya teminattan vazgeçme izni için neler aranır?',
        '**Güvenilirlik standartlarına** sahip olmak; ayrıca belirli sürede rejimin **doğru kullanımı**, gümrük idareleriyle **işbirliği** ve taahhütleri karşılayacak **mali gücün kanıtlanması**.', 'GK m.85/4', '',
        ['Güvenilirlik standartlarına sahip oldukları gümrük idaresince belirlenen kişilere indirilmiş tutarda kapsamlı teminat veya teminattan vazgeçme izni verilebilir.', 'Belirli bir sürede transit rejiminin doğru kullanımı,', 'Gümrük idareleri ile işbirliği,', 'Anılan kişilerin taahhütlerini yerine getirebilecek mali güce sahip olduklarını kanıtlaması,']],
      ['Teminattan vazgeçme izni hangi eşyanın transitinde uygulanmaz?',
        'Müsteşarlıkça **yüksek risk** içerdiği belirlenen eşyanın.', 'GK m.85/5', '',
        'Dördüncü fıkraya göre verilen teminattan vazgeçme izni, Müsteşarlıkça yüksek risk içerdiği belirlenen eşyanın transit işlemlerinde uygulanmaz.'],
      ['Müsteşarlık hangi teminat uygulamalarını geçici olarak kaldırabilir?',
        'Özel durumlarda istisnai önlem olarak **indirilmiş tutarda kapsamlı teminatı**; **büyük ölçekli kaçakçılığa** konu olabilecek eşya için **kapsamlı teminatı**.', 'GK m.85/6', '',
        ['Özel durumlarda istisnai önlem olarak dördüncü fıkra hükümleri doğrultusundaki indirilmiş tutarda kapsamlı teminat uygulamasını,', 'Büyük ölçekli kaçakçılığa konu olabilecek eşya için kapsamlı teminat uygulamasını,', 'geçici olarak kaldırmaya yetkilidir.']],
      ['Teminat şartı aranmaksızın memur refakati uygulanabilir mi?',
        'Evet, **Bakanlıkça belirlenecek istisnai hallerde**.', 'GY m.222/3', '',
        'Bakanlıkça belirlenecek istisnai hallerde transit rejimine tabi eşya için teminat şartına bağlı olmaksızın memur refakati uygulanabilir.'],
    ] },
    { baslik: 'Sorumluluk ve Yükümlülükler (GK m.86; GY m.221)', sorular: [
      ['Asıl sorumlunun transit rejimindeki temel yükümlülüğü nedir?',
        'Eşyayı **öngörülen süre içinde**, ayniyet önlemlerine uyarak **varış gümrük idaresine sağlam ve noksansız sunmak** ve rejim hükümlerine uymak.', 'GK m.86/1', '',
        'Asıl sorumlu, eşyayı öngörülen süre içerisinde ve gümrük idareleri tarafından eşyanın ayniyetinin tespiti amacıyla alınan önlemlere uymak suretiyle, varış gümrük idaresine sağlam ve noksansız olarak sunmak ve transit rejimine ilişkin hükümlere uymakla yükümlüdür.'],
      ['Asıl sorumlu dışında eşyayı varış idaresine sağlam ve noksansız sunmakla kim yükümlüdür?',
        'Eşyanın transit rejimine göre taşındığını **bilerek kabul eden taşıyıcı veya alıcı**.', 'GK m.86/2', '',
        'transit rejimine göre taşındığını bilerek eşyayı kabul eden taşıyıcı veya alıcı da'],
      ['GK m.183–184 kapsamında yükümlülük doğduğunda gümrük idaresine karşı mali olarak kim sorumludur?',
        '**Asıl sorumlu.** 5607 sayılı Kanun uyarınca işlem yapılan hallerde asıl sorumlunun fiilin işlenmesinde **dahlinin olup olmadığı** dikkate alınır.', 'GK m.86/3', '',
        ['183 ve 184 üncü maddeler kapsamında bir gümrük yükümlülüğü doğduğunda, asıl sorumlu, transit rejimine tabi tutulan eşya ile ilgili olarak gümrük idaresine karşı mali olarak sorumludur.', 'asıl sorumlunun sorumluluğunun belirlenmesinde fiilin işlenmesinde dahlinin olup olmadığı hususu dikkate alınır']],
      ['Yönetmeliğe göre rejim hak sahibinin yükümlülükleri nelerdir?',
        'Gerekli **teminatı vermek** (teminat aranmayan/vazgeçilen haller saklı) ve yetkili makamlarca talep edildiğinde belirlenen sürede **bilgi ve belgeleri sunmak**, **gerekli yardımı sağlamak**.', 'GY m.221/1', '',
        ['transit rejimine konu eşyaya ilişkin doğabilecek gümrük vergilerinin ödenmesini sağlamak üzere gerekli teminatı vermekle,', 'Kontrolden sorumlu yetkili makamlarca talep edildiğinde ve belirlenen süre içinde gerekli tüm bilgi ve belgeleri sunmakla ve gerekli tüm yardımı sağlamakla,']],
    ] },
    { baslik: 'Muayene, Önlemler ve Beklenmeyen Haller (GK m.87–92)', sorular: [
      ['Transit eşyası yolda antrepoda bekletilebilir veya başka taşıta aktarılabilir mi?',
        'Evet; gümrük gözetimindeki **antrepolarda** veya izin verilen yerlerde **bir süre kalabilir** ya da **bir taşıttan diğerine aktarılabilir**.', 'GK m.87/2', '',
        'Transit rejimine konu olan eşyanın, gümrük gözetimi altındaki antrepolarda veya gümrük idarelerince eşya konulmasına izin verilen yerlerde bir süre kalması veya bir taşıttan diğer bir taşıta aktarılması mümkündür.'],
      ['Transit eşyası varış gümrük idaresine kadar muayene edilir mi?',
        '**Şüphe veya ihbar** hariç **muayene edilmeksizin**; gerektiğinde **mühür altına alınarak** veya **memur eşliğinde** sevk edilir.', 'GK m.88/1', '',
        'Transit rejimine tabi eşya, şüphe veya ihbar durumları hariç olmak üzere, varış gümrük idaresine kadar muayene edilmeksizin ve gerektiğinde mühür altına alınarak veya memur eşliğinde sevk edilir.'],
      ['Antrepolardan transit rejimiyle taşınan eşya muayene edilir mi; muayenede kimler bulunabilir?',
        '**Gerek görülmesi halinde** muayene edilir (GK m.61–70); muayenede **asıl sorumlu, temsilcisi** veya taşımadan sorumlu kişiler bulunabilir.', 'GK m.88/2', '',
        ['Antrepolardan veya gümrük idarelerince konulmasına izin verilen diğer yerlerden transit rejimi kapsamında taşınan eşya, gerek görülmesi halinde muayene edilir.', 'asıl sorumlu, temsilcisi veya eşyanın taşınmasından sorumlu kişiler de bulunabilir']],
      ['Türkiye karasularından geçen şüpheli transit eşya yüklü gemilere hangi önlemler alınabilir; ne zaman kaldırılır?',
        'Ambar kapakları **mühür altına** alınabilir, **memur eşlik** ettirilebilir veya gemi **dış gözetim** altında tutulabilir; önlemler gemilerin **karasularından çıkışı** üzerine kaldırılır.', 'GK m.90', '',
        ['gümrük idarelerince mühür altına alınabilir. Bu gemilere memur eşlik ettirilebilir veya gemiler seyir halinde iken dış gözetim altında tutulabilir.', 'Yukarıda belirtilen önlemler, gemilerin Türkiye karasularından çıkışı üzerine kaldırılır.']],
      ['Karayolu transit taşıtlarının süreleri, yolları, kontrol noktaları ve konaklama yerlerini düzenlemeye kim yetkilidir?',
        '**Müsteşarlık.**', 'GK m.91', '',
        'transit süreleri, izleyecekleri yollar, kontrol noktaları ve konaklama yerleri ile ilgili olarak düzenlemeler yapmaya Müsteşarlık yetkilidir'],
      ['Transit taşıtı beklenmeyen hal veya mücbir sebeple yoluna devam edemezse ne yapılır?',
        'Durum **gecikmeksizin en yakın gümrük idaresine** bildirilir; başka taşıta aktarma **gümrük gözetiminde** yapılır ve **tutanakla** belgelendirilir.', 'GK m.92/1', '',
        ['bu husus gecikmeksizin en yakın gümrük idaresine bildirilir', 'gümrük idarelerinin gözetimi altında yapılarak, bu durum bir tutanakla belgelendirilir']],
    ] },
    { baslik: 'Kapsam ve Tanımlar (GY m.212)', sorular: [
      ['Yönetmeliğe göre transit rejimi hangi transit işlemlerini kapsar?',
        '**Ulusal transit**, **TIR Sözleşmesi**, **Ortak Transit Rejimine İlişkin Sözleşme**, **Geçici İthalat Sözleşmesi** ve **NATO Kuvvetlerin Statüsü Sözleşmesi** kapsamındaki işlemler.', 'GY m.212/1', '',
        ['Transit rejimi; ulusal transit rejimi, 14/11/1975 tarihli TIR Karneleri Himayesinde Uluslararası Eşya Taşınmasına Dair Gümrük Sözleşmesi (TIR Sözleşmesi)', '20/5/1987 tarihli Ortak Transit Rejimine İlişkin Sözleşme, 26/6/1990 tarihli Geçici İthalat Sözleşmesi ve 19/6/1951 tarihli Kuvvetlerin Statüsü Hakkında Kuzey Atlantik Anlaşmasına Taraf Devletler Arasındaki Sözleşme kapsamındaki transit işlemlerini kapsar']],
      ['Hareket gümrük idaresi ve varış gümrük idaresi nedir?',
        'Hareket: transit beyanının **kabul edildiği** idare. Varış: rejimin **sonlandırılması için** eşyanın **sunulması gereken** idare.', 'GY m.212/2-c, j', '2025',
        ['Hareket gümrük idaresi: Eşyanın transit rejimine tabi tutulmasına ilişkin beyanın kabul edildiği gümrük idaresini,', 'Varış gümrük idaresi: Transit rejimine tabi tutulan eşyanın, rejimin sonlandırılması için sunulması gereken gümrük idaresini,']],
      ['Ulusal transit rejimi ile ortak transit rejimi nasıl ayrılır?',
        'Ulusal: **TGB içinde başlayıp biten** transit. Ortak: Sözleşme kapsamında bir Akit Tarafın idaresinden **en az bir sınır geçerek** aynı veya başka bir Akit Tarafın idaresine taşıma.', 'GY m.212/2-e, i', '',
        ['Ulusal transit rejimi: Türkiye Gümrük Bölgesi içerisinde başlayıp biten transit rejimini,', 'Akit Taraflardan birinin idaresinden en az bir sınır geçerek aynı Akit Tarafın başka bir idaresine veya başka bir Akit Tarafın idaresine taşınmasında uygulanan gümrük rejimini']],
      ['Rejim hak sahibi (asıl sorumlu) kimdir?',
        'Transit beyanında **bulunan** veya **hesabına** beyanda bulunulan ve gümrük idaresine karşı **mali olarak sorumlu** olan kişi.', 'GY m.212/2-f', '',
        'Transit rejimi beyanında bulunan veya hesabına transit rejimi beyanında bulunulan ve transit rejimi kapsamında gümrük idaresine karşı mali olarak sorumlu olan kişiyi'],
      ['Transit rejiminde kefil kimdir?',
        'Teminat tutarına kadar doğabilecek vergi ve yükleri rejim hak sahibiyle birlikte **müştereken ve müteselsilen** ödemeyi **yazılı olarak** üstlenen gerçek veya tüzel **üçüncü kişi**.', 'GY m.212/2-d', '',
        'Kefil: Teminat tutarına kadar doğabilecek gümrük vergileri ve diğer yükleri rejim hak sahibi ile birlikte müştereken ve müteselsilen ödemeyi yazılı olarak üstlenen gerçek veya tüzel üçüncü kişiyi,'],
      ['Ortak transit rejiminde "transit idaresi" nedir?',
        'Bir Akit Tarafa **giriş noktasındaki** idare veya üçüncü ülke sınırından geçilen işlemlerde sevkiyatın Akit Taraftan **çıkış noktasındaki** idare.', 'GY m.212/2-h', '',
        ['Bir Akit Tarafa giriş noktasındaki gümrük idaresini veya,', 'bu Akit Taraftan çıkış noktasındaki gümrük idaresini']],
      ['Ulusal transitte özel veya farklı hüküm bulunmayan hallerde hangi hükümler uygulanır?',
        '**Ortak transit rejimine** ilişkin hükümler.', 'GY m.212/3', '',
        'ortak transit rejimine ilişkin hükümler ulusal transit rejimi için de geçerlidir'],
    ] },
    { baslik: 'Transit Beyanı ve Özel Transit Usulleri (GY m.213–220)', sorular: [
      ['Yönetmeliğe göre transit beyanı olarak hangi belgeler kullanılır?',
        '**Transit refakat belgesi**, **TIR Karnesi**, **ATA Karnesi**, **Form 302**, basitleştirilmiş usulde **CIM taşıma belgesi** (demiryolu) ve **manifesto** (deniz/hava), ulusal transitte **sözlü beyan formu** (Ek-22). (CMR veya fatura sayılmaz.)', 'GY m.213/1', '2024, 2025',
        ['Ortak ve ulusal transit rejimi hükümleri çerçevesinde transit refakat belgesi,', 'TIR Sözleşmesi kapsamında kullanılan bir TIR Karnesi,', 'Geçici İthalat Sözleşmesi kapsamında kullanılan bir ATA Karnesi,', 'Kuvvetlerin Statüsü Hakkında Kuzey Atlantik Anlaşmasına Taraf Devletler Arasındaki Sözleşme ile öngörülen Form 302,', 'Demiryolu ile taşımalara ilişkin basitleştirilmiş usulde CIM taşıma belgesi,', 'Denizyolu ve havayolu ile taşımalara ilişkin basitleştirilmiş usulde manifesto,', 'Ulusal transit rejiminde, 220 nci maddenin birinci fıkrası çerçevesinde Ek-22\'de yer alan sözlü beyan formu,']],
      ['Transit beyanı hangi dilde, kim tarafından ve nasıl yapılır?',
        '**Türkçe**, **rejim hak sahibi** tarafından, kağıt usul hariç **sistem üzerinden**; doğrudan temsilci veya rejim hak sahibinin **dolaylı temsilcisi** de yapabilir.', 'GY m.213/2', '',
        ['Transit beyanı Türkçe olarak, rejim hak sahibi tarafından ve kağıt usulde işlem yapıldığı durumlar hariç sistem üzerinden yapılır.', 'rejim hak sahibinin dolaylı temsilcisi tarafından da yapılabilir']],
      ['Sistem (NCTS) üzerinden yapılan transit beyanı hareket idaresine süresinde sunulmazsa ne olur?',
        'Beyan tarihinden itibaren **otuz gün** içinde kabul için sunulmayan beyan hareket idaresince **reddedilir**; bu retlerde GK **m.241 uygulanmaz**.', 'GY m.212/2-g; m.213/3', '2025',
        ['Yeni Bilgisayarlı Transit Sistemini (NCTS)', 'Sistem üzerinden yapılan ve beyanın yapıldığı tarihten itibaren otuz gün içerisinde kabul işlemi yapılmak üzere hareket gümrük idaresine sunulmayan transit beyanları hareket gümrük idaresince reddedilir.', 'Kanunun 241 inci maddesi uyarınca işlem yapılmaz']],
      ['Transit refakat belgesi ne zamandan itibaren kullanılır; kalem listesinin niteliği nedir?',
        'Eşyanın hareket idaresince **serbest bırakıldığı andan itibaren** eşyaya ve taşımaya eşlik eder; eklenen **kalem listesi** belgenin **ayrılmaz parçasıdır** (birden fazla alıcı/gönderici bilgisi kalem listesine yazılır).', 'GY m.214/1', '',
        ['eşyanın hareket gümrük idaresince serbest bırakıldığı andan itibaren eşyaya ve taşımaya eşlik etmek üzere, transit refakat belgesi kullanılır', 'kalem listesi transit refakat belgesinin ayrılmaz bir parçasını oluşturur', 'alıcı ya da göndericilere ilişkin bilgiler kalem listesine kaydedilir']],
      ['NATO Kuvvetlerin Statüsü Sözleşmesi kapsamındaki eşyanın transiti hangi belgeyle yapılır; ihtilafları kim sonuçlandırır?',
        '**Form 302**; ihtilaflar **Bakanlıkça (Gümrükler Genel Müdürlüğü)** sonuçlandırılır.', 'GY m.218', '2022',
        ['bu sözleşmede yer alan Form 302 ibraz edilmesi halinde, bu belge kapsamında yapılır', 'Form 302 kapsamında yapılacak transit işlemlerinde doğabilecek ihtilaflar Bakanlıkça (Gümrükler Genel Müdürlüğü) sonuçlandırılır.']],
      ['Hangi eşya ulusal transitte sözlü beyanla işlem görebilir?',
        '**Yolcuların beraberindeki**, kişisel veya hediyelik eşya muafiyeti **dışında kalan** eşya (talep halinde); eşya **ticari miktar ve mahiyetteyse** uygulanmaz.', 'GY m.220/1', '',
        ['Yolcuların beraberinde bulunmak kaydıyla; yurt dışından getirilen veya geçici depolama yeri veya antrepolardan çıkarılan ve kişisel veya hediyelik eşya muafiyeti dışında kalan eşyanın ulusal transit rejimine tabi tutulmasında', 'Söz konusu eşyanın ticari miktar ve mahiyette olması halinde bu madde hükmü uygulanmaz.']],
    ] },
    { baslik: 'Ayniyet ve Özel Eşyanın Transiti (GY m.223–226)', sorular: [
      ['Transitte eşyanın ayniyeti genel kural olarak nasıl sağlanır; mühürsüz sevk mümkün müdür?',
        'Genel kural **mühürleme**. Eşyanın tanımı kolayca tanınmasına yeterliyse ve beyan **miktar, cins, seri numarası** gibi belirleyici özellikleri içeriyorsa hareket idaresi **mühürlenmeksizin sevke** karar verebilir.', 'GY m.223/1', '',
        ['Ulusal ve ortak transit rejimi altında taşınan eşyanın ayniyeti genel kural olarak mühürleme ile sağlanır.', 'transit beyanının eşyanın miktarı ile cinsi ve eşyanın seri numarası gibi belirleyici özelliklerini içermesi koşuluyla, hareket idaresince eşyanın mühürlenmeksizin sevkine karar verilebilir']],
      ['Denizyolu ve havayolu taşımalarında mühürleme yapılır mı?',
        'Gümrük idaresince **gerekli görülen haller dışında yapılmaz**.', 'GY m.223/2', '',
        'Denizyolu ve havayolu ile yapılan taşımalarda, gümrük idaresince gerekli görülen hallerin dışında mühürleme yapılmaz.'],
      ['İthali yasaklanan eşyanın transitine izin vermeye kim yetkilidir?',
        '**Gümrük ve ticaret bölge müdürlükleri.**', 'GY m.225/1', '',
        'kanun veya genel idari düzenleyici işlemlerle ithali yasaklanan eşyanın transitine izin vermeye gümrük ve ticaret bölge müdürlükleri yetkilidir'],
      ['Hayvan, hayvansal madde, bitki ve parçalarının sınırdaki sağlık muayenesini kim yapar?',
        '**İlgili kurumun personeli**; bu muayeneler yapılmadan gümrük idaresi serbest bırakma veya sevke **izin vermez**.', 'GY m.226/1', '',
        ['gerekli sağlık muayeneleri, ilgili kurumun personeli tarafından yapılır', 'Bu muayeneler yapılmadan gümrük idaresi eşyanın serbest bırakılmasına veya sevkine izin vermez.']],
    ] },
    { baslik: 'Denizyolu ile Transit (GY m.227)', sorular: [
      ['Bir Türk limanından başka bir Türk limanına transit eşyayı hangi gemiler taşıyabilir?',
        '**Yalnız Türk bandıralı** gemiler.', 'GY m.227/1', '',
        'Bir Türk limanından başka bir Türk limanına transit olunacak eşyayı, yalnız Türk bandıralı gemiler nakledebilir.'],
      ['Yabancı limanlara transit isteklerinin kabulü için ne gerekir?',
        '**Özet beyan** veya yerine geçen belgelerde eşyanın gideceği yerin TGB dışında **yabancı bir liman** olarak gösterilmesi.', 'GY m.227/2', '',
        'özet beyan veya özet beyan yerine geçen belgelerde eşyanın gideceği yerin Türkiye Gümrük Bölgesi dışında yabancı bir liman olarak gösterilmesi gerekir'],
      ['Türk limanına gelen serbest dolaşımda olmayan eşya gemiden indirilmeden aynı gemiyle başka Türk limanına taşınırsa transit beyannamesi düzenlenir mi?',
        '**Hayır**, transit beyannamesi **düzenlenmez**.', 'GY m.227/7', '',
        'Bir Türk limanına denizyolu ile gelen serbest dolaşımda olmayan eşyanın gemiden indirilmeksizin aynı gemi ile bir başka Türk limanına taşınması durumunda transit beyannamesi düzenlenmez.'],
      ['Türk bandıralı gemi kazan, makine veya tekne arızasıyla yoluna devam edemezse yük ne olur?',
        'Kurtarma amacıyla **yabancı bir gemiye aktarılabilir**.', 'GY m.227/5', '',
        'Türk bandıralı geminin, kazan, makine veya teknesinde ortaya çıkan bir arıza sebebiyle yoluna devam edememesi halinde, kurtarma amacıyla, yükü, yabancı bir gemiye aktarılabilir.'],
    ] },
    { baslik: 'Telef veya Kayıp (GK m.92/2; GY m.228)', sorular: [
      ['Transit eşyasının telef veya kaybında gümrük vergileri aranır mı?',
        'Telef veya kaybın **mücbir sebep veya beklenmeyen haller** nedeniyle olduğu **kanıtlanırsa aranmaz**.', 'GK m.92/2; GY m.228/1', '',
        'Türkiye Gümrük Bölgesi içinde transit halindeki eşyanın beklenmeyen haller veya mücbir sebeplerle telef veya kaybının kanıtlanması halinde, gümrük vergileri aranmaz.'],
      ['Telef veya kayıp hangi belgelerle kanıtlanır; ulusal transitte belgeler nereye sunulur?',
        'Suçüstü hırsızlıkta **Cumhuriyet Savcılığı** belgesi; herkesçe bilinen olaylarda **o yerin en büyük mülki idare amiri** belgesi; trafik kazasında kaza raporu ve en yakın gümrük idaresinin tespiti üzerine **gümrük idare amirinin kararı**. Ulusal transitte belgeler **hareket gümrük idaresine** sunulur.', 'GY m.228', '',
        ['Suçüstü şeklindeki hırsızlıklar, hazırlık tahkikatı üzerine Cumhuriyet Savcılığınca verilen belge ile,', 'o yerin en büyük mülki idare amiri tarafından verilecek belge ile,', 'Trafik kazaları, trafik kaza raporuna göre ve en yakın gümrük idaresi tarafından yapılan tespit sonucunda gümrük idare amirinin vereceği karar ile,', 'Birinci fıkrada sayılan belgeler, ulusal transit işlemlerinde hareket gümrük idaresine sunulur.']],
    ] },
    { baslik: 'Basitleştirmeler (GY m.229–238/A)', sorular: [
      ['Bakanlık transit rejiminde hangi basitleştirmelere izin verebilir?',
        '**Kapsamlı teminat veya teminattan vazgeçme**; **taşıma şekillerine özgü** basitleştirmeler (demiryolu, havayolu, denizyolu, boru hattı); **izinli gönderici** yetkisi.', 'GY m.229/1', '',
        ['Kapsamlı teminat veya teminattan vazgeçme,', 'Belirli taşıma şekillerine özgü basitleştirmeler:', 'İzinli gönderici yetkisi,']],
      ['Basitleştirme izni için usulsüzlük ve vergi cezalarına ilişkin koşullar nelerdir?',
        'Son bir yılda işlem gören beyanname sayısının **%2\'sini** aşan sayıda **vergi kaybına** yol açan ihlal cezası ve **%5\'ini** aşan sayıda **usulsüzlük cezası** uygulanmamış olması; **ödenmemiş** vergi, ceza ve gecikme faizi bulunmaması.', 'GY m.230/1-b', '',
        ['% 2\'sini aşan sayıda vergi kaybına neden olan gümrük mevzuatı ihlali nedeniyle ceza uygulanmamış olması', '% 5\'ini aşan sayıda gümrük mevzuatının ihlali nedeniyle usulsüzlük cezası uygulanmamış olması', 'Gümrük ve vergi mevzuatları uyarınca ödenmemiş herhangi bir vergi, ceza ve gecikme faizi bulunmaması.']],
      ['Basitleştirme izni için yerleşiklik ve transit hacmine ilişkin koşullar nelerdir?',
        '**TGB\'de yerleşik** olmak; son bir yılda en az **500 transit beyannamesi** (TIR Karnesi dahil) kapsamı eşyayı transit etmek veya yükümlülükleri yerine getirebileceğine dair bilgi-belge sunmak.', 'GY m.230/1-a, ç', '',
        ['Türkiye Gümrük Bölgesinde yerleşik olmak,', 'en az 500 transit beyannamesi (TIR Karnesi dâhil) kapsamı eşyayı transit etmesi']],
      ['Hangi kuruluşların basitleştirme başvurularında genel koşullar aranmaz?',
        'Genel yönetim kapsamındaki **kamu idareleri**, **iktisadi devlet teşekkülleri**, **kamu iktisadi kuruluşları** ve sermayesinin tamamı bunlara ait **bağlı müesseseler**.', 'GY m.230/2', '',
        'Genel yönetim kapsamındaki kamu idareleri, iktisadi devlet teşekkülleri ve kamu iktisadi kuruluşları ile sermayesinin tamamı bir iktisadi devlet teşekkülüne veya kamu iktisadi kuruluşuna ait bağlı müesseselerin başvurularında bu maddede belirtilen şartlar aranmaz.'],
      ['Basitleştirme izni vermeye kim yetkilidir?',
        '**Bakanlık (Gümrükler Genel Müdürlüğü)**; gümrük ve dış ticaret bölge müdürlükleri **kapsamlı teminat** izni için yetkilendirilebilir.', 'GY m.231/1', '',
        ['Basitleştirme izni vermeye Bakanlık (Gümrükler Genel Müdürlüğü) yetkilidir.', 'Gümrük ve dış ticaret bölge müdürlükleri kapsamlı teminat izni vermek için yetkilendirilebilir.']],
      ['Eksik basitleştirme başvurusu hangi sürede tamamlanır; tamamlanmazsa ne olur?',
        'Eksiklik bildiriminden itibaren **en geç 60 gün** içinde; tamamlanmazsa başvuru **yapılmamış sayılır**.', 'GY m.233/2', '',
        ['bildirimin yapıldığı tarihi müteakip en geç altmış gün içinde tamamlanır', 'Bu süre içerisinde tamamlanmayan başvuru yapılmamış sayılır.']],
      ['Havayolu basitleştirmesinde başvuru sahibinde hangi şartlar aranır?',
        'TGB\'de **en az iki yıldır yerleşik** olmak, **başkası adına ve namına hareket etmemek**, **düzenli** transit işlemi yapmak ve yöneticiler hakkında m.230/1-c\'deki **kesinleşmiş ceza** bulunmaması; m.230\'daki **diğer koşullar aranmaz**.', 'GY m.237/1', '',
        ['başvuru sahibinin Türkiye Gümrük Bölgesinde en az iki yıldır yerleşik olması, başkası adına ve namına hareket etmemesi, düzenli olarak transit işlemleri yapması', 'Bu kapsamda yapılacak başvurularda, 230 uncu maddede belirtilen diğer koşullar aranmaz.']],
      ['Boru hattıyla transitte rejim hak sahibi kimdir ve rejim ne zaman son bulur?',
        'Rejim hak sahibi **boru hattı işletmesidir**; rejim, eşyanın gönderildiği kişinin işletmesine **ulaşıp kayıtlarına geçmesiyle** son bulur. Rejim hak sahipleri **başvuru ve izin koşullarına tabi değildir**.', 'GY m.229/3; m.238/2–3', '',
        ['Boru hattı ile yapılan taşımalarda, rejim hak sahipleri başvuru ve izin koşullarına tabi değildir.', 'Boru hattı ile transit rejiminde, rejim hak sahibi, boru hattı işletmesidir.', 'transit rejimi, eşyanın gönderildiği kişinin işletmesine ulaşıp kayıtlarına geçmesiyle son bulur']],
      ['İzinli gönderici yetkisi kimlere verilebilir?',
        'Transit eşyayı **hareket idaresine sunmaksızın** transit işlemi gerçekleştirmek isteyenlere; bu başvurularda **m.230–234 uygulanmaz**.', 'GY m.238/A; m.229/4', '',
        ['Transit rejimine konu eşyayı hareket idaresine sunmaksızın transit işlemleri gerçekleştirmek isteyen kişilere izinli gönderici yetkisi verilebilir.', 'İzinli gönderici yetkisi başvurularında, 230 ila 234 üncü madde hükümleri uygulanmaz.']],
    ] },
    { baslik: 'Beyana Aykırılıklar ve Tahsilat (GY m.239–244)', sorular: [
      ['Ulusal transitte serbest dolaşımda olmayan eşya varışta eksik çıkarsa süreç nasıl işler?',
        'Varış idaresi hareket idaresine **uyuşmazlık bildirir**; eksikliğin mahrecindeki eksik yükleme/yanlış beyandan kaynaklandığı **28 gün** içinde ispat edilmelidir (yazılı başvuruyla **+28 gün**). İspat edilemezse vergiler + GK **235/5-c** uyarınca vergilerin **iki katı** idari para cezası.', 'GY m.239/1-a', '',
        ['Varış gümrük idaresince, eksik çıkan miktar üzerinden hareket gümrük idaresine uyuşmazlık bildirilir.', 'uyuşmazlık bildiriminden itibaren 28 gün içerisinde rejim hak sahibince hareket gümrük idaresine ispat edilmesi gerekir', 'Bu süre yazılı başvuru halinde 28 gün daha uzatılabilir.', 'eşyanın gümrük vergilerinin iki katı idari para cezası uygulanır']],
      ['Eksiklikte yükümlü vergi ve cezayı varışta öderse rejim nasıl ibra edilir?',
        'Varış bildirimini müteakip **üç gün** içinde ödenirse varış idaresi mesaj gönderir; hareket idaresi **ilave bilgi ve belge aramaksızın** rejimi ibra eder.', 'GY m.239/1-b', '',
        ['bunların varış bildirimini müteakip üç gün içinde ödenmesi halinde', 'hareket gümrük idaresince ilave bilgi ve belge aranmaksızın rejim ibra edilir']],
      ['Ulusal transitte eşya varışta fazla çıkarsa ne yapılır?',
        'Fazla eşya **geçici depolama yeri veya antrepoya** alınır; yanlış beyan belgelerden anlaşılırsa rejim beyanına izin verilir; aksi halde **28 gün** (+28) içinde ispat; ispat edilemezse GK **235/5-d** uygulanır.', 'GY m.239/2-a', '',
        ['Fazla çıkan eşya geçici depolama yeri veya antrepoya alınır', 'Süresi içerisinde ispat edilememesi halinde, Kanunun 235 inci maddesinin beşinci fıkrasının (d) bendi uyarınca işlem yapılır.']],
      ['Eksiklik veya fazlalık eşyanın tabiatı icabı Ek-11 oranları içindeyse ne olur?',
        '**Takibat yapılmaz**, işlemler varışta tespit edilen miktar üzerinden sonuçlandırılır; takibat ve ceza yalnızca Ek-11 oranlarını **aşan kısım** için uygulanır.', 'GY m.241/1', '',
        ['eksiklik veya fazlalık takibatı yapılmayarak işlemler varış gümrük idaresince tespit edilen miktar üzerinden sonuçlandırılır', 'eksiklik veya fazlalığın tamamı için değil, Ek-11\'de belirtilen oranları aşan kısmı için uygulanır']],
      ['"Beyanda belirtilen cinsine uygun" ifadesinden ne anlaşılır?',
        'Beyan edilen ve tespit edilen eşyanın **6\'lı tarife alt pozisyonunun aynı** olması.', 'GY m.241/5', '',
        '"beyanda belirtilen cinsine uygun" ifadesinden, beyan edilen eşya ile tespit edilen eşyanın 6\'lı tarife alt pozisyonunun aynı olması durumu anlaşılır'],
      ['Serbest dolaşımdaki ihraç eşyası varışta miktar veya cins bakımından aykırı çıkarsa hangi hüküm uygulanır?',
        'Sonradan ihraç edilsin veya edilmesin **GK m.241**.', 'GY m.242/1', '',
        'miktar ve cins bakımından transit beyannamesine göre aykırı çıkan ihraç eşyası için sonradan ihraç edilsin veya edilmesin Kanunun 241 inci maddesi uygulanır'],
      ['Karayoluyla sevk edilecek transit eşyanın giriş idaresinde belirgin şekilde farklı cinste olduğu tespit edilirse ne olur?',
        'Tahlil, teknik inceleme ve araştırmaya gerek olmadan tespit edilirse GK **235/5-(a) veya (b)** uyarınca idari para cezası uygulanır, ardından **sevkine izin verilir**.', 'GY m.243/1', '',
        'Kanunun 235 inci maddesinin beşinci fıkrasının (a) veya (b) bentleri uyarınca idari para cezasının uygulanmasını müteakip eşyanın sevkine izin verilir'],
      ['Transit işlemi usulüne uygun gerçekleştirilmezse vergiler nasıl tahsil edilir?',
        '**Tahsilat işlemi başlatılır**; **6183 sayılı Kanuna** göre takip edilir; süresinde ödenmeyenler için **kefil** nezdinde tahsilat başlatılır; teminat yetmezse kalan tutar **yükümlüden** alınır.', 'GY m.244', '',
        ['İlgili gümrük idaresince transit işleminin usulüne uygun olarak gerçekleştirilmediğinin tespit edilmesi durumunda tahsilat işlemi başlatılır.', 'ilgili gümrük idaresince kefil nezdinde tahsilat işlemi başlatılır', 'Teminatın yeterli olmaması halinde kalan tutar, 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanun hükümlerine göre yükümlüsünden tahsil edilir.']],
    ] },
  ],
  tuzaklar: [
    'Transitte **teminat zorunludur**; Kanundaki istisna **havayolu, boru hattı, demiryolu, denizyolu** (yönetmelikle belirlenen haller hariç) — **karayolu istisna değildir**. Yönetmelikte demiryolu yalnızca **m.235 basitleştirilmiş usulde** teminatsızdır.',
    'Transit beyanı: transit refakat belgesi, **TIR Karnesi**, **ATA Karnesi**, **Form 302**, CIM, manifesto, sözlü beyan formu. **CMR** ve **fatura** transit beyanı **değildir**.',
    'Rejim eşya ve belgelerin **varış** gümrük idaresine sunulmasıyla **sona erer**; hareket–varış bilgilerinin karşılaştırılmasıyla **ibra** edilir (sona erme ≠ ibra).',
    'NCTS\'de beyan tarihinden itibaren **30 gün** içinde hareket idaresine sunulmayan beyan **reddedilir**; bu retlerde GK **m.241 uygulanmaz**.',
    'Beyana aykırılık: ispat süresi **28 gün + 28 gün**; varışta ödeme **3 gün**; eksiklikte GK 235/5-**c** (vergilerin **iki katı** İPC), fazlalıkta 235/5-**d**. "Cinsine uygun" = **6\'lı** tarife alt pozisyonu aynı.',
    'Basitleştirme: vergi kaybı cezası **%2**, usulsüzlük cezası **%5**, son bir yılda **500** transit beyannamesi; eksik başvuru **60 gün**; havayolunda **en az 2 yıl** yerleşiklik. Kamu idarelerinde genel şartlar **aranmaz**.',
    'Telef/kayıp kanıtı: hırsızlık → **Cumhuriyet Savcılığı**; herkesçe bilinen olay → **en büyük mülki idare amiri**; trafik kazası → **gümrük idare amiri** kararı.',
    'Boru hattında rejim hak sahibi **boru hattı işletmesi**; rejim eşya alıcının işletmesine ulaşıp **kayıtlarına geçmesiyle** son bulur. Türk limanları arası transit → **yalnız Türk bandıralı** gemi.',
  ],
};
