// 27. Konu — Transit Rejiminde İzinli Gönderici (kaynak: 27-seri no 14.docx)
// Her soru: [soru, cevap, dayanak, çıkmış yıllar, kanıt (kaynaktan birebir)]
module.exports = {
  no: '27',
  konu: 'Transit Rejiminde İzinli Gönderici (Seri No: 14)',
  kaynak: '27-seri no 14.docx (Gümrük Genel Tebliği (Transit Rejimi) Seri No: 14, m.1–21)',
  bolumler: [
    { baslik: 'Amaç, Dayanak ve Tanımlar (Tebliğ m.1–3, 20)', sorular: [
      ['Seri No: 14 Tebliğ GY\'nin hangi maddesindeki yetkiyi düzenler?',
        'GY **m.238/A**\'da düzenlenen **izinli gönderici yetkisi** (koşullar, başvuru, inceleme, verilme, askı, iptal, gümrük işlemleri).', 'Transit Tebliği (Seri No: 14) m.1', '',
        'Gümrük Yönetmeliğinin 238/A maddesinde düzenlenen izinli gönderici yetkisi başvurusunda aranacak koşullar'],
      ['Tebliğin dayanakları ve yürürlük tarihi nedir?',
        '**Ortak Transit Rejimine İlişkin Sözleşme** ve GY **m.238/A**; yürürlük **1/1/2022**.', 'Transit Tebliği (Seri No: 14) m.2, 20', '',
        ['Ortak Transit Rejimine İlişkin Sözleşme ve Gümrük Yönetmeliğinin 238/A maddesine dayanılarak hazırlanmıştır', 'Bu Tebliğ 1/1/2022 tarihinde yürürlüğe girer']],
      ['İzinli gönderici kimdir?',
        'Transit rejimine tabi eşyayı **hareket gümrük idaresine sunmaksızın** sevk etmeye yetkili ve **transit işlemlerinden sorumlu** kişi.', 'Transit Tebliği (Seri No: 14) m.3/1-ç', '',
        'Transit rejimine tabi eşyayı, hareket gümrük idaresine sunmaksızın sevk etmeye yetkilendirilmiş olan ve rejim kapsamında yapılan işlemlerde transit işlemlerinden sorumlu olan kişiyi'],
      ['"Kolay ihracat noktaları uygulaması" nedir?',
        'Nihai çıkış noktası izinli gönderici tesisi olmak kaydıyla, herhangi bir yerden tescilli ihracat eşyasının **transit beyanı ve mühür olmaksızın** tesise getirilip oradan **sınır gümrük idaresine doğrudan** sevki.', 'Transit Tebliği (Seri No: 14) m.3/1-d', '',
        'Nihai çıkış noktasının bir izinli gönderici tesisi olması kaydıyla, ülkenin herhangi bir noktasından tescil edilen ihracat beyannamesi kapsamı eşyanın transit beyanı ve mühür tatbiki olmaksızın getirildiği izinli gönderici tesisinden sınır gümrük idaresine doğrudan sevkine imkan veren uygulamayı'],
    ] },
    { baslik: 'Başvuru Koşulları (Tebliğ m.4)', sorular: [
      ['Teminat bakımından hangi koşul aranır?',
        '**Kapsamlı teminat kullanma** veya **teminattan vazgeçme** izni; kapsamlı teminat mektubu **Türkiye\'de yerleşik kefil kuruluştan** alınmış olmalı.', 'Transit Tebliği (Seri No: 14) m.4/1-a', '',
        'teminat mektubunun, Türkiye\'de yerleşik bir kefil kuruluştan alınmış olması şartıyla kapsamlı teminat kullanma veya teminattan vazgeçme iznine sahip olması'],
      ['Kimler hakkında kesinleşmiş mahkûmiyet kararı bulunmamalıdır?',
        '**Yönetim kurulu üyeleri** ve şirket sermayesinin **%10 veya daha fazlasına** sahip gerçek kişiler.', 'Transit Tebliği (Seri No: 14) m.4/1-b', '',
        'Yönetim kurulu üyeleri ile şirket sermayesinin % 10 veya daha fazlasına sahip gerçek kişiler hakkında başvuru formunda belirtilen suçlarla ilgili kesinleşmiş mahkûmiyet kararı bulunmaması'],
      ['Transit beyanı sayısına ilişkin koşul nedir?',
        'Geriye dönük **3 takvim yılı**, her yıl ayrı: ihracat eşyası taşımasında **TIR karnesi dahil** en az **5.500** transit beyanında **rejim hak sahibi** ya da en az **500** transit beyanında **taşıyıcı** olmak.', 'Transit Tebliği (Seri No: 14) m.4/1-c', '',
        ['geriye dönük üç takvim yılı boyunca her yıl ayrı ayrı değerlendirilmek üzere ihracat beyannamesi kapsamı eşyanın taşınmasına yönelik olarak', 'TIR karnesi dahil en az 5.500 transit beyanında rejim hak sahibi olması veya en az 500 transit beyanında taşıyıcı sıfatını taşıyor olması']],
      ['Ceza uygulanmamış olma koşulundaki oranlar nedir?',
        'Beyanname sayısının **%0,5**\'ini aşan **vergi kaybı** cezası ve **%2**\'sini aşan GK **m.241** usulsüzlük cezası (**birinci fıkra hariç**) uygulanmamış olmalı (son 3 takvim yılı, her yıl ayrı).', 'Transit Tebliği (Seri No: 14) m.4/1-ç', '',
        ['işlem gören tüm beyanname sayısının % 0,5\'ini aşan sayıda vergi kaybına neden olan gümrük mevzuatı ihlali nedeniyle ceza uygulanmamış olması', '% 2\'sini aşan sayıda birinci fıkrası hariç Gümrük Kanununun 241 inci maddesi uyarınca usulsüzlük cezası uygulanmamış olması']],
      ['Sertifika ve mali yapı koşulları nelerdir?',
        'Geçerli **ISO 9001 ve ISO 27001**; mali yapının başvuru yılından önceki **3 yıl** esas alınarak **yeminli mali müşavirce** olumlu raporlanması.', 'Transit Tebliği (Seri No: 14) m.4/1-e, g', '',
        ['geçerli ISO 9001 ve ISO 27001 sertifikalarına sahip olunması', 'başvuru yılından önceki üç yıl esas alınmak suretiyle, yeminli mali müşavir tarafından incelenerek']],
      ['Başvuru sahibi yetkilendirilmiş yükümlü (YYS) ise hangi kolaylık uygulanır?',
        '**(g) mali yapı** ve **(ğ) borç bulunmaması** koşullarını kanıtlamaz; **(c)** transit beyanı sayısı **dörtte bir** oranında uygulanır.', 'Transit Tebliği (Seri No: 14) m.4/2', '',
        ['birinci fıkranın (g) ve (ğ) bentlerinde belirtilen koşulları kanıtlaması gerekmez', 'transit beyanı sayısı ise dörtte bir nispetinde uygulanır']],
    ] },
    { baslik: 'Başvuru, İnceleme ve Yetkinin Geçerliliği (Tebliğ m.5, 11)', sorular: [
      ['Ön başvuru ve başvuru nereye yapılır?',
        'Ön başvuru **Ek-1/A** ile **bölge müdürlüğüne**; başvuru **Ek-1/B** ile **Genel Müdürlüğe**.', 'Transit Tebliği (Seri No: 14) m.5/1', '',
        'Ön Başvuru Ek-1/A\'da yer alan ön başvuru formuyla bölge müdürlüğüne, başvuru ise Ek-1/B\'de yer alan başvuru formuyla Genel Müdürlüğe yapılır'],
      ['Koşulların değerlendirmesi ve yerinde incelemeyi kim yapar?',
        '(a)–(ğ) bentleri: Genel Müdürlükçe görevlendirilen **Ticaret Uzmanı**; (h) bendi (orantısız idari yük): **bölge müdürlüğü**.', 'Transit Tebliği (Seri No: 14) m.5/2', '',
        ['Genel Müdürlükçe görevlendirilen Ticaret Uzmanı', '(h) bendinde belirtilen koşulun sağlandığına ilişkin değerlendirme ve inceleme ise ilgili bölge müdürlüğü tarafından gerçekleştirilir']],
      ['Yerinde incelemenin konaklama ve ulaşım giderlerini kim karşılar?',
        '**5 günü geçmemek** üzere **başvuru sahibi**.', 'Transit Tebliği (Seri No: 14) m.5/3', '',
        'beş günü geçmemek üzere yapılan konaklama ve ulaşım giderleri inceleme sırasında başvuruda bulunanlarca karşılanır'],
      ['İzinli gönderici yetkisi ne kadar geçerlidir; yenileme ne zaman yapılır?',
        '**Askıya alınmadıkça veya iptal edilmedikçe** geçerlidir; yenileme yetkilendirme yılını izleyen **her 3 yılın son ayında** veya Genel Müdürlük talep ettiğinde.', 'Transit Tebliği (Seri No: 14) m.5/4', '',
        ['İzinli gönderici yetkisi askıya alınmadığı veya iptal edilmediği sürece geçerlidir', 'Yenileme başvurusu yetkilendirmenin yapıldığı takvim yılını izleyen her üç yılın son ayında veya Genel Müdürlükçe talep edilmesi halinde yapılır']],
      ['Tesisin bağlı olacağı gümrük müdürlüğü nasıl belirlenir ve değiştirilir?',
        'Bilgiyi **bölge müdürlüğü** Ek-1/A ile Genel Müdürlüğe gönderir; **yükümlü talebiyle** veya **Genel Müdürlükçe resen** değiştirilebilir.', 'Transit Tebliği (Seri No: 14) m.11', '',
        ['tesisin bağlı olacağı gümrük müdürlüğü bilgisini de Ek-1/A\'da yer alan ön başvuru formuyla Genel Müdürlüğe gönderir', 'Tesisin bağlı bulunduğu gümrük müdürlüğü yükümlü talebine istinaden yahut Genel Müdürlükçe resen değiştirilebilir']],
    ] },
    { baslik: 'Tesis ve Yetkinin Askıya Alınması, İptali (Tebliğ m.6–10)', sorular: [
      ['Tesis yetkilendirmesi ne kadar süreyle askıya alınır; örnek bir hal nedir?',
        'Durum **ortadan kalkıncaya kadar**; ör. **bölge müdürlüğünün** somut risk tespiti, memura kolaylık sağlanmaması, lojistik programın uygun olmaması.', 'Transit Tebliği (Seri No: 14) m.6', '',
        ['ilgili tesisin yetkilendirilmesi söz konusu durum ortadan kalkıncaya kadar askıya alınır', 'Bölge müdürlüğünce tesisin faaliyetinin devam etmesinin risk doğuracağına yönelik somut bir tespit bulunması']],
      ['Tesis yetkilendirmesini iptal ettiren hallerden ikisi nedir?',
        '**Hazır bildiriminden sonra** eşyanın tesise girmesi; başka rejim hak sahibinin mühürlü aracına **Ek-3 genel muvafakatname olmadan** yeni mühür tatbiki (ayrıca güvenlik/kamera kayıtları ve erken çıkış halleri).', 'Transit Tebliği (Seri No: 14) m.7', '',
        ['hazır bildiriminin yapılmasından sonra tesise eşyanın giriş yaptığının tespit edilmesi', 'rejim hak sahibinin Ek-3\'te yer alan genel muvafakatnamesi olmaksızın tesiste yeni mühür tatbik edilmesi']],
      ['Yenileme yapılmaması hangi hallerde yetkinin askıya alınmasına yol açar?',
        'Genel Müdürlük talebinde **tebligattan itibaren 30 gün** içinde yenileme başvurusu yapılmaması; **her 3 yılın sonunda** başvurunun yenilenmemesi.', 'Transit Tebliği (Seri No: 14) m.8/1-b, c', '',
        ['tebligat tarihinden başlamak üzere 5 inci maddenin dördüncü fıkrasında belirtilen yenileme başvurusunun 30 gün içerisinde yapılmaması', 'İzinli gönderici yetkisinin verildiği takvim yılını izleyen her üç yılın sonunda başvurunun yenilenmemesi']],
      ['İzinli gönderici yetkisi hangi hallerde iptal edilir?',
        'Askıdan itibaren **90 gün** içinde yenilenmemesi; **tesise girmeyen eşya** için mühürleme/transit işlemi; yanlış, eksik bilgi veya sahte belge; **özel tipte mühür dışında** mühür kullanımı.', 'Transit Tebliği (Seri No: 14) m.9', '',
        ['askıya alma işleminden itibaren 90 gün içerisinde başvurunun yenilenmemesi', 'Tesise girişi gerçekleşmeyen bir eşya için izinli gönderici yetkisi kapsamında mühürleme ve transit işlemlerinin gerçekleştirildiğinin tespit edilmesi', 'Gümrük idaresinden temin edilen özel tipte mühür dışında mühür kullanılması']],
      ['Askı ve iptal kararlarını kim bildirir; iptalde yeniden başvuru tarihi hangi aralıkta belirlenir?',
        '**Genel Müdürlük**, gerekçeli olarak; yeniden başvuru tarihi **1 aydan az, 3 yıldan fazla olmayacak** şekilde.', 'Transit Tebliği (Seri No: 14) m.10', '',
        ['izin sahibine gerekçeli olarak Genel Müdürlükçe bildirilir', 'bir aydan az üç yıldan fazla olmayacak şekilde belirlenir']],
    ] },
    { baslik: 'Gümrük İşlemleri ve Mühür (Tebliğ m.12–18)', sorular: [
      ['İzinli gönderici tesisinden ihraç edilecek eşyanın ihracat beyannamesi nereden tescil edilir?',
        'Kolay ihracat noktaları **hariç**, tesisin **bağlı bulunduğu gümrük müdürlüğünden** elektronik ortamda.', 'Transit Tebliği (Seri No: 14) m.12/3', '',
        'Kolay ihracat noktaları uygulaması hariç olmak üzere, ikinci fıkrada belirtilen eşyaya ilişkin ihracat beyannamesi, izinli gönderici tesisinin bağlı bulunduğu gümrük müdürlüğünden elektronik ortamda tescil edilerek onaylanır'],
      ['Muayene öngörülürse ne kadar sürede ve nerede yapılır?',
        'Kontrol türü bildiriminden itibaren **azami 3 saat** içinde, **izinli gönderici tesislerinde**.', 'Transit Tebliği (Seri No: 14) m.12/6', '',
        'muayene işlemi kontrol türünün bildirimini müteakip azami üç saat içinde yetki kapsamı izinli gönderici tesislerinde gerçekleştirilir'],
      ['Transit beyannamesinde teminat gerekirse yetki sahibi hangi teminatı kullanabilir?',
        'Yalnızca **kendisine ait kapsamlı teminatı**.', 'Transit Tebliği (Seri No: 14) m.12/8', '',
        'yetki sahibi sadece kendisine ait kapsamlı teminatı kullanabilir'],
      ['Transit beyannamesi kırmızı hatta işlem görecekse mühür işlemleri nasıl yürür?',
        'Mührü **muayene memuru** söker; muayeneden sonra **izinli gönderici** yeni mühür tatbik eder.', 'Transit Tebliği (Seri No: 14) m.12/9', '',
        'muayene memurunca tesislerde izinli gönderici mührü sökülür ve muayeneyi müteakip izinli gönderici tarafından yeni mühür tatbik edilir'],
      ['Mesai saatleri dışındaki işlemlerde fazla mesai ücreti hangi hallerde ödenir?',
        '**Belge kontrolü** veya **muayene** bildirilen beyannamelerde ücret yatırılır; bunlar dışındaki beyannameler **ücretsiz** tamamlanır.', 'Transit Tebliği (Seri No: 14) m.13', '',
        ['fazla mesai ücreti yatırılması koşuluyla yerine getirilir', 'fazla mesai ücreti ödenmeksizin tamamlanır']],
      ['İzinli gönderici tesisinde mühür sökme yetkisi hangi araçlarla sınırlıdır?',
        'Yetki sahibinin **rejim hak sahibi olduğu** transit beyanlarıyla gelen araçlarla; **Ek-3 muvafakatname** varsa sınırlama uygulanmaz.', 'Transit Tebliği (Seri No: 14) m.14/1–2', '',
        ['İzinli gönderici tesisinde mühür sökme yetkisi sadece yetki sahibinin rejim hak sahibi olduğu transit beyanlarıyla tesise gelen araçlarla sınırlıdır', 'İzinli göndericinin Ek-3\'te yer alan muvafakatnameye sahip olması durumunda birinci fıkrada yer alan sınırlama uygulanmaz']],
      ['İhracatta yerinde gümrükleme (İYG) tesislerinden yapılacak taşımalarda izinli gönderici ne yapabilir?',
        '**Rejim hak sahibi** olarak **basitleştirilmiş usulde** transit beyanı verir; izinli gönderici mührü **İYG tesisinde** tatbik edilir.', 'Transit Tebliği (Seri No: 14) m.15', '',
        ['İhracatta yerinde gümrükleme izni sahibi firmaların tesislerinden ihraç edilecek eşyanın transit beyanını izinli gönderici yetkisi sahibi rejim hak sahibi olarak basitleştirilmiş usulde verebilir', 'ihracatta yerinde gümrükleme tesislerinde izinli gönderici mührü tatbik edilir']],
      ['Tesisten çıkıştan sonra antrepodan ya da gümrük idaresinden eşya alınırsa mühür işlemlerini kim yapar?',
        'Antrepoda: **yetkilendirilmiş gümrük müşaviri** veya **antrepoda görevli gümrük memuru**; gümrük idaresinden alımda: **gümrük idaresi**.', 'Transit Tebliği (Seri No: 14) m.16/2, 17/2', '',
        ['yetkilendirilmiş gümrük müşaviri veya antrepoda görevli gümrük memuru tarafından yapılır', 'yeni mühür tatbiki işlemleri gümrük idaresi tarafından yapılır']],
      ['İzinli gönderici hangi mührü kullanır; mühürler nerede muhafaza edilir?',
        'Gümrük idaresinden **ücreti karşılığında** alınan, Sözleşmenin **82. maddesine** uygun **özel tipte mühür**; İYG tesisinde mühürleme hali dışında **tesiste muhafaza edilir, tesis dışına çıkarılamaz**.', 'Transit Tebliği (Seri No: 14) m.18/1–2', '',
        ['gümrük idaresinden ücreti karşılığında temin edilecek, Sözleşmenin 82 nci maddesine uygun özel tipte mühür kullanır', 'mühürler izinli gönderici tesisinde muhafaza edilir ve tesis dışına çıkarılamaz']],
    ] },
  ],
  tuzaklar: [
    'Dayanak GY **m.238/A** (+ Ortak Transit Sözleşmesi); yürürlük **1/1/2022**. İzinli gönderici eşyayı **hareket idaresine sunmadan** sevk eder ve transit işlemlerinden **sorumludur**.',
    'Sayılar: **5.500** beyanda **rejim hak sahibi** ya da **500** beyanda **taşıyıcı** (TIR karnesi dahil, son **3 takvim yılı** her yıl ayrı); ceza eşikleri **%0,5** (vergi kaybı) ve **%2** (241 usulsüzlük, **1. fıkra hariç**); ortaklık eşiği **%10 veya daha fazla**.',
    '**YYS** sahibinde (g) mali yapı ve (ğ) borç koşulu **aranmaz**; transit beyanı sayısı **dörtte bir** uygulanır.',
    'Ön başvuru **bölge müdürlüğüne (Ek-1/A)**, başvuru **Genel Müdürlüğe (Ek-1/B)**; (a)–(ğ) incelemesi **Ticaret Uzmanı**, (h) **bölge müdürlüğü**; inceleme gideri **5 gün**e kadar başvuru sahibinden.',
    'Süreler: yenileme **her 3 yılın son ayı**; GM talebinde **30 gün**; askıdan sonra **90 gün** içinde yenilenmezse **iptal**; yeniden başvuru tarihi **1 ay – 3 yıl** arası; muayene **azami 3 saat**.',
    '**Tesis** askısı/iptali ile **yetki** askısı/iptali ayrı maddelerdir (m.6–7 ↔ m.8–9); hepsini **Genel Müdürlük** gerekçeli bildirir.',
    'Mühür: **özel tipte**, gümrükten **ücretli**, Sözleşme **m.82**; tesis dışına çıkarılamaz. Kırmızı hatta mührü **muayene memuru** söker, yenisini **izinli gönderici** takar; antrepoda **yetkilendirilmiş gümrük müşaviri veya antrepo memuru**, gümrük idaresinde **gümrük idaresi**.',
    'Teminat: transit beyannamesinde yalnız **kendi kapsamlı teminatı**; koşul olarak teminat mektubu **Türkiye\'de yerleşik kefil** kuruluştan.',
  ],
};
