# Soru Bankası — Bölüm 04: Onaylanmış Kişi Statüsü (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
# Kaynak: 4-OKSB.txt (Gümrük Yönetmeliği md. 22-26; Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1))
Q = [

# ---------------- STATÜ KOŞULLARI ----------------
dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="SÜRE",
z="Z",
madde="Gümrük Yönetmeliği md. 22; Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 12",
cek="İki yıllık fiili faaliyet şartı, YGM ile ön inceleme için tespit sözleşmesinin yapıldığı tarih itibarıyla değerlendirilir; daha kısa faaliyette başvuru reddedilir.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre, statü belgesi talebinin başvuru sahibinin iki yıldan daha az süredir faaliyette bulunduğu gerekçesiyle reddedilmesinde, faaliyet süresi aşağıdaki tarihlerden hangisi itibarıyla değerlendirilir?"],
d="Yetkilendirilmiş gümrük müşaviriyle ön inceleme için tespit sözleşmesinin yapıldığı tarih",
c=["Ön inceleme için tespit sözleşmesinin yapıldığı ayın ilk günü",
   "Olumlu tespit raporunun düzenlendiği tarih",
   "Başvurunun yetkili bölge müdürlüğünün genel evrak kaydına alındığı tarih",
   "Statü belgesinin düzenlendiği tarih"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre onaylanmış kişi statüsü, Türkiye Gümrük Bölgesinde yerleşik ve en az iki yıldır fiilen faaliyette bulunan gerçek ve tüzel kişilere talepleri hâlinde verilir. Tebliğ, bu sürenin hangi an itibarıyla aranacağını ret hâlleri arasında gösterir: başvuru sahibinin, yetkilendirilmiş gümrük müşaviriyle onaylanmış kişi statüsü başvurusunun ön incelemesi için sözleşme yapıldığı tarih itibarıyla iki yıldan daha az süredir faaliyette bulunduğunun anlaşılması hâlinde statü belgesi talebi reddedilir (devir, birleşme ve kısmi bölünme hâlleri saklıdır). En güçlü çeldirici 'sözleşmenin yapıldığı ayın ilk günü'dür: bu an, ceza kararı oranları ile dış ticaret performansında geriye dönük iki yıllık dönemlerin başlangıcıdır; faaliyet süresinde ise sözleşmenin yapıldığı tarihin kendisi esas alınır. Olumlu tespit raporunun düzenlendiği tarih başvurunun beş iş günlük süresini başlatır; statü belgesinin düzenlendiği tarih ise geri almadaki on iki aylık dönemin başlangıcıdır. Bu nedenle doğru cevap 'Yetkilendirilmiş gümrük müşaviriyle ön inceleme için tespit sözleşmesinin yapıldığı tarih' seçeneğidir. (MD GY 22; OKS Tebliği 12)",
kanit="4-OKSB.txt | Türkiye Gümrük Bölgesinde yerleşik ve en az iki yıldır fiilen faaliyette bulunan gerçek ve tüzel kişilere talep etmeleri halinde onaylanmış kişi statüsü verilir || 4-OKSB.txt | başvuru sahibinin yetkilendirilmiş gümrük müşaviriyle onaylanmış kişi statüsü başvurusunun ön incelemesi için sözleşme yapıldığı tarih itibariyle 2 yıldan daha az süredir faaliyette bulunduğunun anlaşılması || 4-OKSB.txt | ön incelemesi için sözleşme yapıldığı ayın ilk gününden geriye dönük iki yıl içerisinde",
yuva=["GY 23/1-b, c, ç ve 24/1-a: ceza kararı oranları ile dış ticaret performansında geriye dönük iki yılın başlangıcı (sözleşme ayının ilk günü)",
      "Tebliğ 9/1: başvurunun beş iş günlük süresi olumlu tespit raporunun düzenlenme tarihinden başlar",
      "Tebliğ 10/1 ve 42/A/1: başvurunun genel evrak kaydı; kontrol türü kolaylaştırmasında süre başvuru tarihinden geriye sayılır",
      "GY 26/2 ve Tebliğ 62/1: statü belgesinin düzenlenme tarihini takip eden on iki aylık dönem"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[1, 2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="2024/75",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="OLAY",
z="Z",
madde="Gümrük Yönetmeliği md. 22, 24",
cek="YYS statüsü tanınan şirketten kısmi veya tam bölünmeyle kurulan şirketin başvurusunda, şirket ilişkisi varsa iki yıllık faaliyet şartı aranmaz.",
kok=["(A) A.Ş.'ye Gümrük Kanunu kapsamında yetkilendirilmiş yükümlü statüsü tanınmıştır; (A) A.Ş.'nin onaylanmış kişi statü belgesi yoktur. Ayrıca:",
     "- (A) A.Ş., malvarlığının bir bölümünü kısmi bölünme suretiyle yeni kurulan (B) A.Ş.'ye devretmiştir,",
     "- (B) A.Ş.'nin sermayesinin tamamı (A) A.Ş.'ye aittir,",
     "- (B) A.Ş., kuruluşundan on ay sonra onaylanmış kişi statü belgesi için başvurmak istemektedir.",
     "Gümrük Yönetmeliği'nin onaylanmış kişi statüsü verilebilecek kişilere ilişkin hükümlerine göre (B) A.Ş.'nin başvurusunda en az iki yıldır fiilen faaliyette bulunma koşuluna ilişkin aşağıdakilerden hangisi doğrudur?"],
d="İki yıllık faaliyet koşulu, bölünen şirketle aralarında şirket ilişkisi bulunduğu için aranmaz.",
c=["Bölünmede iki yıllık koşulun aranmaması yalnızca statü belgesi sahibi şirketlerin bölünmesine özgü olduğundan (B) A.Ş. iki yılı doldurmadan başvuramaz.",
   "İki yıllık faaliyet koşulu yalnızca tam bölünme hâlinde aranmaz; kısmi bölünmede (B) A.Ş.'nin bu koşulu sağlaması gerekir.",
   "(B) A.Ş., yetkilendirilmiş yükümlü statüsü tanınan bir şirketten bölündüğü için onaylanmış kişi statüsüne başvuramaz.",
   "İki yıllık faaliyet koşulu aranmaz; bu sonuç için bölünen şirketle aralarında şirket ilişkisi bulunup bulunmadığına bakılmaz."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre onaylanmış kişi statüsü kural olarak en az iki yıldır fiilen faaliyette bulunan kişilere verilir. Vakada saklı istisna, bölünen şirketin onaylanmış kişi değil yetkilendirilmiş yükümlü olmasıdır: Yönetmelik, Gümrük Kanunu kapsamında yetkilendirilmiş yükümlü statüsü tanınan şirketin malvarlığının bir veya birden fazla bölümünü yeni kurulacak bir şirkete kısmi veya tam bölünme suretiyle devretmesi hâlinde, idaresi ve murakabesi ve/veya sermayesi bakımından iki şirket arasında vasıtalı veya vasıtasız şirket ilişkisi bulunması koşuluyla, devralan tüzel kişiliğin başvurusunda iki yıllık faaliyet koşulunu aramaz. (B) A.Ş.'nin sermayesinin tamamı (A) A.Ş.'ye ait olduğundan şirket ilişkisi vardır. En güçlü çeldirici, istisnanın yalnızca statü belgesi sahibi şirketlerin devir, birleşme veya kısmi bölünmesine ait olduğunu söyleyen seçenektir; Yönetmelik bu hâllerin yanında yetkilendirilmiş yükümlü şirketlerin bölünmesini ayrıca düzenlemiştir. Tebliğ'deki ret hâli, adına yetkilendirilmiş yükümlü sertifikası düzenlenmiş başvuru sahibine ilişkindir; (B) A.Ş. adına böyle bir sertifika yoktur. Bu nedenle doğru cevap 'İki yıllık faaliyet koşulu, bölünen şirketle aralarında şirket ilişkisi bulunduğu için aranmaz.' seçeneğidir. (MD GY 22; OKS Tebliği 12)",
kanit="4-OKSB.txt | yetkilendirilmiş yükümlü statüsü tanınan şirketin, malvarlığının bir veya birden fazla bölümünü yeni kurulacak bir şirkete kısmi veya tam bölünme suretiyle devretmesi halinde || 4-OKSB.txt | vasıtalı veya vasıtasız şirket ilişkisi bulunması koşuluyla, devralan tüzel kişiliğin yapacağı onaylanmış kişi statü belgesi başvurusunda birinci fıkrada belirtilen en az iki yıldır fiilen faaliyette bulunma koşulu aranmaz || 4-OKSB.txt | adlarına yetkilendirilmiş yükümlü sertifikası düzenlenmiş olduğunun tespit edilmesi",
yuva=["GY 22/2 ile 24/5-6: statü belgesi sahibinin devir, birleşme veya kısmi bölünmesi (istisnanın yalnızca bir kolu)",
      "GY 22/3: istisna 'kısmi veya tam bölünme' için birlikte öngörülmüştür",
      "Tebliğ 12/1-f ve 62/4: adına YYS sertifikası düzenlenmiş kişinin başvurusunun reddi ve belgesinin geri alınması",
      "GY 22/3: istisna 'şirket ilişkisi bulunması koşuluyla' uygulanır"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "KOMŞU", "ŞART"],
duzey=["UYGULAMA"],
profil=[1, 3],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2024/75",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="KAPSAM_DIŞI",
z="K",
madde="Gümrük Yönetmeliği md. 23",
cek="Yöneticiler ve yüzde on ortaklar için aranan sicil koşulunda 5607, 1567, 5015, 5549 sayılı Kanunlar sayılmıştır; 4458 sayılı Gümrük Kanunu sayılmamıştır.",
kok=["Gümrük Yönetmeliği'ne göre onaylanmış kişi statüsü için aranan genel koşullardan biri, başvuru sahibinin yönetim kurulu üyeleri, sermayesinin yüzde on ve fazlasına sahip gerçek kişiler ile gümrük ve dış ticaret işlemlerinde temsil yetkisini haiz çalışanları hakkında sayılan suçlardan ve kanunlara muhalefetten ceza veya mahkumiyet kararı bulunmamasıdır.",
     "Bu koşulda muhalefeti esas alınan kanunlar arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="4458 sayılı Gümrük Kanunu",
c=["1567 sayılı Türk Parasının Kıymetini Koruma Hakkında Kanun",
   "5015 sayılı Petrol Piyasası Kanunu",
   "5549 sayılı Suç Gelirlerinin Aklanmasının Önlenmesi Hakkında Kanun",
   "5607 sayılı Kaçakçılıkla Mücadele Kanunu"],
sirali=True,
siklar=["1567 sayılı Türk Parasının Kıymetini Koruma Hakkında Kanun",
        "4458 sayılı Gümrük Kanunu",
        "5015 sayılı Petrol Piyasası Kanunu",
        "5549 sayılı Suç Gelirlerinin Aklanmasının Önlenmesi Hakkında Kanun",
        "5607 sayılı Kaçakçılıkla Mücadele Kanunu"],
g="Gümrük Yönetmeliği'ne göre başvuru sahibinin yönetim kurulu üyeleri, sermayesinin yüzde on ve fazlasına sahip gerçek kişiler ile gümrük ve dış ticaret işlemlerinde temsil yetkisini haiz çalışanları hakkında; Türk Ceza Kanunu'nda sayılan suçlardan, Vergi Usul Kanunu'na göre vergi kaçakçılığı suçlarından ve tek tek sayılan kanunlara muhalefetten ceza veya mahkumiyet kararı bulunmaması gerekir. Sayılan kanunlar mülga 1918 ve 4926 sayılı Kanunlar ile 5607, 3628, 1567, 5015, 5549, 2313 ve 3298 sayılı Kanunlardır. 4458 sayılı Gümrük Kanunu bu listede yer almaz; Gümrük Kanunu ihlalleri bu koşulda değil, ceza kararı sayısının beyanname sayısına oranını ölçen ayrı genel koşullarda değerlendirilir. En güçlü çeldirici 5015 sayılı Petrol Piyasası Kanunu'dur: gümrükle ilgisiz göründüğü için listeye yabancı sanılır, oysa açıkça sayılmıştır. Bu nedenle doğru cevap '4458 sayılı Gümrük Kanunu' seçeneğidir. (MD GY 23)",
kanit="4-OKSB.txt | Yönetim kurulu üyeleri, sermayesinin yüzde on ve fazlasına sahip gerçek kişiler ile gümrük ve dış ticaret işlemlerinde temsil yetkisini haiz çalışanlarının || 4-OKSB.txt | 21/3/2007 tarihli ve 5607 sayılı Kaçakçılıkla Mücadele Kanununa || 4-OKSB.txt | 20/2/1930 tarihli ve 1567 sayılı Türk Parasının Kıymetini Koruma Hakkında Kanuna, 4/12/2003 tarihli ve 5015 sayılı Petrol Piyasası Kanununa, 11/10/2006 tarihli ve 5549 sayılı Suç Gelirlerinin Aklanmasının Önlenmesi Hakkında Kanuna",
yuva=["GY 23/1-a: listede (1567 sayılı Kanun)",
      "GY 23/1-a: listede (5015 sayılı Petrol Piyasası Kanunu)",
      "GY 23/1-a: listede (5549 sayılı Kanun)",
      "GY 23/1-a: listede (5607 sayılı Kaçakçılıkla Mücadele Kanunu)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU", "KOMŞU"],
duzey=["TANIMA"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Yönetmeliği md. 23",
cek="Ceza kararı oranlarında ihlal tarihi esas alınır; iki yıldan önceki fiiller ve kesinleşmemiş kararlar dikkate alınmaz; aynı tespitten çıkan kararlar tek sayılır.",
kok=["Gümrük Yönetmeliği'ne göre onaylanmış kişi statüsü için aranan genel koşullardan, gümrük mevzuatı ihlalleri nedeniyle düzenlenen ceza kararı sayısının gümrük beyannamesi sayısına oranına ilişkin koşulların uygulanmasıyla ilgili aşağıdaki ifadeler verilmiştir:",
     "I. Ceza kararlarının değerlendirilmesinde ceza kararının kesinleştiği tarih esas alınır.",
     "II. Kesinleşmemiş ceza kararları dikkate alınmaz.",
     "III. Ön inceleme için sözleşme yapıldığı ayın ilk gününden geriye dönük iki yıldan daha önce işlenen fiiller nedeniyle düzenlenen ceza kararları da dikkate alınır.",
     "IV. Aynı tespite istinaden geriye dönük olarak yapılan tarama sonucunda aynı ihlale ilişkin olarak düzenlenen birden fazla ceza kararı tek bir ceza kararı sayılır.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve IV",
c=["I ve II", "III ve IV", "I, II ve IV", "II, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre ceza kararı sayısının beyanname sayısına oranına ilişkin genel koşulların uygulanmasında ceza kararına sebep teşkil eden ihlalin tarihi esas alınır; kararın kesinleştiği tarih esas alınmaz (I yanlış). Kesinleşmemiş ceza kararları dikkate alınmaz (II doğru). Ön inceleme için sözleşme yapıldığı ayın ilk gününden geriye dönük iki yıldan daha önce işlenen fiiller nedeniyle düzenlenen ceza kararları dikkate alınmaz (III yanlış). Aynı tespite istinaden geriye dönük olarak yapılan tarama sonucunda aynı ihlale ilişkin düzenlenen birden fazla ceza kararı tek bir ceza kararı sayılır (IV doğru). En güçlü çeldirici I'dir: kesinleşme, kararın hesaba katılıp katılmayacağının ölçüsüdür; kararın hangi döneme gireceği ise ihlalin tarihine göre belirlenir. Bu nedenle doğru cevap 'II ve IV' seçeneğidir. (MD GY 23)",
kanit="4-OKSB.txt | ceza kararına sebep teşkil eden ihlalin tarihi esas alınır || 4-OKSB.txt | geriye dönük iki yıldan daha önce işlenen fiiller nedeniyle düzenlenen ceza kararları dikkate alınmaz || 4-OKSB.txt | aynı tespite istinaden geriye dönük olarak yapılan tarama sonucunda aynı ihlale ilişkin olarak düzenlenen birden fazla ceza kararı tek bir ceza kararı sayılır || 4-OKSB.txt | bentlerinin uygulanmasında kesinleşmemiş ceza kararları dikkate alınmaz",
yuva=["I ve II: I'deki 'kesinleşme tarihi' değişikliğini fark etmeyen, IV'ü bilmeyen aday (GY 23/7-8)",
      "III ve IV: iki yıllık geriye dönük sınırı ters okuyan aday (GY 23/7 ikinci cümle)",
      "I, II ve IV: dönem tespitinde ihlal tarihi yerine kesinleşme tarihini esas alan aday (GY 23/7 ile 23/9 karışımı)",
      "II, III ve IV: iki yıldan önceki fiillerin dışarıda kaldığını bilmeyen aday (GY 23/7)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "TERSİNE", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="HESAP",
z="ÇZ",
madde="Gümrük Yönetmeliği md. 23",
cek="Üç katı aşan vergi kaybı ceza kararları, beşten fazla ise, her dönemde beyanname sayısının yüzde birini aşmamalıdır; beş karar oran sınırına takılmaz.",
kok=["Onaylanmış kişi statüsü için başvuracak (K) firmasının, yetkilendirilmiş gümrük müşaviriyle ön inceleme için sözleşme yaptığı ayın ilk gününden geriye dönük iki yıl içindeki on ikişer aylık dönemlerine ait bilgiler şöyledir:",
     "- Birinci dönem: İşlem gören ithalat ve ihracat beyannamesi sayısı 450; vergi kaybına neden olan gümrük mevzuatı ihlalleri nedeniyle düzenlenen ve tutarı Kanunda öngörülen usulsüzlük cezasının üç katını aşan ceza kararı sayısı 5,",
     "- İkinci dönem: İşlem gören ithalat ve ihracat beyannamesi sayısı 720; aynı nitelikteki ceza kararı sayısı 7'dir.",
     "- Ceza kararlarının tamamı kesinleşmiş olup her biri, ilgili dönem içinde işlenen ve ayrı beyannamelere ilişkin ayrı ihlallere dayanmaktadır.",
     "Gümrük Yönetmeliği'nin onaylanmış kişi statüsü için aranan, vergi kaybına neden olan ihlallere ilişkin ceza kararı sayısı koşuluna göre (K) firmasının durumu hakkında aşağıdakilerden hangisi doğrudur?"],
d="Koşul her iki dönemde de sağlanmaktadır.",
c=["Koşul yalnızca ikinci dönemde sağlanmaktadır; birinci dönemde ceza kararı sayısı beyanname sayısının yüzde birini aştığından koşul sağlanmamaktadır.",
   "Koşul yalnızca birinci dönemde sağlanmaktadır; ikinci dönemde ceza kararı sayısı beşten fazla olduğundan koşul sağlanmamaktadır.",
   "Koşul hiçbir dönemde sağlanmamaktadır; her iki dönemde de ceza kararı sayısı beyanname sayısının binde üçünü aşmaktadır.",
   "Dönemler birlikte değerlendirildiğinde toplam on iki ceza kararı, toplam beyanname sayısının yüzde birini aştığından koşul sağlanmamaktadır."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre, sözleşmenin yapıldığı ayın ilk gününden geriye dönük iki yıl içinde on ikişer aylık iki dönem ayrı ayrı olmak üzere, her bir dönemde vergi kaybına neden olan ihlaller nedeniyle düzenlenen ve usulsüzlük cezasının üç katını aşan ceza kararlarının toplam sayısı, beşten fazla olmak koşuluyla, o dönemde işlem gören ithalat ve ihracat beyannamesi sayısının yüzde birini aşmamalıdır. Vakada saklı istisna 'beşten fazla olmak koşuluyla' kaydıdır: birinci dönemde karar sayısı 5'tir; beşi aşmadığından oran sınırı uygulanmaz ve koşul sağlanır (450'nin yüzde biri olan 4,5'in aşılması sonucu değiştirmez). İkinci dönemde karar sayısı 7'dir; beşten fazla olduğu için oran sınırı uygulanır, 720'nin yüzde biri 7,2'dir ve 7 bu sınırı aşmadığından koşul sağlanır. En güçlü çeldirici, birinci dönemde yüzde bir sınırının aşıldığını söyleyen seçenektir; bu hesap 'beşten fazla' kaydını atlar. Binde üç oranı, usulsüzlük cezasının yetmiş beş katını aşan kararlara ilişkin ayrı koşula aittir; dönemler de birleştirilmez, her biri ayrı değerlendirilir. Bu nedenle doğru cevap 'Koşul her iki dönemde de sağlanmaktadır.' seçeneğidir. (MD GY 23)",
kanit="4-OKSB.txt | on ikişer aylık iki dönem ayrı ayrı olmak üzere, her bir dönem içerisinde vergi kaybına neden olan gümrük mevzuatı ihlali nedeniyle || 4-OKSB.txt | öngörülen usulsüzlük cezasının üç katını aşan tutarda düzenlenmiş ceza kararı toplam sayısının, beşten fazla olmak koşuluyla, her bir dönemde işlem gören ithalat ve ihracata ilişkin gümrük beyannamesi toplam sayısının yüzde birini aşmaması || 4-OKSB.txt | ikiden fazla olmak koşuluyla, her bir dönemde işlem gören ithalat ve ihracata ilişkin gümrük beyannamesi toplam sayısının binde üçünü aşmaması",
yuva=["GY 23/1-b: 'beşten fazla olmak koşuluyla' kaydı atlanarak oran sınırı birinci döneme de uygulanmış",
      "GY 23/1-b: 'beşten fazla' kaydı oran sınırının kendisi sanılmış",
      "GY 23/1-c: binde üç oranı yetmiş beş kat ve ikiyüzelli kat eşiğindeki kararlara aittir",
      "GY 23/1-b: 'iki dönem ayrı ayrı olmak üzere, her bir dönem içerisinde' kaydı atlanmış"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "AD-HESAP", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[2, 3],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="ŞART",
z="O",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 74/A; Gümrük Yönetmeliği md. 23",
cek="Yönetimi kamu kurumlarına devredilen şirkette kesinleşmiş gümrük vergi-ceza, vergi ve sosyal güvenlik prim borcu bulunmaması koşulları aranmaz.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre, statü belgesi sahibi olan veya statü belgesi için başvuruda bulunan şirketin yönetiminin kamu kurumlarına devredilmesi durumunda, Gümrük Yönetmeliği'nde onaylanmış kişi statüsü için sayılan genel koşullardan hangisi aranmaz?"],
d="Kesinleşmiş gümrük vergisi ve ceza borcu, kesinleşmiş vergi borcu ve kesinleşmiş sosyal güvenlik prim borcu bulunmaması",
c=["Mali yapının yeminli mali müşavir tarafından düzenlenecek raporla olumlu görüşle sonuca bağlanmış olması",
   "Yönetim kurulu üyeleri ve temsil yetkisini haiz çalışanlar hakkında sayılan suçlardan ceza veya mahkumiyet kararı bulunmaması",
   "Vergi kaybına neden olan ihlaller nedeniyle düzenlenen ceza kararı sayısının beyanname sayısına oranının belirlenen sınırları aşmaması",
   "İhracatçılar için performans ve güvenilirliğin Türkiye İhracatçılar Meclisi veya ihracatçı birliklerince onaylanmış olması"],
sirali=False,
g="Tebliğ'e göre onaylanmış kişi statü belgesi sahibi olan veya statü belgesi için başvuruda bulunan şirket yönetiminin kamu kurumlarına devredilmesi durumunda, Gümrük Yönetmeliği'nde sayılan genel koşullardan yalnızca borca ilişkin üç koşul aranmaz: gümrük mevzuatı uyarınca kesinleşmiş vergi ve ceza borcu, vergi mevzuatı uyarınca kesinleşmiş vergi borcu ve ilgili mevzuat uyarınca kesinleşmiş sosyal güvenlik prim borcu bulunmaması. Yöneticiler hakkında ceza veya mahkumiyet kararı bulunmaması, ceza kararı oranları, ihracatçı birliği onayı ve yeminli mali müşavir raporu koşulları bu durumda da aranmaya devam eder. En güçlü çeldirici yeminli mali müşavir raporudur: mali yapıya ilişkin olduğu için borç koşullarıyla karıştırılır, ancak istisna kapsamında sayılmamıştır. Aynı üç borç koşulu, grup ihracatçısı veya grup ithalatçısı başvurularında grup imalatçılarınca da sağlanması gereken koşullardır. Bu nedenle doğru cevap 'Kesinleşmiş gümrük vergisi ve ceza borcu, kesinleşmiş vergi borcu ve kesinleşmiş sosyal güvenlik prim borcu bulunmaması' seçeneğidir. (MD OKS Tebliği 74/A; GY 23)",
kanit="4-OKSB.txt | şirket yönetiminin kamu kurumlarına devredilmesi durumunda Gümrük Yönetmeliğinin 23 üncü maddesinin birinci fıkrasının (d), (e) ve (f) bentlerinde sayılan koşullar aranmaz || 4-OKSB.txt | Gümrük mevzuatı uyarınca kesinleşmiş vergi ve ceza borcu bulunmaması || 4-OKSB.txt | Vergi mevzuatı uyarınca kesinleşmiş vergi borcu bulunmaması || 4-OKSB.txt | İlgili mevzuat uyarınca kesinleşmiş sosyal güvenlik prim borcu bulunmaması",
yuva=["GY 23/1-h: yeminli mali müşavir raporu (istisna dışında; aranmaya devam eder)",
      "GY 23/1-a: yöneticiler için ceza veya mahkumiyet kararı bulunmaması (istisna dışında)",
      "GY 23/1-b: ceza kararı sayısı oranı (istisna dışında)",
      "GY 23/1-g: ihracatçı birliği performans ve güvenilirlik onayı (istisna dışında)"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "İSTİSNA"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="ORAN-TUTAR",
z="K",
madde="Gümrük Yönetmeliği md. 24",
cek="Statünün dış ticaret performansında alternatif koşul: her dönem ithalat ve fiili ihracat toplamı, en az bir milyon dolar ihracat dahil, yedi milyon dolar.",
kok=["Gümrük Yönetmeliği'ne göre onaylanmış kişi statüsü için aranan dış ticaret performansına ilişkin özel koşulun ithalat ve fiili ihracat toplamı üzerinden sağlanmasında, on ikişer aylık iki dönemin her birinde gerçekleştirilen ithalat ve fiili ihracat toplamının, asgari bir milyon FOB/ABD doları fiili ihracat olmak üzere en az kaç milyon ABD doları tutarında olması gerekir?"],
d="7 milyon",
c=["2 milyon", "5 milyon", "10 milyon", "20 milyon"],
sirali=True,
siklar=["2 milyon", "5 milyon", "7 milyon", "10 milyon", "20 milyon"],
g="Gümrük Yönetmeliği'ne göre onaylanmış kişi statüsü için dış ticaret performansına ilişkin iki seçenekli özel koşuldan en az birinin sağlanması gerekir: ön inceleme sözleşmesinin yapıldığı ayın ilk gününden geriye dönük iki yıl içindeki on ikişer aylık dönemlerin her birinde asgari iki milyon FOB/ABD doları fiili ihracat yapılmış olması ya da her bir dönemde ithalat ve fiili ihracat toplamının, asgari bir milyon FOB/ABD doları fiili ihracat olmak üzere, yedi milyon ABD doları olması. Ayrıca ortalama en az otuz işçi istihdamı aranır. En güçlü çeldirici 2 milyondur: bu tutar yalnızca fiili ihracat üzerinden sağlanan ilk seçeneğe aittir. Beş ve yirmi milyon ABD doları, Tebliğ'de beyanın kontrol türüne ilişkin kolaylaştırmalar için aranan ihracat ve dış ticaret toplamı eşikleridir; on milyon ise yetkilendirilmiş yükümlü statüsüne ait bir ihracat eşiğidir. Bu nedenle doğru cevap '7 milyon' seçeneğidir. (MD GY 24)",
kanit="4-OKSB.txt | her bir dönem içerisinde gerçekleştirilen ithalat ve fiili ihracat toplamının asgari bir milyon FOB/ABD doları fiili ihracat olmak üzere yedi milyon ABD doları tutarında olması || 4-OKSB.txt | her bir dönem itibarıyla asgari iki milyon FOB/ABD doları tutarında fiili ihracat yapılmış olması",
yuva=["GY 24/1-a-1: yalnız fiili ihracat seçeneğinde her dönem asgari iki milyon FOB/ABD doları",
      "Tebliğ 42/A/1-b-1: kontrol türü kolaylaştırmasında herhangi bir dönemde beş milyon FOB/ABD doları fiili ihracat",
      "3-YYS.txt: YYS-I statüsünde istihdama alternatif asgari 10 milyon ABD doları ihracat",
      "Tebliğ 42/A/1-b-2: kontrol türü kolaylaştırmasında ithalat ve fiili ihracat toplamı yirmi milyon ABD doları"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="OKS-42A-ESIK",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- BAŞVURU VE ÖN İNCELEME ----------------
dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="ÖNERMELİ",
z="O",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 3, 5, 7",
cek="OK1 tespitini yalnız YGM yapar; olumlu rapor iki, olumsuz rapor bir nüsha teslim edilir; sahte belgeyi YGM yetkili bölge müdürlüğüne bildirir.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre statü belgesi başvurularının ön incelemesine ilişkin OK1 tespiti hakkında aşağıdaki ifadeler verilmiştir:",
     "I. OK1 tespiti, başvuru sahibiyle tespit sözleşmesi yapılması kaydıyla yetkilendirilmemiş bir gümrük müşavirince de yapılabilir.",
     "II. Statü belgesi başvurusunda bulunan kişilerce bir yetkilendirilmiş gümrük müşaviri ile OK1 tespiti için tespit sözleşmesi yapılmış olması gerekir.",
     "III. Olumlu tespit raporu, yetkilendirilmiş gümrük müşavirince kaşelenip imzalanarak başvuru sahibine iki nüsha hâlinde; olumsuz tespit raporu ise bir nüsha hâlinde teslim edilir.",
     "IV. Tespiti yapan yetkilendirilmiş gümrük müşaviri, kendisine ibraz edilen belgelerden birinin sahte olduğunu tespit ederse durumu yetkili bölge müdürlüğüne bildirmekle yükümlüdür.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II, III ve IV",
c=["I ve II", "II ve III", "I, II ve IV", "I, II, III ve IV"],
sirali=False,
g="Tebliğ'de OK1, onaylanmış kişi statü belgesi müracaatına ilişkin başvuru dosyalarının yetkilendirilmiş gümrük müşavirince gerçekleştirilecek ön incelemesi olarak tanımlanır; bu tespiti yetkilendirilmemiş bir gümrük müşaviri yapamaz (I yanlış). Statü belgesi başvurusunda bulunacak kişilerce bir yetkilendirilmiş gümrük müşaviriyle OK1 tespiti için tespit sözleşmesi yapılmış olması gerekir (II doğru). Olumlu tespit raporları yetki numarasını içeren kaşeyle kaşelenip imzalanarak başvuru sahibine iki nüsha, olumsuz tespit raporları bir nüsha hâlinde teslim edilir (III doğru). Tespiti yapan yetkilendirilmiş gümrük müşaviri, kendisine ibraz edilen belgelerden bir veya daha fazlasının sahte veya tahrif edilmiş olduğunu tespit ederse durumu yetkili bölge müdürlüğüne bildirmekle yükümlüdür (IV doğru). En güçlü çeldirici I'dir: 'her gümrük müşaviri bu tespiti yapabilir' önyargısı, tespit yetkisinin yalnızca yetkilendirilmiş gümrük müşavirine ait olduğunu gözden kaçırır. Bu nedenle doğru cevap 'II, III ve IV' seçeneğidir. (MD OKS Tebliği 3, 5, 7)",
kanit="4-OKSB.txt | OK1: Onaylanmış kişi statü belgesi müracaatına ilişkin başvuru dosyalarının yetkilendirilmiş gümrük müşavirince gerçekleştirilecek ön incelemesini || 4-OKSB.txt | Statü belgesi başvurusunda bulunan kişilerce bir YGM ile OK1 tespiti için tespit sözleşmesi yapılmış olması gerekir || 4-OKSB.txt | kaşelenip imzalanarak onaylanmış kişi statü belgesi başvurusunda bulunacak kişiye iki nüsha halinde teslim edilir || 4-OKSB.txt | Olumsuz tespit raporları onaylanmış kişi statü belgesi başvurusunda bulunacak kişiye bir nüsha halinde teslim edilir || 4-OKSB.txt | durumu yetkili bölge müdürlüğüne bildirmekle yükümlüdür",
yuva=["I ve II: yetkilendirilmemiş müşavirin de tespit yapabileceğini sanan (meslek yanlılığı), rapor ve bildirim hükümlerini bilmeyen aday",
      "II ve III: sahte belge bildirim yükümlülüğünü (Tebliğ 7/6) bilmeyen aday",
      "I, II ve IV: olumlu/olumsuz rapor nüsha sayısını karıştıran ve meslek önyargısına kapılan aday (Tebliğ 7/2-3)",
      "I, II, III ve IV: OK1 tespitinin YGM'ye özgü olduğunu atlayan aday (Tebliğ 3/1-j)"],
yakinlik="BİREBİR",
tuzak=["SAĞDUYU", "KOMŞU", "TERİM"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[3, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="YANLIŞ",
z="Z",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 6",
cek="OK1 için adli sicil ve vergi dairesi yazısı sözleşmeden geriye en geç iki ay, sosyal güvenlik borcu yoktur belgesi en geç bir ay içinde alınır.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre statü belgesi başvurularında OK1 tespiti için tespit sözleşmesi yapılmış yetkilendirilmiş gümrük müşavirine ibraz edilecek belgelere ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Kesinleşmiş sosyal güvenlik prim borcu bulunmadığını gösteren belge, tespit sözleşmesinin yapıldığı tarihten geriye dönük en geç iki ay içerisinde alınmış olmalıdır.",
c=["Sayılan suçlardan hüküm giyilmediğine dair adli sicil belgeleri asılları, tespit sözleşmesinin yapıldığı tarihten geriye dönük en geç iki ay içerisinde alınmış olmalıdır.",
   "Kesinleşmiş vergi borcu bulunmadığını gösteren vergi dairesi yazısı aslı, tespit sözleşmesinin yapıldığı tarihten geriye dönük en geç iki ay içerisinde alınmış olmalıdır.",
   "Sürekli olarak yurt dışında ikamet eden yabancı uyruklu kişiler için adli sicil belgesi yerine örneğine uygun taahhütname asılları ibraz edilir.",
   "Kendi adına veya dış ticaret sermaye şirketi, sektörel dış ticaret şirketi ya da grup ihracatçısı aracılığıyla hiç ihracat yapmayan kişilerden performans ve güvenilirlik formu aranmaz."],
sirali=False,
g="Tebliğ'e göre OK1 tespiti için yetkilendirilmiş gümrük müşavirine ibraz edilen belgelerde süre, tespit sözleşmesinin yapıldığı tarihten geriye doğru sayılır. Sayılan suçlardan hüküm giyilmediğine dair adli sicil belgeleri asılları ile bağlı bulunulan ve nakil gelinen vergi dairelerinden alınan kesinleşmiş vergi borcu bulunmadığına dair yazı asılları en geç iki ay içinde alınmış olmalıdır. Türkiye genelinde kesinleşmiş sosyal güvenlik prim borcu bulunmadığına ilişkin 'e-borcu yoktur belgesi' veya Sosyal Güvenlik Kurumu yazısı ise sözleşme tarihinden geriye dönük en geç bir ay içinde alınmış olmalıdır; iki ay yazan ifade yanlıştır. Sürekli olarak yurt dışında ikamet eden yabancı uyruklular için örneğe uygun taahhütname asılları verilir; kendi adına veya dış ticaret sermaye şirketi, sektörel dış ticaret şirketi ya da grup ihracatçısı aracılığıyla hiç ihracat yapmayanlardan performans ve güvenilirlik formu aranmaz. En güçlü tuzak, aynı listedeki adli sicil ve vergi yazısına ait iki aylık sürenin sosyal güvenlik belgesine taşınmasıdır. Bu nedenle doğru cevap 'Kesinleşmiş sosyal güvenlik prim borcu bulunmadığını gösteren belge, tespit sözleşmesinin yapıldığı tarihten geriye dönük en geç iki ay içerisinde alınmış olmalıdır.' seçeneğidir. (MD OKS Tebliği 6)",
kanit="4-OKSB.txt | OK1 tespiti için tespit sözleşmesi yapıldığı tarihten geriye dönük en geç iki ay içerisinde resmi kuruma verilmek üzere alınan adli sicil belgeleri asılları || 4-OKSB.txt | OK1 tespiti için tespit sözleşmesi yapıldığı tarihten geriye dönük en geç bir ay içerisinde Sosyal Güvenlik Kurumunun || 4-OKSB.txt | OK1 tespiti için tespit sözleşmesi yapıldığı tarihten geriye dönük en geç iki ay içerisinde alınan vergi mevzuatı gereğince kesinleşmiş vergi borcu bulunmadığını gösterir yazı aslı || 4-OKSB.txt | sürekli olarak yurtdışında ikamet eden yabancı uyruklular için || 4-OKSB.txt | Kendi adına veya DTSŞ, SDTŞ ya da grup ihracatçısı aracılığıyla hiç ihracat yapmayan kişilerin başvurularında birinci fıkranın (e) bendinde belirtilen belge aranmaz",
yuva=["Tebliğ 6/1-c: adli sicil belgeleri geriye dönük en geç iki ay (doğru ifade)",
      "Tebliğ 6/1-d: vergi dairesi yazısı geriye dönük en geç iki ay (doğru ifade)",
      "Tebliğ 6/1-c: yurt dışında sürekli ikamet eden yabancı uyruklular için taahhütname (doğru ifade)",
      "Tebliğ 6/9: hiç ihracat yapmayanlardan performans ve güvenilirlik formu aranmaz (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[2, 4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="SÜRE",
z="O",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 7, 9, 10, 12",
cek="Statü belgesi başvurusu, olumlu tespit raporunun düzenlenme tarihini izleyen beş iş günü içinde yetkili bölge müdürlüğüne yapılır; rapor sözleşmeden itibaren otuz günde düzenlenir.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre statü belgesi başvurusunun yetkili bölge müdürlüğüne yapılma süresi aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Olumlu tespit raporunun düzenlenme tarihini izleyen beş iş günü içinde",
c=["Tespit sözleşmesinin yapıldığı tarihi izleyen otuz gün içinde",
   "Tespit sözleşmesinin yapıldığı tarihi izleyen beş iş günü içinde",
   "Olumlu tespit raporunun düzenlenme tarihini izleyen on iş günü içinde",
   "Olumlu tespit raporunun başvuru sahibine teslim edildiği tarihi izleyen üç iş günü içinde"],
sirali=False,
g="Tebliğ'e göre başvurular, şahsen veya posta yoluyla, aranan belgelerle birlikte yetkili bölge müdürlüğüne olumlu tespit raporunun düzenlenme tarihini izleyen beş iş günü içinde yapılır; bu süre içinde yapılmayan başvurular reddedilir. Sürenin başlangıcı raporun düzenlenme tarihidir; raporun başvuru sahibine teslim tarihi veya tespit sözleşmesinin tarihi değildir. En güçlü çeldirici 'sözleşmenin yapıldığı tarihi izleyen otuz gün'dür: bu süre, yetkilendirilmiş gümrük müşavirinin OK1 tespitini rapora bağlaması için öngörülmüştür ve bu süreyi aşan tarihte düzenlenen rapor geçersizdir. On iş günü, götürü teminat talep edilmemiş başvurunun bölge müdürlüğünce incelenme süresidir; üç iş günü ise başvurudaki eksikliklerin tamamlanması için tanınan süredir. Bu nedenle doğru cevap 'Olumlu tespit raporunun düzenlenme tarihini izleyen beş iş günü içinde' seçeneğidir. (MD OKS Tebliği 7, 9, 10, 12)",
kanit="4-OKSB.txt | yetkili bölge müdürlüğüne olumlu tespit raporunun düzenlenme tarihini izleyen beş iş günü içerisinde yapılır || 4-OKSB.txt | OK1 tespit işleminin sözleşmenin yapıldığı tarihi izleyen otuz gün içerisinde YGM'ce olumlu veya olumsuz olarak rapora bağlanması zorunludur || 4-OKSB.txt | başvurunun genel evrak kaydına alınmasını takiben en geç on iş günü içinde incelenir || 4-OKSB.txt | eksikliklerin 3 işgünü içinde tamamlanması için başvuru sahibine e-posta ve yazı ile bildirimde bulunulur",
yuva=["Tebliğ 7/1: OK1 tespitinin rapora bağlanma süresi (sözleşmeyi izleyen otuz gün)",
      "Tebliğ 9/1: doğru süre, yanlış başlangıç (sözleşme tarihi değil raporun düzenlenme tarihi)",
      "Tebliğ 10/2-a: götürü teminat talep edilmeyen başvurunun inceleme süresi (on iş günü)",
      "Tebliğ 12/3: başvurudaki eksikliklerin tamamlanma süresi (üç iş günü)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU", "YAKIN-SAYI"],
duzey=["HATIRLAMA"],
profil=[1, 2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- STATÜ BELGESİ VE KAPSAMI ----------------
dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="SONUÇ",
z="O",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 12, 61, 62, 63",
cek="Adına YYS sertifikası düzenlenen statü sahibinin belgesi geri alınır; aynı durumda yeni başvuru reddedilir. İptal yalnız yanlış bilgi veya sahte belgede uygulanır.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre, onaylanmış kişi statü belgesi sahibi bir firma adına Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği uyarınca yetkilendirilmiş yükümlü sertifikası düzenlenmesi hâlinde, firmanın statü belgesi hakkında aşağıdakilerden hangisi uygulanır?"],
d="Statü belgesi geri alınır.",
c=["Statü belgesi iptal edilir.",
   "Statü belgesi, kesinleşmiş gümrük vergisi ve/veya ceza borcu ödenene kadar askıya alınır.",
   "Statü belgesi geri alınmaz; yalnızca belge kapsamındaki götürü teminat yetkisi geri alınır.",
   "Statü belgesi, yetkilendirilmiş yükümlü sertifikasıyla birlikte geçerlilik süresi sonuna kadar kullanılmaya devam edilir."],
sirali=False,
g="Tebliğ'e göre Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği uyarınca adlarına yetkilendirilmiş yükümlü sertifikası düzenlenmiş onaylanmış kişi statüsü sahibi kişilerin statü belgeleri geri alınır; iki statü birlikte sürdürülmez. Aynı nedenle, adına yetkilendirilmiş yükümlü sertifikası düzenlenmiş olduğu tespit edilen kişinin statü belgesi talebi de reddedilir. Statü belgesine ilişkin üç sonuç birbirinden ayrılmalıdır: askıya alma, gümrük işlemlerinden veya cezalarından doğan kamu alacağının süresinde ödenmemesinde borç ödenene kadar uygulanır; iptal, belgenin yanlış veya eksik bilgilere ya da sahte belgelere dayanılarak verildiğinin anlaşılmasında uygulanır; geri alma ise genel koşulların ortadan kalkması, belge sahibinin talebi ve yetkilendirilmiş yükümlü sertifikası düzenlenmesi hâllerinde uygulanır. En güçlü çeldirici 'iptal edilir' seçeneğidir: Gümrük Yönetmeliği'ne göre iptalde belge kapsamındaki yetkiler belgenin düzenlendiği tarih itibarıyla geçersiz sayılır ve bu ağır sonuç yalnızca yanlış bilgi veya sahte belge hâline özgüdür. Bu nedenle doğru cevap 'Statü belgesi geri alınır.' seçeneğidir. (MD OKS Tebliği 12, 61, 62, 63; GY 26)",
kanit="4-OKSB.txt | adlarına yetkilendirilmiş yükümlü sertifikası düzenlenmiş onaylanmış kişi statüsü sahibi kişilerin statü belgeleri geri alınır || 4-OKSB.txt | Yanlış veya eksik bilgilere veya sahte belgelere dayanılarak verildiği anlaşılan statü belgesi || 4-OKSB.txt | kesinleşmiş gümrük vergisi ve/veya ceza borcu ödenene kadar askıya alınır || 4-OKSB.txt | statü belgesi geri alınmaz; sadece söz konusu hak veya yetki",
yuva=["Tebliğ 63/1: iptal, yanlış veya eksik bilgi ya da sahte belge hâline özgü",
      "Tebliğ 61/1: askıya alma, kamu alacağının süresinde ödenmemesi hâline özgü",
      "Tebliğ 64/1: yalnızca bir hak veya yetkiye özgü koşul kaybedildiğinde belge değil o yetki geri alınır",
      "Sağduyu: iki statünün birlikte sürdürülebileceği varsayımı (Tebliğ 62/4 aksini düzenler)"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU", "SAĞDUYU"],
duzey=["HATIRLAMA"],
profil=[3, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2025/98",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="DOĞRU",
z="O",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 4",
cek="Statü belgesi kapsamındaki hak ve uygulamalardan bizzat belge sahibi yararlanır, başkalarına kullandırılamaz; götürü teminat ve diğer yetkiler talep ve koşula bağlıdır.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre statü belgesi kapsamında tanınan hak ve uygulamalara ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Statü belgesi kapsamında tanınan hak ve uygulamalardan yalnızca adına belge düzenlenen kişi yararlanabilir; bu hak ve uygulamalar başkalarına kullandırılamaz.",
c=["Götürü teminat yetkisi, talep aranmaksızın bütün statü belgesi sahiplerine belgenin düzenlenmesiyle birlikte tanınır.",
   "Onaylanmış ihracatçı yetkisi, statü belgesinin geçerlilik süresiyle sınırlı olmaksızın süresiz olarak tanınır.",
   "Daha az muayeneyi sağlayan beyanın kontrol türüne ilişkin kolaylaştırmalar, ihracat tutarı ve işçi sayısı koşulları aranmaksızın bütün statü belgesi sahiplerinin eşyasına uygulanabilir.",
   "Eksik beyan usulünden ve kısmi teminat uygulamasından yalnızca statü belgesinin düzenlenmesini takip eden ilk on iki ay içinde yararlanılabilir."],
sirali=False,
g="Tebliğ'e göre adına statü belgesi düzenlenen gerçek ve tüzel kişilere bu belge kapsamında tanınan hak ve uygulamalardan bizzat bu kişilerce yararlanılır; bu haklardan yararlanma yetkisi başkalarına kullandırılamaz. Statü belgesi sahipleri, belgelerinin geçerlilik süresi boyunca eksik beyan usulü, kısmi teminat uygulaması ve “1000” rejim kodlu ihracat beyannamelerine ilişkin kontrol türü kolaylaştırmasından yararlanabilir; bu imkân ilk on iki ayla sınırlı değildir. Götürü teminat yetkisi ancak talep edilmesi hâlinde tanınabilir; onaylanmış ihracatçı yetkisi de talep hâlinde ve statü belgesinin geçerlilik süresi içinde tanınır, süresiz değildir. Daha az muayeneyi sağlayan kolaylaştırmalardan ise imalatçılık, ihracat veya dış ticaret tutarı ve işçi sayısı koşullarını sağlayanlara talepleri hâlinde izin verilebilir. En güçlü çeldirici götürü teminata ilişkin seçenektir: götürü teminat statü belgesiyle kendiliğinden değil, talep üzerine tanınır. Bu nedenle doğru cevap 'Statü belgesi kapsamında tanınan hak ve uygulamalardan yalnızca adına belge düzenlenen kişi yararlanabilir; bu hak ve uygulamalar başkalarına kullandırılamaz.' seçeneğidir. (MD OKS Tebliği 4, 42/A, 54)",
kanit="4-OKSB.txt | Adına statü belgesi düzenlenen gerçek ve tüzel kişilere bu belge kapsamında tanınan hak ve uygulamalardan bizzat bu kişilerce yararlanılır. Söz konusu haklar ile uygulamalardan yararlanma yetkisi başkalarına kullandırılamaz || 4-OKSB.txt | Onaylanmış kişi statüsü sahiplerine, talep etmeleri halinde, adlarına düzenlenen statü belgesi kapsamında belgenin geçerlilik süresi boyunca 31 ila 42 nci maddeler kapsamında götürü teminat yetkisi tanınabilir || 4-OKSB.txt | belgelerinin geçerlilik süresi boyunca eksik beyan usulü, kısmi teminat uygulaması ile 42/A maddesinin ikinci fıkrasında yer alan beyanın kontrol türüne ilişkin kolaylaştırmadan yararlanılabilir || 4-OKSB.txt | talep etmeleri halinde, statü belgelerinin geçerlilik süresi içinde, onaylanmış ihracatçı yetkisi verilir",
yuva=["Tebliğ 4/3: götürü teminat yetkisi talep hâlinde tanınabilir",
      "Tebliğ 4/5 ve 54/2: onaylanmış ihracatçı yetkisi belgenin geçerlilik süresi içinde/boyunca tanınır",
      "Tebliğ 4/4 ve 42/A/1: imalatçılık, ihracat tutarı ve en az yüz işçi koşulları",
      "Tebliğ 4/2 (geçerlilik süresi boyunca) ile GY 26/2'deki on iki aylık dönemin karıştırılması"],
yakinlik="PARAFRAZ",
tuzak=["ŞART", "KOMŞU", "MUTLAK"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2022/94; 2025/98",
kapsamli=False,
),

# ---------------- EKSİK BEYAN USULÜ ----------------
dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="KAPSAM_DIŞI",
z="K",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 17",
cek="Eksik beyana konu olabilecek belgeler kapalı listedir: fatura, A.TR, menşe ispat belgeleri, navlun makbuzu ve sigorta poliçesi, işlenmiş tarım ürünleri analiz raporu.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre statü belgesi sahiplerinin eksik beyan usulü kapsamında beyannameye eklemeksizin beyanda bulunabilecekleri belgeler arasında aşağıdakilerden hangisi yer almaz?"],
d="Her kapta ne miktar eşya bulunduğunu gösteren çeki listesi",
c=["A.TR dolaşım belgesi",
   "Menşe ispat belgeleri",
   "Ödeme şekli gereği ibrazı gereken navlun makbuzu ve sigorta poliçesi",
   "İşlenmiş tarım ürünlerinin serbest dolaşıma sokulması hâlinde ibrazı gereken analiz sonuç raporu"],
sirali=False,
g="Tebliğ'e göre statü belgesi sahipleri, Gümrük Yönetmeliği'nin eksik beyana ilişkin koşulları saklı kalmak kaydıyla şu belgelerin bir ya da daha fazlasını beyannameye eklemeksizin beyanda bulunabilir: fatura, A.TR dolaşım belgesi, menşe ispat belgeleri, ödeme şekli gereği ibrazı gereken navlun makbuzu ve sigorta poliçesi, işlenmiş tarım ürünlerinin serbest dolaşıma sokulması hâlinde ibrazı gereken işlenmiş tarım ürünleri analiz sonuç raporu. Liste kapalıdır; Gümrük Yönetmeliği'nde tanımlanan ve her kapta ne miktar eşya bulunduğunu gösteren çeki listesi bu listede yer almaz. En güçlü çeldirici işlenmiş tarım ürünleri analiz sonuç raporudur: ticari bir belge olmadığı için listeye yabancı sanılır, oysa açıkça sayılmıştır. Bu nedenle doğru cevap 'Her kapta ne miktar eşya bulunduğunu gösteren çeki listesi' seçeneğidir. (MD OKS Tebliği 17; GY 117)",
kanit="4-OKSB.txt | aşağıda sayılan belgelerin bir ya da daha fazlası beyannameye eklenmeksizin beyanda bulunulabilir || 4-OKSB.txt | A.TR dolaşım belgesi || 4-OKSB.txt | Ödeme şekli gereği ibrazı gereken navlun makbuzu ve sigorta poliçesi || 4-OKSB.txt | İşlenmiş tarım ürünlerinin serbest dolaşıma sokulması halinde ibrazı gereken işlenmiş tarım ürünleri analiz sonuç raporu || 17-BEYAN.txt | her kapta ne miktar eşya bulunduğunu göstermek amacıyla düzenlenen bir belgedir",
yuva=["Tebliğ 17/1-b: listede",
      "Tebliğ 17/1-c: listede",
      "Tebliğ 17/1-ç: listede",
      "Tebliğ 17/1-d: listede"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="ÖNERMELİ",
z="O",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 18, 23",
cek="Eksik belgeler tescilden itibaren bir ayda ibraz edilir; indirimli oran belgesine talep üzerine en çok üç ay, kıymette daha uzun ek süre verilebilir.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre statü belgesi sahiplerinin eksik beyan usulünden yararlanması hâlinde eksik belgelerin tamamlanma süresine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Eksik belgelerin, beyannamenin tescil tarihinden itibaren bir ay içinde beyannamenin tescil edildiği gümrük müdürlüğüne ibraz edilmesi gerekir.",
     "II. İndirimli veya sıfır oranında gümrük vergisi uygulanması için gereken belgelerin eksikliğinde, beyan sahibinin talebi üzerine gümrük müdürlüğünce altı ayı geçmeyecek şekilde ek süre verilebilir.",
     "III. Tamamlanacak eksik beyanın gümrük kıymetiyle ilgili olması ve daha uzun süre gerektiğinin kanıtlanması hâlinde gümrük müdürlüğünce üç aydan uzun bir ek süre belirlenebilir.",
     "IV. Gümrük müdürlükleri, ek süreler dâhil süresi içinde ibraz edilmeyen belgelere ilişkin beyannameleri her ayın son beş iş günü içinde sorgulama yaparak tespit eder.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve III",
c=["I ve II", "II ve IV", "I, II ve III", "I, III ve IV"],
sirali=False,
g="Tebliğ'e göre eksik beyana konu belgelerin, gümrük beyannamesinin tescil tarihinden itibaren bir ay içinde beyannamenin tescil edildiği gümrük müdürlüğüne ibraz edilmesi gerekir (I doğru). İndirimli veya sıfır oranında gümrük vergisi uygulanması için gereken belgelerin eksikliğinde, bu oranların uygulanacağı konusunda yeterli neden bulunması koşuluyla, bir aylık süre içinde beyan sahibinin talebi üzerine gümrük müdürlüğünce verilebilecek ek süre üç ayı geçemez; altı ay yazılması yanlıştır (II yanlış). Tamamlanacak eksik beyanın gümrük kıymetiyle ilgili olması ve beyanın tamamlanmasının daha uzun süre gerektirdiğinin kanıtlanması hâlinde gümrük müdürlüğünce üç aydan uzun bir ek süre belirlenebilir (III doğru). Gümrük müdürlükleri, süresinde ibraz edilmemiş BS-1 kodlu beyannameleri her ayın ilk beş iş günü içinde BİLGE sisteminde sorgulama yaparak tespit eder; 'son beş iş günü' yanlıştır (IV yanlış). En güçlü çeldirici IV'tür: gün sayısı doğrudur, ayın hangi dilimi olduğu değiştirilmiştir. Bu nedenle doğru cevap 'I ve III' seçeneğidir. (MD OKS Tebliği 18, 23)",
kanit="4-OKSB.txt | gümrük beyannamesinin tescil tarihinden itibaren bir ay içinde gümrük beyannamesinin tescil edildiği gümrük müdürlüğüne ibraz edilmeleri gerekir || 4-OKSB.txt | beyan sahibinin talebi üzerine gümrük müdürlüğünce söz konusu belgenin ibrazı için üç ayı geçmeyecek şekilde ek süre verilebilir || 4-OKSB.txt | Tamamlanacak eksik beyanın gümrük kıymeti ile ilgili olması ve beyanın tamamlanmasının daha uzun bir süre gerektirdiğinin kanıtlanması durumunda, gümrük müdürlüğünce üç aydan uzun bir ek süre belirlenebilir || 4-OKSB.txt | Gümrük müdürlüklerince her ayın ilk beş iş günü içinde BİLGE sisteminde sorgulama yapılarak",
yuva=["I ve II: ek süre üst sınırındaki üç ay ile altı ay farkını bilmeyen aday (Tebliğ 18/2)",
      "II ve IV: tescilden itibaren bir aylık temel süreyi ve kıymet istisnasını bilmeyen aday (Tebliğ 18/1, 18/3)",
      "I, II ve III: altı ay değişikliğini fark etmeyen aday (Tebliğ 24/3'teki altı aylık askı süresiyle karışıklık)",
      "I, III ve IV: aylık sorgulamanın ayın ilk beş iş gününde yapıldığını bilmeyen aday (Tebliğ 23/1)"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "SAYI", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="OLAY",
z="Z",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 24, 25",
cek="Aynı gün tescilli birden çok beyannamede eksik belge süresinde tamamlanmazsa her beyanname için ceza uygulanır, ancak kişi bir kez ibraz etmemiş sayılır.",
kok=["Onaylanmış kişi statü belgesi sahibi (M) firmasına ilişkin bilgiler şöyledir:",
     "- Firma, statü belgesinin geçerlilik süresi içinde daha önce bir kez eksik belgeleri ek süreler dâhil süresi içinde ibraz etmemiş; uyarılmış ve hakkında usulsüzlük cezası uygulanmıştır.",
     "- Firma daha sonra aynı gün tescil ettirdiği üç ithalat beyannamesinde eksik beyan usulünden yararlanmış ve bu üç beyannameye ait eksik belgeleri de ek süreler dâhil süresi içinde ibraz etmemiştir.",
     "Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre eksik beyanda bulunma yetkisinin askıya alınmasına ilişkin hükümler çerçevesinde (M) firması hakkında aşağıdakilerden hangisi doğrudur?"],
d="Üç beyannamenin her biri için usulsüzlük cezası uygulanır; firma bu beyannameler için bir kez süresi içinde ibraz etmemiş sayılır.",
c=["Üç beyannamenin her biri için usulsüzlük cezası uygulanır; firma süresi içinde ibraz etmemeyi üçüncü kez tekrarlamış sayıldığından eksik beyanda bulunma yetkisi altı ay süreyle askıya alınır.",
   "Aynı gün tescil edilen beyannameler için tek bir usulsüzlük cezası uygulanır; firma bir kez süresi içinde ibraz etmemiş sayılır.",
   "Firmanın eksik beyanda bulunma yetkisi, statü belgesinin geçerlilik süresi sonuna kadar geri alınır.",
   "Firmanın eksik beyanda bulunma yetkisi bir ay süreyle askıya alınır."],
sirali=False,
g="Tebliğ'e göre eksik belgeleri ek süreler dâhil süresi içinde ibraz etmeyen statü belgesi sahibi uyarılır ve hakkında Gümrük Kanunu'nun 241 inci maddesinin birinci fıkrasındaki usulsüzlük cezası uygulanır; geçerlilik süresi içinde üçüncü kez süresinde ibraz etmeyenin eksik beyanda bulunma yetkisi, eksik belgelerin tamamlanmasını müteakip altı ay süreyle askıya alınır. Vakada saklı istisna, üç beyannamenin aynı gün tescil edilmiş olmasıdır: aynı gün içinde tescil edilmiş birden fazla beyannameye ilişkin eksik belgelerin süresinde tamamlanmaması hâlinde her bir beyanname için usulsüzlük cezası uygulanır, ancak kişi bir kez süresi içinde ibraz etmemiş sayılır. Böylece (M) firmasının ihlal sayısı ikidir; üçüncü ihlal gerçekleşmediğinden altı aylık askı uygulanmaz (firma yalnızca eksik belgeler tamamlanıncaya kadar eksik beyan yetkisinden yararlanamaz). En güçlü çeldirici, üç beyannameyi üç ayrı ihlal sayıp altı aylık askıya alma sonucuna varan seçenektir. Geçerlilik süresi sonuna kadar geri alma, askı süresi bittikten sonra ihlalin tekrarına; bir aylık askı ise mavi hat ihlallerine özgüdür. Bu nedenle doğru cevap 'Üç beyannamenin her biri için usulsüzlük cezası uygulanır; firma bu beyannameler için bir kez süresi içinde ibraz etmemiş sayılır.' seçeneğidir. (MD OKS Tebliği 24, 25, 52)",
kanit="4-OKSB.txt | aynı gün içinde tescil edilmiş birden fazla gümrük beyannamesine ilişkin eksik belge veya belgelerin süresi içinde tamamlanmaması durumunda, her bir beyanname için Gümrük Kanununun 241/1 inci maddesi tatbik edilir ancak kişi bir kez süresi içinde eksik belge veya belgeleri ibraz etmemiş sayılır || 4-OKSB.txt | süresi içinde üçüncü kez ibraz etmeyen statü belgesi sahibi kişiler hakkında bir ve ikinci fıkralar uyarınca işlem yapılır ve eksik belge veya belgelerin tamamlamasını müteakip, statü belgesi kapsamında sahip oldukları eksik beyanda bulunma yetkisi, altı ay süre ile askıya alınır || 4-OKSB.txt | Süresi içinde ibraz edilmeyen eksik belge veya belgeler tamamlanıncaya kadar statü belgesi sahibinin eksik beyanda bulunma yetkisinden yararlanmasına izin verilmez",
yuva=["Tebliğ 24/3: üçüncü kez ibraz etmemede altı ay askı (aynı gün kuralı atlanmış)",
      "Tebliğ 24/4 ters okunmuş: aynı gün kuralı cezayı değil ihlal sayısını tekleştirir; GY 23/2'deki 'aynı beyanname için birden fazla ceza kararı bir sayılır' kuralıyla karışıklık",
      "Tebliğ 25/1: askı süresi bittikten sonra ihlalin tekrarında geçerlilik süresi sonuna kadar geri alma",
      "Tebliğ 52/7: mavi hat ihlallerinde bir ay askı"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "KOMŞU", "SAYI"],
duzey=["UYGULAMA"],
profil=[2, 3],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- KISMİ TEMİNAT ----------------
dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="ÖNERMELİ",
z="O",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 26, 27, 29, 30",
cek="Kısmi teminat: antrepo, GKAİ ve geçici ithalatta talep hâlinde vergilerin yüzde onu; ÖTV (I) listesi hariç; DİR-HİR kararları saklı; ödememe tekrarında geri alınır.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre statü belgesi sahiplerine tanınan kısmi teminat uygulamasına ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Gümrük antrepo, gümrük kontrolü altında işleme ve geçici ithalat rejimlerine tabi tutulan eşya için teminat alınması öngörülen durumlarda, statü belgesi sahiplerinden talep etmeleri hâlinde ithalat vergilerinin yüzde onu oranında teminat alınır.",
     "II. Özel Tüketim Vergisi Kanunu ekindeki (I) sayılı listede yer alan eşyaya ilişkin özel tüketim vergisi için, Bakanlıkça belirlenecek hâller saklı kalmak kaydıyla, kısmi teminat uygulamasından yararlanılamaz.",
     "III. Dâhilde işleme ve hariçte işleme rejimlerinde, bu rejimlere ilişkin kararlarla belirlenmiş teminat hükümlerine bakılmaksızın yüzde on oranında kısmi teminat uygulanır.",
     "IV. Ekonomik etkili gümrük rejimlerine ilişkin ihlaller nedeniyle ödenmesi gereken gümrük vergileri, faiz ve para cezasının tamamını tebliğ edilen ödeme süresi içinde ödememe ihlalinin, statü belgesinin geçerlilik süresi içinde ikinci kez tekrarı hâlinde kısmi teminat yetkisi geçerlilik süresi sonuna kadar geri alınır.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, II ve IV",
c=["I ve II", "I ve III", "II, III ve IV", "I, II, III ve IV"],
sirali=False,
g="Tebliğ'e göre gümrük antrepo, gümrük kontrolü altında işleme ve geçici ithalat rejimlerine tabi tutulan eşya için teminat alınması öngörülen durumlarda statü belgesi sahiplerinden, talep etmeleri hâlinde, ithalat vergilerinin yüzde onu oranında teminat alınır (I doğru). Özel Tüketim Vergisi Kanunu ekindeki (I) sayılı listedeki eşyaya ilişkin özel tüketim vergisi için, Bakanlıkça belirlenecek hâller saklı kalmak kaydıyla kısmi teminattan yararlanılamaz (II doğru). Dâhilde işleme ve hariçte işleme rejimlerine ilişkin kararlarla belirlenmiş teminat uygulamaları saklıdır; bu rejimlerde kısmi teminat hükmü onların yerine geçmez (III yanlış). Ekonomik etkili gümrük rejimlerine ilişkin ihlaller nedeniyle ödenmesi gereken gümrük vergileri, faiz ve para cezasının tamamının tebliğ edilen süre içinde ödenmemesi ihlalinin geçerlilik süresi içinde ikinci kez tekrarı hâlinde kısmi teminat yetkisi statü belgesinin geçerlilik süresi sonuna kadar geri alınır (IV doğru). En güçlü çeldirici III'tür: yüzde on oranı ekonomik etkili rejimlerin tamamına genellenirse dâhilde ve hariçte işlemenin kendi teminat düzenlemesi gözden kaçar. Bu nedenle doğru cevap 'I, II ve IV' seçeneğidir. (MD OKS Tebliği 26, 27, 29, 30)",
kanit="4-OKSB.txt | Gümrük antrepo, gümrük kontrolü altında işleme ve geçici ithalat rejimlerine tabi tutulan eşya için teminat alınması öngörülen durumlarda, statü belgesi sahibi kişilerden, talep etmeleri halinde, ithalat vergilerinin yüzde onu oranında teminat alınır || 4-OKSB.txt | Dâhilde işleme ve hariçte işleme rejimleri ile ilgili usul ve esaslar hakkında çıkarılan bakanlar kurulu kararları ile belirlenmiş teminat uygulamaları hükümleri saklıdır || 4-OKSB.txt | Bakanlıkça belirlenecek haller saklı kalmak kaydıyla, kısmi teminat uygulamasından yararlanılamaz || 4-OKSB.txt | ihlalin statü belgesinin geçerlilik süresi içerisinde ikinci kez tekrarı halinde, kişinin kısmi teminat uygulamasından yararlanma yetkisi statü belgesinin geçerlilik süresi sonuna kadar geri alınır",
yuva=["I ve II: IV'teki geri alma hükmünü (Tebliğ 30/1) bilmeyen aday",
      "I ve III: kısmi teminatı tüm ekonomik etkili rejimlere genelleyen, ÖTV (I) istisnasını bilmeyen aday",
      "II, III ve IV: yüzde on oranını veya rejim listesini (Tebliğ 26/1) yanlış bilen aday",
      "I, II, III ve IV: dâhilde ve hariçte işlemeye ilişkin teminat hükümlerinin saklı tutulduğunu bilmeyen aday (Tebliğ 26/2)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERSİNE"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- BEYANIN KONTROL TÜRÜ VE MAVİ HAT ----------------
dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="DOĞRU",
z="Z",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 42/A; Gümrük Yönetmeliği md. 24",
cek="Daha az muayene izni: imalatçılık, herhangi bir dönemde beş milyon dolar ihracat veya yirmi milyon dış ticaret ve ortalama yüz işçi.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre statü belgesi sahiplerine ait ithalat ve ihracat eşyasının daha az muayeneye tabi tutulabilmesini sağlayan, beyanın kontrol türüne ilişkin kolaylaştırmalardan yararlanma koşullarıyla ilgili aşağıdakilerden hangisi doğrudur?"],
d="Dış ticaret tutarına ilişkin koşullardan biri, izin başvurusu tarihinden geriye dönük iki yıl içindeki on ikişer aylık dönemlerden herhangi birinde asgari beş milyon FOB/ABD doları tutarında fiili ihracat yapılmış olmasıdır.",
c=["İmalatçı olma koşulu, dış ticaret sermaye şirketleri ve sektörel dış ticaret şirketleri dâhil bütün statü belgesi sahiplerinden aranır.",
   "İzin başvurusu tarihinden geriye dönük bir yıl içinde ortalama en az otuz işçi istihdam ediliyor olması yeterlidir.",
   "Dış ticaret tutarına ilişkin diğer koşul, iki dönemin her birinde ayrı ayrı ithalat ve fiili ihracat toplamının asgari yedi milyon ABD doları olmasıdır.",
   "Koşulları sağlayan statü belgesi sahiplerine ait beyannamelerde gümrük idareleri, belirli riskleri dikkate alarak bu kolaylaştırmaların aksi yönünde işlem yapamaz."],
sirali=False,
g="Tebliğ'e göre beyanın kontrol türüne ilişkin kolaylaştırmalardan yararlanacak statü belgesi sahibinin şu koşulları birlikte sağlaması gerekir: dış ticaret sermaye şirketleri, sektörel dış ticaret şirketleri, grup ihracatçıları, grup ithalatçıları, Ar-Ge merkezi belgesine sahip kişiler ile bakım onarım faaliyeti yürüten ticari hava taşımacılığı şirketleri hariç imalatçı olmak; yetkili bölge müdürlüğüne başvuru tarihinden geriye dönük iki yıl içinde on ikişer aylık dönemlerden herhangi birinde asgari beş milyon FOB/ABD doları fiili ihracat ya da asgari yirmi milyon ABD doları ithalat ve fiili ihracat toplamına ulaşmak; başvuru tarihinden geriye dönük bir yıl içinde ortalama en az yüz işçi istihdam etmek. Gümrük idareleri belirli riskleri veya mevzuattaki yükümlülükleri dikkate alarak bu kolaylaştırmaların aksi yönünde işlem yapabilir. En güçlü çeldiriciler onaylanmış kişi statüsünün kendi özel koşullarından taşınmıştır: 'her bir dönemde' yedi milyon ABD doları ve ortalama otuz işçi statü için aranır; kolaylaştırmada ise 'herhangi bir dönemde' beş milyon dolar ihracat veya yirmi milyon dolar toplam ile ortalama yüz işçi aranır. Bu nedenle doğru cevap 'Dış ticaret tutarına ilişkin koşullardan biri, izin başvurusu tarihinden geriye dönük iki yıl içindeki on ikişer aylık dönemlerden herhangi birinde asgari beş milyon FOB/ABD doları tutarında fiili ihracat yapılmış olmasıdır.' seçeneğidir. (MD OKS Tebliği 42/A; GY 24)",
kanit="4-OKSB.txt | Yetkili bölge müdürlüğüne bu izin için başvuru yapıldığı tarihten geriye dönük iki yıl içerisinde, on ikişer aylık iki dönem ayrı ayrı olmak üzere, herhangi bir dönem içerisinde asgari beş milyon FOB/ABD doları tutarında fiili ihracat yapılmış olması || 4-OKSB.txt | bu izin için başvuru yapıldığı tarihten geriye dönük bir yıl içinde ortalama en az yüz işçi istihdam ediyor olması gerekir || 4-OKSB.txt | Ar-Ge merkezi belgesine sahip kişiler ile bakım onarım faaliyeti yürüten ticari hava taşımacılığı şirketleri hariç imalatçı olmak || 4-OKSB.txt | Gümrük idarelerinin belirli riskleri ya da ilgili mevzuatta yer alan yükümlülükleri dikkate alarak birinci, ikinci ve üçüncü fıkraların aksi yönünde işlem yapmaları mümkündür",
yuva=["Tebliğ 42/A/1-a: imalatçılık koşulundan DTSŞ ve SDTŞ hariç tutulmuştur",
      "GY 24/1-b: onaylanmış kişi statüsü için ortalama en az otuz işçi (kolaylaştırmada yüz)",
      "GY 24/1-a-2: statüde her bir dönemde yedi milyon ABD doları (kolaylaştırmada herhangi bir dönemde yirmi milyon)",
      "Tebliğ 42/A/4: gümrük idarelerinin aksi yönde işlem yapması mümkündür"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "YAKIN-SAYI", "TERSİNE"],
duzey=["AYIRT"],
profil=[1, 2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="OKS-42A-ESIK",
guncellik="",
cikmis="2022/94",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="YANLIŞ",
z="O",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 42/A, 43, 44, 45",
cek="“1000” kodlu ihracat beyannameleri tüm statü sahiplerinde, diğer kodlular yalnız kontrol türü kolaylaştırması koşullarını sağlayanlarda risk analiziyle mavi hatta işlem görebilir.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre mavi hat uygulamasına ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="“1000” dışında kalan rejim kodlu ihracat beyannameleri, ek bir koşul aranmaksızın bütün statü belgesi sahipleri için risk analizi sonuçlarına göre mavi hatta işlem görebilir.",
c=["Statü belgesi sahiplerine ait “1000” rejim kodlu ihracat beyannameleri, yapılacak risk analizi sonuçlarına göre mavi hatta işlem görebilir.",
   "Kap, ambalaj, palet ve benzeri eşya haricinde, ilgili rejim hükümlerine göre ayniyat tespiti yapılması gereken eşyaya ilişkin beyannameler mavi hatta işlem görmez.",
   "Mavi hatta işlem gören eşyaya ilişkin beyanın kontrolü, eşyanın çıkış işlemlerinin tamamlanmasından sonra yapılır.",
   "Mavi hatta işlem görmüş beyanname kapsamı eşyaya ilişkin ihracat vergilerinin, statü belgesi sahibinin banka hesabından elektronik ortamda ödenmesi zorunludur."],
sirali=False,
g="Tebliğ'e göre statü belgesi sahiplerine ait “1000” rejim kodlu ihracat beyannameleri risk analizi sonuçlarına göre mavi hatta işlem görebilir. “1000” dışında kalan rejim kodlu ihracat beyannameleri ise yalnızca imalatçılık, dış ticaret tutarı ve işçi sayısı koşullarını sağlayan statü belgesi sahipleri adına tescil edilmişse risk analizine göre mavi hatta işlem görebilir; ek koşul aranmadığını söyleyen ifade yanlıştır. Mavi hat, onaylanmış kişilerce yalnızca ihracat beyannamelerinde yararlanılan, eşyanın çıkış işlemleri tamamlanmadan önce belge kontrolüne veya muayeneye tabi tutulmadığı hattır; beyanın kontrolü çıkıştan sonra yapılır. Kap, ambalaj, palet ve benzeri eşya haricinde ayniyat tespiti gereken eşyanın beyannamesi mavi hatta işlem görmez; tahakkuk eden ihracat vergilerinin statü belgesi sahibinin banka hesabından elektronik ortamda ödenmesi zorunludur. En güçlü tuzak, “1000” kodlu beyannamelere tanınan genel imkânın diğer rejim kodlarına taşınmasıdır. Bu nedenle doğru cevap '“1000” dışında kalan rejim kodlu ihracat beyannameleri, ek bir koşul aranmaksızın bütün statü belgesi sahipleri için risk analizi sonuçlarına göre mavi hatta işlem görebilir.' seçeneğidir. (MD OKS Tebliği 42/A, 43, 44, 45)",
kanit="4-OKSB.txt | rejim kodlu ihracat beyannameleri yapılacak risk analizi sonuçlarına göre mavi hatta işlem görebilir || 4-OKSB.txt | Birinci fıkrada belirtilen koşulları sağlayan statü belgesi sahipleri adına tescil edilmiş olan || 4-OKSB.txt | kap, ambalaj, palet ve benzeri eşya haricinde ilgili rejim hükümlerine göre ayniyat tespiti yapılması gereken eşyaya ilişkin gümrük beyannameleri mavi hatta işlem görmez || 4-OKSB.txt | Mavi hatta işlem gören eşyaya ilişkin beyanın kontrolü eşyanın çıkış işlemlerinin tamamlanmasından sonra yapılır || 4-OKSB.txt | onaylanmış kişi statü belgesine sahip kişinin banka hesabından elektronik ortamda",
yuva=["Tebliğ 42/A/2: doğru ifade",
      "Tebliğ 44/1: doğru ifade",
      "Tebliğ 43/1: doğru ifade",
      "Tebliğ 45/1: doğru ifade"],
yakinlik="BİREBİR",
tuzak=["ŞART", "KOMŞU", "MUTLAK"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2022/95; 2023/52",
kapsamli=False,
),

# ---------------- ONAYLANMIŞ İHRACATÇI ----------------
dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="TANIM",
z="K",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 3, 17, 54",
cek="Onaylanmış ihracatçı yetkisi: basitleştirilmiş işlem kapsamında A.TR dolaşım belgesini gümrüğe ibraz etmeden düzenleme ve vize etme yetkisi; menşe ispat belgesini kapsamaz.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre statü belgesi sahiplerine talepleri hâlinde tanınabilen “onaylanmış ihracatçı yetkisi” aşağıdakilerden hangisini ifade eder?"],
d="Basitleştirilmiş işlem kapsamında A.TR dolaşım belgesi düzenleme ve vize etme yetkisini",
c=["Basitleştirilmiş işlem kapsamında menşe ispat belgesi düzenleme ve vize etme yetkisini",
   "İhracat beyannamesinin, eşyanın çıkış işlemleri tamamlanmadan önce belge kontrolüne veya muayeneye tabi tutulmadığı hatta işlem görmesini",
   "Belirlenmiş tutardaki teminatın, her işlem için ayrı ayrı teminat verilmeksizin bir yıl süreyle kullanılabilmesini",
   "Fatura ve menşe ispat belgeleri gibi belgeler beyannameye eklenmeksizin beyanda bulunulabilmesini"],
sirali=False,
g="Tebliğ'e göre onaylanmış ihracatçı yetkisi, Türkiye ile Avrupa Topluluğu arasında oluşturulan Gümrük Birliği'nin uygulanmasına ilişkin Karar çerçevesinde basitleştirilmiş işlem kapsamında A.TR düzenleme ve vize etme yetkisidir. Bu yetki, Kararın genel hükümlerine bir istisna olarak A.TR dolaşım belgesinin onaylanma ve vize işlemi için gümrük idarelerine ibraz edilme zorunluluğu olmadan düzenlenebilmesini ifade eder. Yetki A.TR dolaşım belgesine özgüdür: Tebliğ, eksik beyan listesinde A.TR dolaşım belgesini menşe ispat belgelerinden ayrı sayar; bu nedenle menşe ispat belgesi düzenleme yetkisini söyleyen seçenek en güçlü çeldiricidir. Diğer seçenekler sırasıyla mavi hat, götürü teminat ve eksik beyan usulünün tanımlarıdır. Bu nedenle doğru cevap 'Basitleştirilmiş işlem kapsamında A.TR dolaşım belgesi düzenleme ve vize etme yetkisini' seçeneğidir. (MD OKS Tebliği 3, 17, 54)",
kanit="4-OKSB.txt | Onaylanmış ihracatçı yetkisi: Karar çerçevesinde basitleştirilmiş işlem kapsamında A.TR düzenleme ve vize etme yetkisini || 4-OKSB.txt | Kararın genel hükümlerine bir istisna olarak, A.TR dolaşım belgesinin Bakanlıkça yetki verilen kişi ve kuruluş tarafından onaylanma ve vize işlemi için gümrük idarelerine ibraz edilme zorunluluğu olmadan düzenlenebilmesini ifade eder || 4-OKSB.txt | Menşe ispat belgeleri",
yuva=["Tebliğ 17/1-c: menşe ispat belgeleri A.TR dolaşım belgesinden ayrı sayılmıştır (statü belgesi ↔ menşe belgesi)",
      "Tebliğ 3/1-i ve 43/1: mavi hat tanımı",
      "Tebliğ 31/1: götürü teminat uygulaması tanımı",
      "Tebliğ 17/1: eksik beyan usulüne konu belgeler"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=3, ayna="",
guncellik="",
cikmis="2025/98",
kapsamli=False,
),

dict(
konu="Onaylanmış Kişi Statüsü", blok="SB04",
kalip="YANLIŞ",
z="O",
madde="Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1) md. 54, 55, 56, 59",
cek="Onaylanmış ihracatçıya aykırılıkta ilk iki seferde yazılı uyarı, üçüncü seferde altı ay askı; yetki için en az elli A.TR şartı aranır.",
kok=["Onaylanmış Kişi Statüsüne İlişkin Gümrük Genel Tebliği (Sıra No: 1)'e göre onaylanmış ihracatçı yetkisine ve basitleştirilmiş işlem kapsamında düzenlenen A.TR dolaşım belgelerine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Yetki sahibince Karar hükümlerine aykırı hareket edildiğinin anlaşılması hâlinde ilk seferde yazılı uyarı yapılır, ikinci seferde onaylanmış ihracatçı yetkisi altı ay süreyle askıya alınır.",
c=["Yetki, başvuru yılından bir önceki takvim yılı içinde veya başvurunun kayda alındığı ayın ilk gününden geriye dönük bir yıl içinde en az elli adet A.TR dolaşım belgesi düzenleyip vize işlemlerini tamamlamış ve kullanmış statü belgesi sahiplerine talepleri hâlinde verilir.",
   "Basitleştirilmiş işlem kapsamında düzenlenecek A.TR dolaşım belgeleri, her belgeye ayrı seri numarası verilerek üç nüsha hâlinde bastırılır.",
   "Basitleştirilmiş işlem kapsamında düzenlenecek A.TR dolaşım belgeleri tasdik edilmeksizin, onaylanmış ihracatçı yetkisini haiz statü belgesi sahibi tarafından vize edilir.",
   "Belgelerin şekil şartları ve içerdiği bilgiler bakımından usulüne uygun düzenlenip düzenlenmediğinden doğrudan doğruya onaylanmış ihracatçı yetkisine sahip kişiler sorumludur."],
sirali=False,
g="Tebliğ'e göre onaylanmış ihracatçı yetkisi sahiplerince statü belgesinin geçerlilik süresi içinde Karar hükümlerine ve basitleştirilmiş usule ilişkin hükümlere aykırı hareket edildiğinin anlaşılması hâlinde ilk iki seferde yazılı uyarı yapılır, üçüncü seferde yetki altı ay süreyle askıya alınır; ikinci seferde askıya alma yazılması yanlıştır. Yetki; başvuru yılından bir önceki takvim yılında veya başvurunun kayda alındığı ayın ilk gününden geriye dönük bir yıl içinde en az elli adet A.TR dolaşım belgesi düzenleyip vize işlemlerini tamamlamış ve kullanmış statü belgesi sahiplerine talepleri hâlinde verilir. Basitleştirilmiş işlem kapsamındaki A.TR dolaşım belgeleri her belgeye ayrı seri numarası verilerek üç nüsha hâlinde bastırılır, tasdik edilmeksizin yetki sahibi tarafından vize edilir; şekil şartları ve içerik bakımından doğrudan doğruya yetki sahibi sorumludur. En güçlü tuzak, eksik beyan ve mavi hattaki 'üçüncü seferde askı' basamağının bir basamak öne çekilmesidir. Bu nedenle doğru cevap 'Yetki sahibince Karar hükümlerine aykırı hareket edildiğinin anlaşılması hâlinde ilk seferde yazılı uyarı yapılır, ikinci seferde onaylanmış ihracatçı yetkisi altı ay süreyle askıya alınır.' seçeneğidir. (MD OKS Tebliği 54, 55, 56, 59)",
kanit="4-OKSB.txt | söz konusu kişiler ilk iki seferde yazılı olarak uyarılır, üçüncü seferde onaylanmış ihracatçı yetkileri altı ay süreyle askıya alınır || 4-OKSB.txt | Başvuru yılından bir önceki takvim yılı içerisinde veya başvurunun kayda alındığı ayın ilk gününden geriye dönük bir yıl içerisinde … en az elli adet A.TR dolaşım belgesi düzenleyip vize işlemlerini tamamlamış || 4-OKSB.txt | her belgeye ayrı seri numarası verilerek üç nüsha halinde bastırılır || 4-OKSB.txt | tasdik edilmeksizin, onaylanmış ihracatçı yetkisini haiz statü belgesi sahibi tarafından vize edilir || 4-OKSB.txt | doğrudan doğruya onaylanmış ihracatçı yetkisine sahip kişiler sorumludur",
yuva=["Tebliğ 54/2: doğru ifade",
      "Tebliğ 55/1: doğru ifade",
      "Tebliğ 56/2: doğru ifade",
      "Tebliğ 56/5: doğru ifade"],
yakinlik="BİREBİR",
tuzak=["SAYI", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[4, 2],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

]
