# Soru Bankası — Bölüm 09: Gümrük Tarifesi ve Tarife Pozisyonlarına Ayırma (Usul) — 20 soru
# Gümrük Koçu - Ufuk Çetintaş
# Kaynak: 9-TAR.POZ.AYIRMA.txt (GK 15-16; GY 32; GGT Seri No: 4 md. 4-5; GGT Seri No: 6 md. 4-7)
K = "Gümrük Tarifesi ve Tarife Pozisyonlarına Ayırma (Usul)"
Q = [

# 1 — GK 15/1: vergilerin hesaplanmasında esas tarife (klasik; vakadan çevrildi)
dict(
konu=K, blok="SB09",
kalip="SONUÇ", z="K",
madde="4458 sayılı Gümrük Kanunu md. 15",
cek="Gümrük vergileri, gümrük yükümlülüğünün başladığı tarihte yürürlükte olan gümrük tarifesine göre hesaplanır; talep, işlem, teslim veya ödeme tarihi esas alınmaz.",
kok=["4458 sayılı Gümrük Kanunu'nun gümrük tarifesine ilişkin hükümlerine göre gümrük vergileri, hangi tarihte yürürlükte olan gümrük tarifesine göre hesaplanır?"],
d="Gümrük yükümlülüğünün başladığı tarihte",
c=["Beyan sahibinin tercihli tarife uygulanmasını talep ettiği tarihte",
   "Gümrük işlemlerinin tamamlandığı tarihte",
   "Eşyanın beyan sahibine teslim edildiği tarihte",
   "Gümrük vergilerinin ödendiği tarihte"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre gümrük vergileri, gümrük yükümlülüğünün başladığı tarihte yürürlükte olan gümrük tarifesine göre hesaplanır. Yükümlülüğün başlamasından sonra gerçekleşen işlemlerin tamamlanması, teslim veya ödeme gibi aşamalar, hesaplamada esas alınacak tarifeyi değiştirmez. En güçlü çeldiriciler aynı maddenin beyan sahibinin talebine ilişkin hükmünden taşınmıştır: Kanun beyan sahibine, gerekli koşulları taşıyan eşyada gümrük vergi oranlarını içeren tarife yerine tercihli tarife ile şartlı muafiyet veya indirim uygulamalarının uygulanmasını isteme imkânı tanır ve bu talebin gümrük işlemlerinin tamamlanmasından veya eşyanın tesliminden sonra da yapılabileceğini belirtir. Talep, işlemlerin tamamlanması ve teslim tarihleri bu nedenle talebin ne zaman yapılabileceğine ilişkindir; vergilerin hangi tarihteki tarifeye göre hesaplanacağını belirlemez. Vergilerin ödendiği tarih ise Kanunda tarifenin belirlenmesine bağlanmış bir an değildir. Bu nedenle doğru cevap 'Gümrük yükümlülüğünün başladığı tarihte' seçeneğidir. (MD GK 15)",
kanit="9-TAR.POZ.AYIRMA.txt | Gümrük vergileri, gümrük yükümlülüğünün başladığı tarihte yürürlükte olan gümrük tarifesine göre hesaplanır. || 9-TAR.POZ.AYIRMA.txt | beyan sahibi (c) bendinde belirtilen tarife yerine (d), (e) ve (f) bentleri hükümlerinin uygulanmasını isteyebilir || 9-TAR.POZ.AYIRMA.txt | söz konusu talep gümrük işlemlerinin tamamlanmasından veya eşyanın tesliminden sonra da yapılabilir",
yuva=["Aynı maddede beyan sahibinin tercihli tarife ile şartlı muafiyet veya indirim uygulamalarını talep edebilmesi hükmü (komşu fıkra)",
      "Aynı maddede tercihli tarife talebinin gümrük işlemlerinin tamamlanmasından sonra da yapılabilmesi (komşu fıkra)",
      "Aynı maddede tercihli tarife talebinin eşyanın tesliminden sonra da yapılabilmesi (komşu fıkra)",
      "Ödeme anı: tarifenin belirlenmesinde rolü olmayan sağduyu çeldiricisi (uydurma)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU", "SAĞDUYU"],
duzey=["HATIRLAMA"],
profil=[3],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 2 — GK 15/2 + GY 32/ç: eşya ticaretine ilişkin özel hükümlerle belirlenmiş önlemler (önermeli)
dict(
konu=K, blok="SB09",
kalip="ÖNERMELİ", z="O",
madde="4458 sayılı Gümrük Kanunu md. 15; Gümrük Yönetmeliği md. 32",
cek="Özel hükümlerle belirlenmiş önlemler gerektiğinde tarife pozisyonuna göre uygulanır; uluslararası anlaşmalar ile kanun, kararname, yönetmelik çerçevesinde ilgili kurumlarca belirlenir.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'nin eşyanın ticaretine ilişkin özel hükümlerle belirlenmiş önlemlere ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Eşya ticaretine ilişkin özel hükümlerle belirlenmiş önlemler, gerektiğinde eşyanın tarife pozisyonu esas alınarak uygulanır.",
     "II. Bir eşyanın ticaretine yönelik olarak uluslararası anlaşmalardan doğan yükümlülükler de bu önlemler arasında yer alır.",
     "III. Bu önlemler, yalnızca gümrük idarelerince belirlenen özel düzenlemelerden oluşur.",
     "IV. Bu önlemler kanunla belirlenebilir; yönetmelik ve benzeri mevzuatla önlem belirlenemez.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve II",
c=["Yalnız I", "I ve III", "II ve IV", "I, II ve IV"],
sirali=False,
g="Gümrük Kanunu'na göre eşya ticaretine ilişkin özel hükümlerle belirlenmiş diğer önlemler, gerektiği takdirde, söz konusu eşyanın tarife pozisyonuna göre uygulanır; I doğrudur. Gümrük Yönetmeliği bu önlemleri, bir eşyanın ticaretine ilişkin olarak uluslararası anlaşmalardan kaynaklanan yükümlülükler ya da kanun, kararname, yönetmelik ve benzeri mevzuat çerçevesinde ilgili kurumlarca belirlenmiş özel düzenlemeler olarak tanımlar. Buna göre uluslararası anlaşmalardan doğan yükümlülükler de bu kapsamdadır (II doğru). Önlemleri belirleyen yalnızca gümrük idareleri değil, ilgili kurumlardır (III yanlış); dayanak da yalnızca kanun değildir, kararname, yönetmelik ve benzeri mevzuat da sayılmıştır (IV yanlış). En güçlü tuzak III. önermedir: tanım, önlemleri belirleyen merci olarak gümrük idarelerini değil 'ilgili kurumları' gösterir. Bu nedenle doğru cevap 'I ve II' seçeneğidir. (MD GK 15; GY 32)",
kanit="9-TAR.POZ.AYIRMA.txt | Eşya ticaretine ilişkin özel hükümlerle belirlenmiş diğer önlemler, gerektiği takdirde, söz konusu eşyanın tarife pozisyonuna göre uygulanır. || 9-TAR.POZ.AYIRMA.txt | Bir eşyanın ticaretine ilişkin olarak uluslararası anlaşmalardan kaynaklanan yükümlülükler ya da kanun, kararname, yönetmelik ve benzeri mevzuat çerçevesinde, ilgili kurumlarca belirlenmiş özel düzenlemeleri",
yuva=["Yalnız I: Yönetmelikteki tanımda uluslararası anlaşmalardan kaynaklanan yükümlülüklerin de sayıldığını bilmeyen aday",
      "I ve III: tanımdaki 'ilgili kurumlarca' ifadesini gümrük idaresi sanan aday (makam karışıklığı)",
      "II ve IV: Kanundaki 'tarife pozisyonuna göre uygulanır' hükmünü bilmeyip dayanağı yalnız kanun sanan aday",
      "I, II ve IV: tanımdaki 'kanun, kararname, yönetmelik ve benzeri mevzuat' sayımını daraltan aday"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "MUTLAK", "UNSUR"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 3 — GK 15/3: gümrük tarifesinin kapsamı (2021/27 alanı, olumlu yönden)
dict(
konu=K, blok="SB09",
kalip="DOĞRU", z="O",
madde="4458 sayılı Gümrük Kanunu md. 15",
cek="Gümrük tarifesi; TGTC, ona tamamen veya kısmen dayanan cetveller, vergi oranları, tarım vergileri, tercihli uygulamalar, şartlı muafiyet-indirim ve diğer tarife uygulamalarını kapsar.",
kok=["4458 sayılı Gümrük Kanunu'na göre gümrük tarifesinin kapsamına ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Türk Gümrük Tarife Cetveline kısmen dayanan ve tarife önlemlerinin uygulanması için tespit edilen cetveller de gümrük tarifesinin kapsamındadır.",
c=["Türk Gümrük Tarife Cetveli, Müsteşarlıkça kabul edilen cetveldir.",
   "Tarım politikası çerçevesinde alınan ithalat vergileri, ayrı özel düzenlemelere tabi olduğundan gümrük tarifesinin kapsamı dışındadır.",
   "Gümrük tarifesi, Kanunda tek tek sayılan tarife uygulamalarıyla sınırlı olup bunların dışında kalan tarife uygulamalarını kapsamaz.",
   "Anlaşmalarla tanınan tercihli tarife uygulamaları gümrük tarifesinin kapsamındadır; Türkiye'nin tek taraflı olarak tanıdıkları ise kapsam dışındadır."],
sirali=False,
g="Gümrük Kanunu'na göre gümrük tarifesi; Cumhurbaşkanınca kabul edilen Türk Gümrük Tarife Cetvelini, tamamen veya kısmen bu cetvele dayanan ya da cetvele alt açılımlar ekleyen ve eşya ticaretine ilişkin tarife önlemlerinin uygulanması için tespit edilen diğer cetvelleri, gümrük vergi oranları ile tarım politikası veya tarım ürünlerinin işlenmesi sonucu elde edilen bazı ürünlere ilişkin özel düzenlemeler çerçevesinde alınan ithalat vergilerini, anlaşmalara dayanan ve Türkiye'nin tek taraflı olarak tanıdığı tercihli tarife uygulamalarını, şartlı muafiyet veya indirim uygulamalarını ve bunların dışında kalan diğer tarife uygulamalarını kapsar. Cetvele kısmen dayanan cetveller de bu nedenle kapsamdadır. Cetveli kabul eden makam Cumhurbaşkanıdır; Müsteşarlık ise cetveli, izahnamesini ve eşya fihristini hazırlayan makamdır. Tarım politikasına ilişkin ithalat vergileri, tek taraflı tercihli uygulamalar ve sayılanların dışındaki diğer tarife uygulamaları da tarifenin içindedir. En güçlü çeldirici Müsteşarlığa ilişkin seçenektir: hazırlama ile kabul yetkisi farklı makamlara aittir. Bu nedenle doğru cevap 'Türk Gümrük Tarife Cetveline kısmen dayanan ve tarife önlemlerinin uygulanması için tespit edilen cetveller de gümrük tarifesinin kapsamındadır.' seçeneğidir. (MD GK 15)",
kanit="9-TAR.POZ.AYIRMA.txt | Tamamen veya kısmen Türk Gümrük Tarife Cetveline dayanan veya bu cetvele alt açılımlar ekleyen ve eşya ticaretine ilişkin tarife önlemlerinin uygulanması için tespit edilen diğer cetvelleri || 9-TAR.POZ.AYIRMA.txt | Cumhurbaşkanınca kabul edilen Türk Gümrük Tarife Cetvelini || 9-TAR.POZ.AYIRMA.txt | Gümrük Tarife Cetveli, izahnamesi ve eşya fihristi, Müsteşarlıkça hazırlanır || 9-TAR.POZ.AYIRMA.txt | Yukarıdakilerin dışında kalan diğer tarife uygulamalarını",
yuva=["Cetvelin kabulü Cumhurbaşkanına aittir; Müsteşarlık cetveli, izahnamesini ve eşya fihristini hazırlar (makamların karıştırılması)",
      "Gümrük vergi oranlarıyla aynı bentte sayılan tarım politikasına ilişkin ithalat vergileri (tersine çevrilmiş)",
      "Sayılanların dışında kalan diğer tarife uygulamalarını da kapsayan son unsur (tersine çevrilmiş)",
      "Anlaşmalara dayanan tercihli uygulamalarla birlikte ayrı bentte sayılan tek taraflı tercihli tarife uygulamaları (unsur düşürülmüş)"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "KOMŞU", "UNSUR"],
duzey=["AYIRT"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/27",
kapsamli=False,
),

# 4 — GK 15/4: beyan sahibinin talep edebileceği uygulamalar (önermeli)
dict(
konu=K, blok="SB09",
kalip="ÖNERMELİ", z="Z",
madde="4458 sayılı Gümrük Kanunu md. 15",
cek="Koşulları taşıyan eşyada beyan sahibi vergi oranlarını içeren tarife yerine anlaşmalı veya tek taraflı tercihli tarife ve şartlı muafiyet-indirim uygulanmasını isteyebilir.",
kok=["4458 sayılı Gümrük Kanunu'nun gümrük tarifesine ilişkin hükümleri çerçevesinde aşağıdaki tarife uygulamaları verilmiştir:",
     "I. Türkiye'nin bazı ülkeler veya ülke grupları ile yaptığı tercihli bir tarife uygulaması gerektiren anlaşmalarda yer alan tercihli tarife uygulamaları",
     "II. Türkiye tarafından tek taraflı olarak bazı ülkeler, ülke grupları veya toprak parçaları için tanınan tercihli tarife uygulamaları",
     "III. İthalat vergilerinde, bazı eşyaya şartlı olarak uygulanacak muafiyet veya indirim uygulamaları",
     "IV. Tarım politikası veya tarım ürünlerinin işlenmesi sonucu elde edilen bazı ürünlere uygulanan özel düzenlemeler çerçevesinde alınan ithalat vergileri",
     "Sabit oranlı vergilendirmeye ilişkin hükümler saklı kalmak üzere, gerekli koşulları taşıyan eşyanın ithalinde beyan sahibi, Türk Gümrük Tarifesinin kapsadığı eşyaya uygulanacak gümrük vergi oranlarını içeren tarife yerine yukarıdakilerden hangilerinin uygulanmasını isteyebilir?"],
d="I, II ve III",
c=["I ve II", "I ve III", "II, III ve IV", "I, II, III ve IV"],
sirali=False,
g="Gümrük Kanunu'na göre sabit oranlı vergilendirmeye ilişkin hükümler saklı kalmak üzere, anlaşmalara dayanan tercihli tarife uygulamalarının, Türkiye'nin tek taraflı olarak tanıdığı tercihli tarife uygulamalarının ve ithalat vergilerinde bazı eşyaya şartlı olarak uygulanacak muafiyet veya indirim uygulamalarının koşullarını taşıyan eşyanın ithalinde beyan sahibi, gümrük vergi oranlarını ve tarım politikası ile işlenmiş tarım ürünlerine ilişkin özel düzenlemeler çerçevesinde alınan ithalat vergilerini kapsayan tarife yerine bu üç uygulamanın uygulanmasını isteyebilir. I, II ve III bu üç uygulamadır. IV'teki tarım politikası çerçevesinde alınan ithalat vergileri ise talep üzerine uygulanacak bir seçenek değil, gümrük vergi oranlarıyla aynı bentte sayılan ve yerine başka uygulama istenebilen tarifenin parçasıdır. En güçlü çeldirici 'I, II, III ve IV'tür: 'özel düzenlemeler' ifadesi IV'ü de bir ayrıcalık gibi gösterir, ancak Kanun bu vergileri talep edilebilecek uygulamalar arasında değil, değiştirilmek istenen tarifenin içinde sayar. Bu nedenle doğru cevap 'I, II ve III' seçeneğidir. (MD GK 15)",
kanit="9-TAR.POZ.AYIRMA.txt | Sabit oranlı vergilendirmeye ilişkin hükümler saklı kalmak üzere, 3 üncü fıkranın (d), (e) ve (f) bentlerinde belirtilen koşulları taşıyan eşyanın ithalinde, beyan sahibi (c) bendinde belirtilen tarife yerine (d), (e) ve (f) bentleri hükümlerinin uygulanmasını isteyebilir. || 9-TAR.POZ.AYIRMA.txt | Tarım politikası veya tarım ürünlerinin işlenmesi sonucu elde edilen bazı ürünlere uygulanan özel düzenlemeler çerçevesinde alınan ithalat vergilerini || 9-TAR.POZ.AYIRMA.txt | İthalat vergilerinde, bazı eşyaya şartlı olarak uygulanacak muafiyet veya indirim uygulamalarını",
yuva=["I ve II: şartlı muafiyet veya indirim uygulamalarının da talep edilebileceğini atlayan aday",
      "I ve III: tek taraflı tercihli tarife uygulamalarını talep kapsamı dışında sanan aday",
      "II, III ve IV: anlaşmalara dayanan tercihli uygulamayı unutup tarım vergilerini ekleyen aday",
      "I, II, III ve IV: yerine başka uygulama istenen tarifenin parçası olan tarım vergilerini talep edilebilir sanan aday"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "SAĞDUYU", "ŞART"],
duzey=["AYIRT"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 5 — GK 15/4 ikinci cümle: teslimden sonra tercihli tarife talebi (vaka)
dict(
konu=K, blok="SB09",
kalip="OLAY", z="O",
madde="4458 sayılı Gümrük Kanunu md. 15",
cek="Koşullar yerine getirilirse tercihli tarife talebi gümrük işlemlerinin tamamlanmasından veya eşyanın tesliminden sonra da yapılabilir.",
kok=["(B) firması, Türkiye'nin tercihli bir tarife uygulaması gerektiren anlaşma yaptığı bir ülkeden ithal ettiği eşyayı, tercihli tarife talep etmeksizin gümrük vergi oranları üzerinden vergilendirerek serbest dolaşıma sokmuştur. Gümrük işlemleri tamamlanmış ve eşya firmaya teslim edilmiştir. Firma daha sonra, eşyanın anlaşmada öngörülen koşulları taşıdığını gösteren belgelerle gümrük idaresine başvurarak tercihli tarifenin uygulanmasını talep etmiştir.",
     "4458 sayılı Gümrük Kanunu'nun gümrük tarifesine ilişkin hükümlerine göre bu talep hakkında aşağıdakilerden hangisi söylenebilir?"],
d="Gerekli koşulların yerine getirilmesi hâlinde talep, eşyanın tesliminden sonra da yapılabileceğinden değerlendirmeye alınır.",
c=["Tercihli tarife talebi beyannamenin tescilinden önce yapılmadığından talep reddedilir.",
   "Talep, gümrük işlemleri tamamlanmış olsa bile eşya teslim edilmeden önce yapılmış olsaydı değerlendirilebilirdi; teslimden sonra yapılamaz.",
   "Teslimden sonra tarife uygulamasının değiştirilmesi Cumhurbaşkanı Kararı gerektirdiğinden, böyle bir Karar olmadıkça talep sonuçsuz kalır.",
   "Tercihli tarife, beyan sahibinin talebine bağlı olmaksızın gümrük idaresince re'sen uygulandığından talep konusuz kalır."],
sirali=False,
g="Gümrük Kanunu'na göre anlaşmalara dayanan veya tek taraflı tanınan tercihli tarife uygulamaları ile şartlı muafiyet veya indirim uygulamalarının koşullarını taşıyan eşyanın ithalinde beyan sahibi, gümrük vergi oranlarını içeren tarife yerine bu uygulamaların uygulanmasını isteyebilir. Gerekli koşulların yerine getirilmesi hâlinde bu talep gümrük işlemlerinin tamamlanmasından veya eşyanın tesliminden sonra da yapılabilir. Vakada eşya teslim edilmiş olsa da firma anlaşmadaki koşulları belgelediğinden talep süresi geçmiş sayılmaz; vakaya saklanan istisna budur. En güçlü çeldirici, talebin ancak teslimden önce yapılabileceğini söyleyen seçenektir: Kanun işlemlerin tamamlanması ile teslimi ayrı ayrı sayar ve talebin her ikisinden sonra da yapılabileceğini açıkça belirtir. Cumhurbaşkanı Kararı, aynı maddede tarife tavanlarının sona ermesi için öngörülmüştür. Kanun tercihli uygulamayı beyan sahibinin isteğine bağladığından, talebin konusuz kaldığını söyleyen seçenek hükmü tersine çevirir. Bu nedenle doğru cevap 'Gerekli koşulların yerine getirilmesi hâlinde talep, eşyanın tesliminden sonra da yapılabileceğinden değerlendirmeye alınır.' seçeneğidir. (MD GK 15)",
kanit="9-TAR.POZ.AYIRMA.txt | Gerekli koşulların yerine getirilmesi halinde, söz konusu talep gümrük işlemlerinin tamamlanmasından veya eşyanın tesliminden sonra da yapılabilir. || 9-TAR.POZ.AYIRMA.txt | beyan sahibi (c) bendinde belirtilen tarife yerine (d), (e) ve (f) bentleri hükümlerinin uygulanmasını isteyebilir || 9-TAR.POZ.AYIRMA.txt | Tarife tavanlarının söz konusu olduğu durumlarda ise Cumhurbaşkanı Kararı ile",
yuva=["Vergilerin yükümlülüğün başladığı tarihteki tarifeye göre hesaplanması kuralı; talebin zamanını sınırlamaz (sağduyu)",
      "Talebin gümrük işlemlerinin tamamlanmasından 'veya' eşyanın tesliminden sonra da yapılabilmesi; teslim unsuru düşürülmüş",
      "Hacimle sınırlı uygulamalardan tarife tavanlarının Cumhurbaşkanı Kararı ile sona ermesi (komşu fıkra)",
      "Uygulamanın beyan sahibinin isteğine bağlanması ('isteyebilir'); tersine çevrilmiş"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "KOMŞU", "TERSİNE"],
duzey=["UYGULAMA"],
profil=[3],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 6 — GK 15/5-a: tarife kotasının sona ermesi (ayna: 7)
dict(
konu=K, blok="SB09",
kalip="SÜRE", z="K",
madde="4458 sayılı Gümrük Kanunu md. 15",
cek="Hacimle sınırlı tercihli veya şartlı uygulamalar tarife kotasında hacim sınırına ulaşılınca, tarife tavanında Cumhurbaşkanı Kararı ile sona erer.",
kok=["4458 sayılı Gümrük Kanunu'na göre, gümrük tarifesinin kapsadığı tercihli tarife ile şartlı muafiyet veya indirim uygulamalarından tarife kotası şeklinde sınırlandırılmış olanlar ne zaman sona erer?"],
d="Tespit edilen ithalat hacmi sınırına ulaşıldığında",
c=["Cumhurbaşkanı Kararı ile sona erdirildiğinde",
   "Gümrük idaresince sona erdirme kararı alındığında",
   "Belirlenen miktarı aşan ithalat için indirimlerin askıya alınmasına karar verildiğinde",
   "Kotanın dolduğu hususu Resmi Gazetede ilan edildiğinde"],
sirali=False,
g="Gümrük Kanunu'na göre gümrük tarifesinin kapsadığı tercihli tarife ile şartlı muafiyet veya indirim uygulamalarından belirli bir ithalat hacmi ile sınırlandırılmış olanlar iki ayrı biçimde sona erer: tarife kotalarının söz konusu olduğu durumlarda tespit edilen ithalat hacmi sınırına ulaşıldığında, tarife tavanlarının söz konusu olduğu durumlarda ise Cumhurbaşkanı Kararı ile. Tarife kotasında sona erme için ayrıca bir karar, askıya alma işlemi veya ilan beklenmez; Kanun bu konuda gümrük idaresine de bir yetki tanımamıştır. En güçlü çeldirici Cumhurbaşkanı Kararı seçeneğidir; bu sona erme biçimi aynı hükümde tarife tavanlarına bağlanmıştır. Aşan miktar için indirimlerin askıya alınması Yönetmelikteki tarife tavanı tanımından, Resmi Gazetede ilan ise tarife cetveli ve izahnamenin yayımlanmasına ilişkin hükümden taşınmıştır. Bu nedenle doğru cevap 'Tespit edilen ithalat hacmi sınırına ulaşıldığında' seçeneğidir. (MD GK 15; GY 32)",
kanit="9-TAR.POZ.AYIRMA.txt | Tarife kotalarının söz konusu olduğu durumlarda, tespit edilen ithalat hacmi sınırına ulaşıldığında, || 9-TAR.POZ.AYIRMA.txt | Tarife tavanlarının söz konusu olduğu durumlarda ise Cumhurbaşkanı Kararı ile || 9-TAR.POZ.AYIRMA.txt | bunu aşan miktar için belirlenen dönemin sonuna kadar bu tarife indirimlerinin askıya alınabilmesi uygulamasını || 9-TAR.POZ.AYIRMA.txt | Müsteşarlıkça hazırlanır ve Resmi Gazetede yayımlanır",
yuva=["Aynı hükümde tarife tavanlarının sona erme biçimi",
      "Sona erdirme yetkisinin gümrük idaresine verildiği izlenimi (makam karışıklığı; Kanunda böyle bir yetki yok)",
      "Yönetmelikteki tarife tavanı tanımında aşan miktar için indirimlerin askıya alınabilmesi",
      "Gümrük Tarife Cetveli ve izahnamenin Resmi Gazetede yayımlanması hükmü (uyarlanmış)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "BAŞLANGIÇ", "MAKAM"],
duzey=["AYIRT"],
profil=[3],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="KOTA-TAVAN",
guncellik="",
cikmis="",
kapsamli=False,
),

# 7 — GK 15/5-b + GY 32/l: tarife tavanının sona ermesi ve tanımı (olumsuz; vakadan çevrildi; ayna: 6)
dict(
konu=K, blok="SB09",
kalip="YANLIŞ", z="Z",
madde="4458 sayılı Gümrük Kanunu md. 15; Gümrük Yönetmeliği md. 32",
cek="Tarife tavanı hacim sınırına ulaşılınca kendiliğinden değil Cumhurbaşkanı Kararıyla sona erer; indirim ithalat ve ihracatta, aşan miktarda askıya alınabilir.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'nin hacimle sınırlı tarife uygulamalarına ilişkin hükümlerine göre tarife tavanı hakkında aşağıdakilerden hangisi söylenemez?"],
d="Belirlenen ithalat hacmi sınırına ulaşıldığında tarife tavanı uygulaması kendiliğinden sona erer.",
c=["Tarife tavanı, belirli bir dönem içinde belli malların belirlenen değer ya da miktarı için normal gümrük vergisi oranında bir indirime gidilmesini öngörür.",
   "Tarife tavanında öngörülen indirim, ithalatın yanı sıra ihracatta da söz konusu olabilir.",
   "Belirlenen değer ya da miktarı aşan miktar için tarife indirimleri, belirlenen dönemin sonuna kadar askıya alınabilir.",
   "Kanunda tarife tavanı, tarife kotası gibi belirli bir ithalat hacmiyle sınırlandırılmış tarife uygulamalarından biri olarak düzenlenmiştir."],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre tercihli tarife ile şartlı muafiyet veya indirim uygulamalarından belirli bir ithalat hacmiyle sınırlandırılmış olanlar, tarife kotalarının söz konusu olduğu durumlarda tespit edilen ithalat hacmi sınırına ulaşıldığında, tarife tavanlarının söz konusu olduğu durumlarda ise Cumhurbaşkanı Kararı ile sona erer. Hacim sınırına ulaşılmasıyla kendiliğinden sona erme tarife kotasına özgüdür; tarife tavanı Cumhurbaşkanı Kararı olmadıkça sona ermez. Gümrük Yönetmeliği de tarife tavanını, belirli bir dönem içinde belli malların belirlenen değer ya da miktar için ithalatta ve ihracatta normal gümrük vergisi oranında bir indirime gidilmesi ve bunu aşan miktar için belirlenen dönemin sonuna kadar bu tarife indirimlerinin askıya alınabilmesi uygulaması olarak tanımlar; dönem ve miktar, ihracat ve askıya alma imkânına ilişkin ifadeler bu tanıma, tarife tavanını tarife kotasıyla birlikte hacimle sınırlı uygulamalar arasında gösteren ifade ise Kanuna uygundur. Aşan miktar için indirimlerin askıya alınabilmesi, uygulamanın hacim aşılınca bittiği izlenimini verdiğinden en güçlü tuzaktır; askıya alma bir imkândır ve uygulamayı sona erdirmez. Bu nedenle doğru cevap 'Belirlenen ithalat hacmi sınırına ulaşıldığında tarife tavanı uygulaması kendiliğinden sona erer.' seçeneğidir. (MD GK 15; GY 32)",
kanit="9-TAR.POZ.AYIRMA.txt | Tarife tavanlarının söz konusu olduğu durumlarda ise Cumhurbaşkanı Kararı ile || 9-TAR.POZ.AYIRMA.txt | Tarife kotalarının söz konusu olduğu durumlarda, tespit edilen ithalat hacmi sınırına ulaşıldığında, || 9-TAR.POZ.AYIRMA.txt | Belirli bir dönem içinde, belli malların belirlenen değer ya da miktar için ithalatta ve ihracatta normal gümrük vergisi oranında bir indirime gidilmesi ve bunu aşan miktar için belirlenen dönemin sonuna kadar bu tarife indirimlerinin askıya alınabilmesi uygulamasını || 9-TAR.POZ.AYIRMA.txt | belirli bir ithalat hacmi ile sınırlandırılmış tarife uygulamaları",
yuva=["Yönetmelikteki tarife tavanı tanımı: dönem, mal ve değer ya da miktar unsuru (doğru ifade)",
      "Yönetmelikteki tarife tavanı tanımı: indirimin ithalatta ve ihracatta söz konusu olması (doğru ifade)",
      "Yönetmelikteki tarife tavanı tanımı: aşan miktar için indirimlerin askıya alınabilmesi (doğru ifade)",
      "Kanunda tarife kotası ve tarife tavanının hacimle sınırlı tarife uygulamaları olarak birlikte düzenlenmesi (doğru ifade)"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "TERİM", "MAKAM"],
duzey=["AYIRT"],
profil=[4, 3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="KOTA-TAVAN",
guncellik="",
cikmis="",
kapsamli=False,
),

# 8 — GK 15/7 + Seri No: 4 md. 5: izahnamenin bağlayıcılığı (ayna: 9)
dict(
konu=K, blok="SB09",
kalip="YANLIŞ", z="O",
madde="4458 sayılı Gümrük Kanunu md. 15; Gümrük Genel Tebliği (Gümrük Tarife Cetveli İzahnamesi) (Seri No: 4) md. 4, 5",
cek="İzahname Resmi Gazetede yayımlanır; AS Nomanklatürünün uluslararası resmî yorumunda zorunlu ve tamamlayıcıdır; hükümleri idari ve kazai uygulamalarda esas tutulur.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Genel Tebliği (Gümrük Tarife Cetveli İzahnamesi) (Seri No: 4)'e göre Gümrük Tarife Cetveli İzahnamesine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="İzahname hükümleri idari uygulamalarda esas tutulur; yargı mercilerince verilecek kararlarda ise yalnızca yol gösterici niteliktedir.",
c=["İzahname, Gümrük Tarife Cetveli ve eşya fihristi gibi Resmi Gazetede yayımlanır.",
   "İzahname hükümleri, Armonize Sistem Nomanklatürünün uluslararası seviyede resmî yorumunun yapılmasında zorunlu ve tamamlayıcı bir unsurdur.",
   "İzahname hükümlerinin uygulamada esas tutulması, Gümrük Kanunu'nun gümrük tarifesine ilişkin hükmüne dayanır.",
   "İzahnameye ilişkin Tebliğde Genel Yorum Kuralları, Türk Gümrük Tarife Cetvelinde yer alan Tarifenin yorumuna ilişkin kurallar olarak tanımlanmıştır."],
sirali=False,
g="Gümrük Kanunu'na göre Gümrük Tarife Cetveli, izahnamesi ve eşya fihristi hazırlanarak Resmi Gazetede yayımlanır ve bu şekilde yayımlanan metinler idari ve kazai uygulamalarda esas tutulur. Seri No: 4 Tebliği de Armonize Sistem Nomanklatürünün uluslararası seviyede resmî yorumunun yapılmasında zorunlu ve tamamlayıcı bir unsur olan İzahname hükümlerinin, Kanunun bu hükmü gereğince idari ve kazai uygulamalarda esas tutulacağını belirtir. Dolayısıyla izahname yargı (kazai) uygulamalarında da esas alınır; yalnızca yol gösterici olduğunu söyleyen ifade yanlıştır. 'Bağlayıcı olmayıp yol gösterici' nitelik, Gümrük Yönetmeliğinde bölüm başlıkları için öngörülmüştür; yanlış ifade bu nitelemeyi izahnameye taşımıştır. Genel Yorum Kuralları da aynı Tebliğde Tarifenin yorumuna ilişkin kurallar olarak tanımlanmıştır. Bu nedenle doğru cevap 'İzahname hükümleri idari uygulamalarda esas tutulur; yargı mercilerince verilecek kararlarda ise yalnızca yol gösterici niteliktedir.' seçeneğidir. (MD GK 15; Seri No: 4 Tebliği 4-5)",
kanit="9-TAR.POZ.AYIRMA.txt | Gümrük Tarife Cetveli, izahnamesi ve eşya fihristi, Müsteşarlıkça hazırlanır ve Resmi Gazetede yayımlanır. Bu şekilde yayımlanan metinler idari ve kazai uygulamalarda esas tutulur. || 9-TAR.POZ.AYIRMA.txt | Armonize Sistem Nomanklatürünün uluslararası seviyede resmî yorumunun yapılmasında zorunlu ve tamamlayıcı bir unsur olan İzahname hükümleri || 9-TAR.POZ.AYIRMA.txt | Türk Gümrük Tarife Cetvelinde yer alan Tarifenin yorumuna ilişkin Genel Yorum Kurallarını || 9-TAR.POZ.AYIRMA.txt | tarifenin yorumu bakımından bağlayıcı olmayıp, yol gösterici nitelikte olan ibareleri",
yuva=["Kanunda cetvel, izahname ve eşya fihristinin Resmi Gazetede yayımlanması (doğru ifade)",
      "Seri No: 4 Tebliğinde izahname hükümlerinin niteliği (doğru ifade)",
      "Seri No: 4 Tebliğinde izahnamenin Kanundaki tarife hükmü gereğince esas tutulması (doğru ifade)",
      "Seri No: 4 Tebliğinde Genel Yorum Kuralları tanımı (doğru ifade)"],
yakinlik="PARAFRAZ",
tuzak=["TERSİNE", "KOMŞU", "UNSUR"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="BAĞLAYICILIK",
guncellik="",
cikmis="",
kapsamli=False,
),

# 9 — GY 32/a-c, e, f: başlık ve notların niteliği (ayna: 8)
dict(
konu=K, blok="SB09",
kalip="YANLIŞ", z="O",
madde="Gümrük Yönetmeliği md. 32",
cek="Bölüm başlıkları bağlayıcı olmayıp yol gösterici, fasıl başlıkları da bağlayıcı olmayan ibarelerdir; bölüm ve fasıl notları başlıklardan sonra yer alır.",
kok=["Gümrük Yönetmeliği'nin gümrük tarifesi uygulamasına ilişkin tanımlarına göre Türk Gümrük Tarife Cetvelindeki bölüm ve fasıllara ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Fasıl başlıkları, fasılların başında bulunan ve bağlayıcı nitelik taşıyan ibarelerdir.",
c=["Bölüm başlıkları, her bölümün başında yer alan ve tarifenin yorumu bakımından bağlayıcı olmayıp yol gösterici nitelikte olan ibarelerdir.",
   "Bölüm notları, bölümlerle ilgili olarak bölüm başlıklarından sonra yer alan açıklamalardır.",
   "Fasıl notları, fasıl başlıklarından sonra gelmek üzere fasıllarla ilgili yapılan açıklamaların yer aldığı kayıtlardır.",
   "Bölüm, birbirine benzeyen aynı nitelikteki veya çoğunlukla aynı hammaddeden yapılan eşyayı içine alacak şekilde oluşturulan gruplardır."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre fasıl başlıkları, Türk Gümrük Tarife Cetvelinde yer alan fasılların başında bulunan ve bağlayıcı olmayan ibarelerdir. Bölüm başlıkları da tarifenin yorumu bakımından bağlayıcı olmayıp yol gösterici niteliktedir. Bölüm notları bölüm başlıklarından sonra, fasıl notları fasıl başlıklarından sonra yer alan açıklamalardır; bölüm ise birbirine benzeyen aynı nitelikteki veya çoğunlukla aynı hammaddeden yapılan eşyayı içine alacak şekilde oluşturulan gruptur. Yanlış ifade, fasıl başlıklarının 'bağlayıcı olmayan' niteliğini 'bağlayıcı' olarak değiştirmiştir. Kanunda idari ve kazai uygulamalarda esas tutulacağı belirtilen metinler Resmi Gazetede yayımlanan tarife cetveli, izahname ve eşya fihristidir; bölüm ve fasıl başlıkları ise bağlayıcı değildir. Bu nedenle doğru cevap 'Fasıl başlıkları, fasılların başında bulunan ve bağlayıcı nitelik taşıyan ibarelerdir.' seçeneğidir. (MD GY 32)",
kanit="9-TAR.POZ.AYIRMA.txt | Türk Gümrük Tarife Cetvelinde yer alan fasılların başında bulunan ve bağlayıcı olmayan ibareleri || 9-TAR.POZ.AYIRMA.txt | tarifenin yorumu bakımından bağlayıcı olmayıp, yol gösterici nitelikte olan ibareleri || 9-TAR.POZ.AYIRMA.txt | Türk Gümrük Tarife Cetvelinde fasıl başlıklarından sonra gelmek üzere, fasıllarla ilgili yapılan açıklamaların yer aldığı kayıtları || 9-TAR.POZ.AYIRMA.txt | birbirine benzeyen aynı nitelikteki veya çoğunlukla aynı hammaddeden yapılan eşyayı içine alacak şekilde oluşturulan grupları",
yuva=["Bölüm başlığı tanımı (doğru ifade)",
      "Bölüm notu tanımı (doğru ifade)",
      "Fasıl notu tanımı (doğru ifade)",
      "Bölüm tanımı (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="BAĞLAYICILIK",
guncellik="",
cikmis="",
kapsamli=False,
),

# 10 — GK 16/1-2: nihai kullanım gerekçeli tercihli tarife (boşluk)
dict(
konu=K, blok="SB09",
kalip="BOŞLUK", z="O",
madde="4458 sayılı Gümrük Kanunu md. 16",
cek="Nihai kullanım gerekçeli tercihli tarife Cumhurbaşkanınca belirlenen şartlara tabidir; tarife kotası kapsamında olsa dahi indirim veya şartlı muafiyet anlamına gelir.",
kok=["\"Mahiyeti ve nihai kullanım şekli gerekçesiyle, bazı eşyanın yararlanabileceği tercihli tarife uygulaması, ………. belirlenen şartlara tabidir. Söz konusu tercihli tarife uygulaması ifadesi, tarife kotaları kapsamında olsa dahi, ithalat vergilerinde bir ………. anlamına gelir.\"",
     "4458 sayılı Gümrük Kanunu'nun nihai kullanım şekli gerekçesiyle uygulanan tercihli tarifeye ilişkin hükmünde yer alan yukarıdaki boşluklara sırasıyla aşağıdakilerden hangisi gelmelidir?"],
d="Cumhurbaşkanınca – indirim veya şartlı muafiyet uygulaması",
c=["Müsteşarlıkça – indirim veya şartlı muafiyet uygulaması",
   "Cumhurbaşkanınca – geri ödeme uygulaması",
   "Müsteşarlıkça – tam muafiyet uygulaması",
   "Cumhurbaşkanınca – tam muafiyet uygulaması"],
sirali=False,
g="Gümrük Kanunu'na göre mahiyeti ve nihai kullanım şekli gerekçesiyle bazı eşyanın yararlanabileceği tercihli tarife uygulaması, Cumhurbaşkanınca belirlenen şartlara tabidir; bir izin gerektiğinde Kanunun 80 ve 81 inci madde hükümleri uygulanır. Aynı maddeye göre bu tercihli tarife uygulaması ifadesi, tarife kotaları kapsamında olsa dahi, ithalat vergilerinde bir indirim veya şartlı muafiyet uygulaması anlamına gelir. Müsteşarlık, Kanunda tarife cetveli, izahname ve eşya fihristini hazırlayan makam olarak geçer; şartları belirleyen makam değildir. Geri ödeme ve tam muafiyet ise Kanunda başka rejimlerde (dahilde işleme ve geçici ithalat) geçen kavramlardır. En güçlü çeldirici 'Cumhurbaşkanınca – tam muafiyet uygulaması' seçeneğidir: makam doğru, ancak Kanun 'tam muafiyet' değil 'indirim veya şartlı muafiyet' ifadesini kullanır. Bu nedenle doğru cevap 'Cumhurbaşkanınca – indirim veya şartlı muafiyet uygulaması' seçeneğidir. (MD GK 16)",
kanit="9-TAR.POZ.AYIRMA.txt | Mahiyeti ve nihai kullanım şekli gerekçesiyle, bazı eşyanın yararlanabileceği tercihli tarife uygulaması, Cumhurbaşkanınca belirlenen şartlara tabidir. || 9-TAR.POZ.AYIRMA.txt | tarife kotaları kapsamında olsa dahi, ithalat vergilerinde bir indirim veya şartlı muafiyet uygulaması anlamına gelir. || 32-DAHİLDE İŞLEME.txt | Eşyanın bu şekilde dahilde işleme rejiminden yararlanmasına geri ödeme sistemi denir. || 34-GEÇİCİ İTHALAT.txt | İthal vergilerinden tam muafiyet suretiyle geçici ithalat rejiminin",
yuva=["Kanunda tarife cetveli, izahname ve eşya fihristini hazırlayan makam (Müsteşarlık)",
      "Dahilde işleme rejimindeki geri ödeme sistemi (komşu rejim)",
      "Hazırlayan makam (Müsteşarlık) ile geçici ithalat rejimindeki tam muafiyet kavramının birleşimi",
      "Makam doğru; geçici ithalat rejimindeki tam muafiyet kavramı (komşu rejim)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "TERİM", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 11 — GY 32/i: tarife kotası (kontenjanı) — addan tanım (2022/43 alanı, ters yön)
dict(
konu=K, blok="SB09",
kalip="TANIM", z="K",
madde="Gümrük Yönetmeliği md. 32",
cek="Tarife kotası (kontenjanı): bir mal veya mal grubunun gümrük vergisi oranlarında belirli miktar veya değer için indirim ya da muafiyet sağlanması.",
kok=["Gümrük Yönetmeliği'nin gümrük tarifesi uygulamasına ilişkin tanımlarına göre \"tarife kotası veya tarife kontenjanı\" aşağıdakilerden hangisini ifade eder?"],
d="Bir mal ya da mal grubunun gümrük vergisi oranlarında belirli bir miktar veya değer için indirim yapılması ya da muafiyet sağlanmasını",
c=["Bir takvim yılı içinde veya muayyen bir dönem itibarıyla yapılmasına izin verilen ithalatın miktar ve/veya değerini",
   "Belirli bir dönemde belli mallar için belirlenen değer ya da miktarda ithalatta ve ihracatta vergi indirimine gidilmesini ve aşan miktar için indirimlerin askıya alınabilmesini",
   "İki ya da daha çok ülkenin yaptıkları ticaret anlaşması uyarınca, aralarındaki ticarette karşılıklı olarak daha düşük tarife uygulamasını",
   "Dış ticaretin serbest piyasa koşullarında gelişmesine, konulan gümrük vergileri ile engel olunmasını"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre tarife kotası veya tarife kontenjanı, bir mal ya da mal grubunun gümrük vergisi oranlarında belirli bir miktar veya değer için indirim yapılması ya da muafiyet sağlanmasıdır. Ayırt edici unsur, miktar veya değer sınırının vergi indirimi ya da muafiyetle birlikte bulunmasıdır. En güçlü çeldirici kota tanımıdır: kota, bir takvim yılı içinde veya muayyen bir dönem itibarıyla yapılmasına izin verilen ithalatın miktar ve/veya değeridir; vergi indirimi içermez, ithalatın kendisini sınırlar. Dönem sonuna kadar indirimlerin askıya alınabilmesi tarife tavanının, karşılıklı daha düşük tarife uygulaması tercihli tarifenin, gümrük vergileriyle dış ticarete engel olunması ise tarife önlemlerinin tanımıdır. Bu nedenle doğru cevap 'Bir mal ya da mal grubunun gümrük vergisi oranlarında belirli bir miktar veya değer için indirim yapılması ya da muafiyet sağlanmasını' seçeneğidir. (MD GY 32)",
kanit="9-TAR.POZ.AYIRMA.txt | Bir mal ya da mal grubunun gümrük vergisi oranlarında belirli bir miktar veya değer için indirim yapılması ya da muafiyet sağlanmasını || 9-TAR.POZ.AYIRMA.txt | Bir takvim yılı içinde veya muayyen bir dönem itibarıyla yapılmasına izin verilen ithalatın miktar ve/veya değerini || 9-TAR.POZ.AYIRMA.txt | Dış ticaretin serbest piyasa koşullarında gelişmesine, konulan gümrük vergileri ile engel olunmasını",
yuva=["Kota tanımı (komşu tanım)",
      "Tarife tavanı tanımı (komşu tanım)",
      "Tercihli tarife tanımı (komşu tanım)",
      "Tarife önlemleri tanımı (komşu tanım)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2022/43",
kapsamli=False,
),

# 12 — GY 32/ğ, h, j, m: kota, tercihli tarife, tarife önlemleri, işlenmiş tarım ürünleri (tek kelime değişikliği; önermeliden çevrildi; 2024/37 alanı)
dict(
konu=K, blok="SB09",
kalip="YANLIŞ", z="O",
madde="Gümrük Yönetmeliği md. 32",
cek="Tarife önlemi gümrük vergileriyle engeldir, miktar kısıtlaması değildir; kota izin verilen ithalat miktarı/değeri; tercihli tarife tek taraflı da olabilir.",
kok=["Gümrük Yönetmeliği'nin gümrük tarifesi uygulamasına ilişkin tanımlarına göre kota, tercihli tarife, tarife önlemleri ve işlenmiş tarım ürünleriyle ilgili özel düzenlemelere ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Tarife önlemleri, dış ticaretin serbest piyasa koşullarında gelişmesine, konulan miktar kısıtlamaları ile engel olunmasını ifade eder.",
c=["Kota, bir takvim yılı içinde veya muayyen bir dönem itibarıyla yapılmasına izin verilen ithalatın miktar ve/veya değeridir.",
   "Tercihli tarife, iki ya da daha çok ülkenin yaptıkları ticaret anlaşması uyarınca aralarındaki ticarette karşılıklı olarak daha düşük tarife uygulamasını ifade eder.",
   "Bir ülkenin belli ülke ya da toprak parçaları menşeli eşyaya tek taraflı olarak daha düşük tarife uygulaması da tercihli tarife kapsamındadır.",
   "İşlenmiş tarım ürünleriyle ilgili özel düzenlemeler, tarım ürünlerinin işlenmesi sonucu elde edilen işlenmiş tarım ürünlerinin ticaretinde uygulanan özel hükümlerdir."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre tarife önlemleri, dış ticaretin serbest piyasa koşullarında gelişmesine konulan gümrük vergileri ile engel olunmasıdır; yanlış ifade 'gümrük vergileri' unsurunu 'miktar kısıtlamaları' ile değiştirmiştir. Miktar kısıtlamaları, Gümrük Yönetmeliği'nin genel tanımlarında gözetim, korunma önlemleri ve ithalat veya ihracat yasaklamalarıyla birlikte tarife dışı önlem niteliğindeki ticaret politikası önlemleri arasında sayılır; ithalatın izin verilen miktar ve/veya değerini ifade eden kavram ise kotadır. Aynı tanımlara göre kota, bir takvim yılı içinde veya muayyen bir dönem itibarıyla yapılmasına izin verilen ithalatın miktar ve/veya değeridir; tercihli tarife, iki ya da daha çok ülkenin ticaret anlaşması uyarınca aralarındaki ticarette karşılıklı olarak ya da bir ülkenin belli ülke veya toprak parçaları menşeli eşyaya tek taraflı olarak daha düşük tarife uygulamasıdır; işlenmiş tarım ürünleriyle ilgili özel düzenlemeler ise tarım ürünlerinin işlenmesi sonucu elde edilen işlenmiş tarım ürünlerinin ticaretinde uygulanan özel hükümlerdir. Kota ile tarife önlemini karıştıran aday yanlış ifadeyi doğru sanır. Bu nedenle doğru cevap 'Tarife önlemleri, dış ticaretin serbest piyasa koşullarında gelişmesine, konulan miktar kısıtlamaları ile engel olunmasını ifade eder.' seçeneğidir. (MD GY 32; GY 3)",
kanit="9-TAR.POZ.AYIRMA.txt | Dış ticaretin serbest piyasa koşullarında gelişmesine, konulan gümrük vergileri ile engel olunmasını || 9-TAR.POZ.AYIRMA.txt | Bir takvim yılı içinde veya muayyen bir dönem itibarıyla yapılmasına izin verilen ithalatın miktar ve/veya değerini || 9-TAR.POZ.AYIRMA.txt | İki ya da daha çok ülkenin yaptıkları ticaret anlaşması uyarınca, aralarındaki ticarette karşılıklı olarak ya da bir ülkenin belli ülke ya da toprak parçaları menşeli eşyaya tek taraflı olarak daha düşük tarife uygulamasını || 9-TAR.POZ.AYIRMA.txt | Tarım ürünlerinin işlenmesi sonucu elde edilen işlenmiş tarım ürünlerinin ticaretinde uygulanan özel hükümleri || 1-TANIMLAR.txt | Gözetim, korunma önlemleri, miktar kısıtlamaları ve ithalat veya ihracat yasaklamaları gibi eşyanın ithal ve ihracı ile ilgili hükümlerle belirlenmiş tarife dışı önlemleri",
yuva=["Kota tanımı (doğru ifade)",
      "Tercihli tarife tanımı: anlaşmaya dayanan karşılıklı uygulama (doğru ifade)",
      "Tercihli tarife tanımı: tek taraflı uygulama (doğru ifade)",
      "İşlenmiş tarım ürünleriyle ilgili özel düzenlemeler tanımı (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU", "UNSUR"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2024/37",
kapsamli=False,
),

# 13 — GY 32/c: bölüm notunun içeriği (liste dışı)
dict(
konu=K, blok="SB09",
kalip="KAPSAM_DIŞI", z="O",
madde="Gümrük Yönetmeliği md. 32",
cek="Bölüm notları tabirlerin anlamı, atıfların kapsamı, yalnız o bölümdeki eşya ve şartları, bölüme dahil olmayan eşya hakkında bilgi verir; vergi oranları listede yoktur.",
kok=["Gümrük Yönetmeliği'ne göre Türk Gümrük Tarife Cetvelinde bölüm başlıklarından sonra yer alan bölüm notlarının bilgi verdiği hususlar arasında aşağıdakilerden hangisi yer almaz?"],
d="Bölümde yer alan eşyaya uygulanacak gümrük vergisi oranları",
c=["Bölümde geçen bazı tabirlerin ne anlama geldiği",
   "İlgili bölümde bir eşyaya yapılan bir atfın hangi tür eşyayı kapsadığı",
   "Hangi eşyanın sadece ilgili bölümde yer alabileceği ve bunun için hangi şartların gerektiği",
   "Hangi eşyanın o bölüme dahil olmadığı"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre bölüm notu, Türk Gümrük Tarife Cetvelinde bölümlerle ilgili olarak bölüm başlıklarından sonra yer alan ve bölümde geçen bazı tabirlerin ne anlama geldiği, ilgili bölümde bir eşyaya yapılan bir atfın hangi tür eşyayı kapsadığı, hangi eşyanın sadece ilgili bölümde yer alabileceği ve bunun için hangi şartların gerektiği ile hangi eşyanın o bölüme dahil olmadığı hakkında bilgi veren açıklamalardır. Eşyaya uygulanacak gümrük vergisi oranları bu listede yer almaz; Gümrük Kanunu'na göre gümrük vergi oranları gümrük tarifesinin kapsadığı ayrı bir unsurdur. Bu seçenek, sınıflandırmaya yön veren not içeriğine mantıklı görünen bir vergi bilgisi eklediğinden mevzuatı sağduyuyla çözen aday onu da notların kapsamında sanar. Bu nedenle doğru cevap 'Bölümde yer alan eşyaya uygulanacak gümrük vergisi oranları' seçeneğidir. (MD GY 32; GK 15)",
kanit="9-TAR.POZ.AYIRMA.txt | bölümde geçen bazı tabirlerin ne anlama geldiği, ilgili bölümde bir eşyaya yapılan bir atfın hangi tür eşyayı kapsadığı, hangi eşyanın sadece ilgili bölümde yer alabileceği ve bu eşyanın bu bölümde yer alabilmesi için hangi şartların gerektiği, hangi eşyanın o bölüme dahil olmadığı hakkında bilgi veren açıklamaları || 9-TAR.POZ.AYIRMA.txt | Gümrük vergi oranlarını",
yuva=["Bölüm notu tanımı: bölümde geçen tabirlerin anlamı",
      "Bölüm notu tanımı: atfın kapsadığı eşya türü",
      "Bölüm notu tanımı: yalnız ilgili bölümde yer alabilecek eşya ve şartları",
      "Bölüm notu tanımı: bölüme dahil olmayan eşya"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 14 — Seri No: 6 md. 4/ı: pozisyon — tanımdan ad (2023/96 alanı)
dict(
konu=K, blok="SB09",
kalip="TANIM", z="O",
madde="Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 6) md. 4",
cek="Seri No: 6'da pozisyon: fasıl rakamlarından sonraki iki rakamla oluşan, eşyanın faslın kaçıncı sırasında olduğunu gösteren dört basamaklı sayı grubu.",
kok=["Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 6)'da \"fasla ilişkin ilk iki rakamdan sonra gelen iki rakamla birlikte dört basamaklı rakamla ifade edilen, eşyanın ilgili faslın kaçıncı sırasında olduğunu gösteren sayı grupları\" şeklinde tanımlanan kavram aşağıdakilerden hangisidir?"],
d="Pozisyon",
c=["Alt pozisyon", "Fasıl", "Bölüm", "Gümrük tarife istatistik pozisyonu"],
sirali=False,
g="Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 6)'ya göre pozisyon, fasla ilişkin ilk iki rakamdan sonra gelen iki rakamla birlikte dört basamaklı rakamla ifade edilen ve eşyanın ilgili faslın kaçıncı sırasında olduğunu gösteren sayı gruplarıdır. Gümrük Yönetmeliği aynı dört rakamlı grubu 'tarife pozisyonu' olarak adlandırır. Alt pozisyon, pozisyon numarasına iki rakam eklenerek oluşan altı basamaklı gruptur; fasıl Armonize Sistem Kodunun ilk iki rakamıdır; gümrük tarife istatistik pozisyonu ise on iki rakamdan oluşur. Bölüm ise fasılları içeren gruplardır. En güçlü çeldirici alt pozisyondur: pozisyonun iki rakam eklenmiş biçimidir. Bu nedenle doğru cevap 'Pozisyon' seçeneğidir. (MD Seri No: 6 Tebliği 4; GY 32)",
kanit="9-TAR.POZ.AYIRMA.txt | Fasla ilişkin ilk iki rakamdan sonra gelen iki rakamla birlikte dört basamaklı rakamla ifade edilen, eşyanın ilgili faslın kaçıncı sırasında olduğunu gösteren sayı gruplarını || 9-TAR.POZ.AYIRMA.txt | Pozisyon numarasından sonra gelmek üzere iki rakamın eklenmesiyle ve kendinden önce gelen dört rakamla birlikte oluşan altı basamaklı sayı gruplarını || 9-TAR.POZ.AYIRMA.txt | Türk Gümrük Tarife Cetvelinde, oniki rakamdan oluşan pozisyonu",
yuva=["Seri No: 4 Tebliğinde alt pozisyon tanımı (altı basamak)",
      "Fasıl tanımı (Armonize Sistem Kodunun ilk iki rakamı)",
      "Bölüm tanımı (fasılları içeren gruplar)",
      "Gümrük Yönetmeliğinde gümrük tarife istatistik pozisyonu tanımı (on iki rakam)"],
yakinlik="BİREBİR",
tuzak=["TERİM", "SAYI"],
duzey=["TANIMA"],
profil=[1, 2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2023/96",
kapsamli=False,
),

# 15 — GY 32/d, g, ı, k, n: rakam grupları (tek kelime değişikliği; 2025/28 alanı)
dict(
konu=K, blok="SB09",
kalip="YANLIŞ", z="K",
madde="Gümrük Yönetmeliği md. 32",
cek="Tarife pozisyonu dört, tarife alt pozisyonu altı, gümrük tarife istatistik pozisyonu on iki rakamdan oluşur; fasıl bölümlerden alt düzeydedir.",
kok=["Gümrük Yönetmeliği'nin gümrük tarifesi uygulamasına ilişkin tanımlarına göre Türk Gümrük Tarife Cetvelinin yapısına ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Gümrük tarife istatistik pozisyonu, Türk Gümrük Tarife Cetvelinde on rakamdan oluşan pozisyondur.",
c=["Tarife pozisyonu, fasıla ilişkin ilk iki rakamdan sonra gelen iki rakamla birlikte dörtlü rakamlarla ifade edilen gruplardır.",
   "Tarife alt pozisyonu, pozisyon numarasını izleyen iki rakam ile birlikte altılı rakamlarla ifade edilen gruplardır.",
   "Fasıl, bölümlerden daha alt düzeyde ve bölümlere nazaran daha çok birbirine benzeyen aynı nitelikteki eşyayı içine alır.",
   "Türk Gümrük Tarife Cetveli, eşyanın cins ve niteliklerine göre sistematik bir şekilde numaralandırılarak sınıflandırıldığı cetveldir."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre gümrük tarife istatistik pozisyonu, Türk Gümrük Tarife Cetvelinde on iki rakamdan oluşan pozisyondur; 'on rakam' ifadesi yanlıştır. Tarife pozisyonu fasıla ilişkin ilk iki rakamdan sonra gelen iki rakamla birlikte dört rakamlı, tarife alt pozisyonu ise pozisyon numarasını izleyen iki rakamla birlikte altı rakamlı gruplardır. Fasıl bölümlerden daha alt düzeyde ve bölümlere nazaran daha çok birbirine benzeyen aynı nitelikteki eşyayı içine alır; Türk Gümrük Tarife Cetveli de eşyanın cins ve niteliklerine göre sistematik bir şekilde numaralandırılarak sınıflandırıldığı cetveldir. Sayıyı yaklaşık bilen aday, on iki rakamlı istatistik pozisyonunu on rakamlı sanarak yanlış ifadeyi doğru kabul eder. Bu nedenle doğru cevap 'Gümrük tarife istatistik pozisyonu, Türk Gümrük Tarife Cetvelinde on rakamdan oluşan pozisyondur.' seçeneğidir. (MD GY 32)",
kanit="9-TAR.POZ.AYIRMA.txt | Türk Gümrük Tarife Cetvelinde, oniki rakamdan oluşan pozisyonu || 9-TAR.POZ.AYIRMA.txt | Türk Gümrük Tarife Cetvelinde fasıla ilişkin ilk iki rakamdan sonra gelen iki rakamla birlikte dörtlü rakamlarla ifade edilen grupları || 9-TAR.POZ.AYIRMA.txt | pozisyon numarasını izleyen iki rakam ile birlikte altılı rakamlarla ifade edilen grupları || 9-TAR.POZ.AYIRMA.txt | Bölümlerden daha alt düzeyde ve bölümlere nazaran daha çok birbirine benzeyen aynı nitelikteki eşyayı içine alan || 9-TAR.POZ.AYIRMA.txt | Eşyanın cins ve niteliklerine göre sistematik bir şekilde numaralandırılarak sınıflandırıldığı",
yuva=["Tarife pozisyonu tanımı (doğru ifade)",
      "Tarife alt pozisyonu tanımı (doğru ifade)",
      "Fasıl tanımı (doğru ifade)",
      "Türk Gümrük Tarife Cetveli tanımı (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["SAYI", "YAKIN-SAYI", "TERSİNE"],
duzey=["HATIRLAMA"],
profil=[2, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2025/28",
kapsamli=False,
),

# 16 — Seri No: 6 md. 5/2, 6: Açıklama Notlarına uymayan BTB'lerin geçersizlik anı (eksen 14)
dict(
konu=K, blok="SB09",
kalip="SÜRE", z="O",
madde="Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 6) md. 5, 6",
cek="Açıklama Notlarına uymayan BTB'ler, yayımı tarihinde yürürlüğe giren Tebliğin yürürlüğe girdiği tarihten itibaren geçerliliğini yitirir.",
kok=["Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 6)'ya göre bu Tebliğ eki Gümrük Tarife Cetveli Açıklama Notlarına uymayan Bağlayıcı Tarife Bilgileri hangi tarihten itibaren geçerliliğini yitirir?"],
d="Tebliğin yürürlüğe girdiği tarihten itibaren",
c=["Tebliğin yürürlüğe girdiği tarihten itibaren altı aylık sürenin sonunda",
   "Açıklama Notlarına uymadığının hak sahibine tebliğ edildiği tarihten itibaren",
   "Gümrük idaresince iptal kararının verildiği tarihten itibaren",
   "Bağlayıcı Tarife Bilgisinin veriliş tarihinden itibaren altı yıllık sürenin sonunda"],
sirali=False,
g="Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 6)'ya göre bu Tebliğ eki Açıklama Notlarına uymayan Bağlayıcı Tarife Bilgileri, Gümrük Kanunu'nun bağlayıcı tarife bilgisinin geçerliliğini kaybetmesine ilişkin hükmü uyarınca Tebliğin yürürlüğe girdiği tarihten itibaren geçerliliğini yitirir. Tebliğ yayımı tarihinde yürürlüğe girdiğinden geçersizlik anı yayım tarihiyle aynıdır; ayrıca bir tebligat veya iptal kararı beklenmez. En güçlü çeldirici altı aylık süre seçeneğidir: Gümrük Kanunu'na göre altı ay, geçerliliğini kaybeden bilgiye dayanarak bağlayıcı sözleşme yapmış hak sahibinin bu bilgiyi kullanabileceği süredir; bilginin geçersiz hâle geldiği anı değiştirmez. Altı yıl bağlayıcı tarife bilgisinin olağan geçerlilik süresidir; iptal kararının verildiği tarih ise yanlış veya eksik bilgiye dayanan bilginin iptaline ilişkindir. Bu nedenle doğru cevap 'Tebliğin yürürlüğe girdiği tarihten itibaren' seçeneğidir. (MD Seri No: 6 Tebliği 5-6)",
kanit="9-TAR.POZ.AYIRMA.txt | Bu Tebliğ eki Gümrük Tarife Cetveli Açıklama Notlarına uymayan Bağlayıcı Tarife Bilgileri 4458 sayılı Gümrük Kanununun 9 uncu maddesinin beşinci fıkrası uyarınca bu Tebliğin yürürlüğe girdiği tarihten itibaren geçerliliğini yitirir. || 9-TAR.POZ.AYIRMA.txt | Bu Tebliğ yayımı tarihinde yürürlüğe girer. || 7-BİLGİ.txt | söz konusu yayımın ya da tebligatın yapıldığı tarihten itibaren altı aylık bir süre boyunca kullanabilir || 7-BİLGİ.txt | Bağlayıcı tarife bilgisi veriliş tarihinden itibaren altı yıl || 7-BİLGİ.txt | iptal, iptal kararının verildiği tarihten itibaren hüküm ifade eder",
yuva=["Gümrük Kanunu: geçerliliğini kaybeden bilginin bağlayıcı sözleşme varsa altı ay kullanılabilmesi",
      "Gümrük Kanunu: bağlayıcı tarife bilgisinin iptal veya değiştirildiğinin bilgi verilen kişiye tebliği ile geçerlilik kaybı",
      "Tarife Seri No: 14 Tebliği: yanlış veya eksik bilgiye dayanan BTB iptalinin iptal kararı tarihinden hüküm ifade etmesi",
      "Gümrük Kanunu: bağlayıcı tarife bilgisinin veriliş tarihinden itibaren altı yıl geçerliliği"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU", "YAKIN-SAYI"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=True,
eksen=14, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 17 — Seri No: 6 md. 4-7: Ek Not, AS İzahnamesi, kaldırılan tebliğ, yürürlük, yürütme
dict(
konu=K, blok="SB09",
kalip="YANLIŞ", z="O",
madde="Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 6) md. 4, 5, 6, 7",
cek="Seri No: 6'da Ek Not, TGTC'nin hazırlanmasında esas alınan Avrupa Birliği Kombine Nomanklatürü Notlarıdır; Seri No: 3 kaldırılmış, Tebliği Ticaret Bakanı yürütür.",
kok=["Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 6)'nın tanımlarına ve yürürlüğe ilişkin hükümlerine göre aşağıdakilerden hangisi yanlıştır?"],
d="Ek Not, Türk Gümrük Tarife Cetvelinin hazırlanmasında esas alınan ve pozisyonlara ilişkin açıklamalar getiren Dünya Gümrük Örgütü Sınıflandırma Kararlarıdır.",
c=["Armonize Sistem İzahnamesi, Uyumu sağlanmış (Armonize) Mal Tanımı ve Kodlama Sistemi Hakkında Uluslararası Sözleşme eki Armonize Sistem Nomanklatürü İzahnamesidir.",
   "Bu Tebliğ ile Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 3) yürürlükten kaldırılmıştır.",
   "Tebliğ, yayımı tarihinde yürürlüğe girer.",
   "Tebliğ hükümlerini Ticaret Bakanı yürütür."],
sirali=False,
g="Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 6)'ya göre Ek Not; Armonize Sistem bölüm, fasıl ve alt pozisyon notları ile birlikte Türk Gümrük Tarife Cetvelinin hazırlanmasında esas alınan ve pozisyon ve alt pozisyonlara ilişkin açıklamalar getiren Avrupa Birliği Kombine Nomanklatürü Notlarıdır; Dünya Gümrük Örgütü Sınıflandırma Kararları değildir. Dünya Gümrük Örgütü Sınıflandırma Kararları, Bağlayıcı Tarife Bilgisi değerlendirmesinde dikkate alınan kaynaklar arasında sayılır. Aynı Tebliğe göre Armonize Sistem İzahnamesi, Uyumu sağlanmış (Armonize) Mal Tanımı ve Kodlama Sistemi Hakkında Uluslararası Sözleşme eki Armonize Sistem Nomanklatürü İzahnamesidir; Tebliğ Seri No: 3 Tebliğini yürürlükten kaldırmış, yayımı tarihinde yürürlüğe girmiş ve yürütmesi Ticaret Bakanına verilmiştir. Bu nedenle doğru cevap 'Ek Not, Türk Gümrük Tarife Cetvelinin hazırlanmasında esas alınan ve pozisyonlara ilişkin açıklamalar getiren Dünya Gümrük Örgütü Sınıflandırma Kararlarıdır.' seçeneğidir. (MD Seri No: 6 Tebliği 4-7)",
kanit="9-TAR.POZ.AYIRMA.txt | Türk Gümrük Tarife Cetvelinin hazırlanmasında esas alınan ve pozisyon ve alt pozisyonlara ilişkin açıklamalar getiren Avrupa Birliği Kombine Nomanklatürü Notlarını || 9-TAR.POZ.AYIRMA.txt | Uyumu sağlanmış (Armonize) Mal Tanımı ve Kodlama Sistemi Hakkında Uluslararası Sözleşme eki Armonize Sistem Nomanklatürü İzahnamesini || 9-TAR.POZ.AYIRMA.txt | Gümrük Genel Tebliği (Gümrük Tarife Cetveli Açıklama Notları) (Seri No: 3) yürürlükten kaldırılmıştır. || 9-TAR.POZ.AYIRMA.txt | Bu Tebliğ hükümlerini Ticaret Bakanı yürütür. || 7-BİLGİ.txt | DGÖ Sınıflandırma Kararlarını",
yuva=["Seri No: 6 Tebliğinde Armonize Sistem İzahnamesi tanımı (doğru ifade)",
      "Seri No: 6 Tebliğinde yürürlükten kaldırılan düzenleme (doğru ifade)",
      "Seri No: 6 Tebliğinin yürürlük hükmü (doğru ifade)",
      "Seri No: 6 Tebliğinin yürütme hükmü (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"],
duzey=["TANIMA"],
profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 18 — GK 15/6: "eşyanın tarife pozisyonunun belirlenmesi" deyimi
dict(
konu=K, blok="SB09",
kalip="DOĞRU", z="Z",
madde="4458 sayılı Gümrük Kanunu md. 15",
cek="Tarife pozisyonunun belirlenmesi; TGTC veya ona dayanan cetvellerin ve tarife dışı önlemler için Cumhurbaşkanı Kararıyla oluşturulan cetvelin alt açılımlarının belirlenmesidir.",
kok=["4458 sayılı Gümrük Kanunu'nda yer alan \"eşyanın tarife pozisyonunun belirlenmesi\" deyimine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Özel alanlara ait eşya ticaretine ilişkin tarife dışı önlemlerin uygulanması amacıyla Cumhurbaşkanı Kararı ile oluşturulan bir cetvelin alt açılımlarının belirlenmesini de kapsar.",
c=["Yalnızca Türk Gümrük Tarife Cetvelinin alt açılımlarının belirlenmesini ifade eder; bu cetvele dayanan diğer cetveller kapsam dışındadır.",
   "Eşyanın tabi olduğu gümrük vergisi oranının belirlenmesini ifade eder.",
   "Eşyanın girdiği bölüm ve faslın belirlenmesiyle sınırlıdır; alt açılımların belirlenmesini kapsamaz.",
   "Eşyanın girdiği alt açılım, yürürlükteki hükümlerden bağımsız olarak beyan sahibinin talebine göre belirlenir."],
sirali=False,
g="Gümrük Kanunu'na göre eşyanın tarife pozisyonunun belirlenmesi deyiminden, yürürlükteki hükümlere uygun olarak eşyanın girdiği; Türk Gümrük Tarife Cetvelinin veya gümrük tarifesinin kapsadığı diğer cetvelin alt açılımlarının ve tamamen veya kısmen Türk Gümrük Tarifesine dayanan ya da bu cetvele alt açılımlar ekleyen, özel alanlara ait eşya ticaretine ilişkin tarife dışı önlemlerin uygulanması amacıyla Cumhurbaşkanı Kararı ile oluşturulan bir diğer cetvelin alt açılımlarının belirlenmesi anlaşılır. Deyim yalnızca Türk Gümrük Tarife Cetveli ile sınırlı değildir; bölüm ve fasıl düzeyinde de kalmaz, alt açılımlara iner. Vergi oranı gümrük tarifesinin kapsadığı ayrı bir unsurdur; belirleme de beyan sahibinin talebine göre değil, yürürlükteki hükümlere uygun olarak yapılır. En güçlü çeldirici 'yalnızca Türk Gümrük Tarife Cetveli' ifadesini taşıyan seçenektir: Kanun diğer cetvellerin alt açılımlarını da deyime dahil eder. Bu nedenle doğru cevap 'Özel alanlara ait eşya ticaretine ilişkin tarife dışı önlemlerin uygulanması amacıyla Cumhurbaşkanı Kararı ile oluşturulan bir cetvelin alt açılımlarının belirlenmesini de kapsar.' seçeneğidir. (MD GK 15)",
kanit="9-TAR.POZ.AYIRMA.txt | Eşyanın tarife pozisyonunun belirlenmesi deyiminden, yürürlükteki hükümlere uygun olarak, söz konusu eşyanın girdiği; || 9-TAR.POZ.AYIRMA.txt | Türk Gümrük Tarife Cetvelinin veya 3 üncü fıkranın (b) bendinde öngörülen diğer cetvelin alt açılımlarının || 9-TAR.POZ.AYIRMA.txt | özel alanlara ait eşya ticaretine ilişkin tarife dışı önlemlerin uygulanması amacıyla",
yuva=["Deyimin ilk unsuru: TGTC 'veya' diğer cetvelin alt açılımları (mutlaklaştırılmış)",
      "Gümrük tarifesinin kapsadığı gümrük vergi oranları (komşu fıkra)",
      "Yönetmelikteki bölüm ve fasıl tanımları (alt açılım unsuru düşürülmüş)",
      "Tercihli tarifede beyan sahibinin talep imkânı; 'yürürlükteki hükümlere uygun olarak' kaydı tersine çevrilmiş"],
yakinlik="BİREBİR",
tuzak=["MUTLAK", "KOMŞU", "UNSUR"],
duzey=["AYIRT"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 19 — GY 32/n: TGTC'deki vergi oranlarının yer aldığı kanun (dayanak; sayısal sıralı)
dict(
konu=K, blok="SB09",
kalip="DAYANAK", z="O",
madde="Gümrük Yönetmeliği md. 32",
cek="TGTC'de gösterilen gümrük vergisi oranları 474 sayılı Gümrük Giriş Tarife Cetveli Hakkında Kanunda yer alır.",
kok=["Gümrük Yönetmeliği'nin gümrük tarifesi uygulamasına ilişkin tanımlarına göre, eşyanın cins ve niteliklerine göre sistematik bir şekilde numaralandırılarak sınıflandırıldığı cetvelde gösterilen gümrük vergisi oranları aşağıdaki kanunlardan hangisinde yer almaktadır?"],
d="474 sayılı Gümrük Giriş Tarife Cetveli Hakkında Kanun",
c=["213 sayılı Vergi Usul Kanunu", "492 sayılı Harçlar Kanunu", "4458 sayılı Gümrük Kanunu", "4760 sayılı Özel Tüketim Vergisi Kanunu"],
sirali=True,
siklar=["213 sayılı Vergi Usul Kanunu", "474 sayılı Gümrük Giriş Tarife Cetveli Hakkında Kanun", "492 sayılı Harçlar Kanunu", "4458 sayılı Gümrük Kanunu", "4760 sayılı Özel Tüketim Vergisi Kanunu"],
g="Gümrük Yönetmeliği'ne göre Türk Gümrük Tarife Cetveli, eşyanın cins ve niteliklerine göre sistematik bir şekilde numaralandırılarak sınıflandırıldığı ve 474 sayılı Gümrük Giriş Tarife Cetveli Hakkında Kanunda yer alan gümrük vergisi oranlarının gösterildiği cetveldir. Dolayısıyla cetvelde gösterilen gümrük vergisi oranlarının yer aldığı kanun 474 sayılı Kanundur. En güçlü çeldirici 4458 sayılı Gümrük Kanunu'dur: Gümrük Kanunu gümrük vergilerinin yükümlülüğün başladığı tarihte yürürlükte olan gümrük tarifesine göre hesaplanacağını ve tarifenin kapsamını düzenler; Yönetmelik ise oranların yer aldığı kanun olarak 474 sayılı Kanunu gösterir. Vergi Usul, Harçlar ve Özel Tüketim Vergisi Kanunları gümrük mevzuatının başka bölümlerinde atıf yapılan kanunlardır. Bu nedenle doğru cevap '474 sayılı Gümrük Giriş Tarife Cetveli Hakkında Kanun' seçeneğidir. (MD GY 32)",
kanit="9-TAR.POZ.AYIRMA.txt | Eşyanın cins ve niteliklerine göre sistematik bir şekilde numaralandırılarak sınıflandırıldığı ve 474 sayılı Gümrük Giriş Tarife Cetveli Hakkında Kanunda yer alan gümrük vergisi oranlarının gösterildiği || 9-TAR.POZ.AYIRMA.txt | Gümrük vergileri, gümrük yükümlülüğünün başladığı tarihte yürürlükte olan gümrük tarifesine göre hesaplanır.",
yuva=["Gümrük mevzuatının başka bölümlerinde atıf yapılan vergi usulü kanunu",
      "Gümrük mevzuatının başka bölümlerinde atıf yapılan harçlar kanunu",
      "Gümrük vergilerinin tarifeye göre hesaplanmasını ve tarifenin kapsamını düzenleyen Kanun",
      "Gümrük mevzuatının başka bölümlerinde atıf yapılan özel tüketim vergisi kanunu"],
yakinlik="BİREBİR",
tuzak=["TERİM", "SAĞDUYU"],
duzey=["HATIRLAMA"],
profil=[1, 2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 20 — GY 32/d + Seri No: 4 md. 4/d: fasıl ve Armonize Sistem Kodu (iki bilgi birlikte)
dict(
konu=K, blok="SB09",
kalip="ORAN-TUTAR", z="O",
madde="Gümrük Yönetmeliği md. 32; Gümrük Genel Tebliği (Gümrük Tarife Cetveli İzahnamesi) (Seri No: 4) md. 4",
cek="Fasıl, altı basamaklı Armonize Sistem Kodunun ilk iki rakamıyla ifade edilir.",
kok=["Gümrük Yönetmeliği ve Gümrük Genel Tebliği (Gümrük Tarife Cetveli İzahnamesi) (Seri No: 4)'e göre fasıl, Armonize Sistem Kodunun ilk kaç rakamıyla ifade edilir ve bu kod kaç basamaktan oluşur?"],
d="İlk iki rakamıyla – altı basamaktan",
c=["İlk iki rakamıyla – dört basamaktan",
   "İlk iki rakamıyla – on iki basamaktan",
   "İlk dört rakamıyla – altı basamaktan",
   "İlk dört rakamıyla – on iki basamaktan"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre fasıl, bölümlerden daha alt düzeyde ve bölümlere nazaran daha çok birbirine benzeyen aynı nitelikteki eşyayı içine alan ve altı basamaklı Armonize Sistem Kodunun ilk iki rakamını ifade eden kısımdır; Seri No: 4 Tebliği de faslı, altı basamaklı rakamdan oluşan Armonize Sistem Kodunun ilk iki rakamıyla ifade edilen kısımlar olarak tanımlar. Dört rakam tarife pozisyonuna, altı rakam tarife alt pozisyonuna, on iki rakam ise gümrük tarife istatistik pozisyonuna aittir. En güçlü çeldirici 'İlk iki rakamıyla – on iki basamaktan' seçeneğidir: fasıl rakamını bilen ancak Armonize Sistem Kodunu on iki rakamlı gümrük tarife istatistik pozisyonuyla karıştıran adayı yakalar. Bu nedenle doğru cevap 'İlk iki rakamıyla – altı basamaktan' seçeneğidir. (MD GY 32; Seri No: 4 Tebliği 4)",
kanit="9-TAR.POZ.AYIRMA.txt | altı basamaklı Armonize Sistem Kodunun ilk iki rakamını || 9-TAR.POZ.AYIRMA.txt | altı basamaklı rakamdan oluşan Armonize Sistem Kodunun ilk iki rakamıyla ifade edilen kısımları || 9-TAR.POZ.AYIRMA.txt | Türk Gümrük Tarife Cetvelinde, oniki rakamdan oluşan pozisyonu",
yuva=["Dört rakam tarife pozisyonuna aittir; fasıl rakamı doğru, kod uzunluğu yanlış",
      "On iki rakam gümrük tarife istatistik pozisyonuna aittir; fasıl rakamı doğru, kod uzunluğu yanlış",
      "Dört rakam tarife pozisyonuna aittir; kod uzunluğu doğru, fasıl rakamı yanlış",
      "Dört rakam tarife pozisyonuna, on iki rakam istatistik pozisyonuna aittir"],
yakinlik="BİREBİR",
tuzak=["SAYI", "YAKIN-SAYI", "TERİM"],
duzey=["HATIRLAMA"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

]
