# Soru Bankası — Bölüm 10: Menşe (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
Q = [

# 1 ---------------- GK 17: tercihli olmayan menşein belirlenme amaçları ----------------
dict(
konu="Menşe", blok="SB10",
kalip="KAPSAM",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 17, 22",
cek="Tercihli olmayan menşe; tercihli uygulamalar hariç TGT, tarife dışı Cumhurbaşkanı Kararı önlemleri ve menşe şahadetnamelerinin hazırlanıp verilmesi amacıyla belirlenir.",
kok=["4458 sayılı Gümrük Kanunu'na göre aşağıdakilerden hangisi, eşyanın tercihli olmayan menşeinin belirlenme amaçları arasında yer alır?"],
d="Menşe şahadetnamelerinin hazırlanması ve verilmesi",
c=["A.TR dolaşım belgelerinin hazırlanması ve verilmesi",
   "EUR.1 dolaşım sertifikalarının hazırlanması ve verilmesi",
   "Serbest ticaret anlaşmaları çerçevesindeki tarife uygulamalarından yararlandırılma",
   "Genelleştirilmiş Tercihler Sistemi çerçevesindeki tarife uygulamalarından yararlandırılma"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre eşyanın tercihli olmayan menşei üç amaçla belirlenir: tercihli tarife uygulamaları hariç olmak üzere Türk Gümrük Tarifesinin uygulanması, eşya ticaretine ilişkin tarife önlemleri dışında Cumhurbaşkanı Kararı ile oluşturulan önlemlerin uygulanması ve menşe şahadetnamelerinin hazırlanması ve verilmesi. Bu yüzden menşe şahadetnamesi, eşyanın tercihli olmayan menşeini gösteren belgedir. Serbest ticaret anlaşmaları ve Genelleştirilmiş Tercihler Sistemi çerçevesindeki tarife uygulamaları tercihli tarife uygulamalarıdır; bunlarda eşyanın tercihli menşei aranır ve tercihli menşe kuralları anlaşmalarla veya Cumhurbaşkanı Kararı ile belirlenir. En güçlü çeldirici EUR.1 dolaşım sertifikasıdır: Dahilde İşleme Rejimi Tebliği bu belgeyi, anlaşmalar çerçevesinde tercihli rejimden yararlanmak üzere malın menşeini belirleyen menşe ispat belgeleri arasında sayar; yani o da bir menşe belgesidir, ancak tercihli menşei gösterir. A.TR dolaşım belgesi ise serbest dolaşımdaki eşyanın Katma Protokoldeki tercihli rejimden yararlanmasını sağlar. Bu nedenle doğru cevap 'Menşe şahadetnamelerinin hazırlanması ve verilmesi' seçeneğidir. (MD GK 17, 22; GY 205; DİR Tebliği 3)",
kanit="10-MENŞEİ.txt | Menşe şahadetnamelerinin hazırlanması ve verilmesi, || 10-MENŞEİ.txt | Amaçları ile bu Kanunun 18 ila 21 inci maddelerindeki hükümler çerçevesinde belirlenir || 10-MENŞEİ.txt | Serbest ticaret anlaşmaları veya Genelleştirilmiş Tercihler Sistemi çerçevesinde tercihli tarife uygulamasının || 32-DAHİLDE İŞLEME.txt | malın menşeini belirleyen EUR.1 dolaşım sertifikası",
yuva=["DİR Tebliği tanımlar: A.TR dolaşım belgesi, serbest dolaşımdaki eşyanın Katma Protokoldeki tercihli rejimden yararlanmasını sağlar",
      "DİR Tebliği tanımlar: EUR.1, anlaşmalar çerçevesinde tercihli rejim için malın menşeini belirleyen menşe ispat belgesi",
      "GK 22/a ve GY 205/4-b: serbest ticaret anlaşmaları çerçevesindeki tercihli tarife; tercihli menşe kuralları anlaşmalarla belirlenir",
      "GK 22/b ve GY 205/4-b: GTS çerçevesindeki tercihli tarife; tercihli menşe kuralları Cumhurbaşkanı Kararı ile belirlenir"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU", "SAĞDUYU"], duzey=["AYIRT"], profil=[3],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2024/68", kapsamli=False,
),

# 2 ---------------- GK 21: düzenleme ve ek kanıt mercii ----------------
dict(
konu="Menşe", blok="SB10",
kalip="DAYANAK",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 21",
cek="Menşe şahadetnamesi aranacak hâller, şekli ve içereceği bilgiler yönetmelikle belirlenir; ciddi şüphede ek kanıtı gümrük idareleri ister.",
kok=["4458 sayılı Gümrük Kanunu'na göre, menşe şahadetnamesi aranacak hâller ile şahadetnamelerin şekli ve içereceği bilgilere ilişkin usul ve esasların belirlendiği düzenleme ile menşe şahadetnamesinin ibrazına rağmen ciddi bir şüphe durumunda ek kanıtları istemeye yetkili merci aşağıdakilerin hangisinde sırasıyla doğru olarak verilmiştir?"],
d="Yönetmelik – Gümrük idareleri",
c=["Cumhurbaşkanı Kararı – Gümrük idareleri",
   "Yönetmelik – Bakanlık",
   "Bakanlıkça çıkarılan tebliğ – Gümrük idareleri",
   "Cumhurbaşkanı Kararı – Bakanlık"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre menşe şahadetnamesi aranacak hâller ile menşe şahadetnamelerinin şekli ve içereceği bilgilere ilişkin usul ve esaslar yönetmelikle belirlenir; menşe şahadetnamesinin ibrazına rağmen ciddi bir şüphe durumunda ek kanıtları istemeye gümrük idareleri yetkilidir. Cumhurbaşkanı Kararı Kanunda, eşya ticaretine ilişkin tarife önlemleri dışındaki önlemlerin ve anlaşmalar dışında kalan tercihli tarife uygulamalarından yararlanan eşyanın tercihli menşe kurallarının dayanağı olarak geçer; menşe şahadetnamesinin usul ve esaslarının dayanağı değildir. Bakanlık (Yönetmelik metninde Müsteşarlık) ise gümrük idaresinin incelemesine rağmen tereddüt devam ettiğinde şahadetnamenin sonradan kontrol talebiyle gönderildiği mercidir. En güçlü çeldirici 'Yönetmelik – Bakanlık' seçeneğidir: düzenleme doğru, ancak ek kanıt isteme yetkisi doğrudan gümrük idarelerine aittir. Bu nedenle doğru cevap 'Yönetmelik – Gümrük idareleri' seçeneğidir. (MD GK 17, 21, 22; GY 41)",
kanit="10-MENŞEİ.txt | Menşe şahadetnamesi aranacak haller ile menşe şahadetnamelerinin şekli ve içereceği bilgilere ilişkin usul ve esaslar yönetmelikle belirlenir || 10-MENŞEİ.txt | Menşe şahadetnamesinin ibrazına rağmen ciddi bir şüphe durumunda, ek kanıtları isteme konusunda gümrük idareleri yetkilidir",
yuva=["GK 17/b ve 22/b: Cumhurbaşkanı Kararı, tarife dışı önlemlerin ve tercihli menşe kurallarının dayanağı",
      "GY 41/2: tereddüt sürerse şahadetname sonradan kontrol talebiyle Müsteşarlığa (Bakanlık) gönderilir",
      "DİR Tebliği: menşe ispat belgeleri bir Bakanlık tebliğinde tanımlanır (sağduyu çeldiricisi)",
      "GK 22/b ve GY 41/2: iki komşu dayanak ve merci birlikte"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"], duzey=["HATIRLAMA"], profil=[3],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 3 ---------------- GK 18: tümüyle elde edilme — kara suları ve deniz ürünleri (klasik; vakadan çevrildi) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="DOĞRU",
z="Z",
madde="4458 sayılı Gümrük Kanunu md. 18",
cek="Tümüyle elde edilmede ülke ifadesi kara sularını kapsar; bandıra ölçütü kara suları dışındaki denizlere, deniz dibi münhasır işletme hakkına bağlıdır.",
kok=["4458 sayılı Gümrük Kanunu'nun tümüyle bir ülkede elde edilen veya üretilen eşyaya ilişkin hükümlerine göre aşağıdakilerden hangisi doğrudur?"],
d="Tümüyle bir ülkede elde edilen veya üretilen eşyanın belirlenmesinde ülke ifadesi, o ülkenin kara sularını da kapsar.",
c=["Bir ülkede kayıtlı olup o ülkenin bandırasını taşıyan araçlarca başka bir ülkenin kara sularında avlanan ürünler, bandıra ülkesinde tümüyle elde edilmiş sayılır.",
   "Fabrika gemilerinde, kara suları dışındaki denizlerden çıkartılan av ürünlerinden elde edilen eşya, geminin bulunduğu denize kıyısı olan ülkede tümüyle elde edilmiş sayılır.",
   "Bir ülkenin kara suları dışındaki denizlerin dibinden çıkartılan ürünler, münhasır işletme hakkı aranmaksızın o ülkede tümüyle elde edilmiş sayılır.",
   "Sadece hammadde elde etmek için bir ülkede toplanan atık ve artıklar, o ülkede tümüyle elde edilmiş eşya sayılmaz."],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre tümüyle bir ülkede elde edilen veya üretilen eşyanın sayıldığı hükmün uygulanmasında ülke ifadesi o ülkenin kara sularını da kapsar. Bu nedenle bir ülkenin kara sularında tutulan ve avlanan balıkçılık ürünleri o ülkede tutulmuş sayılır ve geminin bandırası sonucu değiştirmez. Bandıra ölçütü yalnızca o ülkede kayıtlı veya tescilli olup o ülkenin bandırasını taşıyan araçlarca herhangi bir ülkenin kara suları dışındaki denizlerden çıkartılan av ürünleri ve diğer deniz ürünleri için geçerlidir; başka bir ülkenin kara sularında yapılan avı bandıra ülkesine bağlayan ifade bu kaydı yok saymaktadır. Fabrika gemilerinde bu ürünlerden elde edilen eşya da kıyı ülkesine değil, geminin kayıtlı olduğu ve bandırasını taşıdığı ülkeye bağlanır. Kara suları dışındaki denizlerin dibinden çıkartılan ürünlerin o ülke menşeli sayılması, o ülke tarafından münhasır işletme hakkına sahip olarak çıkartılmalarına bağlıdır. Sadece hammadde elde etmek için o ülkede toplanan atık ve artıklar ise tümüyle elde edilen eşya sayımında açıkça yer alır. En güçlü çeldirici bandıra ülkesine ilişkin ifadedir: 'kara suları dışındaki' kaydı düşürüldüğünde akla yatkın görünür. Bu nedenle doğru cevap 'Tümüyle bir ülkede elde edilen veya üretilen eşyanın belirlenmesinde ülke ifadesi, o ülkenin kara sularını da kapsar.' seçeneğidir. (MD GK 18)",
kanit="10-MENŞEİ.txt | 2 nci fıkranın uygulanmasında ülke ifadesi o ülkenin kara sularını da kapsar || 10-MENŞEİ.txt | O ülkede tutulan ve avlanan balıkçılık ve avcılık ürünleri || 10-MENŞEİ.txt | O ülkede kayıtlı veya tescilli olup, o ülkenin bandırasını taşıyan araçlar tarafından herhangi bir ülkenin kara suları dışındaki denizlerden çıkartılan av ürünleri ve diğer deniz ürünleri || 10-MENŞEİ.txt | Söz konusu ülkede kayıtlı ya da tescilli olan ve ülkenin bandırasını taşıyan, fabrika gemilerde (f) bendinde öngörülen ürünlerden elde edilen eşya || 10-MENŞEİ.txt | O ülkenin kara suları dışındaki denizlerin dibinden ya da deniz dibindeki toprağın altından münhasır işletme hakkına sahip olarak o ülke tarafından çıkartılan ürünler || 10-MENŞEİ.txt | Sadece hammadde elde etmek için o ülkede toplanan, imalat işlemlerinden veya kullanım kalıntılarından elde edilen atık ve artıklar",
yuva=["GK 18/2-f: bandıra ölçütü kara suları dışındaki denizlerden çıkartılan ürünlere aittir; 'dışındaki' kaydı düşürülmüş",
      "GK 18/2-g: fabrika gemisinde elde edilen eşya geminin kayıtlı olduğu ve bandırasını taşıdığı ülkeye bağlanır; kıyı ülkesine taşınmış",
      "GK 18/2-h: deniz dibinden çıkartılan ürünlerde münhasır işletme hakkı şartı düşürülmüş",
      "GK 18/2-ı: hammadde elde etmek için toplanan atık ve artıklar sayımda yer alır; tersine çevrilmiş"],
yakinlik="BİREBİR",
tuzak=["UNSUR", "KOMŞU", "TERSİNE"], duzey=["AYIRT"], profil=[3, 1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2024/33; 2025/47", kapsamli=False,
),

# 4 ---------------- GK 18-20, GY 34: tümüyle elde ↔ esaslı işçilik ↔ yetersiz işlem ----------------
dict(
konu="Menşe", blok="SB10",
kalip="ÖNERMELİ",
z="Z",
madde="4458 sayılı Gümrük Kanunu md. 18, 19, 20; Gümrük Yönetmeliği md. 34",
cek="Başka ülke girdisiyle üretim tümüyle elde değildir; esaslı işçilik en son ve donanımlı işletmede; basit montaj yetersiz; kanaat de menşei engeller.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'nin eşyanın tercihli olmayan menşeinin belirlenmesine ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Bir ülkede başka bir ülke menşeli girdiler kullanılarak üretilen eşya, o ülkede tümüyle elde edilen veya üretilen eşya sayılır.",
     "II. Üretimi birden fazla ülkede gerçekleştirilen eşyanın bir ülke menşeli sayılabilmesi için, o ülkede yeni bir ürün imal edilmesi veya imalatın önemli bir aşamasının ve ekonomik yönden gerekli görülen en son esaslı işçilik ve eylemin o ülkede bu amaçla donatılmış işletmelerde yapılması gerekir.",
     "III. Tekstil ürünlerinde, tamamlanmış bir ürün oluşturmak üzere parçaların basit montajı, pozisyon değişikliği koşulunun sağlanıp sağlanmadığına bakılmaksızın yetersiz işçilik veya işlem olarak kabul edilir.",
     "IV. Esas amacının, Türkiye tarafından belirli ülkelerin eşyasına uygulanan hükümleri aşmak olduğu kesin olarak tespit edilmedikçe, yapılan araştırma sonucunda yalnızca bu yönde bir kanaat oluşması eşyanın o ülke menşeli sayılmasına engel olmaz.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve III",
c=["Yalnız III", "I ve II", "I, II ve III", "II, III ve IV"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre bir ülkede tümüyle elde edilen veya üretilen eşya kapalı bir sayımla belirlenmiştir: o ülkede çıkarılan, toplanan, doğup yetiştirilen, avlanan ürünler, sayılan eşyadan üretimin herhangi bir aşamasında elde edilen eşya ve türevleri gibi. Başka ülke menşeli girdilerle üretilen eşya bu sayımda yer almaz; böyle bir eşya üretimi birden fazla ülkede gerçekleştirilen eşyadır ve ancak esaslı işçilik kuralıyla menşe kazanabilir (I yanlış). Esaslı işçilik kuralına göre o ülkede yeni bir ürün imal edilmesi veya imalatın önemli bir aşamasının ve ekonomik yönden gerekli görülen en son esaslı işçilik ve eylemin o ülkede bu amaçla donatılmış işletmelerde yapılması gerekir (II doğru). Gümrük Yönetmeliği'ne göre tekstil ürünlerinde tamamlanmış bir ürün oluşturmak üzere parçaların basit montajı, pozisyon değişikliği koşulunun sağlanıp sağlanmadığına bakılmaksızın yetersiz işçilik veya işlemdir (III doğru). Kanuna göre esas amacının belirli ülkelerin eşyasına uygulanan hükümleri aşmak olduğu tespit edilen veya yapılan araştırma sonucunda hakkında bu yönde bir kanaat oluşan işçilik ya da işlemle üretilen eşya o ülke menşeli sayılmaz; kesin tespit aranmaz, kanaat de yeterlidir (IV yanlış). En güçlü tuzak IV'tür: hükümdeki 'veya ... kanaat oluşan' kaydı, kanaati tespitle aynı sonuca bağlar. Bu nedenle doğru cevap 'II ve III' seçeneğidir. (MD GK 18, 19, 20; GY 34)",
kanit="10-MENŞEİ.txt | Yukarıdaki bentlerde sayılan eşyadan üretimin herhangi bir aşamasında elde edilen eşya || 10-MENŞEİ.txt | Üretimi birden fazla ülkede gerçekleştirilen eşyanın bir ülke menşeli sayılabilmesi için, o ülkede yeni bir ürün imal edilmesi veya imalatın önemli bir aşamasının ve ekonomik yönden gerekli görülen en son esaslı işçilik ve eylemin o ülkede bu amaçla donatılmış işletmelerde yapılması gerekir || 10-MENŞEİ.txt | Tamamlanmış bir ürün oluşturmak üzere parçaların basit montajı || 10-MENŞEİ.txt | tespit edilen veya yapılan araştırma sonucunda hakkında bu yönde bir kanaat oluşan bir işçilik veya işlemle üretilmiş eşya",
yuva=["Yalnız III: GY 34/2-d doğru; GK 19'daki esaslı işçilik tanımı atlanmış",
      "I ve II: GK 18/2 tümüyle elde sayımı ile GK 19 esaslı işçilik karıştırılmış",
      "I, II ve III: GK 18/2 kapalı sayımına başka ülke girdisi eklenmiş",
      "II, III ve IV: GK 20'deki 'tespit edilen veya ... kanaat oluşan' kaydı daraltılmış"],
yakinlik="BİREBİR",
tuzak=["UNSUR", "KOMŞU", "ŞART"], duzey=["AYIRT"], profil=[3, 1],
olumsuz=False, vaka=False, baslangic=False, eksen=4, ayna="", guncellik="", cikmis="2023/64; 2024/34; 2025/53", kapsamli=False,
),

# 5 ---------------- Vaka: serbest dolaşım ≠ menşe; yetersiz işlem (eksen 3) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="OLAY",
z="Z",
madde="4458 sayılı Gümrük Kanunu md. 18, 19; Gümrük Yönetmeliği md. 34, 36",
cek="Serbest dolaşıma giriş menşe kazandırmaz; ambalaj değişikliği ve etiket konulması birlikte yapılsa da, pozisyon değişse de yetersiz işlemdir.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'nin tercihli olmayan menşee ilişkin hükümleri çerçevesinde aşağıdaki olay verilmiştir:",
     "- Türkiye'de yerleşik X firması, Çin menşeli olup Türk Gümrük Tarife Cetvelinin XI inci bölümünde yer alan tekstil ürünlerini serbest dolaşıma giriş rejimi kapsamında ithal etmiştir.",
     "- Firma, eşyayı deposunda yeni ambalajlara aktarmış ve ürünlerin üzerine kendi markasını taşıyan etiketler koymuştur.",
     "- Eşya bu hâliyle Gürcistan'a ihraç edilecektir.",
     "Buna göre ihraç edilecek eşyanın menşeine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Eşya Çin menşelidir; serbest dolaşıma girmesi ve üzerinde yapılan işlemler eşyaya Türk menşei kazandırmaz",
c=["Eşya, serbest dolaşıma giriş rejimine tabi tutulduğu anda Türk menşei kazanmıştır",
   "Ambalaj değişikliği ile etiket konulması bir arada yapıldığından eşya Türk menşei kazanmıştır",
   "Yapılan işlemler eşyanın tarife pozisyonunu değiştirmişse eşya Türk menşei kazanır; değiştirmemişse Çin menşeli kalır",
   "Eşyanın menşe ülkesi, Gürcistan'a en son gönderildiği ülke olan Türkiye'dir"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre eşya iki yoldan bir ülke menşeli olur: tümüyle o ülkede elde edilmesi ya da üretimi birden fazla ülkede gerçekleşen eşyada o ülkede yeni bir ürün imal edilmesi veya imalatın önemli bir aşamasının ve en son esaslı işçilik ve eylemin o ülkede bu amaçla donatılmış işletmelerde yapılması. Serbest dolaşıma giriş bu iki yoldan biri değildir; eşyanın serbest dolaşıma girmesi tek başına ona Türk menşei kazandırmaz. Gümrük Yönetmeliği'ne göre ambalaj değişikliği ve basit ambalajlama işlemleri ile ürün veya ambalajı üzerine marka ve etiket konulması yetersiz işçilik veya işlemdir; bunların iki veya daha fazlasının bir arada yapılması da yetersiz sayılır ve bu sonuç tarife pozisyonu değişikliği koşulunun sağlanıp sağlanmadığına bakılmaksızın geçerlidir. Eşya bu yüzden Çin menşeli kalır. En güçlü çeldirici pozisyon değişikliğine bağlanan seçenektir: tekstilde pozisyon değişikliği genel kuraldır, ancak sayılan yetersiz işlemler bu kurala bakılmaksızın menşe kazandırmaz. 'En son gönderildiği ülke' ise menşe ülkeyi değil, eşyanın geldiği ülkeyi tanımlar. Bu nedenle doğru cevap 'Eşya Çin menşelidir; serbest dolaşıma girmesi ve üzerinde yapılan işlemler eşyaya Türk menşei kazandırmaz' seçeneğidir. (MD GK 18, 19; GY 34, 36)",
kanit="10-MENŞEİ.txt | o ülkede yeni bir ürün imal edilmesi veya imalatın önemli bir aşamasının ve ekonomik yönden gerekli görülen en son esaslı işçilik ve eylemin o ülkede bu amaçla donatılmış işletmelerde yapılması gerekir || 10-MENŞEİ.txt | birinci fıkrada belirtilen koşulların sağlanıp sağlanmadığına bakılmaksızın eşyanın menşe kazanması için yetersiz işçilik veya işlem olarak kabul edilir || 10-MENŞEİ.txt | Ürün veya ambalajı üzerine marka, etiket ve diğer benzeri ayırt edici işaretlerin konulması || 10-MENŞEİ.txt | Bu maddenin (a) ila (d) alt bentlerinde belirtilen işlemlerin iki veya daha fazlasının bir arada gerçekleştirilmesi",
yuva=["Statü-menşe karışıklığı: serbest dolaşıma giriş, GK 18-19'daki menşe kazanma yolları arasında yok",
      "GY 34/2-e: yetersiz işlemlerin iki veya daha fazlasının bir arada yapılması da yetersizdir",
      "GY 34/1 tekstilde pozisyon değişikliği kuralı; GY 34/2 yetersiz işlemleri bu koşula bakılmaksızın dışlar",
      "GY 36/3: en son gönderildiği ülke eşyanın geldiği ülkedir; menşe ülke değildir"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "TERİM", "KOMŞU"], duzey=["BÜTÜNLEŞİK"], profil=[3],
olumsuz=False, vaka=True, baslangic=False, eksen=3, ayna="E3 statü-menşe: menşe kazandırma (A.TR-menşe ispat belgesi sorusuyla çift)", guncellik="", cikmis="2024/40; 2025/39; 2025/52", kapsamli=False,
),

# 6 ---------------- DİR Tebliği: menşe ispat belgeleri ↔ A.TR (eksen 3 ayna) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="KAPSAM_DIŞI",
z="O",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 3",
cek="Menşe ispat belgeleri: EUR.1, EUR-MED dolaşım sertifikası, EUR-MED fatura beyanı, fatura beyanı; A.TR serbest dolaşımdaki eşyaya ilişkin ayrı belgedir.",
kok=["Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12)'nde \"menşe ispat belgeleri\" olarak tanımlanan ve Türkiye'nin taraf olduğu anlaşmalar çerçevesinde tercihli rejimden yararlanmak üzere malın menşeini belirleyen belgeler arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="A.TR dolaşım belgesi",
c=["EUR.1 dolaşım sertifikası",
   "EUR-MED dolaşım sertifikası",
   "EUR-MED fatura beyanı",
   "Fatura beyanı"],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) menşe ispat belgelerini; Türkiye'nin taraf olduğu anlaşmalar çerçevesinde tercihli rejimden yararlanmak üzere ihracatçı ülke yetkili kuruluşlarınca düzenlenip gümrük idaresince vize edilen ve malın menşeini belirleyen EUR.1 dolaşım sertifikası, EUR-MED dolaşım sertifikası, EUR-MED fatura beyanı veya fatura beyanı olarak tanımlar. A.TR dolaşım belgesi bu sayımda yer almaz; Tebliğ onu ayrıca, Türkiye veya Toplulukta serbest dolaşımda bulunan eşyanın Katma Protokolde öngörülen tercihli rejimden yararlanabilmesini sağlayan belge olarak tanımlar. A.TR'nin dayanağı eşyanın menşei değil serbest dolaşımda bulunmasıdır; gümrük statüsü ile menşe arasındaki ayrımın belgedeki karşılığı budur. En güçlü çeldirici EUR.1 dolaşım sertifikasıdır: adı A.TR gibi 'dolaşım' içerse de malın menşeini belirleyen bir menşe ispat belgesidir. Bu nedenle doğru cevap 'A.TR dolaşım belgesi' seçeneğidir. (MD DİR Tebliği 3)",
kanit="32-DAHİLDE İŞLEME.txt | malın menşeini belirleyen EUR.1 dolaşım sertifikası, EUR-MED dolaşım sertifikası, EUR-MED fatura beyanı veya fatura beyanını || 32-DAHİLDE İŞLEME.txt | A.TR dolaşım belgesi: Türkiye veya Toplulukta serbest dolaşımda bulunan eşyanın Katma Protokolde öngörülen tercihli rejimden yararlanabilmesini sağlamak üzere",
yuva=["Menşe ispat belgeleri tanımı (sayımda: EUR.1 dolaşım sertifikası)",
      "Menşe ispat belgeleri tanımı (sayımda: EUR-MED dolaşım sertifikası)",
      "Menşe ispat belgeleri tanımı (sayımda: EUR-MED fatura beyanı)",
      "Menşe ispat belgeleri tanımı (sayımda: fatura beyanı)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "TERİM"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=3, ayna="E3 statü-menşe: belge (serbest dolaşım vakasıyla çift)", guncellik="", cikmis="2023/41; 2025/41; 2025/45", kapsamli=False,
),

# 7 ---------------- GY 36/2: "kıymet" deyimi (addan tanım) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="TANIM",
z="Z",
madde="Gümrük Yönetmeliği md. 36",
cek="Kıymet: menşeli olmayan maddelerin ithalattaki gümrük kıymeti; bilinmez veya tespit edilemezse imalat ülkesinde ödenen tespiti mümkün ilk fiyat.",
kok=["Gümrük Yönetmeliği'ne göre, ek listelerdeki menşe kuralının eşyanın imalatında fabrika çıkış fiyatının belirli bir yüzde oranını aşmayacak şekilde menşeli olmayan madde kullanımını öngördüğü hâllerde, bu oranın hesaplanmasında kullanılan \"kıymet\" deyimi aşağıdakilerden hangisini ifade eder?"],
d="Kullanılan menşeli olmayan maddelerin ithalatı esnasındaki gümrük kıymetini; bunun bilinmemesi veya tespit edilememesi hâlinde imalatın yapıldığı ülkede maddeler için ödenen tespiti mümkün ilk fiyatı",
c=["Kullanılan menşeli olmayan maddelerin ithalatı esnasındaki gümrük kıymetini; bunun bilinmemesi veya tespit edilememesi hâlinde imalatın yapıldığı ülkede maddeler için ödenen tespiti mümkün en yüksek fiyatı",
   "Kullanılan menşeli olmayan maddeler için imalatın yapıldığı ülkede ödenen tespiti mümkün ilk fiyatı; bunun tespit edilememesi hâlinde maddelerin ithalatı esnasındaki gümrük kıymetini",
   "Elde edilen ürünün fabrika çıkış fiyatından, ürünün ihracında geri ödenmiş veya ödenecek yurt içi vergilerin tenziliyle bulunan fiyatı",
   "Montaj işlemlerinin yapıldığı ülkede o ülke menşeli parçaların birleştirilmesinden doğan, kâr ve genel giderler dahil kıymet artışını"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre ek listelerdeki menşe kuralı menşeli olmayan madde kullanımını fabrika çıkış fiyatının belirli bir yüzdesiyle sınırlıyorsa, bu oranın hesabında kullanılan 'kıymet' deyimi, kullanılan menşeli olmayan maddelerin ithalatı esnasındaki gümrük kıymetini; bunun bilinmemesi veya tespit edilememesi hâlinde ise imalatın yapıldığı ülkede maddeler için ödenen tespiti mümkün ilk fiyatı ifade eder. Sıra önemlidir: esas olan gümrük kıymetidir, ilk fiyata ancak gümrük kıymeti bilinmez veya tespit edilemezse gidilir; sırayı tersine çeviren seçenek en güçlü çeldiricidir. 'Tespiti mümkün en yüksek fiyat' ifadesi hükümdeki 'tespiti mümkün ilk fiyat' kaydını bozar. Yurt içi vergilerin tenziliyle bulunan fiyat 'fabrika çıkış fiyatı', o ülke menşeli parçaların birleştirilmesinden doğan kıymet artışı ise 'montaj işlemleri sonucu oluşan kıymet' deyimidir. Bu nedenle doğru cevap 'Kullanılan menşeli olmayan maddelerin ithalatı esnasındaki gümrük kıymetini; bunun bilinmemesi veya tespit edilememesi hâlinde imalatın yapıldığı ülkede maddeler için ödenen tespiti mümkün ilk fiyatı' seçeneğidir. (MD GY 36)",
kanit="10-MENŞEİ.txt | Kıymet deyimi, kullanılan menşeli olmayan maddelerin ithalatı esnasındaki gümrük kıymetini, bunun bilinmemesi veya tespit edilememesi halinde ise imalatın yapıldığı ülkede maddeler için ödenen tespiti mümkün ilk fiyatı || 10-MENŞEİ.txt | Fabrika çıkış fiyatı deyimi, elde edilen ürünün fabrika çıkış fiyatından ürünün ihracında geri ödenmiş veya ödenecek yurt içi vergilerin tenziliyle bulunan fiyatı",
yuva=["Aynı bent: 'tespiti mümkün ilk fiyat' kaydı 'en yüksek fiyat' olarak bozulmuş",
      "Aynı bent: gümrük kıymeti ile ilk fiyatın öncelik sırası ters çevrilmiş",
      "GY 36/2-b: fabrika çıkış fiyatı deyimi",
      "GY 36/2-c: montaj işlemleri sonucu oluşan kıymet deyimi"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU", "UNSUR"], duzey=["AYIRT"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 8 ---------------- GY 36/3: eşyanın geldiği ülke (tanımdan ad) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="KAVRAM",
z="K",
madde="Gümrük Yönetmeliği md. 36",
cek="Eşyanın geldiği ülke: Türkiye'ye en son gönderildiği veya getiren araca yüklendiği ülke; üçüncü ülkede antrepo menşei değiştirmez.",
kok=["Gümrük Yönetmeliği'nde \"eşyanın Türkiye'ye en son gönderildiği veya getiren araca yüklendiği ülke\" olarak açıklanan kavram aşağıdakilerden hangisidir?"],
d="Eşyanın geldiği ülke",
c=["Eşyanın menşe ülkesi",
   "Eşyanın üretildiği ülke",
   "Eşyanın tercihli menşe ülkesi",
   "Eşyanın varış ülkesi"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre eşyanın geldiği ülkeden maksat, Türkiye'ye en son gönderildiği veya getiren araca yüklendiği ülkedir. Eşya üretildiği ülkeden doğrudan Türkiye'ye getirilmeyip üçüncü ülkeler yoluyla getirilmiş ve oralarda geçici depolama yerlerine veya antrepolara konmuş olsa dahi menşe ülkesi değişmez; başka bir ülkede antrepoya konmaksızın yalnızca araç değiştirilmesi de eşyanın geldiği ülkeyi değiştirmez. En güçlü çeldirici menşe ülkesidir: iki kavram aynı hükümde birlikte düzenlenmiştir, fakat menşe ülkesi ara ülkelerdeki depolamayla değişmezken geldiği ülke en son gönderilen ülkeye göre belirlenir. Tercihli menşe tercihli tarife uygulamalarında, varış ülkesi ise yedek parçaların menşeinde ithalatın yapıldığı ülke anlamında geçer. Bu nedenle doğru cevap 'Eşyanın geldiği ülke' seçeneğidir. (MD GY 36, 37)",
kanit="10-MENŞEİ.txt | Eşyanın geldiği ülkeden maksat Türkiye'ye en son gönderildiği veya getiren araca yüklendiği ülkedir || 10-MENŞEİ.txt | oralarda geçici depolama yerlerine ve antrepolara konmuş olsa dahi menşe ülkesi değişmez",
yuva=["GY 36/3 ilk cümle: menşe ülkesi, üçüncü ülkede antrepoya konulsa da değişmez",
      "GY 36/3: eşyanın üretildiği ülkeden doğrudan getirilmemesi hâli",
      "GY 205/4-a: tercihli menşei tevsik eden belgeler",
      "GY 37/3: varış ülkesindeki ithalat için gereklilik"],
yakinlik="BİREBİR",
tuzak=["TERİM"], duzey=["TANIMA"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 9 ---------------- GY 37: aksesuar, yedek parça ve aksam ----------------
dict(
konu="Menşe", blok="SB10",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Yönetmeliği md. 37",
cek="Beraberinde teslim edilen aksesuar aynı menşeli; parça ifadesi XVI-XVIII bölümler; önemli yedek parçanın serbest dolaşımında menşe şahadetnamesi gerekir.",
kok=["Gümrük Yönetmeliği'nin aksesuarlar, yedek parçalar ve aksamın menşeine ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Bir cihaz, makine, alet veya aracın parçası beraberinde teslim edilen ve normal olarak cihazın bölümü durumundaki aksesuarlar, yedek parçalar ve aksamın, söz konusu cihaz, makine, alet veya aracın parçası ile aynı menşei taşıdığı kabul edilir.",
     "II. Bu hükümlerin uygulanmasında cihaz, makine, alet veya aracın parçası ifadesi, Türk Gümrük Tarife Cetvelinin XI, XVI ve XVII nci bölümlerinde yer alan eşyayı ifade eder.",
     "III. Önemli yedek parçaların serbest dolaşıma sokulmak istenmesi hâlinde, menşe şahadetnamesinde bulunması zorunlu bilgileri içeren bir menşe şahadetnamesinin ibrazı gerekir.",
     "IV. Bu hükümlere göre menşe belirlenebilmesi için, önemli yedek parçaların üretim aşamasında ilgili teçhizat, makine, cihaz veya taşıtın bünyesine girmesinin, bu eşyanın imalatının yapıldığı ülkenin menşeine sahip olmasını engellememesi gerekir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, III ve IV",
c=["I ve II", "I ve III", "II ve IV", "I, II, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre bir cihaz, makine, alet veya aracın parçası beraberinde teslim edilen ve normal olarak cihazın bölümü durumundaki aksesuarlar, yedek parçalar ve aksam, söz konusu cihaz, makine, alet veya aracın parçası ile aynı menşei taşır (I doğru). Bu hükümlerin uygulanmasında 'cihaz, makine, alet veya aracın parçası', Türk Gümrük Tarife Cetvelinin XVI, XVII ve XVIII inci bölümlerinde yer alan eşyadır; XI inci bölüm Yönetmelikte tekstil ürünlerinin yer aldığı bölüm olarak geçer (II yanlış). Önemli yedek parçaların serbest dolaşıma sokulmak istenmesi hâlinde, menşe şahadetnamesinde bulunması zorunlu bilgileri içeren menşe şahadetnamesinin ibrazı gerekir; gümrük idaresi buna ek olarak fatura, sözleşme ve gerekli gördüğü başka belgeleri isteyebilir (III doğru). Bu kurallara göre menşe belirlenebilmesi için varış ülkesindeki ithalat için gerekli olması ve önemli yedek parçaların üretim aşamasında teçhizatın bünyesine girmesinin, teçhizatın imalatının yapıldığı ülkenin menşeine sahip olmasını engellememesi gerekir (IV doğru). En güçlü tuzak II'dir: bölüm numaralarından biri tekstil bölümüyle değiştirilmiştir. Bu nedenle doğru cevap 'I, III ve IV' seçeneğidir. (MD GY 34, 37, 40)",
kanit="10-MENŞEİ.txt | normal olarak bir cihazın bölümü durumundaki aksesuarlar, yedek parçalar ve aksamın, söz konusu cihaz, makine, alet veya aracın parçası ile aynı menşei taşıdığı kabul edilir || 10-MENŞEİ.txt | Cihaz, makine, alet veya aracın parçası, Türk Gümrük Tarife Cetvelinin XVI, XVII ve XVIII inci bölümlerinde yer alan eşyayı || 10-MENŞEİ.txt | Önemli yedek parçaların serbest dolaşıma sokulmak istenmesi halinde, 40 ıncı maddede belirtilen bilgileri içeren menşe şahadetnamesinin ibrazı gerekir || 10-MENŞEİ.txt | bu teçhizat, makine, cihaz veya taşıtın imalatının yapıldığı ülkenin menşeine sahip olmasını engellememesi gerekir",
yuva=["I ve II: II'deki bölüm sayımına tekstil bölümü (GY 34/1, XI) taşınmış",
      "I ve III: GY 37/3'teki menşe belirleme şartı atlanmış",
      "II ve IV: GY 37/1 ve 37/6 atlanmış; II'de XI bölüm (GY 34/1) taşınmış",
      "I, II, III ve IV: II'deki XI-XVI-XVII sayımı doğru sanılmış (doğrusu GY 37/4-a: XVI, XVII, XVIII)"],
yakinlik="BİREBİR",
tuzak=["SAYI", "KOMŞU"], duzey=["AYIRT"], profil=[1, 2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 10 ---------------- GY 37/5: önemli yedek parça ihracında aranan belge ----------------
dict(
konu="Menşe", blok="SB10",
kalip="BELGE",
z="Z",
madde="Gümrük Yönetmeliği md. 37",
cek="Önemli yedek parça ihracında menşe şahadetnamesi için başvuranın yazılı beyanı aranır; fatura, sözleşme ve diğer belgeleri idare isteyebilir.",
kok=["Gümrük Yönetmeliği'ne göre, daha önce ihraç edilmiş bir makinenin normal bakımında kullanılacak önemli yedek parçaların ihracatında menşe şahadetnamesi düzenlenirken, şahadetnamenin ilgili kutusunun doldurulmasından başka aşağıdakilerden hangisi her durumda aranır?"],
d="Başvuru sahibinin, yedek parçaların daha önce ihraç edilen makinenin normal bakımında kullanılacağına ilişkin yazılı beyanı",
c=["Daha önce ihraç edilmiş makinenin parçası ile ilgili fatura veya bu faturanın bir nüshası",
   "Teslimatın normal bakım hizmetinin bir parçası olarak yapılmakta olduğunu gösteren sözleşme veya bu sözleşmenin bir nüshası",
   "Daha önce ihraç edilmiş makineye ait menşe şahadetnamesinin sayı, tarih ve onaylayan bilgilerini içeren ayrıntılar",
   "Gümrük idaresince gerekli görülen ve yedek parçaların Türkiye menşeli olduğunu tevsik eden diğer belgeler"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre önemli yedek parçaların ihracatında menşe şahadetnamesi düzenlenirken, şahadetnamenin eşyanın tanımı, koli sayısı ve cinsi, marka ve sayısını gösteren kutusunun doldurulmasından başka, başvuruda bulunanın bu eşyanın daha önce ihraç edilmiş cihaz, makine, alet veya aracın bir parçasının normal bakımı için kullanılacağına ilişkin yazılı beyanı aranır; bu beyanda cihazın tüm özellikleri de yer alır. Daha önce ihraç edilmiş cihaza ait menşe şahadetnamesinin sayı, tarih ve onaylayan gibi ayrıntıları başvuruda yalnızca 'mümkünse' sunulur. Fatura veya nüshası, teslimatın normal bakım hizmetinin parçası olarak yapıldığını gösteren sözleşme veya nüshası ve gerekli görülen başka belgeler ise gümrük idaresinin ek olarak 'isteyebileceği' belgelerdir; Türkiye menşeini tevsik eden bilgiler de yetkili makamlarca 'talep edilebilir'. En güçlü çeldirici fatura seçeneğidir: hükümde geçer, ancak idarenin takdirine bağlıdır ve her durumda aranmaz. Bu nedenle doğru cevap 'Başvuru sahibinin, yedek parçaların daha önce ihraç edilen makinenin normal bakımında kullanılacağına ilişkin yazılı beyanı' seçeneğidir. (MD GY 37, 42)",
kanit="10-MENŞEİ.txt | başvuruda bulunan tarafından yine bu eşyanın daha önce ihraç edilmiş olan cihaz, makine, alet veya aracın bir parçasının normal bakımı için kullanılacağına ilişkin yazılı beyanı aranır || 10-MENŞEİ.txt | Başvurularda, mümkünse, daha önce ihraç edilmiş olan || 10-MENŞEİ.txt | Gümrük idaresi buna ek olarak daha önce ihraç edilmiş cihaz, makine veya alet veya aracın parçası ile ilgili fatura veya bu faturanın bir nüshasının",
yuva=["GY 37/5: fatura veya nüshası — gümrük idaresi 'isteyebilir'",
      "GY 37/5: normal bakım sözleşmesi veya nüshası — gümrük idaresi 'isteyebilir'",
      "GY 37/5: önceki şahadetnameye ait sayı, tarih, onaylayan ayrıntıları — 'mümkünse' sunulur",
      "GY 37/5 ve 42/5: idarenin gerekli gördüğü belge ve Türkiye menşeini tevsik eden bilgi — 'isteyebilir/talep edebilir'"],
yakinlik="PARAFRAZ",
tuzak=["TERİM", "KOMŞU"], duzey=["AYIRT"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 11 ---------------- GY 38/1: şahadetnameyi düzenleyen makam ----------------
dict(
konu="Menşe", blok="SB10",
kalip="YETKİ",
z="O",
madde="Gümrük Yönetmeliği md. 38",
cek="Önlemin uygulanmaması için ibraz edilen menşe şahadetnamesi menşe ülkenin veya ihracatçı ülkenin yetkili makamlarınca düzenlenmiş olmalıdır.",
kok=["Gümrük Yönetmeliği'ne göre, menşe esaslı ticaret politikası önlemine tabi eşyanın serbest dolaşıma girişinde önlemin uygulanmaması için eşyanın söz konusu önleme tabi ülke menşeli olmadığını tevsik etmek üzere ibraz edilecek menşe şahadetnamesi aşağıdakilerden hangisince düzenlenmiş olmalıdır?"],
d="Eşyanın menşe ülkesinin veya eşyayı ihraç eden ülkenin yetkili makamlarınca",
c=["Yalnızca eşyanın menşe ülkesinin yetkili makamlarınca",
   "Menşe ülkenin yetkili makamlarınca düzenlenip ihracatçı ülkenin yetkili makamlarınca onaylanarak",
   "İthalatçının yazılı başvurusu üzerine Türkiye'deki gümrük idaresince",
   "İhracatçı ülke yetkili kuruluşlarınca düzenlenip Türkiye'deki gümrük idaresince vize edilerek"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre menşe esaslı ticaret politikası önlemlerine, ilave gümrük vergisine veya diğer mali yükümlülüklere tabi eşyanın serbest dolaşıma girişinde, önlemin uygulanmaması için eşyanın bu uygulamalara tabi ülke menşeli olmadığını tevsik etmek üzere menşe ülkenin veya ihracatçı ülkenin yetkili makamlarınca düzenlenmiş menşe şahadetnamesi ibraz edilir. İki makam seçimlik olarak sayılmıştır ('veya'): biri yeterlidir, ikisinin birlikte işlem yapması aranmaz ve yetki menşe ülke makamıyla da sınırlı değildir. En güçlü çeldirici iki makamı birleştiren seçenektir: hüküm, birinin düzenleyip ötekinin onaylamasını aramaz. Türkiye'deki gümrük idaresi ithalatta menşe şahadetnamesi düzenlemez; yazılı başvuru üzerine düzenleme Yönetmelikte Türkiye'den ihracatta düzenlenecek şahadetnameler için geçer. 'Düzenlenip gümrük idaresince vize edilme' ise Dahilde İşleme Rejimi Tebliğinde A.TR ve menşe ispat belgelerinin tanımında yer alan ifadedir. Bu nedenle doğru cevap 'Eşyanın menşe ülkesinin veya eşyayı ihraç eden ülkenin yetkili makamlarınca' seçeneğidir. (MD GY 38, 42)",
kanit="10-MENŞEİ.txt | menşe ülkenin veya ihracatçı ülkenin yetkili makamlarınca düzenlenmiş olan menşe şahadetnamesi ibraz edilir || 10-MENŞEİ.txt | Menşe şahadetnamesi ihracatçının veya ihracatçının sorumluluğundaki yetkili temsilcisinin yazılı başvurusuna binaen düzenlenir",
yuva=["GY 38/1: 'menşe ülkenin veya ihracatçı ülkenin' seçimlik sayımı daraltılmış",
      "GY 38/1: seçimlik 'veya' birlikte arama (düzenleme + onay) şartına çevrilmiş",
      "GY 42/2: yazılı başvuru üzerine düzenleme, Türkiye'den ihracattaki şahadetnamelere ait",
      "DİR Tebliği tanımlar: 'ihracatçı ülke yetkili kuruluşlarınca düzenlenip gümrük idaresince vize edilen' (A.TR, menşe ispat belgeleri)"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "UNSUR", "ŞART"], duzey=["HATIRLAMA"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2024/38", kapsamli=False,
),

# 12 ---------------- GY 38/2: sonradan ibraz — teminat, süre, uzatma makamı, irat (olumsuz; önermeliden çevrildi) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="YANLIŞ",
z="O",
madde="Gümrük Yönetmeliği md. 38",
cek="Sonradan ibrazda yükümlülükler nakit teminata bağlanır; tescilden itibaren altı ay; idare amirince en fazla otuz gün uzatma; ibrazda iade, kabul edilmezse irat.",
kok=["Gümrük Yönetmeliği'ne göre, menşe şahadetnamesinin sonradan ibraz edileceğinin serbest dolaşıma giriş beyannamesinde belirtildiği durumda uygulanacak işlemlere ilişkin aşağıdakilerden hangisi söylenemez?"],
d="İbraz süresi, mücbir sebep hâlleri saklı kalmak ve bitiminden önce başvurulmak kaydıyla bölge müdürlüğünce en fazla otuz gün uzatılabilir.",
c=["Dünya Ticaret Örgütü üyesi olmayan ülkelere uygulanan yüksek orandan doğan vergi farkı ile menşe esaslı ticaret politikası önlemleri ve ilave gümrük vergisi nakit olarak teminata bağlanır.",
   "Usulüne uygun bir menşe şahadetnamesinin ibrazı için beyannamenin tescil tarihinden itibaren altı aylık süre verilir.",
   "Verilen süre içinde usulüne uygun menşe şahadetnamesinin ibrazı hâlinde alınan teminat iade edilir.",
   "Menşe şahadetnamesinin kabul edilmemesi hâlinde alınan teminat irat kaydedilir."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre menşe şahadetnamesinin sonradan ibraz edileceğinin beyannamede belirtilmesi hâlinde; Dünya Ticaret Örgütü üyesi olmayan ülkelere uygulanan yüksek orandan doğan gümrük vergisi farkı, menşe esaslı ticaret politikası önlemleri, ilave gümrük vergisi veya ek mali yükümlülük gibi diğer mali yükümlülükler nakit teminata bağlanır ve usulüne uygun bir menşe şahadetnamesi ibrazı için beyannamenin tescil tarihinden itibaren altı aylık süre verilir. Bu süre, mücbir sebep hâlleri saklı kalmak ve bitiminden önce başvurmak kaydıyla gümrük idare amirince en fazla otuz gün uzatılabilir; uzatma yetkisi bölge müdürlüğüne değil gümrük idare amirine aittir. Süresi içinde usulüne uygun şahadetname ibraz edilirse teminat iade edilir; şahadetname kabul edilmezse alınan teminat irat kaydedilir. Yanlış ifadede süre ve koşullar doğru verilmiş, yalnızca uzatma makamı değiştirildiğinden ifade ilk bakışta doğru görünür; makamı karıştıran aday bunu doğru sanar. Bu nedenle doğru cevap 'İbraz süresi, mücbir sebep hâlleri saklı kalmak ve bitiminden önce başvurulmak kaydıyla bölge müdürlüğünce en fazla otuz gün uzatılabilir.' seçeneğidir. (MD GY 38)",
kanit="10-MENŞEİ.txt | Dünya Ticaret Örgütü üyesi olmayan ülkeler için uygulanan yüksek oranda vergiden kaynaklanan gümrük vergisi farkı, menşe esaslı ticaret politikası önlemleri, ilave gümrük vergisi veya ek mali yükümlülük gibi diğer mali yükümlülükler nakit teminata bağlanmak suretiyle usulüne uygun bir menşe şahadetnamesi ibrazı için beyannamenin tescil tarihinden itibaren altı aylık süre verilir || 10-MENŞEİ.txt | Mücbir sebep halleri saklı kalmak ve bitiminden önce başvurmak kaydıyla bu süre gümrük idare amirince en fazla otuz gün uzatılabilir || 10-MENŞEİ.txt | Süresi içinde usulüne uygun olarak düzenlenmiş menşe şahadetnamesinin ibrazı halinde alınan teminat iade edilir || 10-MENŞEİ.txt | Menşe şahadetnamesinin kabul edilmemesi halinde ise alınan teminat irat kaydedilir",
yuva=["GY 38/2: yükümlülüklerin nakit teminata bağlanması (doğru ifade)",
      "GY 38/2: tescil tarihinden itibaren altı aylık ibraz süresi (doğru ifade)",
      "GY 38/2: süresinde ibrazda teminatın iadesi (doğru ifade)",
      "GY 38/2 son cümle: şahadetname kabul edilmezse teminatın irat kaydı (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"], duzey=["HATIRLAMA"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2025/48", kapsamli=False,
),

# 13 ---------------- GY 38/3: beyan edilip ödenen tutarın geri verilmesi — süre ve başlangıç ----------------
dict(
konu="Menşe", blok="SB10",
kalip="SÜRE",
z="O",
madde="Gümrük Yönetmeliği md. 38",
cek="Beyan edilip ödenen önlem ve İGV, tescil tarihinden itibaren altı ayı aşmadan menşe şahadetnamesiyle başvurulursa geri verilir.",
kok=["Gümrük Yönetmeliği'ne göre, menşe şahadetnamesinin sonradan ibraz edileceği beyannamede belirtilmeksizin yapılan serbest dolaşıma girişte ilave gümrük vergisi beyan edilerek ödenmiştir.",
     "Ödenen tutarın geri verilebilmesi için menşe şahadetnamesi ile gümrük idaresine başvuru süresi, sürenin uzatılmadığı varsayıldığında aşağıdakilerden hangisidir?"],
d="Beyannamenin tescil tarihinden itibaren altı ay",
c=[],
sirali=True,
siklar=["Beyannamenin tescil tarihinden itibaren otuz gün",
        "İlave gümrük vergisinin ödendiği tarihten itibaren altı ay",
        "Beyannamenin tescil tarihinden itibaren altı ay",
        "Gümrük idaresince yapılan tespit tarihinden itibaren altı ay",
        "Beyannamenin tescil tarihinden itibaren altı ay otuz gün"],
g="Gümrük Yönetmeliği'ne göre, şahadetnamenin sonradan ibraz edileceğinin belirtildiği veya ibraz edilen şahadetnamenin kabul edilmediği hâller dışında; Dünya Ticaret Örgütü üyesi olmayan ülkelere uygulanan yüksek orandan doğan gümrük vergisi farkı, menşe esaslı ticaret politikası önlemleri, ilave gümrük vergisi veya diğer mali yükümlülükler beyan edilerek ödenmişse, beyannamenin tescil tarihinden itibaren altı aylık süreyi aşmamak üzere menşe şahadetnamesi ile gümrük idaresine başvurulması hâlinde tahsil edilen tutar geri verilir. Sürenin başlangıcı ödeme tarihi değil beyannamenin tescil tarihidir. Mücbir sebep hâlleri saklı kalmak ve bitiminden önce başvurmak kaydıyla bu süre gümrük idare amirince en fazla otuz gün uzatılabilir; soruda uzatma olmadığından 'altı ay otuz gün' seçeneği doğru değildir, otuz gün ise uzatma süresinin kendisidir. Tespit tarihinden itibaren altı ay, gümrük işlemleri tamamlandıktan sonra yapılan denetimde pozisyon değişikliği nedeniyle önleme tabi olduğu anlaşılan eşya için verilen süredir. En güçlü çeldirici ödeme tarihinden başlatılan altı aydır: süre doğru, başlangıç anı yanlıştır. Bu nedenle doğru cevap 'Beyannamenin tescil tarihinden itibaren altı ay' seçeneğidir. (MD GY 38)",
kanit="10-MENŞEİ.txt | beyan edilerek ödenmesi halinde, beyannamenin tescil tarihinden itibaren altı aylık süreyi aşmamak üzere menşe şahadetnamesi ile gümrük idaresine başvurulması halinde, tahsil edilen tutar geri verilir || 10-MENŞEİ.txt | yükümlüye uygun bir menşe şahadetnamesinin gümrük idaresine ibrazı için yapılan tespit tarihinden itibaren altı aylık süre verilir",
yuva=["GY 38/3 ikinci cümle: otuz gün, idare amirince verilebilecek azami uzatma süresi",
      "GY 38/3: başlangıç anı ödeme tarihine kaydırılmış (doğrusu tescil tarihi)",
      "GY 38/5: işlemler tamamlandıktan sonraki denetimde tespit tarihinden itibaren altı ay",
      "GY 38/3: altı ay ve azami otuz günlük uzatma birlikte (uzatma yokken geçersiz)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "YAKIN-SAYI", "KOMŞU"], duzey=["AYIRT"], profil=[2, 1],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 14 ---------------- GY 39: 430 Avro ve aynı gönderici kuralı (iki bilgi; vakadan çevrildi) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="ORAN-TUTAR",
z="Z",
madde="Gümrük Yönetmeliği md. 39",
cek="Ticari olmayan ve CIF 430 Avro'yu geçmeyen eşyada şahadetname aranmaz; aynı göndericinin aynı alıcıya kolileri birlikte değerlendirilir.",
kok=["Gümrük Yönetmeliği'nin menşe şahadetnamesi aranmayacak eşyaya ilişkin hükmüne göre, ticari mahiyette olmayan eşyada menşe şahadetnamesi aranmamasının CIF kıymet sınırı ile birden fazla kap veya kolinin kıymetinin birlikte dikkate alınmasına ilişkin kural aşağıdakilerin hangisinde birlikte doğru olarak verilmiştir?"],
d="430 Avro – Aynı gönderici tarafından Türkiye'deki bir alıcı adına gönderilen kap ve kolilerin tamamının kıymeti birlikte dikkate alınır",
c=[],
sirali=True,
siklar=["150 Avro – Aynı gönderici tarafından Türkiye'deki bir alıcı adına gönderilen kap ve kolilerin tamamının kıymeti birlikte dikkate alınır",
        "430 Avro – Göndericileri farklı olsa da Türkiye'deki aynı alıcı adına gelen kap ve kolilerin tamamının kıymeti birlikte dikkate alınır",
        "430 Avro – Aynı gönderici tarafından Türkiye'deki bir alıcı adına gönderilen kap ve kolilerin tamamının kıymeti birlikte dikkate alınır",
        "500 Avro – Göndericileri farklı olsa da Türkiye'deki aynı alıcı adına gelen kap ve kolilerin tamamının kıymeti birlikte dikkate alınır",
        "500 Avro – Her kap ve kolinin kıymeti ayrı ayrı dikkate alınır"],
g="Gümrük Yönetmeliği'ne göre ticari mahiyette olmayan ve CIF kıymeti 430 Avro'yu geçmeyen eşya için menşe şahadetnamesi aranmaz. Aynı gönderici tarafından Türkiye'deki bir alıcı adına gönderilen kap ve kolilerin hepsi bir bütün teşkil eder ve tamamının kıymeti birlikte dikkate alınır; böylece aynı gönderinin kolilere bölünmesiyle sınırın aşılması engellenir. Birleştirme ölçütü yalnızca alıcının aynı olması değildir, göndericinin de aynı olması gerekir; farklı göndericilerden aynı alıcıya gelen koliler birleştirilmez. Kolilerin her birini ayrı değerlendiren kural ise hükmün ikinci cümlesini yok sayar. 150 Avro, posta ya da hızlı kargo yoluyla gelen kişisel kullanıma mahsus kitap veya benzeri basılı yayına tanınan muafiyette, 500 Avro ise Gümrük Yönetmeliği'nde aynı gümrük idaresinden sürekli ve periyodik olarak ithal edilen eşyada beyanname yerine ticari veya idari belgeyle işlem yapılmasına ilişkin hükümde geçen sınırlardır. En güçlü çeldirici 430 Avro sınırını aynı alıcı ölçütüyle veren seçenektir: sınır doğru, birleştirme ölçütü genişletilmiştir. Bu nedenle doğru cevap '430 Avro – Aynı gönderici tarafından Türkiye'deki bir alıcı adına gönderilen kap ve kolilerin tamamının kıymeti birlikte dikkate alınır' seçeneğidir. (MD GY 39)",
kanit="10-MENŞEİ.txt | Ticari mahiyette olmayan ve CIF kıymeti 430 Avro'yu geçmeyen eşya için menşe şahadetnamesi aranmaz || 10-MENŞEİ.txt | Aynı gönderici tarafından Türkiye'deki bir alıcı adına gönderilen kap ve kolilerin hepsi bir bütün teşkil eder ve tamamın kıymeti birlikte dikkate alınır || 39-muafiyetler.txt | 150 Avro'yu geçmeyen kişisel kullanıma mahsus kitap veya benzeri basılı yayına muafiyet || 17-BEYAN.txt | 500 Avro'yu geçmeyen diğer eşyayı aynı gümrük idaresinden sürekli ve periyodik olarak ithal",
yuva=["2009/15481 sayılı Kararda posta ve hızlı kargoyla gelen kişisel kullanıma mahsus kitap muafiyetindeki 150 Avro sınırı (sayı havuzu); kural doğru",
      "Sınır doğru; GY 39 ikinci cümle genişletilmiş: birleştirme aynı gönderici şartına bağlıdır, yalnız aynı alıcı yetmez",
      "GY 148: sürekli ve periyodik ithal edilen eşyada belgeyle işlem için 500 Avro sınırı (sayı havuzu) ile aynı alıcı ölçütü birlikte",
      "GY 148'deki 500 Avro sınırı ile GY 39 ikinci cümlesinin atlanması (kolilerin ayrı ayrı değerlendirilmesi) birlikte"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "ŞART", "KOMŞU"], duzey=["HATIRLAMA", "AYIRT"], profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 15 ---------------- GY 40/1: zorunlu bilgiler (liste dışı) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="KAPSAM_DIŞI",
z="K",
madde="Gümrük Yönetmeliği md. 40",
cek="Menşe şahadetnamesinde zorunlu bilgiler: gönderen, alıcı, kap bilgileri, cins-ağırlık, tasdik şerhi, işlem açıklaması; tarife pozisyonu sayılmamıştır.",
kok=["Gümrük Yönetmeliği'ne göre menşe şahadetnamelerinde bulunması zorunlu olan bilgiler arasında aşağıdakilerden hangisi yer almaz?"],
d="Eşyanın gümrük tarife istatistik pozisyonu",
c=["Kapların marka, numara ve sayıları",
   "Eşyanın cinsi, nev'i, daralı ve net ağırlıkları veya diğer ölçüleri",
   "Şahadetnameyi veren makamın tarih, imza ile mühür veya kaşeden oluşan tasdik şerhi",
   "Şahadetname eşyanın o ülkede gördüğü değişiklik ve işlemler nedeniyle verilmişse bu husustaki etraflı açıklamalar"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre menşe şahadetnamesi ürünün teşhis edilmesini sağlamak üzere gerekli tüm ayrıntıları taşır ve şu bilgilerin bulunması zorunludur: eşyayı gönderenin adı, soyadı; Türkiye'deki alıcısının adı, soyadı; kapların marka, numara ve sayıları; eşyanın cinsi, nev'i, daralı ve net ağırlıkları veya diğer ölçüleri; şahadetnameyi veren makamın tarih, imza ile mühür veya kaşeden oluşan tasdik şerhi; şahadetname eşyanın o ülkede gördüğü değişiklik ve işlemlerden ötürü verilmişse bu husustaki etraflı açıklamalar. Eşyanın gümrük tarife istatistik pozisyonu bu sayımda yer almaz; Yönetmelik bu ifadeyi, ekinde şahadetname bulunmayan beyannamelerin denetiminde pozisyonun değişmesi sonucu önleme tabi olunduğunun anlaşılması hâlinde kullanır. Sahada her belgede görüldüğü için akla yatkındır, ancak zorunlu bilgi değildir. En güçlü çeldirici işlem açıklamalarıdır: yalnızca şahadetname o ülkede görülen işlemler nedeniyle verilmişse aranır, yine de zorunlu bilgiler arasında sayılmıştır. Bu nedenle doğru cevap 'Eşyanın gümrük tarife istatistik pozisyonu' seçeneğidir. (MD GY 38, 40)",
kanit="10-MENŞEİ.txt | menşe şahadetnamelerinde aşağıda yazılı bilgilerin bulunması zorunludur || 10-MENŞEİ.txt | Kapların marka, numara ve sayıları || 10-MENŞEİ.txt | Şahadetnameyi veren makamın tasdik şerhi, (tarih, imza ile mührü veya kaşesi) || 10-MENŞEİ.txt | eşyanın gümrük tarife istatistik pozisyonunun değişmesi sonucunda",
yuva=["GY 40/1-c: kapların marka, numara ve sayıları (zorunlu)",
      "GY 40/1-ç: cins, nev'i, daralı ve net ağırlık veya diğer ölçüler (zorunlu)",
      "GY 40/1-d: veren makamın tasdik şerhi (zorunlu)",
      "GY 40/1-e: o ülkede görülen işlemlere ilişkin etraflı açıklamalar (zorunlu)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"], duzey=["TANIMA"], profil=[3, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2024/29; 2025/46", kapsamli=False,
),

# 16 ---------------- GY 40/2: idare amiri onayıyla giderilemeyen noksanlık ----------------
dict(
konu="Menşe", blok="SB10",
kalip="KAPSAM_DIŞI",
z="O",
madde="Gümrük Yönetmeliği md. 40",
cek="Gönderen, alıcı, cins-ağırlık ve işlem açıklamasındaki noksanlık idare amiri onayıyla giderilir; kap bilgileri ve tasdik şerhi bu kolaylığın dışındadır.",
kok=["Gümrük Yönetmeliği'ne göre, menşe şahadetnamesinde bulunması zorunlu bilgilerden hangisindeki noksanlık veya yanlışlık, şahadetnamenin gümrük idare amirinin onayı ile işleme konulabileceği hâller arasında sayılmamıştır?"],
d="Kapların marka, numara ve sayıları",
c=["Eşyayı gönderenin adı, soyadı",
   "Türkiye'deki alıcının adı, soyadı",
   "Eşyanın cinsi, nev'i, daralı ve net ağırlıkları veya diğer ölçüleri",
   "Şahadetname eşyanın o ülkede gördüğü değişiklik ve işlemler nedeniyle verilmişse bu husustaki etraflı açıklamalar"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre menşe şahadetnamesindeki zorunlu bilgilerden yalnızca dördünde noksanlık veya yanlışlık bulunması hâlinde şahadetname gümrük idare amirinin onayı ile işleme konulur: eşyayı gönderenin adı, soyadı; Türkiye'deki alıcının adı, soyadı; eşyanın cinsi, nev'i, daralı ve net ağırlıkları veya diğer ölçüleri; şahadetname o ülkede görülen işlemler nedeniyle verilmişse bu husustaki etraflı açıklamalar. Kapların marka, numara ve sayıları ile şahadetnameyi veren makamın tasdik şerhi de zorunlu bilgilerdendir, ancak bu kolaylığın kapsamında sayılmamıştır. En güçlü çeldirici işlem açıklamalarıdır: zorunlu bilgiler sayımının sonunda yer aldığı için atlanabilir, oysa idare amirinin onayıyla giderilebilecek noksanlıklar arasındadır. Bu nedenle doğru cevap 'Kapların marka, numara ve sayıları' seçeneğidir. (MD GY 40)",
kanit="10-MENŞEİ.txt | Birinci fıkranın (a), (b), (ç) ve (e) bentlerinde belirtilen hususlarda noksanlık ve yanlışlığın bulunması halinde, menşe şahadetnamesi gümrük idare amirinin onayı ile işleme konulur || 10-MENŞEİ.txt | Kapların marka, numara ve sayıları",
yuva=["GY 40/2 ile 40/1-a: gönderenin adı, soyadı (onayla giderilebilir)",
      "GY 40/2 ile 40/1-b: Türkiye'deki alıcının adı, soyadı (onayla giderilebilir)",
      "GY 40/2 ile 40/1-ç: cins, nev'i, ağırlık veya diğer ölçüler (onayla giderilebilir)",
      "GY 40/2 ile 40/1-e: o ülkede görülen işlemlere ilişkin açıklamalar (onayla giderilebilir)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "TERSİNE"], duzey=["AYIRT"], profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2024/29", kapsamli=False,
),

# 17 ---------------- GY 41: inceleme, sonradan kontrol, müeyyide ----------------
dict(
konu="Menşe", blok="SB10",
kalip="YANLIŞ",
z="O",
madde="Gümrük Yönetmeliği md. 41",
cek="Menşe şahadetnamesinin sıhhatinde aykırılık tespitinde duruma göre 5607 sayılı Kaçakçılıkla Mücadele Kanunu uygulanır; tereddütte sonradan kontrol yapılır.",
kok=["Gümrük Yönetmeliği'ne göre gümrük idarelerine ibraz olunan menşe şahadetnamelerinin incelenmesi ve sonradan kontrolüne ilişkin aşağıdaki ifadelerden hangisi yanlıştır?"],
d="İnceleme sonucunda şahadetnamenin sıhhati konusunda bir aykırılık tespit edilmesi hâlinde, duruma göre 4458 sayılı Gümrük Kanunu'ndaki usulsüzlük cezası hükümleri uygulanır",
c=["Şahadetnamede yer alan bilgilerin gerçeğe aykırı olduğu yönünde şüphe veya ihbar bulunması hâlinde, gümrük idaresince eşya, eşyanın orijinal ambalajı, markası ve patenti gibi hususlarda inceleme yapılır",
   "İnceleme sonucunda şahadetnamenin gerçekliği hakkında yeterli kanaat elde edilemez ve tereddüt devam ederse, şahadetname bu kanaati uyandıran tüm bilgi ve belgelerle birlikte sonradan kontrol talebiyle Müsteşarlığa gönderilir",
   "Müsteşarlıkça ihracatçı ülke gümrük idaresi nezdinde yapılan incelemeler sonucunda elde edilen bilgiler çerçevesinde işlem yapılması için keyfiyet ilgili gümrük idaresine bildirilir",
   "Ticaret politikası önlemlerine tabi eşya için yükümlülerce yazılı talepte bulunulması hâlinde, tahsili gereken vergi veya diğer mali yükümlülükler teminata bağlanarak eşya araştırma sonucu beklenmeden teslim edilebilir"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre ibraz olunan menşe şahadetnamelerinde yer alan bilgilerin gerçeğe aykırı olduğu yönünde şüphe veya ihbar varsa gümrük idaresi eşya, orijinal ambalaj, marka ve patent gibi hususlarda inceleme yapar; inceleme sonucunda şahadetnamenin sıhhati konusunda aykırılık tespit edilirse duruma göre 5607 sayılı Kaçakçılıkla Mücadele Kanunu hükümleri uygulanır. Gümrük Kanunu'ndaki usulsüzlük cezası bu hükümde yer almaz; ifade bu yüzden yanlıştır. Tereddüt devam ederse şahadetname tüm bilgi ve belgelerle sonradan kontrol talebiyle Müsteşarlığa gönderilir; Müsteşarlıkça ihracatçı ülke gümrük idaresi nezdinde yapılan incelemelerin sonucu ilgili gümrük idaresine bildirilir. Önlemlere tabi eşya, yükümlünün yazılı talebi üzerine, tahsili gereken tutarlar teminata bağlanarak araştırma sonucu beklenmeden teslim edilebilir. En güçlü çeldirici teminatla teslime ilişkin ifadedir: yazılı talep şartıyla Yönetmelikte aynen yer alır. Bu nedenle doğru cevap 'İnceleme sonucunda şahadetnamenin sıhhati konusunda bir aykırılık tespit edilmesi hâlinde, duruma göre 4458 sayılı Gümrük Kanunu'ndaki usulsüzlük cezası hükümleri uygulanır' seçeneğidir. (MD GY 41)",
kanit="10-MENŞEİ.txt | İnceleme sonucunda şahadetnamenin sıhhati konusunda bir aykırılığın tespiti halinde duruma göre 5607 sayılı Kaçakçılıkla Mücadele Kanunu hükümleri uygulanır || 10-MENŞEİ.txt | gümrük idaresince eşya, eşyanın orijinal ambalajı, markası ve patenti gibi hususlarda inceleme yapılır || 10-MENŞEİ.txt | sonradan kontrol talebiyle Müsteşarlığa gönderilir || 10-MENŞEİ.txt | teminata bağlanmak suretiyle eşya araştırma sonucu beklenmeden teslim edilebilir",
yuva=["GY 41/1 ilk cümle: şüphe veya ihbarda gümrük idaresince inceleme (doğru ifade)",
      "GY 41/2 ilk cümle: tereddüt sürerse sonradan kontrol talebiyle Müsteşarlığa (doğru ifade)",
      "GY 41/2 ikinci cümle: sonucun ilgili gümrük idaresine bildirilmesi (doğru ifade)",
      "GY 41/3: yazılı talep ve teminatla araştırma sonucu beklenmeden teslim (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"], duzey=["AYIRT"], profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 18 ---------------- GY 42: Türkiye'den ihracatta menşe şahadetnamesi (meslek yanlılığı) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="YANLIŞ",
z="O",
madde="Gümrük Yönetmeliği md. 42",
cek="Türkiye'den ihracatta menşe şahadetnamesi ihracatçının veya sorumluluğundaki yetkili temsilcisinin yazılı başvurusuyla düzenlenir; gümrük müşaviri şart değildir.",
kok=["Gümrük Yönetmeliği'ne göre Türkiye'den ihracatta düzenlenecek menşe şahadetnamelerine ilişkin aşağıdaki ifadelerden hangisi yanlıştır?"],
d="Menşe şahadetnamesi, ancak ihracatçı adına hareket eden gümrük müşavirinin yazılı başvurusu üzerine düzenlenir",
c=["Menşe şahadetnamesi Türkçe, İngilizce ve Fransızca dillerinde basılır; başvuru formu ise Türkçe dilinde basılır",
   "Menşe şahadetnamesi, biri meneviş desenli baskılı zeminli, ikisi beyaz olan üç nüshalık takım hâlindedir",
   "Başvuru formu Türkçe dilinde doldurulur; menşe şahadetnamesi ise Türkçe ya da ticaretin gereklerine göre herhangi bir dilde doldurulabilir",
   "İhracatın düzenli aralıklarla yapılması ve eşyanın menşe şartlarını karşıladığına ilişkin gerekli teminatların verilmesi kaydıyla, yetkili makamlar her ihracat işlemi için ayrı başvuru formu istemeyebilir"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre Türkiye'den ihracatta menşe şahadetnamesi, ihracatçının veya ihracatçının sorumluluğundaki yetkili temsilcisinin yazılı başvurusuna binaen düzenlenir; başvuruyu ihracatçının kendisi de yapabilir ve gümrük müşavirinin başvurusu şart değildir. Bu ifade, 'her işlemde gümrük müşaviri şarttır' önyargısını yoklar. Diğer ifadeler Yönetmelikte yer alır: şahadetname Türkçe, İngilizce ve Fransızca, başvuru formu Türkçe basılır; şahadetname biri meneviş desenli baskılı zeminli, ikisi beyaz üç nüshalık takımdır; başvuru formu Türkçe, şahadetname Türkçe ya da ticaretin gereklerine göre herhangi bir dilde doldurulur; ihracat düzenli aralıklarla yapılıyor ve gerekli teminatlar verilmişse her işlem için ayrı başvuru formu istenmeyebilir. En güçlü çeldirici dil ifadesidir: basımda üç dil sayılırken doldurmada 'herhangi bir dil' serbestliği tanınmıştır. Bu nedenle doğru cevap 'Menşe şahadetnamesi, ancak ihracatçı adına hareket eden gümrük müşavirinin yazılı başvurusu üzerine düzenlenir' seçeneğidir. (MD GY 42)",
kanit="10-MENŞEİ.txt | Menşe şahadetnamesi ihracatçının veya ihracatçının sorumluluğundaki yetkili temsilcisinin yazılı başvurusuna binaen düzenlenir || 10-MENŞEİ.txt | Başvuru formu Türkçe dilinde, menşe şahadetnamesi ise Türkçe, İngilizce ve Fransızca dillerinde basılır || 10-MENŞEİ.txt | Menşe şahadetnamesi biri meneviş desenli baskılı zeminli, ikisi beyaz olan üç nüshalık takım halindedir || 10-MENŞEİ.txt | menşe şahadetnamesi ise Türkçe ya da ticaretin gereklerine göre herhangi bir dilde doldurulur || 10-MENŞEİ.txt | yetkili makamlar her bir ihracat işlemi için ayrı bir başvuru formu istemeyebilir",
yuva=["GY 42/3: basım dilleri (doğru ifade)",
      "GY 42/3 son cümle: üç nüshalık takım (doğru ifade)",
      "GY 42/4: doldurma dili serbestliği (doğru ifade)",
      "GY 42/2: düzenli ihracatta ayrı başvuru formu istenmeyebilir (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["MUTLAK", "UNSUR"], duzey=["AYIRT"], profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 19 ---------------- GY 205/1-3, 7: tescil tarihi, belge geçerliliği, ibraz yeri, numune (tek kelime değişikliği; önermeliden çevrildi) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="YANLIŞ",
z="O",
madde="Gümrük Yönetmeliği md. 205",
cek="Önlemlerde tescil tarihi esas; tescil tarihinde süresi dolmuş belge kabul edilmez; şahadetname beyanname ekinde; numunelere bu hükümler uygulanmaz.",
kok=["Gümrük Yönetmeliği'nin serbest dolaşıma girişte ticaret politikası önlemleri, ilave gümrük vergisi ve diğer mali yükümlülüklere ilişkin hükümlerine göre aşağıdakilerden hangisi yanlıştır?"],
d="Önlem kararı bir belgeye istinaden uygulanıyorsa, beyannamenin tescil tarihi itibarıyla geçerlilik süresi sona ermiş belgeler de kabul edilir.",
c=["Eşyanın serbest dolaşıma girişinde, o tarihte yürürlükte bulunan ticaret politikası önlemlerine ilişkin mevzuat ile konulmuş hükümler de uygulanır.",
   "Önlemlerin, ilave gümrük vergisinin veya diğer mali yükümlülüklerin uygulanmasında serbest dolaşıma giriş beyannamesinin tescil tarihi esas alınır.",
   "Bu yükümlülüklere tabi eşyanın menşei menşe şahadetnamesi ile ispat olunur ve şahadetname, serbest dolaşıma girişe ilişkin beyanname ekinde ibraz edilir.",
   "Numunelerin serbest dolaşıma girişinde bu hükümler uygulanmaz."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre önlem kararının düzenlenecek bir belgeye istinaden uygulanması durumunda, gümrük beyannamesinin tescil tarihi itibarıyla geçerlilik süresi sona eren belgeler kabul edilmez; yanlış ifade 'kabul edilmez' hükmünü 'kabul edilir' biçimine çevirmiştir. Diğer ifadeler Yönetmelikte yer alır: serbest dolaşıma girişte o tarihte yürürlükte bulunan ticaret politikası önlemlerine, ilave gümrük vergisine veya diğer mali yükümlülüklere ilişkin mevzuat ile konulmuş hükümler de uygulanır; bu yükümlülüklerin uygulanmasında serbest dolaşıma giriş beyannamesinin tescil tarihi esas alınır; yükümlülüklere tabi eşyanın menşei menşe şahadetnamesi ile ispat olunur ve şahadetname beyanname ekinde ibraz edilir; numunelerin serbest dolaşıma girişinde ise bu hükümler uygulanmaz. Belgenin geçerliliği de önlemin uygulanmasında esas alınan tescil tarihine göre değerlendirilir. Numunelere ilişkin istisna, beklenmedik göründüğü için yanlış sanılabilecek en güçlü tuzaktır. Bu nedenle doğru cevap 'Önlem kararı bir belgeye istinaden uygulanıyorsa, beyannamenin tescil tarihi itibarıyla geçerlilik süresi sona ermiş belgeler de kabul edilir.' seçeneğidir. (MD GY 205)",
kanit="10-MENŞEİ.txt | gümrük beyannamesinin tescil tarihi itibariyle geçerlilik süresi sona eren belgeler kabul edilmez || 10-MENŞEİ.txt | o tarihte yürürlükte bulunan ticaret politikası önlemlerine, ilave gümrük vergisine veya ek mali yükümlülük gibi diğer mali yükümlülüklere ilişkin mevzuat ile konulmuş hükümler de uygulanır || 10-MENŞEİ.txt | serbest dolaşıma giriş beyannamesinin tescil tarihi esas alınır || 10-MENŞEİ.txt | Menşe şahadetnamesi, eşyanın serbest dolaşıma girişine ilişkin beyanname ekinde ibraz edilir || 10-MENŞEİ.txt | Numunelerin serbest dolaşıma girişinde bu madde hükümleri uygulanmaz",
yuva=["GY 205/1: girişte yürürlükteki önlemlere ilişkin hükümlerin uygulanması (doğru ifade)",
      "GY 205/2 ilk cümle: tescil tarihinin esas alınması (doğru ifade)",
      "GY 205/3: menşein şahadetnameyle ispatı ve beyanname ekinde ibraz (doğru ifade)",
      "GY 205/7: numunelerde hükümlerin uygulanmaması (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU"], duzey=["HATIRLAMA"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 20 ---------------- GY 205/4, 38/1: menşe şahadetnamesi aranmayan hâl (A.TR) ----------------
dict(
konu="Menşe", blok="SB10",
kalip="TABİ",
z="Z",
madde="Gümrük Yönetmeliği md. 205, 38",
cek="AB'den A.TR eşliğinde gelen eşyada menşe şahadetnamesi aranmaz; önlem ülkesi menşeli beyanda birden fazla önlem ya da ülkeye göre farklı oranda aranır.",
kok=["Gümrük Yönetmeliği'ne göre ticaret politikası önlemlerine, ilave gümrük vergisine veya ek mali yükümlülük gibi diğer mali yükümlülüklere tabi eşyanın serbest dolaşıma girişinde aşağıdaki durumların hangisinde menşe şahadetnamesi aranmaz?"],
d="1/95 sayılı Ortaklık Konseyi Kararının ticaret politikası önlemlerine ilişkin hükümleri saklı kalmak üzere, AB'ye üye ülkelerden A.TR Dolaşım Belgesi eşliğinde gelen eşyada",
c=["Önlemin uygulandığı ülke dışındaki bir ülkeden gelen eşyanın, önlemin uygulanmaması için söz konusu önleme tabi ülke menşeli olmadığının tevsik edilmesi gereken durumda",
   "Önlemin uygulandığı ülke menşeli olduğu beyan edilen eşyanın, aynı zamanda birden fazla ticaret politikası önlemine tabi olması durumunda",
   "Önlemin uygulandığı ülke menşeli olduğu beyan edilen eşya için aynı düzenleme kapsamında ülkesine göre farklı oranların belirlenmiş olması durumunda",
   "Dünya Ticaret Örgütü üyesi olmayan ülkeler için öngörülen daha yüksek gümrük vergisi oranının uygulanmaması için eşyanın bu Örgüte üye bir ülke menşeli olduğunun tevsik edilmesi gereken durumda"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre bu yükümlülüklere tabi eşyanın serbest dolaşıma girişinde menşe şahadetnamesi aranmayan hâller sayılmıştır: tercihli menşei tevsik eden belgelerin ibrazı; serbest ticaret anlaşmaları veya Genelleştirilmiş Tercihler Sistemi çerçevesindeki tercihli tarifenin kalktığı tarihten önce gümrük gözetimindeki eşyaya ait bu belgelerin ibrazı; doğrudan önlem uygulanan ülkeden ithal edilen veya o ülke menşeli olduğu beyan edilen eşya; 1/95 sayılı Ortaklık Konseyi Kararının ticaret politikası önlemlerine ilişkin hükmü saklı kalmak üzere AB'ye üye ülkelerden A.TR Dolaşım Belgesi eşliğinde gelen eşya. Önlem uygulanan ülke menşeli beyan edilen eşya aynı zamanda birden fazla önleme tabiyse veya aynı düzenlemede ülkesine göre farklı oranlar belirlenmişse, bu hâlin istisnası olarak şahadetname aranır; ibraz edilmezse tahsil edilmesi gerekenlerden en yüksek tutarlar esas alınır. Önlemin uygulanmaması için eşyanın önleme tabi ülke menşeli olmadığının veya Dünya Ticaret Örgütü üyesi ülke menşeli olduğunun tevsiki gerekiyorsa da menşe ülkenin veya ihracatçı ülkenin yetkili makamlarınca düzenlenmiş şahadetname ibraz edilir. En güçlü çeldiriciler istisna hâlleridir: önlem uygulanan ülke menşeli beyan genel olarak şahadetname aranmayan bir hâldir, fakat birden fazla önlem veya farklı oran varsa şahadetname aranır. Bu nedenle doğru cevap '1/95 sayılı Ortaklık Konseyi Kararının ticaret politikası önlemlerine ilişkin hükümleri saklı kalmak üzere, AB'ye üye ülkelerden A.TR Dolaşım Belgesi eşliğinde gelen eşyada' seçeneğidir. (MD GY 38, 205)",
kanit="10-MENŞEİ.txt | AB'ye üye ülkelerden A.TR Dolaşım Belgesi eşliğinde gelen eşyanın serbest dolaşıma girişinde, || 10-MENŞEİ.txt | eşyanın aynı zamanda birden fazla ticaret politikası önlemi, ilave gümrük vergisi veya ek mali yükümlülük gibi diğer mali yükümlülüklere tabi olması ya da aynı düzenleme kapsamında ülkesine göre farklı oranların belirlenmiş olması durumunda menşe şahadetnamesi aranır || 10-MENŞEİ.txt | eşyanın Dünya Ticaret Örgütü üyesi ülke menşeli olduğunu tevsik etmek üzere menşe ülkenin veya ihracatçı ülkenin yetkili makamlarınca düzenlenmiş olan menşe şahadetnamesi ibraz edilir",
yuva=["GY 38/1: önleme tabi ülke menşeli olmadığının tevsiki için şahadetname ibraz edilir (aranır)",
      "GY 205/4 son cümleler: birden fazla önleme tabi olma istisnası (aranır)",
      "GY 205/4 son cümleler: ülkesine göre farklı oran istisnası (aranır)",
      "GY 38/1 ve 205/5: DTÖ üyesi ülke menşeinin tevsiki için şahadetname ibraz edilir (aranır)"],
yakinlik="PARAFRAZ",
tuzak=["İSTİSNA", "KOMŞU"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2023/42", kapsamli=False,
),

]
