# Soru Bankası — Bölüm 13: Kabotaj (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
# Kaynak: 14-KABOTAJ.txt (Türkiye Limanları ve İskeleleri Arasında Deniz Taşıtlarıyla Yapılan Taşıma ile Yükleme ve
# Boşaltmalarda Gümrük Gözetim ve Kontrolü Usul ve Esaslarına İlişkin Tebliğ, 07.06.2013/28670 R.G.);
# çıkmış alan 2021/70 için 42-kumanya.txt (Gümrük Yönetmeliği md. 481: kabotaja girecek gemilerin yakıtı)
T = "Türkiye Limanları ve İskeleleri Arasında Deniz Taşıtlarıyla Yapılan Taşıma ile Yükleme ve Boşaltmalarda Gümrük Gözetim ve Kontrolü Usul ve Esaslarına İlişkin Tebliğ"
K = "14-KABOTAJ.txt"
KU = "42-kumanya.txt"
CZ = "48-cezalar.txt"
M = "Kabotaj Tebliği (07.06.2013/28670 R.G.)"
Q = [

# 1 — Amaç, dayanak, kapsam, yürütme (önermeli; I, II, IV doğru)
dict(
konu="Kabotaj", blok="SB13",
kalip="ÖNERMELİ",
z="O",
madde=M + " md. 1, 2, 14, 17",
cek="Tebliğ, kaçakçılığın önlenmesine yönelik olarak tüm deniz taşıtlarıyla limanlar arası taşımayı kapsar; 4458, 5607 ve 815 sayılı Kanunlara dayanır; Bakan yürütür.",
kok=[T + "'e göre Tebliğin amacı, dayanağı, kapsamı ve yürütülmesine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Tebliğin amacı, kaçakçılığın önlenmesine yönelik olarak Türkiye Gümrük Bölgesindeki limanlar ve iskeleler arasında yapılan taşıma ile yükleme ve boşaltmalarda gümrük gözetimi ve kontrolüne ilişkin usul ve esasları düzenlemektir.",
     "II. Tebliğ, 4458 sayılı Gümrük Kanunu ve 5607 sayılı Kaçakçılıkla Mücadele Kanununun yanı sıra 815 sayılı Türkiye Sahillerinde Nakliyatı Bahriye ve Limanlarla Karasuları Dâhilinde İcrayı Sanat ve Ticaret Hakkında Kanuna da dayanılarak hazırlanmıştır.",
     "III. Tebliğ hükümleri, yalnızca Türk bayraklı deniz taşıtlarıyla yapılan taşıma ile yükleme ve boşaltmalarda uygulanır.",
     "IV. Tebliğ hükümlerini Gümrük ve Ticaret Bakanı yürütür.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, II ve IV",
c=["I ve II", "I ve III", "II ve IV", "I, II, III ve IV"],
sirali=False,
g="Tebliğ'e göre Tebliğin amacı, kaçakçılığın önlenmesine yönelik olarak Türkiye Gümrük Bölgesindeki limanlar ve iskeleler arasında tüm deniz taşıtlarıyla yapılan taşıma ile yükleme ve boşaltmalarda gümrük gözetimi ve kontrolüne ilişkin usul ve esasları düzenlemektir (I doğru). Tebliğ; 4458 sayılı Gümrük Kanunu, 5607 sayılı Kaçakçılıkla Mücadele Kanunu ve 815 sayılı Türkiye Sahillerinde Nakliyatı Bahriye ve Limanlarla Karasuları Dâhilinde İcrayı Sanat ve Ticaret Hakkında Kanuna dayanılarak hazırlanmıştır (II doğru). Amaç hükmü 'tüm deniz taşıtları' ifadesini kullanır; Tebliğ yabancı bayraklı gemilerle yapılan taşımaları da düzenler, örneğin serbest dolaşımdaki eşyanın yabancı bayraklı gemilerle taşındığı tespit edilirse konu mülki idare amirine intikal ettirilir. Bu nedenle kapsamı yalnızca Türk bayraklı taşıtlarla sınırlayan III yanlıştır. Tebliğ hükümlerini Gümrük ve Ticaret Bakanı yürütür (IV doğru). En güçlü tuzak III. önermedir: Tebliğde yabancı limana uğrayan ve uluslararası sefer yapan gemilere ilişkin özel hükümler Türk bayraklı gemiler için kurulmuştur; bu, Tebliğin bütününün Türk bayraklı taşıtlarla sınırlı olduğu anlamına gelmez. Bu nedenle doğru cevap 'I, II ve IV' seçeneğidir. (MD 1, 2, 14, 17)",
kanit=K + " | kaçakçılığın önlenmesine yönelik olarak, Türkiye Gümrük Bölgesindeki limanlar ve iskeleler arasında tüm deniz taşıtlarıyla yapılan taşıma ile yükleme ve boşaltmalarda || " + K + " | 4458 sayılı Gümrük Kanununun 10 uncu ve 34 üncü maddeleri || " + K + " | 5607 sayılı Kaçakçılıkla Mücadele Kanununun 7 nci maddesi || " + K + " | 815 sayılı Türkiye Sahillerinde Nakliyatı Bahriye ve Limanlarla Karasuları Dâhilinde İcrayı Sanat ve Ticaret Hakkında Kanunun 1 inci ve 2 nci maddelerine dayanılarak hazırlanmıştır || " + K + " | Serbest dolaşımdaki eşyanın yabancı bayraklı gemilerle taşındığının tespit edilmesi halinde || " + K + " | Bu Tebliğ hükümlerini Gümrük ve Ticaret Bakanı yürütür.",
yuva=["Eksik seçim: yürütme hükmü (IV) dışarıda bırakılmış",
      "III, amaç hükmündeki 'tüm deniz taşıtları' ifadesine aykırıdır; yabancı limana uğrama ve uluslararası sefer hükümlerindeki 'Türk bayraklı gemiler' kaydından taşınmıştır",
      "Eksik seçim: amaç hükmünün kendisi (I) dışarıda bırakılmış",
      "En kapsamlı şık: III'teki 'yalnızca Türk bayraklı' kaydını görmeyen adayı yakalar"],
yakinlik="BİREBİR",
tuzak=["UNSUR", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 2 — Tanım: liman başkanlığı (addan tanım)
dict(
konu="Kabotaj", blok="SB13",
kalip="TANIM",
z="K",
madde=M + " md. 3, 4",
cek="Tebliğde liman başkanlığı, Ulaştırma, Denizcilik ve Haberleşme Bakanlığı liman başkanlıklarını; Bakanlık ise Gümrük ve Ticaret Bakanlığını ifade eder.",
kok=[T + "'in uygulanmasında kullanılan \"liman başkanlığı\" ifadesinin tanımı aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Ulaştırma, Denizcilik ve Haberleşme Bakanlığı liman başkanlıkları",
c=["Gümrük ve Ticaret Bakanlığının taşra teşkilatında yer alan liman başkanlıkları",
   "Gümrük ve muhafaza başmüdürlükleri",
   "Gümrük idaresi bulunmayan liman ve iskelelerde görev yapan gümrük muhafaza birimleri",
   "Liman işletme müdürlükleri"],
sirali=False,
g="Tebliğ'in tanımlar hükmünde 'liman başkanlığı', Ulaştırma, Denizcilik ve Haberleşme Bakanlığı liman başkanlıklarını ifade eder. Aynı hükümde 'Bakanlık' Gümrük ve Ticaret Bakanlığı olarak tanımlanmıştır. Beyannameleri seri numaralı olarak bastıran ve gümrük idaresi bulunmayan yerlerde liman başkanlığına zimmetle veren Bakanlık Gümrük ve Ticaret Bakanlığıdır; ancak liman başkanlıkları bu Bakanlığın birimi değildir. En güçlü çeldirici liman başkanlıklarını Gümrük ve Ticaret Bakanlığına bağlayan seçenektir: iki ayrı tanımı birleştirir. Gümrük ve muhafaza başmüdürlükleri ile liman işletme müdürlükleri gümrük mevzuatının başka hükümlerinde geçen birimlerdir; gümrük muhafaza personeli ise Tebliğde beyannameyi imzalayıp mühürleyen görevlidir. Bu nedenle doğru cevap 'Ulaştırma, Denizcilik ve Haberleşme Bakanlığı liman başkanlıkları' seçeneğidir. (MD 3, 4)",
kanit=K + " | Liman başkanlığı: Ulaştırma, Denizcilik ve Haberleşme Bakanlığı liman başkanlıklarını || " + K + " | Bakanlık: Gümrük ve Ticaret Bakanlığını || " + K + " | Beyannameler, Bakanlık tarafından seri numaralı olarak bastırılır",
yuva=["Tanımlar hükmü: 'Bakanlık' Gümrük ve Ticaret Bakanlığıdır; iki ayrı tanım birleştirilmiş",
      "Gümrük Yönetmeliği akaryakıt ve kumanya hükümleri: süre uzatımına yetkili gümrük ve muhafaza başmüdürlükleri",
      "Yükleme ve boşaltma hükümleri: beyannameyi imzalayıp mühürleyen gümrük muhafaza personeli",
      "Serbest bölge mevzuatı: liman başkanlığı ile birlikte anılan liman işletme müdürlüğü"],
yakinlik="BİREBİR",
tuzak=["TERİM", "MAKAM"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 3 — Beyanname içeriği (liste dışı unsur)
dict(
konu="Kabotaj", blok="SB13",
kalip="KAPSAM_DIŞI",
z="O",
madde=M + " md. 4",
cek="Kabotaj beyannamesinde gemi bilgileri, liman çıkış belgesi, mühürler, eşyanın cinsi, kap bilgileri, gönderici ve alıcı bulunur; tarife pozisyonu sayılmamıştır.",
kok=[T + "'e göre kabotaj beyannamelerinde bulunması gereken bilgiler arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="Eşyanın gümrük tarife istatistik pozisyonu",
c=["Geminin IMO numarası, gros tonu ve kütük numarası",
   "Liman çıkış belgesi ile mühür adedi ve numaraları",
   "Kapların adedi, markası, numarası ve ağırlığı",
   "Eşyanın göndericisi ve alıcısı"],
sirali=False,
g="Tebliğ'e göre beyannamelerde; gümrük idaresinin ya da liman başkanlığının adı, geminin adı, IMO numarası, gros tonu, kütük numarası, yükleme ve boşaltma limanları, kaptanın adı ve soyadı, liman çıkış belgesi, donatanı, acentesi ile mühür adedi ve numaraları; eşyanın cinsi; kapların adedi, markası, numarası, ağırlığı; eşyanın göndericisi ve alıcısı ile gerekli diğer bilgiler bulunur. Sayılan bilgiler arasında eşyanın gümrük tarife istatistik pozisyonu yoktur; beyannamede eşya cinsiyle gösterilir. Bu unsur, Gümrük Yönetmeliği'ne göre dış sefer yapan Türk bandıralı gemilerde tutulan yakıt ve kumanya defterine yazılan bilgiler arasındadır; gümrük işlemlerinde sık görüldüğü için akla yatkın bir çeldiricidir. Bu nedenle doğru cevap 'Eşyanın gümrük tarife istatistik pozisyonu' seçeneğidir. (MD 4; GY 479)",
kanit=K + " | gros tonu, kütük numarası, yükleme ve boşaltma limanları, kaptanın adı ve soyadı, liman çıkış belgesi, donatanı, acentesi ile mühür adedi ve numaraları || " + K + " | Kapların adedi, markası, numarası, ağırlığı || " + K + " | Eşyanın göndericisi ve alıcısı ile gerekli diğer bilgiler || " + KU + " | Bu deftere yakıt ve kumanyanın gümrük tarife istatistik pozisyonu, miktarı ve beyanname ile faturanın numara ve tarihi",
yuva=["Beyanname içeriği: geminin IMO numarası, gros tonu ve kütük numarası sayılmıştır",
      "Beyanname içeriği: liman çıkış belgesi ile mühür adedi ve numaraları sayılmıştır",
      "Beyanname içeriği: kapların adedi, markası, numarası, ağırlığı sayılmıştır",
      "Beyanname içeriği: eşyanın göndericisi ve alıcısı sayılmıştır"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 4 — Beyannamenin basımı ve kullanımı (makam değişikliği; yanlış ifade)
dict(
konu="Kabotaj", blok="SB13",
kalip="YANLIŞ",
z="O",
madde=M + " md. 3, 4",
cek="Kabotaj beyannameleri Bakanlıkça seri numaralı bastırılır; gümrük idaresi bulunmayan yerlerde liman başkanlığına zimmetle verilir; silinti ve kazıntı yapılamaz.",
kok=[T + "'e göre kabotaj beyannamesine ilişkin aşağıdaki ifadelerden hangisi yanlıştır?"],
d="Beyannameler liman başkanlıklarınca seri numaralı olarak bastırılır ve gümrük idarelerinin bulunduğu yerlerde bu idarelere zimmetle verilir.",
c=["Beyannamelerde silinti veya kazıntı yapılamaz.",
   "Eşyanın çeşitli olması veya göndericisi ile alıcısının birden fazla olması nedeniyle beyannamenin ilgili alanlarının yeterli olmadığı durumlarda birden fazla beyanname kullanılabilir.",
   "Beyanname vermekle yükümlü olanlar, beyannamede yazılı olanlardan başka sefer harici yükleri olmadığını beyan ederek beyannameyi imzalamak zorundadır.",
   "Kaptan veya acente, liman çıkış belgesi ve kabotaj eşyasına ilişkin belgeler ile gümrük idaresince gerek görülecek diğer belgeleri ibraz etmek zorundadır."],
sirali=False,
g="Tebliğ'e göre beyannameler Bakanlık, yani Gümrük ve Ticaret Bakanlığı tarafından seri numaralı olarak bastırılır; gümrük idarelerinin bulunduğu yerlerde bu idarelere, bulunmadığı yerlerde ise liman başkanlığına zimmetle verilir. Liman başkanlığı beyannameyi basan makam değil, gümrük idaresi bulunmayan yerlerde beyannameyi zimmetle teslim alan makamdır; yanlış ifade bu iki rolü yer değiştirmiştir. Diğer ifadeler hükmün kendisidir: beyannamelerde silinti veya kazıntı yapılamaz; alanların yetmediği durumlarda birden fazla beyanname kullanılabilir; beyanname vermekle yükümlü olanlar eşyayı boşaltma limanı olarak gösterilen yere götüreceklerini ve beyannamede yazılı olanlardan başka sefer harici yükleri olmadığını beyan ederek imzalar; kaptan veya acente liman çıkış belgesi, kabotaj eşyasına ilişkin belgeler ve gümrük idaresince gerek görülecek diğer belgeleri ibraz eder. Bu nedenle doğru cevap 'Beyannameler liman başkanlıklarınca seri numaralı olarak bastırılır ve gümrük idarelerinin bulunduğu yerlerde bu idarelere zimmetle verilir.' seçeneğidir. (MD 3, 4)",
kanit=K + " | Beyannameler, Bakanlık tarafından seri numaralı olarak bastırılır ve gümrük idarelerinin bulunduğu yerlerde bu idarelere, bulunmadığı yerlerde ise liman başkanlığına zimmetle verilir. || " + K + " | Beyannamelerde silinti veya kazıntı yapılamaz. || " + K + " | beyannamelerin ilgili alanlarının yeterli olmadığı durumlarda, birden fazla beyanname kullanılabilir || " + K + " | başka sefer harici yükü olmadığını beyan ederek imzalamaları zorunludur || " + K + " | liman çıkış belgesi ve kabotaj eşyasına ilişkin belgeler ile gümrük idaresince gerek görülecek diğer belgeleri ibraz etmek zorundadır",
yuva=["Beyannameye ilişkin hüküm: silinti veya kazıntı yasağı (doğru ifade)",
      "Beyannameye ilişkin hüküm: alanların yetmediği durumda birden fazla beyanname (doğru ifade)",
      "Beyannameye ilişkin hüküm: sefer harici yük bulunmadığının beyan edilerek imzalanması (doğru ifade)",
      "Beyannameye ilişkin hüküm: kaptan veya acentenin ibraz edeceği belgeler (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 5 — Yüklemede beyannameyi düzenleyen ve nüsha sayısı (iki bilgi; meslek yanlılığı)
dict(
konu="Kabotaj", blok="SB13",
kalip="YETKİ",
z="O",
madde=M + " md. 5, 6, 7, 9",
cek="Gümrük idaresi bulunan limandan yüklemede beyanname kaptan ve acente tarafından üç nüsha düzenlenip imzalanır; gümrük muhafaza personeli imzalayıp mühürler.",
kok=[T + "'e göre gümrük idaresinin bulunduğu liman ve iskelelerden yapılacak yüklemelerde, yüke ilişkin beyannameyi düzenleyip imzalayacak olanlar ile beyannamenin düzenleneceği nüsha sayısı aşağıdakilerden hangisinde birlikte doğru olarak verilmiştir?"],
d="Kaptan ve acente – üç nüsha",
c=["Kaptan ve acente – iki nüsha",
   "Gümrük muhafaza personeli – üç nüsha",
   "Kaptan ve acentenin yetkilendirdiği gümrük müşaviri – üç nüsha",
   "Yükleme yerindeki liman başkanlığı – iki nüsha"],
sirali=False,
g="Tebliğ'e göre gümrük idaresinin bulunduğu liman ve iskelelerden yapılacak yüklemelerde beyanname, yüke ilişkin olarak kaptan ve acente tarafından üç nüsha düzenlenip imzalanır ve gümrük idaresine ibraz edilir. Gümrük muhafaza personeli beyannameyi düzenlemez; ibraz edilen beyannameyi imzalayarak mühürler. İki nüsha, ilave yük alınırken ve boşaltma limanında kaptandan istenen beyanname sayısıdır; çünkü yükleme sonunda birinci nüsha gümrük idaresinde kalır, diğer iki nüsha kaptana verilir. Beyannamenin liman başkanlığınca düzenlenmesi yalnızca gümrük idaresi bulunmayan liman ve iskeleler için öngörülmüştür. Tebliğ bu beyannamenin düzenlenmesi yükümlülüğünü doğrudan kaptan ve acenteye vermiştir; gümrük müşavirine ilişkin bir hüküm içermez. Bu nedenle doğru cevap 'Kaptan ve acente – üç nüsha' seçeneğidir. (MD 5, 6, 7, 9)",
kanit=K + " | Kaptan ve acente tarafından, yüke ilişkin üç nüsha olarak düzenlenerek imzalanan beyanname gümrük idaresine ibraz edilir ve gümrük muhafaza personeli tarafından imzalanarak mühürlenir. || " + K + " | kaptanda mevcut iki nüsha beyanname istenilerek || " + K + " | gümrük idaresine ibraz edilen iki nüsha beyanname esas alınarak eşya boşaltılır || " + K + " | Yükleme yerindeki liman başkanlığınca 4 üncü maddedeki esaslar çerçevesinde düzenlenen beyanname",
yuva=["İlave yük ve boşaltma hükümleri: kaptandan istenen iki nüsha beyanname",
      "Yükleme hükmü: ibraz edilen beyannameyi imzalayıp mühürleyen gümrük muhafaza personeli (düzenleyen değil)",
      "Meslek yanlılığı çeldiricisi: Tebliğ beyannameyi kaptan ve acenteye düzenletir; gümrük müşaviri gümrük beyanında temsil hükümlerinden taşınmıştır",
      "Gümrük idaresi bulunmayan yerler: beyannameyi yükleme yerindeki liman başkanlığı düzenler"],
yakinlik="BİREBİR",
tuzak=["SAYI", "MAKAM", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 6 — Yükleme sonrası nüsha dağılımı (ayna: boşaltma sonrası dağılım, soru 9)
dict(
konu="Kabotaj", blok="SB13",
kalip="DOĞRU",
z="O",
madde=M + " md. 5",
cek="Yüklemede beyannamenin birinci nüshası gümrük idaresince alıkonulur, ikinci ve üçüncü nüshası kaptana verilir; bir örneği varış gümrük idaresine gönderilir.",
kok=[T + "'e göre gümrük idaresinin bulunduğu limanda yükleme işlemleri tamamlanan kabotaj beyannamesinin nüshalarına ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Birinci nüshası gümrük idaresince alıkonulur, ikinci ve üçüncü nüshası kaptana teslim edilir.",
c=["Birinci ve ikinci nüshası gümrük idaresince alıkonulur, üçüncü nüshası kaptana teslim edilir.",
   "Birinci nüshası gümrük idaresince alıkonulur, ikinci nüshası kaptana teslim edilir, üçüncü nüshası varış gümrük idaresine gönderilir.",
   "Birinci nüshası kaptana teslim edilir, ikinci ve üçüncü nüshası gümrük idaresince alıkonulur.",
   "Birinci nüshası gümrük idaresince alıkonulur, ikinci ve üçüncü nüshası yükleme yerindeki liman başkanlığına teslim edilir."],
sirali=False,
g="Tebliğ'e göre yükleme tamamlandıktan sonra beyannamenin birinci nüshası gümrük idaresince alıkonulur, ikinci ve üçüncü nüshası kaptana teslim edilir. Kaptana verilen bu iki nüsha, yolda ilave yük alınırken ya da boşaltma limanında gümrük idaresine ibraz edilen nüshalardır. Ayrıca beyannamenin bir örneği en seri şekilde varış gümrük idaresine gönderilir; ancak bu örnek, kaptana verilen nüshalardan biri değildir. En güçlü çeldirici üçüncü nüshanın varış gümrük idaresine gönderildiğini söyleyen seçenektir: varış idaresine 'bir örnek' gönderilmesi hükmünü nüsha dağılımına karıştırır. Bu nedenle doğru cevap 'Birinci nüshası gümrük idaresince alıkonulur, ikinci ve üçüncü nüshası kaptana teslim edilir.' seçeneğidir. (MD 5, 6, 7)",
kanit=K + " | Beyannamenin birinci nüshası gümrük idaresince alıkonulur, ikinci ve üçüncü nüshası kaptana teslim edilir. || " + K + " | Beyannamenin bir örneği en seri şekilde varış gümrük idaresine gönderilir.",
yuva=["Aynı fıkra: ikinci nüsha kaptana verilir; dağılım değiştirilmiş",
      "Aynı maddenin sonraki fıkrası: varış gümrük idaresine 'bir örnek' gönderilmesi",
      "Aynı fıkranın tersine çevrilmiş hâli",
      "Gümrük idaresi bulunmayan yerler: liman başkanlıklarının yetki ve sorumluluğu"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "SAYI"],
duzey=["HATIRLAMA"],
profil=[1, 2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="nusha-dagilimi",
guncellik="",
cikmis="",
kapsamli=False,
),

# 7 — Mesai saatleri dışında kalan yükleme (sonuç; parafraz)
dict(
konu="Kabotaj", blok="SB13",
kalip="SONUÇ",
z="O",
madde=M + " md. 5",
cek="Yükleme mesai içinde bitmez ve fazla çalışma ücreti yatırılmazsa durum tutanağa bağlanır, ambarlar mühürlenir, yüklemeye izleyen ilk iş günü devam edilir.",
kok=[T + "'e göre gümrük idaresinin bulunduğu limanda kabotaj eşyasının yüklenmesi mesai saatleri içerisinde bitirilemez ve fazla çalışma ücreti de yatırılmazsa aşağıdakilerden hangisi uygulanır?"],
d="Durum tutanağa bağlanarak gemi ambarları mühürlenir ve yüklemeye izleyen ilk iş gününde devam edilir.",
c=["Yüklenen eşya gemiden boşaltılarak gümrüklü yer ve sahalara alınır ve izleyen ilk iş gününde yeni bir beyanname ile yüklenir.",
   "Yüklemeye, gemiye gümrük muhafaza personeli refakat ettirilmek suretiyle mesai saatleri dışında devam edilir.",
   "Beyanname iptal edilir ve yüklemeye, izleyen ilk iş gününde daha önce yüklenen eşyayı da kapsayan yeni bir beyanname ile devam edilir.",
   "Yükleme durdurulur ve izleyen ilk iş gününde eşyanın kapsamlı tespiti yapılmadan yüklemeye devam edilmez."],
sirali=False,
g="Tebliğ'e göre yüklemenin mesai saatleri içerisinde bitirilememesi hâlinde, Gümrük Kanunu'nun fazla çalışma ücretine ilişkin hükmüne uygun olarak ücret yatırılırsa yüklemeye devam edilebilir. Ücret yatırılmazsa durum tutanakla tespit edilir, gemi ambarları mühür altına alınır ve takip eden ilk iş günü yüklemeye devam edilir. Eşyanın boşaltılması, yeni beyanname düzenlenmesi veya refakat bu hâlin sonucu değildir: önceki yükle birlikte yeni beyanname düzenlenmesi, geminin gümrük idaresi bulunan başka bir limandan ilave yük alması hâline; refakat ise uluslararası sefer yapan Türk bayraklı gemilere kabotaj eşyası alınması hâline aittir. Kapsamlı tespit de ancak gerek görüldüğü durumlarda yapılır. Bu nedenle doğru cevap 'Durum tutanağa bağlanarak gemi ambarları mühürlenir ve yüklemeye izleyen ilk iş gününde devam edilir.' seçeneğidir. (MD 5, 6, 11)",
kanit=K + " | Yüklemenin mesai saatleri içerisinde bitirilememesi halinde, Gümrük Kanununun 221 inci maddesine uygun olarak fazla çalışma ücretinin yatırılması durumunda yüklemeye devam edilebilir. || " + K + " | Aksi halde, durum tutanakla tespit edilerek gemi ambarları mühür altına alınır ve takip eden ilk iş günü yüklemeye devam edilir. || " + K + " | İhtiyaç duyulması halinde, bu gemilere gümrük muhafaza personeli refakat ettirilebilir. || " + K + " | Gerek görüldüğü durumlarda eşyanın kapsamlı tespiti yapılır.",
yuva=["Gümrüklü yer ve sahalarda yükleme-boşaltma hükmü ile ilave yükte yeni beyanname hükmünün birleştirilmesi",
      "Uluslararası seferdeki Türk bayraklı gemilere kabotaj eşyası alınmasında gümrük muhafaza personeli refakati",
      "İlave yük alınmasında mührün iptal edilip önceki yükle birlikte yeni beyanname düzenlenmesi",
      "Yükleme hükmü: gerek görüldüğü durumlarda yapılan kapsamlı tespit (zorunlu hâle getirilmiş)"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "ŞART"],
duzey=["HATIRLAMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 8 — Gümrük idaresi bulunan limandan yükleme (önermeli; II ve III doğru)
dict(
konu="Kabotaj", blok="SB13",
kalip="ÖNERMELİ",
z="Z",
madde=M + " md. 5, 10, 11",
cek="Yüklemede beyanname gümrük muhafaza personelince imzalanıp mühürlenir; eşya kap ve içeriği kontrol edilerek yüklenir; ambar mührü gerek görülürse vurulur.",
kok=[T + "'e göre gümrük idaresinin bulunduğu liman ve iskelelerden yapılacak kabotaj yüklemelerine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Yüklemenin tamamlanmasından sonra gemi ambarları her hâlde mühürlenir.",
     "II. Gümrük idaresine ibraz edilen beyanname, gümrük muhafaza personeli tarafından imzalanarak mühürlenir.",
     "III. Eşya, beyannameye göre kap ve içeriği kontrol edilerek gözetim altında yüklenir.",
     "IV. Yük arasında bulunan ve beyan edilmemiş olan kontrole tabi eşya, yükleme tamamlandıktan sonra verilecek ek bir beyanla beyannameye ilave edilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve III",
c=["I ve II", "III ve IV", "I, II ve III", "II, III ve IV"],
sirali=False,
g="Tebliğ'e göre gümrük idaresine ibraz edilen beyanname gümrük muhafaza personeli tarafından imzalanarak mühürlenir (II doğru) ve eşya beyannameye göre kap ve içeriği kontrol edilerek gözetim altında yüklenir (III doğru). Gemi ambarları yükleme tamamlandıktan sonra her hâlde değil, gerek görülmesi hâlinde mühürlenir; mühürlerin adedi ve vurulduğu yerler beyannamenin her üç nüshasına işlenir (I yanlış). Yük arasında bulunan ve Tebliğ ekinde yer alan eşyadan beyan edilmemiş olanlar ile beyana göre fazla çıkan miktar için ek bir beyanda bulunulmadıkça ya da yeni bir beyanname düzenlenmedikçe yüklemeye izin verilmez; ek beyan yüklemeden sonra değil, yüklemeye izin verilmesinden önce verilir (IV yanlış). En güçlü tuzak I. önermedir: dâhili seferde yabancı limana uğrayan ve uluslararası seferde kabotaj eşyası alan gemilerde ambarlar mühür altına alınır; gümrük idaresi bulunan limandan olağan yüklemede ise mühür gerek görülmesine bağlıdır. Bu nedenle doğru cevap 'II ve III' seçeneğidir. (MD 5, 10, 11)",
kanit=K + " | Yüklemenin tamamlanmasından sonra gerek görülmesi halinde gemi ambarları mühürlenir ve mühürlerin adedi ile vurulduğu yerler beyannamenin her üç nüshasına işlenir. || " + K + " | gümrük muhafaza personeli tarafından imzalanarak mühürlenir || " + K + " | Eşya, beyannameye göre kap ve içeriği kontrol edilerek gözetim altında yüklenir. || " + K + " | ek bir beyanda bulunulmadıkça ya da yeni bir beyanname düzenlenmedikçe yüklemeye izin verilmez || " + K + " | kabotaj eşyasının bulunduğu ambar ve mahaller mühür altına alınarak işlemleri yapılır",
yuva=["I'deki 'her hâlde' kaydı, ambar mührünün kesin olduğu yabancı limana uğrama ve uluslararası sefer hükümlerinden taşınmıştır",
      "IV, ek beyanı yüklemeye izin şartı olmaktan çıkarıp yüklemeden sonraya bırakır (aynı maddenin ek beyan fıkrası)",
      "I'in mutlaklaştırılmış hâlini kabul eden seçim",
      "IV'teki zaman kaydı değişikliğini görmeyen seçim"],
yakinlik="BİREBİR",
tuzak=["MUTLAK", "ŞART", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 9 — Boşaltma sonrası nüsha dağılımı (ayna: soru 6; parafraz)
dict(
konu="Kabotaj", blok="SB13",
kalip="DOĞRU",
z="O",
madde=M + " md. 7, 8",
cek="Boşaltma limanında iki nüsha beyanname esas alınır; işlem bitince bir nüsha boşaltma yerindeki gümrük idaresinde kalır, diğeri hareket gümrük idaresine gönderilir.",
kok=[T + "'e göre gümrük idaresi bulunan bir limanda boşaltma işlemi tamamlanan kabotaj beyannamesine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="İki nüshadan biri boşaltmanın yapıldığı yerdeki gümrük idaresinde kalır, diğeri gecikmeksizin hareket gümrük idaresine gönderilir.",
c=["İki nüshadan biri boşaltmanın yapıldığı yerdeki gümrük idaresinde kalır, diğeri mühür ve imza ile tasdik edilerek kaptana iade edilir.",
   "İki nüshadan biri boşaltmanın yapıldığı yerdeki gümrük idaresinde kalır, diğeri sonucun bildirilmesi için en yakın liman başkanlığına gönderilir.",
   "Her iki nüsha da boşaltmanın yapıldığı yerdeki gümrük idaresinde saklanır; hareket gümrük idaresine yalnızca yazılı bilgi verilir.",
   "İki nüshadan biri hareket gümrük idaresine, diğeri varış yerindeki liman başkanlığına gönderilir."],
sirali=False,
g="Tebliğ'e göre boşaltma limanında eşya, kaptan veya acentesi tarafından gümrük idaresine ibraz edilen iki nüsha beyanname esas alınarak boşaltılır; eşya beyannameye uygunsa her iki nüsha gümrük muhafaza personelince imzalanarak mühürlenir. İşlemi tamamlanan beyannamenin bir nüshası boşaltma yerindeki gümrük idaresinde saklanır, diğer nüsha en seri şekilde hareket gümrük idaresine gönderilir. En güçlü çeldirici nüshanın tasdik edilerek kaptana iade edildiğini söyleyen seçenektir: bu işlem, eşyanın yalnızca bir kısmının varış yolu üzerindeki bir limana boşaltıldığı ve kalan eşyanın yoluna devam ettiği hâle aittir. Liman başkanlıklarına gönderim ise gümrük idaresi bulunmayan yerlerdeki işlemlere ilişkindir. Bu nedenle doğru cevap 'İki nüshadan biri boşaltmanın yapıldığı yerdeki gümrük idaresinde kalır, diğeri gecikmeksizin hareket gümrük idaresine gönderilir.' seçeneğidir. (MD 7, 8, 9)",
kanit=K + " | Boşaltma limanında kaptan veya acentesi tarafından gümrük idaresine ibraz edilen iki nüsha beyanname esas alınarak eşya boşaltılır. || " + K + " | İşlemi tamamlanan beyannamenin bir nüshası boşaltma yerindeki gümrük idaresinde saklanır, diğer nüsha en seri şekilde hareket gümrük idaresine gönderilir. || " + K + " | mühür ve imza ile tasdik edildikten sonra kaptana iade edilir",
yuva=["Boşaltma yerinin değiştirilmesi: kısmi boşaltmada nüshaların tasdik edilip kaptana iadesi",
      "Gümrük idaresi bulunmayan yerler: liman başkanlığının sonucu en yakın gümrük idaresine bildirmesi",
      "Yükleme hükmü: birinci nüshanın gümrük idaresince alıkonulması (boşaltmaya taşınmış)",
      "Gümrük idaresi bulunmayan yerler: beyannamenin varış yerindeki liman başkanlığına gönderilmesi"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "MAKAM"],
duzey=["HATIRLAMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="nusha-dagilimi",
guncellik="",
cikmis="",
kapsamli=False,
),

# 10 — Boşaltma yerinin değiştirilmesi (önermeli; I ve III doğru)
dict(
konu="Kabotaj", blok="SB13",
kalip="ÖNERMELİ",
z="Z",
madde=M + " md. 8",
cek="Tamamından vazgeçilirse yol üzerindeki gümrüklü limana boşaltılabilir; kısmi boşaltma isteği kabul edilir, nüshalar tasdikle kaptana iade edilir; yol dışı boşaltmada boşaltma idaresine bildirilir.",
kok=[T + "'e göre beyannamede kayıtlı kabotaj eşyasının boşaltma yerinin değiştirilmesine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Eşyanın tamamının varılacak liman veya iskeleye boşaltılmasından vazgeçilmesi durumunda eşya, varış limanı yolu üzerinde gümrük idaresi bulunan liman veya iskelelerden herhangi birine boşaltılabilir.",
     "II. Eşyanın bir kısmının varış yolu üzerindeki bir liman veya iskeleye boşaltılması isteği, ilgili gümrük idaresince ancak hareket gümrük idaresinin onayı alınarak kabul edilir.",
     "III. Kısmi boşaltmada boşaltılan eşyanın tespiti yapılır; kaptanda bulunan iki nüsha beyannamenin ilgili kısmı doldurularak mühür ve imza ile tasdik edildikten sonra kaptana iade edilir.",
     "IV. Seyir esnasında eşyanın varış yolu dışında kalan bir limana boşaltılması gerektiğinde, kaptan veya acente tarafından hareket gümrük idaresine en seri şekilde bildirimde bulunulur.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve III",
c=["Yalnız I", "II ve IV", "I, III ve IV", "I, II, III ve IV"],
sirali=False,
g="Tebliğ'e göre beyannamede kayıtlı eşyanın tamamının varılacak yere boşaltılmasından vazgeçilirse eşya, varış limanı yolu üzerinde gümrük idaresi bulunan liman veya iskelelerden herhangi birine boşaltılabilir ve boşaltma işlemleri boşaltma yerindeki idarece yapılır (I doğru). Eşyanın bir kısmının varış yolu üzerindeki bir limana boşaltılması istenirse bu istek ilgili gümrük idaresince kabul edilir; Tebliğ bunun için hareket gümrük idaresinin onayını aramaz (II yanlış). Bu durumda boşaltılan eşyanın tespiti yapılır, kaptandaki iki nüsha beyannamenin ilgili kısmı doldurulup mühür ve imza ile tasdik edilerek kaptana iade edilir ve kalan eşya varış yerine sevk edilir (III doğru). Seyir esnasında eşyanın varış yolu dışındaki bir limana boşaltılması gerektiğinde bildirim, hareket gümrük idaresine değil, boşaltma yapılacak gümrük idaresine en seri şekilde yapılır (IV yanlış). En güçlü tuzak IV. önermedir: Tebliğde hareket gümrük idaresi, boşaltma veya ilave yük işlemi tamamlandıktan sonra beyanname nüshasının gönderildiği idaredir; boşaltma yerinin değişmesinde bildirim muhatabı değildir. Bu nedenle doğru cevap 'I ve III' seçeneğidir. (MD 6, 7, 8)",
kanit=K + " | eşya varış limanı yolu üzerinde gümrük idaresi bulunan liman veya iskelelerden herhangi birine boşaltılabilir || " + K + " | bu istek ilgili gümrük idaresince kabul edilir || " + K + " | kaptanda bulunan iki nüsha beyannamenin ilgili kısmı doldurularak mühür ve imza ile tasdik edildikten sonra kaptana iade edilir || " + K + " | kaptan veya acente tarafından boşaltma yapılacak gümrük idaresine en seri şekilde bildirimde bulunulur",
yuva=["Eksik seçim: kısmi boşaltma hükmü (III) aynen alınmıştır",
      "II'ye eklenen onay şartı ve IV'teki makam değişikliği; hareket gümrük idaresi nüsha gönderimi hükümlerinden taşınmıştır",
      "IV'teki makam değişikliğini görmeyen seçim",
      "En kapsamlı şık: II ve IV'teki tek unsur değişikliklerini görmeyen adayı yakalar"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "ŞART", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 11 — İlave yük alınması (yanlış ifade)
dict(
konu="Kabotaj", blok="SB13",
kalip="YANLIŞ",
z="O",
madde=M + " md. 4, 6",
cek="İlave yükte kaptandaki iki nüsha karşılaştırılır, biri idarede kalır, diğeri ilk hareket idaresine gider; mühür iptal edilir, tüm yük için yeni beyanname düzenlenir.",
kok=[T + "'e göre kabotaj eşyası taşıyan geminin gümrük idaresi bulunan başka bir liman veya iskeleden ilave yük alması gerektiğinde yapılacak işlemlere ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Daha önceki mevcut yük için düzenlenmiş beyanname geçerliliğini korur; yalnızca yeni yük için ayrı bir beyanname düzenlenir.",
c=["O yer gümrük idaresince öncelikle kaptanda mevcut iki nüsha beyanname istenerek beyan ile taşınan eşya karşılaştırılır.",
   "Varsa ambar mühürleri incelenir; şüphe uyandıracak bir durum bulunmazsa mühür koparılıp iptal edilir.",
   "Onaylanıp kapatılan iki nüsha beyannameden biri idarede kalır, diğeri ilk hareket gümrük idaresine en seri şekilde gönderilir.",
   "Eşya yüklendikten sonra ambarlar tekrar mühür altına alınarak gemi gideceği yere sevk edilir."],
sirali=False,
g="Tebliğ'e göre geminin gümrük idaresi bulunan başka bir liman veya iskeleden ilave yük alması gerektiğinde o yer gümrük idaresi öncelikle kaptandaki iki nüsha beyannameyi isteyerek beyan ile taşınan eşyayı karşılaştırır, varsa ambar mühürlerini inceler. Şüphe uyandıracak bir durum yoksa onaylanıp kapatılan iki nüshadan biri idarede kalır, diğeri en seri şekilde ilk hareket gümrük idaresine gönderilir; mühür koparılıp iptal edilir. Ardından daha önceki mevcut yükle birlikte, yeni yük için yeni bir beyanname düzenlenir; eşya yükleme esaslarına göre gemiye yüklenir ve ambarlar tekrar mühürlenerek gemi gideceği yere sevk edilir. Dolayısıyla eski beyanname onaylanıp kapatılır; eski beyannameyi yürürlükte bırakıp yalnızca yeni yük için ayrı beyanname düzenlemek hükme aykırıdır. Yanlış ifade, beyanname alanlarının yetmediği durumlarda birden fazla beyanname kullanılabileceğine ilişkin hükümle karıştırılmaktadır. Bu nedenle doğru cevap 'Daha önceki mevcut yük için düzenlenmiş beyanname geçerliliğini korur; yalnızca yeni yük için ayrı bir beyanname düzenlenir.' seçeneğidir. (MD 4, 5, 6)",
kanit=K + " | o yer gümrük idaresince öncelikle kaptanda mevcut iki nüsha beyanname istenilerek beyan ile taşınan eşya karşılaştırılır, varsa ambar mühürleri incelenir. || " + K + " | onaylanıp kapatılan iki nüsha beyannameden biri idarede kalır, diğer nüsha ise ilk hareket gümrük idaresine en seri şekilde gönderilir || " + K + " | Mühür koparılıp iptal edilir ve daha önceki mevcut yükle birlikte, söz konusu yeni yük için yeni bir beyanname düzenlenerek || " + K + " | ambarlar tekrar mühür altına alınarak gemi gideceği yere sevk edilir",
yuva=["İlave yük hükmü: kaptandaki iki nüshanın istenmesi ve karşılaştırma (doğru ifade)",
      "İlave yük hükmü: ambar mühürlerinin incelenmesi, mührün koparılıp iptali (doğru ifade)",
      "İlave yük hükmü: nüshalardan birinin idarede kalması, diğerinin ilk hareket gümrük idaresine gönderilmesi (doğru ifade)",
      "İlave yük hükmü: ambarların tekrar mühürlenerek geminin sevki (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["UNSUR", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 12 — Gümrük idaresi bulunmayan yerlerde varışın teyidi (makam; parafraz)
dict(
konu="Kabotaj", blok="SB13",
kalip="YETKİ",
z="Z",
madde=M + " md. 9, 14",
cek="Yalnız liman başkanlığı bulunan yere boşaltmada teyit nüshası boşaltmadan sonra düzenleyen idareye gider; varışı belirleyen liman başkanlığı sonucu en yakın gümrük idaresine yazıyla bildirir.",
kok=[T + "'e göre kabotaj eşyasının yalnızca liman başkanlığının bulunduğu bir liman veya iskeleye boşaltılması hâlinde, eşyanın varış yerine ulaştığının belirlenmesine ve sonucun bildirilmesine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Teyit nüshası üzerinden eşyanın varışını belirleyen liman başkanlığı, sonucu en yakın gümrük idaresine yazıyla bildirir.",
c=["Teyit nüshası üzerinden eşyanın varışını belirleyen liman başkanlığı, sonucu Ulaştırma, Denizcilik ve Haberleşme Bakanlığına yazıyla bildirir.",
   "Beyannamenin teyit nüshası, eşya boşaltılmadan önce varış yerindeki liman başkanlığınca beyannameyi düzenleyen idareye gönderilir.",
   "Teyit nüshası üzerinden eşyanın varışını belirleyen liman başkanlığı, sonucu mülki idare amirine yazıyla bildirir.",
   "Beyannamenin teyit nüshası eşyanın boşaltılmasından sonra en yakın gümrük idaresine gönderilir ve varış bu idarece belirlenir."],
sirali=False,
g="Tebliğ'e göre gümrük idaresi bulunmayan liman ve iskelelerden yapılacak yükleme ve boşaltmalarda liman başkanlıkları yetkili ve sorumludur. Eşya yalnızca liman başkanlığının bulunduğu bir yere boşaltılırsa, boşaltmadan sonra beyannamenin teyit nüshası beyannameyi düzenleyen gümrük idaresine ya da liman başkanlığına en seri şekilde gönderilir. Teyit nüshasını alarak eşyanın varış yerine ulaştığını belirleyen liman başkanlıkları sonucu en yakın gümrük idaresine yazılı olarak bildirir. Teyit nüshası boşaltmadan önce değil sonra gönderilir; varışı belirleyen de gümrük idaresi değil liman başkanlığıdır. En güçlü çeldirici, sonucun liman başkanlığının bağlı olduğu Ulaştırma, Denizcilik ve Haberleşme Bakanlığına bildirildiğini söyleyen seçenektir; Tebliğ sonucun gümrük idaresine bildirilmesini öngörür. Mülki idare amirine intikal ise serbest dolaşımdaki eşyanın yabancı bayraklı gemiyle taşınmasına ilişkin ceza hükmüne aittir. Bu nedenle doğru cevap 'Teyit nüshası üzerinden eşyanın varışını belirleyen liman başkanlığı, sonucu en yakın gümrük idaresine yazıyla bildirir.' seçeneğidir. (MD 3, 9, 14)",
kanit=K + " | eşyanın boşaltılmasından sonra beyannamenin teyit nüshası beyannameyi düzenleyen gümrük idaresine ya da liman başkanlığına en seri şekilde gönderilir || " + K + " | Teyit nüshasını alarak eşyanın varış yerine ulaştığını belirleyen liman başkanlıkları, sonucu en yakın gümrük idaresine yazılı olarak bildirirler.",
yuva=["Tanımlar: liman başkanlıklarının bağlı olduğu Ulaştırma, Denizcilik ve Haberleşme Bakanlığı",
      "Aynı hükmün önceki bendi: teyit nüshası boşaltmadan sonra gönderilir (zaman kaydı ters çevrilmiş)",
      "Cezalar: serbest dolaşımdaki eşyanın yabancı bayraklı gemiyle taşınmasında mülki idare amirine intikal",
      "Aynı hüküm: en yakın gümrük idaresi sonucun bildirildiği makamdır; teyit nüshasının gönderildiği ve varışı belirleyen makam değildir"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "BAŞLANGIÇ", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 13 — Vaka: dâhili seferde yabancı limana uğrayacak gemi (bildirim zamanı ve yeri; ayna: soru 14)
dict(
konu="Kabotaj", blok="SB13",
kalip="OLAY",
z="Z",
madde=M + " md. 9, 10",
cek="Dâhili seferde yabancı limana uğrayacak Türk bayraklı gemi için bildirim, limandan hareketten en az iki saat önce en son çıkış yapılacak gümrük idaresine yapılır.",
kok=[T + "'e göre dâhili sefer yaparken yabancı bir limana uğrayacak bir gemiye ilişkin bilgiler aşağıda verilmiştir:",
     "- Türk bayraklı bir gemi, İzmir Limanında yüklediği kabotaj eşyasını Mersin Limanına taşımaktadır.",
     "- Gemi bu dâhili sefer sırasında yabancı bir limana da uğrayacaktır.",
     "- Gemi, Türkiye'den en son çıkış yapacağı Antalya Limanından 12 Mayıs günü saat 18.00'de hareket edecektir.",
     "- İzmir, Antalya ve Mersin limanlarında gümrük idaresi bulunmaktadır.",
     "Buna göre kaptan veya acentenin, geminin yabancı limana uğrayacağına ilişkin bildirimi en geç ne zaman ve nereye yapması gerekir?"],
d="12 Mayıs saat 16.00'ya kadar Antalya Limanındaki gümrük idaresine",
c=["12 Mayıs saat 16.00'ya kadar İzmir Limanındaki gümrük idaresine",
   "12 Mayıs saat 16.00'ya kadar Mersin Limanındaki gümrük idaresine",
   "12 Mayıs saat 18.00'e kadar Antalya Limanındaki gümrük idaresine",
   "12 Mayıs saat 16.00'ya kadar Antalya Liman Başkanlığına"],
sirali=False,
g="Tebliğ'e göre Türk bayraklı gemilerin Türk limanları arasındaki seferleri esnasında yabancı limanlara da uğraması durumunda kaptan veya acenteleri, geminin limandan hareketinden en az iki saat önce en son çıkış yapılacak gümrük idaresine bildirimde bulunur; gümrük idaresi de kabotaj eşyasının bulunduğu ambar ve mahalleri mühür altına alır. Olayda Türkiye'den en son çıkış Antalya Limanından 12 Mayıs saat 18.00'de yapılacağından bildirim en geç saat 16.00'ya kadar Antalya'daki gümrük idaresine yapılmalıdır. Seferin başladığı İzmir'deki idare, Tebliğde ilave yük ve boşaltma işlemlerinde nüsha gönderilen hareket gümrük idaresidir. Gemi yabancı limandan dönerken ayrıca Türkiye Gümrük Bölgesindeki ilk limana varışından en az iki saat önce gümrük idaresine bildirimde bulunulur; ancak bu, sorulan hareket öncesi bildirim değildir. Antalya'da gümrük idaresi bulunduğundan liman başkanlığı yetkili değildir; hareket saatinin kendisini esas alan seçenek ise iki saatlik süre kaydını yok sayar. Bu nedenle doğru cevap '12 Mayıs saat 16.00'ya kadar Antalya Limanındaki gümrük idaresine' seçeneğidir. (MD 7, 9, 10)",
kanit=K + " | geminin limandan hareketinden en az iki saat önce en son çıkış yapılacak gümrük idaresine bildirimde bulunulur || " + K + " | deniz taşıtının Türkiye Gümrük Bölgesindeki ilk limana varışından en az iki saat önce gümrük idaresine bildirimde bulunulur || " + K + " | Gümrük idaresi bulunmayan liman ve iskelelerden yapılacak yükleme ve boşaltmalarda liman başkanlıkları yetkili ve sorumludur.",
yuva=["İlave yük ve boşaltma hükümleri: nüshanın gönderildiği hareket gümrük idaresi (seferin başladığı İzmir)",
      "Yabancı limana uğrayarak gelen gemiler: Türkiye Gümrük Bölgesindeki ilk limana varıştan önce yapılan bildirim",
      "Aynı fıkra: 'en az iki saat önce' kaydı düşürülerek hareket anının kendisi alınmış",
      "Gümrük idaresi bulunmayan yerler: liman başkanlıklarının yetki ve sorumluluğu"],
yakinlik="ÇIKARIM",
tuzak=["BAŞLANGIÇ", "MAKAM", "SAYI"],
duzey=["UYGULAMA"],
profil=[2, 1],
olumsuz=False, vaka=True, baslangic=True,
eksen=0, ayna="iki-saat-bildirim",
guncellik="",
cikmis="",
kapsamli=False,
),

# 14 — Yabancı limana uğrayarak gelen gemilerde bildirimin başlangıç anı (ayna: soru 13)
dict(
konu="Kabotaj", blok="SB13",
kalip="SÜRE",
z="O",
madde=M + " md. 10",
cek="Dâhili seferde yabancı limana uğrayarak gelen gemide bildirim, Türkiye Gümrük Bölgesindeki ilk limana varıştan en az iki saat önce gümrük idaresine yapılır.",
kok=[T + "'e göre Türk limanları arasında sefer yaparken yabancı bir limana uğrayarak gelen gemilerin kaptan veya acentelerinin gümrük idaresine yapacakları bildirimin zamanı aşağıdakilerden hangisidir?"],
d="Deniz taşıtının Türkiye Gümrük Bölgesindeki ilk limana varışından en az iki saat önce",
c=["Deniz taşıtının uğradığı yabancı limandan hareketinden en az iki saat önce",
   "Deniz taşıtının Türkiye Gümrük Bölgesindeki ilk limana varışından itibaren en geç iki saat içinde",
   "Deniz taşıtının beyannamede boşaltma limanı olarak gösterilen limana varışından en az iki saat önce",
   "Deniz taşıtının uğrayacağı yabancı limana varışından en az iki saat önce"],
sirali=False,
g="Tebliğ'e göre Türk limanları arasında sefer yaparken yabancı bir limana uğrayarak gelen gemilerin kaptan veya acenteleri, deniz taşıtının Türkiye Gümrük Bölgesindeki ilk limana varışından en az iki saat önce gümrük idaresine bildirimde bulunur. Bu gemiler Türk limanına geldiklerinde harici sefer yapan gemiler gibi kontrole tabi tutulur. Sürenin miktarı iki saattir; belirleyici olan başlangıç anıdır: süre, yabancı limandan hareketten değil, Türkiye Gümrük Bölgesindeki ilk limana varıştan geriye doğru hesaplanır ve bildirim varıştan önce yapılır. En güçlü çeldirici 'hareketinden en az iki saat önce' ifadesidir; bu başlangıç anı, gemi yabancı limana gitmek üzere Türkiye'den en son çıkış yapacağı limandan ayrılırken yapılan bildirime aittir. Bu nedenle doğru cevap 'Deniz taşıtının Türkiye Gümrük Bölgesindeki ilk limana varışından en az iki saat önce' seçeneğidir. (MD 10)",
kanit=K + " | deniz taşıtının Türkiye Gümrük Bölgesindeki ilk limana varışından en az iki saat önce gümrük idaresine bildirimde bulunulur || " + K + " | harici sefer yapan gemiler gibi kontrole tabi tutulur || " + K + " | geminin limandan hareketinden en az iki saat önce",
yuva=["Aynı maddenin önceki fıkrası: Türkiye'den en son çıkış limanından hareketten en az iki saat önce (başlangıç anı taşınmış)",
      "Aynı fıkra: 'önce' kaydı 'varıştan itibaren' olarak ters çevrilmiş",
      "Boşaltma hükümleri: beyannamede boşaltma limanı olarak gösterilen yer",
      "Aynı maddenin önceki fıkrası: yabancı limana uğrama (başlangıç anı yabancı limana kaydırılmış)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU", "TERSİNE"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="iki-saat-bildirim",
guncellik="",
cikmis="",
kapsamli=False,
),

# 15 — Uluslararası seferde kabotaj eşyası alan gemiler (makam değişikliği; yanlış ifade)
dict(
konu="Kabotaj", blok="SB13",
kalip="YANLIŞ",
z="O",
madde=M + " md. 9, 11, 12",
cek="Uluslararası seferde kabotaj eşyası alınacaksa en az iki saat önce ilgili gümrük idaresine bildirilir; ambarlar ayrı mühürlenir; refakat ihtiyaridir; konteynerde istif planı sunulur.",
kok=[T + "'e göre uluslararası seferleri esnasında bir Türk limanından kabotaj eşyası almak isteyen Türk bayraklı gemilere ilişkin aşağıdaki ifadelerden hangisi yanlıştır?"],
d="Kaptan veya acente, kabotaj eşyası alınacağını en az iki saat önce liman başkanlığına bildirir.",
c=["Gümrük muhafaza personelince kabotaj eşyası ile serbest dolaşıma girmemiş eşyanın birbirinden ayrılması sağlanarak ambarlar ayrı ayrı mühürlenir.",
   "İhtiyaç duyulması hâlinde bu gemilere gümrük muhafaza personeli refakat ettirilebilir.",
   "İçinde kabotaj eşyası bulunan konteynerler taşınmak istenirse, serbest dolaşımdaki eşya ile serbest dolaşımda olmayan eşyanın gemideki yerini gösterir istif planı gümrük idaresine sunulur.",
   "Gümrük idaresinin, geminin ambarları dışına yüklenen eşya için branda veya çadır bezi örtülmesine ilişkin talebi kaptan tarafından yerine getirilmek zorundadır."],
sirali=False,
g="Tebliğ'e göre Türk bayraklı gemilerin uluslararası seferleri esnasında bir Türk limanından kabotaj eşyası almak istemeleri hâlinde kaptan veya acenteleri bu hususu en az iki saat önce liman başkanlığına değil, ilgili gümrük idaresine bildirir. Gümrük muhafaza personelince kabotaj eşyası ile serbest dolaşıma girmemiş eşya birbirinden ayrılarak ambarlar ayrı ayrı mühürlenir; ihtiyaç duyulursa gemiye gümrük muhafaza personeli refakat ettirilebilir. Uluslararası sefer yapan Türk bayraklı gemilerle içinde kabotaj eşyası bulunan konteyner taşınacaksa iki tür eşyanın gemideki yerini gösteren istif planı gümrük idaresine sunulur. Gümrük idaresinin, ambarlar dışına yüklenen eşya ile ambarı bulunmayan gemilere yüklenen eşya için branda veya çadır bezi örtülmesine ilişkin talebini kaptan yerine getirmek zorundadır. Liman başkanlıkları yalnızca gümrük idaresi bulunmayan liman ve iskelelerdeki işlemlerde yetkili ve sorumludur. Bu nedenle doğru cevap 'Kaptan veya acente, kabotaj eşyası alınacağını en az iki saat önce liman başkanlığına bildirir.' seçeneğidir. (MD 9, 11, 12)",
kanit=K + " | bir Türk limanından kabotaj eşyası almak istemeleri halinde kaptan veya acenteleri en az iki saat önce bu hususu ilgili gümrük idaresine bildirir || " + K + " | Gümrük muhafaza personelince kabotaj eşyası ile serbest dolaşıma girmemiş eşyanın birbirinden ayrılması sağlanarak ambarlar ayrı ayrı mühürlenir. || " + K + " | İhtiyaç duyulması halinde, bu gemilere gümrük muhafaza personeli refakat ettirilebilir. || " + K + " | serbest dolaşımdaki eşya ile serbest dolaşımda olmayan eşyanın gemideki yerini gösterir istif planı gümrük idaresine sunulur || " + K + " | branda veya çadır bezi örtülmesine ilişkin talebi, kaptan tarafından yerine getirilmek zorundadır",
yuva=["Uluslararası sefer hükmü: kabotaj eşyası ile serbest dolaşıma girmemiş eşyanın ayrılarak ambarların ayrı ayrı mühürlenmesi (doğru ifade)",
      "Uluslararası sefer hükmü: ihtiyaç hâlinde refakat (doğru ifade)",
      "Konteyner hükmü: uluslararası sefer yapan Türk bayraklı gemilerde istif planı (doğru ifade)",
      "Yükleme hükmü: branda veya çadır bezi talebinin kaptanca yerine getirilmesi (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 16 — Kabotaj konteynerinin nitelikleri (liste dışı unsur)
dict(
konu="Kabotaj", blok="SB13",
kalip="ŞART",
z="O",
madde=M + " md. 5, 10, 11, 12",
cek="Kabotaj konteyneri serbest dolaşımda veya geçici ithal edilmiş, dört yanında 'KABOTAJ' yazılı, 50x25 cm, IMO standartlı, beyaz üzerine siyah etiketli olmalıdır.",
kok=[T + "'e göre kabotaj eşyasının konteynerle taşınmasına izin verilebilmesi için kullanılacak konteynerlerde aranan nitelikler arasında aşağıdakilerden hangisi yer almaz?"],
d="Kapılarının gümrük idaresince mühür altına alınmış olması",
c=["Serbest dolaşımda bulunması veya geçici ithal yoluyla ülkeye girmiş olması",
   "Dört bir tarafından rahatlıkla okunabilecek şekilde üzerinde \"KABOTAJ\" yazılı olması",
   "50x25 cm ebatında ve Uluslararası Denizcilik Örgütü (IMO) etiketleri standartlarına uygun etiketlerle markalanmış olması",
   "Etiketlerinin \"beyaz renk\" üzerine \"siyah yazılı\" olması"],
sirali=False,
g="Tebliğ'e göre kabotaj eşyasının konteynerle taşınmak istenmesi hâlinde bu eşyanın ancak serbest dolaşımda bulunan veya geçici ithal yoluyla ülkeye giren, dört bir tarafından rahatlıkla okunabilecek şekilde üzerinde 'KABOTAJ' yazılı, 50x25 cm ebatında, Uluslararası Denizcilik Örgütü (IMO) etiketleri standartlarına uygun, beyaz renk üzerine siyah yazılı etiketlerle markalanmış konteynerlerle taşınmasına izin verilebilir. Konteynerin gümrük idaresince mühürlenmesi bu nitelikler arasında sayılmamıştır. Tebliğde mühür gemi ambarları için öngörülmüştür: yükleme sonrasında gerek görülürse, yabancı limana uğrayan ve uluslararası sefer yapan gemilerde ise ambarlar mühür altına alınır. Geçici ithalat izniyle gelen konteynerler dâhili taşımacılıkta kullanılırsa konteyner içeriği eşya ayrıca bir çeki listesiyle beyannameye eklenir. Bu nedenle doğru cevap 'Kapılarının gümrük idaresince mühür altına alınmış olması' seçeneğidir. (MD 5, 10, 11, 12)",
kanit=K + " | bu tür eşyanın ancak serbest dolaşımda bulunan veya geçici ithal yoluyla ülkeye giren, dört bir tarafından rahatlıkla okunabilecek şekilde üzerinde \"KABOTAJ\" yazılı, 50x25 cm ebatında, Uluslararası Denizcilik Örgütü (IMO) etiketleri standartlarına uygun, \"beyaz renk\" üzerine \"siyah yazılı\" etiketlerle markalanmış konteynerlerle taşınmasına izin verilebilir || " + K + " | konteyner içeriği eşya bir çeki listesi ile beyannameye eklenir || " + K + " | gerek görülmesi halinde gemi ambarları mühürlenir",
yuva=["Konteyner hükmü: serbest dolaşımda bulunan veya geçici ithal yoluyla giren konteyner (sayılmıştır)",
      "Konteyner hükmü: dört bir tarafından okunabilecek 'KABOTAJ' yazısı (sayılmıştır)",
      "Konteyner hükmü: 50x25 cm, IMO etiket standartlarına uygun etiket (sayılmıştır)",
      "Konteyner hükmü: beyaz renk üzerine siyah yazılı etiket (sayılmıştır)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 17 — İstisnalar (liste dışı unsur)
dict(
konu="Kabotaj", blok="SB13",
kalip="KAPSAM_DIŞI",
z="O",
madde=M + " md. 13",
cek="Tebliğ; kamu kurumlarının eşyasına, gemi adamlarının ihtiyaç malzemesi ve kumanyasına, balıkçı gemilerinin su ürünlerine, tek liman başkanlığı içi taşımaya uygulanmaz; yakıt sayılmamıştır.",
kok=[T + "'e göre Tebliğ hükümlerinin uygulanmayacağı eşya arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="Gemilerin kendi ihtiyaçları için kullanacakları yakıt ve yağlar",
c=["Kamu kurum ve kuruluşlarına ait eşya",
   "Gemi adamlarının ihtiyaç malzemesi ve kumanya",
   "Elde edildikleri yerlerden Türk liman ve iskelelerine boşaltılması amacıyla her tonajdaki balıkçı gemileriyle taşınan, denizden elde edilen su ürünleri",
   "Gümrük Yönetmeliğinin ilgili hükmü kapsamında yabancı bayraklı gemilerce yapılacak taşımalar"],
sirali=False,
g="Tebliğ'e göre bu Tebliğ hükümleri; kamu kurum ve kuruluşlarına ait eşya, gemi adamlarının ihtiyaç malzemesi ve kumanya, elde edildikleri yerlerden Türk liman ve iskelelerine boşaltılması amacıyla her tonajdaki balıkçı gemileriyle taşınan denizden elde edilen su ürünleri, tek bir liman başkanlığı idari sınırları içerisinde taşınan her türlü eşya ve Gümrük Yönetmeliği'nin ilgili hükmü kapsamında yabancı bayraklı gemilerce yapılacak taşımalar için uygulanmaz. Gemilerin kendi ihtiyaçları için kullanacakları yakıt ve yağlar bu istisnalar arasında sayılmamıştır. Listede gemi adamlarının kumanyasının bulunması ve Gümrük Kanunu'nda dış seferlerde kullanılacak yakıt ve yağlar ile kumanyanın birlikte düzenlenmesi, yakıtın da sayıldığı izlenimini verir; ancak Tebliğdeki istisna listesi yakıt ve yağı içermez. Bu nedenle doğru cevap 'Gemilerin kendi ihtiyaçları için kullanacakları yakıt ve yağlar' seçeneğidir. (MD 13; GK 176)",
kanit=K + " | Aşağıdaki eşya için bu Tebliğ hükümleri uygulanmaz || " + K + " | Kamu kurum ve kuruluşlarına ait eşya || " + K + " | Gemi adamlarının ihtiyaç malzemesi ve kumanya || " + K + " | her tonajdaki balıkçı gemileriyle taşınan, denizden elde edilen su ürünleri || " + K + " | kapsamında yabancı bayraklı gemilerce yapılacak taşımalar || " + KU + " | dış seferlerde kullanacakları yakıt ve yağları ile karaya çıkarılmamak şartıyla yurtdışından getirdikleri kumanyaları ithalat vergilerinden muaftır",
yuva=["İstisnalar: kamu kurum ve kuruluşlarına ait eşya (sayılmıştır)",
      "İstisnalar: gemi adamlarının ihtiyaç malzemesi ve kumanya (sayılmıştır)",
      "İstisnalar: her tonajdaki balıkçı gemileriyle taşınan su ürünleri (sayılmıştır)",
      "İstisnalar: Gümrük Yönetmeliği kapsamında yabancı bayraklı gemilerce yapılacak taşımalar (sayılmıştır)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU", "KOMŞU"],
duzey=["TANIMA"],
profil=[3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 18 — Vaka: tek liman başkanlığı sınırları içinde taşıma (saklı istisna)
dict(
konu="Kabotaj", blok="SB13",
kalip="OLAY",
z="Z",
madde=M + " md. 9, 13, 14",
cek="Tek bir liman başkanlığı idari sınırları içinde taşınan her türlü eşyaya, Tebliğ ekindeki eşya olsa bile Tebliğ hükümleri uygulanmaz.",
kok=[T + "'e göre aşağıdaki olaya ilişkin bilgiler verilmiştir:",
     "- Türk bayraklı bir yük gemisi, Tebliğ ekinde yer alan kontrole tabi eşyayı taşımıştır.",
     "- Yükleme ve boşaltma, aynı liman başkanlığının idari sınırları içerisinde bulunan iki iskelede yapılmıştır.",
     "- Taşıma için kabotaj beyannamesi düzenlenmemiştir.",
     "Buna göre bu taşımayla ilgili aşağıdakilerden hangisi doğrudur?"],
d="Bu taşımaya, kabotaj beyannamesi dâhil Tebliğ hükümleri uygulanmaz.",
c=["Beyanname düzenlenmediğinden 4458 sayılı Gümrük Kanunu'nun usulsüzlük cezasına ilişkin hükmü uyarınca işlem yapılır.",
   "Beyannamenin yükleme yerindeki liman başkanlığınca düzenlenerek varış yerindeki liman başkanlığına gönderilmesi gerekirdi.",
   "Konu, 815 sayılı Kanun uyarınca işlem yapılmak üzere mülki idare amirine intikal ettirilir.",
   "5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca işlem yapılır."],
sirali=False,
g="Tebliğ'e göre tek bir liman başkanlığı idari sınırları içerisinde taşınan her türlü eşya için Tebliğ hükümleri uygulanmaz. Olaydaki eşya Tebliğ ekinde yer alan kontrole tabi eşya olsa da yükleme ve boşaltma aynı liman başkanlığının idari sınırları içinde yapıldığından taşıma Tebliğ kapsamı dışındadır; kabotaj beyannamesi düzenlenmesi gerekmez ve beyanname düzenlenmemesine ilişkin ceza hükmü işletilmez. En güçlü çeldirici usulsüzlük cezası seçeneğidir: Tebliğ, kabotaj eşyası için beyanname düzenlenmemesini Gümrük Kanunu'nun usulsüzlük cezasına ilişkin hükmü uyarınca işlem yapılacak hâller arasında sayar; ancak bu hüküm Tebliğin uygulandığı taşımalar içindir. Beyannamenin liman başkanlığınca düzenlenmesi gümrük idaresi bulunmayan yerlerdeki kabotaj taşımalarına, 815 sayılı Kanun serbest dolaşımdaki eşyanın yabancı bayraklı gemiyle taşınmasına, 5607 sayılı Kanun ise serbest dolaşımda olmayan eşyanın kaçak olarak sokulmasına ilişkindir. Bu nedenle doğru cevap 'Bu taşımaya, kabotaj beyannamesi dâhil Tebliğ hükümleri uygulanmaz.' seçeneğidir. (MD 9, 13, 14; GK 241)",
kanit=K + " | Aşağıdaki eşya için bu Tebliğ hükümleri uygulanmaz || " + K + " | Tek bir liman başkanlığı idari sınırları içerisinde taşınan her türlü eşya || " + K + " | Kabotaj eşyası ile ilgili beyanname düzenlenmemesi, beyannamenin kaybedilmesi, beyannamede silinti veya kazıntı yapılması || " + K + " | Aşağıdaki hallerde, Gümrük Kanununun 241 inci maddesi uyarınca işlem yapılır || " + CZ + " | Bu Kanunda ayrı bir ceza tayin edilmiş haller saklı kalmak üzere",
yuva=["Cezalar: beyanname düzenlenmemesinde Gümrük Kanunu'nun usulsüzlük cezası hükmü (Tebliğ kapsamındaki taşımalar için)",
      "Gümrük idaresi bulunmayan yerler: beyannamenin yükleme yerindeki liman başkanlığınca düzenlenip gönderilmesi",
      "Cezalar: serbest dolaşımdaki eşyanın yabancı bayraklı gemiyle taşınması (815 sayılı Kanun, mülki idare amiri)",
      "Cezalar: serbest dolaşımda olmayan eşyanın kaçak olarak sokulması (5607 sayılı Kanun)"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "KOMŞU", "SAĞDUYU"],
duzey=["UYGULAMA"],
profil=[3, 1],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 19 — Ceza hükümleri: durum – uygulanacak kanun eşleştirmesi
dict(
konu="Kabotaj", blok="SB13",
kalip="EŞLEŞTİRME",
z="O",
madde=M + " md. 14; 4458 sayılı Gümrük Kanunu md. 241",
cek="Beyanname, bildirim ve yol kesme ihlallerinde Gümrük Kanunu; kaçak sokmada 5607; serbest dolaşımdaki eşyayı yabancı bayraklı gemiyle taşımada 815 sayılı Kanun uygulanır.",
kok=[T + "'e göre aşağıdaki durum ile yapılacak işlem eşleştirmelerinden hangisi yanlıştır?"],
d="Serbest dolaşımdaki eşyanın yabancı bayraklı gemilerle taşındığının tespit edilmesi – 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca işlem yapılması",
c=["Beyannamede silinti veya kazıntı yapılması – 4458 sayılı Gümrük Kanunu uyarınca işlem yapılması",
   "Bildirim yükümlülüklerine uyulmaması – 4458 sayılı Gümrük Kanunu uyarınca işlem yapılması",
   "Serbest dolaşımda olmayan eşyanın yurda kaçak olarak sokulmaya teşebbüs edildiğinin saptanması – 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca işlem yapılması",
   "Geminin seyir hâlinde iken kontrol amacıyla yol kesmesi istenildiği hâlde yol kesmemesi – 4458 sayılı Gümrük Kanunu uyarınca işlem yapılması"],
sirali=False,
g="Tebliğ'e göre kabotaj eşyasının yüklenmesi, taşınması ve boşaltılması sırasında beyannamede kayıtlı olmayan veya beyana aykırı eşya tespit edilmesi, Gümrük Kanunu'nda belirtilen miktar ve oranları aşan eksiklik veya fazlalık çıkması, seyir hâlindeki geminin kontrol için istenmesine rağmen yol kesmemesi, bildirim yükümlülüklerine uyulmaması ile beyannamenin düzenlenmemesi, kaybedilmesi veya beyannamede silinti ya da kazıntı yapılması hâllerinde Gümrük Kanunu'nun usulsüzlük cezasına ilişkin hükmü uyarınca işlem yapılır. Eşyanın serbest dolaşımda olmayan eşya olduğu ve yurda kaçak olarak sokulduğu ya da sokulmaya teşebbüs edildiği saptanırsa 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca işlem yapılır. Serbest dolaşımdaki eşyanın yabancı bayraklı gemilerle taşındığı tespit edilirse ilgililer hakkında 815 sayılı Türkiye Sahillerinde Nakliyatı Bahriye ve Limanlarla Karasuları Dâhilinde İcrayı Sanat ve Ticaret Hakkında Kanun uyarınca işlem yapılmak üzere konu mülki idare amirine intikal ettirilir. Yanlış eşleştirmede eşyanın statüsü gözden kaçırılmıştır: kaçakçılık hükmü serbest dolaşımda olmayan eşyaya, 815 sayılı Kanun ise serbest dolaşımdaki eşyanın yabancı bayraklı gemiyle taşınmasına uygulanır. Bu nedenle doğru cevap 'Serbest dolaşımdaki eşyanın yabancı bayraklı gemilerle taşındığının tespit edilmesi – 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca işlem yapılması' seçeneğidir. (MD 14; GK 241)",
kanit=K + " | Aşağıdaki hallerde, Gümrük Kanununun 241 inci maddesi uyarınca işlem yapılır || " + K + " | Geminin seyir halinde iken kontrol amacıyla yol kesmesi istenildiği halde yol kesmemesi || " + K + " | Bildirim yükümlülüklerine uyulmaması || " + K + " | beyannamede silinti veya kazıntı yapılması || " + K + " | sokulmaya teşebbüs edildiğinin saptanması halinde 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca işlem yapılır || " + K + " | Serbest dolaşımdaki eşyanın yabancı bayraklı gemilerle taşındığının tespit edilmesi halinde, ilgililer hakkında 815 sayılı || " + K + " | uyarınca işlem yapılmak üzere konu mülki idare amirine intikal ettirilir",
yuva=["Cezalar: beyannamede silinti veya kazıntı — Gümrük Kanunu (doğru eşleştirme)",
      "Cezalar: bildirim yükümlülüklerine uyulmaması — Gümrük Kanunu (doğru eşleştirme)",
      "Cezalar: serbest dolaşımda olmayan eşyanın kaçak sokulmaya teşebbüsü — 5607 sayılı Kanun (doğru eşleştirme)",
      "Cezalar: seyir hâlinde yol kesmeme — Gümrük Kanunu (doğru eşleştirme)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 20 — Hesap: kabotaja girecek geminin yabancı limandan aldığı yakıt (çıkmış alan 2021/70)
dict(
konu="Kabotaj", blok="SB13",
kalip="HESAP",
z="O",
madde="Gümrük Yönetmeliği md. 481",
cek="Kabotaja girecek geminin yabancı limandan aldığı yakıtta vergiye esas miktar: seyir jurnaline göre alınan ile jurnal ve devriçark defterine göre sarf edilen arasındaki fark.",
kok=["Gümrük Yönetmeliği'nin kabotaja girecek gemilerin yabancı limanlardan aldıkları yakıtların miktarının tespitine ilişkin hükmüne göre aşağıdaki olayda vergiye esas tutulacak yakıt miktarı belirlenecektir:",
     "- Kabotaja girecek bir gemi, yabancı bir limandan yakıt almıştır.",
     "- Yabancı limanda düzenlenen yakıt satış faturasına göre alınan yakıt 420 tondur.",
     "- Seyir jurnaline göre alınan yakıt 400 tondur.",
     "- Kaptanın yazılı beyanına göre sefer sırasında sarf edilen yakıt 180 tondur.",
     "- Seyir jurnali ve devriçark defterine göre sefer sırasında sarf edilen yakıt 150 tondur.",
     "Buna göre vergiye esas tutulacak yakıt miktarı kaç tondur?"],
d="250 ton",
c=["220 ton", "240 ton", "270 ton", "400 ton"],
sirali=True,
siklar=["220 ton", "240 ton", "250 ton", "270 ton", "400 ton"],
g="Gümrük Yönetmeliği'ne göre kabotaja girecek gemilerin yabancı limanlardan aldıkları yakıtların miktarı gemilerin seyir jurnallerinde ve devriçark defterinde gösterildiğinden, seyir jurnaline göre alınan miktar ile seyir jurnali ve devriçark defterine göre sarf edilen miktar arasındaki fark bulunarak vergiye esas tutulacak miktar tespit olunur. Olayda alınan miktar seyir jurnaline göre 400 ton, sarf edilen miktar seyir jurnali ve devriçark defterine göre 150 tondur; vergiye esas miktar 400 − 150 = 250 tondur. Fatura (420 ton) ve kaptanın beyanı (180 ton) hükmün esas aldığı kayıtlar değildir: 270 ton fatura miktarını, 220 ton kaptan beyanını, 240 ton ikisini birlikte kullanan hesaptır; 400 ton ise sarf edilen yakıtın düşülmediği hesaptır. Bu nedenle doğru cevap '250 ton' seçeneğidir. (MD GY 481)",
kanit=KU + " | Kabotaja girecek gemilerin yabancı limanlardan aldıkları yakıtların miktarı gemilerin seyir jurnallerinde ve devriçark defterinde gösterildiğinden seyir jurnaline göre alınan miktar ile, seyir jurnali ve devriçark defterine göre sarf edilen miktar arasındaki fark bulunarak vergiye esas tutulacak miktar tespit olunur.",
yuva=["220 ton: sarf edilen miktarı kaptanın beyanından alan hesap (hükmün esas aldığı kayıt seyir jurnali ve devriçark defteridir)",
      "240 ton: alınan miktarı faturadan, sarf edilen miktarı kaptan beyanından alan hesap",
      "270 ton: alınan miktarı yakıt satış faturasından alan hesap (alınan miktar seyir jurnaline göre tespit edilir; fatura numara ve tarihi yakıt ve kumanya defterine yazılan bilgidir)",
      "400 ton: seyir jurnaline göre alınan miktarın tamamı; sarf edilen miktar düşülmemiş"],
yakinlik="ÇIKARIM",
tuzak=["AD-HESAP", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[1, 2],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/70",
kapsamli=False,
),
]
