# Soru bankası — Bölüm 23: Transit Tebliği (Seri No: 5) — havayolu basitleştirmesi (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
# Not: Seri No: 6 (SB24) ve Seri No: 8 (SB25) ile ortak hükümler (askı-iptal süreleri, 60 gün eksik belge,
# 15 gün bildirim, GGM izin makamı, hareket idaresi tanımı, kalkışa kadar iletim, varışta sonlandırma,
# rejim hak sahibi, sonradan kontrol) tekrar sorulmadı; set havayoluna özgü hükümlere dayanır.
Q = [

# 1 ---------------- TANIM (addan tanım): izin sahibi ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="TANIM",
z="K",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 3",
cek="Seri No: 5'te izin sahibi, eşyanın havayolu ile basitleştirilmiş usulde taşınmasına ilişkin izin verilen havayolu şirketidir.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'te yer alan “izin sahibi” ifadesinin tanımı aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Eşyanın havayolu ile basitleştirilmiş usulde taşınmasına ilişkin izin verilen havayolu şirketi",
c=["Eşyanın havayolu ile basitleştirilmiş usulde taşınmasına ilişkin verilen izin",
   "Transit rejimine konu eşyayı hareket idaresine sunmaksızın transit işlemleri gerçekleştirmesine izin verilen kişi",
   "Basitleştirme izni kapsamında taşınan eşyanın alıcısı olarak hava konşimentosunda gösterilen kişi",
   "Basitleştirme izni kapsamında taşınan eşyanın konulduğu geçici depolama yerinin işleticisi"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) izin sahibini, eşyanın havayolu ile basitleştirilmiş usulde taşınmasına ilişkin izin verilen havayolu şirketi olarak tanımlar. Aynı tanımlar maddesinde “izin” ise eşyanın havayolu ile basitleştirilmiş usulde taşınmasına ilişkin verilen izindir; biri izni, öteki izin verilen şirketi gösterir. Eşyayı hareket idaresine sunmaksızın transit işlemi yapabilen kişi, Gümrük Yönetmeliği'ndeki izinli gönderici yetkisinin sahibidir. Alıcı, izin sahibinin talep üzerine ibraz edeceği listede her konşimento için yer verilen bir bilgidir; geçici depolama yeri ise süresinde bilgi iletilmeyen eşyanın alındığı yerdir. Demiryolu basitleştirmesinde izin sahibi demiryolu tren işletmecisi olarak tanımlandığından, havayolunda tanımın “havayolu şirketi” ile kurulması bu Tebliğe özgüdür. En güçlü çeldirici “izin” tanımıdır; iki tanım art arda gelir ve yalnızca biri kişiyi tanımlar. Bu nedenle doğru cevap 'Eşyanın havayolu ile basitleştirilmiş usulde taşınmasına ilişkin izin verilen havayolu şirketi' seçeneğidir. (MD 3)",
kanit="24-SERİ NO 5.txt | İzin sahibi: Eşyanın havayolu ile basitleştirilmiş usulde taşınmasına ilişkin izin verilen havayolu şirketini || 24-SERİ NO 5.txt | İzin: Eşyanın havayolu ile basitleştirilmiş usulde taşınmasına ilişkin verilen izni || 20-TRANSİT REJİMİ.txt | Transit rejimine konu eşyayı hareket idaresine sunmaksızın transit işlemleri gerçekleştirmek isteyen kişilere izinli gönderici yetkisi verilebilir || 25-SERİ NO 6.txt | izin verilen demiryolu tren işletmecisini",
yuva=["Aynı tanımlar maddesi: “izin” tanımı",
      "Gümrük Yönetmeliği: izinli gönderici yetkisi",
      "Talep üzerine ibraz edilecek liste: her konşimento için alıcı bilgisi",
      "Hareket idaresi işlemleri: süre aşılırsa eşya geçici depolama yerine alınır"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 2 ---------------- DAYANAK ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="DAYANAK",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 2",
cek="Seri No: 5, Gümrük Kanunu transit hükümleri ile Gümrük Yönetmeliği'nin havayolu basitleştirmesi hükmüne dayanır; Ortak Transit Sözleşmesine dayanmaz.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) hangi düzenlemelere dayanılarak hazırlanmıştır?"],
d="4458 sayılı Gümrük Kanunu ile Gümrük Yönetmeliği",
c=["Ortak Transit Rejimine İlişkin Sözleşme, 4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği",
   "Ortak Transit Rejimine İlişkin Sözleşme ile Gümrük Yönetmeliği",
   "4458 sayılı Gümrük Kanunu, 640 sayılı Kanun Hükmünde Kararname ve Bakanlar Kurulu Kararı",
   "Gümrük Yönetmeliği ile Sonradan Kontrol ve Riskli İşlemlerin Kontrolü Yönetmeliği"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5), 4458 sayılı Gümrük Kanunu'nun transit rejimine ilişkin hükümleri ile Gümrük Yönetmeliği'nin havayolu ile taşımalara ilişkin basitleştirilmiş usulü düzenleyen hükmüne dayanılarak hazırlanmıştır. Demiryolu basitleştirmesini düzenleyen Seri No: 6 bunlara ek olarak Ortak Transit Rejimine İlişkin Sözleşmeye, izinli gönderici yetkisini düzenleyen Seri No: 14 ise Sözleşme ile Gümrük Yönetmeliğine dayanır; Seri No: 5'in dayanak maddesinde ise Sözleşme sayılmamıştır. Kanun Hükmünde Kararname ve Bakanlar Kurulu Kararı, petrol ürünlerinin transitini düzenleyen Seri No: 3'ün dayanağıdır. Sonradan Kontrol ve Riskli İşlemlerin Kontrolü Yönetmeliği ise bu Tebliğde dayanak olarak değil, izin sahibinin işlemlerinin sonradan kontrolüne esas düzenleme olarak anılır. En güçlü çeldirici Sözleşmeyi de sayan seçenektir. Bu nedenle doğru cevap '4458 sayılı Gümrük Kanunu ile Gümrük Yönetmeliği' seçeneğidir. (MD 2)",
kanit="24-SERİ NO 5.txt | 4458 sayılı Gümrük Kanununun 84 ilâ 92 nci maddeleri ve 7/10/2009 tarihli ve 27369 mükerrer sayılı Resmî Gazete'de yayımlanan Gümrük Yönetmeliğinin 237 nci maddesine dayanılarak hazırlanmıştır || 25-SERİ NO 6.txt | 6333 sayılı Kanunla onaylanması uygun bulunan 20/5/1987 tarihli Ortak Transit Rejimine İlişkin Sözleşme || 22-SERİ NO 3.txt | 640 sayılı Gümrük ve Ticaret Bakanlığının Teşkilat ve Görevleri Hakkında Kanun Hükmünde Kararnamenin 2 nci maddesi ile 2011/2033 sayılı Bakanlar Kurulu || 24-SERİ NO 5.txt | Sonradan Kontrol ve Riskli İşlemlerin Kontrolü Yönetmeliği kapsamında sonradan kontrole tabi tutulur",
yuva=["Seri No: 6 (demiryolu basitleştirmesi) dayanak maddesi: Sözleşme, Kanun ve Yönetmelik",
      "Seri No: 14 (izinli gönderici) dayanak maddesi: Sözleşme ve Gümrük Yönetmeliği",
      "Seri No: 3 (petrol ürünleri transiti) dayanak maddesi: Kanun, KHK ve BKK",
      "Aynı Tebliğ sonradan kontrol maddesi: Sonradan Kontrol ve Riskli İşlemlerin Kontrolü Yönetmeliği"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 3 ---------------- SÜRE (dönem): yurtiçi tarifeli sefer koşulu ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="SÜRE",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 4",
cek="Başvuran havayolu şirketi, başvuru yılı ve bir önceki yıl içinde yurtiçi tarifeli seferlerle yolcu ya da kargo taşımış olmalıdır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre havayolu basitleştirmesi izni için başvuran havayolu şirketinin, özel koşullar kapsamında yurtiçi tarifeli seferlerle yolcu ya da kargo taşımacılığı yapmış olması gereken dönem aşağıdakilerden hangisidir?"],
d="Başvuru yılı ve bir önceki yıl",
c=["Başvurunun kayda alındığı ayın ilk gününden geriye dönük son bir yıl",
   "Yalnızca başvuru yılı",
   "Başvuru yılından önceki iki takvim yılı",
   "Başvuru tarihinden itibaren bir yıl"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre başvuru sahibi havayolu şirketi; başvuru tarihi itibarıyla iki taşımacılık ruhsatından birine sahip olmalı, bünyesinde asgari 3 kargo uçağı ya da asgari 10 yolcu uçağı bulundurmalı ve başvuru yılı ile bir önceki yıl içinde yurtiçi tarifeli seferlerle yolcu ya da kargo taşımacılığı yapmış olmalıdır. Dönem, içinde bulunulan başvuru yılını da kapsar; başvuru yılından önceki iki takvim yılı esas alınmaz. Yalnızca başvuru yılını esas alan seçenek, aranan iki yıldan birini düşürür. Başvurunun kayda alındığı ayın ilk gününden geriye dönük son bir yıl, Gümrük Yönetmeliği'ndeki basitleştirme izni genel koşullarının hesaplandığı dönemdir. Başvuru tarihinden itibaren bir yıl ise ISO sertifikaları için başvuru yapıldığını tevsik eden şirketin sertifika örneklerini Bakanlığa ibraz süresidir. En güçlü çeldirici, Yönetmelikteki genel koşulların geriye dönük bir yıllık dönemidir. Bu nedenle doğru cevap 'Başvuru yılı ve bir önceki yıl' seçeneğidir. (MD 4; GY 230)",
kanit="24-SERİ NO 5.txt | başvuru yılı ve bir önceki yıl içerisinde yurtiçi tarifeli seferlerle yolcu ya da kargo taşımacılığı yapmış olmak || 20-TRANSİT REJİMİ.txt | Başvurunun kayda alındığı ayın ilk gününden geriye dönük son bir yıl içinde || 24-SERİ NO 5.txt | sertifikaların birer örneğini başvuru tarihinden itibaren bir yıl içerisinde Bakanlığa ibraz etmek",
yuva=["Gümrük Yönetmeliği genel koşullar: kayda alındığı ayın ilk gününden geriye dönük son bir yıl",
      "Aynı bent: başvuru yılına ek olarak bir önceki yıl da aranır (unsur düşürülmüş)",
      "Aynı bent: dönem başvuru yılını da kapsar (başvuru yılı ve bir önceki yıl)",
      "Aynı fıkra: ISO sertifika örneklerinin başvuru tarihinden itibaren bir yıl içinde ibrazı"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "UNSUR", "KOMŞU"],
duzey=["AYIRT"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 4 ---------------- VAKA: başvurudaki özel koşullar ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="ŞART",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 4",
cek="Özel koşul: iki ruhsattan biri, asgari 3 kargo ya da 10 yolcu uçağı; ISO sertifikası yoksa başvuru tevsiki ve bir yılda Bakanlığa ibraz.",
kok=["Bir havayolu şirketi, Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) kapsamında havayolu basitleştirmesi izni almak için 2026 yılında başvuruda bulunmuştur. Başvuru tarihi itibarıyla şirkete ilişkin bilgiler şöyledir:",
     "- İç ve Dış Hatlarda Tarifeli ve Tarifesiz Seferlerle Kargo Taşımacılığı Ruhsatına sahiptir.",
     "- Bünyesinde 2 adet kargo uçağı ve 12 adet yolcu uçağı bulunmaktadır.",
     "- 2025 ve 2026 yıllarında yurtiçi tarifeli seferlerle yolcu taşımacılığı yapmıştır.",
     "- Manifesto ve konşimento kayıtlarını elektronik ortamda tutmakta olup hareket ve varış gümrük idarelerinin bu bilgilere anlık erişimi için gerekli altyapıya sahiptir.",
     "- ISO 9001 sertifikasına sahiptir; ISO 27001 sertifikasının alınması için ise başvuru yapmış ve bunu belgelemiştir.",
     "Buna göre Tebliğde düzenlenen özel koşullar bakımından aşağıdakilerden hangisi doğrudur?"],
d="Özel koşullar sağlanmaktadır; ISO 27001 sertifikasının bir örneği başvuru tarihinden itibaren bir yıl içerisinde Bakanlığa ibraz edilmelidir.",
c=["Bünyesindeki kargo uçağı sayısı asgari sınırın altında kaldığından özel koşullar sağlanmamaktadır.",
   "ISO 27001 sertifikası başvuru tarihi itibarıyla alınmamış olduğundan özel koşullar sağlanmamaktadır.",
   "Özel koşullar sağlanmaktadır; ISO 27001 sertifikasının bir örneği başvuru tarihinden itibaren bir ay içerisinde Bakanlığa ibraz edilmelidir.",
   "Kargo taşımacılığı ruhsatı tek başına yeterli olmadığından şirketin yolcu ve yük taşımacılığı ruhsatına da sahip olması gerekir."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre havayolu basitleştirmesi izni isteyen şirket, Yönetmelikteki koşullara ilave olarak üç özel koşulu sağlar. Birincisi; yolcu ve yük taşımacılığı ya da kargo taşımacılığı ruhsatlarından birine sahip olmak, bünyesinde asgari 3 kargo uçağı ya da asgari 10 yolcu uçağı bulundurmak ve başvuru yılı ile bir önceki yıl içinde yurtiçi tarifeli seferlerle yolcu ya da kargo taşımacılığı yapmış olmaktır. İkincisi, manifesto ve konşimento kayıtlarını elektronik ortamda tutmak ve hareket ve varış idarelerinin anlık erişimine uygun altyapıya sahip olmaktır. Üçüncüsü, ISO 9001 ve ISO 27001 sertifikalarına sahip olmak ya da sertifikalar için başvuru yapıldığını tevsik edip sertifikaların birer örneğini başvuru tarihinden itibaren bir yıl içinde Bakanlığa ibraz etmektir. Olaydaki şirketin kargo uçağı sayısı 3'ün altındadır; ancak uçak koşulu seçimlidir ve 12 yolcu uçağı asgari 10 sınırını karşılar. Kargo taşımacılığı ruhsatı, iki ruhsattan biri olarak tek başına yeterlidir. ISO 27001 için başvuru yapıldığı belgelendiğinden koşul sağlanır; sertifika örneği ise bir yıl içinde Bakanlığa sunulmalıdır. En güçlü çeldirici kargo uçağı sayısına dayanan seçenektir; vakada saklanan istisna, uçak koşulundaki 'ya da' bağlacıdır. Bir aylık süre, başvuruya eklenecek adli sicil kayıtlarının alınma süresidir. Bu nedenle doğru cevap 'Özel koşullar sağlanmaktadır; ISO 27001 sertifikasının bir örneği başvuru tarihinden itibaren bir yıl içerisinde Bakanlığa ibraz edilmelidir.' seçeneğidir. (MD 4)",
kanit="24-SERİ NO 5.txt | Ruhsatlarından birine sahip olmak, bünyesinde asgari 3 adet kargo uçağı ya da asgari 10 adet yolcu uçağı bulundurmak ve başvuru yılı ve bir önceki yıl içerisinde yurtiçi tarifeli seferlerle yolcu ya da kargo taşımacılığı yapmış olmak || 24-SERİ NO 5.txt | ISO 9001 ve ISO 27001 sertifikalarına sahip olmak ya da söz konusu sertifikaların alınması için başvuru yapıldığının tevsik edilerek sertifikaların birer örneğini başvuru tarihinden itibaren bir yıl içerisinde Bakanlığa ibraz etmek || 24-SERİ NO 5.txt | son bir ay içerisinde alınmış adli sicil kayıtlarını",
yuva=["Aynı bent: asgari 3 kargo uçağı ya da asgari 10 yolcu uçağı; koşul seçimlidir",
      "Aynı fıkra: sertifikaya sahip olmak ya da başvurunun tevsiki seçimlidir",
      "Başvuru belgeleri: son bir ay içerisinde alınmış adli sicil kayıtları (bir ay)",
      "Aynı bent: iki ruhsattan birine sahip olmak yeterlidir"],
yakinlik="ÇIKARIM",
tuzak=["ŞART", "İSTİSNA", "YAKIN-SAYI"],
duzey=["UYGULAMA"],
profil=[2, 1],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 5 ---------------- KAPSAM DIŞI: başvuru belgeleri ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="KAPSAM_DIŞI",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 4",
cek="Uçak sayısı ve seferler Sivil Havacılık Genel Müdürlüğü yazısıyla kanıtlanır; hava taşıtlarının tescil belgeleri ek belgeler arasında sayılmamıştır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre havayolu basitleştirmesi izni için başvuran havayolu şirketinin, Gümrük Yönetmeliği uyarınca ibraz edilecek belgelere ek olarak izin makamına sunması gereken belgeler arasında aşağıdakilerden hangisi yer almaz?"],
d="Taşımalarda kullanılacak her bir hava taşıtının tescil belgesinin noter onaylı sureti",
c=["Şirket bünyesindeki uçak sayısını ve yurtiçi tarifeli seferlerle taşımacılık yapıldığını kanıtlayan, Ulaştırma, Denizcilik ve Haberleşme Bakanlığından (Sivil Havacılık Genel Müdürlüğü) alınmış yazı",
   "Ek-1'de yer alan örneğe uygun olarak doldurulmuş havayolu basitleştirmesi için başvuru formu",
   "Şirketi temsile yetkili kişilerce imzalanmış, Ek-2'de yer alan beyan formu",
   "Basitleştirme izni kapsamında taşıma yapılacak havalimanlarının listesi"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre başvuru sahibi, Yönetmelik uyarınca ibraz edilecek belgelere ek olarak izin makamına şunları sunar: Ek-1'deki başvuru formu, ticaret sicil bilgilerini içeren liste, yönetim kurulu üyeleri ile ortakların ve temsil yetkili çalışanların adli sicil kayıtları, Ek-2'deki beyan formu, taşımacılık ruhsatının noter onaylı sureti, uçak sayısını ve yurtiçi tarifeli seferleri kanıtlayan Sivil Havacılık Genel Müdürlüğü yazısı, ISO sertifikaları ve taşıma yapılacak havalimanlarının listesi. Bünyedeki uçak sayısı tek tek hava taşıtlarının tescil belgeleriyle değil, Sivil Havacılık Genel Müdürlüğünden alınan yazıyla kanıtlanır; listede noter onaylı suret yalnızca ruhsat için istenir. En güçlü çeldirici Sivil Havacılık Genel Müdürlüğü yazısıdır: tescil belgesi seçeneği bu yazının yerine geçecek gibi görünen, sağduyuya dayalı bir unsurdur. Bu nedenle doğru cevap 'Taşımalarda kullanılacak her bir hava taşıtının tescil belgesinin noter onaylı sureti' seçeneğidir. (MD 4)",
kanit="24-SERİ NO 5.txt | Ek-1'de yer alan örneğe uygun olarak doldurulmuş havayolu basitleştirmesi için başvuru formunu || 24-SERİ NO 5.txt | Şirketi temsile yetkili kişilerce imzalanmış Ek-2'de yer alan beyan formunu || 24-SERİ NO 5.txt | Basitleştirme izni kapsamında taşıma yapılacak havalimanlarının listesini || 24-SERİ NO 5.txt | Şirket bünyesinde asgari 3 adet kargo uçağı ya da asgari 10 adet yolcu uçağı bulundurduğunu || 24-SERİ NO 5.txt | Ruhsatının noter onaylı suretini",
yuva=["Tebliğdeki ek belgeler listesi: Sivil Havacılık Genel Müdürlüğünden alınmış yazı",
      "Tebliğdeki ek belgeler listesi: Ek-1 başvuru formu",
      "Tebliğdeki ek belgeler listesi: Ek-2 beyan formu",
      "Tebliğdeki ek belgeler listesi: taşıma yapılacak havalimanlarının listesi"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU", "KOMŞU"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 6 ---------------- ÖNERMELİ: iznin kullanımı ve başvuru belgeleri ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 4, 6",
cek="İzin kendi sefer koduyla getirilen eşya ve ihracat eşyası için kullanılır; ISO sertifikaları akrediteli kuruluşça; ruhsat noter onaylı suretle sunulur.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre havayolu basitleştirmesi izninin kullanımı ve başvuruda sunulacak belgelere ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Basitleştirme izni, izin sahibinin kendi havayolu şirketine ait sefer kodu ile yurtdışından getirdiği eşyanın Türkiye Gümrük Bölgesi içerisindeki iki gümrük idaresi arasında taşınmasında kullanılabilir.",
     "II. Basitleştirme izni, ihracat eşyasının Türkiye Gümrük Bölgesi içerisindeki iki gümrük idaresi arasında taşınmasında kullanılamaz.",
     "III. Başvuruda sunulacak ISO 9001 ve ISO 27001 sertifikaları, Avrupa Akreditasyon Birliğinin karşılıklı tanıma anlaşmalarına imza atmış akreditasyon kurumlarınca akredite edilmiş uygunluk değerlendirme kuruluşlarınca düzenlenmiş ve akreditasyon kurumunun markasını taşıyan güncel sertifikalar olmalıdır.",
     "IV. Başvuruda, sahip olunan taşımacılık ruhsatının Sivil Havacılık Genel Müdürlüğünce onaylanmış sureti sunulur.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve III",
c=["I ve II", "II ve IV", "I, III ve IV", "I, II, III ve IV"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre basitleştirme izni, izin sahibinin kendi havayolu şirketine ait sefer kodu ile yurtdışından Türkiye Gümrük Bölgesine getirdiği eşyanın bölge içindeki iki gümrük idaresi arasında taşınmasında ve ihracat eşyasının yine izin sahibinin kendi sefer kodu ile bölge içindeki iki gümrük idaresi arasında taşınmasında kullanılabilir. Bu nedenle I doğru, ihracat eşyasını dışarıda bırakan II yanlıştır. Başvuruda; Avrupa Akreditasyon Birliğinin karşılıklı tanıma anlaşmalarına imza atmış akreditasyon kurumlarınca akredite edilmiş uygunluk değerlendirme kuruluşlarınca düzenlenen ve akreditasyon kurumunun markasını taşıyan güncel ISO 9001 ve ISO 27001 sertifikalarının aslı veya onaylı örneği ya da sertifikalar için başvuru yapıldığına ilişkin belgeler sunulur; III doğrudur. Taşımacılık ruhsatı ise noter onaylı suretiyle sunulur; Sivil Havacılık Genel Müdürlüğünden alınan yazı ruhsatın onayı için değil, uçak sayısı ile yurtiçi tarifeli seferlerin kanıtlanması için istenir; IV yanlıştır. En güçlü çeldiriciler II'yi içeren seçeneklerdir: izin yalnız yurtdışından getirilen eşya için değil, ihracat eşyası için de kullanılabilir. Bu nedenle doğru cevap 'I ve III' seçeneğidir. (MD 4, 6)",
kanit="24-SERİ NO 5.txt | Basitleştirme izni, izin sahibinin kendi havayolu şirketine ait sefer kodu ile yurtdışından Türkiye Gümrük Bölgesi'ne getirdiği eşyanın Türkiye Gümrük Bölgesi içerisindeki iki gümrük idaresi arasında taşınmasında ve ihracat eşyasının izin sahibinin kendi havayolu şirketine ait sefer kodu ile Türkiye Gümrük Bölgesi içerisindeki iki gümrük idaresi arasında taşınmasında kullanılabilir || 24-SERİ NO 5.txt | Avrupa Akreditasyon Birliğinin karşılıklı tanıma anlaşmalarına imza atmış akreditasyon kurumları tarafından akredite edilmiş uygunluk değerlendirme kuruluşlarınca düzenlenecek ve akreditasyon kurumunun markasını taşıyan güncel ISO 9001 ve ISO 27001 sertifikalarının aslı veya onaylı örneğini || 24-SERİ NO 5.txt | Ruhsatının noter onaylı suretini",
yuva=["II yanlış: aynı fıkra ihracat eşyasını da kapsar",
      "II ve IV yanlış önermelerdir: ihracat eşyası kapsamdadır, ruhsat noter onaylı suretle sunulur",
      "IV yanlış: ruhsat noter onaylı suretle sunulur; SHGM yazısı uçak sayısı ve seferler içindir",
      "En kapsamlı şık: II ve IV yanlış olduğundan tutmaz"],
yakinlik="PARAFRAZ",
tuzak=["TERSİNE", "KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 7 ---------------- ÖNERMELİ: transit beyanı olarak iletilecek bilgiler ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="ÖNERMELİ",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 7",
cek="Bilgiler sefer ve manifesto bazında iletilir; vergi numarası, uçuş numarası-tarihi, havalimanları ve hareket-varış idareleri bulunur; kayıtlar anlık erişime açıktır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre basitleştirme izni kapsamında transit beyanı olarak gümrük idaresine iletilecek bilgilere ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Her bir taşımaya ilişkin olarak iletilecek bilgiler arasında yükleme (hareket) ve boşaltma (varış) havalimanının adı yer alır; hareket ve varış gümrük idarelerine ise bu bilgilerde yer verilmez.",
     "II. İzin sahibi tarafından basitleştirme izni kapsamında işlem yapılan manifestolar ve manifesto kapsamı konşimentolar, hareket ve varış gümrük idarelerinin elektronik ortamda anlık erişimine açık olmalıdır.",
     "III. Bilgiler, her bir taşımaya ilişkin olarak sefer ve manifesto bazında elektronik ortamda iletilir.",
     "IV. İletilecek bilgiler arasında eşyayı taşıyan havayolu şirketinin vergi numarası ile uçuş numarası ve uçuş tarihi de yer alır.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II, III ve IV",
c=["I ve II", "II ve III", "I, III ve IV", "I, II, III ve IV"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre izin sahibinin basitleştirme izni kapsamında işlem yaptığı manifestolar ve manifesto kapsamı konşimentolar, hareket ve varış gümrük idarelerinin elektronik ortamda anlık erişimine açık olmalıdır; II doğrudur. Her bir taşımaya ilişkin olarak sefer ve manifesto bazında; eşyayı taşıyan havayolu şirketinin vergi numarası, uçuş numarası, uçuş tarihi, yükleme (hareket) ve boşaltma (varış) havalimanının adı, hareket ve varış gümrük idareleri ile hava konşimentosu numaraları elektronik ortamda iletilir; III ve IV doğrudur. Hareket ve varış gümrük idareleri de iletilecek bilgiler arasında sayıldığından I yanlıştır. Gümrük Yönetmeliği'ne göre de havayolu ile taşımalara ilişkin basitleştirilmiş usulde manifesto transit beyanı olarak kullanılır; bu Tebliğ manifesto bilgilerinin hangi ayrıntıyla iletileceğini düzenler. En güçlü çeldirici I'i içeren seçeneklerdir: önermenin ilk yarısı doğru olduğu için ikinci yarıdaki eksiltme gözden kaçabilir. Bu nedenle doğru cevap 'II, III ve IV' seçeneğidir. (MD 7)",
kanit="24-SERİ NO 5.txt | İzin sahibi tarafından basitleştirme izni kapsamında işlem yapılan manifestolar ve manifesto kapsamı konşimentolar hareket ve varış gümrük idarelerinin elektronik ortamda anlık erişimine açık olmalıdır || 24-SERİ NO 5.txt | Basitleştirme izni kapsamında gümrük idaresine, her bir taşımaya ilişkin olarak sefer ve manifesto bazında || 24-SERİ NO 5.txt | Eşyayı taşıyan havayolu şirketinin vergi numarası || 24-SERİ NO 5.txt | Yükleme (hareket) ve boşaltma (varış) havalimanının adı || 24-SERİ NO 5.txt | Hareket ve varış gümrük idareleri || 20-TRANSİT REJİMİ.txt | Denizyolu ve havayolu ile taşımalara ilişkin basitleştirilmiş usulde manifesto",
yuva=["I yanlış: hareket ve varış gümrük idareleri de iletilecek bilgiler arasındadır",
      "III doğru olmasına rağmen dışarıda bırakılmıştır (eksik seçim)",
      "I yanlış olduğundan tutmaz",
      "En kapsamlı şık: I yanlış olduğundan tutmaz"],
yakinlik="BİREBİR",
tuzak=["UNSUR", "KOMŞU"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2025/73",
kapsamli=False,
),

# 8 ---------------- YANLIŞ: konşimento kodları ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="YANLIŞ",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 7",
cek="Öncesinde transit beyanına konu olmuş eşyanın kodu H, devamı HD'dir; TD transite tabi devam eşyasının kodudur.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre basitleştirme izni kapsamında iletilen bilgilerde ilgili konşimento numarasının karşısında kullanılacak kodlara ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Öncesinde bir transit beyanına konu olmuş eşya için “TD” kodu kullanılır.",
c=["Transit rejimine konu olmayan serbest dolaşımdaki kabotaj eşyası için “K” kodu kullanılır.",
   "Transit refakat belgesi düzenlenen eşya için “TR” kodu kullanılır.",
   "İhracata konu olan ve daha önceki bir sefer ile taşınan eşyanın devamı niteliğindeki eşya için “XD” kodu kullanılır.",
   "Transit rejimine tabi tutulan serbest dolaşımda olmayan eşya için “T” kodu kullanılır."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre konşimento numarasının karşısında sekiz kod kullanılır: transite tabi serbest dolaşımda olmayan eşya için T, bunun önceki seferle taşınan eşyanın devamı niteliğindeki kısmı için TD, transit rejimine konu olmayan serbest dolaşımdaki kabotaj eşyası için K, ihracata konu eşya için X, bunun devamı için XD, öncesinde bir transit beyanına konu olmuş eşya için H, bunun devamı için HD ve transit refakat belgesi düzenlenen eşya için TR. Öncesinde bir transit beyanına konu olmuş eşyanın kodu H'dir; TD, transit rejimine tabi tutulan, serbest dolaşımda olmayan ve daha önceki bir seferle taşınan eşyanın devamı niteliğindeki eşyanın kodudur. Diğer seçeneklerdeki eşleşmeler Tebliğle aynıdır. Denizyolu ve demiryolu basitleştirmesini düzenleyen Tebliğlerde yalnızca T, TD, X ve XD kodları sayılmıştır; K, H, HD ve TR kodları havayolu basitleştirmesine özgüdür. En güçlü tuzak, “devam” anlamı taşıyan TD kodunun “önceden transit beyanına konu olma” ile karıştırılmasıdır. Bu nedenle doğru cevap 'Öncesinde bir transit beyanına konu olmuş eşya için “TD” kodu kullanılır.' seçeneğidir. (MD 7)",
kanit="24-SERİ NO 5.txt | Öncesinde bir transit beyanına konu olmuş eşya için “H” kodu || 24-SERİ NO 5.txt | Transit rejimine konu olmayan serbest dolaşımdaki kabotaj eşyası için “K” kodu || 24-SERİ NO 5.txt | Transit refakat belgesi düzenlenen eşya için “TR” kodu || 24-SERİ NO 5.txt | İhracata konu olan ve daha önceki bir sefer ile taşınan eşyanın devamı niteliğindeki eşya için “XD” kodu || 24-SERİ NO 5.txt | Transit rejimine tabi tutulan serbest dolaşımda olmayan eşya için “T” kodu || 26-seri no 8.txt | Serbest dolaşımda olmayan ve daha önceki bir sefer ile taşınan eşyanın devamı niteliğindeki eşya için “TD” kodu",
yuva=["Aynı fıkra: K kodu kabotaj eşyası (doğru eşleşme)",
      "Aynı fıkra: TR kodu transit refakat belgesi düzenlenen eşya (doğru eşleşme)",
      "Aynı fıkra: XD kodu ihracata konu devam eşyası (doğru eşleşme)",
      "Aynı fıkra: T kodu transite tabi serbest dolaşımda olmayan eşya (doğru eşleşme)"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"],
duzey=["TANIMA"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 9 ---------------- KAPSAM DIŞI: talep üzerine ibraz edilecek liste ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="KAPSAM_DIŞI",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 7",
cek="Havayolunda talep üzerine verilen listede konşimento başına alıcı, gönderici, kap adedi, ticari tanım ve brüt ağırlık bulunur; konteyner numarası yoktur.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre izin sahibinin, gümrük idaresince talep edilmesi halinde belirli bir tarih aralığındaki işlemlere ilişkin olarak ibraz edeceği listede her bir konşimento için asgari olarak yer verilecek bilgiler arasında aşağıdakilerden hangisi yer almaz?"],
d="Eşyanın taşındığı konteynerin numarası",
c=["Alıcı ve gönderici",
   "Kap adedi",
   "Brüt ağırlık",
   "Eşyanın tanınması için gerekli tüm bilgileri içeren normal ticari tanımı"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre izin sahibi, gümrük idaresince talep edilmesi halinde belirli bir tarih aralığındaki işlemlere ilişkin bilgileri liste halinde ibraz eder. Listede transit beyanı olarak iletilen bilgilere ek olarak her bir konşimento için asgari olarak alıcı, gönderici, kap adedi, eşyanın tanınması için gerekli tüm bilgileri içeren normal ticari tanımı ve brüt ağırlık yer alır. Konteyner numarası havayolu listesinde sayılmamıştır; bu bilgi, konteynerle taşınan eşyanın deniz limanları arasında taşınmasını düzenleyen denizyolu basitleştirmesi Tebliğindeki listeye eklenmiştir. En güçlü çeldirici budur: iki Tebliğin listeleri büyük ölçüde aynı olduğu için denizyolundaki ek unsur havayoluna taşınabilir. Bu nedenle doğru cevap 'Eşyanın taşındığı konteynerin numarası' seçeneğidir. (MD 7)",
kanit="24-SERİ NO 5.txt | her bir konşimento için asgari olarak aşağıdaki bilgilere yer verilir || 24-SERİ NO 5.txt | Eşyanın tanınması için gerekli tüm bilgileri içeren normal ticari tanımı || 26-seri no 8.txt | Konteyner numarası",
yuva=["Aynı fıkra: alıcı ve gönderici", "Aynı fıkra: kap adedi", "Aynı fıkra: brüt ağırlık", "Aynı fıkra: normal ticari tanım"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "KOMŞU"],
duzey=["AYIRT"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 10 ---------------- KAPSAM DIŞI: konşimento bilgilerinin ilişkilendirileceği kayıtlar ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="KAPSAM_DIŞI",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 8",
cek="Konşimento bilgileri giriş özet beyan, ihracat beyannamesi, transit refakat belgesi ya da transit beyanı kayıtlarıyla ilişkilendirilir.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre basitleştirme izni kapsamında izin sahibince gümrük idaresinin sistemine iletilen konşimento bilgilerinin ilişkilendirileceği kayıtlar arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="Serbest dolaşıma giriş beyannamesi kayıtları",
c=["Eşyaya ilişkin olarak verilen giriş özet beyan kayıtları",
   "İhracat beyannamesi kayıtları",
   "Transit refakat belgesi kayıtları",
   "Transit beyanı kayıtları"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre transit beyanı sayılan bilgiler elektronik veri değişimi sistemiyle sisteme iletilir ve konşimento bilgileri eşyaya ilişkin giriş özet beyan, ihracat beyannamesi, transit refakat belgesi ya da transit beyanı kayıtları ile ilişkilendirilir. Transit refakat belgesi ve transit beyanı kayıtları, havayoluna özgü “TR”, “H” ve “HD” kodlarıyla gösterilen, daha önce transit işlemine konu olmuş eşya içindir. Serbest dolaşıma giriş beyannamesi bu listede yoktur. Demiryolu basitleştirmesinde ilişkilendirme yalnızca giriş özet beyan ya da ihracat beyannamesi kayıtlarıyla, denizyolunda ise özet beyan ya da beyanname kayıtlarıyla yapılır; havayolu listesi bu nedenle ayrıca bilinmelidir. En güçlü çeldirici transit beyanı kayıtlarıdır: bu usulde bilgiler transit beyanı sayıldığından ayrıca bir transit beyanıyla ilişkilendirme yapılmayacağı sanılabilir. Bu nedenle doğru cevap 'Serbest dolaşıma giriş beyannamesi kayıtları' seçeneğidir. (MD 7, 8)",
kanit="24-SERİ NO 5.txt | konşimento bilgileri, eşyaya ilişkin giriş özet beyan, ihracat beyannamesi, transit refakat belgesi ya da transit beyanı kayıtları ile ilişkilendirilir || 25-SERİ NO 6.txt | eşyaya ilişkin giriş özet beyan ya da ihracat beyannamesi kayıtları ile ilişkilendirilir || 26-seri no 8.txt | eşyaya ilişkin özet beyan ya da beyanname kayıtları ile ilişkilendirilir",
yuva=["Aynı fıkra: giriş özet beyan kayıtları", "Aynı fıkra: ihracat beyannamesi kayıtları",
      "Aynı fıkra: transit refakat belgesi kayıtları", "Aynı fıkra: transit beyanı kayıtları"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU", "KOMŞU"],
duzey=["AYIRT"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 11 ---------------- VAKA: 96 saatlik süre ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="SÜRE",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 8",
cek="Bilgiler giriş özet beyandan itibaren 96 saatte iletilmezse eşya geçici depolamaya alınır, sevk ulusal transit beyanıyla yapılır.",
kok=["İzin sahibi bir havayolu şirketi, kendi sefer koduyla yurtdışından İstanbul'daki giriş gümrük idaresine getirdiği ve Ankara'daki bir gümrük idaresine sevk edeceği serbest dolaşımda olmayan eşya için basitleştirme izni çerçevesinde işlem yapmak istemektedir. Olaya ilişkin bilgiler şöyledir:",
     "- Giriş özet beyanda eşyanın başka bir gümrük idaresine sevk edileceğine ilişkin bilgiye yer verilmiş ve özet beyan 3 Mart 2026 günü saat 09.00'da verilmiştir.",
     "- Transit beyanı olarak kabul edilen bilgiler, gümrük idaresinin sistemine 7 Mart 2026 günü saat 11.00'de iletilmiştir.",
     "Buna göre Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) hükümleri çerçevesinde aşağıdakilerden hangisi doğrudur?"],
d="Süre aşıldığından eşya geçici depolama yerine alınır ve varış gümrük idaresine sevki ulusal transit rejimi çerçevesinde transit beyanı ile gerçekleştirilir.",
c=["Bilgiler dört gün içinde iletildiğinden işlemler, eşya geçici depolama yerine alınmaksızın basitleştirme izni çerçevesinde gerçekleştirilir.",
   "Süre aşıldığından eşya geçici depolama yerine alınır; ancak varış gümrük idaresine sevki basitleştirme izni çerçevesinde kayıt numarası üzerinden yapılır.",
   "Süre aşıldığından izin sahibi yazılı olarak uyarılır ve işlemler eşya geçici depolama yerine alınmaksızın sürdürülür.",
   "Bilgilerin hava taşıtının kalkışına kadar iletilmesi yeterli olduğundan süre aşımı söz konusu değildir ve işlemler eşya geçici depolama yerine alınmaksızın yürütülür."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre Türkiye Gümrük Bölgesine havayoluyla getirilen ve giriş gümrük idaresinden bölge içindeki başka bir gümrük idaresine sevk edilecek eşyada basitleştirme izni çerçevesinde işlem yapılabilmesi için transit beyanı sayılan bilgiler, giriş özet beyanın verildiği tarihten itibaren 96 saat içinde gümrük idaresinin sistemine iletilir; bu durumda işlemler eşya geçici depolama yerine alınmaksızın yürütülür. Olayda özet beyan 3 Mart saat 09.00'da verilmiş, bilgiler 7 Mart saat 11.00'de iletilmiştir. Geçen süre 98 saattir ve 96 saatlik süre aşılmıştır. Süre aşılınca eşya geçici depolama yerine alınır ve geçici depolama yerine alınan eşyanın varış gümrük idaresine sevki ulusal transit rejimi çerçevesinde transit beyanı ile gerçekleştirilir. En güçlü çeldirici 'dört gün' yaklaşımıdır: süre gün olarak değil saat olarak ve özet beyanın verildiği andan itibaren hesaplanır. Taşıtın kalkışına kadar iletim, bilgilerin hareket ve varış idarelerine ulaştırılması için öngörülen ayrı bir sınırdır; giriş özet beyanından itibaren işleyen 96 saatlik süreyi ortadan kaldırmaz. Yazılı uyarı ise Tebliğ hükümlerine aykırılıkta askıya almadan önce izin sahibine uygulanan aşamadır. Bu nedenle doğru cevap 'Süre aşıldığından eşya geçici depolama yerine alınır ve varış gümrük idaresine sevki ulusal transit rejimi çerçevesinde transit beyanı ile gerçekleştirilir.' seçeneğidir. (MD 8)",
kanit="24-SERİ NO 5.txt | giriş özet beyanın verildiği tarihten itibaren 96 saat içerisinde gümrük idaresinin sistemine iletilir || 24-SERİ NO 5.txt | Söz konusu sürenin aşılması halinde, eşya geçici depolama yerine alınır || 24-SERİ NO 5.txt | geçici depolama yerine alınan eşyanın varış gümrük idaresine sevki, ulusal transit rejimi çerçevesinde transit beyanı ile gerçekleştirilir || 24-SERİ NO 5.txt | taşıtın kalkışına kadar hareket ve varış gümrük idarelerine iletilmek üzere",
yuva=["Aynı fıkra: 96 saat içinde iletilirse geçici depolamaya alınmaksızın işlem (süre saatle ölçülür)",
      "Hareket idaresi işlemleri: süresinde iletilen bilgilerde kayıt numarası üzerinden basitleştirilmiş sevk",
      "İznin askıya alınması: Tebliğ hükümlerine aykırılıkta ilk iki seferde yazılı uyarı",
      "Aynı madde: bilgiler taşıtın kalkışına kadar iletilir (ayrı sınır)"],
yakinlik="ÇIKARIM",
tuzak=["SAYI", "BAŞLANGIÇ", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[2, 1],
olumsuz=False, vaka=True, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 12 ---------------- SONUÇ: “ambar harici” senetlerde düzeltme ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="SONUÇ",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 8",
cek="“Ambar harici” senetteki eşyanın geçici depolamaya alınması gerekirse gümrük idaresi usulsüzlük cezası uygulamadan sistemde düzeltme yapar.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre basitleştirme izni kapsamında geçici depolama yerine alınmaksızın varış gümrük idaresine sevk edilmesi planlanan eşyaya ilişkin giriş özet beyanda “ambar harici” olarak belirtilen taşıma senetlerinde, eşyanın geçici depolama yerine alınmasının gerekmesi durumunda nasıl işlem yapılır?"],
d="Usulsüzlük cezası uygulanmaksızın sistemde gümrük idaresince gerekli düzeltme yapılır.",
c=["Usulsüzlük cezası uygulanarak sistemde gümrük idaresince gerekli düzeltme yapılır.",
   "Düzeltme, izin sahibinin kayıt numarasını kullanarak taşıtın varış havalimanına varışına kadar değişiklik bilgilerini iletmesiyle yapılır.",
   "İzin sahibi yazılı olarak uyarılır ve taşıma senedindeki kayıt düzeltilmeksizin eşya geçici depolama yerine alınır.",
   "Taşıma senedindeki kayıt düzeltilmeksizin eşya geçici depolama yerine alınır ve Kanunun tasfiye hükümleri uygulanır."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre basitleştirme izni kapsamında geçici depolama yerine alınmaksızın varış gümrük idaresine sevk edilmesi planlanan eşyaya ilişkin giriş özet beyanda “ambar harici” olarak belirtilen taşıma senetlerinde, eşyanın geçici depolama yerine alınmasının gerekmesi durumunda Gümrük Kanunu'nun usulsüzlük cezasına ilişkin hükmü uygulanmaksızın sistemde gümrük idaresince gerekli düzeltme yapılır. Bu şekilde geçici depolama yerine alınan eşyanın varış gümrük idaresine sevki ulusal transit rejimi çerçevesinde transit beyanı ile gerçekleştirilir. Kayıt numarası kullanılarak taşıtın varış havalimanına varışına kadar yapılan değişiklik, izin sahibinin sisteme ilettiği transit beyanı bilgilerine ilişkindir; düzeltmeyi bu hükümde gümrük idaresi yapar. Yazılı uyarı Tebliğ hükümlerine aykırılığa, tasfiye ise süresinde sebebi ispat edilemeyen fazla kaplara bağlanmış sonuçlardır. En güçlü çeldirici usulsüzlük cezasını uygulayan seçenektir; Tebliğ, geçici depolamaya alınma zorunluluğunu cezaya konu etmemiştir. Bu nedenle doğru cevap 'Usulsüzlük cezası uygulanmaksızın sistemde gümrük idaresince gerekli düzeltme yapılır.' seçeneğidir. (MD 8)",
kanit="24-SERİ NO 5.txt | giriş özet beyanda “ambar harici” olarak belirtilen taşıma senetlerinde, eşyanın geçici depolama yerine alınmasının gerekmesi durumunda, Kanunun 241 inci maddesinin birinci fıkrası uygulanmaksızın sistemde gümrük idaresince gerekli düzeltme yapılır || 24-SERİ NO 5.txt | ilgili kayıt numarası kullanılarak değişiklik bilgileri taşıtın varış havalimanına varışına kadar || 24-SERİ NO 5.txt | izin sahibi ilk iki seferde yazılı olarak uyarılır || 24-SERİ NO 5.txt | fazla çıkan eşya Kanunun 177 nci maddesi kapsamında tasfiyeye tabi tutulur",
yuva=["Aynı fıkra: düzeltme usulsüzlük cezası uygulanmaksızın yapılır (tersine çevrilmiş)",
      "Aynı madde: izin sahibinin değişiklik bilgilerini varış havalimanına varışa kadar iletmesi",
      "İznin askıya alınması: Tebliğ hükümlerine aykırılıkta ilk iki seferde yazılı uyarı",
      "Varış işlemleri: fazla çıkan kapın sebebi ispat edilemezse tasfiye"],
yakinlik="PARAFRAZ",
tuzak=["TERSİNE", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 13 ---------------- ÖNERMELİ (bütünleşik): havayolu ile transit ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Yönetmeliği md. 222, 223; Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 8",
cek="Havayolu transitinde teminat aranmaz, gerekli görülmedikçe mühürlenmez; taşıyan havayolu şirketi rejim hak sahibidir; kalkış öncesi iletimle eşya hareket idaresine sunulmuş sayılır.",
kok=["Gümrük Yönetmeliği ve Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre havayolu ile yapılan transit taşımalarına ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Havayolu ile yapılan transit taşımalarında teminat aranmaz.",
     "II. Havayolu ile yapılan taşımalarda, gümrük idaresince gerekli görülen haller dışında mühürleme yapılmaz.",
     "III. Basitleştirme izni kapsamında taşıma yapan havayolu şirketi rejim hak sahibi olmaz; taşıma işlemleri için rejim hak sahibi eşyanın alıcısıdır.",
     "IV. Basitleştirme izni kapsamında transit beyanı sayılan bilgilerin hava taşıtının kalkışı öncesinde sisteme iletilmesi halinde, eşyanın varış gümrük idaresine sunulmuş olduğu kabul edilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve II",
c=["I ve III", "II ve IV", "I, II ve IV", "I, II, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre transit rejiminde teminat kural olarak zorunludur; ancak havayolu, boru hattı, denizyolu ve basitleştirilmiş usulde demiryolu ile yapılan taşımalarda teminat aranmaz; I doğrudur. Yönetmelik ayniyetin genel kural olarak mühürlemeyle sağlanacağını belirtir; denizyolu ve havayolu ile yapılan taşımalarda ise gümrük idaresince gerekli görülen haller dışında mühürleme yapılmaz; II doğrudur. Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre basitleştirme izni kapsamında taşıma yapan havayolu şirketi, taşıma işlemleri için rejim hak sahibi olur; III yanlıştır. Transit beyanı sayılan bilgilerin hava taşıtının kalkışı öncesinde sisteme iletilmesi halinde eşyanın varış idaresine değil hareket gümrük idaresine sunulmuş olduğu kabul edilir; IV yanlıştır. En güçlü çeldirici 'I, II ve IV' seçeneğidir: IV'te tek kelime değiştirilmiş, hareket idaresi yerine varış idaresi yazılmıştır. Bu nedenle doğru cevap 'I ve II' seçeneğidir. (MD 8; GY 222, 223)",
kanit="20-TRANSİT REJİMİ.txt | teminat verilmesi zorunludur. Ancak || 20-TRANSİT REJİMİ.txt | ile yapılan taşımalarda teminat aranmaz || 20-TRANSİT REJİMİ.txt | Denizyolu ve havayolu ile yapılan taşımalarda, gümrük idaresince gerekli görülen hallerin dışında mühürleme yapılmaz || 24-SERİ NO 5.txt | Basitleştirme izni kapsamında taşıma yapan havayolu şirketi, taşıma işlemleri için rejim hak sahibi olur || 24-SERİ NO 5.txt | hava taşıtının kalkışı öncesinde gümrük idaresinin sistemine elektronik veri değişimi sistemi ile iletilmesi halinde, eşyanın hareket gümrük idaresine sunulmuş olduğu kabul edilir",
yuva=["III yanlış: taşıma yapan havayolu şirketi rejim hak sahibidir",
      "IV yanlış: kalkış öncesi iletimle eşya hareket idaresine sunulmuş sayılır",
      "IV yanlış olduğundan üçlü birleşim tutmaz (hareket ↔ varış)",
      "En kapsamlı şık: III ve IV yanlış olduğundan tutmaz"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU", "TERİM"],
duzey=["BÜTÜNLEŞİK"],
profil=[1, 4],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/47; 2022/76",
kapsamli=False,
),

# 14 ---------------- YANLIŞ: varış gümrük idaresindeki işlemler ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="YANLIŞ",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 9",
cek="Varış işlemleri, taşıtın varışının idarece tespiti ya da belge aranmaksızın izin sahibi firmanın elektronik bildirimi üzerine kayıt numarasıyla yapılır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre varış gümrük idaresinde yapılacak işlemlere ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Varış işlemleri, hava taşıtının varış havalimanına ulaştığının izin sahibi adına gümrük müşavirince düzenlenen belgelerle varış gümrük idaresine yazılı olarak bildirilmesi üzerine gerçekleştirilir.",
c=["Hava taşıtının varış havalimanına ulaştığının gümrük idaresince tespit edilmesi üzerine, varış işlemleri kayıt numarası üzerinden gerçekleştirilir.",
   "Varış işlemleri ile birlikte, giriş özet beyanda ilgili konşimentoda kayıtlı eşya bilgileri varış gümrük idaresindeki kayıt ile ilişkilendirilir.",
   "Beyana aykırılığın Kaçakçılıkla Mücadele Kanununu da ihlal eder nitelikte olması durumunda, izin sahibinin havayolu taşımacılığına ilişkin uluslararası ve ulusal mevzuattaki sorumlulukları da göz önünde bulundurulur.",
   "Varış gümrük idaresince gerek görülmesi halinde, belirli bir tarih aralığındaki işlemlere ilişkin tarama veya yoklama yöntemiyle kontroller gerçekleştirilir."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre varış işlemleri, hava taşıtının varış havalimanına ulaştığının gümrük idaresince tespit edilmesi ya da herhangi bir belge aranmaksızın izin sahibi firma tarafından gümrük idaresine elektronik ortamda bildirilmesi üzerine, transit beyanı bilgilerinin iletilmesiyle verilen kayıt numarası üzerinden gerçekleştirilir. Bildirim izin sahibi havayolu şirketince elektronik ortamda yapılır; gümrük müşavirince düzenlenmiş belgelerle yazılı bildirim öngörülmemiştir. Varış işlemleriyle giriş özet beyandaki konşimento bilgileri varış idaresindeki kayıtla ilişkilendirilir; 5607 sayılı Kanunu ihlal eden aykırılıklarda izin sahibinin uluslararası ve ulusal mevzuattaki sorumlulukları gözetilir; varış idaresi gerek görürse tarama veya yoklama yöntemiyle kontrol yapar. Bu soruda tuzak, her işlemde gümrük müşavirinin belgesinin arandığı önyargısıdır; Tebliğ varış bildirimini belge aramaksızın izin sahibine bırakmıştır. Bu nedenle doğru cevap 'Varış işlemleri, hava taşıtının varış havalimanına ulaştığının izin sahibi adına gümrük müşavirince düzenlenen belgelerle varış gümrük idaresine yazılı olarak bildirilmesi üzerine gerçekleştirilir.' seçeneğidir. (MD 9)",
kanit="24-SERİ NO 5.txt | Hava taşıtının varış havalimanına ulaştığının gümrük idaresince tespit edilmesi ya da herhangi bir belge aranmaksızın izin sahibi firma tarafından gümrük idaresine elektronik ortamda bildirilmesi üzerine || 24-SERİ NO 5.txt | giriş özet beyanda ilgili konşimentoda kayıtlı eşya bilgileri de varış gümrük idaresindeki kayıt ile ilişkilendirilir || 24-SERİ NO 5.txt | izin sahibinin havayolu ile eşya taşımacılığına ilişkin olarak uluslararası ve ulusal mevzuat ile düzenlenmiş sorumlulukları da göz önünde bulundurularak || 24-SERİ NO 5.txt | Varış gümrük idaresince gerek görülmesi halinde, belirli bir tarih aralığında izin kapsamında gerçekleştirilen işlemlere ilişkin olarak tarama veya yoklama yöntemiyle kontroller gerçekleştirilir",
yuva=["Aynı fıkra: gümrük idaresinin tespiti üzerine kayıt numarasıyla varış işlemi (doğru)",
      "Aynı fıkra: konşimento bilgilerinin varış kaydıyla ilişkilendirilmesi (doğru)",
      "Aynı madde: 5607 ihlalinde izin sahibinin sorumluluklarının gözetilmesi (doğru)",
      "Aynı madde: varış idaresince tarama veya yoklama (doğru)"],
yakinlik="BİREBİR",
tuzak=["SAĞDUYU", "TERİM", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 15 ---------------- KAPSAM: eksik-fazla usulünün uygulandığı durum ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="KAPSAM",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 9; Gümrük Yönetmeliği md. 239",
cek="Tebliğdeki eksik-fazla usulü, boşaltmadan sonra izin sahibi veya idarenin tespitinde cinsi uygun serbest dolaşımda olmayan eşyada kap adedi farkında uygulanır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'te varış gümrük idaresinde kap adedinin eksik veya fazla çıkması haline ilişkin olarak öngörülen usul aşağıdaki durumlardan hangisinde uygulanır?"],
d="Eşyanın boşaltılması sonrasında izin sahibi havayolu işleticisi veya gümrük idaresince yapılan tespitte, serbest dolaşımda olmayan eşyanın beyandaki cinsine uygun olmakla birlikte kap adedinin farklı çıkması",
c=["Eşyanın boşaltılması sonrasında yapılan tespitte, transit rejimine konu olmayan serbest dolaşımdaki kabotaj eşyasının kap adedinin farklı çıkması",
   "Eşyanın boşaltılması sonrasında yapılan tespitte, serbest dolaşımda olmayan eşyanın beyandaki cinsinden farklı bir eşya olarak çıkması",
   "Eşyanın hareket havalimanında hava taşıtına yüklenmesi sırasında hareket gümrük idaresince yapılan tespitte kap adedinin farklı çıkması",
   "Eşyanın boşaltılması sonrasında yapılan tespitte, kap adedi beyana uygun olan serbest dolaşımda olmayan eşyanın brüt ağırlığının farklı çıkması"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre eşyanın boşaltılması sonrasında izin sahibi havayolu işleticisi veya gümrük idaresince yapılan tespit sonucunda, serbest dolaşımda olmayan eşyanın beyanda belirtilen cinsine uygun olmakla birlikte kap adedinin eksik veya fazla çıkması halinde Tebliğdeki özel usul uygulanır: eksik kaplar için on gün içinde başka bir hava taşıtıyla getirme ve ispat süresi, fazla kaplar için geçici depolama, ispat ve tasfiye. Usulün dört unsuru vardır: tespit boşaltmadan sonra yapılır, tespiti izin sahibi havayolu işleticisi de yapabilir, eşya serbest dolaşımda değildir ve aykırılık cinste değil kap adedindedir. Kabotaj eşyası serbest dolaşımdadır ve transit rejimine konu değildir. Beyan edilenden farklı eşya çıkması hâli için Gümrük Yönetmeliği ayrı bir usul öngörür. Tespitin yükleme sırasında hareket idaresince yapılması da, kap adedi beyana uygunken yalnızca brüt ağırlığın farklı çıkması da hükmün kapsamında değildir; brüt ağırlık, izin sahibinin talep üzerine ibraz edeceği listede yer alan bir bilgidir. En güçlü çeldirici cins farkını içeren seçenektir: Tebliğ yalnızca cinsi beyana uygun eşyada kap adedi farkını düzenler. Bu nedenle doğru cevap 'Eşyanın boşaltılması sonrasında izin sahibi havayolu işleticisi veya gümrük idaresince yapılan tespitte, serbest dolaşımda olmayan eşyanın beyandaki cinsine uygun olmakla birlikte kap adedinin farklı çıkması' seçeneğidir. (MD 9; GY 239)",
kanit="24-SERİ NO 5.txt | Eşyanın boşaltılması sonrasında izin sahibi havayolu işleticisi veya gümrük idaresince yapılan tespit sonucunda serbest dolaşımda olmayan eşyanın beyanda belirtilen cinsine uygun olmakla birlikte || 24-SERİ NO 5.txt | Transit rejimine konu olmayan serbest dolaşımdaki kabotaj eşyası || 20-TRANSİT REJİMİ.txt | beyan edilen serbest dolaşımda bulunmayan eşyaya ilaveten farklı eşya tespit edilmesi halinde",
yuva=["Konşimento kodları: K kodlu kabotaj eşyası serbest dolaşımdadır ve transite konu değildir",
      "Gümrük Yönetmeliği ulusal transit: beyan dışı farklı eşya için ayrı usul",
      "Hareket idaresi işlemleri: kontroller hareket idaresince; hüküm boşaltma sonrası tespiti arar",
      "Talep üzerine verilen liste: brüt ağırlık bilgisi; hüküm yalnızca kap adedi farkını düzenler"],
yakinlik="BİREBİR",
tuzak=["UNSUR", "KOMŞU", "İSTİSNA"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 16 ---------------- VAKA: eksik çıkan kaplar ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="SONUÇ",
z="ÇZ",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 9; Gümrük Yönetmeliği md. 239",
cek="Eksik kaplar süresinde başka hava taşıtıyla getirilirse ispat aranmaz; getirilmeyenler için ispat varış gümrük idaresine yapılır.",
kok=["Basitleştirme izni sahibi bir havayolu şirketi, kendi sefer koduyla yurtdışından getirdiği 40 kaplık serbest dolaşımda olmayan eşyayı Türkiye Gümrük Bölgesi içindeki bir varış gümrük idaresine taşımıştır. Olaya ilişkin bilgiler şöyledir:",
     "- Eşyanın boşaltılması sonrasında yapılan tespitte eşyanın beyanda belirtilen cinsine uygun olduğu, ancak 5 kabın eksik çıktığı anlaşılmıştır.",
     "- Eksik kaplardan 3'ü, tespitten 3 gün sonra başka bir hava taşıtı ile getirilerek varış gümrük idaresine sunulmuştur.",
     "- Kalan 2 kap, tespitten itibaren 15 gün geçmesine rağmen getirilmemiştir.",
     "Buna göre Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) hükümleri çerçevesinde aşağıdakilerden hangisi doğrudur?"],
d="Yalnızca getirilmeyen 2 kap için, eksikliğin mahrecindeki eksik yüklemeden veya yanlış beyandan kaynaklandığının varış gümrük idaresine ispat edilmesi istenir.",
c=["Eksik çıkan 5 kabın tamamı için, eksikliğin mahrecindeki eksik yüklemeden veya yanlış beyandan kaynaklandığının varış gümrük idaresine ispat edilmesi istenir.",
   "Yalnızca getirilmeyen 2 kap için, eksikliğin mahrecindeki eksik yüklemeden veya yanlış beyandan kaynaklandığının hareket gümrük idaresine ispat edilmesi istenir.",
   "Getirilmeyen 2 kap için ispat istenmeksizin gümrük vergileri ve diğer yükler tahsil edilir ve usulsüzlük cezası uygulanır.",
   "Getirilmeyen 2 kap için gümrük vergileri ile birlikte gümrük vergilerinin iki katı idari para cezası tahsil edilerek rejim ibra edilir."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre boşaltma sonrasında serbest dolaşımda olmayan eşyanın beyandaki cinsine uygun olmakla birlikte kap adedinin eksik çıkması ve eksik eşyanın 10 gün içinde başka bir hava taşıtıyla getirilerek varış gümrük idaresine sunulmaması halinde, varış gümrük idaresi izin sahibinden eksikliğin mahrecindeki eksik yüklemeden veya yanlış beyandan kaynaklandığının yirmi sekiz gün içinde varış gümrük idaresine ispat edilmesini ister; bu süre yazılı başvuruyla yirmi sekiz gün daha uzatılabilir. İspat edilirse işlemler tamamlanır; edilemezse gümrük vergileri ve diğer yükler tahsil edilir ve ayrıca usulsüzlük cezası uygulanır. Olayda 3 kap on günlük süre içinde getirildiğinden ispat yükümlülüğü yalnızca getirilmeyen 2 kap için doğar; vakada saklanan istisna budur. Gümrük Yönetmeliği'nin ulusal transitteki eksiklik için öngördüğü genel usulde ise ispat, uyuşmazlık bildiriminden itibaren 28 gün içinde hareket gümrük idaresine yapılır ve ispat edilemezse vergilerin iki katı idari para cezası uygulanarak rejim ibra edilir; havayolu basitleştirmesinde ispat makamı varış gümrük idaresidir. Vergilerin tahsili ve usulsüzlük cezası ise ancak ispat süresi sonuçsuz geçtiğinde gündeme gelir. En güçlü çeldirici, beş kabın tamamını ispata tabi tutan seçenektir. Bu nedenle doğru cevap 'Yalnızca getirilmeyen 2 kap için, eksikliğin mahrecindeki eksik yüklemeden veya yanlış beyandan kaynaklandığının varış gümrük idaresine ispat edilmesi istenir.' seçeneğidir. (MD 9; GY 239)",
kanit="24-SERİ NO 5.txt | eksik çıkan eşyanın 10 gün içerisinde başka bir hava taşıtı ile getirilerek varış gümrük idaresine sunulmaması durumunda, varış gümrük idaresince izin sahibinden eksikliğin mahrecindeki eksik yüklemeden veya yanlış beyandan kaynaklandığının, yirmi sekiz gün içerisinde varış gümrük idaresine ispat edilmesi istenir || 24-SERİ NO 5.txt | gümrük vergileri ve diğer yüklerin tahsil edilmesinin yanı sıra, Kanunun 241 inci maddesinin birinci fıkrası uygulanır || 20-TRANSİT REJİMİ.txt | uyuşmazlık bildiriminden itibaren 28 gün içerisinde rejim hak sahibince hareket gümrük idaresine ispat edilmesi gerekir || 20-TRANSİT REJİMİ.txt | eşyanın gümrük vergilerinin iki katı idari para cezası uygulanır ve hareket gümrük idaresince rejim ibra edilir",
yuva=["Aynı bent: süresinde getirilen kaplar için ispat istenmez (istisna gözden kaçarsa)",
      "Gümrük Yönetmeliği ulusal transitte eksiklik: ispat hareket gümrük idaresine yapılır",
      "Aynı bent: süresinde ispat edilemezse vergiler tahsil edilir ve usulsüzlük cezası uygulanır",
      "Gümrük Yönetmeliği ulusal transitte eksiklik: vergilerin iki katı idari para cezası ve ibra"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "MAKAM", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[1],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="eksik-fazla",
guncellik="",
cikmis="",
kapsamli=False,
),

# 17 ---------------- SÜRE (çift bilgi): eksik kaplarda getirme ve ispat süreleri ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="SÜRE",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 9",
cek="Eksik kaplar on gün içinde başka hava taşıtıyla getirilmezse sebep yirmi sekiz günde ispat edilir; süre yazılı başvuruyla yirmi sekiz gün uzar.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre basitleştirme izni kapsamında taşınan serbest dolaşımda olmayan eşyanın boşaltılması sonrasında kap adedinin eksik çıkması halinde, eksik eşyanın başka bir hava taşıtıyla getirilerek varış gümrük idaresine sunulması için öngörülen süre ile eksikliğin sebebinin ispatı için izin sahibine verilen süre sırasıyla aşağıdakilerden hangisidir?"],
d="10 gün – 28 gün",
c=[],
sirali=True,
siklar=["10 gün – 15 gün", "10 gün – 28 gün", "10 gün – 30 gün", "15 gün – 28 gün", "28 gün – 28 gün"],
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre kap adedi eksik çıkan eşyanın 10 gün içinde başka bir hava taşıtıyla getirilerek varış gümrük idaresine sunulmaması halinde, varış gümrük idaresi izin sahibinden eksikliğin mahrecindeki eksik yüklemeden veya yanlış beyandan kaynaklandığının yirmi sekiz gün içinde ispat edilmesini ister. Yirmi sekiz günlük süre yazılı başvuru halinde yirmi sekiz gün daha uzatılabilir; fazla çıkan kaplarda da ispat süresi aynı biçimde 28 gündür. On beş gün, taşıma yapılacak havalimanlarındaki değişikliklerin taşımalardan önce Bakanlığa bildirilme süresidir; otuz gün ise izin koşullarının karşılanmadığı durumlarda düzeltme için verilen süredir. En güçlü çeldirici '28 gün – 28 gün' seçeneğidir: ikinci 28 gün ispat süresinin uzatılabileceği ek süredir, getirme süresi değildir. Bu nedenle doğru cevap '10 gün – 28 gün' seçeneğidir. (MD 9)",
kanit="24-SERİ NO 5.txt | eksik çıkan eşyanın 10 gün içerisinde başka bir hava taşıtı ile getirilerek varış gümrük idaresine sunulmaması durumunda || 24-SERİ NO 5.txt | yirmi sekiz gün içerisinde varış gümrük idaresine ispat edilmesi istenir. Bu süre yazılı başvuru halinde, yirmi sekiz gün daha uzatılabilir || 24-SERİ NO 5.txt | taşımaların başlamasının planlandığı tarihten en geç 15 gün öncesinde || 24-SERİ NO 5.txt | bildirim tarihinden başlamak üzere otuz gün süre verilir",
yuva=["Yükümlülükler: havalimanı değişiklikleri en geç 15 gün önce bildirilir",
      "Askıya alma: izin koşullarının düzeltilmesi için otuz gün",
      "On beş gün havalimanı bildirimine aittir; ispat süresi doğru",
      "Aynı bent: ispat süresi 28 gün ve yazılı başvuruyla 28 gün daha uzatma"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"],
duzey=["AYIRT"],
profil=[2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 18 ---------------- ÖNERMELİ: fazla çıkan kaplar ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 9",
cek="Fazla kap geçici depolamaya alınır, diğer eşyaya devam edilir; ticari belgeden yanlış beyan anlaşılırsa doğrudan, aksi halde ispatla rejim beyanı; ispatsızlıkta tasfiye.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre basitleştirme izni kapsamında taşınan serbest dolaşımda olmayan eşyanın boşaltılması sonrasında kap adedinin miktarca fazla çıkması haline ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Fazlalığın yanlış beyan sebebiyle ortaya çıktığı beyannameye ekli fatura ve ticari belgelerde kayıtlı bilgilerden anlaşılsa bile, fazla eşya için rejim beyanında bulunulabilmesi fazlalığın sebebinin ayrıca ispat edilmesine bağlıdır.",
     "II. Fazla çıkan eşya geçici depolama yerine alınır; talep edilmesi halinde beyana konu diğer eşyanın gümrük işlemlerine devam edilir.",
     "III. Fazlalığın sebebinin süresi içerisinde ispat edilmesi halinde, fazla çıkan eşyaya ilişkin rejim beyanında bulunulmasına izin verilir.",
     "IV. Fazlalığın sebebinin süresi içerisinde ispat edilememesi halinde, gümrük vergileri ve diğer yükler tahsil edilir ve usulsüzlük cezası uygulanır.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve III",
c=["I ve II", "III ve IV", "I, II ve III", "II, III ve IV"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre kap adedinin fazla çıkması halinde fazla eşya geçici depolama yerine alınır ve talep edilirse beyana konu diğer eşyanın gümrük işlemlerine devam edilir; II doğrudur. Fazlalığın yanlış beyan sebebiyle ortaya çıktığı beyannameye ekli fatura ve ticari belgelerden anlaşılırsa, ayrıca ispat aranmadan fazla eşyaya ilişkin rejim beyanına izin verilir; I yanlıştır. Aksi halde fazlalığın mahrecindeki fazla yüklemeden veya yanlış beyandan kaynaklandığı 28 gün içinde ispat edilir, süre yazılı başvuruyla yirmi sekiz gün daha uzatılabilir ve süresinde ispat edilirse rejim beyanına izin verilir; III doğrudur. Süresinde ispat edilemezse fazla çıkan eşya Gümrük Kanunu'nun tasfiye hükmü kapsamında tasfiyeye tabi tutulur; vergilerin tahsili ve usulsüzlük cezası aynı fıkrada eksik çıkan kaplara bağlanmış sonuçtur; IV yanlıştır. En güçlü çeldirici 'II, III ve IV' seçeneğidir: eksik ve fazla kaplar aynı fıkrada farklı sonuçlara bağlanmıştır. Bu nedenle doğru cevap 'II ve III' seçeneğidir. (MD 9)",
kanit="24-SERİ NO 5.txt | Kap adedinin miktarca fazla çıkması halinde, fazla çıkan eşya geçici depolama yerine alınır; talep edilmesi halinde, beyana konu diğer eşyanın gümrük işlemlerine devam edilir || 24-SERİ NO 5.txt | Beyannameye ekli fatura ve ticari belgelerde kayıtlı bilgilerden fazlalığın yanlış beyan sebebiyle ortaya çıktığı anlaşılırsa, fazla eşyaya ilişkin rejim beyanında bulunulmasına izin verilir || 24-SERİ NO 5.txt | Fazlalığın sebebinin süresi içerisinde ispat edilmesi halinde, fazla çıkan eşyaya ilişkin rejim beyanında bulunulmasına izin verilir || 24-SERİ NO 5.txt | Fazlalığın sebebinin süresi içerisinde ispat edilememesi halinde, fazla çıkan eşya Kanunun 177 nci maddesi kapsamında tasfiyeye tabi tutulur",
yuva=["I yanlış: ticari belgelerden anlaşılırsa ispat aranmadan rejim beyanına izin verilir",
      "IV yanlış: sonuç tasfiyedir; vergi ve usulsüzlük cezası eksik kaplara aittir",
      "I yanlış olduğundan tutmaz",
      "IV yanlış olduğundan tutmaz (eksik ↔ fazla sonuç karışması)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERSİNE", "ŞART"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="eksik-fazla",
guncellik="",
cikmis="",
kapsamli=False,
),

# 19 ---------------- ŞART: çıktı sunma yükümlülüğü ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="ŞART",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 12",
cek="İzin sahibi, talep edilmesi veya sistemdeki bilgilere anlık erişim sağlanamaması halinde manifesto ve konşimento çıktısını idarelere sunar.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre izin sahibi, hareket ve varış gümrük idarelerine manifestonun ve manifesto kapsamı konşimentoların çıktısını hangi hallerde sunmakla yükümlüdür?"],
d="Gümrük idaresince talep edilmesi veya sistemdeki bilgilere anlık erişimin sağlanamadığı hallerde",
c=["Yalnızca özet beyan eksiklik ve fazlalığının tespit edildiği hallerde",
   "Her taşımada, hava taşıtının kalkışından önce",
   "Yalnızca varış gümrük idaresince eşyanın muayene edilmesine karar verilen hallerde",
   "Belirli bir tarih aralığındaki işlemler için her takvim yılının sonunda"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre izin sahibi, gümrük idaresince talep edilmesi veya sistemdeki bilgilere anlık erişimin sağlanamadığı hallerde hareket ve varış gümrük idarelerine manifestonun ve manifesto kapsamı konşimentoların çıktısını sunmakla yükümlüdür. Denizyolu basitleştirmesinde bu yükümlülük yalnızca idarelerce talep edilmesine bağlanmıştır; havayolu düzenlemesi ise kayıtların hareket ve varış idarelerinin anlık erişimine açık tutulmasını esas aldığından anlık erişimin sağlanamaması halini de ayrıca sayar. Özet beyan eksiklik ve fazlalığı ile beyanın kontrolüne veya eşyanın muayenesine karar verilen durumlar, giriş özet beyanlara ilişkin kâğıt ibraz kolaylığının istisnalarıdır; çıktı yükümlülüğü bunlarla sınırlı değildir. Kalkıştan önce yapılan işlem bilgilerin elektronik ortamda iletilmesidir; takvim yılı ise yazılı uyarıların sayıldığı dönemdir. En güçlü çeldirici muayene kararına bağlayan seçenektir; Tebliğ çıktı yükümlülüğünü muayene ile sınırlamamış, talep ve erişim sorunu hallerine bağlamıştır. Bu nedenle doğru cevap 'Gümrük idaresince talep edilmesi veya sistemdeki bilgilere anlık erişimin sağlanamadığı hallerde' seçeneğidir. (MD 12)",
kanit="24-SERİ NO 5.txt | Gümrük idaresince talep edilmesi veya sistemdeki bilgilere anlık erişimin sağlanamadığı hallerde hareket ve varış gümrük idarelerine manifestonun ve manifesto kapsamı konşimentoların çıktısını sunmakla || 24-SERİ NO 5.txt | özet beyan eksiklik ve fazlalık durumları hariç olmak üzere || 26-seri no 8.txt | Hareket veya varış gümrük idarelerince talep edilmesi halinde, manifestonun ve manifesto içeriği konşimentoların çıktıları",
yuva=["Hareket idaresi işlemleri: kâğıt ibraz kolaylığının istisnası olan eksiklik-fazlalık durumları",
      "Hareket idaresi işlemleri: bilgiler taşıtın kalkışına kadar elektronik ortamda iletilir",
      "Varış idaresi işlemleri: varış idaresi gerekli gördüğünde muayene eder ve çıktı isteyebilir",
      "Askıya alma: yazılı uyarıların sayıldığı takvim yılı"],
yakinlik="BİREBİR",
tuzak=["ŞART", "KOMŞU"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 20 ---------------- YANLIŞ: izin sahibinin yükümlülükleri ----------------
dict(
konu="Transit Tebliği (Seri No: 5)", blok="SB23",
kalip="YANLIŞ",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5) md. 12",
cek="İzin sahibi manifesto ve konşimentoların sorgulanabilmesi için işlem tarihinden itibaren üç yıl erişim sağlar.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre izin sahibinin yükümlülüklerine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="İzin kapsamındaki işlemlere ait manifesto ve konşimentoların gümrük idaresince sorgulanabilmesi için işlem tarihinden itibaren beş yıl süreyle erişim sağlamakla yükümlüdür.",
c=["Kayıtlarında, izin kapsamı sevkiyatlara konu eşyanın statüsüne ilişkin gerekli ayrımı sağlamakla yükümlüdür.",
   "Sevkiyatın ayniyetini sağlamak üzere gerekli tedbirleri almakla yükümlüdür.",
   "Gümrük idaresinin yapacağı gümrük kontrolleri için gerek duyulan uygun ortamı sağlamakla yükümlüdür.",
   "Her türlü usulsüzlük ve uyuşmazlığı hareket ve varış gümrük idarelerine bildirmek ve bunların araştırılmasında bu idarelerle işbirliği yapmakla yükümlüdür."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 5)'e göre izin sahibi, belirli bir tarih aralığında izin kapsamında gerçekleştirdiği işlemlere ilişkin manifesto ve manifesto kapsamı konşimentoların gümrük idaresince sorgulanabilmesi için işlem tarihinden itibaren üç yıl süreyle gerekli erişimi sağlamak ve talep halinde bunları liste halinde ibraz etmekle yükümlüdür; beş yıl ifadesi yanlıştır. Eşyanın statüsüne ilişkin kayıtlarda gerekli ayrımı sağlamak, sevkiyatın ayniyetini sağlamak üzere tedbir almak, gümrük kontrolleri için uygun ortamı sağlamak ve her türlü usulsüzlük ile uyuşmazlığı hareket ve varış idarelerine bildirip araştırmada işbirliği yapmak Tebliğde sayılan yükümlülüklerdendir. Bu soruda tuzak süredir: erişim süresini yaklaşık hatırlayan aday değiştirilmiş sayıyı fark etmez. Bu nedenle doğru cevap 'İzin kapsamındaki işlemlere ait manifesto ve konşimentoların gümrük idaresince sorgulanabilmesi için işlem tarihinden itibaren beş yıl süreyle erişim sağlamakla yükümlüdür.' seçeneğidir. (MD 12)",
kanit="24-SERİ NO 5.txt | işlem tarihinden itibaren üç yıl süre ile gerekli erişimi sağlamakla || 24-SERİ NO 5.txt | Kayıtlarında, izin kapsamı sevkiyatlara konu eşyanın statüsüne ilişkin gerekli ayrımı sağlamakla || 24-SERİ NO 5.txt | Sevkiyatın ayniyetini sağlamak üzere gerekli tedbirleri almakla || 24-SERİ NO 5.txt | Gümrük idaresinin yapacağı gümrük kontrolleri için gerek duyulan uygun ortamı sağlamakla || 24-SERİ NO 5.txt | Her türlü usulsüzlük ve uyuşmazlıkları hareket ve varış gümrük idarelerine bildirmekle",
yuva=["Yükümlülükler: statüye ilişkin kayıtlarda ayrım (doğru ifade)",
      "Yükümlülükler: sevkiyatın ayniyetinin sağlanması (doğru ifade)",
      "Yükümlülükler: gümrük kontrolleri için uygun ortam (doğru ifade)",
      "Yükümlülükler: usulsüzlük ve uyuşmazlıkların bildirimi ve işbirliği (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["SAYI", "YAKIN-SAYI"],
duzey=["HATIRLAMA"],
profil=[4, 2],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

]
