# Soru Bankası — Bölüm 21: Transit Tebliği (Seri No: 3) — 20 soru
# Gümrük Koçu - Ufuk Çetintaş
# Kaynak: 22-SERİ NO 3.txt (Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 3) md. 1-17, Geçici 1)
# Sayı havuzu çeldiricileri için: 29-iŞLETİCİLER.txt (GY 518, 527), 30-Güm.Sat.Mağazaları.txt
K = "Transit Tebliği (Seri No: 3)"
T = "Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 3)"
Q = [

# 1 — md 1: Tebliğin kapsamındaki ürünler (kapalı liste, liste dışı)
dict(
konu=K, blok="SB21",
kalip="KAPSAM_DIŞI", z="O",
madde=T + " md. 1",
cek="Tebliğ yedi ürünün (ham petrol, nafta, fuel-oil, gazyağı, benzin, motorin, jet yakıtı) karayolu veya demiryolu transitini düzenler; LPG kapsamda değildir.",
kok=[T + "'e göre, 2011/2033 sayılı Bakanlar Kurulu Kararı kapsamında transitine izin verilen ve Türkiye Cumhuriyeti Gümrük Bölgesinde karayolu veya demiryolu ile transitinde uyulacak usul ve esasları bu Tebliğle belirlenen serbest dolaşımda bulunmayan eşya arasında aşağıdakilerden hangisi yer almaz?"],
d="Sıvılaştırılmış petrol gazı (LPG)",
c=["Nafta", "Fuel-oil", "Gazyağı", "Jet yakıtı"],
sirali=False,
g="Tebliğin amacı, 2011/2033 sayılı Bakanlar Kurulu Kararı kapsamında transitine izin verilen serbest dolaşımda bulunmayan ham petrol, nafta, fuel-oil, gazyağı, benzin, motorin ve jet yakıtın Türkiye Cumhuriyeti Gümrük Bölgesinde karayolu veya demiryolu ile transitinde uyulacak usul ve esasları belirlemektir. Bu yedi ürünlük liste kapalıdır; sıvılaştırılmış petrol gazı (LPG) listede yer almaz. LPG ifadesi Tebliğde yalnızca, temin edilecek fuel-oilin transitinde taşıyıcı ve sürücü hükümlerinin uygulanacağını belirten hükümde 5307 sayılı Sıvılaştırılmış Petrol Gazları (LPG) Piyasası Kanunu'nun adı içinde geçer. En güçlü çeldirici fuel-oil şıkkıdır: fuel-oil, faaliyet süresi ve sermaye şartını düzenleyen izin ön koşulu ile ön izin başvurusuna ilişkin hükümdeki ürün sayımlarında geçmese de Tebliğin amaç ve kapsamında açıkça sayılmıştır. Bu nedenle doğru cevap 'Sıvılaştırılmış petrol gazı (LPG)' seçeneğidir. (MD 1, 4)",
kanit="22-SERİ NO 3.txt | transitine izin verilen serbest dolaşımda bulunmayan ham petrol, nafta, fuel-oil, gazyağı,[1] benzin, motorin ve jet yakıtın Türkiye Cumhuriyeti Gümrük Bölgesinde karayolu veya demiryolu ile transitinde uyulacak usul ve esasları belirlemektir || 22-SERİ NO 3.txt | 5307 sayılı Sıvılaştırılmış Petrol Gazları (LPG) Piyasası Kanunu",
yuva=["Amaç ve kapsam hükmündeki ürün listesi: nafta",
      "Amaç ve kapsam hükmündeki ürün listesi: fuel-oil (sermaye şartı ve ön izin hükümlerindeki sayımlarda geçmez, amaç hükmünde vardır)",
      "Amaç ve kapsam hükmündeki ürün listesi: gazyağı",
      "Amaç ve kapsam hükmündeki ürün listesi: jet yakıtı"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 2 — md 2: Tebliğin dayanağı (dayanak ↔ tanımda anılan kanunlar)
dict(
konu=K, blok="SB21",
kalip="DAYANAK", z="O",
madde=T + " md. 2, 3",
cek="Tebliğ Gümrük Kanunu, Bakanlık teşkilat KHK'si ve 2011/2033 sayılı BKK'ya dayanır; kaçakçılık, LPG kanunları ve Seri No: 2 dayanak değildir.",
kok=[T + "'ün hazırlanmasında dayanılan düzenlemeler arasında aşağıdakilerden hangisi yer almaktadır?"],
d="Gümrük ve Ticaret Bakanlığının Teşkilat ve Görevleri Hakkında Kanun Hükmünde Kararname",
c=["Petrol Piyasası Kanunu",
   "Kaçakçılıkla Mücadele Kanunu",
   "Gümrük Genel Tebliği (Transit Rejimi Seri No: 2)",
   "Sıvılaştırılmış Petrol Gazları (LPG) Piyasası Kanunu ve Elektrik Piyasası Kanununda Değişiklik Yapılmasına Dair Kanun"],
sirali=False,
g="Tebliğ; 4458 sayılı Gümrük Kanunu'nun ilgili maddeleri, 640 sayılı Gümrük ve Ticaret Bakanlığının Teşkilat ve Görevleri Hakkında Kanun Hükmünde Kararname ile 2011/2033 sayılı Bakanlar Kurulu Kararına dayanılarak hazırlanmıştır. Diğer seçeneklerdeki düzenlemeler de Tebliğde anılır, ancak dayanak olarak değil: 5015 sayılı Petrol Piyasası Kanunu ile 5607 sayılı Kaçakçılıkla Mücadele Kanunu 'kaçakçılık' tanımında, 5307 sayılı Sıvılaştırılmış Petrol Gazları (LPG) Piyasası Kanunu fuel-oilin transitine ilişkin hükümde geçer; Gümrük Genel Tebliği (Transit Rejimi Seri No: 2) ise bu Tebliğle yürürlükten kaldırılan tebliğdir. En güçlü çeldirici Kaçakçılıkla Mücadele Kanunu'dur: Tebliğ bu Kanuna yalnızca kaçakçılık suçlarını belirlemek için atıf yapar. Bu nedenle doğru cevap 'Gümrük ve Ticaret Bakanlığının Teşkilat ve Görevleri Hakkında Kanun Hükmünde Kararname' seçeneğidir. (MD 2, 3, 15)",
kanit="22-SERİ NO 3.txt | 640 sayılı Gümrük ve Ticaret Bakanlığının Teşkilat ve Görevleri Hakkında Kanun Hükmünde Kararnamenin 2 nci maddesi ile 2011/2033 sayılı Bakanlar Kurulu Kararına dayanılarak hazırlanmıştır || 22-SERİ NO 3.txt | 5015 sayılı Petrol Piyasası Kanunu ile 21/3/2007 tarihli ve 5607 sayılı Kaçakçılıkla Mücadele Kanununda belirtilen kaçakçılık suçlarını || 22-SERİ NO 3.txt | Gümrük Genel Tebliği (Transit Rejimi Seri No:2) yürürlükten kaldırılmıştır || 22-SERİ NO 3.txt | 5307 sayılı Sıvılaştırılmış Petrol Gazları (LPG) Piyasası Kanunu ve Elektrik Piyasası Kanununda Değişiklik Yapılmasına Dair Kanunun",
yuva=["Tanımlar: 'kaçakçılık' tanımında anılan 5015 sayılı Petrol Piyasası Kanunu",
      "Tanımlar: 'kaçakçılık' tanımında anılan 5607 sayılı Kaçakçılıkla Mücadele Kanunu",
      "Yürürlükten kaldırılan tebliğ: Transit Rejimi Seri No: 2 bu Tebliğle kaldırılmıştır",
      "İzin ön koşulları: 5307 sayılı Kanun kapsamında temin edilecek fuel-oilin transitinde taşıyıcı ve sürücü hükümlerinin uygulanması"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 3 — md 3: macun tanımı (tanımdan ad; macun ↔ macun tahlili)
dict(
konu=K, blok="SB21",
kalip="TANIM", z="K",
madde=T + " md. 3",
cek="Macun, petrol ürünlerindeki farklı eşyanın varlığını ve seviyesini renk değişimiyle tespit eden üründür; macun tahlili bu ürünle yapılan belirleme yöntemidir.",
kok=[T + "'te \"ham petrol ve her türlü akaryakıt, mineral yağlar ve hidrokarbonlar gibi petrol ürünleri içindeki farklı eşyanın varlığını ve seviyesini renk değişimi ile tespit eden özel bir ürün\" olarak tanımlanan kavram aşağıdakilerden hangisidir?"],
d="Macun",
c=["Macun tahlili", "Analiz raporu", "Numune", "Tartı fişi"],
sirali=False,
g="Tebliğde macun, ham petrol ve her türlü akaryakıt, mineral yağlar ve hidrokarbonlar gibi petrol ürünleri içindeki farklı eşyanın varlığını ve seviyesini renk değişimi ile tespit eden özel bir ürün olarak tanımlanır. En güçlü çeldirici macun tahlilidir: macun tahlili bir ürün değil, macun kullanılmak suretiyle ham petrol veya akaryakıtın içinde farklı bir eşya olup olmadığının belirlenmesi yöntemidir. Analiz raporu ve tartı fişi hareket gümrük idaresinde transit beyannamesine eklenen belgeler, numune ise şüphe hâlinde tahlile gönderilmek üzere eşyadan alınan örnektir. Bu nedenle doğru cevap 'Macun' seçeneğidir. (MD 3, 10)",
kanit="22-SERİ NO 3.txt | Macun: Ham petrol ve her türlü akaryakıt, mineral yağlar ve hidrokarbonlar gibi petrol ürünleri içindeki farklı eşyanın varlığını ve seviyesini renk değişimi ile tespit eden özel bir ürünü || 22-SERİ NO 3.txt | Macun tahlili: Macun kullanılmak suretiyle ham petrol veya akaryakıtın içerisinde farklı bir eşya olup olmadığının belirlenmesi yöntemini",
yuva=["Tanımlar: macun tahlili (ürün değil, belirleme yöntemi)",
      "Alınacak önlemler: mahreç ülkesinden alınmış analiz raporu ve antrepodaki eşyanın analiz raporu",
      "Alınacak önlemler: şüphe hâlinde alınarak tahlile gönderilen numune",
      "Alınacak önlemler: transit beyannamesine eklenen tartı fişi"],
yakinlik="BİREBİR",
tuzak=["TERİM"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 4 — md 3: taşıyıcı firma tanımı (R2 / C2-L2 / demiryolu)
dict(
konu=K, blok="SB21",
kalip="TANIM", z="Z",
madde=T + " md. 3",
cek="Taşıyıcı firma: karayolunda R2'de taşıma işleri organizatörü, C2/L2'de belge sahibi firma; demiryolunda tren işletmecisi.",
kok=[T + "'te yer alan \"taşıyıcı firma\" tanımına ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Karayolunda taşımanın R2 yetki belgesi kapsamında yapılması hâlinde taşıyıcı firma, R2 yetki belgesi sahibi taşıma işleri organizatörüdür.",
c=["Karayolunda taşımanın R2 yetki belgesi kapsamında yapılması hâlinde taşıyıcı firma, taşımada kullanılan aracın kayıtlı olduğu C2 veya L2 yetki belgesi sahibi firmadır.",
   "Karayolunda taşımanın C2 veya L2 yetki belgesi kapsamında yapılması hâlinde taşıyıcı firma, taşıma işleri organizatörüdür.",
   "Demiryolunda taşıyıcı firma, demiryolu altyapı işletmecisidir.",
   "Demiryolunda taşıyıcı firma, Tebliğ kapsamında izin verilen izin sahibi firmadır."],
sirali=False,
g="Tebliğde taşıyıcı firma, taşıma yoluna ve yetki belgesinin türüne göre ayrı ayrı tanımlanır: karayolunda taşımanın R2 yetki belgesi kapsamında yapılması hâlinde R2 yetki belgesi sahibi taşıma işleri organizatörü; C2 veya L2 yetki belgesi kapsamında yapılması hâlinde C2 veya L2 yetki belgesi sahibi firma; demiryolunda ise demiryolu tren işletmecisi taşıyıcı firmadır. En güçlü çeldirici, R2 kapsamındaki taşımada aracın kayıtlı olduğu C2 veya L2 belgesi sahibini taşıyıcı sayan seçenektir: C2 veya L2 belgesi sahibi firma ancak taşıma bu belgeler kapsamında yapıldığında taşıyıcı firmadır. Demiryolunda taşıyıcı, altyapı işletmecisi değil tren işletmecisidir; izin sahibi firma ise Tebliğde taşıyıcı firmadan ayrı bir taraf olarak düzenlenir. Bu nedenle doğru cevap 'Karayolunda taşımanın R2 yetki belgesi kapsamında yapılması hâlinde taşıyıcı firma, R2 yetki belgesi sahibi taşıma işleri organizatörüdür.' seçeneğidir. (MD 3, 11)",
kanit="22-SERİ NO 3.txt | Taşıyıcı firma: Karayolunda; taşımanın R2 yetki belgesi kapsamında yapılması halinde, R2 yetki belgesi sahibi taşıma işleri organizatörünü; taşımanın C2 veya L2 yetki belgesi kapsamında yapılması halinde ise C2 veya L2 yetki belgesi sahibi firmayı, demiryolunda demiryolu tren işletmecisini",
yuva=["Aynı tanımın C2 veya L2 ayağı, R2 hâline taşınmış",
      "Aynı tanımın R2 ayağı (taşıma işleri organizatörü), C2 veya L2 hâline taşınmış",
      "Aynı tanımın demiryolu ayağı: 'tren işletmecisi' yerine 'altyapı' (altyapı ifadesi izin sahibinin araç takip sistemi giderlerine ilişkin hükümde geçer)",
      "İzin sahibi firmanın yükümlülükleri: izin sahibi firma taşıyıcı firmadan ayrı taraftır"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 5 — md 4/1: faaliyet süresi ve ödenmiş sermaye (iki bilgi, sıralı)
dict(
konu=K, blok="SB21",
kalip="ORAN-TUTAR", z="O",
madde=T + " md. 4",
cek="İzin başvurusunda bulunacak firma en az bir senedir faaliyette olmalı, ödenmiş sermayesi en az 4.000.000 TL olmalıdır.",
kok=[T + "'e göre ham petrol, benzin, nafta, gazyağı, motorin ve jet yakıtının karayolu ve demiryolu ile transitini yapmak üzere izin başvurusunda bulunacak firmaların en az ne kadar süredir faaliyette bulunması ve Türkiye'de yerleşik ve Türk Ticaret Siciline kayıtlı ödenmiş sermayesinin en az ne kadar olması gerekir?"],
d="Bir yıl – 4.000.000 TL",
c=["Bir yıl – 2.000.000 TL", "Bir yıl – 3.000.000 TL", "Üç yıl – 4.000.000 TL", "Üç yıl – 10.000.000 TL"],
sirali=True,
siklar=["Bir yıl – 2.000.000 TL", "Bir yıl – 3.000.000 TL", "Bir yıl – 4.000.000 TL", "Üç yıl – 4.000.000 TL", "Üç yıl – 10.000.000 TL"],
g="Tebliğe göre ham petrol, benzin, nafta, gazyağı, motorin ve jet yakıtının karayolu ve demiryolu ile transitini yapmak üzere izin başvurusunda bulunacak firmaların en az bir senedir faaliyette bulunması ve Türkiye'de yerleşik, Türk Ticaret Siciline kayıtlı ödenmiş sermayesinin en az 4.000.000 TL olması gerekir. En güçlü çeldiriciler üç yıl içeren seçeneklerdir: asgari üç yıl faaliyet ve bölgelere göre 10.000.000 TL'den başlayan ödenmiş sermaye, Gümrük Yönetmeliği'nde antrepo yatırım izni için aranan şartlardır. 2.000.000 TL ve 3.000.000 TL ise sermaye şartı değil, gümrüksüz satış mağazaları ile antrepolar için öngörülen götürü teminat tutarlarıdır. Bu nedenle doğru cevap 'Bir yıl – 4.000.000 TL' seçeneğidir. (MD 4)",
kanit="22-SERİ NO 3.txt | izin başvurusunda bulunacak firmaların en az bir senedir faaliyette bulunması, Türkiye'de yerleşik ve Türk Ticaret Siciline kayıtlı ödenmiş sermayesinin en az 4.000.000 TL olması gerekir || 29-iŞLETİCİLER.txt | asgari üç yıldır faaliyette bulunan || 29-iŞLETİCİLER.txt | 5. ve 6. Bölge kapsamındaki iller için 10.000.000 TL || 29-iŞLETİCİLER.txt | 1.000 m² veya 2.000 m³'e kadar olanlar için 3.000.000[128] TL || 30-Güm.Sat.Mağazaları.txt | Mağaza ve depo başına alınacak götürü teminat miktarı, tütün, tütün mamulleri ve alkollü içki satışı yapan mağazalar için 5.000.000 TL, diğerleri için 2.000.000 TL dir",
yuva=["Gümrüksüz satış mağazalarında tütün ve alkol dışı mağaza ve depo başına götürü teminat (2.000.000 TL)",
      "Gümrük Yönetmeliği: 1.000 m² veya 2.000 m³'e kadar antrepo için götürü teminat (3.000.000 TL)",
      "Gümrük Yönetmeliği: antrepo yatırım izninde asgari üç yıl faaliyet şartı, Tebliğdeki sermaye ile birleştirilmiş",
      "Gümrük Yönetmeliği: antrepo yatırım izninde üç yıl faaliyet ve 5.-6. bölge illeri için 10.000.000 TL ödenmiş sermaye"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 6 — md 4/4: karayolu araçlarında aranan nitelikler (liste dışı, sağduyu)
dict(
konu=K, blok="SB21",
kalip="KAPSAM_DIŞI", z="O",
madde=T + " md. 4, 10",
cek="Karayolu araçları tehlikeli eşyaya uygun, Türk plakalı, dijital takograflı, araç takip sistemli ve muayeneli olmalı; izin sahibinin mülkiyeti aranmaz.",
kok=[T + "'e göre Irak'a yapılacak benzin, gazyağı, motorin ve jet yakıtı sevkiyatlarında, Tebliğ kapsamındaki ürünlerin karayoluyla taşınmasında kullanılacak araçlarda aranan nitelikler arasında aşağıdakilerden hangisi yer almaz?"],
d="İzin sahibi firmanın mülkiyetinde bulunması",
c=["Karayolu ile tehlikeli eşya taşınmasına uygun ve Türk plakalı olması",
   "Sayısal (dijital) takograf donanımlı olması",
   "Araç takip sistemini haiz olması",
   "2918 sayılı Karayolları Trafik Kanunu uyarınca muayenelerinin yapılmış olması"],
sirali=False,
g="Tebliğe göre Tebliğ kapsamındaki ürünlerin karayoluyla taşınması; karayolu ile tehlikeli eşya taşınmasına uygun, Türk plakalı, sayısal (dijital) takograf donanımlı, araç takip sistemini haiz ve 2918 sayılı Karayolları Trafik Kanunu uyarınca muayeneleri yapılmış araçlarla yapılır. Aracın izin sahibi firmanın mülkiyetinde bulunması bu nitelikler arasında sayılmamıştır; hareket gümrük idaresi de Türk plakalı araçlarda yalnızca aracın taşıyıcı veya alt nakliye firmasının yetki belgesinde kayıtlı olup olmadığını kontrol eder. Mülkiyet şartı, mantıklı görünen ama listede bulunmayan bir sağduyu tuzağıdır. Bu nedenle doğru cevap 'İzin sahibi firmanın mülkiyetinde bulunması' seçeneğidir. (MD 4, 10)",
kanit="22-SERİ NO 3.txt | karayolu ile tehlikeli eşya taşınmasına uygun, Türk plakalı, sayısal (dijital) takograf donanımlı, araç takip sistemini haiz ve 13/10/1983 tarihli ve 2918 sayılı Karayolları Trafik Kanunu uyarınca muayeneleri yapılmış araçlarla yapılır || 22-SERİ NO 3.txt | Türk plakalı araçlarda, aracın taşıyıcı veya alt nakliye firmasının yetki belgesinde kayıtlı olup olmadığı",
yuva=["İzin ön koşulları: tehlikeli eşya taşınmasına uygunluk ve Türk plakası (listede)",
      "İzin ön koşulları: sayısal (dijital) takograf (listede)",
      "İzin ön koşulları: araç takip sistemi (listede)",
      "İzin ön koşulları: 2918 sayılı Kanun uyarınca muayene (listede)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 7 — md 4/4, 4/6: Gürcistan–Nahçıvan taşımalarında yabancı plakalı araç (vaka, saklı istisna)
dict(
konu=K, blok="SB21",
kalip="OLAY", z="Z",
madde=T + " md. 4, 10",
cek="Gürcistan–Nahçıvan taşımalarında şartları taşıyan yabancı plakalı araçlar kullanılabilir; muayene aracın kayıtlı olduğu ülkede yapılmış olmalıdır.",
kok=["(A) Lojistik A.Ş., Gürcistan'dan Nahçıvan Özerk Cumhuriyeti'ne Türkiye üzerinden motorin sevkiyatı yapmak üzere " + T + " kapsamında izin almıştır. Firma bu taşımada Azerbaycan plakalı araçları kullanmak istemektedir. Araçlara ilişkin bilgiler şunlardır:",
     "- Araçlar karayolu ile tehlikeli eşya taşınmasına uygundur.",
     "- Araçlar sayısal (dijital) takograf donanımlıdır ve araç takip sistemini haizdir.",
     "- Araçların muayenesi, kayıtlı oldukları ülkede usulüne uygun olarak yapılmıştır.",
     "Buna göre Tebliğ hükümleri çerçevesinde aşağıdakilerden hangisi doğrudur?"],
d="Araçların yabancı plakalı olması, taşımanın bu araçlarla yapılmasına engel değildir.",
c=["Tebliğ kapsamındaki ürünlerin karayoluyla taşınması Türk plakalı araçlarla yapılacağından taşıma bu araçlarla yapılamaz.",
   "Yabancı plakalı araç kullanılabilmesi için sözleşmenin Gürcistan'da yetkili Bakanlıkça imzalanmış olması gerekir.",
   "Yabancı plakalı araçlar yalnızca Irak'tan yapılacak ham petrol ve nafta sevkiyatlarında kullanılabileceğinden taşıma bu araçlarla yapılamaz.",
   "Yabancı plakalı araçla taşıma yapılabilmesi için Bakanlıkça ek güvenlik tedbirleri alınmış olması zorunludur."],
sirali=False,
g="Tebliğe göre Tebliğ kapsamındaki ürünlerin karayoluyla taşınması kural olarak Türk plakalı ve 2918 sayılı Karayolları Trafik Kanunu uyarınca muayeneleri yapılmış araçlarla yapılır. Ancak Gürcistan'dan Nahçıvan Özerk Cumhuriyeti'ne Türkiye üzerinden yapılacak taşımalarda yabancı plakalı araçlar da kullanılabilir; bu durumda aracın karayolu ile tehlikeli eşya taşınmasına uygun, sayısal (dijital) takograf donanımlı, araç takip sistemini haiz ve kayıtlı olduğu ülkede usulüne uygun muayenesi yapılmış olması aranır. Vakadaki araçlar bu şartların tamamını taşıdığından yabancı plakalı olmaları taşımaya engel değildir. En güçlü çeldirici Türk plakası şartını ileri süren seçenektir: bu şart genel kuraldır ve Gürcistan–Nahçıvan taşımaları için istisna getirilmiştir. Bu sevkiyatlara ilişkin sözleşmelerde yetkili Bakanlık veya Bakanlıkça yetki verilmiş kişilerce imzalanmış olma şartı da aranmaz; Bakanlığın ek güvenlik tedbirleri alması ise bir şart değil, gerekli gördüğü takdirde kullanabileceği bir yetkidir. Bu nedenle doğru cevap 'Araçların yabancı plakalı olması, taşımanın bu araçlarla yapılmasına engel değildir.' seçeneğidir. (MD 4, 10)",
kanit="22-SERİ NO 3.txt | Gürcistan'dan Nahçıvan Özerk Cumhuriyeti'ne Türkiye üzerinden yapılacak taşımalarda, yabancı plakalı araçlar da kullanılabilir. Bu durumda, aracın karayolu ile tehlikeli eşya taşınmasına uygun, sayısal (dijital) takograf donanımlı, araç takip sistemini haiz ve kayıtlı olduğu ülkede usulüne uygun muayenesi yapılmış olması şartı aranır. || 22-SERİ NO 3.txt | imzalanmış olma şartı aranmaz || 22-SERİ NO 3.txt | Bakanlık gerekli gördüğü takdirde mevcut sistemlere ilaveten ek güvenlik tedbirleri almaya yetkilidir",
yuva=["İzin ön koşulları: karayolu taşımalarında Türk plakası genel kuralı (Nahçıvan istisnası gözden kaçırılmış)",
      "İzin ön koşulları: Gürcistan–Nahçıvan sözleşmelerinde yetkili Bakanlık imzası şartı aranmaz (tersine çevrilmiş)",
      "İzin ön koşulları: Irak'tan ham petrol ve nafta sevkiyatına ilişkin sözleşme hükmü, plaka istisnasına taşınmış",
      "Alınacak önlemler: Bakanlığın gerekli gördüğünde ek güvenlik tedbiri alma yetkisi, şarta dönüştürülmüş"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[1],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 8 — md 4: izin ön koşulları (tek kelime değişikliği: devir ve temlik)
dict(
konu=K, blok="SB21",
kalip="YANLIŞ", z="O",
madde=T + " md. 4, 8",
cek="İzinlerin devir ve temlikine dair müracaatlar değerlendirmeye alınmaz; ön koşul taşıyan devralan firma bulunması sonucu değiştirmez.",
kok=[T + "'te düzenlenen izin ön koşullarına ilişkin aşağıdaki ifadelerden hangisi yanlıştır?"],
d="Verilen izinlerin devir ve temlikine dair müracaatlar, devralacak firmanın izin ön koşullarını taşıması hâlinde değerlendirmeye alınır.",
c=["Irak'tan Türkiye'ye yapılacak ham petrol ve nafta sevkiyatlarına ilişkin sözleşmenin, Irak'ta yetkili Bakanlık veya Bakanlıkça sözleşme yapma izni verilen kişiler tarafından imzalanması şarttır.",
   "Irak ile yapılacak sevkiyatlara ilişkin sözleşmede, izin sahibi firmanın söz konusu eşyanın sevkiyatının Türkiye üzerinden yapılacak olduğunun, eşya miktarının ve türünün belirtilmesi gerekir.",
   "Transiti yapacak izin sahibi ve/veya taşıyıcı firmanın, ticarete konu eşya türüne uygun ilgili kurumlardan mevzuatları gereğince alınmış izin, ruhsat, lisans ve/veya yetki belgesi sahibi olması gerekir.",
   "5307 sayılı Sıvılaştırılmış Petrol Gazları (LPG) Piyasası Kanunu ve Elektrik Piyasası Kanununda Değişiklik Yapılmasına Dair Kanunun geçici maddesi kapsamında temin edilecek fuel-oilin transiti için Tebliğin taşıyıcı ve sürücülere ilişkin hükümleri uygulanır."],
sirali=False,
g="Tebliğe göre verilen izinlerin devir ve temlikine dair müracaatlar değerlendirmeye alınmaz; izinlerin üçüncü kişilere devredildiğinin tespiti ise verilmiş izinlerin askıya alınması ve yeni izin başvurularının reddedilmesi sonucunu doğurur. Devralacak firmanın ön koşulları taşıması bu sonucu değiştirmez. Diğer ifadeler metinle aynıdır: Irak'tan yapılacak ham petrol ve nafta sevkiyatlarına ilişkin sözleşmenin Irak'ta yetkili Bakanlık veya sözleşme yapma izni verilen kişilerce imzalanması şarttır; sözleşmede sevkiyatın Türkiye üzerinden yapılacağı, eşya miktarı ve türü belirtilir; izin sahibi ve/veya taşıyıcı firmanın eşya türüne uygun izin, ruhsat, lisans veya yetki belgesi bulunmalıdır; 5307 sayılı Kanunun geçici maddesi kapsamında temin edilecek fuel-oilin transitinde Tebliğin taşıyıcı ve sürücü hükümleri uygulanır. Bu nedenle doğru cevap 'Verilen izinlerin devir ve temlikine dair müracaatlar, devralacak firmanın izin ön koşullarını taşıması hâlinde değerlendirmeye alınır.' seçeneğidir. (MD 4, 8)",
kanit="22-SERİ NO 3.txt | Verilen izinlerin devir ve temlikine dair müracaatlar değerlendirmeye alınmaz. || 22-SERİ NO 3.txt | verilen izinlerin üçüncü kişilere devredildiğinin || 22-SERİ NO 3.txt | Irak'tan ülkemize yapılacak ham petrol ve nafta sevkiyatları ile ilgili sözleşmenin, Türkiye üzerinden transit edilmek üzere Irak'ta yetkili Bakanlık veya Bakanlıkça bu Tebliğ kapsamdaki taşımalara ilişkin olarak sözleşme yapma izni verilen kişiler tarafından imzalanması şarttır || 22-SERİ NO 3.txt | Sözleşmede izin sahibi firmanın söz konusu eşyanın sevkiyatının Türkiye üzerinden yapılacak olduğunun, eşya miktarının ve türünün belirtilmesi gerekir. || 22-SERİ NO 3.txt | ticarete konu eşya türüne uygun ilgili kurumlardan mevzuatları gereğince alınmış izin, ruhsat, lisans ve/veya yetki belgesi sahibi olması gerekir || 22-SERİ NO 3.txt | kapsamında temin edilecek olan fuel-oilin transiti için bu Tebliğin taşıyıcı ve sürücülere ilişkin hükümleri uygulanır",
yuva=["İzin ön koşulları: Irak sözleşmesinin yetkili Bakanlıkça imzalanması (doğru ifade)",
      "İzin ön koşulları: sözleşmede Türkiye üzerinden sevkiyat, miktar ve tür (doğru ifade)",
      "İzin ön koşulları: izin, ruhsat, lisans ve/veya yetki belgesi (doğru ifade)",
      "İzin ön koşulları: 5307 sayılı Kanun kapsamındaki fuel-oil (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "ŞART"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 9 — md 5/2: sözleşmenin ön izin formuna eklenme şekli (meslek yanlılığı)
dict(
konu=K, blok="SB21",
kalip="BELGE", z="O",
madde=T + " md. 5",
cek="Ön izin başvurusunda sözleşmenin ve yeminli tercümesinin noter tasdikli suretleri eklenir; gümrük müşaviri onayı öngörülmez.",
kok=[T + "'e göre transiti yapacak firmanın Bakanlığa (Gümrükler Genel Müdürlüğü) yapacağı ön izin başvurusunda, imzalanmış sözleşme ön izin başvuru formuna hangi şekilde eklenir?"],
d="Sözleşmenin ve yeminli tercüman tarafından yapılmış tercümesinin noter tasdikli suretleri eklenir.",
c=["Sözleşmenin ve tercümesinin, başvuruyu takip eden gümrük müşavirince aslının aynı olduğu onaylanmış suretleri eklenir.",
   "Sözleşmenin aslı ile Irak'ta yetkili Bakanlıkça onaylanmış Türkçe tercümesi eklenir.",
   "Sözleşmenin Büyükelçilik kanalıyla Bakanlığa bildirilmiş onaylı örneği eklenir.",
   "Sözleşmenin aslı ile mahreç ülkesinden alınmış Türkçe tercümesi eklenir."],
sirali=False,
g="Tebliğe göre ön izin başvurusunda imzalanmış sözleşmenin ve yeminli tercüman tarafından yapılmış tercümesinin noter tasdikli suretleri ön izin başvuru formuna eklenir. Sözleşme, Irak'ta yetkili Bakanlıkça sözleşme yapma izni verilen kişilerle yapılmışsa bu yetkinin verildiğine ilişkin belgenin de yeminli tercümesiyle birlikte noter tasdikli sureti eklenir. Tebliğ bu belgeler için gümrük müşaviri onayına yer vermez; aranan şekil noter tasdikidir. Büyükelçilik kanalı yalnızca askeri güçlerle imzalanan sözleşmelerin Bakanlığa bildirilmesinde, mahreç ülkesinden alınan Türkçe tercüme ise hareket gümrük idaresinde transit beyannamesine eklenen analiz raporunda geçer. Bu nedenle doğru cevap 'Sözleşmenin ve yeminli tercüman tarafından yapılmış tercümesinin noter tasdikli suretleri eklenir.' seçeneğidir. (MD 5, 10, 12)",
kanit="22-SERİ NO 3.txt | İmzalanmış sözleşmenin ve yeminli tercüman tarafından yapılmış tercümesinin noter tasdikli suretleri ön izin başvuru formuna eklenir. || 22-SERİ NO 3.txt | bu yetkinin verildiğine ilişkin belgenin yeminli tercüman tarafından yapılmış tercümesi ile birlikte noter tasdikli sureti de ön izin başvuru formuna eklenir || 22-SERİ NO 3.txt | askeri güçler ile imzalanan sözleşmenin Büyükelçilik kanalı ile Bakanlığa (Gümrükler Genel Müdürlüğü) bildirilmiş olması gerekir || 22-SERİ NO 3.txt | Mahreç ülkesinden alınmış analiz raporu ve Türkçe tercümesi ile tartı fişi transit beyannamesine eklenir",
yuva=["Uydurma (meslek yanlılığı): Tebliğde gümrük müşavirine onay rolü verilmez; noter tasdiki aranır",
      "Ön izin başvurusu: Irak'ta yetkili Bakanlıkça verilen sözleşme yapma yetkisine ilişkin belge (onay değil yetki belgesi)",
      "Askeri güçlere yapılacak sevkiyatlar: sözleşmenin Büyükelçilik kanalıyla Bakanlığa bildirilmesi",
      "Alınacak önlemler: mahreç ülkesinden alınmış analiz raporu ve Türkçe tercümesi"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU", "SAĞDUYU"],
duzey=["HATIRLAMA"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 10 — md 5, 6: ön izin ve izin başvuruları (tek kayıt değişikliği: ret sonucuna süre eklenmiş)
dict(
konu=K, blok="SB21",
kalip="YANLIŞ", z="O",
madde=T + " md. 4, 5, 6",
cek="Ön izin Ek-1 formla GGM'ye yapılır; adli takibatta aynı/benzer ön izinler reddedilir; reddedilen izin başvurusu yapamaz; demiryolunda taşıyıcı belgeleri aranmaz.",
kok=[T + "'te düzenlenen ön izin ve izin başvurularına ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Ön izin başvurusu reddedilen firma, ret tarihinden itibaren bir yıl geçtikten sonra izin başvurusunda bulunabilir.",
c=["Ön izin başvurusu, Bakanlığa (Gümrükler Genel Müdürlüğü) örneği Ek-1'de yer alan form ile yapılır.",
   "Ön izin başvurusunda adli takibatı devam eden bir hususa rastlanılması hâlinde, adli makamlarca değerlendirme sonuçlanıncaya kadar firmanın aynı veya benzer konuya ilişkin ön izin başvuruları reddedilir.",
   "İzin başvurusu, Ek-2'de sayılan belgeler ve Ek-3'te yer alan taahhütname ile Bakanlığa (Gümrükler Genel Müdürlüğü) yapılır.",
   "Demiryoluyla taşımada, izin başvurusunda Ek-2'de sayılan belgelerden taşıyıcıya ilişkin belgeler aranmaz."],
sirali=False,
g="Tebliğe göre ön izin başvurularının kabul edilip edilmediği başvuru sahibine bildirilir ve ön izin başvurusu reddedilen firmalar izin başvurusunda bulunamaz. Tebliğ bu engel için bir bekleme süresi öngörmez; ret, izin başvurusunun yolunu kapatan bir sonuçtur. Bir yıl ise izin başvurusunda bulunacak firmanın en az ne kadar süredir faaliyette olması gerektiğini gösteren izin ön koşuludur. Diğer ifadeler metinle aynıdır: ön izin başvurusu Bakanlığa (Gümrükler Genel Müdürlüğü) Ek-1'deki form ile yapılır; adli takibatı devam eden bir hususa rastlanırsa adli makamların değerlendirmesi sonuçlanıncaya kadar firmanın aynı veya benzer konudaki ön izin başvuruları reddedilir; izin başvurusu Ek-2'deki belgeler ve Ek-3'teki taahhütname ile Bakanlığa yapılır; demiryoluyla taşımada Ek-2'deki belgelerden taşıyıcıya ilişkin olanlar aranmaz. En güçlü çeldirici demiryolu istisnasıdır: Ek-2'deki belgelerin her taşımada eksiksiz arandığını sanan aday bu doğru ifadeyi yanlış sayar. Bu nedenle doğru cevap 'Ön izin başvurusu reddedilen firma, ret tarihinden itibaren bir yıl geçtikten sonra izin başvurusunda bulunabilir.' seçeneğidir. (MD 4, 5, 6)",
kanit="22-SERİ NO 3.txt | Ön izin başvurusu reddedilen firmalar izin başvurusunda bulunamaz. || 22-SERİ NO 3.txt | Bakanlığa (Gümrükler Genel Müdürlüğü) örneği Ek-1'de yer alan form ile ön izin başvurusunda bulunur || 22-SERİ NO 3.txt | adli makamlarca buna ilişkin değerlendirme sonuçlanıncaya kadar söz konusu firmanın aynı veya benzer konuya ilişkin ön izin başvuruları reddedilir || 22-SERİ NO 3.txt | izin başvurusu Ek-2'de sayılan belgeler ve Ek-3'te yer alan taahhütname ile Bakanlığa (Gümrükler Genel Müdürlüğü) yapılır || 22-SERİ NO 3.txt | Demiryoluyla taşımada ek-2'de sayılan belgelerden taşıyıcıya ilişkin belgeler aranmaz. || 22-SERİ NO 3.txt | en az bir senedir faaliyette bulunması",
yuva=["Ön izin başvurusu: Ek-1 form ile Bakanlığa (GGM) başvuru (doğru ifade)",
      "Ön izin başvurusu: adli takibat hâlinde aynı veya benzer konudaki ön izin başvurularının reddi (doğru ifade)",
      "İzin başvurusunda aranacak bilgi ve belgeler: Ek-2 belgeleri ve Ek-3 taahhütnamesi (doğru ifade)",
      "İzin başvurusunda aranacak bilgi ve belgeler: demiryolunda taşıyıcı belgelerinin aranmaması (doğru ifade)"],
yakinlik="PARAFRAZ",
tuzak=["TERSİNE", "SAYI", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 11 — md 6/3: sürücü listeleri ve adli sicil belgesinin alınma süresi (başlangıç anı)
dict(
konu=K, blok="SB21",
kalip="SÜRE", z="O",
madde=T + " md. 6, 9, Geçici 1",
cek="Sürücü listeleri izni müteakip, teslim tarihinden itibaren son 15 gün içinde alınmış adli sicil belgeleriyle Bakanlığa verilir.",
kok=[T + "'e göre taşımayı gerçekleştirecek sürücülerin bilgilerini içeren listelerle birlikte Bakanlığa verilecek, \"herhangi bir adli sicil ve arşiv kaydının bulunmadığına dair\" adli sicil belgelerinin hangi süre içinde alınmış olması gerekir?"],
d="Listelerin teslim tarihinden itibaren son 15 gün içerisinde",
c=["Listelerin teslim tarihinden itibaren son 10 gün içerisinde",
   "İzin başvurusunun yapıldığı tarihten itibaren son 15 gün içerisinde",
   "Ön izin başvurusunun kabulünün bildirildiği tarihten itibaren son 15 gün içerisinde",
   "Listelerin teslim tarihinden itibaren son 2 ay içerisinde"],
sirali=False,
g="Tebliğe göre taşımayı gerçekleştirecek sürücülerin adı, soyadı, T.C. Kimlik Numaraları, anne ve baba adları ile doğum yeri ve tarihi bilgilerinin kayıtlı olduğu liste ve bu listelerdeki değişiklikler, izin alınmasını müteakip, listelerin teslim tarihinden itibaren son 15 gün içerisinde alınmış adli sicil belgeleri ile birlikte Bakanlığa verilir. Süre, izin veya ön izin başvurusunun tarihinden değil, listelerin teslim tarihinden geriye doğru hesaplanır; sürücü listeleri zaten izin başvurusuyla birlikte değil, izin alındıktan sonra verilir. On gün, ortaklık ve yönetimdeki değişikliklere ilişkin Ticaret Sicili Gazetesi örneğinin gönderilme süresidir; 2 ay ise Tebliğden önce verilmiş izinler kapsamında taşıma yapan araçların yeni şartlara uygun hâle getirilme süresidir. Bu nedenle doğru cevap 'Listelerin teslim tarihinden itibaren son 15 gün içerisinde' seçeneğidir. (MD 6, 9, Geçici 1)",
kanit="22-SERİ NO 3.txt | alınacak izni müteakip, anılan listelerin teslim tarihinden itibaren son 15 gün içerisinde alınmış \"herhangi bir adli sicil ve arşiv kaydının bulunmadığına dair\" adli sicil belgeleri ile birlikte Bakanlığa verilir || 22-SERİ NO 3.txt | yayımını takip eden on gün içerisinde Bakanlığa (Gümrükler Genel Müdürlüğü) gönderilmesi gerekir || 22-SERİ NO 3.txt | taşıma yapan araçların 2 ay içerisinde bu Tebliğde belirtilen şartlara uygun hale getirilmesi gerekmektedir",
yuva=["İlave bilgi ve belge ibrazı: Ticaret Sicili Gazetesi örneğinin yayımı takip eden on gün içinde gönderilmesi",
      "İzin başvurusu: başlangıç anı listelerin teslimi yerine izin başvurusuna kaydırılmış (listeler izni müteakip verilir)",
      "Ön izin başvurusu: kabulün başvuru sahibine bildirilmesi, başlangıç anı olarak taşınmış",
      "Mevcut izinler: araçların 2 ay içinde şartlara uygun hâle getirilmesi"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "YAKIN-SAYI"],
duzey=["AYIRT"],
profil=[2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 12 — md 7: izin başvurularının değerlendirilmesi (önermeli, II-IV)
dict(
konu=K, blok="SB21",
kalip="ÖNERMELİ", z="Z",
madde=T + " md. 7",
cek="Kamu düzeni görüşü ilgili kurumlardan, ulaştırma yetkisi görüşü Ulaştırma Bakanlığından alınır; uygun bulunmayan başvuru yalnız başvuru sahibine bildirilir.",
kok=[T + "'e göre izin başvurularının değerlendirilmesine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Başvuru sahibi firmanın ve/veya taşıyıcı firmanın ulaştırma mevzuatı açısından taşımayı yapmaya yetkili olup olmadığı konusunda ilgili gümrük ve ticaret bölge müdürlüğünün görüşü alınır.",
     "II. Nihai değerlendirmeden önce başvuru sahibi firmalar ve taşıyıcı firmalar hakkında, kamu düzeni ve kamu güvenliği yönünden Tebliğdeki işlemleri yapmaya engel bir değerlendirme bulunup bulunmadığına ilişkin ilgili kurumların görüşüne başvurulur.",
     "III. Uygun bulunmayan izin başvuruları, başvuru sahibinin yanı sıra hareket ve varış gümrük idarelerine de bildirilir.",
     "IV. Sürücü listelerinden uygun görülenler, başvuru sahibi ile ilgili hareket ve varış gümrük idarelerine bildirilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve IV",
c=["I ve II", "I ve III", "II ve III", "II, III ve IV"],
sirali=False,
g="Tebliğe göre başvuru sahibi firmalar ve taşıyıcı firmalar hakkında nihai değerlendirme yapılmadan önce, kamu düzeni ve kamu güvenliği yönünden Tebliğde düzenlenen işlemleri yapmaya engel değerlendirmelerin olup olmadığına dair ilgili kurumların görüşü alınır (II doğru). Firmaların ulaştırma mevzuatı açısından taşımayı yapmaya yetkili olup olmadığına ilişkin görüş ise bölge müdürlüğünden değil, Ulaştırma, Denizcilik ve Haberleşme Bakanlığından alınır (I yanlış). Değerlendirme sonucunda uygun bulunan izin başvuruları başvuru sahibine ve hareket/varış gümrük idarelerine bildirilir; uygun bulunmayanlar ise yalnızca başvuru sahibine bildirilir (III yanlış). Sürücü listelerinden uygun görülenler başvuru sahibine ve ilgili hareket ve varış gümrük idarelerine bildirilir (IV doğru). En güçlü tuzak III. önermedir: hareket ve varış idarelerine bildirim yalnızca uygun bulunan başvurular için öngörülmüştür. Bu nedenle doğru cevap 'II ve IV' seçeneğidir. (MD 7)",
kanit="22-SERİ NO 3.txt | kamu düzeni ve kamu güvenliği yönünden bu Tebliğde düzenlenen işlemleri yapmaya engel değerlendirmelerinin olup olmadığına dair ilgili kurumların görüşü alınır || 22-SERİ NO 3.txt | Ulaştırma, Denizcilik ve Haberleşme Bakanlığının görüşü alınır || 22-SERİ NO 3.txt | izin başvurusu uygun bulunanlar, başvuru sahibine ve hareket/varış gümrük idarelerine; izin başvurusu uygun bulunmayanlar ise başvuru sahibine bildirilir || 22-SERİ NO 3.txt | uygun görülenler başvuru sahibine ve ilgili hareket ve varış gümrük idarelerine bildirilir",
yuva=["I ve II: ulaştırma mevzuatı yönünden görüşü bölge müdürlüğünden alınıyor sanan aday (görüş Ulaştırma, Denizcilik ve Haberleşme Bakanlığından alınır)",
      "I ve III: makamı karıştıran ve olumsuz sonucun bildirim muhataplarını genişleten aday",
      "II ve III: uygun bulunanlara ilişkin bildirim hükmünü uygun bulunmayanlara taşıyan aday",
      "II, III ve IV: hareket ve varış idarelerine bildirimin yalnızca uygun bulunanlar için olduğunu gözden kaçıran aday"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 13 — md 8, 9/1: tespit/durum – uygulanacak işlem (eşleştirme; askı ↔ iptal basamakları)
dict(
konu=K, blok="SB21",
kalip="EŞLEŞTİRME", z="Z",
madde=T + " md. 8, 9",
cek="Bilgi-belge ibraz etmeyenin talebi reddedilir veya izni iptal edilir; düzeltilinceye kadar askı yalnız araç takip sistemlerinin üçte birinin izlenememesine özgüdür.",
kok=[T + "'e göre aşağıda verilen tespit veya durumlardan hangisi, bu durumda uygulanacak işlemle yanlış eşleştirilmiştir?"],
d="Bakanlıkça istenen bilgi ve belgelerin ibraz edilmemesi – Durum düzeltilinceye kadar verilmiş izinlerin askıya alınması",
c=["İzin sahibi firmanın ibraz ettiği belgelerin sahte olduğunun tespiti – Verilmiş izinlerin askıya alınması ve yeni izin başvurularının reddedilmesi",
   "Firmanın temsil ve ilzama yetkili yöneticisi hakkında kaçakçılık yapıldığı iddiasıyla dava açılmış olması – Mahkemelerce aksine karar tesis edilinceye kadar izinlerin askıya alınması ve yeni izin başvurularının reddedilmesi",
   "Firmanın sermayesinin yüzde onundan fazlasına sahip gerçek kişi ortağı hakkında kaçakçılıktan kesinleşmiş mahkûmiyet kararı bulunması – İzinlerin iptal edilmesi ve bu tarihten sonraki başvuruların değerlendirmeye alınmaması",
   "Taşıma yapan karayolu araç sürücüsünün araç takip sistemini izlenebilir olmaktan çıkardığının tespiti – Söz konusu sürücünün Tebliğ kapsamında taşıma yapmasına izin verilmemesi"],
sirali=False,
g="Tebliğde yaptırımlar basamaklıdır. Belgelerde tahrifat veya sahtelik, izinlerin üçüncü kişilere devri, taahhütnameye aykırılık ve başvuru şartlarının kaybı hâllerinde verilmiş izinler askıya alınır, yeni izin başvuruları reddedilir. Firma sahibi, sermayesinin yüzde onundan fazlasına sahip gerçek kişi ortağı, yönetim kurulu üyeleri ya da temsil ve ilzama yetkili yöneticilerinden en az biri hakkında kaçakçılık iddiasıyla dava açılmışsa izinler mahkemelerce aksine karar tesis edilinceye kadar askıya alınır; bu kişiler hakkında kaçakçılıktan kesinleşmiş mahkûmiyet kararı varsa izinler iptal edilir ve sonraki başvurular değerlendirmeye alınmaz. Araç takip sistemini izlenebilir olmaktan çıkaran sürücünün taşıma yapmasına izin verilmez. Bakanlıkça istenen bilgi ve belgeleri ibraz etmeyenlerin ise izin talepleri reddedilir veya verilmiş izinleri iptal edilir; 'durum düzeltilinceye kadar askı', araç takip sistemlerinin üçte birinin izlenebilir olmaktan çıkarılması hâline özgü sonuçtur. Bu nedenle doğru cevap 'Bakanlıkça istenen bilgi ve belgelerin ibraz edilmemesi – Durum düzeltilinceye kadar verilmiş izinlerin askıya alınması' seçeneğidir. (MD 8, 9)",
kanit="22-SERİ NO 3.txt | Söz konusu bilgi ve belgeleri ibraz etmeyenlerin izin talepleri reddedilir veya verilmiş izinleri iptal edilir. || 22-SERİ NO 3.txt | araç takip sistemlerinin üçte birinin izlenebilir olmaktan çıkarıldığının tespit edilmesi durumunda söz konusu durum düzeltilinceye kadar firmanın izni askıya alınır || 22-SERİ NO 3.txt | ibraz edilen belgelerin sahte olduğunun || 22-SERİ NO 3.txt | verilmiş izinler askıya alınır, yeni izin başvuruları reddedilir || 22-SERİ NO 3.txt | mahkemelerce aksine karar tesis edilinceye kadar, söz konusu firmaların bu Tebliğ kapsamında verilmiş izinleri askıya alınır || 22-SERİ NO 3.txt | Tebliğ kapsamında verilmiş izinleri iptal edilir. Bu tarihten sonraki başvuruları değerlendirmeye alınmaz. || 22-SERİ NO 3.txt | söz konusu sürücünün bu Tebliğ kapsamında taşıma yapmasına izin verilmez",
yuva=["İznin durdurulması, askıya alınması ve iptali: sahte belge → askı ve yeni başvuruların reddi (doğru eşleşme)",
      "İznin durdurulması, askıya alınması ve iptali: kaçakçılık davası → mahkeme kararına kadar askı (doğru eşleşme)",
      "İznin durdurulması, askıya alınması ve iptali: kesinleşmiş mahkûmiyet → iptal (doğru eşleşme)",
      "İznin durdurulması, askıya alınması ve iptali: sürücüye taşıma yasağı (doğru eşleşme)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 14 — md 8/4-5: araç takip sistemlerinin üçte biri (firma düzeyinde askı ↔ münferit araç)
dict(
konu=K, blok="SB21",
kalip="SONUÇ", z="O",
madde=T + " md. 8",
cek="Araç takip sistemlerinin üçte biri izlenemezse firmanın izni düzeltilinceye kadar askıya alınır; münferit araçta yalnız o aracın taşımasına izin verilmez.",
kok=[T + "'e göre yapılan kontrollerde araç takip sistemlerinin üçte birinin izlenebilir olmaktan çıkarıldığının tespit edilmesi durumunda aşağıdakilerden hangisi uygulanır?"],
d="Durum düzeltilinceye kadar firmanın Tebliğ kapsamında verilmiş izni askıya alınır.",
c=["Durum düzeltilinceye kadar yalnızca söz konusu araçların Tebliğ kapsamında taşıma yapmasına izin verilmez.",
   "Firmanın Tebliğ kapsamında verilmiş izni iptal edilir ve bu tarihten sonraki başvuruları değerlendirmeye alınmaz.",
   "Firmanın izni askıya alınmaksızın söz konusu araçların sürücülerinin Tebliğ kapsamında taşıma yapmasına izin verilmez.",
   "Firmanın izni mahkemelerce aksine karar tesis edilinceye kadar askıya alınır."],
sirali=False,
g="Tebliğe göre yapılan kontrollerde araç takip sistemlerinin üçte birinin izlenebilir olmaktan çıkarıldığının tespit edilmesi durumunda, söz konusu durum düzeltilinceye kadar firmanın izni askıya alınır. Yaptırım firma düzeyindedir ve süresi durumun düzeltilmesine bağlıdır. En güçlü çeldirici yalnızca ilgili araçların taşımasını durduran seçenektir: bu sonuç, münferit bir karayolu aracındaki araç takip sisteminin izlenebilir olmaktan çıkarılması hâline aittir. Sürücüye yönelik taşıma yasağı, araç takip sistemini sürücünün izlenebilir olmaktan çıkardığının tespitine bağlıdır ve firma düzeyindeki askının yerini tutmaz. İznin iptali ve sonraki başvuruların değerlendirmeye alınmaması kaçakçılıktan kesinleşmiş mahkûmiyet kararına, mahkemelerce aksine karar tesis edilinceye kadar askı ise kaçakçılık iddiasıyla dava açılmasına bağlanmıştır. Bu nedenle doğru cevap 'Durum düzeltilinceye kadar firmanın Tebliğ kapsamında verilmiş izni askıya alınır.' seçeneğidir. (MD 8)",
kanit="22-SERİ NO 3.txt | Yapılan kontrollerde araç takip sistemlerinin üçte birinin izlenebilir olmaktan çıkarıldığının tespit edilmesi durumunda söz konusu durum düzeltilinceye kadar firmanın izni askıya alınır. || 22-SERİ NO 3.txt | araç takip sisteminin izlenebilir olmaktan çıkarıldığının tespit edilmesi durumunda söz konusu durum düzeltilinceye kadar söz konusu aracın bu Tebliğ kapsamında tasıma yapmasına izin verilmez || 22-SERİ NO 3.txt | söz konusu sürücünün bu Tebliğ kapsamında taşıma yapmasına izin verilmez || 22-SERİ NO 3.txt | Tebliğ kapsamında verilmiş izinleri iptal edilir. Bu tarihten sonraki başvuruları değerlendirmeye alınmaz. || 22-SERİ NO 3.txt | mahkemelerce aksine karar tesis edilinceye kadar, söz konusu firmaların bu Tebliğ kapsamında verilmiş izinleri askıya alınır",
yuva=["Münferit karayolu aracında araç takip sisteminin izlenemez hâle gelmesi: yalnız o aracın taşıması durdurulur",
      "Kaçakçılıktan kesinleşmiş mahkûmiyet: izinlerin iptali ve sonraki başvuruların değerlendirmeye alınmaması",
      "Sistemi sürücünün izlenebilir olmaktan çıkarması: sürücünün taşıma yapmasına izin verilmez (firma askısının yerine konmuş)",
      "Kaçakçılık iddiasıyla dava açılması: mahkemelerce aksine karar tesis edilinceye kadar askı"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "UNSUR"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 15 — md 9/2: ortak ve yönetici değişikliğinde Ticaret Sicili Gazetesi (süre + başlangıç anı)
dict(
konu=K, blok="SB21",
kalip="SÜRE", z="O",
madde=T + " md. 9",
cek="Ortak ve yönetici değişikliğinde Ticaret Sicili Gazetesi örneği, yayımını takip eden on gün içinde Bakanlığa (GGM) gönderilir.",
kok=[T + "'e göre izin sahibi firma ve taşıyıcı firmaların sahibi, sermayesinin yüzde onundan fazlasına sahip gerçek kişi ortakları ile yönetim kurulu üyeleri ya da temsil ve ilzama yetkili yöneticilerinde değişiklik olması durumunda, değişikliğe ilişkin Ticaret Sicili Gazetesi'nin bir örneği Bakanlığa (Gümrükler Genel Müdürlüğü) hangi süre içinde gönderilmelidir?"],
d="Gazetenin yayımını takip eden on gün içinde",
c=["Gazetenin yayımını takip eden on beş gün içinde",
   "Değişikliğe ilişkin kararın alındığı tarihi takip eden on gün içinde",
   "Değişikliği izleyen takvim yılının Ocak ayı sonuna kadar",
   "Gecikmeksizin"],
sirali=False,
g="Tebliğe göre izin sahibi firma ve taşıyıcı firmaların sahibi, sermayesinin yüzde onundan fazlasına sahip gerçek kişi ortakları ile yönetim kurulu üyeleri ya da temsil ve ilzama yetkili yöneticilerinde değişiklik olursa, değişikliğe ilişkin Ticaret Sicili Gazetesi'nin bir örneği yayımını takip eden on gün içinde Bakanlığa (Gümrükler Genel Müdürlüğü) gönderilir. Süre, değişiklik kararının alındığı tarihten değil, gazetedeki yayımdan başlar. On beş gün, Cumhuriyet Başsavcılığından alınacak adli sicil kaydının alınmış olması gereken süredir ve bu kayıt her takvim yılının Ocak ayı sonuna kadar gönderilir; 'gecikmeksizin' bilgi verme ise merkez ve şube adresleri ile iletişim bilgilerindeki değişikliklere özgüdür. Bu nedenle doğru cevap 'Gazetenin yayımını takip eden on gün içinde' seçeneğidir. (MD 9)",
kanit="22-SERİ NO 3.txt | söz konusu değişikliğe ilişkin Ticaret Sicili Gazetesi'nin bir örneğinin yayımını takip eden on gün içerisinde Bakanlığa (Gümrükler Genel Müdürlüğü) gönderilmesi gerekir || 22-SERİ NO 3.txt | Cumhuriyet Başsavcılığından son onbeş gün içinde alınmış arşiv bilgilerini içerir Adli Sicil Kaydının her takvim yılının Ocak ayı sonuna kadar || 22-SERİ NO 3.txt | gümrük ve ticaret bölge müdürlüklerine gecikmeksizin bilgi verilmesi gerekir",
yuva=["İlave bilgi ve belge ibrazı: adli sicil kaydının son onbeş gün içinde alınmış olması",
      "Başlangıç anı gazetedeki yayımdan değişiklik kararına kaydırılmış (uydurma başlangıç)",
      "İlave bilgi ve belge ibrazı: adli sicil kaydının her takvim yılının Ocak ayı sonuna kadar gönderilmesi",
      "İlave bilgi ve belge ibrazı: merkez ve şube adresi ile iletişim bilgisi değişikliğinde gecikmeksizin bilgi verilmesi"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "YAKIN-SAYI", "KOMŞU"],
duzey=["AYIRT"],
profil=[2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 16 — md 10/2: araç takip sistemi erişim şifresi (makam zinciri)
dict(
konu=K, blok="SB21",
kalip="YETKİ", z="O",
madde=T + " md. 10",
cek="Firma birden fazla kullanıcıya uygun şifreyi hareket idaresine verir; hareket idaresi şifreyi varış idaresine ve güzergâhtaki kolluk birimlerine bildirir.",
kok=[T + "'e göre Türkiye Gümrük Bölgesinde gerçekleştirilecek sevkiyatların, taşımacılık yapacak firmaların kendi filolarında kullandıkları araç takip sistemi vasıtasıyla izlenmesinde sisteme erişim şifresine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Firma şifreyi hareket gümrük idaresine verir; hareket gümrük idaresi şifreyi varış gümrük idaresi ile zorunlu güzergâh üzerindeki kolluk birimlerine bildirir.",
c=["Firma şifreyi varış gümrük idaresine verir; varış gümrük idaresi şifreyi hareket gümrük idaresi ile zorunlu güzergâh üzerindeki kolluk birimlerine bildirir.",
   "Firma şifreyi Bakanlığa (Gümrükler Genel Müdürlüğü) verir; Bakanlık şifreyi hareket ve varış gümrük idarelerine bildirir.",
   "Firma şifreyi hareket gümrük idaresine verir; hareket gümrük idaresi şifreyi ilgili gümrük ve ticaret bölge müdürlüğüne bildirir.",
   "Firma tek kullanıcı erişimine uygun şifreyi zorunlu güzergâh üzerindeki kolluk birimlerine verir; kolluk birimleri şifreyi hareket gümrük idaresine bildirir."],
sirali=False,
g="Tebliğe göre sevkiyatlar, taşımacılık yapacak firmaların kendi filolarında kullandıkları araç takip sistemiyle izlenir. Firma bu taşımalar için sisteminde ayırt edici işaretler oluşturur ve hareket gümrük idaresine birden fazla kullanıcı erişimine uygun şifre verir; hareket gümrük idaresi de bu erişim şifresini varış gümrük idaresi ile zorunlu güzergâh üzerinde bulunan kolluk birimlerine bildirir. En güçlü çeldirici, şifrenin varış gümrük idaresine verildiğini söyleyen seçenektir: şifrenin muhatabı ve dağıtıcısı hareket gümrük idaresidir, varış idaresi bildirimin alıcısıdır. Bakanlığa (Gümrükler Genel Müdürlüğü) ve bölge müdürlüklerine bildirim, firmaya ilişkin ortaklık ve adres değişikliklerinde öngörülür; şifre ise tek değil birden fazla kullanıcı erişimine uygun olmalıdır. Bu nedenle doğru cevap 'Firma şifreyi hareket gümrük idaresine verir; hareket gümrük idaresi şifreyi varış gümrük idaresi ile zorunlu güzergâh üzerindeki kolluk birimlerine bildirir.' seçeneğidir. (MD 9, 10)",
kanit="22-SERİ NO 3.txt | Firma bu Tebliğ kapsamındaki taşımalar için kendi araç takip sisteminde ayırt edici işaretler oluşturur ve hareket gümrük idaresine anılan sistem için birden fazla kullanıcı erişimine uygun şifre verir. Hareket gümrük idaresince anılan erişim şifresi varış gümrük idaresi ile zorunlu güzergâh üzerinde bulunan kolluk birimlerine bildirilir.",
yuva=["Aynı hüküm: hareket ve varış idarelerinin rolleri yer değiştirmiş",
      "İlave bilgi ve belge ibrazı: Bakanlığa (Gümrükler Genel Müdürlüğü) yapılan bildirimler, şifre zincirine taşınmış",
      "İlave bilgi ve belge ibrazı: adres değişikliğinde gümrük ve ticaret bölge müdürlüklerine bilgi verilmesi",
      "Aynı hüküm: 'birden fazla kullanıcı' yerine 'tek kullanıcı'; kolluk birimleri bildirimin alıcısı iken verici yapılmış"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 17 — md 10/4-b: Irak'tan sevkiyatta hareket gümrük idaresi işlemleri (tek kelime; ayna 1/2)
dict(
konu=K, blok="SB21",
kalip="YANLIŞ", z="O",
madde=T + " md. 10",
cek="Irak'tan sevkiyatta hareket idaresi şüphede numune alıp tahlile gönderir; araç mühürlenerek tahlil sonucu beklenmeksizin varış idaresine sevk edilir.",
kok=[T + "'e göre Irak'tan yapılacak ham petrol, nafta ve fuel-oil sevkiyatlarında hareket gümrük idaresince gerçekleştirilecek işlemlere ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Şüphe hâlinde eşyadan numune alınarak tahlile gönderilir ve araç, tahlil sonucu alınıncaya kadar varış gümrük idaresine sevk edilmez.",
c=["Mahreç ülkesinden alınmış analiz raporu ve Türkçe tercümesi ile tartı fişi transit beyannamesine eklenir, beyannamede eşyanın tarifesi belirtilir.",
   "Eşyanın öncelikle macun tahlili yöntemiyle tespiti yapılır.",
   "Eşyanın tahlile gönderildiğine ilişkin beyanname üzerine açıklama düşülür.",
   "Araçlarda bulunan araç takip sisteminin çalışıp çalışmadığı kontrol edilir."],
sirali=False,
g="Tebliğe göre Irak'tan ham petrol, nafta ve fuel-oil sevkiyatlarında hareket gümrük idaresinde mahreç ülkesinden alınmış analiz raporu ve Türkçe tercümesi ile tartı fişi transit beyannamesine eklenir ve beyannamede eşyanın tarifesi belirtilir; eşyanın öncelikle macun tahlili yöntemiyle tespiti yapılır, şüphe hâlinde numune alınarak tahlile gönderilir ve bu durum beyanname üzerine açıklama olarak düşülür. Aracın ilgili yerleri mühürlenerek araç, tahlil sonucu beklenilmeksizin varış gümrük idaresine sevk edilir. Araç takip sisteminin çalışıp çalışmadığı ise her taşımada hareket gümrük idaresince kontrol edilir. Tahlil sonucunun beklenmesi varış gümrük idaresine ait bir kuraldır: varışta şüphenin devamı hâlinde alınan numunenin tahlil sonucu gelmeden eşyanın tahliyesine veya çıkışına izin verilmez. Bu nedenle doğru cevap 'Şüphe hâlinde eşyadan numune alınarak tahlile gönderilir ve araç, tahlil sonucu alınıncaya kadar varış gümrük idaresine sevk edilmez.' seçeneğidir. (MD 10)",
kanit="22-SERİ NO 3.txt | Aracın ilgili yerleri mühürlenerek tahlil sonucu beklenilmeksizin araç, varış gümrük idaresine sevk edilir. || 22-SERİ NO 3.txt | Mahreç ülkesinden alınmış analiz raporu ve Türkçe tercümesi ile tartı fişi transit beyannamesine eklenir, beyannamede eşyanın tarifesi belirtilir. || 22-SERİ NO 3.txt | Eşyanın öncelikle macun tahlili yöntemiyle tespiti yapılır. Şüphe halinde numune alınarak tahlile gönderilir. Eşyanın tahlile gönderildiğine ilişkin beyanname üzerine açıklama düşülür. || 22-SERİ NO 3.txt | Araçlarda bulunan araç takip sisteminin çalışıp çalışmadığı",
yuva=["Alınacak önlemler, hareket idaresi (Irak'tan sevkiyat): analiz raporu, tercüme ve tartı fişi (doğru ifade)",
      "Alınacak önlemler, hareket idaresi (Irak'tan sevkiyat): öncelikle macun tahlili (doğru ifade)",
      "Alınacak önlemler, hareket idaresi (Irak'tan sevkiyat): beyannameye açıklama düşülmesi (doğru ifade)",
      "Alınacak önlemler, hareket idaresi (her taşıma): araç takip sisteminin kontrolü (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="tahlil-bekleme",
guncellik="",
cikmis="",
kapsamli=False,
),

# 18 — md 10/5: varış gümrük idaresinde işlemler (ayna 2/2)
dict(
konu=K, blok="SB21",
kalip="DOĞRU", z="Z",
madde=T + " md. 10",
cek="Hareket idaresince tahlile gönderilen eşyada varış idaresi numune alıp tahlile gönderir, tahliyeye izin verir; sonuçlar hareket idaresine bildirilir.",
kok=[T + "'e göre Tebliğ kapsamındaki taşımalarda varış gümrük idarelerince gerçekleştirilecek işlemlere ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Hareket gümrük idaresince eşyanın tahlile gönderilmiş olması hâlinde, varış gümrük idaresince de eşyadan numune alınarak tahlile gönderilir ve eşyanın tahliyesine veya çıkışına izin verilir.",
c=["Hareket gümrük idaresince eşyanın tahlile gönderilmiş olması hâlinde, hareket gümrük idaresince gönderilen numunenin tahlil sonucu gelmeden eşyanın tahliyesine veya çıkışına izin verilmez.",
   "Şüphenin devamı hâlinde eşyadan numune alınarak tahlile gönderilir ve tahlil sonucu beklenmeksizin eşyanın tahliyesine veya çıkışına izin verilir.",
   "Hareket ve varış gümrük idarelerince alınan numunelerin tahlil sonuçlarının farklı çıkması hâlinde mevzuat dâhilinde gerekli işlem varış gümrük idaresince yapılır.",
   "Macun tahlili yöntemiyle yapılan tespitte şüpheye düşülmesi hâlinde, takograf ve araç takip sistemi bilgileri kontrol edilmeksizin eşyadan numune alınarak tahlile gönderilir."],
sirali=False,
g="Tebliğe göre varış gümrük idaresinde aracın mühürleri kontrol edilir ve macun tahlili yöntemiyle eşyanın tespiti yapılır; şüphe hâlinde takograf ve araç takip sistemi bilgileri kontrol edilir, şüphenin devamı hâlinde eşyadan numune alınarak tahlile gönderilir ve bu durumda tahlil sonucu gelmeden eşyanın tahliyesine veya çıkışına izin verilmez. Eşya hareket gümrük idaresince tahlile gönderilmişse, bu kontrol hükümleri saklı kalmak üzere varış idaresi de eşyadan numune alarak tahlile gönderir ve eşyanın tahliyesine veya çıkışına izin verir; tahlil sonuçları alındıktan sonra karşılaştırma için hareket gümrük idaresine bildirilir ve sonuçlar farklı çıkarsa gerekli işlemi hareket gümrük idaresi yapar. En güçlü çeldirici hareket idaresinin numunesinin sonucunu bekleten seçenektir: tahlil sonucu beklenmesi, varış idaresinin kendi kontrolünde şüphenin devam ettiği hâle aittir. Şüphenin devamında sonucun beklenmeden tahliyeye izin verilmesi, hareket idaresindeki 'tahlil sonucu beklenilmeksizin sevk' kuralının varışa taşınmış hâlidir; takograf ve araç takip sistemi bilgilerinin kontrolü ise numune alınmadan önceki basamaktır. Bu nedenle doğru cevap 'Hareket gümrük idaresince eşyanın tahlile gönderilmiş olması hâlinde, varış gümrük idaresince de eşyadan numune alınarak tahlile gönderilir ve eşyanın tahliyesine veya çıkışına izin verilir.' seçeneğidir. (MD 10)",
kanit="22-SERİ NO 3.txt | Hareket gümrük idaresince eşyanın tahlile gönderilmiş olması halinde birinci bent hükümleri saklı kalmak üzere, eşyadan numune alınarak tahlile gönderilir ve eşyanın tahliyesine /çıkışına izin verilir. Tahlil sonuçlarının alınmasını müteakip gerekli kontrol ve karşılaştırmanın yapılmasını teminen hareket gümrük idaresine sonuçlar bildirilir. Sonuçların farklı çıkması halinde hareket gümrük idaresince mevzuat dâhilinde gerekli işlem yapılır. || 22-SERİ NO 3.txt | Aracın mühürleri kontrol edilir, macun tahlili yöntemi ile eşyanın tespiti yapılır. Şüphe halinde takograf ve araç takip sistemi bilgileri kontrol edilir. Şüphenin devamı halinde eşyadan numune alınarak tahlile gönderilir. Bu durumda, tahlil sonucu gelmeden eşyanın tahliyesine/çıkışına izin verilmez. || 22-SERİ NO 3.txt | Aracın ilgili yerleri mühürlenerek tahlil sonucu beklenilmeksizin araç, varış gümrük idaresine sevk edilir.",
yuva=["Varış idaresi, kendi kontrolünde şüphenin devamı hâli (tahlil sonucu gelmeden tahliye yok), hareket idaresinin numunesine taşınmış (sağduyu)",
      "Hareket idaresi: aracın tahlil sonucu beklenilmeksizin sevki, varış idaresinin şüphe devamı hâline taşınmış",
      "Aynı hüküm: farklı sonuçta işlem makamı hareket gümrük idaresiyken varış gümrük idaresi yapılmış",
      "Varış idaresi: şüphe hâlinde takograf ve araç takip sistemi bilgilerinin kontrolü basamağı atlanmış"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "MAKAM", "SAĞDUYU", "KOMŞU"],
duzey=["AYIRT"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="tahlil-bekleme",
guncellik="",
cikmis="",
kapsamli=False,
),

# 19 — md 10/3, 11: firmaların yükümlülükleri (önermeli, yanlıştır; II-III)
dict(
konu=K, blok="SB21",
kalip="ÖNERMELİ", z="Z",
madde=T + " md. 10, 11",
cek="Araç takip ve macun teçhizatını izin sahibi firma temin eder; sözleşme sahibi taşımazsa vergilerden taşıyıcı ile izin sahibi müteselsilen sorumludur.",
kok=[T + "'e göre Tebliğ kapsamındaki taşımalarda firmaların yükümlülüklerine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Taşıma yapacak araçlara takılacak araç takip sistemleri ve takip ünitelerinin temininden ve bu sistemlerin tüm altyapı, veri iletim giderleri ve oluşabilecek diğer giderlerinin karşılanmasından izin sahibi firma sorumludur.",
     "II. Macun tahlili yöntemiyle yapılacak tespitte kullanılacak macun ile takograf kayıtlarının kontrolüne ilişkin teçhizat, ilgili gümrük idarelerince temin edilir.",
     "III. Taşımanın sözleşme sahibi firma tarafından yapılmaması durumunda, bu taşımadan doğabilecek gümrük vergileri ve diğer mali yüklerden yalnızca taşıyıcı firma sorumludur.",
     "IV. Firmanın filosundaki çekiciden ayrılabilir dorse tanker ile taşıma yapılması hâlinde, dorse tankerin takip edilebilmesi için gerekli tedbirler firmalar tarafından alınır.",
     "Yukarıdaki ifadelerden hangileri yanlıştır?"],
d="II ve III",
c=["I ve II", "I ve IV", "III ve IV", "I, II ve III"],
sirali=False,
g="Tebliğe göre araç takip sistemleri ve takip ünitelerinin temininden, bu sistemlerin tüm altyapı ve veri iletim giderleri ile oluşabilecek diğer giderlerin karşılanmasından izin sahibi firma sorumludur (I doğru). Macun tahlili yöntemiyle yapılacak tespitte kullanılacak macunun ve takograf kayıtlarının kontrolüne ilişkin teçhizatın izin sahibi firma tarafından temin edilerek ilgili gümrük idarelerine teslimi gerekir; teçhizatı gümrük idaresi temin etmez, firmadan teslim alır (II yanlış). Taşımanın sözleşme sahibi firma tarafından yapılmaması durumunda, doğabilecek gümrük vergileri ve diğer mali yüklerden taşıyıcı firma ile izin sahibi firma müteselsilen sorumludur; sorumluluk yalnız taşıyıcıya ait değildir (III yanlış). Çekiciden ayrılabilir dorse tankerle taşıma yapılması hâlinde dorse tankerin takip edilebilmesi için gerekli tedbirler firmalar tarafından alınır; Bakanlık gerekli görürse ek güvenlik tedbirleri almaya da yetkilidir (IV doğru). Kök yanlış ifadeleri sormaktadır. Bu nedenle doğru cevap 'II ve III' seçeneğidir. (MD 10, 11)",
kanit="22-SERİ NO 3.txt | araç takip sistemleri ve takip ünitelerinin temininden ve söz konusu araç takip sistemlerinin tüm altyapı, veri iletim giderleri ve oluşabilecek diğer giderlerin karşılanmasından izin sahibi firma sorumludur || 22-SERİ NO 3.txt | Macun tahlili yöntemi ile yapılacak tespitte kullanılacak macunun ve takograf kayıtlarının kontrolüne ilişkin teçhizatın izin sahibi firma tarafından temin edilerek ilgili gümrük idarelerine teslimi gerekir. || 22-SERİ NO 3.txt | bu taşımadan doğabilecek gümrük vergileri ve diğer mali yüklerden taşıyıcı firma ile izin sahibi firma müteselsilen sorumludur || 22-SERİ NO 3.txt | dorse tankerin takip edilebilmesi için firmalar tarafından gerekli tedbirler alınır",
yuva=["I ve II: araç takip sistemi giderlerinin izin sahibine ait olduğunu bilmeyen, müteselsil sorumluluğu gözden kaçıran aday",
      "I ve IV: yanlış ifadeleri değil doğru ifadeleri işaretleyen aday (olumsuz kökü hızlı okuma)",
      "III ve IV: dorse tanker tedbirini Bakanlığın ek tedbir yetkisiyle karıştıran, teçhizat teslimini atlayan aday",
      "I, II ve III: araç takip sistemi giderlerinden izin sahibinin sorumlu olduğunu bilmeyen aday"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "MAKAM", "UNSUR"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=15, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 20 — md 12: askeri güçlere yapılacak sevkiyatlar (Irak sözleşme imza şartı hariç)
dict(
konu=K, blok="SB21",
kalip="ŞART", z="Z",
madde=T + " md. 4, 12",
cek="Askeri güçlere sevkiyatta ihale kazanılmış ve sözleşme Büyükelçilik kanalıyla bildirilmiş olmalı; Irak sözleşmesinin yetkili Bakanlıkça imzası şartı uygulanmaz.",
kok=[T + "'e göre 2011/2033 sayılı Bakanlar Kurulu Kararı kapsamında askeri güçlerin ihtiyacını karşılamak üzere diğer ülkelere karayolu veya demiryolu ile yapılacak sevkiyatlara ilişkin izinlerde aşağıdakilerden hangisi aranmaz?"],
d="Sözleşmenin, Irak'ta yetkili Bakanlık veya Bakanlıkça sözleşme yapma izni verilen kişiler tarafından imzalanmış olması",
c=["Askeri güçlerin açtığı ihalenin kazanılmış olması",
   "Askeri güçler ile imzalanan sözleşmenin Büyükelçilik kanalı ile Bakanlığa (Gümrükler Genel Müdürlüğü) bildirilmiş olması",
   "İzin sahibi ve/veya taşıyıcı firmanın ticarete konu eşya türüne uygun ilgili kurumlardan alınmış izin, ruhsat, lisans ve/veya yetki belgesi sahibi olması",
   "Karayoluyla taşımanın sayısal (dijital) takograf donanımlı ve araç takip sistemini haiz araçlarla yapılması"],
sirali=False,
g="Tebliğe göre 2011/2033 sayılı Bakanlar Kurulu Kararı kapsamında askeri güçlerin ihtiyacını karşılamak üzere diğer ülkelere karayolu veya demiryolu ile yapılacak sevkiyatlar için, askeri güçlerin açtığı ihalenin kazanılmış ve askeri güçlerle imzalanan sözleşmenin Büyükelçilik kanalıyla Bakanlığa (Gümrükler Genel Müdürlüğü) bildirilmiş olması gerekir. Bu izinlerde, Irak'a ve Irak'tan yapılacak sevkiyatlara ilişkin sözleşmenin Irak'ta yetkili Bakanlık veya Bakanlıkça sözleşme yapma izni verilen kişilerce imzalanması şartını düzenleyen hüküm hariç, Tebliğin diğer hükümleri uygulanır. Bu nedenle firmanın eşya türüne uygun izin, ruhsat, lisans veya yetki belgesine sahip olması ve karayolu araçlarının sayısal takograf ile araç takip sistemine sahip olması bu sevkiyatlarda da aranır. En güçlü çeldirici Büyükelçilik kanalıyla bildirimdir: bu, Irak sözleşmelerinde değil, askeri güçlerle yapılan sözleşmelerde aranan özel şarttır. Bu nedenle doğru cevap 'Sözleşmenin, Irak'ta yetkili Bakanlık veya Bakanlıkça sözleşme yapma izni verilen kişiler tarafından imzalanmış olması' seçeneğidir. (MD 4, 12)",
kanit="22-SERİ NO 3.txt | askeri güçlerin açtığı ihalenin kazanılmış ve askeri güçler ile imzalanan sözleşmenin Büyükelçilik kanalı ile Bakanlığa (Gümrükler Genel Müdürlüğü) bildirilmiş olması gerekir || 22-SERİ NO 3.txt | Birinci fıkra kapsamında verilecek izinlere ilişkin hususlarda 4 üncü maddenin ikinci fıkrası hükmü hariç diğer hükümler uygulanır. || 22-SERİ NO 3.txt | Irak'ta yetkili Bakanlık veya Bakanlıkça bu Tebliğ kapsamdaki taşımalara ilişkin olarak sözleşme yapma izni verilen kişiler tarafından imzalanması şarttır",
yuva=["Askeri güçlere sevkiyat: ihalenin kazanılmış olması (aranır)",
      "Askeri güçlere sevkiyat: sözleşmenin Büyükelçilik kanalıyla Bakanlığa bildirilmesi (aranır)",
      "İzin ön koşulları: eşya türüne uygun izin, ruhsat, lisans ve/veya yetki belgesi (askeri sevkiyatta da uygulanır)",
      "İzin ön koşulları: karayolu araçlarında takograf ve araç takip sistemi (askeri sevkiyatta da uygulanır)"],
yakinlik="PARAFRAZ",
tuzak=["İSTİSNA", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

]
