# Soru Bankası — Bölüm 26: Transit Tebliği (Seri No: 14) (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
# Dayanak: Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) — izinli gönderici yetkisi
#          (yan kaynak: Gümrük Yönetmeliği md. 238/A; çeldirici yuvaları için GİKY, GK 241)
Q = [

# ---------------- AMAÇ, DAYANAK, TANIMLAR (md. 1-3) ----------------
dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="TANIM",
z="K",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 3, 14",
cek="Nihai çıkış noktası izinli gönderici tesisi olan, transit beyanı ve mühür olmadan tesise getirilen ihracat eşyasının sınıra doğrudan sevki kolay ihracat noktalarıdır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre; nihai çıkış noktasının bir izinli gönderici tesisi olması kaydıyla, ülkenin herhangi bir noktasından tescil edilen ihracat beyannamesi kapsamı eşyanın transit beyanı ve mühür tatbiki olmaksızın getirildiği izinli gönderici tesisinden sınır gümrük idaresine doğrudan sevkine imkân veren uygulama aşağıdakilerden hangisidir?"],
d="Kolay ihracat noktaları uygulaması",
c=["İhracatta yerinde gümrükleme uygulaması",
   "Sınır kapılarından öncelikli geçiş uygulaması",
   "Basitleştirilmiş usulde transit uygulaması",
   "Mühürden vazgeçme uygulaması"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre kolay ihracat noktaları uygulaması; nihai çıkış noktasının bir izinli gönderici tesisi olması kaydıyla, ülkenin herhangi bir noktasından tescil edilen ihracat beyannamesi kapsamı eşyanın transit beyanı ve mühür tatbiki olmaksızın getirildiği izinli gönderici tesisinden sınır gümrük idaresine doğrudan sevkine imkân veren uygulamadır. Bu uygulamada eşya, herhangi bir gümrük idaresinde tescil edilen ihracat beyannamesiyle transit beyannamesi ve mühür olmadan izinli gönderici tesisine getirilir; hazır bildirimi tesisin bağlı bulunduğu gümrük müdürlüğüne iletilebilir. En güçlü çeldirici ihracatta yerinde gümrüklemedir: orada eşya izin sahibi firmanın kendi tesisinden çıkar ve ihracat beyannamesi bu uygulamaya özgü basitleştirilmiş işlem koduyla tescil edilir; 'ülkenin herhangi bir noktasından izinli gönderici tesisine getirme' unsuru bu uygulamada yoktur. Basitleştirilmiş usulde transit beyannamesi, izinli gönderici tesisinde araca izinli gönderici mührü tatbik edilerek tescil edilen beyannamedir; sınır kapılarından öncelikli geçiş yetkilendirilmiş yükümlülere tanınan bir kolaylık, mühürden vazgeçme ise Gümrük Yönetmeliği'nde transit eşyasının sevkinde geçen bir mühür usulüdür. Bu nedenle doğru cevap 'Kolay ihracat noktaları uygulaması' seçeneğidir. (MD 3, 14)",
kanit="27-seri no 14.txt | Kolay ihracat noktaları uygulaması: Nihai çıkış noktasının bir izinli gönderici tesisi olması kaydıyla, ülkenin herhangi bir noktasından tescil edilen ihracat beyannamesi kapsamı eşyanın transit beyanı ve mühür tatbiki olmaksızın getirildiği izinli gönderici tesisinden sınır gümrük idaresine doğrudan sevkine imkan veren uygulamayı || 3-YYS.txt | sınır kapılarından öncelikli geçiş hakkı uygulamasından yararlanma izni verilir || 20-TRANSİT REJİMİ.txt | mühürden vazgeçme uygulanarak varış gümrük idaresine sevk edilen",
yuva=["Tebliğin ihracatta yerinde gümrükleme tesislerinden yapılacak taşımalar hükmü (izin sahibinin kendi tesisi, kendine özgü işlem kodu)",
      "GİKY: yetkilendirilmiş yükümlü ve izinli gönderici sahiplerine tanınan sınır kapılarından öncelikli geçiş hakkı",
      "Tebliğin gümrük işlemleri hükmü: araca izinli gönderici mührü tatbik edilerek basitleştirilmiş usulde transit beyannamesi tescili",
      "Gümrük Yönetmeliği ortak transitte beyana aykırılık hükmü: mühürden vazgeçme uygulanarak sevk"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="DAYANAK",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 1, 2; Gümrük Yönetmeliği md. 238/A",
cek="Tebliğ, Ortak Transit Rejimine İlişkin Sözleşme ile Gümrük Yönetmeliğinin izinli gönderici hükmüne dayanır; Gümrük Kanunu ve Kolaylaştırma Yönetmeliği dayanak değildir.",
kok=["İzinli gönderici yetkisine ilişkin usul ve esasları düzenleyen Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) aşağıdakilerden hangisine dayanılarak hazırlanmıştır?"],
d="Ortak Transit Rejimine İlişkin Sözleşme ile Gümrük Yönetmeliği",
c=["4458 sayılı Gümrük Kanunu ile Gümrük Yönetmeliği",
   "Ortak Transit Rejimine İlişkin Sözleşme ile Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği",
   "TIR Sözleşmesi ile Gümrük Yönetmeliği",
   "Ortak Transit Rejimine İlişkin Sözleşme ile 4458 sayılı Gümrük Kanunu"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14), 6333 sayılı Kanunla onaylanması uygun bulunan Ortak Transit Rejimine İlişkin Sözleşme ile Gümrük Yönetmeliği'nin izinli gönderici yetkisini düzenleyen hükmüne dayanılarak hazırlanmıştır. Yönetmelikteki bu hüküm, transit rejimine konu eşyayı hareket idaresine sunmaksızın transit işlemi yapmak isteyenlere izinli gönderici yetkisi verilebileceğini belirtir; yetki başvurusunun koşullarını, incelenmesini, yetkinin verilmesi, askıya alınması ve iptalini Bakanlıkça düzenlenecek konular olarak sayar. Tebliğ bu düzenlemedir. Gümrük Kanunu bu Tebliğin dayanakları arasında sayılmamıştır; Kanunun transit hükümlerine dayanmak Seri No: 4, 5, 6 ve 8 gibi diğer transit tebliğlerinin özelliğidir. En güçlü çeldirici Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği'dir: yetkilendirilmiş yükümlü sertifikası sahiplerine verilen izinli gönderici yetkisi o Yönetmelikte ayrıca düzenlenir, ancak bu Tebliğin dayanağı değildir. TIR Sözleşmesi Gümrük Yönetmeliği'nin transit kapsamında sayılan ayrı bir sözleşmedir; Tebliğ TIR Karnesi işlemlerinin usul ve esaslarını Genel Müdürlüğe bırakır. Bu nedenle doğru cevap 'Ortak Transit Rejimine İlişkin Sözleşme ile Gümrük Yönetmeliği' seçeneğidir. (MD 1, 2, 19; GY 238/A)",
kanit="27-seri no 14.txt | Bu Tebliğ, 22/6/2012 tarihli ve 6333 sayılı Kanunla onaylanması uygun bulunan 20/5/1987 tarihli Ortak Transit Rejimine İlişkin Sözleşme ve Gümrük Yönetmeliğinin 238/A maddesine dayanılarak hazırlanmıştır || 20-TRANSİT REJİMİ.txt | Yetki başvurusunda aranacak koşullar, başvurunun yapılması, başvurunun incelenmesi, yetkinin verilmesi, askıya alınması, iptali, gümrük işlemleri ve diğer hususlar Bakanlıkça düzenlenir || 24-SERİ NO 5.txt | 4458 sayılı Gümrük Kanununun 84 ilâ 92 nci maddeleri ve 7/10/2009 tarihli ve 27369 mükerrer sayılı Resmî Gazete'de yayımlanan Gümrük Yönetmeliğinin 237 nci maddesine dayanılarak hazırlanmıştır",
yuva=["Seri No: 5 ve Seri No: 8 transit tebliğlerinin dayanağı: Gümrük Kanunu ile Gümrük Yönetmeliği",
      "GİKY: yetkilendirilmiş yükümlü sertifikası sahiplerine izinli gönderici yetkisi (ek koşullar)",
      "Gümrük Yönetmeliği transit kapsamı: TIR Sözleşmesi kapsamındaki transit işlemleri; Tebliğde TIR işlemleri Genel Müdürlüğe bırakılmış",
      "Seri No: 4 ve Seri No: 6 transit tebliğlerinin dayanağı: Sözleşme ile birlikte Kanunun transit hükümleri"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- KOŞULLAR (md. 4) ----------------
dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="KAPSAM_DIŞI",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 4",
cek="Tebliğdeki izinli gönderici şartlarında uluslararası taşımacı yetki belgesi yoktur; o, Kolaylaştırma Yönetmeliğinde YYS sahibinin izinli gönderici ek koşuludur.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici başvurusunda bulunacak kişilerin taşıması gereken şartlar arasında aşağıdakilerden hangisi yer almaz?"],
d="Ulaştırma ve Altyapı Bakanlığından alınmış uluslararası taşımacı yetki belgesine sahip olunması",
c=["Kapsamlı teminat kullanma veya teminattan vazgeçme iznine sahip olunması",
   "Başvuru formunda belirtilen asgari şartlara haiz en az bir tesise sahip olunması",
   "Gümrük mevzuatı uyarınca kesinleşmiş ancak ödenmemiş herhangi bir vergi ve ceza borcu bulunmaması",
   "Kayıtların güvenilir ve izlenebilir şekilde tutulduğu bir lojistik programının kullanılıyor olması"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici başvurusunda bulunacak kişiler şu şartları taşıdıklarını kanıtlar: Türkiye'de yerleşik bir kefil kuruluştan alınmış teminat mektubuyla ilişkili kapsamlı teminat kullanma veya teminattan vazgeçme iznine sahip olmak; yönetim kurulu üyeleri ile sermayenin %10 veya daha fazlasına sahip gerçek kişiler hakkında kesinleşmiş mahkûmiyet kararı bulunmaması; transit beyanı sayısı şartı; ceza oranı şartı; asgari şartlara haiz en az bir tesis; ISO 9001 ve ISO 27001 sertifikaları; kayıtların güvenilir ve izlenebilir tutulduğu lojistik programı; mali yapıya ilişkin yeminli mali müşavir raporu; kesinleşmiş ancak ödenmemiş vergi ve ceza borcu bulunmaması; tesiste gümrük hizmeti verilmesinin orantısız idari yük getirmemesi. Ulaştırma ve Altyapı Bakanlığından alınmış uluslararası taşımacı yetki belgesi bu listede yoktur; bu belge Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği'nde yetkilendirilmiş yükümlü sertifikası sahiplerine verilen izinli gönderici yetkisinin ek koşuludur. Kapsamlı teminat ve en az bir tesis şartları iki düzenlemede de bulunduğundan, iki listeyi karıştıran aday taşımacı yetki belgesini de Tebliğ şartı sanır. Bu nedenle doğru cevap 'Ulaştırma ve Altyapı Bakanlığından alınmış uluslararası taşımacı yetki belgesine sahip olunması' seçeneğidir. (MD 4)",
kanit="27-seri no 14.txt | İzinli gönderici başvurusunda bulunacak kişilerin aşağıda yer alan şartları taşıdığını başvuru formunda belirtilen esaslar çerçevesinde kanıtlaması gerekir || 27-seri no 14.txt | Başvuru formunda belirtilen asgari şartlara haiz en az bir tesise sahip olması || 27-seri no 14.txt | Gümrük mevzuatı uyarınca kesinleşmiş ancak ödenmemiş herhangi bir vergi ve ceza borcu bulunmaması || 27-seri no 14.txt | kayıtların güvenilir ve izlenebilir şekilde tutulduğu bir lojistik programını kullanıyor olması || 3-YYS.txt | Ulaştırma ve Altyapı Bakanlığından alınmış uluslararası taşımacı yetki belgesi sahibi olmak",
yuva=["Tebliğ şartları: kapsamlı teminat kullanma veya teminattan vazgeçme izni (listede; GİKY'de de var)",
      "Tebliğ şartları: asgari şartlara haiz en az bir tesis (listede; GİKY'de de var)",
      "Tebliğ şartları: kesinleşmiş ancak ödenmemiş vergi ve ceza borcu bulunmaması (listede)",
      "Tebliğ şartları: güvenilir ve izlenebilir kayıtlı lojistik programı (listede)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "KOMŞU", "SAĞDUYU"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 4, 8",
cek="Teminat mektubu Türkiye'de yerleşik kefilden; yöneticilerde kesinleşmiş mahkûmiyet aranır, dava değil; YYS'de YMM raporu kanıtlanmaz; ISO 9001 ve 27001 gerekir.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici başvurusunda aranan koşullara ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Sahip olunan kapsamlı teminat izni ile ilişkili teminat mektubunun Türkiye'de yerleşik bir kefil kuruluştan alınmış olması gerekir.",
     "II. Yönetim kurulu üyeleri ile şirket sermayesinin % 10 veya daha fazlasına sahip gerçek kişiler hakkında, başvuru formunda belirtilen suçlarla ilgili dava açılmamış olması gerekir.",
     "III. Başvuru sahibinin yetkilendirilmiş yükümlü statüsü olması hâlinde, mali yapının yeminli mali müşavir tarafından incelenerek olumlu görüşle rapora bağlanmış olması koşulunun kanıtlanması gerekmez.",
     "IV. Avrupa Akreditasyon Birliğinin karşılıklı tanıma anlaşmalarına imza atmış akreditasyon kurumlarınca akredite edilmiş uygunluk değerlendirme kuruluşlarınca düzenlenen geçerli ISO 9001 ve ISO 27001 sertifikalarına sahip olunması gerekir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, III ve IV",
c=["I ve III", "II ve IV", "I, II ve III", "I, II, III ve IV"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre I doğrudur: kapsamlı teminat kullanma veya teminattan vazgeçme izni, sahip olunan kapsamlı teminat izni ile ilişkili teminat mektubunun Türkiye'de yerleşik bir kefil kuruluştan alınmış olması şartıyla aranır. II yanlıştır: yönetim kurulu üyeleri ile sermayenin %10 veya daha fazlasına sahip gerçek kişiler için aranan şart, başvuru formunda belirtilen suçlarla ilgili kesinleşmiş mahkûmiyet kararı bulunmamasıdır; dava açılmış olması başvuru şartı değildir, yetki verildikten sonra izinli gönderici yetkisinin askıya alınma sebebidir. III doğrudur: başvuru sahibinin yetkilendirilmiş yükümlü statüsü varsa mali yapıya ilişkin yeminli mali müşavir raporu ile kesinleşmiş ancak ödenmemiş vergi ve ceza borcu bulunmaması koşulları kanıtlanmaz. IV doğrudur: Avrupa Akreditasyon Birliğinin karşılıklı tanıma anlaşmalarına imza atmış akreditasyon kurumlarınca akredite edilmiş kuruluşlarca düzenlenen ve akreditasyon kurumunun markasını taşıyan geçerli ISO 9001 ve ISO 27001 sertifikaları aranır. En güçlü tuzak II. önermedir; 'dava açılması' ifadesi Tebliğde gerçekten geçer, ancak askıya alma hâlleri arasındadır. Bu nedenle doğru cevap 'I, III ve IV' seçeneğidir. (MD 4, 8)",
kanit="27-seri no 14.txt | Sahip olunan kapsamlı teminat izni ile ilişkili teminat mektubunun, Türkiye'de yerleşik bir kefil kuruluştan alınmış olması şartıyla || 27-seri no 14.txt | Yönetim kurulu üyeleri ile şirket sermayesinin % 10 veya daha fazlasına sahip gerçek kişiler hakkında başvuru formunda belirtilen suçlarla ilgili kesinleşmiş mahkûmiyet kararı bulunmaması || 27-seri no 14.txt | Başvuru sahibinin yetkilendirilmiş yükümlü statüsü olması halinde birinci fıkranın (g) ve (ğ) bentlerinde belirtilen koşulları kanıtlaması gerekmez || 27-seri no 14.txt | akreditasyon kurumunun markasını taşıyan geçerli ISO 9001 ve ISO 27001 sertifikalarına sahip olunması || 27-seri no 14.txt | ilgililer hakkında başvuru formunda belirtilen suçlardan dava açıldığının veya mahkûmiyet kararı verildiğinin tespit edilmesi",
yuva=["I ve III: IV'teki ISO 27001 şartını bilmeyen aday",
      "II ve IV: II'deki askıya alma sebebini başvuru şartı sanan, I ve III'ü atlayan aday",
      "I, II ve III: II'yi doğru, IV'ü yanlış sanan aday",
      "I, II, III ve IV: askıya alma hâlindeki 'dava açılması'nı başvuru şartı sanan aday"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="HESAP",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 4",
cek="YYS statüsündeki başvuranda transit beyanı sayısı dörtte bir uygulanır: rejim hak sahibi olarak üç yılın her birinde en az 1.375 beyan.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) kapsamında izinli gönderici yetkisi için başvuru yapacak bir şirkete ilişkin bilgiler şöyledir:",
     "- Doğu Lojistik A.Ş., 2026 yılında izinli gönderici yetkisi için başvuru yapacaktır.",
     "- Şirket, yetkilendirilmiş yükümlü statüsüne sahiptir.",
     "- Şirket, ihracat beyannamesi kapsamı eşyanın taşınmasına yönelik transit beyanlarında (TIR karnesi dahil) taşıyıcı olarak değil, rejim hak sahibi sıfatıyla yer almaktadır.",
     "Buna göre şirketin, transit beyanı sayısına ilişkin koşulu sağlayabilmesi için 2023, 2024 ve 2025 yıllarının her birinde rejim hak sahibi olarak yer alması gereken asgari transit beyanı sayısı kaçtır?"],
d="1.375",
c=["125", "500", "4.125", "5.500"],
sirali=True,
siklar=["125", "500", "1.375", "4.125", "5.500"],
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre başvuru sahibi, başvurunun yapıldığı takvim yılından geriye dönük üç takvim yılı boyunca, her yıl ayrı ayrı değerlendirilmek üzere, ihracat beyannamesi kapsamı eşyanın taşınmasına yönelik olarak TIR karnesi dahil en az 5.500 transit beyanında rejim hak sahibi olmalı veya en az 500 transit beyanında taşıyıcı sıfatını taşımalıdır. Vakada saklı istisna şirketin yetkilendirilmiş yükümlü statüsüdür: bu durumda transit beyanı sayısı dörtte bir nispetinde uygulanır. Şirket rejim hak sahibi olarak yer aldığından aranacak sayı 5.500 ÷ 4 = 1.375'tir ve bu sayıya 2023, 2024 ve 2025 yıllarının her birinde ayrı ayrı ulaşılması gerekir. 5.500 istisnayı görmeyen adayın; 4.125 (1.375 × 3) 'her yıl ayrı ayrı' kaydını atlayıp üç yılı toplayan adayın; 125 ve 500 ise taşıyıcı sıfatına ait sayıları rejim hak sahibine uygulayan adayın cevabıdır. Bu nedenle doğru cevap '1.375' seçeneğidir. (MD 4)",
kanit="27-seri no 14.txt | Başvurunun yapıldığı takvim yılından geriye dönük üç takvim yılı boyunca her yıl ayrı ayrı değerlendirilmek üzere ihracat beyannamesi kapsamı eşyanın taşınmasına yönelik olarak TIR karnesi dahil en az 5.500 transit beyanında rejim hak sahibi olması veya en az 500 transit beyanında taşıyıcı sıfatını taşıyor olması || 27-seri no 14.txt | Aynı fıkranın (c) bendinde belirtilen transit beyanı sayısı ise dörtte bir nispetinde uygulanır",
yuva=["Taşıyıcı sıfatında aranan 500 beyanın dörtte biri (yetkilendirilmiş yükümlüde taşıyıcı sayısı)",
      "Taşıyıcı sıfatı için aranan genel sayı (500)",
      "Üç yılın toplamı (1.375 × 3): 'her yıl ayrı ayrı' kaydını atlayan hesap",
      "Yetkilendirilmiş yükümlü indirimi uygulanmamış genel sayı (5.500)"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "AD-HESAP", "YAKIN-SAYI"],
duzey=["UYGULAMA"],
profil=[2],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="ORAN-TUTAR",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 4",
cek="Üç yılın her birinde vergi kaybına yol açan ihlal cezası, işlem gören tüm beyannamelerin %0,5'ini aşmamalı; usulsüzlük cezasında sınır %2'dir.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici başvurusunda, başvurunun yapıldığı takvim yılından geriye dönük üç takvim yılı boyunca her yıl ayrı ayrı değerlendirilmek üzere, vergi kaybına neden olan gümrük mevzuatı ihlali nedeniyle ceza uygulanan beyanname sayısı, işlem gören tüm beyanname sayısının yüzde kaçını aşmamalıdır?"],
d="% 0,5",
c=["% 0,2", "% 2", "% 10", "% 25"],
sirali=True,
siklar=["% 0,2", "% 0,5", "% 2", "% 10", "% 25"],
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre başvurunun yapıldığı takvim yılından geriye dönük üç takvim yılı boyunca her yıl ayrı ayrı değerlendirilmek üzere, işlem gören tüm beyanname sayısının %0,5'ini aşan sayıda vergi kaybına neden olan gümrük mevzuatı ihlali nedeniyle ceza uygulanmamış olması gerekir. Aynı şartın ikinci ayağında, gümrük mevzuatının ihlali nedeniyle %2'sini aşan sayıda, Gümrük Kanunu'nun usulsüzlük cezalarına ilişkin hükmü (ilk fıkrası hariç) uyarınca usulsüzlük cezası uygulanmamış olması aranır. En güçlü çeldirici %2'dir; bu oran aynı şartta usulsüzlük cezalarına aittir. %10 yönetim kurulu üyeleriyle birlikte değerlendirilen ortakların sermaye payını, %25 (dörtte bir) yetkilendirilmiş yükümlülerde transit beyanı sayısının uygulanma oranını gösterir; binde 2 (%0,2) ise Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği'nde yetkilendirilmiş yükümlü sertifikası için aranan ceza kriteridir. Bu nedenle doğru cevap '% 0,5' seçeneğidir. (MD 4)",
kanit="27-seri no 14.txt | işlem gören tüm beyanname sayısının % 0,5'ini aşan sayıda vergi kaybına neden olan gümrük mevzuatı ihlali nedeniyle ceza uygulanmamış olması ve gümrük mevzuatının ihlali nedeniyle % 2'sini aşan sayıda || 27-seri no 14.txt | şirket sermayesinin % 10 veya daha fazlasına sahip gerçek kişiler || 3-YYS.txt | ithalat ve ihracat gümrük beyannamesi toplamının binde 2'sini aşmamalıdır",
yuva=["GİKY yetkilendirilmiş yükümlü ceza kriteri: beyanname toplamının binde 2'si",
      "Aynı şartın ikinci ayağı: usulsüzlük cezası uygulanan beyanname oranı %2",
      "Aynı listede yönetim kurulu üyeleriyle birlikte sayılan ortakların sermaye payı %10",
      "Yetkilendirilmiş yükümlüde transit beyanı sayısının dörtte bir (%25) nispetinde uygulanması"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- BAŞVURU, İNCELEME, YENİLEME (md. 5, 11) ----------------
dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="EŞLEŞTİRME",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 5, 11, 19",
cek="Ön başvuru bölge müdürlüğüne, başvuru Genel Müdürlüğe yapılır; koşulların yerinde incelemesi Ticaret Uzmanı, idari yük değerlendirmesi bölge müdürlüğünce yapılır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yetkisine ilişkin işlemler ile bu işlemlerin yapılacağı veya bu işlemleri yapan makam eşleştirmelerinden hangisi yanlıştır?"],
d="Ön başvuru formuyla ön başvurunun yapılması – Genel Müdürlük",
c=["Başvuru formuyla başvurunun yapılması – Genel Müdürlük",
   "Tesiste gümrük hizmeti verilmesinin gümrük idaresi üzerinde orantısız idari yük getirmeyeceğine ilişkin değerlendirme – İlgili bölge müdürlüğü",
   "Kapsamlı teminat, ISO sertifikaları ve lojistik programı koşullarına ilişkin yerinde inceleme – Genel Müdürlükçe görevlendirilen Ticaret Uzmanı",
   "TIR Karnesi kapsamında yapılacak işlemlere ilişkin usul ve esasların belirlenmesi – Genel Müdürlük"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre ön başvuru, ön başvuru formuyla bölge müdürlüğüne; başvuru ise başvuru formuyla Genel Müdürlüğe yapılır. Bölge müdürlüğü, ilgili konumda tesis açılmasının gümrük idaresi üzerinde orantısız idari yük getirmeyeceğine ilişkin değerlendirmesini ve tesisin bağlı olacağı gümrük müdürlüğü bilgisini ön başvuru formuyla Genel Müdürlüğe gönderir. Kapsamlı teminattan kesinleşmiş vergi ve ceza borcuna kadar olan koşulların değerlendirilmesi ve yerinde incelemesi Genel Müdürlükçe görevlendirilen Ticaret Uzmanı, orantısız idari yük koşulunun değerlendirilmesi ise ilgili bölge müdürlüğü tarafından yapılır. TIR Karnesi kapsamında yapılacak işlemlere ilişkin usul ve esasları Genel Müdürlük belirler. Yanlış eşleştirme ön başvurudadır: ön başvuru Genel Müdürlüğe değil bölge müdürlüğüne yapılır; ön başvuru formu Genel Müdürlüğe ancak bölge müdürlüğünün değerlendirmesiyle birlikte gönderilir. Bu nedenle doğru cevap 'Ön başvuru formuyla ön başvurunun yapılması – Genel Müdürlük' seçeneğidir. (MD 5, 11, 19)",
kanit="27-seri no 14.txt | Ön Başvuru Ek-1/A'da yer alan ön başvuru formuyla bölge müdürlüğüne, başvuru ise Ek-1/B'de yer alan başvuru formuyla Genel Müdürlüğe yapılır || 27-seri no 14.txt | değerlendirme ve yerinde inceleme Genel Müdürlükçe görevlendirilen Ticaret Uzmanı, (h) bendinde belirtilen koşulun sağlandığına ilişkin değerlendirme ve inceleme ise ilgili bölge müdürlüğü tarafından gerçekleştirilir || 27-seri no 14.txt | TIR Karnesi kapsamında yapılacak işlemlere ilişkin usul ve esaslar Genel Müdürlükçe belirlenir || 27-seri no 14.txt | tesisin bağlı olacağı gümrük müdürlüğü bilgisini de Ek-1/A'da yer alan ön başvuru formuyla Genel Müdürlüğe gönderir",
yuva=["Başvuru başvuru formuyla Genel Müdürlüğe yapılır (doğru eşleşme)",
      "Orantısız idari yük koşulunun değerlendirilmesi ilgili bölge müdürlüğünce (doğru eşleşme)",
      "Kapsamlı teminattan ödenmemiş borca kadarki koşulların yerinde incelemesi Ticaret Uzmanınca (doğru eşleşme)",
      "TIR Karnesi işlemlerinin usul ve esasları Genel Müdürlükçe belirlenir (doğru eşleşme)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="YANLIŞ",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 5",
cek="Yetki askıya alınmadıkça veya iptal edilmedikçe geçerlidir; yenileme, yetkilendirme takvim yılını izleyen her üç yılın son ayındadır, yetki tarihinden itibaren değil.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yetkisi başvurusunun yerinde incelenmesi, yetkinin geçerliliği ve yenilenmesine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Yenileme başvurusu, yetkilendirmenin yapıldığı tarihten itibaren her üç yılın dolduğu ayda yapılır.",
c=["İzinli gönderici yetkisi askıya alınmadığı veya iptal edilmediği sürece geçerlidir.",
   "Koşulların yerinde incelenmesine ilişkin olarak beş günü geçmemek üzere yapılan konaklama ve ulaşım giderleri, inceleme sırasında başvuruda bulunanlarca karşılanır.",
   "Yenileme başvurusunun yapıldığı tarihte yetki kapsamındaki tesislere ilişkin yerinde incelemenin üzerinden bir yıldan daha az süre geçmişse, bu tesislerde yerinde inceleme yapılmayabilir.",
   "Yerinde inceleme sonucunda gerekli şartların sağlandığı anlaşılırsa başvuru sahibi adına izinli gönderici yetki numarası ve yetki belgesi düzenlenir."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yetkisi askıya alınmadığı veya iptal edilmediği sürece geçerlidir; yetkinin belirli bir süresi yoktur. Yenileme başvurusu ise yetkilendirmenin yapıldığı tarihten değil, yetkilendirmenin yapıldığı takvim yılını izleyen her üç yılın son ayında veya Genel Müdürlükçe talep edilmesi hâlinde yapılır; örneğin 15 Mart 2022'de verilen yetkide ilk yenileme dönemi 2025 yılının mart ayı değil, aralık ayıdır. Koşulların yerinde incelenmesine ilişkin olarak beş günü geçmemek üzere yapılan konaklama ve ulaşım giderleri inceleme sırasında başvuruda bulunanlarca karşılanır. Yenileme başvurusunun yapıldığı tarihte tesislere ilişkin yerinde incelemenin üzerinden bir yıldan az süre geçmişse bu tesislerde yerinde inceleme yapılmayabilir; üç yıllık süre Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği'nde yetkilendirilmiş yükümlülerin tesis koşulları için öngörülmüştür. Yerinde inceleme sonucunda yerinde inceleme değerlendirme formu düzenlenir, şartlar sağlanmışsa başvuru sahibi adına izinli gönderici yetki numarası ve yetki belgesi düzenlenir. Yanlış seçenekte yenileme döneminin başlangıcı ve ölçüsü değiştirilmiştir. Bu nedenle doğru cevap 'Yenileme başvurusu, yetkilendirmenin yapıldığı tarihten itibaren her üç yılın dolduğu ayda yapılır.' seçeneğidir. (MD 5)",
kanit="27-seri no 14.txt | İzinli gönderici yetkisi askıya alınmadığı veya iptal edilmediği sürece geçerlidir || 27-seri no 14.txt | Yenileme başvurusu yetkilendirmenin yapıldığı takvim yılını izleyen her üç yılın son ayında veya Genel Müdürlükçe talep edilmesi halinde yapılır || 27-seri no 14.txt | beş günü geçmemek üzere yapılan konaklama ve ulaşım giderleri inceleme sırasında başvuruda bulunanlarca karşılanır || 27-seri no 14.txt | yapılan yerinde incelemenin üzerinden bir yıldan daha az bir süre geçmiş olması durumunda yenileme başvuru kapsamında bu tesislerde yerinde inceleme yapılmayabilir || 27-seri no 14.txt | gerekli şartların sağlandığının anlaşılması halinde başvuru sahibi adına Ek-2/A'da yer alan izinli gönderici yetki numarası || 3-YYS.txt | incelenmiş ve yapılan incelemenin üzerinden 3 yıldan daha az süre geçmişse",
yuva=["Tebliğ md. 5/4 ilk cümle: yetkinin geçerliliği (doğru)",
      "Tebliğ md. 5/3: beş güne kadar konaklama ve ulaşım giderleri (doğru)",
      "Tebliğ md. 5/4 son cümle: son incelemeden bir yıl geçmemişse yerinde inceleme yapılmayabilir (doğru; GİKY'deki üç yılla karıştırılabilir)",
      "Tebliğ md. 5/5: yetki numarası ve yetki belgesinin düzenlenmesi (doğru)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "YAKIN-SAYI", "KOMŞU"],
duzey=["AYIRT"],
profil=[2, 4],
olumsuz=True, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="TANIM",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 3",
cek="İzinli gönderici, transite tabi eşyayı hareket gümrük idaresine sunmaksızın sevk etmeye yetkili ve transit işlemlerinden sorumlu kişidir; izinli alıcı varışta teslim alır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre \"izinli gönderici\" deyimi aşağıdakilerden hangisini ifade eder?"],
d="Transit rejimine tabi eşyayı, hareket gümrük idaresine sunmaksızın sevk etmeye yetkilendirilmiş olan ve rejim kapsamında yapılan işlemlerde transit işlemlerinden sorumlu olan kişi",
c=["Transit rejimine tabi eşyayı, varış gümrük idaresine sunmaksızın yetkilendirilmiş tesislerde teslim almaya ve transit işlemlerini bu yerlerde sonlandırmaya yetkilendirilmiş olan taşımadan sorumlu veya ithalatçı kişi",
   "Teminat tutarına kadar doğabilecek gümrük vergileri ve diğer yükleri rejim hak sahibi ile birlikte müştereken ve müteselsilen ödemeyi yazılı olarak üstlenen gerçek veya tüzel üçüncü kişi",
   "İhracatta yerinde gümrükleme, basitleştirilmiş işlem kapsamında A.TR Dolaşım Belgesi düzenleme ve vize etme ile kıymetine bakılmaksızın fatura beyanı düzenleme izinlerinden bir veya daha fazlasına sahip kişi",
   "Aynı gruba ait imalatçı firmaların ihracat işlemlerini gerçekleştiren, yine bu gruba ait olan dış ticaret veya pazarlama şirketi"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'ün tanımlar hükmünde izinli gönderici; transit rejimine tabi eşyayı, hareket gümrük idaresine sunmaksızın sevk etmeye yetkilendirilmiş olan ve rejim kapsamında yapılan işlemlerde transit işlemlerinden sorumlu olan kişi olarak tanımlanmıştır. Tanımın iki unsuru vardır: eşyanın hareket gümrük idaresine sunulmadan sevki ve transit işlemlerinden sorumluluk. Gümrük İşlemlerinin Kolaylaştırılması Yönetmeliği'ndeki izinli alıcı ise transitin öbür ucundadır: eşyayı varış gümrük idaresine sunmaksızın yetkilendirilmiş tesislerde teslim alır ve transit işlemlerini orada sonlandırır. Vergileri rejim hak sahibiyle birlikte müştereken ve müteselsilen ödemeyi yazılı olarak üstlenen üçüncü kişi, Gümrük Yönetmeliği'nin transit rejimine ilişkin hükümlerindeki kefil tanımıdır; sayılan izinlerden birine sahip kişi onaylanmış ihracatçı, aynı gruptaki imalatçıların ihracat işlemlerini yapan şirket ise grup ihracatçısıdır. En güçlü çeldirici izinli alıcı tanımıdır: iki kavram aynı basitleştirmenin hareket ve varış kutuplarıdır. Bu nedenle doğru cevap 'Transit rejimine tabi eşyayı, hareket gümrük idaresine sunmaksızın sevk etmeye yetkilendirilmiş olan ve rejim kapsamında yapılan işlemlerde transit işlemlerinden sorumlu olan kişi' seçeneğidir. (MD 3)",
kanit="27-seri no 14.txt | İzinli gönderici: Transit rejimine tabi eşyayı, hareket gümrük idaresine sunmaksızın sevk etmeye yetkilendirilmiş olan ve rejim kapsamında yapılan işlemlerde transit işlemlerinden sorumlu olan kişiyi || 3-YYS.txt | varış gümrük idaresine sunmaksızın izinli alıcı yetkisi ve/veya ithalatta yerinde gümrükleme izni kapsamı tesislerde teslim almaya ve transit işlemlerini bu yerlerde sonlandırmaya yetkilendirilmiş olan taşımadan sorumlu veya ithalatçı kişiyi || 20-TRANSİT REJİMİ.txt | Teminat tutarına kadar doğabilecek gümrük vergileri ve diğer yükleri rejim hak sahibi ile birlikte müştereken ve müteselsilen ödemeyi yazılı olarak üstlenen gerçek veya tüzel üçüncü kişiyi || 3-YYS.txt | Onaylanmış ihracatçı: Aşağıdaki izinlerden bir veya daha fazlasına sahip kişiyi || 3-YYS.txt | aynı gruba ait imalatçı firmaların ihracat işlemlerini gerçekleştiren, yine bu gruba ait olan dış ticaret veya pazarlama şirketini",
yuva=["GİKY md. 3: izinli alıcı tanımı (transitin varış kutbu)",
      "Gümrük Yönetmeliği md. 212: transit rejiminde kefil tanımı",
      "GİKY md. 3: onaylanmış ihracatçı tanımı",
      "GİKY md. 3: grup ihracatçısı tanımı"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- ASKIYA ALMA VE İPTAL (md. 6-10) ----------------
dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="SÜRE",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 8, 9",
cek="Genel Müdürlük yenileme isterse tebligattan itibaren 30 günde başvurmayanın yetkisi askıya alınır; askıdan itibaren 90 günde yenilenmezse iptal edilir.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre yenilemenin Genel Müdürlükçe talep edildiği durumda, izinli gönderici yetkisi sahibinin yenileme başvurusunda bulunmaması hâlinde uygulanacak askıya alma ve iptal süreleri aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Tebligat tarihinden başlamak üzere 30 gün içinde başvuru yapılmazsa yetki askıya alınır; askıya alma işleminden itibaren 90 gün içinde de başvuru yenilenmezse yetki iptal edilir.",
c=["Tebligat tarihinden başlamak üzere 90 gün içinde başvuru yapılmazsa yetki askıya alınır; askıya alma işleminden itibaren 30 gün içinde de başvuru yenilenmezse yetki iptal edilir.",
   "Tebligat tarihinden başlamak üzere 30 gün içinde başvuru yapılmazsa yetki askıya alınır; tebligat tarihinden itibaren 90 gün içinde de başvuru yenilenmezse yetki iptal edilir.",
   "Talep yazısının tarihinden başlamak üzere 30 gün içinde başvuru yapılmazsa yetki askıya alınır; askıya alma işleminden itibaren 90 gün içinde de başvuru yenilenmezse yetki iptal edilir.",
   "Tebligat tarihinden başlamak üzere 30 gün içinde başvuru yapılmazsa yetki doğrudan iptal edilir; iptal kararında yeniden başvuru yapılabilecek tarih bir aydan az olamaz."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre yenilemenin Genel Müdürlükçe talep edildiği durumlarda, tebligat tarihinden başlamak üzere yenileme başvurusunun 30 gün içerisinde yapılmaması izinli gönderici yetkisinin askıya alınma sebebidir. Bu askıya alma işleminden itibaren 90 gün içerisinde başvurunun yenilenmemesi ise yetkinin iptal sebebidir. İki sürenin başlangıcı farklıdır: 30 günlük süre tebligat tarihinden, 90 günlük süre askıya alma işleminden başlar. Sürelerin yer değiştirildiği seçenek iki sayıyı karıştıran adayı, 90 günü tebligat tarihinden başlatan seçenek ise başlangıç anını karıştıran adayı yakalar; süre talep yazısının tarihinden değil tebligattan başlar. 'Bir aydan az olamaz' ifadesi iptal kararlarında yeniden başvuru tarihinin alt sınırıdır; süresinde başvurmamanın ilk sonucu iptal değil askıya almadır. Bu nedenle doğru cevap 'Tebligat tarihinden başlamak üzere 30 gün içinde başvuru yapılmazsa yetki askıya alınır; askıya alma işleminden itibaren 90 gün içinde de başvuru yenilenmezse yetki iptal edilir.' seçeneğidir. (MD 8, 9, 10)",
kanit="27-seri no 14.txt | Yenilemenin Genel Müdürlükçe talep edildiği durumlarda tebligat tarihinden başlamak üzere 5 inci maddenin dördüncü fıkrasında belirtilen yenileme başvurusunun 30 gün içerisinde yapılmaması || 27-seri no 14.txt | askıya alma işleminden itibaren 90 gün içerisinde başvurunun yenilenmemesi || 27-seri no 14.txt | bir aydan az üç yıldan fazla olmayacak şekilde belirlenir",
yuva=["Aynı iki hükmün süreleri yer değiştirilmiş (askıya alma 30, iptal 90 gün)",
      "İptal için 90 günün başlangıcı askıya alma işlemidir; tebligat tarihi askıya almadaki 30 günün başlangıcıdır",
      "Askıya almadaki 30 günün başlangıcı tebligat tarihidir; talep yazısı tarihi başlangıç anı tuzağı",
      "Bildirim hükmü: iptal kararında yeniden başvuru tarihi bir aydan az olamaz; süresinde başvurmama önce askıya alma sebebidir"],
yakinlik="PARAFRAZ",
tuzak=["YAKIN-SAYI", "BAŞLANGIÇ", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="KAPSAM_DIŞI",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 6, 7",
cek="Tesis askı hâlleri: memura kolaylık sağlanmaması, risk tespiti, sanık yetkilinin görevde kalması, lojistik program; güvenlik ve kamera-lojistik kaydı eksikliği iptal sebebidir.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre aşağıdakilerden hangisi, ilgili tesisin yetkilendirilmesinin söz konusu durum ortadan kalkıncaya kadar askıya alınmasını gerektiren durumlar arasında yer almaz?"],
d="Tesiste gerekli güvenlik önlemlerinin alınmadığının, kamera kayıtları ve lojistik kayıtlarının gerektiği gibi saklanmadığının tespit edilmesi",
c=["Yetki kapsamında işlem görecek eşyanın kontrolü için görevli memura gerekli kolaylığın ve görevini gerçekleştirmesine uygun çalışma ortamının sağlanmaması",
   "Bölge müdürlüğünce tesisin faaliyetinin devam etmesinin risk doğuracağına yönelik somut bir tespit bulunması",
   "Tesis müdürü ve müdür yardımcısı olarak bildirilen kişi hakkında başvuru formunda belirtilen suçlardan dava açıldığı hâlde ilgili kişinin görevine devam etmesi",
   "Tesiste kullanılan lojistik programının gerekli nitelikleri taşımadığının veya usulüne uygun kullanılmadığının tespit edilmesi"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre ilgili tesisin yetkilendirilmesi şu durumlardan birinin varlığında, durum ortadan kalkıncaya kadar askıya alınır: görevli memura gerekli kolaylığın ve uygun çalışma ortamının sağlanmaması; bölge müdürlüğünce tesisin faaliyetinin devam etmesinin risk doğuracağına yönelik somut tespit bulunması; tesis müdürü ve müdür yardımcısı olarak bildirilen temsile yetkili kişi hakkında belirtilen suçlardan dava açıldığı veya mahkûmiyet kararı verildiği hâlde kişinin görevine devam etmesi; lojistik programının gerekli nitelikleri taşımadığının veya usulüne uygun kullanılmadığının tespiti. Tesiste gerekli güvenlik önlemlerinin alınmaması, kamera kayıtları ve lojistik kayıtlarının gerektiği gibi saklanmaması ise askıya alma değil, tesis yetkilendirmesinin iptal sebebidir. En güçlü tuzak 'lojistik' kelimesidir: lojistik programının niteliksizliği askıya alma, lojistik kayıtlarının saklanmaması iptal sebebidir. Bu nedenle doğru cevap 'Tesiste gerekli güvenlik önlemlerinin alınmadığının, kamera kayıtları ve lojistik kayıtlarının gerektiği gibi saklanmadığının tespit edilmesi' seçeneğidir. (MD 6, 7)",
kanit="27-seri no 14.txt | ilgili tesisin yetkilendirilmesi söz konusu durum ortadan kalkıncaya kadar askıya alınır || 27-seri no 14.txt | Tesiste kullanılan lojistik programının gerekli nitelikleri taşımadığının veya usulüne uygun kullanılmadığının tespit edilmesi || 27-seri no 14.txt | Tesiste gerekli güvenlik önlemlerinin alınmadığının, kamera kayıtları ve lojistik kayıtlarının gerektiği gibi saklanmadığının tespit edilmesi || 27-seri no 14.txt | Bölge müdürlüğünce tesisin faaliyetinin devam etmesinin risk doğuracağına yönelik somut bir tespit bulunması",
yuva=["Tesis askıya alma hâli: görevli memura kolaylık ve uygun çalışma ortamı sağlanmaması (listede)",
      "Tesis askıya alma hâli: bölge müdürlüğünün somut risk tespiti (listede)",
      "Tesis askıya alma hâli: dava açılan tesis müdürü veya yardımcısının görevine devamı (listede)",
      "Tesis askıya alma hâli: lojistik programının nitelik veya kullanım eksikliği (listede)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="AYNA-1 Askıya alma ↔ iptal: tesis askı listesinde olmayan (iptal sebebi) ↔ yetki iptal listesinde olmayan (askı sebebi)",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="KAPSAM_DIŞI",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 8, 9",
cek="Yetki iptali: girişi olmayan eşyaya mühürleme, askıdan 90 gün yenilememe, yanlış bilgi veya sahte belge, özel tip dışı mühür; dava açılması askı sebebidir.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre aşağıdakilerden hangisi, izinli gönderici yetkisinin iptal edilmesini gerektiren durumlar arasında yer almaz?"],
d="İlgililer hakkında başvuru formunda belirtilen suçlardan dava açıldığının tespit edilmesi",
c=["Tesise girişi gerçekleşmeyen bir eşya için izinli gönderici yetkisi kapsamında mühürleme ve transit işlemlerinin gerçekleştirildiğinin tespit edilmesi",
   "Yenileme yapılmaması nedeniyle uygulanan askıya alma işleminden itibaren 90 gün içerisinde başvurunun yenilenmemesi",
   "İznin yanlış, eksik bilgilere veya sahte belgelere dayanılarak verildiğinin anlaşılması",
   "Gümrük idaresinden temin edilen özel tipte mühür dışında mühür kullanılması"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yetkisi şu hâllerde iptal edilir: tesise girişi gerçekleşmeyen bir eşya için yetki kapsamında mühürleme ve transit işlemlerinin gerçekleştirildiğinin tespiti; yenileme yapılmaması nedeniyle uygulanan askıya alma işleminden itibaren 90 gün içinde başvurunun yenilenmemesi; iznin yanlış, eksik bilgilere veya sahte belgelere dayanılarak verildiğinin anlaşılması; gümrük idaresinden temin edilen özel tipte mühür dışında mühür kullanılması. İlgililer hakkında başvuru formunda belirtilen suçlardan dava açıldığının veya mahkûmiyet kararı verildiğinin tespiti ise iptal değil askıya alma sebebidir; askı, dava kesin olarak beraatla sonuçlanıncaya veya davalı kişi yönetim kurulu üyeleri ve %10 veya daha fazla paya sahip gerçek kişiler arasından çıkarılıncaya kadar sürer. Suç ve dava ağır bir hâl gibi göründüğünden aday iptal sanabilir; üstelik denizyolu basitleştirmesini düzenleyen Seri No: 8'de, hakkında kesinleşmiş yargı kararı verilen kişinin 60 gün içinde firmayla ilişiğinin kesilmemesi gerçekten iptal sebebidir. Bu Tebliğ ise dava açılmasını veya mahkûmiyet kararı verilmesini askıya alma hâlleri arasında saymıştır. Bu nedenle doğru cevap 'İlgililer hakkında başvuru formunda belirtilen suçlardan dava açıldığının tespit edilmesi' seçeneğidir. (MD 8, 9)",
kanit="27-seri no 14.txt | Aşağıdaki durumlardan birinin varlığı halinde izinli gönderici yetkisi iptal edilir || 27-seri no 14.txt | Gümrük idaresinden temin edilen özel tipte mühür dışında mühür kullanılması || 27-seri no 14.txt | ilgililer hakkında başvuru formunda belirtilen suçlardan dava açıldığının veya mahkûmiyet kararı verildiğinin tespit edilmesi || 27-seri no 14.txt | Davanın kesin olarak beraatla sonuçlandığı veya davalı kişinin || 26-seri no 8.txt | kesinleşmiş yargı kararının verilmiş olması durumunda hakkında yargı kararı verilmiş kişinin 60 gün içerisinde firma ile ilişiğinin kesilmemiş olması",
yuva=["Yetki iptal hâli: tesise girmeyen eşya için mühürleme ve transit işlemi (listede)",
      "Yetki iptal hâli: yenilememe nedeniyle askıya almadan itibaren 90 gün içinde yenilememe (listede)",
      "Yetki iptal hâli: yanlış, eksik bilgi veya sahte belgeye dayalı izin (listede)",
      "Yetki iptal hâli: gümrük idaresinden temin edilmeyen mühür kullanımı (listede)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERSİNE"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="AYNA-1 Askıya alma ↔ iptal: tesis askı listesinde olmayan (iptal sebebi) ↔ yetki iptal listesinde olmayan (askı sebebi)",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 10",
cek="Askı ve iptal kararını Genel Müdürlük gerekçeli bildirir, uygulama tarihini yazar; iptalde yeniden başvuru tarihi bir aydan az, üç yıldan fazla olmaz.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yetkisi ve tesis yetkilendirmesine ilişkin askıya alma ve iptal kararlarının bildirilmesiyle ilgili aşağıdaki ifadeler verilmiştir:",
     "I. Askıya alma ve iptal kararları izin sahibine gerekçeli olarak ilgili bölge müdürlüğünce bildirilir.",
     "II. Yapılan bildirimde askıya alma ve iptal kararının uygulamaya konulacağı tarihe de yer verilir.",
     "III. İptal kararlarında yeniden başvuru yapılabilecek tarih bilgisi de yer alır.",
     "IV. Yeniden başvuru yapılabilecek tarih, bir aydan az ve bir yıldan fazla olmayacak şekilde belirlenir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve III",
c=["I ve II", "III ve IV", "I, II ve III", "II, III ve IV"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yetkisi ve/veya tesis yetkilendirmesinin iptal ve askıya alma kararı izin sahibine gerekçeli olarak Genel Müdürlükçe bildirilir; bu nedenle I yanlıştır. Bildirimde askıya alma ve iptal kararının uygulamaya konulacağı tarihe de yer verilir (II doğru). İptal kararlarında ayrıca yeniden başvuru yapılabilecek tarih bilgisi yer alır (III doğru). Bu tarih; gerekçeye konu ihmalin ortaya çıkardığı riskin boyutu, sürekliliği ve ihmal tarihinden sonra gerekli önlemlerin alınıp alınmadığı dikkate alınarak bir aydan az, üç yıldan fazla olmayacak şekilde belirlenir; IV'teki 'bir yıl' üst sınırı yanlıştır. Bir yıl, bu Tebliğde yenileme başvurusunda yerinde incelemenin yapılmayabileceği süreye; denizyolu basitleştirmesini düzenleyen Seri No: 8'de ise iptalden sonra yeni izin başvurularının reddedildiği döneme aittir. En güçlü tuzak I. önermedir: ön başvuru ve idari yük değerlendirmesinde bölge müdürlüğü görevlidir, ancak askıya alma ve iptal kararlarını Genel Müdürlük bildirir. Bu nedenle doğru cevap 'II ve III' seçeneğidir. (MD 5, 10)",
kanit="27-seri no 14.txt | İzinli gönderici yetkisi ve/veya tesis yetkilendirmesinin iptal ve askıya alma kararı izin sahibine gerekçeli olarak Genel Müdürlükçe bildirilir || 27-seri no 14.txt | Yapılan bildirimde askıya alma ve iptal kararının uygulamaya konulacağı tarihe de yer verilir || 27-seri no 14.txt | İptal kararlarında yeniden başvuru yapılabilecek tarih bilgisi de yer alır || 27-seri no 14.txt | bir aydan az üç yıldan fazla olmayacak şekilde belirlenir || 26-seri no 8.txt | Birinci fıkradaki iptal işlemini müteakip bir yıl içerisinde yapılan izin başvuruları reddedilir",
yuva=["I ve II: bildirimi yapan makamı bölge müdürlüğü sanan, III'ü atlayan aday",
      "III ve IV: yeniden başvuru tarihinin üst sınırını bir yıl sanan aday (bir yıl: yenilemede yerinde incelemenin yapılmayabileceği süre; Seri No: 8'de iptalden sonra başvuruların reddedildiği dönem)",
      "I, II ve III: bildirim makamını bölge müdürlüğü sanan aday (bölge müdürlüğü ön başvuru ve idari yük değerlendirmesinde görevli)",
      "II, III ve IV: üç yıllık üst sınırı yenileme hükmündeki bir yılla karıştıran aday"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "YAKIN-SAYI"],
duzey=["HATIRLAMA"],
profil=[2, 4],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- GÜMRÜK İŞLEMLERİ (md. 12-15) ----------------
dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="SÜRE",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 12",
cek="Muayene öngörülürse muayene, kontrol türünün bildirimini müteakip azami üç saat içinde yetki kapsamı izinli gönderici tesislerinde yapılır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici tesisinden ihraç edilecek eşya için muayenenin öngörülmesi durumunda muayene işleminin ne zaman ve nerede gerçekleştirileceği aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Kontrol türünün bildirimini müteakip azami üç saat içinde, yetki kapsamı izinli gönderici tesislerinde",
c=["Hazır bildiriminin yapılmasını müteakip azami üç saat içinde, yetki kapsamı izinli gönderici tesislerinde",
   "Kontrol türünün bildirimini müteakip azami üç saat içinde, tesisin bağlı bulunduğu gümrük müdürlüğünde",
   "Kontrol türünün bildirimini müteakip azami yirmi dört saat içinde, yetki kapsamı izinli gönderici tesislerinde",
   "Transit beyannamesinin tescilini müteakip azami üç saat içinde, yetki kapsamı izinli gönderici tesislerinde"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici, eşyanın ihraç edilmeye hazır olduğunu gümrük idaresine elektronik ortamda bildirir (hazır bildirimi); ardından gümrük idaresi beyanın hangi kontrol türüne tabi tutulacağını beyan sahibi ile izinli göndericiye elektronik ortamda bildirir. Muayenenin öngörülmesi durumunda muayene, kontrol türünün bildirimini müteakip azami üç saat içinde yetki kapsamı izinli gönderici tesislerinde gerçekleştirilir; eşya muayene yapılana kadar müdahale edilmeksizin tesiste bekletilir. Süre hazır bildiriminden değil, kontrol türünün bildiriminden başlar; muayene gümrük müdürlüğünde değil, tesiste yapılır. Tesisin bağlı bulunduğu gümrük müdürlüğü ihracat beyannamesinin elektronik ortamda tescil edilip onaylandığı yerdir; transit beyannamesinin tescili ise ihracat işlemleri bittikten sonraki aşamadır. Yirmi dört saat, Gümrük Kanunu'nda karayolu transit süresinin aşılmasına ilişkin ilk ceza basamağıdır. Bu nedenle doğru cevap 'Kontrol türünün bildirimini müteakip azami üç saat içinde, yetki kapsamı izinli gönderici tesislerinde' seçeneğidir. (MD 12)",
kanit="27-seri no 14.txt | Muayenenin öngörülmesi durumunda muayene işlemi kontrol türünün bildirimini müteakip azami üç saat içinde yetki kapsamı izinli gönderici tesislerinde gerçekleştirilir || 27-seri no 14.txt | izinli gönderici tesisinin bağlı bulunduğu gümrük müdürlüğünden elektronik ortamda tescil edilerek onaylanır || 48-cezalar.txt | verilen süreleri yirmidört saate kadar aşması",
yuva=["Hazır bildirimi: eşyanın ihraca hazır olduğunun bildirilmesi (sürenin başlangıcı değil)",
      "Tesisin bağlı bulunduğu gümrük müdürlüğü: ihracat beyannamesinin tescil ve onay yeri",
      "GK usulsüzlük cezası: karayolu transit süresinin yirmi dört saate kadar aşılması",
      "Basitleştirilmiş usulde transit beyannamesinin tescili: ihracat işlemleri bittikten sonraki aşama"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU", "YAKIN-SAYI"],
duzey=["HATIRLAMA"],
profil=[2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="YANLIŞ",
z="K",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 12",
cek="Transit beyannamesinde teminat gerekirse izinli gönderici sadece kendisine ait kapsamlı teminatı kullanabilir; götürü teminat sayılmamıştır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yetkisi kapsamında tesisten ihraç edilecek eşyaya ilişkin gümrük işlemleriyle ilgili aşağıdakilerden hangisi yanlıştır?"],
d="Transit beyannamesinde teminat verilmesi gereken hâllerde yetki sahibi sadece kendisine ait götürü teminatı kullanabilir.",
c=["İhraç edilecek eşya, tesislerde taşıma aracına yüklenmeye hazır olarak açık veya kapalı bir yere konulur ya da taşıma aracında yüklü olarak bekletilir.",
   "Eşyanın ihraç edilmeye hazır olduğu izinli gönderici tarafından gümrük idaresine elektronik ortamda bildirilir ve eşya bu bildirim esnasında tesiste hazır bulunur.",
   "Transit beyannamesinin kırmızı hatta işlem görecek olması hâlinde izinli gönderici mührü muayene memurunca sökülür, muayeneyi müteakip yeni mühür izinli gönderici tarafından tatbik edilir.",
   "İhracat beyannamesinin işlemleri bittikten sonra eşya hâlihazırda yüklü değilse taşıta yüklenir ve araca izinli gönderici mührü tatbik edilerek basitleştirilmiş usulde transit beyannamesi tescil edilir."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre transit beyannamesinde teminat verilmesi gereken hâllerde yetki sahibi sadece kendisine ait kapsamlı teminatı kullanabilir; seçenekteki 'götürü teminat' ifadesi bu nedenle yanlıştır. Götürü teminat Gümrük Yönetmeliği'nde birden fazla işlem için verilen ve antrepo işleticilerince de kullanılabilen ayrı bir teminat sistemidir; izinli gönderici başvurusunun koşulu da kapsamlı teminat kullanma veya teminattan vazgeçme iznidir. Diğer seçenekler Tebliğdeki işlem sırasını aynen verir: eşya tesiste yüklenmeye hazır olarak açık veya kapalı bir yere konulur ya da araçta yüklü bekletilir; izinli gönderici hazır bildirimini elektronik ortamda yapar ve eşya bu sırada tesiste bulunur; ihracat beyannamesinin işlemleri bitince araca izinli gönderici mührü tatbik edilerek basitleştirilmiş usulde transit beyannamesi tescil edilir; transit beyannamesi kırmızı hatta işlem görecekse mühür muayene memurunca sökülür, muayeneden sonra yeni mührü izinli gönderici tatbik eder. Bu nedenle doğru cevap 'Transit beyannamesinde teminat verilmesi gereken hâllerde yetki sahibi sadece kendisine ait götürü teminatı kullanabilir.' seçeneğidir. (MD 4, 12)",
kanit="27-seri no 14.txt | Transit beyannamesinde teminat verilmesi gereken hallerde yetki sahibi sadece kendisine ait kapsamlı teminatı kullanabilir || 27-seri no 14.txt | Transit beyannamesinin kırmızı hatta işlem görecek olması halinde muayene memurunca tesislerde izinli gönderici mührü sökülür ve muayeneyi müteakip izinli gönderici tarafından yeni mühür tatbik edilir || 27-seri no 14.txt | taşıma aracına yüklenmeye hazır olarak açık veya kapalı bir yere konulur ya da taşıma aracında yüklü olarak bekletilir || 27-seri no 14.txt | araca izinli gönderici mührü tatbik edilerek basitleştirilmiş usulde transit beyannamesi tescil edilir",
yuva=["Gümrük işlemleri: eşyanın tesiste yüklenmeye hazır konulması veya araçta yüklü bekletilmesi (doğru)",
      "Gümrük işlemleri: hazır bildirimi ve eşyanın bildirim esnasında tesiste bulunması (doğru)",
      "Gümrük işlemleri: kırmızı hatta mührü muayene memuru söker, yeni mührü izinli gönderici tatbik eder (doğru)",
      "Gümrük işlemleri: ihracat işlemleri bitince izinli gönderici mührüyle basitleştirilmiş usulde transit tescili (doğru)"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"],
duzey=["TANIMA"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="DOĞRU",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 13",
cek="Mesai dışında belge kontrolüne tabi ihracat ile muayeneli ihracat ve transit beyannameleri fazla mesai ücretine bağlıdır; diğerleri ücretsiz tamamlanır.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici tesisinde hazır bildirimi sonrasında kontrol türü bildirilen beyannamelere ilişkin işlemlerin mesai saatleri dışında tamamlanmasıyla ilgili aşağıdakilerden hangisi doğrudur?"],
d="Eşyanın muayene edileceği bildirilen transit beyannamelerine ilişkin işlemlerin mesai saatleri dışında tamamlanma talepleri, fazla mesai ücreti yatırılması koşuluyla yerine getirilir.",
c=["Belge kontrolüne tabi tutulacağı bildirilen ihracat beyannamelerine ilişkin işlemler, mesai saatleri dışında fazla mesai ücreti ödenmeksizin tamamlanır.",
   "Eşyanın muayene edilmeyeceği bildirilen transit beyannamelerine ilişkin işlemlerin mesai saatleri dışında tamamlanma talepleri, fazla mesai ücreti yatırılması koşuluyla yerine getirilir.",
   "Belge kontrolüne tabi tutulmayacağı bildirilen ihracat beyannamelerine ilişkin işlemlerin mesai saatleri dışında tamamlanma talepleri, fazla mesai ücreti yatırılması koşuluyla yerine getirilir.",
   "Mesai saatleri dışında fazla mesai ücreti yalnızca eşyanın muayene edileceği bildirilen ihracat beyannameleri için aranır; transit beyannamelerinde aranmaz."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre hazır bildirimi sonrasında belge kontrolüne tabi tutulacağı bildirilen ihracat beyannameleri ile eşyanın muayene edileceği bildirilen ihracat ve transit beyannamelerine ilişkin işlemlerin mesai saatleri dışında tamamlanma talepleri, fazla mesai ücreti yatırılması koşuluyla yerine getirilir. Bu kapsamda yer almayan, belge kontrolüne tabi tutulmayacağı bildirilen ihracat beyannameleri ile eşyanın muayene edilmeyeceği bildirilen ihracat ve transit beyannamelerine ilişkin işlemler ise fazla mesai ücreti ödenmeksizin tamamlanır. Ücreti belirleyen beyannamenin türü değil, bildirilen kontrol türüdür: muayene edileceği bildirilen transit beyannamesi ücrete bağlıdır, muayene edilmeyeceği bildirilen transit beyannamesi ücretsiz tamamlanır. Belge kontrolüne tabi ihracat beyannamesini ücretsiz gösteren, belge kontrolüne tabi olmayan ihracat beyannamesini veya muayenesiz transit beyannamesini ücrete bağlayan seçenekler iki grubun yerini değiştirir; ücreti yalnız muayeneli ihracat beyannamelerine bağlayan seçenek ise 'yalnızca' kaydıyla listeyi daraltır. Bu nedenle doğru cevap 'Eşyanın muayene edileceği bildirilen transit beyannamelerine ilişkin işlemlerin mesai saatleri dışında tamamlanma talepleri, fazla mesai ücreti yatırılması koşuluyla yerine getirilir.' seçeneğidir. (MD 13)",
kanit="27-seri no 14.txt | belge kontrolüne tabi tutulacağı bildirilen ihracat beyannameleri ile eşyanın muayene edileceği bildirilen ihracat ve transit beyannamelerine ilişkin işlemlerin mesai saatleri dışında tamamlanma talepleri, fazla mesai ücreti yatırılması koşuluyla yerine getirilir || 27-seri no 14.txt | belge kontrolüne tabi tutulmayacağı bildirilen ihracat beyannameleri ile eşyanın muayene edilmeyeceği bildirilen ihracat ve transit beyannamelerine ilişkin işlemler fazla mesai ücreti ödenmeksizin tamamlanır",
yuva=["Tebliğ md. 13/1: belge kontrolüne tabi ihracat beyannamesi ücrete bağlıdır (tersine çevrilmiş)",
      "Tebliğ md. 13/2: muayene edilmeyeceği bildirilen transit beyannamesi ücretsiz tamamlanır (tersine çevrilmiş)",
      "Tebliğ md. 13/2: belge kontrolüne tabi tutulmayacağı bildirilen ihracat beyannamesi ücretsiz tamamlanır (tersine çevrilmiş)",
      "Tebliğ md. 13/1: ücret belge kontrollü ihracat ile muayeneli ihracat ve transit beyannamelerinde aranır ('yalnızca' ile daraltılmış)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU", "MUTLAK"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="YANLIŞ",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 14",
cek="Tesiste mühür sökme yetkisi, yetki sahibinin rejim hak sahibi olduğu transit beyanlarıyla gelen araçlarla sınırlıdır; Ek-3 muvafakatnamesi varsa sınır kalkar.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici tesisine mühürlü vaziyette veya kolay ihracat noktaları kullanılarak getirilen araçların işlemlerine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="İzinli gönderici tesisinde mühür sökme yetkisi, yetki sahibinin taşıyıcı sıfatını taşıdığı transit beyanlarıyla tesise gelen araçlarla sınırlıdır.",
c=["İzinli göndericinin Ek-3'te yer alan muvafakatnameye sahip olması durumunda mühür sökme yetkisine ilişkin sınırlama uygulanmaz.",
   "Araç üzerinde bulunan transit beyanlarına ilişkin transit refakat belgelerine yeni mühür numarası elle yazılır ve izinli gönderici kaşesi vurularak imzalanır.",
   "Kolay ihracat noktaları uygulaması kapsamında herhangi bir gümrük idaresinden tescil edilen ihracat beyannamesi kapsamı eşya, transit beyannamesi ve mühür tatbiki olmaksızın doğrudan izinli gönderici tesisine getirilebilir.",
   "Kolay ihracat noktaları uygulaması kapsamında tesise getirilen eşyaya ilişkin hazır bildirimi, tesisin bağlı bulunduğu gümrük müdürlüğüne iletilebilir."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici tesisinde mühür sökme yetkisi sadece yetki sahibinin rejim hak sahibi olduğu transit beyanlarıyla tesise gelen araçlarla sınırlıdır; seçenekteki 'taşıyıcı sıfatı' ifadesi bu nedenle yanlıştır. Taşıyıcı sıfatı Tebliğde yalnızca başvuru koşullarındaki transit beyanı sayısının ikinci seçeneğinde (en az 500 transit beyanı) geçer. İzinli gönderici Ek-3'teki muvafakatnameye sahipse bu sınırlama uygulanmaz; araç üzerindeki transit beyanlarına ilişkin refakat belgelerine yeni mühür numarası elle yazılır ve izinli gönderici kaşesi vurularak imzalanır. Kolay ihracat noktaları uygulamasında herhangi bir gümrük idaresinden tescil edilen ihracat beyannamesi kapsamı eşya transit beyannamesi ve mühür olmadan doğrudan tesise getirilebilir; hazır bildirimi tesisin bağlı bulunduğu gümrük müdürlüğüne iletilebilir. Bu nedenle doğru cevap 'İzinli gönderici tesisinde mühür sökme yetkisi, yetki sahibinin taşıyıcı sıfatını taşıdığı transit beyanlarıyla tesise gelen araçlarla sınırlıdır.' seçeneğidir. (MD 4, 14)",
kanit="27-seri no 14.txt | İzinli gönderici tesisinde mühür sökme yetkisi sadece yetki sahibinin rejim hak sahibi olduğu transit beyanlarıyla tesise gelen araçlarla sınırlıdır || 27-seri no 14.txt | İzinli göndericinin Ek-3'te yer alan muvafakatnameye sahip olması durumunda birinci fıkrada yer alan sınırlama uygulanmaz || 27-seri no 14.txt | transit refakat belgelerine yeni mühür numarası elle yazılır ve izinli gönderici kaşesi vurularak imzalanır || 27-seri no 14.txt | bu eşyaya ilişkin hazır bildirimi tesisin bağlı bulunduğu gümrük müdürlüğüne iletilebilir",
yuva=["Muvafakatname varsa mühür sökme sınırlaması uygulanmaz (doğru)",
      "Refakat belgesine yeni mühür numarasının elle yazılması ve kaşe-imza (doğru)",
      "Kolay ihracat: herhangi bir gümrük idaresinden tescilli eşyanın beyan ve mühürsüz getirilmesi (doğru)",
      "Kolay ihracat: hazır bildiriminin tesisin bağlı bulunduğu gümrük müdürlüğüne iletilmesi (doğru)"],
yakinlik="BİREBİR",
tuzak=["TERİM"],
duzey=["TANIMA"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="DOĞRU",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 15",
cek="İYG tesisinden ihraç eşyasının transit beyanını izinli gönderici rejim hak sahibi olarak basitleştirilmiş usulde verir; yer alanına İYG tesis kodu girilir.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre ihracatta yerinde gümrükleme izni sahibi firmaların tesislerinden ihraç edilecek eşyanın taşınmasına ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Transit beyanı, izinli gönderici yetkisi sahibi tarafından rejim hak sahibi olarak basitleştirilmiş usulde verilebilir.",
c=["Transit beyanı, ihracatta yerinde gümrükleme izni sahibi firma tarafından rejim hak sahibi olarak basitleştirilmiş usulde verilir.",
   "İhracat beyannamesi, kolay ihracat noktaları uygulamasına özgü basitleştirilmiş işlem koduyla tescil edilir.",
   "Transit beyannamesinde eşyanın bulunduğu yer alanına izinli gönderici tesis kodu girilir.",
   "İzinli gönderici mührü, eşya izinli gönderici tesisine getirildikten sonra bu tesiste tatbik edilir."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre ihracatta yerinde gümrükleme izni sahibi firmaların tesislerinden ihraç edilecek eşyanın transit beyanını izinli gönderici yetkisi sahibi, rejim hak sahibi olarak basitleştirilmiş usulde verebilir. Bu durumda ihracat beyannamesi ihracatta yerinde gümrüklemeye özgü basitleştirilmiş işlem koduyla tescil edilir; ihracat beyannamesinin işlemleri tamamlandıktan sonra eşyanın bulunduğu yer alanına ihracatta yerinde gümrükleme tesis kodu girilerek basitleştirilmiş usulde transit beyannamesi tescil edilir ve izinli gönderici mührü ihracatta yerinde gümrükleme tesislerinde tatbik edilir. Rejim hak sahibi ihracatta yerinde gümrükleme izni sahibi firma değil, izinli göndericidir; en güçlü çeldirici bu iki kişiyi yer değiştiren seçenektir. Eşya izinli gönderici tesisine getirilmez; kolay ihracat noktaları uygulaması ise başka gümrük idarelerinde tescil edilen ihracat beyannamesi kapsamı eşyanın izinli gönderici tesisine getirilmesine ilişkindir. Bu nedenle doğru cevap 'Transit beyanı, izinli gönderici yetkisi sahibi tarafından rejim hak sahibi olarak basitleştirilmiş usulde verilebilir.' seçeneğidir. (MD 15)",
kanit="27-seri no 14.txt | İhracatta yerinde gümrükleme izni sahibi firmaların tesislerinden ihraç edilecek eşyanın transit beyanını izinli gönderici yetkisi sahibi rejim hak sahibi olarak basitleştirilmiş usulde verebilir || 27-seri no 14.txt | ihracat beyannamesi ihracatta yerinde gümrüklemeye özgü basitleştirilmiş işlem koduyla tescil edilir || 27-seri no 14.txt | eşyanın bulunduğu yer alanına ihracatta yerinde gümrükleme tesis kodu girilerek basitleştirilmiş usulde transit beyannamesi tescil edilir ve ihracatta yerinde gümrükleme tesislerinde izinli gönderici mührü tatbik edilir",
yuva=["Aynı hüküm: rejim hak sahibi izinli gönderici yetkisi sahibidir (kişiler yer değiştirilmiş)",
      "Aynı hüküm: işlem kodu ihracatta yerinde gümrüklemeye özgüdür; kolay ihracat noktaları tanımdaki komşu uygulama",
      "Aynı hüküm: yer alanına ihracatta yerinde gümrükleme tesis kodu girilir",
      "Aynı hüküm: mühür ihracatta yerinde gümrükleme tesislerinde tatbik edilir; tesise getirme kolay ihracat noktalarına özgüdür"],
yakinlik="PARAFRAZ",
tuzak=["TERİM", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- YOLDA EŞYA ALINMASI VE MÜHÜR (md. 16-18) ----------------
dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="YETKİ",
z="Z",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 14, 16, 17",
cek="Yolda antrepodan eşya alınırsa mühür işlemini yetkilendirilmiş gümrük müşaviri veya antrepodaki gümrük memuru, gümrük idaresinden alınırsa gümrük idaresi yapar.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici tesisinden çıkış yapıldıktan sonra antrepodan serbest dolaşımda olmayan eşya veya gümrük idaresinden eşya alınması hâllerinde, yüklü aracın mührünün sökülmesi ve eşya yüklendikten sonra yeni mühür tatbiki işlemlerini yapacak olanlar aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Antrepodan alınmada yetkilendirilmiş gümrük müşaviri veya antrepoda görevli gümrük memuru; gümrük idaresinden alınmada gümrük idaresi",
c=["Her iki hâlde de yetkilendirilmiş gümrük müşaviri veya ilgili gümrük idaresinde görevli gümrük memuru",
   "Antrepodan alınmada antrepo işleticisi veya antrepoda görevli gümrük memuru; gümrük idaresinden alınmada gümrük idaresi",
   "Antrepodan alınmada yetkilendirilmiş gümrük müşaviri veya antrepoda görevli gümrük memuru; gümrük idaresinden alınmada izinli gönderici",
   "Her iki hâlde de, yetki sahibinin rejim hak sahibi olması kaydıyla izinli gönderici"],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yahut ihracatta yerinde gümrükleme tesisinden çıkış yapıldıktan sonra antrepodan serbest dolaşımda olmayan eşya alınabilir; bu durumda yüklü aracın mührünün sökülmesi ve eşya yüklendikten sonra yeni mühür tatbiki işlemleri yetkilendirilmiş gümrük müşaviri veya antrepoda görevli gümrük memuru tarafından yapılır. Aynı şekilde gümrük idaresinden de eşya alınabilir; bu durumda mühür sökme ve yeni mühür tatbiki işlemlerini gümrük idaresi yapar, refakat belgelerine yeni mühür numarasını da gümrük idaresi yazar. Gümrük müşavirinin bu işlemdeki yetkisi antrepodan eşya alınmasıyla sınırlıdır; 'her iki hâlde de gümrük müşaviri' seçeneği, müşavirin her işlemde yetkili olduğunu düşünen adayı yakalar. Antrepo işleticisi sağduyuya yatkın görünse de Tebliğde mühür işlemini yapacaklar arasında sayılmamıştır; izinli göndericinin mühür sökme yetkisi ise kendi tesisine gelen araçlarla ilgilidir. Bu nedenle doğru cevap 'Antrepodan alınmada yetkilendirilmiş gümrük müşaviri veya antrepoda görevli gümrük memuru; gümrük idaresinden alınmada gümrük idaresi' seçeneğidir. (MD 14, 16, 17)",
kanit="27-seri no 14.txt | yüklü aracın mührünün sökülmesi ve eşya yüklendikten sonra yeni mühür tatbiki işlemleri yetkilendirilmiş gümrük müşaviri veya antrepoda görevli gümrük memuru tarafından yapılır || 27-seri no 14.txt | yüklü aracın mührünün sökülmesi ve eşya yüklendikten sonra yeni mühür tatbiki işlemleri gümrük idaresi tarafından yapılır || 27-seri no 14.txt | mevcut transit refakat belgelerine yeni mühür numarası gümrük idaresi tarafından elle yazılır ve mühür vurulur",
yuva=["Antrepodan eşya alınması hükmündeki yetkilendirilmiş gümrük müşavirini gümrük idaresinden alınmaya da taşıyan okuma (meslek yanlılığı)",
      "Antrepo rejiminde geçen antrepo işleticisi (Tebliğde mühür işlemi yapanlar arasında yok; sağduyu)",
      "Tesise mühürlü gelen araçlarda izinli göndericinin mühür sökme yetkisi (gümrük idaresinden alınmaya taşınmış)",
      "Tesise gelen araçlarda rejim hak sahibi izinli göndericinin mühür sökme yetkisi (yoldaki alımlara genellenmiş)"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "SAĞDUYU", "KOMŞU"],
duzey=["AYIRT"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="AYNA-2 Antrepodan eşya alınması ↔ gümrük idaresinden eşya alınması (mühür işlemini yapan)",
guncellik="",
cikmis="",
kapsamli=False,
),

dict(
konu="Transit Tebliği (Seri No: 14)", blok="SB26",
kalip="DOĞRU",
z="O",
madde="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14) md. 9, 18",
cek="Özel tipte mühür gümrük idaresinden ücretle alınır; İYG tesisinde mühürleme dışında tesiste saklanır, dışarı çıkarılamaz; bozuk, kırılan, sökülen mühür kaydedilir.",
kok=["Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yetkisi sahiplerinin özel tipte mühür kullanımına ilişkin aşağıdakilerden hangisi doğrudur?"],
d="İhracatta yerinde gümrükleme tesisinde mühürleme yapılacak durumlar haricinde mühürler izinli gönderici tesisinde muhafaza edilir ve tesis dışına çıkarılamaz.",
c=["Özel tipte mühürler gümrük idaresinden ücretsiz olarak temin edilir.",
   "İzinli gönderici yetkisi sahipleri, Sözleşmeye uygun olmak kaydıyla gümrük idaresi dışından temin ettikleri mühürleri de kullanabilir.",
   "İhracatta yerinde gümrükleme tesisinde mühürleme yapılacak durumlarda taşıyıcıya teslim edilen mühürlerin ayrıca kayıt altına alınması gerekmez.",
   "Bozuk çıkan veya tatbik esnasında kırılan mühürler kayıt altına alınır; sökülen mühürlerin ise kayıt altına alınması gerekmez."],
sirali=False,
g="Gümrük Genel Tebliği (Transit Rejimi) (Seri No: 14)'e göre izinli gönderici yetkisi sahipleri, gümrük idaresinden ücreti karşılığında temin edilecek ve Sözleşmeye uygun özel tipte mühür kullanır. İhracatta yerinde gümrükleme tesisinde mühürleme yapılacak durumlarda taşıyıcıya teslim edilen mühürler; teslim alan taşımacı, teslim tarihi, mühür numaraları ve ihracatta yerinde gümrükleme izin sahibinin unvanını içerecek şekilde ayrıca kayıt altına alınır. Bu durum haricinde mühürler izinli gönderici tesisinde muhafaza edilir ve tesis dışına çıkarılamaz. Bozuk çıkan, tatbik esnasında kırılan veya sökülen mühürlerin üçü de ayrıca kayıt altına alınır. Gümrük idaresinden temin edilen özel tipte mühür dışında mühür kullanılması izinli gönderici yetkisinin iptal sebebidir; bu yüzden başka kaynaktan mühür kullanılabileceği yönündeki seçenek en güçlü çeldiricidir. Bu nedenle doğru cevap 'İhracatta yerinde gümrükleme tesisinde mühürleme yapılacak durumlar haricinde mühürler izinli gönderici tesisinde muhafaza edilir ve tesis dışına çıkarılamaz.' seçeneğidir. (MD 9, 18)",
kanit="27-seri no 14.txt | Bu durum haricinde mühürler izinli gönderici tesisinde muhafaza edilir ve tesis dışına çıkarılamaz || 27-seri no 14.txt | gümrük idaresinden ücreti karşılığında temin edilecek || 27-seri no 14.txt | Bozuk çıkan, tatbik esnasında kırılan veya sökülen mühürler ayrıca kayıt altına alınır || 27-seri no 14.txt | Gümrük idaresinden temin edilen özel tipte mühür dışında mühür kullanılması",
yuva=["Aynı hüküm: mühürler gümrük idaresinden ücreti karşılığında temin edilir (tersine)",
      "Yetki iptal hâli: gümrük idaresinden temin edilen özel tipte mühür dışında mühür kullanılması",
      "Aynı hüküm: İYG tesisinde taşıyıcıya teslim edilen mühürler ayrıca kayıt altına alınır (tersine)",
      "Aynı hüküm: bozuk, kırılan ve sökülen mühürlerin üçü de kayıt altına alınır (unsur düşürülmüş)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "UNSUR", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[4],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

]
