# Soru Bankası — Bölüm 28: Gümrük Antrepoları ve İşleticileri (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
# Kaynak: 29-iŞLETİCİLER.txt (GY 518-559, GK 47-50, GY 77-98/A, GY 512-517)
Q = [

# 1 — Yolcu eşyası ambarı / teslim alınan kişisel kara taşıtı: üç ay + üç ay (vaka)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="SÜRE",
z="O",
madde="Gümrük Yönetmeliği md. 79, 417; 4458 sayılı Gümrük Kanunu md. 46",
cek="Üç ay kalış ve mücbir sebep aranmaksızın üç ay uzatma, teslim alınan kişisel taşıt ile yolcu eşyasına özgüdür; ağır-havaleli eşya, ihraç ve denizyolu eşyasına uygulanmaz.",
kok=["Gümrük Yönetmeliği'nin geçici depolama yerlerine ilişkin hükümlerine göre aşağıdakilerden hangisi, geçici depolama yerinde ya da geçici depolama yeri addolunan yerde üç ay kalabilen ve bu süresi talep hâlinde mücbir sebep belgesi aranmaksızın ilgili gümrük müdürlüğünce üç aya kadar uzatılabilen eşyadır?"],
d="Tam muafiyetle geçici ithal edilmiş olup yurt dışı edilmek üzere gümrük idaresince teslim alınan kişisel kullanıma mahsus kara taşıtı",
c=["Limanlardaki geçici depolama yerlerinin mütemmim cüz'ü niteliğindeki açık alanlara konulan ağır ve havaleli eşya",
   "İhracat veya yeniden ihracat amacıyla geçici depolama yerine konulması talep edilen eşya",
   "Denizyolu ile gelen ve özet beyan kapsamında geçici depolama yerine konulan eşya",
   "Denizyolu dışındaki bir yolla gelen ve özet beyan kapsamında geçici depolama yerine konulan eşya"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre limanlardaki geçici depolama yerlerinin mütemmim cüz'ü niteliğindeki ağır ve havaleli eşyaya mahsus açık alanlar, yolcu eşyasına mahsus gümrük ambarları ve ithalat vergilerinden tam muafiyet suretiyle geçici ithal edilip yurt dışı edilmek ya da gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulmak üzere gümrük idarelerince teslim alınan kişisel kullanıma mahsus kara taşıtlarının konulduğu yerler geçici depolama yeri addolunur. Aynı hükme göre buralarda üç ay kalabilen ve bu süresi talep hâlinde mücbir sebep belgesi aranmaksızın ilgili gümrük müdürlüğünce üç aya kadar uzatılabilen eşya yalnızca yolcu eşyası ve taşıtlardır; ağır ve havaleli eşya bu cümlenin öznesi değildir. İhracat veya yeniden ihracat amacıyla geçici depolama yerine konulan eşya bir ay kalabilir ve gümrük müdürlüklerince en çok üç aya kadar ek süre verilebilir. Özet beyan kapsamındaki eşyada gümrükçe onaylanmış işlem veya kullanıma ilişkin işlemler, Gümrük Kanunu'na göre denizyolu ile gelen eşyada özet beyanın verildiği tarihten itibaren kırk beş günde, diğer yollarla gelen eşyada yirmi günde tamamlanır. En güçlü çeldirici ağır ve havaleli eşyadır: aynı cümlede geçici depolama yeri addolunan yerler arasında sayılır, ancak üç aylık süre yalnızca yolcu eşyası ve taşıtlar için öngörülmüştür. Bu nedenle doğru cevap 'Tam muafiyetle geçici ithal edilmiş olup yurt dışı edilmek üzere gümrük idaresince teslim alınan kişisel kullanıma mahsus kara taşıtı' seçeneğidir. (MD GY 79, 417; GK 46)",
kanit="29-iŞLETİCİLER.txt | teslim alınan kişisel kullanıma mahsus kara taşıtlarının konulduğu yerler de geçici depolama yeri addolunur. Yolcu eşyası ve taşıtlar buralarda üç ay kalabilir. Bu süre, talep halinde mücbir sebep belgesi aranmaksızın ilgili gümrük müdürlüğünce üç aya kadar uzatılabilir. || 29-iŞLETİCİLER.txt | Ağır ve havaleli eşyanın konulmasına mahsus olmak üzere, limanlar gibi gümrük işlemlerinin yapıldığı yerlerde bulunan geçici depolama yerlerinin mütemmim cüz'ü niteliğindeki açık alanlar || 36-ihracat.txt | geçici depolama yerlerine konulması talep edilen eşya, buralarda bir ay kalabilir || 16-GOBİK VE SAHTE EŞYA.txt | Denizyolu ile gelen eşya için, özet beyan verildiği tarihten itibaren kırk beş gün || 16-GOBİK VE SAHTE EŞYA.txt | Diğer bir yolla gelen eşya için, özet beyanın verildiği tarihten itibaren yirmi gün",
yuva=["GY 79/2: ağır ve havaleli eşya açık alanları aynı cümlede addolunan yer sayılır, ancak üç aylık süre yolcu eşyası ve taşıtlara özgüdür",
      "GY 417: ihracat amaçlı geçici depolamada bir ay kalış, gümrük müdürlüklerince en çok üç ay ek süre",
      "GK 46/2-a: denizyolu ile gelen eşyada özet beyandan itibaren kırk beş gün",
      "GK 46/2-b: diğer yollarla gelen eşyada özet beyandan itibaren yirmi gün"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "YAKIN-SAYI", "SAYI"], duzey=["AYIRT"], profil=[2],
olumsuz=False, vaka=False, baslangic=False, eksen=13, ayna="", guncellik="", cikmis="2021/40; 2023/50; 2025/80; 2025/94", kapsamli=False,
),

# 2 — GK 47-50 önermeli (statü, teminat "isteyebilir", elleçleme, tasfiye şartı)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="TANIM",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 3, 47; Gümrük Yönetmeliği md. 77",
cek="Geçici depolanan eşya, gümrüğe sunuştan gümrükçe onaylanmış işlem veya kullanıma tabi tutuluncaya kadarki statüdür; antrepo, transit, geçici ithalat birer rejimdir.",
kok=["4458 sayılı Gümrük Kanunu'na göre \"geçici depolanan eşya\" statüsünde bulunan ve bu şekilde adlandırılan eşya aşağıdakilerden hangisidir?"],
d="Gümrüğe sunulmasından sonra gümrükçe onaylanmış bir işlem veya kullanıma tabi tutuluncaya kadar bekleyen eşya",
c=["Özet beyanı verilmiş olmakla birlikte henüz gümrüğe sunulmamış eşya",
   "Gümrük antrepo rejimine tabi tutularak gümrük antreposuna konulmuş ve antrepodan çıkarılıncaya kadar bekleyen eşya",
   "Transit rejimine tabi tutularak hareket gümrük idaresinden sevk edilmiş ve varış gümrük idaresine sunuluncaya kadar yolda bulunan eşya",
   "Geçici ithalat rejimine tabi tutularak ithalat vergilerinden tamamen veya kısmen muaf olarak Türkiye Gümrük Bölgesi içinde kullanılan eşya"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre eşya, gümrüğe sunulmasından sonra gümrükçe onaylanmış bir işlem veya kullanıma tabi tutuluncaya kadar geçici depolanan eşya statüsünde bulunur ve bu şekilde adlandırılır. Statü gümrüğe sunuşla başlar ve eşyanın gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulmasıyla sona erer; geçici depolama bir gümrük rejimi değil, rejim beyanına kadar süren bir statüdür. Özet beyan eşyanın gümrüğe sunulmasından önce de verilebilir; ancak Gümrük Yönetmeliği'ne göre bu durumda Kanundaki geçici depolama süreleri eşyanın gümrüğe sunulduğu tarihten başlar, yani statü sunuşla doğar. Gümrük antrepo rejimi, transit rejimi ve geçici ithalat rejimi ise Kanunda sayılan gümrük rejimleridir; eşyanın bir gümrük rejimine tabi tutulması gümrükçe onaylanmış bir işlem veya kullanım olduğundan geçici depolanan eşya statüsünü sona erdirir. En güçlü çeldirici antrepoya konulan eşyadır: antrepo da gümrük gözetimi altındaki eşyanın konulduğu bir yerdir, ancak eşya oraya bir rejim beyanıyla girer. Bu nedenle doğru cevap 'Gümrüğe sunulmasından sonra gümrükçe onaylanmış bir işlem veya kullanıma tabi tutuluncaya kadar bekleyen eşya' seçeneğidir. (MD GK 3, 47; GY 77)",
kanit="29-iŞLETİCİLER.txt | Eşya, gümrüğe sunulmasından sonra gümrükçe onaylanmış bir işlem veya kullanıma tabi tutuluncaya kadar geçici depolanan eşya statüsünde bulunur ve bu şekilde adlandırılır || 29-iŞLETİCİLER.txt | Özet beyanın eşyanın gümrüğe sunulmasından önce verildiği hallerde, Kanunun 46 ncı maddesinde belirtilen süreler eşyanın gümrüğe sunulduğu tarihten itibaren başlar || 1-TANIMLAR.txt | Bir gümrük rejimine tabi tutulmasını || 1-TANIMLAR.txt | Gümrük antrepo rejimini || 28-antrepo rejimi.txt | Gümrük antreposu, gümrük gözetimi altında bulunan eşyanın konulması amacıyla kurulan",
yuva=["GY 77/2: özet beyan sunuştan önce verilebilir, ancak süreler sunuşla başlar (statü sunuştan önce doğmaz)",
      "GK 3 ve 93: gümrük antrepo rejimi bir gümrük rejimidir; antrepoya konma GOİK'tir (2024 sınavındaki karıştırma)",
      "GK 3: transit rejimi bir gümrük rejimidir; transite tabi tutma GOİK'tir",
      "GK 128: geçici ithalat rejimi; rejime tabi tutma GOİK'tir"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU", "BAŞLANGIÇ"], duzey=["TANIMA"], profil=[3],
olumsuz=False, vaka=False, baslangic=False, eksen=10, ayna="", guncellik="", cikmis="2024/100", kapsamli=False,
),

# 3 — Yaygın götürü teminat başvurusu: eşit dağılımda şirket merkezinin bağlı olduğu bölge müdürlüğü (vaka)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="YANLIŞ",
z="Z",
madde="Gümrük Yönetmeliği md. 527",
cek="Yaygın götürü teminat başvurusu en fazla antreponun bulunduğu bölge müdürlüğüne, belirlenemezse şirket merkezinin bağlı olduğu bölge müdürlüğüne yapılır; Bakanlığa yapılmaz.",
kok=["Gümrük Yönetmeliği'nin antrepo işleticilerince verilecek götürü ve yaygın götürü teminata ilişkin hükümlerine göre aşağıdakilerden hangisi yanlıştır?"],
d="Yaygın götürü teminat kullanılması talep edilen antrepolar birden fazla bölge müdürlüğü bağlantısı gümrük müdürlüğünün denetimindeyse başvuru, işleticinin en fazla antreposunun bulunduğu bölge müdürlüğüne, bu şekilde belirleme yapılamazsa Bakanlığa yapılır.",
c=["Götürü teminat verilen antrepoya konulan eşya için başka bir teminat aranmaz.",
   "Birden fazla antreposu bulunan antrepo işleticilerince, birden fazla antrepoyu kapsayacak şekilde yaygın götürü teminat verilebilir.",
   "Yaygın götürü teminatın kullanılacağı antrepo sayısının 5 ve üzeri olduğu durumda, hesaplanan götürü teminatların toplam tutarının %75'i kadar yaygın götürü teminat verilebilir.",
   "Alan veya hacim değişikliği nedeniyle mevcut teminat tutarı yetersiz kalırsa ek teminat mektubu, değişikliği takip eden bir ay içerisinde önceki teminatın verildiği bölge müdürlüğüne verilir."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre antrepo işleticilerince antrepo rejiminde kullanılmak üzere götürü teminat verilebilir ve götürü teminat verilen antrepoya konulan eşya için başka bir teminat aranmaz. Birden fazla antreposu bulunan işleticiler, birden fazla antrepoyu kapsayacak şekilde yaygın götürü teminat verebilir; yaygın götürü teminatın kullanılacağı antrepo sayısı 5 ve üzerindeyse hesaplanan götürü teminatların toplam tutarının %75'i kadar yaygın götürü teminat verilebilir. Alan veya hacim değişikliği nedeniyle teminat yetersiz kalırsa ek teminat mektubu, değişikliği takip eden bir ay içinde önceki teminatın verildiği bölge müdürlüğüne verilir. Yaygın götürü teminat başvuruları ilgili bölge müdürlüğüne yapılır; antrepolar birden fazla bölge müdürlüğü bağlantısı gümrük müdürlüğünün denetimindeyse başvuru, işleticinin bu kapsamdaki en fazla antreposunun bulunduğu bölge müdürlüğüne, bu şekilde belirleme yapılamazsa (örneğin antrepolar iki bölgeye eşit dağılmışsa) Bakanlığa değil, işleticinin şirket merkezinin bulunduğu ilin bağlı olduğu bölge müdürlüğüne yapılır ve işlemler bölge müdürlüğünce sonuçlandırılır. Yanlış seçenekte belirleme yapılamayan hâldeki makam değiştirilmiştir. Bu nedenle doğru cevap 'Yaygın götürü teminat kullanılması talep edilen antrepolar birden fazla bölge müdürlüğü bağlantısı gümrük müdürlüğünün denetimindeyse başvuru, işleticinin en fazla antreposunun bulunduğu bölge müdürlüğüne, bu şekilde belirleme yapılamazsa Bakanlığa yapılır.' seçeneğidir. (MD GY 527)",
kanit="29-iŞLETİCİLER.txt | Yaygın götürü teminata ilişkin başvurular, ilgili bölge müdürlüğüne yapılır. Yaygın götürü teminat kullanılması talep edilen antrepoların, birden fazla bölge müdürlüğü bağlantısı gümrük müdürlüğü denetiminde olması halinde başvuru, antrepo işleticisinin bu kapsamdaki en fazla antreposunun bulunduğu bölge müdürlüğüne, bu şekilde belirleme yapılamaması halinde antrepo işleticisinin şirket merkezinin bulunduğu ilin bağlı olduğu bölge müdürlüğüne yapılır. || 29-iŞLETİCİLER.txt | Götürü teminat verilen antrepoya konulan eşya için başka bir teminat aranmaz || 29-iŞLETİCİLER.txt | Birden fazla antreposu bulunan antrepo işleticilerince, birden fazla antrepoyu kapsayacak şekilde yaygın götürü teminat verilebilir || 29-iŞLETİCİLER.txt | ikinci fıkra uyarınca hesaplanan götürü teminatların toplam tutarının % 75'i kadar yaygın götürü teminat verilebilir || 29-iŞLETİCİLER.txt | değişikliği takip eden bir ay içerisinde önceki teminatın verildiği bölge müdürlüğüne verilir",
yuva=["GY 527/1: götürü teminat verilen antrepoda başka teminat aranmaz (doğru)",
      "GY 527/4: birden fazla antrepo için yaygın götürü teminat (doğru)",
      "GY 527/5: beş ve üzeri antrepoda toplamın %75'i (doğru)",
      "GY 527/7: alan veya hacim değişikliğinde bir ay içinde ek teminat (doğru)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "İSTİSNA", "KOMŞU"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2025/81", kapsamli=False,
),

# 4 — Özel antrepoda yatırım izni aranmaz (akaryakıt hariç)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="KAPSAM_DIŞI",
z="Z",
madde="Gümrük Yönetmeliği md. 518, 520, 521, 534",
cek="Akaryakıt antrepoları hariç özel antrepolar için yatırım izni aranmaz; sicil, kesinleşmiş vergi-ceza borcu yokluğu, Ek-81 taahhütname ve Ek-80 nitelikleri aranır.",
kok=["Gümrük Yönetmeliği'ne göre makine ve yedek parça depolamak amacıyla özel antrepo açıp işletmek isteyen bir anonim şirket bakımından aşağıdakilerden hangisi aranmaz?"],
d="Yatırım yapmadan önce antreponun bağlı bulunacağı gümrük müdürlüğüne başvurularak yatırım izni alınması",
c=["Yönetim kurulu başkan ve üyeleri ile şirket sermayesinin %10 veya daha fazlasına sahip gerçek kişiler hakkında sayılan suçlardan kesinleşmiş mahkumiyet kararı bulunmaması",
   "Gümrük mevzuatı uyarınca kesinleşmiş vergi ve ceza borcu ile vergi mevzuatı uyarınca kesinleşmiş vergi borcu bulunmaması",
   "Başvurunun Ek-81'de yer alan taahhütname ile antreponun bağlı bulunacağı gümrük müdürlüğüne yapılması",
   "Antrepo olarak kullanılacak alanların Ek-80'de antrepolarda aranacak şart ve nitelikler olarak belirtilen koşulları taşıması"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre antrepo açma ve işletme izni almak üzere başvuracak kişiler kural olarak yatırım yapmadan önce antreponun bağlı bulunacağı gümrük müdürlüğüne dilekçeyle başvurur ve yatırım izni talepleri Bakanlıkça sonuçlandırılır; ancak akaryakıt antrepoları hariç olmak üzere özel antrepolar için yatırım izni aranmaz. Makine ve yedek parça depolanacak özel antrepo akaryakıt antreposu olmadığından yatırım izni aranmaz. Buna karşılık antrepo açma izni için anonim şirketin yönetim kurulu başkan ve üyeleri ile sermayenin %10 veya daha fazlasına sahip gerçek kişiler hakkında sayılan suçlardan kesinleşmiş mahkumiyet kararı bulunmaması, şirketin gümrük mevzuatı uyarınca kesinleşmiş vergi ve ceza borcu ile vergi mevzuatı uyarınca kesinleşmiş vergi borcu bulunmaması, başvurunun Ek-80'deki belgeler ve Ek-81'deki taahhütnameyle yapılması ve kullanılacak alanların Ek-80'deki şart ve nitelikleri taşıması aranır. En güçlü çeldirici sicil şartıdır: bu şart yatırım iznine ilişkin hükümde yer aldığı için yalnız yatırım iznine bağlı sanılır; oysa antrepo açma izni almak üzere başvuracak anonim şirketlerin tümü için aranır. Bu nedenle doğru cevap 'Yatırım yapmadan önce antreponun bağlı bulunacağı gümrük müdürlüğüne başvurularak yatırım izni alınması' seçeneğidir. (MD GY 518, 520, 521, 534)",
kanit="29-iŞLETİCİLER.txt | Akaryakıt antrepoları hariç olmak üzere, özel antrepolar için yatırım izni aranmaz || 29-iŞLETİCİLER.txt | Antrepo açma izni almak üzere başvuracak anonim şirketlerin yönetim kurulu başkan ve üyeleri ile şirketlerde || 29-iŞLETİCİLER.txt | gümrük mevzuatı uyarınca kesinleşmiş vergi ve ceza borcu ile vergi mevzuatı uyarınca kesinleşmiş vergi borcu bulunmaması şarttır || 29-iŞLETİCİLER.txt | Ek-81'de yer alan taahhütname ile antreponun bağlı bulunacağı gümrük müdürlüğüne başvuruda bulunmaları gerekir || 29-iŞLETİCİLER.txt | Genel ve özel antrepo olarak kullanılacak kapalı ve/veya açık alanlarda Ek-80'in",
yuva=["Antrepo açma izni için yöneticiler ve %10 ortaklarda sicil şartı (GY 518/3)",
      "Kesinleşmiş vergi ve ceza borcu bulunmaması şartı (GY 521/6)",
      "Başvuru belgeleri ve Ek-81 taahhütname (GY 520/1)",
      "Genel ve özel antrepolarda aranacak Ek-80 şart ve nitelikleri (GY 534/1)"],
yakinlik="PARAFRAZ",
tuzak=["İSTİSNA", "KOMŞU"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2025/84", kapsamli=False,
),

# 5 — Yatırım izninden sonra altı ay; başlangıç bildirim tarihi
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="SÜRE",
z="O",
madde="Gümrük Yönetmeliği md. 518",
cek="Yatırım izni sahibi, kendisine yapılan bildirim tarihinden itibaren altı ay içinde tesisi hazırlayıp gümrük müdürlüğüne başvurur; ek süre Bakanlıktan istenir.",
kok=["Gümrük Yönetmeliği'ne göre antrepo yatırım izni verilen başvuru sahibinin, antrepo olarak açılmak istenen tesisi hazır hâle getirerek ilgili gümrük müdürlüğüne başvurması gereken süre aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Kendisine yapılacak bildirim tarihinden itibaren altı ay içinde",
c=["Yatırım izni başvurusunun yapıldığı tarihten itibaren altı ay içinde",
   "Bakanlıkça yatırım izni verildiği tarihten itibaren altı ay içinde",
   "Kendisine yapılacak bildirim tarihinden itibaren üç ay içinde",
   "Kendisine yapılacak bildirim tarihinden itibaren bir yıl içinde"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre yatırım izni verilen başvuru sahiplerine yapılacak bildirim tarihinden itibaren altı ay içerisinde antrepo olarak açılmak istenen tesisin veya yerin hazır hâle getirilerek ilgili gümrük müdürlüğüne başvurulması gerekir. Bu sürede tesis hazırlanamaz veya belgeler sunulamazsa süre içinde ilgili gümrük müdürlüğü ve bölge müdürlüğü aracılığıyla Bakanlıktan ek süre istenir; verilen ek süre içinde başvuru yapılmaz ya da süre bitiminde yeniden ek süre talep edilmezse yatırım izni iptal edilebilir. Sürenin başlangıcı iznin verildiği ya da başvurunun yapıldığı tarih değil, izin sahibine yapılan bildirimin tarihidir. En güçlü çeldirici 'Bakanlıkça yatırım izni verildiği tarihten itibaren altı ay içinde' seçeneğidir: süre miktarı doğru, başlangıç anı yanlıştır. 'Üç ay' hafif kusurda verilen süreden, 'bir yıl' yükümlülüklerin yerine getirilmesi için verilebilecek azami süreden gelir. Bu nedenle doğru cevap 'Kendisine yapılacak bildirim tarihinden itibaren altı ay içinde' seçeneğidir. (MD GY 518)",
kanit="29-iŞLETİCİLER.txt | Yatırım izni verilen başvuru sahiplerine yapılacak bildirim tarihinden itibaren altı ay içerisinde antrepo olarak açılmak istenen tesisin/yerin hazır hale getirilerek ilgili gümrük müdürlüğüne başvurulması gerekir || 29-iŞLETİCİLER.txt | ilgili gümrük müdürlüğü ve bölge müdürlüğü aracılığıyla Bakanlıktan ek süre talebinde bulunulması gerekir",
yuva=["Başvuru tarihi: yatırım izni başvurusu (GY 518/1) – süre başlangıcı kaydırılmış",
      "İznin verildiği tarih: yatırım izni Bakanlıkça sonuçlandırılır (GY 518/8) – süre başlangıcı kaydırılmış",
      "Üç ay: hafif kusurda verilen süre (GY 525/10) – aynı mevzuatın sayı havuzu",
      "Bir yıl: yükümlülüklerin yerine getirilmesi için verilecek azami süre (GY 525/2) – aynı mevzuatın sayı havuzu"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "YAKIN-SAYI"], duzey=["HATIRLAMA"], profil=[2],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 6 — Genel antrepoda alan şartına tabi olmayanlar (liste dışı)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="KAPSAM_DIŞI",
z="Z",
madde="Gümrük Yönetmeliği md. 519",
cek="Genel antrepo alan şartından muaf: soğuk hava, yanıcı-parlayıcı-patlayıcı, kıymetli maden-taş antrepoları ve havalimanı vb. sahadaki havayolu kargo antrepoları; ağır-havaleli eşya sayılmamış.",
kok=["Gümrük Yönetmeliği'ne göre genel antrepo olarak açılıp işletilmesi istenen yerler için öngörülen asgari alan büyüklüğü şartına tabi olmayan antrepolar arasında aşağıdakilerden hangisi yer almaz?"],
d="Ağır ve havaleli eşyanın konulmasına mahsus açık alanlardan oluşan antrepolar",
c=["Soğuk hava tertibatı gerektiren eşyanın konulduğu antrepolar",
   "Kıymetli maden ve kıymetli taşların konulduğu antrepolar",
   "Yanıcı, parlayıcı, patlayıcı nitelikteki eşya için özel tertibat gerektiren antrepolar",
   "Havalimanı sahasında bulunan ve havayolu ile kargo taşımacılığında kullanılan antrepolar"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre genel antrepo olarak açılacak yerlerin açık ve kapalı alanları toplamı, en az %20'si kapalı olmak üzere büyükşehir belediyesi sınırları içinde 5.000 m²'den, diğer yerlerde 3.000 m²'den küçük olamaz. Bu şarta tabi olmayanlar tek tek sayılmıştır: soğuk hava tertibatı ya da yanıcı, parlayıcı, patlayıcı nitelikteki eşya için özel tertibat gerektiren veya kıymetli maden ve kıymetli taşların konulduğu antrepolar, alanının en az yarısı bu nitelikteki eşyanın depolanacağı bölümlerden oluşan antrepolar ile havalimanı, demiryolu istasyonu veya aktarma tesisi ve deniz limanı sahasında bulunan, havayolu ile kargo taşımacılığında kullanılan antrepolar. Ağır ve havaleli eşyaya mahsus açık alanlar bu listede yoktur; bu ifade, limanlardaki geçici depolama yerlerinin mütemmim cüzü sayılan ve geçici depolama yeri addolunan açık alanlara ilişkin komşu hükümden taşınmıştır. Liste kapalıdır ve sağduyuyla genişletilemez. Bu nedenle doğru cevap 'Ağır ve havaleli eşyanın konulmasına mahsus açık alanlardan oluşan antrepolar' seçeneğidir. (MD GY 519; GY 79)",
kanit="29-iŞLETİCİLER.txt | Soğuk hava tertibatı ya da yanıcı, parlayıcı, patlayıcı nitelikteki eşya için özel tertibat gerektiren veya kıymetli maden ve kıymetli taşların konulduğu antrepolar || 29-iŞLETİCİLER.txt | havalimanı, demiryolu istasyonu/aktarma tesisi ve deniz limanı sahasında bulunan, havayolu ile kargo taşımacılığında kullanılan antrepolar bu şarta tabi değildir || 29-iŞLETİCİLER.txt | Ağır ve havaleli eşyanın konulmasına mahsus olmak üzere, limanlar gibi gümrük işlemlerinin yapıldığı yerlerde bulunan geçici depolama yerlerinin mütemmim cüz'ü niteliğindeki açık alanlar",
yuva=["Alan şartına tabi olmayan: soğuk hava tertibatı gerektiren eşya antrepoları (GY 519/3)",
      "Alan şartına tabi olmayan: kıymetli maden ve kıymetli taş antrepoları (GY 519/3)",
      "Alan şartına tabi olmayan: yanıcı, parlayıcı, patlayıcı eşya için özel tertibatlı antrepolar (GY 519/3)",
      "Alan şartına tabi olmayan: havalimanı vb. sahada havayolu kargo antrepoları (GY 519/3)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU", "KOMŞU"], duzey=["TANIMA"], profil=[3],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="AYNA-ALAN (antrepo ↔ geçici depolama yeri)", guncellik="", cikmis="", kapsamli=False,
),

# 7 — Değişiklik talepleri – sonuçlandıran merci eşleştirmesi (antrepo ↔ GDY)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="EŞLEŞTİRME",
z="Z",
madde="Gümrük Yönetmeliği md. 524, 516/A",
cek="Antrepoda plan değişikliği gerektiren talep bölge müdürlüğünde, gerektirmeyen gümrük müdürlüğünde; GDY'de gerektirmeyen bölge müdürlüğünde, gerektiren Bakanlıkta sonuçlanır.",
kok=["Gümrük Yönetmeliği'ne göre antrepo ve geçici depolama yerlerinde yapılacak değişikliklere ilişkin talepler ile bu talepleri sonuçlandıran merciler aşağıda eşleştirilmiştir.",
     "Bu eşleştirmelerden hangisi yanlıştır?"],
d="Geçici depolama yerinde yapılmak istenen ve plan değişikliği gerektirmeyen talepler – Gümrük müdürlüğü",
c=["Antrepo planında değişiklik yapılmasını gerektiren tadilat, genişletme ve daraltma talepleri – Bölge müdürlüğü",
   "Antrepo planında değişiklik yapılmasını gerektirmeyen değişiklik talepleri – Gümrük müdürlüğü",
   "Antreponun aynı gümrük idaresi denetiminde bulunan başka bir adrese taşınması talepleri – Bakanlık",
   "Geçici depolama yerinde yapılmak istenen ve plan değişikliği gerektiren talepler – Bakanlık"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre antrepolarda antrepo planında değişiklik yapılmasını gerektiren tadilat, genişletme ve daraltma talepleri gümrük müdürlüğünün görüşüyle bölge müdürlüğüne aktarılır ve bölge müdürlüğünce sonuçlandırılarak Bakanlığa bilgi verilir; plan değişikliği gerektirmeyen talepler ise gümrük müdürlüğünce sonuçlandırılır. Antreponun aynı gümrük idaresi denetiminde başka bir adrese taşınması talebi bölge müdürlüğünün görüşüyle Bakanlıkça sonuçlandırılır. Geçici depolama yerlerinde kademe bir basamak yukarıdadır: plan değişikliği gerektirmeyen talepler gümrük müdürlüğünün görüşüyle bölge müdürlüğünce sonuçlandırılarak Bakanlığa bilgi verilir, plan değişikliği gerektiren talepler bölge müdürlüğünün görüşüyle Bakanlıkça sonuçlandırılır. Yanlış eşleştirme, antrepodaki 'plan değişikliği gerektirmeyen talep – gümrük müdürlüğü' kuralının geçici depolama yerine taşınmasıyla kurulmuştur. Bu nedenle doğru cevap 'Geçici depolama yerinde yapılmak istenen ve plan değişikliği gerektirmeyen talepler – Gümrük müdürlüğü' seçeneğidir. (MD GY 524, 516/A)",
kanit="29-iŞLETİCİLER.txt | Geçici depolama yerinde yapılmak istenen ve plan değişikliği gerektirmeyen talepler, ilgili gümrük müdürlüğünün görüşü ile birlikte ilgili bölge müdürlüğüne aktarılır ve ilgili bölge müdürlüğünce sonuçlandırılarak Bakanlığa bilgi verilir || 29-iŞLETİCİLER.txt | geçici depolama yerlerinde yapılmak istenen ve plan değişikliği gerektiren talepler, ilgili bölge müdürlüğünün görüşü ile birlikte Bakanlıkça sonuçlandırılır || 29-iŞLETİCİLER.txt | gümrük müdürlüğünün görüşü ile birlikte bölge müdürlüğüne aktarılır ve bölge müdürlüğünce sonuçlandırılarak Bakanlığa bilgi verilir || 29-iŞLETİCİLER.txt | antrepo planında değişiklik yapılmasını gerektirmeyen değişiklik talepleri ise gümrük müdürlüğünce sonuçlandırılır || 29-iŞLETİCİLER.txt | Talep bölge müdürlüğünün görüşü ile birlikte Bakanlığa aktarılır ve Bakanlıkça sonuçlandırılır",
yuva=["Doğru eşleşme: antrepoda plan değişikliği gerektiren talep bölge müdürlüğünce sonuçlandırılır (GY 524/1)",
      "Doğru eşleşme: antrepoda plan değişikliği gerektirmeyen talep gümrük müdürlüğünce sonuçlandırılır (GY 524/1)",
      "Doğru eşleşme: başka adrese taşınma talebi Bakanlıkça sonuçlandırılır (GY 524/2)",
      "Doğru eşleşme: GDY'de plan değişikliği gerektiren talep Bakanlıkça sonuçlandırılır (GY 516/A/2)"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "KOMŞU"], duzey=["AYIRT"], profil=[1],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 8 — GDY alan ve mesafe şartı (ayna: antrepo alan şartı)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="ŞART",
z="Z",
madde="Gümrük Yönetmeliği md. 513",
cek="Gümrüklü saha dışında açılacak GDY en az 3.000 m²'si kapalı 10.000 m² olmalı ve gümrük müdürlüğüne en fazla 10 km mesafede bulunmalıdır.",
kok=["Gümrük Yönetmeliği'ne göre gümrüklü sahada veya gümrük idaresi bulunan deniz ve hava limanı içerisinde ya da iç gümrük idarelerinde gümrük müdürlüğüne bitişik olarak açılanlar dışında kalan geçici depolama yerleri için genel olarak aranan alan ve mesafe şartları aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="En az 3.000 m²'si kapalı olmak üzere 10.000 m²'den küçük olmaması; mutat yollarla gümrük müdürlüğüne en fazla 10 km mesafede olması",
c=["En az %20'si kapalı olmak üzere 5.000 m²'den küçük olmaması; mutat yollarla gümrük müdürlüğüne en fazla 50 km mesafede olması",
   "En az 3.000 m²'si kapalı olmak üzere 10.000 m²'den küçük olmaması; mutat yollarla gümrük müdürlüğüne en fazla 20 km mesafede olması",
   "En az 5.000 m²'si kapalı olmak üzere 10.000 m²'den küçük olmaması; mutat yollarla gümrük müdürlüğüne en fazla 10 km mesafede olması",
   "En az %20'si kapalı olmak üzere 3.000 m²'den küçük olmaması; mutat yollarla gümrük müdürlüğüne en fazla 10 km mesafede olması"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre gümrüklü sahada, gümrük idaresi bulunan deniz ve hava limanı içinde veya iç gümrük idarelerinde gümrük müdürlüğüne bitişik olarak açılanlar dışında kalan geçici depolama yerlerinin en az 3.000 m²'si kapalı olmak üzere 10.000 m²'den küçük olmaması ve mutat yolların izlenmesi kaydıyla gümrük müdürlüğüne en fazla 10 km mesafede olması gerekir. Taşıt depolanacak yerlerde kapalı alan, havayolu ile hızlı kargo taşımacılığına ilişkin yerlerde alan şartı aranmaz. En güçlü çeldirici 20 km'yi içeren seçenektir: 20 km, ekonomik ihtiyaç hâlinde liman işleticisinin 10.000.000 TL teminatla kapalı alan şartı aranmaksızın açabileceği geçici depolama yerine ilişkin istisnadır. %20 kapalı alan, 5.000 m², 3.000 m² ve 50 km değerleri ise genel antrepolara aittir. Bu nedenle doğru cevap 'En az 3.000 m²'si kapalı olmak üzere 10.000 m²'den küçük olmaması; mutat yollarla gümrük müdürlüğüne en fazla 10 km mesafede olması' seçeneğidir. (MD GY 513; GY 519)",
kanit="29-iŞLETİCİLER.txt | İkinci fıkranın (b) bendinde belirtilen yerler dışında geçici depolama yeri olarak açılıp işletilmek istenilen yerlerin, en az 3.000 m2'si kapalı olmak üzere 10.000 m2'den küçük olmaması ve mutat yolların izlenmesi kaydıyla gümrük müdürlüğüne en fazla 10 km mesafede olması gerekir || 29-iŞLETİCİLER.txt | Gümrüklü sahada veya gümrük idaresi bulunan deniz ve hava limanı içerisinde veya iç gümrük idarelerinde gümrük müdürlüğüne bitişik || 29-iŞLETİCİLER.txt | limanın bağlı bulunduğu gümrük müdürlüğüne en fazla 20 km mesafede olması şartlarıyla",
yuva=["Genel antrepo: büyükşehirde 5.000 m², en az %20 kapalı; gümrük müdürlüğüne en fazla 50 km (GY 519/2-3)",
      "Liman işleticisinin ön izinle açacağı GDY'de 20 km (GY 513/10) – aynı maddenin istisna fıkrası",
      "5.000 m²: genel antreponun büyükşehirdeki asgari alanı (GY 519/3)",
      "3.000 m² ve %20 kapalı: genel antreponun diğer yerlerdeki asgari alanı (GY 519/3)"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"], duzey=["AYIRT"], profil=[2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="AYNA-ALAN (antrepo ↔ geçici depolama yeri)", guncellik="", cikmis="", kapsamli=False,
),

# 9 — Antrepo stok kayıtları antrepo tipine göre (ikiz eksen 17)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Yönetmeliği md. 536, 537",
cek="Stok kaydını A, C, D, E tipinde işletici tutar; B tipinde tutulmayabilir; F tipinde gümrük kayıtları yerini alır; E tipinde giriş kaydı depolama yerine ulaşınca.",
kok=["Gümrük Yönetmeliği'nin antrepo stok kayıtlarına ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. A, C, D ve E tipi antrepolarda antrepo stok kayıtlarını antrepo işleticileri tutar.",
     "II. B tipi antrepoda antrepo stok kayıtlarının antrepo işleticisi tarafından tutulması zorunludur.",
     "III. F tipi antrepoda gümrük kayıtları stok kayıtlarının yerini alır.",
     "IV. E tipi antrepoda stok kayıtlarına giriş işlemi, eşyanın izin hak sahibinin antrepo addedilen depolama yerine ulaştığında yapılır.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, III ve IV",
c=["I ve III", "II ve IV", "I, II ve III", "I, II, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre A, C, D ve E tipi antrepolarda antrepo stok kayıtlarını antrepo işleticileri tutar (I doğru). B tipi antrepoda ise rejime giriş beyannamesinin ve rejimi sona erdiren beyanname ve belgelerin kaydını denetleyici gümrük idaresi tutar; işletici ve kullanıcı yalnızca belgeleri muhafaza eder ve stok kayıtları tutulmayabilir (II yanlış). F tipi antrepoda gümrük kayıtları stok kayıtlarının yerini alır (III doğru). Stok kayıtlarına giriş işlemi A, C ve D tipi antrepoda eşyanın antrepoya fiziken girdiği sırada, E tipi antrepoda ise eşyanın izin hak sahibinin antrepo addedilen depolama yerine ulaştığında yapılır (IV doğru). En güçlü çeldirici dört ifadeyi de doğru sayan seçenektir: B tipinde kayıt yükü işleticide değil denetleyici gümrük idaresindedir ve stok kaydı zorunlu değildir. Bu nedenle doğru cevap 'I, III ve IV' seçeneğidir. (MD GY 536, 537)",
kanit="29-iŞLETİCİLER.txt | A, C, D ve E tipi antrepolarda, Kanunun 99 uncu maddesinde belirtilen antrepo stok kayıtlarını antrepo işleticileri tutar || 29-iŞLETİCİLER.txt | B tipi antrepoda, denetleyici gümrük idaresi, rejime giriş beyannamesinin ve rejimi sona erdiren beyanname ve belgelerin kaydını tutar ve belgeleri muhafaza eder. B tipi antrepo işleticisi ve/veya kullanıcısı da, söz konusu belgeleri muhafaza eder. Stok kayıtları tutulmayabilir. || 29-iŞLETİCİLER.txt | F tipi antrepoda, gümrük kayıtları stok kayıtlarının yerini alır || 29-iŞLETİCİLER.txt | E tipi antrepoda eşyanın izin hak sahibinin antrepo addedilen depolama yerine ulaştığında",
yuva=["I ve III: IV de doğrudur; E tipi giriş anı (GY 537/1-a-2) atlanmış",
      "II ve IV: II'de B tipi için stok kaydı zorunluluğu yok, kaydı denetleyici gümrük idaresi tutar (GY 536/3)",
      "I, II ve III: II yanlış (GY 536/3), IV atlanmış",
      "I, II, III ve IV: B tipinde stok kaydı tutulmayabilir (GY 536/3)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM", "MAKAM"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=False, vaka=False, baslangic=False, eksen=17, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 10 — İşletici ve kullanıcının mali sorumluluğu: sigorta tazminatında vergi sigorta ettirenden
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="YANLIŞ",
z="O",
madde="Gümrük Yönetmeliği md. 522",
cek="Vergiler dâhil sigortalanan eşyada vergiler sigortadan tazminat alınmışsa noksanlık vergileri işleticiden değil sigorta ettirenden veya lehine ettirilenden alınır.",
kok=["Gümrük Yönetmeliği'ne göre antrepo işleticileri ve kullanıcılarının antrepoya alınan eşya nedeniyle gümrük idaresine karşı mali sorumluluğuna ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Eşya gümrük vergileri de dahil olduğu halde sigortalanmış ve bu vergiler sigorta şirketinden tazminat olarak alınmışsa, noksanlıklara ait gümrük vergileri antrepo işleticisinden alınır.",
c=["Sorumluluk, eşyanın girerken gümrük idaresince tespit edilen miktarı, tespit yapılmamışsa belgelerinde yazılı miktarları üzerinden doğar.",
   "Eşyanın tabiatından doğan kayıp ve firelerin gümrük idaresine ispat edilmesi ve bunun idarece de kabul edilmesi halinde sorumluluk söz konusu olmaz.",
   "Tabiatları gereği antrepolarda fire veren eşyanın ek-11'de yer alması halinde fire miktarlarının belirlenmesinde bu oranlar dikkate alınır.",
   "Denizyoluyla konteyner ile getirilip giriş gümrük idaresince miktar tespiti yapılmaksızın aynı gümrük müdürlüğüne bağlı antrepoya sevk edilen eşyanın kap adedinde farklılık tespit edilirse, kullanıcıdan farklılığın sebebini 45 gün içinde izah etmesi istenir."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre antrepo işleticileri ve kullanıcıları, eşyanın girerken gümrük idaresince tespit edilen, tespit yapılmamışsa belgelerinde yazılı miktarları üzerinden gümrük idaresine karşı mali bakımdan sorumludur; sorumluluk eksiklik veya değişikliğe ait gümrük vergilerini ve cezalarını kapsar. Eşyanın tabiatından doğan kayıp ve fireler, gözetim altında yapılan işleme faaliyetinden doğan noksanlıklar ve işletici ile kullanıcının kusurundan doğmayan eksiklikler idareye ispat edilip kabul edilirse sorumluluk doğmaz; fire veren eşya ek-11'de yer alıyorsa bu oranlar dikkate alınır. Denizyoluyla konteynerle getirilip miktar tespiti yapılmadan antrepoya sevk edilen eşyanın kap adedinde fark çıkarsa kullanıcıdan farkın sebebini 45 gün içinde izah etmesi istenir; süre talep hâlinde 30 gün uzatılabilir. Eşya gümrük vergileri dâhil sigortalanmış ve bu vergiler sigorta şirketinden tazminat olarak alınmışsa, noksanlıklara ait gümrük vergileri antrepo işleticisinden değil, sigorta ettirenden veya lehine sigorta ettirilenden alınır. Yanlış ifade, tazminatı alan kişiye ait yükümlülüğü genel sorumluluk kuralına bağlayarak kurulmuştur. Bu nedenle doğru cevap 'Eşya gümrük vergileri de dahil olduğu halde sigortalanmış ve bu vergiler sigorta şirketinden tazminat olarak alınmışsa, noksanlıklara ait gümrük vergileri antrepo işleticisinden alınır.' seçeneğidir. (MD GY 522)",
kanit="29-iŞLETİCİLER.txt | Eşya gümrük vergileri de dahil olduğu halde sigortalanmış ve sigorta sözleşmesine göre bu vergileri sigorta şirketinden tazminat olarak alınmış ise, bu gibi noksanlık ve eksikliklere ait gümrük vergileri sigorta ettirenden veya lehine ettirilenden alınır || 29-iŞLETİCİLER.txt | antrepolarına alınan eşyanın girerken gümrük idaresince tespit edilen miktarı üzerinden ve eğer tespit yapılmamışsa belgelerinde yazılı miktarları üzerinden || 29-iŞLETİCİLER.txt | Eşyanın tabiatından doğan kayıp ve firelerin || 29-iŞLETİCİLER.txt | gümrük idaresine ispat edilmesi ve bunun idarece de kabul edilmesi halinde sorumluluk söz konusu olmaz || 29-iŞLETİCİLER.txt | fire veren eşyanın ek-11'de yer alması halinde fire miktarlarının belirlenmesinde bu oranlar dikkate alınır || 29-iŞLETİCİLER.txt | kullanıcıdan söz konusu farklılığın sebebinin 45 gün içinde izah edilmesi istenir",
yuva=["Doğru hüküm: sorumluluğun miktar esası (GY 522/2)",
      "Doğru hüküm: tabiattan doğan kayıp ve fire istisnası (GY 522/4-a)",
      "Doğru hüküm: ek-11 fire oranları (GY 522/7)",
      "Doğru hüküm: konteynerde kap adedi farkının 45 gün içinde izahı (GY 522/8)"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"], duzey=["AYIRT"], profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 11 — YGM tespit raporu (meslek yanlılığı: "rapor her değişiklikte şarttır" önyargısı)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="DOĞRU",
z="Z",
madde="Gümrük Yönetmeliği md. 524",
cek="Değişiklik işlemlerinde YGM tespit raporu düzenlenir, izin Bakanlıkça verilmişse Bakanlığa da gönderilir; plan değişikliği gerektirmeyen diğer taleplerde rapor düzenlenmez.",
kok=["Gümrük Yönetmeliği'ne göre antrepolarda yapılacak değişikliklere ilişkin olarak yetkilendirilmiş gümrük müşavirince düzenlenecek tespit raporu ile ilgili aşağıdakilerden hangisi doğrudur?"],
d="İznin Bakanlıkça verildiği durumlarda tespit raporları Bakanlığa (Tasfiye Hizmetleri Genel Müdürlüğü) da gönderilir.",
c=["Antrepoda yapılacak her türlü değişiklik talebinde, antrepo planında değişiklik gerektirip gerektirmediğine bakılmaksızın tespit raporu düzenlenmesi zorunludur.",
   "Tespit raporu yalnızca akaryakıt antrepolarına ilişkin tank ilavesi taleplerinde düzenlenir.",
   "Antreponun başka bir adrese taşınması taleplerinde tespit raporu düzenlenmez; gümrük müdürlüğünce düzenlenen görgü raporu yeterlidir.",
   "Antrepo planında değişiklik gerektiren tadilat, genişletme ve daraltma taleplerinde tespit raporu, yetkilendirilmiş gümrük müşaviri yerine bölge müdürlüğünce düzenlenir."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre antrepo planında değişiklik gerektiren tadilat, genişletme ve daraltma talepleri ile antreponun başka bir adrese taşınması ve akaryakıt antrepolarında tank ilavesi taleplerine ilişkin işlemler için yetkilendirilmiş gümrük müşavirince tespit raporu düzenlenir; iznin Bakanlıkça verildiği durumlarda bu raporlar Bakanlığa (Tasfiye Hizmetleri Genel Müdürlüğü) da gönderilir. Bu işlemlerin kapsamı dışında kalan ve antrepo planında değişiklik yapılmasını gerektirmeyen değişiklik talepleri için ise yetkilendirilmiş gümrük müşavirince tespit raporu düzenlenmez. En güçlü çeldirici raporu her türlü değişiklikte zorunlu sayan seçenektir; 'gümrük müşavirinin raporu her durumda şarttır' önyargısını yoklar. Görgü raporu ise antrepo açılış başvurusunun incelenmesinde gümrük müdürlüğünce düzenlenen ayrı bir belgedir. Bu nedenle doğru cevap 'İznin Bakanlıkça verildiği durumlarda tespit raporları Bakanlığa (Tasfiye Hizmetleri Genel Müdürlüğü) da gönderilir.' seçeneğidir. (MD GY 524; GY 521)",
kanit="29-iŞLETİCİLER.txt | Birinci ve ikinci fıkrada yer alan işlemlere ilişkin yetkilendirilmiş gümrük müşavirince tespit raporu düzenlenir. İznin Bakanlıkça verildiği durumlarda tespit raporları Bakanlığa da (Tasfiye Hizmetleri Genel Müdürlüğü) gönderilir. Birinci ve ikinci fıkra kapsamı dışında kalan ve antrepo planında değişiklik yapılmasını gerektirmeyen değişiklik talepleri için yetkilendirilmiş gümrük müşavirince tespit raporu düzenlenmez. || 29-iŞLETİCİLER.txt | Antreponun aynı gümrük idaresi veya aynı Bölge Müdürlüğü bağlantısı farklı gümrük idaresi || 29-iŞLETİCİLER.txt | ilgili gümrük müdürlüğü tarafından antrepo olarak açılmak ve işletilmek üzere hazırlanan yer için görgü raporu düzenlenir",
yuva=["Plan değişikliği gerektirmeyen ve kapsam dışı taleplerde rapor düzenlenmez (GY 524/5 son cümle) – meslek önyargısı",
      "Tank ilavesi raporlu işlemlerden yalnızca biridir; adres taşıma ve tadilat da kapsamdadır (GY 524/2, 524/5)",
      "Adres taşıma talebi raporlu işlemler arasındadır (GY 524/2, 524/5); görgü raporu açılış incelemesine aittir (GY 521/2)",
      "Raporu yetkilendirilmiş gümrük müşaviri düzenler; bölge müdürlüğü talebi sonuçlandırır (GY 524/1, 524/5)"],
yakinlik="BİREBİR",
tuzak=["MUTLAK", "KOMŞU", "TERİM"], duzey=["AYIRT"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 12 — Özel antrepo devrinde devredilmeyen eşya: bir ay + en çok iki ay
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="SÜRE",
z="O",
madde="Gümrük Yönetmeliği md. 523",
cek="Özel antreponun devrinde devralana devredilmeyen eşyanın çıkarılması için bir ay verilir; gümrük idaresi bu süreyi en çok iki ay uzatabilir.",
kok=["Gümrük Yönetmeliği'ne göre özel antrepoların devri durumunda, antrepodaki eşyanın devralana devredilmemesi hâlinde, bu eşyanın antrepodan çıkarılması için gümrük idaresince verilecek süre ve bu sürenin uzatılabileceği azami süre aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Bir ay; en çok iki ay uzatılabilir",
c=["Beş iş günü; en çok beş iş günü uzatılabilir", "On beş gün; en çok bir ay uzatılabilir",
   "Bir ay; en çok altı ay uzatılabilir", "Üç ay; en çok üç ay uzatılabilir"],
sirali=True,
siklar=["Beş iş günü; en çok beş iş günü uzatılabilir", "On beş gün; en çok bir ay uzatılabilir",
        "Bir ay; en çok iki ay uzatılabilir", "Bir ay; en çok altı ay uzatılabilir",
        "Üç ay; en çok üç ay uzatılabilir"],
g="Gümrük Yönetmeliği'ne göre antrepo işleticisinin hak ve yükümlülükleri izin üzerine başka bir kişiye devredilebilir. Özel antrepoların devrinde antrepodaki eşya devralana devredilmezse, bu eşyanın antrepodan çıkarılması için gümrük idaresince bir aylık süre verilir; uzatmayı gerektiren bir durum varsa bu süre gümrük idaresince en çok iki ay uzatılabilir. En güçlü çeldirici beş iş günüdür: beş iş günü antreponun değil, özel antrepodaki eşyanın devrine ilişkin süredir ve eşyanın devrini müteakip gümrükçe onaylanmış yeni bir işlem veya kullanıma tabi tutularak antrepodan çıkarılmasını ifade eder. Altı ay kapatılacak antrepolardaki eşyanın başka antrepoya nakil, ihraç veya serbest dolaşıma sokulma süresi; on beş gün ise akaryakıt antreposu tankında serbest dolaşıma girmiş eşyanın çekilme süresidir; bu süre gümrük müdürlüğünce otuz güne kadar uzatılabilir. Bu nedenle doğru cevap 'Bir ay; en çok iki ay uzatılabilir' seçeneğidir. (MD GY 523; GY 333)",
kanit="29-iŞLETİCİLER.txt | Özel antrepoların devri durumunda, antrepodaki eşyanın devralana devredilmemesi halinde, bu eşyanın antrepodan çıkarılması için gümrük idaresince bir aylık süre verilir. Bu sürenin uzatılmasını gerektirir bir durumun olması halinde, bu süre gümrük idaresince en çok iki ay uzatılabilir. || 28-antrepo rejimi.txt | Özel antrepoda bulunan eşyanın devrine ilişkin talepler, eşyanın devrini müteakip beş iş günü içinde || 29-iŞLETİCİLER.txt | en geç altı ay içerisinde gümrük müdürlüğünce gösterilen diğer antrepolara nakil",
yuva=["Beş iş günü: özel antrepodaki eşyanın devrinde çıkış süresi (28-antrepo rejimi.txt, GY 333/4) – komşu rejim hükmü",
      "On beş gün ve otuz güne kadar uzatma: akaryakıt tankında serbest dolaşıma girmiş eşyanın çekilmesi (GY 542/6-d)",
      "Altı ay: kapatılacak antrepodaki eşyanın nakil, ihraç veya serbest dolaşıma sokulma süresi (GY 523/10) – aynı madde",
      "Üç ay + üç ay: yolcu eşyası ve taşıtların GDY addolunan yerde kalış süresi ve uzatması (GY 79/2)"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"], duzey=["AYIRT"], profil=[2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 13 — Götürü teminat hesabı (1.000 m²'ye tamamlama)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="HESAP",
z="Z",
madde="Gümrük Yönetmeliği md. 527",
cek="Götürü teminat: ilk 1.000 m² 3.000.000 TL, sonraki her 1.000 m² 1.000.000 TL; küsurat 1.000 m²'ye tamamlanır; 4.300 m² için 7.000.000 TL.",
kok=["Gümrük Yönetmeliği'nin antrepo işleticilerince verilecek götürü teminata ilişkin hükümlerine göre aşağıdaki bilgiler verilmiştir:",
     "- Bir antrepo işleticisi, alanı 4.300 m² olan antreposu için götürü teminat verecektir.",
     "- Teminat tutarı alan esas alınarak hesaplanacaktır.",
     "Buna göre bu antrepo için verilmesi gereken götürü teminat tutarı kaç TL'dir?"],
d="7.000.000 TL",
c=["6.000.000 TL", "6.300.000 TL", "7.300.000 TL", "8.000.000 TL"],
sirali=True,
siklar=["6.000.000 TL", "6.300.000 TL", "7.000.000 TL", "7.300.000 TL", "8.000.000 TL"],
g="Gümrük Yönetmeliği'ne göre antrepo işleticilerince her bir antrepo için verilecek götürü teminat, 1.000 m²'ye kadar olan antrepolar için 3.000.000 TL'dir; 1.000 m²'den sonraki her 1.000 m² için 1.000.000 TL eklenir ve 1.000 m²'nin altındaki artışlar 1.000 m²'ye tamamlanır. Bir antrepo için hesaplanan tutarın 40.000.000 TL'yi aşan kısmı dikkate alınmaz. Olayda ilk 1.000 m² için 3.000.000 TL hesaplanır; kalan 3.300 m² 4.000 m²'ye tamamlanır ve 4 x 1.000.000 = 4.000.000 TL eklenir. Toplam 7.000.000 TL'dir. En güçlü çeldirici 6.300.000 TL'dir: artışı oransal hesaplayıp 1.000 m²'ye tamamlama kuralını atlayan aday bu sonuca ulaşır. 6.000.000 TL artışı aşağı yuvarlamaktan, 7.300.000 TL ilk 1.000 m²'yi düşmeden oransal hesaplamaktan, 8.000.000 TL ise ilk 1.000 m²'yi düşmeden yukarı yuvarlamaktan doğar. Bu nedenle doğru cevap '7.000.000 TL' seçeneğidir. (MD GY 527)",
kanit="29-iŞLETİCİLER.txt | 1.000 m² veya 2.000 m³'e kadar olanlar için 3.000.000 || 29-iŞLETİCİLER.txt | 1.000 m²'den sonraki her 1.000 m² için 1.000.000 || 29-iŞLETİCİLER.txt | 1.000 m²'nin altındaki artışlar 1.000 m²'ye tamamlanır || 29-iŞLETİCİLER.txt | Bir antrepo için hesaplanan götürü teminatın 40.000.000",
yuva=["AD-HESAP: kalan 3.300 m² aşağı yuvarlanmış (3 x 1.000.000) – tamamlama kuralı (GY 527/2-b) ters uygulanmış",
      "AD-HESAP: kalan 3.300 m² oransal hesaplanmış (3,3 x 1.000.000) – tamamlama kuralı atlanmış",
      "AD-HESAP: ilk 1.000 m² düşülmeden 4.300 m² oransal hesaplanmış (3.000.000 + 4.300.000)",
      "AD-HESAP: ilk 1.000 m² düşülmeden 4.300 m² 5.000 m²'ye tamamlanmış (3.000.000 + 5.000.000)"],
yakinlik="ÇIKARIM",
tuzak=["AD-HESAP", "İSTİSNA"], duzey=["UYGULAMA"], profil=[2],
olumsuz=False, vaka=True, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 14 — Antrepo kusurları: hafif üç ay, orta bir ay; ilk tebligattan; bir kez uzatma
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Yönetmeliği md. 525",
cek="Kusurda süre ilk tebligattan başlar: hafif üç ay, orta bir ay, bu sürede eşya girişi serbest; ağır kusurda giriş durur; süre bir kez uzatılır.",
kok=["Gümrük Yönetmeliği'ne göre yapılan inceleme, denetim veya işlemlerde antrepoda Ek-80'de sayılan kusurların tespit edilmesi hâlinde uygulanacak işlemlerle ilgili aşağıdaki ifadeler verilmiştir:",
     "I. Yükümlülüklerin yerine getirilmesi için işleticiye verilen süre, kusurun tespit edildiği tarihten başlar.",
     "II. Hafif kusurda üç ay, orta kusurda bir ay süre verilir.",
     "III. Ağır kusur durumunda da işleticiye süre verilir ve bu süre içinde antrepoya eşya girişine izin verilir.",
     "IV. Verilen süreler en fazla bir kez ve verilen süre kadar uzatılır.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve IV",
c=["I ve II", "III ve IV", "I, II ve IV", "II, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre izin işlemlerinde Ek-80'deki hafif, orta ve ağır kusurlar dikkate alınır. Kusur tespit edilirse işleticiye ilk tebligat tarihinden başlamak üzere hafif kusurda üç ay, orta kusurda bir ay süre verilerek yükümlülüklerin yerine getirilmesi bildirilir ve bu sürede antrepoya eşya girişine izin verilir (II doğru). Süre kusurun tespit edildiği tarihten değil, ilk tebligat tarihinden başlar (I yanlış). Hafif veya orta kusurun verilen sürede giderilememesi ile ağır kusur durumlarında antrepoya eşya girişine izin verilmez ve taahhüde uymayan işleticilere uygulanan genel usule göre işlem yapılır (III yanlış). Bu kapsamda verilen süreler en fazla bir kez ve verilen süre kadar uzatılır (IV doğru). En güçlü çeldiriciler I'i içeren kombinasyonlardır: süre miktarları doğru olsa da başlangıç anı ilk tebligat tarihidir. Bu nedenle doğru cevap 'II ve IV' seçeneğidir. (MD GY 525)",
kanit="29-iŞLETİCİLER.txt | antrepo işleticilerine ilk tebligat tarihinden başlamak üzere \"Hafif Kusur\"da üç ay, \"Orta Kusur\"da bir ay süre verilerek yükümlülüklerin yerine getirilmesi bildirilir ve bu sürede antrepoya eşya girişine izin verilir || 29-iŞLETİCİLER.txt | \"Ağır Kusur\" durumlarında antrepoya eşya girişine izin verilmez || 29-iŞLETİCİLER.txt | Bu fıkra kapsamında verilen süreler en fazla bir kez ve verilen süre kadar uzatılır",
yuva=["I ve II: I'de başlangıç anı kaydırılmış (ilk tebligat tarihi yerine tespit tarihi)",
      "III ve IV: III'te ağır kusura hafif-orta kusur rejimi uygulanmış",
      "I, II ve IV: I'deki başlangıç anı yanlış",
      "II, III ve IV: III yanlış; ağır kusurda eşya girişine izin verilmez"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "SAYI", "İSTİSNA"], duzey=["AYIRT"], profil=[2],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 15 — YGM ile işletici arasında iş ilişkisi: üç ay eşya alınmaz (meslek)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="SÜRE",
z="O",
madde="Gümrük Yönetmeliği md. 525",
cek="YGM ile tespit yaptıran işletici arasında tespit dışı iş ilişkisi saptanırsa antrepoya üç ay, YGM belgesi asgari ücret ihlalinden geri alınırsa bir ay eşya alınmaz.",
kok=["Gümrük Yönetmeliği'ne göre antrepolarda yapılan denetleme neticesinde, yetkilendirilmiş gümrük müşaviri ile tespit işlemi yaptıran antrepo işleticisi arasında tespit işlemi haricinde doğrudan veya dolaylı iş ilişkisi tespit edilmesi hâlinde ilgili antrepoya ne kadar süreyle eşya alınmasına izin verilmez?"],
d="Üç ay",
c=["On beş gün", "Bir ay", "Altı ay", "Bir yıl"],
sirali=True,
siklar=["On beş gün", "Bir ay", "Üç ay", "Altı ay", "Bir yıl"],
g="Gümrük Yönetmeliği'ne göre antrepolarda yapılan denetleme sonucunda, yetkilendirilmiş gümrük müşavirliği asgari ücret tarifesinin altında hizmet verilmesi nedeniyle yetkilendirilmiş gümrük müşavirinin belgesinin geri alınmasına karar verilirse bir ay süreyle; yetkilendirilmiş gümrük müşaviri ile tespit işlemi yaptıran antrepo işleticisi arasında tespit işlemi dışında doğrudan veya dolaylı iş ilişkisi tespit edilirse üç ay süreyle ilgili antrepoya eşya alınmasına izin verilmez. En güçlü çeldirici 'Bir ay' seçeneğidir; bu süre aynı hükümdeki asgari ücret tarifesi ihlaline aittir. 'Bir yıl' ise asgari ücret tarifesinin altında hizmet veren yetkilendirilmiş gümrük müşavirinin yetki belgesinin geri alınma süresidir; antrepoya değil müşavire uygulanır. Bu nedenle doğru cevap 'Üç ay' seçeneğidir. (MD GY 525)",
kanit="29-iŞLETİCİLER.txt | Yetkilendirilmiş gümrük müşaviri ile tespit işlemi yaptıran antrepo işleticisi arasında tespit işlemi haricinde doğrudan veya dolaylı iş ilişkisinin tespiti halinde üç ay süreyle || 29-iŞLETİCİLER.txt | Yetkilendirilmiş gümrük müşavirliği asgari ücret tarifesinin altında hizmet verilmesi sonucu yetkilendirilmiş gümrük müşavirinin belgesinin geri alınmasına karar verilmesi halinde bir ay süreyle || 31-YGM.txt | asgari ücret tarifesinin altında hizmet verildiğinin tespiti halinde yetkilendirilmiş gümrük müşavirine ait yetki belgesi 1 yıl süreyle geri alınır",
yuva=["On beş gün: akaryakıt tankında serbest dolaşıma girmiş eşyanın çekilme süresi (GY 542/6-d) – sayı havuzu",
      "Bir ay: asgari ücret tarifesi altında hizmet nedeniyle YGM belgesi geri alınınca antrepoya eşya alınmama süresi (GY 525/7-a) – aynı fıkra",
      "Altı ay: kapatılacak antrepodaki eşyanın çıkarılma süresi (GY 523/10) – sayı havuzu",
      "Bir yıl: asgari ücret tarifesi altında hizmette YGM yetki belgesinin geri alınma süresi (31-YGM.txt) – komşu mevzuat"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"], duzey=["HATIRLAMA"], profil=[2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 16 — Antrepo teminatında kabul edilen türler (dar liste)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="KAPSAM_DIŞI",
z="O",
madde="Gümrük Yönetmeliği md. 526",
cek="Antrepo teminatında yalnız TL, yabancı para, Hazine tahvil ve bonosu ile Bakanlıkça tespit edilecek bankaların teminat mektupları kabul edilir.",
kok=["Gümrük Yönetmeliği'ne göre antrepo işleticileri ve kullanıcılarınca tahakkuk edebilecek gümrük vergilerini karşılamak amacıyla verilecek teminat olarak aşağıdakilerden hangisi kabul edilmez?"],
d="Genel yönetim kapsamındaki kamu idarelerinin verecekleri garanti mektupları",
c=["Türk lirası", "Yabancı para", "Hazine tahvil ve bonosu",
   "Bakanlıkça tespit edilecek bankalardan alınmış teminat mektupları"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre antrepo işleticileri ve kullanıcıları, Kanundaki sorumlulukları çerçevesinde tahakkuk edebilecek gümrük vergilerini karşılamak amacıyla teminat verir. Bu teminat bakımından Türk lirası veya yabancı para, Hazine tahvil ve bonosu ya da Bakanlıkça tespit edilecek bankalardan alınmış teminat mektupları dışında teminat kabul edilmez. Genel yönetim kapsamındaki kamu idarelerinin garanti mektupları, gümrük işlemlerinde genel olarak kabul edilen teminat türleri arasında sayılır; ancak antrepo teminatı için öngörülen dar listede yer almaz. Genel teminat listesini bilen fakat antrepoya özgü sınırlamayı bilmeyen aday bu şıkkı kabul edilir sanır. Bu nedenle doğru cevap 'Genel yönetim kapsamındaki kamu idarelerinin verecekleri garanti mektupları' seçeneğidir. (MD GY 526; GY 495)",
kanit="29-iŞLETİCİLER.txt | Türk lirası veya yabancı para, Hazine tahvil ve bonosu ya da Bakanlıkça tespit edilecek bankalardan alınmış teminat mektupları dışında teminat kabul edilmez || 46-teminat ve faiz.txt | Genel yönetim kapsamındaki kamu idarelerinin, belediyelerin, sermayesinin tamamı devlete ait olan kamu iktisadî teşebbüslerinin ve Türkiye'deki yabancı misyon şeflerinin verecekleri garanti mektupları",
yuva=["Antrepo teminatında kabul edilir: Türk lirası (GY 526/6)",
      "Antrepo teminatında kabul edilir: yabancı para (GY 526/6)",
      "Antrepo teminatında kabul edilir: Hazine tahvil ve bonosu (GY 526/6)",
      "Antrepo teminatında kabul edilir: Bakanlıkça tespit edilecek bankaların teminat mektupları (GY 526/6)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "KOMŞU", "SAĞDUYU"], duzey=["TANIMA"], profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 17 — Akaryakıt antrepoları tanımı: hammadde ve solvent nafta hariç
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="KAPSAM_DIŞI",
z="O",
madde="Gümrük Yönetmeliği md. 541",
cek="Akaryakıt antreposu tanımında benzin, ham petrol, nafta, gaz yağı, jet yakıtı, motorin, fuel-oil, bio dizel ve LPG vardır; hammadde ve solvent nafta hariçtir.",
kok=["Gümrük Yönetmeliği'nde yer alan akaryakıt antrepoları tanımına göre, bu antrepolara dökme veya kaplı olarak konulmasına özgü olduğu belirtilen eşya arasında aşağıdakilerden hangisi yer almaz?"],
d="Hammadde ve solvent nafta",
c=["Ham petrol", "Jet yakıtı", "Bio dizel", "Sıvılaştırılmış petrol gazı (LPG)"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre akaryakıt antrepoları; benzin türleri, ham petrol, nafta (hammadde ve solvent nafta hariç), gaz yağı, jet yakıtı, motorin türleri, fuel-oil türleri, bio dizel ile sıvılaştırılmış petrol gazının (LPG) dökme veya kaplı olarak konulmasına özgü genel veya özel antrepolardır. Nafta tanımda yer almakla birlikte hammadde ve solvent nafta açıkça hariç tutulmuştur. Akaryakıt konulan antrepoların mal tahmil ve tahliyesinde kullanılan boru hatları da antreponun mütemmim cüzü sayılır. En güçlü çeldirici ham petroldür: denizyoluyla gelen akaryakıtın sayaçla ölçülmesine ilişkin listede ham petrol yer almaz, ancak akaryakıt antreposu tanımında sayılmıştır. Bu nedenle doğru cevap 'Hammadde ve solvent nafta' seçeneğidir. (MD GY 541; GY 542)",
kanit="29-iŞLETİCİLER.txt | Akaryakıt antrepoları, benzin türleri, ham petrol, nafta (hammadde ve solvent nafta hariç), gaz yağı, jet yakıtı, motorin türleri, fuel-oil türleri, bio dizel ile sıvılaştırılmış petrol gazının (LPG) dökme veya kaplı olarak konulmasına özgü genel veya özel antrepolardır || 29-iŞLETİCİLER.txt | denizyoluyla gelen veya giden benzin türleri, nafta (hammadde ve solvent nafta hariç), gaz yağı, jet yakıtı",
yuva=["Tanımda sayılan: ham petrol (GY 541/1); sayaç listesinde yer almaması (GY 542/1) karışıklık yaratır",
      "Tanımda sayılan: jet yakıtı (GY 541/1)",
      "Tanımda sayılan: bio dizel (GY 541/1)",
      "Tanımda sayılan: sıvılaştırılmış petrol gazı (LPG) (GY 541/1)"],
yakinlik="BİREBİR",
tuzak=["İSTİSNA", "LİSTE-DIŞI"], duzey=["TANIMA"], profil=[1, 3],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 18 — İznin geri alınmasının sonuçları (kalıcı yasak ↔ beş yıllık yasak)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="DOĞRU",
z="Z",
madde="Gümrük Yönetmeliği md. 525",
cek="Kaçakçılık gibi suistimal veya vergi kaybı nedeniyle izni geri alınana yeni izin verilmez; kendi isteğiyle kapatma hariç bağlantılı tüzel kişilere beş yıl izin verilmez.",
kok=["Gümrük Yönetmeliği'ne göre antrepo açma ve işletme izninin geri alınmasının sonuçlarına ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Antrepoda kaçakçılık gibi bir suistimal saptanması nedeniyle antrepo açma ve işletme izni geri alınan kişilere yeni bir antrepo açma ve işletme izni verilmez.",
c=["Sahiplerinin isteği üzerine kapatılan antreponun işleticisi olan şirketin yönetim kurulu üyelerinin yer aldığı diğer tüzel kişilere, kapatma tarihinden itibaren beş yıl süreyle antrepo açma izni verilmez.",
   "İzni geri alınan şirketin ortaklarının yer aldığı diğer tüzel kişilere, iznin geri alındığı tarihten itibaren üç yıl süreyle yeniden antrepo açma izni verilmez.",
   "Yasaklama süresi geçtikten sonra bu kişilerin antrepo açma veya devralma müracaatları bölge müdürlüğünce sonuçlandırılır.",
   "Antrepo işleticisinin taahhüt ve yükümlülüklerine aykırı hareket etmesi nedeniyle vergi kaybına neden olunması hâlinde izin geri alınamaz; yalnızca antrepoya eşya girişi durdurulur."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre antrepo işleticisinin taahhüt ve yükümlülüklerine aykırı hareket etmesi nedeniyle vergi kaybına neden olunması hâlinde antrepo açma ve işletme izni geri alınabilir. Antrepoda kaçakçılık gibi bir suistimal ve/veya yolsuzluk saptanması ya da bu vergi kaybı nedeniyle izni geri alınan kişilere yeni bir antrepo açma ve işletme izni verilmez. Sahiplerinin isteğiyle kapatılma hâli hariç olmak üzere izni geri alınan şirketin anonim şirketlerde yönetim kurulu üyelerinin, limited şirketlerde ortakları ile şirket müdürünün ve sermayenin %10 veya daha fazlasına sahip gerçek kişilerin yer aldığı diğer tüzel kişilere iznin geri alındığı tarihten itibaren 5 yıl süreyle yeniden antrepo açma izni verilmez; bu süre geçtikten sonraki açma veya devralma müracaatları Bakanlıkça sonuçlandırılır. En güçlü çeldirici kendi isteğiyle kapatılan antrepoya beş yıllık yasağı uygulayan seçenektir; hüküm bu hâli açıkça dışarıda bırakır. Üç yıl ise yatırım izni başvurusunda aranan asgari faaliyet süresidir. Bu nedenle doğru cevap 'Antrepoda kaçakçılık gibi bir suistimal saptanması nedeniyle antrepo açma ve işletme izni geri alınan kişilere yeni bir antrepo açma ve işletme izni verilmez.' seçeneğidir. (MD GY 525)",
kanit="29-iŞLETİCİLER.txt | Antrepoda kaçakçılık gibi bir suistimal ve/veya yolsuzluk saptanması veya sekizinci fıkrada belirtilen durum nedeniyle antrepo açma ve işletme izni geri alınan kişilere, yeni bir antrepo açma ve işletme izni verilmez || 29-iŞLETİCİLER.txt | sahiplerinin isteği ile kapatılma hali hariç, antrepo açma izni geri alınan || 29-iŞLETİCİLER.txt | iznin geri alındığı tarihten itibaren 5 yıl süre ile yeniden antrepo açma izni verilmez. Bu süre geçtikten sonra, bu fıkrada sayılan kişilerin antrepo açmak veya devralmak istemeleri halinde; müracaatlar, ilgili bilgi, belge ve veriler dikkate alınarak Bakanlıkça sonuçlandırılır || 29-iŞLETİCİLER.txt | Antrepo işleticisinin taahhüt ve yükümlülüklerine aykırı hareket etmesi nedeniyle vergi kaybına neden olunması halinde antrepo açma ve işletme izni geri alınabilir",
yuva=["Beş yıllık yasak sahiplerinin isteğiyle kapatma hâlini kapsamaz (GY 525/6) – istisna",
      "Yasak süresi beş yıldır (GY 525/6); üç yıl yatırım izninde aranan faaliyet süresidir (GY 518/2)",
      "Süre sonrası müracaatlar Bakanlıkça sonuçlandırılır (GY 525/6) – makam",
      "Vergi kaybında izin geri alınabilir (GY 525/8); eşya girişinin durdurulması tedbir hükmüdür (GY 525/2)"],
yakinlik="BİREBİR",
tuzak=["SAYI", "İSTİSNA", "MAKAM"], duzey=["AYIRT"], profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 19 — Geçici depolama yeri tanımından ad
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="KAVRAM",
z="K",
madde="Gümrük Yönetmeliği md. 79",
cek="Eşyayı dış etken ve müdahalelerden koruyacak şekilde yapılmış, taşıtların durduğu, yanaştığı veya indiği yerlerdeki ambar, depo, ardiye, hangar gibi yerler geçici depolama yerleridir.",
kok=["Gümrük Yönetmeliği'ne göre gümrüğe sunulmuş ve henüz gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulmamış eşyanın her türlü dış etken ve müdahalelerden korunmasını sağlayacak şekilde yapılmış olan ve taşıtların durduğu, yanaştığı veya indiği yerlerdeki ambar, ardiye veya hangar gibi yerlere ne ad verilir?"],
d="Geçici depolama yerleri",
c=["Gümrüklü sahalar", "Genel antrepolar", "Rezerve yerleri", "Yolcu beraberi eşya ambarları"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre geçici depolanan eşyanın her türlü dış etken ve müdahalelerden korunmasını sağlayacak şekilde yapılmış ve taşıtların durduğu, yanaştığı veya indiği yerlerdeki ambar, depo, ardiye veya hangar gibi yerler geçici depolama yerleridir. Gümrüğe sunulan eşya gümrükçe onaylanmış bir işlem veya kullanıma tabi tutuluncaya kadar geçici depolanan eşya statüsündedir; tanımdaki yerler bu eşyanın konulduğu yerlerdir. Gümrüklü saha, gümrük idaresinin denetiminde fiziki olarak etrafından ayrılmış veya böyle addedilen alanı ifade eder; yolcu beraberi eşya ambarları ise geçici depolama yeri addolunan özel yerlerdir. Rezerve yeri, rezerveli eşyanın geçici depolama yeri içinde ayrılan çift kilitli bölümüdür; genel antrepolar ise antrepo rejimine tabi eşyanın depolandığı yerlerdir. Bu nedenle doğru cevap 'Geçici depolama yerleri' seçeneğidir. (MD GY 79; GK 47)",
kanit="29-iŞLETİCİLER.txt | Geçici depolanan eşyanın her türlü dış etken ve müdahalelerden korunmasını sağlayacak şekilde yapılmış ve taşıtların durduğu, yanaştığı veya indiği yerlerdeki ambar, depo, ardiye veya hangar gibi yerler geçici depolama yerleridir || 1-TANIMLAR.txt | fiziki olarak etrafından ayrılmış veya böyle addedilen yerleri || 29-iŞLETİCİLER.txt | geçici depolama yerinde ayrılmış kapalı ve muhafazalı rezerve yerine konulur",
yuva=["Gümrüklü saha tanımı (1-TANIMLAR.txt, GY 3) – benzer kavram",
      "Genel antrepolar: antrepo rejimine tabi eşyanın depolandığı yerler (GY 519, 536) – komşu kavram",
      "Rezerve yeri: rezerveli eşyanın konulduğu çift kilitli bölüm (GY 84/3) – komşu madde",
      "Yolcu beraberi eşya ambarı: GDY addolunan özel yer (GY 79/2, 80) – komşu fıkra"],
yakinlik="PARAFRAZ",
tuzak=["TERİM"], duzey=["TANIMA"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# 20 — Güncellik: GDY'den kesin çıkış hükmünün 2022 değişik hâlinin Danıştay kararlarıyla iptali (12.08.2026)
dict(
konu="Gümrük Antrepoları ve İşleticileri", blok="SB28",
kalip="DOĞRU",
z="Z",
madde="Gümrük Yönetmeliği md. 94",
cek="GDY'den kesin çıkışta sistemde çıkış onayıyla sahip, temsilci veya vekile izin verilir; hükmün 25.05.2022 değişik hâli 12.08.2026 yazısıyla iptal edilmiştir.",
kok=["Gümrük Yönetmeliği'nin geçici depolama yerlerinden eşyanın kesin çıkış işlemlerine ilişkin hükmü ile ilgili aşağıdakilerden hangisi doğrudur?"],
d="Hükmün 25.05.2022 tarihli değişiklikle kazandığı hâli, 12.08.2026 tarihli yazı eki Danıştay kararları ile iptal edilmiştir.",
c=["Hükmün 25.05.2022 tarihli değişiklikle kazandığı hâlinin yürütmesi 12.08.2026 tarihli yazı eki Danıştay kararları ile durdurulmuş, hüküm ise uygulanmaya devam etmektedir.",
   "Hüküm 25.05.2022 tarihinde yürürlükten kaldırılmış, 12.08.2026 tarihli yazı eki Danıştay kararları ile yeniden yürürlüğe konulmuştur.",
   "Çıkış onayı, gümrük işlemlerinin sistem üzerinde tamamlanması beklenmeksizin geçici depolama yeri işleticisince verilir.",
   "Eşyanın çıkarılmasına yalnızca eşya sahibi veya temsilcisi için izin verilir; eşyayı teslim almak için vekâlet verilmiş diğer kişilere izin verilmez."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre gümrük işlemlerinin sistem üzerinde tamamlandığının anlaşılması üzerine bilgisayar sisteminde çıkış onayı verilerek eşya sahibinin, temsilcisinin veya eşyayı teslim almak için vekâlet verilmiş diğer kişilerin eşyayı geçici depolama yerinden çıkarmasına izin verilir. Hükmün 25.05.2022 tarihli ve 31846 sayılı Resmî Gazete ile yapılan değişiklikle kazandığı hâli, 12.08.2026 tarihli yazı eki Danıştay kararları ile iptal edilmiştir; bu iptal son on iki ay içinde gerçekleşmiştir. En güçlü çeldirici yürütmenin durdurulduğunu söyleyen seçenektir: Yönetmelikte yürütmesi durdurulan hükümler ayrıca belirtilmiştir, bu hükümde ise iptal söz konusudur. Çıkış onayı gümrük işlemleri sistemde tamamlanmadan işleticice verilemez; vekâlet verilmiş kişilerin eşyayı çıkarması da mümkündür. Bu nedenle doğru cevap 'Hükmün 25.05.2022 tarihli değişiklikle kazandığı hâli, 12.08.2026 tarihli yazı eki Danıştay kararları ile iptal edilmiştir.' seçeneğidir. (MD GY 94)",
kanit="29-iŞLETİCİLER.txt | (25.05.2022 / 31846 sayılı R.G. ile değişik hali 12.08.2026 / 125252902 yazı eki Danıştay Kararları ile iptal edilmiştir.) || 29-iŞLETİCİLER.txt | Gümrük işlemlerinin sistem üzerinde tamamlandığının anlaşılması üzerine bilgisayar sisteminde çıkış onayı verilerek eşya sahibinin, temsilcisinin veya eşya sahibi tarafından eşyayı teslim almak için vekâlet verilmiş diğer kişilerin eşyayı geçici depolama yerinden çıkarmasına izin verilir || 29-iŞLETİCİLER.txt | Danıştay 10.Daire 2014/6556 sayılı Yürütülmesinin Durdurulması Kararı",
yuva=["Yürütmeyi durdurma notları başka GDY hükümlerinde geçer (GY 78/4-5) – komşu madde; bu hükümde iptal vardır",
      "Uydurma kronoloji: hüküm 2022'de değiştirilmiş, kaldırılmamıştır; 2026'da değişik hâli iptal edilmiştir",
      "Çıkış onayı gümrük işlemlerinin sistemde tamamlanmasından sonra verilir (GY 94/1)",
      "Vekâlet verilmiş kişiler de eşyayı çıkarabilir (GY 94/1)"],
yakinlik="PARAFRAZ",
tuzak=["TERİM", "KOMŞU"], duzey=["HATIRLAMA"], profil=[5],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="12.08.2026", cikmis="", kapsamli=False,
),

]
