# Soru Bankası — Bölüm 29: Gümrüksüz Satış Mağazaları (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
# Kaynak: 30-Güm.Sat.Mağazaları.txt (Gümrüksüz Satış Mağazaları Yönetmeliği, 08.08.2017/30148 R.G.);
# eksen 17 yuvası için 28-antrepo rejimi.txt (GK 94), sayı havuzu için 29-iŞLETİCİLER.txt (GY 527),
# 'diplomatik satış mağazası' yuvası için 31-YGM.txt
K = "30-Güm.Sat.Mağazaları.txt"
AN = "28-antrepo rejimi.txt"
IS = "29-iŞLETİCİLER.txt"
YG = "31-YGM.txt"
M = "Gümrüksüz Satış Mağazaları Yönetmeliği"
Y = "Gümrüksüz Satış Mağazaları Yönetmeliği'ne göre"
Q = [

# 1 — Addan tanım: depo (özel antrepo sayılan yer) — eksen 17, çıkmış 2024/63 bilgi alanı
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="TANIM",
z="O",
madde=M + " md. 3; 4458 sayılı Gümrük Kanunu md. 94",
cek="Depo, aynı firmanın çeşitli yerlerdeki mağazalarının stok ihtiyacı için eşya konulan ve özel antrepo sayılan yerdir; mağazalar da özel antrepo sayılır.",
kok=[M + "'nde geçen \"depo\" ifadesinin tanımı aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Aynı firmanın çeşitli yerlerde bulunan mağazalarının stok ihtiyacını karşılamak amacıyla eşya konulan ve özel antrepo sayılan yerler",
c=["Aynı firmanın çeşitli yerlerde bulunan mağazalarının stok ihtiyacını karşılamak amacıyla eşya konulan ve genel antrepo sayılan yerler",
   "Farklı firmalara ait mağazaların ortak stok ihtiyacını karşılamak amacıyla eşya konulan ve özel antrepo sayılan yerler",
   "Uçaklara ve gemilere teslim edilecek eşyanın hazırlandığı, hava ve deniz hudut kapılarında yolcu giriş ve çıkışı yapılan yerlerde açılması zorunlu olan yerler",
   "Mağazalarda satılamayan veya satışına izin verilmeyen eşyanın iade edilerek geçici depolama yeri olarak muhafaza edildiği yerler"],
sirali=False,
g="Gümrüksüz Satış Mağazaları Yönetmeliği'nde depo; aynı firmanın çeşitli yerlerde bulunan mağazalarının stok ihtiyacını karşılamak amacıyla eşya konulan, Gümrük Kanunu ve Gümrük Yönetmeliği'nde belirtilen özellikleri taşıyan ve özel antrepo sayılan yerler olarak tanımlanır. Yönetmelik aynı nitelemeyi gümrüksüz satış mağazası, uçakta satış mağazası ve gemilere satış mağazası için de kullanır; bunların hepsi özel antrepo sayılan yerlerdir. Gümrük Kanunu'na göre genel antrepo, eşyanın konulması için herkes tarafından kullanılabilen antrepodur; depo ise yalnızca aynı firmanın mağazalarına hizmet eder. En güçlü çeldirici 'genel antrepo sayılan yerler' ifadesidir: tanımın diğer bütün unsurları doğrudur, yalnızca antrepo türü değiştirilmiştir. Depo farklı firmaların ortak deposu da değildir; firmalar yalnızca kendi mağaza ve depoları arasında eşya sevk edebilir. Depoların hava ve deniz kapılarında yolcu giriş ve çıkışı yapılan yerler dışında da açılmasına izin verilebilir. Bu nedenle doğru cevap 'Aynı firmanın çeşitli yerlerde bulunan mağazalarının stok ihtiyacını karşılamak amacıyla eşya konulan ve özel antrepo sayılan yerler' seçeneğidir. (MD 3; GK 94)",
kanit=K + " | Depo: Aynı firmanın çeşitli yerlerde bulunan mağazalarının stok ihtiyacını karşılamak amacıyla eşya konulan || " + K + " | belirtilen özellikleri taşıyan ve özel antrepo sayılan yerleri || " + K + " | 1 inci maddede belirtilen kişilere satış yapmak üzere açılmasına ve işletilmesine izin verilen ve özel antrepo sayılan yerleri || " + AN + " | Genel Antrepolar, eşyanın konulması için herkes tarafından kullanılabilen || " + K + " | Firmaların sadece kendi mağaza ve depoları arasında eşya sevki yapılabilir.",
yuva=["Gümrük Kanunu'ndaki antrepo türleri: genel antrepo herkesin kullanabildiği antrepodur; tanım 'özel antrepo' der (eksen 17)",
      "Eşya hareketleri hükmü: firmalar yalnızca kendi mağaza ve depoları arasında sevk yapabilir; 'aynı firma' unsuru 'farklı firmalar'a çevrilmiş",
      "Mağaza ve depo açılabilecek yerler hükmü: depolar hava ve deniz kapılarında yolcu giriş-çıkış yerleri dışında da açılabilir; uçakta satış mağazası tanımı ile karıştırılmış",
      "Eşya hareketleri hükmü: satışına izin verilmeyen eşya depodan mağazaya sevk edilemez ve mağazadan depoya iade yapılır; geçici depolama ayrı bir statüdür"],
yakinlik="BİREBİR",
tuzak=["TERİM", "UNSUR"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=17, ayna="",
guncellik="",
cikmis="2024/63",
kapsamli=False,
),

# 2 — Diplomatik muafiyetten yararlananlara satış yapılan mağazalar — çıkmış 2025/83 bilgi alanı
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="KAPSAM",
z="O",
madde=M + " md. 3, 4, 11",
cek="Diplomatik muafiyetten yararlananlar ve yabancı basın mensuplarına Ankara ve İstanbul hava hudut kapılarındaki yolcu girişi mağazalarından takrirle satış yapılır.",
kok=[Y + " diplomatik muafiyetlerden yararlananlar ile yabancı basın yayın organlarının yabancı uyruklu mensuplarına, bu sıfatlarına dayanılarak satış yapılabilecek mağazalar aşağıdakilerden hangisidir?"],
d="Ankara ve İstanbul'daki hava hudut kapılarında yolcu girişi yapılan yerlerde bulunan mağazalar",
c=["Ankara ve İstanbul'daki hava hudut kapılarında yolcu çıkışı yapılan yerlerde bulunan mağazalar",
   "Ankara'da yalnızca bu kişilere satış yapmak üzere açılan ve özel antrepo sayılan diplomatik satış mağazaları",
   "Kara, hava, deniz ve demiryolu gümrük kapılarında yolcu girişi yapılan yerlerde bulunan bütün mağazalar",
   "Hava hudut kapılarında yolculardan arındırılmış yerlerde açılan uçakta satış mağazaları"],
sirali=False,
g="Yönetmeliğe göre Ankara ve İstanbul'daki hava hudut kapılarında yolcu girişi yapılan yerlerde bulunan mağazalardan, diplomatik muafiyetlerden yararlananlar ile yabancı basın yayın organlarının yabancı uyruklu mensuplarına satış yapılabilir. Satış; diplomatik muafiyetlerden faydalananlar için Dışişleri Bakanlığınca onaylanmış, yabancı basın mensupları için Cumhurbaşkanlığı İletişim Başkanlığı tarafından düzenlenmiş ve ilgili gümrük müdürlüğünce tescil edilmiş takrirler karşılığında yapılır. Yönetmelik bu kişiler için ayrı bir 'diplomatik satış mağazası' türü tanımlamaz; tanımlanan yerler gümrüksüz satış mağazası, gemilere satış mağazası, uçakta satış mağazası ve depodur. En güçlü çeldirici aynı kapılardaki çıkış mağazalarıdır: hüküm yalnızca yolcu girişi yapılan yerlerdeki mağazaları sayar. Uçakta satış mağazası ise yalnızca yabancı ülkelere sefer yapan uçaklara eşya teslim eder; bütün kapılardaki giriş mağazaları da bu kişilere bu sıfatla satış yapamaz. Bu nedenle doğru cevap 'Ankara ve İstanbul'daki hava hudut kapılarında yolcu girişi yapılan yerlerde bulunan mağazalar' seçeneğidir. (MD 3, 4, 11)",
kanit=K + " | Ankara ve İstanbul'daki hava hudut kapılarında yolcu girişi yapılan yerlerde bulunan mağazalardan, diplomatik muafiyetlerden yararlananlar ile yabancı basın yayın organlarının yabancı uyruklu mensuplarına satış yapılabilir || " + K + " | Diplomatik muafiyetlerden faydalananlara Dışişleri Bakanlığınca onaylanmış || " + K + " | ilgili gümrük müdürlüğünce tescil edilmiş takrirler karşılığında satış yapılır || " + K + " | sadece yabancı ülkelere sefer yapan uçaklara eşya teslimi yapmak üzere hava hudut kapılarında yolculardan arındırılmış yerlerde açılan || " + YG + " | diplomatik satış mağazaları, uçakta satış mağazaları ve gemilere eşya satış mağazaları",
yuva=["Satılabilecek eşya hükmü: çıkış kapılarındaki mağazalar Türkiye'den çıkış yapan yolculara satar; giriş-çıkış ters çevrilmiş",
      "Yetkilendirilmiş Gümrük Müşavirliği Tebliği'nde 'diplomatik satış mağazaları' ifadesi geçer; Yönetmelik böyle ayrı bir tür tanımlamaz",
      "Mağaza ve depo açılabilecek yerler hükmü: kara, hava, deniz ve demiryolu kapılarındaki giriş ve çıkış yerleri; 'bütün' ile genelleştirilmiş",
      "Tanımlar hükmü: uçakta satış mağazası yolculardan arındırılmış yerlerde açılır ve yalnızca yabancı ülkelere sefer yapan uçaklara eşya teslim eder"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM", "SAĞDUYU"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2025/83",
kapsamli=False,
),

# 3 — Açma eşiğinde esas alınan dönem (süre + başlangıç anı)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="SÜRE",
z="Z",
madde=M + " md. 4, 29",
cek="Açma eşiğinde başvuru tarihinden önceki aydan başlayan son on iki ay ya da bir önceki takvim yılı esas alınır; iptal yalnız önceki takvim yılına bakar.",
kok=[Y + " hudut kapılarında girişte mağaza açılabilmesi için aranan toplam en az 30.000 yolcu, nakil vasıtası sürücü ve hizmetlisi girişi hangi dönem esas alınarak değerlendirilir?"],
d="Başvuru tarihinden önceki aydan başlamak üzere son on iki ay ya da bir önceki takvim yılı",
c=["Yalnızca başvuru tarihinden bir önceki takvim yılı",
   "Başvuru tarihinden önceki aydan başlamak üzere son altı ay",
   "Başvuru tarihinden geriye doğru son beş yılın yıllık ortalaması",
   "Ön izin başvurusunun Genel Müdürlükçe uygun bulunduğu tarihten geriye doğru son on iki ay"],
sirali=False,
g="Yönetmeliğe göre hudut kapılarında girişte mağaza açılabilmesi için başvuru tarihinden önceki aydan başlamak üzere son on iki ay ya da bir önceki takvim yılı içinde toplam en az 30.000 yolcu, nakil vasıtası sürücü ve hizmetlisinin giriş yapmış olması gerekir; çıkışta aynı dönem için aranan sayı 10.000'dir. Dönemin başlangıcı başvuru tarihi değil, başvuru tarihinden önceki aydır ve iki dönemden biri esas alınabilir. En güçlü çeldirici 'yalnızca bir önceki takvim yılı' seçeneğidir: bu ölçüt açılmış mağazanın izninin iptali değerlendirilirken kullanılır; iptal hükmü bir önceki takvim yılında bu sayıların altında giriş ve çıkış yapılmasını esas alır. Altı ay faaliyete geçme süresine, son beş yıl ise kurumlar vergisi ortalamasının hesaplandığı döneme aittir; ön izin aşamasında Genel Müdürlük yolcu sayısının sağlanıp sağlanmadığını değerlendirir, dönemi ön izin tarihinden saymaz. Bu nedenle doğru cevap 'Başvuru tarihinden önceki aydan başlamak üzere son on iki ay ya da bir önceki takvim yılı' seçeneğidir. (MD 4, 29)",
kanit=K + " | girişte mağaza açılabilmesi için başvuru tarihinden önceki aydan başlamak üzere son on iki ay ya da bir önceki takvim yılı içinde toplam en az 30.000 yolcu || " + K + " | toplam en az 10.000 yolcu, nakil vasıtası sürücü ve hizmetlisinin çıkış yapmış olması gerekir || " + K + " | Bir önceki takvim yılında, yolcu, nakil vasıtası sürücü ve hizmetlileri sayısı itibarıyla 4 üncü maddenin ikinci fıkrasında belirtilen sayıların altında giriş ve çıkış yapıldığı tespit edilen",
yuva=["İzinlerin iptali hükmü: bir önceki takvim yılında eşiğin altında kalan kapılardaki mağazaların izni iptal edilebilir",
      "Faaliyete geçme hükmü: izin yazısının tebliğini izleyen günden itibaren altı ay (sayı havuzu)",
      "Başvurabilecekler hükmü: son beş yılda tahakkuk eden kurumlar vergisinin basit ortalaması",
      "Ön izin hükmü: Genel Müdürlük gerekli yolcu sayısının sağlanıp sağlanmadığını değerlendirir; başlangıç anı kaydırılmış"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU"],
duzey=["AYIRT"],
profil=[2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 4 — Tek işletmeci (tek kelime değişikliği: çıkış -> giriş)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="YANLIŞ",
z="O",
madde=M + " md. 5",
cek="Her hudut kapısında tek işletmeci esastır; tek işletmeciyle sözleşmeli firmalara alkol-tütün dışı satış izni yalnız çıkış mağazaları için verilebilir.",
kok=[Y + " hudut kapılarında mağaza işletmeciliğine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Girişe yönelik mağazalarla sınırlı olarak, tek işletmeci ile işletme sözleşmesi bulunan firmalara alkollü içki, tütün ve tütün mamulleri dışında eşya satışı için mağaza açma izni verilebilir.",
c=["Gümrüksüz satış mağazası açılmak istenilen her bir hudut kapısı ve yerde mağaza işletmeciliği tek bir işletmeci tarafından yapılır.",
   "Her bir hudut kapısı ve yerde bulunan mağaza için açma izni başvuruları ayrı ayrı yapılarak sonuçlandırılır.",
   "Hava hudut kapılarında uçakta satış mağazası işletmeciliği, her bir hudut kapısı itibarıyla tek bir işletmeci tarafından yapılır.",
   "Kamu kurum ve kuruluşları ile belediyeler, mağaza açılabilecek yerlerdeki taşınmazlarını Bakanlıktan görüş alınması suretiyle ve tek bir işletmeci tarafından işletilmek şartıyla ihale mevzuatı çerçevesinde kiraya verebilir."],
sirali=False,
g="Yönetmeliğe göre mağaza açılmak istenilen her bir hudut kapısı ve yerde işletmecilik tek bir işletmeci tarafından yapılır ve her mağaza için açma izni başvuruları ayrı ayrı sonuçlandırılır. Bu kuralın istisnası yalnızca çıkışa yönelik mağazalar içindir: çıkışa yönelik mağazalarla sınırlı olarak, o yerdeki tek işletmeci ile işletme sözleşmesi bulunan ve başvuru şartlarını taşıyan firmalara alkollü içki, tütün ve tütün mamulleri dışında eşya satışı yapmak üzere mağaza açma izni verilebilir. Yanlış ifadede 'çıkışa' yerine 'girişe' yazılmıştır; bu tek kelime hükmün uygulandığı mağazaları tersine çevirir. Uçakta satış mağazası işletmeciliği de her hudut kapısı itibarıyla tek işletmecidedir. En güçlü çeldirici kamu taşınmazlarının kiralanmasına ilişkin ifadedir: uzun ve ayrıntılı olduğu için yanlış sanılabilir, ancak Bakanlık görüşü ve tek işletmeci şartı hükmün lafzıdır. Bu nedenle doğru cevap 'Girişe yönelik mağazalarla sınırlı olarak, tek işletmeci ile işletme sözleşmesi bulunan firmalara alkollü içki, tütün ve tütün mamulleri dışında eşya satışı için mağaza açma izni verilebilir.' seçeneğidir. (MD 5)",
kanit=K + " | Gümrüksüz satış mağazası açılmak istenilen her bir hudut kapısı ve yerde mağaza işletmeciliği tek bir işletmeci tarafından yapılır. || " + K + " | Her bir hudut kapısı ve yerde bulunan mağaza için açma izni başvuruları ayrı ayrı yapılarak sonuçlandırılır. || " + K + " | Çıkışa yönelik mağazalarla sınırlı olarak, bu yerdeki tek işletmeci ile işletme sözleşmesi bulunan ve 6 ncı maddede belirtilen şartları taşıyan firmalara alkollü içki, tütün ve tütün mamulleri dışında eşya satışı yapmak üzere mağaza açma izni verilebilir || " + K + " | Hava hudut kapılarında uçakta satış mağazası işletmeciliği, her bir hudut kapısı itibarıyla tek bir işletmeci tarafından yapılır. || " + K + " | Bakanlıktan görüş alınması suretiyle gümrüksüz satış mağazası işletmek üzere tek bir işletmeci tarafından işletilmek şartı ile ilgili ihale mevzuatı çerçevesinde kiraya verebilir",
yuva=["Tek işletmeci hükmü, ilk cümle (doğru ifade)",
      "Tek işletmeci hükmü, ikinci cümle: başvurular her kapı için ayrı ayrı sonuçlandırılır (doğru ifade)",
      "Tek işletmeci hükmü: uçakta satış mağazasında her hudut kapısı itibarıyla tek işletmeci (doğru ifade)",
      "Tek işletmeci hükmü: kamu kurumları ve belediyelerin taşınmazlarını kiraya vermesi (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 5 — Vaka: 50.000.000 TL sermaye istisnası
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="ŞART",
z="Z",
madde=M + " md. 6, 18",
cek="Sermaye ve ihtiyatları en az 50.000.000 TL olan şirkette iki yıl faaliyet ve kurumlar vergisi şartları aranmaz; mahkûmiyet ve borç şartları sürer.",
kok=["(A) Anonim Şirketi, bir hava hudut kapısında gümrüksüz satış mağazası açma izni almak üzere başvuru hazırlığındadır. Şirkete ilişkin bilgiler şöyledir:",
     "- Şirket 14 aydır faaliyettedir.",
     "- Ödenmiş sermayesi ve ihtiyatları toplamı 60.000.000 TL'dir.",
     "- Faaliyette bulunduğu tek hesap döneminde tahakkuk eden kurumlar vergisi 120.000 TL'dir.",
     "- Gümrük ve vergi mevzuatı uyarınca vadesi geçmiş borcu yoktur; yönetim kurulu üyeleri hakkında başvuruya engel bir mahkûmiyet kararı bulunmamaktadır.",
     M + "'nin mağaza ve depo açma izni için başvuruda bulunabileceklere ilişkin hükümlerine göre (A) Anonim Şirketi hakkında aşağıdakilerden hangisi doğrudur?"],
d="Faaliyet süresi ve kurumlar vergisi şartları aranmayacağından şirket mağaza açma izni için başvuruda bulunabilir.",
c=["Asgari iki yıldır faaliyette bulunma şartını taşımadığından şirket başvuruda bulunamaz.",
   "İki yıllık faaliyet şartı aranmaz; ancak kurumlar vergisi ortalaması 300.000 TL'nin altında kaldığından şirket başvuruda bulunamaz.",
   "Şirketin başvurabilmesi için kurucu ortaklarından en az birinin asgari iki yıldır faaliyette bulunması gerekir.",
   "Sermaye istisnası nedeniyle yönetim kurulu üyeleri için mahkûmiyet bulunmaması şartı da aranmaz."],
sirali=False,
g="Yönetmeliğe göre mağaza ve depo açma izni, kamu kuruluşları dışında, asgari iki yıldır faaliyette bulunan, ödenmiş sermayeleri ve ihtiyatları toplamı en az 5.000.000 TL ve son beş yılda tahakkuk eden kurumlar vergisinin basit ortalaması en az 300.000 TL olan limited veya anonim şirketlere verilebilir. Vakada saklanan istisna sermaye tutarıdır: ödenmiş sermayeleri ve ihtiyatları toplamı en az 50.000.000 TL olan şirketlerde iki yıl faaliyette bulunma ve kurumlar vergisi şartları aranmaz. (A) Anonim Şirketinin sermaye ve ihtiyatları 60.000.000 TL olduğundan 14 aylık faaliyet süresi ve 120.000 TL kurumlar vergisi başvuruya engel değildir. Bu istisna, yönetim kurulu üyeleri ve sermayenin yüzde onundan fazlasına sahip gerçek kişiler hakkında mahkûmiyet bulunmaması şartını ve vadesi geçmiş borç bulunmaması şartını kaldırmaz; vakada bu şartlar sağlanmıştır. En güçlü çeldirici iki yıl şartına dayanan seçenektir: genel kuralı bilen ama 50.000.000 TL istisnasını görmeyen adayı yakalar. Kurucu ortaklardan birinin iki yıldır faaliyette olması ise devralan şirketin yeni kurulmuş olduğu devir hâline ilişkin hükümdür. Bu nedenle doğru cevap 'Faaliyet süresi ve kurumlar vergisi şartları aranmayacağından şirket mağaza açma izni için başvuruda bulunabilir.' seçeneğidir. (MD 6, 18)",
kanit=K + " | Asgari iki yıldır faaliyette bulunan, ödenmiş sermayeleri ve ihtiyatları toplamı en az 5.000.000 (beş milyon) TL ve son beş yılda tahakkuk eden kurumlar vergisinin basit ortalaması en az 300.000 (üç yüz bin) TL olan limited veya anonim şirketler || " + K + " | Ödenmiş sermayeleri ve ihtiyatları toplamı en az 50.000.000 (elli milyon) TL olan şirketlerde, birinci fıkranın (b) bendinde yer alan 2 yıl faaliyette bulunma ve kurumlar vergisi şartları aranmaz || " + K + " | sermayesinin yüzde onundan fazlasına sahip gerçek kişiler || " + K + " | Devralan şirketin yeni kurulmuş bir şirket olması ve kurucu ortaklarından en az birinin asgari iki yıldır faaliyette bulunması hâlinde",
yuva=["Başvurabilecekler hükmünün genel kuralı: asgari iki yıl faaliyet (istisna görülmemiş)",
      "Başvurabilecekler hükmünün genel kuralı: kurumlar vergisi ortalaması en az 300.000 TL (istisnanın yarısı uygulanmış)",
      "Mağazaların devri hükmü: devralan yeni şirkette kurucu ortaklardan birinin iki yıl faaliyeti aranır",
      "Başvurabilecekler hükmü: mahkûmiyet bulunmaması şartı sermaye istisnasından etkilenmez (istisna genişletilmiş)"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "ŞART"],
duzey=["UYGULAMA"],
profil=[2],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 6 — Götürü teminat tutarı (sıralı sayısal)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="ORAN-TUTAR",
z="O",
madde=M + " md. 19, 20",
cek="Mağaza başına götürü teminat tütün, tütün mamulleri ve alkollü içki satan mağazalarda 5.000.000 TL, diğerlerinde 2.000.000 TL'dir.",
kok=[Y + " tütün, tütün mamulleri ve alkollü içki satışı yapan bir mağaza için mağaza başına alınacak götürü teminat miktarı kaç TL'dir?"],
d="5.000.000",
c=["2.000.000", "3.000.000", "30.000.000", "40.000.000"],
sirali=True,
siklar=["2.000.000", "3.000.000", "5.000.000", "30.000.000", "40.000.000"],
g="Yönetmeliğe göre mağaza ve depo başına alınacak götürü teminat miktarı, tütün, tütün mamulleri ve alkollü içki satışı yapan mağazalar için 5.000.000 TL, diğerleri için 2.000.000 TL'dir. Birden fazla mağaza ve depo işletmeciliği yapan firmalar, Merkez Saymanlık Müdürlüğü hesabına kaydedilmek üzere Elektronik Teminat Modülü üzerinden Genel Müdürlüğe 30.000.000 TL tutarında teminat vererek birden fazla mağaza ve depo için götürü teminat sisteminden yararlanabilir. Götürü teminat sisteminden yararlanan firmaların mağaza ve depolarına konulacak eşya için ayrıca teminat aranmaz. En güçlü çeldirici aynı hükümdeki 2.000.000 TL'dir; bu tutar tütün ve alkol satmayan mağazalara aittir. 3.000.000 TL ve 40.000.000 TL ise Gümrük Yönetmeliği'nde antrepo işleticilerinin götürü teminatına ilişkin tutarlardır. Bu nedenle doğru cevap '5.000.000' seçeneğidir. (MD 19, 20; GY 527)",
kanit=K + " | tütün, tütün mamulleri ve alkollü içki satışı yapan mağazalar için 5.000.000 TL, diğerleri için 2.000.000 TL dir || " + K + " | Elektronik Teminat Modülü üzerinden Genel Müdürlüğe 30.000.000 TL || " + K + " | Götürü teminat sisteminden yararlanan firmaların mağaza ve depolarına konulacak eşya için ayrıca teminat aranmaz. || " + IS + " | 2.000 m³'e kadar olanlar için 3.000.000 || " + IS + " | Bir antrepo için hesaplanan götürü teminatın 40.000.000",
yuva=["Aynı hüküm: tütün ve alkol satmayan diğer mağazalar için 2.000.000 TL",
      "Gümrük Yönetmeliği: 1.000 m² veya 2.000 m³'e kadar antrepolar için götürü teminat 3.000.000 TL (komşu rejim)",
      "Aynı madde: birden fazla mağaza ve depo için Genel Müdürlüğe verilen götürü teminat 30.000.000 TL",
      "Gümrük Yönetmeliği: bir antrepo için götürü teminatın dikkate alınan üst sınırı 40.000.000 TL (komşu rejim)"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 7 — Nakil vasıtası sürücü ve hizmetlilerinin alışveriş sınırları (önermeli; I, II, IV doğru)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="ÖNERMELİ",
z="O",
madde=M + " md. 11",
cek="Sürücü ve hizmetliler girişte 1 karton sigara, 1 litrelik içki, 120 ml parfüm alır; çıkışta liste miktarları 3 kat; kara dönüşü ayda 10 defa.",
kok=[Y + " nakil vasıtası sürücü ve hizmetlilerinin mağazalardan yapabilecekleri alışverişe ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Ülkeye girişlerinde, yolcu girişi yapılan hudut kapılarındaki mağazalardan 1 karton sigara ve en fazla 1 litrelik 1 adet alkollü içki satın alabilirler.",
     "II. Ülkeye girişlerinde, en fazla 120 ml'lik 1 adet parfüm ve 1 adet kozmetik ürün ile en fazla 1 kilogram çikolata veya şekerden mamul yiyecek satın alabilirler.",
     "III. Türkiye'den çıkışlarında, yürürlükte bulunan Yolcu Beraberi Kişisel Eşya Listesi'nde yer alan eşyaya ilişkin miktarlar iki kat olarak uygulanır.",
     "IV. Kara hudut kapısından diğer ülkelere çıkış yapanlar, dönüşlerinde alışveriş haklarını kara hudut kapılarında bulunan mağazalarda ayda en fazla 10 defa kullanabilirler.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, II ve IV",
c=["I ve II", "I ve IV", "II, III ve IV", "I, II, III ve IV"],
sirali=False,
g="Yönetmeliğe göre nakil vasıtası sürücü ve hizmetlileri ülkeye girişlerinde, yolcu girişi yapılan hudut kapılarındaki mağazalardan 1 karton sigara, en fazla 1 litrelik 1 adet alkollü içki, en fazla 120 ml'lik 1 adet parfüm ve 1 adet kozmetik ürün ile en fazla 1 kilogram çikolata veya şekerden mamul yiyecek satın alabilir (I ve II doğru). Türkiye'den çıkış yapan yolcular, nakil vasıtası sürücü ve hizmetlileri için Yolcu Beraberi Kişisel Eşya Listesi'ndeki miktarlar iki kat değil 3 kat olarak uygulanır (III yanlış). Kara hudut kapısından diğer ülkelere çıkış yapan nakil vasıtası sürücü ve hizmetlileri, dönüşlerinde alışveriş haklarını kara hudut kapılarındaki mağazalarda ayda en fazla 10 defa kullanabilir (IV doğru). En güçlü çeldiriciler III'ü de doğru sayan seçeneklerdir: III'te yalnızca kat sayısı değiştirilmiştir. Bu nedenle doğru cevap 'I, II ve IV' seçeneğidir. (MD 11)",
kanit=K + " | Nakil vasıtası sürücü ve hizmetlileri ülkeye girişlerinde, yolcu girişi yapılan hudut kapılarındaki mağazalardan 1 karton sigara, en fazla 1 litrelik 1 adet alkollü içki, en fazla 120 ml'lik 1 adet parfüm ve 1 adet kozmetik ürün ile en fazla 1 kilogram çikolata veya şekerden mamul yiyecek satın alabilirler || " + K + " | Yolcu Beraberi Kişisel Eşya Listesi'nde yer alan eşyaya ilişkin miktarlar 3 kat olarak uygulanır || " + K + " | dönüşlerinde alışveriş haklarını kara hudut kapılarında bulunan mağazalarda ayda en fazla 10 defa kullanabilirler",
yuva=["Eksik seçim: IV'teki ayda 10 defa sınırı dışarıda bırakılmış",
      "Eksik seçim: II'deki parfüm, kozmetik ve çikolata sınırları dışarıda bırakılmış",
      "III'ü doğru sayan seçim: aynı hükümde çıkışta liste miktarları 3 kat uygulanır; sayı değiştirilmiş",
      "En kapsamlı şık: III'teki tek sayı değişikliğini görmeyen adayı yakalar"],
yakinlik="BİREBİR",
tuzak=["SAYI", "YAKIN-SAYI"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 8 — Faaliyete geçme süresi ve başlangıcı
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="SÜRE",
z="O",
madde=M + " md. 7, 8",
cek="Açma izni verilenler izin yazısının tebliğini izleyen günden itibaren altı ay içinde faaliyete geçer; geçmezse izin iptal, teminat iade edilir.",
kok=[Y + " mağaza ve depo açma izni verilenlerin faaliyete geçmeleri gereken süre ve bu sürenin başlangıcı aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="İzin yazısının kendilerine tebliğ tarihini izleyen günden itibaren altı ay",
c=["Ön izin başvurusunun uygun bulunduğunun bölge müdürlüğüne bildirildiği tarihten itibaren altı ay",
   "Açma ve işletme izin belgesi harcının peşin olarak tahsil edildiği tarihten itibaren altı ay",
   "İzin yazısının kendilerine tebliğ tarihini izleyen günden itibaren bir yıl",
   "İzin yazısının kendilerine tebliğ tarihini izleyen günden itibaren on iş günü"],
sirali=False,
g="Yönetmeliğe göre mağaza ve depo açma izni verilenlerin, izin yazısının kendilerine tebliğ tarihini izleyen günden itibaren altı ay içinde faaliyete geçmeleri gerekir. Mücbir sebep ve beklenmeyen hâller dışında bu süre içinde faaliyete geçilmemesi hâlinde verilen izin iptal edilir ve alınan teminat iade edilir; bu durumda yeniden başvuru yapılabilir. Süre, ön iznin bildirildiği veya harcın tahsil edildiği tarihten değil, izin yazısının tebliğini izleyen günden başlar; ön izin başvurusunun uygun bulunması mağaza veya depoya açılış izni verileceği anlamına da gelmez. En güçlü çeldirici harcın tahsil tarihini esas alan seçenektir: harç, açma ve işletme izin belgesi düzenlenmeden önce peşin tahsil edilir, ancak faaliyete geçme süresini başlatmaz. Bir yıl ve on iş günü Yönetmelikteki faaliyet durdurma hükümlerinde geçen sürelerdir. Bu nedenle doğru cevap 'İzin yazısının kendilerine tebliğ tarihini izleyen günden itibaren altı ay' seçeneğidir. (MD 7, 8)",
kanit=K + " | Mağaza ve depo açma izni verilenlerin izin yazısının kendilerine tebliğ tarihini izleyen günden itibaren altı ay içinde faaliyete geçmeleri gerekir || " + K + " | bu süre içinde faaliyete geçilmemesi hâlinde verilen izin iptal edilir ve alınan teminat iade edilir || " + K + " | Ön izin başvurusunun uygun bulunması, mağaza veya depoya açılış izni verileceği anlamına gelmez || " + K + " | harcın peşin olarak tahsilini müteakip gümrük müdürlüğünce Ek-3'te yer alan açma ve işletme izin belgesi düzenlenir",
yuva=["Ön izin hükmü: Genel Müdürlük ön iznin verilip verilmediğini bölge müdürlüğüne bildirir; başlangıç anı kaydırılmış",
      "Açma izni hükmü: harç peşin tahsil edildikten sonra açma ve işletme izin belgesi düzenlenir; başlangıç anı kaydırılmış",
      "Geçici durdurma hükmü: usulsüz satışta on gün ilâ bir yıl (sayı havuzu)",
      "Geçici durdurma hükmü: belge ibrazı ve bilgisayar sistemi için on iş günü (sayı havuzu)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "YAKIN-SAYI"],
duzey=["HATIRLAMA"],
profil=[2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 9 — Yıllık sayım, fazlalık ve noksanlık
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="DOĞRU",
z="Z",
madde=M + " md. 30",
cek="Sayımda fazla çıkan eşya kayıtlara alınır; kabul edilebilir neden ispatlanamazsa tasfiye edilir. Kusurlu noksanlıkta vergi tahsil edilip ceza aranmaz.",
kok=[Y + " mağaza ve depolarda yapılan sayımlara ve sayım sonuçlarına ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Sayım sonunda fazla çıkan eşya kayıtlara alınır; fazlalığın kabul edilebilir nedenlerden ileri geldiği ispatlanamazsa eşya tasfiye edilir.",
c=["Mağaza sayımlarında bulunacak heyete yetkilendirilmiş gümrük müşaviri başkanlık eder.",
   "Telef, kayıp veya çalıntıyı tespit edip beyan eden işletmecinin kusuru bulunuyorsa, gümrük vergilerinin tahsiline ek olarak ayrıca para cezası da uygulanır.",
   "Eşyanın kısa sürede sayılamayacak olması hâlinde dahi sayım, eşyanın tamamı tek tek sayılarak yapılır.",
   "İşletmecinin kusurundan kaynaklanmayan telef, kayıp ve çalıntılar, gümrük idaresine tevsik edilmesine gerek olmaksızın kayıtlardan düşülür."],
sirali=False,
g="Yönetmeliğe göre sayım sonunda fazla çıkan eşya kayıtlara alınır; fazlalığın kabul edilebilir nedenlerden ileri geldiği ispatlanamazsa fazla çıkan eşya Kanun hükümleri çerçevesinde tasfiye edilir ve fazla çıkan kısım için ayrıca Kanunun ceza hükmü uygulanır. Mağaza sayımlarında heyete gümrük müdürünce tayin edilecek en az şef seviyesinde bir memur başkanlık eder; yetkilendirilmiş gümrük müşaviri ise depolar, uçakta satış mağazaları ve gemilere satış mağazalarındaki sayımları altışar aylık dönemler itibarıyla yapar. Eşya kısa sürede sayılamayacaksa örnekleme yöntemiyle sayım yapılabilir. Telef, kayıp veya çalıntıyı işletmeci tespit edip beyan etmişse ve kusuru varsa, gümrük vergileri tahsil edilmek kaydıyla eşyanın kayıtlardan düşülmesine izin verilir ve ayrıca ceza aranmaz; işletmecinin kusurundan kaynaklanmayan telef, kayıp ve çalıntıların ise gümrük idaresine tevsiki gerekir. En güçlü çeldirici kusur hâlinde para cezası da uygulanacağını söyleyen seçenektir: hüküm, işletmecinin kendi beyanı üzerine vergilerin tahsil edildiği bu hâlde ceza aramaz. Bu nedenle doğru cevap 'Sayım sonunda fazla çıkan eşya kayıtlara alınır; fazlalığın kabul edilebilir nedenlerden ileri geldiği ispatlanamazsa eşya tasfiye edilir.' seçeneğidir. (MD 30)",
kanit=K + " | Sayım sonunda fazla çıkan eşya kayıtlara alınır. Bu fazlalığın kabul edilebilir nedenlerden ileri geldiği ispatlanamadığı takdirde, fazla çıkan eşya Kanun hükümleri çerçevesinde tasfiye edilir. || " + K + " | Mağaza sayımlarında bulunacak heyete ilgili gümrük müdürü tarafından tayin edilecek en az şef seviyesinde bir memur başkanlık eder. || " + K + " | Eşyanın kısa sürede sayılamayacak olması hâlinde örnekleme yöntemiyle sayım yapılabilir. || " + K + " | gümrük vergileri tahsil edilmek kaydıyla, bu eşyanın kayıtlardan düşülmesine izin verilir ve bu durumda ayrıca ceza aranmaz || " + K + " | Mağaza işletmecilerinin kusurlarından kaynaklanmayan telef, kayıp ve çalıntıların gümrük idaresine tevsiki gerekir.",
yuva=["Sayım hükmü: mağaza sayımında heyete en az şef seviyesinde memur başkanlık eder; müşavir depolar ile uçakta ve gemilere satış mağazalarında sayım yapar (makam değiştirilmiş)",
      "Sayım hükmü: kusur hâlinde vergiler tahsil edilip kayıtlardan düşülür ve ayrıca ceza aranmaz (tersine çevrilmiş)",
      "Sayım hükmü: kısa sürede sayılamayacak eşyada örnekleme yöntemi kullanılabilir (mutlaklaştırılmış)",
      "Sayım hükmü: kusurdan kaynaklanmayan telef, kayıp ve çalıntıların gümrük idaresine tevsiki gerekir (tersine çevrilmiş)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "MAKAM", "MUTLAK"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 10 — Sarf malzemeleri ve numuneler (güncellik: 18.06.2026)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="DOĞRU",
z="O",
madde=M + " md. 14",
cek="Satılan eşyayla bedelsiz verilen azami 10 ml'lik eşantiyon numune sayılmaz, takibat yapılmaz; numune boş şişeleri aylık dönemlerle ibraz edilip imha edilir.",
kok=[Y + " sarf malzemeleri ve numunelere ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Mağazalarda satılan eşya ile birlikte müşterilere bedelsiz olarak verilen azami 10 ml'lik eşantiyonlar numune olarak değerlendirilmez.",
c=["Parfüm ve kozmetik numunelerinin boş şişeleri altışar aylık dönemler itibarıyla gümrük müdürlüğüne ibraz edilir.",
   "Eşyanın tanıtımında kullanılıp alıcıya bedelsiz sunulan eşantiyonlar ile ambalaj malzemelerine, satışa sunulan eşyaya uygulanan işlemler aynen uygulanır.",
   "Boş şişesi ibraz edilemeyen parfüm numuneleri için, eksiklik işletmecinin kusurundan kaynaklanmasa ve bu durum ispat edilse dahi gümrük vergileri tahsil edilir.",
   "Numunelerin boş şişeleri, işletmecinin belirleyeceği dönemlerde tutanak düzenlenmeksizin imha edilir."],
sirali=False,
g="Yönetmeliğe göre mağazalarda satılan eşya ile birlikte müşterilere bedelsiz olarak verilen azami 10 ml'lik eşantiyonlar numune olarak değerlendirilmez ve bunlar için takibat yapılmaz. Bu hüküm, 18.06.2026 tarihli ve 33284 sayılı Resmî Gazete'de yayımlanan düzenlemeyle son hâlini almıştır. Parfüm ve kozmetik numunelerinin boş şişeleri altışar değil birer aylık dönemler itibarıyla, aylık satış listesinin iletilmesi gereken süre içinde gümrük müdürlüğüne ibraz edilir ve gümrük müdürlüğünce belirlenecek dönemlerde, onun gözetiminde tutanak düzenlenerek imha edilir. Boş şişesi ibraz edilemeyen her numune için gümrük vergileri tahsil edilir; ancak işletmecinin kusur ve hatasından ileri gelmeyen ve gümrük müdürlüğüne ispat edilebilen eksiklikler bunun dışındadır. Eşyanın tanıtımında kullanılan bedelsiz eşantiyonlar ile ambalaj malzemelerine, satışa sunulan eşyaya uygulanan işlemler uygulanmaz. En güçlü çeldirici ambalaj ve eşantiyonlara satış eşyasının işlemlerinin uygulanacağını söyleyen seçenektir; hüküm bunun tersini söyler. Bu nedenle doğru cevap 'Mağazalarda satılan eşya ile birlikte müşterilere bedelsiz olarak verilen azami 10 ml'lik eşantiyonlar numune olarak değerlendirilmez.' seçeneğidir. (MD 14)",
kanit=K + " | Mağazalarda satılan eşya ile birlikte müşterilere bedelsiz olarak verilen azami 10 ml'lik eşantiyonlar numune olarak değerlendirilmez ve eşantiyonlar için takibat yapılmaz. (18.06.2026 / 33284 sayılı R.G.) || " + K + " | numunelerin boş şişelerinin birer aylık dönemler itibarıyla || " + K + " | gümrük müdürlüğünce belirlenecek dönemlerde gümrük müdürlüğünün gözetiminde tutanak düzenlenmek suretiyle imha edilmesi gerekir || " + K + " | kusur ve hatalarından ileri gelmeyen kayıp, çalınma ve diğer haller dolayısıyla meydana gelen ve gümrük müdürlüğüne ispat edilebilen eksiklikler hariç olmak üzere || " + K + " | eşyanın konulduğu ambalaj malzemelerine, satışa sunulan eşyaya uygulanan işlemler uygulanmaz",
yuva=["Sayım hükmü: altışar aylık dönem müşavirin depolar ile uçakta ve gemilere satış mağazalarındaki sayım dönemidir; numunede birer aylık",
      "Aynı madde, ilk fıkra: eşantiyon ve ambalaja satış eşyasının işlemleri uygulanmaz (tersine çevrilmiş)",
      "Aynı fıkra: kusurdan ileri gelmeyen ve ispat edilen eksiklikler vergi tahsilinin dışındadır (istisna silinmiş)",
      "Aynı fıkra: imha dönemlerini gümrük müdürlüğü belirler, imha onun gözetiminde tutanakla yapılır (makam ve usul değiştirilmiş)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "İSTİSNA", "KOMŞU"],
duzey=["AYIRT"],
profil=[5],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="18.06.2026",
cikmis="",
kapsamli=False,
),

# 11 — Gemilere satış mağazaları (önermeli; II ve III doğru) — 12/3 güncellik 18.06.2026
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="ÖNERMELİ",
z="Z",
madde=M + " md. 4, 7, 12",
cek="Boğazlarda toplam iki gemilere satış mağazası açılabilir, genel yer şartı aranmaz; Deniz Ticaret Odası kaydı aranır; sorumluluk gemi personeli teslim alana kadar sürer.",
kok=[Y + " gemilere satış mağazalarına ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Gemilere satış mağazası açılabilmesi için mağazanın, gümrük kapıları itibarıyla Türkiye Gümrük Bölgesinden çıkış ve Türkiye Gümrük Bölgesine giriş yerleri içinde yer alması şartı aranır.",
     "II. İstanbul Boğazı'nda bir adet, Çanakkale Boğazı'nda bir adet olmak üzere toplam iki adet gemilere satış mağazası açılmasına izin verilebilir.",
     "III. Gemilere satış mağazası açma izni için başvuranların Deniz Ticaret Odasına kayıtlı olması gerekir.",
     "IV. Gemilere eşya satışında mağaza işletmecisinin sorumluluğu, eşyanın mağazadan çıkışında yetkilendirilmiş gümrük müşavirince tespit işleminin yapılmasıyla sona erer.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve III",
c=["I ve II", "I ve IV", "I, II ve III", "II, III ve IV"],
sirali=False,
g="Yönetmeliğe göre mağaza ve depolar kural olarak gümrük kapıları itibarıyla Türkiye Gümrük Bölgesinden çıkış ve giriş yerleri içinde yer alır; ancak gemilere satış mağazaları açılmasında bu genel yer şartları aranmaz (I yanlış). İstanbul Boğazı'nda bir adet, Çanakkale Boğazı'nda bir adet olmak üzere toplam iki adet gemilere satış mağazası açılmasına izin verilebilir (II doğru). Gemilere satış mağazası açma izni için ayrıca gümrük denetimine tabi gemilere sefer yapacak en az bir deniz hizmet teknesi, mağaza adına VHF cihazı işletme izni ve Deniz Ticaret Odasına kayıt aranır (III doğru). Gemilere eşya satışında mağaza işletmecisinin sorumluluğu, eşyanın geminin yetkili bir personeli (gemi kaptanı veya gemi kâtibi) tarafından teslim alınmasına kadar devam eder; yetkilendirilmiş gümrük müşavirinin mağazadan çıkışta yaptığı tespit sorumluluğu sona erdirmez (IV yanlış). Gemilere satışa ilişkin bu hüküm 18.06.2026 tarihli ve 33284 sayılı Resmî Gazete'de yayımlanan düzenlemeyle son hâlini almıştır. En güçlü çeldirici I'i de doğru sayan 'I, II ve III' seçeneğidir: genel yer şartı mağazalar için doğrudur, fakat aynı hükmün gemilere satış mağazalarına ilişkin cümlesi bu şartı aramaz. Bu nedenle doğru cevap 'II ve III' seçeneğidir. (MD 4, 7, 12)",
kanit=K + " | İstanbul Boğazı'nda bir adet, Çanakkale Boğazı'nda bir adet olmak üzere toplam iki adet gemilere satış mağazası açılmasına izin verilebilir. Gemilere satış mağazaları açılmasında birinci fıkrada belirtilen şartlar aranmaz. || " + K + " | Türkiye Gümrük Bölgesinden çıkış ve Türkiye Gümrük Bölgesine giriş yerleri içinde yer alır || " + K + " | Deniz Ticaret Odasına kayıtlı olunması || " + K + " | Mağaza işletmecisinin sorumluluğu, eşyanın geminin yetkili bir personeli (gemi kaptanı veya gemi kâtibi) tarafından teslim alınmasına kadar devam eder || " + K + " | mağazada görevli yetkilendirilmiş gümrük müşavirince tespit işlemi yapılır",
yuva=["I'i doğru sayıp III'ü atlayan seçim: genel yer şartı mağaza ve depo açılabilecek yerler hükmündedir; gemilere satış mağazasında aranmaz",
      "Yanlış iki ifadeyi birlikte seçen aday: I genel yer şartını, IV müşavirin tespit işlemini sorumluluğun sonu sanır",
      "I'i doğru sayan seçim: aynı hükümdeki gemilere satış mağazaları için 'şartlar aranmaz' istisnası görülmemiş",
      "IV'ü doğru sayan seçim: gemilere satışta müşavir tespiti çıkışta yapılır, sorumluluk gemi kaptanı veya kâtibi teslim alana kadar sürer"],
yakinlik="BİREBİR",
tuzak=["İSTİSNA", "KOMŞU"],
duzey=["AYIRT"],
profil=[1, 5],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="18.06.2026",
cikmis="",
kapsamli=False,
),

# 12 — Meslek yanlılığı: yetkilendirilmiş gümrük müşavirinin yapmadığı işlem
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="KAPSAM_DIŞI",
z="O",
madde=M + " md. 7, 12, 15, 30",
cek="Depodan mağazaya sevkte çıkış tespitini yetkilendirilmiş gümrük müşaviri yapar; eşyaya refakat ise gümrük veya gümrük muhafaza memurunca edilir.",
kok=[Y + " aşağıdaki işlemlerden hangisi yetkilendirilmiş gümrük müşaviri tarafından yapılmaz?"],
d="Eşyanın firmanın deposundan aynı gümrük müdürlüğü denetimi altındaki mağazasına sevkinde eşyaya refakat edilmesi",
c=["Mağaza veya depo açma izni başvurusunda sunulacak tespit raporunun düzenlenmesi",
   "Eşyanın firmanın deposundan aynı gümrük müdürlüğü denetimi altındaki mağazasına sevkinde, depodan çıkışta tespit işleminin yapılması",
   "Yabancı ülkelere sefer yapan uçaklarda satışa sunulacak eşyanın mağazadan çıkışında tespit işleminin yapılması",
   "Depolardaki yıllık sayımların altışar aylık dönemler itibarıyla yapılması"],
sirali=False,
g="Yönetmeliğe göre eşyanın firmanın deposundan aynı gümrük müdürlüğü denetimi altındaki mağazasına sevkinde depodan çıkışta tespit işlemini yetkilendirilmiş gümrük müşaviri yapar; ancak eşya depodan mağazaya, gümrük müdürlüğünün görevlendireceği gümrük veya gümrük muhafaza memurunun refakatinde sevk edilir. Refakat, gümrük müşavirine verilmiş bir görev değildir. Yetkilendirilmiş gümrük müşaviri ayrıca açma başvurusunda sunulan tespit raporunu düzenler, yabancı ülkelere sefer yapan uçaklara teslim edilecek eşyanın mağazadan çıkışında tespit yapar ve depolar, uçakta satış mağazaları ile gemilere satış mağazalarındaki yıllık sayımları altışar aylık dönemler itibarıyla yapar. Soru 'müşavir her işlemde yer alır' önyargısını yoklar. En güçlü çeldirici aynı sevk işlemindeki tespit görevidir: aynı hükümde tespit müşavire, refakat memura verilmiştir. Bu nedenle doğru cevap 'Eşyanın firmanın deposundan aynı gümrük müdürlüğü denetimi altındaki mağazasına sevkinde eşyaya refakat edilmesi' seçeneğidir. (MD 7, 12, 15, 30)",
kanit=K + " | Depodan eşya çıkışında, yetkilendirilmiş gümrük müşaviri tarafından tespit işlemi yapılır. Eşya, depodan mağazaya gümrük müdürlüğünün görevlendireceği gümrük veya gümrük muhafaza memurunun refakatinde sevk edilir. || " + K + " | Yetkilendirilmiş gümrük müşaviri tarafından düzenlenen tespit raporu || " + K + " | Yabancı ülkelere sefer yapan uçaklarda satışa sunulacak olan ve eşyanın cinsini ve miktarını gösteren talep formuna istinaden hazırlanan eşyanın mağazadan çıkışında mağazada görevli yetkilendirilmiş gümrük müşavirince tespit işlemi yapılır || " + K + " | Depolar, uçakta satış mağazaları ve gemilere satış mağazalarındaki yıllık sayımlar ise yetkilendirilmiş gümrük müşaviri tarafından altışar aylık dönemler itibarıyla yapılır",
yuva=["Ön izin ve başvuru belgeleri hükmü: tespit raporunu yetkilendirilmiş gümrük müşaviri düzenler (müşavirin görevi)",
      "Depodan mağazaya sevk hükmü: depodan çıkışta tespiti yetkilendirilmiş gümrük müşaviri yapar (müşavirin görevi)",
      "Uçaklara satış hükmü: mağazadan çıkışta tespiti mağazada görevli yetkilendirilmiş gümrük müşaviri yapar (müşavirin görevi)",
      "Sayım hükmü: depolardaki yıllık sayımları müşavir altışar aylık dönemlerle yapar (müşavirin görevi)"],
yakinlik="PARAFRAZ",
tuzak=["SAĞDUYU", "KOMŞU"],
duzey=["AYIRT"],
profil=[3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 13 — Eşya hareketleri ile usul eşleştirmesi (ayna: aynı/farklı müdürlük)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="EŞLEŞTİRME",
z="Z",
madde=M + " md. 15, 16, 17",
cek="Aynı müdürlükte depodan depoya sevk yeni antrepo beyannamesiyle yapılır; elektronik bildirim yalnız mağaza-mağaza, depo-mağaza, mağaza-depo sevkindedir.",
kok=[Y + " aynı firmaya ait mağaza ve depolar arasındaki eşya hareketleri ile bu hareketlerde izlenecek usul eşleştirmelerinden hangisi yanlıştır?"],
d="Bir depodan aynı gümrük müdürlüğü denetimi altındaki başka bir depoya sevk – Gümrük müdürlüğüne elektronik bildirim",
c=["Bir depodan farklı gümrük müdürlüğü denetimi altındaki bir mağazaya sevk – Transit rejimi hükümleri",
   "Firmanın deposundan aynı gümrük müdürlüğü denetimi altındaki mağazasına sevk – Gümrük müdürlüğüne elektronik bildirim",
   "Firmanın mağazasından aynı gümrük müdürlüğü denetimi altındaki diğer mağazasına sevk – Gümrük müdürlüğüne elektronik bildirim",
   "Firmanın mağazasından farklı gümrük müdürlüğü denetimi altındaki diğer mağazasına sevk – Transit rejimi hükümleri"],
sirali=False,
g="Yönetmeliğe göre eşyanın bir depodan aynı gümrük müdürlüğü denetimi altındaki başka bir depoya sevkinde yeni bir antrepo beyannamesi verilir. Gümrük müdürlüğüne elektronik bildirim yapılarak sevk yalnızca aynı gümrük müdürlüğü denetimindeki mağazadan mağazaya, depodan mağazaya ve mağazadan depoya sevklerde uygulanır; depodan depoya sevk bu sayımda yer almaz. Farklı gümrük müdürlükleri denetimindeki mağaza ve depolar arasındaki sevkler ise transit rejimi hükümleri çerçevesinde yapılır ve eşya varışta antrepo beyannamesiyle alınır. En güçlü çeldirici depodan aynı müdürlükteki mağazaya sevkin elektronik bildirimle yapılmasıdır: bu eşleştirme doğrudur ve aynı usulün depodan depoya sevke de uygulandığı izlenimini verir. Bu nedenle doğru cevap 'Bir depodan aynı gümrük müdürlüğü denetimi altındaki başka bir depoya sevk – Gümrük müdürlüğüne elektronik bildirim' seçeneğidir. (MD 15, 16, 17)",
kanit=K + " | Eşyanın bir depodan aynı gümrük müdürlüğü denetimi altındaki başka bir depoya sevkinde, yeni bir antrepo beyannamesi verilmek suretiyle işlem yapılır. || " + K + " | Aynı gümrük müdürlüğü denetimi altında bulunan mağazadan mağazaya, depodan mağazaya ve mağazadan depoya eşya sevkinde || " + K + " | Eşyanın bir depodan, farklı gümrük müdürlüğü denetimi altındaki bir mağaza veya depoya sevki, Kanun ve Gümrük Yönetmeliğinin transit rejimi hükümleri çerçevesinde gerçekleştirilir || " + K + " | Eşyanın firmanın deposundan aynı gümrük müdürlüğü denetimi altındaki bir mağazasına sevki, 16 ncı madde çerçevesinde gümrük müdürlüğüne elektronik ortamda bildirim yapılması suretiyle gerçekleştirilir || " + K + " | Bir firmanın aynı gümrük müdürlüğü denetimi altında bulunan bir mağazasından diğer mağazasına eşya sevki 16 ncı madde çerçevesinde gümrük müdürlüğüne elektronik bildirim yapılması suretiyle gerçekleştirilir || " + K + " | Bir firmanın mağazasından farklı gümrük müdürlüğü denetimi altında bulunan diğer mağazasına eşya sevki Kanun ve Gümrük Yönetmeliğinin transit rejimi hükümleri çerçevesinde gerçekleştirilir",
yuva=["Depodan farklı müdürlükteki mağaza veya depoya sevk: transit rejimi (doğru eşleştirme)",
      "Depodan aynı müdürlükteki mağazaya sevk: elektronik bildirim (doğru eşleştirme)",
      "Aynı müdürlükte mağazadan mağazaya sevk: elektronik bildirim (doğru eşleştirme)",
      "Farklı müdürlükteki mağazaya sevk: transit rejimi (doğru eşleştirme)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="esya-sevki-ayni-farkli-mudurluk",
guncellik="",
cikmis="",
kapsamli=False,
),

# 14 — Vaka: farklı müdürlükteki mağazaya sevk yalnız depodan (ayna: aynı/farklı müdürlük)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="OLAY",
z="Z",
madde=M + " md. 15, 17",
cek="Mağazasının bulunduğu müdürlükte deposu da olan firma, başka müdürlükteki mağazasına eşyayı sadece deposundan sevk edebilir.",
kok=["(B) Firmasının İzmir'de aynı gümrük müdürlüğünün denetimi altında bir gümrüksüz satış mağazası ve bir deposu, Antalya'da ise başka bir gümrük müdürlüğünün denetimi altında bir gümrüksüz satış mağazası bulunmaktadır. Firma, İzmir'deki mağazasında bulunan bir parti eşyayı Antalya'daki mağazasına göndermek istemektedir.",
     M + "'nin eşya sevkine ilişkin hükümlerine göre bu sevkiyat hakkında aşağıdakilerden hangisi doğrudur?"],
d="Antalya'daki mağazaya eşya sevki yalnızca firmanın İzmir'deki deposundan yapılabilir.",
c=["Eşya, İzmir'deki mağazadan doğrudan transit rejimi hükümleri çerçevesinde sevk edilir ve Antalya'daki mağazaya antrepo beyannamesiyle alınır.",
   "Eşya, İzmir'deki mağazadan gümrük müdürlüğüne yapılan elektronik bildirime istinaden doğrudan sevk edilir.",
   "Eşya, İzmir'deki mağazadan Antalya'daki mağazaya satış suretiyle devredilerek gönderilir.",
   "Firmalar, farklı gümrük müdürlüklerinin denetimindeki kendi mağazaları arasında eşya sevki yapamaz."],
sirali=False,
g="Yönetmeliğe göre bir firmanın mağazasından farklı gümrük müdürlüğü denetimi altındaki diğer mağazasına eşya sevki transit rejimi hükümleri çerçevesinde yapılır ve eşya varışta antrepo beyannamesiyle alınır. Vakada saklanan istisna, firmanın İzmir'de aynı gümrük müdürlüğü denetiminde bir deposunun da bulunmasıdır: mağazanın bulunduğu gümrük müdürlüğü denetimi altında deposu da bulunan firmanın başka bir gümrük müdürlüğü denetimi altındaki mağazasına eşya sevki sadece deposundan yapılır. Bu nedenle eşya İzmir'deki mağazadan doğrudan Antalya'ya gönderilemez; sevk İzmir'deki depodan yapılır. En güçlü çeldirici mağazadan doğrudan transitle sevki öngören seçenektir: genel kuralı doğru verir ama depo bulunması hâlindeki istisnayı atlar. Elektronik bildirim yalnızca aynı gümrük müdürlüğü denetimindeki sevklerde kullanılır; mağazadaki eşyanın satış suretiyle devri ise firmanın aynı gümrük müdürlüğü denetiminde deposu bulunmadığında mümkündür. Bu nedenle doğru cevap 'Antalya'daki mağazaya eşya sevki yalnızca firmanın İzmir'deki deposundan yapılabilir.' seçeneğidir. (MD 15, 17)",
kanit=K + " | Bir firmanın mağazasının bulunduğu gümrük müdürlüğü denetimi altında deposunun da bulunması hâlinde, firmanın başka bir gümrük müdürlüğü denetimi altındaki mağazasına eşya sevki sadece deposundan yapılır. || " + K + " | Bir firmanın mağazasından farklı gümrük müdürlüğü denetimi altında bulunan diğer mağazasına eşya sevki Kanun ve Gümrük Yönetmeliğinin transit rejimi hükümleri çerçevesinde gerçekleştirilir || " + K + " | Bir firmanın aynı gümrük müdürlüğü denetimi altında deposu bulunmaması durumunda, mağazada bulunan eşyanın satış suretiyle devri de mümkündür.",
yuva=["Mağazalar arası sevk hükmünün genel kuralı: farklı müdürlükteki mağazaya transit (istisna görülmemiş)",
      "Mağazalar arası sevk hükmü: elektronik bildirim aynı müdürlük denetimindeki mağazalar arasında uygulanır",
      "Satış suretiyle devir hükmü: mağazadaki eşyanın devri, firmanın aynı müdürlükte deposu bulunmadığında mümkündür",
      "Eşya hareketleri hükmü: firmalar yalnızca kendi mağaza ve depoları arasında sevk yapabilir; yasak olarak okunmuş (mutlaklaştırma)"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[1],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="esya-sevki-ayni-farkli-mudurluk",
guncellik="",
cikmis="",
kapsamli=False,
),

# 15 — Boşluk: aylık satış listesi ve stok cetvelinin iletilme süreleri
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="BOŞLUK",
z="O",
madde=M + " md. 25, 26",
cek="Aylık satış listesi en geç takip eden ayın beşinci günü mesai bitimine, stok cetveli Ocak, Mayıs ve Eylül aylarının ilk on günü içinde iletilir.",
kok=["\"Aylık satış listesi, en geç takip eden ayın ..(I).. günü mesai bitimine kadar; stok cetveli ise ..(II).. aylarının ilk on günü içinde mağaza veya deponun bağlı bulunduğu gümrük müdürlüğüne bilgisayar ortamında iletilir.\"",
     M + "'ne göre yukarıdaki boşluklara sırasıyla aşağıdakilerden hangisi gelmelidir?"],
d="beşinci – Ocak, Mayıs ve Eylül",
c=["onuncu – Ocak, Mayıs ve Eylül",
   "beşinci – Ocak ve Temmuz",
   "beşinci – Ocak, Nisan, Temmuz ve Ekim",
   "onuncu – Ocak ve Temmuz"],
sirali=False,
g="Yönetmeliğe göre aylık satış listesi, her ay satılan eşyaya ilişkin satış belgeleri esas alınarak bilgisayar ortamında düzenlenir ve en geç takip eden ayın beşinci günü mesai bitimine kadar mağazanın bağlı bulunduğu gümrük müdürlüğüne iletilir. Stok cetveli mağaza ve depolarda dörder aylık dönemler itibarıyla düzenlenir ve Ocak, Mayıs ve Eylül aylarının ilk on günü içinde gümrük müdürlüğüne bilgisayar ortamında iletilir. En güçlü çeldirici 'onuncu' günü içeren seçenektir: on gün, aynı cümlede stok cetvelinin iletim süresidir. Ocak ve Temmuz, yetkilendirilmiş gümrük müşavirinin altışar aylık sayım dönemlerini çağrıştırır; dört ayrı ay ise üçer aylık dönem varsayımına dayanır. Bu iki yükümlülüğe aykırılık hâlinde Gümrük Kanunu'nun usulsüzlük cezası hükmü uygulanır. Bu nedenle doğru cevap 'beşinci – Ocak, Mayıs ve Eylül' seçeneğidir. (MD 25, 26, 31)",
kanit=K + " | Liste, en geç takip eden ayın beşinci günü mesai bitimine kadar mağazanın bağlı bulunduğu gümrük müdürlüğüne bilgisayar ortamında iletilir. || " + K + " | Düzenlenen stok cetveli, Ocak, Mayıs ve Eylül aylarının ilk on günü içinde mağaza veya deponun bağlı bulunduğu gümrük müdürlüğüne bilgisayar ortamında iletilir. || " + K + " | Mağaza ve depolarda dörder aylık dönemler itibarıyla dönem başı mevcudunu göstermek için bilgisayar ortamında stok cetveli düzenlenir || " + K + " | yetkilendirilmiş gümrük müşaviri tarafından altışar aylık dönemler itibarıyla yapılır",
yuva=["Aynı cümle: 'ilk on günü' stok cetvelinin iletim süresidir; aylık satış listesine taşınmış",
      "Sayım hükmü: müşavirin altışar aylık sayım dönemleri (Ocak–Temmuz çağrışımı)",
      "Uydurmaya yakın: dörder aylık dönem yerine üçer aylık dönem varsayımı",
      "İki boşlukta da komşu değer: on gün ve altışar aylık dönem"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 16 — Faaliyetin geçici olarak durdurulması (önermeli; I, III ve IV doğru)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="ÖNERMELİ",
z="Z",
madde=M + " md. 28",
cek="Mevzuata aykırılıkta müfettiş veya bölge müdürlüğü on güne kadar, usulsüz satışta Genel Müdürlük on gün–bir yıl durdurur; sistem dışı mağazaya on iş günü verilir.",
kok=[Y + " mağaza ve depoların faaliyetinin geçici olarak durdurulmasına ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Gümrük mevzuatına aykırılıkların tespiti durumunda mağaza veya deponun faaliyeti, inceleme, denetim ve soruşturma yapan ticaret müfettiş veya müfettiş yardımcıları ya da ilgili bölge müdürlüğünce tedbir mahiyetinde on güne kadar geçici olarak durdurulabilir.",
     "II. Usulsüz satış yapıldığının tespiti hâlinde mağazanın faaliyeti, usulsüzlük ve ihlalin ağırlığı ile tekerrür durumuna göre ilgili bölge müdürlüğünce on gün ilâ bir yıl arasında geçici olarak durdurulur.",
     "III. Tedbir mahiyetindeki durdurma süresinin uzatılması yönünde Genel Müdürlükçe karar verilmediği takdirde, gümrük müdürlüğü sürenin bitimini izleyen gün mağaza veya deponun faaliyetinin devamına izin verir.",
     "IV. Bakanlıkça uygulamaya konulan bilgisayar sistemi dışına çıkan mağazaya, sisteme dâhil olunması ve varsa eksik verilerin sisteme işlenmesi için gümrük müdürlüğünce on iş günü süre verilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, III ve IV",
c=["I ve II", "I ve IV", "II ve III", "I, II, III ve IV"],
sirali=False,
g="Yönetmeliğe göre gümrük mevzuatına aykırılıkların veya mağaza ya da deponun faaliyet alanları dışında kullanıldığının tespiti hâlinde faaliyet, inceleme, denetim ve soruşturma yapan ticaret müfettiş veya müfettiş yardımcıları ya da ilgili bölge müdürlüğünce tedbir mahiyetinde on güne kadar durdurulabilir (I doğru). Genel Müdürlük bu süreyi aykırılıklar giderilinceye kadar uzatabilir; uzatma kararı verilmezse gümrük müdürlüğü sürenin bitimini izleyen gün faaliyetin devamına izin verir (III doğru). Usulsüz satış tespitinde ise faaliyeti on gün ilâ bir yıl arasında durduran makam bölge müdürlüğü değil Genel Müdürlüktür (II yanlış). Bilgisayar sistemi dışına çıkan mağazaya gümrük müdürlüğünce on iş günü süre verilir; mücbir sebep ve beklenmeyen hâller dışında süre sonunda sisteme dâhil olmayan mağazanın faaliyeti gümrük müdürlüğünce durdurulur (IV doğru). En güçlü çeldirici II'yi de doğru sayan en kapsamlı seçenektir: II'de yalnızca makam değiştirilmiştir. Bu nedenle doğru cevap 'I, III ve IV' seçeneğidir. (MD 28)",
kanit=K + " | inceleme, denetim ve soruşturma yapan ticaret müfettiş veya müfettiş yardımcıları ya da ilgili bölge müdürlüğünce tedbir mahiyetinde on güne kadar geçici olarak durdurulabilir || " + K + " | Usulsüz satış yapıldığının tespiti hâlinde mağazanın faaliyeti, usulsüzlük ve ihlalin ağırlığı ve tekerrür durumuna göre Genel Müdürlükçe on gün ilâ bir yıl arasında geçici olarak durdurulur || " + K + " | Genel Müdürlükçe bu sürenin uzatılması yönünde karar verilmediği takdirde gümrük müdürlüğü sürenin bitimini izleyen gün mağaza veya deponun faaliyetinin devamına izin verir || " + K + " | sisteme dâhil olunması ve varsa eksik verilerin sisteme işlenmesi için gümrük müdürlüğünce on iş günü süre verilir",
yuva=["II'yi doğru sayan, III'ü atlayan seçim: usulsüz satışta durdurma makamı Genel Müdürlüktür",
      "Eksik seçim: III'teki 'sürenin bitimini izleyen gün' kuralı dışarıda bırakılmış",
      "II'yi doğru sayan seçim: bölge müdürlüğü tedbir mahiyetindeki on günlük durdurmanın makamıdır, usulsüz satışın değil",
      "En kapsamlı şık: II'deki makam değişikliğini görmeyen adayı yakalar"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 17 — Vaka: beş yıllık yeni izin yasağının kapsamı
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="MÜEYYİDE",
z="Z",
madde=M + " md. 7, 18, 29",
cek="Beş yıl yeni izin yasağı yalnız kaçakçılık mahkûmiyeti ve bilgisayar sisteminde değişiklik iptallerinde uygulanır; satış yokluğu iptalinde uygulanmaz.",
kok=["(C) Limited Şirketinin bir kara hudut kapısındaki gümrüksüz satış mağazasında bir önceki takvim yılında hiç satış yapılmadığı anlaşılmış; mağazanın açma ve işletme izni, hudut kapısının ileriye dönük potansiyeli ve mevcut kira sözleşmesi hükümleri de dikkate alınarak Genel Müdürlükçe iptal edilmiştir. Şirket, iptalden dört ay sonra başka bir hudut kapısında mağaza açma izni almak üzere başvuruda bulunmuştur.",
     Y + " şirketin yeni başvurusu hakkında aşağıdakilerden hangisi doğrudur?"],
d="İptalin nedeni satış bulunmaması olduğundan şirkete beş yıl süreyle yeni izin verilmemesi yasağı uygulanmaz.",
c=["Açma ve işletme izni iptal edilen şirkete beş yıl süre ile yeni mağaza ve depo açma ve işletme izni verilmez.",
   "Şirketin yeni başvurusu, iptal tarihinden itibaren bir yıl geçmedikçe değerlendirilemez.",
   "Şirketin yeni başvurusunda ön izin başvurusu yapılmaz.",
   "Şirketin yeni başvurusunda asgari iki yıl faaliyette bulunma ve kurumlar vergisi şartları aranmaz."],
sirali=False,
g="Yönetmeliğe göre bir önceki takvim yılında satışı bulunmadığı anlaşılan mağazaların açma ve işletme izinleri Genel Müdürlükçe iptal edilebilir. Beş yıl süreyle yeni mağaza ve depo açma ve işletme izni verilmemesi ise yalnızca iki iptal hâline bağlanmıştır: firma ortakları veya yönetim kurulu üyelerinden biri hakkında kaçakçılık suçlarından verilen mahkûmiyetin kesinleşmesi ve satışların takibini sağlayan bilgisayar sisteminde usulsüz satışa imkân verecek değişiklik yapılması. Vakada saklanan istisna iptalin nedenidir: iptal satış bulunmamasına dayandığından beş yıllık yasak uygulanmaz ve şirketin yeni başvurusu genel hükümlere göre değerlendirilir. En güçlü çeldirici beş yıllık yasağı her iptale uygulayan seçenektir. Ön izin başvurusunun yapılmaması yalnızca devir başvurularına; faaliyet süresi ve kurumlar vergisi şartlarının aranmaması ise sermaye ve ihtiyatları en az 50.000.000 TL olan şirketlere ve belirli devir hâllerine özgüdür. Bu nedenle doğru cevap 'İptalin nedeni satış bulunmaması olduğundan şirkete beş yıl süreyle yeni izin verilmemesi yasağı uygulanmaz.' seçeneğidir. (MD 7, 18, 29)",
kanit=K + " | bir önceki takvim yılında satışı bulunmadığı anlaşılan mağazaların açma ve işletme izinleri || " + K + " | Mağaza ve depo açma ve işletme izinleri üçüncü ve dördüncü fıkralar uyarınca iptal edilen firma ve ortaklarına, 6 ncı madde hükümleri saklı kalmak kaydıyla, beş yıl süre ile yeni mağaza ve depo açma ve işletme izni verilmez. || " + K + " | Devir başvurularında ön izin başvurusu yapılmaz. || " + K + " | 2 yıl faaliyette bulunma ve kurumlar vergisi şartları aranmaz",
yuva=["İptal hükmü: beş yıllık yasak yalnızca mahkûmiyet ve bilgisayar sistemi değişikliği iptallerine bağlanmıştır (genelleştirilmiş)",
      "Geçici durdurma hükmü: usulsüz satışta on gün ilâ bir yıl (sayı havuzu)",
      "Mağazaların devri hükmü: ön izin başvurusu yalnızca devir başvurularında yapılmaz",
      "Başvurabilecekler hükmü: faaliyet süresi ve kurumlar vergisi şartları sermayesi en az 50.000.000 TL olan şirketlerde aranmaz"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[3],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 18 — Harç alınmayan işlem
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="TABİ",
z="O",
madde=M + " md. 7, 9",
cek="Genişletme, daraltma, tamirat, tadilat ve adres değişikliğinden harç alınmaz; izin belgesinin düzenlenmesi, yenilenmesi, devri ve yeniden düzenlenmesi harca tabidir.",
kok=[Y + " aşağıdaki işlemlerden hangisinde 492 sayılı Harçlar Kanunu uyarınca harç alınmaz?"],
d="Mağazanın genişletilmesi",
c=["Başvurusu uygun bulunan mağaza için açma ve işletme izin belgesinin düzenlenmesi",
   "Açma ve işletme izin belgesinin yenilenmesi",
   "Açma ve işletme izin belgesinin devir suretiyle başkasına intikali",
   "Herhangi bir sebeple iptal edilen açma ve işletme izin belgesinin yeniden düzenlenmesi"],
sirali=False,
g="Yönetmeliğe göre mağaza ve depolarda yapılacak genişletme, daraltma, tamirat veya tadilat işlemleri ile adres değişiklikleri gümrük müdürlüklerince sonuçlandırılır ve bu işlemlerden harç alınmaz; unvan değişikliği ile gümrük idaresi değişikliğinde de harç aranmaksızın yalnızca mevcut açma ve işletme izin belgesi üzerinde düzeltme yapılır. Buna karşılık açma ve işletme izin belgesinin ilk düzenlenmesinde harç peşin tahsil edilir; belgenin yenilenmesi, devir suretiyle başkasına intikali veya herhangi bir sebeple iptal edildikten sonra yeniden düzenlenmesi durumlarında da 492 sayılı Harçlar Kanunu uyarınca harç alınır. En güçlü çeldirici devir suretiyle intikaldir: unvan değişikliği harçsızdır, ancak belgenin başkasına devri harca tabidir. Bu nedenle doğru cevap 'Mağazanın genişletilmesi' seçeneğidir. (MD 7, 9)",
kanit=K + " | Mağaza ve depolarda yapılacak genişletme, daraltma, tamirat veya tadilat işlemleri ile adres değişiklikleri gümrük müdürlüklerince sonuçlandırılır ve bu işlemlerden harç alınmaz. || " + K + " | Açma ve işletme izin belgesinin yenilenmesi, devir suretiyle başkasına intikali veya herhangi bir sebeple iptal edildikten sonra yeniden düzenlenmesi durumlarında 492 sayılı Harçlar Kanunu uyarınca harç alınır. || " + K + " | harcın peşin olarak tahsilini müteakip gümrük müdürlüğünce Ek-3'te yer alan açma ve işletme izin belgesi düzenlenir",
yuva=["Açma izni hükmü: izin belgesi, harcın peşin tahsilinden sonra düzenlenir (harca tabi)",
      "Yıllık kontroller hükmü: izin belgesinin yenilenmesinde harç alınır",
      "Yıllık kontroller hükmü: izin belgesinin devir suretiyle intikalinde harç alınır (unvan değişikliğinin harçsız olmasıyla karıştırılır)",
      "Yıllık kontroller hükmü: iptal sonrası yeniden düzenlemede harç alınır"],
yakinlik="PARAFRAZ",
tuzak=["TERSİNE", "KOMŞU"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 19 — Satış usulleri (tek unsur değişikliği: kara kapısı dil üçlüsü)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="YANLIŞ",
z="O",
madde=M + " md. 11, 12",
cek="Uyarıcı tabelalar kara kapılarında Türkçe, İngilizce ve komşu ülke dilinde; hava ve deniz kapılarında Türkçe, İngilizce ve Arapça hazırlanır.",
kok=[Y + " mağazalardan yapılacak satışlara ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Kara hudut kapılarındaki mağazalarda uyarıcı ve bilgilendirici tabelaların Türkçe, İngilizce ve Arapça olarak hazırlanması zorunludur.",
c=["Türkiye'ye girişte mağazalardan satın alınacak eşyanın pasaport işlemleri tamamlandıktan sonra ve gümrük muayenesinden geçmeden önce alınması şarttır; Tek Durak uygulamasının faaliyette olduğu kara gümrük kapılarındaki mağazalar için bu şart aranmaz.",
   "Mağazadan eşya satışı, Türk Lirası veya konvertibl yabancı para cinsinden her türlü ödeme aracıyla yapılır.",
   "Vekâlet ve pasaport ibraz edilse dahi yolcu dışındaki bir kişiye satış yapılamaz.",
   "Mağazalarda esas itibarıyla serbest dolaşıma girmemiş eşya satılır; serbest dolaşımda olan eşyanın satılmasına Genel Müdürlükçe izin verilebilir."],
sirali=False,
g="Yönetmeliğe göre uyarıcı ve bilgilendirici tabelalar kara hudut kapılarında Türkçe, İngilizce ve komşu ülkenin dilinde; hava ve deniz hudut kapılarındaki mağazalarda ise Türkçe, İngilizce ve Arapça olarak hazırlanır; ayrıca alışveriş yapan yolculara uygun diğer diller de kullanılabilir. Yanlış ifade hava ve deniz kapılarına ait dil üçlüsünü kara kapılarına taşımıştır. Türkiye'ye girişte eşyanın pasaport işlemleri tamamlandıktan sonra ve gümrük muayenesinden geçmeden önce alınması şarttır; Tek Durak uygulamasının faaliyette olduğu kara gümrük kapılarındaki mağazalar için bu şart aranmaz. Satış Türk Lirası veya konvertibl yabancı para cinsinden her türlü ödeme aracıyla yapılır. Mağazalarda esas itibarıyla serbest dolaşıma girmemiş eşya satılır; serbest dolaşımdaki eşyanın satışına Genel Müdürlükçe izin verilebilir. En güçlü çeldirici vekâlet ve pasaport ibrazına rağmen satış yasağını öngören ifadedir: katı görünse de hükmün lafzıdır, satış bizzat yolcunun kendisine yapılır. Bu nedenle doğru cevap 'Kara hudut kapılarındaki mağazalarda uyarıcı ve bilgilendirici tabelaların Türkçe, İngilizce ve Arapça olarak hazırlanması zorunludur.' seçeneğidir. (MD 11, 12)",
kanit=K + " | kara hudut kapılarında Türkçe, İngilizce ve komşu ülkenin dilinde, hava ve deniz hudut kapılarındaki mağazalarda ise Türkçe, İngilizce ve Arapça olarak hazırlanması zorunlu || " + K + " | satın alınacak eşyanın pasaport işlemleri tamamlandıktan sonra ve girişte gümrük muayenesinden geçmeden önce alınması şarttır || " + K + " | Tek Durak uygulamasının faaliyette olduğu kara gümrük kapılarında bulunan gümrüksüz satış mağazaları için bu şart aranmaz. || " + K + " | Mağazadan eşya satışı, Türk Lirası veya konvertibl yabancı para cinsinden her türlü ödeme aracıyla yapılır. || " + K + " | Vekâlet ve pasaport ibraz edilse dahi yolcu dışındaki bir kişiye satış yapılamaz. || " + K + " | Mağazalarda esas itibarıyla serbest dolaşıma girmemiş eşya satılır. Serbest dolaşımda olan eşyanın mağazalarda satılmasına Genel Müdürlükçe izin verilebilir.",
yuva=["Satılabilecek eşya hükmü: girişte pasaport işlemlerinden sonra ve muayeneden önce alım şartı (doğru ifade)",
      "Eşyanın satışı hükmü: TL veya konvertibl döviz ile her türlü ödeme aracı (doğru ifade)",
      "Eşyanın satışı hükmü: vekâlet ve pasaport ibrazına rağmen yolcu dışındakine satış yasağı (doğru ifade)",
      "Satılabilecek eşya hükmü: serbest dolaşıma girmemiş eşya esastır, serbest dolaşımdakine Genel Müdürlük izni (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 20 — Usulsüzlük cezası uygulanacağı ayrıca sayılan yükümlülükler (liste dışı)
dict(
konu="Gümrüksüz Satış Mağazaları", blok="SB29",
kalip="KAPSAM_DIŞI",
z="Z",
madde=M + " md. 12, 31",
cek="Adlî sicil, uyarıcı tabela, uçak listeleri, defter, aylık satış listesi ve stok cetveli aykırılığında usulsüzlük cezası sayılmıştır; döviz kuru tabelası sayılmamıştır.",
kok=[M + "'nde, aykırı hareket edilmesi hâlinde 4458 sayılı Gümrük Kanunu'nun usulsüzlük cezasına ilişkin hükmünün uygulanacağı ayrıca belirtilen yükümlülükler arasında aşağıdakilerden hangisi yer almaz?"],
d="Döviz kurlarına ilişkin bilgilendirme tabelalarının mağaza içerisine asılması",
c=["Adlî sicil belgelerinin her yıl Ocak ayı sonuna kadar ilgili gümrük müdürlüğüne ibraz edilmesi",
   "Uyarıcı ve bilgilendirici tabelaların mağaza içinde alıcılarca kolaylıkla görülebilecek yerlere asılması",
   "Antrepo giriş-çıkış defterine kayıtların giriş veya çıkış işlemini takip eden beş iş günü içinde yapılması",
   "Aylık satış listesinin satış belgeleri esas alınarak düzenlenip süresi içinde gümrük müdürlüğüne iletilmesi"],
sirali=False,
g="Yönetmeliğe göre gümrük mevzuatındaki antrepo rejimine ilişkin usulsüzlük cezaları gümrüksüz satış mağazaları ve depoları için de uygulanır. Bunun yanında Yönetmelik, aykırı hareket edilmesi hâlinde Gümrük Kanunu'nun usulsüzlük cezası hükmünün uygulanacağı yükümlülükleri ayrıca sayar: adlî sicil belgelerinin her yıl Ocak ayı sonuna kadar ibrazı, uyarıcı ve bilgilendirici tabelaların asılması, uçakta satışa ilişkin teslim, iade ve satış listelerinin düzenlenmesi, antrepo giriş-çıkış defterine kayıtların beş iş günü içinde yapılması, aylık satış listesinin ve stok cetvelinin süresi içinde iletilmesi. Döviz kurlarına ilişkin bilgilendirme tabelasını asmak da zorunludur; ancak bu yükümlülük sayılan hükümler arasında yer almaz. En güçlü çeldirici uyarıcı ve bilgilendirici tabelalardır: mağazadaki iki tabela yükümlülüğünden yalnızca bu tabelalar sayılmıştır. Bu nedenle doğru cevap 'Döviz kurlarına ilişkin bilgilendirme tabelalarının mağaza içerisine asılması' seçeneğidir. (MD 12, 31)",
kanit=K + " | 9 uncu maddesinin birinci, 11 inci maddesinin on ikinci, 12 nci maddesinin dördüncü, 22 nci maddesinin üçüncü, 25 inci maddesinin üçüncü ve 26 ncı maddesinin dördüncü fıkrası hükümlerine aykırı hareket edilmesi hâlinde Kanunun 241 inci maddesinin birinci fıkrası uygulanır || " + K + " | döviz kurlarına ilişkin bilgilendirme tabelalarının yolcular tarafından görülebilecek şekilde mağaza içerisine asılması zorunludur || " + K + " | adlî sicil belgelerinin her yıl Ocak ayı sonuna kadar ilgili gümrük müdürlüğüne ibraz edilmesi gerekir || " + K + " | mağaza içerisinde alıcılar tarafından kolaylıkla görülebilecek yerlere asılması gerekir || " + K + " | Deftere kayıtların giriş veya çıkış işlemini takip eden beş iş günü içinde yapılması zorunludur.",
yuva=["Yıllık kontroller hükmü: adlî sicil belgelerinin Ocak ayı sonuna kadar ibrazı (sayılmış)",
      "Satılabilecek eşya hükmü: uyarıcı ve bilgilendirici tabelalar (sayılmış; döviz tabelasıyla karıştırılır)",
      "Antrepo giriş-çıkış defteri hükmü: kayıtların beş iş günü içinde yapılması (sayılmış)",
      "Aylık satış listesi hükmü: listenin süresi içinde iletilmesi (sayılmış)"],
yakinlik="PARAFRAZ",
tuzak=["LİSTE-DIŞI", "KOMŞU"],
duzey=["AYIRT"],
profil=[3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

]
