# Soru Bankası — Bölüm 31: Dahilde İşleme Rejimi (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
F = "32-DAHİLDE İŞLEME.txt"
Q = [

# 1 — GK 108/2: geri ödeme sistemi (addan tanım) — ayna A (eksen 2)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="TANIM",
z="K",
madde="4458 sayılı Gümrük Kanunu md. 108",
cek="Geri ödeme sistemi: serbest dolaşıma girişte tahsil edilen ithalat vergilerinin, işlem görmüş ürünlerin ihracında dahilde işleme kapsamında geri verilmesidir.",
kok=["4458 sayılı Gümrük Kanunu'na göre dahilde işleme rejiminde \"geri ödeme sistemi\" aşağıdakilerden hangisini ifade eder?"],
d="Serbest dolaşımda bulunan eşyanın işlem görmüş ürünlerin üretiminde kullanılmasından sonra ihraç edilmesi hâlinde, serbest dolaşıma girişi esnasında tahsil edilmiş olan ithalat vergilerinin geri verilmesi",
c=["Serbest dolaşımda olmayan eşyanın, gümrük vergileri ve ticaret politikası önlemlerine tabi tutulmaksızın ve vergileri teminata bağlanmak suretiyle geçici olarak ithal edilmesi ve işlem görmüş ürünler şeklinde ihracı hâlinde teminatın iade olunması",
   "İthal eşyasının rejime tabi tutulmadan önce eşdeğer eşyadan üretilen işlem görmüş ürünlerin ihracına ve ithal eşyasının sonradan ithaline imkân veren uygulama",
   "İşlem görmüş ürünün ihracından önce bu ürünün elde edilmesinde kullanılacak eşyanın ithal edilmesi",
   "İkame ürün olarak adlandırılan ithal eşyasının bir işlem görmüş ürün ile değiştirilmesine imkân veren uygulama"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre dahilde işleme rejiminden iki sistemle yararlanılır. Serbest dolaşımda bulunan eşya işlem görmüş ürünlerin üretiminde kullanıldıktan sonra Türkiye Gümrük Bölgesinden ihraç edilirse, bu eşyanın serbest dolaşıma girişi sırasında tahsil edilmiş ithalat vergileri dahilde işleme rejimi kapsamında geri verilir; Kanun bu yararlanma biçimine geri ödeme sistemi adını verir. En güçlü çeldirici şartlı muafiyet sisteminin tanımıdır: orada serbest dolaşımda olmayan eşyanın vergileri tahsil edilmez, teminata bağlanır ve işlem görmüş ürün ihraç edilince teminat iade olunur. Eşdeğer eşyadan üretilen ürünün ithalattan önce ihracı önceden ihracat, ürünün ihracından önce eşyanın ithali önceden ithalat uygulamasıdır; ikame ürünün işlem görmüş ürünle değiştirilmesi ise hariçte işleme rejimindeki standart değişim sistemine aittir. Bu nedenle doğru cevap 'Serbest dolaşımda bulunan eşyanın işlem görmüş ürünlerin üretiminde kullanılmasından sonra ihraç edilmesi hâlinde, serbest dolaşıma girişi esnasında tahsil edilmiş olan ithalat vergilerinin geri verilmesi' seçeneğidir. (MD GK 108)",
kanit=F + " | Serbest dolaşımda bulunan eşyanın işlem görmüş ürünlerin üretiminde kullanılmasından sonra Türkiye Gümrük Bölgesinden ihraç edilmesi halinde, bu eşyanın serbest dolaşıma girişi esnasında tahsil edilmiş olan ithalat vergileri, dahilde işleme rejimi kapsamında geri verilir || " + F + " | Eşyanın bu şekilde dahilde işleme rejiminden yararlanmasına geri ödeme sistemi denir || " + F + " | vergileri teminata bağlanmak suretiyle, dahilde işleme rejimi kapsamında geçici olarak ithal edilebilir. Eşyanın işlem görmüş ürünler şeklinde ihracı halinde, teminat iade olunur",
yuva=["GK 108/1: şartlı muafiyet sistemi (vergiler teminata bağlanır, ihraçta teminat iade olunur)",
      "GY 349/2-b: önceden ihracat tanımı",
      "DİR Tebliği 3/cc: önceden ithalat tanımı",
      "GK 144/1 (Hariçte işleme): standart değişim sistemi, ikame ürün"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["TANIMA"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=2, ayna="SB31-A: geri ödeme tanımı ↔ şartlı muafiyet/geri ödeme kuralları",
guncellik="",
cikmis="2021/21; 2023/99; 2025/62",
kapsamli=False,
),

# 2 — GK 108/3-8: kavram–tanım eşleştirmesi
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="EŞLEŞTİRME",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 108",
cek="Asıl işlem görmüş ürün, rejim kapsamında elde edilmesi amaçlanan üründür; işleme faaliyetleri sonucunda elde edilen tüm ürünler işlem görmüş üründür.",
kok=["4458 sayılı Gümrük Kanunu'nda dahilde işleme rejimine ilişkin olarak yapılan aşağıdaki kavram–tanım eşleştirmelerinden hangisi yanlıştır?"],
d="Asıl işlem görmüş ürün – İşleme faaliyetleri sonucunda elde edilen tüm ürünler",
c=["İkincil işlem görmüş ürün – İşleme faaliyetleri sonucunda elde edilen asıl işlem görmüş ürün dışındaki ürünler",
   "Eşdeğer eşya – İşlem görmüş ürünlerin imali için ithal eşyasının yerine kullanılan serbest dolaşımda bulunan eşya",
   "Verimlilik oranı – Belirli miktardaki ithal eşyasının işlenmesi sonucunda elde edilen işlem görmüş ürünlerin miktarı veya yüzde oranı",
   "İşleme faaliyetleri – Eşyanın montajı, kurulması ve diğer eşya ile birleştirilmesi dahil olmak üzere işçiliğe tabi tutulmasını da kapsayan faaliyetler"],
sirali=False,
g="4458 sayılı Gümrük Kanunu, dahilde işleme rejimine ilişkin kavramları ayrı ayrı tanımlar. İşleme faaliyetleri sonucunda elde edilen tüm ürünler 'işlem görmüş ürün'dür. 'Asıl işlem görmüş ürün' ise bunlardan yalnızca dahilde işleme rejimi kapsamında elde edilmesi amaçlanan üründür; bu nedenle asıl işlem görmüş ürünü 'tüm ürünler' diye tanımlayan eşleştirme yanlıştır. Asıl ürün dışındaki ürünler ikincil işlem görmüş üründür. İthal eşyasının yerine kullanılan serbest dolaşımda bulunan eşya eşdeğer eşyadır. Belirli miktardaki ithal eşyasının işlenmesiyle elde edilen ürün miktarı veya yüzde oranı verimlilik oranıdır. Montaj, kurma ve diğer eşya ile birleştirme dahil işçilik de işleme faaliyetlerindendir. Bu dört eşleştirme Kanundaki tanımlarla örtüşür. En güçlü tuzak, 'işlem görmüş ürün' tanımının 'asıl' ürüne taşınmasıdır. Bu nedenle doğru cevap 'Asıl işlem görmüş ürün – İşleme faaliyetleri sonucunda elde edilen tüm ürünler' seçeneğidir. (MD GK 108)",
kanit=F + " | \"İşlem görmüş ürün\" deyimi, işleme faaliyetleri sonucunda elde edilen tüm ürünler anlamına gelir || " + F + " | \"Asıl işlem görmüş ürün\" deyimi, dahilde işleme rejimi kapsamında elde edilmesi amaçlanan ürün anlamına gelir || " + F + " | \"İkincil işlem görmüş ürün\" deyimi, işleme faaliyetleri sonucunda elde edilen asıl işlem görmüş ürün dışındaki ürünler anlamına gelir || " + F + " | \"Eşdeğer eşya\" deyimi, işlem görmüş ürünlerin imali için ithal eşyasının yerine kullanılan serbest dolaşımda bulunan eşya anlamına gelir || " + F + " | \"Verimlilik oranı\" deyimi, belirli miktardaki ithal eşyasının işlenmesi sonucunda elde edilen işlem görmüş ürünlerin miktarı veya yüzde oranı anlamına gelir || " + F + " | Eşyanın montajı, kurulması ve diğer eşya ile birleştirilmesi dahil olmak üzere işçiliğe tabi tutulması",
yuva=["GK 108/6: ikincil işlem görmüş ürün tanımı (doğru eşleştirme)",
      "GK 108/7: eşdeğer eşya tanımı (doğru eşleştirme)",
      "GK 108/8: verimlilik oranı tanımı (doğru eşleştirme)",
      "GK 108/3-a: işleme faaliyetleri (doğru eşleştirme)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["TANIMA"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2023/55; 2025/63",
kapsamli=False,
),

# 3 — Tebliğ 5, 11: şartlı muafiyet ↔ geri ödeme — ayna A (eksen 2)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="YANLIŞ",
z="O",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 5, 11",
cek="Şartlı muafiyette eşya ticaret politikası önlemlerine tabi tutulmadan, vergisi teminata bağlanarak ithal edilir; geri ödeme sisteminde ticaret politikası önlemleri uygulanır.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre şartlı muafiyet sistemi ve geri ödeme sistemine ilişkin aşağıdaki ifadelerden hangisi yanlıştır?"],
d="Geri ödeme sistemi kapsamında ithal edilen eşya için ticaret politikası önlemleri uygulanmaz.",
c=["Şartlı muafiyet sisteminde serbest dolaşımda bulunmayan eşya, ticaret politikası önlemlerine tabi tutulmaksızın, vergisi teminata bağlanmak suretiyle ithal edilir ve ihracat taahhüdünün gerçekleşmesini müteakip teminat iade edilir.",
   "Şartlı muafiyet sisteminde belge/izin kapsamında yapılacak işletme malzemesi ithalatında katma değer vergisi ve özel tüketim vergisi tahsil edilir ve ticaret politikası önlemleri uygulanır.",
   "Geri ödeme sisteminde ithalat esnasında alınan vergi, işlem görmüş ürünün ihracı hâlinde, işletme malzemesine ilişkin katma değer vergisi ve özel tüketim vergisi hariç olmak üzere geri ödenir.",
   "Geri ödeme sisteminden yararlanmak için eşyanın bu sistem kapsamında olduğunun ithalat esnasında gümrük idaresince gümrük beyannamesine kaydedilmesi zorunludur."],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği'ne göre şartlı muafiyet sisteminde serbest dolaşımda bulunmayan eşya ticaret politikası önlemlerine tabi tutulmaksızın, vergisi teminata bağlanarak ithal edilir ve ihracat taahhüdü gerçekleşince teminat iade edilir; yalnızca işletme malzemesi ithalatında katma değer vergisi ve özel tüketim vergisi tahsil edilir ve ticaret politikası önlemleri uygulanır. Geri ödeme sisteminde ise vergi ithalatta alınır ve işlem görmüş ürün ihraç edilince, işletme malzemesine ilişkin katma değer vergisi ve özel tüketim vergisi hariç, geri ödenir. Bu sistemde ithal edilen eşya için gümrük idaresince ticaret politikası önlemleri uygulanır; dış ticarette teknik düzenlemeler ve standardizasyon mevzuatı dahil diğer işlemlerin tamamlanması da aranır. Yanlış ifade, şartlı muafiyet sistemine ait 'ticaret politikası önlemlerine tabi tutulmaksızın' kuralını geri ödeme sistemine taşımaktadır. Geri ödeme sisteminden yararlanmak için eşyanın bu sistem kapsamında olduğunun ithalatta beyannameye kaydedilmesi ise gerçekten zorunludur. Bu nedenle doğru cevap 'Geri ödeme sistemi kapsamında ithal edilen eşya için ticaret politikası önlemleri uygulanmaz.' seçeneğidir. (MD Tebliğ 5, 11)",
kanit=F + " | Türkiye Gümrük Bölgesinde (serbest bölgeler hariç) yerleşik firmalarca, ticaret politikası önlemlerine tabi tutulmaksızın, vergisi teminata bağlanmak suretiyle bedelli ve/veya bedelsiz ithal edilmesi ve ihracat taahhüdünün gerçekleşmesini müteakip, alınan teminatın iade edilmesidir || " + F + " | belge/izin kapsamında yapılacak işletme malzemesi ithalatında, katma değer vergisi ve özel tüketim vergisi tahsil edilir ve ticaret politikası önlemleri uygulanır || " + F + " | ithalat esnasında alınan verginin (işletme malzemesine ilişkin katma değer vergisi ve özel tüketim vergisi hariç) geri ödenmesidir. Bu kapsamda ithal edilen eşya için gümrük idaresince, ticaret politikası önlemleri uygulanır || " + F + " | eşyanın geri ödeme sistemi kapsamında olduğunun gümrük idaresince ithalat esnasında belgeye/izne ilişkin gümrük beyannamesine kaydedilmesi zorunludur",
yuva=["Tebliğ 5/1: şartlı muafiyetin kapsamı (doğru ifade)",
      "Tebliğ 5/2: işletme malzemesinde KDV-ÖTV tahsili ve TPÖ (doğru ifade)",
      "Tebliğ 11/1 birinci cümle: geri ödemenin kapsamı (doğru ifade)",
      "Tebliğ 11/4: beyannameye kayıt zorunluluğu (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=2, ayna="SB31-A: geri ödeme tanımı ↔ şartlı muafiyet/geri ödeme kuralları",
guncellik="",
cikmis="2023/65; 2024/51; 2025/64; 2025/71",
kapsamli=False,
),

# 4 — GY 350/2: yardımcı eşya istisnası
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="KAPSAM",
z="ÇZ",
madde="Gümrük Yönetmeliği md. 350; 4458 sayılı Gümrük Kanunu md. 108",
cek="Ürünlerin denenmesi veya kusur tespiti dışındaki yakıt-enerji, denenme-ayarlama-geri alma dışındaki yağlar ile alet ve gereç için izin verilmez.",
kok=["Gümrük Yönetmeliği'ne göre, işleme sırasında tamamen veya kısmen tüketilseler dahi işlem görmüş ürünler içinde bulunmayan ancak bu ürünlerin üretilmesini sağlayan veya kolaylaştıran eşyanın kullanılması kapsamında aşağıdakilerden hangisi için dahilde işleme izni verilebilir?"],
d="İşlem görmüş ürünlerin denenmesinde kullanılan yakıt ve enerji kaynakları",
c=["Üretim makinelerinin çalıştırılmasında kullanılan yakıt ve enerji kaynakları",
   "Üretim makinelerinin yağlanmasında kullanılan yağlar",
   "İşleme faaliyetinde kullanılan aletler",
   "Üretim hattında kullanılan ölçüm gereçleri"],
sirali=False,
g="4458 sayılı Gümrük Kanunu, işleme sırasında tüketilse dahi işlem görmüş ürünün içinde bulunmayan ama üretimi sağlayan veya kolaylaştıran önceden belirlenmiş bazı eşyanın kullanılmasını da işleme faaliyeti sayar. Gümrük Yönetmeliği bu tür eşya için izni üç grup hariç verir. Birincisi, işlem görmüş ürünlerin denenmesinde veya tamire ihtiyacı olan ithal eşyanın kusurlarının tespitinde kullanılanlar dışındaki yakıt ve enerji kaynaklarıdır. İkincisi, ürünlerin denenmesi, ayarlanması veya geri alınmasında kullanılanlar dışındaki yağlardır. Üçüncüsü alet ve gereçtir. Böylece ürünlerin denenmesinde kullanılan yakıt ve enerji kaynakları istisnanın istisnası olarak izin kapsamına girer. Makinelerin çalıştırılmasındaki yakıt, makinelerin yağlanmasındaki yağ, aletler ve ölçüm gereçleri ise hariç tutulan gruplardadır. En güçlü çeldirici makinelerin çalıştırılmasında kullanılan yakıttır; yakıtın izne girmesi yalnızca ürünün denenmesi veya kusur tespiti amacına bağlıdır. Bu nedenle doğru cevap 'İşlem görmüş ürünlerin denenmesinde kullanılan yakıt ve enerji kaynakları' seçeneğidir. (MD GY 350; GK 108)",
kanit=F + " | İşlem görmüş ürünlerin denenmesinde veya tamire ihtiyacı olan ithal eşyanın kusurlarının tespitinde kullanılanlar haricindeki yakıt ve enerji kaynakları || " + F + " | İşlem görmüş ürünlerin denenmesi, ayarlanması veya geri alınmasında kullanılan yağlar dışındaki yağlar || " + F + " | Alet ve gereç, hariç olmak üzere, izin verilebilir || " + F + " | İşleme sırasında tamamen veya kısmen tüketilseler dahi, işlem görmüş ürünler içinde bulunmayan ancak, bu ürünlerin üretilmesini sağlayan veya kolaylaştıran önceden belirlenmiş bazı eşyanın kullanılması",
yuva=["GY 350/2-a: denenme ve kusur tespiti dışındaki yakıt ve enerji kaynakları (izin verilmez)",
      "GY 350/2-b: denenme, ayarlama ve geri alma dışındaki yağlar (izin verilmez)",
      "GY 350/2-c: alet (izin verilmez)",
      "GY 350/2-c: gereç (izin verilmez)"],
yakinlik="PARAFRAZ",
tuzak=["İSTİSNA", "KOMŞU"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 5 — GK 110: izin (vaka) — yurt dışı yerleşik, ticari ithalat
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="OLAY",
z="Z",
madde="4458 sayılı Gümrük Kanunu md. 110",
cek="DİR izni sadece TGB'de yerleşik kişilere verilir; TGB dışında yerleşiklere yalnız ticari nitelikte olmayan ithalat için izin verilebilir.",
kok=["4458 sayılı Gümrük Kanunu'nun dahilde işleme izninin verilmesine ilişkin hükümleri çerçevesinde aşağıdaki olayı değerlendiriniz:",
     "- (K) şirketinin kanuni merkezi ve bütün işyerleri Almanya'dadır; şirketin Türkiye'de işyeri veya şubesi bulunmamaktadır.",
     "- (K) şirketi, Türkiye'deki bir fabrikaya işleteceği kumaşları dahilde işleme rejimi kapsamında ithal etmek için izin talep etmiştir.",
     "- Fabrikada üretilecek gömlekler, (K) şirketi tarafından Avrupa'daki mağazalarda satılmak üzere yurt dışına gönderilecektir.",
     "- Kumaşın gömlekler içerisindeki mevcudiyeti tespit edilebilmekte, ekonomik koşulların da sağlandığı anlaşılmaktadır.",
     "Buna göre (K) şirketinin izin talebi hakkında aşağıdakilerden hangisi doğrudur?"],
d="Türkiye Gümrük Bölgesi dışında yerleşik kişilere yalnızca ticari nitelikte olmayan dahilde işleme amaçlı ithalat için izin verilebileceğinden talep karşılanamaz.",
c=["İşleme faaliyetini kendisi yapmayıp başka bir fabrikaya yaptıracağı için şirkete dahilde işleme izni verilemez.",
   "Ticari nitelikteki ithalat için de Türkiye Gümrük Bölgesi dışında yerleşik kişilere izin verilebileceğinden talep karşılanır.",
   "İşleme faaliyeti Türkiye'deki bir fabrikada yapılacağından yerleşiklik şartı sağlanmış sayılır ve izin verilir.",
   "İzin, Türkiye Gümrük Bölgesinde yerleşik bir temsilci aracılığıyla talep edilmesi kaydıyla şirkete verilebilir."],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre dahilde işleme izni, işleme faaliyetlerini yapan veya yaptıran kişinin talebi üzerine ve sadece Türkiye Gümrük Bölgesinde yerleşik kişilere verilebilir. Bu kuralın tek istisnası ticari nitelikte olmayan dahilde işleme amaçlı ithalattır; bu durumda Türkiye Gümrük Bölgesi dışında yerleşik kişilere de izin verilebilir. Olayda (K) şirketinin Türkiye'de işyeri veya şubesi yoktur ve gömlekler mağazalarda satılacağı için ithalat ticari niteliktedir. Bu nedenle mevcudiyet tespiti ve ekonomik koşullar sağlanmış olsa bile talep karşılanamaz. İşlemeyi başka bir fabrikaya yaptırmak izne engel değildir, çünkü izin işlemeyi yaptıran kişiye de verilebilir. Fabrikanın Türkiye'de bulunması şirketi yerleşik yapmaz; bir temsilci aracılığıyla başvurmak da izin sahibinin yerleşik olma şartını ortadan kaldırmaz. En güçlü çeldirici 'fason yaptırma' gerekçesidir; Kanun yaptıranı da açıkça saymıştır. Bu nedenle doğru cevap 'Türkiye Gümrük Bölgesi dışında yerleşik kişilere yalnızca ticari nitelikte olmayan dahilde işleme amaçlı ithalat için izin verilebileceğinden talep karşılanamaz.' seçeneğidir. (MD GK 110)",
kanit=F + " | işleme faaliyetlerini yapan veya yaptıran kişinin talebi üzerine verilebilir || " + F + " | Dahilde işleme izni sadece; a) Türkiye Gümrük Bölgesinde yerleşik kişilere || " + F + " | Ticari nitelikte olmayan dahilde işleme amaçlı ithalat için Türkiye Gümrük Bölgesi dışında yerleşik kişilere de izin verilmesi mümkündür",
yuva=["GK 110/1: izin işleme faaliyetlerini yapan veya yaptıran kişinin talebiyle verilir",
      "GK 110/3: TGB dışında yerleşiklere izin yalnız ticari nitelikte olmayan ithalat için (tersine çevrilmiş)",
      "GK 110/2-a: yerleşiklik şartı izin sahibine ilişkindir (sağduyu)",
      "DİR Tebliği 30/1: temsilci aracılığıyla ithalat (izin talebi değil)"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "ŞART", "SAĞDUYU"],
duzey=["UYGULAMA"],
profil=[3],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2024/50; 2025/66",
kapsamli=False,
),

# 6 — Tebliğ 3, 15: izin belgesi müracaatı — ayna B (eksen 18)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="YETKİ",
z="K",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 3, 15",
cek="İzin belgesi Bakanlıkça düzenlenir ve elektronik ortamda Bakanlığa (İhracat Genel Müdürlüğü) başvurulur; dahilde işleme izni gümrük idaresince verilir.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre ihraç amacıyla gümrük muafiyetli ithalata ve/veya yurt içi alımlara imkân sağlayan dahilde işleme izin belgesini almak isteyen firmanın müracaatı aşağıdakilerden hangisine yapılır?"],
d="Elektronik ortamda Bakanlığa (İhracat Genel Müdürlüğü)",
c=["Ek-1'de belirtilen bilgi ve belgelerle elektronik ortamda gümrük idaresine",
   "Elektronik ortamda Gümrükler Genel Müdürlüğüne",
   "Belge aslı ile birlikte ilgili bölge müdürlüğüne",
   "Üyesi bulunulan ihracatçı birliği genel sekreterliğine"],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği iki ayrı izin aracı tanımlar. Dahilde işleme izin belgesi, ihraç amacıyla gümrük muafiyetli ithalata ve/veya yurt içi alımlara imkân sağlayan ve Bakanlıkça düzenlenen belgedir; bu belgeyi almak için elektronik ortamda Bakanlığa (İhracat Genel Müdürlüğü) müracaat edilir. Dahilde işleme izni ise yalnız gümrük muafiyetli ithalata imkân sağlar ve gümrük idaresince verilir. Bu izin için ek-1'deki bilgi ve belgelerle elektronik ortamda gümrük idaresine başvurulur. En güçlü çeldirici, izne ait bu başvuru yeridir. Gümrükler Genel Müdürlüğü iznin uygulama esaslarını belirler. Bölge müdürlüğüne belge aslıyla yapılan başvurular revize ve kayıp belge işlemlerine, ihracatçı birliklerinin kontrolü ise telafi edici vergi tablosuna ilişkindir. Bu nedenle doğru cevap 'Elektronik ortamda Bakanlığa (İhracat Genel Müdürlüğü)' seçeneğidir. (MD Tebliğ 3, 15)",
kanit=F + " | Dahilde işleme izin belgesi: İhraç amacıyla gümrük muafiyetli ithalata ve/veya yurt içi alımlara imkan sağlayan Bakanlıkça düzenlenen belgeyi || " + F + " | Dahilde işleme izin belgesi almak için elektronik ortamda Bakanlığa (İhracat Genel Müdürlüğü) || " + F + " | Dahilde işleme izni almak için ek-1'de belirtilen bilgi ve belgelerle elektronik ortamda || " + F + " | Dahilde işleme izni: İhraç amacıyla gümrük muafiyetli ithalata imkan sağlayan ve gümrük idaresince verilen izni",
yuva=["Tebliğ 15/1-b: dahilde işleme izni müracaatı gümrük idaresine",
      "Tebliğ 17/3: izin uygulama esaslarını Gümrükler Genel Müdürlüğü belirler",
      "Tebliğ 19/2 ve 41: belge aslıyla revize ve kayıp belge müracaatı bölge müdürlüğüne",
      "Tebliğ 38/5: telafi edici vergi tablosunu ihracatçı birlikleri genel sekreterliği kontrol eder"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=18, ayna="SB31-B: izin belgesi müracaatı ↔ dahilde işleme izni işlemleri",
guncellik="",
cikmis="2023/56; 2025/71",
kapsamli=False,
),

# 7 — Tebliğ 17, 19, 37, 38: dahilde işleme izni — ayna B (eksen 18)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="DOĞRU",
z="Z",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 17, 19, 37, 38",
cek="İzin, İhracat GM görüşüyle Gümrükler GM'nin uygulama esasları çerçevesinde elektronik ortamda gümrük idaresince verilir; revizesi ve kapatması da gümrük idaresindedir.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre dahilde işleme iznine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Dahilde işleme izni, İhracat Genel Müdürlüğünün görüşü alınmak suretiyle Gümrükler Genel Müdürlüğünce belirlenen uygulama esasları çerçevesinde elektronik ortamda gümrük idaresince verilir.",
c=["Dahilde işleme iznine ilişkin revize müracaatı elektronik ortamda Bakanlığa (İhracat Genel Müdürlüğü) yapılır ve Bakanlıkça sonuçlandırılır.",
   "Dahilde işleme izni ihracat taahhüdünü kapatmak için gerekli bilgi ve belgeler, izin süresi sonundan itibaren üç ay içinde ilgili bölge müdürlüğüne sunulur.",
   "Dahilde işleme izninde döviz kullanım oranı, yüzde sekseni geçmemek üzere gümrük idaresince belirlenir.",
   "İhracat taahhüdü kapatılan dahilde işleme izinlerinin taahhüt kapatma işlemleri, maddi hata hâlinde İhracat Genel Müdürlüğünün uygun görüşüne istinaden geri alınabilir."],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği'ne göre dahilde işleme izni, İhracat Genel Müdürlüğünün görüşü alınarak Gümrükler Genel Müdürlüğünce belirlenen uygulama esasları çerçevesinde elektronik ortamda gümrük idaresince verilir. Diğer ifadeler, izin belgesine ait kuralları izne taşımaktadır. İznin revize müracaatı gümrük idaresine yapılır ve gümrük idaresince sonuçlandırılır; Bakanlığa elektronik müracaat belgenin revizesine aittir. İzin ihracat taahhüdünün kapatılması için bilgi ve belgeler üç ay içinde gümrük idaresine sunulur; bölge müdürlüğü belge kapatmasının merciidir. Döviz kullanım oranı dahilde işleme izninde aranmaz; yüzde seksenlik sınır belgeye ilişkindir. Kapatılmış izinlerde taahhüt kapatma işleminin geri alınması Bölge Müdürlüklerinin uygun görüşüne bağlıdır; İhracat Genel Müdürlüğünün uygun görüşü belgeler için aranır. Bu nedenle doğru cevap 'Dahilde işleme izni, İhracat Genel Müdürlüğünün görüşü alınmak suretiyle Gümrükler Genel Müdürlüğünce belirlenen uygulama esasları çerçevesinde elektronik ortamda gümrük idaresince verilir.' seçeneğidir. (MD Tebliğ 17, 19, 37, 38)",
kanit=F + " | İhracat Genel Müdürlüğünün görüşü alınmak suretiyle Gümrükler Genel Müdürlüğünce belirlenen uygulama esasları çerçevesinde elektronik ortamda gümrük idaresince verilir || " + F + " | Dahilde işleme iznine ilişkin revize müracaatı, ilgili firma tarafından gerekli bilgi ve belgeler ile birlikte ilgili gümrük idaresine yapılır. Yapılan revize müracaatı gümrük idaresince sonuçlandırılır || " + F + " | Dahilde işleme izni ihracat taahhüdünü kapatmak için en geç izin süresi sonundan itibaren 3 (üç) ay[62] içerisinde, Ek-4'te belirtilen bilgi ve belgeleri ilgili gümrük idaresine || " + F + " | Döviz kullanım oranı; a) Dahilde işleme izninde || " + F + " | ihracat taahhüdü kapatılan dahilde işleme izinlerinin taahhüt kapatma işlemleri Bölge Müdürlüklerinin uygun görüşüne istinaden",
yuva=["Tebliğ 19/1 ve 19/4: elektronik müracaatla Bakanlıkça revize belgeye aittir; izin revizesi gümrük idaresinde",
      "Tebliğ 37/1-a: bölge müdürlüğüne kapatma müracaatı belgeye aittir; izinde gümrük idaresi",
      "Tebliğ 17/8-a ve 17/9: döviz kullanım oranı izinde aranmaz; %80 sınırı belgeye ilişkindir",
      "Tebliğ 38/11: İhracat GM uygun görüşü belgeler için; izinlerde Bölge Müdürlükleri"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=18, ayna="SB31-B: izin belgesi müracaatı ↔ dahilde işleme izni işlemleri",
guncellik="",
cikmis="2023/56",
kapsamli=False,
),

# 8 — Tebliğ 14, 17/4: izin kapsamındaki işlemler
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="KAPSAM_DIŞI",
z="Z",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 14, 17",
cek="Tarım ürünlerinin bedelsiz ithalatına izin kapsamında gümrük idaresince müsaade edilmez; bu talepler izin belgesi kapsamında Bakanlıkça değerlendirilir.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre aşağıdaki işlemlerden hangisine konu eşyanın ithaline dahilde işleme izni kapsamında ilgili gümrük idaresince müsaade edilmez?"],
d="Tarım ürünlerinin bedelsiz olarak ithal edilerek işleme faaliyetine tabi tutulması",
c=["Fide ithalatını müteakip, ihraç edilmek üzere kesme çiçek yetiştirilmesi",
   "Çelik filmaşin ithalatını müteakip, ihraç edilmek üzere çivi ve sıcak çekme siyah tel üretimi",
   "Rulo sacın ithalatını müteakip, ihraç edilmek üzere kesilmiş sac elde edilmesinde kullanılması",
   "Kıymetli maden ve taşların ithalatını müteakip, işlendikten sonra ihraç edilmek üzere işçiliğe tabi tutulması"],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği, dahilde işleme izni kapsamında ithaline izin verilecek işlemleri sayar. Fide ithalatını müteakip kesme çiçek yetiştirilmesi, çelik filmaşinden çivi ve sıcak çekme siyah tel üretimi, rulo sacdan kesilmiş sac elde edilmesi ve kıymetli maden ile taşların işçiliğe tabi tutulması bu listededir. Bedelsiz ithal edilen eşyanın işlenmesi de listededir; ancak tarım ürünlerindeki bedelsiz ithalat bu kapsamın dışında bırakılmıştır. Tebliğ ayrıca tarım ürünlerinin bedelsiz ithalatına izin kapsamında gümrük idarelerince müsaade edilmeyeceğini açıkça söyler; bu talepler dahilde işleme izin belgesi kapsamında Bakanlıkça değerlendirilir. En güçlü tuzak, bedelsiz ithalatın genel olarak izin kapsamında olmasıdır; istisna tarım ürünlerinde gizlidir. Bu nedenle doğru cevap 'Tarım ürünlerinin bedelsiz olarak ithal edilerek işleme faaliyetine tabi tutulması' seçeneğidir. (MD Tebliğ 14, 17)",
kanit=F + " | Fide ithalatını müteakip, ihraç edilmek üzere kesme çiçek yetiştirilmesi || " + F + " | Çelik filmaşin ithalatını müteakip, ihraç edilmek üzere çivi ve sıcak çekme siyah tel üretimi || " + F + " | Rulo sacın ithalatını müteakip, ihraç edilmek üzere kesilmiş sac elde edilmesinde kullanılması || " + F + " | işlendikten sonra ihraç edilmek üzere işçiliğe tabi tutulması || " + F + " | Bedelsiz olarak ithal edilen eşyanın işleme faaliyetine tabi tutulması (Tarım ürünlerindeki bedelsiz ithalat || " + F + " | tarım ürünlerinin bedelsiz ithalatına, Savunma Sanayi Projeleri kapsamında yapılacak bedelsiz ithalata ve Ek-7'de belirtilen ürünlerin bedelli veya bedelsiz olarak ithalatına dahilde işleme izni kapsamında ilgili gümrük idarelerince müsaade edilmez || " + F + " | Bu çerçevedeki talepler dahilde işleme izin belgesi kapsamında Bakanlıkça değerlendirilir",
yuva=["Tebliğ 14/1-g: fide → kesme çiçek (izin kapsamında)",
      "Tebliğ 14/1-ğ: çelik filmaşin → çivi ve siyah tel (izin kapsamında)",
      "Tebliğ 14/1-h: rulo sac → kesilmiş sac (izin kapsamında)",
      "Tebliğ 14/1-b: kıymetli maden ve taşların işçiliği (izin kapsamında)"],
yakinlik="BİREBİR",
tuzak=["İSTİSNA", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=True, vaka=False, baslangic=False,
eksen=18, ayna="",
guncellik="",
cikmis="2025/59",
kapsamli=False,
),

# 9 — Tebliğ 17/12: işletme malzemesi %2
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="ORAN-TUTAR",
z="K",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 17",
cek="İşletme malzemesi değeri ihracat taahhüdünün %2'sini geçemez (doğal taş, kıymetli maden ve taşta %10'a kadar); değişmemiş eşya azami %1.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre doğal taşlar ile kıymetli maden ve taş ihraç taahhüdü içermeyen bir belge/izin kapsamında ithaline izin verilecek işletme malzemesi değeri, ihracat taahhüdünün yüzde kaçını geçemez?"],
d="%2",
c=["%1", "%10", "%25", "%80"],
sirali=True,
siklar=["%1", "%2", "%10", "%25", "%80"],
g="Dahilde İşleme Rejimi Tebliği'ne göre belge veya izin kapsamında ithaline izin verilecek işletme malzemesinin değeri ihracat taahhüdünün yüzde ikisini geçemez. Doğal taşlar ile kıymetli maden ve taş ihraç taahhüdü içeren belge veya izinlerde bu oran yüzde ona kadar tespit edilebilir; soru bu istisnanın dışındaki durumu sormaktadır. En güçlü çeldirici, hemen önceki hükümde yer alan yüzde birdir; bu oran ihracat taahhüdü içindeki değişmemiş eşya ithalatının azami sınırıdır. Yüzde yirmi beş performansa dayalı ek süre eşiği, yüzde seksen ise belgede döviz kullanım oranının azami sınırıdır. Bu nedenle doğru cevap '%2' seçeneğidir. (MD Tebliğ 17)",
kanit=F + " | Belge/izin kapsamında ithaline izin verilecek işletme malzemesi değeri, ihracat taahhüdünün % 2'sini geçemez || " + F + " | doğal taşlar ile kıymetli maden ve taş ihraç taahhüdü içeren belgede/izinde, bu oran % 10'a kadar tespit edilebilir || " + F + " | Belge/izin kapsamında ihracat taahhüdünün azami % 1'i oranında değişmemiş eşya ithalatına izin verilebilir",
yuva=["Tebliğ 17/11: değişmemiş eşya ithalatı azami %1",
      "Tebliğ 17/12 ikinci cümle: doğal taş, kıymetli maden ve taşta %10'a kadar",
      "Tebliğ 22/2: performansa dayalı ek süre için en az %25",
      "Tebliğ 17/9: belgede döviz kullanım oranı azami %80"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 10 — Tebliğ 3/h, 38/4: döviz kullanım oranı (hesap)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="HESAP",
z="O",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 3, 17, 38",
cek="Döviz kullanım oranı, yurt içi alımlar hariç CIF ithal tutarının FOB ihraç tutarına yüzde oranıdır.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre döviz kullanım oranının hesaplanmasına ilişkin aşağıdaki bilgiler verilmiştir:",
     "- (M) firması adına düzenlenen dahilde işleme izin belgesi kapsamında 300.000 ABD Doları CIF tutarında ithalat yapılmıştır.",
     "- Aynı belge kapsamında yurt içinden 100.000 ABD Doları tutarında hammadde alımı yapılmıştır.",
     "- Belge kapsamında gerçekleştirilen ihracatın FOB tutarı 400.000 ABD Dolarıdır.",
     "- Belge kapsamında ikincil işlem görmüş ürün elde edilmemiştir.",
     "Buna göre belge kapsamındaki döviz kullanım oranı yüzde kaçtır?"],
d="%75",
c=["%25", "%60", "%80", "%100"],
sirali=True,
siklar=["%25", "%60", "%75", "%80", "%100"],
g="Dahilde İşleme Rejimi Tebliği'ne göre döviz kullanım oranı, yurt içi alımlar hariç CIF ithal tutarının FOB ihraç tutarına yüzde oranıdır. Paydaya, ikincil işlem görmüş ürün serbest dolaşıma giriş rejimine göre ithal edilmişse onun gümrük kıymeti eklenir; olayda ikincil ürün yoktur. Buna göre oran 300.000 / 400.000 = %75'tir. Vakadaki tuzak yurt içi alımdır. 100.000 ABD Dolarlık alım CIF ithal tutarına eklenirse oran (300.000 + 100.000) / 400.000 = %100 bulunur; bu hesap hatalıdır. Alım paydaya eklenirse 300.000 / 500.000 = %60 çıkar; bu da hatalıdır. %80 hesaplanan oran değil, belgede döviz kullanım oranının aşamayacağı azami sınırdır. %25 ise yalnızca yurt içi alımın ihracata oranıdır. Bu nedenle doğru cevap '%75' seçeneğidir. (MD Tebliğ 3, 17, 38)",
kanit=F + " | Döviz kullanım oranı: Dahilde işleme izin belgesi/dahilde işleme izni kapsamındaki CIF ithal (yurt içi alımlar hariç) tutarının FOB ihraç tutarına || " + F + " | yurt içi alımlar hariç CIF ithal tutarının (Fatura bedelinin CIF ABD Dolarına karşılık gelen değerinin) FOB ihraç tutarına || " + F + " | Dahilde işleme izin belgesi kapsamında döviz kullanım oranı % 80'i geçmemek üzere Bakanlıkça belirlenir",
yuva=["Yurt içi alımın FOB ihraç tutarına oranı (formülde yer almaz)",
      "Yurt içi alımın paydaya eklenmesi (Tebliğ 38/4 formülüne aykırı)",
      "Tebliğ 17/9: belgede döviz kullanım oranının azami sınırı %80",
      "Yurt içi alımın CIF ithal tutarına eklenmesi (Tebliğ 3/h ve 38/4: yurt içi alımlar hariç)"],
yakinlik="ÇIKARIM",
tuzak=["AD-HESAP", "İSTİSNA"],
duzey=["UYGULAMA"],
profil=[2],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2025/71",
kapsamli=False,
),

# 11 — GY 353-355, Tebliğ 6/3: önceden ihracat (önermeli)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Yönetmeliği md. 353, 354, 355; Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 6",
cek="Önceden ihracatta ithal eşyası beyan süresi ihracat beyannamesinin tescilinden başlar, haklı gerekçeyle uzatılır; ithalatta KDV dahil vergiler teminata bağlanır.",
kok=["Gümrük Yönetmeliği ile Dahilde İşleme Rejimi Tebliği'nin (İhracat: 2006/12) şartlı muafiyet sisteminde önceden ihracat uygulamasına ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Eşdeğer eşya karşılığı ithal eşyasının gümrük beyanı için gereken süre, dahilde işleme izin belgesinin tarihinden itibaren işlemeye başlar.",
     "II. Eşdeğer eşya karşılığı ithal eşyasının gümrük beyanı için gereken süre, izin hak sahibinin haklı bir gerekçeye dayanan talebi üzerine uzatılabilir.",
     "III. Önceden ihracata tekabül eden ithalat esnasında, Özel Tüketim Vergisi Kanunu hükümleri saklı kalmak kaydıyla, katma değer vergisi dahil tüm vergiler teminata bağlanır ve ticaret politikası önlemleri uygulanmaz.",
     "IV. İthal edilecek eşyanın rejime girmesi şartıyla, ithal eşyası rejime girişi sırasında serbest dolaşımda bulunan eşya kabul edilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II, III ve IV",
c=["I ve II", "II ve III", "I, III ve IV", "I, II, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre önceden ihracat durumunda, eşdeğer eşya karşılığı ithal eşyasının gümrük beyanı için gereken süre izin belgesinde belirtilir. Bu süre, eşdeğer eşyadan elde edilen işlem görmüş ürünlere ait ihracat beyannamesinin tescil tarihinden itibaren işler. Bu yüzden süreyi izin belgesinin tarihinden başlatan I. ifade yanlıştır; izin belgesinin tarihi, belgenin kendi geçerlilik süresinin başlangıcıdır. II. ifade doğrudur: süre, izin hak sahibinin haklı bir gerekçeye dayanan talebi üzerine uzatılabilir. III. ifade doğrudur: Tebliğe göre önceden ihracata tekabül eden ithalatta, Özel Tüketim Vergisi Kanunu hükümleri saklı kalmak kaydıyla katma değer vergisi dahil tüm vergiler teminata bağlanır ve ticaret politikası önlemleri uygulanmaz. IV. ifade de doğrudur: ithal edilecek eşyanın rejime girmesi şartıyla, ithal eşyası rejime girişi sırasında serbest dolaşımda bulunan eşya kabul edilir. Bu nedenle doğru cevap 'II, III ve IV' seçeneğidir. (MD GY 353-355; Tebliğ 6)",
kanit=F + " | Önceden ihracat durumunda izin belgesinde, eşdeğer eşya karşılığı ithal eşyasının gümrük beyanı için gereken süre belirtilir. Bu süre, ilgili eşdeğer eşyadan elde edilen işlem görmüş ürünler için ihracat beyannamesinin tescil tarihinden itibaren işlemeye başlar || " + F + " | Süre, izin hak sahibinin haklı bir gerekçeye dayanan talebi üzerine uzatılabilir || " + F + " | katma değer vergisi dahil tüm vergiler (4760 sayılı Özel Tüketim Vergisi Kanunu hükümleri saklı kalmak kaydıyla) teminata bağlanır ve ticaret politikası önlemleri uygulanmaz || " + F + " | Önceden ihracat durumunda, ithal edilecek eşyanın rejime girmesi şartıyla işlem görmüş ürünler ihracat beyannamesinin tescil edilmesiyle serbest dolaşımda olmayan eşya, ithal eşyası ise rejime girişi sırasında serbest dolaşımda bulunan eşya kabul edilir || " + F + " | Sürenin başlangıcı izin belgesinin tarihidir",
yuva=["I yanlış olduğundan eksik ve hatalı kombinasyon",
      "IV de doğru olduğundan eksik kombinasyon",
      "I yanlış: izin belgesinin tarihi belge süresinin başlangıcıdır (GY 353/1)",
      "I yanlış olduğundan en kapsamlı şık hatalı"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="2025/67",
kapsamli=False,
),

# 12 — Tebliğ 25: mücbir sebep ve fevkalade hâller
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="KAPSAM_DIŞI",
z="O",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 25",
cek="Mücbir sebep listesinde ölüm yalnızca şahıs firmalarında firma sahibinin ölümüdür; sermaye şirketinde ortağın ölümü sayılmamıştır.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre belge/izin süresi içerisinde meydana gelmesi hâlinde dahilde işleme izin belgesine veya dahilde işleme iznine ilave süre verilebilecek mücbir sebep ile fevkalade hâller arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="Sermaye şirketlerinde şirket ortaklarından birinin ölümü",
c=["Yükümlü firmanın faaliyetinin kamu otoritelerince kısıtlanması, durdurulması veya firmaya el konulması",
   "Ülkemizde veya ithalatçı ülkede genel salgın hastalık",
   "Yükümlü firmanın konkordato ilan etmiş olması",
   "Grev ve lokavt"],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği, belge veya izin süresi içinde meydana geldiğinde ilave süre verilebilecek mücbir sebep ve fevkalade hâlleri tek tek sayar: deprem, sel, don, fırtına, kasırga gibi tabii afetler ve yangın; ülkemizde veya ithalatçı ülkede devletçe konulan yasaklar, harp ve abluka hâli ya da genel salgın hastalık; yükümlü firmanın faaliyetinin kamu otoritelerince kısıtlanması, durdurulması veya firmaya el konulması; firmanın iflası, konkordato ilan etmesi ya da hakkında iflasın ertelenmesi kararı verilmesi; şahıs firmalarında firma sahibinin ölümü; grev ve lokavt. Ölüm yalnızca şahıs firmalarında ve yalnızca firma sahibi için sayılmıştır. Sermaye şirketlerinde bir ortağın ölümü listede yer almaz. En güçlü tuzak, listedeki 'ölüm' unsurunun kişi ve şirket türü kaydı düşürülerek genişletilmesidir. Bu nedenle doğru cevap 'Sermaye şirketlerinde şirket ortaklarından birinin ölümü' seçeneğidir. (MD Tebliğ 25)",
kanit=F + " | Şahıs firmalarında firma sahibinin ölümü || " + F + " | Yükümlü firmanın faaliyetinin kamu otoritelerince kısıtlanması, durdurulması veya firmaya el konulması || " + F + " | Ülkemiz veya ithalatçı ülkede; devletçe konulan yasaklar, harp ve abluka hali veya genel salgın hastalık || " + F + " | Yükümlü firmanın iflası veya konkordato ilan etmiş olması || " + F + " | Grev ve lokavt (İl çalışma müdürlüklerinden alınacak yazı ile)",
yuva=["Tebliğ 25/1-c: faaliyetin kısıtlanması, durdurulması, el konulması",
      "Tebliğ 25/1-b: ülkemizde veya ithalatçı ülkede genel salgın hastalık",
      "Tebliğ 25/1-ç: iflas veya konkordato",
      "Tebliğ 25/1-e: grev ve lokavt"],
yakinlik="BİREBİR",
tuzak=["UNSUR", "LİSTE-DIŞI"],
duzey=["AYIRT"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2024/53",
kapsamli=False,
),

# 13 — Tebliğ 30: temsilci aracılığıyla ithalat (meslek yanlılığı)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="YANLIŞ",
z="O",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 30",
cek="Belge/izin kapsamı ithalat, Borçlar Kanununa göre doğrudan veya dolaylı temsille tayin edilen temsilciyle yapılabilir; gümrük müşaviri şartı yoktur.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre dahilde işleme izin belgesi/dahilde işleme izni kapsamındaki eşyanın temsilci aracılığıyla ithalatına ilişkin aşağıdaki ifadelerden hangisi yanlıştır?"],
d="Belge/izin kapsamındaki eşyanın temsilci aracılığıyla ithalatı, ancak bir gümrük müşavirinin dolaylı temsilci olarak tayin edilmesi hâlinde yapılabilir.",
c=["Elektronik ortamda düzenlenen dahilde işleme izin belgesi kapsamında temsilci aracılığıyla ithalat yapılabilmesi için önceden ilgili bölge müdürlüğünden izin alınması gerekir.",
   "Temsilci aracılığıyla yapılan ithalata, belge/izin süresi içerisinde belirtilen miktarı geçmemesi kaydıyla ilgili gümrük idaresince izin verilir.",
   "Temsilci aracılığıyla yapılan ithalata ilişkin gümrük beyannamesi üzerinde belge sahibi firma unvanı ile belge satır kodunun kaydedilmiş olması gerekir.",
   "İthalata aracılık eden temsilcinin eşyayı belge/izin sahibine teslim etmediğinin tespiti hâlinde temsilci, alınmayan vergiden belge/izin sahibi firma ile birlikte müştereken ve müteselsilen sorumludur."],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği'ne göre belge veya izin kapsamındaki eşyanın ithalatı belge/izin sahibi firma tarafından yapılabilir. Borçlar Kanununun doğrudan ya da dolaylı temsil hükümlerine göre tayin edilmiş bir temsilci aracılığıyla da yapılabilir. Tebliğ temsilcinin gümrük müşaviri olmasını veya yalnızca dolaylı temsil yolunun kullanılmasını şart koşmaz; bu nedenle ithalatı gümrük müşavirinin dolaylı temsilci olarak tayinine bağlayan ifade yanlıştır. Diğer ifadeler doğrudur. Elektronik ortamda düzenlenen belgede temsilci aracılığıyla ithalat için önceden ilgili bölge müdürlüğünden izin alınır. Gümrük idaresi, belge/izin süresi içinde belirtilen miktarı geçmemek ve beyannamede belge sahibi firma unvanı ile satır kodu kaydedilmek kaydıyla ithalata izin verir. Temsilci eşyayı belge/izin sahibine teslim etmezse, alınmayan vergiden firma ile birlikte müştereken ve müteselsilen sorumludur. Bu nedenle doğru cevap 'Belge/izin kapsamındaki eşyanın temsilci aracılığıyla ithalatı, ancak bir gümrük müşavirinin dolaylı temsilci olarak tayin edilmesi hâlinde yapılabilir.' seçeneğidir. (MD Tebliğ 30)",
kanit=F + " | Borçlar Kanununun doğrudan ya da dolaylı temsil hükümlerine göre tayin edilmiş olmak kaydıyla, temsilci aracılığıyla da yapılabilir || " + F + " | elektronik ortamda düzenlenen dahilde işleme izin belgesi kapsamında temsilci aracılığıyla ithalat yapılabilmesi için önceden ilgili bölge müdürlüğünden izin alınması gerekir || " + F + " | belge/izin süresi içerisinde belirtilen miktarı geçmemesi kaydıyla ithalata izin verilir || " + F + " | belge sahibi firma unvanı ile belge satır kodunun kaydedilmiş olması kaydıyla || " + F + " | ithalata aracılık eden temsilcinin eşyayı belge/izin sahibine teslim etmediğinin",
yuva=["Tebliğ 30/1 ikinci cümle (doğru ifade)",
      "Tebliğ 30/2 birinci cümle (doğru ifade)",
      "Tebliğ 30/2 ikinci cümle (doğru ifade)",
      "Tebliğ 30/3 (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["SAĞDUYU", "ŞART"],
duzey=["AYIRT"],
profil=[3, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 14 — Tebliğ 33: telafi edici vergi
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="DOĞRU",
z="Z",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 33",
cek="Önceden ihracattan sonra ithalatta telafi edici vergi, önceden ihracat beyannamesinin tescil tarihindeki kur ve vergiyle hesaplanıp ithalat esnasında ödenir.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre şartlı muafiyet sistemi kapsamında işlem görmüş ürünün A.TR dolaşım belgesi eşliğinde Avrupa Topluluğuna üye ülkelere ihracatında, ürünün elde edilmesinde kullanılan üçüncü ülke menşeli eşyaya ilişkin ödenen telafi edici vergi ile ilgili aşağıdakilerden hangisi doğrudur?"],
d="Önceden ihracattan sonra ithalat yapılıyorsa vergi, önceden ihracata ilişkin gümrük beyannamesinin tescil tarihindeki kur ve gümrük vergisi üzerinden hesaplanıp ithalat esnasında ödenir.",
c=["Vergi, önceden ihracat yapılmış olsun olmasın, her durumda ithal eşyasına ilişkin gümrük beyannamesinin tescil tarihindeki Türkiye Cumhuriyet Merkez Bankası döviz satış kuru üzerinden hesaplanır.",
   "Tahsil edilen telafi edici vergi, ihracatı gerçekleştiren firmanın üyesi olduğu ihracatçı birliğinin hesabına irat kaydedilir.",
   "İşlem görmüş ürünün elde edilmesinde kullanılan vergiye konu eşyanın tespitinde gümrük idaresince düzenlenen ekspertiz raporu esas alınır.",
   "Elde edilmesinde üçüncü ülke menşeli eşya kullanılan harp araç, gereç ve teçhizatının bu ülkelere ihracatında da telafi edici vergi aranır."],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği'ne göre telafi edici vergi, ihracata ilişkin gümrük beyannamesinin tescil tarihindeki Türkiye Cumhuriyet Merkez Bankası döviz satış kuru ve o tarihte ithalat rejiminde belirtilen gümrük vergisi ile varsa toplu konut fonu üzerinden hesaplanır ve ihracat esnasında ödenir. Belge kapsamında önceden ihracattan sonra ithalat yapılıyorsa vergi, önceden ihracata ilişkin gümrük beyannamesinin tescil tarihindeki kur ve vergi üzerinden hesaplanır ve önceden ihracata tekabül eden ithalat yapılırken ödenir. En güçlü çeldirici, hesaplamayı ithal eşyasına ilişkin beyannamenin tescil tarihine bağlayan ifadedir; esas alınan beyanname her durumda ihracata ilişkin beyannamedir. Tahsil edilen telafi edici vergi bütçeye irat kaydedilir. Vergiye konu eşyanın tespitinde firma beyanı esas alınır. Üçüncü ülke menşeli eşya kullanılarak elde edilip Avrupa Topluluğuna üye ülkelere ihraç edilen harp araç, gereç ve teçhizatı için telafi edici vergi aranmaz. Bu nedenle doğru cevap 'Önceden ihracattan sonra ithalat yapılıyorsa vergi, önceden ihracata ilişkin gümrük beyannamesinin tescil tarihindeki kur ve gümrük vergisi üzerinden hesaplanıp ithalat esnasında ödenir.' seçeneğidir. (MD Tebliğ 33)",
kanit=F + " | Ancak, belge kapsamında önceden ihracat işleminden sonra ithalat yapılması durumunda, bu vergi serbest bölgelerden gerçekleştirilen satışlar dahil önceden ihracata ilişkin gümrük beyannamesinin tescil tarihindeki Türkiye Cumhuriyet Merkez Bankası döviz satış kuru ve bu tarihte ithalat rejiminde belirtilen gümrük vergisi ve varsa toplu konut fonu üzerinden hesaplanarak, önceden ihracata tekabül eden ithalatın yapılması esnasında ödenir || " + F + " | Tahsil edilen telafi edici vergi bütçeye irat kaydedilir || " + F + " | İşlem görmüş ürünün elde edilmesinde kullanılan vergiye konu eşyanın tespitinde firma beyanı esas alınır || " + F + " | bunların yapım, bakım ve onarımlarında kullanılacak yedek parçalar için telafi edici vergi aranmaz || " + F + " | serbest bölgelerden gerçekleştirilen satışlar dahil ihracata ilişkin gümrük beyannamesinin tescil tarihindeki Türkiye Cumhuriyet Merkez Bankası döviz satış kuru",
yuva=["Tebliğ 33/7 birinci cümle: esas alınan ihracata ilişkin beyannamenin tescil tarihi",
      "Tebliğ 33/7 son cümle: telafi edici vergi bütçeye irat kaydedilir",
      "Tebliğ 33/8: vergiye konu eşyanın tespitinde firma beyanı esas alınır",
      "Tebliğ 33/9: harp araç, gereç ve teçhizatı için telafi edici vergi aranmaz"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/89; 2022/46; 2024/54",
kapsamli=False,
),

# 15 — Tebliğ 3, 33: menşe ve dolaşım belgeleri (önermeli)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="ÖNERMELİ",
z="Z",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 3, 33",
cek="EUR.1 menşe ispat belgesidir; tedarikçi beyanı kümülasyonda menşei gösterir; tarım ürünlerinde menşe ispat belgesi aranır; A.TR'yi ihracatçı ülke düzenler.",
kok=["Dahilde İşleme Rejimi Tebliği'nde (İhracat: 2006/12) yer alan dolaşım ve menşe belgelerine ilişkin hükümler çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. EUR.1 dolaşım sertifikası, Tebliğde malın menşeini belirleyen menşe ispat belgeleri arasında sayılmıştır.",
     "II. Tedarikçi beyanı, A.TR dolaşım belgesi, EUR.1 dolaşım sertifikası veya EUR-MED dolaşım sertifikası ile birlikte kullanılan ve Pan-Avrupa veya Pan-Avrupa-Akdeniz Menşe Kümülasyonu kapsamı eşyanın menşeini gösteren belgedir.",
     "III. Şartlı muafiyet sistemi kapsamında tarım ürünlerinin Avrupa Topluluğuna üye ülkelere ihracatında, üçüncü ülke menşeli girdilere ilişkin verginin tahsili A.TR dolaşım belgesinin düzenlenmesi kaydıyla öngörülmüştür.",
     "IV. A.TR dolaşım belgesi, ithalatçı ülke yetkili kuruluşlarınca düzenlenip gümrük idaresince vize edilen belgedir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve II",
c=["Yalnız I", "I ve III", "II ve IV", "I, II ve III"],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği'ne göre menşe ispat belgeleri, malın menşeini belirleyen EUR.1 dolaşım sertifikası, EUR-MED dolaşım sertifikası, EUR-MED fatura beyanı veya fatura beyanıdır; bu yüzden I. ifade doğrudur. Tedarikçi beyanı, A.TR dolaşım belgesi, EUR.1 veya EUR-MED dolaşım sertifikası ile birlikte kullanılan ve Türkiye ile Topluluk arasında ticarete konu Pan-Avrupa veya Pan-Avrupa-Akdeniz menşe kümülasyonu kapsamı eşyanın menşeini gösteren belgedir; II. ifade de doğrudur. III. ifade yanlıştır: şartlı muafiyet sisteminde tarım ürünlerinin Avrupa Topluluğuna üye ülkelere ihracatında üçüncü ülke menşeli girdilere ilişkin vergi, anlaşmadaki menşe kuralının sağlanması ve bir menşe ispat belgesinin düzenlenmesi kaydıyla tahsil edilir. A.TR dolaşım belgesi ise sanayi ürünleri ile işlenmiş tarım ürünlerine ilişkin hükümlerde geçer. IV. ifade de yanlıştır: A.TR dolaşım belgesi ithalatçı ülkenin değil, ihracatçı ülkenin yetkili kuruluşlarınca düzenlenir ve gümrük idaresince vize edilir. Bu nedenle doğru cevap 'I ve II' seçeneğidir. (MD Tebliğ 3, 33)",
kanit=F + " | ihracatçı ülke yetkili kuruluşlarınca düzenlenip gümrük idaresince vize edilen ve malın menşeini belirleyen EUR.1 dolaşım sertifikası, EUR-MED dolaşım sertifikası, EUR-MED fatura beyanı veya fatura beyanını || " + F + " | Tedarikçi beyanı: A.TR dolaşım belgesi, EUR.1 dolaşım sertifikası veya EUR-MED dolaşım sertifikası ile birlikte kullanılan ve Türkiye ile Topluluk arasında ticarete konu Pan-Avrupa Menşe Kümülasyonu veya Pan-Avrupa-Akdeniz Menşe Kümülasyonu kapsamı eşyanın menşeini gösteren belgeyi || " + F + " | Anlaşma ile belirlenen menşe kuralının sağlanması ve bir menşe ispat belgesinin düzenlenmesi kaydıyla, şartlı muafiyet sistemi kapsamında ülkemizde doğmuş ve büyütülmüş canlı hayvanlar || " + F + " | tarım ürünlerinin Avrupa Topluluğuna üye ülkelere ihracatında; bu ürünlerin elde edilmesinde kullanılan üçüncü ülke menşeli hammadde || " + F + " | Katma Protokolde öngörülen tercihli rejimden yararlanabilmesini sağlamak üzere, ihracatçı ülke yetkili kuruluşlarınca düzenlenip gümrük idaresince vize edilen belgeyi",
yuva=["II de doğru olduğundan eksik kombinasyon",
      "III yanlış: tarım ürünlerinde menşe ispat belgesi aranır (Tebliğ 33/3); A.TR sanayi ürünlerinde (33/1)",
      "IV yanlış: A.TR'yi ihracatçı ülke yetkili kuruluşları düzenler (Tebliğ 3/c)",
      "III yanlış olduğundan hatalı kombinasyon"],
yakinlik="PARAFRAZ",
tuzak=["TERİM", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2023/41; 2025/41",
kapsamli=False,
),

# 16 — GY 359, GK 114-115: ikincil işlem görmüş ürünlerin vergileri (önermeli)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="ÖNERMELİ",
z="O",
madde="Gümrük Yönetmeliği md. 359; 4458 sayılı Gümrük Kanunu md. 114, 115",
cek="İkincil ürün vergisi serbest dolaşıma giriş tescilindeki oranla, ayniyet tespitsiz alınır; ilk partiyle toplu beyan ve ithal eşyası esasına göre hesap talebi mümkündür.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'nin dahilde işleme rejiminde işlem görmüş ikincil ürünlerin vergilendirilmesine ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. İşlem görmüş asıl ürünlerin ihraç edilen kısmı ile orantılı olarak serbest dolaşıma girecek işlem görmüş ikincil ürünlerin gümrük vergileri, serbest dolaşıma giriş beyannamesinin tescil edildiği tarihte yürürlükte bulunan vergi oranı üzerinden hesaplanır.",
     "II. Hak sahibince, ihracata konu işlem görmüş asıl ürünün ilk partisinin ihracatı ile eş zamanlı olarak belgelerde öngörülen işlem görmüş ikincil ürünün tamamı için serbest dolaşıma giriş beyannamesi verilebilir.",
     "III. İkincil işlem görmüş ürünlerin serbest dolaşıma girişinde gümrük vergileri, ilgili kurumların kontrolleri hariç olmak üzere, ayniyet tespiti yapılmaksızın firma beyanı ve izinde öngörülen gerçekleşme oranları üzerinden hesaplanan miktar ve birim fiyat esas alınarak tahsil edilir.",
     "IV. İzin hak sahibi, bu hesaplamanın ithal eşyasının dahilde işleme rejimine ilişkin beyannamesinin tescil tarihindeki vergi oranı ve diğer vergilendirme unsurlarına göre yapılmasını talep edebilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, II, III ve IV",
c=["I ve II", "II ve IV", "I, II ve III", "I, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre işlem görmüş asıl ürünlerin ihraç edilen kısmıyla orantılı olarak serbest dolaşıma girecek ikincil ürünlerin gümrük vergileri, serbest dolaşıma giriş beyannamesinin tescil edildiği tarihteki vergi oranı üzerinden hesaplanır; I. ifade doğrudur. Hak sahibi, asıl ürünün ilk partisinin ihracatıyla eş zamanlı olarak belgelerde öngörülen ikincil ürünün tamamı için serbest dolaşıma giriş beyannamesi verebilir; II. ifade doğrudur. Bu ürünlerin serbest dolaşıma girişinde gümrük vergileri, ilgili kurumların kontrolleri hariç, ayniyet tespiti yapılmaksızın firma beyanı ve izinde öngörülen gerçekleşme oranları üzerinden hesaplanan miktar ve birim fiyat esas alınarak tahsil edilir; III. ifade doğrudur. İzin hak sahibi bu hesaplamanın Kanunda ithal eşyası için öngörülen esasa göre yapılmasını da talep edebilir; bu esas, ithal eşyasının dahilde işleme rejimine ilişkin beyannamesinin tescil tarihindeki vergi oranı ve diğer vergilendirme unsurlarıdır. Bu yüzden IV. ifade de doğrudur. Tuzak, 'ayniyet tespiti yapılmaksızın' ve 'talep edebilir' gibi kolaylık hükümlerinin yanlış sanılmasıdır. Bu nedenle doğru cevap 'I, II, III ve IV' seçeneğidir. (MD GY 359; GK 114, 115)",
kanit=F + " | işlem görmüş asıl ürünlerin ihraç edilen kısmı ile orantılı olarak serbest dolaşıma girecek işlem görmüş ikincil ürünlerin gümrük vergileri, serbest dolaşıma giriş beyannamesinin tescil edildiği tarihte yürürlükte bulunan vergi oranı üzerinden hesaplanır || " + F + " | hak sahibince ihracata konu işlem görmüş asıl ürünün ilk partisinin ihracatı ile eş zamanlı olarak belgelerde öngörülen işlem görmüş ikincil ürünün tamamı için serbest dolaşıma giriş beyannamesi verilebilir || " + F + " | ilgili kurumların yürürlükteki mevzuatları uyarınca yapacakları kontroller hariç olmak üzere, gümrük vergileri ayniyet tespiti yapılmaksızın firma beyanı ve izinde öngörülen gerçekleşme oranları üzerinden hesaplanan miktar ve birim fiyat esas alınarak tahsil edilir || " + F + " | İzin hak sahibi, bu hesaplamanın Kanunun 114 üncü maddesinde belirtilen esaslara göre yapılmasını talep edebilir || " + F + " | ithal eşyasının dahilde işleme rejimine ilişkin beyannamenin tescil tarihindeki vergi oranı ve diğer vergilendirme unsurları göz önünde bulundurularak hesaplanır",
yuva=["III ve IV de doğru olduğundan eksik",
      "I ve III de doğru olduğundan eksik",
      "IV de doğru (GY 359/2) olduğundan eksik",
      "II de doğru (GY 359/1 üçüncü cümle) olduğundan eksik"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=True,
),

# 17 — GK 117: geri ödeme sistemi uygulanmayan eşya
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="KAPSAM_DIŞI",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 117",
cek="Geri ödeme: miktar kısıtlaması, kota kapsamı tarife önlemi, tarım lisansı-sertifikası, ihracat iadesi veya vergisi olan eşyada uygulanmaz; anti-damping sayılmamıştır.",
kok=["4458 sayılı Gümrük Kanunu'na göre serbest dolaşıma giriş beyannamesinin tescili sırasında taşıdığı nitelik nedeniyle geri ödeme sistemi uygulanmayan eşya arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="Anti-damping vergisine tabi olan eşya",
c=["İthalat miktar kısıtlamasına tabi olan eşya",
   "Kota kapsamında tarife önlemleri uygulanan eşya",
   "Tarım politikası çerçevesinde ithalat veya ihracat lisansı veya sertifikası ibrazını gerektiren eşya",
   "İşlem görmüş ürün için ihracat iadesi veya vergisi mevcut olan eşya"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre geri ödeme sisteminden kural olarak her eşya yararlanabilir. Ancak serbest dolaşıma giriş beyannamesinin tescili sırasında dört nitelikteki eşya için sistem uygulanmaz: ithalat miktar kısıtlamasına tabi olan; kota kapsamında tarife önlemleri uygulanan; tarım politikası çerçevesinde ithalat veya ihracat lisansı ya da sertifikası ibrazını gerektiren; işlem görmüş ürün için ihracat iadesi veya vergisi mevcut olan eşya. Anti-damping vergisine tabi olmak bu sayılanlar arasında yer almaz. Anti-damping vergisi Dahilde İşleme Rejimi Tebliği'nde indirimli teminatın uygulanmayacağı vergi olarak geçer, geri ödeme sistemini engelleyen hâl olarak geçmez. Sayılanlar sınırlıdır; ticaret politikasıyla ilgili göründüğü için akla yatkın gelen unsur bunlara eklenemez. Bu nedenle doğru cevap 'Anti-damping vergisine tabi olan eşya' seçeneğidir. (MD GK 117)",
kanit=F + " | Geri ödeme sisteminden her eşya yararlanabilir. Ancak, serbest dolaşıma giriş beyannamesinin tescili sırasında || " + F + " | İthalat miktar kısıtlamasına tabi olan || " + F + " | Kota kapsamında tarife önlemleri uygulanan || " + F + " | Tarım politikası çerçevesinde ithalat veya ihracat lisansı veya sertifikası ibrazını gerektiren || " + F + " | İşlem görmüş ürün için ihracat iadesi veya vergisi mevcut, eşya için geri ödeme sistemi uygulanmaz || " + F + " | sadece anti-damping ve sübvansiyon vergisine indirimli teminat uygulanmaz",
yuva=["GK 117/1-a: ithalat miktar kısıtlaması (listede)",
      "GK 117/1-b: kota kapsamında tarife önlemleri (listede)",
      "GK 117/1-c: tarım politikası lisans veya sertifikası (listede)",
      "GK 117/1-d: ihracat iadesi veya vergisi (listede)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 18 — GK 121: geri ödeme talebine dayanak rejimler
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="KAPSAM_DIŞI",
z="Z",
madde="4458 sayılı Gümrük Kanunu md. 121",
cek="Geri ödeme talebi için ürünün ihracı, serbest bölgeye konulması ya da transit, antrepo, geçici ithalat veya şartlı muafiyetli DİR'e tabi tutulması belgelendirilir.",
kok=["4458 sayılı Gümrük Kanunu'na göre izin hak sahibi, geri ödeme sistemi çerçevesinde serbest dolaşıma giren ithal eşyasından elde edilmiş işlem görmüş ürünlerin daha sonra yeniden ihraç edilmek üzere aşağıdaki rejimlerden hangisine tabi tutulduğunu belgelendirerek ithalat vergilerinin geri verilmesini veya kaldırılmasını isteyemez?"],
d="Gümrük kontrolü altında işleme rejimi",
c=["Transit rejimi",
   "Gümrük antrepo rejimi",
   "Geçici ithalat rejimi",
   "Şartlı muafiyet sistemine tabi dahilde işleme rejimi"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre geri ödeme sisteminde izin hak sahibi, serbest dolaşıma giren ithal eşyasından elde edilen işlem görmüş ürünlerin veya değişmemiş eşyanın üç durumdan birinde olduğunu belgelendirerek ithalat vergilerinin geri verilmesini veya kaldırılmasını isteyebilir. Bunlar ihraç edilmesi, serbest bölgeye konulması ve daha sonra yeniden ihraç edilmek üzere belirli rejimlere tabi tutulmasıdır. Bu rejimler transit rejimi, gümrük antrepo rejimi, geçici ithalat rejimi ve şartlı muafiyet sistemine tabi dahilde işleme rejimidir. Gümrük kontrolü altında işleme rejimi burada sayılmamıştır. En güçlü tuzak, gümrük kontrolü altında işleme rejiminin Kanunda şartlı muafiyet düzenlemeleri arasında yer almasıdır. Bu yüzden öteki rejimlerle birlikte düşünülmesi kolaydır, ancak geri ödeme talebine dayanak rejimler arasında değildir. Bu nedenle doğru cevap 'Gümrük kontrolü altında işleme rejimi' seçeneğidir. (MD GK 121; GK 79)",
kanit=F + " | Daha sonra yeniden ihraç edilmek üzere transit rejimi, gümrük antrepo rejimi, geçici ithalat rejimi veya şartlı muafiyet sistemine tabi dahilde işleme rejimine tabi tutulduğunu || " + F + " | Belgelendirmek ve rejimin uygulanmasına ilişkin diğer tüm şartlara uyulmuş olmak kaydıyla, ithalat vergilerinin geri verilmesini veya kaldırılmasını isteyebilir || 19-ŞARTLI M VE E.E.G.R.txt | - Gümrük kontrolü altında işleme",
yuva=["GK 121/1-b: transit rejimi (listede)",
      "GK 121/1-b: gümrük antrepo rejimi (listede)",
      "GK 121/1-b: geçici ithalat rejimi (listede)",
      "GK 121/1-b: şartlı muafiyet sistemine tabi DİR (listede)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "KOMŞU"],
duzey=["AYIRT"],
profil=[3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 19 — Tebliğ 38/12: müeyyideli kapatmaya itiraz (süre + makam + başlangıç)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="SÜRE",
z="O",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 37, 38",
cek="Belge sahibi, müeyyideli kapatmaya tebliğ tarihinden itibaren bir ay içinde Bakanlığa (İhracat Genel Müdürlüğü) yazılı itiraz eder; izinde Gümrük Kanunu itiraz yolu.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre dahilde işleme izin belgesi sahibi firmalar, kendilerine tebliğ edilen taahhüt hesabının müeyyideli kapatılması işlemine karşı hangi süre içinde ve hangi makama itiraz edebilir?"],
d="Tebliğ tarihinden itibaren bir ay içinde Bakanlığa (İhracat Genel Müdürlüğü) yazılı olarak",
c=["Tebliğ tarihinden itibaren üç ay içinde Bakanlığa (İhracat Genel Müdürlüğü) yazılı olarak",
   "Belge süresi sonundan itibaren bir ay içinde Bakanlığa (İhracat Genel Müdürlüğü) yazılı olarak",
   "Tebliğ tarihinden itibaren bir ay içinde ilgili bölge müdürlüğüne yazılı olarak",
   "Tebliğ tarihinden itibaren bir ay içinde ihracatçı birliği genel sekreterliğine yazılı olarak"],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği'ne göre dahilde işleme izin belgesi sahibi firmalar, kendilerine tebliğ edilen taahhüt hesabının müeyyideli kapatılması işlemine karşı tebliğ tarihinden itibaren bir ay içinde Bakanlığa (İhracat Genel Müdürlüğü) yazılı olarak itiraz edebilir. İzinlere ilişkin müeyyideli kapatmalarda ise Gümrük Kanunu'ndaki itiraz yoluna başvurulur. Süre, belge süresi sonundan değil, müeyyideli kapatma işleminin tebliğ tarihinden başlar. Belge süresi sonundan itibaren işleyen süre üç aydır ve kapatma için bilgi ve belgelerin sunulmasına ilişkindir. Bölge müdürlüğü, itiraz haklı bulunduğunda izinler için kapatma işlemini geri alan mercidir. İhracatçı birlikleri genel sekreterlikleri ise telafi edici vergi tablosunu kontrol eder. Bu nedenle doğru cevap 'Tebliğ tarihinden itibaren bir ay içinde Bakanlığa (İhracat Genel Müdürlüğü) yazılı olarak' seçeneğidir. (MD Tebliğ 37, 38)",
kanit=F + " | kendilerine tebliğ edilen taahhüt hesabının müeyyideli kapatılması işlemine karşı tebliğ tarihinden itibaren 1 (bir) ay içerisinde Bakanlığa (İhracat Genel Müdürlüğü) yazılı olarak itiraz edebilirler || " + F + " | Dahilde işleme izinlerine ilişkin müeyyideli kapatma işlemlerine ise, 4458 sayılı Gümrük Kanununun 242 nci maddesi uyarınca itiraz yoluna başvurulabilir || " + F + " | taahhüt kapatma işlemi belge için İhracat Genel Müdürlüğü, izin için ilgili Bölge Müdürlüğünce geri alınarak || " + F + " | en geç belge süresi sonundan itibaren üç ay içerisinde Ek-3'te belirtilen bilgi ve belgeleri",
yuva=["Tebliğ 37/1-a: belge süresi sonundan itibaren üç ay (kapatma müracaatı)",
      "Tebliğ 37/1-a: belge süresi sonu kapatma müracaatının başlangıcıdır",
      "Tebliğ 38/12: itiraz haklıysa izin kapatmasını Bölge Müdürlüğü geri alır",
      "Tebliğ 38/5: ihracatçı birlikleri telafi edici vergi tablosunu kontrol eder"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "MAKAM", "YAKIN-SAYI"],
duzey=["AYIRT"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 20 — Tebliğ 45/5: süre bitiminden sonra ihracat (vaka)
dict(
konu="Dahilde İşleme Rejimi", blok="SB31",
kalip="MÜEYYİDE",
z="Z",
madde="Dahilde İşleme Rejimi Tebliği (İhracat: 2006/12) md. 45",
cek="Süre bitimini takiben bir ayda tamamlanan işlem belge kapsamında sayılır, usulsüzlük cezasının iki katı; iki ayda tamamlananda dört katı alınır.",
kok=["Dahilde İşleme Rejimi Tebliği'ne (İhracat: 2006/12) göre dahilde işleme tedbirlerine uyulmaması hâlinde yapılacak işlemler çerçevesinde aşağıdaki olayı değerlendiriniz:",
     "- (T) firmasının dahilde işleme izin belgesinin süresi 31 Mayıs 2026 tarihinde bitmiştir.",
     "- Belge kapsamında Türkiye gümrük bölgesine getirilen ithal eşyasının bir kısmından elde edilen işlem görmüş ürünler, belge süresi içinde ihraç edilememiştir.",
     "- Bu ürünlere ilişkin ihracat beyannamesi 15 Temmuz 2026 tarihinde tescil edilmiş ve ihracat aynı gün gerçekleşmiştir.",
     "Buna göre bu ihracat hakkında aşağıdakilerden hangisi uygulanır?"],
d="İhracat belge kapsamında değerlendirilir; ancak usulsüzlük cezasının dört katı para cezası tahsil edilir.",
c=["İhracat belge kapsamında değerlendirilir; ancak usulsüzlük cezasının iki katı para cezası tahsil edilir.",
   "İhracat belge kapsamında değerlendirilmez; ithalat esnasında alınmayan vergi tahsil edilir ve ayrıca Gümrük Kanunu çerçevesinde müeyyide uygulanır.",
   "İhracat belge kapsamında değerlendirilir ve firmaya herhangi bir para cezası uygulanmaz.",
   "İhracat belge kapsamında değerlendirilir; ancak firma adına düzenlenen belgelerde altı ay süreyle indirimli teminat uygulanmaz."],
sirali=False,
g="Dahilde İşleme Rejimi Tebliği'ne göre belge kapsamında getirilen eşya için rejimin gerektirdiği işlemler, ihracat veya gümrükçe onaylanmış işlem ya da kullanım, belge süresinin bitimini takiben bir ay içinde tamamlanırsa belge kapsamında değerlendirilir. Bu durumda usulsüzlük cezasının iki katı para cezası tahsil edilir. İşlem iki ay içinde tamamlanırsa yine belge kapsamında değerlendirilir, ancak usulsüzlük cezasının dört katı para cezası tahsil edilir. Olayda süre 31 Mayıs 2026'da bitmiştir. Bir aylık dönem 30 Haziran 2026'da, iki aylık dönem 31 Temmuz 2026'da sona erer. 15 Temmuz 2026'daki ihracat ikinci aya düştüğü için dört kat uygulanır. Vakadaki istisna bu tolerans hükmüdür: süre aşıldı diye ithalatta alınmayan verginin tahsili ve Gümrük Kanunu'na göre müeyyide uygulanması yoluna gidilmez. İndirimli teminatın altı ay uygulanmaması ise şartlara uyulmaması veya döviz kullanım oranının aşılması gibi başka ihlallerin müeyyidesidir. Bu nedenle doğru cevap 'İhracat belge kapsamında değerlendirilir; ancak usulsüzlük cezasının dört katı para cezası tahsil edilir.' seçeneğidir. (MD Tebliğ 45)",
kanit=F + " | belge/izin süresinin bitimini takiben 2 (iki) ay içerisinde rejimin gerektirdiği işlemlerin bitirilmesi, ihracı veya gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulması halinde, bu işlemler belge/izin kapsamında değerlendirilir … usulsüzlük cezasının dört katı para cezası tahsil edilir || " + F + " | belge/izin süresinin bitimini takiben 1 (bir) ay içerisinde rejimin gerektirdiği işlemlerin bitirilmesi … usulsüzlük cezasının iki katı para cezası tahsil edilir || " + F + " | ithal tarihi itibarıyla 4458 sayılı Gümrük Kanunu ile 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanun hükümlerine göre tahsil edilir || " + F + " | Bakanlıkça uygun görüldüğü tarihten itibaren 6 (altı) ay süreyle indirimli teminat uygulanmaz",
yuva=["Tebliğ 45/5 birinci cümle: bir ay içinde tamamlanırsa iki kat",
      "Tebliğ 45/1-a ve son paragraf: ihracatı gerçekleştirilmeyen eşyada vergi tahsili ve müeyyide",
      "Tebliğ 38/2: süresinde tescil edilen beyanname belge kapsamında sayılır (burada tescil süre sonrası)",
      "Tebliğ 45/4: şartlara uyulmaması ve döviz kullanım oranı aşımında altı ay indirimli teminat yok"],
yakinlik="ÇIKARIM",
tuzak=["SAYI", "İSTİSNA", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[2],
olumsuz=False, vaka=True, baslangic=False,
eksen=5, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

]
