# Soru Bankası — Bölüm 39: Posta ve Hızlı Kargo (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
T = "40-posta ve hızlı kargo.txt"
TM = "2-TEMSİL.txt"
KK = '2009/15481 sayılı "4458 sayılı Gümrük Kanununun Bazı Maddelerinin Uygulanması Hakkında Karar"'
TB = "Posta ve Hızlı Kargo Yoluyla Taşınan Eşyanın Gümrük İşlemlerine İlişkin Tebliğ (Seri No: 1)"

Q = [

# ---------------- 1. KANUN: POSTA EŞYASININ KONTROLÜ (çıkmış 2021/59, olumsuz) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="YANLIŞ",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 173",
cek="Posta eşyası, çantaları ve kolileri gümrük kontrolüne ve muayenesine tabidir; içinde eşya bulunmadığı anlaşılan mektuplar bu hükmün dışındadır.",
kok=["4458 sayılı Gümrük Kanunu'na göre posta yoluyla taşınan eşyanın gümrük kontrolü ve muayenesine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="İçinde eşya bulunmadığı anlaşılan mektuplar da gümrük idaresinin kontrolüne ve muayenesine tabidir.",
c=["Posta yoluyla Türkiye'ye iade edilen eşya da gümrük idaresinin kontrolüne ve muayenesine tabidir.",
   "Türkiye Gümrük Bölgesine gelen bütün posta çantaları ve koliler ilk giriş kapısından itibaren gümrük gözetimi altında posta idarelerine sevk edilir.",
   "Gönderilecek posta çantaları ve kolilerin ihracına, gümrükçe konulan mühür veya işaretlerin varlığı ve kapların sağlamlığı tespit edildikten sonra çıkış gümrüğünden izin verilir.",
   "Posta gönderilerine ait gümrük kontrolünün kapsamı ve yöntemi, Ulaştırma Bakanlığı ile Bakanlıkça müştereken hazırlanacak bir yönetmelikle belirlenir."],
sirali=False,
g="Gümrük Kanunu'na göre posta yoluyla Türkiye Gümrük Bölgesine gelen, Türkiye'den gönderilen veya Türkiye'ye iade edilen eşya, posta çantaları ve koliler gümrük idaresinin kontrolüne ve muayenesine tabidir; ancak içinde eşya bulunmadığı anlaşılan mektuplar bu hükmün dışındadır. Yanlış ifade bu istisnayı tersine çevirerek eşya içermeyen mektupları da kontrole tabi göstermektedir. Gelen posta çantaları ve kolilerin ilk giriş kapısından itibaren gümrük gözetimi altında posta idarelerine sevk edilip orada muayene edilmesi, gönderilecek çanta ve kolilerin daha önce gümrükçe kontrol edildiğine ilişkin mühür veya işaretler ile kapların sağlamlığı tespit edildikten sonra çıkış gümrüğünden ihracına izin verilmesi ve kontrolün kapsam ve yönteminin Ulaştırma Bakanlığı ile Bakanlıkça müştereken hazırlanacak yönetmelikle belirlenmesi Kanun'daki doğru hükümlerdir. Kontrole tabi olanlar arasında Türkiye'ye iade edilen eşyanın da sayılması en sık gözden kaçan ayrıntıdır. Bu nedenle doğru cevap 'İçinde eşya bulunmadığı anlaşılan mektuplar da gümrük idaresinin kontrolüne ve muayenesine tabidir.' seçeneğidir. (MD GK 173)",
kanit=T + " | İçinde eşya bulunmadığı anlaşılan mektuplar bu hükmün dışındadır. || " + T + " | Türkiye'den gönderilen veya Türkiye'ye iade edilen eşya, posta çantaları ve koliler gümrük idaresinin kontrolüne || " + T + " | ilk giriş kapısından itibaren gümrük gözetimi altında posta idarelerine sevk edilir ve buralarda gümrük muayenesine tabi tutulur || " + T + " | mühür veya diğer işaretlerinin bulunup bulunmadığı ve kapların sağlamlığı tespit edildikten sonra çıkış gümrüğünden, ihracına izin verilir || " + T + " | Ulaştırma Bakanlığı ve Gümrük Müsteşarlığının bağlı olduğu Bakanlıkça müştereken hazırlanacak bir yönetmelikle belirlenir",
yuva=["Aynı maddenin birinci fıkrası: iade edilen eşya da kontrol ve muayeneye tabidir (doğru)",
      "Aynı maddenin ikinci fıkrası: gelen çanta ve koliler ilk giriş kapısından itibaren gözetim altında sevk edilir (doğru)",
      "Aynı maddenin üçüncü fıkrası: mühür-işaret ve kap sağlamlığı tespitiyle çıkış gümrüğünden ihraç (doğru)",
      "Aynı maddenin dördüncü fıkrası: kontrolün kapsam ve yöntemi müşterek yönetmelikle belirlenir (doğru)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "İSTİSNA"],
duzey=["TANIMA"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/59",
kapsamli=False,
),

# ---------------- 2. KANUN: POSTA EŞYASININ KONULACAĞI YER (ikiz eksen 17, ayna) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="DOĞRU",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 174",
cek="Posta yoluyla gelen veya giden eşya, posta idaresinin sorumluluğu ve gümrüğün gözetimi altında genel antrepo sayılan yerlere konulur; bekleme süresi uluslararası posta anlaşmalarına tabidir.",
kok=["4458 sayılı Gümrük Kanunu'na göre posta yoluyla Türkiye Gümrük Bölgesine gelen eşyanın konulacağı yerler ve bu yerlerdeki bekleme süresine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Eşya, genel antrepo sayılan yerlere posta idaresinin sorumluluğu ve gümrük idaresinin gözetimi altında konulur; bekleme süresi Türkiye'nin taraf olduğu uluslararası posta anlaşmaları hükümlerine tabidir.",
c=["Eşya, özel antrepo sayılan yerlere posta idaresinin sorumluluğu ve gümrük idaresinin gözetimi altında konulur; bekleme süresi Türkiye'nin taraf olduğu uluslararası posta anlaşmaları hükümlerine tabidir.",
   "Eşya, genel antrepo sayılan yerlere gümrük idaresinin sorumluluğu ve posta idaresinin gözetimi altında konulur; bekleme süresi Türkiye'nin taraf olduğu uluslararası posta anlaşmaları hükümlerine tabidir.",
   "Eşya, genel antrepo sayılan yerlere posta idaresinin sorumluluğu ve gümrük idaresinin gözetimi altında konulur; bekleme süresi antrepo beyannamesinin tescil tarihinden itibaren bir aydır.",
   "Eşya, genel antrepo sayılan yerlere posta idaresinin sorumluluğu ve gümrük idaresinin gözetimi altında konulur; bekleme süresi Ulaştırma Bakanlığı ile Bakanlıkça müştereken çıkarılan yönetmelikle belirlenir."],
sirali=False,
g="Gümrük Kanunu'na göre posta yoluyla Türkiye Gümrük Bölgesine gelen veya Gümrük Bölgesinden giden eşya, genel antrepo sayılan yerlere posta idaresinin sorumluluğu ve gümrük idaresinin gözetimi altında konulur; eşyanın buralarda bekleme süresi Türkiye'nin taraf olduğu uluslararası posta anlaşmaları hükümlerine tabidir. Sorumluluk posta idaresinde, gözetim gümrük idaresindedir; ikisinin yer değiştirdiği seçenek bu nedenle yanlıştır. Bu yerler özel antrepo değil genel antrepo sayılır. En güçlü çeldirici olan 'antrepo beyannamesinin tescil tarihinden itibaren bir ay' süresi, Gümrük Yönetmeliği'nde yalnızca posta yoluyla yurt dışına gönderilecek ticari eşya için öngörülmüştür; gelen eşyanın bekleme süresi uluslararası anlaşmalara bırakılmıştır. Ulaştırma Bakanlığı ile müştereken hazırlanacak yönetmelik ise posta gönderilerine ait gümrük kontrolünün kapsam ve yöntemini belirler, bekleme süresini değil. Bu nedenle doğru cevap 'Eşya, genel antrepo sayılan yerlere posta idaresinin sorumluluğu ve gümrük idaresinin gözetimi altında konulur; bekleme süresi Türkiye'nin taraf olduğu uluslararası posta anlaşmaları hükümlerine tabidir.' seçeneğidir. (MD GK 174, 173; GY 469)",
kanit=T + " | genel antrepo sayılan yerlere, posta idaresinin sorumluluğu ve gümrük idaresinin gözetimi altında konulur || " + T + " | Eşyanın buralarda bekleme süresi, Türkiye'nin taraf olduğu uluslararası posta anlaşmaları hükümlerine tabidir. || " + T + " | Eşya, buralarda antrepo beyannamesinin tescil tarihinden itibaren bir ay bekletilebilir.",
yuva=["Antrepo tipleri ekseni: posta idaresinin kolilere ayrılmış kapalı yerleri genel antrepo sayılır, özel antrepo değil (Kanun aynı madde; GY antrepo hükmü)",
      "Aynı madde: sorumluluk posta idaresinde, gözetim gümrük idaresindedir; roller yer değiştirilmiş",
      "Gümrük Yönetmeliği: posta yoluyla yurt dışına gönderilecek ticari eşyanın genel antrepoda bir ay bekletilmesi",
      "Kanunun bir önceki maddesi: kontrolün kapsam ve yöntemi Ulaştırma Bakanlığı ile müşterek yönetmelikle belirlenir"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "MAKAM", "TERİM"],
duzey=["AYIRT"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=17, ayna="posta-bekleme: gelen ↔ giden ticari eşya",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 3. YÖNETMELİK: GİDEN TİCARİ EŞYANIN BEKLEME SÜRESİ (ayna, başlangıç) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="SÜRE",
z="Z",
madde="Gümrük Yönetmeliği md. 469, 463, 462",
cek="Posta yoluyla yurt dışına gönderilecek ticari eşya genel antrepoda antrepo beyannamesinin tescil tarihinden itibaren bir ay bekletilebilir.",
kok=["Gümrük Yönetmeliği'ne göre posta yolu ile yurt dışına gönderilecek ticari eşyanın, gümrüğün gözetimi ve posta idaresinin sorumluluğu altındaki genel antrepolarda bekletilebileceği süre aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Antrepo beyannamesinin tescil tarihinden itibaren bir ay",
c=["Eşyanın posta idaresince kabul edildiği tarihten itibaren bir ay",
   "Gümrük beyannamesinin tescil tarihinden itibaren bir ay",
   "Antrepo beyannamesinin tescil tarihinden itibaren bir hafta",
   "Antrepo beyannamesinin tescil tarihinden itibaren üç ay"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre posta yolu ile yurt dışına gönderilecek ticari eşya, gümrüğün gözetimi ve posta idaresinin sorumluluğu altındaki genel antrepolara konulur ve buralarda antrepo beyannamesinin tescil tarihinden itibaren bir ay bekletilebilir. Sürenin başlangıcı, eşyanın posta idaresince kabul edildiği tarih ya da ticari eşyanın ihracat rejimi kapsamında verilen gümrük beyannamesinin tescil tarihi değil, antrepo beyannamesinin tescil tarihidir; başlangıç anını karıştıran aday en güçlü çeldiricilere yönelir. Bir hafta, posta idaresinin gümrük adına tahsil ettiği paraları gümrük veznesine ödemesi için öngörülen en geç süredir. Posta yoluyla gelen eşyanın bekleme süresi ise Kanun'a göre uluslararası posta anlaşmalarına tabidir; ayna soruda bu ayrım ölçülmüştür. Bu nedenle doğru cevap 'Antrepo beyannamesinin tescil tarihinden itibaren bir ay' seçeneğidir. (MD GY 469, 463, 462)",
kanit=T + " | Posta yolu ile yurt dışına gönderilecek ticari eşya, gümrüğün gözetimi ve posta idaresinin sorumluluğu altındaki genel antrepolara konulur. || " + T + " | Eşya, buralarda antrepo beyannamesinin tescil tarihinden itibaren bir ay bekletilebilir. || " + T + " | yurt dışına posta yolu ile gönderilecek ticari ve ticari olmayan eşya posta idaresi tarafından kabul edilir || " + T + " | Yurt dışına posta yoluyla gönderilecek ticari nitelikteki eşya ihracat rejimi kapsamında gümrük beyannamesi ile beyan olunur || " + T + " | Posta idaresi gümrük adına tahsil ettiği paraları en geç bir hafta içinde",
yuva=["Posta kolilerinin ihracat işlemleri: eşya posta idaresi tarafından kabul edilir (başlangıç anı karıştırılmış)",
      "Posta kolilerinin ihracat işlemleri: ticari eşya ihracat rejimi kapsamında gümrük beyannamesiyle beyan olunur (belge adı karıştırılmış)",
      "Posta idaresince tahsil olunacak vergiler: paralar en geç bir hafta içinde gümrük veznesine ödenir",
      "2022/9 sayılı Genelge: geri gönderilen cep telefonunda Kararda belirtilen 3 aylık süre"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "SAYI", "TERİM"],
duzey=["AYIRT"],
profil=[1, 2],
olumsuz=False, vaka=False, baslangic=True,
eksen=13, ayna="posta-bekleme: gelen ↔ giden ticari eşya",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 4. YÖNETMELİK: KOLİ LİSTELERİ (çıkmış 2021/65 komşusu, önermeli) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="ÖNERMELİ",
z="O",
madde="Gümrük Yönetmeliği md. 455, 456",
cek="Koli listeleri birikme beklenmeden düzenlenir, iki nüshası imza karşılığı gümrüğe verilir; gümrükçe sıra numarasına göre saklanır; sıra numarası yılbaşından teselsül eder.",
kok=["Gümrük Yönetmeliği'ne göre posta kolilerinin gümrüğe bildirilmesine mahsus listelere ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Posta idareleri, gelen kolilere ait listelerin bir nüshasını imza karşılığında gümrük idaresine verir.",
     "II. Listeler, alınan her posta için ayrı ayrı düzenlenebileceği gibi bir günde gelen bütün koliler için tek bir liste olarak da düzenlenebilir.",
     "III. Listeler, posta idaresi tarafından sıra numarasına göre saklanır.",
     "IV. Listelerde gösterilen sıra numarası her yılbaşından itibaren teselsül ettirilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve IV",
c=["Yalnız II", "I ve III", "I, II ve IV", "II, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre posta kolileri, gümrük işlemlerinin yapılacağı posta idarelerinde sıra numarası izleyen bir listeyle gümrüğe beyan olunur. Posta idareleri gelen kolilere ait listeleri vakit geçirmeden ve kolilerin birikmesini beklemeden düzenler ve iki nüshasını imza karşılığında gümrük idaresine verir; I'deki 'bir nüsha' bu nedenle yanlıştır. Listeler alınan her posta için ayrı ayrı düzenlenebileceği gibi bir günde gelen bütün koliler için tek liste olarak da düzenlenebilir (II doğru). Listeler posta idaresince değil gümrük idaresi tarafından sıra numarasına göre saklanır (III yanlış). Listelerde gösterilecek hususların ilki her yılbaşından itibaren teselsül ettirilen sıra numarasıdır (IV doğru). En güçlü çeldirici III'tür: listeyi düzenleyen posta idaresi olduğu için saklayanın da o olduğu sanılır. Bu nedenle doğru cevap 'II ve IV' seçeneğidir. (MD GY 455, 456)",
kanit=T + " | Posta idareleri, gelen kolilere ait listeleri, vakit geçirmeden ve kolilerin birikmesini beklemeden düzenler ve iki nüshasını imza karşılığında gümrük idaresine verir. || " + T + " | Bu listeler alınan her posta için ayrı ayrı düzenlenebileceği gibi bir günde gelen bütün koliler için tek bir liste de düzenlenebilir. || " + T + " | Bu listeler gümrük idaresi tarafından sıra numarasına göre saklanır. || " + T + " | Her yılbaşından itibaren teselsül ettirilen sıra numarası",
yuva=["Yalnız II: IV'teki sıra numarasının her yılbaşından teselsül ettirildiğini bilmeyen aday",
      "I ve III: nüsha sayısını ve listeleri saklayan idareyi birlikte karıştıran aday",
      "I, II ve IV: 'iki nüsha' yerine 'bir nüsha'yı doğru sanan aday (aynı maddenin nüsha sayısı)",
      "II, III ve IV: listeleri saklayan idareyi posta idaresi sanan aday (aynı maddenin saklama hükmü)"],
yakinlik="BİREBİR",
tuzak=["SAYI", "MAKAM"],
duzey=["AYIRT"],
profil=[1, 2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/65",
kapsamli=False,
),

# ---------------- 5. YÖNETMELİK: BAŞKA İDAREYE SEVK (çıkmış 2021/67) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="DOĞRU",
z="O",
madde="Gümrük Yönetmeliği md. 468",
cek="Mektup postası dışındaki eşya transitle sevk edilir; her araç için ayrı transit beyannamesi; çuvallar mühürlüyse taşıt mühürlenmez; aynı ilde CN-38/CN-41 bordrosu mümkündür.",
kok=["Gümrük Yönetmeliği'ne göre mektup postası dışında kalan posta eşyasının başka bir gümrük idaresine sevk edilmesine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Her araç için ayrı bir transit beyannamesi düzenlenir; posta çuvalları mühürlü ise ayrıca taşıt aracı mühürlenmez.",
c=["Her araç için ayrı bir transit beyannamesi düzenlenir; posta çuvalları mühürlü olsa bile taşıt aracının ayrıca mühürlenmesi zorunludur.",
   "Eşyanın aynı il içerisindeki havalimanından Posta İşleme Merkezine Posta Teslim Bordrosu ile sevkinde sorumluluk gümrük idaresine aittir.",
   "Posta Teslim Bordrosu ile sevk, farklı illerde bulunan havalimanı ile Posta İşleme Merkezi arasında da yapılabilir.",
   "Eşya, transit rejimi yerine antrepo rejimi hükümleri çerçevesinde posta idaresinin sorumluluğu altında sevk edilir."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre mektup postası dışında kalan eşyanın başka bir gümrük idaresine sevk edilmek istenmesi hâlinde eşya transit rejimi hükümleri çerçevesinde sevk edilir. Bu durumda her araç için ayrı bir transit beyannamesi düzenlenir; posta çuvalları mühürlü ise ayrıca taşıt aracı mühürlenmez. Eşyanın aynı il içerisindeki havalimanından Posta İşleme Merkezine Posta Teslim Bordrosu (CN-38 veya CN-41) ile posta idaresinin sorumluluğu altında sevk edilmesi de mümkündür; bu kolaylık aynı il ile sınırlıdır ve sorumluluk gümrük idaresine değil posta idaresine aittir. En güçlü çeldirici taşıt mühürleme kuralını tersine çeviren seçenektir; mühürlü posta çuvalı taşıtın ayrıca mühürlenmesini gereksiz kılar. Sevk antrepo rejimiyle değil transit rejimiyle yapılır; genel antrepo kavramı posta eşyasının bekletildiği yerlere ilişkindir. Bu nedenle doğru cevap 'Her araç için ayrı bir transit beyannamesi düzenlenir; posta çuvalları mühürlü ise ayrıca taşıt aracı mühürlenmez.' seçeneğidir. (MD GY 468)",
kanit=T + " | Mektup postası dışında kalan eşyanın başka bir gümrük idaresine sevk edilmek istenilmesi halinde, eşya transit rejimi hükümleri çerçevesinde sevk edilir. || " + T + " | Bu durumda, her araç için ayrı bir transit beyannamesi düzenlenir. Posta çuvalları mühürlü ise ayrıca taşıt aracı mühürlenmez. || " + T + " | Söz konusu eşyanın aynı il içerisindeki havalimanından Posta İşleme Merkezine Posta Teslim Bordrosu (CN-38 veya CN-41) ile posta idaresinin sorumluluğu altında sevk edilmesi mümkündür.",
yuva=["Aynı fıkra: posta çuvalları mühürlü ise taşıt aracı ayrıca mühürlenmez (tersine çevrilmiş)",
      "Aynı maddenin ikinci fıkrası: Posta Teslim Bordrosu ile sevk posta idaresinin sorumluluğu altındadır",
      "Aynı maddenin ikinci fıkrası: bordro ile sevk aynı il içerisindeki havalimanından Posta İşleme Merkezine yapılır",
      "Gümrük Kanunu ve Yönetmelik: posta eşyasının konulduğu yerler genel antrepo sayılır (bekletme hükmü, sevk değil)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "MAKAM", "ŞART", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/67",
kapsamli=False,
),

# ---------------- 6. YÖNETMELİK: POSTA EŞYASININ BEYANI (eşleştirme, olumsuz) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="EŞLEŞTİRME",
z="O",
madde="Gümrük Yönetmeliği md. 459",
cek="Ticari olmayan posta eşyasında DeD beyannamedir; DeD'siz ticari olmayan kolide sözlü beyan formu; ticari eşyada gümrük beyannamesi; DİR, Gİ, geri gelende ilgili rejim.",
kok=["Gümrük Yönetmeliği'ne göre posta yolu ile gelen eşya ile bu eşyanın beyanında kullanılacak belge veya uygulanacak usul arasındaki eşleştirmelerden hangisi yanlıştır?"],
d="Dahilde işleme, geçici ithalat veya geri gelen eşya rejiminden faydalanmak üzere gelen eşya – Sözlü beyan formu düzenlenmesi",
c=["Ticari nitelikte olmayan hediyelik, numunelik, zat ve aile ihtiyaçlarını karşılayan eşya – Déclaration en Douane'ın beyanname olarak kabul edilmesi",
   "Déclaration en Douane olmadan gelen ve ticari nitelik arz etmeyen eşya içeren koliler – Sözlü beyan formu düzenlenmesi",
   "Ticari nitelik arz eden eşya – Gümrük beyannamesi düzenlenmesi",
   "Gazete, kitap, broşür ile periyodik dergiler – Gümrük işlemlerinin Müsteşarlıkça belirlenmesi"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre posta yolu ile gelen ve ticari nitelikte olmayan hediyelik, numunelik, zat ve aile ihtiyaçlarını karşılayan ve benzeri eşya için Déclaration en Douane'lar gümrük idaresince beyanname olarak kabul edilir. Déclaration en Douane olmadan gelen ve ticari nitelik arz etmeyen eşya içeren koliler için sözlü beyan formu, ticari nitelik arz eden eşya için gümrük beyannamesi düzenlenir. Gazete, kitap, broşür ile periyodik dergiler için yapılacak gümrük işlemleri Müsteşarlıkça belirlenir. Dahilde işleme, geçici ithalat ve geri gelen eşya rejiminden faydalanmak üzere posta yolu ile gelen eşya için ise sözlü beyan formu değil, ilgili rejim hükümleri uygulanarak işlem yapılır. Sözlü beyan formu yalnızca Déclaration en Douane'sız gelen ticari olmayan koliler içindir; yanlış eşleştirme bu komşu hükümden taşınmıştır. Bu nedenle doğru cevap 'Dahilde işleme, geçici ithalat veya geri gelen eşya rejiminden faydalanmak üzere gelen eşya – Sözlü beyan formu düzenlenmesi' seçeneğidir. (MD GY 459)",
kanit=T + " | Posta yolu ile gelen ve ticari nitelikte olmayan hediyelik, numunelik, zat ve aile ihtiyaçlarını karşılayan ve benzeri eşya için, Déclaration en Douane'lar gümrük idaresince beyanname olarak kabul edilir. || " + T + " | Déclaration en Douane olmadan gelen ve ticari nitelik arz etmeyen eşya içeren koliler için sözlü beyan formu düzenlenir. || " + T + " | Ticari nitelik arz eden eşya için gümrük beyannamesi düzenlenir. || " + T + " | Ancak gazete, kitap, broşür ile periyodik dergiler için yapılacak gümrük işlemleri Müsteşarlıkça belirlenir. || " + T + " | Keza dahilde işleme, geçici ithalat ve geri gelen eşya rejiminden faydalanmak üzere posta yolu ile gelen eşya için ilgili rejim hükümleri uygulanarak işlem yapılır.",
yuva=["Aynı maddenin birinci fıkrası: ticari olmayan hediyelik ve benzeri eşyada Déclaration en Douane beyannamedir (doğru eşleşme)",
      "Aynı maddenin ikinci fıkrası: Déclaration en Douane'sız ticari olmayan kolide sözlü beyan formu (doğru eşleşme)",
      "Aynı maddenin üçüncü fıkrası: ticari eşyada gümrük beyannamesi (doğru eşleşme)",
      "Aynı maddenin dördüncü fıkrası: gazete, kitap, broşür, periyodik dergilerde işlemler Müsteşarlıkça belirlenir (doğru eşleşme)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 7. KANUN + YÖNETMELİK: BEYANNAME HÜKMÜNDE BELGE VE CEZA (önermeli) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="ÖNERMELİ",
z="Z",
madde="4458 sayılı Gümrük Kanunu md. 175; Gümrük Yönetmeliği md. 474, 475",
cek="Ticari olmayan posta eşyasında uluslararası belgeler beyanname hükmündedir; DeD farklılıklarına ceza aranmaz; ticari eşyada ithalatta Kanun cezası, ihracatta gümrük veya kaçakçılık mevzuatı uygulanır.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'nin posta yoluyla gelen ve gönderilen eşyanın beyanı ile beyandaki farklılıklara ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Ticari mahiyette olmayan eşyanın gümrük idaresine sunulması sırasında ibraz edilen uluslararası kabul görmüş belgeler beyanname hükmünde olup ayrıca beyanname aranmaz.",
     "II. Posta yolu ile gönderilen ticari nitelikte olmayan eşyaya ilişkin Déclaration en Douane'larda kayıtlı bilgilere nazaran tespit edilen farklılıklardan dolayı ceza aranmaz.",
     "III. İhracatta ticari eşyanın beyanı ile muayenesi arasında farklılık bulunması hâlinde, duruma bakılmaksızın yalnızca kaçakçılıkla mücadele mevzuatı uyarınca işlem yapılır.",
     "IV. Posta yolu ile gelen ticari nitelikteki eşyaya ilişkin beyanın kontrolü sonucunda tespit edilen fark ve aykırılıklardan dolayı da ceza aranmaz.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve II",
c=["Yalnız II", "I ve IV", "I, II ve III", "I, II, III ve IV"],
sirali=False,
g="Gümrük Kanunu'na göre ticari mahiyette olmayan posta eşyasının gümrük idaresine sunulması sırasında ibraz edilen uluslararası kabul görmüş belgeler beyanname hükmündedir ve ayrıca beyanname aranmaz (I doğru). Gümrük Yönetmeliği'ne göre posta yolu ile gelen veya gönderilen ticari nitelikte olmayan eşyaya ilişkin Déclaration en Douane'larda kayıtlı bilgilere nazaran tespit edilen farklılıklardan dolayı ceza aranmaz (II doğru). İhracatta ticari eşyanın beyanı ile muayenesi arasında farklılık bulunursa duruma göre gümrük veya kaçakçılıkla mücadele mevzuatı uyarınca işlem yapılır; 'yalnızca kaçakçılık' denmesi hükmü mutlaklaştırır (III yanlış). Posta yolu ile gelen ticari nitelikteki eşyanın beyanının kontrolünde tespit edilen fark ve aykırılıklar için Gümrük Kanunu'nun ilgili ceza hükmüne göre işlem yapılır; ceza aranmaması yalnızca ticari olmayan eşyaya özgüdür (IV yanlış). Bu nedenle doğru cevap 'I ve II' seçeneğidir. (MD GK 175; GY 474, 475)",
kanit=T + " | Ticari mahiyette olmayan eşyanın gümrük idaresine sunulması sırasında, ibraz edilen uluslararası kabul görmüş belgeler beyanname hükmünde olup, ayrıca beyanname aranmaz. || " + T + " | Posta yolu ile gönderilen ticari nitelikte olmayan eşyaya ilişkin Déclaration en Douane'larda kayıtlı bilgilere nazaran tespit edilen farklılıklardan dolayı ceza aranmaz. || " + T + " | İhracatta ticari eşyanın beyanı ile muayenesi arasında farklılık bulunması halinde duruma göre gümrük veya kaçakçılıkla mücadele mevzuatı uyarınca işlem yapılır. || " + T + " | Ticari nitelikte olan eşyaya ilişkin beyanın kontrolü sonucunda, tespit edilecek fark ve aykırılıklardan dolayı, Kanunun 234 üncü maddesi hükümlerine göre işlem yapılır.",
yuva=["Yalnız II: Kanundaki uluslararası belgelerin beyanname hükmünde olduğunu bilmeyen aday",
      "I ve IV: ithalatta ticari eşyada Kanun hükümlerine göre işlem yapıldığını bilmeyen aday (Yönetmelik serbest dolaşımdaki cezalar hükmünün ikinci fıkrası)",
      "I, II ve III: 'duruma göre gümrük veya kaçakçılık mevzuatı' ifadesini 'yalnızca kaçakçılık' sanan aday (ihracatta ceza hükmünün ikinci fıkrası)",
      "I, II, III ve IV: ticari ve ticari olmayan eşya ayrımını gözden kaçıran aday"],
yakinlik="BİREBİR",
tuzak=["MUTLAK", "KOMŞU", "TERSİNE"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 8. TEBLİĞ: DOKÜMAN TANIMI (tanımdan ad) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="TANIM",
z="K",
madde="Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 3",
cek="Kişisel yazılı mesaj, kartpostal ve ticari değer taşımayan basılı materyal şeklindeki gönderiler Tebliğde doküman olarak tanımlanır.",
kok=[TB + "'e göre \"bir kişiden diğer bir kişiye gönderilen kişisel yazılı mesaj, kartpostal ile herhangi bir ticari değer taşımayan basılı materyal şeklindeki gönderiler\" şeklinde tanımlanan kavram aşağıdakilerden hangisidir?"],
d="Doküman",
c=["Gönderi", "Posta haberleşme gönderisi", "Mektup postası", "Basılı yayın"],
sirali=False,
g="Posta ve Hızlı Kargo Tebliği'nde bir kişiden diğer bir kişiye gönderilen kişisel yazılı mesaj, kartpostal ile herhangi bir ticari değer taşımayan basılı materyal şeklindeki gönderiler 'doküman' olarak tanımlanmıştır. Aynı maddede tanımlanan 'gönderi' ise içerisinde ticari veya gayri ticari nitelikte eşya bulunan paket, koli, poşet ve benzerini ifade eder; tanım cümlesinde 'gönderiler' kelimesi geçtiği için en güçlü çeldirici budur. 'Posta haberleşme gönderisi' ve 'mektup postası' Gümrük Yönetmeliği'nin posta gümrük işlemlerine ilişkin hükümlerinde geçen kavramlardır; 'basılı yayın' ise kişisel kullanıma mahsus kitap veya benzeri basılı yayın için kullanılan ifadedir. Dokümanlar tasnifte belge kontrolüne tabi ayrı bir kategori oluşturur ve beyanda tek bir kalemde topluca beyan edilir. Bu nedenle doğru cevap 'Doküman' seçeneğidir. (MD Tebliğ 3, 9, 10)",
kanit=T + " | Doküman: Bir kişiden diğer bir kişiye gönderilen kişisel yazılı mesaj, kartpostal ile herhangi bir ticari değer taşımayan basılı materyal şeklindeki gönderileri || " + T + " | Gönderi: Bir kişiden diğer bir kişiye gönderilen, içerisinde ticari veya gayri ticari nitelikte eşya bulunan paket, koli, poşet ve benzerini || " + T + " | Doküman kapsamına giren gönderiler, tek bir kalemde topluca beyan edilir.",
yuva=["Aynı tanımlar maddesi: gönderi, içerisinde ticari veya gayri ticari eşya bulunan paket, koli, poşet ve benzeri",
      "Gümrük Yönetmeliği posta haberleşme gönderileri hükmü: yeşil etiketli mektuplar, küçük paketler ve basılmış kâğıtlar",
      "Gümrük Yönetmeliği başka idareye sevk hükmü: mektup postası dışında kalan eşya",
      "2022/9 sayılı Genelge: kişisel kullanıma mahsus kitap veya benzeri basılı yayın"],
yakinlik="BİREBİR",
tuzak=["TERİM"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 9. KANUN + TEBLİĞ: DOLAYLI TEMSİL YETKİSİ (çıkmış 2021/90, ikiz eksen 12) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="YETKİ",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 225; Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 1, 3, 6, 7",
cek="Posta ve hızlı kargo eşyasının miktar ve değerini Cumhurbaşkanı belirler; posta idaresi ve kargo şirketleri dolaylı temsilcidir; yetkiyi Bakanlık verir, vekâletname aranmaz.",
kok=["4458 sayılı Gümrük Kanunu ile " + TB + "'e göre posta idaresi ve hızlı kargo taşımacılığı yapan şirketlerin temsil yetkisine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Posta idaresi veya hızlı kargo şirketlerinin dolaylı temsilci olarak işlemlerini takip edip sonuçlandırabileceği eşyanın miktarı ve değeri Cumhurbaşkanınca belirlenir.",
c=["Posta idaresi ve hızlı kargo şirketleri, bu eşyanın gümrük işlemlerini alıcı veya gönderici adına ve hesabına doğrudan temsilci olarak takip eder.",
   "Operatörlerin yetki kapsamındaki işlemlerde alıcıyı veya göndericiyi temsil edebilmesi için vekâletname ibrazı aranır.",
   "Operatör yetkisi, başvurunun yapıldığı Gümrük ve Dış Ticaret Bölge Müdürlüğünce verilir.",
   "Operatör, hızlı kargo kapsamındaki gönderilerin gümrük işlemlerini dolaylı temsil yoluyla yapmaya yetkili gerçek ve tüzel kişileri ifade eder."],
sirali=False,
g="Gümrük Kanunu'na göre posta yolu ve hızlı kargo taşımacılığı kapsamında gelen ya da gönderilen, miktarı ve değeri Cumhurbaşkanınca belirlenecek eşyanın gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulması faaliyetlerinin takip edilip sonuçlandırılmasında posta idaresi ya da hızlı kargo taşımacılığı yapan şirketler dolaylı temsilci olarak yetkili kılınabilir. Tebliğ de bu yetkiyi dolaylı temsil yetkisi olarak düzenler; 'doğrudan temsil' seçeneği iki temsil türünü karıştırır. Operatörler yetki kapsamındaki işlemlerde alıcıyı veya göndericiyi ayrıca başka bir işleme gerek kalmadan temsil eder ve vekâletname ibrazı aranmaz. Başvuru Gümrük ve Dış Ticaret Bölge Müdürlüğüne yapılsa da koşulların varlığı tespit edilince yetkiyi Bakanlık verir; en güçlü çeldirici budur. Operatör tanımı yalnızca tüzel kişileri kapsar. Bu nedenle doğru cevap 'Posta idaresi veya hızlı kargo şirketlerinin dolaylı temsilci olarak işlemlerini takip edip sonuçlandırabileceği eşyanın miktarı ve değeri Cumhurbaşkanınca belirlenir.' seçeneğidir. (MD GK 225; Tebliğ 1, 3, 6, 7)",
kanit=TM + " | Posta yolu ve hızlı kargo taşımacılığı kapsamında gelen ya da gönderilen, miktarı ve değeri Cumhurbaşkanınca belirlenecek eşyanın gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulması faaliyetlerinin takip edilip sonuçlandırılmasında, posta idaresi ya da hızlı kargo taşımacılığı yapan şirketler dolaylı temsilci olarak yetkili kılınabilir. || " + T + " | Operatörlerce yetki kullanılırken vekâletname ibrazı aranmaz. || " + T + " | aranan koşulların varlığının tespit edilmesi halinde kişiye Bakanlıkça yetki verilir. || " + T + " | gümrük beyanı dahil tüm gümrük işlemlerini dolaylı temsil yoluyla yapmaya yetkili tüzel kişileri",
yuva=["İkiz eksen doğrudan ↔ dolaylı temsil: Kanun posta idaresi ve kargo şirketlerini dolaylı temsilci olarak yetkilendirir",
      "Tebliğ yetkilendirme maddesi: operatörlerce yetki kullanılırken vekâletname ibrazı aranmaz (tersine çevrilmiş)",
      "Tebliğ başvuru maddesi: başvuru bölge müdürlüğüne yapılır; yetkiyi Bakanlık verir",
      "Tebliğ tanımlar maddesi: operatör yalnızca tüzel kişileri kapsar (unsur eklenmiş)"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "TERİM", "TERSİNE", "UNSUR"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=12, ayna="",
guncellik="",
cikmis="2021/90",
kapsamli=False,
),

# ---------------- 10. TEBLİĞ + GENELGE: OPERATÖRÜN ALABİLECEĞİ ÜCRETLER (meslek yanlılığı, olumsuz) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="YANLIŞ",
z="Z",
madde="Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 12, 18; 2022/9 sayılı Genelge bölüm I/1.4",
cek="Basitleştirilmiş beyandaki eşyada operatör müşavirlik, ordino, terminal ücreti ve ilk üç gün ardiye alamaz; detaylı beyanda asgari ücret tarifesi esas alınır.",
kok=[TB + " ile posta ve hızlı kargo taşımacılığı yoluyla gelen veya giden eşyaya ilişkin 2022/9 sayılı Genelge'ye göre operatörlerin alıcıdan alabileceği ücret ve tutarlara ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Operatörler, basitleştirilmiş gümrük beyannamesi ile beyan edilen eşyanın gümrük işlemleri için gümrük müşavirliği hizmeti karşılığında Asgari Ücret Tarifesine göre ücret alabilir.",
c=["Operatörler, basitleştirilmiş gümrük beyannamesi ile beyan edilen eşyanın gümrük işlemleri için verilen hizmet karşılığında ordino ve terminal adı altında ilave ücret alamaz.",
   "Operatörler, basitleştirilmiş gümrük beyannamesi ile beyan edilen eşya için gönderinin geldiğine dair bildirimin alıcıya yapıldığı tarihten itibaren ilk üç gün için ardiye ücreti alamaz.",
   "Normal usulde detaylı beyan ile serbest dolaşıma giren eşyada dolaylı temsil yetkisiyle yapılan işlemlerin ücretinin belirlenmesinde Asgari Ücret Tarifesine İlişkin Tebliğ hükümleri esas alınır.",
   "Basitleştirilmiş gümrük beyannamesinde beyan edilen gönderilerin tahakkuk ettirilen gümrük vergileri operatör tarafından tahsil edilebilir."],
sirali=False,
g="2022/9 sayılı Genelge'ye göre operatörler, basitleştirilmiş gümrük beyannamesiyle beyan edilen eşyanın gümrük işlemleri için verilen hizmet karşılığında gümrük müşavirliği, ordino, terminal ve benzeri isimler altında ilave ücret ile gönderinin geldiğine dair bildirimin alıcıya yapıldığı tarihten itibaren ilk üç gün için ardiye ücreti alamaz. Yanlış ifade, bu eşya için gümrük müşavirliği ücreti alınabileceğini söylemektedir. Tebliğe göre Gümrük Müşavirliği ve Yetkilendirilmiş Gümrük Müşavirliği Asgari Ücret Tarifesine İlişkin Tebliğ hükümleri yalnızca normal usulde detaylı beyana konu eşyada dolaylı temsil yetkisiyle yapılan işlemlerin ücretinde esas alınır; çeldirici bu komşu hükümden taşınmış olup 'müşavirlik hizmeti her işlemde ücretlidir' önyargısını yoklar. Basitleştirilmiş gümrük beyannamesinde beyan edilen gönderilerin tahakkuk ettirilen gümrük vergileri ise operatör tarafından tahsil edilebilir. Bu nedenle doğru cevap 'Operatörler, basitleştirilmiş gümrük beyannamesi ile beyan edilen eşyanın gümrük işlemleri için gümrük müşavirliği hizmeti karşılığında Asgari Ücret Tarifesine göre ücret alabilir.' seçeneğidir. (MD Tebliğ 12, 18; Genelge 2022/9 bölüm I/1.4, 2.1)",
kanit=T + " | Operatörler, yukarıda yer alan eşyanın gümrük işlemleri için verilen hizmet karşılığında gümrük müşavirliği, ordino, terminal ve benzeri isimler altında ilave ücret ile gönderinin geldiğine dair bildirimin alıcıya yapıldığı tarihten itibaren ilk üç gün için ardiye ücreti alamaz. || " + T + " | dolaylı temsil yetkisiyle yapılan gümrük beyanı dahil tüm gümrük işlemlerine ilişkin faaliyetler için alınacak ücretlerin belirlenmesinde 30/12/2015 tarihli ve 29578 sayılı Resmî Gazete'de yayımlanan Gümrük Müşavirliği ve Yetkilendirilmiş Gümrük Müşavirliği Asgari Ücret Tarifesine İlişkin Tebliğ hükümleri esas alınır. || " + T + " | ticari miktar ve mahiyet arz etmeyen eşyanın serbest dolaşıma giriş beyanı normal usulde detaylı beyan ile yapılır. || " + T + " | Basitleştirilmiş gümrük beyannamesinde beyan edilen gönderilerin tahakkuk ettirilen gümrük vergileri operatör tarafından tahsil edilebilir",
yuva=["2022/9 sayılı Genelge basitleştirilmiş beyan bölümü: ordino ve terminal adı altında ilave ücret alınamaz (doğru)",
      "Aynı Genelge hükmü: bildirimden itibaren ilk üç gün ardiye ücreti alınamaz (doğru)",
      "Tebliğ diğer hükümler maddesi: detaylı beyana konu eşyada ücretlerde Asgari Ücret Tarifesi esas alınır (doğru)",
      "Tebliğ vergilerin ödenmesi maddesi: tahakkuk eden vergiler operatörce tahsil edilebilir (doğru)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "SAĞDUYU"],
duzey=["AYIRT"],
profil=[4, 3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 11. TEBLİĞ: BAŞVURU VE DEĞERLENDİRME (önermeli) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="ÖNERMELİ",
z="O",
madde="Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 4, 5, 6",
cek="Başvuru bölge müdürlüğüne yapılır; heyet yerinde tespit eder; dosya on beş günde Bakanlığa gider, Bakanlık on beş günde karar verir; posta idaresinden belge aranmaz.",
kok=[TB + "'e göre operatör yetkisi için yapılacak başvuru ve başvurunun değerlendirilmesine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Başvuru, yetki kapsamı işlemlerin yapılacağı gümrük müdürlüğünün bağlı olduğu Gümrük ve Dış Ticaret Bölge Müdürlüğüne yapılır.",
     "II. Başvurunun eksiksiz yapıldığının anlaşılması hâlinde gerekli şartların sağlanıp sağlanmadığı, gümrük müdürlüğünce oluşturulacak bir heyet marifetiyle yerinde tespit edilir.",
     "III. Talep, Bakanlıkça on beş gün içinde karara bağlanır.",
     "IV. Posta idaresi de başvurusunda adli sicil belgesi ve teminat mektubu ibraz eder.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve III",
c=["Yalnız I", "I ve IV", "II ve III", "I, II ve III"],
sirali=False,
g="Tebliğ'e göre başvuru, gerekli belgelerle birlikte yetki kapsamı işlemlerin yapılacağı gümrük müdürlüğünün bağlı olduğu Gümrük ve Dış Ticaret Bölge Müdürlüğüne yapılır (I doğru). Başvurunun eksiksiz olduğu anlaşılırsa gerekli şartların sağlanıp sağlanmadığı, gümrük müdürlüğünce değil Gümrük ve Dış Ticaret Bölge Müdürlüğünce oluşturulacak bir heyet marifetiyle yerinde tespit edilerek tutanağa bağlanır (II yanlış); tespit sonuçları, başvuru evrakı ve bölge müdürlüğü görüşü başvuru tarihinden itibaren on beş gün içinde Bakanlığa gönderilir. Talep Bakanlıkça on beş gün içinde karara bağlanır (III doğru). Posta idaresi için başvuruda aranan belgeler aranmaz, yalnızca başvuru formu ile başvurulur; başvuru koşullarından da yalnızca gümrük müşaviri ve altyapı koşulları aranır, teminat mektubu aranmaz (IV yanlış). Bu nedenle doğru cevap 'I ve III' seçeneğidir. (MD Tebliğ 4, 5, 6)",
kanit=T + " | yetki kapsamı işlemlerin yapılacağı gümrük müdürlüğünün bağlı olduğu Gümrük ve Dış Ticaret Bölge Müdürlüğüne yapılır. || " + T + " | Gümrük ve Dış Ticaret Bölge Müdürlüğünce oluşturulacak bir heyet marifetiyle gerekli şartların sağlanıp sağlanmadığı yerinde tespit edilerek bir tutanağa bağlanır. || " + T + " | Talep, Bakanlıkça on beş gün içinde karara bağlanır. || " + T + " | Posta idaresi için birinci fıkrada belirtilen belgeler aranmaz; Ek-1'de yer alan başvuru formu ile başvuruda bulunulur.",
yuva=["Yalnız I: Bakanlığın on beş günlük karar süresini bilmeyen aday",
      "I ve IV: posta idaresinden belge ve teminat aranmadığını bilmeyen aday (başvuru belgeleri maddesinin üçüncü fıkrası)",
      "II ve III: heyeti oluşturan makamı gümrük müdürlüğü sanan aday (başvurunun değerlendirilmesi maddesi)",
      "I, II ve III: II'deki makam değişikliğini fark etmeyen aday"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 12. TEBLİĞ: GÖNDERİLERİN TASNİFİ (liste dışı, olumsuz) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="KAPSAM_DIŞI",
z="Z",
madde="Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 3, 9",
cek="Gelen gönderiler barkod ve X-ray sonrası dört kategoriye ayrılır: belge kontrolüne tabi doküman; basitleştirilmiş kapsamda belge kontrolüne veya muayeneye tabi gönderiler; kapsam dışı gönderiler.",
kok=[TB + "'e göre yurt dışından gelen gönderilerin otomatik barkod okuyucu ve X-ray kontrolünden geçirildikten sonra otomatik olarak ayrıldığı kategoriler arasında aşağıdakilerden hangisi yer almaz?"],
d="Gümrükçe muayeneye tabi tutulacak doküman",
c=["Belge kontrolüne tabi doküman",
   "Basitleştirilmiş gümrük beyannamesine konu edilebilecek kapsamda gelen ve belge kontrolüne tabi gönderiler",
   "Basitleştirilmiş gümrük beyannamesine konu edilebilecek kapsamda gelen ve gümrükçe muayeneye tabi tutulacak gönderiler",
   "Basitleştirilmiş gümrük beyannamesine konu edilebilecek kapsamın dışında kalan gönderiler"],
sirali=False,
g="Tebliğ'e göre yurt dışından gelen gönderiler, otomatik barkod okuyucu ve X-ray kontrolünden geçirildikten sonra otomatik olarak dört kategoriye ayrılır: belge kontrolüne tabi doküman; Kararda basitleştirilmiş gümrük beyannamesine konu edilebileceği belirtilen kapsamda gelen ve belge kontrolüne tabi gönderiler; aynı kapsamda gelen ve gümrükçe muayeneye tabi tutulacak gönderiler; bu kapsamın dışında kalan gönderiler. Muayeneye tabi kategori yalnızca bu kapsamdaki gönderiler için öngörülmüştür; dokümanlar yalnızca belge kontrolüne tabi kategoride yer alır. 'Gümrükçe muayeneye tabi tutulacak doküman', listedeki iki ayrı kategorinin birleştirilmesiyle oluşturulmuş, akla yatkın ama listede olmayan bir unsurdur. Basitleştirilmiş gümrük beyannamesinin Tebliğdeki tanımı, bu beyannamenin Kararın posta ve hızlı kargo hükmündeki gelen eşya ile ihracat eşyası için kullanıldığını gösterir. Bu nedenle doğru cevap 'Gümrükçe muayeneye tabi tutulacak doküman' seçeneğidir. (MD Tebliğ 3, 9)",
kanit=T + " | otomatik barkod okuyucu ve X-ray kontrolünden geçirildikten sonra otomatik olarak aşağıdaki dört kategoriye ayrılır || " + T + " | Belge kontrolüne tabi doküman. || " + T + " | bendi kapsamında gelen ve belge kontrolüne tabi gönderiler. || " + T + " | bendi kapsamında gelen ve gümrükçe muayeneye tabi tutulacak gönderiler. || " + T + " | bendi kapsamı dışında kalan gönderiler. || " + T + " | Kararın 126 ncı maddesinin birinci fıkrasının (a) ve (c) bentleri kapsamı eşyanın operatör tarafından beyan edilmesinde kullanılan",
yuva=["Aynı maddenin birinci kategorisi: belge kontrolüne tabi doküman (listede)",
      "Aynı maddenin ikinci kategorisi: basitleştirilmiş kapsamda gelen ve belge kontrolüne tabi gönderiler (listede)",
      "Aynı maddenin üçüncü kategorisi: basitleştirilmiş kapsamda gelen ve muayeneye tabi gönderiler (listede)",
      "Aynı maddenin dördüncü kategorisi: bu kapsamın dışında kalan gönderiler (listede)"],
yakinlik="PARAFRAZ",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 13. TEBLİĞ: İHRACATTA AĞIRLIK VE DEĞER SINIRI (vaka, güncellik) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="OLAY",
z="O",
madde="Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 10/7; 2022/9 sayılı Genelge bölüm I/3.1",
cek="Operatör, brüt 600 kilogramı ve değeri 30.000 Avro'yu geçmeyen ihracat eşyasını Tebliğ çerçevesinde beyan eder; iki sınır birlikte aranır.",
kok=[TB + "'e göre hızlı kargo operatörü (X) A.Ş.'nin aynı gün yurt dışına göndereceği ve ihracat rejimine konu edilecek dört gönderiye ilişkin bilgiler şöyledir:",
     "- 1 numaralı gönderi: brüt 450 kilogram, değeri 28.000 Avro",
     "- 2 numaralı gönderi: brüt 640 kilogram, değeri 12.000 Avro",
     "- 3 numaralı gönderi: brüt 120 kilogram, değeri 31.500 Avro",
     "- 4 numaralı gönderi: brüt 600 kilogram, değeri 30.000 Avro",
     "Buna göre hangi gönderilerin beyanı bu Tebliğ hükümleri çerçevesinde operatör tarafından yapılabilir?"],
d="1 ve 4",
c=["Yalnız 1", "1, 2 ve 4", "1, 3 ve 4", "1, 2, 3 ve 4"],
sirali=False,
g="Tebliğ'e göre posta ve hızlı kargo taşımacılığı kapsamında miktarı brüt 600 kilogramı ve değeri 30.000 Avro'yu geçmeyen ihracat rejimine konu eşyanın beyanı Tebliğ hükümleri çerçevesinde operatör tarafından yapılır; bu sınırlar 03.01.2026 tarihli ve 33126 sayılı Resmî Gazete'de yayımlanan Seri No: 5 Tebliğ ile belirlenmiş, 2022/9 sayılı Genelge de 2026/4 sayılı Genelgeyle aynı sınırlara göre düzenlenmiştir. İki sınır birlikte aranır ve 'geçmeyen' ifadesi sınır değerin kendisini de kapsar. 1 numaralı gönderi her iki sınırın altındadır; 4 numaralı gönderi tam sınırda olduğundan sınırı geçmemektedir. 2 numaralı gönderi değer sınırının altında kalsa da brüt 600 kilogramı aşmakta, 3 numaralı gönderi ise ağırlık sınırının altında olsa da 30.000 Avro'yu aşmaktadır. En güçlü tuzak, sınırlardan yalnızca birini sağlamayı yeterli sayarak 2 veya 3 numaralı gönderiyi de dahil etmektir. Bu nedenle doğru cevap '1 ve 4' seçeneğidir. (MD Tebliğ 10/7; Genelge 2022/9 bölüm I/3.1)",
kanit=T + " | ve değeri 30.000 Avro'yu[8] geçmeyen ihracat rejimine konu eşyanın beyanı bu Tebliğ hükümleri çerçevesinde operatör tarafından yapılır. (03.01.2026 / 33126 R.G. Seri No: 5 Tebliğ) || " + T + " | Kararın 126 ncı maddesi kapsamında miktarı brüt 600 kilogramı",
yuva=["Yalnız 1: 'geçmeyen' ifadesinin sınır değeri de kapsadığını görmeyen aday (4 numaralı gönderi dışarıda bırakılmış)",
      "1, 2 ve 4: yalnızca değer sınırını uygulayan aday (aynı fıkranın ağırlık sınırı)",
      "1, 3 ve 4: yalnızca ağırlık sınırını uygulayan aday (aynı fıkranın değer sınırı)",
      "1, 2, 3 ve 4: iki sınırdan birini sağlamayı yeterli sayan aday ('ve' şartını 'veya' okuyan)"],
yakinlik="ÇIKARIM",
tuzak=["ŞART", "SAYI"],
duzey=["UYGULAMA"],
profil=[5, 2],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="03.01.2026 / 33126 R.G. (Seri No: 5 Tebliğ)",
cikmis="",
kapsamli=False,
),

# ---------------- 14. TEBLİĞ: AYLIK BEŞ TAŞIMA SENEDİ SINIRI ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="SONUÇ",
z="Z",
madde="Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 10/10, 10/13; 2022/9 sayılı Genelge bölüm I/2.1",
cek="Aylık beş taşıma senedi sınırını aşan gönderiler sonraki aya devredilemez; operatörce normal usulde detaylı beyan kapsamında işlem görür.",
kok=[TB + "'e göre basitleştirilmiş gümrük beyannamesiyle beyan edilen ve aynı gerçek kişi adına bir takvim ayında en fazla beş taşıma senedi sınırına tabi tutulan eşyada bu sınırın aşılması hâlinde, aşan gönderilere ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Aşan gönderiler için operatör tarafından normal usulde detaylı beyan kapsamında işlem tesis edilir.",
c=["Aşan gönderiler bir sonraki aya devredilerek basitleştirilmiş gümrük beyannamesine konu edilir.",
   "Aşan gönderiler, önceki gönderilerden farklı cinste eşya içermeleri hâlinde basitleştirilmiş gümrük beyannamesine konu edilebilir.",
   "Aşan gönderiler için sözlü beyan usulü çerçevesinde maktu vergi tahsil edilmesi kaydıyla eşya teslim edilir.",
   "Aşan gönderilerin serbest dolaşıma girişine izin verilmez ve mahrecine iadesi zorunludur."],
sirali=False,
g="Tebliğ'e göre basitleştirilmiş gümrük beyannamesine konu belirli eşyada aynı kişi adına bir takvim ayında en fazla beş taşıma senedi muhteviyatı eşyanın, aynı veya farklı cinste olup olmadığına bakılmaksızın serbest dolaşıma girişine izin verilir. Beş taşıma senedi sayısı aşılırsa aşan miktarın bir sonraki aya devredilerek basitleştirilmiş gümrük beyannamesine konu edilmesine izin verilmez; bu gönderiler için Kararda bir gerçek kişiye gelen eşyaya ilişkin öngörülen kapsamda işlem tesis edilir ve normal usulde detaylı beyan, dolaylı temsil yetkisine sahip operatör tarafından gümrük mevzuatının genel hükümlerine göre yapılır. Sınır eşyanın cinsine bakılmaksızın uygulandığından farklı cins eşya için ayrıcalık tanınmaz. Sözlü beyan usulüyle maktu vergi tahsil edilerek teslim, 2011/39 sayılı Genelge'nin 24.03.2014'te yürürlükten kaldırılan posta eşyası hükümlerinde muafiyetin yılda beş kez kullanım sınırının aşılmasına bağlanan eski sonuçtur; eski kaynaktan çalışan adayı yakalar. Bu nedenle doğru cevap 'Aşan gönderiler için operatör tarafından normal usulde detaylı beyan kapsamında işlem tesis edilir.' seçeneğidir. (MD Tebliğ 10/10, 10/13; Genelge 2022/9 bölüm I/2.1)",
kanit=T + " | aynı kişi adına bir takvim ayında en fazla beş taşıma senedi muhteviyatı eşyanın, aynı veya farklı cinste olup olmadığına bakılmaksızın, serbest dolaşıma girişine izin verilir. || " + T + " | Beş taşıma senedi sayısının aşılması durumunda, aşan miktarın bir sonraki aya devredilerek basitleştirilmiş gümrük beyannamesine konu edilmesine izin verilmez ve Kararın 126 ncı maddesinin birinci fıkrasının (b) bendi kapsamında işlem tesis edilir. || " + T + " | Bu kapsamda gelen eşyanın normal usulde detaylı beyanı dolaylı temsil yetkisine sahip operatör tarafından gümrük mevzuatının genel hükümlerine tabi olarak yapılır. || " + T + " | sözlü beyan usulü çerçevesinde işlem yapılarak, Kararın 62 inci maddesi kapsamında maktu vergi tahsil edilmesi kaydıyla eşya teslim edilir.",
yuva=["Aynı fıkra: aşan miktarın bir sonraki aya devredilmesine izin verilmez (tersine çevrilmiş)",
      "Aynı fıkra: sınır eşyanın aynı veya farklı cinste olup olmadığına bakılmaksızın uygulanır",
      "2011/39 sayılı Genelge'nin 2014'te kaldırılan posta eşyası hükmü: beş kez sınırı aşılınca sözlü beyanla maktu vergi (eski hâl)",
      "Tebliğin geri gelen ve mahrece iade edilen eşya maddesi: mahrece iade operatör beyanıyla ve talebe bağlıdır"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "TERSİNE"],
duzey=["AYIRT"],
profil=[1, 5],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 15. TEBLİĞ: TAHSİL EDİLEN VERGİLERİN ÖDENME SÜRESİ (başlangıç) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="SÜRE",
z="O",
madde="Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 12/2; Gümrük Yönetmeliği md. 462",
cek="Operatörün gümrük adına tahsil ettiği vergiler eşyanın operatöre teslimini takip eden yedi günde ödenir; posta idaresinde süre alıcıya teslimden başlar.",
kok=[TB + "'e göre basitleştirilmiş gümrük beyannamesinde beyan edilen gönderilere ilişkin olarak hızlı kargo operatörünce gümrük idaresi adına tahsil edilen vergiler hangi süre içinde ödenir?"],
d="Eşyanın operatöre teslimini takip eden yedi gün içinde",
c=["Eşyanın alıcısına teslimini takip eden yedi gün içinde",
   "Basitleştirilmiş gümrük beyannamesinin tescilini takip eden yedi gün içinde",
   "Eşyanın operatöre teslimini takip eden üç iş günü içinde",
   "Eşyanın operatöre teslimini takip eden on beş gün içinde"],
sirali=False,
g="Tebliğ'e göre basitleştirilmiş gümrük beyannamesinde beyan edilen gönderilerin tahakkuk ettirilen gümrük vergileri operatör tarafından tahsil edilebilir ve gümrük idaresi adına tahsil edilen vergiler eşyanın operatöre teslimini takip eden yedi gün içinde ödenir. Posta idaresi için aynı süre, Gümrük Yönetmeliği'ndeki hüküm gereğince eşyanın alıcısına tesliminden itibaren başlar; en güçlü çeldirici alıcıya teslim tarihini esas alan seçenektir, ancak kök hızlı kargo operatörünü sormaktadır. Süre beyannamenin tescilinden başlamaz. Üç iş günü, teslim tarihi ile alıcının kimlik veya telefon bilgilerinin gümrük müdürlüğüne iletilme süresidir; on beş gün ise başvuru dosyasının Bakanlığa gönderilme ve Bakanlığın karar verme süresidir. Bu nedenle doğru cevap 'Eşyanın operatöre teslimini takip eden yedi gün içinde' seçeneğidir. (MD Tebliğ 12/2; GY 462)",
kanit=T + " | gümrük idaresi adına tahsil edilen vergiler eşyanın operatöre teslimini takip eden yedi gün içerisinde ödenir. || " + T + " | Posta idaresi için söz konusu süre, Gümrük Yönetmeliğinin 462 nci maddesinin üçüncü fıkrası gereğince, eşyanın alıcısına tesliminden itibaren başlar. || " + T + " | eşyanın alıcısına teslimini takip eden üç iş günü içerisinde gümrük müdürlüğüne elektronik ortamda iletilir || " + T + " | Talep, Bakanlıkça on beş gün içinde karara bağlanır.",
yuva=["Aynı fıkranın ikinci cümlesi: posta idaresi için süre eşyanın alıcısına tesliminden başlar (başlangıç anı karıştırılmış)",
      "Tebliğ beyan maddesi: basitleştirilmiş beyanname tescil edilinceye kadar özet beyan statüsündedir (başlangıç anı karıştırılmış)",
      "Tebliğ beyan maddesi: teslim tarihi ve alıcı bilgileri üç iş günü içinde iletilir",
      "Tebliğ başvuru maddesi: dosya on beş günde Bakanlığa gönderilir, talep on beş günde karara bağlanır"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU", "SAYI"],
duzey=["AYIRT"],
profil=[2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 16. TEBLİĞ: MÜEYYİDE (güncellik, olumsuz) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="MÜEYYİDE",
z="Z",
madde="Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 17",
cek="Koşulu kaybeden operatör yetkiden yararlanamaz; Tebliğe aykırılıkta usulsüzlük cezası taşıma senedi bazında, aynı mahiyetteki düzeltmede yalnız beyanname için uygulanır.",
kok=[TB + "'e göre operatörler hakkında uygulanacak müeyyidelere ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Basitleştirilmiş gümrük beyannamesi içeriği birden fazla taşıma senedinde düzeltmeye konu veri alanının aynı mahiyette olması durumunda da müeyyide her bir taşıma senedi için ayrı ayrı uygulanır.",
c=["Başvuru koşullarından birinin veya birden fazlasının operatörce kaybedildiğinin anlaşılması hâlinde, bu koşullar yeniden sağlanıncaya kadar operatörün yetkiden faydalanmasına izin verilmez.",
   "Tebliğde düzenlenen hususlara aykırı hareket eden operatör hakkında, fiil daha ağır bir cezai yaptırımı gerektirmiyorsa Gümrük Kanunu'nun usulsüzlük cezasına ilişkin hükmü uyarınca işlem yapılır.",
   "Müeyyidelerin uygulanmasında posta hizmetlerine ilişkin uluslararası yükümlülükler dikkate alınır.",
   "Tebliğe aykırılık nedeniyle uygulanacak müeyyide, basitleştirilmiş gümrük beyanı kapsamı her bir taşıma senedi bazında ayrı değerlendirilir."],
sirali=False,
g="Tebliğ'e göre başvuru koşullarından birinin veya birden fazlasının operatörce kaybedildiğinin anlaşılması hâlinde, bu koşullar yeniden sağlanıncaya kadar operatörün yetkiden faydalanmasına izin verilmez. Tebliğde düzenlenen hususlara aykırı hareket eden operatörler hakkında fiil daha ağır bir cezai yaptırımı gerektirmiyorsa Gümrük Kanunu'nun usulsüzlük cezasına ilişkin hükmü uygulanır; bu müeyyide basitleştirilmiş gümrük beyanı kapsamı her bir taşıma senedi bazında ayrı değerlendirilir ve uygulamada posta hizmetlerine ilişkin uluslararası yükümlülükler dikkate alınır. 06.11.2025 tarihli ve 33069 sayılı Resmî Gazete ile eklenen hükme göre ise basitleştirilmiş gümrük beyannamesi içeriği birden fazla taşıma senedinde düzeltmeye konu veri alanının aynı mahiyette olması durumunda usulsüzlük cezası yalnızca basitleştirilmiş gümrük beyannamesi için uygulanır. Yanlış ifade bu yeni istisnayı görmezden gelerek genel kuralı her durumda uygulamaktadır; güncellemeyi izlemeyen aday bu ifadeyi doğru sanar. Bu nedenle doğru cevap 'Basitleştirilmiş gümrük beyannamesi içeriği birden fazla taşıma senedinde düzeltmeye konu veri alanının aynı mahiyette olması durumunda da müeyyide her bir taşıma senedi için ayrı ayrı uygulanır.' seçeneğidir. (MD Tebliğ 17)",
kanit=T + " | bu koşul veya koşullar yeniden sağlanıncaya kadar operatörün bu Tebliğ kapsamındaki yetkiden faydalanmasına izin verilmez. || " + T + " | fiilin daha ağır bir cezai yaptırımı gerektirmemesi halinde, Kanunun 241 inci maddesinin birinci fıkrası uyarınca işlem yapılır. || " + T + " | Bu maddenin uygulanmasında posta hizmetlerine ilişkin uluslararası yükümlülükler dikkate alınır. || " + T + " | basitleştirilmiş gümrük beyanı kapsamı her bir taşıma senedi bazında ayrı değerlendirilir. || " + T + " | birden fazla taşıma senedinde düzeltmeye konu veri alanının aynı mahiyette olması durumunda, Kanunun 241 inci maddesinin birinci fıkrası yalnızca basitleştirilmiş gümrük beyannamesi için uygulanır. (06.11.2025 / 33069 R.G. ile eklenmiştir) || " + T + " | usulsüzlüğe konu her bir gönderi için Gümrük Kanununun 241 inci maddesinin birinci fıkrası çerçevesinde işlem yapılması gerektiğinden",
yuva=["Aynı maddenin birinci fıkrası: koşul kaybında yeniden sağlanıncaya kadar yetkiden faydalanılamaz (doğru)",
      "Aynı maddenin üçüncü fıkrası: daha ağır yaptırım gerektirmiyorsa usulsüzlük cezası hükmü (doğru)",
      "Aynı maddenin dördüncü fıkrası: posta hizmetlerine ilişkin uluslararası yükümlülükler dikkate alınır (doğru)",
      "Aynı maddenin beşinci fıkrasının ilk cümlesi: müeyyide taşıma senedi bazında ayrı değerlendirilir (doğru)"],
yakinlik="BİREBİR",
tuzak=["İSTİSNA", "TERSİNE"],
duzey=["AYIRT"],
profil=[5, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="06.11.2025 / 33069 R.G.",
cikmis="",
kapsamli=False,
),

# ---------------- 17. GENELGE: GERİ GÖNDERİLEN CEP TELEFONU (vaka, saklı istisna) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="OLAY",
z="O",
madde="2022/9 sayılı Genelge bölüm IV/12",
cek="Cep telefonu posta-kargoyla getirilemez; IMEI'si Türkiye'de kayıtlı ve üç ay içinde geri gönderilen yolcu telefonu teyitle muafen teslim edilir; kod YLC0.",
kok=["Yurt dışına çıkış yapan yolcu (A)'nın IMEI numarası Türkiye'de kayıtlı olan cep telefonu yurt dışında kalmıştır. Telefon, Kararda öngörülen üç aylık süre içinde hızlı kargo ile Türkiye'ye geri gönderilmiş ve IMEI numarasının kayıtlı olduğu yapılan sorgulamayla teyit edilmiştir.",
     KK + " kapsamında posta ve hızlı kargo taşımacılığı yoluyla gelen eşyaya ilişkin 2022/9 sayılı Genelge'ye göre bu telefona ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Telefon muafen teslim edilir; basitleştirilmiş gümrük beyannamesinde YLC0 muafiyet kodu kullanılır.",
c=["Cep telefonunun posta veya hızlı kargo yoluyla getirilmesi hiçbir surette mümkün olmadığından telefon mahrecine iade edilir.",
   "Telefon, vergileri ödenmek kaydıyla basitleştirilmiş gümrük beyannamesi ile beyan edilerek teslim edilir.",
   "Telefon, normal usulde detaylı beyanla BS20 kodu seçilerek ve vergileri ödenerek teslim edilir.",
   "Telefon muafen teslim edilir; basitleştirilmiş gümrük beyannamesinde KNSY muafiyet kodu kullanılır."],
sirali=False,
g="2022/9 sayılı Genelge'ye göre cep telefonunun posta veya hızlı kargo taşımacılığı yoluyla muafen veya vergileri ödenerek getirilmesi hiçbir surette mümkün değildir. Ancak yurt dışına giden yolcuların IMEI numarası Türkiye'de kayıtlı olan cep telefonlarının yurt dışında kalması ve Kararda belirtilen üç aylık süre içinde posta veya hızlı kargo yoluyla geri gönderilmesi durumunda, IMEI numarasının kayıtlı olduğu sorgulamayla teyit edilirse telefon muafen teslim edilir ve basitleştirilmiş gümrük beyannamesinde YLC0 muafiyet kodu kullanılır. Vakadaki istisnayı görmeyen aday genel yasağa giderek mahrece iade seçeneğini işaretler. Vergi ödenerek getirme de yasak kapsamında olduğundan basitleştirilmiş beyanla ya da BS20 kodlu normal usulde detaylı beyanla vergili teslim mümkün değildir. KNSY muafiyet kodu konsinye ihracat için düzenlenen basitleştirilmiş gümrük beyannamesine aittir. Bu nedenle doğru cevap 'Telefon muafen teslim edilir; basitleştirilmiş gümrük beyannamesinde YLC0 muafiyet kodu kullanılır.' seçeneğidir. (MD Genelge 2022/9 bölüm IV/12)",
kanit=T + " | Cep telefonunun posta veya hızlı kargo taşımacılığı yoluyla muafen veya vergileri ödenerek hiçbir surette getirilmesi mümkün bulunmamaktadır. || " + T + " | 3 aylık süre içerisinde posta veya hızlı kargo taşımacılığı yoluyla geri gönderilmesi durumunda || " + T + " | adresinden yapılacak sorgulama sonucu teyit edilmesi halinde muafen teslim edilmesi mümkündür. Bu durumda basitleştirilmiş gümrük beyannamesinde \"YLC0\" muafiyet kodu kullanılarak beyan yapılır. || " + T + " | Konsinye ihracat için düzenlenen basitleştirilmiş gümrük beyannamesinde KNSY muafiyet kodu seçilir.",
yuva=["Aynı hükmün ilk cümlesi: cep telefonu posta-kargoyla hiçbir surette getirilemez (istisna görülmemiş)",
      "Aynı hükmün ilk cümlesi: vergileri ödenerek getirme de yasaktır",
      "2022/9 sayılı Genelge detaylı beyan bölümü: operatör beyanında BS20 kodu seçilir",
      "2022/9 sayılı Genelge ihracat bölümü: konsinye ihracatta KNSY muafiyet kodu"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "TERİM"],
duzey=["UYGULAMA"],
profil=[1, 3],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# ---------------- 18. TEBLİĞ + GENELGE: KIYMETE NAVLUN İLAVESİ (hesap, çıkmış 2025/76) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="HESAP",
z="Z",
madde="Posta ve Hızlı Kargo Tebliği (Seri No: 1) md. 12/1; 2022/9 sayılı Genelge bölüm II",
cek="Posta-kargo eşyasında giriş yerine kadar nakliye kıymete eklenir; navlun dahil teslimde navlun faturada ayrı gösterilmemişse 3 Avro emsal navlun eklenir.",
kok=["Türkiye'deki bir gerçek kişiye hızlı kargo ile iki ayrı gönderi gelmiştir. Her iki gönderide teslim şekli navlun giderinin dahil olduğu bir teslim şeklidir:",
     "- 1. gönderi: Faturada eşyanın fiyatı 60 Avro olarak yer almakta, navlun gideri ayrıca gösterilmemektedir.",
     "- 2. gönderi: Faturada eşyanın fiyatı 40 Avro, Türkiye'deki giriş yerine kadar navlun gideri 5 Avro olarak ayrı ayrı gösterilmektedir.",
     TB + " ile 2022/9 sayılı Genelge'nin kıymet tespitine ilişkin hükümlerine göre bu iki gönderinin kıymetlerinin toplamı kaç Avro'dur?"],
d="108 Avro",
c=["100 Avro", "103 Avro", "105 Avro", "111 Avro"],
sirali=True,
siklar=["100 Avro", "103 Avro", "105 Avro", "108 Avro", "111 Avro"],
g="Tebliğ ve 2022/9 sayılı Genelge'ye göre posta veya hızlı kargo taşımacılığı yoluyla gelen eşya için Türkiye'deki giriş liman veya yerine kadar yapılan nakliye giderleri eşyanın kıymetine ilave edilir; kıymet ibraz edilen faturaya, satış fişine veya eşya bedelinin ödendiğine ilişkin belgeye göre belirlenir. Navlun giderinin dahil olduğu teslim şekillerinde fatura üzerinde eşyanın fiyatı ile navlun gideri ayrı ayrı gösterilir; ayrı gösterilmemişse 3 Avro tutarında emsal navlun gideri fiilen ödenen veya ödenecek fiyata eklenir. Birinci gönderide navlun ayrıca gösterilmediğinden kıymet 60 + 3 = 63 Avro, ikinci gönderide navlun ayrıca gösterildiğinden kıymet 40 + 5 = 45 Avro olur; toplam 108 Avro'dur. Hiç navlun eklemeyen aday 100, yalnızca emsal navlunu ekleyen aday 103, yalnızca faturadaki navlunu ekleyen aday 105, faturada navlun gösterilen gönderiye de ayrıca emsal navlun ekleyen aday 111 Avro'ya ulaşır. Bu nedenle doğru cevap '108 Avro' seçeneğidir. (MD Tebliğ 12/1; Genelge 2022/9 bölüm II)",
kanit=T + " | Türkiye'deki giriş liman veya yerine kadar yapılan nakliye giderleri, eşyanın kıymetine ilave edilir. || " + T + " | Navlun giderinin dahil olduğu teslim şekillerinde, ibraz edilen fatura, satış fişi veya eşya bedelinin ödendiğine ilişkin belgede eşyanın fiilen ödenen veya ödenecek fiyatı ile navlun gideri ayrı ayrı gösterilir. || " + T + " | Navlun giderinin bu belgelerde ayrı gösterilmediği durumlarda, 3 (üç) avro tutarında emsal navlun gideri fiilen ödenen veya ödenecek fiyata eklenir.",
yuva=["100 Avro: navlunun fiyata dahil olduğu düşüncesiyle hiçbir nakliye giderini eklemeyen aday (giriş yerine kadar nakliyenin kıymete ilavesi hükmü)",
      "103 Avro: yalnızca emsal navlunu ekleyip faturada ayrı gösterilen navlunu ekleyen hükmü atlayan aday",
      "105 Avro: yalnızca faturada gösterilen navlunu ekleyip emsal navlun hükmünü atlayan aday",
      "111 Avro: navlunu ayrı gösterilen gönderiye de 3 Avro emsal navlun ekleyen aday"],
yakinlik="ÇIKARIM",
tuzak=["AD-HESAP", "SAĞDUYU"],
duzey=["UYGULAMA"],
profil=[2, 3],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2025/76",
kapsamli=False,
),

# ---------------- 19. GENELGE 2011/39: YOLCU BERABERİ TÜTÜN VE TÜKETİM MADDELERİ (çıkmış 2023/48, önermeli) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="ÖNERMELİ",
z="O",
madde="2011/39 sayılı Genelge (Kişisel eşya; Yolcu beraberi hediyelik eşya)",
cek="Ek-9 sigarasına ek 200 adet alınabilir; tütün-alkol muafiyeti her ürün için ayrı kullanılır; 18 yaş altı yararlanamaz; tüketim maddeleri yalnız yolcu beraberinde gelir.",
kok=[KK + "a göre muafiyet tanınan yolcu beraberi eşyaya ilişkin 2011/39 sayılı Genelge'de yer alan açıklamalar çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Karar ekindeki listenin tüketim maddeleri bölümünde yer alan sigara miktarına ek olarak yolcular 200 adet sigara daha alabilir.",
     "II. Tütün ve tütün ürünleri ile alkollü ürünler için muafiyet hakkı, karşısında yazılı miktarı aşmamak kaydıyla her bir ürün için ayrı ayrı kullanılabilir.",
     "III. Tütün ve tütün ürünleri ile alkollü ürünlere ilişkin muafiyet hakkından 18 yaşın altındaki yolcular faydalanamaz.",
     "IV. Listenin tüketim maddeleri bölümünde yer alan eşya, yolcunun gelişinden bir ay önce veya bir ay sonra posta yoluyla da getirilebilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, II ve III",
c=["Yalnız III", "I ve II", "II ve IV", "I, II, III ve IV"],
sirali=False,
g="2011/39 sayılı Genelge'ye göre Karar ekindeki listenin tüketim maddeleri bölümündeki sigara miktarına ek olarak yolcular 200 adet sigara daha alabilir (I doğru). Aynı bölümdeki tütün ve tütün ürünleri ile alkollü ürünler için muafiyet hakkı, karşısında yazılı miktarı aşmamak kaydıyla her bir ürün için ayrı ayrı kullanılabilir (II doğru). Tütün ve tütün ürünleri ile alkollü ürünlere ilişkin muafiyet hakkından 18 yaşın altındaki yolcular faydalanamaz (III doğru). Tüketim maddeleri bölümünde yer alan eşyanın yalnızca yolcu beraberinde getirilmesi mümkündür; gelişten önce veya sonra gelme imkânı listedeki diğer kişisel eşya içindir, tüketim maddeleri posta yoluyla getirilemez (IV yanlış). Muafiyet listede karşılarında yazılı miktarlarla sınırlı olduğundan bu miktarları aşan sigara muafen getirilemez. En güçlü çeldirici IV'tür; kişisel eşyaya tanınan gelişten önce veya sonra gelme imkânı tüketim maddelerine taşınmıştır. Bu nedenle doğru cevap 'I, II ve III' seçeneğidir. (MD Genelge 2011/39 Kişisel eşya, Yolcu beraberi hediyelik eşya)",
kanit=T + " | Bu bölümdeki sigara miktarına ek olarak yolcuların 200 adet sigara daha alabilmeleri mümkündür. || " + T + " | Aynı bölümde yer alan tütün ve tütün ürünleri ile alkollü ürünler için muafiyet hakkı karşısında yazılı miktarı aşmamak kaydıyla her bir ürün için ayrı ayrı kullanılabilir. || " + T + " | tütün ve tütün ürünleri ile alkollü ürünlere ilişkin muafiyet hakkından, 18 yaşın altındaki yolcular faydalanamayacaktır. || " + T + " | Tüketim Maddeleri\" bölümünde yer alan eşyanın sadece yolcu beraberinde getirilmesi mümkündür. || " + T + " | gelişlerinden bir ay önce veya bir ay sonraki[1] süreler içerisinde gelen",
yuva=["Yalnız III: 200 adet ek sigara ve ürün bazında ayrı kullanım hükümlerini bilmeyen aday",
      "I ve II: 18 yaş sınırını başka bir yaş sınırıyla karıştıran aday",
      "II ve IV: kişisel eşyanın gelişten önce veya sonra gelme imkânını tüketim maddelerine taşıyan aday (aynı Genelgenin kişisel eşya bölümü)",
      "I, II, III ve IV: tüketim maddelerinin yalnızca yolcu beraberinde getirilebileceği kaydını gözden kaçıran aday"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "ŞART"],
duzey=["AYIRT"],
profil=[3, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2023/48",
kapsamli=False,
),

# ---------------- 20. GENELGE: İTHALİ MÜMKÜN OLMAYAN EŞYA (güncellik, olumsuz) ----------------
dict(
konu="Posta ve Hızlı Kargo", blok="SB39",
kalip="KAPSAM_DIŞI",
z="O",
madde="2022/9 sayılı Genelge bölüm IV/2, 3, 7, 9, 13",
cek="Uyuşturucu-uyarıcı etkili maddeler 2313 kapsamında olmasa da posta-kargoyla ithal edilemez; reçeteli ilaç, raporlu takviye gıda, kontrol edilen bitki ve uygunluk yazılı bıçak girebilir.",
kok=[KK + " kapsamında posta ve hızlı kargo taşımacılığı yoluyla gelen eşyaya ilişkin 2022/9 sayılı Genelge'ye göre aşağıdakilerden hangisinin posta veya hızlı kargo taşımacılığı yoluyla ithali mümkün değildir?"],
d="2313 sayılı Uyuşturucu Maddelerin Murakabesi Hakkında Kanun kapsamında bulunmamakla birlikte uyuşturucu ve uyarıcı etkiye haiz maddeler",
c=["Doktor tavsiyesiyle kullanıldığına dair sağlık kuruluşu raporu gümrük idaresine ibraz edilen takviye edici gıdalar",
   "Şahsi tedavide kullanılmak üzere getirilen ve doktor reçetesi gümrük idaresine ibraz edilen ilaçlar",
   "Bitki Karantinası Yönetmeliği hükümlerine göre kontrolü yapılan bitki ve bitkisel ürünler",
   "Emniyet Genel Müdürlüğünden uygunluk yazısı alınan, silah ve tüfek dışındaki bıçak ve benzeri aletler"],
sirali=False,
g="2022/9 sayılı Genelge'ye göre 2313 sayılı Uyuşturucu Maddelerin Murakabesi Hakkında Kanun kapsamında bulunmamakla birlikte uyuşturucu ve uyarıcı etkiye haiz maddelerin posta veya hızlı kargo taşımacılığı yoluyla ithali ve ihracı mümkün değildir; maddenin Kanun kapsamı dışında kalması yasağı ortadan kaldırmaz. Buna karşılık şahsi tedavide kullanılacak ilaçların girişine rapor veya reçete ibrazı koşuluyla, bitki ve bitkisel ürünlerin girişine Bitki Karantinası Yönetmeliği hükümlerine göre kontrolü yapılarak, silah ve tüfekler dışındaki bıçak ve benzeri aletlerin serbest dolaşıma sokulmasına ise Emniyet Genel Müdürlüğünden alınacak genel güvenlik ve asayiş yönünden uygunluk yazısının ibrazıyla izin verilir. Takviye edici gıdalar ve sporcu gıdaları, 2026/4 sayılı Genelge ile yapılan değişiklikle Kararın tek ve maktu vergiye ilişkin hükmü kapsamında ithal edilebilir; doktor tavsiyesiyle kullananların sağlık kuruluşu raporu veya reçetesini ibraz etmesi hâlinde posta veya hızlı kargo yoluyla getirilmesine izin verilir. Eski Genelgede bu ürünlerin muafen ithalinin mümkün olmadığı yazdığından, güncellemeyi izlemeyen aday en güçlü çeldirici olan bu seçeneği işaretler. Bu nedenle doğru cevap '2313 sayılı Uyuşturucu Maddelerin Murakabesi Hakkında Kanun kapsamında bulunmamakla birlikte uyuşturucu ve uyarıcı etkiye haiz maddeler' seçeneğidir. (MD Genelge 2022/9 bölüm IV/2, 3, 7, 9, 13)",
kanit=T + " | 2313 sayılı Uyuşturucu Maddelerin Murakabesi Hakkında Kanun kapsamında bulunmamakla birlikte uyuşturucu ve uyarıcı etkiye haiz maddelerin posta veya hızlı kargo taşımacılığı yoluyla ithali ve ihracı mümkün bulunmamaktadır. || " + T + " | \"sporcu gıdaları\"nın Kararın 62 nci maddesi kapsamında ithali mümkün bulunmaktadır.[10] (2026/4 sayılı Genelge) || " + T + " | hastalıklarına dair sağlık kuruluşundan alınmış bir raporu veya doktorun önerdiğine dair bir reçeteyi || " + T + " | Posta veya hızlı kargo taşımacılığı yoluyla şahsi tedavide kullanılmak üzere getirilen ilaçların, gümrük idaresine belge (sağlık kuruluşundan alınan rapor, doktor raporu veya reçete) ibraz edilmesi koşuluna bağlı olarak, girişine izin verilir. || " + T + " | posta veya hızlı kargo taşımacılığı yoluyla gelen bitki veya bitkisel ürünlerin, söz konusu Yönetmelik hükümlerine göre kontrolü yapılarak ülkeye girişine izin verilir. || " + T + " | Emniyet Genel Müdürlüğünden alınacak genel güvenlik ve asayiş yönünden uygunluk yazısının ibrazı gerekmektedir. || " + T + " | Kararın 45 inci ve 62 nci maddesi kapsamında muafen ithali mümkün bulunmamaktadır.",
yuva=["Aynı bölümün takviye edici gıdalar hükmü: 2026/4 sayılı Genelge ile ithali mümkün hâle geldi, raporla izin verilir (eski Genelgede muafen ithal edilemezdi)",
      "Aynı bölümün ilaç hükmü: rapor veya reçete ibrazıyla girişine izin verilir",
      "Aynı bölümün bitki karantinası hükmü: kontrolü yapılarak girişine izin verilir",
      "Aynı bölümün silah ve bıçak hükmü: silah ve tüfek hariç, Emniyet uygunluk yazısıyla serbest dolaşıma sokulabilir"],
yakinlik="BİREBİR",
tuzak=["SAĞDUYU", "KOMŞU"],
duzey=["AYIRT"],
profil=[5, 3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="2026/4 sayılı Genelge (yürürlük 06.02.2026)",
cikmis="",
kapsamli=False,
),

]
