# Soru Bankası — Bölüm 35: İhracat Rejimi (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
# Kaynak: 36-ihracat.txt (GK 150–151; GY 415–418; İhracat Rejimi Kararı; İhracat Yönetmeliği;
#         İhracı Yasak ve Ön İzne Bağlı Mallara İlişkin Tebliğ (96/31); Bedelsiz İhracat Tebliği (2008/12);
#         Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1) md. 6–19)
K = "36-ihracat.txt"
Q = [

# 1 — GK 150, 151; GY 415/3: rejim tanımı (bulunan ↔ bulunmayan), kontrolün sona ermesi, beyannamesiz çıkış
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="ÖNERMELİ",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 150, 151; Gümrük Yönetmeliği md. 415",
cek="İhracat rejimi serbest dolaşımdaki eşyaya uygulanır; fiili ihraçla gümrük kontrolü sona erer; mektup, kartpostal ve basılmış metinde beyanname aranmaz.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'nin ihracat rejimine ve ihraç edilecek eşyanın beyanına ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. İhracat rejimi, serbest dolaşımda bulunmayan eşyanın ihraç amacıyla Türkiye Gümrük Bölgesi dışına çıkışına ilişkin hükümlerin uygulandığı rejimdir.",
     "II. İhracat, ticaret politikası önlemleri ve gerektiği takdirde ihracat vergileri de dahil olmak üzere çıkış işlemlerine ilişkin hükümlerin uygulanmasıyla gerçekleştirilir.",
     "III. Fiilen ihraç edilmiş sayılan eşya üzerindeki gümrük kontrolü, eşyanın varış ülkesinde gümrük işlemlerine tabi tutulmasıyla sona erer.",
     "IV. Türkiye Gümrük Bölgesinden çıkacak eşyanın gümrük beyannamesine tabi olmayacağı hâl ve şartlar yönetmelikle belirlenir; elektronik ortamda olanlar da dahil mektuplar, kartpostallar ve basılmış metinler için gümrük beyannamesi aranmaz.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve IV",
c=["I ve II", "III ve IV", "I, II ve IV", "II, III ve IV"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre ihracat rejimi, serbest dolaşımda bulunan eşyanın ihraç amacıyla Türkiye Gümrük Bölgesi dışına çıkışına ilişkin hükümlerin uygulandığı rejimdir; I. ifadede 'bulunan' kaydı 'bulunmayan' olarak değiştirildiği için ifade yanlıştır. Kanuna göre ihracat, ticaret politikası önlemleri ve gerektiği takdirde ihracat vergileri de dahil olmak üzere çıkış işlemlerine ilişkin hükümlerin uygulanmasıyla gerçekleştirilir (II doğru). İhraç eşyası, beyannamenin tescili sırasındaki durum ve niteliğini gümrük kontrolünden çıktığı sırada da aynen muhafaza edip bu hâliyle Türkiye Gümrük Bölgesini terk ettiğinde fiilen ihraç edilmiş sayılır ve bu durumda eşya üzerindeki gümrük kontrolü sona erer; kontrolün varış ülkesindeki işlemlere kadar sürdüğünü söyleyen III yanlıştır. Kanun, beyannameye tabi olmayacak hâl ve şartların yönetmelikle belirleneceğini öngörür; Gümrük Yönetmeliği de elektronik ortamda olanlar dahil mektuplar, kartpostallar ve basılmış metinler ile yolcunun kişisel bagajı kapsamındaki eşya için gümrük beyannamesi aranmayacağını düzenler (IV doğru). En güçlü çeldirici 'I, II ve IV' seçeneğidir: Kanundaki tanım ile I. ifade arasındaki fark tek bir kelimedir ve hızlı okuyan aday değişikliği görmez. Bu nedenle doğru cevap 'II ve IV' seçeneğidir. (MD GK 150, 151; GY 415)",
kanit=K + " | İhracat rejimi, serbest dolaşımda bulunan eşyanın ihraç amacıyla Türkiye Gümrük Bölgesi dışına çıkışına ilişkin hükümlerin uygulandığı rejimdir || " + K + " | İhracat, ticaret politikası önlemleri ve gerektiği takdirde ihracat vergileri de dahil olmak üzere çıkış işlemlerine ilişkin hükümlerin uygulanmasıyla gerçekleştirilir || " + K + " | Bu durumda, ihraç eşyası üzerindeki gümrük kontrolü[132] sona erer || " + K + " | gümrük beyannamesine tabi olmayacağı hal ve şartlar yönetmelikle belirlenir || " + K + " | Elektronik ortamda olanlar da dahil, mektuplar, kartpostallar ve basılmış metinler ile yolcunun kişisel bagajı kapsamındaki eşya için gümrük beyannamesi aranmaz",
yuva=["I ve II: Kanundaki tanımda 'serbest dolaşımda bulunan' kaydını gözden kaçıran, Yönetmelikteki beyannamesiz çıkış hükmünü bilmeyen aday",
      "III ve IV: gümrük kontrolünün eşyanın Türkiye Gümrük Bölgesini terkiyle sona erdiğini bilmeyen aday (Kanunun fiili ihracat hükmü)",
      "I, II ve IV: ihracat rejimi tanımındaki tek kelime değişikliğini görmeyen aday",
      "II, III ve IV: Kanunun fiili ihracat hükmündeki 'gümrük kontrolü sona erer' kaydını bilmeyen aday"],
yakinlik="PARAFRAZ",
tuzak=["TERSİNE", "TERİM", "KOMŞU"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/68; 2024/45",
kapsamli=False,
),

# 2 — GK 151: fiili ihracat (boşluk: tescil anı ve TGB'yi terk)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="BOŞLUK",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 151",
cek="İhraç eşyası, beyanname tescilindeki durum ve niteliğini koruyarak Türkiye Gümrük Bölgesini terk ederse fiilen ihraç edilmiş sayılır.",
kok=["4458 sayılı Gümrük Kanunu'nun fiili ihracata ilişkin hükmü aşağıda boşluklu olarak verilmiştir:",
     "\"İhraç eşyası, buna ilişkin gümrük beyannamesinin ………… sırasında bulunduğu durum ve niteliğini gümrük kontrolünden çıktığı sırada da aynen muhafaza etmesi ve bu haliyle ………… koşuluyla fiilen ihraç edilmiş sayılır.\"",
     "Yukarıdaki cümlede boş bırakılan yerlere sırasıyla aşağıdakilerden hangisi gelmelidir?"],
d="tescili – Türkiye Gümrük Bölgesini terk etmesi",
c=["muayenesi – Türkiye Gümrük Bölgesini terk etmesi",
   "kapatılması – Türkiye Gümrük Bölgesini terk etmesi",
   "tescili – çıkış gümrük idaresine sunulması",
   "İhracatçı Birlikleri Genel Sekreterliğince onaylanması – taşıta yüklenmesi"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre ihraç eşyası, buna ilişkin gümrük beyannamesinin tescili sırasında bulunduğu durum ve niteliğini gümrük kontrolünden çıktığı sırada da aynen muhafaza etmesi ve bu hâliyle Türkiye Gümrük Bölgesini terk etmesi koşuluyla fiilen ihraç edilmiş sayılır; bu durumda eşya üzerindeki gümrük kontrolü sona erer. Karşılaştırmada esas alınan an beyannamenin tescilidir; muayene, beyannamenin kapatılması veya İhracatçı Birlikleri Genel Sekreterliğinin onayı bu hükümde esas alınan an değildir. İkinci koşul ise eşyanın çıkış gümrük idaresine sunulması ya da taşıta yüklenmesi değil, Türkiye Gümrük Bölgesini fiilen terk etmesidir; Gümrük Yönetmeliği de deniz ve hava yoluyla çıkışlarda terk tarihi olarak yükleme tarihini değil, taşıtın hareket ettiği tarihi kabul eder. En güçlü çeldirici 'kapatılması' ifadesini içeren seçenektir: beyannamenin kapatılması, Gümrük Yönetmeliği'nde geçici depolama yerlerine konulmaksızın ihraç edilen eşya için iki aylık süreye bağlanan ayrı bir işlemdir. Bu nedenle doğru cevap 'tescili – Türkiye Gümrük Bölgesini terk etmesi' seçeneğidir. (MD GK 151; GY 416, 417)",
kanit=K + " | İhraç eşyası, buna ilişkin gümrük beyannamesinin tescili sırasında bulunduğu durum ve niteliğini gümrük kontrolünden[131] çıktığı sırada da aynen muhafaza etmesi ve bu haliyle Türkiye Gümrük Bölgesini terk etmesi koşuluyla fiilen ihraç edilmiş sayılır || " + K + " | Deniz ve hava yoluyla çıkışlarda, eşyanın yüklendiği deniz veya hava taşıtının hareket ettiği || " + K + " | Geçici depolama yerlerine konulmaksızın ihraç edilecek eşyanın beyanname kapatma süresi iki aydır",
yuva=["Kanunun beyan hükümleri: beyandan sonra yapılan muayene aşaması; fiili ihracatta esas alınan an tescildir",
      "Gümrük Yönetmeliği: geçici depolamaya konulmaksızın ihraç edilen eşyada beyannamenin iki ay içinde kapatılması",
      "Gümrük Kanunu tanımları: eşyanın Türkiye Gümrük Bölgesini terk etmeden önce sunulduğu çıkış gümrük idaresi",
      "İhracat Yönetmeliği: beyannamenin İBGS'ye onaylatılması; Gümrük Yönetmeliği: deniz/hava yolunda yükleme değil hareket tarihi"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "TERİM", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/68",
kapsamli=False,
),

# 3 — GY 415/2: beyanname yerine işlemleri yürütülen belgeler (tam liste)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="KAPSAM",
z="O",
madde="Gümrük Yönetmeliği md. 415",
cek="İhracatta beyanname yerine işlemleri yürütülen belgeler: sözlü beyan formu, özel fatura, kumanya listesi, ATA ve CPD karneleri, Form 302.",
kok=["Gümrük Yönetmeliği'nin ihracat rejimine ilişkin beyan hükümlerine göre, ihracına izin verilen eşyanın gümrük işlemlerinin gümrük beyannamesi yerine kendileri ile yürütüldüğü belgeler aşağıdakilerin hangisinde tam olarak verilmiştir?"],
d="Sözlü beyan formu, özel fatura, kumanya listesi, ATA ve CPD karneleri, Form 302 belgesi",
c=["Sözlü beyan formu, özel fatura, kumanya listesi, TIR ve CPD karneleri, Form 302 belgesi",
   "Sözlü beyan formu, proforma fatura, kumanya listesi, ATA ve CPD karneleri, Form 302 belgesi",
   "Sözlü beyan formu, özel fatura, Bedelsiz İhracat Formu, ATA ve CPD karneleri, Form 302 belgesi",
   "Sözlü beyan formu, özel fatura, kumanya listesi, ATA ve CPD karneleri, Elçilik Mektubu"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre Türkiye Gümrük Bölgesinden ihraç edilecek eşya kural olarak ilgili gümrük idarelerine gümrük beyannamesi ile beyan edilir; ancak sözlü beyan formu, özel fatura, kumanya listesi, ATA ve CPD karneleri ve Form 302 belgesi ile ihracına izin verilen eşyanın gümrük işlemleri bu belgeler ile yürütülür. Liste beş kalemdir ve tam olarak yalnızca bu seçenekte yer alır. TIR karnesi ve Elçilik Mektubu, Yönetmeliğin genel beyan hükümlerinde gümrük beyannamesi yerine kullanılan belgeler arasında sayılır, ancak ihracat beyanına ilişkin bu listede yer almaz; proforma fatura, geçici ihracatta sergi ve fuar eşyasının beyannamesine eklenen belgedir; Bedelsiz İhracat Formu ise 250.000 ABD Doları ve üzerindeki bazı bedelsiz ihracat başvurularında İhracatçı Birlikleri Genel Sekreterliğine verilen formdur. En güçlü çeldirici TIR karnesini içeren seçenektir; karne adlarının benzerliği ve genel listedeki yeri adayı yanıltır. Bu nedenle doğru cevap 'Sözlü beyan formu, özel fatura, kumanya listesi, ATA ve CPD karneleri, Form 302 belgesi' seçeneğidir. (MD GY 415; GY 131)",
kanit=K + " | Sözlü beyan formu, özel fatura, kumanya listesi, ATA ve CPD Karneleri ve Form 302 belgesi ile ihracına izin verilen eşyanın gümrük işlemleri bu belgeler ile yürütülür || 17-BEYAN.txt | Elçilik Mektubu, Kurye Mektubu, TIR Karnesi, ATA Karnesi, Kumanya Listesi, Özel Fatura || " + K + " | Bu eşyaya ilişkin kesin satış faturası aranmayarak proforma fatura veya sevk irsaliyesinin beyannameye eklenmesi sağlanır || " + K + " | ekteki Bedelsiz İhracat Formu doldurularak İhracatçı Birlikleri Genel Sekreterliklerine yapılır",
yuva=["Gümrük Yönetmeliği genel beyan hükmü: TIR karnesi beyanname yerine kullanılan belgelerdendir, ihracat listesinde yoktur",
      "Geçici İhracat Tebliği: sergi ve fuar eşyasının beyannamesine proforma fatura veya sevk irsaliyesi eklenir",
      "Bedelsiz İhracat Tebliği: 250.000 ABD Doları ve üzeri başvurularda doldurulan Bedelsiz İhracat Formu",
      "Gümrük Yönetmeliği genel beyan hükmü: Elçilik Mektubu beyanname yerine kullanılan belgelerdendir, ihracat listesinde yoktur"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "KOMŞU", "TERİM"],
duzey=["TANIMA"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2024/45",
kapsamli=False,
),

# 4 — GY 416, 418: Türkiye Gümrük Bölgesini terk tarihi (vaka: serbest bölge, hava yolu, taşıta teslim)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="OLAY",
z="Z",
madde="Gümrük Yönetmeliği md. 416, 418",
cek="Terk tarihi: kara yolunda serbest bölgeye fiilen giriş, hava yolunda taşıtın hareketi, dış sefer taşıtına teslimde teslim tarihidir.",
kok=["(X) firmasının üç ayrı ihracat sevkiyatına ilişkin bilgiler şöyledir:",
     "- Birinci sevkiyatta eşya kara yoluyla bir serbest bölgeye gönderilmiş; gümrük idaresince çıkış işlemleri 2 Mayıs'ta tamamlanmış, eşya 3 Mayıs'ta serbest bölgeye fiilen girmiş ve 9 Mayıs'ta serbest bölgeden yabancı bir ülkeye gönderilmiştir.",
     "- İkinci sevkiyatta eşya 4 Mayıs'ta uçağa yüklenmiş, uçak 5 Mayıs'ta hareket etmiştir.",
     "- Üçüncü sevkiyatta serbest dolaşımda bulunan işletme ve donatım eşyası, dış sefere çıkacak bir gemiye 6 Mayıs'ta teslim edilmiş, gemi 7 Mayıs'ta limandan hareket etmiştir.",
     "Gümrük Yönetmeliği'ne göre bu sevkiyatlarda eşyanın Türkiye Gümrük Bölgesini terk ettiği tarih olarak kabul edilecek tarihler sırasıyla aşağıdakilerden hangisidir?"],
d="3 Mayıs – 5 Mayıs – 6 Mayıs",
c=["9 Mayıs – 5 Mayıs – 6 Mayıs",
   "3 Mayıs – 4 Mayıs – 6 Mayıs",
   "3 Mayıs – 5 Mayıs – 7 Mayıs",
   "2 Mayıs – 4 Mayıs – 7 Mayıs"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre eşyanın Türkiye Gümrük Bölgesini terk ettiği tarih; kara ve demir yoluyla çıkışlarda gümrük idaresince çıkış işlemleri tamamlanıp kara sınırından yabancı bir ülkeye fiilen çıktığı veya serbest bölgeye fiilen girdiği tarih, deniz ve hava yoluyla çıkışlarda eşyanın yüklendiği deniz veya hava taşıtının hareket ettiği tarih, dış seferde bulunan ya da dış sefere çıkacak deniz ve hava taşıtlarına yapılan teslimlerde ise eşyanın teslim edildiği tarihtir. Birinci sevkiyatta eşyanın serbest bölgeye fiilen girdiği 3 Mayıs esastır; çıkış işlemlerinin tamamlandığı 2 Mayıs ve serbest bölgeden yabancı ülkeye gönderildiği 9 Mayıs esas alınmaz. İkinci sevkiyatta yükleme tarihi değil, uçağın hareket ettiği 5 Mayıs esastır. Üçüncü sevkiyatta kumanya, yağ ve yakıt dışında dış sefere çıkacak taşıta serbest dolaşımdaki işletme ve donatım eşyası teslimi ihracat hükmündedir ve terk tarihi geminin hareketi değil, teslimin yapıldığı 6 Mayıs'tır. Vakada saklanan istisna, taşıtlara yapılan teslimde hareket tarihinin değil teslim tarihinin esas alınmasıdır; en güçlü çeldirici bu nedenle üçüncü sevkiyat için 7 Mayıs'ı gösteren seçenektir. Bu nedenle doğru cevap '3 Mayıs – 5 Mayıs – 6 Mayıs' seçeneğidir. (MD GY 416, 418)",
kanit=K + " | gümrük idaresince çıkış işlemleri tamamlanıp kara sınırından yabancı bir ülkeye fiilen çıktığı veya serbest bölgeye fiilen girdiği || " + K + " | Deniz ve hava yoluyla çıkışlarda, eşyanın yüklendiği deniz veya hava taşıtının hareket ettiği || " + K + " | Dış seferde bulunan ya da dış sefere çıkacak olan deniz ve hava taşıtlarına 418 ve 476 ila 482 nci maddeler çerçevesinde yapılacak teslimlerde eşyanın teslim edildiği || " + K + " | dış seferde bulunan ya da dış sefere çıkacak olan deniz ve hava taşıtlarına serbest dolaşımda bulunan işletme ve donatım eşyası teslimi ihracat hükmündedir",
yuva=["9 Mayıs: serbest bölgeden yabancı ülkeye çıkış; kara yolunda serbest bölgeye fiilen giriş yeterlidir (GY 416 kara ve demir yolu)",
      "4 Mayıs: hava yolunda yükleme tarihi; Yönetmelik hava taşıtının hareket tarihini esas alır",
      "7 Mayıs: deniz yolu çıkışlarındaki hareket kuralı; dış sefer taşıtlarına teslimde teslim tarihi esastır",
      "2 Mayıs ve 4 Mayıs: çıkış işlemlerinin tamamlandığı ve yükleme tarihleri; 7 Mayıs: geminin hareketi"],
yakinlik="ÇIKARIM",
tuzak=["BAŞLANGIÇ", "İSTİSNA", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[1],
olumsuz=False, vaka=True, baslangic=True,
eksen=0, ayna="",
guncellik="",
cikmis="2024/55; 2025/69",
kapsamli=False,
),

# 5 — GY 417/1, 417/3: geçici depolamada bir ay + en çok üç ay; depolamasız ihraçta iki ay + gümrük müdürlüğünce iki ay
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="ÖNERMELİ",
z="O",
madde="Gümrük Yönetmeliği md. 417",
cek="İhracat amaçlı geçici depolamada süre bir ay, ek süre en çok üç ay; geçici depolamasız ihraçta kapatma iki ay, gümrük müdürlüğünce iki ay uzatma.",
kok=["Gümrük Yönetmeliği'nin ihraç eşyasının geçici depolama süresine ve takip edilmeyen beyannamelere ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. İhracat amacıyla geçici depolama yerlerine konulması talep edilen eşya buralarda bir ay kalabilir.",
     "II. Bu eşya için beyanname tescil edilip edilmediğine bakılmaksızın bir aylık süre içinde ek süre talebinde bulunulması hâlinde, gümrük müdürlüklerince en çok iki aya kadar ek süre verilebilir.",
     "III. Geçici depolama yerlerine konulmaksızın ihraç edilecek eşyanın beyanname kapatma süresi iki aydır.",
     "IV. Geçici depolama yerlerine konulmaksızın ihraç edilecek eşyanın beyanname kapatma süresi, bölge müdürlüklerince makul sebeplerle en çok iki ay uzatılabilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve III",
c=["I ve II", "III ve IV", "I, II ve III", "I, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre ihracat veya yeniden ihracat amacıyla geçici depolama yerlerine konulması talep edilen eşya buralarda bir ay kalabilir (I doğru). Beyanname tescil edilip edilmediğine bakılmaksızın bu süre içinde ek süre talep edilirse gümrük müdürlüklerince en çok üç aya kadar ek süre verilebilir; II. ifadedeki 'iki ay' bu nedenle yanlıştır. Geçici depolama yerlerine konulmaksızın ihraç edilecek eşyanın beyanname kapatma süresi iki aydır (III doğru); bu süre bölge müdürlüklerince değil, gümrük müdürlüklerince makul sebeplerle en çok iki ay uzatılabilir ve süreler içinde işlemleri tamamlanmayan beyannameler iptal edilir (IV yanlış). En güçlü çeldirici 'I, II ve III' seçeneğidir: aynı maddede geçen iki aylık kapatma ve uzatma süreleri, geçici depolamadaki üç aylık ek süreyle karıştırıldığında II. ifade de doğru sanılır. Bu nedenle doğru cevap 'I ve III' seçeneğidir. (MD GY 417)",
kanit=K + " | ihracat veya yeniden ihracat amacıyla geçici depolama yerlerine konulması talep edilen eşya, buralarda bir ay kalabilir || " + K + " | beyanname tescil edilip edilmediğine bakılmaksızın bu süre içinde ek süre talebinde bulunulması halinde, gümrük müdürlüklerince en çok üç aya kadar ek süre verilebilir || " + K + " | Geçici depolama yerlerine konulmaksızın ihraç edilecek eşyanın beyanname kapatma süresi iki aydır || " + K + " | Bu süre gümrük müdürlüklerince makul sebeplerle en çok iki ay uzatılabilir",
yuva=["I ve II: üç aylık ek süreyi aynı maddedeki iki aylık kapatma ve uzatma süresiyle karıştıran aday",
      "III ve IV: uzatma makamını bölge müdürlüğüyle karıştıran ve bir aylık süreyi bilmeyen aday",
      "I, II ve III: geçici depolamadaki üç aylık ek süreyi iki ay sanan aday",
      "I, III ve IV: uzatma yetkisinin gümrük müdürlüklerinde olduğunu bilmeyen aday"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "MAKAM", "KOMŞU"],
duzey=["AYIRT"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=13, ayna="",
guncellik="",
cikmis="2022/82; 2024/46; 2024/97; 2025/25",
kapsamli=False,
),

# 6 — GY 417/2: süresinde kaldırılmayan eşya; tebliğden otuz gün, terk, beyanname iptali (vaka)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="OLAY",
z="Z",
madde="Gümrük Yönetmeliği md. 417",
cek="Süresinde kaldırılmayan ihraç eşyası, tebliğden itibaren otuz gün içinde çıkarılmazsa gümrüğe terk edilmiş sayılır; tescilli beyanname iptal edilir.",
kok=["İhracat amacıyla geçici depolama yerine konulan eşyaya ilişkin bilgiler şöyledir:",
     "- Eşya 3 Mart 2026 tarihinde geçici depolama yerine konulmuş, ihracat beyannamesi aynı gün tescil edilmiştir.",
     "- Bir aylık süre içinde ek süre talebinde bulunulmamış, gümrük işlemleri bitirilerek eşya bu süre içinde yerinden kaldırılmamıştır.",
     "- Gümrük idaresince gümrük yükümlüsüne yapılan tebligat 20 Nisan 2026 tarihinde tebliğ edilmiştir.",
     "Gümrük Yönetmeliği'ne göre bu eşyaya ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Eşya 20 Mayıs 2026 tarihine kadar geçici depolama yerinden çıkarılmazsa gümrüğe terk edilmiş sayılır ve tescil edilmiş beyanname iptal edilir.",
c=["Eşya 3 Mayıs 2026 tarihine kadar geçici depolama yerinden çıkarılmazsa gümrüğe terk edilmiş sayılır ve tescil edilmiş beyanname iptal edilir.",
   "Eşya 20 Mayıs 2026 tarihine kadar geçici depolama yerinden çıkarılmazsa gümrüğe terk edilmiş sayılır; ancak tescil edilmiş beyanname geçerliliğini korur.",
   "Eşya 20 Haziran 2026 tarihine kadar geçici depolama yerinden çıkarılmazsa gümrüğe terk edilmiş sayılır ve tescil edilmiş beyanname iptal edilir.",
   "Eşya 3 Temmuz 2026 tarihine kadar geçici depolama yerinden çıkarılmazsa gümrüğe terk edilmiş sayılır ve tescil edilmiş beyanname iptal edilir."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre ihracat amacıyla geçici depolama yerlerine konulan eşya buralarda bir ay kalabilir; ek süre ancak bu süre içinde talepte bulunulması hâlinde gümrük müdürlüklerince en çok üç aya kadar verilebilir. Bir aylık süre ve verilen ek süre içinde gümrük işlemleri bitirilerek yerinden kaldırılmayan eşya için gümrük yükümlüsüne tebligat yapılır; tebliğ tarihinden itibaren otuz gün içinde eşyanın geçici depolama yerinden çıkarılması, aksi takdirde gümrüğe terk edilmiş sayılacağı bildirilir. Bu süre içinde de çıkarılmayan eşya gümrüğe terk edilmiş sayılır, tasfiye hükümlerine göre işlem yapılır ve tescil edilmiş beyanname varsa iptal edilir. Vakada ek süre talep edilmediğinden ek süre söz konusu değildir; otuz günlük süre bir aylık sürenin bittiği 3 Nisan'dan değil, tebliğ tarihi olan 20 Nisan 2026'dan başlar ve 20 Mayıs 2026'da dolar. En güçlü çeldirici 3 Mayıs 2026 tarihini içeren seçenektir; süreyi bir aylık sürenin bitiminden başlatan aday bu şıkka gider. 20 Haziran tarihi geçici depolamasız ihraçtaki iki aylık kapatma süresinden, 3 Temmuz tarihi ise yalnızca talep hâlinde verilebilecek üç aylık ek süreden türetilmiştir. Bu nedenle doğru cevap 'Eşya 20 Mayıs 2026 tarihine kadar geçici depolama yerinden çıkarılmazsa gümrüğe terk edilmiş sayılır ve tescil edilmiş beyanname iptal edilir.' seçeneğidir. (MD GY 417)",
kanit=K + " | Bir aylık süre ve verilen ek süre içinde gümrük işlemleri bitirilerek yerinden kaldırılmayan eşya için gümrük yükümlüsüne tebligat yapılarak, tebliğ tarihinden itibaren otuz gün içinde eşyanın geçici depolama yerinden çıkarılması || " + K + " | Bu süre içinde de yerinden çıkarılmaması halinde eşya gümrüğe terk edilmiş sayılır ve tasfiye hükümlerine göre işlem yapılır || " + K + " | Bu eşyaya ilişkin olarak tescil edilmiş beyanname varsa iptal edilir || " + K + " | bu süre içinde ek süre talebinde bulunulması halinde, gümrük müdürlüklerince en çok üç aya kadar ek süre verilebilir",
yuva=["3 Mayıs 2026: otuz günü tebliğ tarihi yerine bir aylık sürenin bitiminden başlatan hesap",
      "Beyanname geçerliliğini korur: Yönetmelikteki 'tescil edilmiş beyanname varsa iptal edilir' hükmünün tersi",
      "20 Haziran 2026: geçici depolama yerlerine konulmaksızın ihraçtaki iki aylık beyanname kapatma süresi",
      "3 Temmuz 2026: talep hâlinde verilebilecek en çok üç aylık ek süre (vakada talep yok)"],
yakinlik="ÇIKARIM",
tuzak=["BAŞLANGIÇ", "SAYI", "KOMŞU"],
duzey=["UYGULAMA"],
profil=[2],
olumsuz=False, vaka=True, baslangic=True,
eksen=13, ayna="",
guncellik="",
cikmis="2024/46",
kapsamli=False,
),

# 7 — İhracat Rejimi Kararı md. 3: kısıtlama/yasaklama nedenleri (liste dışı: fikri ve sınai mülkiyet)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="KAPSAM_DIŞI",
z="O",
madde="İhracat Rejimi Kararı (95/7623) md. 3, 4",
cek="Bakanlık; piyasa gelişmesi, malda yetersizlik, kamu güvenliği-ahlakı, sağlık, çevre ve sanatsal-tarihi meta nedeniyle ihracatı kısıtlar; fikri mülkiyet sayılmamıştır.",
kok=["İhracat Rejimi Kararı'na göre, ihracatta yetkili merci olan Bakanlığın ihracatta kısıtlama veya yasaklama getirmeye yetkili olduğu nedenler arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="Fikri ve sınai mülkiyet haklarının korunması",
c=["Piyasalarda meydana gelen olağan dışı bir gelişme",
   "İhracata konu malda görülen yetersizlik",
   "Sanatsal, tarihi ve arkeolojik değer taşıyan metanın korunması",
   "Hayvanların, bitkilerin veya çevrenin korunması"],
sirali=False,
g="İhracat Rejimi Kararı'na göre ihracatta yetkili merci olan Bakanlık; piyasalarda meydana gelen olağan dışı bir gelişme, ihracata konu malda görülen yetersizlik, kamu güvenliği, kamu ahlakı, insan sağlığı, hayvanların, bitkilerin veya çevrenin korunması amacına yönelik tedbirler ile sanatsal, tarihi ve arkeolojik değer taşıyan metanın korunması nedenleriyle ihracatta kısıtlama veya yasaklama getirmeye yetkilidir. Kararın ihracat serbestisi hükmü de bütün malların ihracını, bu kısıtlama ve yasaklama yetkisi saklı kalmak üzere serbest kabul eder. Fikri ve sınai mülkiyet haklarının korunması bu sayımda yer almaz; bu gerekçe Gümrük Kanunu'nda Cumhurbaşkanının eşyanın gümrükçe onaylanmış işlem veya kullanıma tabi tutulmasına yasaklama veya kısıtlama koyabileceği gerekçeler arasında sayılmıştır. En güçlü çeldirici sanatsal, tarihi ve arkeolojik değer taşıyan metanın korunmasıdır: bu neden her iki düzenlemede de bulunduğu için aday fikri mülkiyetin de ortak olduğunu düşünür. Bu nedenle doğru cevap 'Fikri ve sınai mülkiyet haklarının korunması' seçeneğidir. (MD İhracat Rejimi Kararı md. 3, 4; GK 55)",
kanit=K + " | Piyasalarda meydana gelen olağan dışı bir gelişme, ihracata konu malda görülen yetersizlik, kamu güvenliği, kamu ahlakı, insan sağlığı, hayvanların, bitkilerin veya çevrenin korunması amacına yönelik tedbirler, sanatsal, tarihi ve arkeolojik değer taşıyan metanın korunması nedenleriyle ihracatta kısıtlama veya yasaklama getirmeye || 16-GOBİK VE SAHTE EŞYA.txt | fikri ve sınai mülkiyet haklarının korunması gerekçeleri ile eşyanın gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulmasına yasaklama veya kısıtlamalar koyabilir",
yuva=["Kararın yetki hükmü: piyasalarda meydana gelen olağan dışı gelişme (sayılmış)",
      "Kararın yetki hükmü: ihracata konu malda görülen yetersizlik (sayılmış)",
      "Kararın yetki hükmü: sanatsal, tarihi ve arkeolojik değer taşıyan meta (sayılmış; Gümrük Kanunu'nda da var)",
      "Kararın yetki hükmü: hayvanların, bitkilerin veya çevrenin korunması (sayılmış)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU", "KOMŞU"],
duzey=["TANIMA"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 8 — İhracat Rejimi Kararı md. 3 son paragraflar, 4, geçici madde: destekleme kaynağı TCMB ↔ Eximbank
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="YANLIŞ",
z="Z",
madde="İhracat Rejimi Kararı (95/7623) md. 3, 4, Geçici Madde",
cek="Kararla yapılacak desteklemenin kaynağı TCMB nezdindeki Destekleme ve Fiyat İstikrar Fonu ile ilgili diğer fon ve kaynaklardır; Eximbank değil.",
kok=["İhracat Rejimi Kararı'nın ihracatta yetki, ihracat serbestisi, ihracatın koordinasyonu ve başlamış işlemlere ilişkin hükümlerine göre aşağıdakilerden hangisi yanlıştır?"],
d="Bu Karar kapsamında yapılacak desteklemenin kaynağını, Türkiye İhracat Kredi Bankası (Eximbank) nezdindeki Destekleme ve Fiyat İstikrar Fonu ile ilgili diğer fon ve kaynaklar teşkil eder.",
c=["İhracat işlemlerinde, ilgili mevzuatla belirlenmiş olanlar dışında hiçbir belge aranmaz.",
   "Kamu kurum ve kuruluşları, madde bazında miktar veya dönem itibarıyla ihracatın kısıtlanmasına veya yasaklanmasına yönelik kanun ve kararnamelerin hazırlanması aşamasında Bakanlığın görüşünü alırlar.",
   "Bakanlık, yetkilerinin kullanılması sırasında mevzuat hükümleri çerçevesinde İhracatçı Birliklerini, Türkiye İhracatçılar Meclisini ve uluslararası gözetim şirketlerini görevlendirebilir.",
   "Kararın yürürlüğe girmesinden önce başlamış işlemlere, lehte olması hâlinde önceki hükümlere göre devam edilir."],
sirali=False,
g="İhracat Rejimi Kararı'na göre Karar kapsamında yapılacak desteklemenin kaynağını, Türkiye Cumhuriyet Merkez Bankası nezdindeki Destekleme ve Fiyat İstikrar Fonu ile ilgili diğer fon ve kaynaklar teşkil eder; şıkta Merkez Bankası yerine Türkiye İhracat Kredi Bankası yazıldığı için ifade yanlıştır. Eximbank Kararda, Bakanlığın genel ihracat politikası hedefleri çerçevesinde bu bankanın ihracatla ilgili programlarını müştereken tespit etme yetkisi bağlamında geçer; en güçlü çeldiricinin kaynağı bu komşu yetki hükmüdür. Diğer ifadeler Kararla örtüşür: ihracat işlemlerinde ilgili mevzuatla belirlenmiş olanlar dışında hiçbir belge aranmaz; kamu kurum ve kuruluşları ihracatı kısıtlayan veya yasaklayan kanun ve kararnamelerin hazırlanması aşamasında Bakanlığın görüşünü alır; Bakanlık yetkilerini kullanırken İhracatçı Birlikleri, Türkiye İhracatçılar Meclisi, İhracatı Geliştirme Etüd Merkezi, uluslararası gözetim şirketleri ve ilgili diğer kurum ve kuruluşları görevlendirebilir; Kararın yürürlüğünden önce başlamış işlemlere lehte olması hâlinde önceki hükümlere göre devam edilir. Bu nedenle doğru cevap 'Bu Karar kapsamında yapılacak desteklemenin kaynağını, Türkiye İhracat Kredi Bankası (Eximbank) nezdindeki Destekleme ve Fiyat İstikrar Fonu ile ilgili diğer fon ve kaynaklar teşkil eder.' seçeneğidir. (MD İhracat Rejimi Kararı md. 3, 4, geçici madde)",
kanit=K + " | Türkiye Cumhuriyet Merkez Bankası nezdindeki Destekleme ve Fiyat İstikrar Fonu ile, ilgili diğer fon ve kaynaklar teşkil eder || " + K + " | İhracat işlemlerinde, ilgili mevzuatla belirlenmiş olanlar dışında hiçbir belge aranmaz || " + K + " | kanun ve kararnamelerin hazırlanması aşamasında Dış Ticaret Müsteşarlığı'nın bağlı olduğu Bakanlığın görüşünü alırlar || " + K + " | İhracatçı Birlikleri, Türkiye İhracatçılar Meclisi, İhracatı Geliştirme Etüd Merkezi, uluslararası gözetim şirketleri ve ilgili diğer kurum ve kuruluşları görevlendirebilir || " + K + " | lehte olması halinde önceki hükümlere göre devam edilir || " + K + " | Türkiye İhracat Kredi Bankası (Eximbank) tarafından ihracatla ilgili olarak gerçekleştirilecek programları müştereken tespit etmeye",
yuva=["İhracat serbestisi hükmü: ilgili mevzuatla belirlenenler dışında belge aranmaz (doğru ifade)",
      "Koordinasyon hükmü: kısıtlayıcı kanun ve kararnamelerin hazırlanması aşamasında Bakanlığın görüşü alınır (doğru ifade)",
      "Yetki hükmünün son paragrafı: görevlendirilebilecek kurum ve kuruluşlar (doğru ifade)",
      "Geçici madde: başlamış işlemlerde lehte olan önceki hükümler uygulanır (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 9 — İhracat Yönetmeliği md. 4: tanımdan ad (bağlı muamele ↔ takas)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="KAVRAM",
z="K",
madde="İhracat Yönetmeliği md. 4, 13",
cek="İhracat Yönetmeliği'nde ikiden fazla taraf arasında yapılan takas işlemi bağlı muamele olarak tanımlanır.",
kok=["İhracat Yönetmeliği'nde \"ikiden fazla taraf arasında yapılan takas işlemi\" şeklinde tanımlanan kavram aşağıdakilerden hangisidir?"],
d="Bağlı muamele",
c=["Takas", "Offset", "Transit ticaret", "Konsinye ihracat"],
sirali=False,
g="İhracat Yönetmeliği'ne göre bağlı muamele, ikiden fazla taraf arasında yapılan takas işlemidir. Takas ise ihraç veya ithal edilen mal veya hizmet bedelinin kısmen veya tamamen mal, hizmet veya döviz ile karşılanması işlemidir; tanımında taraf sayısına yer verilmez. Offset, kamu kuruluşlarınca açılan uluslararası ihaleler çerçevesinde ihaleyi kazanan firma veya kuruluşun Türkiye'de üretilen malları ve hizmetleri ihraç etmesi ya da taahhüt gereğince Türkiye'nin ihracat potansiyelini geliştirmesine yönelik işlemleri; transit ticaret, yurt dışında veya serbest bölgede yerleşik bir firmadan ya da antrepodan satın alınan malın yine yurt dışında veya serbest bölgede yerleşik bir firmaya ya da antrepoya satılmasını; konsinye ihracat ise kesin satışı daha sonra yapılmak üzere malın yurt dışına gönderilmesini ifade eder. Takas ve bağlı muamele işlemleri yürürlükteki ihracat ve ithalat rejimleri çerçevesinde yürütülür. En güçlü çeldirici 'Takas' seçeneğidir: tanımda geçen takas kelimesi adayı genel kavrama götürür, oysa 'ikiden fazla taraf' unsuru bağlı muameleyi ayırır. Bu nedenle doğru cevap 'Bağlı muamele' seçeneğidir. (MD İhracat Yönetmeliği md. 4, 13)",
kanit=K + " | Bağlı muamele: İkiden fazla taraf arasında yapılan takas işlemini || " + K + " | Takas: İhraç veya ithal edilen mal veya hizmet bedelinin, kısmen veya tamamen mal, hizmet veya döviz ile karşılanması işlemini || " + K + " | Takas ve bağlı muamele işlemleri yürürlükteki ihracat ve ithalat rejimleri çerçevesinde yürütülür",
yuva=["Tanımlar: takas — mal veya hizmet bedelinin mal, hizmet veya dövizle karşılanması (taraf sayısı unsuru yok)",
      "Tanımlar: offset — uluslararası kamu ihalesini kazanan firmanın ihracat taahhüdü",
      "Tanımlar: transit ticaret — yurt dışından veya serbest bölgeden alınan malın yurt dışına veya serbest bölgeye satışı",
      "Tanımlar: konsinye ihracat — kesin satışı sonra yapılmak üzere malın yurt dışına gönderilmesi"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 10 — İhracat Yönetmeliği md. 4: başlamış işlem (eşleştirme; konsinye – iznin verilmesi, kesin satış değil)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="EŞLEŞTİRME",
z="Z",
madde="İhracat Yönetmeliği md. 4",
cek="Başlamış işlem: kayda bağlıda kaydın, konsinyede iznin verilmesi; bedelsizde beyanname tescili; offsette anlaşma imzası; genel esaslarda İBGS onayı.",
kok=["İhracat Yönetmeliği'ndeki \"başlamış işlem\" tanımına göre aşağıdaki ihracat şekli – işlemin başlamış sayılması için gerçekleşmiş olması gereken durum eşleştirmelerinden hangisi yanlıştır?"],
d="Konsinye ihracat – Malın yurt dışında nihai kullanıcıya kesin satışının yapılmış olması",
c=["Kayda bağlı ihracat – İhracatçı Birlikleri Genel Sekreterliğince kaydın verilmiş olması",
   "Bedelsiz ihracat – Gümrük beyannamesi düzenlenmesi gereken hâllerde beyannamenin tescil edilmiş olması",
   "Offset kapsamında ihracat – Offset anlaşmasının imzalanmış olması",
   "Genel esaslar çerçevesinde ihracat – Gümrük beyannamesinin İhracatçı Birlikleri Genel Sekreterliğine onaylatılmış olması"],
sirali=False,
g="İhracat Yönetmeliği'nde başlamış işlem, ihracat şekline göre ayrı ayrı tanımlanmıştır: kayda bağlı ihracatta İhracatçı Birlikleri Genel Sekreterliğince kaydın verilmiş olması; bedelsiz ihracatta, gümrük mevzuatı uyarınca gümrük beyannamesi düzenlenmesi gereken hâllerde beyannamenin tescil edilmiş olması; offset kapsamındaki ihracatta offset anlaşmasının imzalanmış olması; genel esaslar çerçevesinde gümrük beyannamesinin İhracatçı Birlikleri Genel Sekreterliğine onaylatılmış olması; müsaadeye bağlı ihracatta müsaadenin verilmiş olması. Konsinye ihracat ile yurt dışı müteahhitlik ve teknik müşavirlik kapsamındaki ihracatta ise işlem, iznin verilmiş olmasıyla başlamış sayılır. Malın nihai kullanıcıya satılması Yönetmelikte 'kesin satış' olarak tanımlanır ve konsinye ihracatın sonraki aşamasıdır; bu nedenle eşleştirme yanlıştır. En güçlü tuzak, konsinye ihracat tanımının kesin satışa atıf yapmasıdır. Bu nedenle doğru cevap 'Konsinye ihracat – Malın yurt dışında nihai kullanıcıya kesin satışının yapılmış olması' seçeneğidir. (MD İhracat Yönetmeliği md. 4)",
kanit=K + " | Konsinye ihracat ile yurt dışı müteahhitlik ve teknik müşavirlik kapsamındaki ihracatta, iznin verilmiş olmasını || " + K + " | Kesin satış: Konsinye ihracatta malın nihai kullanıcıya satılmasını || " + K + " | Kayda bağlı ihracatta, İhracatçı Birlikleri Genel Sekreterliğince kaydın verilmiş olmasını || " + K + " | gümrük beyannamesi düzenlenmesi gereken hâllerde gümrük beyannamesinin tescil edilmiş olmasını || " + K + " | Offset kapsamında ihracatta offset anlaşmasının imzalanmış olmasını || " + K + " | Genel esaslar çerçevesinde, gümrük beyannamesinin İhracatçı Birlikleri Genel Sekreterliğine onaylatılmış olmasını",
yuva=["Başlamış işlem tanımı: kayda bağlı ihracatta kaydın verilmesi (doğru eşleştirme)",
      "Başlamış işlem tanımı: bedelsiz ihracatta beyanname gereken hâllerde tescil (doğru eşleştirme)",
      "Başlamış işlem tanımı: offset kapsamında anlaşmanın imzalanması (doğru eşleştirme)",
      "Başlamış işlem tanımı: genel esaslarda beyannamenin İBGS'ye onaylatılması (doğru eşleştirme)"],
yakinlik="PARAFRAZ",
tuzak=["BAŞLANGIÇ", "TERİM", "KOMŞU"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 11 — İhracat Yönetmeliği md. 7: kayda alınmış beyannamenin sunulma süresi (sayısal, sıralı)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="SÜRE",
z="O",
madde="İhracat Yönetmeliği md. 7",
cek="Kayda alınmış beyanname, İBGS onay tarihinden itibaren uzatılmamak üzere otuz gün içinde gümrüğe sunulur; kısıtlamalı ülkelerde Bakanlık farklı belirleyebilir.",
kok=["İhracat Yönetmeliği'ne göre, ihracı kayda bağlı mallara ilişkin olarak İhracatçı Birlikleri Genel Sekreterliğince kayda alınmış gümrük beyannamesinin gümrük idarelerine sunulma süresi, kural olarak İhracatçı Birlikleri Genel Sekreterliğinin onay tarihinden itibaren uzatılmamak üzere kaç gündür?"],
d="30",
c=["5", "15", "60", "120"],
sirali=True,
siklar=["5", "15", "30", "60", "120"],
g="İhracat Yönetmeliği'ne göre ihracı kayda bağlı mallar Bakanlıkça yayımlanacak tebliğ ile belirlenir ve bu malların ihracından önce gümrük beyannamelerinin İhracatçı Birlikleri Genel Sekreterliğince kayda alınması gerekir. Kayda alınmış gümrük beyannamesinin gümrük idarelerine sunulma süresi, Genel Sekreterliğin onay tarihinden itibaren uzatılmamak üzere otuz gündür. Ancak ülkemiz ihraç ürünlerine miktar kısıtlaması uygulayan ülkelere yapılan, kısıtlama kapsamındaki malın ihracına ait kayıt meşruhatı düşülerek onaylanmış beyannamelerde bu süre Bakanlıkça otuz günden kısa veya uzun belirlenebilir; kökteki 'kural olarak' ifadesi bu istisnayı dışarıda bırakır. Diğer değerler komşu sürelerdir: beş gün, Genel Sekreterliğin konsinye kesin satış bilgisini aracı bankaya ve gümrük idaresine bildirme süresi; on beş gün, fuar ve sergi beyannamelerinin onaylı örneğinin kapanış tarihinden itibaren gönderilme süresi; altmış gün, Gümrük Yönetmeliği'ndeki iki aylık beyanname kapatma süresinin karşılığı; yüz yirmi gün ise konsinye ihracatta kesin satışın ihracatçı tarafından bildirilme süresidir. En güçlü çeldirici 15'tir: İhracatçı Birlikleri Genel Sekreterliğine beyanname gönderilmesine ilişkin fuar süresi adayı yanıltır. Bu nedenle doğru cevap '30' seçeneğidir. (MD İhracat Yönetmeliği md. 7, 9, 10)",
kanit=K + " | İhracatçı Birlikleri Genel Sekreterliğince kayda alınmış gümrük beyannamesinin gümrük idarelerine sunulma süresi, İhracatçı Birlikleri Genel Sekreterliğinin onay tarihinden itibaren uzatılmamak üzere otuz gündür || " + K + " | otuz günden daha kısa veya daha uzun olarak Bakanlıkça || " + K + " | malın kesin satışının kendilerine bildirilmesinden itibaren beş gün içinde aracı bankaya || " + K + " | en geç onbeş gün içinde firmanın beyan ettiği İhracatçı Birlikleri Genel Sekreterliğine gönderir || " + K + " | kesin satışının yapılmasından sonraki yüz yirmi gün içinde",
yuva=["5: İhracat Yönetmeliği konsinye hükmü — İBGS'nin kesin satış bilgisini beş gün içinde bildirmesi",
      "15: İhracat Yönetmeliği fuar hükmü — onaylı beyanname örneğinin kapanıştan itibaren en geç on beş günde gönderilmesi",
      "60: Gümrük Yönetmeliği — geçici depolamaya konulmaksızın ihraçta iki aylık beyanname kapatma süresi",
      "120: İhracat Yönetmeliği konsinye hükmü — kesin satıştan sonraki yüz yirmi gün içinde bildirim"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "SAYI", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 12 — İhracat Yönetmeliği md. 9 (06.05.2025 değişik): basitleştirilmiş beyannamede konsinye; süre ihraçtan başlar, uzatılmaz
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="SÜRE",
z="O",
madde="İhracat Yönetmeliği md. 4, 9",
cek="Basitleştirilmiş gümrük beyannamesiyle konsinyede kesin satış ihraç tarihinden itibaren bir yılda yapılır, uzatılmaz; genel kuralda İBGS iki yıl uzatabilir.",
kok=["İhracat Yönetmeliği'ne göre basitleştirilmiş gümrük beyannamesi kapsamında gerçekleştirilen konsinye ihracat işlemlerinde kesin satış süresine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Kesin satışın, malın ihraç tarihinden itibaren bir yıl içinde yapılması gerekir ve bu süre uzatılmaz.",
c=["Kesin satışın, malın ihraç tarihinden itibaren bir yıl içinde yapılması gerekir; bu süre haklı ve zorunlu nedenlerle İhracatçı Birlikleri Genel Sekreterliğince iki yıl daha uzatılabilir.",
   "Kesin satışın, konsinye ihracata ilişkin gümrük beyannamesinin İhracatçı Birlikleri Genel Sekreterliğince onaylandığı tarihten itibaren bir yıl içinde yapılması gerekir ve bu süre uzatılmaz.",
   "Kesin satışın, gümrük beyannamesinin tescil tarihinden itibaren yüz yirmi gün içinde yapılması gerekir ve bu süre uzatılmaz.",
   "Kesin satışın, malın ihraç tarihinden itibaren iki yıl içinde yapılması gerekir ve bu süre uzatılmaz."],
sirali=False,
g="İhracat Yönetmeliği'nin konsinye ihracata ilişkin hükümleri, 06.05.2025 tarihli ve 32892 sayılı Resmî Gazete'de yayımlanan değişiklikle yeniden düzenlenmiştir. Genel kurala göre konsinye olarak gönderilen malın ihraç tarihinden itibaren bir yıl içinde kesin satışının yapılması gerekir ve bu süre, haklı ve zorunlu nedenlere istinaden müracaat edilmesi hâlinde izni veren İhracatçı Birlikleri Genel Sekreterliğince iki yıl daha uzatılabilir. Basitleştirilmiş gümrük beyannamesi, posta veya hızlı kargo yoluyla taşınan eşyanın operatör tarafından beyanında kullanılan, basitleştirilmiş veri setine sahip elektronik gümrük beyannamesidir; bu kapsamda gerçekleştirilen konsinye ihracat işlemlerinde de kesin satışın ihraç tarihinden itibaren bir yıl içinde yapılması gerekir, ancak bu süre uzatılmaz. Sürenin başlangıcı, beyannamenin İhracatçı Birlikleri Genel Sekreterliğince onaylandığı tarih veya tescil tarihi değil, malın ihraç tarihidir; yüz yirmi gün ise kesin satıştan sonra ihracatçının bildirim süresidir. En güçlü çeldirici, genel kuraldaki iki yıllık uzatma imkânını bu işlemlere de taşıyan seçenektir. Bu nedenle doğru cevap 'Kesin satışın, malın ihraç tarihinden itibaren bir yıl içinde yapılması gerekir ve bu süre uzatılmaz.' seçeneğidir. (MD İhracat Yönetmeliği md. 4, 9)",
kanit=K + " | Konsinye ihracat (06.05.2025 / 32892 sayılı R.G. ile değişik) || " + K + " | Bu kapsamda gerçekleştirilen konsinye ihracat işlemlerinde konsinye olarak gönderilen malın ihraç tarihinden itibaren bir yıl içinde kesin satışının yapılması gerekir. Bu süre uzatılmaz || " + K + " | Bu süre, haklı ve zorunlu nedenlere istinaden müracaat edilmesi halinde, izni veren İhracatçı Birlikleri Genel Sekreterliğince iki yıl daha uzatılabilir || " + K + " | basitleştirilmiş veri setine sahip elektronik gümrük beyannamesini || " + K + " | İhracatçı Birlikleri Genel Sekreterliğince konsinye ihracat olarak onaylanmış gümrük beyannamelerinin otuz gün içinde gümrük idarelerine sunulması gerekir || " + K + " | kesin satışının yapılmasından sonraki yüz yirmi gün içinde",
yuva=["Konsinye genel kuralı: bir yıllık süre İBGS'ce iki yıl daha uzatılabilir (basitleştirilmiş beyannamede uygulanmaz)",
      "Konsinye hükmü: İBGS'ce onaylanan beyannamenin otuz gün içinde sunulması; süre ise onay tarihinden değil ihraç tarihinden başlar",
      "Konsinye hükmü: kesin satıştan sonraki yüz yirmi gün içinde bildirim; başlangıç olarak tescil tarihi esas alınmaz",
      "Konsinye genel kuralı: iki yıllık uzatma süresi kesin satış süresi gibi kullanılmış"],
yakinlik="BİREBİR",
tuzak=["İSTİSNA", "BAŞLANGIÇ", "SAYI", "KOMŞU"],
duzey=["AYIRT"],
profil=[5, 2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="",
guncellik="06.05.2025",
cikmis="",
kapsamli=False,
),
# 13 — İhracat Yönetmeliği md. 10: yurt dışı fuar ve sergiler (aranmaz → aranır)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="YANLIŞ",
z="O",
madde="İhracat Yönetmeliği md. 10",
cek="Kamu ve meslek kuruluşları ile vakıfların düzenlediği fuarlarda organizatöre verilen Yeterlilik veya Geçici Yeterlilik Belgesi aranmaz.",
kok=["İhracat Yönetmeliği'nin yurt dışı fuar ve sergilere katılım ve ihracata ilişkin hükümleri çerçevesinde aşağıdakilerden hangisi yanlıştır?"],
d="Kamu ve meslek kuruluşları ile vakıflarca düzenlenen fuarlarda da organizatör kuruluşa verilmiş olan Yeterlilik Belgesi veya Geçici Yeterlilik Belgesi aranır.",
c=["Ülkemizi temsilen katılınacak uluslararası yurt dışı fuar ve sergiler Bakanlık tarafından belirlenir.",
   "Uluslararası ticari fuar ve sergilere gönderilecek bedelli veya bedelsiz malların yurt dışına çıkışıyla ilgili başvurular doğrudan ilgili gümrük idarelerine yapılır.",
   "Gümrük idareleri, bilim, sanat, kültür ve tanıtım amaçlı fuar ve sergiler hariç olmak üzere, çıkışına izin verdikleri mallara ilişkin gümrük beyannamelerinin onaylı bir örneğini, beyannamenin kapanış tarihinden itibaren en geç on beş gün içinde firmanın beyan ettiği İhracatçı Birlikleri Genel Sekreterliğine gönderir.",
   "Uluslararası ticari fuar ve sergilerde sergilenmek üzere yurt dışına çıkarılan malların kesin satışına ilişkin talepler, geçici çıkışa esas gümrük beyannamesinin İhracatçı Birlikleri Genel Sekreterliğince onaylanmasını müteakip gümrük idarelerince sonuçlandırılır."],
sirali=False,
g="İhracat Yönetmeliği'ne göre gümrük idareleri, özel organizatör kuruluşların ülkemizi temsilen ulusal düzeyde katılacağı ticari nitelikli fuar ve sergilerde, organizatör kuruluşa Bakanlıkça (İhracat Genel Müdürlüğü) verilmiş olan Yeterlilik Belgesi veya Geçici Yeterlilik Belgesi ile birlikte ulusal katılım organizasyonunun bu kuruluşça yapılmasının onaylandığını gösterir uygunluk yazısını arar; ancak kamu ve meslek kuruluşları ile vakıflarca düzenlenen fuarlarda bu belgeler aranmaz. Şıkta 'aranmaz' kaydı 'aranır' olarak değiştirildiği için ifade yanlıştır. Diğer ifadeler Yönetmelikle örtüşür: ülkemizi temsilen katılınacak fuar ve sergileri Bakanlık belirler; mal çıkışına ilişkin başvurular doğrudan gümrük idarelerine yapılır; gümrük idareleri bilim, sanat, kültür ve tanıtım amaçlı olanlar hariç beyannamelerin onaylı örneğini kapanış tarihinden itibaren en geç on beş gün içinde İhracatçı Birlikleri Genel Sekreterliğine gönderir; kesin satış talepleri, geçici çıkışa esas beyannamenin Genel Sekreterlikçe onaylanmasından sonra gümrük idarelerince sonuçlandırılır. En güçlü çeldirici on beş günlük gönderme süresine ilişkin ifadedir; süre beyannamenin kapanış tarihinden başlar ve bilim, sanat, kültür ve tanıtım amaçlı fuarlar bu yükümlülüğün dışındadır. Bu nedenle doğru cevap 'Kamu ve meslek kuruluşları ile vakıflarca düzenlenen fuarlarda da organizatör kuruluşa verilmiş olan Yeterlilik Belgesi veya Geçici Yeterlilik Belgesi aranır.' seçeneğidir. (MD İhracat Yönetmeliği md. 10)",
kanit=K + " | kamu ve meslek kuruluşları ile vakıflarca düzenlenen fuarlarda bahse konu belgeler aranmaz || " + K + " | Ülkemizi temsilen katılınacak uluslararası yurt dışı fuar ve sergiler Bakanlık || " + K + " | yurt dışına çıkışıyla ilgili başvurular doğrudan ilgili gümrük idarelerine yapılır || " + K + " | beyannamenin kapanış tarihinden itibaren, en geç onbeş gün içinde firmanın beyan ettiği İhracatçı Birlikleri Genel Sekreterliğine gönderir || " + K + " | geçici çıkışa esas gümrük beyannamesinin İhracatçı Birlikleri Genel Sekreterliğince onaylanmasını müteakip gümrük idarelerince sonuçlandırılır",
yuva=["Fuar hükmü: ülkemizi temsilen katılınacak fuarları Bakanlık belirler (doğru ifade)",
      "Fuar hükmü: çıkış başvuruları doğrudan gümrük idarelerine yapılır (doğru ifade)",
      "Fuar hükmü: onaylı beyanname örneği kapanıştan itibaren en geç on beş günde İBGS'ye gönderilir (doğru ifade)",
      "Fuar hükmü: kesin satış talepleri İBGS onayını müteakip gümrük idarelerince sonuçlandırılır (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "İSTİSNA"],
duzey=["HATIRLAMA"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 14 — İhracat Yönetmeliği md. 14, 15: alıcısına teslim edilemeyen mallar — Bakanlık (İhracat GM)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="YETKİ",
z="K",
madde="İhracat Yönetmeliği md. 14, 15",
cek="Yanma, çalınma gibi haklı ve zorunlu nedenlerle alıcısına teslim edilemeyen mallara ilişkin ihracat talepleri Bakanlıkça (İhracat Genel Müdürlüğü) sonuçlandırılır.",
kok=["İhracat Yönetmeliği'ne göre yanma, çalınma gibi haklı ve zorunlu nedenlerle alıcısına teslim edilemeyen mallara ilişkin ihracat talepleri, durumu gösteren belgelere dayanılarak aşağıdakilerden hangisi tarafından sonuçlandırılır?"],
d="Bakanlık (İhracat Genel Müdürlüğü)",
c=["İhracatçı Birlikleri Genel Sekreterliği",
   "Gümrük idareleri",
   "Bakanlık yurt dışı teşkilatı",
   "Mükellefin bağlı bulunduğu vergi dairesi"],
sirali=False,
g="İhracat Yönetmeliği'ne göre yanma, çalınma gibi haklı ve zorunlu nedenlerle alıcısına teslim edilemeyen mallara ilişkin ihracat talepleri ile geri getirilmesinde ekonomik yarar görülmeyen malların terk edilmesine ilişkin talepler, durumu gösteren belgelere dayanılarak Bakanlıkça (İhracat Genel Müdürlüğü) sonuçlandırılır. Alıcısı tarafından kabul edilmeyen mallarda ise makam farklıdır: aynı bedel ve şartlarla mal ihracı ile başka bedel ve şartlarla satış talepleri gümrük idarelerince sonuçlandırılır ve sonuç İhracatçı Birlikleri Genel Sekreterliğine ve mükellefin bağlı bulunduğu vergi dairesine bildirilir; kabul edilmeyen mal bozulabilir nitelikteyse talepler İhracatçı Birlikleri Genel Sekreterliği veya Bakanlık yurt dışı teşkilatınca sonuçlandırılır. En güçlü çeldirici 'Gümrük idareleri' seçeneğidir: alıcısınca kabul edilmeyen mallara ilişkin komşu hüküm adayı bu makama yönlendirir. Bu nedenle doğru cevap 'Bakanlık (İhracat Genel Müdürlüğü)' seçeneğidir. (MD İhracat Yönetmeliği md. 14, 15)",
kanit=K + " | Yanma, çalınma gibi haklı ve zorunlu nedenlerle alıcısına teslim edilemeyen mallara ilişkin ihracat talepleri, durumu gösteren belgelere dayanılarak Bakanlıkça || " + K + " | giriş ve çıkışta ayniyeti tespit edilmek suretiyle gümrük idarelerince sonuçlandırılır || " + K + " | Gümrük idarelerince sonuçlandırılan talepler ilgili İhracatçı Birlikleri Genel Sekreterliğine ve mükellefin bağlı bulunduğu vergi dairesine bildirilir || " + K + " | yurt dışı teşkilatınca sonuçlandırılır",
yuva=["Konsinye ihracat başvuruları ve kabul edilmeyen bozulabilir mallar: İBGS",
      "Alıcısı tarafından kabul edilmeyen mallarda aynı veya başka bedel ve şartlarla talepler: gümrük idareleri",
      "Alıcısı tarafından kabul edilmeyen bozulabilir nitelikteki mallar: Bakanlık yurt dışı teşkilatı",
      "Gümrük idarelerince sonuçlandırılan talepler vergi dairesine bildirilir (sonuçlandıran makam değildir)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 15 — İhracat 96/31 Tebliği Ek-1/Ek-2: yasak listesinde yer almayan (ayna A)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="KAPSAM_DIŞI",
z="O",
madde="İhracı Yasak ve Ön İzne Bağlı Mallara İlişkin Tebliğ (İhracat 96/31) md. 1, Ek-1, Ek-2",
cek="Yaban domuzu, kurt, çakal, tilki ve sansar ihracı yasak değil, Çevre ve Orman Bakanlığının ön iznine bağlıdır.",
kok=["İhracı Yasak ve Ön İzne Bağlı Mallara İlişkin Tebliğ'e göre aşağıdakilerden hangisi İhracı Yasak Mallar Listesinde yer almaz?"],
d="Yaban domuzu, kurt, çakal, tilki ve sansarın canlı ve cansız hâlleri",
c=["Doğadan toplanan doğal çiçek soğanları",
   "Hint keneviri",
   "Tütün tohumu ve fidesi",
   "Ceviz, dut ve kiraz ağaçlarının kütük, tomruk, kereste, kalas ve taslak olarak ihracı"],
sirali=False,
g="İhracı Yasak ve Ön İzne Bağlı Mallara İlişkin Tebliğ'e göre kanun, kararname ve uluslararası anlaşmalarla ihracı yasaklanmış veya belli kamu kurum ve kuruluşlarının ön iznine bağlanmış mallar Tebliğ ekindeki listelerde sıralanmıştır. İhracı Yasak Mallar Listesinde av ve yaban hayvanları, 'ihracı ön izne bağlı mallar listesinde yer alan türler hariç' kaydıyla yer alır. Yaban domuzu, kurt, çakal, tilki, sansar, porsuk ile yılanlar, kaplumbağa ve kertenkelelerin canlı ve cansız hâlde ve tanınabilir parçaları ise İhracı Ön İzne Bağlı Mallar Listesinde, Çevre ve Orman Bakanlığının iznine bağlı olarak sayılmıştır; bu nedenle yasak listesinde yer almaz. Doğadan toplanan doğal çiçek soğanları, Hint keneviri, tütün tohumu ve fidesi ile ceviz, dut, kiraz gibi ağaç türlerinin kütük, tomruk, kereste, kalas ve taslak olarak ihracı yasak listesindedir. Sorudaki tuzak, 'bütün av ve yaban hayvanları' ifadesindeki istisnayı görmemektir; en güçlü çeldirici ise ön izin listesindeki kotalı doğal çiçek soğanlarıyla karışan doğadan toplanan doğal çiçek soğanlarıdır. Bu nedenle doğru cevap 'Yaban domuzu, kurt, çakal, tilki ve sansarın canlı ve cansız hâlleri' seçeneğidir. (MD İhracat 96/31 Tebliği md. 1, Ek-1, Ek-2)",
kanit=K + " | İhracı ön izne bağlı mallar listesinde yer alan türler hariç bütün av ve yaban hayvanları || " + K + " | Yaban domuzu, kurt, çakal, tilki, sansar, porsuk ile yılanlar, kaplumbağa ve kertenkelelerin canlı ve cansız halde || " + K + " | Doğadan toplanan doğal çiçek soğanları || " + K + " | 2-Hint keneviri || " + K + " | Tütün tohumu ve fidesi || " + K + " | Ceviz, dut, kiraz, armut, erik, porsuk, dışbudak, karaağaç ve ıhlamur adlı ağaç türlerinin kütük, tomruk, kereste, kalas ve taslak olarak ihracı",
yuva=["İhracı Yasak Mallar Listesi: doğadan toplanan doğal çiçek soğanları (ön izin listesindeki kotalı soğanlardan ayrı)",
      "İhracı Yasak Mallar Listesi: Hint keneviri",
      "İhracı Yasak Mallar Listesi: tütün tohumu ve fidesi (yaprak tütün ise ön izin listesinde)",
      "İhracı Yasak Mallar Listesi: ceviz, dut, kiraz vb. ağaç türlerinin kütük, tomruk, kereste, kalas ve taslak olarak ihracı"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "İSTİSNA", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="A: yasak ↔ ön izin listesi",
guncellik="",
cikmis="",
kapsamli=False,
),

# 16 — İhracat 96/31 Tebliği Ek-1/Ek-2: ön izin listesinde yer almayan (ayna A)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="KAPSAM_DIŞI",
z="O",
madde="İhracı Yasak ve Ön İzne Bağlı Mallara İlişkin Tebliğ (İhracat 96/31) Ek-1, Ek-2",
cek="Salep ihracı yasaktır; kotalı doğal çiçek soğanı, yaprak tütün, mavi yüzgeçli orkinos ve Ankara keçisi ön izne bağlıdır.",
kok=["İhracı Yasak ve Ön İzne Bağlı Mallara İlişkin Tebliğ'e göre aşağıdakilerden hangisi İhracı Ön İzne Bağlı Mallar Listesinde yer almaz?"],
d="Salep (toz, tablet ve her türlü formda)",
c=["İhracatı kotayla veya başka herhangi bir kayıtla sınırlandırılan doğal çiçek soğanları",
   "Yaprak tütün ve tütün döküntüleri",
   "Mavi yüzgeçli orkinos (canlı, taze soğutulmuş, dondurulmuş veya işlenmiş)",
   "Ankara (Tiftik) keçisi"],
sirali=False,
g="İhracı Yasak ve Ön İzne Bağlı Mallara İlişkin Tebliğ'e göre İhracı Ön İzne Bağlı Mallar Listesinde her malın karşısında izni veren kurum gösterilmiştir: ihracatı kotayla veya başka herhangi bir kayıtla sınırlandırılan doğal çiçek soğanları, mavi yüzgeçli orkinos ve Ankara (Tiftik) keçisi Tarım ve Köyişleri Bakanlığının, yaprak tütün ve tütün döküntüleri Tütün ve Alkol Piyasası Düzenleme Kurumunun iznine bağlıdır. Toz, tablet ve her türlü formdaki salep ise İhracı Yasak Mallar Listesinde yer alır; ön izinle de ihraç edilemez ve bedelsiz olarak da ihracına izin verilmez. En güçlü çeldirici doğal çiçek soğanlarıdır: doğadan toplanan doğal çiçek soğanları yasak listesinde, ihracatı kotayla veya başka bir kayıtla sınırlandırılanlar ise ön izin listesindedir. Bu nedenle doğru cevap 'Salep (toz, tablet ve her türlü formda)' seçeneğidir. (MD İhracat 96/31 Tebliği Ek-1, Ek-2; Bedelsiz İhracat Tebliği md. 4)",
kanit=K + " | Salep (toz, tablet ve her türlü formda) || " + K + " | İhracatı kotayla veya başka herhangi bir kayıtla sınırlandırılan doğal çiçek soğanları || " + K + " | Yaprak tütün, tütün döküntüleri || " + K + " | Mavi yüzgeçli orkinos (thynus thunnus) (canlı, taze soğutulmuş, dondurulmuş veya işlenmiş) || " + K + " | Ankara (Tiftik) keçisi || " + K + " | Kanun, kararname ve uluslararası anlaşmalarla ihracı yasaklanmış malların bedelsiz ihracatına izin verilmez",
yuva=["İhracı Ön İzne Bağlı Mallar Listesi: kotalı doğal çiçek soğanları — Tarım ve Köyişleri Bakanlığı",
      "İhracı Ön İzne Bağlı Mallar Listesi: yaprak tütün ve döküntüleri — Tütün ve Alkol Piyasası Düzenleme Kurumu",
      "İhracı Ön İzne Bağlı Mallar Listesi: mavi yüzgeçli orkinos — Tarım ve Köyişleri Bakanlığı",
      "İhracı Ön İzne Bağlı Mallar Listesi: Ankara (Tiftik) keçisi — Tarım ve Köyişleri Bakanlığı"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "KOMŞU", "TERİM"],
duzey=["TANIMA"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="A: yasak ↔ ön izin listesi",
guncellik="",
cikmis="",
kapsamli=False,
),

# 17 — Bedelsiz İhracat Tebliği md. 2, 3, 6, 8: belediyenin afet yardımı (vaka; 250.000 USD eşiği uygulanmaz)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="OLAY",
z="Z",
madde="Bedelsiz İhracata İlişkin Tebliğ (İhracat 2008/12) md. 2, 3, 6, 8",
cek="Belediyelerin afet insani yardım malzemesinde bedelsiz ihracat başvurusu, değer ve miktara bakılmaksızın doğrudan gümrük idaresine yapılır; üyelik aranmaz.",
kok=["(B) Belediyesine ilişkin bilgiler şöyledir:",
     "- (B) Belediyesi, deprem yaşanan bir ülkeye insani yardım malzemesi göndermek istemektedir.",
     "- Gönderilecek malzemenin toplam değeri 400.000 ABD Dolarıdır.",
     "- Malzeme, ihracı yasaklanmış veya ön izne bağlanmış mallardan değildir.",
     "- (B) Belediyesi herhangi bir İhracatçı Birliğine üye değildir.",
     "Bedelsiz İhracata İlişkin Tebliğ'e göre bu gönderime ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Bedelsiz ihracat izni başvurusu, değer ve miktarına bakılmaksızın doğrudan ilgili gümrük idaresine yapılır.",
c=["Malzemenin değeri 250.000 ABD Dolarını aştığından başvuru, Bedelsiz İhracat Formu doldurularak İhracatçı Birlikleri Genel Sekreterliğine yapılır.",
   "Başvuru, Dış Ticaret Müsteşarlığının (İhracat Genel Müdürlüğü) görüşü alınarak İhracatçı Birlikleri Genel Sekreterliğince sonuçlandırılır.",
   "Belediye İhracatçı Birliğine üye olmadığından malzeme bedelsiz ihracat kapsamında gönderilemez.",
   "Gönderilen malzeme, ihracatta uygulanan desteklerden yararlandırılır."],
sirali=False,
g="Bedelsiz İhracata İlişkin Tebliğ'e göre savaş, deprem, sel, salgın hastalık, kıtlık ve benzeri afet durumlarında kamu kurum ve kuruluşları, belediyeler, üniversiteler, Kızılay ile kamu yararına çalışan dernek ve vakıfların gönderecekleri insani yardım malzemeleri bedelsiz olarak ihraç edilebilir. Hediyeler, numuneler, reklam ve tanıtım malları ile önceden ihraç edilmiş malların parçaları gibi mallarda değeri 250.000 ABD Dolarına kadar olanların başvurusu doğrudan gümrük idaresine, 250.000 ABD Doları ve üzerindekilerin başvurusu ise Bedelsiz İhracat Formu ile İhracatçı Birlikleri Genel Sekreterliklerine yapılır; ancak kamu kurumları, belediyeler ve üniversitelerin görevleri gereği gönderdikleri mallar ile afet durumlarındaki insani yardım malzemelerinde başvuru, değer ve miktarına bakılmaksızın doğrudan ilgili gümrük idaresine yapılır. Vakada saklanan istisna budur: 400.000 ABD Dolarlık değer 250.000 ABD Doları eşiğine takılmaz. Ayrıca insani yardım malzemesinin bedelsiz ihracatında İhracatçı Birliğine üye olma şartı aranmaz ve bedelsiz ihracata konu mal ihracatta uygulanan desteklerden yararlandırılmaz. Tebliğde sayılanlar dışında kalan hususlar Dış Ticaret Müsteşarlığının görüşü alınarak sonuçlandırılır; vakadaki gönderim ise Tebliğde sayılan hâllerdendir. En güçlü çeldirici 250.000 ABD Doları eşiğine dayanan seçenektir. Bu nedenle doğru cevap 'Bedelsiz ihracat izni başvurusu, değer ve miktarına bakılmaksızın doğrudan ilgili gümrük idaresine yapılır.' seçeneğidir. (MD Bedelsiz İhracat Tebliği md. 2, 3, 6, 8)",
kanit=K + " | Savaş, deprem, sel, salgın hastalık, kıtlık ve benzeri afet durumlarında; kamu kurum ve kuruluşları, belediyeler, üniversiteler, Kızılay ile kamu yararına çalışan dernek ve vakıfların gönderecekleri insani yardım malzemeleri || " + K + " | değer ve miktarına bakılmaksızın birinci fıkrasının (d) ve (e) bentlerinde belirtilen malların bedelsiz ihracat izni başvuruları doğrudan ilgili gümrük idaresine yapılır || " + K + " | değeri 250.000 (ikiyüzellibin) ABD Doları ve üzeri olanların bedelsiz ihracat izni başvuruları ise, ekteki Bedelsiz İhracat Formu doldurularak İhracatçı Birlikleri Genel Sekreterliklerine yapılır || " + K + " | Bedelsiz ihracata konu mal, ihracatta uygulanan desteklerden yararlandırılmaz || " + K + " | (a), (c), (ç), (d) ve (e) bentleri kapsamında yapılacak bedelsiz ihracatta, İhracatçı Birliğine üye olma şartı aranmaz || " + K + " | Yukarıda belirtilenler dışında kalan hususlar, Dış Ticaret Müsteşarlığının (İhracat Genel Müdürlüğü) görüşü alınarak",
yuva=["Tebliğin izin mercii hükmü: hediye, numune, tanıtım malı ve parçalarda 250.000 ABD Doları ve üzeri için İBGS'ye form",
      "Tebliğin uygulama hükmü: sayılanlar dışındaki hususlar DTM görüşü alınarak gümrük idaresi veya İBGS'ce sonuçlandırılır",
      "Tebliğin üyelik hükmü: insani yardım dahil sayılan hâllerde İhracatçı Birliğine üyelik aranmaz",
      "Tebliğin destek hükmü: bedelsiz ihracata konu mal desteklerden yararlandırılmaz"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "SAYI", "MAKAM"],
duzey=["UYGULAMA"],
profil=[1, 3],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 18 — Bedelsiz İhracat Tebliği md. 3, 5, 8: izin süresi, 1.000 USD fon muafiyeti, kayıt şartı, üyelik
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="ÖNERMELİ",
z="O",
madde="Bedelsiz İhracata İlişkin Tebliğ (İhracat 2008/12) md. 2, 3, 5, 8",
cek="Bedelsiz ihraç izni bir yıl geçerli; FOB 1.000 doları geçmeyen mal fon kesintisine tabi değil; kayda bağlı malda 1.000 doları aşınca kayıt aranır.",
kok=["Bedelsiz İhracata İlişkin Tebliğ çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Bedelsiz ihraç izinlerinin geçerlilik süresi bir yıldır.",
     "II. FOB değeri 1.000 ABD Dolarını geçmeyen malların bedelsiz ihracı Destekleme ve Fiyat İstikrar Fonu kesintisine tabi değildir.",
     "III. İhracı kayda bağlı mallardan değeri FOB 1.000 ABD Dolarını geçenlerin bedelsiz olarak ihracında kayıt şartı aranmaz.",
     "IV. Gerçek veya tüzel kişiler tarafından gönderilen hediyeler ile miktarı ticari teamüllere uygun numunelerin bedelsiz ihracatında İhracatçı Birliğine üye olma şartı aranmaz.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, II ve IV",
c=["I ve II", "II ve III", "I, III ve IV", "I, II, III ve IV"],
sirali=False,
g="Bedelsiz İhracata İlişkin Tebliğ'e göre bedelsiz ihraç izinlerinin geçerlilik süresi bir yıldır (I doğru). İhracında Destekleme ve Fiyat İstikrar Fonu'na prim kesintisi yapılan malların bedelsiz ihracında primin ödendiğine dair banka dekontu aranır; ancak FOB değeri 1.000 ABD Dolarını geçmeyen malların bedelsiz ihracı fon kesintisine tabi değildir (II doğru). İhracı Kayda Bağlı Mallara İlişkin Tebliğ eki listedeki mallardan değeri FOB 1.000 ABD Dolarını geçenlerin bedelsiz olarak ihracında kayıt şartı aranır; III. ifadede 'aranır' kaydı 'aranmaz' olarak değiştirildiği için ifade yanlıştır. Hediyeler, ticari teamüllere uygun numuneler, reklam ve tanıtım malları ile yabancılar, kamu kurumları ve insani yardımlar için yapılan bedelsiz ihracatta İhracatçı Birliğine üye olma şartı aranmaz; bu muafiyet önceden ihraç edilmiş malların parçaları ve garanti kapsamındaki yenileme parçalarını kapsamaz (IV doğru). En güçlü çeldirici 'I, II, III ve IV' seçeneğidir: aynı maddede iki kez geçen 1.000 ABD Doları sınırı, fon kesintisindeki muafiyetle kayıt şartı arasında karıştırıldığında III. ifade de doğru sanılır. Bu nedenle doğru cevap 'I, II ve IV' seçeneğidir. (MD Bedelsiz İhracat Tebliği md. 2, 3, 5, 8)",
kanit=K + " | Bedelsiz ihraç izinlerinin geçerlilik süresi 1 (bir) yıldır || " + K + " | Ancak FOB değeri l.000 (bin) ABD Dolarını geçmeyen malların bedelsiz ihracı Destekleme ve Fiyat İstikrar Fonu kesintisine tabi değildir || " + K + " | değeri FOB l.000 (bin) ABD Dolarını geçenlerin bedelsiz olarak ihracında kayıt şartı aranır || " + K + " | (a), (c), (ç), (d) ve (e) bentleri kapsamında yapılacak bedelsiz ihracatta, İhracatçı Birliğine üye olma şartı aranmaz || " + K + " | Gerçek veya tüzel kişiler tarafından götürülen veya gönderilen hediyeler, miktarı ticari teamüllere uygun numuneler",
yuva=["I ve II: hediye ve numunelerde üyelik şartının aranmadığını bilmeyen aday",
      "II ve III: kayıt şartını tersine okuyan ve izin süresini bilmeyen aday",
      "I, III ve IV: aynı maddedeki iki 1.000 ABD Doları kuralını (fon muafiyeti ↔ kayıt şartı) yer değiştiren aday",
      "I, II, III ve IV: kayıt şartının 1.000 ABD Dolarını aşan kayda bağlı mallarda 'aranır' olduğunu görmeyen aday"],
yakinlik="BİREBİR",
tuzak=["SAYI", "TERSİNE", "ŞART"],
duzey=["HATIRLAMA"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 19 — Geçici İhracat Tebliği md. 6: taşıtlarda üç yıllık kanuni süre ve süre uzatımında gümrük müdürlüğü
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="SÜRE",
z="O",
madde="Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1) md. 6, 8, 19",
cek="Geçici çıkarılan taşıtlarda kanuni süre Gümrük Kanunu'ndaki üç yıldır; mücbir sebepte süre uzatımını ilgili gümrük müdürlüğü yapar.",
kok=["Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1)'e göre Türkiye Gümrük Bölgesinden geçici olarak çıkarılan taşıtların beklenmeyen hâller veya mücbir sebeplerle Türkiye'ye geri getirilememesi hâlinde, Gümrük Kanunu'nda belirtilen kanuni süre ile ilgilinin yazılı talebi üzerine süre uzatımını yapacak makam aşağıdakilerin hangisinde birlikte doğru olarak verilmiştir?"],
d="Üç yıl – İlgili gümrük müdürlüğü",
c=["Üç yıl – Dış Ticaret Müsteşarlığı",
   "İki yıl – İlgili gümrük müdürlüğü",
   "İki yıl – Dışişleri Bakanlığı",
   "Bir yıl – Gümrük ve Ticaret Bakanlığı (Gümrükler Genel Müdürlüğü)"],
sirali=False,
g="Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1)'e göre geçici olarak Türkiye Gümrük Bölgesi dışına çıkarılan taşıtların, Gümrük Kanunu'nda belirtilen üç yıllık kanuni süre içinde yurt dışında ağır hasar görmesi, el konulması, arızalanması, sürücünün tutuklanması veya hastalanması, doğal afet ya da iç karışıklık gibi beklenmeyen hâller veya mücbir sebeplerle Türkiye'ye geri getirilememesi hâlinde, ilgilinin yazılı talebi üzerine ilgili gümrük müdürlüğünce süre uzatımı yapılır. Dış Ticaret Müsteşarlığı, yurt dışı müteahhitlik hizmetleri kapsamında geçici ihraç edilen eşyanın süresini uzatan makamdır; Dışişleri Bakanlığı, yurt dışındaki kadrolara atanan devlet memurlarının görev süresine ilişkin belgeyi veren kurumdur; Gümrük ve Ticaret Bakanlığı (Gümrükler Genel Müdürlüğü) ise Tebliğde öngörülmeyen durumları sonuçlandırmaya yetkilidir. İki yıl, konsinye ihracatta kesin satış süresinin uzatılabileceği süre; bir yıl ise bedelsiz ihraç izinlerinin geçerlilik süresidir. En güçlü çeldirici 'Üç yıl – Dış Ticaret Müsteşarlığı' seçeneğidir: süre doğru olmakla birlikte makam, müteahhitlik eşyasına ilişkin komşu hükümden taşınmıştır. Bu nedenle doğru cevap 'Üç yıl – İlgili gümrük müdürlüğü' seçeneğidir. (MD Geçici İhracat Tebliği md. 6, 8, 19)",
kanit=K + " | 4458 sayılı Gümrük Kanununun 168 inci maddesinde belirtilen 3 yıllık kanuni süre içerisinde || " + K + " | ilgilinin yazılı talebi üzerine ilgili gümrük müdürlüğünce süre uzatımı yapılır || " + K + " | Ancak bu süre Dış Ticaret Müsteşarlığınca uzatılabilir || " + K + " | Dışişleri Bakanlığı veya bağlı olduğu kurumdan alınacak belgenin ibraz edilmesi halinde || " + K + " | Tebliğde öngörülmeyen durumları inceleyerek sonuçlandırmaya Gümrük ve Ticaret Bakanlığı (Gümrükler Genel Müdürlüğü) yetkilidir",
yuva=["Yurt dışı müteahhitlik eşyası: üç yıllık süre Dış Ticaret Müsteşarlığınca uzatılabilir",
      "İhracat Yönetmeliği konsinye: kesin satış süresinin İBGS'ce iki yıl daha uzatılabilmesi (süre komşusu)",
      "Taşıt hükmü: yurt dışı kadrolara atanan memurlar için Dışişleri Bakanlığından alınan belge",
      "Tebliğin yetki hükmü: öngörülmeyen durumlarda Gümrük ve Ticaret Bakanlığı (GGM); bir yıl bedelsiz ihraç izni süresi"],
yakinlik="PARAFRAZ",
tuzak=["SAYI", "MAKAM", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[2],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2021/32",
kapsamli=False,
),

# 20 — Geçici İhracat Tebliği md. 9; İhracat Yönetmeliği md. 13: ticari kiralama (muvafakatname)
dict(
konu="İhracat Rejimi", blok="SB35",
kalip="DOĞRU",
z="Z",
madde="Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1) md. 9; İhracat Yönetmeliği md. 13",
cek="Ticari kiralama konusu eşyanın mülkiyeti kiraya verene ait değilse noterde tanzim ettirilmiş muvafakatname ibraz edilir; başvuru gümrük müdürlüğüne yapılır.",
kok=["Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1)'e göre ticari kiralama yoluyla yapılacak ihracata ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Ticari kiralama konusu eşyanın mülkiyetinin kiraya verene ait olmaması durumunda, eşyanın mülkiyetinin başkasına ait olduğuna ilişkin noterde tanzim ettirilmiş muvafakatname ibraz edilir.",
c=["Ticari kiralama yoluyla yapılacak ihracat talepleri İhracatçı Birlikleri Genel Sekreterliğine yapılır ve bu Genel Sekreterlikçe onaylanan gümrük beyannamesi izin hükmündedir.",
   "Kiraya verilen eşyanın motorlu kara nakil vasıtası olması durumunda, ayrıca aracın trafik tescil kuruluşlarınca ve vergi dairelerince kayıtlarının kapatıldığının belgelenmesi gerekir.",
   "Ticari kiralama yoluyla yapılacak ihracatta süre, Gümrük Kanunu'nda belirtilen üç yıllık süreyi aşamaz ve bu süre hiçbir şekilde uzatılamaz.",
   "Ticari kiralama konusu eşyanın finansal kiralama yoluyla elde edilmiş olması durumunda, yalnızca kiralayan ile kiraya veren arasında yapılan sözleşmenin ibrazı yeterlidir."],
sirali=False,
g="Gümrük Genel Tebliği (Hariçte İşleme-Geçici İhracat) (Seri No: 1)'e göre ticari kiralama yoluyla yapılacak ihracat talepleri; kiracı firma veya kuruluşla yapılan sözleşmenin aslı veya noter tasdikli örneği ve yeminli tercümanca yapılmış Türkçe tercümesi ile, kiraya verilen eşya motorlu kara nakil vasıtası ise ayrıca motorlu araç tescil belgesinin bir örneğiyle birlikte çıkış işlemlerinin yapılacağı gümrük müdürlüğüne yapılır ve gümrük müdürlüğünce onaylanan beyanname izin hükmündedir. Eşyanın mülkiyeti kiraya verene ait değilse, mülkiyetin başkasına ait olduğuna ilişkin noterde tanzim ettirilmiş muvafakatname ibraz edilir. Eşya finansal kiralama yoluyla elde edilmişse kiralayan ile kiraya veren arasındaki sözleşmenin yanında kiralayan kişi tarafından noterden tanzim ettirilmiş muvafakatname de aranır. Süre, Gümrük Kanunu'nda belirtilen üç yıllık süreyi aşamaz; ancak bitiminden önce başvurulmak kaydıyla gümrük müdürlüğünce sözleşmede belirlenen süre kadar uzatılabilir. İhracat Yönetmeliği de ticari kiralama yoluyla yapılacak ihracatın gümrük mevzuatı hükümlerine tabi olduğunu belirtir. En güçlü çeldirici trafik kayıtlarının kapatılmasına ilişkin seçenektir; bu koşul, Bedelsiz İhracat Tebliği'nde yurt dışında ikamet edenlerin taşıt götürmesi hâline aittir. Bu nedenle doğru cevap 'Ticari kiralama konusu eşyanın mülkiyetinin kiraya verene ait olmaması durumunda, eşyanın mülkiyetinin başkasına ait olduğuna ilişkin noterde tanzim ettirilmiş muvafakatname ibraz edilir.' seçeneğidir. (MD Geçici İhracat Tebliği md. 9; İhracat Yönetmeliği md. 13)",
kanit=K + " | Ticari kiralama konusu eşyanın mülkiyetinin kiraya verene ait olmaması durumunda, eşyanın mülkiyetinin başkasına ait olduğuna ilişkin noterde tanzim ettirilmiş muvafakatname ibraz edilir || " + K + " | çıkış işlemlerinin yapılacağı gümrük müdürlüğüne yapılır. Gümrük müdürlüğü tarafından onaylanan beyanname izin hükmündedir || " + K + " | aracın motorlu araç tescil belgesinin bir örneği ile birlikte || " + K + " | kiralayan kişi tarafından noterden tanzim ettirilmiş muvafakatname ibraz edilir || " + K + " | Ancak bu süre, bitiminden önce başvurulmak kaydıyla, ilgili gümrük müdürlüğünce ticari kiralama sözleşmesinde belirlenen süre kadar uzatılabilir || " + K + " | Ticari kiralama yoluyla yapılacak ihracat gümrük mevzuatı hükümlerine tabidir || " + K + " | taşıtın trafik tescil kuruluşlarınca ve vergi dairelerince kayıtlarının kapatıldığının belgelenmesi gerekir",
yuva=["İhracat Yönetmeliği konsinye: başvurular İBGS'ye yapılır ve İBGS'ce sonuçlandırılır",
      "Bedelsiz İhracat Tebliği: yurt dışında ikamet edenlerin taşıt götürmesinde trafik tescil ve vergi dairesi kayıtlarının kapatıldığının belgelenmesi",
      "Ticari kiralama süre hükmü: üç yılı aşamaz, ancak bitiminden önce başvuruyla sözleşme süresi kadar uzatılabilir",
      "Ticari kiralama hükmü: finansal kiralamayla elde edilen eşyada sözleşmeye ek olarak noterden muvafakatname"],
yakinlik="BİREBİR",
tuzak=["ŞART", "KOMŞU", "MUTLAK", "MAKAM"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

]
