# Soru Bankası — Bölüm 48: İtirazlar (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
# Kaynak: 49-itirazlar.txt — 4458 sayılı Gümrük Kanunu md. 242-243; Gümrük Yönetmeliği md. 585-590;
# Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2) md. 12.
# Çeldirici yuvası için ayrıca: 50-uzlaşma.txt (süre durması, beş gün, 45 gün), 38-serbest bölge.txt (muttali olma),
# 18-Ser.Dol.Giriş Rejimi.txt (işlenmiş tarım ürünlerinde ikinci tahlil), 17-BEYAN.txt (akredite dış laboratuvar).
K = "49-itirazlar.txt"
UZ = "50-uzlaşma.txt"
SD = "18-Ser.Dol.Giriş Rejimi.txt"
TT = "Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2)"

Q = [

# 1 — GK 242/1: itiraz süresi, başlangıcı ve makamı (iki bilgi; ayna: S2)
dict(
konu="İtirazlar", blok="SB48",
kalip="SÜRE",
z="K",
madde="4458 sayılı Gümrük Kanunu md. 242",
cek="Vergi, ceza ve idari kararlara itiraz, tebliğ tarihinden itibaren on beş gün içinde bir üst makama, üst makam yoksa aynı makama yapılır.",
kok=["4458 sayılı Gümrük Kanunu'na göre yükümlülerin kendilerine tebliğ edilen gümrük vergileri, cezalar ve idari kararlara karşı itiraz süresi ve itirazın yapılacağı makam aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Tebliğ tarihinden itibaren on beş gün içinde, bir üst makama; üst makam yoksa aynı makama",
c=["Tebliğ tarihinden itibaren otuz gün içinde, bir üst makama; üst makam yoksa aynı makama",
   "Tebliğ tarihinden itibaren on beş gün içinde, gümrük ve muhafaza başmüdürlüğüne",
   "Olaya muttali olunduğu tarihten itibaren on beş gün içinde, bir üst makama; üst makam yoksa aynı makama",
   "Tebliğ tarihinden itibaren on beş gün içinde, işlemin yapıldığı yerdeki idari yargı merciine"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre yükümlüler, kendilerine tebliğ edilen gümrük vergileri, cezalar ve idari kararlara karşı tebliğ tarihinden itibaren on beş gün içinde bir üst makama, üst makam yoksa aynı makama verecekleri bir dilekçe ile itiraz edebilir. Süre olaya muttali olma tarihinden değil, tebliğ tarihinden başlar; muttali olma tarihi serbest bölgelerdeki işletici hizmetlerine yapılan şikâyet usulüne aittir. Otuz gün itiraz süresi değil, idareye intikal eden itirazın karara bağlanma süresidir. Gümrük ve muhafaza başmüdürlüğü yalnızca kimyevi tahlil sonuçlarına yapılan itirazın makamıdır. İşlemin yapıldığı yerdeki idari yargı mercilerine ise itirazın reddi kararından sonra başvurulur. En güçlü çeldirici, aynı maddede itirazın karara bağlanma süresi olarak geçen otuz gündür. Bu nedenle doğru cevap 'Tebliğ tarihinden itibaren on beş gün içinde, bir üst makama; üst makam yoksa aynı makama' seçeneğidir. (MD GK 242, 243)",
kanit=K + " | Yükümlüler kendilerine tebliğ edilen gümrük vergileri, cezalar ve idari kararlara karşı tebliğ tarihinden itibaren onbeş gün içinde bir üst makama, üst makam yoksa aynı makama verecekleri bir dilekçe ile itiraz edebilir || " + K + " | İdareye intikal eden itirazlar otuz gün içinde karara bağlanarak ilgili kişiye tebliğ edilir || " + K + " | İtirazın reddi kararlarına karşı işlemin yapıldığı yerdeki idari yargı mercilerine başvurulabilir || 38-serbest bölge.txt | itiraz ve şikayet konusu olaya muttali olunduğu tarihten itibaren en geç üç gün içinde",
yuva=["Aynı maddenin ikinci fıkrası: idareye intikal eden itirazların otuz gün içinde karara bağlanması (karar süresi)",
      "GK 243/1: kimyevi tahlil sonuçlarına itiraz gümrük ve muhafaza başmüdürlüğüne yapılır (tahlil itirazının makamı)",
      "Serbest Bölgeler Uygulama Yönetmeliği md. 51: işletici hizmetlerine itirazda süre olaya muttali olunduğu tarihten başlar (başlangıç anı taşındı)",
      "Aynı maddenin dördüncü fıkrası: idari yargı yolu itirazın reddi kararlarına karşıdır"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "BAŞLANGIÇ", "MAKAM", "KOMŞU"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[2],
olumsuz=False, vaka=False, baslangic=True,
eksen=0, ayna="Genel itiraz ↔ tahlil itirazı makamı",
guncellik="",
cikmis="2022/66; 2024/95",
kapsamli=False,
),

# 2 — GK 243: kimyevi tahlil sonuçlarına itirazın makamı (yanlış: bir üst makam; ayna: S1)
dict(
konu="İtirazlar", blok="SB48",
kalip="YANLIŞ",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 243",
cek="Kimyevi tahlil sonuçlarına itiraz, tebliğden itibaren on beş gün içinde gümrük ve muhafaza başmüdürlüğüne yazılı yapılır; bir üst makama yapılmaz.",
kok=["4458 sayılı Gümrük Kanunu'nun gümrük vergilerinin hesaplanmasında esas alınan kimyevi tahlil sonuçlarına itiraza ilişkin hükümleri çerçevesinde aşağıdaki ifadelerden hangisi yanlıştır?"],
d="Kimyevi tahlil sonuçlarına karşı itiraz, bir üst makama, üst makam yoksa aynı makama yapılır.",
c=["Kimyevi tahlil sonuçlarına karşı tebliğden itibaren on beş gün içinde yazılı olarak itiraz edilebilir.",
   "İtiraz üzerine ikinci tahlil, birinci tahlilin yapıldığı gümrük laboratuvarında görevli olan ve ilk tahlili yapan kimyager dışındaki iki kimyager tarafından yapılır.",
   "Yükümlünün talebi hâlinde gümrük idareleri, gümrük kimyageri olmayan bir gözlemci kimyagerin de ikinci tahlilde hazır bulunmasına izin verir.",
   "İkinci tahlil sonucu, eşyanın teknik özelliklerinin ve niteliklerinin belirlenmesi yönünden kesindir."],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre ilgili kişilere tebliğ edilen gümrük vergilerinin hesaplanmasında esas alınan kimyevi tahlil sonuçlarına karşı tebliğden itibaren on beş gün içinde gümrük ve muhafaza başmüdürlüğüne yazılı olarak itiraz edilebilir. 'Bir üst makama, üst makam yoksa aynı makama' itiraz, aynı Kanunda gümrük vergileri, cezalar ve idari kararlara karşı yapılan genel itirazın makamıdır; tahlil sonucuna itirazın makamı ayrıca belirlenmiştir. İtiraz üzerine ikinci tahlil, birinci tahlilin yapıldığı laboratuvarda görevli olan ve ilk tahlili yapan kimyager dışındaki iki kimyager tarafından yapılır; yükümlü isterse gümrük kimyageri olmayan bir gözlemci kimyager de hazır bulunabilir. İkinci tahlil sonucu, eşyanın teknik özellikleri ve nitelikleri yönünden kesindir. Olumsuz kökü hızlı okuyan aday, iki itirazda sürenin aynı (on beş gün) olmasına bakarak makamın da aynı olduğunu varsayar. Bu nedenle doğru cevap 'Kimyevi tahlil sonuçlarına karşı itiraz, bir üst makama, üst makam yoksa aynı makama yapılır.' seçeneğidir. (MD GK 242, 243)",
kanit=K + " | gümrük vergilerinin hesaplanmasında esas alınan kimyevi tahlil sonuçlarına karşı tebliğden itibaren onbeş gün içinde gümrük ve muhafaza başmüdürlüğüne … yazılı olarak itiraz edilebilir || " + K + " | birinci tahlilin yapıldığı gümrük laboratuarında görevli olan ve ilk tahlili yapan kimyager dışındaki iki kimyager tarafından ikinci tahlil yapılır || " + K + " | Yükümlünün talebi halinde, gümrük idareleri, gümrük kimyageri olmayan bir gözlemci kimyagerin de ikinci tahlilde hazır bulunmasına izin verirler || " + K + " | İkinci tahlil sonucu, eşyanın teknik özelliklerinin ve niteliklerinin belirlenmesi yönünden kesindir || " + K + " | bir üst makama, üst makam yoksa aynı makama verecekleri bir dilekçe ile itiraz edebilir",
yuva=["GK 243/1: tebliğden itibaren on beş gün, yazılı itiraz (doğru ifade)",
      "GK 243/2: ilk tahlili yapan dışındaki iki kimyager (doğru ifade)",
      "GK 243/2: talep hâlinde gümrük kimyageri olmayan gözlemci kimyager (doğru ifade)",
      "GK 243/3: ikinci tahlil sonucunun kesinliği (doğru ifade)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU", "TERSİNE"],
duzey=["AYIRT"],
profil=[4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="Genel itiraz ↔ tahlil itirazı makamı",
guncellik="",
cikmis="2023/78",
kapsamli=False,
),

# 3 — GK 242/3: süresi içinde yanlış makama verilen dilekçe
dict(
konu="İtirazlar", blok="SB48",
kalip="SONUÇ",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 242",
cek="Süresi içinde yanlış makama verilen itiraz dilekçesi süresinde yapılmış sayılır ve idarece yetkili makama ulaştırılır.",
kok=["4458 sayılı Gümrük Kanunu'na göre itiraz dilekçesinin süresi içinde yanlış makama verilmesi hâlinde aşağıdakilerden hangisi uygulanır?"],
d="İtiraz süresinde yapılmış sayılır ve dilekçe idarece yetkili makama ulaştırılır.",
c=["İtiraz süresi durur; dilekçe yetkili makama ulaştığında süre kaldığı yerden işlemeye devam eder.",
   "İtiraz incelenmeksizin reddedilir; ret kararına karşı idari yargı mercilerine başvurulabilir.",
   "Dilekçe idarece yetkili makama ulaştırılır; ancak itiraz, dilekçenin yetkili makamın kaydına girdiği tarihte yapılmış sayılır.",
   "Yükümlüye, dilekçeyi yetkili makama vermesi için beş günlük ek süre tanınır."],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre itiraz dilekçelerinin süresi içinde yanlış makama verilmesi hâlinde itiraz süresinde yapılmış sayılır ve dilekçe idarece yetkili makama ulaştırılır. Yükümlünün itiraz hakkı korunur; dilekçeyi doğru makama ulaştırma yükü idareye aittir. Sürenin durması ve kaldığı yerden işlemesi uzlaşma talebinde bulunulmasına, sürenin beş güne tamamlanması ise uzlaşmanın sağlanamadığı hâle ait kurallardır. Kayda giriş tarihi, Yönetmelikte taahhütsüz posta yoluyla veya doğrudan gümrük idaresine verilen dilekçede sürenin tespiti için aranır; yanlış makama süresinde verilen dilekçede yetkili makama ulaşma tarihi esas alınmaz. Ret ve idari yargı yolu ise itiraz incelendikten sonra gündeme gelir. En güçlü çeldirici, kayda giriş tarihini esas alan seçenektir. Bu nedenle doğru cevap 'İtiraz süresinde yapılmış sayılır ve dilekçe idarece yetkili makama ulaştırılır.' seçeneğidir. (MD GK 242; GY 585)",
kanit=K + " | İtiraz dilekçelerinin süresi içinde yanlış makama verilmesi halinde, itiraz süresinde yapılmış sayılır ve idarece yetkili makama ulaştırılır || " + UZ + " | Uzlaşma talebinde bulunulması halinde, itiraz veya dava açma süresi durur || " + UZ + " | sürenin bitimine beş günden az kalmış olması halinde süre beş güne tamamlanır || " + K + " | itiraz dilekçesinin itirazın yapıldığı gümrük idaresinin kaydına giriş tarihi",
yuva=["Uzlaşma Yönetmeliği md. 14: uzlaşma talebinde itiraz ve dava açma süresi durur, kaldığı yerden işler",
      "Aynı maddenin dördüncü fıkrası: itirazın reddi kararlarına karşı idari yargı yolu",
      "GY 585/4-b: posta yoluyla veya doğrudan yapılan itirazda kayda giriş tarihi",
      "Uzlaşma Yönetmeliği md. 14: sürenin bitimine beş günden az kalmışsa süre beş güne tamamlanır"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "BAŞLANGIÇ"],
duzey=["AYIRT"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 4 — GK 242/2, 242/4; GY 590: önermeli (II ve III)
dict(
konu="İtirazlar", blok="SB48",
kalip="ÖNERMELİ",
z="O",
madde="4458 sayılı Gümrük Kanunu md. 242; Gümrük Yönetmeliği md. 590",
cek="İtirazlar otuz günde karara bağlanıp tebliğ edilir; ret kararına işlemin yapıldığı yerdeki idari yargıda gidilir; ikinci tahlil sonucuyla tarife ve vergiler duyurulur.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'nin itirazlara ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. İtirazın reddi kararlarına karşı yükümlünün yerleşim yerindeki idari yargı mercilerine başvurulabilir.",
     "II. İdareye intikal eden itirazlar otuz gün içinde karara bağlanarak ilgili kişiye tebliğ edilir.",
     "III. Yükümlülere ikinci tahlil sonucu ile bu sonuca göre yapılan tarife uygulaması ve tahakkuk ettirilen vergiler duyurulur.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve III",
c=["Yalnız II", "I ve II", "I ve III", "I, II ve III"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre idareye intikal eden itirazlar otuz gün içinde karara bağlanarak ilgili kişiye tebliğ edilir (II doğru). İtirazın reddi kararlarına karşı başvurulacak yargı yeri 'işlemin yapıldığı yerdeki' idari yargı mercileridir; Kanun yükümlünün yerleşim yerini ölçü almaz (I yanlış). Gümrük Yönetmeliği'ne göre ikinci tahlil sonucu eşyanın teknik özellik ve niteliklerinin tayin ve tespiti bakımından kesin olduğundan, yükümlülere yalnızca bu sonuç değil, sonuca göre yapılan tarife uygulaması ve tahakkuk ettirilen vergiler de duyurulur (III doğru). En güçlü tuzak I'dir: yargı yerinin ölçütü 'işlemin yapıldığı yer' yerine 'yükümlünün yerleşim yeri' yapılmıştır. Otuz günü itiraz süresiyle karıştıran aday ise II'yi yanlış sayar; on beş gün itirazın yapılma süresidir. Bu nedenle doğru cevap 'II ve III' seçeneğidir. (MD GK 242; GY 590)",
kanit=K + " | İdareye intikal eden itirazlar otuz gün içinde karara bağlanarak ilgili kişiye tebliğ edilir || " + K + " | İtirazın reddi kararlarına karşı işlemin yapıldığı yerdeki idari yargı mercilerine başvurulabilir || " + K + " | yükümlülere ikinci tahlil sonucu ile bu sonuca göre yapılan tarife uygulaması ve tahakkuk ettirilen vergiler duyurulur",
yuva=["Eksik seçim: otuz günü itiraz süresi sanıp III'ü tek başına bırakmayan, yalnız II'yi seçen aday",
      "I'i doğru sayan aday: yargı yeri 'işlemin yapıldığı yer' yerine 'yerleşim yeri' yazılmış (GK 242/4)",
      "II'yi yanlış sayan aday: karar süresini on beş günle (GK 242/1) karıştırır",
      "Üç ifadeyi de doğru sayan aday: I'deki yer kaydı değişikliğini fark etmez"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM", "YAKIN-SAYI"],
duzey=["AYIRT"],
profil=[2, 1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2023/77",
kapsamli=False,
),

# 5 — GK 243/2 ikinci paragraf: üç kimyagerden fazla kimyager bulunmayan laboratuvar
dict(
konu="İtirazlar", blok="SB48",
kalip="SONUÇ",
z="Z",
madde="4458 sayılı Gümrük Kanunu md. 243",
cek="Üç kimyagerden fazla kimyager bulunmayan laboratuvardaki tahlile itirazda ikinci tahlil, en az iki kimyager bulunan en yakın gümrük idaresi laboratuvarında yapılır.",
kok=["4458 sayılı Gümrük Kanunu'na göre üç kimyagerden fazla kimyager bulunmayan bir gümrük laboratuvarında yapılan tahlile itiraz edilmesi hâlinde ikinci tahlil nerede yaptırılır?"],
d="En az iki kimyager bulunan en yakın gümrük idaresine ait laboratuvarda",
c=["Gümrük ve muhafaza başmüdürlüğünce uygun görülecek bir laboratuvarda",
   "Resmî bilimsel bir kuruluşun laboratuvarında",
   "Bakanlıkça belirlenen akredite bir dış laboratuvarda",
   "Birinci tahlilin yapıldığı laboratuvarda, ilk tahlili yapan kimyagerin de katılımıyla"],
sirali=False,
g="4458 sayılı Gümrük Kanunu'na göre itiraz üzerine ikinci tahlil, kural olarak birinci tahlilin yapıldığı gümrük laboratuvarında görevli olan ve ilk tahlili yapan kimyager dışındaki iki kimyager tarafından yapılır. Üç kimyagerden fazla kimyager bulunmayan gümrük laboratuvarında yapılan tahlile itiraz edilmesi hâlinde ise ikinci tahlil, en az iki kimyager bulunan en yakın gümrük idaresine ait laboratuvarda yaptırılır. Gümrük ve muhafaza başmüdürlüğünce uygun görülecek laboratuvar, Yönetmelikte birinci tahlilin gümrük laboratuvarları dışında yapıldığı hâle aittir. Resmî bilimsel kuruluş laboratuvarı işlenmiş tarım ürünlerine ilişkin tebliğde, akredite dış laboratuvar ise Bakanlığın yeniden tahlil yaptırma yetkisinde geçer. İlk tahlili yapan kimyager ikinci tahlile katılmaz. En güçlü çeldirici, birinci tahlili gümrük laboratuvarı dışında yapılan eşyaya ait başmüdürlük seçeneğidir. Bu nedenle doğru cevap 'En az iki kimyager bulunan en yakın gümrük idaresine ait laboratuvarda' seçeneğidir. (MD GK 243; GY 589)",
kanit=K + " | Üç kimyagerden fazla kimyager bulunmayan gümrük laboratuarında yapılan tahlile itiraz edilmesi halinde, ikinci tahlil en az iki kimyager bulunan en yakın gümrük idaresine ait laboratuarda yaptırılır || " + K + " | ikinci tahlil gümrük ve muhafaza başmüdürlüğünce uygun görülecek bir laboratuvarda yaptırılır || " + SD + " | ikinci tahlil resmi bilimsel bir kuruluş laboratuarında || 17-BEYAN.txt | akredite dış laboratuvarlarda tekrar tahlil yaptırma yetkisini haizdir",
yuva=["GY 589/1-c: birinci tahlil gümrük laboratuvarları haricinde yapılmışsa başmüdürlüğün uygun göreceği laboratuvar",
      "Serbest Dolaşıma Giriş Rejimi Tebliği (işlenmiş tarım ürünleri) md. 6: üç veya daha fazla gümrük kimyageri yoksa resmî bilimsel kuruluş laboratuvarı",
      "GY 201/4 (17-BEYAN.txt): Bakanlığın akredite dış laboratuvarlarda tekrar tahlil yaptırma yetkisi",
      "GK 243/2 birinci cümle: ikinci tahlili ilk tahlili yapan kimyager dışındaki iki kimyager yapar (ilk kimyager katılmaz)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM", "SAĞDUYU"],
duzey=["AYIRT"],
profil=[3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 6 — GY 588/1-ç: numuneden kaynaklanan itirazda yapılan işlemin adı (tanımdan ad: birinci tahlilin tekrarlanması ↔ ikinci tahlil)
dict(
konu="İtirazlar", blok="SB48",
kalip="KAVRAM",
z="Z",
madde="Gümrük Yönetmeliği md. 588, 589; 4458 sayılı Gümrük Kanunu md. 65, 243",
cek="Numuneden kaynaklanan itirazda tutanakla yeni numune alınır ve birinci tahlil tekrarlanır; ikinci tahlil ilk tahlili yapan dışındaki iki kimyagerce yapılır.",
kok=["Gümrük Yönetmeliği'ne göre tahlil sonuçlarına numuneden kaynaklanan nedenlerden dolayı itiraz edilmesi hâlinde, beyan sahibi veya temsilcisi huzurunda tutanak tanzim edilerek alınan yeni numune ile yapılan işlem aşağıdakilerden hangisidir?"],
d="Birinci tahlilin tekrarlanması",
c=["İkinci tahlil",
   "İkinci muayene",
   "Ayrıntılı muayene",
   "Gümrük rejiminden önce laboratuvar tahlili"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre tahlil sonuçlarına numuneden kaynaklanan nedenlerden dolayı itiraz edilmesi hâlinde, beyan sahibi veya temsilcisi huzurunda Yönetmelik ekindeki tutanak tanzim edilerek tekrar alınan numune ile birinci tahlil tekrarlanır; bu analizler için Gümrük Laboratuvarları Tahlil Ücretleri Listesinde belirtilen tutarda ücret alınır. İkinci tahlil ise tahlil sonucuna itiraz üzerine, birinci tahlilin yapıldığı gümrük laboratuvarında görevli olan ve ilk tahlili yapan kimyager dışındaki iki kimyager tarafından yapılan ve sonucu eşyanın teknik özellik ve niteliklerinin tayin ve tespiti bakımından kesin olan ayrı bir işlemdir; sorun numunenin kendisinden kaynaklanıyorsa yeni numuneyle ikinci tahlile değil, birinci tahlilin tekrarına gidilir. Gümrük Kanunu'nda ikinci muayene, kontrol amacıyla muayenesi yapılmış ve işlemleri tamamlanmış eşyanın yeniden muayenesidir; ayrıntılı muayene, beyanın doğruluğunu araştırmak üzere numune alınabilen muayenedir. Gümrük rejiminden önce laboratuvar tahlili ise Yönetmelikte yükümlünün başvurusu üzerine eşyanın rejim beyanında bulunulmadan önce tahlile gönderilmesidir. En güçlü çeldirici 'İkinci tahlil'dir: tahlil sonucuna her itirazda ikinci tahlil yapılacağını düşünen aday bu seçeneği işaretler. Bu nedenle doğru cevap 'Birinci tahlilin tekrarlanması' seçeneğidir. (MD GY 588, 589; GK 65, 243)",
kanit=K + " | Numuneden kaynaklanan nedenlerden dolayı itiraz edilmesi halinde, beyan sahibi veya temsilcisi huzurunda ek-25'te yer alan tutanak tanzim edilerek tekrar alınan numune ile birinci tahlil tekrarlanır || " + K + " | Birinci tahlilin tekrarlanması amacıyla yapılan analizler için || " + K + " | İtiraz üzerine, birinci tahlilin yapıldığı gümrük laboratuvarında görevli olan ve ilk tahlili yapan kimyager dışındaki iki kimyager tarafından ikinci tahlil yapılır || 17-BEYAN.txt | muayenesi yapılmış ve işlemleri tamamlanmış eşyanın ikinci muayenesini her zaman yapabilirler || 17-BEYAN.txt | Eşyayı muayene edebilir ve ayrıntılı muayene veya tahlil amacıyla numune alabilirler || 17-BEYAN.txt | Gümrük rejiminden önce eşyanın laboratuvar tahliline tabi tutulması",
yuva=["GK 243/2 ve GY 589/1-a: ikinci tahlil, itiraz üzerine ilk tahlili yapan dışındaki iki kimyagerce yapılır (numuneden kaynaklanan itirazda değil)",
      "GK 65/3 (17-BEYAN.txt): kontrol amacıyla işlemleri tamamlanmış eşyanın ikinci muayenesi",
      "GK 65/1-b (17-BEYAN.txt): beyanın doğruluğunu araştırmak üzere ayrıntılı muayene amacıyla numune alınması",
      "GY 196/A (17-BEYAN.txt): yükümlünün başvurusu üzerine gümrük rejiminden önce laboratuvar tahlili"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"],
duzey=["TANIMA", "AYIRT"],
profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 7 — GY 585/4: vaka (taahhütsüz posta → kayda giriş tarihi; ayna: S20)
dict(
konu="İtirazlar", blok="SB48",
kalip="OLAY",
z="Z",
madde="Gümrük Yönetmeliği md. 585",
cek="Taahhütsüz postayla veya doğrudan yapılan itirazda kayda giriş tarihi, taahhütlü postada postaya veriliş tarihi süre tespitinde esas alınır.",
kok=["Gümrük Yönetmeliği'nin itirazların süresi içinde yapılıp yapılmadığının tespitine ilişkin hükümleri çerçevesinde aşağıdaki olay verilmiştir:",
     "- Gümrük müdürlüğünce düzenlenen ek tahakkuk kararı yükümlüye 2 Mayıs 2024 tarihinde tebliğ edilmiştir.",
     "- Yükümlü, itiraz dilekçesini 13 Mayıs 2024 tarihinde taahhütlü olmayan posta yoluyla göndermiştir.",
     "- Dilekçe, itirazın yapıldığı gümrük idaresinin kaydına 21 Mayıs 2024 tarihinde girmiştir.",
     "Buna göre aşağıdakilerden hangisi doğrudur?"],
d="Dilekçenin kayda giriş tarihi esas alınır; itiraz süresi içinde yapılmamıştır.",
c=["Dilekçenin postaya verildiği tarih esas alınır; itiraz süresi içinde yapılmıştır.",
   "Dilekçenin kayda giriş tarihi esas alınır; itiraz süresi içinde yapılmıştır.",
   "Dilekçe süresi içinde yanlış makama verilmiş gibi işlem görür; itiraz süresinde yapılmış sayılır.",
   "İtirazın idarece karara bağlandığı tarih esas alınır; itiraz süresi içinde yapılmamıştır."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre yükümlüler, tebliğ edilen gümrük vergileri, cezalar ve idari kararlara karşı tebliğ tarihinden itibaren on beş gün içinde itiraz edebilir. İtirazın süresinde olup olmadığı tespit edilirken taahhütlü posta ile yapılan itirazlarda dilekçenin postaya verildiği tarih; posta yolu ile veya doğrudan ilgili gümrük idaresine yapılan itirazlarda ise dilekçenin itirazın yapıldığı gümrük idaresinin kaydına giriş tarihi dikkate alınır. Olayda dilekçe taahhütsüz gönderildiği için 13 Mayıs değil, 21 Mayıs esas alınır. Tebliğ 2 Mayıs 2024 Perşembe günü yapıldığından on beş günlük süre, iş günü olan 17 Mayıs 2024 Cuma günü dolmuştur; 21 Mayıs süre dışındadır. Vakaya saklanan istisna gönderim türüdür: dilekçe taahhütlü gönderilseydi postaya veriliş tarihi esas alınacak ve itiraz süresinde sayılacaktı. Kayda giriş tarihini esas alıp itirazı süresinde sayan aday, idarenin otuz günlük karar süresini itiraz süresi sanmıştır. Bu nedenle doğru cevap 'Dilekçenin kayda giriş tarihi esas alınır; itiraz süresi içinde yapılmamıştır.' seçeneğidir. (MD GY 585; GK 242)",
kanit=K + " | tebliğ tarihinden itibaren onbeş gün içinde bir üst makama (…)[153], üst makam yoksa aynı makama || " + K + " | Taahhütlü olarak posta yolu ile yapılacak itirazlarda, itiraz dilekçesinin postaya verildiği tarih || " + K + " | Posta yolu ile veya doğrudan ilgili gümrük idaresine yapılacak itirazlarda, itiraz dilekçesinin itirazın yapıldığı gümrük idaresinin kaydına giriş tarihi || " + K + " | İdareye intikal eden itirazlar otuz gün içinde karara bağlanarak",
yuva=["GY 585/4-a: taahhütlü postada postaya verildiği tarih (vakada saklanan istisna)",
      "GK 242/2: otuz gün idarenin karar süresidir; itiraz süresi sanılırsa 21 Mayıs süre içinde görünür",
      "GK 242/3: süresi içinde yanlış makama verilen dilekçe süresinde yapılmış sayılır (olayda yanlış makam yok)",
      "GK 242/2: itirazların karara bağlanması (süre tespitinde esas alınan tarih değildir)"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "BAŞLANGIÇ", "AD-HESAP"],
duzey=["UYGULAMA"],
profil=[1],
olumsuz=False, vaka=True, baslangic=False,
eksen=0, ayna="Taahhütlü ↔ taahhütsüz posta (süre tespiti)",
guncellik="",
cikmis="",
kapsamli=False,
),

# 8 — GY 587/1: karardan önce eşyanın çekilmesi şartları (liste dışı: gümrük müşaviri — meslek yanlılığı)
dict(
konu="İtirazlar", blok="SB48",
kalip="KAPSAM_DIŞI",
z="O",
madde="Gümrük Yönetmeliği md. 587",
cek="Karardan önce eşya çekiminde tebellüğ ve dilekçe, teminat, yargıya intikalin belgelenmesi, istenen bilgi-belge aranır; gümrük müşaviri aracılığı şartı yoktur.",
kok=["Gümrük Yönetmeliği'ne göre yükümlülerin, mercilerince verilecek kararlardan önce ihtilaf konusu eşyayı çekebilmeleri için aranan şartlar arasında aşağıdakilerden hangisi yer almaz?"],
d="Eşyanın çekilmesine ilişkin işlemlerin yükümlü adına bir gümrük müşaviri tarafından takip edilmesi",
c=["Kararların yükümlüce tebellüğ edilmiş olması ve taleplerinin bir dilekçe ile gümrüğe verilmiş olması",
   "Uyuşmazlığın idari yargı merciine intikali hâlinde bu hususun belgelenmesi",
   "İdarece gerekli görülecek her türlü bilgi veya belgenin sunulması",
   "Düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hâllerde vergi tahakkukları arasındaki farkın teminata bağlanması"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre yükümlüler, mercilerince verilecek kararlardan önce ihtilaf konusu eşyayı çekmek isterlerse istekleri sayılan şartlarla kabul olunur: kararların yükümlüce tebellüğ edilmiş olması ve talebin bir dilekçe ile gümrüğe verilmesi; yükümlünün beyanına göre yapılan vergi tahakkukları ile idarece tahakkuk ettirilen bütün vergiler arasındaki farkın ve eşyanın alıcısı adına düzenlenen para cezalarının teminata bağlanması; uyuşmazlığın idari yargı merciine intikali hâlinde bunun belgelenmesi; idarece gerekli görülecek her türlü bilgi veya belgenin sunulması; düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hâllerde vergi farkının teminata bağlanması (bu son şart 03.01.2023 tarihli değişiklikle eklenmiştir). İşlemlerin bir gümrük müşaviri tarafından takip edilmesi bu şartlar arasında sayılmamıştır; talep dilekçesini yükümlü kendisi de verebilir. Bu seçenek, gümrük müşavirinin her işlemde zorunlu olduğu önyargısını yoklar. Bu nedenle doğru cevap 'Eşyanın çekilmesine ilişkin işlemlerin yükümlü adına bir gümrük müşaviri tarafından takip edilmesi' seçeneğidir. (MD GY 587)",
kanit=K + " | Yükümlüler, mercilerince verilecek kararlardan önce, ihtilaf konusu eşyayı çekmek isterlerse, aşağıda yazılı şartlarla istekleri kabul olunur ve eşyanın çekilmesine izin verilir || " + K + " | Kararların yükümlüce tebellüğ edilmiş olması ve taleplerinin bir dilekçe ile gümrüğe verilmiş olması || " + K + " | Uyuşmazlığın idari yargı merciine intikali halinde bu hususun belgelenmesi || " + K + " | İdarece gerekli görülecek her türlü bilgi veya belgenin sunulması || " + K + " | Düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hallerde yükümlünün beyanına göre yapılan vergi tahakkukları ile gümrük idaresince tahakkuk ettirilen bütün vergiler arasındaki farkın teminata bağlanması",
yuva=["GY 587/1-a: kararların tebellüğü ve dilekçe (listede)",
      "GY 587/1-c: uyuşmazlığın idari yargıya intikalinin belgelenmesi (listede)",
      "GY 587/1-ç: idarece gerekli görülen bilgi veya belge (listede)",
      "GY 587/1-d: düşük kıymet şüphesinde vergi farkının teminata bağlanması (listede, 2023'te eklendi)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[3, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 9 — GY 587/1-d, 587/3: önermeli, yanlıştır kökü (I ve III) — başlangıç anı
dict(
konu="İtirazlar", blok="SB48",
kalip="ÖNERMELİ",
z="Z",
madde="Gümrük Yönetmeliği md. 587",
cek="Düşük kıymet araştırmasında vergi farkı teminata bağlanır; araştırma talep tarihinden itibaren bir yılda bitmezse mevcut verilerle sonuçlandırılır; sonraki farklar için işlem yapılır.",
kok=["Gümrük Yönetmeliği'ne göre düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hâllerde ihtilaf konusu eşyanın karardan önce çekilmesine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Kıymet araştırmasının sonuçlanması için öngörülen bir yıllık süre, beyannamenin tescil tarihinden itibaren işlemeye başlar.",
     "II. Araştırmanın öngörülen sürede sonuçlanmaması hâlinde işlem, gümrük idaresinde mevcut verilere göre sonuçlandırılır.",
     "III. Öngörülen süreden sonra alınan cevaplar çerçevesinde vergi farkı ortaya çıksa dahi, işlem sonuçlandırılmış olduğundan ayrıca bir işlem yapılmaz.",
     "IV. Eşyanın çekilebilmesi için yükümlünün beyanına göre yapılan vergi tahakkukları ile gümrük idaresince tahakkuk ettirilen bütün vergiler arasındaki farkın teminata bağlanması gerekir.",
     "Yukarıdaki ifadelerden hangileri yanlıştır?"],
d="I ve III",
c=["Yalnız I", "Yalnız III", "II ve IV", "I, III ve IV"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hâllerde eşyanın karardan önce çekilebilmesi için yükümlünün beyanına göre yapılan vergi tahakkukları ile gümrük idaresince tahakkuk ettirilen bütün vergiler arasındaki farkın teminata bağlanması gerekir (IV doğru; şart 03.01.2023 tarihli değişiklikle eklenmiştir). Araştırma, bu uygulamanın talep edildiği tarihten itibaren bir yılda sonuçlanmazsa işlem gümrük idaresinde mevcut verilere göre sonuçlandırılır (II doğru). Bir yıllık süre beyannamenin tescil tarihinden değil, eşyanın karardan önce çekilmesi uygulamasının talep edildiği tarihten başlar (I yanlış). Bu süreden sonra alınan cevaplar çerçevesinde vergi farkı ortaya çıkarsa gerekli işlemler yerine getirilir; işlemin mevcut verilerle sonuçlandırılmış olması farkın takibine engel değildir (III yanlış). En güçlü tuzak I'dir: süre doğru verilmiş, yalnızca başlangıç anı değiştirilmiştir. Bu nedenle doğru cevap 'I ve III' seçeneğidir. (MD GY 587)",
kanit=K + " | Düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hallerde yükümlünün beyanına göre yapılan vergi tahakkukları ile gümrük idaresince tahakkuk ettirilen bütün vergiler arasındaki farkın teminata bağlanması || " + K + " | araştırmanın bu maddenin uygulanmasının talep edildiği tarihten itibaren bir yılda sonuçlanmaması halinde, gümrük idaresinde mevcut verilere göre işlem sonuçlandırılır || " + K + " | Bu süreden sonra alınan cevaplar çerçevesinde vergi farkı ortaya çıkan hallerde gerekli işlemler yerine getirilir",
yuva=["Eksik seçim: yalnız başlangıç anı değişikliğini fark eden aday",
      "Eksik seçim: yalnız sonradan gelen cevaplara ilişkin değişikliği fark eden aday",
      "Ters seçim: doğru olan II ve IV'ü yanlış sayan aday (olumsuz kökü olumlu okur)",
      "IV'ü de yanlış sayan aday: düşük kıymet şüphesinde vergi farkının teminata bağlanması şartı aranır (GY 587/1-d)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "TERSİNE"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=True, vaka=False, baslangic=True,
eksen=0, ayna="Eşya çekiminde teminat: genel hâl ↔ düşük kıymet",
guncellik="",
cikmis="",
kapsamli=False,
),

# 10 — GY 587/2: karardan önce eşya çekimi hükmünün uygulanmadığı hâl (olumsuz: yasaklama ve kısıtlama istisnası)
dict(
konu="İtirazlar", blok="SB48",
kalip="KAPSAM_DIŞI",
z="Z",
madde="Gümrük Yönetmeliği md. 587",
cek="Kesinleşmeden önceki uyuşmazlık yasaklama ve kısıtlama hükümlerini ihlal eder mahiyetteyse karardan önce eşya çekimine ilişkin hüküm uygulanmaz.",
kok=["Gümrük Yönetmeliği'ne göre aşağıdaki durumların hangisinde, ihtilaf konusu eşyanın mercilerince verilecek kararlardan önce çekilebilmesine ilişkin hüküm uygulanmaz?"],
d="Vergi tahakkukunun kesinleşmesinden önce idare ile yükümlü arasında çıkan uyuşmazlığın yürürlükteki yasaklama ve kısıtlama hükümlerini ihlal eder mahiyette olması",
c=["Vergi tahakkukunun kesinleşmesinden önce idare ile yükümlü arasında tahakkuk ettirilen vergi tutarına ilişkin uyuşmazlık çıkması",
   "Uyuşmazlığın idari yargı merciine intikal etmiş olması",
   "Uyuşmazlığın düşük kıymet beyanı şüphesiyle yapılan kıymet araştırmasından kaynaklanması",
   "Uyuşmazlık nedeniyle eşyanın alıcısı adına para cezası düzenlenmiş olması"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre yükümlüler, mercilerince verilecek kararlardan önce ihtilaf konusu eşyayı çekmek isterlerse; kararların tebellüğü ve dilekçe, vergi farkı ile eşyanın alıcısı adına düzenlenen para cezalarının teminata bağlanması, uyuşmazlığın idari yargı merciine intikali hâlinde bunun belgelenmesi, idarece istenen bilgi ve belgelerin sunulması ve düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hâllerde vergi farkının teminata bağlanması şartlarıyla eşyanın çekilmesine izin verilir. Ancak vergi tahakkukunun kesinleşmesinden önce idare ile yükümlü arasında çıkan uyuşmazlık yürürlükteki yasaklama ve kısıtlama hükümlerini ihlal eder mahiyette olduğu takdirde bu hüküm uygulanmaz; teminat ve belge şartları karşılansa da eşya karardan önce çekilemez. Vergi tutarına ilişkin uyuşmazlıkta, uyuşmazlığın idari yargıya intikal ettiği hâlde, düşük kıymet şüphesiyle kıymet araştırmasında ve alıcı adına para cezası düzenlenen hâlde ise hüküm uygulanır; Yönetmelik bu hâllerde yalnızca teminat veya belgeleme şartı arar. Tuzak, teminat verildiğinde her uyuşmazlıkta eşyanın çekilebileceğini düşünmektir. Bu nedenle doğru cevap 'Vergi tahakkukunun kesinleşmesinden önce idare ile yükümlü arasında çıkan uyuşmazlığın yürürlükteki yasaklama ve kısıtlama hükümlerini ihlal eder mahiyette olması' seçeneğidir. (MD GY 587)",
kanit=K + " | Vergi tahakkukunun kesinleşmesinden önce idare ile yükümlü arasında çıkan uyuşmazlık yürürlükteki yasaklama ve kısıtlama hükümlerini ihlal eder mahiyette olduğu takdirde bu madde hükmü uygulanmaz || " + K + " | Yükümlüler, mercilerince verilecek kararlardan önce, ihtilaf konusu eşyayı çekmek isterlerse, aşağıda yazılı şartlarla istekleri kabul olunur ve eşyanın çekilmesine izin verilir || " + K + " | Uyuşmazlığın idari yargı merciine intikali halinde bu hususun belgelenmesi || " + K + " | Düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hallerde yükümlünün beyanına göre yapılan vergi tahakkukları ile gümrük idaresince tahakkuk ettirilen bütün vergiler arasındaki farkın teminata bağlanması || " + K + " | farkın ve eşyanın alıcısı adına düzenlenen para cezalarının",
yuva=["GY 587/1-b: vergi farkına ilişkin uyuşmazlıkta fark teminata bağlanarak eşya çekilebilir (hüküm uygulanır)",
      "GY 587/1-c: idari yargıya intikal hâlinde belgelenme şartıyla eşya çekilebilir (hüküm uygulanır)",
      "GY 587/1-d: düşük kıymet şüphesinde vergi farkı teminata bağlanarak eşya çekilebilir (hüküm uygulanır)",
      "GY 587/1-b: alıcı adına düzenlenen para cezaları teminata bağlanarak eşya çekilebilir (hüküm uygulanır)"],
yakinlik="BİREBİR",
tuzak=["İSTİSNA", "KOMŞU", "SAĞDUYU"],
duzey=["AYIRT"],
profil=[3, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 11 — GY 588/1-b: tahlile itiraz dilekçesinin içeriği (liste dışı)
dict(
konu="İtirazlar", blok="SB48",
kalip="KAPSAM_DIŞI",
z="O",
madde="Gümrük Yönetmeliği md. 588",
cek="Tahlile itiraz dilekçesinde beyanname no-tescil tarihi, eşyanın cins-türü, itiraz yönü ve gözlemci kimyager bilgisi gösterilir; kıymet ve vergi tutarı aranmaz.",
kok=["Gümrük Yönetmeliği'ne göre tahlil sonuçlarına karşı verilecek itiraz dilekçesinde gösterilmesi gereken hususlar arasında aşağıdakilerden hangisi yer almaz?"],
d="Eşyanın gümrük kıymeti ile itiraz edilen vergi tutarı",
c=["Beyanname numarası ve tescil tarihi",
   "Eşyanın cins ve türü",
   "Tahlile ne yönden itirazda bulunulduğu",
   "Gözlemci kimyager bulundurulacaksa adı soyadı ve adresi"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre tahlil sonuçlarına karşı tebliğ tarihinden itibaren on beş gün içinde gümrük ve muhafaza başmüdürlüğüne verilecek dilekçede beyanname numarası ve tescil tarihi, eşyanın cins ve türü, tahlile ne yönden itirazda bulunulduğu, gözlemci kimyager bulundurulup bulundurulmayacağı ve bulundurulacaksa adı soyadı ile adresi gösterilir. Eşyanın gümrük kıymeti ve itiraz edilen vergi tutarı bu sayımda yer almaz. Vergi farkı, itiraz sürerken eşyanın çekilmek istenmesi hâlinde teminata bağlanacak tutar olarak başka bir hükümde geçer. Tahlil itirazı eşyanın teknik özellik ve niteliklerine yöneliktir; sağduyuyla 'vergiyle ilgili itirazda tutar da yazılır' diye düşünen aday kapalı listeye yabancı unsur ekler. Bu nedenle doğru cevap 'Eşyanın gümrük kıymeti ile itiraz edilen vergi tutarı' seçeneğidir. (MD GY 588)",
kanit=K + " | Dilekçede, beyanname numarası ve tescil tarihi ile eşyanın cins ve türü, tahlile ne yönden itirazda bulunulduğu, gözlemci kimyager bulundurulup bulundurulmayacağı, bulundurulacaksa adı soyadı ve adresi gösterilir",
yuva=["GY 588/1-b: beyanname numarası ve tescil tarihi (listede)",
      "GY 588/1-b: eşyanın cins ve türü (listede)",
      "GY 588/1-b: tahlile ne yönden itiraz edildiği (listede)",
      "GY 588/1-b: gözlemci kimyagerin adı soyadı ve adresi (listede)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"],
duzey=["TANIMA"],
profil=[1, 3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 12 — GY 588/1-c: ikinci tahlil ücreti (tutar ve birim)
dict(
konu="İtirazlar", blok="SB48",
kalip="ORAN-TUTAR",
z="Z",
madde="Gümrük Yönetmeliği md. 588",
cek="Tahlil itirazında ikinci tahlil için numune başına 2.330 TL ücret alınır; Ek-24 listesi tekrarlanan birinci tahlile aittir.",
kok=["Gümrük Yönetmeliği'ne göre tahlil sonuçlarına yapılan itiraz üzerine ikinci tahlil için alınacak ücret aşağıdakilerden hangisidir?"],
d="Numune başına 2.330 TL",
c=["Beyanname başına 2.330 TL",
   "Tahlile itiraz edilen her eşya cinsi için 2.330 TL",
   "Yönetmelik ekindeki Gümrük Laboratuvarları Tahlil Ücretleri Listesinde belirtilen tutar",
   "Laboratuvarca belirlenen ve yükümlü tarafından peşin ödenen tahlil ücreti"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre idarece yapılan inceleme sonunda itirazın kanuni süresi içinde yapıldığı ve eşyanın örneklerinin henüz gümrükte bulunduğu tespit olunursa, ikinci tahlil için numune başına 2.330 TL ücret alınır (tutar 22.03.2018 tarihli değişiklikle belirlenmiştir). Ücret beyanname ya da eşya cinsi esasına göre değil, numune esasına göre alınır. Gümrük Laboratuvarları Tahlil Ücretleri Listesindeki tutar, numuneden kaynaklanan nedenlerle itiraz edildiğinde birinci tahlilin tekrarlanması için yapılan analizlere aittir. Yükümlünün peşin ödediği ücret ise işlenmiş tarım ürünlerine ilişkin tebliğde gümrük laboratuvarı dışında yapılan tahliller için öngörülmüştür. En güçlü çeldirici, tekrarlanan birinci tahlile ait liste tutarıdır. Bu nedenle doğru cevap 'Numune başına 2.330 TL' seçeneğidir. (MD GY 588)",
kanit=K + " | İdarece yapılan inceleme sonunda, itirazın kanuni süresi içinde yapıldığı ve eşyanın örneklerinin henüz gümrükte bulunduğu tespit olunursa, ikinci tahlil için numune başına 2.330 TL ücret alınır || " + K + " | Birinci tahlilin tekrarlanması amacıyla yapılan analizler için bu Yönetmeliğin 24 numaralı ekinde yer alan || " + SD + " | Gümrük laboratuarı dışında yapılacak tahlillere ilişkin ücretler yükümlü tarafından peşin olarak ödenir",
yuva=["GY 588/1-b: dilekçede beyanname numarası geçer; ücretin birimi beyanname değildir",
      "GY 588/1-b: dilekçede eşyanın cins ve türü geçer; ücretin birimi eşya cinsi değildir",
      "GY 588/1-ç: Ek-24 listesindeki tutar tekrarlanan birinci tahlile aittir",
      "Serbest Dolaşıma Giriş Rejimi Tebliği (işlenmiş tarım ürünleri) md. 6: gümrük laboratuvarı dışındaki tahlil ücretleri yükümlüce peşin ödenir"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"],
duzey=["HATIRLAMA", "AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 13 — GY 588/1-c: ikinci tahlil ücreti alınmasının şartları
dict(
konu="İtirazlar", blok="SB48",
kalip="ŞART",
z="O",
madde="Gümrük Yönetmeliği md. 588",
cek="İkinci tahlil ücreti için idare, itirazın kanuni süresinde yapıldığını ve eşya örneklerinin henüz gümrükte bulunduğunu tespit etmelidir.",
kok=["Gümrük Yönetmeliği'ne göre tahlil sonuçlarına yapılan itirazda ikinci tahlil için ücret alınabilmesi bakımından idarece yapılan inceleme sonunda tespit edilmesi gereken hususlar aşağıdakilerden hangisinde birlikte doğru olarak verilmiştir?"],
d="İtirazın kanuni süresi içinde yapıldığı ve eşyanın örneklerinin henüz gümrükte bulunduğu",
c=["İtirazın kanuni süresi içinde yapıldığı ve dilekçede gözlemci kimyagerin adı soyadı ile adresinin gösterildiği",
   "Eşyanın örneklerinin henüz gümrükte bulunduğu ve itirazın numuneden kaynaklanan nedenlere dayanmadığı",
   "İtirazın başmüdürlüğe yapıldığı ve vergi farkının teminata bağlandığı",
   "İtirazın kanuni süresi içinde yapıldığı ve birinci tahlilin bir gümrük laboratuvarında yapıldığı"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre idarece yapılan inceleme sonunda itirazın kanuni süresi içinde yapıldığı ve eşyanın örneklerinin henüz gümrükte bulunduğu tespit olunursa ikinci tahlil için ücret alınır. İki unsur birlikte aranır. Gözlemci kimyagerin adı soyadı ve adresi, gözlemci bulundurulacaksa dilekçede gösterilecek bilgidir; ücretin şartı değildir. İtirazın numuneden kaynaklanması ikinci tahlili değil birinci tahlilin tekrarını gerektirir; bu ayrı bir usuldür. Vergi farkının teminata bağlanması eşyanın karardan önce çekilmesine, birinci tahlilin gümrük laboratuvarı dışında yapılması ise ikinci tahlilin yapılacağı yere ilişkindir. En güçlü çeldirici, kanuni süre şartını doğru verip ikinci unsuru dilekçe içeriğinden alan seçenektir. Bu nedenle doğru cevap 'İtirazın kanuni süresi içinde yapıldığı ve eşyanın örneklerinin henüz gümrükte bulunduğu' seçeneğidir. (MD GY 588)",
kanit=K + " | İdarece yapılan inceleme sonunda, itirazın kanuni süresi içinde yapıldığı ve eşyanın örneklerinin henüz gümrükte bulunduğu tespit olunursa || " + K + " | gözlemci kimyager bulundurulup bulundurulmayacağı, bulundurulacaksa adı soyadı ve adresi gösterilir || " + K + " | Numuneden kaynaklanan nedenlerden dolayı itiraz edilmesi halinde || " + K + " | Birinci tahlilin gümrük laboratuvarları haricinde bir laboratuvarda yapılmış olması halinde",
yuva=["GY 588/1-b: gözlemci kimyagerin adı soyadı ve adresi dilekçe içeriğidir",
      "GY 588/1-ç: numuneden kaynaklanan itirazda birinci tahlil tekrarlanır (ayrı usul)",
      "GK 243/1 ve GY 587/1-b: başmüdürlük itiraz makamı, vergi farkı teminatı eşya çekimi şartı",
      "GY 589/1-c: birinci tahlilin gümrük laboratuvarı dışında yapılması ikinci tahlilin yerine ilişkindir"],
yakinlik="BİREBİR",
tuzak=["ŞART", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 14 — Tahsilat Tebliği md. 12/3: idari dava sonucunun diğer ilgiliye etkisi ve iştirak istisnası (eksen 15)
dict(
konu="İtirazlar", blok="SB48",
kalip="YANLIŞ",
z="Z",
madde=TT + " md. 12",
cek="Bir ilgilinin davası diğerine ilişkin işlemleri zamanaşımı gözetilerek etkiler; vergi aslına bağlı olmayan cezaya konu fiil iştirakle işlenmişse bu kural uygulanmaz.",
kok=[TT + "'ye göre, alacağa ilişkin olarak idarece düzenlenip ilgililere tebliğ edilen kararlara karşı ilgililerden birinin idari yargıya başvurması durumunda, aynı alacağa dair diğer ilgili hakkında yapılacak işlemlere ilişkin aşağıdakilerden hangisi söylenemez?"],
d="Vergi aslına bağlı olmayan para cezasına konu kabahat fiili iştirak hâlinde işlenmişse de diğer fail hakkındaki işlemler dava sonucuna göre değerlendirilir.",
c=["Diğer ilgili hakkında yapılacak işlemler değerlendirilirken tahsil zamanaşımı süreleri göz önünde bulundurulur.",
   "İlgililerden birinin açtığı davanın sonucu, aynı alacak bakımından diğer ilgili hakkındaki işlemlerin değerlendirilmesinde esas alınır.",
   "Bu değerlendirme usulü, ilgililerden birinin kendisine tebliğ edilen karara karşı idari yargıya başvurmasıyla gündeme gelir.",
   "Vergi aslına bağlı para cezalarında da diğer ilgili hakkındaki işlemler idari dava sürecinin sonuçlarına göre değerlendirilir."],
sirali=False,
g="Tahsilat İşlemlerine ilişkin Gümrük Genel Tebliği'ne göre alacağa ilişkin olarak idarece düzenlenip ilgililere tebliğ edilen kararlara karşı ilgililerden birinin idari yargıya başvurması durumunda, aynı alacağa dair diğeri hakkında yapılacak işlemler tahsil zamanaşımı süreleri dikkate alınarak idari dava süreci sonuçlarına göre değerlendirilir. Vergi aslına bağlı olmayan para cezalarına konu kabahat fiilinin iştirak hâlinde işlenmesi durumunda ise bu hüküm uygulanmaz; çünkü vergi alacağı tek ve ortak olduğu hâlde, vergi aslına bağlı olmayan para cezası her fail için ayrı ve kişiseldir. Bu nedenle bir failin açtığı davanın sonucu diğer failin cezasına yansıtılmaz. İstisna yalnızca vergi aslına bağlı 'olmayan' cezalar için öngörüldüğünden, vergi aslına bağlı para cezalarında genel kural uygulanır. Olumsuz kökü hızlı okuyan aday, istisnanın tersine çevrildiği ifadeyi doğru sanır. Bu nedenle doğru cevap 'Vergi aslına bağlı olmayan para cezasına konu kabahat fiili iştirak hâlinde işlenmişse de diğer fail hakkındaki işlemler dava sonucuna göre değerlendirilir.' seçeneğidir. (MD Tebliğ 12)",
kanit=K + " | Alacağa ilişkin olarak idare tarafından düzenlenerek ilgililere tebliğ edilen kararlara karşı ilgililerden birinin idari yargıya başvurması durumunda, aynı alacağa dair diğeri hakkında yapılacak işlemler, tahsil zamanaşımı süreleri dikkate alınarak, idari dava süreci sonuçlarına göre değerlendirilir || " + K + " | Vergi aslına bağlı olmayan para cezalarına konu kabahat fiilinin iştirak dahilinde işlenmesi durumunda bu hüküm uygulanmaz",
yuva=["Tebliğ md. 12/3: tahsil zamanaşımı süreleri dikkate alınır (doğru ifade)",
      "Tebliğ md. 12/3: diğeri hakkındaki işlemler idari dava süreci sonuçlarına göre değerlendirilir (doğru ifade, parafraz)",
      "Tebliğ md. 12/3: kural, ilgililerden birinin idari yargıya başvurmasıyla işler (doğru ifade)",
      "Tebliğ md. 12/3: istisna yalnızca vergi aslına bağlı olmayan cezalarda; vergi aslına bağlı cezada genel kural (eksen 15'in öbür kutbu)"],
yakinlik="PARAFRAZ",
tuzak=["İSTİSNA", "TERSİNE", "UNSUR"],
duzey=["AYIRT"],
profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False,
eksen=15, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 15 — Tahsilat Tebliği md. 12/2: dolaylı temsilcinin itirazı ile asıl yükümlünün uzlaşma başvurusu
dict(
konu="İtirazlar", blok="SB48",
kalip="SONUÇ",
z="O",
madde=TT + " md. 12",
cek="Müteselsil sorumlu asıl yükümlü uzlaşma, dolaylı temsilci itiraz yoluna giderse itiraz, uzlaşma talebi sonuçlandıktan sonra değerlendirmeye alınır.",
kok=[TT + "'ye göre, aynı gümrük vergilerinin ödenmesinden asıl yükümlü ile birlikte müştereken ve müteselsilen sorumlu olan dolaylı temsilcinin Gümrük Kanunu uyarınca itiraz ettiği, asıl yükümlünün ise uzlaşma başvurusunda bulunduğu durumda dolaylı temsilcinin itirazı hakkında aşağıdakilerden hangisi doğrudur?"],
d="Asıl yükümlünün uzlaşma talebi sonuçlanıncaya kadar beklenir; itiraz bu talep sonuçlandıktan sonra ele alınır.",
c=["Uzlaşma başvurusundan bağımsız olarak, idareye intikal ettiği tarihten itibaren otuz gün içinde karara bağlanır.",
   "Asıl yükümlünün uzlaşma başvurusu, dolaylı temsilcinin itirazı sonuçlanıncaya kadar değerlendirmeye alınmaz.",
   "Aynı alacak için itiraz ve uzlaşma yolu birlikte kullanılamayacağından itiraz incelenmeksizin reddedilir.",
   "Asıl yükümlünün açacağı idari davanın sonucu beklenerek itiraz dava sonucuna göre değerlendirilir."],
sirali=False,
g="Tahsilat İşlemlerine ilişkin Gümrük Genel Tebliği'ne göre aynı gümrük vergilerinin ödenmesinden asıl yükümlü ile birlikte dolaylı temsilcinin müştereken ve müteselsilen sorumlu olması durumunda, taraflardan birinin uzlaşma başvurusunda bulunması, diğerinin ise Gümrük Kanunu'na göre itiraz etmesi hâlinde itiraz, uzlaşma talebi sonuçlandıktan sonra değerlendirmeye alınır. Sıra uzlaşmadan yanadır; uzlaşma başvurusu itirazın sonucunu beklemez. İtiraz reddedilmez: itiraz ve uzlaşma hakkının aynı anda kullanılamaması Uzlaşma Yönetmeliği'nde aynı yükümlü için öngörülmüştür; burada iki ayrı sorumlu iki ayrı yola başvurmuştur. Otuz günlük karar süresi genel kuraldır; idari dava sonucunun beklenmesi ise ilgililerden birinin idari yargıya başvurduğu hâle aittir. En güçlü çeldirici, sıralamayı tersine çeviren seçenektir. Bu nedenle doğru cevap 'Asıl yükümlünün uzlaşma talebi sonuçlanıncaya kadar beklenir; itiraz bu talep sonuçlandıktan sonra ele alınır.' seçeneğidir. (MD Tebliğ 12)",
kanit=K + " | Aynı gümrük vergilerinin ödenmesinden asıl yükümlü ile birlikte dolaylı temsilcinin müştereken ve müteselsilen sorumlu olması durumunda, taraflardan birinin uzlaşma başvurusunda bulunması, diğerinin ise Kanunun 242 nci maddesine göre itiraz etmesi halinde itiraz, uzlaşma talebi sonuçlandıktan sonra değerlendirmeye alınır || " + UZ + " | uzlaşma hakkını aynı anda kullanamaz || " + K + " | idari dava süreci sonuçlarına göre değerlendirilir",
yuva=["GK 242/2: itirazların otuz gün içinde karara bağlanması (genel kural)",
      "Tebliğ md. 12/2'nin tersine çevrilmiş hâli (önce itiraz, sonra uzlaşma)",
      "Uzlaşma Yönetmeliği md. 25: aynı yükümlü itiraz ve uzlaşma hakkını aynı anda kullanamaz",
      "Tebliğ md. 12/3: ilgililerden biri idari yargıya başvurursa diğeri hakkındaki işlemler dava sonucuna göre değerlendirilir"],
yakinlik="PARAFRAZ",
tuzak=["TERSİNE", "KOMŞU"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 16 — Tahsilat Tebliği md. 12/5: 5326 sayılı Kanun uyarınca mahkemelerce verilen idari para cezaları
dict(
konu="İtirazlar", blok="SB48",
kalip="KAPSAM_DIŞI",
z="O",
madde=TT + " md. 12; 4458 sayılı Gümrük Kanunu md. 242, 243",
cek="5326 sayılı Kanun uyarınca mahkemelerce verilen idari para cezalarına Gümrük Kanunu uyarınca itiraz edilemez, uzlaşma istenemez; 5326'daki itiraz yolu izlenir.",
kok=[TT + " ve 4458 sayılı Gümrük Kanunu'nun itirazlara ilişkin hükümlerine göre aşağıdakilerden hangisine karşı Gümrük Kanunu uyarınca itiraz edilemez?"],
d="5326 sayılı Kanun hükümleri uyarınca mahkemeler tarafından verilen idari para cezalarına",
c=["Gümrük idarelerinin amirleri veya yardımcıları tarafından Gümrük Kanunu uyarınca verilen idari yaptırım kararlarına",
   "Kendisine tebligat yapılan yükümlüye tebliğ edilen gelir eksiğine",
   "Yükümlüye tebliğ edilen gümrük vergilerine",
   "Gümrük vergilerinin hesaplanmasında esas alınan kimyevi tahlil sonuçlarına"],
sirali=False,
g="Tahsilat İşlemlerine ilişkin Gümrük Genel Tebliği'ne göre Gümrük Kanunu uyarınca idari yaptırım kararları gümrük idarelerinin amirleri veya yardımcıları tarafından verilir ve bu kararlara karşı itiraz ile uzlaşma usulleri Kanunda belirlenmiştir. Buna karşılık 5326 sayılı Kanun hükümleri uyarınca mahkemeler tarafından verilen idari para cezalarına karşı, mahkeme kararının icrası kapsamında yine 5326 sayılı Kanunda öngörülen itiraz yolu izlenir; bu kararlara karşı Gümrük Kanunu uyarınca itiraz edilemez ve uzlaşma talebinde de bulunulamaz. Tebliğ edilen gelir eksiği ve gümrük vergilerine karşı on beş gün içinde bir üst makama, kimyevi tahlil sonuçlarına karşı ise gümrük ve muhafaza başmüdürlüğüne itiraz edilebilir. En güçlü çeldirici amir ve yardımcılarınca verilen idari yaptırım kararlarıdır: iki seçenekte de 'idari' yaptırım geçer, fark kararı verenin idare mi mahkeme mi olduğundadır. Bu nedenle doğru cevap '5326 sayılı Kanun hükümleri uyarınca mahkemeler tarafından verilen idari para cezalarına' seçeneğidir. (MD Tebliğ 12; GK 242, 243)",
kanit=K + " | 5326 sayılı Kanun hükümleri uyarınca mahkemeler tarafından verilen idari para cezalarına karşı mahkeme kararının icrası kapsamında yine 5326 sayılı Kanunda öngörülen itiraz yolu izleneceğinden bu kararlara karşı Gümrük Kanunu uyarınca itiraz edilemez ve uzlaşma talebinde bulunulamaz || " + K + " | Gümrük Kanunu uyarınca idari yaptırım kararlarının gümrük idarelerinin amirleri veya yardımcıları tarafından verileceği || " + K + " | Tebliğ edilen gelir eksiği ve para cezalarına karşı kendisine tebligat yapılan yükümlü tarafından || " + K + " | kimyevi tahlil sonuçlarına karşı tebliğden itibaren onbeş gün içinde",
yuva=["Tebliğ md. 12/5: amir veya yardımcılarınca verilen idari yaptırım kararlarına Kanundaki itiraz usulü uygulanır",
      "Tebliğ md. 12/1: gelir eksiği ve para cezalarına on beş gün içinde itiraz",
      "GK 242/1: tebliğ edilen gümrük vergilerine itiraz",
      "GK 243/1: kimyevi tahlil sonuçlarına başmüdürlüğe itiraz"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1, 3],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 17 — Tahsilat Tebliği md. 12/4; GY 586: itirazların karara bağlanması (yanlış: bildirimin süre dolduktan sonra yapılması)
dict(
konu="İtirazlar", blok="SB48",
kalip="YANLIŞ",
z="O",
madde=TT + " md. 12; Gümrük Yönetmeliği md. 586; 4458 sayılı Gümrük Kanunu md. 6, 242",
cek="İtiraz otuz günde sonuçlandırılır; karar alınamayacaksa süre dolmadan gerekçeler ve ek süre yükümlüye bildirilir.",
kok=[TT + " ve Gümrük Yönetmeliği'nin itirazların karara bağlanmasına ilişkin hükümlerine göre aşağıdakilerden hangisi yanlıştır?"],
d="Otuz gün içinde karar alınamayacaksa, süre aşımının gerekçeleri ve ek süre, bu süre dolduktan sonra yükümlüye bildirilir.",
c=["İtirazlar otuz gün içinde karara bağlanarak ilgili kişiye tebliğ edilir.",
   "İtirazın karara bağlanmasına ilişkin otuz günlük süreye uyulması mümkün değilse bu süre aşılabilir.",
   "Süre aşımı hâlinde yükümlüye yapılacak bildirimde, süre aşımını gerekli kılan gerekçeler ile karar için gerekli görülen ek süre belirtilir.",
   "İtirazlar karara bağlanırken gerek duyulması hâlinde ilgili gümrük idaresinin mütalaası da alınır."],
sirali=False,
g="Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2)'ye göre itiraz başvurularının otuz gün içerisinde sonuçlandırılması gerekir; bu süre zarfında karar alınamayacaksa sürenin dolmasından önce, süre aşımını gerekli kılan gerekçeler ve ek süre yükümlüye bildirilir. Bildirimin süre dolduktan sonra yapılacağını söyleyen ifade bu nedenle yanlıştır. Gümrük Yönetmeliği'ne göre itirazlar, gerek duyulması hâlinde ilgili gümrük idaresinin mütalaası da alınarak otuz gün içinde karara bağlanır ve ilgili kişiye tebliğ edilir; otuz gün içinde karar alınamadığı durumlarda Gümrük Kanunu'nun kararlara ilişkin genel hükmü uygulanır. Bu hükme göre gümrük idareleri otuz günlük süreye uyamıyorsa süre aşılabilir; ancak idare, sürenin dolmasından önce süre aşımını haklı kılan gerekçeler ile karar için gerekli gördüğü ek süreyi başvuru sahibine bildirir. Tuzak bildirimin zamanındadır: süre aşılabilir, fakat gerekçe ve ek süre süre dolmadan bildirilir. Bu nedenle doğru cevap 'Otuz gün içinde karar alınamayacaksa, süre aşımının gerekçeleri ve ek süre, bu süre dolduktan sonra yükümlüye bildirilir.' seçeneğidir. (MD Tebliğ 12; GY 586; GK 6, 242)",
kanit=K + " | Yapılan itiraz başvurularının, otuz gün içerisinde sonuçlandırılması gerekmekle birlikte eğer bu süre zarfında karar alınamayacak ise sürenin dolmasından önce, süre aşımını gerekli kılan gerekçeler ve ek süre yükümlüye bildirilir || " + K + " | gerek duyulması halinde ilgili gümrük idaresinin mütalaası da alınmak suretiyle otuz gün içinde karara bağlanarak ilgili kişiye tebliğ edilir || " + K + " | Otuz gün içerisinde karar alınamadığı durumlarda Kanunun 6 ncı maddesinin ikinci fıkrası uygulanır || 6-KARAR.txt | Ancak, gümrük idareleri tarafından bu süreye uyulması mümkün değilse, belirtilen süre aşılabilir || 6-KARAR.txt | yukarıda belirlenen sürenin dolmasından önce başvuru sahibine süre aşımını haklı kılan gerekçeler ile talep hakkında karar vermek için gerekli gördükleri ek süreyi de belirterek bilgi verirler",
yuva=["GY 586 ve GK 242/2: itirazlar otuz gün içinde karara bağlanıp ilgili kişiye tebliğ edilir (doğru)",
      "GY 586 ile GK 6/2: otuz günlük süreye uyulamıyorsa süre aşılabilir (doğru)",
      "Tebliğ md. 12/4 ve GK 6/2: bildirimin içeriği gerekçeler ile ek süre (doğru)",
      "GY 586: gerek duyulursa ilgili gümrük idaresinin mütalaası alınır (doğru)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "BAŞLANGIÇ", "KOMŞU"],
duzey=["AYIRT"],
profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="2023/77",
kapsamli=False,
),

# 18 — GY 587/1-b: genel hâlde teminata bağlanacak tutar (ayna: S9 düşük kıymet)
dict(
konu="İtirazlar", blok="SB48",
kalip="KAPSAM",
z="Z",
madde="Gümrük Yönetmeliği md. 587",
cek="Genel hâlde eşyanın karardan önce çekilmesi için vergi farkı ile eşyanın alıcısı adına düzenlenen para cezaları teminata bağlanır.",
kok=["Gümrük Yönetmeliği'ne göre, düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hâller dışında, itiraz konusu eşyanın mercilerince karar verilmeden önce çekilebilmesi için teminata bağlanması gereken tutar aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Beyana göre tahakkuk eden vergiler ile idarece tahakkuk ettirilen bütün vergiler arasındaki fark ve eşyanın alıcısı adına düzenlenen para cezaları",
c=["Yalnızca beyana göre tahakkuk eden vergiler ile idarece tahakkuk ettirilen bütün vergiler arasındaki fark",
   "İdarece tahakkuk ettirilen vergilerin tamamı ile eşyanın alıcısı adına düzenlenen para cezaları",
   "Beyana göre tahakkuk eden vergiler ile idarece tahakkuk ettirilen bütün vergiler arasındaki fark ve beyan sahibi ile temsilcisi adına düzenlenen para cezaları",
   "Yalnızca eşyanın alıcısı adına düzenlenen para cezaları"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre ihtilaf konusu eşyanın karardan önce çekilebilmesi için, genel hâlde yükümlünün beyanına göre yapılan vergi tahakkukları ile gümrük idaresince tahakkuk ettirilen bütün vergiler arasındaki farkın ve eşyanın alıcısı adına düzenlenen para cezalarının teminata bağlanması gerekir. Teminat vergilerin tamamı üzerinden değil, iki tahakkuk arasındaki fark üzerinden hesaplanır; para cezalarından da yalnızca eşyanın alıcısı adına düzenlenenler teminata konu edilir. Yalnızca vergi farkının teminatı, 03.01.2023 tarihli değişiklikle düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hâller için öngörülmüştür; kök bu hâli dışarıda bırakmıştır. 'Beyan sahibi veya temsilcisi' ifadesi ise numuneden kaynaklanan itirazda tutanağın kimin huzurunda düzenleneceğini gösterir. En güçlü çeldirici, düşük kıymet hâline ait 'yalnızca vergi farkı' seçeneğidir. Bu nedenle doğru cevap 'Beyana göre tahakkuk eden vergiler ile idarece tahakkuk ettirilen bütün vergiler arasındaki fark ve eşyanın alıcısı adına düzenlenen para cezaları' seçeneğidir. (MD GY 587, 588)",
kanit=K + " | Yükümlünün beyanına göre yapılan vergi tahakkukları ile gümrük idaresince tahakkuk ettirilen bütün vergiler arasındaki farkın ve eşyanın alıcısı adına düzenlenen para cezalarının … teminata bağlanması || " + K + " | Düşük kıymet beyanı şüphesiyle kıymet araştırması yapılan hallerde yükümlünün beyanına göre yapılan vergi tahakkukları ile gümrük idaresince tahakkuk ettirilen bütün vergiler arasındaki farkın teminata bağlanması || " + K + " | beyan sahibi veya temsilcisi huzurunda ek-25'te yer alan tutanak",
yuva=["GY 587/1-d: yalnızca vergi farkı düşük kıymet şüphesiyle kıymet araştırması yapılan hâlde aranır",
      "GY 587/1-b: teminat iki tahakkuk arasındaki fark üzerinden alınır, vergilerin tamamı üzerinden değil (UNSUR)",
      "GY 588/1-ç: 'beyan sahibi veya temsilcisi' tutanak usulüne aittir; teminattaki cezalar eşyanın alıcısı adına düzenlenenlerdir",
      "GY 587/1-b: vergi farkı da teminata bağlanır (unsur eksik)"],
yakinlik="PARAFRAZ",
tuzak=["UNSUR", "KOMŞU", "TERİM"],
duzey=["AYIRT"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="Eşya çekiminde teminat: genel hâl ↔ düşük kıymet",
guncellik="",
cikmis="",
kapsamli=False,
),

# 19 — GY 585/1: itiraz dilekçesinin niteliği (boşluk doldurma)
dict(
konu="İtirazlar", blok="SB48",
kalip="BOŞLUK",
z="O",
madde="Gümrük Yönetmeliği md. 585",
cek="Yönetmelik, itiraz dilekçesinin gerekçeleri de açıkça göstermesini arar; Kanun yalnızca dilekçeden söz eder.",
kok=["Gümrük Yönetmeliği'nin itiraz başvurusuna ilişkin hükmünde yer alan \"Yükümlüler, kendilerine tebliğ edilen gümrük vergileri, cezalar ve idari kararlara karşı tebliğ tarihinden itibaren on beş gün içinde bir üst makama, üst makam yoksa aynı makama verecekleri, ……… bir dilekçeyle itiraz edebilirler.\" cümlesinde boş bırakılan yere gelmesi gereken ifade aşağıdakilerden hangisidir?"],
d="gerekçelerini de açıkça gösteren",
c=["itiraz edilen vergi farkının teminata bağlandığını gösteren",
   "beyanname numarası ve tescil tarihini de gösteren",
   "noter tarafından onaylanmış",
   "ilgili gümrük idaresinin mütalaasını da içeren"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre yükümlüler, kendilerine tebliğ edilen gümrük vergileri, cezalar ve idari kararlara karşı tebliğ tarihinden itibaren on beş gün içinde bir üst makama, üst makam yoksa aynı makama verecekleri, gerekçelerini de açıkça gösteren bir dilekçeyle itiraz edebilirler. Kanun yalnızca 'bir dilekçe ile' itirazdan söz ederken Yönetmelik dilekçede gerekçenin açıkça gösterilmesini de arar. Vergi farkının teminata bağlanması eşyanın karardan önce çekilmesinin, beyanname numarası ve tescil tarihi ise tahlil sonuçlarına itiraz dilekçesinin içeriğidir. İlgili gümrük idaresinin mütalaası, itirazın incelenmesi sırasında gerek duyulursa idarece alınır; yükümlünün dilekçesine eklenmez. Noter tasdiki gümrük müşavirlerinin temsil yetkisine dayanak vekâletnamede aranır. En güçlü çeldirici, tahlil itirazına ait dilekçe içeriğidir. Bu nedenle doğru cevap 'gerekçelerini de açıkça gösteren' seçeneğidir. (MD GY 585, 586, 588)",
kanit=K + " | üst makam yoksa aynı makama verecekleri, gerekçelerini de açıkça gösteren bir dilekçeyle itiraz edebilirler || " + K + " | Dilekçede, beyanname numarası ve tescil tarihi ile eşyanın cins ve türü || " + K + " | gerek duyulması halinde ilgili gümrük idaresinin mütalaası da alınmak suretiyle || 2-TEMSİL.txt | eşya sahibince verilmiş noter tasdikli vekaletnameyi haiz gümrük müşavirleri",
yuva=["GY 587/1-b: vergi farkının teminatı eşyanın karardan önce çekilmesinin şartıdır",
      "GY 588/1-b: beyanname numarası ve tescil tarihi tahlile itiraz dilekçesinin içeriğidir",
      "GY 561 (2-TEMSİL.txt): noter tasdikli vekâletname gümrük müşavirinin dolaylı temsil yetkisine aittir",
      "GY 586: ilgili gümrük idaresinin mütalaası, gerek duyulursa itirazın incelenmesinde idarece alınır"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM"],
duzey=["TANIMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="",
guncellik="",
cikmis="",
kapsamli=False,
),

# 20 — GY 585/4-a: taahhütlü postada süre tespiti (ayna: S7)
dict(
konu="İtirazlar", blok="SB48",
kalip="SONUÇ",
z="K",
madde="Gümrük Yönetmeliği md. 585",
cek="Taahhütlü posta ile yapılan itirazda sürenin tespitinde dilekçenin postaya verildiği tarih dikkate alınır.",
kok=["Gümrük Yönetmeliği'ne göre taahhütlü olarak posta yoluyla yapılan itirazların süresi içinde olup olmadığının tespitinde aşağıdaki tarihlerden hangisi dikkate alınır?"],
d="İtiraz dilekçesinin postaya verildiği tarih",
c=["İtiraz dilekçesinin, itirazın yapıldığı gümrük idaresinin kaydına giriş tarihi",
   "İtiraz dilekçesinin idarece yetkili makama ulaştırıldığı tarih",
   "İtiraza konu kararın yükümlüye tebliğ edildiği tarih",
   "İtirazın idarece karara bağlandığı tarih"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre itirazların süresi içinde olup olmadığının tespitinde taahhütlü olarak posta yolu ile yapılan itirazlarda itiraz dilekçesinin postaya verildiği tarih dikkate alınır. Taahhütsüz posta yolu ile veya doğrudan ilgili gümrük idaresine yapılan itirazlarda ise dilekçenin itirazın yapıldığı gümrük idaresinin kaydına giriş tarihi esas alınır; bu nedenle taahhütlü gönderim yükümlüyü postadaki gecikmenin sonucundan korur. Kararın tebliğ tarihi itiraz süresinin başladığı andır; tespit edilen ise itirazın hangi gün yapılmış sayılacağıdır. Dilekçenin yetkili makama ulaştırılması süresi içinde yanlış makama verilen dilekçeye, karara bağlama ise idarenin otuz günlük karar süresine ilişkindir. En güçlü çeldirici, aynı hükmün öbür bendinde yer alan kayda giriş tarihidir. Bu nedenle doğru cevap 'İtiraz dilekçesinin postaya verildiği tarih' seçeneğidir. (MD GY 585; GK 242)",
kanit=K + " | Taahhütlü olarak posta yolu ile yapılacak itirazlarda, itiraz dilekçesinin postaya verildiği tarih || " + K + " | Posta yolu ile veya doğrudan ilgili gümrük idaresine yapılacak itirazlarda, itiraz dilekçesinin itirazın yapıldığı gümrük idaresinin kaydına giriş tarihi || " + K + " | idarece yetkili makama ulaştırılır",
yuva=["GY 585/4-b: taahhütsüz posta yoluyla veya doğrudan yapılan itirazda kayda giriş tarihi",
      "GK 242/3: süresi içinde yanlış makama verilen dilekçe idarece yetkili makama ulaştırılır",
      "GK 242/1: tebliğ tarihi itiraz süresinin başlangıcıdır, tespit anı değildir",
      "GK 242/2: itirazların otuz gün içinde karara bağlanması"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU"],
duzey=["HATIRLAMA"],
profil=[1],
olumsuz=False, vaka=False, baslangic=False,
eksen=0, ayna="Taahhütlü ↔ taahhütsüz posta (süre tespiti)",
guncellik="",
cikmis="",
kapsamli=False,
),

]
