# Soru Bankası — Bölüm 46: Geri Verme ve Kaldırma (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
Q = [

# ---------------- 1 TANIMDAN AD ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="KAVRAM", z="K",
madde="4458 sayılı Gümrük Kanunu md. 210, 211",
cek="Henüz ödenmemiş gümrük vergilerinin tamamen veya kısmen alınmamasına karar verilmesi 'kaldırma'; ödenmiş vergilerin geri ödenmesi 'geri verme'dir.",
kok=["4458 sayılı Gümrük Kanunu'nda kullanılan deyimlerden hangisi, henüz ödenmemiş olan gümrük vergilerinin tamamen veya kısmen alınmamasına karar verilmesi anlamına gelir?"],
d="Kaldırma",
c=["Geri verme", "Geri ödeme", "Mahsup", "Tecil"],
sirali=False,
g="Gümrük Kanunu iki deyimi verginin ödenmiş olup olmamasına göre ayırır: ödenmiş olan gümrük vergilerinin tamamen veya kısmen geri ödenmesi 'geri verme', henüz ödenmemiş olan gümrük vergilerinin tamamen veya kısmen alınmamasına karar verilmesi ise 'kaldırma' deyimiyle ifade edilir. Bu ayrım Kanunun diğer hükmünde de korunur: kanunen ödenmemeleri gerektiği hâlde ödenmiş vergiler geri verilir, kanunen tahakkuk ettirilmemeleri gerektiği hâlde tahakkuk ettirilen vergiler kaldırılır. En güçlü çeldirici 'Geri verme'dir; bu deyim verginin ödenmiş olduğu durumu karşılar. Geri ödeme, dahilde işleme rejiminde serbest dolaşıma girişte tahsil edilen vergilerin geri verildiği sistemin adıdır; mahsup geri verilecek tutarın muaccel borçlara sayılmasını, tecil ise ödemenin ertelenmesini ifade eder. Bu nedenle doğru cevap 'Kaldırma' seçeneğidir. (MD 210, 211)",
kanit="47-geri verme kaldırma.txt | \"Kaldırma\" deyimi, henüz ödenmemiş olan gümrük vergilerinin tamamen veya kısmen alınmamasına karar verilmesi || 47-geri verme kaldırma.txt | \"Geri verme\" deyimi, ödenmiş olan gümrük vergilerinin tamamen veya kısmen geri ödenmesi || 47-geri verme kaldırma.txt | Kanunen tahakkuk ettirilmemeleri gerektiği halde tahakkuk ettirilen gümrük vergileri kaldırılır",
yuva=["GK 210/a: ödenmiş olan gümrük vergilerinin tamamen veya kısmen geri ödenmesi (geri verme deyimi)",
      "GK 108 (32-DAHİLDE İŞLEME): serbest dolaşıma girişte tahsil edilen vergilerin DİR kapsamında geri verilmesine geri ödeme sistemi denir",
      "Tahsilat Tebliği md. 39: geri verilecek amme alacağının muaccel borçlara mahsup edilmesi",
      "GK 198 (45-tebliğ): ödeme süresinin uzatılmasında tecil faizi alınması"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"], duzey=["TANIMA"], profil=[3],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# ---------------- 2 ÖNERMELİ: PARA CEZALARI ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="ÖNERMELİ", z="Z",
madde="4458 sayılı Gümrük Kanunu md. 210; Gümrük Yönetmeliği md. 511",
cek="Geri verme hükümleri GK kapsamındaki para cezalarına da uygulanır; usulsüzlük cezasında tevsik edici belge gerekir; muhbir payı kararın verilmesinden itibaren bir ayda geri istenir.",
kok=["4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'nin para cezalarının geri verilmesi ve kaldırılmasına ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Gümrük vergilerinin geri verilmesi veya kaldırılmasına ilişkin hükümler, Gümrük Kanunu kapsamında tatbik edilen para cezaları için de uygulanır.",
     "II. Gümrük Kanunu uyarınca muhbirlere dağıtılan para cezalarından geri verilmesine karar verilenler, kararın verildiği tarihten itibaren üç ay içerisinde geri istenir.",
     "III. Usulsüzlüklere ilişkin para cezalarının geri verilmesi ve kaldırılmasında, bu cezalara ilişkin kararların kanunen düzenlenmemesi gerektiği hâlde düzenlendiğini veya bu cezaların kanunen ödenmemesi gerektiği hâlde ödendiğini tevsik eden belgelerin ibrazı gerekir.",
     "IV. Vergi kaybına neden olabilecek işlemlere uygulanacak para cezalarının geri verilmesi ve kaldırılmasında, gümrük vergilerinin geri verilmesine ve kaldırılmasına ilişkin hükümler uygulanır.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, III ve IV",
c=["I ve III", "II ve IV", "I, II ve III", "I, II, III ve IV"],
sirali=False,
g="Gümrük Kanunu'na göre gümrük vergilerinin geri verilmesi veya kaldırılmasına ilişkin hükümler, bu Kanun kapsamında tatbik edilen para cezaları için de uygulanır (I doğru); hüküm Gümrük Kanunu dışındaki kanunlara göre verilen para cezalarını kapsamaz. Gümrük Yönetmeliği bu genel kuralı ceza türüne göre ayrıntılandırır: vergi kaybına neden olabilecek işlemlere uygulanacak para cezalarında gümrük vergilerinin geri verilmesine ve kaldırılmasına ilişkin hükümler uygulanır (IV doğru); usulsüzlüklere ilişkin para cezalarında ise ceza kararının kanunen düzenlenmemesi gerektiği hâlde düzenlendiğini veya cezanın kanunen ödenmemesi gerektiği hâlde ödendiğini tevsik eden belgelerin ibrazı gerekir (III doğru). Muhbirlere dağıtılan para cezalarından geri verilmesine karar verilenler ise kararın verildiği tarihten itibaren üç ay değil, bir ay içerisinde geri istenir; II yanlıştır. En güçlü çeldirici 'I, II, III ve IV'tür: muhbir payının geri istenme süresini yaklaşık bilen aday bütün önermeleri doğru sayar. Bu nedenle doğru cevap 'I, III ve IV' seçeneğidir. (MD GK 210; GY 511)",
kanit="47-geri verme kaldırma.txt | Gümrük vergilerinin geri verilmesi veya kaldırılmasına ilişkin hükümler bu Kanun kapsamında tatbik edilen para cezaları için de uygulanır || 47-geri verme kaldırma.txt | Vergi kaybına neden olabilecek işlemlere uygulanacak para cezalarının geri verilmesi ve kaldırılmasında, gümrük vergilerinin geri verilmesine ve kaldırılmasına ilişkin hükümler uygulanır || 47-geri verme kaldırma.txt | Usulsüzlüklere ilişkin para cezalarının geri verilmesi ve kaldırılmasında, bu cezalara ilişkin kararların kanunen düzenlenmemesi gerektiği halde düzenlendiğini veya bu cezaların kanunen ödenmemesi gerektiği halde ödendiğini tevsik eden belgelerin ibrazı gerekir || 47-geri verme kaldırma.txt | muhbirlere dağıtılan para cezalarından geri verilmesine karar verilenler kararın verildiği tarihten itibaren bir ay içerisinde geri istenir",
yuva=["I ve III: IV'teki vergi kaybı cezalarında vergi hükümlerinin uygulanacağını bilmeyip usulsüzlükteki belge şartını genel kural sanan aday (GY 511/1)",
      "II ve IV: GK 210'daki genel kuralı ve usulsüzlükteki belge şartını atlayıp muhbir süresini doğru sanan aday",
      "I, II ve III: muhbir süresini yanlış bilen ve vergi kaybı cezalarındaki atfı (GY 511/1) görmeyen aday",
      "I, II, III ve IV: GY 511/3'teki bir aylık süreyi üç ay sanan aday"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"], duzey=["AYIRT"], profil=[1, 2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2021/80; 2023/69", kapsamli=False,
),

# ---------------- 3 SÜRE: GENEL SÜRENİN BAŞLANGICI (EKSEN 8 / AYNA-a) ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="SÜRE", z="O",
madde="Gümrük Yönetmeliği md. 502; 4458 sayılı Gümrük Kanunu md. 211",
cek="Kanunen ödenmemesi gereken vergilerde üç yıllık geri verme veya kaldırma başvuru süresi, vergilerin yükümlüye tebliğ edildiği tarihte başlar.",
kok=["Gümrük Yönetmeliği'ne göre, kanunen ödenmemeleri veya tahakkuk ettirilmemeleri gerektiği hâlde ödenen ya da tahakkuk ettirilen gümrük vergilerinin geri verilmesi veya kaldırılması için öngörülen üç yıllık başvuru süresi hangi tarihte başlar?"],
d="Gümrük vergilerinin yükümlüye tebliğ edildiği tarihte",
c=["Gümrük beyannamesinin tescil edildiği tarihte",
   "Gümrük vergilerinin ödendiği tarihte",
   "Eşyanın yükümlüye teslim edildiği tarihte",
   "Gümrük vergilerinin kesinleştiği tarihte"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre kanunen ödenmemesi veya tahakkuk ettirilmemesi gereken vergilerin geri verilmesi veya kaldırılması işlemlerinde başvuru süresi üç yıldır ve bu süre, gümrük vergilerinin yükümlüye tebliğ edildiği tarihte başlar. Kanun da geri verme veya kaldırmayı vergilerin yükümlüye tebliğ edilmesine ve ilgilinin üç yıl içinde gümrük idaresine müracaatına bağlar. En güçlü çeldirici ödeme tarihidir: geri verme ödenmiş vergiye ilişkin olduğundan aday süreyi ödemeden başlatabilir; oysa kaldırmada ortada bir ödeme yoktur ve süre her iki işlemde tebliğle başlar. Tescil tarihi, kusurlu veya sözleşmeye aykırı eşyada eşyanın durumunun değerlendirildiği andır; teslim beyanname iptalinde talep süresini belirleyen ölçüttür; kesinleşme ise itiraz veya dava süresinin bitmesine bağlı ayrı bir kavramdır. Bu nedenle doğru cevap 'Gümrük vergilerinin yükümlüye tebliğ edildiği tarihte' seçeneğidir. (MD GY 502; GK 211)",
kanit="47-geri verme kaldırma.txt | Gümrük Kanununun 211 inci maddesi uyarınca yapılacak geri verme veya kaldırma işlemlerinde, başvuru süresi üç yıldır. Söz konusu süre, gümrük vergilerinin yükümlüye tebliğ edildiği tarihte başlar. || 47-geri verme kaldırma.txt | söz konusu vergilerin yükümlüye tebliğ edilmesi ve ilgilinin üç yıl içinde gümrük idaresine müracaatı üzerine geri verilir veya kaldırılır",
yuva=["GK 213/1: kusurlu eşyada 'beyannamenin tescili tarihi itibariyle' değerlendirme",
      "GK 210/a ve 216/2: geri vermenin ödenmiş vergiye ilişkin olması; faizin 'ödemenin yapıldığı tarih'e kadar hesaplanması",
      "GY 499/1: beyanname iptalinin 'eşyanın tesliminden önce' yapılmasına göre talep süresinin belirlenmesi",
      "GK 197/5 (45-tebliğ): itiraz veya dava süresinin bitiminde vergilerin kesinleşmesi"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU"], duzey=["AYIRT"], profil=[1],
olumsuz=False, vaka=False, baslangic=True, eksen=8, ayna="AYNA-8: genel süre (tebliğden üç yıl) ↔ uluslararası anlaşma süresi (tebliğden bir yıl)", guncellik="", cikmis="2022/89; 2021/80", kapsamli=False,
),

# ---------------- 4 SÜRE + MAKAM: ULUSLARARASI ANLAŞMA (EKSEN 8 / AYNA-b) ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="SÜRE", z="O",
madde="4458 sayılı Gümrük Kanunu md. 214",
cek="Uluslararası anlaşma kapsamındaki geri verme başvurusu vergilerin tebliğinden itibaren bir yıl içinde yapılır; mücbir sebepte sürenin aşılmasına Müsteşarlık izin verir.",
kok=["4458 sayılı Gümrük Kanunu'na göre gümrük vergilerinin, Türkiye'nin taraf olduğu uluslararası anlaşma hükümleri çerçevesinde belirlenecek hâllerde geri verilmesi veya kaldırılması için ilgili gümrük idaresine başvuru süresi ile mücbir sebebin tespiti hâlinde bu sürenin aşılmasına izin vermeye yetkili makam aşağıdakilerden hangisinde birlikte doğru olarak verilmiştir?"],
d="Vergilerin yükümlüye tebliği tarihinden itibaren bir yıl – Müsteşarlık",
c=["Vergilerin yükümlüye tebliği tarihinden itibaren üç yıl – Müsteşarlık",
   "Vergilerin yükümlüye tebliği tarihinden itibaren bir yıl – Cumhurbaşkanı",
   "Gümrük beyannamesinin tescili tarihinden itibaren bir yıl – Müsteşarlık",
   "Vergilerin yükümlüye tebliği tarihinden itibaren bir yıl – İlgili gümrük idaresi"],
sirali=False,
g="Gümrük Kanunu'na göre gümrük vergileri, Kanunda sayılan diğer hâller dışında, Türkiye'nin taraf olduğu uluslararası anlaşma hükümleri çerçevesinde Cumhurbaşkanı tarafından belirlenecek hâllerde geri verilir veya kaldırılır. Bu işlemler, gümrük vergilerinin yükümlüye tebliği tarihinden itibaren bir yıl içinde ilgili gümrük idaresine başvurulması üzerine yapılır; mücbir sebebin tespiti hâlinde bu sürenin aşılmasına Müsteşarlıkça izin verilir. En güçlü çeldirici üç yıllık süredir; bu süre kanunen ödenmemesi gereken vergiler için öngörülen genel süredir. Cumhurbaşkanı aynı hükümde geri verme hâllerini belirleyen makamdır, sürenin aşılmasına izin veren makam değildir; ilgili gümrük idaresi ise başvurunun yapıldığı yerdir. Süre beyannamenin tescilinden değil tebliğden başlar. Bu nedenle doğru cevap 'Vergilerin yükümlüye tebliği tarihinden itibaren bir yıl – Müsteşarlık' seçeneğidir. (MD 214)",
kanit="47-geri verme kaldırma.txt | Bu maddede belirlenen geri verme ve kaldırma işlemleri, gümrük vergilerinin yükümlüye tebliği tarihinden itibaren bir yıl içinde ilgili gümrük idaresine başvurulması üzerine yapılır. || 47-geri verme kaldırma.txt | Ancak, mücbir sebebin tespiti halinde, bu sürenin aşılmasına Müsteşarlıkça izin verilir. || 47-geri verme kaldırma.txt | tarafından belirlenecek hallerde geri verilir veya kaldırılır",
yuva=["GK 211/2 ve GY 502/5: kanunen ödenmemesi gereken vergilerde tebliğden itibaren üç yıllık genel süre",
      "GK 214 birinci paragraf: geri verme hâllerini Cumhurbaşkanı belirler (izin makamı değil)",
      "GK 213/1: 'beyannamenin tescili tarihi itibariyle' ifadesinden süreyi tescilden başlatan hata",
      "GK 214 ikinci paragraf: başvurunun yapıldığı yer olan ilgili gümrük idaresi"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "MAKAM", "BAŞLANGIÇ"], duzey=["AYIRT"], profil=[2],
olumsuz=False, vaka=False, baslangic=True, eksen=8, ayna="AYNA-8: genel süre (tebliğden üç yıl) ↔ uluslararası anlaşma süresi (tebliğden bir yıl)", guncellik="", cikmis="2022/91; 2024/83", kapsamli=False,
),

# ---------------- 5 ÖNERMELİ (YANLIŞTIR): KUSURLU EŞYA ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="ÖNERMELİ", z="Z",
madde="4458 sayılı Gümrük Kanunu md. 213",
cek="Kusurlu eşyaya teslimden önce hasar gören eşya dahildir; kullanılmama ve ihraç birlikte aranır; başvuru tebliğden bir yıldır; denenen eşyada kanıt gerekir.",
kok=["4458 sayılı Gümrük Kanunu'nun, kusurlu veya ithaline esas sözleşme hükümlerine aykırı olduğu için ithalatçı tarafından kabul edilmeyen eşyaya ilişkin ithalat vergilerinin geri verilmesi veya kaldırılmasına dair hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Kusurlu eşyaya, teslimden önce hasar gören eşya da dahildir.",
     "II. Vergilerin geri verilmesi veya kaldırılması; eşyanın, kusurlu veya sözleşme hükümlerine aykırı olduğunun tespiti için gerekli olan ilk kullanım dışında kullanılmamış olması ya da Türkiye Gümrük Bölgesi dışına ihraç edilmesi koşullarından birinin gerçekleşmesine bağlıdır.",
     "III. Geri verme veya kaldırma için vergilerin yükümlüye tebliği tarihinden itibaren üç yıl içerisinde gümrük idaresine müracaat edilmesi gerekir.",
     "IV. Gümrük beyanından önce denenmek üzere geçici olarak teslim edilen eşyanın vergileri, eşyanın kusurlu veya sözleşme hükümlerine aykırı olduğu hususlarının deneme sırasında anlaşılamadığı kanıtlanmadıkça geri verilmez veya kaldırılmaz.",
     "Yukarıdaki ifadelerden hangileri yanlıştır?"],
d="II ve III",
c=["Yalnız III", "I ve IV", "III ve IV", "II, III ve IV"],
sirali=False,
g="Gümrük Kanunu'na göre beyannamenin tescili tarihi itibarıyla kusurlu veya ithaline esas sözleşme hükümlerine aykırı olduğu için ithalatçı tarafından kabul edilmeyen eşyanın ithalat vergileri geri verilir veya kaldırılır ve kusurlu eşyaya teslimden önce hasar gören eşya da dahildir (I doğru). Geri verme veya kaldırma, eşyanın aykırılığın tespiti için gerekli ilk kullanım dışında kullanılmamış olması ve Türkiye Gümrük Bölgesi dışına ihraç edilmesi koşullarına birlikte bağlıdır; bu iki koşuldan yalnız birinin gerçekleşmesi yetmez (II yanlış). Bu hâlde müracaat süresi üç yıl değil, vergilerin yükümlüye tebliği tarihinden itibaren bir yıldır; üç yıl kanunen ödenmemesi gereken vergiler için öngörülen genel süredir (III yanlış). Gümrük beyanından önce denenmek üzere geçici olarak teslim edilen eşyanın vergileri ise kusurun deneme sırasında anlaşılamadığı kanıtlanmadıkça geri verilmez veya kaldırılmaz (IV doğru). En güçlü çeldirici 'Yalnız III'tür: süreyi bilip 've' bağlacının 'ya da'ya çevrildiğini fark etmeyen aday bu şıkka gider. Bu nedenle doğru cevap 'II ve III' seçeneğidir. (MD 213)",
kanit="47-geri verme kaldırma.txt | Kusurlu eşyaya, teslimden önce hasar gören eşya da dahildir. || 47-geri verme kaldırma.txt | ilk kullanım dışında eşyanın kullanılmamış olması ve eşyanın Türkiye Gümrük Bölgesi dışına ihraç edilmesi koşullarına bağlıdır || 47-geri verme kaldırma.txt | vergilerin yükümlüye tebliği tarihinden itibaren bir yıl içerisinde gümrük idaresine müracaat edilmesi gerekir || 47-geri verme kaldırma.txt | deneme sırasında anlaşılamadığı kanıtlanmadıkça geri verilmez veya kaldırılmaz",
yuva=["Yalnız III: GK 213/2'deki iki koşulun birlikte arandığını ('ve') gözden kaçıran aday",
      "I ve IV: GK 213/1 son cümlesi ve 213/3'ü (gerçekte doğru) yanlış sanan, II ve III'ü doğru kabul eden aday",
      "III ve IV: GK 213/3'teki deneme amaçlı teslim hükmünü yanlış sanıp II'deki bağlaç değişikliğini görmeyen aday",
      "II, III ve IV: GK 213/3'ün 'kanıtlanmadıkça geri verilmez' kaydını tersine okuyan aday"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "ŞART", "KOMŞU"], duzey=["AYIRT"], profil=[2, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=8, ayna="", guncellik="", cikmis="2025/26", kapsamli=False,
),

# ---------------- 6 LİSTE DIŞI: İHRAÇ YERİNE İZİN VERİLEN İŞLEMLER ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="KAPSAM_DIŞI", z="O",
madde="4458 sayılı Gümrük Kanunu md. 213",
cek="Kusurlu eşyada ihracat yerine talep üzerine imha, yeniden ihraç amaçlı transit veya antrepo ve serbest bölgeye konulma izni verilir; gümrüğe terk sayılmamıştır.",
kok=["4458 sayılı Gümrük Kanunu'na göre kusurlu veya sözleşme hükümlerine aykırı olduğu için ithalatçı tarafından kabul edilmeyen eşyanın vergilerinin geri verilmesinde, gümrük idarelerinin ilgilinin talebi üzerine eşyanın ihracı yerine izin verebileceği işlem veya kullanımlar arasında aşağıdakilerden hangisi yer almaz?"],
d="Eşyanın gümrüğe terk edilmesi",
c=["Eşyanın imha edilmesi",
   "Eşyanın yeniden ihraç amacıyla transit rejimine tabi tutulması",
   "Eşyanın yeniden ihraç amacıyla gümrük antrepo rejimine tabi tutulması",
   "Eşyanın serbest bölgeye konulması"],
sirali=False,
g="Gümrük Kanunu'na göre kusurlu veya sözleşmeye aykırı eşyanın vergilerinin geri verilmesi, kural olarak eşyanın Türkiye Gümrük Bölgesi dışına ihraç edilmesine bağlıdır. Gümrük idareleri ilgilinin talebi üzerine ihracat yerine dört işlem veya kullanıma izin verir: eşyanın imhası, yeniden ihraç amacıyla transit rejimine veya gümrük antrepo rejimine tabi tutulması ve serbest bölgeye konulması. Bu işlem veya kullanımlardan birine tabi tutulan eşya serbest dolaşımda olmayan eşya olarak değerlendirilir. Gümrüğe terk, Kanunun gümrükçe onaylanmış işlem veya kullanımlar arasında saydığı bir seçenektir; ancak kusurlu eşyada ihracat yerine izin verilen işlemler arasında sayılmamıştır. En güçlü tuzak, imha ile terkin aynı listede yer aldığı genel gümrükçe onaylanmış işlem listesinin bu hükme taşınmasıdır. Bu nedenle doğru cevap 'Eşyanın gümrüğe terk edilmesi' seçeneğidir. (MD 213)",
kanit="47-geri verme kaldırma.txt | Gümrük idareleri, ilgilinin talebi üzerine, eşyanın ihracı yerine; imhasına, yeniden ihraç amacıyla transit veya gümrük antrepo rejimine tabi tutulmasına veya serbest bölgeye konulmasına izin verirler. || 47-geri verme kaldırma.txt | Söz konusu işlem veya kullanımlardan birine tabi tutulan eşya, serbest dolaşımda olmayan eşya olarak değerlendirilir. || 1-TANIMLAR.txt | Gümrüğe terk edilmesini",
yuva=["GK 213/2 ikinci paragraf: ihracat yerine imha (listede)",
      "GK 213/2 ikinci paragraf: yeniden ihraç amacıyla transit rejimi (listede)",
      "GK 213/2 ikinci paragraf: yeniden ihraç amacıyla gümrük antrepo rejimi (listede)",
      "GK 213/2 ikinci paragraf: serbest bölgeye konulma (listede)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU", "KOMŞU"], duzey=["TANIMA"], profil=[3, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2025/26", kapsamli=False,
),

# ---------------- 7 VAKA: TİCARET POLİTİKASI ÖNLEMİ, KIYMETİN BEYANLA ARTIRILMASI ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="OLAY", z="O",
madde="4458 sayılı Gümrük Kanunu md. 211",
cek="Ticaret politikası önlemine tabi eşyanın kıymeti yükümlünün kendi beyanıyla artırılarak ödenen vergilerin geri verilmesi talebi, süresinde yapılsa da kabul edilmez.",
kok=["İthalatçı (B) Ltd. Şti., ticaret politikası önlemlerine tabi bir eşyayı serbest dolaşıma sokarken eşyanın gümrük kıymetini kendi beyanı ile artırmış ve bu kıymet üzerinden tahakkuk eden gümrük vergilerini ödemiştir. İşlemlerde ilgili kişinin kasten yaptığı herhangi bir tahrifat bulunmamaktadır. (B) Ltd. Şti., vergilerin kendisine tebliğinden sekiz ay sonra, artırılan kıymete isabet eden vergilerin kanunen ödenmemesi gerektiğini ileri sürerek geri verilmesi için gümrük idaresine başvurmuştur.",
     "4458 sayılı Gümrük Kanunu'na göre bu başvuru hakkında aşağıdakilerden hangisi doğrudur?"],
d="Vergiler, ticaret politikası önlemlerine tabi eşyanın gümrük kıymetinin yükümlünün kendi beyanı ile artırılması sonucunda ödendiğinden talep kabul edilmez.",
c=["Başvuru vergilerin tebliğinden itibaren üç yıllık süre içinde yapıldığından talep kabul edilir ve artırılan kıymete isabet eden vergiler geri verilir.",
   "Kasıtlı bir tahrifat bulunmadığından talep kabul edilir; ancak bu tür taleplerde başvurunun tebliğden itibaren bir yıl içinde yapılması gerekir.",
   "Talep, ancak kontrol ve denetleme sonucunda geri verme hâlinin tespit edilmesi durumunda değerlendirilir; yükümlünün başvurusu üzerine geri verme yapılmaz.",
   "Talep, ancak başvurunun gecikmesine mücbir sebep veya beklenmeyen hâllerin yol açtığı kanıtlanırsa kabul edilir."],
sirali=False,
g="Gümrük Kanunu'na göre kanunen ödenmemeleri gerektiği hâlde ödenmiş olduğu belirlenen gümrük vergileri, vergilerin tebliğinden itibaren üç yıl içinde yapılan müracaat üzerine geri verilir. Ancak kanunen ödenmemesi gereken vergiler ilgili kişinin kasten yaptığı bir tahrifat veya ticaret politikası önlemlerine tabi eşyanın gümrük kıymetinin yükümlünün kendi beyanı ile artırılması sonucunda ödenmişse, bu vergilerin geri verilmesine ilişkin talepler kabul edilmez. Olayda tahrifat bulunmaması sonucu değiştirmez; iki engel birbirinden bağımsızdır ve kıymetin kendi beyanıyla artırılması tek başına talebin reddini gerektirir. En güçlü çeldirici üç yıllık süreye dayanan seçenektir: başvuru süresi içinde yapılmış olsa da istisna nedeniyle talep kabul edilmez. Bir yıllık süre kusurlu eşya ile uluslararası anlaşma hâllerine aittir; kontrol ve denetleme sonucunda doğrudan geri verme yapılması ise başvuru yolunu kapatmaz; mücbir sebep yalnızca sürenin uzatılmasıyla ilgilidir. Bu nedenle doğru cevap 'Vergiler, ticaret politikası önlemlerine tabi eşyanın gümrük kıymetinin yükümlünün kendi beyanı ile artırılması sonucunda ödendiğinden talep kabul edilmez.' seçeneğidir. (MD 211)",
kanit="47-geri verme kaldırma.txt | ilgili kişinin kasten yaptığı bir tahrifat veya ticaret politikası önlemlerine tabi eşyanın gümrük kıymetinin yükümlünün kendi beyanı ile artırılması … sonucunda ödenmiş veya tahakkuk ettirilmişse, bu vergilerin geri verilmesine veya kaldırılmasına ilişkin talepler kabul edilmez",
yuva=["GK 211/2: kanunen ödenmemesi gereken vergilerde tebliğden itibaren üç yıl içinde müracaat üzerine geri verme (genel kural)",
      "GK 213/4 ve 214: kusurlu eşya ile uluslararası anlaşma hâllerinde tebliğden itibaren bir yıllık başvuru süresi",
      "GK 211/2 ikinci paragraf: kontrol ve denetleme sonucunda geri verme işleminin doğrudan yapılması",
      "GK 211/2 son cümle: sürenin mücbir sebep veya beklenmeyen hâllerde uzatılabilmesi"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "KOMŞU"], duzey=["UYGULAMA"], profil=[3],
olumsuz=False, vaka=True, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2023/76; 2021/80", kapsamli=False,
),

# ---------------- 8 KAPSAM DIŞI: TALEBİN KABUL EDİLMEDİĞİ DURUMLAR (TEBLİĞ) ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="KAPSAM_DIŞI", z="Z",
madde="Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2) md. 31, 38, 41",
cek="Beyannamede ağırlık, adet, kıymet gibi unsurların belgelere aykırı yanlış yazılmasıyla fazla ödenen vergilere ilişkin talepler, beyanın bağlayıcılığına rağmen kabul edilerek değerlendirilir.",
kok=["Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2)'ye göre aşağıdaki durumlardan hangisi, geri verme veya kaldırma talebinin kabul edilmemesine yol açmaz?"],
d="Beyanname ekindeki belgelere aykırı olarak beyannamede eşyanın ağırlığının yanlış yazılması nedeniyle vergilerin fazla ödenmiş olması",
c=["Menşe ve dolaşım belgelerinin mahreç ülke nezdinde sonradan kontrole tabi tutulmasına karşın ilgili mevzuatında öngörülen süreler içinde sonuç alınamaması",
   "Menşe ve dolaşım belgeleri dışında kalan ve vergilendirmeyi doğrudan etkileyen bir belgenin sonradan ibraz edilmesi",
   "Kıymet kriterli gözetim uygulamasında yükümlünün kendi isteğiyle gözetim tebliğinde belirlenen eşik kıymet üzerinden beyanda bulunması",
   "Tarımsal mali yükler dışındaki ithalat vergisi oranının tescilden sonra ancak vergilerin ödenmesinden önce indirilmesine rağmen indirimli oranın uygulanmasının beyan sahibince talep edilmemesi"],
sirali=False,
g="Tahsilat Tebliği'ne göre beyanın bağlayıcılığı, yükümlünün beyannamede yer alan eşyadan kaynaklanan vergi ve cezalardan idareye karşı sorumlu olduğunu ifade eder; ancak idarenin vergileri geri verme sorumluluğunu ortadan kaldırmaz. Bu nedenle beyanname ekindeki belgelere aykırı olarak ağırlık, adet, ölçü, kıymet veya döviz cinsinin yanlış yazılması gibi nedenlerle fazla ödenen vergilere ilişkin talepler kabul edilerek değerlendirilir. Buna karşılık Tebliğ, menşe ve dolaşım belgelerinin sonradan kontrolünde öngörülen sürelerde sonuç alınamaması, menşe ve dolaşım belgeleri dışındaki vergilendirmeyi doğrudan etkileyen belgelerin sonradan ibrazı ve kıymet kriterli gözetimde yükümlünün kendi isteğiyle eşik kıymet üzerinden beyanı hâllerinde talebin reddedileceğini belirtir. Tarımsal mali yükler dışındaki vergi oranının tescilden sonra, ödemeden önce indirilmesine rağmen indirimli oran talep edilmemişse, indirim talebe bağlı olduğundan kanunen ödenmemesi gereken vergilerin geri verilmesine ilişkin hüküm uygulanamaz. En güçlü tuzak, 'beyan bağlayıcıdır' sağduyusuyla ağırlığın yanlış yazılmasının da reddi gerektirdiğini düşünmektir. Bu nedenle doğru cevap 'Beyanname ekindeki belgelere aykırı olarak beyannamede eşyanın ağırlığının yanlış yazılması nedeniyle vergilerin fazla ödenmiş olması' seçeneğidir. (MD Tebliğ 31, 38, 41)",
kanit="47-geri verme kaldırma.txt | beyanname ekinde yer alan belgelere aykırı olarak, beyanname üzerinde ağırlık, adet, ölçü, kıymet veya döviz cinsinin yanlış yazılması gibi nedenlerden ötürü fazla ödenen || 47-geri verme kaldırma.txt | kapsamında geri verilmesi veya kaldırılması yönündeki talepler kabul edilerek değerlendirilir || 47-geri verme kaldırma.txt | Menşe ve dolaşım belgelerinin mahreç ülkeler nezdinde sonradan kontrole tabi tutulmasına karşın ilgili mevzuatında öngörülen süreler içinde sonuç alınamaması || 47-geri verme kaldırma.txt | Menşe ve dolaşım belgelerinin sonradan ibrazının öngörüldüğü haller hariç, vergilendirmeyi doğrudan etkileyen diğer belgelerin sonradan ibrazı || 47-geri verme kaldırma.txt | Kıymet kriterli gözetim uygulamalarında, yükümlünün kendi isteğiyle ilgili gözetim tebliğinde belirlenen eşik kıymet üzerinden beyan yapılması || 47-geri verme kaldırma.txt | indirimin talebe bağlı olması ve zorunlu olmaması nedeniyle Gümrük Kanununun 211 inci maddesinin uygulanması mümkün değildir",
yuva=["Tebliğ md. 38/1-a: sonradan kontrolde öngörülen sürede sonuç alınamaması (talep reddedilir)",
      "Tebliğ md. 38/1-b: menşe ve dolaşım belgeleri dışındaki vergilendirmeyi doğrudan etkileyen belgenin sonradan ibrazı (talep reddedilir)",
      "Tebliğ md. 38/1-c: kıymet kriterli gözetimde kendi isteğiyle eşik kıymet üzerinden beyan (talep reddedilir)",
      "Tebliğ md. 41: indirimli oranın talep edilmemesi hâlinde GK 211 uygulanamaz"],
yakinlik="PARAFRAZ",
tuzak=["SAĞDUYU", "KOMŞU", "LİSTE-DIŞI"], duzey=["AYIRT"], profil=[1, 3, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# ---------------- 9 VAKA: YETKİLİ İDARE, TOPLAM TUTAR ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="YETKİ", z="Z",
madde="Gümrük Yönetmeliği md. 500, 502",
cek="Ek tahakkuk ve bağlı ceza kararı için tek başvuru formu düzenlenir; yetkili idare toplam tutara göre belirlenir: 4.730.000 TL üstü bölge müdürlüğü.",
kok=["(C) A.Ş. hakkında yapılan kontrol sonucunda düzenlenen bir ek tahakkuk ile 3.200.000 TL gümrük vergisi, bu ek tahakkuka bağlı ceza kararı ile de 1.900.000 TL para cezası tahsil edilmiştir. Daha sonra (C) A.Ş., ek tahakkuk ve buna bağlı ceza kararındaki tutarların tamamının kanunen ödenmemesi gerektiğini ileri sürerek süresi içinde geri verme başvurusunda bulunmuştur.",
     "Gümrük Yönetmeliği'nde yer alan tutar sınırlarına göre bu başvuru hakkında geri verme işlemini yapmaya yetkili idare aşağıdakilerden hangisidir?"],
d="Gümrük ve dış ticaret bölge müdürlüğü",
c=["İlgili gümrük müdürlüğü",
   "Bakanlık",
   "Ceza kararını veren gümrük müdürlüğü",
   "Yükümlünün bağlı bulunduğu vergi dairesi"],
sirali=False,
g="Gümrük Yönetmeliği'ne göre geri verme veya kaldırma işlemlerini 4.730.000 TL'ye kadar ilgili gümrük müdürlükleri, 47.397.000 TL'ye kadar gümrük ve dış ticaret bölge müdürlükleri, bu tutarın üstünde ise Bakanlık yapar. Başvuru formu her beyanname, ek tahakkuk ve ceza kararı için düzenlenir; ancak bir ek tahakkuk ve buna bağlı ceza kararı için tek bir başvuru formu düzenlenir ve yetkili idare toplam tutar dikkate alınarak belirlenir. Olayda vergi (3.200.000 TL) ve ceza (1.900.000 TL) ayrı ayrı gümrük müdürlüğü sınırının altında kalsa da toplam 5.100.000 TL'dir; bu tutar 4.730.000 TL'yi aşıp 47.397.000 TL'yi aşmadığından yetki gümrük ve dış ticaret bölge müdürlüğündedir. En güçlü çeldirici 'İlgili gümrük müdürlüğü'dür: tutarları ayrı ayrı değerlendiren aday bu şıkka gider. Ceza kararını veren gümrük müdürlüğü para cezalarına ilişkin başvurunun yapılacağı yerdir; vergi dairesine ise geri verilen vergiler yalnızca bildirilir. Bu nedenle doğru cevap 'Gümrük ve dış ticaret bölge müdürlüğü' seçeneğidir. (MD GY 500, 502)",
kanit="47-geri verme kaldırma.txt | 4.730.000  TL'ye kadar olan geri verme veya kaldırma işlemlerini yapmaya ilgili gümrük müdürlükleri || 47-geri verme kaldırma.txt | 47.397.000. TL'ye kadar olan geri verme veya kaldırma işlemlerini yapmaya gümrük ve dış ticaret bölge müdürlükleri || 47-geri verme kaldırma.txt | Tek başvuru kapsamı bir beyanname ve bu beyannameye bağlı ceza kararı ile bir ek tahakkuk ve buna bağlı ceza kararı için 500 üncü madde uyarınca geri verme veya kaldırma işlemini yapmaya yetkili idarenin tespiti toplam tutar dikkate alınarak yapılır",
yuva=["GY 500/1-a: 4.730.000 TL'ye kadar ilgili gümrük müdürlüğü (tutarları ayrı ayrı değerlendiren hata)",
      "GY 500/1-c: 47.397.000 TL'nin üstünde Bakanlık",
      "Tahsilat Tebliği md. 34/2: para cezası geri verme talebinin cezayı veren gümrük müdürlüğüne yapılması",
      "GY 505/3: geri verilen gümrük vergilerinin yükümlünün bağlı bulunduğu vergi dairesine bildirilmesi"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "MAKAM", "AD-HESAP"], duzey=["UYGULAMA"], profil=[1, 2],
olumsuz=False, vaka=True, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2022/90", kapsamli=False,
),

# ---------------- 10 SÜRE + İŞLEM: KARARA BAĞLAMA SÜRESİ ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="SÜRE", z="O",
madde="Gümrük Yönetmeliği md. 504; Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2) md. 31",
cek="Geri verme talebi otuz gün içinde idare amirince karara bağlanır; uyulamayacaksa süre dolmadan gerekçe ve ek süre yükümlüye bildirilir.",
kok=["Gümrük Yönetmeliği ve Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2)'ye göre geri verme veya kaldırma talebinin yetkili gümrük idaresince karara bağlanma süresi ile bu süreye uyulamayacak olması hâlinde yapılacak işlem aşağıdakilerden hangisinde birlikte doğru olarak verilmiştir?"],
d="Otuz gün – Süre dolmadan önce, gecikmenin gerekçeleri ile karar için gereken ek süre yükümlüye bildirilir.",
c=["Otuz gün – Süre içinde karar alınamazsa başvuru geri çekilmiş sayılır ve başvuru sahibi derhal haberdar edilir.",
   "Otuz gün – Süre içinde karar alınamazsa geri verilecek tutar üzerinden kanuni faiz oranında faiz ödenir.",
   "On beş gün – Süre dolmadan önce, gecikmenin gerekçeleri ile karar için gereken ek süre yükümlüye bildirilir.",
   "Dört ay – Süre içinde karar alınamazsa geri verilecek tutar üzerinden kanuni faiz oranında faiz ödenir."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre geri verme veya kaldırma talebi yetkili gümrük idaresince incelenerek otuz gün içerisinde idare amirince karara bağlanır. Tahsilat Tebliği bu süreye uyulamayan durumu düzenler: başvuru otuz günlük süre içinde sonuçlandırılamayacaksa, süre dolmadan önce süre aşımını gerekli kılan gerekçeler ile talep hakkında karar vermek için gerekli görülen ek süre belirtilerek yükümlüye bildirimde bulunulur. Başvurunun geri çekilmiş sayılması, eksik bilgi veya belgenin idarece belirlenen sürede tamamlanmaması hâlinin sonucudur. Dört ay ve kanuni faiz ise karar alındıktan sonra geri verme kararının tebliğinden itibaren dört ay içinde uygulanmaması hâline aittir. On beş gün, hatalı olarak geri verilen tutarların tebliğden itibaren ödenme süresidir. En güçlü çeldirici, aynı otuz günü geri çekilmiş sayılma sonucuyla birleştiren seçenektir. Bu nedenle doğru cevap 'Otuz gün – Süre dolmadan önce, gecikmenin gerekçeleri ile karar için gereken ek süre yükümlüye bildirilir.' seçeneğidir. (MD GY 504; Tebliğ 31)",
kanit="47-geri verme kaldırma.txt | Geri verme veya kaldırma talebi, yetkili gümrük idaresi tarafından incelenerek otuz gün içerisinde idare amirince karara bağlanır || 47-geri verme kaldırma.txt | eğer bu süreye uyulamıyorsa, sürenin dolmasından önce, süre aşımını gerekli kılan gerekçeler ile talep hakkında karar vermek için gerekli görülen ek süreyi de belirterek yükümlüye bildirimde bulunulması gerekir",
yuva=["GY 502/4: eksik bilgi-belge süresine uyulmazsa başvurunun geri çekilmiş sayılması",
      "GK 216/2: geri verme kararının uygulanmaması hâlinde kanuni faiz (süre otuz gün değil)",
      "GK 217: hatalı geri verilen tutarların tebliğden itibaren on beş gün içinde ödenmesi",
      "GK 216/2: karar tebliğinden itibaren dört ay içinde uygulanmazsa kanuni faiz"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "YAKIN-SAYI"], duzey=["AYIRT"], profil=[1, 2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2024/84", kapsamli=False,
),

# ---------------- 11 SÜRE: FAİZİN HESAPLANDIĞI DÖNEM ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="SÜRE", z="Z",
madde="4458 sayılı Gümrük Kanunu md. 216",
cek="Geri verme kararı dört ayda uygulanmazsa talep üzerine faiz, karar tebliğinden ödeme tarihine kadar kanuni faiz oranında hesaplanır.",
kok=["4458 sayılı Gümrük Kanunu'na göre geri verme kararının tebliğ edildiği tarihten itibaren dört ay içerisinde idarece uygulanmaması hâlinde, ilgilinin talebi üzerine geri verilecek tutar üzerinden ödenecek faiz hangi süre için hesaplanır?"],
d="Geri verme kararının tebliğ tarihinden ödemenin yapıldığı tarihe kadar geçen süre için",
c=["Dört aylık sürenin bittiği tarihten ödemenin yapıldığı tarihe kadar geçen süre için",
   "Gümrük vergilerinin ödendiği tarihten geri verme kararının tebliğ tarihine kadar geçen süre için",
   "Geri verme başvurusunun yapıldığı tarihten ödemenin yapıldığı tarihe kadar geçen süre için",
   "Geri verme kararının tebliğ tarihinden ilgilinin faiz talebinde bulunduğu tarihe kadar geçen süre için"],
sirali=False,
g="Gümrük Kanunu'na göre geri verme kararının tebliğ edildiği tarihten itibaren dört ay içerisinde idarece söz konusu kararın uygulanmaması hâlinde, ilgilinin talebi üzerine, tebliğ tarihinden ödemenin yapıldığı tarihe kadar geçen süre için geri verilecek tutar üzerinden aynı dönemde kanuni faiz oranında hesaplanan faiz ödenir. Dört aylık süre faizin doğup doğmayacağını belirler; faiz doğduğunda dönemin başlangıcı dört ayın bitimi değil, kararın tebliğ tarihidir. En güçlü çeldirici 'Dört aylık sürenin bittiği tarihten' başlayan seçenektir; aynı cümledeki iki ayrı tarihi karıştıran aday bu şıkka gider. Vergilerin ödendiği tarih ve başvuru tarihi faiz döneminin unsurları değildir; faiz talebi faizin ödenmesinin şartıdır, dönemin bitişi ise ödemenin yapıldığı tarihtir. Bu nedenle doğru cevap 'Geri verme kararının tebliğ tarihinden ödemenin yapıldığı tarihe kadar geçen süre için' seçeneğidir. (MD 216)",
kanit="47-geri verme kaldırma.txt | ay içerisinde idarece söz konusu kararın uygulanmaması hâlinde, ilgilinin talebi üzerine, tebliğ tarihinden ödemenin yapıldığı tarihe kadar geçen süre için geri verilecek tutar üzerinden, aynı dönemde kanuni faiz",
yuva=["GK 216/2: aynı cümledeki dört aylık uygulama süresi (faizin doğma şartı, dönem başlangıcı değil)",
      "GK 210/a: geri vermenin ödenmiş vergiye ilişkin olmasından hareketle dönemi vergi ödemesinden başlatan hata",
      "GK 211/2 ve GY 502/1: ilgilinin müracaatı/başvurusu üzerine geri verme",
      "GK 216/2: aynı cümledeki 'ilgilinin talebi üzerine' kaydı (faizin şartı, dönem sonu değil)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU"], duzey=["AYIRT"], profil=[2],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# ---------------- 12 HESAP: KISMİ İHRAÇ VE İMHA ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="HESAP", z="Z",
madde="Gümrük Yönetmeliği md. 510; 4458 sayılı Gümrük Kanunu md. 213",
cek="Eşyanın bir kısmı ihraç edilir veya izinli başka işleme (imha) konu edilirse geri verilecek tutar, tamamının vergisiyle kalan kısmın vergisi arasındaki farktır.",
kok=["(D) A.Ş. tarafından aynı birim kıymet ve vergi oranına tabi 100 adet makine serbest dolaşıma sokulmuş ve eşyanın tamamı için 80.000 TL ithalat vergisi ödenmiştir. Beyannamenin tescili tarihi itibarıyla 40 adet makinenin ithaline esas sözleşme hükümlerine aykırı olduğu anlaşılmış ve bu makineler ithalatçı tarafından kabul edilmemiştir. Bu 40 makine, aykırılığın tespiti için gerekli ilk kullanım dışında kullanılmamış; bunlardan 30 adedi Türkiye Gümrük Bölgesi dışına ihraç edilmiş, 10 adedi ise ithalatçının talebi üzerine ihracat yerine gümrük idaresinin izniyle ve denetimi altında imha edilmiştir. Geri verme başvurusu süresi içinde yapılmıştır.",
     "4458 sayılı Gümrük Kanunu ve Gümrük Yönetmeliği'ne göre (D) A.Ş.'ye geri verilmesi gereken ithalat vergisi tutarı kaç TL'dir?"],
d="32.000",
c=["24.000", "48.000", "56.000", "80.000"],
sirali=True,
siklar=["24.000", "32.000", "48.000", "56.000", "80.000"],
g="Gümrük Kanunu'na göre kusurlu veya sözleşmeye aykırı eşyanın vergileri, eşya ilk kullanım dışında kullanılmamışsa ve ihraç edilirse geri verilir; gümrük idareleri ilgilinin talebi üzerine ihracat yerine imhaya da izin verir. Gümrük Yönetmeliği'ne göre talebe konu eşyanın bir kısmının ihraç edilmesi veya gümrükçe izin verilen başka bir işlem veya kullanıma konu edilmesi hâlinde geri verilecek tutar, eşyanın tamamına uygulanan ithalat vergileri ile geri kalan kısmına uygulanması gereken ithalat vergileri arasındaki farktır. İhraç edilen 30 ve imha edilen 10 makine birlikte değerlendirilir; geriye 60 makine kalır. Birim vergi 80.000 / 100 = 800 TL olduğundan kalan kısmın vergisi 60 × 800 = 48.000 TL, geri verilecek tutar 80.000 − 48.000 = 32.000 TL'dir. En güçlü çeldirici 24.000'dir: izinle imha edilen 10 makineyi hesaba katmayıp yalnızca ihraç edilenleri esas alan aday bu sonuca ulaşır. 48.000 kalan kısmın vergisidir; 56.000 hem imhayı atlayıp hem de kalan kısmın vergisini geri verilecek tutar sanan hesaptır. Bu nedenle doğru cevap '32.000' seçeneğidir. (MD GY 510; GK 213)",
kanit="47-geri verme kaldırma.txt | Geri verme veya kaldırma talebine konu eşyanın bir kısmının ihraç veya yeniden ihraç edilmesi veya gümrükçe izin verilen başka bir işlem veya kullanıma konu edilmesi halinde || 47-geri verme kaldırma.txt | eşyanın tamamına uygulanan ithalat vergileri tutarı ile eşyanın geri kalan kısmına uygulanması gereken ithalat vergileri tutarı arasındaki fark kadardır || 47-geri verme kaldırma.txt | Gümrük idareleri, ilgilinin talebi üzerine, eşyanın ihracı yerine; imhasına",
yuva=["24.000: GY 510'daki 'gümrükçe izin verilen başka bir işlem' kapsamındaki imhayı atlayıp yalnız ihraç edilen 30 makineyi esas alan hesap",
      "48.000: GY 510'daki farkın ikinci terimi (kalan 60 makinenin vergisi) geri verilecek tutar sanılmış",
      "56.000: imha atlanmış ve kalan 70 makinenin vergisi geri verilecek tutar sanılmış",
      "80.000: kısmi hâl göz ardı edilip eşyanın tamamına uygulanan vergi geri verilmiş (GY 510'un birinci terimi)"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "AD-HESAP"], duzey=["UYGULAMA"], profil=[1, 2],
olumsuz=False, vaka=True, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2025/26", kapsamli=False,
),

# ---------------- 13 MESLEK YANLILIĞI: YGM'YE TESPİT YAPTIRILMASI ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="YETKİ", z="O",
madde="Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2) md. 31",
cek="Mavi ve yeşil hat beyannamelerinde geri verme için yükümlü nezdinde tespit gerekirse bu işlemler yetkilendirilmiş gümrük müşavirlerine yaptırılabilir.",
kok=["Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2)'ye göre mavi ve yeşil hat kontrol türleri kapsamında işlem görmüş gümrük beyannamelerine ilişkin geri verme veya kaldırma başvurularının değerlendirilmesinde, yükümlü nezdinde ayrıca bir inceleme veya tespit yapılmasına gerek bulunması durumunda bu tespit işlemlerine ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Tespit işlemleri yetkilendirilmiş gümrük müşavirlerine yaptırılabilir.",
c=["Tespit işlemlerinin, başvuruyu yükümlü adına yapan gümrük müşavirince yürütülmesi zorunludur.",
   "Tespit işlemleri, gümrük müşavirlerinin yanında çalışan gümrük müşavir yardımcılarına yaptırılabilir.",
   "Tespit işlemleri yalnızca başvurunun yapıldığı gümrük idaresinin memurlarınca yapılabilir.",
   "Tespit işlemleri, yükümlünün bağlı bulunduğu vergi dairesine yaptırılır."],
sirali=False,
g="Tahsilat Tebliği'ne göre mavi ve yeşil hat kontrol türleri kapsamında işlem görmüş gümrük beyannamelerine ilişkin geri verme veya kaldırma başvurularının değerlendirilmesinde, yükümlü nezdinde ayrıca bir inceleme veya tespit yapılmasına gerek bulunursa, buna ilişkin tespit işlemleri yetkilendirilmiş gümrük müşavirlerine yaptırılabilir. Hüküm bir imkân tanır, zorunluluk getirmez ve bu yetkiyi yalnızca yetkilendirilmiş gümrük müşavirine verir. Başvuruyu temsilci sıfatıyla yapan gümrük müşavirinin tespiti yürütmesi zorunlu değildir; gümrük müşavir yardımcısına da böyle bir görev tanınmamıştır. Başvurunun şeklen incelenmesi ve tamamlayıcı işlemler başvurunun yapıldığı gümrük idaresince yerine getirilir, ancak tespitin yalnızca idare memurlarınca yapılabileceğine dair bir sınır yoktur; vergi dairesine ise geri verilen vergiler yalnızca bildirilir. En güçlü tuzak, 'müşavir her işte zorunludur' ya da 'yardımcı da yapabilir' önyargısıdır. Bu nedenle doğru cevap 'Tespit işlemleri yetkilendirilmiş gümrük müşavirlerine yaptırılabilir.' seçeneğidir. (MD Tebliğ 31)",
kanit="47-geri verme kaldırma.txt | mavi ve yeşil hat kontrol türleri kapsamında işlem görmüş gümrük beyannamelerine ilişkin geri verme veya kaldırma başvurularının değerlendirilmesinde, yükümlü nezdinde ayrıca bir inceleme veya tespit yapılmasına gerek bulunması durumunda, buna ilişkin tespit işlemleri yetkilendirilmiş gümrük müşavirlerine yaptırılabilir",
yuva=["GY 502/1: başvurunun temsilci tarafından yapılabilmesi (zorunluluk değil); 'müşavir şarttır' önyargısı",
      "Meslek yanlılığı: hükmün yalnız yetkilendirilmiş gümrük müşavirini sayması; yardımcıya yetki tanınmamıştır",
      "Tahsilat Tebliği md. 31/1: şekli inceleme ve tamamlayıcı işlemlerin başvurunun yapıldığı gümrük idaresince yürütülmesi",
      "GY 505/3: geri verilen gümrük vergilerinin yükümlünün bağlı bulunduğu vergi dairesine bildirilmesi"],
yakinlik="BİREBİR",
tuzak=["TERİM", "MUTLAK", "KOMŞU"], duzey=["TANIMA"], profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# ---------------- 14 ÖNERMELİ: MAHSUP VE ÖDEME ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="ÖNERMELİ", z="Z",
madde="Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2) md. 39, 40",
cek="Geri verme için gümrük idarelerine muaccel borç bulunmamalı; mahsup önce Bakanlığa, sonra Maliye Bakanlığına bağlı dairelere; ödeme asıl yükümlünün hesabına yapılır.",
kok=["Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2)'nin geri verilecek tutarın mahsubu ve yükümlüye ödenmesine ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Geri verilecek amme alacağı öncelikle yükümlünün Maliye Bakanlığına bağlı tahsil dairelerine olan muaccel borçlarına, kalan tutar ise Bakanlığa bağlı tahsil dairelerine olan muaccel borçlarına mahsup edilir.",
     "II. Gümrük idaresince geri verme yapılabilmesi için yükümlünün 6183 sayılı Kanun kapsamında gümrük idarelerine muaccel hâle gelmiş borcunun bulunmaması gerekir.",
     "III. Mahsup hâlleri dışında, geri verme kararları uyarınca ödenecek tutarlar asıl yükümlüye veya temsilcisine ait banka hesap numarasına aktarılır.",
     "IV. Yükümlünün borç durumunu gösteren belge, belge talebinin yapıldığı gümrük idaresince karşılanabileceği gibi e-Devlet üzerinden de temin edilebilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="II ve IV",
c=["I ve II", "I ve III", "II ve III", "II, III ve IV"],
sirali=False,
g="Tahsilat Tebliği'ne göre gümrük idaresince geri verme yapılabilmesi için yükümlünün 6183 sayılı Kanun kapsamında gümrük idarelerine muaccel hâle gelmiş borcunun bulunmaması gerekir (II doğru). Yükümlü borç durumunu gösteren belgeyi talep ederse bu talep, talebin yapıldığı gümrük idaresince karşılanır; belge e-Devlet üzerinden de temin edilebilir (IV doğru). Amme alacağının geri verilmesinde mahsup sırası terstir: gümrük idaresince öncelikle yükümlünün Bakanlığa bağlı tahsil dairelerine olan muaccel borçlarına mahsup yapılır, kalan tutar bulunursa Maliye Bakanlığına bağlı tahsil dairelerine olan muaccel borçlara mahsup edilir (I yanlış). Mahsup hâlleri dışında ödenecek tutarlar yalnızca asıl yükümlüye ait banka hesap numarasına aktarılır; temsilci hesabına aktarma öngörülmemiştir (III yanlış). En güçlü çeldirici 'II, III ve IV'tür: başvuruyu temsilcinin yapabilmesinden hareketle ödemenin de temsilciye yapılabileceğini düşünen aday bu şıkka gider. Bu nedenle doğru cevap 'II ve IV' seçeneğidir. (MD Tebliğ 39, 40)",
kanit="47-geri verme kaldırma.txt | amme alacağının geri verilmesinde gümrük idaresince öncelikle yükümlünün Bakanlığa bağlı tahsil dairelerine olan muaccel borçlarına mahsup yapılır, mahsup sonrası kalan bir tutar bulunması halinde ise bu tutar, Maliye Bakanlığına bağlı tahsil dairelerine olan muaccel borçlarına mahsup edilir || 47-geri verme kaldırma.txt | Gümrük idaresince geri verme yapılabilmesi için, yükümlünün 6183 sayılı Kanun kapsamında gümrük idarelerine muaccel hale gelmiş borcunun bulunmaması gerekir || 47-geri verme kaldırma.txt | 39 uncu maddedeki mahsup halleri hariç, asıl yükümlüye ait olan banka hesap numarasına aktarılır || 47-geri verme kaldırma.txt | belge talebinin yapıldığı gümrük idaresince karşılanır. Borç durumunu gösteren belge e-Devlet üzerinden de temin edilebilir",
yuva=["I ve II: Tebliğ md. 39/3'teki mahsup sırasını ters bilen aday",
      "I ve III: mahsup sırasını ters bilen ve GY 502/1'deki temsilci başvurusunu ödemeye taşıyan aday",
      "II ve III: Tebliğ md. 40'taki 'asıl yükümlü' kaydını kaçırıp md. 39/4'teki e-Devlet imkânını bilmeyen aday",
      "II, III ve IV: GY 502/1'deki temsilcinin başvuru yapabilmesini ödeme hesabına taşıyan aday (md. 40: asıl yükümlü)"],
yakinlik="PARAFRAZ",
tuzak=["TERSİNE", "MAKAM", "UNSUR"], duzey=["AYIRT"], profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# ---------------- 15 SÜRE: BEYANNAME İPTALİNDE GERİ VERME İSTEMİ ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="SÜRE", z="O",
madde="4458 sayılı Gümrük Kanunu md. 212",
cek="Beyanname iptali üzerine ödenmiş vergilerin geri verilmesi ilgilinin talebiyle olur; istem beyanname iptali başvurusu için öngörülen süreler içinde yapılır.",
kok=["4458 sayılı Gümrük Kanunu'na göre bir gümrük beyannamesine dayanılarak ödenmiş olan gümrük vergilerinin bu beyannamenin iptal edilmesi üzerine geri verilmesine ilişkin istem hangi süre içerisinde yapılmalıdır?"],
d="Gümrük beyannamesinin iptal edilmesi amacıyla müracaatta bulunulması için öngörülen süreler içerisinde",
c=["Vergilerin yükümlüye tebliği tarihinden itibaren üç yıl içerisinde",
   "Vergilerin yükümlüye tebliği tarihinden itibaren bir yıl içerisinde",
   "Beyannamenin iptal edildiği tarihten itibaren otuz gün içerisinde",
   "Beyannamenin iptal edildiği tarihten itibaren dört ay içerisinde"],
sirali=False,
g="Gümrük Kanunu'na göre bir gümrük beyannamesine dayanılarak ödenmiş olan gümrük vergileri, bu beyannamenin iptal edilmesi üzerine ilgilinin talebiyle geri verilir ve bu istemin gümrük beyannamesinin iptal edilmesi amacıyla müracaatta bulunulması için öngörülen süreler içerisinde yapılması gerekir. Yani beyanname iptalinde geri verme için ayrı bir süre öngörülmemiş, iptal başvurusunun süresine bağlanmıştır; Yönetmelik de talebin iptal sebebine göre belirlenen süreler içinde yapılmasını arar. Üç yıl kanunen ödenmemesi gereken vergiler için, bir yıl kusurlu eşya ile uluslararası anlaşma hâlleri için öngörülen başvuru süreleridir. Otuz gün geri verme talebinin karara bağlanma süresi, dört ay ise geri verme kararının uygulanma süresidir. En güçlü çeldirici üç yıllık genel süredir; beyanname iptalini de 'kanunen ödenmemesi gereken vergi' sayan aday bu şıkka gider. Bu nedenle doğru cevap 'Gümrük beyannamesinin iptal edilmesi amacıyla müracaatta bulunulması için öngörülen süreler içerisinde' seçeneğidir. (MD GK 212; GY 499)",
kanit="47-geri verme kaldırma.txt | Bir gümrük beyannamesine dayanılarak ödenmiş olan gümrük vergileri bu beyannamenin iptal edilmesi üzerine ilgilinin talebiyle geri verilir. Bu istemin, gümrük beyannamesinin iptal edilmesi amacıyla müracaatta bulunulması için öngörülen süreler içerisinde yapılması gerekir.",
yuva=["GK 211/2 ve GY 502/5: kanunen ödenmemesi gereken vergilerde tebliğden itibaren üç yıl",
      "GK 213/4 ve 214: kusurlu eşya ile uluslararası anlaşma hâllerinde tebliğden itibaren bir yıl",
      "GY 504/2: geri verme talebinin otuz gün içinde karara bağlanması",
      "GK 216/2: geri verme kararının tebliğinden itibaren dört ay içinde uygulanması"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "SAYI"], duzey=["HATIRLAMA"], profil=[2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# ---------------- 16 YANLIŞ: HATALI GERİ VERME VE KALDIRMA ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="YANLIŞ", z="O",
madde="4458 sayılı Gümrük Kanunu md. 216, 217",
cek="Hatalı kaldırma veya geri vermede vergiler ve ödenmiş faizler yeniden tahsil edilir; tebliğ tarihinden itibaren on beş günde ödenmeyenlere 6183 uygulanır.",
kok=["4458 sayılı Gümrük Kanunu'nun geri verme kararlarının uygulanmasına ve gümrük vergilerinin hatalı olarak kaldırılması veya geri verilmesi hâlinde yapılacak işlemlere ilişkin hükümlerine göre aşağıdakilerden hangisi yanlıştır?"],
d="Hatalı olarak kaldırılan veya geri verilen ve tahsil edilmeyen miktarlar, hatanın tespit edildiği tarihten itibaren on beş gün içinde ödenir.",
c=["Gümrük vergilerinin hatalı olarak kaldırılması veya geri verilmesi hâlinde başlangıçta tahakkuk eden vergiler yeniden tahsil edilir.",
   "Geri verme kararının süresinde uygulanmaması nedeniyle ödenmiş faizler de hatalı geri verme hâlinde yeniden tahsil edilir.",
   "Yeniden tahsil edilmesi gereken miktarlardan süresi içinde ödenmeyenler için 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanun hükümlerine göre işlem yapılır.",
   "Geri verme kararının tebliğinden itibaren dört ay içinde idarece uygulanmaması hâlinde, ilgilinin talebi üzerine kanuni faiz oranında faiz ödenir."],
sirali=False,
g="Gümrük Kanunu'na göre gümrük vergilerinin hatalı olarak kaldırılması veya geri verilmesi hâlinde, başlangıçta tahakkuk eden vergiler ile geri verme kararının dört ay içinde uygulanmaması nedeniyle ödenmiş faizler yeniden tahsil edilir. Tahsil edilmeyen miktarlar hatanın tespit edildiği tarihten değil, tebliğ tarihinden itibaren on beş gün içinde ödenir; bu süre içinde ödenmeyenler için 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanun hükümlerine göre işlem yapılır. Kanun ayrıca geri verme kararının tebliğinden itibaren dört ay içinde idarece uygulanmaması hâlinde ilgilinin talebi üzerine kanuni faiz oranında faiz ödeneceğini öngörür. Yanlış şık, on beş günlük sürenin başlangıcını tek bir unsurla değiştirmiştir; sayı doğru olduğu için hızlı okuyan aday bu şıkkı doğru sanar. Bu nedenle doğru cevap 'Hatalı olarak kaldırılan veya geri verilen ve tahsil edilmeyen miktarlar, hatanın tespit edildiği tarihten itibaren on beş gün içinde ödenir.' seçeneğidir. (MD 216, 217)",
kanit="47-geri verme kaldırma.txt | Gümrük vergilerinin hatalı olarak kaldırılması veya geri verilmesi halinde, başlangıçta tahakkuk eden vergiler ile 216 ncı madde uyarınca ödenmiş faizler yeniden tahsil edilir. || 47-geri verme kaldırma.txt | Tahsil edilmeyen miktarlar tebliğ tarihinden itibaren onbeş gün || 47-geri verme kaldırma.txt | Bu süre içinde ödenmeyenler için 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanun hükümlerine göre işlem yapılır.",
yuva=["GK 217 birinci cümle: başlangıçta tahakkuk eden vergilerin yeniden tahsili (doğru)",
      "GK 217 birinci cümle: GK 216 uyarınca ödenmiş faizlerin yeniden tahsili (doğru)",
      "GK 217 son cümle: süresinde ödenmeyenlere 6183 sayılı Kanun hükümlerinin uygulanması (doğru)",
      "GK 216/2: karar tebliğinden itibaren dört ay içinde uygulanmazsa talep üzerine kanuni faiz (doğru)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU"], duzey=["AYIRT"], profil=[4],
olumsuz=True, vaka=False, baslangic=True, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# ---------------- 17 DOĞRU: BAŞVURU SÜRELERİ (TEBLİĞ) ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="DOĞRU", z="Z",
madde="Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2) md. 32, 33",
cek="Süresinde yapılan geri verme başvurusuna, itiraz süresinin kaçırılmış olması engel değildir; ek tahakkukta süre ek tahakkukun tebliğinden itibaren üç yıldır.",
kok=["Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No: 2)'nin geri verme veya kaldırma işlemlerinde başvuru sürelerine ilişkin hükümlerine göre aşağıdakilerden hangisi doğrudur?"],
d="Başvurunun öngörülen süreler içinde yapılması hâlinde, itiraz hakkından yararlanmak için süresi içinde itiraz başvurusunda bulunulmamış olması geri verme veya kaldırma başvurusuna engel teşkil etmez.",
c=["Kontrol ve denetlemeler sonucunda hiç alınmadığı veya noksan alındığı belirlenerek tahsil edilen vergilere ilişkin geri verme başvurusunun, ek tahakkukun tebliği tarihinden itibaren bir yıl içinde yapılması gerekir.",
   "Kontrol ve denetlemeler sonucunda hiç alınmadığı veya noksan alındığı belirlenerek tahsil edilen vergilere ilişkin geri verme başvurusunun, ek tahakkukun ödendiği tarihten itibaren üç yıl içinde yapılması gerekir.",
   "Dahilde işleme rejimi kapsamında yapılan ihracat sırasında kur veya vergi oranının yanlış hesaplanması nedeniyle fazla alınan telafi edici verginin geri verilmesi için, vergilerin tebliğinden itibaren bir yıl içinde talepte bulunulması gerekir.",
   "Dahilde işleme rejimi kapsamında işlem gören ihracat beyannamesinin iptali üzerine telafi edici verginin geri verilmesi için, beyannamenin iptal edildiği tarihten itibaren üç yıl içinde talepte bulunulması gerekir."],
sirali=False,
g="Tahsilat Tebliği'ne göre geri verme veya kaldırma başvurusu Kanunda ve Yönetmelikte belirlenen süreler içinde yapılırsa, itiraz hakkından yararlanmak için süresi içinde itiraz başvurusunda bulunulmamış olması geri verme veya kaldırma başvurusuna engel teşkil etmez; iki yol birbirinden bağımsızdır. Kontrol ve denetlemeler sonucunda hiç alınmadığı veya noksan alındığı belirlenerek tahsil edilen vergilerde geri verme başvurusu, ek tahakkukun ödendiği tarihten değil tebliği tarihinden itibaren ve bir yıl değil üç yıl içinde yapılır. Dahilde işleme rejimi kapsamında ihracat sırasında kur veya vergi oranının yanlış hesaplanması gibi nedenlerle fazla alınan telafi edici vergi, kanunen ödenmemesi gereken vergiler için öngörülen üç yıllık süre içinde talep edilirse geri verilir. Dahilde işleme kapsamındaki ihracat beyannamesinin iptali üzerine telafi edici verginin geri verilmesi ise üç yıl içinde değil, Yönetmelikte beyanname iptali için belirlenen süre içinde talep edilir. En güçlü tuzak, 'itiraz süresini kaçıran geri verme de isteyemez' sağduyusudur. Bu nedenle doğru cevap 'Başvurunun öngörülen süreler içinde yapılması hâlinde, itiraz hakkından yararlanmak için süresi içinde itiraz başvurusunda bulunulmamış olması geri verme veya kaldırma başvurusuna engel teşkil etmez.' seçeneğidir. (MD Tebliğ 32, 33)",
kanit="47-geri verme kaldırma.txt | Bu süreler içerisinde başvurunun yapılması halinde Gümrük Kanununun 242 nci maddesinde düzenlenen itiraz hakkından yararlanmak için süresi içerisinde itiraz başvurusunda bulunulmaması geri verme veya kaldırma başvurusunda bulunulmasına engel teşkil etmez || 47-geri verme kaldırma.txt | buna ilişkin başvurunun ek tahakkukun tebliği tarihinden itibaren üç yıl içinde yapılması gerekir || 47-geri verme kaldırma.txt | fazla alındığı anlaşılan telafi edici vergi, Gümrük Kanununun 211 inci maddesi ikinci fıkrasında belirtilen süre içerisinde talepte bulunulması halinde geri verilir || 47-geri verme kaldırma.txt | Gümrük Yönetmeliğinin 417 nci maddesindeki beyanname iptali için belirlenen süre içerisinde talepte bulunulması gerekir",
yuva=["Tebliğ md. 32/2: ek tahakkukta süre tebliğden itibaren üç yıl (bir yıl kusurlu eşya ve uluslararası anlaşma süresidir)",
      "Tebliğ md. 32/2: sürenin ek tahakkukun tebliği tarihinden başlaması (ödeme tarihi değil)",
      "Tebliğ md. 33/3: yanlış hesaplanan telafi edici vergide GK 211/2'deki üç yıllık süre",
      "Tebliğ md. 33/1: DİR ihracat beyannamesi iptalinde GY 417'deki beyanname iptali süresi"],
yakinlik="BİREBİR",
tuzak=["SAĞDUYU", "BAŞLANGIÇ", "YAKIN-SAYI", "KOMŞU"], duzey=["AYIRT"], profil=[1, 3],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="", guncellik="", cikmis="2022/89", kapsamli=False,
),

# ---------------- 18 YANLIŞ: BAŞVURU USULÜ (YÖNETMELİK) ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="YANLIŞ", z="O",
madde="Gümrük Yönetmeliği md. 502",
cek="Birden fazla beyanname, ek tahakkuk ve ceza kararı için elektronik ortamda tek başvuru formu düzenlenmesine ilişkin düzenleme yapmaya Bakanlık yetkilidir.",
kok=["Gümrük Yönetmeliği'nin geri verme veya kaldırma başvurusunun yapılması, başvuru formunun düzenlenmesi ve eksikliklerin tamamlanmasına ilişkin hükümlerine göre aşağıdakilerden hangisi yanlıştır?"],
d="Konusu ve gümrük idaresi aynı olan birden fazla beyanname için elektronik ortamda tek bir başvuru formu ile başvuru yapılabilmesine ilişkin düzenleme yapmaya gümrük ve dış ticaret bölge müdürlükleri yetkilidir.",
c=["Başvuru; vergileri ve cezaları ödeyen veya ödemekle yükümlü olan kişi, bunların temsilcileri ya da hak ve yükümlülükleri devralan kişi tarafından yapılabilir.",
   "Bir beyanname ile bu beyannameye bağlı ceza kararı için tek bir başvuru formu düzenlenir.",
   "Eksik bilgi veya belgenin tamamlanması için gümrük idaresince belirlenen süreye uyulmazsa başvuru geri çekilmiş sayılır.",
   "Kontrol ve denetleme sonucunda geri verme hâllerinden birinin tespit edilmesi üzerine işlem doğrudan yapıldığında, gümrük idaresince hak sahibine gerekli bildirimde bulunulur."],
sirali=False,
g="Gümrük Yönetmeliği'ne göre geri verme veya kaldırma başvurusu; vergileri ve cezaları ödeyen veya ödemekle yükümlü olan kişi, bunların temsilcileri veya hak ve yükümlülükleri devralan kişi tarafından elektronik olarak yapılır. Başvuru formu her beyanname, ek tahakkuk ve ceza kararı için ayrı düzenlenir; ancak bir beyanname ve buna bağlı ceza kararı için tek form düzenlenir. Eksik bilgi veya belge için idarenin belirlediği süreye uyulmazsa başvuru geri çekilmiş sayılır ve başvuru sahibi derhal haberdar edilir. Kontrol ve denetleme sonucunda işlemin doğrudan yapıldığı hâlde de aynı usul uygulanır ve hak sahibine bildirim yapılır. Konusu ve gümrük idaresinin aynı olması, aralarında maddi veya hukuki bağlılık bulunması şartıyla birden fazla beyanname, ek tahakkuk ve ceza kararı için elektronik ortamda tek başvuru formu ile başvuru yapılabilmesine ilişkin düzenleme yapmaya ise bölge müdürlükleri değil Bakanlık yetkilidir. Yanlış şık yalnızca yetkili makamı değiştirmiştir; bölge müdürlüğünün yetki tutarı sınırlarında geçmesi bu karışıklığı kolaylaştırır. Bu nedenle doğru cevap 'Konusu ve gümrük idaresi aynı olan birden fazla beyanname için elektronik ortamda tek bir başvuru formu ile başvuru yapılabilmesine ilişkin düzenleme yapmaya gümrük ve dış ticaret bölge müdürlükleri yetkilidir.' seçeneğidir. (MD GY 502)",
kanit="47-geri verme kaldırma.txt | bu vergileri ve cezaları ödeyen veya ödemekle yükümlü olan kişi veya bunların temsilcileri veya hak ve yükümlülükleri devralan kişi tarafından || 47-geri verme kaldırma.txt | bir beyanname ve bu beyannameye bağlı ceza kararı ile bir ek tahakkuk ve buna bağlı ceza kararı için tek bir başvuru formu düzenlenir || 47-geri verme kaldırma.txt | Bu süreye uyulmaması halinde başvuru geri çekilmiş sayılarak başvuru sahibi derhal bu durumdan haberdar edilir || 47-geri verme kaldırma.txt | Gümrük idaresince hak sahibine bu yönde gerekli bildirimde bulunulur || 47-geri verme kaldırma.txt | elektronik ortamda tek bir başvuru formu ile başvuru yapılabilmesine ilişkin düzenleme yapmaya Bakanlık yetkilidir",
yuva=["GY 502/1: başvurabilecek kişiler (doğru)",
      "GY 502/3 ikinci cümle: beyanname ve bağlı ceza kararı için tek form (doğru)",
      "GY 502/4: süreye uyulmazsa başvurunun geri çekilmiş sayılması (doğru)",
      "GY 502/2: doğrudan yapılan işlemde hak sahibine bildirim (doğru)"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "KOMŞU"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

# ---------------- 19 SÖYLENEMEZ: KANUNEN ÖDENMEMESİ GEREKEN VERGİLER ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="YANLIŞ", z="O",
madde="4458 sayılı Gümrük Kanunu md. 211",
cek="Kontrol ve denetleme sonucunda geri verme veya kaldırma hâli tespit edilirse işlem, müracaat beklenmeden üç yıllık süre içinde doğrudan yapılır.",
kok=["4458 sayılı Gümrük Kanunu'nun kanunen ödenmemesi veya tahakkuk ettirilmemesi gereken gümrük vergilerinin geri verilmesi veya kaldırılmasına ilişkin hükümleri için aşağıdakilerden hangisi söylenemez?"],
d="Kontrol ve denetleme sonucunda geri verme veya kaldırma hâllerinden birinin tespit edilmesi durumunda dahi işlem, ancak ilgilinin gümrük idaresine müracaatı üzerine yapılabilir.",
c=["Kanunen tahakkuk ettirilmemeleri gerektiği hâlde tahakkuk ettirilen gümrük vergileri kaldırılır.",
   "Kanunen ödenmemeleri gerektiği hâlde ödenmiş olduğu belirlenen gümrük vergileri geri verilir.",
   "Geri verme veya kaldırma, vergilerin yükümlüye tebliğ edilmesi ve ilgilinin üç yıl içinde gümrük idaresine müracaatı üzerine yapılır.",
   "Başvuru süresi mücbir sebep veya beklenmeyen hâllerde uzatılabilir."],
sirali=False,
g="Gümrük Kanunu'na göre kanunen ödenmemeleri gerektiği hâlde ödenmiş olduğu belirlenen gümrük vergileri geri verilir, kanunen tahakkuk ettirilmemeleri gerektiği hâlde tahakkuk ettirilen gümrük vergileri kaldırılır. Bu vergiler, yükümlüye tebliğ edilmeleri ve ilgilinin üç yıl içinde gümrük idaresine müracaatı üzerine geri verilir veya kaldırılır; bu süre mücbir sebep veya beklenmeyen hâllerde uzatılabilir. Ancak geri verme veya kaldırma her zaman başvuruya bağlı değildir: kontrol ve denetleme sonucunda geri verme veya kaldırma hâllerinden birinin tespiti durumunda, aynı süre içinde işlem doğrudan yapılır. Yanlış şık, doğrudan (re'sen) yapılan işlemi tersine çevirerek müracaat şartına bağlamıştır. Bu nedenle doğru cevap 'Kontrol ve denetleme sonucunda geri verme veya kaldırma hâllerinden birinin tespit edilmesi durumunda dahi işlem, ancak ilgilinin gümrük idaresine müracaatı üzerine yapılabilir.' seçeneğidir. (MD 211)",
kanit="47-geri verme kaldırma.txt | Kontrol ve denetleme sonucunda, geri verme veya kaldırma hallerinden birinin tespiti durumunda, aynı süre içinde geri verme veya kaldırma işlemi doğrudan yapılır. || 47-geri verme kaldırma.txt | Bu süre mücbir sebep veya beklenmeyen hallerde uzatılabilir. || 47-geri verme kaldırma.txt | Kanunen tahakkuk ettirilmemeleri gerektiği halde tahakkuk ettirilen gümrük vergileri kaldırılır. || 47-geri verme kaldırma.txt | söz konusu vergilerin yükümlüye tebliğ edilmesi ve ilgilinin üç yıl içinde gümrük idaresine müracaatı üzerine geri verilir veya kaldırılır",
yuva=["GK 211/1 ikinci cümle: tahakkuk ettirilmemesi gerekenlerin kaldırılması (doğru)",
      "GK 211/1 birinci cümle: ödenmemesi gerekenlerin geri verilmesi (doğru)",
      "GK 211/2 birinci paragraf: tebliğ ve üç yıl içinde müracaat (doğru)",
      "GK 211/2 son cümle: mücbir sebep veya beklenmeyen hâllerde sürenin uzatılması (doğru)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU"], duzey=["AYIRT"], profil=[4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="2021/80; 2022/89", kapsamli=False,
),

# ---------------- 20 YETKİ: GERİ VERMEYE TABİ OLMAYACAK MİKTAR ----------------
dict(
konu="Geri Verme ve Kaldırma", blok="SB46",
kalip="YETKİ", z="O",
madde="4458 sayılı Gümrük Kanunu md. 215",
cek="Geri verme veya kaldırma işlemine tabi olmayacak gümrük vergileri miktarı Cumhurbaşkanı Kararı ile belirlenir.",
kok=["4458 sayılı Gümrük Kanunu'na göre geri verme veya kaldırma işlemine tabi olmayacak gümrük vergileri miktarı aşağıdakilerden hangisi ile belirlenir?"],
d="Cumhurbaşkanı Kararı",
c=["Gümrük Yönetmeliği",
   "Bakanlıkça yapılacak düzenleme",
   "Gümrük ve dış ticaret bölge müdürlüğü kararı",
   "Vergi Usul Kanunu uyarınca belirlenen yeniden değerleme oranı"],
sirali=False,
g="Gümrük Kanunu'na göre geri verme veya kaldırma işlemine tabi olmayacak gümrük vergileri miktarı Cumhurbaşkanı Kararı ile belirlenir. Bu miktar, işlemi hangi idarenin yapacağını gösteren tutar sınırlarıyla karıştırılmamalıdır: gümrük müdürlüğü, bölge müdürlüğü ve Bakanlık arasındaki yetki sınırları Gümrük Yönetmeliği'nde belirlenmiş olup her yıl Vergi Usul Kanunu uyarınca belirlenen yeniden değerleme oranında artırılır. Bakanlık ise birden fazla beyanname için tek başvuru formuna ilişkin düzenleme yapmaya yetkilidir. En güçlü çeldirici 'Gümrük Yönetmeliği'dir: yetki tutarlarını bilen aday, tabi olmayacak miktarın da Yönetmelikte düzenlendiğini sanabilir. Bu nedenle doğru cevap 'Cumhurbaşkanı Kararı' seçeneğidir. (MD GK 215; GY 500)",
kanit="47-geri verme kaldırma.txt | Geri verme veya kaldırma işlemine tabi olmayacak gümrük vergileri miktarı Cumhurbaşkanı || 47-geri verme kaldırma.txt | Kararı ile belirlenir. || 47-geri verme kaldırma.txt | Birinci fıkrada belirtilen tutarlar, her yıl, bir önceki yıla ilişkin olarak 213 sayılı Vergi Usul Kanunu uyarınca belirlenen yeniden değerleme oranında arttırılır",
yuva=["GY 500/1: geri verme yetki tutar sınırlarının Yönetmelikte belirlenmesi",
      "GY 502/3: birden fazla beyanname için tek başvuru formuna ilişkin düzenleme yapmaya Bakanlığın yetkili olması",
      "GY 500/1-b: bölge müdürlüğünün 47.397.000 TL'ye kadar geri verme yetkisi",
      "GY 500/2: yetki tutarlarının her yıl VUK yeniden değerleme oranında artırılması"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"], duzey=["HATIRLAMA"], profil=[3],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

]
