# Soru Bankası — Bölüm 54: Elkonulan Akaryakıt Uygulama Yönetmeliği (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
Q = [

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="TANIM",
z="K",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 3",
cek="Kaçak akaryakıtın değeri: elkonulan akaryakıt ihraç eşyasıysa FOB, ithal eşyasıysa CIF kıymeti veya varsa mahkemece belirlenmiş değeridir.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'nde yer alan \"kaçak akaryakıtın değeri\" ifadesinin tanımı aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Elkonulan akaryakıt ihraç eşyası ise FOB kıymeti, ithal eşyası ise CIF kıymeti ya da varsa mahkemece belirlenmiş değeri",
c=["Elkonulan akaryakıt ihraç eşyası ise CIF kıymeti, ithal eşyası ise FOB kıymeti ya da varsa mahkemece belirlenmiş değeri",
   "Elkonulan akaryakıtın temin edildiği yer ve tarihteki normal alım ve satım bedeli",
   "İlana çıkıldığı tarihteki benzeri ürünlerin rafineri çıkış bedelinden vergiler düşüldükten sonra kalan kısım",
   "Rafineride bir önceki ay sonunda oluşan ham petrol/devir maliyet fiyatı"],
sirali=False,
g="Yönetmelikte kaçak akaryakıtın değeri, 5607 sayılı Kanun uyarınca elkonulan akaryakıtın ihraç eşyası olması hâlinde FOB kıymeti, ithal eşyası olması hâlinde CIF kıymeti veya varsa mahkemece belirlenmiş değeri olarak tanımlanmıştır. Bu değer, günlük muhafaza ücretinin hesaplandığı ve ücretin üst sınırının (değerin yüzde otuzu) belirlendiği tutardır. En güçlü çeldirici FOB ile CIF'in yer değiştirdiği seçenektir: ihraç eşyasında FOB, ithal eşyasında CIF esas alınır. 'Temin edildiği yer ve tarihteki normal alım ve satım bedeli' Yönetmelikteki rayiç bedel tanımıdır; rafineri çıkış bedeline dayanan tutar satış ihalesinde tahmini satış bedelinin, ham petrol/devir maliyet fiyatı ise teknik düzenlemelere uygun olmayan akaryakıtın rafinericiye satış bedelinin dayanağıdır. Bu nedenle doğru cevap 'Elkonulan akaryakıt ihraç eşyası ise FOB kıymeti, ithal eşyası ise CIF kıymeti ya da varsa mahkemece belirlenmiş değeri' seçeneğidir. (MD 3, 8)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Kaçak akaryakıtın değeri: 5607 sayılı Kanun uyarınca elkonulan akaryakıtın ihraç eşyası olması halinde FOB kıymetini, ithal eşyası olması halinde CIF kıymetini veya varsa mahkemece belirlenmiş değerini || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Rayiç bedel: Bir mal, iş veya hizmetin temin edildiği yer ve tarihteki normal alım ve satım bedelini || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Muhafaza ücreti, kaçak akaryakıtın değerinin yüzde otuzunu geçemez",
yuva=["Aynı tanımın FOB/CIF eşleşmesinin ters çevrilmiş hâli (ihraçta FOB, ithalde CIF)",
      "Rayiç bedel tanımı (md 3/ı)",
      "Satış ihalesinde tahmini satış bedelinin hesap dayanağı: rafineri çıkış bedelinden vergiler düşüldükten sonra kalan kısım (md 17)",
      "Teknik düzenlemelere uygun olmayan akaryakıtın rafinericiye satış bedeli alt sınırı (md 18)"],
yakinlik="PARAFRAZ",
tuzak=["UNSUR", "TERİM", "KOMŞU"], duzey=["TANIMA", "AYIRT"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="KAVRAM",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 3",
cek="Elkoyan/alıkoyan idare kaçakçılığı önleme, izleme ve araştırmakla görevli birimdir; akaryakıtı teslim alıp muhafaza eden il özel idaresi değildir.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'nde \"5607 sayılı Kanun uyarınca kaçakçılığı önleme, izleme ve araştırmakla görevli olan idare/birim\" biçiminde tanımlanan kavram aşağıdakilerden hangisidir?"],
d="Elkoyan/Alıkoyan idare/birim",
c=["Gümrük idaresi",
   "Müdahil gümrük idaresi",
   "Teslim almakla sorumlu idare",
   "Kurum"],
sirali=False,
g="Yönetmelikte elkoyan/alıkoyan idare/birim, 5607 sayılı Kanun uyarınca kaçakçılığı önleme, izleme ve araştırmakla görevli olan idare veya birim olarak tanımlanmıştır. Akaryakıtı yakalama yerinde kolluk gücünden teslim alıp analiz sonuçları gelinceye kadar saklamakla yükümlü olan il özel idaresi (il özel idaresi bulunmayan yerlerde yatırım izleme ve koordinasyon başkanlığı) teslim almakla sorumlu idaredir; elkoyan idare değildir. Gümrük idaresi, gümrük mevzuatında belirtilen işlemlerin kısmen veya tamamen yerine getirildiği merkez veya taşra teşkilatındaki hiyerarşik yönetim birimlerinin tamamı; Kurum ise Enerji Piyasası Düzenleme Kurumu olarak tanımlanmıştır. Müdahil gümrük idaresi, numunelerin bir adedinin gönderildiği ve muhafazada bozulma veya yok olma hâllerinin bildirildiği idaredir. En güçlü çeldirici 'Teslim almakla sorumlu idare'dir: akaryakıtı fiilen elinde tutan idareyi elkoyan idareyle karıştıran aday bunu seçer. Bu nedenle doğru cevap 'Elkoyan/Alıkoyan idare/birim' seçeneğidir. (MD 3, 4, 5, 16)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Elkoyan/Alıkoyan idare/birim: 5607 sayılı Kanun uyarınca kaçakçılığı önleme, izleme ve araştırmakla görevli olan idareyi/birimi || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Gümrük idaresi: Gümrük mevzuatında belirtilen işlemlerin kısmen veya tamamen yerine getirildiği merkez veya taşra teşkilatındaki hiyerarşik yönetim birimlerinin || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Kurum: Enerji Piyasası Düzenleme Kurumunu || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | akaryakıtı teslim almakla sorumlu idareden || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Numunelerin bir adedi müdahil gümrük idaresine gönderilir",
yuva=["Gümrük idaresi tanımı: gümrük işlemlerinin yapıldığı merkez veya taşra hiyerarşik birimlerinin tamamı (md 3/e)",
      "Müdahil gümrük idaresi: numunelerin bir adedinin gönderildiği, bozulma ve kayıp hâllerinin bildirildiği idare (md 4/1, 5/3)",
      "Teslim almakla sorumlu idare: akaryakıtı yakalama yerinde teslim alıp muhafaza eden il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı (md 5, 16/1)",
      "Kurum tanımı: Enerji Piyasası Düzenleme Kurumu, denetim yapan kurum (md 3/h, 4/1)"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU"], duzey=["TANIMA"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="YANLIŞ",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 4, 5",
cek="Numune Alma Tutanağı düzenlenir; bir adedi müdahil gümrük idaresine gider, sonuç tasfiyeyle ilgili kuruma bildirilir; numuneler gümrük idaresince saklanır.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre elkonulan kaçak akaryakıttan numune alınması ve numunelerin analizine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Numuneler, akaryakıtı muhafaza eden il özel idaresince saklanır.",
c=["Elkonulan kaçak akaryakıttan alınan numuneler için Numune Alma Tutanağı düzenlenir.",
   "Numunelerin bir adedi müdahil gümrük idaresine gönderilir.",
   "Analiz sonuçları, tasfiye ile ilgili kuruma bildirilir.",
   "Mahkemece yeniden analize sevki veya tedbir alınması istenmeyen numunelerin tasfiye edilmesi için mahkemesinden karar istenir."],
sirali=False,
g="Yönetmeliğe göre denetimler sonucunda veya kara, hava ve deniz hudut kapılarında elkonulan kaçak akaryakıttan alınan numuneler için Numune Alma Tutanağı düzenlenir; numunelerin bir adedi müdahil gümrük idaresine gönderilir ve analiz sonuçları tasfiye ile ilgili kuruma bildirilir. Numuneler gümrük idaresince saklanır; saklama süresince mahkemece yeniden analize sevki veya tedbir alınması istenmeyen numuneler için mahkemesinden tasfiye kararı istenir. Yanlış ifade saklama görevini gümrük idaresinden il özel idaresine kaydırmıştır. Tuzak komşu hükümdedir: il özel idaresi (bulunmayan yerlerde yatırım izleme ve koordinasyon başkanlığı) teslim edilen akaryakıtın kendisini analiz sonuçları gelinceye kadar saklamakla yükümlüdür; numuneleri saklayan ise gümrük idaresidir. Bu nedenle doğru cevap 'Numuneler, akaryakıtı muhafaza eden il özel idaresince saklanır.' seçeneğidir. (MD 4, 5)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Numuneler gümrük idaresince saklanır || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Numunelerin bir adedi müdahil gümrük idaresine gönderilir ve analiz sonuçları tasfiye ile ilgili kuruma bildirilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Numune Alma Tutanağı düzenlenir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | mahkemece yeniden analize sevki veya tedbir alınması istenmeyen numuneler için mahkemesinden numunelerin tasfiye edilmesi için karar istenir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | teslim edilen ürünleri analiz sonuçları gelinceye kadar",
yuva=["Numune Alma Tutanağının düzenlenmesi (md 4/1) — doğru",
      "Numunenin bir adedinin müdahil gümrük idaresine gönderilmesi (md 4/1) — doğru",
      "Analiz sonuçlarının tasfiye ile ilgili kuruma bildirilmesi (md 4/1) — doğru",
      "Numunelerin tasfiyesi için mahkemeden karar istenmesi (md 4/3) — doğru"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="YANLIŞ",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 5, 6",
cek="Kolluk akaryakıtı yakalama yerinde il özel idaresi/YİKOB'a teslim eder; LPG ikincil olarak lisanslı depoya; uygun yer yoksa yediemine; markersiz-uygun ürün ayrı saklanır.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre kaçak akaryakıtın teslimi ve muhafazasına ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Kaçak zannıyla ele geçirilen petrol ürünleri, bunları yakalayan kolluk gücü tarafından en yakın gümrük idaresine teslim edilir.",
c=["Depolama hazırlıkları tamamlanamadığı için il özel idaresine veya yatırım izleme ve koordinasyon başkanlığına teslim edilemeyen LPG, depolama lisanslı firmaların depolarında muhafaza edilir.",
   "Muhafaza için teslim edilecek uygun yer bulunamayan akaryakıt yediemine teslim edilir.",
   "Ulusal marker seviyesi yeterli bulunmayan ancak laboratuvar sonuçlarına göre teknik düzenlemelere uygun olduğu belirlenen akaryakıt, tasfiye kararı verilene kadar ayrı koşullarda saklanır.",
   "Ulusal marker kontrolü sonuçlarına itiraz edilmiş ve laboratuvar raporunda marker seviyesinin yeterli görüldüğü belirtilmişse ürün, sahibine teslim edilmek üzere ayrı şartlarda muhafaza edilir."],
sirali=False,
g="Yönetmeliğe göre kaçak zannıyla ele geçirilen petrol ürünleri, Kaçak Akaryakıt Tespit ve Elkoyma Tutanağı ile birlikte ele geçirilen mahallin bağlı olduğu il özel idaresine, il özel idaresi bulunmayan yerlerde yatırım izleme ve koordinasyon başkanlığına, yakalayan kolluk gücü tarafından yakalama yerinde teslim edilir; gümrük idaresine teslim söz konusu değildir. LPG'nin teslimi öncelikle il özel idaresine veya yatırım izleme ve koordinasyon başkanlığına yapılır; depolama hazırlıkları tamamlanamadığı için buralara teslim edilemeyen LPG, depolama lisanslı firmaların depolarında tutanak karşılığı muhafaza edilir. Teslim edilecek uygun yer bulunamayan akaryakıt yediemine teslim edilir. Ulusal marker seviyesi yeterli bulunmayan ancak laboratuvar sonuçlarına göre teknik düzenlemelere uygun olan ürünler tasfiye kararı verilene kadar ayrı koşullarda saklanır; marker kontrolüne itiraz edilip laboratuvar raporunda marker seviyesi yeterli bulunan ürün ise sahibine teslim edilmek üzere ayrı şartlarda muhafaza edilir. Yanlış ifade komşu rejimden taşınmıştır: kaçak zannıyla elkonulan eşyanın öncelikle en yakın gümrük idaresine teslimi, akaryakıt dışındaki eşya için Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliğinde öngörülen kuraldır; akaryakıtta ise gümrük idaresi yalnızca numunelerin bir adedinin gönderildiği müdahil idaredir. En güçlü çeldirici LPG'ye ilişkin ifadedir: lisanslı depolar LPG için yalnızca ikincil muhafaza yeridir ve ifade bu kaydı doğru biçimde taşır. Bu nedenle doğru cevap 'Kaçak zannıyla ele geçirilen petrol ürünleri, bunları yakalayan kolluk gücü tarafından en yakın gümrük idaresine teslim edilir.' seçeneğidir. (MD 4, 5, 6)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | kaçak akaryakıt ürünlerini yakalayan kolluk gücü tarafından yakalama yerinde teslim edilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | ele geçirilen mahallin bağlı olduğu il özel idareleri, il özel idaresi bulunmayan yerlerde yatırım izleme ve koordinasyon başkanlıklarına || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Depolama için hazırlıkların tamamlanamamasından dolayı bu yerlere teslimi mümkün olmayan LPG'nin muhafazası ise depolama lisanslı firmaların depolarına bu birimlerce tutanak karşılığı gerçekleştirilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | teslim edilecek uygun yer bulunamayan akaryakıt yediemine teslim edilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Ulusal marker seviyesi yeterli bulunmayan akaryakıt ürünlerinden laboratuvar sonuçlarına göre teknik düzenlemelere uygun olduğu belirlenenler, tasfiye kararı verilene kadar ayrı koşullarda saklanmaya devam edilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | ve laboratuvar raporunda ulusal marker seviyesinin yeterli görüldüğü belirtilmiş ise bu numunenin alındığı ürün, sahibine teslim edilmek üzere ayrı şartlarda muhafaza edilir || 5607_sayili_kacakcilikla_mucadele_kanununa_gore_elkonulan_esya_ve_alikonulan_tasitlara_iliskin_uygulama_yonetmeligi.txt | Kaçak zannı ile elkonulan eşya, alıkonulan taşıtlar ve numuneler öncelikle || 5607_sayili_kacakcilikla_mucadele_kanununa_gore_elkonulan_esya_ve_alikonulan_tasitlara_iliskin_uygulama_yonetmeligi.txt | gümrük idaresine, gümrük ve işletme müdürlüğünün aynı yerde bulunması halinde",
yuva=["LPG'nin ikincil olarak depolama lisanslı firmaların depolarında muhafazası (md 5/5) — doğru",
      "Uygun yer bulunamayan akaryakıtın yediemine teslimi (md 5/6) — doğru",
      "Marker seviyesi yetersiz ama teknik düzenlemelere uygun ürünün ayrı saklanması (md 6/3) — doğru",
      "Marker itirazında laboratuvarca yeterli bulunan ürünün sahibine teslim için ayrı muhafazası (md 6/2) — doğru"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "KOMŞU"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="YETKİ",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 5",
cek="İl özel idaresine teslimi mümkün olmayan, özel tesis gerektiren veya kapasiteyi aşan akaryakıt; büyükşehirler dahil ilçelerde kaymakam, illerde vali onayıyla başka depolara verilir.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre il özel idaresine veya yatırım izleme ve koordinasyon başkanlığına teslimi mümkün olmayan, muhafazası özel tesis ve tertibat gerektiren ya da bu idarelerin depolama kapasitesini aşan akaryakıtın, fiziki depoları uygun olan kamu kurum ve kuruluşları ile özel kişi ve kuruluşların depolarına teslimi aşağıdakilerden hangisinin onayı ile yapılır?"],
d="Büyükşehirler dahil ilçelerde kaymakamın, illerde valinin",
c=["Büyükşehirlerde valinin, diğer ilçelerde kaymakamın",
   "İl özel idarelerinde genel sekreterin, diğer yerlerde valinin",
   "İlgili davaya müdahil gümrük idaresinin",
   "Enerji Piyasası Düzenleme Kurumunun"],
sirali=False,
g="Yönetmeliğe göre il özel idaresine veya yatırım izleme ve koordinasyon başkanlığına teslimi mümkün olmayan, muhafazası özel tesis ve tertibat gerektiren ya da bu idarelerin depolama kapasitesini aşan akaryakıt; büyükşehirler dahil ilçelerde kaymakamın, illerde valinin onayı ile özellik ve miktarına göre fiziki depoları uygun olan kamu kurum ve kuruluşları ile özel kişi ve kuruluşların depolarına, il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı tarafından yakalandığı yerden teslim alınarak tutanakla teslim edilir. En güçlü çeldirici büyükşehirleri valiye bırakan seçenektir: metin ilçeleri 'büyükşehirler dahil' kaydıyla kaymakama bağlamıştır. Genel sekreter onayı tahsis kararlarına, müdahil gümrük idaresi ise muhafaza sırasında akaryakıtın bozulması veya yok olması hâllerinin bildirimine ilişkindir; Enerji Piyasası Düzenleme Kurumu ise Yönetmelik hazırlanırken görüşü alınan kurumdur. Bu nedenle doğru cevap 'Büyükşehirler dahil ilçelerde kaymakamın, illerde valinin' seçeneğidir. (MD 5, 16)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | büyükşehirler dahil ilçelerde kaymakam, illerde valinin onayı ile özellik ve miktarına göre fiziki depoları uygun olan kamu kurum ve kuruluşları ile özel kişi ve kuruluşların depolarına || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Tahsis kararları il özel idarelerinde genel sekreter, ya da görevlendireceği yardımcısı tarafından onaylanır || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | olayı tevsik eden resmi belgelerle birlikte ilgili davaya müdahil gümrük idaresine bildirilir",
yuva=["Aynı hükmün 'büyükşehirler dahil' kaydının tersine çevrilmesi (md 5/4)",
      "Tahsis kararlarının il özel idarelerinde genel sekreterce onaylanması (md 16/2)",
      "Muhafazada kayıp, hırsızlık, yangın gibi hâllerin bildirildiği müdahil gümrük idaresi (md 5/3)",
      "Yönetmeliğin hazırlanmasında görüşü alınan Kurum (md 22)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "UNSUR", "KOMŞU"], duzey=["HATIRLAMA", "AYIRT"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="SÜRE",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 7, 8",
cek="Muhafaza, depolama, yükleme, boşaltma ve nakliye masrafları elkonulduğu andan itibaren teslim almakla sorumlu il özel idaresi/YİKOB bütçesinden ödenir.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre elkonulan kaçak akaryakıtın muhafazası, depolanması, yüklenmesi, boşaltılması ve nakliyesi gibi nedenlerle yapılan masrafların hangi andan itibaren ve hangi bütçeden karşılanacağı aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Elkonulduğu andan itibaren – teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı bütçesinden",
c=["Muhafaza edileceği yere teslim edildiği tarihten itibaren – teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı bütçesinden",
   "Elkonulduğu andan itibaren – akaryakıta elkoyan idarenin bütçesinden",
   "Tasfiye kararının verildiği tarihten itibaren – teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı bütçesinden",
   "Elkonulduğu andan itibaren – ilgili davaya müdahil gümrük idaresinin bütçesinden"],
sirali=False,
g="Yönetmeliğe göre elkonulan kaçak akaryakıtın muhafazası, depolanması, yüklenmesi, boşaltılması ve nakliyesi gibi nedenlerle elkonulduğu andan itibaren yapılan masraflar, teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı bütçesinden ödenir; bu kapsamdaki her türlü mal, araç, gereç ve hizmet alımında 4734 sayılı Kamu İhale Kanunu uygulanmaz. Masrafların başlangıcı elkoyma anıdır. En güçlü çeldirici 'muhafaza edileceği yere teslim edildiği tarih'tir: bu an, muhafaza ücretinin hesaplandığı muhafaza süresinin başlangıcıdır; masraflar ise teslimden önceki yükleme ve nakliyeyi de kapsayacak biçimde elkoyma anından itibaren karşılanır. Elkoyan idare kaçakçılığı önleme, izleme ve araştırmakla görevli birimdir, masrafı ödemez; müdahil gümrük idaresi ise muhafaza sırasında akaryakıtın bozulması veya yok olması hâllerinin bildirildiği idaredir. Bu nedenle doğru cevap 'Elkonulduğu andan itibaren – teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı bütçesinden' seçeneğidir. (MD 7, 8)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Elkonulan kaçak akaryakıtın muhafazası, depolanması, yüklenmesi, boşaltılması ve nakliyesi gibi nedenlerle elkonulduğu andan itibaren yapılan masraflar, teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | bütçesinden ödenir. Bu kapsamda yapılacak her türlü mal, araç, gereç ve hizmet alımlarında || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Muhafaza edileceği yere teslim edildiği tarihten itibaren",
yuva=["Muhafaza süresinin başlangıcı: muhafaza edileceği yere teslim tarihi (md 8/1)",
      "Elkoyan/alıkoyan idare tanımı: kaçakçılığı önlemekle görevli birim, ödeme yapan değil (md 3/d)",
      "Tasfiye kararı: ayrı koşullarda saklamanın sona erdiği an (md 6/3-4)",
      "Bozulma, kayıp ve yok olma hâllerinin bildirildiği müdahil gümrük idaresi (md 5/3)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "MAKAM", "SAĞDUYU"], duzey=["AYIRT"], profil=[1, 3],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="A2: masrafların başlangıcı (elkoyma anı) ↔ muhafaza süresinin başlangıcı (teslim tarihi)", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="SÜRE",
z="Z",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 8",
cek="Muhafaza süresi teslim tarihinden başlar; iade kararında kararın sahibine tebliğini takip eden otuzuncu gün dahil, tasfiyede teslim alma tarihine kadar sürer.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre elkonulan kaçak akaryakıtın mahkemece sahibine iadesine karar verilmesi hâlinde, akaryakıtın muhafaza süresi aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Muhafaza edileceği yere teslim edildiği tarihten itibaren, kararın akaryakıt sahibine tebliğ edildiği tarihi takip eden otuzuncu gün dahil geçen süre",
c=["Elkonulduğu andan itibaren, kararın akaryakıt sahibine tebliğ edildiği tarihi takip eden otuzuncu gün dahil geçen süre",
   "Muhafaza edileceği yere teslim edildiği tarihten itibaren, kararın kesinleştiği tarihe kadar geçen süre",
   "Muhafaza edileceği yere teslim edildiği tarihten itibaren, akaryakıtın teslim alındığı tarihe kadar geçen süre",
   "Muhafaza edileceği yere teslim edildiği tarihten itibaren, kararın akaryakıt sahibine tebliğ edildiği tarihi takip eden on beşinci gün dahil geçen süre"],
sirali=False,
g="Yönetmeliğe göre kaçak akaryakıtın muhafaza süresi, akaryakıtın muhafaza edileceği yere teslim edildiği tarihten başlar. Mahkemece sahibine iadesine karar verilmesi hâlinde süre, kararın akaryakıt sahibine tebliğ edildiği tarihi takip eden otuzuncu gün dahil olmak üzere sona erer; akaryakıtın tasfiye edilmesi durumunda ise teslim alma tarihine kadar geçen süre muhafaza süresidir. En güçlü çeldirici 'elkonulduğu andan itibaren' başlayan seçenektir: elkoyma anı masrafların karşılanmaya başladığı andır, muhafaza süresi ise muhafaza yerine teslimle başlar. 'Teslim alındığı tarihe kadar' kaydı tasfiye hâline, 'kararın kesinleştiği tarih' ise satılan veya tahsis edilen akaryakıtın iadesinde kanuni faizin bitiş anına aittir; on beş gün tahsis edilen akaryakıtın teslim alınma süresidir. Bu nedenle doğru cevap 'Muhafaza edileceği yere teslim edildiği tarihten itibaren, kararın akaryakıt sahibine tebliğ edildiği tarihi takip eden otuzuncu gün dahil geçen süre' seçeneğidir. (MD 7, 8, 20)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Muhafaza edileceği yere teslim edildiği tarihten itibaren || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Mahkemece sahibine iadesine karar verilmesi halinde, kararın akaryakıt sahibine tebliğ edildiği tarihi takip eden otuzuncu gün dahil || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Akaryakıtın tasfiye edilmesi durumunda, teslim alma tarihine kadar || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | elkoyma tarihinden kararın kesinleştiği tarihe kadar geçen süre için kanuni faiz ilave edilerek",
yuva=["Masrafların başlangıcı: elkonulduğu an (md 7)",
      "Satılan/tahsis edilen akaryakıtın iadesinde kanuni faizin bitişi: kararın kesinleştiği tarih (md 20)",
      "Tasfiye hâlinde muhafaza süresinin bitişi: teslim alma tarihi (md 8/1-b)",
      "Tahsis edilen akaryakıtın teslim alınma süresi: on beş gün (md 16/5)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU", "YAKIN-SAYI"], duzey=["AYIRT"], profil=[1, 2],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="A2: masrafların başlangıcı (elkoyma anı) ↔ muhafaza süresinin başlangıcı (teslim tarihi)", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="ÖNERMELİ",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 8, 9",
cek="Muhafaza ücreti değer üzerinden günlük binde bir, altı aydan sonra yarısı; son gün hesaba katılmaz; ücret değerin yüzde otuzunu geçemez.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre kaçak akaryakıtın muhafaza ücretine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Muhafaza ücreti, kaçak akaryakıtın değeri üzerinden günlük binde bir olarak uygulanır.",
     "II. Altı aydan sonraki muhafaza süresi için, günlük binde bir olarak hesaplanan ücretin yarısı oranında ücret uygulanır.",
     "III. Ücret hesabında, kaçak akaryakıtın muhafazasının sona erdiği gün de dikkate alınır.",
     "IV. Muhafaza ücreti, kaçak akaryakıtın değerinin yüzde on beşini geçemez.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve II",
c=["I ve III", "II ve IV", "I, II ve III", "I, II ve IV"],
sirali=False,
g="Yönetmeliğe göre kaçak akaryakıtın muhafaza ücreti, kaçak akaryakıtın değeri üzerinden günlük binde bir olarak uygulanır (I doğru); altı aydan sonraki muhafaza süresi için bu ücretin yarısı oranında uygulanır (II doğru). Ücret hesabında kaçak akaryakıtın muhafazasının sona erdiği gün dikkate alınmaz (III yanlış). Muhafaza ücreti kaçak akaryakıtın değerinin yüzde otuzunu geçemez; yüzde on beş oranı ise satış suretiyle tasfiyede satış bedeli üzerinden muhafaza ücreti olarak esas alınan orandır (IV yanlış). En güçlü tuzak IV'tür: iki oran da muhafaza ücreti konusunda geçtiği için tavan oranı ile satıştaki oran karıştırılır. Bu nedenle doğru cevap 'I ve II' seçeneğidir. (MD 8, 9)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Kaçak akaryakıtın değeri üzerinden günlük binde bir olarak || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Altı aydan sonraki muhafaza süresi için (a) bendindeki ücretin yarısı oranında || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Ücret hesabında, kaçak akaryakıtın muhafazasının sona erdiği gün dikkate alınmaz || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Muhafaza ücreti, kaçak akaryakıtın değerinin yüzde otuzunu geçemez || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | satış bedelinin yüzde onbeşi muhafaza ücreti olarak esas alınır",
yuva=["I ve III: muhafazanın sona erdiği günün de hesaba katıldığını sanan, altı ay sonrası indirimi bilmeyen aday",
      "II ve IV: günlük oranı bilmeyip satıştaki yüzde on beşi (md 9/1) tavan sanan aday",
      "I, II ve III: son günün hesaba katılmadığı kaydını tersine okuyan aday",
      "I, II ve IV: yüzde otuz tavanı (md 8/4) satıştaki yüzde on beş oranıyla (md 9/1) karıştıran aday"],
yakinlik="BİREBİR",
tuzak=["SAYI", "TERSİNE", "KOMŞU"], duzey=["HATIRLAMA", "AYIRT"], profil=[2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="HESAP",
z="Z",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 3, 8, 9",
cek="Satış suretiyle tasfiyede muhafaza ücreti satış bedelinin yüzde on beşidir; tutar akaryakıt değerinin yüzde otuzunu hiçbir şekilde geçemez.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği kapsamında elkonulan kaçak akaryakıta ilişkin bilgiler şöyledir:",
     "- Akaryakıt ithal eşyasıdır ve CIF kıymeti 100.000 TL'dir.",
     "- Akaryakıt, valinin onayıyla fiziki deposu uygun bir özel kuruluşun deposuna teslim edilmiş ve tasfiyesine kadar bu depoda muhafaza edilmiştir.",
     "- Akaryakıt, on ay muhafaza edildikten sonra satış suretiyle tasfiye edilmiş ve 80.000 TL'ye satılmıştır.",
     "Buna göre depoyu işleten kuruluşa muhafaza ücreti olarak ödenecek tutar kaç TL'dir?"],
d="12.000 TL",
c=["6.000 TL", "15.000 TL", "24.000 TL", "30.000 TL"],
sirali=True,
siklar=["6.000 TL", "12.000 TL", "15.000 TL", "24.000 TL", "30.000 TL"],
g="Yönetmeliğe göre akaryakıtın satış suretiyle tasfiyesi hâlinde satış bedelinin yüzde on beşi muhafaza ücreti olarak esas alınır ve il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı bütçesinden ödenir; bu tutar hiçbir şekilde kaçak akaryakıtın değerinin yüzde otuzu olan azami haddi geçemez. Kaçak akaryakıtın değeri, ithal eşyasında CIF kıymetidir. Olayda satış bedeli 80.000 TL olduğundan ücret 80.000 × %15 = 12.000 TL'dir; azami had 100.000 × %30 = 30.000 TL olduğundan sınır aşılmamıştır. Vakadaki saklı nokta satıştır: günlük binde bir ve altı aydan sonra yarı oran kuralı satış hâlinde uygulanmaz. 30.000 TL tavanın kendisini, 24.000 TL tavan oranının satış bedeline uygulanmasını, 15.000 TL yüzde on beşin satış bedeli yerine CIF kıymetine uygulanmasını, 6.000 TL ise altı ay sonrası yarı oran kuralının satıştaki ücrete yanlış uygulanmasını gösterir. Bu nedenle doğru cevap '12.000 TL' seçeneğidir. (MD 3, 8, 9)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Akaryakıtın satış suretiyle tasfiyesi halinde, satış bedelinin yüzde onbeşi muhafaza ücreti olarak esas alınır || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Ödenecek bu tutar hiçbir şekilde 8 inci maddenin dördüncü fıkrasındaki azami haddi geçemez || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Muhafaza ücreti, kaçak akaryakıtın değerinin yüzde otuzunu geçemez || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | ithal eşyası olması halinde CIF kıymetini",
yuva=["6.000: altı aydan sonraki muhafaza süresi için ücretin yarısı oranı (md 8/2-b) satıştaki ücrete yanlış uygulanmış",
      "15.000: yüzde on beş oranı (md 9/1) satış bedeli yerine kaçak akaryakıtın değerine, CIF kıymetine (md 3/ğ) uygulanmış",
      "24.000: yüzde otuz tavan oranı (md 8/4) satış bedeline uygulanmış",
      "30.000: muhafaza ücretinin azami haddi, değerin yüzde otuzu (md 8/4)"],
yakinlik="ÇIKARIM",
tuzak=["AD-HESAP", "İSTİSNA", "KOMŞU"], duzey=["UYGULAMA"], profil=[2],
olumsuz=False, vaka=True, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="KAPSAM_DIŞI",
z="Z",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 10, 11",
cek="Piyasa araştırmasız alım: tek kişinin karşılayabileceğinin en az üç kişilik komisyonca tespiti, özel hak belgesi, kamu kurumu ya da çoğunluğu kamuya ait kuruluştan alım.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre elkonulan kaçak akaryakıt için yapılacak mal ve hizmet alımlarında, piyasa fiyat araştırması yapılmadan alım yapılabilecek durumlar arasında aşağıdakilerden hangisi yer almaz?"],
d="Alınacak mal veya hizmetin fiyatının il veya ilçede faaliyet gösteren kamu kurumu niteliğindeki meslek kuruluşunun tarifesinde belirlenmiş olması",
c=["İhtiyacın yalnızca gerçek veya tüzel tek kişi tarafından karşılanabileceğinin, ihtiyaç sahibi birim amirince oluşturulan en az üç kişilik komisyonca tespit edilmesi",
   "Yalnızca gerçek veya tüzel tek kişinin özel bir hakka sahip olduğunun belgelenmesi",
   "Alımın kamu kurum ve kuruluşlarından yapılması",
   "Alımın sermayesinin yarısından fazlası kamuya ait bulunan kuruluşlardan yapılması"],
sirali=False,
g="Yönetmeliğe göre mal ve hizmet alımı üç durumda piyasa fiyat araştırması yapılmadan gerçekleştirilebilir: ihtiyacın sadece gerçek veya tüzel tek kişi tarafından karşılanabileceğinin ihtiyaç sahibi birim amirince oluşturulacak en az üç kişilik bir komisyonca tespit edilmesi; sadece gerçek veya tüzel tek kişinin özel bir hakka sahip olduğunun belgelenmesi; alımın kamu kurum ve kuruluşları, sermayesinin yarısından fazlası kamuya ait kuruluşlar veya özel kanunlarla kurulup kamu görevi verilmiş tüzel kişiliği haiz kuruluşlardan yapılması. Kamu kurumu niteliğindeki meslek kuruluşlarının tarifeleri ise piyasa araştırmasını kaldıran bir hâl değildir: nakliye, yükleme ve boşaltma masrafları için düzenlenen Piyasa Fiyat Araştırması Tutanağı bu tarifeler dikkate alınarak, yoksa piyasadan fiyat araştırması yapılarak hazırlanır. Tuzak, tutanağın hazırlanma yöntemini araştırmadan muafiyet sanmaktır. Bu nedenle doğru cevap 'Alınacak mal veya hizmetin fiyatının il veya ilçede faaliyet gösteren kamu kurumu niteliğindeki meslek kuruluşunun tarifesinde belirlenmiş olması' seçeneğidir. (MD 10, 11)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | piyasa fiyat araştırması yapılmadan bu yerlerden gerçekleştirilebilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | İhtiyacın sadece gerçek veya tüzel tek kişi tarafından karşılanabileceğinin ihtiyaç sahibi birim amiri tarafından oluşturulacak en az üç kişilik bir komisyon tarafından tespit edilmesi || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Sadece gerçek veya tüzel tek kişinin özel bir hakka sahip olduğunun belgelenmesi || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Kamu kurum ve kuruluşları ile sermayesinin yarısından fazlası kamuya ait bulunan kuruluşlardan || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | il veya ilçelerde faaliyet gösteren kamu kurumu veya kamu kurumu niteliğine haiz meslek kuruluşları tarifeleri dikkate alınarak, yoksa piyasadan fiyat araştırması yapılarak düzenlenir",
yuva=["Listede: tek kişi tarafından karşılanabilirliğin en az üç kişilik komisyonca tespiti (md 11/a)",
      "Listede: tek kişinin özel hakkının belgelenmesi (md 11/b)",
      "Listede: kamu kurum ve kuruluşlarından alım (md 11/c)",
      "Listede: sermayesinin yarısından fazlası kamuya ait kuruluşlardan alım (md 11/c)"],
yakinlik="PARAFRAZ",
tuzak=["LİSTE-DIŞI", "SAĞDUYU", "KOMŞU"], duzey=["AYIRT"], profil=[3, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="KAPSAM_DIŞI",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 14",
cek="Mücadele alımlarında 4734 uygulanmaz: Ticaret ve İçişleri Bakanlıklarının merkez-taşra teşkilatı, EPDK ve il özel idareleri; Hazine ve Maliye 2024'te çıkarıldı.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre akaryakıt kaçakçılığı ile mücadele konusunda yapılacak her türlü mal, araç, gereç ve hizmet alımlarında, 4734 sayılı Kanun hükümleri uygulanmadan giderleri ilgili kurum bütçesinden karşılanan kurum ve kuruluşlar arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="Hazine ve Maliye Bakanlığının taşra teşkilatı",
c=["Ticaret Bakanlığının taşra teşkilatı",
   "İçişleri Bakanlığının merkez teşkilatı",
   "Enerji Piyasası Düzenleme Kurumu",
   "İl özel idareleri"],
sirali=False,
g="Yönetmeliğe göre akaryakıt kaçakçılığı ile mücadele konusunda Ticaret Bakanlığı ve İçişleri Bakanlığının merkez ve taşra teşkilatları, Enerji Piyasası Düzenleme Kurumu ve il özel idareleri tarafından yapılacak her türlü mal, araç, gereç ve hizmet alımları 4734 sayılı Kanun hükümleri uygulanmadan ilgili kurum bütçesinden karşılanır. Hazine ve Maliye Bakanlığı bu sayımdan 18.01.2024 tarihli ve 32433 sayılı Resmî Gazete'de yayımlanan değişiklikle çıkarılmıştır; eski metinden çalışan aday bu seçeneği listede sanır. Aynı değişiklikle Yönetmelikteki defterdarlıkların yerini de yatırım izleme ve koordinasyon başkanlıkları almıştır. Bu nedenle doğru cevap 'Hazine ve Maliye Bakanlığının taşra teşkilatı' seçeneğidir. (MD 14)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | akaryakıt kaçakçılığı ile mücadele konusunda Ticaret Bakanlığı ve İçişleri Bakanlığının || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | merkez ve taşra teşkilatları, Enerji Piyasası Düzenleme Kurumu ve il özel idareleri tarafından yapılacak her türlü mal, araç, gereç ve hizmet alımlarında || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | ibaresi \"Ticaret Bakanlığı ve İçişleri Bakanlığının\" olarak 18.01.2024 / 32433 sayılı R.G. ile değiştirilmiştir",
yuva=["Listede: Ticaret Bakanlığının merkez ve taşra teşkilatları",
      "Listede: İçişleri Bakanlığının merkez ve taşra teşkilatları",
      "Listede: Enerji Piyasası Düzenleme Kurumu",
      "Listede: il özel idareleri"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "SAĞDUYU"], duzey=["HATIRLAMA"], profil=[3, 5],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="18.01.2024 / 32433 R.G.", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="YANLIŞ",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 16",
cek="Tahsis komisyonu en az üç kişi; kararı genel sekreter onaylar; tahsis edilen akaryakıt on beş günde teslim alınmazsa karar iptal edilmiş sayılır.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre elkonulan kaçak akaryakıtın bedelsiz tahsisine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Tahsisi yapılan akaryakıt, muhafaza edildiği yerden tahsis yapılan birim tarafından otuz gün içerisinde teslim alınır.",
c=["Tahsis komisyonu, akaryakıtı teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığınca en az üç kişiden oluşturulur.",
   "Kamu kurum ve kuruluşları ile mahalli idareler, akaryakıtın cinsi ve miktarını belirterek bedelsiz tahsis talebinde bulunur.",
   "Tahsis kararları il özel idarelerinde genel sekreter ya da görevlendireceği yardımcısı tarafından onaylanır.",
   "Süresi içinde teslim alınmayan akaryakıta ilişkin tahsis kararı iptal edilmiş sayılır ve başka birime tahsis yapılır."],
sirali=False,
g="Yönetmeliğe göre tahsisi yapılan akaryakıt, muhafaza edildiği yerden tahsis yapılan birim tarafından on beş gün içerisinde teslim alınır; bu süre içinde teslim alınmayan akaryakıta ilişkin tahsis kararı iptal edilmiş sayılır ve başka birime tahsis yapılır. Yanlış ifade süreyi otuz güne çıkarmıştır; otuzuncu gün, mahkemece iade kararı verildiğinde muhafaza süresinin sona erdiği günü belirleyen sayıdır. Tahsis komisyonu teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığınca en az üç kişiden oluşturulur; kamu kurum ve kuruluşları ile mahalli idareler akaryakıtın cinsi ve miktarını belirterek bedelsiz tahsis talebinde bulunur; tahsis kararları il özel idarelerinde genel sekreter ya da görevlendireceği yardımcısı tarafından onaylanır. Bu nedenle doğru cevap 'Tahsisi yapılan akaryakıt, muhafaza edildiği yerden tahsis yapılan birim tarafından otuz gün içerisinde teslim alınır.' seçeneğidir. (MD 8, 16)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Tahsisi yapılan akaryakıt muhafaza edildiği yerden, tahsis yapılan birim tarafından onbeş gün içerisinde teslim alınır || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Bu süre içerisinde teslim alınmayan akaryakıta ilişkin tahsis kararı iptal edilmiş sayılır ve başka birime tahsisi yapılır || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | en az üç kişiden oluşan tahsis komisyonu oluşturulur || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | akaryakıtın cinsi ve miktarını belirterek bedelsiz tahsis talebinde bulunurlar || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Tahsis kararları il özel idarelerinde genel sekreter, ya da görevlendireceği yardımcısı tarafından onaylanır",
yuva=["Tahsis komisyonunun en az üç kişiden oluşturulması (md 16/1) — doğru",
      "Kamu kurumları ve mahalli idarelerin cins ve miktar belirterek talepte bulunması (md 16/1) — doğru",
      "Tahsis kararlarının genel sekreter ya da yardımcısınca onaylanması (md 16/2) — doğru",
      "Süresinde teslim alınmayan akaryakıtta tahsis kararının iptal edilmiş sayılması (md 16/5) — doğru"],
yakinlik="BİREBİR",
tuzak=["SAYI", "YAKIN-SAYI", "KOMŞU"], duzey=["HATIRLAMA"], profil=[2, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="SONUÇ",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 16",
cek="Genel tahsis önceliği kaçakçılıkla mücadele eden birimlerdir; ancak hudut kapılarında elkonulan kaçak akaryakıt gümrük idarelerine bedelsiz tahsis edilir.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre kara, hava ve deniz hudut kapılarında elkonulan kaçak akaryakıt, aşağıdakilerden hangisine bedelsiz tahsis edilerek tasfiye edilir?"],
d="Gümrük idarelerine",
c=["Akaryakıt kaçakçılığı ile mücadele eden kurum veya birimlere",
   "Akaryakıtın muhafaza edildiği yerdeki kamu kurum ve kuruluşlarına",
   "Akaryakıtın muhafaza edildiği il dışındaki kamu kurum ve kuruluşlarına",
   "Akaryakıtı teslim almakla sorumlu il özel idaresine"],
sirali=False,
g="Yönetmeliğe göre elkonulan kaçak akaryakıt kural olarak öncelik sırasına göre akaryakıt kaçakçılığı ile mücadele eden kurum veya birimlere, akaryakıtın muhafaza edildiği yerdeki kamu kurum ve kuruluşlarına veya mahalli idarelere, son olarak il dışındaki diğer kamu kurum ve kuruluşları ile mahalli idarelere kullanım amacıyla bedelsiz tahsis edilir. Ancak kara, hava ve deniz hudut kapılarında elkonulan kaçak akaryakıt gümrük idarelerine bedelsiz tahsis edilerek tasfiye edilir; ihtiyaç fazlası olursa kamu kurum ve kuruluşları ile mahalli idarelerin kullanımına tahsis edilir. Sorudaki tuzak genel öncelik sırasıdır: bu sıranın başında akaryakıt kaçakçılığı ile mücadele eden kurum veya birimler bulunur, hudut kapısında elkoyma ise bu sıranın istisnasıdır. Muhafaza edildiği yerdeki ve il dışındaki kamu kurum ve kuruluşları genel sıranın ikinci ve üçüncü basamaklarıdır; il özel idaresi ise akaryakıtı teslim alan ve tahsis komisyonunu oluşturan idaredir, tahsisten yararlanan değildir. Bu nedenle doğru cevap 'Gümrük idarelerine' seçeneğidir. (MD 16)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Kara, hava ve deniz hudut kapılarında elkonulan kaçak akaryakıt, gümrük idarelerine bedelsiz tahsis edilerek tasfiye edilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Akaryakıt kaçakçılığı ile mücadele eden kurum veya birimlere || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Akaryakıtın muhafaza edildiği yerdeki kamu kurum ve kuruluşlarına veya mahalli idarelere || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Akaryakıtın muhafaza edildiği il dışındaki diğer kamu kurum ve kuruluşları ile mahalli idarelere || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | oluşan tahsis komisyonu oluşturulur",
yuva=["Genel öncelik sırasında birinci sıra (md 16/3-a)",
      "Genel öncelik sırasında ikinci sıra (md 16/3-b)",
      "Genel öncelik sırasında üçüncü sıra (md 16/3-c)",
      "Tahsis komisyonunu oluşturan, akaryakıtı teslim almakla sorumlu idare (md 16/1)"],
yakinlik="BİREBİR",
tuzak=["İSTİSNA", "KOMŞU"], duzey=["AYIRT"], profil=[1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="ORAN-TUTAR",
z="Z",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 17",
cek="Akaryakıta dönüştürülmek için bulundurulan petrol türevlerinde tahmini satış bedeli: dönüştürülmemişte piyasa değerinin %65'i, dönüştürülmüşte orijinal hâlin %40'ı.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre akaryakıta dönüştürülmek maksadıyla kullanılan veya bulundurulan madenî ve baz yağ, asfalt, solvent, nafta ve benzeri petrol türevlerinden dönüştürme işlemi yapılmış olanların satış suretiyle tasfiyesinde tahmini satış bedeli, dönüştürülmeden önceki orijinal hâlinin piyasa değerinin yüzde kaçından aşağı belirlenemez?"],
d="%40",
c=["%15", "%30", "%60", "%65"],
sirali=True,
siklar=["%15", "%30", "%40", "%60", "%65"],
g="Yönetmeliğe göre akaryakıta dönüştürülmek maksadıyla kullanılan veya bulundurulan madenî ve baz yağ, asfalt, solvent, nafta ve benzeri petrol türevleri de akaryakıt niteliğindeki ürünlerle aynı usulle satılır; ancak bunların ihalesine yalnızca benzeri ürünlerin ithali için Kurumdan alınan uygunluk belgesi sahipleri katılabilir. Bu ürünlerin tahmini satış bedeli, dönüştürülmemiş olanlarda ihale ilan tarihindeki benzerlerinin piyasa değerinin yüzde altmış beşinden, dönüştürme işlemi yapılmış olanlarda ise dönüştürülmeden önceki orijinal hâlinin piyasa değerinin yüzde kırkından aşağı belirlenemez. En güçlü çeldirici aynı cümledeki yüzde altmış beştir; bu oran dönüştürülmemiş ürünlere aittir. Yüzde altmış teknik düzenlemelere uygun olmayan diğer ürünlerin rafinericiye satış bedeline, yüzde otuz muhafaza ücretinin azami haddine, yüzde on beş satış suretiyle tasfiyedeki muhafaza ücretine aittir. Bu nedenle doğru cevap '%40' seçeneğidir. (MD 8, 9, 17, 18)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | dönüştürme işlemi yapılmışlarda ise dönüştürülmeden önceki orijinal halinin piyasa değerinin yüzde kırkından aşağı belirlenemez || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | dönüştürülmemiş ürünlerde ihale ilan tarihindeki benzerlerinin piyasa değerinin yüzde altmış beşinden || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | diğer ürünlerde ise yüzde altmışından az olamaz || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Ancak, bunların satış ihalesine sadece benzeri ürünlerin ithali için Kurumdan alınan uygunluk belgesi sahipleri katılabilir",
yuva=["%15: satış suretiyle tasfiyede muhafaza ücreti oranı (md 9/1)",
      "%30: muhafaza ücretinin azami haddi (md 8/4)",
      "%60: teknik düzenlemelere uygun olmayan diğer ürünlerin rafinericiye satış bedeli alt sınırı (md 18/1)",
      "%65: dönüştürülmemiş ürünlerde tahmini satış bedeli alt sınırı (aynı cümle)"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "KOMŞU"], duzey=["HATIRLAMA", "AYIRT"], profil=[2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="SÜRE",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 17",
cek="Teknik düzenlemelere uygun akaryakıtın tasfiye ihalesi, numune analiz raporunun laboratuvardan geldiği tarihten başlayarak bir ay içerisinde gerçekleştirilir.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre numune analiz sonuçları teknik düzenlemelere uygun çıkan ve bedelsiz tahsis edilemeyen kaçak akaryakıtın satış suretiyle tasfiyesinde, tasfiye ihalesinin gerçekleştirilme süresi aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Numune analiz raporunun laboratuvardan geldiği tarihten başlayarak bir ay içerisinde",
c=["Tasfiye kararının verildiği tarihten başlayarak bir ay içerisinde",
   "Numune analiz raporunun laboratuvardan geldiği tarihten başlayarak on beş gün içerisinde",
   "İhale ilanına çıkıldığı tarihten başlayarak bir ay içerisinde",
   "Akaryakıtın muhafaza edileceği yere teslim edildiği tarihten başlayarak altı ay içerisinde"],
sirali=False,
g="Yönetmeliğe göre numune analiz sonuçları teknik düzenlemelere uygun çıkan ve bedelsiz tahsis edilemeyen akaryakıt niteliğindeki ürünlerin tasfiyesi, il özel idaresince veya yatırım izleme ve koordinasyon başkanlığınca 2886 sayılı Devlet İhale Kanununun açık teklif ve pazarlık usulü emsal alınarak yapılır ve tasfiye ihalesi numune analiz raporunun laboratuvardan geldiği tarihten başlayarak bir ay içerisinde gerçekleştirilir. En güçlü çeldirici 'tasfiye kararının verildiği tarih'tir: süre karar tarihinden değil, analiz raporunun laboratuvardan geldiği tarihten başlar. İhale ilan tarihi tahmini satış bedelinin hesaplandığı tarihtir; on beş gün tahsis edilen akaryakıtın teslim alınma süresi, altı ay ise muhafaza ücretinin yarı orana indiği eşiktir. Bu nedenle doğru cevap 'Numune analiz raporunun laboratuvardan geldiği tarihten başlayarak bir ay içerisinde' seçeneğidir. (MD 8, 16, 17)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Tasfiye ihalesi, numune analiz raporunun laboratuvardan geldiği tarihten başlayarak bir ay içerisinde gerçekleştirilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | 2886 sayılı Devlet İhale Kanununun açık teklif ve pazarlık usulünü düzenleyen || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Tahmini satış bedeli, ilana çıkıldığı tarihteki benzeri ürünlerin rafineri çıkış bedelinden",
yuva=["Tasfiye kararı: ayrı koşullarda saklamanın sona erdiği an (md 6/3-4)",
      "On beş gün: tahsis edilen akaryakıtın teslim alınma süresi (md 16/5)",
      "İlan tarihi: tahmini satış bedelinin belirlendiği tarih (md 17/1-a)",
      "Altı ay: muhafaza ücretinin yarı orana indiği eşik; teslim tarihi muhafaza süresinin başlangıcı (md 8)"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "YAKIN-SAYI", "KOMŞU"], duzey=["AYIRT"], profil=[1, 2],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="A1: teknik düzenlemeye uygun akaryakıtın satış ihalesi ↔ uygun olmayan akaryakıtın rafinericiye satışı", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="ÖNERMELİ",
z="Z",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 18",
cek="Uygun olmayan akaryakıt en yakın rafinericiye satılır; analiz akredite laboratuvarda, gideri rafinericide; sahipsiz markersiz ürün analizsiz aykırı sayılır; zararlı ürün bertarafa gider.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre numune analiz sonuçları teknik düzenlemelere uygun olmayan kaçak akaryakıtın tasfiyesine ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Bu akaryakıt, il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı tarafından en yakın rafinericiye satılır ve rafinerici bu ürünleri almakla yükümlüdür.",
     "II. Rafineri üretim süreçlerine zarar verip vermeyeceğinin tespitine yönelik analizleri gerçekleştirecek laboratuvarın akreditasyon sertifikasına sahip olması gerekir; analiz giderleri rafinericiler tarafından karşılanır.",
     "III. Sahipsiz olarak yakalanan kaçak akaryakıtın ulusal marker saha ölçüm sonucu Enerji Piyasası Düzenleme Kurumu tarafından belirlenen şart ve seviyede değilse, ürün analizi yapılmaksızın teknik düzenlemelere aykırı kabul edilir.",
     "IV. Rafineri üretim süreçlerine zarar vereceği kanıtlanan kaçak akaryakıt, bertaraf ettirilmek üzere il özel idarelerine veya çevre ve şehircilik il müdürlüklerine gönderilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, II, III ve IV",
c=["I ve III", "II ve IV", "I, II ve III", "I, III ve IV"],
sirali=False,
g="Yönetmeliğe göre numune analiz sonuçları teknik düzenlemelere uygun olmayan kaçak akaryakıt, il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı tarafından en yakın rafinericiye satılır, numune analiz raporu ile birlikte teslim edilir ve rafinerici bu ürünleri almakla yükümlüdür (I doğru). Rafinericiler akaryakıtın belirlenen kriterlerin üzerinde yabancı madde içerip içermediğini ve üretim süreçlerine zarar verip vermeyeceğini uluslararası kabul görmüş deney yöntemlerine göre yapar veya yaptırır; bu analizleri yapacak laboratuvarın akreditasyon sertifikasına sahip olması gerekir ve analiz giderleri rafinericiler tarafından karşılanır (II doğru). Sahipsiz olarak yakalanan kaçak akaryakıtın ulusal marker saha ölçüm sonucu Kurumca belirlenen şart ve seviyede değilse ürün analizi yapılmaksızın teknik düzenlemelere aykırı kabul edilir ve en yakın rafinericiye satılarak tasfiye edilir (III doğru). Üretim süreçlerine zarar vereceği kanıtlanan akaryakıt ise atık yakma ve beraber yakma tesislerinde bertaraf ettirilmek üzere il özel idarelerine veya çevre ve şehircilik il müdürlüklerine gönderilir (IV doğru). II ve IV'teki hükümler 28.02.2020 tarihli değişiklikle eklenmiştir; analiz giderlerini idarenin karşıladığını sanan aday II'yi eler. Bu nedenle doğru cevap 'I, II, III ve IV' seçeneğidir. (MD 18)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | tarafından en yakın rafinericiye satılır. Bu kapsamdaki kaçak akaryakıt, numune analiz raporu ile birlikte rafinericiye teslim edilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Rafinerici, bu ürünleri almakla yükümlüdür || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Bu analizleri gerçekleştirecek laboratuarların akreditasyon sertifikasına sahip laboratuvar olması gerekir. Analiz giderleri rafinericiler tarafından karşılanır || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | bahse konu ürünler analizi yapılmaksızın teknik düzenlemelere aykırı kabul edilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | bertaraf ettirilmek üzere il özel idarelerine veya çevre ve şehircilik il müdürlüklerine gönderilir",
yuva=["I ve III: 2020'de eklenen analiz gideri ve bertaraf hükümlerini (md 18/4-5) bilmeyen aday",
      "II ve IV: rafinericinin alım yükümlülüğünü ve sahipsiz akaryakıtta analizsiz kabulü bilmeyen aday",
      "I, II ve III: zarar verecek akaryakıtın gönderileceği idareleri (md 18/5) bilmeyen aday",
      "I, III ve IV: analiz giderlerinin idarece karşılandığını sanan (sağduyu) aday"],
yakinlik="BİREBİR",
tuzak=["SAĞDUYU", "KOMŞU"], duzey=["HATIRLAMA", "AYIRT"], profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="A1: teknik düzenlemeye uygun akaryakıtın satış ihalesi ↔ uygun olmayan akaryakıtın rafinericiye satışı", guncellik="", cikmis="", kapsamli=True,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="YANLIŞ",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 4, 17, 19",
cek="Gümrüğe terk edilen akaryakıttan kural olarak numune alınmaz; uygun olanlar önce gümrük idarelerine tahsis edilir, tahsis edilemeyen Tasfiye Yönetmeliğine göre tasfiye edilir.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre 4458 sayılı Gümrük Kanunu uyarınca gümrüğe terk edilen veya gümrük mevzuatına göre terk edilmiş sayılan akaryakıta ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Teknik düzenlemelere uygun olup bedelsiz tahsis edilemeyen akaryakıt, 2886 sayılı Devlet İhale Kanununun açık teklif ve pazarlık usulü emsal alınarak satılır.",
c=["Bu akaryakıt için kural olarak numune alınmaz.",
   "Niteliğinden şüphe duyulan akaryakıtın cinsinin tespiti için Türk Standartları Enstitüsünün ilgili standartlarına göre numune alınarak analiz yaptırılabilir.",
   "Teknik düzenlemelere uygun olanlar ilk olarak gümrük idarelerinin kullanımına bedelsiz tahsis edilir.",
   "Gümrük idarelerinin ihtiyacını aşan kısım, kamu kurum ve kuruluşları ile mahalli idarelerin kullanımına bedelsiz tahsis edilir."],
sirali=False,
g="Yönetmeliğe göre gümrüğe terk edilen veya terk edilmiş sayılan akaryakıt için numune alınmaz; ancak niteliğinden şüphe duyulan akaryakıtın cinsinin tespiti için Türk Standartları Enstitüsü tarafından belirlenen ilgili standartlara göre numune alınarak analiz yaptırılabilir. Bu akaryakıttan teknik düzenlemelere uygun olanlar öncelikle gümrük idarelerinin kullanımına, ihtiyaç fazlası ise kamu kurum ve kuruluşları ile mahalli idarelerin kullanımına bedelsiz tahsis edilir. Bu şekilde tahsis edilemeyen akaryakıt Tasfiye Yönetmeliği hükümlerine göre tasfiye edilir. Yanlış ifadedeki 2886 sayılı Devlet İhale Kanununun emsal alınması, elkonulan kaçak akaryakıttan tahsis edilemeyenlerin satış suretiyle tasfiyesine ilişkin komşu hükümdür; gümrüğe terk edilen akaryakıta uygulanmaz. Bu nedenle doğru cevap 'Teknik düzenlemelere uygun olup bedelsiz tahsis edilemeyen akaryakıt, 2886 sayılı Devlet İhale Kanununun açık teklif ve pazarlık usulü emsal alınarak satılır.' seçeneğidir. (MD 4, 17, 19)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Gümrüğe terk edilen veya terk edilmiş sayılan akaryakıt için numune alınmaz || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | niteliğinden şüphe duyulan akaryakıtın cinsinin tespiti için Türk Standartları Enstitüsü tarafından belirlenen ilgili standartlarda belirtildiği şekilde numune alınarak analiz yaptırılabilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | teknik düzenlemelere uygun olanlar öncelikle gümrük idarelerinin kullanımına, ihtiyaç fazlası akaryakıt ise kamu kurum ve kuruluşları ile mahalli idarelerin kullanımına bedelsiz tahsis edilir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | uyarınca tahsis edilemeyen akaryakıt ise || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Tasfiye Yönetmeliği hükümlerine göre tasfiye edilir",
yuva=["Terk edilen akaryakıtta numune alınmaması (md 4/2) — doğru",
      "Şüphe hâlinde TSE standartlarına göre numune alınıp analiz yaptırılması (md 4/2) — doğru",
      "Öncelikle gümrük idarelerinin kullanımına bedelsiz tahsis (md 19/1) — doğru",
      "İhtiyaç fazlasının kamu kurumları ve mahalli idarelere bedelsiz tahsisi (md 19/1) — doğru"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "TERSİNE"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="SONUÇ",
z="Z",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 20",
cek="Tahsis edilmiş akaryakıtın iadesinde rafinericiye satış bedeli esaslı tutardan vergiler düşülür; elkoymadan kararın kesinleşmesine kadar kanuni faiz eklenir.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre bedelsiz tahsis edilmiş akaryakıta ilişkin yargılamanın sonucunda sahibine iadesine karar verilmesi hâlinde, hak sahibine yapılacak ödemenin hesaplanmasına ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Rafinericiye satış bedeli üzerinden hesaplanacak bedelden vergiler düşülür; kalan tutara elkoyma tarihinden kararın kesinleştiği tarihe kadar kanuni faiz eklenir.",
c=["Toplam satış bedelinden vergiler düşülür; kalan tutara elkoyma tarihinden kararın kesinleştiği tarihe kadar kanuni faiz eklenir.",
   "Rafinericiye satış bedeli üzerinden hesaplanacak bedelden vergiler düşülür; kalan tutara tahsis tarihinden kararın kesinleştiği tarihe kadar kanuni faiz eklenir.",
   "Rafinericiye satış bedeli üzerinden hesaplanacak bedelden vergiler düşülür; kalan tutara elkoyma tarihinden kararın sahibine tebliğ edildiği tarihe kadar kanuni faiz eklenir.",
   "Akaryakıtın CIF kıymetinden vergiler düşülür; kalan tutara elkoyma tarihinden kararın kesinleştiği tarihe kadar kanuni faiz eklenir."],
sirali=False,
g="Yönetmeliğe göre tahsis edilmiş akaryakıta ilişkin yargılamanın sonucunda sahibine iadesine karar verilmesi hâlinde; benzin, motorin türleri, gaz yağı, jet yakıtı ile nafta ve solvent türlerinde rafineride bir önceki ay sonunda oluşan ham petrol/devir maliyet fiyatından, diğer ürünlerde ise yüzde altmışından az olmayan rafinericiye satış bedeli üzerinden hesaplanacak bedelden vergiler düşülür; kalan tutar, elkoyma tarihinden kararın kesinleştiği tarihe kadar geçen süre için kanuni faiz eklenerek ilgili il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı bütçesinden hak sahibine ödenir. Sorudaki tuzak akaryakıtın satılmamış, tahsis edilmiş olmasıdır: toplam satış bedelinden vergilerin düşülmesi, satılarak bedeli bütçeye gelir kaydedilen akaryakıtın iadesine ilişkin komşu hükümdür. Faiz tahsis veya tebliğ tarihine göre değil, elkoyma tarihinden kararın kesinleştiği tarihe kadar işletilir; kararın sahibine tebliği iade kararında muhafaza süresinin bitişine esas alınan andır. CIF kıymeti ise ithal eşyasında kaçak akaryakıtın değeridir ve muhafaza ücretinin hesaplandığı tutardır. Bu nedenle doğru cevap 'Rafinericiye satış bedeli üzerinden hesaplanacak bedelden vergiler düşülür; kalan tutara elkoyma tarihinden kararın kesinleştiği tarihe kadar kanuni faiz eklenir.' seçeneğidir. (MD 3, 8, 20)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Tahsis edilmiş akaryakıta ilişkin yargılamanın sonucunda sahibine iadesine karar verilmesi halinde || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | rafinericiye satış bedeli üzerinden hesaplanacak bedelden vergiler düşüldükten sonra kalan tutar, elkoyma tarihinden kararın kesinleştiği tarihe kadar geçen süre için kanuni faiz ilave edilerek || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | yargılamanın sonucunda sahibine iadesine karar verilmesi halinde, toplam satış bedelinden vergiler düşüldükten sonra kalan tutar",
yuva=["Satılarak bedeli bütçeye gelir kaydedilen akaryakıtın iadesi: toplam satış bedelinden vergiler (md 20/1)",
      "Faizin başlangıcının tahsis tarihi sanılması; tahsis ve teslim süreci (md 16)",
      "Kararın sahibine tebliği: iade kararında muhafaza süresinin bitişine esas alınan an (md 8/1-a)",
      "CIF kıymeti: kaçak akaryakıtın değeri tanımı, muhafaza ücretinin matrahı (md 3/ğ)"],
yakinlik="PARAFRAZ",
tuzak=["KOMŞU", "BAŞLANGIÇ", "TERİM"], duzey=["AYIRT"], profil=[1],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="YETKİ",
z="K",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 21",
cek="Yönetmelikte öngörülmeyen durumları inceleyip sonuçlandırmaya konusuna göre Ticaret ve İçişleri Bakanlıkları yetkilidir; Hazine ve Maliye 18.01.2024'te çıkarıldı.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'ne göre Yönetmelik ile yapılan düzenlemelere ilişkin öngörülmeyen durumların ortaya çıkması hâlinde, bunları inceleyip sonuçlandırmaya aşağıdakilerden hangisi yetkilidir?"],
d="Konusuna göre Ticaret ve İçişleri Bakanlıkları",
c=["Konusuna göre Ticaret, İçişleri ve Hazine ve Maliye Bakanlıkları",
   "Enerji Piyasası Düzenleme Kurumu",
   "Konusuna göre Ticaret Bakanlığı ve Enerji Piyasası Düzenleme Kurumu",
   "Akaryakıtın muhafaza edildiği ilin valisi"],
sirali=False,
g="Yönetmeliğe göre Yönetmelik ile yapılan düzenlemelere ilişkin öngörülmeyen durumların ortaya çıkması hâlinde bunları inceleyip sonuçlandırmaya, konusuna göre Ticaret ve İçişleri Bakanlıkları yetkilidir. Hükmün önceki hâlinde Hazine ve Maliye Bakanlığı da sayılıyordu; bu ibare 18.01.2024 tarihli ve 32433 sayılı Resmî Gazete'de yayımlanan değişiklikle çıkarılmıştır. 2021 sınavında bu bilgi sorulduğunda resmî cevap, o tarihteki metne göre üç bakanlığı içeriyordu; güncel metne göre yetkili yalnızca Ticaret ve İçişleri Bakanlıklarıdır. Enerji Piyasası Düzenleme Kurumu Yönetmelik hazırlanırken görüşü alınan kurumdur, yetki hükmünde yer almaz; vali ise akaryakıtın başka depolara tesliminde onay makamıdır. Bu nedenle doğru cevap 'Konusuna göre Ticaret ve İçişleri Bakanlıkları' seçeneğidir. (MD 5, 21, 22)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Bu Yönetmelik ile yapılan düzenlemelere ilişkin öngörülmeyen durumların ortaya çıkması halinde bunları inceleyip sonuçlandırmaya, konusuna göre Ticaret ve İçişleri Bakanlıkları || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | ibaresi \"Ticaret ve İçişleri Bakanlıkları\" olarak 18.01.2024 / 32433 sayılı R.G. ile değiştirilmiştir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Enerji Piyasası Düzenleme Kurumunun görüşü alınarak",
yuva=["Aynı hükmün 18.01.2024 öncesi hâli (dipnot 27; 2021/95 resmî cevabı)",
      "Yönetmelik hazırlanırken görüşü alınan Kurum (md 22)",
      "Görüş veren Kurum ile hazırlayan Bakanlığın birleştirilmesi (md 22)",
      "Akaryakıtın başka depolara tesliminde onay makamı olan vali (md 5/4)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"], duzey=["HATIRLAMA"], profil=[1, 5],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="18.01.2024 / 32433 R.G.", cikmis="2021/95", kapsamli=False,
),

dict(
konu="Elkonulan Akaryakıt Uygulama Yönetmeliği", blok="SB54",
kalip="YANLIŞ",
z="O",
madde="Elkonulan Akaryakıt Uygulama Yönetmeliği md. 1, 2, 22, 23",
cek="Dayanak 5015 ve 5607 sayılı Kanunlar; EPDK görüşüyle Ticaret ve İçişleri Bakanlıklarınca hazırlandı; 1/4/2014'te yürürlüğe girdi; Ticaret ve İçişleri Bakanları yürütür.",
kok=["5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Akaryakıtın Teslimi, Muhafazası, Tasfiyesi ve Yapılan Masraflara İlişkin Uygulama Yönetmeliği'nin amacı, dayanağı, hazırlanması, yürürlüğü ve yürütülmesine ilişkin aşağıdakilerden hangisi söylenemez?"],
d="Yönetmelik, Ticaret Bakanlığı ile Enerji Piyasası Düzenleme Kurumu tarafından müştereken hazırlanmıştır.",
c=["Yönetmelik, 5015 sayılı Petrol Piyasası Kanunu ve 5607 sayılı Kanun hükümlerine dayanılarak hazırlanmıştır.",
   "Yönetmelik hükümlerini Ticaret ve İçişleri Bakanları yürütür.",
   "Yönetmelik 1/4/2014 tarihinde yürürlüğe girmiştir.",
   "Yönetmeliğin amacı, elkonulan kaçak akaryakıtın muhafazası, depolanması, yüklenmesi, boşaltılması, nakliyesi ve tasfiyesi ile bu işlemlere ilişkin giderlerin karşılanmasına ilişkin usul ve esasları belirlemektir."],
sirali=False,
g="Yönetmelik, 5607 sayılı Kanun uyarınca elkonulan kaçak akaryakıtın muhafazası, depolanması, yüklenmesi, boşaltılması, nakliyesi ve tasfiyesi ile bu işlemlere ilişkin giderlerin karşılanmasına ilişkin usul ve esasları belirlemek amacıyla, 5015 sayılı Petrol Piyasası Kanunu ve 5607 sayılı Kanun hükümlerine dayanılarak hazırlanmıştır. Yönetmelik, Enerji Piyasası Düzenleme Kurumunun görüşü alınarak Ticaret Bakanlığı ile İçişleri Bakanlığı tarafından müştereken hazırlanmış, 26.03.2014 tarihli Resmî Gazete'de yayımlanmış ve 1/4/2014 tarihinde yürürlüğe girmiştir; hükümlerini Ticaret ve İçişleri Bakanları yürütür. Söylenemeyecek ifade, görüşü alınan Kurumu hazırlayan makam yerine koymuş ve İçişleri Bakanlığını düşürmüştür; Kurum hazırlayan değil, görüşü alınan kurumdur. En güçlü çeldirici yürürlük tarihine ilişkin ifadedir: yayım ve yürürlük tarihlerinin aynı olduğunu sanan aday bu ifadeyi yanlış sayar, oysa Yönetmelik yayımından sonraki 1/4/2014 tarihinde yürürlüğe girmiştir. Bu nedenle doğru cevap 'Yönetmelik, Ticaret Bakanlığı ile Enerji Piyasası Düzenleme Kurumu tarafından müştereken hazırlanmıştır.' seçeneğidir. (MD 1, 2, 22, 23)",
kanit="kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Bu Yönetmelik, 4/12/2003 tarihli ve 5015 sayılı Petrol Piyasası Kanunu ve 5607 sayılı Kanun hükümlerine dayanılarak hazırlanmıştır || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Enerji Piyasası Düzenleme Kurumunun görüşü alınarak, Ticaret Bakanlığı ile İçişleri Bakanlığı || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | tarafından müştereken hazırlanan bu Yönetmelik 1/4/2014 tarihinde yürürlüğe girer || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | Bu Yönetmelik hükümlerini, Ticaret ve İçişleri Bakanları || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | nakliyesi ve tasfiyesi ile bu işlemlere ilişkin giderlerin karşılanmasına ilişkin usul ve esasları belirlemektir || kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt | 26.03.2014 tarih ve 28953",
yuva=["Dayanak hükmü: 5015 sayılı Petrol Piyasası Kanunu ve 5607 sayılı Kanun (md 2) — doğru",
      "Yürütme hükmü: Ticaret ve İçişleri Bakanları (md 23) — doğru",
      "Yürürlük hükmü: 1/4/2014; yayım tarihi 26.03.2014'ten farklı (md 22) — doğru",
      "Amaç hükmü: muhafaza, depolama, yükleme, boşaltma, nakliye, tasfiye ve giderler (md 1) — doğru"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "KOMŞU"], duzey=["HATIRLAMA", "AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="", cikmis="", kapsamli=False,
),

]
