# Soru Bankası — Bölüm 52: Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği (20 soru)
# Gümrük Koçu - Ufuk Çetintaş
Y = "5607_sayili_kacakcilikla_mucadele_kanununa_gore_elkonulan_esya_ve_alikonulan_tasitlara_iliskin_uygulama_yonetmeligi.txt"
A = "kacakcilikla_mucadele_kanununa_gore_elkonulan_akaryakitin_teslimi_muhafazasi_tasfiyesi_ve_yapilan_masraflara_iliskin_uygulama_yonetmeligi.txt"
KN = "5607_sayili_kacakcilikla_mucadele_kanunu.txt"
YA = "5607 sayılı Kaçakçılıkla Mücadele Kanununa Göre Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliği"
MD = "Elkonulan Eşya ve Alıkonulan Taşıtlara İlişkin Uygulama Yönetmeliği"
Q = [

# 1 ---------------- md. 1, 3/g: kapsam — kaçak akaryakıt hariç ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="KAPSAM_DIŞI",
z="K",
madde=MD + " md. 1, 3",
cek="Yönetmelik kaçak akaryakıt hariç elkonulan her türlü eşya ve alıkonulan taşıtın muhafaza, depolama, nakliye, imha ve masraflarını düzenler; akaryakıt ayrı yönetmeliktedir.",
kok=[YA + "'nin amaç ve kapsamına göre, aşağıdakilerden hangisinin muhafazası, depolanması, nakliyesi ve imhası ile bu işlemlere ilişkin masrafların karşılanması bu Yönetmeliğin kapsamı dışında kalır?"],
d="5607 sayılı Kanun uyarınca elkonulan kaçak akaryakıt",
c=["5607 sayılı Kanun uyarınca alıkonulan deniz taşıtları",
   "Ambalajında yabancı bandrol bulunan tütün mamulleri",
   "Elkonulan kültür ve tabiat varlıkları",
   "Elkonulan elektronik sigara ve solüsyonları"],
sirali=False,
g="Yönetmeliğin amacı, 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca kaçak akaryakıt hariç elkonulan her türlü eşya ve alıkonulan taşıtların muhafazası, depolanması, yüklenmesi, boşaltılması, nakliyesi ve imhası ile bu işlemlere ilişkin masrafların karşılanmasına ilişkin usul ve esasları belirlemektir. Yönetmelikteki 'eşya' tanımı da kaçak akaryakıtı açıkça dışarıda bırakır. Elkonulan kaçak akaryakıtın muhafazası, depolanması, nakliyesi, tasfiyesi ve giderleri, 5607 sayılı Kanuna göre çıkarılmış ayrı bir uygulama yönetmeliğinde düzenlenmiştir. Alıkonulan deniz taşıtları (liman başkanlıklarının gözetiminde en yakın liman işletmesine teslim), kültür ve tabiat varlıkları (müzelere teslim), yabancı bandrollü tütün mamulleri ile elektronik sigara ve solüsyonları (numune alınması ve imha) ise bu Yönetmelikte ayrıca düzenlenmiştir. En güçlü çeldirici alıkonulan deniz taşıtlarıdır: bu taşıtların gümrük idaresi yerine liman işletmesine teslim edilmesi kapsam dışı oldukları izlenimini verir, ancak Yönetmelik elkonulan eşya ile birlikte alıkonulan taşıtları da kapsar. Bu nedenle doğru cevap '5607 sayılı Kanun uyarınca elkonulan kaçak akaryakıt' seçeneğidir. (MD 1, 3)",
kanit=Y + " | Bu Yönetmeliğin amacı; 21/3/2007 tarihli ve 5607 sayılı Kaçakçılıkla Mücadele Kanunu uyarınca, kaçak akaryakıt hariç elkonulan her türlü eşya ve alıkonulan taşıtların muhafazası || " + Y + " | Eşya: Kaçak akaryakıt hariç 5607 sayılı Kanun uyarınca elkonulan her türlü eşya ve alıkonulan taşıtları || " + A + " | uyarınca elkonulan kaçak akaryakıtın muhafazası, depolanması, yüklenmesi, boşaltılması, nakliyesi ve tasfiyesi || " + Y + " | Deniz taşıtları; sahibi tarafından teslim alınmayan deniz taşıtları || " + Y + " | yabancı bandrol bulunan tütün ve tütün mamulleri || " + Y + " | Kültür ve tabiat varlıkları; işlemleri tamamlandıktan sonra Kültür ve Turizm Bakanlığına bağlı müzelere || " + Y + " | elektronik nargile dahil her türlü mamul ve bu mamullerin tüketiminde kullanılan elektronik cihaz, aksam, yedek parça ve solüsyonlar",
yuva=["Eşyanın teslimi: deniz taşıtları liman başkanlıklarının gözetiminde en yakın liman işletmesine teslim edilir (Yönetmelik kapsamında)",
      "Tütün ve alkollü içkiler bölümü: yabancı bandrollü tütün mamullerinden numune alınması (Yönetmelik kapsamında)",
      "Eşyanın teslimi: kültür ve tabiat varlıkları Kültür ve Turizm Bakanlığına bağlı müzelere teslim edilir (Yönetmelik kapsamında)",
      "Tütün ve alkollü içkiler bölümü: elektronik sigara, cihaz ve solüsyonlardan numune alınması (Yönetmelik kapsamında)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "KOMŞU", "SAĞDUYU"], duzey=["HATIRLAMA"], profil=[1, 3],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="",
cikmis="2021/99", kapsamli=False,
),

# 2 ---------------- md. 3/ğ: eşyanın değeri — addan tanım (26.05.2025 değişikliği) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="TANIM",
z="O",
madde=MD + " md. 3",
cek="Eşyanın değeri: varsa mahkemece belirlenen bedel; yoksa kaçak eşya tespit tutanağındaki ihraç eşyasında FOB, ithal eşyasında CIF değeridir.",
kok=[YA + "'ne göre \"eşyanın değeri\" ifadesinin tanımı aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Varsa mahkemece belirlenen bedel, bedel belirlenmemiş ise kaçak eşyaya mahsus tespit tutanağında yer alan ihraç eşyası için FOB, ithal eşyası için CIF değeri",
c=["Kaçak eşyaya mahsus tespit tutanağında yer alan ihraç eşyası için FOB, ithal eşyası için CIF değeri; bu değer bulunmuyorsa mahkemece belirlenen bedel",
   "Varsa mahkemece belirlenen bedel, bedel belirlenmemiş ise kaçak eşyaya mahsus tespit tutanağında yer alan ihraç eşyası için CIF, ithal eşyası için FOB değeri",
   "İthal eşyası için eşyanın CIF kıymeti ile gümrük vergileri toplamı, ihraç eşyası için FOB kıymeti ile gümrük vergileri toplamı",
   "Eşyanın elkonulduğu yer ve tarihteki piyasada oluşan alım ve satım bedeli"],
sirali=False,
g="Yönetmeliğe göre eşyanın değeri; varsa mahkemece belirlenen bedeli, bedel belirlenmemiş ise kaçak eşyaya mahsus tespit tutanağında yer alan ihraç eşyası için FOB, ithal eşyası için CIF değerini ifade eder. Tanımda öncelik mahkemece belirlenen bedeldedir; tespit tutanağındaki FOB veya CIF değerine ancak mahkeme bir bedel belirlememişse başvurulur. Tanım bugünkü hâlini 26.05.2025 tarihli ve 32911 sayılı Resmî Gazete'de yayımlanan değişiklikle almıştır; önceki metinde FOB ve CIF kıymeti önce, mahkemece belirlenmiş değer sonra sayılıyordu. FOB ihraç eşyasına, CIF ithal eşyasına aittir; ters eşleştirme yanlıştır. CIF veya FOB kıymeti ile gümrük vergilerinin toplamı 5607 sayılı Kanundaki gümrüklenmiş değerin tanımıdır. Temin edildiği yer ve tarihteki piyasa alım ve satım bedeli ise Yönetmelikte rayiç bedel olarak ayrıca tanımlanmıştır. En güçlü çeldirici öncelik sırası ters kurulmuş seçenektir: değişiklik öncesi metinle çalışan aday tespit tutanağındaki değeri önce saymaya yönelir. Bu nedenle doğru cevap 'Varsa mahkemece belirlenen bedel, bedel belirlenmemiş ise kaçak eşyaya mahsus tespit tutanağında yer alan ihraç eşyası için FOB, ithal eşyası için CIF değeri' seçeneğidir. (MD 3)",
kanit=Y + " | Eşyanın değeri: Varsa mahkemece belirlenen bedeli, bedel belirlenmemiş ise kaçak eşyaya mahsus tespit tutanağında yer alan ihraç eşyası için FOB, ithal eşyası için CIF değerini || " + Y + " | elkonulan ihraç eşyası için FOB, ithal eşyası için CIF kıymetini veya varsa mahkemece belirlenmiş değerini || " + KN + " | ithal eşyası için eşyanın CIF kıymeti ile gümrük vergileri toplamını || " + Y + " | Rayiç bedel: Bir mal, iş veya hizmetin temin edildiği yer ve tarihteki piyasadaki alım ve satım bedelini",
yuva=["Eşyanın değeri tanımının 26.05.2025 öncesi hâli (dipnot): FOB/CIF kıymeti önce, mahkemece belirlenmiş değer sonra",
      "Aynı tanım: FOB ihraç eşyasına, CIF ithal eşyasına aittir (burada ters eşleştirilmiş)",
      "5607 sayılı Kanun: gümrüklenmiş değer tanımı (CIF/FOB kıymeti ile gümrük vergileri toplamı)",
      "Aynı maddenin rayiç bedel bendi: temin edildiği yer ve tarihteki piyasa alım ve satım bedeli"],
yakinlik="BİREBİR",
tuzak=["TERİM", "KOMŞU", "UNSUR"], duzey=["AYIRT"], profil=[5, 1],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="26.05.2025 / 32911 R.G.",
cikmis="", kapsamli=False,
),

# 3 ---------------- md. 3/a, c, l: tanımlar — önermeli (I ve IV) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="ÖNERMELİ",
z="Z",
madde=MD + " md. 3",
cek="Alıkonulan kara taşıtının değeri kasko, deniz taşıtınınki tekne-makine sigortasına esas değerdir; alkollü içki tanımı etil alkol ve metanolü kapsar.",
kok=[YA + "'nde yer alan tanımlara ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. Alıkonulan taşıtın değeri, kara taşıtlarında kasko değeridir.",
     "II. Alıkonulan taşıtın değeri, tekne ve makine sigortası bulunan deniz taşıtlarında piyasa değeridir.",
     "III. Yönetmelikte geçen \"alkollü içki\" ifadesi etil alkol ve metanolü kapsamaz.",
     "IV. Rayiç bedel, bir mal, iş veya hizmetin temin edildiği yer ve tarihteki piyasadaki alım ve satım bedelidir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I ve IV",
c=["I ve II", "II ve III", "I, II ve IV", "I, III ve IV"],
sirali=False,
g="Yönetmeliğe göre alıkonulan taşıtın değeri, kara taşıtlarında kasko değerini ifade eder (I doğru). Deniz taşıtlarında değer, tekne ve makine sigortasına esas teşkil eden değerdir; piyasa değeri yalnızca sigortasız taşıtlar ile hava ve demiryolu taşıtları için esas alınır (II yanlış). Yönetmelikteki 'alkollü içki' tanımı etil alkol, metanol ve alkollü içkileri birlikte kapsar; bu nedenle etil alkol ve metanol tanımın dışında değildir (III yanlış). Rayiç bedel, bir mal, iş veya hizmetin temin edildiği yer ve tarihteki piyasadaki alım ve satım bedelidir (IV doğru). En güçlü çeldirici 'I, II ve IV' seçeneğidir: aynı tanımda sigortasız taşıtlar için öngörülen piyasa değeri, sigortalı deniz taşıtına taşınırsa II doğru sanılır. Bu nedenle doğru cevap 'I ve IV' seçeneğidir. (MD 3)",
kanit=Y + " | Alıkonulan taşıtın değeri: Kara taşıtlarında kasko değerini; deniz taşıtlarında, tekne ve makine sigortasına esas teşkil eden değeri; sigortasız taşıtlar ile hava ve demiryolu taşıtlarında ise piyasa değerini || " + Y + " | Alkollü içki: Etil alkol, metanol ve alkollü içkileri || " + Y + " | Rayiç bedel: Bir mal, iş veya hizmetin temin edildiği yer ve tarihteki piyasadaki alım ve satım bedelini",
yuva=["I ve II: deniz taşıtında sigortaya esas değeri sigortasız taşıtlara ait piyasa değeriyle karıştıran aday",
      "II ve III: kasko ve rayiç bedel tanımlarını bilmeyip metanolü alkollü içki dışında sanan aday",
      "I, II ve IV: aynı tanımdaki sigortasız taşıt kuralını sigortalı deniz taşıtına uygulayan aday",
      "I, III ve IV: alkollü içki tanımının etil alkol ve metanolü de kapsadığını bilmeyen aday"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "TERİM", "UNSUR"], duzey=["AYIRT"], profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False, eksen=0,
ayna="SB52-A metanol: alkollü içki tanımına dahil (soru 3) ↔ özellikli eşya listesinde yok (soru 9)",
guncellik="", cikmis="2025/89", kapsamli=False,
),

# 4 ---------------- md. 5/3: doğrudan teslim — eşya/idare eşleştirmesi (yanlış olan) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="EŞLEŞTİRME",
z="O",
madde=MD + " md. 5",
cek="Gıda maddeleri ve gıda takviyeleri Tarım ve Orman Bakanlığına; ilaç, tıbbi cihaz, aşı, kozmetik ve sular Sağlık Bakanlığı birimlerine teslim edilir.",
kok=[YA + "'ne göre elkoyan birimlerce doğrudan ilgili idarelere teslim edilecek eşya ile teslim edileceği idare eşleştirmelerinden hangisi yanlıştır?"],
d="Gıda takviyeleri – Sağlık Bakanlığının ilgili birimleri",
c=["Hava taşıtları – Devlet Hava Meydanları İşletmesi müdürlükleri",
   "Sahte paralar – Türkiye Cumhuriyet Merkez Bankası şubeleri veya mal müdürlükleri",
   "Nesli tükenmekte olan canlı hayvan ve bitkiler – hayvanat bahçeleri, botanik bahçeleri ve belediyeler",
   "Kimyasal maddeler – kimyevi madde üretimi yapan kamu kurum ve kuruluşları"],
sirali=False,
g="Yönetmelik, bazı eşya ve taşıtların gümrük idaresine değil, elkoyan birimlerce doğrudan ilgili idarelere teslim edilmesini öngörür. Bu listeye göre gıda maddeleri, gıda takviyeleri, hayvansal ürünler, bitki ve hayvan sağlığına ilişkin ilaçlar, su ürünleri ve canlı hayvanlar Tarım ve Orman Bakanlığının ilgili birimlerine veya uygun tesise sahip kamu kurum ve kuruluşlarına teslim edilir. Sağlık Bakanlığının ilgili birimleri ise insan sağlığına ilişkin ilaçlar, ilaç hammaddeleri, tıbbi cihaz ve malzemeler, aşılar, kozmetikler ve sular için öngörülen teslim yeridir. Hava taşıtları Devlet Hava Meydanları İşletmesi müdürlüklerine; kıymetli maden ve taşlar ile Türk Lirası banknotlar, döviz, efektif ve sahte paralar Türkiye Cumhuriyet Merkez Bankası şubelerine veya mal müdürlüklerine; nesli tükenmekte olan canlı hayvan ve bitkiler Tarım ve Orman Bakanlığının ilgili birimlerine, hayvanat bahçelerine, botanik bahçelerine ve belediyelere; kimyasal maddeler kimyevi madde üretimi yapan kamu kurum ve kuruluşlarına teslim edilir. En güçlü tuzak sağduyudur: gıda takviyesi sağlık ürünü gibi görünse de Yönetmelik onu gıda maddeleriyle aynı bende koymuştur. Bu nedenle doğru cevap 'Gıda takviyeleri – Sağlık Bakanlığının ilgili birimleri' seçeneğidir. (MD 5)",
kanit=Y + " | Gıda maddeleri, gıda takviyeleri, hayvansal ürünler, bitki ve hayvan sağlığına ilişkin ilaçlar, su ürünleri ve canlı hayvanlar; Tarım ve Orman Bakanlığının ilgili birimlerine || " + Y + " | aşılar, kozmetikler ve sular; Sağlık Bakanlığının ilgili birimlerine || " + Y + " | Hava taşıtları; Devlet Hava Meydanları İşletmesi müdürlüklerine teslim edilir || " + Y + " | Türk Lirası banknotlar, döviz, efektif, sahte paralar; Türkiye Cumhuriyet Merkez Bankası şubelerine veya mal müdürlüklerine || " + Y + " | Nesli tükenmekte olan canlı hayvan ve bitkiler; Tarım ve Orman Bakanlığının ilgili birimlerine, hayvanat bahçelerine, botanik bahçelerine ve belediyelere || " + Y + " | Kimyasal maddeler; kimyevi madde üretimi yapan kamu kurum ve kuruluşlarına",
yuva=["Doğrudan teslim listesi, hava taşıtları bendi (doğru eşleşme)",
      "Doğrudan teslim listesi, kıymetli maden, döviz ve sahte paralar bendi (doğru eşleşme)",
      "Doğrudan teslim listesi, nesli tükenmekte olan canlılar bendi (doğru eşleşme; Tarım ve Orman Bakanlığı birimleri de sayılmış)",
      "Doğrudan teslim listesi, kimyasal maddeler bendi (doğru eşleşme)"],
yakinlik="BİREBİR",
tuzak=["KOMŞU", "SAĞDUYU", "MAKAM"], duzey=["AYIRT"], profil=[3, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="",
cikmis="", kapsamli=False,
),

# 5 ---------------- md. 5/8: teslim tutanağı — üç iş günü, düzenlenme tarihinden ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="SÜRE",
z="O",
madde=MD + " md. 5",
cek="Teslim tutanağının bir örneği, düzenlenme tarihini takip eden üç iş günü içinde ilgili müdahil gümrük müdürlüğüne gönderilir.",
kok=[YA + "'ne göre elkonulan eşyanın tesliminde düzenlenen teslim tutanağının bir örneğinin ilgili müdahil gümrük müdürlüğüne gönderilme süresi aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Tutanağın düzenlenme tarihini takip eden üç iş günü içinde",
c=["Eşyaya el konulduğu tarihi takip eden üç iş günü içinde",
   "Tutanağın düzenlenme tarihini takip eden otuzuncu günü geçmemek üzere",
   "Eşyaya el konulduğu tarihten itibaren altı ay içinde",
   "Derhal, telefon ve faks gibi haberleşme araçlarıyla"],
sirali=False,
g="Yönetmeliğe göre eşya veya taşıtın tesliminde Kaçak Eşya Teslim Tutanağı ya da Taşıt Tespit ve Teslim-Tesellüm Tutanağı düzenlenir ve teslim tutanağının bir örneği düzenlenme tarihini takip eden üç iş günü içinde ilgili müdahil gümrük müdürlüğüne gönderilir. Süre, eşyaya el konulduğu tarihten değil, tutanağın düzenlenme tarihinden başlar. Otuzuncu gün, iade kararının müdahil idarece sahibine tebliğinden sonra muhafaza süresinin sona erdiği sınırdır; altı ay, bandrollü tütün ve alkollü içkilerde adli mercilerin karar bildirmesi için beklenen süredir; derhal telefon ve faks gibi araçlarla bildirim ise nükleer ve radyoaktif maddelerin yakalanmasına aittir. En güçlü çeldirici, süre aynı kalıp başlangıcı el koyma tarihine kaydırılmış seçenektir. Bu nedenle doğru cevap 'Tutanağın düzenlenme tarihini takip eden üç iş günü içinde' seçeneğidir. (MD 5, 6, 8, 11)",
kanit=Y + " | Teslim tutanağının bir örneği düzenlenme tarihini takip eden üç iş günü içinde ilgili müdahil gümrük müdürlüğüne gönderilir || " + Y + " | tebliğ edildiği tarihi takip eden otuzuncu günü geçmemek üzere || " + Y + " | Elkoyma tarihinden itibaren altı ay içinde adli mercilerce herhangi bir karar bildirilmemiş olması halinde || " + Y + " | yakalayan birim tarafından derhal telefon ve faks gibi haberleşme araçlarıyla",
yuva=["Aynı fıkra: süre üç iş günü, ancak başlangıç anı tutanağın düzenlenme tarihidir (el koyma tarihi değil)",
      "Muhafaza süresi: iade kararının tebliğ edildiği tarihi takip eden otuzuncu gün",
      "İmha işlemleri: bandrollü tütün ve alkollü içkilerde elkoyma tarihinden itibaren altı ay",
      "Eşyanın muhafazası: nükleer ve radyoaktif maddenin yakalanmasında derhal telefon ve faksla bildirim"],
yakinlik="BİREBİR",
tuzak=["BAŞLANGIÇ", "KOMŞU", "SAYI"], duzey=["HATIRLAMA"], profil=[2],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="", guncellik="",
cikmis="", kapsamli=False,
),

# 6 ---------------- md. 15/2-4: harcama talimatı — işletme müdürlüğü düzenler ve örneği elkoyan idareye gönderir ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="YETKİ",
z="Z",
madde=MD + " md. 3, 15",
cek="Zorunlu nakliye ve imha masraflarında harcama talimatını işletme müdürlüğü düzenler, onaylanan örneği elkoyan idareye gönderir; alımı elkoyan idare yapar.",
kok=[YA + "'ne göre elkonulan eşyanın elkonulduğu araçla ya da elkoyan idareye veya gümrük idaresine ait uygun araçla naklinin mümkün olmaması durumunda, zorunlu nakliye, yükleme, boşaltma ve imha masrafları için kendisine ulaşan belgeleri inceleyip ödenek kontrolünü yaparak harcama talimatını düzenleyen ve onaylanan harcama talimatının bir örneğini elkoyan idareye gönderen merci aşağıdakilerden hangisidir?"],
d="Sorumluluk alanındaki tasfiye işletme müdürlüğü",
c=["Gümrük ve dış ticaret bölge müdürlüğü",
   "Elkoyma işlemini yapan idare amiri",
   "Eşyanın teslim edildiği gümrük müdürlüğü",
   "Eşyayı teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı"],
sirali=False,
g="Yönetmeliğe göre eşyanın elkonulduğu araçla naklinin veya elkoyan idareye ya da gümrük idaresine ait uygun araçla taşınmasının mümkün olmaması durumunda, zorunlu nakliye, yükleme, boşaltma ve imha masrafları için elkoyma işlemini yapan idare amirinin görevlendireceği personelce düzenlenen ve idare amirince imzalanan Piyasa Fiyat Araştırması Tutanağı ile elkoyma tutanağının birer örneği ilgili işletme müdürlüğüne gönderilir. İşletme müdürlüğü, kendisine ulaşan belgeleri inceleyip ödenek kontrolünü yaparak harcama talimatını düzenler ve onaylanan harcama talimatının bir örneğini elkoyan idareye gönderir; elkoyan idare de mal veya hizmet alımını bu talimata uygun olarak gerçekleştirir. Yönetmelikte işletme müdürlüğü, tasfiye işletme müdürlüklerini ifade eder; harcamaya ilişkin belgeler de ek tabloda yer alan sorumluluk alanındaki ilgili işletme müdürlüğüne gönderilir. 26.05.2025 tarihli ve 32911 sayılı Resmî Gazete'de yayımlanan değişiklikten önce harcama talimatı bölge müdürlüğüne gönderiliyor, onaylanan talimatın örneği bölge müdürlüğünce elkoyan idareye iletiliyordu; bu ara halka kaldırılmıştır. İdare amiri tutanağı imzalayan ve personeli görevlendiren makamdır; il özel idaresi ise kaçak akaryakıt yönetmeliğinde harcama işlemlerini yürüten kurumdur. En güçlü çeldirici bölge müdürlüğüdür: değişiklik öncesi metinle çalışan aday onaylanan talimatın örneğini bölge müdürlüğünün gönderdiğini hatırlar. Bu nedenle doğru cevap 'Sorumluluk alanındaki tasfiye işletme müdürlüğü' seçeneğidir. (MD 3, 15)",
kanit=Y + " | elkoyan idareye veya gümrük idaresine ait uygun araç olması durumlarında öncelikle bu imkânlar kullanılır || " + Y + " | elkoyma işlemini yapan idare amirinin görevlendireceği personelce || " + Y + " | Piyasa Fiyat Araştırması Tutanağı ile elkoyma tutanağının birer örneği ilgili işletme müdürlüğüne gönderilerek || " + Y + " | İşletme müdürlüğü, kendisine ulaşan belgeleri inceleyip ödenek kontrolünü yaparak harcama talimatı düzenler ve onaylanan harcama talimatının bir örneğini elkoyan idareye gönderir || " + Y + " | Elkoyan idare, onaylanan harcama talimatına uygun olarak mal veya hizmet alımını gerçekleştirir || " + Y + " | İşletme müdürlüğü: Tasfiye işletme müdürlüklerini || " + Y + " | tabloda yer alan sorumluluk alanındaki ilgili işletme müdürlüğüne gönderilir || " + Y + " | Döner sermaye işletmesi müdürlüğü, kendisine ulaşan belgeleri inceler ve ödenek kontrolünü yaparak düzenleyeceği harcama talimatını Gümrük ve Ticaret Bölge Müdürlüğüne gönderir. Onaylanan harcama talimatının bir örneği bölge müdürlüğünce elkoyan idareye gönderilir || " + A + " | teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığınca",
yuva=["Aynı fıkranın 26.05.2025 öncesi hâli (dipnot): onaylanan talimatın örneği bölge müdürlüğünce elkoyan idareye gönderilirdi",
      "Aynı madde: elkoyma işlemini yapan idare amiri personeli görevlendirir ve Piyasa Fiyat Araştırması Tutanağını imzalar",
      "Eşyanın teslimi: eşya öncelikle en yakın gümrük idaresine teslim edilir (harcama talimatında görevi yok)",
      "Elkonulan akaryakıt yönetmeliği: Piyasa Fiyat Araştırması Tutanağını teslim almakla sorumlu il özel idaresi veya yatırım izleme ve koordinasyon başkanlığı düzenler"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "KOMŞU", "TERİM"], duzey=["AYIRT"], profil=[1, 5],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="26.05.2025 / 32911 R.G.",
cikmis="", kapsamli=False,
),

# 7 ---------------- md. 5/3-c, 5/4, 6/2: nükleer ve radyoaktif madde — izin / bilgi (yanlış olan) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="YANLIŞ",
z="Z",
madde=MD + " md. 5, 6",
cek="Nükleer ve radyoaktif madde ancak TENMAK izniyle, gümrük idaresinin bilgisi dahilinde çıkarılır; diğer eşya gümrük idaresinin yazılı bildirimiyle çıkarılır.",
kok=[YA + "'ne göre elkonulan nükleer madde ve radyoaktif maddelere ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Bulunduğu yerden ancak gümrük idaresinin izniyle, Türkiye Enerji, Nükleer ve Maden Araştırma Kurumunun bilgisi dahilinde çıkartılabilir.",
c=["Yakalanması hâlinde yakalayan birim tarafından derhal telefon ve faks gibi haberleşme araçlarıyla Türkiye Enerji, Nükleer ve Maden Araştırma Kurumuna, valiliğe ve gümrük idaresine bildirilir.",
   "Özel kişi ve kuruluşların depolarında depolanamaz.",
   "Türkiye Enerji, Nükleer ve Maden Araştırma Kurumu tarafından yapılacak değerlendirme sonucunda bu Kuruma veya Kurumun uygun göreceği yerlere teslim edilir.",
   "Gerekli inceleme, test ve ölçümler Kurum uzmanları tarafından veya Kurumun kontrolünde, uygun göreceği kurum veya kuruluşlardan görevlendirilen elemanlarca yapılır."],
sirali=False,
g="Yönetmeliğe göre nükleer madde, radyoaktif madde, radyoaktif bulaşma bulunan madde ile nükleer veya radyoaktif atık niteliği taşıyan maddenin yakalanması hâlinde yakalayan birim, derhal telefon ve faks gibi haberleşme araçlarıyla Türkiye Enerji, Nükleer ve Maden Araştırma Kurumuna, valiliğe ve gümrük idaresine bildirimde bulunur. Gerekli inceleme, test ve ölçümler Kurum uzmanları tarafından veya Kurumun kontrolünde, uygun göreceği kurum veya kuruluşlardan görevlendirilen elemanlarca yapılır. Bu nitelikteki eşya bulunduğu yerden ancak Kurumun izniyle, gümrük idaresinin bilgisi dahilinde çıkartılabilir; seçenekte izin ve bilgi makamları yer değiştirmiştir. Diğer eşyanın bulunduğu yerden çıkartılması ise gümrük idaresinin yazılı bildirimi üzerine yapılır. Bu maddeler Kurumun değerlendirmesi sonucunda Kuruma veya Kurumun uygun göreceği yerlere teslim edilir ve özel kişi ve kuruluşların depolarında depolanamaz. En güçlü tuzak, diğer eşyada gümrük idaresine tanınan belirleyici rolün nükleer maddeye taşınmasıdır: nükleer maddede izni veren Kurumdur, gümrük idaresi yalnızca bilgilendirilir. Bu nedenle doğru cevap 'Bulunduğu yerden ancak gümrük idaresinin izniyle, Türkiye Enerji, Nükleer ve Maden Araştırma Kurumunun bilgisi dahilinde çıkartılabilir.' seçeneğidir. (MD 5, 6)",
kanit=Y + " | Bu nitelikteki eşya bulunduğu yerden ancak, Türkiye Enerji, Nükleer ve Maden Araştırma Kurumunun … izniyle, gümrük idaresinin bilgisi dahilinde çıkartılabilir || " + Y + " | Diğer eşyanın bulunduğu yerden çıkartılması ise gümrük idaresinin yazılı bildirimi üzerine yapılır || " + Y + " | yakalayan birim tarafından derhal telefon ve faks gibi haberleşme araçlarıyla Türkiye Enerji, Nükleer ve Maden Araştırma Kurumuna … valiliğe ve gümrük idaresine bildirilerek || " + Y + " | uzmanları tarafından veya kontrolünde anılan Kurumun uygun göreceği kurum veya kuruluşlardan görevlendirilen elemanlarca || " + Y + " | Enerji, Nükleer ve Maden Araştırma Kurumu tarafından yapılacak değerlendirme sonucunda bu Kuruma veya bu Kurumun teknik, donanım ve yapısal inceleme ve değerlendirmesi sonucunda uygun göreceği yerlere teslim edilir || " + Y + " | nükleer veya radyoaktif atık niteliği taşıyan maddeler özel kişi ve kuruluşların depolarında depolanamaz",
yuva=["Eşyanın muhafazası: derhal telefon ve faksla Kuruma, valiliğe ve gümrük idaresine bildirim (doğru)",
      "Eşyanın teslimi: nükleer ve radyoaktif maddeler özel kişi ve kuruluş depolarında depolanamaz (doğru)",
      "Doğrudan teslim listesi, nükleer madde bendi: Kurumun değerlendirmesiyle Kuruma veya uygun göreceği yerlere teslim (doğru)",
      "Eşyanın muhafazası: inceleme, test ve ölçümler Kurum uzmanlarınca veya kontrolünde görevlendirilen elemanlarca (doğru)"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "MAKAM", "KOMŞU"], duzey=["AYIRT"], profil=[4],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="",
cikmis="", kapsamli=False,
),

# 8 ---------------- md. 7/3-4: numune miktarları — dökme tütünde eski "üç kilogram" (yanlış olan) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="YANLIŞ",
z="Z",
madde=MD + " md. 7",
cek="Numune: paketli sigara, puro ve sigarilloda on paket; etil alkol, metanol ve alkollü içkide iki şişe; dökme tütünde bir kilogram (2025 öncesi üç kilogram).",
kok=[YA + "'ne göre ambalajlarında kamu kurumlarınca uygulanan bandrol veya benzeri işaret bulunmayan tütün ve tütün mamulleri ile alkollü içkilerden elkoyan idarece alınacak numunelere ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Tütün veya tütün mamulünün dökme olması hâlinde, eşya karıştırılarak üç kilogramdan az olmamak üzere numune alınır.",
c=["Her bir cins, nevi, marka ve ebat itibarıyla paketlenmiş sigara, puro ve sigarillolarda numune miktarı on pakettir.",
   "Etil alkol, metanol ve alkollü içkilerde numune miktarı her bir cins, nevi, marka ve ebat itibarıyla iki şişedir.",
   "Elkonulan eşyanın belirtilen numune miktarından daha az olması durumunda tamamı muhafaza edilir.",
   "Numuneler, kovuşturma sonrasında verilen esasa ilişkin kararın kesinleşmesini müteakip muhafaza eden birim tarafından imha edilerek tutanağa bağlanır."],
sirali=False,
g="Yönetmeliğe göre numune miktarı; her bir cins, nevi, marka ve ebat itibarıyla paketlenmiş sigara, puro ve sigarillo, nargilelik, pipoluk ve sarmalık kıyılmış tütün ve tütün mamullerinde on paket, etil alkol, metanol ve alkollü içkilerde iki şişedir. Tütün veya tütün mamulü, ilaç hammaddesi ve benzeri eşyanın dökme olması hâlinde alınacak numune bir kilogramdır. Üç kilogram, 26.05.2025 tarihli ve 32911 sayılı Resmî Gazete'de yayımlanan değişiklikten önceki metinde dökme tütün için öngörülen alt sınırdır; aynı değişiklikle paketli tütün mamullerinde yirmi paket on pakete, alkollü içkilerde üç şişe iki şişeye indirilmiştir. Elkonulan eşya belirtilen numune miktarından az ise tamamı muhafaza edilir. Alınan numuneler, kovuşturma sonrasında verilen esasa ilişkin kararın kesinleşmesini müteakip muhafaza eden birim tarafından imha edilerek tutanağa bağlanır. Kök yanlış olanı sorduğu için değişiklik öncesi miktarı taşıyan seçenek aranmaktadır; eski metinden çalışan aday bu seçeneği doğru sanır. Bu nedenle doğru cevap 'Tütün veya tütün mamulünün dökme olması hâlinde, eşya karıştırılarak üç kilogramdan az olmamak üzere numune alınır.' seçeneğidir. (MD 7)",
kanit=Y + " | pipoluk ve sarmalık kıyılmış tütün ve tütün mamullerinde on paket, etil alkol, metanol ve alkollü içkilerde iki şişe || " + Y + " | Tütün veya tütün mamulü, ilaç hammaddesi ve ilaç hammaddesi içeren eşya ile benzeri eşyanın dökme olması halinde bir kilogram || " + Y + " | Tütün veya tütün mamulü cinsi eşyanın dökme olması halinde eşya karıştırılarak üç kilogramdan az olmamak üzere numune alınır || " + Y + " | bu fıkrada belirtilen numune miktarından daha az miktarda olması durumunda, tamamı muhafaza edilir || " + Y + " | numuneler muhafaza eden birim tarafından imha edilerek tutanağa bağlanır",
yuva=["Numune miktarı: paketlenmiş sigara, puro ve sigarillo için on paket (doğru; değişiklik öncesi yirmi paket)",
      "Numune miktarı: etil alkol, metanol ve alkollü içkilerde iki şişe (doğru; değişiklik öncesi üç şişe)",
      "Aynı fıkra: belirtilen miktardan az olan eşyanın tamamının muhafazası (doğru)",
      "Numunelerin muhafazası: esasa ilişkin kararın kesinleşmesinden sonra muhafaza eden birimce imha (doğru)"],
yakinlik="BİREBİR",
tuzak=["SAYI", "YAKIN-SAYI", "TERSİNE"], duzey=["AYIRT"], profil=[2, 4, 5],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="26.05.2025 / 32911 R.G.",
cikmis="", kapsamli=False,
),

# 9 ---------------- md. 9: özellikli eşya — metanol sayılmamış ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="KAPSAM_DIŞI",
z="O",
madde=MD + " md. 3, 9",
cek="Özellikli eşya: ilaç, ilaç hammaddesi, ilaç hammaddesi içeren ürün, tıbbi cihaz ve malzeme ile etil alkol; metanol sayılmamıştır.",
kok=[YA + "'ne göre kullanım tarihi geçmiş, CE işareti olmayan, lisansa tabi olup lisansı bulunmayan ve kullanılmayacak hâlde olduğu tahlil, teknik inceleme ve araştırmaya gerek olmaksızın anlaşılması hâlinde imha edilecek özellikli eşya arasında aşağıdakilerden hangisi sayılmamıştır?"],
d="Metanol",
c=["Etil alkol", "İlaç hammaddeleri", "İlaç hammaddesi içeren ürünler", "Tıbbi cihaz ve malzemeler"],
sirali=False,
g="Yönetmelik, ilaç, ilaç hammaddesi, ilaç hammaddesi içeren ürünler, tıbbi cihaz ve malzemeler ile etil alkol cinsi eşyayı özellikli eşya olarak ayrıca düzenler. Bu eşyadan kullanım tarihi geçmiş, CE işareti olmayan, lisansa tabi olup lisansı bulunmayan ve kullanılmayacak hâlde olduğu tahlil, teknik inceleme ve araştırmaya gerek olmaksızın anlaşılanlar imha edilir; bunun dışında kalanlar hakkında ilgili Bakanlık birimlerine uygunluğunun değerlendirilmesi için bildirimde bulunularak alınan görüşe göre işlem yapılır. Metanol bu listede yer almaz: Yönetmelik metanolü alkollü içki tanımının içinde sayar ve metanol ile alkollü içkilerin niteliklerine uygun yöntemlerle imha edilmesini öngörür. En güçlü tuzak etil alkol ile metanolün aynı kategoride sanılmasıdır; özellikli eşya listesinde yalnızca etil alkol vardır. Bu nedenle doğru cevap 'Metanol' seçeneğidir. (MD 3, 8, 9)",
kanit=Y + " | ilaç, ilaç hammaddesi, ilaç hammaddesi içeren ürünler, tıbbi cihaz ve malzemeler ile etil alkol cinsi eşyadan kullanım tarihi geçmiş, CE işareti olmayan || " + Y + " | lisansa tabi olup lisansı bulunmayan ve kullanılmayacak halde olduğu tahlil, teknik inceleme ve araştırmaya gerek olmaksızın anlaşılanlar imha edilir || " + Y + " | uygunluğunun değerlendirilmesi için bildirimde bulunularak alınan görüşe göre işlem yapılır || " + Y + " | Alkollü içki: Etil alkol, metanol ve alkollü içkileri || " + Y + " | metanol ve alkollü içkiler, ilaç, ilaç hammaddeleri, ilaç hammaddesi içeren ürünler, tıbbi cihaz ve malzemeler",
yuva=["Özellikli eşya listesi: etil alkol (listede)",
      "Özellikli eşya listesi: ilaç hammaddesi (listede)",
      "Özellikli eşya listesi: ilaç hammaddesi içeren ürünler (listede)",
      "Özellikli eşya listesi: tıbbi cihaz ve malzemeler (listede)"],
yakinlik="BİREBİR",
tuzak=["LİSTE-DIŞI", "TERİM", "SAĞDUYU"], duzey=["AYIRT"], profil=[3, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0,
ayna="SB52-A metanol: alkollü içki tanımına dahil (soru 3) ↔ özellikli eşya listesinde yok (soru 9)",
guncellik="", cikmis="", kapsamli=False,
),

# 10 ---------------- md. 8/2: bandrollü tütün ve alkollü içki — makam ve altı ay (doğru olan) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="DOĞRU",
z="Z",
madde=MD + " md. 8; 5607 sayılı Kaçakçılıkla Mücadele Kanunu md. 16",
cek="Bandrollü tütün ve alkollü içkide tasfiye kararı soruşturmada elkoyan idarece hâkimden, kovuşturmada müdahil idarece mahkemeden istenir; altı ayda karar yoksa numuneyle imha.",
kok=[YA + "'ne göre ambalajlarında kamu kurumlarınca uygulanan bandrol, etiket, hologram, pul, damga veya benzeri işaret bulunan tütün ve tütün mamulleri ile alkollü içkilerin imhasına ilişkin aşağıdakilerden hangisi doğrudur?"],
d="Kovuşturma aşamasında, imha için tasfiye kararı verilmesini mahkemeden talep etme görevi müdahil idareye aittir.",
c=["Soruşturma aşamasında, imha için tasfiye kararı verilmesini hâkimden talep etme görevi müdahil idareye aittir.",
   "Elkoyma tarihinden itibaren bir ay içinde adli mercilerce karar bildirilmemesi hâlinde eşya derhal imha edilir.",
   "Tasfiye kararının talep edildiği tarihten itibaren altı ay içinde adli mercilerce karar bildirilmemesi hâlinde eşya imha edilir.",
   "Adli mercilerce süresinde karar bildirilmemesi hâlinde eşya, numune alınmaksızın derhal imha edilir."],
sirali=False,
g="Yönetmeliğe göre ambalajında kamu kurumlarınca uygulanan bandrol veya benzeri işaret bulunan tütün ve tütün mamulleri ile alkollü içkiler için, 5607 sayılı Kanunun tasfiye kararına ilişkin hükmü uyarınca, el konulmasını müteakip soruşturma aşamasında elkoyan idarece hâkimden, kovuşturma aşamasında müdahil idarece mahkemeden imhası yapılmak üzere tasfiye kararı verilmesi derhal talep edilir. Elkoyma tarihinden itibaren altı ay içinde adli mercilerce herhangi bir karar bildirilmemişse Yönetmelikte belirtilen miktarlarda numune alınarak eşya derhal imha edilir. Buna göre soruşturma aşamasında talep müdahil idarenin değil elkoyan idarenin görevidir; süre bir ay değil altı aydır ve tasfiye kararının talep edildiği tarihten değil elkoyma tarihinden başlar; imhadan önce numune alınması zorunludur. Bir aylık süre, 5607 sayılı Kanunda eşyanın zarara uğraması, değerinde esaslı kayıp tehlikesi veya muhafazasının ciddi külfet oluşturması hâlinde tasfiye kararı için öngörülen süredir. En güçlü çeldirici soruşturma aşamasını müdahil idareye bağlayan seçenektir: iki aşamanın makam ve merci çiftleri birbirinden ayrıdır. Bu nedenle doğru cevap 'Kovuşturma aşamasında, imha için tasfiye kararı verilmesini mahkemeden talep etme görevi müdahil idareye aittir.' seçeneğidir. (MD 8; 5607 sayılı Kanun md. 16)",
kanit=Y + " | elkonulmasını müteakip soruşturma aşamasında elkoyan idarece hakimden, kovuşturma aşamasında müdahil idarece mahkemeden imhası yapılmak üzere tasfiye kararı verilmesi derhal talep edilir || " + Y + " | Elkoyma tarihinden itibaren altı ay içinde adli mercilerce herhangi bir karar bildirilmemiş olması halinde, 7 nci maddede belirtilen miktarlarda numune alınarak eşya derhal imha edilir || " + KN + " | muhafazasının ciddi külfet oluşturması halinde bir ay içinde",
yuva=["Aynı fıkra: soruşturma aşamasında talep elkoyan idarece hâkimden yapılır (idare yer değiştirmiş)",
      "5607 sayılı Kanun: zarar veya değer kaybı tehlikesinde tasfiye kararı için bir ay",
      "Aynı fıkra: altı aylık süre elkoyma tarihinden başlar (başlangıç kaydırılmış)",
      "Aynı fıkra: imhadan önce belirtilen miktarlarda numune alınır (unsur düşürülmüş)"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "BAŞLANGIÇ", "KOMŞU"], duzey=["AYIRT"], profil=[1, 2],
olumsuz=False, vaka=False, baslangic=True, eksen=0,
ayna="SB52-B bandrollü alkollü içki: genel kural altı ay ve adli merci kararı (soru 10) ↔ 'uygun değildir' raporunda beklemeden imha (soru 11)",
guncellik="", cikmis="", kapsamli=False,
),

# 11 ---------------- md. 8/3: "uygun değildir" raporu — altı ay beklenmeden imha (vaka) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="OLAY",
z="Z",
madde=MD + " md. 8",
cek="Bandrollü alkollü içkiye Tarım ve Orman Bakanlığı veya akredite laboratuvarca 'uygun değildir' raporu verilirse altı ay ve adli karar beklenmeden numuneyle imha edilir.",
kok=["Kaçakçılığı önleme, izleme ve araştırmakla görevli bir birim, 3 Mart tarihinde ambalajlarında kamu kurumlarınca uygulanan bandrol bulunan 400 şişe alkollü içkiye 5607 sayılı Kanun uyarınca el koymuş ve soruşturma aşamasında hâkimden imhası yapılmak üzere tasfiye kararı verilmesini talep etmiştir. Elkoyan birimce Tarım ve Orman Bakanlığına yaptırılan değerlendirme sonucunda 20 Nisan tarihinde eşya için \"uygun değildir\" raporu verilmiştir. Bu tarih itibarıyla adli mercilerce herhangi bir karar bildirilmemiştir.",
     YA + "'ne göre bu eşya hakkında yapılacak işlem aşağıdakilerden hangisidir?"],
d="Elkoyma tarihinden itibaren altı ayın dolması ve adli merci kararı beklenmeksizin, Yönetmelikte belirtilen miktarlarda numune alınarak eşya imha edilir.",
c=["Eşya, elkoyma tarihinden itibaren altı ay dolana kadar muhafaza edilir; bu süre içinde adli mercilerce karar bildirilmezse numune alınarak imha edilir.",
   "Rapor tarihinden itibaren bir ay içinde hâkim kararı beklenir; karar bildirilmezse eşya numune alınmaksızın imha edilir.",
   "Eşya, rapor üzerine Tarım ve Orman Bakanlığının ilgili birimlerine teslim edilir.",
   "Eşyanın imhası için kovuşturma aşamasına geçilmesi ve müdahil idarece mahkemeden tasfiye kararı talep edilmesi gerekir."],
sirali=False,
g="Yönetmeliğe göre bandrollü tütün mamulleri ve alkollü içkiler için genel kural, soruşturma aşamasında elkoyan idarece hâkimden tasfiye kararı istenmesi ve elkoyma tarihinden itibaren altı ay içinde adli mercilerce karar bildirilmemişse numune alınarak imha edilmesidir. Ancak ambalajında kamu kurumlarınca uygulanan bandrol bulunan alkollü içkilerden, elkoyan birimlerce Tarım ve Orman Bakanlığına veya bu Bakanlıktan Özel Gıda Kontrol Laboratuvarı Kuruluş Yeterlilik İzin Belgesi almış akredite laboratuvarlara yaptırılan değerlendirme sonucunda \"uygun değildir\" raporu verilenler, genel kuraldaki şartlar beklenmeksizin Yönetmelikte belirtilen miktarlarda numune alınarak imha edilir. Vakada rapor Tarım ve Orman Bakanlığınca verildiği için istisna uygulanır; altı aylık sürenin dolacağı 3 Eylül'ü veya adli merci kararını beklemeye gerek yoktur. Numune alınması bu istisnada da zorunludur. Tarım ve Orman Bakanlığı birimlerine teslim, gıda maddeleri ve canlı hayvanlar gibi eşyanın doğrudan teslimine ilişkindir; kovuşturma aşamasında müdahil idarece mahkemeden talep ise genel kuraldaki ikinci makam çiftidir. En güçlü çeldirici altı ayın beklenmesini öngören seçenektir: istisnayı görmeyen aday genel kuralı uygular. Bu nedenle doğru cevap 'Elkoyma tarihinden itibaren altı ayın dolması ve adli merci kararı beklenmeksizin, Yönetmelikte belirtilen miktarlarda numune alınarak eşya imha edilir.' seçeneğidir. (MD 8)",
kanit=Y + " | alkollü içkilerden elkoyan birimlerce Tarım ve Orman Bakanlığına veya Tarım ve Orman Bakanlığından Özel Gıda Kontrol Laboratuvarı Kuruluş Yeterlilik İzin Belgesi almış akredite laboratuvarlara yaptırılan değerlendirme sonucunda || " + Y + " | \"uygun değildir\" raporu verilenler, ikinci fıkrada belirtilen şartlar beklenmeksizin 7 nci maddede belirtilen miktarlarda numune alınarak imha edilir || " + Y + " | Elkoyma tarihinden itibaren altı ay içinde adli mercilerce herhangi bir karar bildirilmemiş olması halinde || " + Y + " | Gıda maddeleri, gıda takviyeleri, hayvansal ürünler, bitki ve hayvan sağlığına ilişkin ilaçlar, su ürünleri ve canlı hayvanlar; Tarım ve Orman Bakanlığının ilgili birimlerine",
yuva=["Aynı madde, genel kural: elkoyma tarihinden itibaren altı ay içinde karar bildirilmezse numune alınarak imha",
      "5607 sayılı Kanun: tehlike hâlinde tasfiye kararı için bir aylık süre; numune alma zorunluluğu düşürülmüş",
      "Doğrudan teslim listesi: gıda maddeleri ve canlı hayvanların Tarım ve Orman Bakanlığı birimlerine teslimi",
      "Aynı madde, genel kural: kovuşturma aşamasında müdahil idarece mahkemeden tasfiye kararı talebi"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "KOMŞU", "BAŞLANGIÇ"], duzey=["UYGULAMA"], profil=[1, 3],
olumsuz=False, vaka=True, baslangic=False, eksen=0,
ayna="SB52-B bandrollü alkollü içki: genel kural altı ay ve adli merci kararı (soru 10) ↔ 'uygun değildir' raporunda beklemeden imha (soru 11)",
guncellik="", cikmis="", kapsamli=False,
),

# 12 ---------------- md. 8/4-7: imha usulü — önermeli (I, III ve IV); meslek yanlılığı II ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="ÖNERMELİ",
z="Z",
madde=MD + " md. 8",
cek="İmhada Çevre Kanunu gözetilir; lisanssız imhada Bakanlık taşra teşkilatı ve belediyeden birer kişi çağrılır; video kaydı beş yıl saklanır; işletme müdürlüğü imkânı kullanılabilir.",
kok=[YA + "'nin imha veya bertaraf işlemlerine ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. İmha veya bertaraf işlemlerinde, 2872 sayılı Çevre Kanunu ve bu Kanuna dayanılarak yürürlüğe konulan düzenlemeler çerçevesinde çevreye zarar vermeyen yöntemlerin kullanılması gerekir.",
     "II. Çevre, Şehircilik ve İklim Değişikliği Bakanlığından lisans almış firmalara teslim edilmeksizin yapılan imhalarda, eşya sahibi ile temsilcisi gümrük müşavirinin hazır bulunması için bildirimde bulunulur.",
     "III. Eşyanın bulunduğu yerdeki durumundan imha aşamalarına kadar imha komisyonunca alınan video kayıtları, elektronik ortamda beş yıl süreyle muhafaza edilir.",
     "IV. İmha yapılırken elkoyan birimin imkânlarının yeterli olmaması hâlinde varsa işletme müdürlüklerinin teknik ve fiziki imkânları, araç ve gereçleri kullanılabilir.",
     "Yukarıdaki ifadelerden hangileri doğrudur?"],
d="I, III ve IV",
c=["I ve II", "II ve III", "III ve IV", "I, II, III ve IV"],
sirali=False,
g="Yönetmeliğe göre imha veya bertaraf işlemlerinde 2872 sayılı Çevre Kanunu ve bu Kanuna dayanılarak yürürlüğe konulan düzenlemeler çerçevesinde insan, hayvan, bitki ve çevre sağlığı gözetilerek çevreye zarar vermeyen yöntemler kullanılır (I doğru). Çevre, Şehircilik ve İklim Değişikliği Bakanlığından lisans almış firmalara teslim edilmeksizin yapılan imhalarda imhayı gerçekleştirecek idare, anılan Bakanlığın taşra teşkilatından ve ilgili belediyeden birer kişinin hazır bulunması için bildirimde bulunur; bunlar katılmazsa imha komisyonunca işlem gerçekleştirilir. Eşya sahibinin veya gümrük müşavirinin hazır bulundurulmasına ilişkin bir hüküm yoktur (II yanlış). Eşyanın bulunduğu yerdeki durumu, nakliye aracına yüklenmesi, imha mahalline boşaltılması ve imha aşamaları imha komisyonunca video kaydına alınır ve kayıtlar elektronik ortamda beş yıl süreyle muhafaza edilir (III doğru). Elkoyan birimin imkânları yetersizse varsa işletme müdürlüklerinin teknik ve fiziki imkânları, araç ve gereçleri kullanılabilir (IV doğru). En güçlü çeldirici 'I, II, III ve IV' seçeneğidir: gümrükle ilgili her işlemde müşavirin bulunacağı önyargısı II'yi doğru gösterir; oysa Yönetmelik hazır bulunacakları Bakanlık taşra teşkilatı ve belediye olarak belirlemiştir. Bu nedenle doğru cevap 'I, III ve IV' seçeneğidir. (MD 8)",
kanit=Y + " | 2872 sayılı Çevre Kanunu ve bu Kanuna dayanılarak yürürlüğe konulan düzenlemeler çerçevesinde || " + Y + " | çevreye zarar vermeyen yöntemlerin kullanılması gerekir || " + Y + " | imhayı gerçekleştirecek idarece mezkur Bakanlığın taşra teşkilatından ve ilgili belediyeden birer kişinin imha veya bertaraf işlemi sırasında hazır bulunması için bildirimde bulunulur || " + Y + " | Bunlardan katılım olmaması halinde imha komisyonunca, imha veya bertaraf işlemi gerçekleştirilir || " + Y + " | bu kayıtlar elektronik ortamda beş yıl süreyle muhafaza edilir || " + Y + " | birimin imkânlarının yeterli olmaması halinde varsa işletme müdürlüklerinin teknik ve fiziki imkânları, araç ve gereçleri kullanılabilir",
yuva=["I ve II: hazır bulunacakları sağduyuyla müşavire genişleten, video kayıt süresini ve işletme müdürlüğü imkânını bilmeyen aday",
      "II ve III: Çevre Kanunu atfını ve işletme müdürlüğü imkânını bilmeyen, müşavir önyargısı taşıyan aday",
      "III ve IV: imhada Çevre Kanunu çerçevesinin gözetileceğini bilmeyen aday",
      "I, II, III ve IV: hazır bulunacakların Bakanlık taşra teşkilatı ve belediye olduğunu bilmeyip müşavirin her işlemde bulunacağını sanan aday"],
yakinlik="BİREBİR",
tuzak=["SAĞDUYU", "KOMŞU", "UNSUR"], duzey=["AYIRT"], profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="",
cikmis="", kapsamli=False,
),

# 13 ---------------- md. 10: imha komisyonu — gönderim yerleri yer değiştirmiş (yanlıştır köklü önermeli) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="ÖNERMELİ",
z="Z",
madde=MD + " md. 10",
cek="İmha komisyonu başkan ve en az iki üyedir; imha tutanakları soruşturmayı yürüten adli birimlere, tüm işlem belgeleri davaya müdahil gümrük idaresine gönderilir.",
kok=[YA + "'ne göre imha komisyonunun kuruluşu, görevleri ve çalışmasına ilişkin aşağıdaki ifadeler verilmiştir:",
     "I. İmha komisyonu, ilgili idare amirinin görevlendireceği başkan ve en az iki üyeden oluşur.",
     "II. İmha işlemleri sırasında güvenliğe ve yangın önlemeye ilişkin önlemler imha komisyonu tarafından alınır.",
     "III. İmha tutanakları ve bunlara ilişkin belgeler, imhayı gerçekleştiren idarece davaya müdahil gümrük idaresine gönderilir.",
     "IV. Komisyonca yapılan tüm işlemlere ilişkin bilgi ve belgeler, soruşturmayı yürüten adli birimlere gönderilir.",
     "Yukarıdaki ifadelerden hangileri yanlıştır?"],
d="III ve IV",
c=["I ve III", "II ve IV", "I, II ve III", "II, III ve IV"],
sirali=False,
g="Yönetmeliğe göre imha edilmesi gereken eşyanın işlemlerini gerçekleştirecek imha komisyonu, ilgili idare amirinin görevlendireceği başkan ve en az iki üyeden oluşur (I doğru). İmha işlemleri sırasında güvenliğe ve yangın önlemeye ilişkin önlemler imha komisyonu tarafından alınır (II doğru). İmha Kararı ve İmha/Bertaraf Tutanağı, komisyon başkan ve üyelerinin adları, soyadları ve görev unvanları belirtilerek imzalanır. İmha tutanakları ve bunlara ilişkin belgeler, imhayı gerçekleştiren idarece soruşturmayı yürüten adli birimlere gönderilir; davaya müdahil gümrük idaresine değil (III yanlış). Komisyonca yapılan tüm işlemlere ilişkin bilgi ve belgeler ise davaya müdahil gümrük idaresine gönderilir; soruşturmayı yürüten adli birimlere değil (IV yanlış). Kök yanlış olanları sorduğu için doğru kombinasyon III ve IV'tür. En güçlü çeldirici 'I ve III' seçeneğidir: imha komisyonunu, piyasa araştırmasına gerek olmayan hâllerdeki en az üç kişilik tespit komisyonuyla karıştıran aday I'i yanlış sanar. Bu nedenle doğru cevap 'III ve IV' seçeneğidir. (MD 10, 16)",
kanit=Y + " | imha komisyonu, ilgili idare amirinin görevlendireceği başkan ve en az iki üyeden oluşur || " + Y + " | İmha işlemleri sırasında güvenliğe ve yangın önlemeye ilişkin önlemler imha komisyonu tarafından alınır || " + Y + " | İmha tutanakları ve bunlara ilişkin belgeler, imhayı gerçekleştiren idarece soruşturmayı yürüten adli birimlere gönderilir || " + Y + " | Komisyonca yapılan tüm işlemlere ilişkin bilgi ve belgeler, davaya müdahil gümrük idaresine gönderilir || " + Y + " | en az üç kişilik bir komisyon tarafından tespit edilmesi",
yuva=["I ve III: imha komisyonunu tek kaynak tespitindeki en az üç kişilik komisyonla karıştırıp I'i yanlış sanan aday",
      "II ve IV: güvenlik ve yangın önlemlerinin komisyona ait olduğunu bilmeyen aday",
      "I, II ve III: IV'teki gönderim yerinin yer değiştirdiğini görmeyen, komisyon yapısını da yanlış bilen aday",
      "II, III ve IV: güvenlik önlemleri hükmünü bilmeyen aday"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "TERSİNE", "KOMŞU"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=True, vaka=False, baslangic=False, eksen=0,
ayna="",
guncellik="", cikmis="", kapsamli=False,
),

# 14 ---------------- md. 5/1, 5/2, 5/6: teslim — yükleme ve nakliye hizmetini elkoyan birim sağlar (yanlış olan) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="YANLIŞ",
z="O",
madde=MD + " md. 5",
cek="Eşya, taşıt ve numuneler öncelikle en yakın gümrük idaresine teslim edilir; muhafaza yerine kadar yükleme, boşaltma ve nakliye hizmetini elkoyan/alıkoyan birim sağlar.",
kok=[YA + "'ne göre kaçak zannı ile elkonulan eşya ve alıkonulan taşıtların teslimine ilişkin aşağıdakilerden hangisi yanlıştır?"],
d="Eşyanın muhafaza edileceği yere kadar yüklenmesi, boşaltılması veya nakliyesi gibi hizmetler, eşyayı teslim alacak gümrük idaresince sağlanır.",
c=["Elkonulan eşya, alıkonulan taşıtlar ve numuneler öncelikle en yakın gümrük idaresine teslim edilir.",
   "Gümrük ve işletme müdürlüğünün aynı yerde bulunması hâlinde teslim, bünyesinde kaçak eşya depolama yeri bulunan idareye yapılır.",
   "Taşıtın tesliminde, ayırt edici özelliklerini belirten Taşıt Tespit ve Teslim-Tesellüm Tutanağı düzenlenir.",
   "Yönetmelikte öngörülen yerlere teslimi mümkün olmayan eşyanın yediemin olarak teslimi mümkündür."],
sirali=False,
g="Yönetmeliğe göre kaçak zannı ile elkonulan eşya, alıkonulan taşıtlar ve numuneler öncelikle en yakın gümrük idaresine; gümrük ve işletme müdürlüğünün aynı yerde bulunması hâlinde bünyesinde kaçak eşya depolama yeri bulunan idareye teslim edilir. Eşyanın muhafaza edileceği yere kadar yüklenmesi, boşaltılması veya nakliyesi gibi hizmetler, eşyayı teslim alacak gümrük idaresince değil, elkoyan/alıkoyan birimlerce sağlanır; seçenekte hizmeti sağlayan birim değiştirilmiştir. Eşya veya taşıtın tesliminde miktarı, cinsi, markası, tipi, modeli, seri numarası gibi ayırt edici özelliklerini belirten Kaçak Eşya Teslim Tutanağı veya Taşıt Tespit ve Teslim-Tesellüm Tutanağı düzenlenir. Sayılan yerlere teslimi mümkün olmayan eşyanın yediemin olarak teslimi de mümkündür. Nakil için de önce eşyanın elkonulduğu araç ile elkoyan idareye veya gümrük idaresine ait uygun araçlar kullanılır. En güçlü tuzak, eşyanın gümrük idaresine teslim edilmesinden hareketle taşıma hizmetinin de teslim alan idareye ait olduğunu düşünmektir. Bu nedenle doğru cevap 'Eşyanın muhafaza edileceği yere kadar yüklenmesi, boşaltılması veya nakliyesi gibi hizmetler, eşyayı teslim alacak gümrük idaresince sağlanır.' seçeneğidir. (MD 5, 15)",
kanit=Y + " | Kaçak zannı ile elkonulan eşya, alıkonulan taşıtlar ve numuneler öncelikle || " + Y + " | en yakın gümrük idaresine, gümrük ve işletme müdürlüğünün aynı yerde bulunması halinde bünyesinde kaçak eşya depolama yeri bulunan idareye teslim edilir || " + Y + " | Eşyanın muhafaza edileceği yere kadar yüklenmesi, boşaltılması veya nakliyesi gibi hizmetler elkoyan/alıkoyan birimlerce sağlanır || " + Y + " | Taşıt Tespit ve Teslim-Tesellüm Tutanağı düzenlenir || " + Y + " | Yukarıdaki fıkralara göre teslimi mümkün olmayan eşyanın, yediemin olarak teslimi mümkündür || " + Y + " | elkoyan idareye veya gümrük idaresine ait uygun araç olması durumlarında öncelikle bu imkânlar kullanılır",
yuva=["Eşyanın teslimi: eşya, taşıt ve numuneler öncelikle en yakın gümrük idaresine teslim edilir (doğru)",
      "Aynı fıkra: gümrük ve işletme müdürlüğü aynı yerdeyse kaçak eşya depolama yeri bulunan idareye teslim (doğru)",
      "Aynı madde: taşıt tesliminde Taşıt Tespit ve Teslim-Tesellüm Tutanağı (doğru)",
      "Aynı madde: sayılan yerlere teslimi mümkün olmayan eşyanın yediemin olarak teslimi (doğru)"],
yakinlik="BİREBİR",
tuzak=["MAKAM", "TERSİNE", "KOMŞU"], duzey=["AYIRT"], profil=[4, 1],
olumsuz=True, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="",
cikmis="", kapsamli=False,
),

# 15 ---------------- md. 11/1-a: iade kararında muhafaza süresi — teslimden, tebliği izleyen 30. güne (vaka) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="SÜRE",
z="Z",
madde=MD + " md. 11",
cek="Muhafaza süresi depoya teslimden başlar; iade kararında, kararın sahibine tebliğini izleyen otuzuncu günü geçmemek üzere teslim alınana kadar sürer.",
kok=["Kaçak zannı ile 5 Ocak tarihinde elkonulan bir eşya, 10 Ocak tarihinde muhafaza edileceği yere teslim edilmiştir. Yargı mercilerince eşyanın sahibine iadesine karar verilmiş, iade kararı müdahil idarece eşya sahibine 1 Mart tarihinde tebliğ edilmiştir. Eşya sahibi eşyayı 20 Nisan tarihinde muhafaza edildiği yerden teslim almıştır.",
     YA + "'ne göre bu eşyanın muhafaza süresi aşağıdakilerden hangisidir?"],
d="10 Ocak ile 31 Mart tarihleri arasında geçen süre",
c=["5 Ocak ile 31 Mart tarihleri arasında geçen süre",
   "10 Ocak ile 1 Mart tarihleri arasında geçen süre",
   "10 Ocak ile 20 Nisan tarihleri arasında geçen süre",
   "1 Mart ile 31 Mart tarihleri arasında geçen süre"],
sirali=False,
g="Yönetmeliğe göre muhafaza süresi, kaçak zannı ile elkonulan eşyanın muhafaza edileceği yere teslim edildiği tarihten başlar. Yargı mercilerince iade kararı verilmişse süre, kararın müdahil idarece sahibine tebliğ edildiği tarihi takip eden otuzuncu günü geçmemek üzere eşyanın teslim alındığı tarihe kadar devam eder. Vakada süre elkoyma tarihi olan 5 Ocak'tan değil, muhafaza yerine teslim tarihi olan 10 Ocak'tan başlar. Tebliğ 1 Mart'ta yapıldığından takip eden otuzuncu gün 31 Mart'tır; eşya sahibi eşyayı 20 Nisan'da almış olsa da muhafaza süresi 31 Mart'ı aşamaz. 1 Mart ise sürenin bittiği değil, otuz günlük sürenin hesabına esas alınan tebliğ tarihidir. En güçlü çeldirici 20 Nisan'a kadar uzanan seçenektir: otuzuncu gün sınırını görmeyen aday fiilî teslim alma tarihini esas alır. Bu nedenle doğru cevap '10 Ocak ile 31 Mart tarihleri arasında geçen süre' seçeneğidir. (MD 11)",
kanit=Y + " | elkonulan eşya ile alıkonulan taşıtın muhafaza edileceği yere teslim edildiği tarihten başlamak üzere || " + Y + " | Yargı mercilerince verilen iade kararının müdahil idarece sahibine tebliğ edildiği tarihi takip eden otuzuncu günü geçmemek üzere teslim alındığı tarihe kadar || " + Y + " | geçen süre muhafaza süresidir",
yuva=["Muhafaza süresinin başlangıcı: elkoyma tarihi değil, muhafaza yerine teslim tarihi (başlangıç kaydırılmış)",
      "İade kararının tebliğ tarihi: otuz günlük sürenin hesabına esas tarihtir, muhafaza süresinin sonu değildir",
      "Muhafaza süresi: otuzuncu gün sınırı göz ardı edilip fiilî teslim alma tarihi esas alınmış",
      "Tebliğ tarihi muhafaza süresinin başlangıcı sanılmış (başlangıç kaydırılmış)"],
yakinlik="ÇIKARIM",
tuzak=["BAŞLANGIÇ", "SAYI", "İSTİSNA"], duzey=["UYGULAMA"], profil=[2, 1],
olumsuz=False, vaka=True, baslangic=True, eksen=0, ayna="", guncellik="",
cikmis="", kapsamli=False,
),

# 16 ---------------- Ek-8 (b), (c), (d): muhafaza ücreti — yüzde on beş tavanı saklı (hesap) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="HESAP",
z="Z",
madde=MD + " md. 3, 11, 12; Ek-8",
cek="Taşıt dışı eşyada günlük binde bir uygulanır; muhafaza ücreti eşya değerinin yüzde on beşini ve her hâlükârda 100.000 TL'yi geçemez.",
kok=["Kaçak zannı ile elkonulan ve korunması özel tesis veya tertibat gerektirmeyen bir ithal eşyası gümrük idaresi dışındaki bir depoda muhafaza edilmiş; eşyanın muhafaza edileceği yere teslim edildiği tarihten gümrük idaresince teslim alındığı tarihe kadar 170 gün geçmiştir. Eşya için mahkemece bir bedel belirlenmemiş olup kaçak eşyaya mahsus tespit tutanağında yer alan CIF değeri 500.000 TL'dir.",
     YA + " ve eki ücret tarifesine göre bu eşya için ödenecek muhafaza ücreti kaç TL'dir?"],
d="75.000",
c=["42.500", "85.000", "100.000", "340.000"],
sirali=True,
siklar=["42.500", "75.000", "85.000", "100.000", "340.000"],
g="Yönetmeliğe göre gümrük idaresince teslim alınan eşyanın muhafaza süresi, muhafaza edileceği yere teslim edildiği tarihten gümrük idaresince teslim alındığı tarihe kadar geçen süredir ve bu eşyanın muhafaza ücreti Yönetmeliğe ekli ücret tarifesine göre hesaplanır. Tarifeye göre taşıt haricindeki eşya için eşyanın değeri üzerinden günlük binde bir uygulanır; soğuk hava deposu gibi özel tesis ve tertibat gerektiren eşyada oran binde dörttür; altı aydan sonraki muhafaza süresi için ücretler yarısı oranında uygulanır. Muhafaza ücreti, eşya değerinin yüzde on beşini ve her hâlükârda 100.000 TL'yi geçemez. Eşyanın değeri, mahkemece bedel belirlenmediği için tespit tutanağındaki CIF değeri olan 500.000 TL'dir. Günlük ücret 500.000 × 1/1.000 = 500 TL; 170 gün için 500 × 170 = 85.000 TL'dir. Süre altı ayı aşmadığı için yarı oran uygulanmaz. Tavan 500.000 × %15 = 75.000 TL'dir ve 100.000 TL'lik mutlak sınırın altında kaldığı için bağlayıcı olan budur; ödenecek ücret 75.000 TL'dir. Ücret tarifesi ve bu tavan 26.05.2025 tarihli ve 32911 sayılı Resmî Gazete'de yayımlanan değişiklikle getirilmiştir; önceki metinde tavan eşya değerinin yüzde otuzuydu ve bu tavanla sonuç 85.000 TL olurdu. 42.500 TL altı ay dolmadan yarı oranı uygulayan, 100.000 TL mutlak sınırı ücret sanan, 340.000 TL ise özel tesis gerektirmeyen eşyaya binde dört uygulayıp tavanı da gözden kaçıran hesaptır. En güçlü çeldirici 85.000 TL'dir: günlük ücret doğru hesaplanmış, ancak yüzde on beş tavanı görülmemiştir. Bu nedenle doğru cevap '75.000' seçeneğidir. (MD 3, 11, 12; Ek-8)",
kanit=Y + " | Gümrük idaresince teslim alındığı veya gümrük idaresi dışındaki yerlerde satış haricindeki yöntemlerle tasfiye edilmesi durumunda ilgilisine teslim edildiği tarihe kadar || " + Y + " | Taşıt haricindeki eşya için, eşyanın değeri üzerinden günlük binde biri || " + Y + " | eşyanın muhafazasında muhafaza ücreti olarak eşyanın değerinin binde dördü uygulanır || " + Y + " | Altı aydan sonraki muhafaza süresi için bu ücretler yarısı oranında uygulanır || " + Y + " | eşya değerinin yüzde onbeşini ve her halükarda 100.000 TL'yi geçemez || " + Y + " | bedel belirlenmemiş ise kaçak eşyaya mahsus tespit tutanağında yer alan ihraç eşyası için FOB, ithal eşyası için CIF değerini || " + Y + " | Muhafaza ücreti eşya veya taşıtın değerinin yüzde otuzunu geçemez",
yuva=["42.500: altı ay dolmadan tarifedeki 'altı aydan sonraki süre için yarı oran' kuralı uygulanmış",
      "85.000: günlük binde bir doğru, yüzde on beş tavanı uygulanmamış (değişiklik öncesi yüzde otuz tavanıyla da sonuç budur)",
      "100.000: tarifedeki her hâlükârda aşılamayacak mutlak sınır ücretin kendisi sanılmış",
      "340.000: özel tesis gerektiren eşyaya ait binde dört oranı uygulanmış, tavan da görülmemiş"],
yakinlik="ÇIKARIM",
tuzak=["İSTİSNA", "AD-HESAP", "YAKIN-SAYI"], duzey=["UYGULAMA"], profil=[2, 5],
olumsuz=False, vaka=True, baslangic=False, eksen=0,
ayna="SB52-D yüzde on beş: eşya değerinin %15'i ücret tavanı (soru 16) ↔ satış bedelinin %15'i ücret karşılığı (soru 18)",
guncellik="26.05.2025 / 32911 R.G. (Ek-8)", cikmis="", kapsamli=False,
),

# 17 ---------------- Ek-8 (a): taşıt ve konteyner günlük maktu ücreti — dolu konteyner 17 TL ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="ORAN-TUTAR",
z="O",
madde=MD + " md. 12; Ek-8",
cek="Günlük maktu ücret: dolu konteyner 17, boş konteyner 15, otomobil 10, tır-kamyon-otobüs ve iş makinesi 20, motosiklet 2 TL'dir.",
kok=[YA + " eki ücret tarifesine göre, Yönetmelik kapsamında muhafaza edilen dolu bir konteyner için adet başına uygulanacak günlük maktu muhafaza ücreti (KDV dahil) kaç TL'dir?"],
d="17",
c=["2", "10", "15", "20"],
sirali=True,
siklar=["2", "10", "15", "17", "20"],
g="Yönetmeliğe ekli ücret tarifesine göre, Yönetmelik kapsamında muhafaza edilen motorlu taşıt ve konteynerler için KDV dahil günlük maktu ücretler şöyledir: iş makineleri ile tır çekicisi, dorse, tanker, kamyon ve otobüs adet başına 20 TL; minibüs, midibüs, karavan, traktör ve kamyonet adet başına 15 TL; otomobil, diğer motorlu binek ve yük vasıtaları adet başına 10 TL; motosikletler, motorlu bisikletler ve oto römorkları adet başına 2 TL; engellilere mahsus araçlar adet başına 1 TL; boş konteyner adet başına 15 TL; dolu konteyner adet başına 17 TL; deniz ve hava taşıtları için uzunluk esas alınarak metre başına 2 TL. Dolu konteyner için günlük ücret 17 TL'dir. Bu tarife 26.05.2025 tarihli değişiklikle Yönetmeliğe eklenmiştir ve altı aydan sonraki muhafaza süresi için yarısı oranında uygulanır. En güçlü çeldirici 15 TL'dir: aynı tablodaki boş konteyner ücretidir. Bu nedenle doğru cevap '17' seçeneğidir. (MD 12; Ek-8)",
kanit=Y + " | günlük ücret tarifesi (KDV Dahil) (TL) || " + Y + " | Dolu konteyner adet başına | 17 || " + Y + " | Boş konteyner adet başına | 15 || " + Y + " | Otomobil, diğer motorlu binek ve yük vasıtaları adet başına | 10 || " + Y + " | Tır çekicisi, dorse, tanker, kamyon ve otobüs adet başına | 20 || " + Y + " | Motosikletler, motorlu bisikletler ve oto römorkları adet başına | 2 || " + Y + " | Ek-8 (26.05.2025 / 32911 R.G. ile eklenmiştir)",
yuva=["2: motosiklet, motorlu bisiklet ve oto römorkları (deniz ve hava taşıtlarında da metre başına 2)",
      "10: otomobil, diğer motorlu binek ve yük vasıtaları",
      "15: boş konteyner (minibüs, midibüs, karavan, traktör ve kamyonet de 15)",
      "20: iş makineleri ile tır çekicisi, dorse, tanker, kamyon ve otobüs"],
yakinlik="BİREBİR",
tuzak=["YAKIN-SAYI", "SAYI", "KOMŞU"], duzey=["HATIRLAMA"], profil=[2],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="",
cikmis="", kapsamli=False,
),

# 18 ---------------- md. 12, 14/1: masraflar ve muhafaza ücreti — önermeli (Yalnız II) ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="ÖNERMELİ",
z="Z",
madde=MD + " md. 12, 14",
cek="Masraflar döner sermayeden, Kamu İhale Kanunu uygulanmadan karşılanır; satışla tasfiyede satış bedelinin %15'i ödenir, süreye göre paylaştırılır; sahibine yediemine ödeme yok.",
kok=[YA + "'nin masrafların karşılanması ve muhafaza ücretlerine ilişkin hükümleri çerçevesinde aşağıdaki ifadeler verilmiştir:",
     "I. Elkonulan eşyanın el konulduğu andan itibaren yapılan muhafaza, nakliye ve imha masrafları döner sermaye gelirlerinden karşılanır ve bu kapsamdaki mal ve hizmet alımlarında 4734 sayılı Kamu İhale Kanunu hükümleri uygulanır.",
     "II. Gümrük idaresi dışındaki yerlerde satış yoluyla tasfiye edilen eşyada, muhafaza ücreti karşılığı olarak satış bedelinin yüzde on beşi ödenir.",
     "III. Satış yoluyla tasfiye edilen eşyanın farklı depolama yerlerinde muhafaza edilmesi durumunda muhafaza ücreti, depolama yerleri arasında eşit olarak paylaştırılır.",
     "IV. Sahibine yediemin olarak verilen eşya ve taşıt için de muhafaza ücreti, muhafaza ücretlerine ilişkin usul ve esaslara göre tespit edilerek ödenir.",
     "Yukarıdaki ifadelerden hangisi veya hangileri doğrudur?"],
d="Yalnız II",
c=["I ve II", "II ve IV", "II, III ve IV", "I, II, III ve IV"],
sirali=False,
g="Yönetmeliğe göre kaçak akaryakıt hariç elkonulan veya alıkonulan her türlü eşya ve taşıtın muhafazası, depolanması, yüklenmesi, boşaltılması, nakliyesi ve imhası gibi nedenlerle el konulduğu andan itibaren yapılan masraflar döner sermaye gelirlerinden karşılanır; ancak bu kapsamdaki mal, araç, gereç ve hizmet alımlarında 4734 sayılı Kamu İhale Kanunu hükümleri uygulanmaz (I yanlış). Gümrük idaresi dışındaki yerlerde satış yoluyla tasfiye edilen eşyada muhafaza ücreti karşılığı olarak satış bedelinin yüzde on beşi ödenir (II doğru). Eşya veya taşıtın farklı depolama yerlerinde muhafaza edilmesi durumunda bu ücret eşit olarak değil, muhafaza süreleri dikkate alınarak paylaştırılır (III yanlış). Yediemin olarak teslimde de muhafaza ücreti aynı usul ve esaslara göre tespit edilip ödenir; ancak sahibine yediemin olarak verilen eşya ve taşıt için herhangi bir ödeme yapılmaz (IV yanlış). Satış bedelinin yüzde on beşi olan bu ücret, ücret tarifesindeki eşya değerinin yüzde on beşi olarak belirlenen tavanla karıştırılmamalıdır. En güçlü çeldirici 'II ve IV' seçeneğidir: yediemin teslimde ücret ödenmesi kuralı, eşyanın sahibine yediemin olarak bırakıldığı istisnaya da uygulanırsa IV doğru sanılır. Bu nedenle doğru cevap 'Yalnız II' seçeneğidir. (MD 12, 14)",
kanit=Y + " | konulduğu andan itibaren yapılan masraflar, döner sermaye || " + Y + " | Bu kapsamda yapılacak her türlü mal, araç, gereç ve hizmet alımlarında 4/1/2002 tarihli ve 4734 sayılı Kamu İhale Kanunu hükümleri uygulanmaz || " + Y + " | eşyanın muhafaza ücreti karşılığı olarak satış bedelinin yüzde onbeşi ödenir || " + Y + " | söz konusu ücret, muhafaza süreleri dikkate alınarak paylaştırılır || " + Y + " | Eşya ve taşıtın yediemin olarak tesliminde de muhafaza ücreti || " + Y + " | Sahibine yediemin olarak verilen eşya ve taşıt için herhangi bir ödeme yapılmaz",
yuva=["I ve II: masraflarda Kamu İhale Kanununun uygulanmayacağını bilmeyen aday",
      "II ve IV: yediemin teslimdeki ödeme kuralını sahibine yediemin bırakılan eşyaya da uygulayan aday",
      "II, III ve IV: paylaştırmanın muhafaza sürelerine göre yapıldığını ve sahibine yediemin istisnasını bilmeyen aday",
      "I, II, III ve IV: dört hükümde de tek unsurun değiştirildiğini fark etmeyen aday"],
yakinlik="BİREBİR",
tuzak=["TERSİNE", "KOMŞU", "İSTİSNA"], duzey=["AYIRT"], profil=[1, 4],
olumsuz=False, vaka=False, baslangic=False, eksen=0,
ayna="SB52-D yüzde on beş: eşya değerinin %15'i ücret tavanı (soru 16) ↔ satış bedelinin %15'i ücret karşılığı (soru 18)",
guncellik="", cikmis="", kapsamli=False,
),

# 19 ---------------- md. 14/2: iade kararında satış bedeli — kanuni faiz elkoyma tarihinden ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="SONUÇ",
z="O",
madde=MD + " md. 12, 14",
cek="Satılıp bedeli emanete alınan eşyanın iadesinde satış bedeli, elkoyma tarihinden iade tarihine kadar kanuni faiziyle döner sermaye bütçesinden ödenir.",
kok=[YA + "'ne göre satılarak bedeli emanet hesabına alınan eşya veya taşıtın sahibine iadesine karar verilmesi hâlinde, hak sahibine yapılacak ödeme aşağıdakilerden hangisinde doğru olarak verilmiştir?"],
d="Satış bedeli, elkoyma tarihinden iade tarihine kadar geçen süre için hesaplanan kanuni faiziyle birlikte döner sermaye bütçesinden ödenir.",
c=["Satış bedeli, satış tarihinden iade tarihine kadar geçen süre için hesaplanan kanuni faiziyle birlikte döner sermaye bütçesinden ödenir.",
   "Satış bedeli, elkoyma tarihinden iade tarihine kadar geçen süre için hesaplanan tecil faiziyle birlikte döner sermaye bütçesinden ödenir.",
   "Satış bedelinden muhafaza ücreti karşılığı olarak yüzde on beş düşüldükten sonra kalan tutar, faiz uygulanmaksızın ödenir.",
   "Satış bedeli, iade kararının tebliğ tarihinden ödeme tarihine kadar geçen süre için hesaplanan kanuni faiziyle birlikte döner sermaye bütçesinden ödenir."],
sirali=False,
g="Yönetmeliğe göre satılarak bedeli emanet hesabına alınan eşya ile taşıtın sahibine iadesine karar verilmesi hâlinde satış bedeli, Gümrük Kanunu ve Tasfiye Yönetmeliği hükümleri çerçevesinde elkoyma tarihinden iade tarihine kadar geçen süre için kanuni faizi ile birlikte döner sermaye bütçesinden hak sahibine ödenir. Faiz satış tarihinden veya iade kararının tebliğinden değil, elkoyma tarihinden işlemeye başlar ve faizin türü kanuni faizdir. Tebliğ tarihinden ödeme tarihine kadar kanuni faiz, Gümrük Kanununda geri verme kararının dört ay içinde uygulanmaması hâline ait bir kuraldır; tecil faizi ise Gümrük Kanununda ödeme süresinin uzatılmasında, Tasfiye Yönetmeliğinde ise satış bedelinin taksitlendirilmesinde alınan faizdir. Satış bedelinin yüzde on beşi, gümrük idaresi dışında satış yoluyla tasfiye edilen eşyada muhafaza edene ödenen muhafaza ücreti karşılığıdır; Yönetmelik iadede ödemeyi satış bedeli ve kanuni faiz üzerinden düzenler. En güçlü çeldirici faizi satış tarihinden başlatan seçenektir: bedel satışla emanete alınmış olsa da faiz elkoyma tarihinden işler. Bu nedenle doğru cevap 'Satış bedeli, elkoyma tarihinden iade tarihine kadar geçen süre için hesaplanan kanuni faiziyle birlikte döner sermaye bütçesinden ödenir.' seçeneğidir. (MD 12, 14)",
kanit=Y + " | Satılarak bedeli emanet hesabına alınan eşya ile taşıtın sahibine iadesine karar verilmesi halinde || " + Y + " | elkoyma tarihinden iade tarihine kadar geçen süre için kanuni faizi ile birlikte döner sermaye bütçesinden hak sahibine ödenir || " + Y + " | eşyanın muhafaza ücreti karşılığı olarak satış bedelinin yüzde onbeşi ödenir || 47-geri verme kaldırma.txt | tebliğ tarihinden ödemenin yapıldığı tarihe kadar geçen süre için geri verilecek tutar üzerinden || 45-tebliğ.txt | Uzatılan süre için 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanunun 48 inci maddesine göre tecil faizi alınır || 43-tasfiye.txt | Taksitlendirmede 21/7/1953 tarihli ve 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanuna göre tecil faizi alınır",
yuva=["Aynı fıkra: faiz elkoyma tarihinden işler (başlangıç satış tarihine kaydırılmış)",
      "Gümrük Kanunu ödeme süresinin uzatılması ve Tasfiye Yönetmeliği taksitlendirme hükümleri: tecil faizi (faiz türü değiştirilmiş)",
      "Muhafaza ücretleri: gümrük idaresi dışında satış yoluyla tasfiyede satış bedelinin yüzde on beşi muhafaza ücreti karşılığı",
      "Gümrük Kanunu geri verme: kararın dört ay içinde uygulanmaması hâlinde tebliğden ödeme tarihine kadar kanuni faiz"],
yakinlik="PARAFRAZ",
tuzak=["BAŞLANGIÇ", "KOMŞU", "TERİM"], duzey=["AYIRT"], profil=[1, 2],
olumsuz=False, vaka=False, baslangic=True, eksen=0, ayna="", guncellik="",
cikmis="", kapsamli=False,
),

# 20 ---------------- md. 3/m, 19: öngörülmeyen durumlarda yetki — Ticaret Bakanlığı ----------------
dict(
konu="Elkonulan Eşya ve Alıkonulan Taşıtlar Uygulama Yönetmeliği", blok="SB52",
kalip="YETKİ",
z="O",
madde=MD + " md. 3, 19",
cek="Yönetmelikte öngörülmeyen durumları inceleyip sonuçlandırmaya Ticaret Bakanlığı yetkilidir; elkonulan akaryakıt yönetmeliğinde Ticaret ve İçişleri Bakanlıkları yetkilidir.",
kok=[YA + "'nde düzenlenen hususlarla ilgili öngörülmeyen durumların ortaya çıkması hâlinde bunları inceleyip sonuçlandırmaya yetkili merci aşağıdakilerden hangisidir?"],
d="Ticaret Bakanlığı",
c=["Ticaret ve İçişleri Bakanlıkları",
   "Ticaret, İçişleri ve Hazine ve Maliye Bakanlıkları",
   "Gümrük ve dış ticaret bölge müdürlükleri",
   "Tasfiye işletme müdürlükleri"],
sirali=False,
g="Yönetmeliğe göre Yönetmelikte düzenlenen hususlarla ilgili öngörülmeyen durumların ortaya çıkması hâlinde bunları inceleyip sonuçlandırmaya Bakanlık yetkilidir; Yönetmelik 'Bakanlık' ifadesini Ticaret Bakanlığı olarak tanımlar. Yönetmelikte düzenlenen tutanak, karar ve harcama talimatının örneği ile ücret tarifesi de Bakanlığın resmî internet sitesinde yayımlanır. Elkonulan kaçak akaryakıta ilişkin ayrı uygulama yönetmeliğinde ise öngörülmeyen durumlarda konusuna göre Ticaret ve İçişleri Bakanlıkları yetkilidir; bu hüküm 18.01.2024 tarihli değişiklikten önce Ticaret, İçişleri ve Hazine ve Maliye Bakanlıklarını sayıyordu. Gümrük ve dış ticaret bölge müdürlükleri tasfiye işletme müdürlüklerinin sorumluluk alanlarını gösteren ek tabloda yer alır; tasfiye işletme müdürlükleri ise harcama talimatı ve ödeme belgesi işlemlerini yürütür. En güçlü çeldirici 'Ticaret ve İçişleri Bakanlıkları' seçeneğidir: kaçak akaryakıt yönetmeliğinin yetki hükmü bu Yönetmeliğe taşınırsa yanlış cevaba gidilir. Bu nedenle doğru cevap 'Ticaret Bakanlığı' seçeneğidir. (MD 3, 19)",
kanit=Y + " | inceleyip sonuçlandırmaya, Bakanlık || " + Y + " | Bakanlık: Ticaret Bakanlığını || " + Y + " | harcama talimatının örneği ile ücret tarifesi Bakanlığın resmî internet sitesinde yayımlanır || " + A + " | konusuna göre Ticaret ve İçişleri Bakanlıkları || " + A + ' | Hazine ve Maliye Bakanlıkları" ibaresi "Ticaret ve İçişleri Bakanlıkları" olarak 18.01.2024',
yuva=["Elkonulan akaryakıt yönetmeliği: öngörülmeyen durumlarda konusuna göre Ticaret ve İçişleri Bakanlıkları",
      "Elkonulan akaryakıt yönetmeliğinin 18.01.2024 öncesi hâli: Ticaret, İçişleri ve Hazine ve Maliye Bakanlıkları",
      "Ek-7: tasfiye işletme müdürlüklerinin sorumluluk alanları tablosundaki gümrük ve dış ticaret bölge müdürlükleri",
      "İşletme müdürlüğü tanımı: tasfiye işletme müdürlükleri (harcama talimatı ve ödeme belgesi işlemleri)"],
yakinlik="PARAFRAZ",
tuzak=["MAKAM", "KOMŞU"], duzey=["HATIRLAMA"], profil=[1, 3],
olumsuz=False, vaka=False, baslangic=False, eksen=0, ayna="", guncellik="",
cikmis="", kapsamli=False,
),
]
