# -*- coding: utf-8 -*-
# Her soru: tip, zorluk, tuzak, madde, cekirdek, kok (liste: paragraflar), dogru, celdiriciler, gerekce, tuzak_not, protB
Q = [
dict(tip="SÜ", z="K", tuzak="Süre kaydırma", madde="GK m.6/2",
 cek="Karar talebi: idare, başvurunun kendisine ulaştığı tarihten itibaren otuz gün içinde karar alır",
 kok=["Gümrük Kanunu uyarınca, gümrük mevzuatının uygulanmasına ilişkin karar talebinde gümrük idaresinin karar alma süresi ve bu sürenin başlangıcı aşağıdakilerden hangisinde doğru verilmiştir?"],
 d="Başvurunun gümrük idaresine ulaştığı tarihten itibaren otuz gün içinde karar alınır.",
 c=["Başvurunun gümrük idaresine ulaştığı tarihten itibaren otuz iş günü içinde karar alınır.",
    "Başvuru dilekçesinin kayda alındığı tarihten itibaren altmış gün içinde karar alınır.",
    "Eksik belgelerin tamamlandığı tarihi izleyen günden itibaren on beş gün içinde karar alınır.",
    "Başvuru tarihinden itibaren kırk beş gün içinde karar alınarak başvuru sahibine bildirilir."],
 g="Gümrük idareleri, karar talebine ilişkin başvurunun kendilerine ulaştığı tarihten itibaren otuz gün içinde karar alır. Mevzuatta bu süre \"otuz gün\" olarak belirlenmiştir; iş günü olarak nitelenmemiştir.",
 t="Süre \"otuz iş günü\"ne ya da başlangıç \"kayıt tarihi\"ne kaydırılmıştır. Süre takvim günüyle ifade edilmiştir ve başvurunun idareye ulaştığı tarihten başlar."),

dict(tip="DĞ", z="O", tuzak="Belge eşleştirme", madde="GK m.6/1, 6/2, 6/4; GY m.27/1",
 cek="Karar alınması talebinin yazılı olarak yapılması zorunludur",
 kok=["Gümrük mevzuatının uygulanmasına ilişkin karar talebi ve kararın verilmesi hakkında aşağıdaki ifadelerden hangisi yanlıştır?"],
 d="Karar alınması talebi yazılı veya sözlü olarak yapılabilir; sözlü talepler tutanağa bağlanır.",
 c=["Karar talep eden kişi, kararın verilebilmesi için gerekli bütün bilgi ve belgeleri idareye ibraz eder.",
    "Gümrük idarelerince verilen kararlar, başvuru sahibine yazılı olarak tebliğ edilir.",
    "Alınan kararlar, gümrük idareleri tarafından herhangi bir bekleme olmaksızın derhal uygulanır.",
    "Gerekli bilgi ve belgelerle başvuran her kişi, gümrük idaresinden karar vermesini isteyebilir."],
 g="Gümrük Kanunu karar alınması talebinin yazılı olarak yapılmasını zorunlu tutmuştur; sözlü talep öngörülmemiştir. Diğer şıklar Kanun ve Yönetmelik hükümleriyle örtüşmektedir.",
 t="Kararın tebliğinin yazılı olduğu bilinir; ancak talebin de yazılı olması gerektiği gözden kaçırılır."),

dict(tip="ÇI", z="O", tuzak="İstisna atlatma", madde="GK m.6/2 (ikinci paragraf)",
 cek="Süre aşımı: süre aşılabilir; süre dolmadan gerekçe ve gerekli ek süre başvuru sahibine bildirilir",
 kok=["Gümrük Kanunu uyarınca, gümrük idaresinin karar talebini öngörülen süre içinde sonuçlandırmasının mümkün olmadığı durumlara ilişkin olarak;",
      "I. Belirtilen süre aşılabilir.",
      "II. İdare, sürenin dolmasından önce başvuru sahibine süre aşımını haklı kılan gerekçeleri bildirir.",
      "III. İdare, talep hakkında karar vermek için gerekli gördüğü ek süreyi başvuru sahibine bildirir.",
      "IV. Süre aşıldığında talep reddedilmiş sayılır.",
      "ifadelerinden hangileri doğrudur?"],
 d="I, II ve III", c=["I ve II", "I, III ve IV", "II, III ve IV", "I, II, III ve IV"],
 g="Kanun, idarenin süreye uyamaması halinde sürenin aşılabileceğini; bu durumda sürenin dolmasından önce başvuru sahibine gerekçelerin ve gerekli görülen ek sürenin bildirileceğini düzenler. Süre aşımının talebin reddi sonucunu doğurduğuna dair bir hüküm yoktur.",
 t="IV. öncül, idari yargıdaki \"zımni ret\" mantığını çağrıştırır; Gümrük Kanunu'nda karar talebi için böyle bir sonuç öngörülmemiştir."),

dict(tip="UK", z="Z", tuzak="Tanım çiftleri", madde="GK m.6/2, 6/3",
 cek="Ret ve aleyhe kararlar gerekçeli alınır, itiraz yolunun açık olduğu kararda belirtilir",
 kok=["Gümrük idaresinden gümrük mevzuatının uygulanmasına ilişkin karar talep eden bir kişinin başvurusu reddedilmiştir.",
      "Gümrük Kanunu uyarınca bu ret kararına ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="Ret kararı gerekçeli olarak alınır, itiraz yolunun açık olduğu kararda belirtilir ve karar yazılı olarak tebliğ edilir.",
 c=["Ret kararı gerekçe gösterilmeksizin alınabilir; ancak itiraz yolunun açık olduğu kararda belirtilir ve karar tebliğ edilir.",
    "Ret kararına karşı itiraz yolu kapalıdır; başvuru sahibi yalnızca yeni bilgi ve belgelerle yeniden karar talebinde bulunabilir.",
    "Ret kararı gerekçeli olarak alınır; ancak kararın uygulanması itiraz süresi sona erinceye kadar ertelenir ve bu durum kararda belirtilir.",
    "Yalnızca muhatabı lehine olan kararlar gerekçeli alınır; ret kararları ise gerekçesiz olarak başvuru sahibine bildirilir."],
 g="Başvuruların reddine ve muhatabı aleyhine verilen yazılı kararlar, itiraz yolu açık olmak üzere gerekçeli olarak alınır ve bu hususlar kararda belirtilir. Verilen kararlar başvuru sahibine yazılı olarak tebliğ edilir.",
 t="Gerekçe zorunluluğu lehe kararlar için değil, ret ve aleyhe kararlar için öngörülmüştür; kararlar da itiraz süresi beklenmeden derhal uygulanır."),

dict(tip="ÇI", z="Z", tuzak="Eşik/oran kaydırma", madde="GK m.7/1",
 cek="Lehe kararın zorunlu iptali: yanlış/eksik bilgi + başvuranın bilmesi/bilmesi gerekmesi + doğru bilgiyle verilememe, üçü bir arada",
 kok=["Gümrük Kanunu uyarınca, gümrük idaresinin ilgilinin lehine olan bir kararının iptal edilmesi için;",
      "I. Kararın yanlış veya eksik bilgilere dayanılarak verilmiş olması",
      "II. Başvuru sahibinin bu yanlışlık veya eksikliği bilmesi veya bilmesi gerekmesi",
      "III. Kararın doğru veya tam bilgilere dayanılarak verilmesinin mümkün olmadığının tespit edilmesi",
      "IV. Lehine olan kararda öngörülen bir yükümlülüğe ilgilinin uymaması",
      "hallerinden hangilerinin bir arada bulunması gerekir?"],
 d="I, II ve III", c=["I ve III", "I, III ve IV", "II, III ve IV", "I, II, III ve IV"],
 g="Lehe kararın iptal edilmesi (zorunlu iptal) için yanlış veya eksik bilgiye dayanma, başvuru sahibinin bunu bilmesi veya bilmesi gerekmesi ve doğru bilgiyle kararın verilememesinin tespiti hallerinin bir arada bulunması gerekir. Yükümlülüğe uyulmaması ise ayrı bir fıkrada, değiştirme veya iptal edilebilme sebebi olarak düzenlenmiştir.",
 t="IV. öncül ikinci fıkradaki \"iptal edilebilir\" sebeplerindendir; birinci fıkradaki \"bir arada bulunma\" şartına dahil değildir."),

dict(tip="DY", z="O", tuzak="Tanım çiftleri", madde="GK m.7/2-a",
 cek="Karara esas koşulun gerçekleşmemesi/gerçekleşemez olması: lehe karar değiştirilir veya iptal edilebilir (ihtiyari)",
 kok=["Gümrük Kanunu'na göre, karara esas teşkil eden koşullardan birinin gerçekleşmemiş veya gerçekleşemez olması halinde ilgilinin lehine olan karar hakkında aşağıdakilerden hangisi doğrudur?"],
 d="Lehe olan karar değiştirilebilir veya iptal edilebilir.",
 c=["Lehe olan karar hiçbir koşul aranmaksızın iptal edilir.",
    "Lehe olan karar yalnızca değiştirilebilir, iptal edilemez.",
    "Lehe olan karar, ilgilinin bunu bilmesi şartıyla iptal edilir.",
    "Lehe olan karar geçerli kalır, yalnızca yeni işlemlere uygulanmaz."],
 g="Karara esas teşkil eden bir veya birden fazla koşulun gerçekleşmemiş veya gerçekleşemez olması halinde, ilgilinin lehine olan karar değiştirilir veya iptal edilebilir.",
 t="Birinci fıkradaki \"iptal edilir\" (zorunlu) ile ikinci fıkradaki \"değiştirilir veya iptal edilebilir\" ifadeleri birbirine karıştırılmaktadır."),

dict(tip="EŞ", z="ÇZ", tuzak="Süre kaydırma", madde="GK m.7/4",
 cek="Yürürlük: zorunlu iptal → iptal kararının verildiği tarih; değiştirme/iptal edilebilir hali → tebliğ tarihi",
 kok=["Gümrük Kanunu uyarınca, ilgilinin lehine olan kararların iptali veya değiştirilmesinde yürürlük tarihine ilişkin aşağıdaki eşleştirmelerden hangisi doğrudur?"],
 d="Bir arada bulunan hallere dayalı iptalde iptal kararının verildiği tarih; koşulun gerçekleşmemesi veya yükümlülüğe uyulmaması halinde tebliğ tarihi",
 c=["Bir arada bulunan hallere dayalı iptalde tebliğ tarihi; koşulun gerçekleşmemesi veya yükümlülüğe uyulmaması halinde iptal kararının verildiği tarih",
    "Her iki halde de iptal veya değiştirme kararının muhatabına tebliğ edildiği tarih; yürürlük tarihinin ertelenmesi hiçbir halde mümkün değildir",
    "Her iki halde de iptal veya değiştirme kararının verildiği tarih; istisnai hallerde idarece yürürlük tarihi geriye doğru yürütülebilir",
    "Bir arada bulunan hallere dayalı iptalde asıl kararın verildiği tarih; koşulun gerçekleşmemesi halinde tebliği izleyen otuzuncu gün"],
 g="Birinci fıkraya göre (hallerin bir arada bulunması) kararın iptali, iptal kararının verildiği tarihten; ikinci fıkraya göre verilen iptal veya değiştirme kararı ise tebliğ tarihinden itibaren yürürlüğe girer.",
 t="İki fıkranın yürürlük anları çapraz eşleştirilmiştir; ayrıca \"asıl kararın verildiği tarih\" ile \"iptal kararının verildiği tarih\" karıştırılmaktadır."),

dict(tip="DY", z="Z", tuzak="İstisna atlatma", madde="GK m.7/4 (ikinci cümle)",
 cek="İstisna: muhatabın yasal çıkarları gerektirirse yönetmelikle belirlenen koşullarda yürürlük tarihi ertelenebilir",
 kok=["Gümrük Kanunu'na göre, lehe kararın iptalinin veya değiştirilmesinin yürürlük tarihine ilişkin istisnai düzenleme aşağıdakilerden hangisidir?"],
 d="Karar muhatabının yasal çıkarlarının gerektirdiği istisnai hallerde, yönetmelikle belirlenen koşullar altında yürürlük tarihi ertelenebilir.",
 c=["Gümrük idaresinin mali çıkarlarının gerektirdiği istisnai hallerde, yönetmelikle belirlenen koşullar altında yürürlük tarihi öne alınabilir.",
    "Karar muhatabının yasal çıkarlarının gerektirdiği hallerde, Bakanlık onayıyla iptal kararı geriye dönük olarak tamamen ortadan kaldırılabilir.",
    "Karar muhatabının yazılı talebi halinde, itiraz sonuçlanıncaya kadar iptal veya değiştirme kararının yürürlüğü kendiliğinden durdurulur.",
    "Karar muhatabının yasal çıkarlarının gerektirdiği istisnai hallerde, gümrük idaresi yürürlük tarihini herhangi bir koşula bağlı olmadan belirler."],
 g="Kanun, karar muhatabının yasal çıkarlarının gerektirdiği istisnai hallerde, kararın iptalinin veya değiştirilmesinin yürürlük tarihinin yönetmelikle belirlenen koşullar altında ertelenebileceğini öngörür.",
 t="İstisnanın kimin çıkarı için ve hangi yönde (erteleme) olduğu kaydırılmıştır; ayrıca \"yönetmelikle belirlenen koşullar\" şartı atlatılmıştır."),

dict(tip="UK", z="Z", tuzak="Rejim sınıflandırma", madde="GY m.27/3, 27/4",
 cek="Değiştirme/iptal, yürürlük tarihinde rejime tabi tutulmaya başlanmış eşyaya uygulanmaz; idare belirli dönemde GOİK isteyebilir",
 kok=["İptal edilen bir karar uyarınca, iptal kararının yürürlüğe girdiği tarihte bir gümrük rejimine tabi tutulmaya başlanmış eşya bulunmaktadır.",
      "Gümrük Yönetmeliği uyarınca bu eşya bakımından aşağıdakilerden hangisi doğrudur?"],
 d="İptal kararı bu eşyaya uygulanmaz; ancak idare, belirlenecek bir dönem içinde eşyanın gümrükçe onaylanmış bir işleme veya kullanıma tabi tutulmasını isteyebilir.",
 c=["İptal kararı bu eşyaya da uygulanır; eşya, iptal kararının tebliğinden itibaren derhal serbest dolaşıma sokulmak zorundadır ve vergileri tahsil edilir.",
    "İptal kararı bu eşyaya uygulanmaz; eşya, başlanan rejimin süresi sonuna kadar idarece hiçbir ek işlem istenmeksizin aynı koşullarla rejimde kalmaya devam eder.",
    "İptal kararı bu eşyaya uygulanmaz; ancak idare, otuz gün içinde eşyanın Türkiye Gümrük Bölgesi dışına yeniden ihracını her durumda zorunlu olarak ister.",
    "İptal kararı bu eşyaya ancak başvuru sahibinin yanlış bilgiyi bildiği hallerde uygulanır; diğer hallerde eşya rejimde kalmaya devam eder."],
 g="Değiştirme ya da iptal kararları, yürürlüğe girdikleri tarihte iptal edilen ya da değiştirilen kararlar uyarınca bir gümrük rejimine tabi tutulmaya başlanmış eşya için uygulanmaz. Bununla birlikte gümrük idareleri, belirlenecek bir dönem içinde bu eşyanın gümrükçe onaylanmış bir işleme ya da kullanıma tabi tutulmasını isteyebilir.",
 t="Hükmün ikinci cümlesi atlatılmıştır; idare belirli bir işlem (yeniden ihraç) ya da belirli bir süre (otuz gün) dayatmaz, belirlenecek bir dönemde gümrükçe onaylanmış bir işlem veya kullanım isteyebilir.", protB=True),

dict(tip="SÜ", z="O", tuzak="Süre kaydırma", madde="GY m.586/1",
 cek="İtirazlar otuz gün içinde karara bağlanıp tebliğ edilir; bu sürede karar alınamazsa GK m.6/2 (süre aşımı) uygulanır",
 kok=["Gümrük Yönetmeliği uyarınca itirazların karara bağlanma süresi ve bu süre içinde karar alınamaması halinde uygulanacak usul aşağıdakilerden hangisinde doğru verilmiştir?"],
 d="İtirazlar otuz gün içinde karara bağlanır; bu sürede karar alınamazsa karar taleplerine ilişkin süre aşımı usulü uygulanır.",
 c=["İtirazlar otuz iş günü içinde karara bağlanır; bu sürede karar alınamazsa itiraz kabul edilmiş sayılarak ilgili kişiye tebliğ edilir.",
    "İtirazlar altmış gün içinde karara bağlanır; bu sürede karar alınamazsa itiraz reddedilmiş sayılarak ilgili kişiye bildirim yapılır.",
    "İtirazlar on beş gün içinde karara bağlanır; bu sürede karar alınamazsa dosya re'sen bir üst makama gönderilerek orada incelenir.",
    "İtirazlar otuz gün içinde karara bağlanır; bu sürede karar alınamazsa itiraz zımnen reddedilmiş sayılır ve doğrudan dava yolu açılır."],
 g="İtirazlar otuz gün içinde karara bağlanarak ilgili kişiye tebliğ edilir. Otuz gün içinde karar alınamadığı durumlarda Gümrük Kanunu'nun karar talebine ilişkin süre aşımı hükmü (sürenin aşılabilmesi, gerekçe ve ek sürenin bildirilmesi) uygulanır. Süre \"otuz gün\" olarak belirlenmiş olup iş günü olarak nitelenmemiştir.",
 t="Süre \"otuz iş günü\"ne kaydırılmış ya da sürenin aşılmasına \"kabul\" veya \"zımni ret\" sonucu bağlanmıştır; mevzuatta bu sonuçlar yoktur."),

dict(tip="BD", z="Z", tuzak="Belge eşleştirme", madde="GY m.586/1",
 cek="İtiraz incelemesi: örnek alınamazsa eşyanın kendisi veya fotoğraf, katalog, prospektüs gibi fikir verecek belgeler incelenir",
 kok=["Gümrük Yönetmeliği uyarınca itirazların karara bağlanmasında, eşyadan örnek alınmasının mümkün olmadığı hallerde incelenecek unsurlar aşağıdakilerden hangisinde doğru verilmiştir?"],
 d="Eşyanın kendisi veya fotoğraf, katalog, prospektüs gibi eşyayı görmeden fikir verecek diğer belgeler incelenir.",
 c=["Yalnızca anlaşmazlığa konu beyanname incelenir; fotoğraf veya katalog gibi eşyaya ilişkin belgeler dikkate alınmaz.",
    "Eşyanın kendisi incelenemez; bu durumda yalnızca ilgili gümrük idaresinin mütalaası esas alınarak karar verilir.",
    "Örnek alınamıyorsa itiraz incelenmez; itiraz edenden eşyaya ait laboratuvar tahlil raporunu sunması istenir.",
    "Eşyanın kendisi veya fotoğrafı incelenir; katalog ve prospektüs gibi ticari belgeler ise delil olarak kabul edilmez."],
 g="İtirazlar; anlaşmazlığa konu beyanname ve her türlü belge ile eşyadan alınacak örnek, örnek alınması mümkün olmayan hallerde eşyanın kendisi veya fotoğraf, katalog, prospektüs gibi eşyayı görmeden fikir verecek diğer belgeler incelenerek karara bağlanır.",
 t="Örnek alınamadığında incelemenin durmadığı, eşyanın kendisi ve fikir verecek belgelere geçildiği atlanır; katalog ve prospektüs açıkça sayılmıştır."),

dict(tip="MK", z="O", tuzak="İdare/makam karıştırma", madde="GY m.586/1",
 cek="İtiraz incelemesinde gerek duyulursa ilgili gümrük idaresinin mütalaası alınır",
 kok=["Gümrük Yönetmeliği uyarınca itirazlar karara bağlanırken gerek duyulması halinde görüşüne başvurulacak merci aşağıdakilerden hangisidir?"],
 d="İtiraza konu işlemle ilgili gümrük idaresinin mütalaası alınır.",
 c=["Ticaret Bakanlığı merkez teşkilatının mütalaası alınmak zorundadır.",
    "İtiraz edenin gümrük müşavirinin yazılı mütalaası alınır.",
    "Gümrük müşavirleri derneğinin yazılı görüşü alınır.",
    "Gümrük ve dış ticaret bölge müdürlüğünün onayı alınmalıdır."],
 g="İtirazların incelenmesinde, gerek duyulması halinde ilgili gümrük idaresinin mütalaası da alınır. Mevzuat mütalaayı zorunlu değil, gerek duyulması halinde başvurulan bir yol olarak düzenlemiştir.",
 t="Mütalaa merciinin \"ilgili gümrük idaresi\" olduğu, merkez teşkilat veya bölge müdürlüğü gibi üst makamlarla karıştırılmaktadır."),

dict(tip="ÇI", z="ÇZ", tuzak="İstisna atlatma", madde="GK m.6/3, 6/4, 7/3, 7/4; GY m.27/3",
 cek="Kararın iptali muhatabına tebliğ edilir (diğer kurallarla birlikte değerlendirme)",
 kok=["Gümrük Kanunu ve Gümrük Yönetmeliği hükümleri birlikte değerlendirildiğinde;",
      "I. Muhatabı aleyhine verilen yazılı kararlar gerekçeli olarak alınır.",
      "II. Kararın iptali muhatabına tebliğ edilir.",
      "III. Değiştirme veya iptal kararları, yürürlüğe girdikleri tarihte iptal edilen karar uyarınca rejime tabi tutulmaya başlanmış eşyaya da uygulanır.",
      "IV. Hallerin bir arada bulunmasına dayalı iptal, iptal kararının tebliğ tarihinden itibaren yürürlüğe girer.",
      "V. Alınan kararlar gümrük idareleri tarafından derhal uygulanır.",
      "ifadelerinden hangileri doğrudur?"],
 d="I, II ve V", c=["I ve V", "I, III ve V", "II, IV ve V", "I, II, IV ve V"],
 g="Aleyhe yazılı kararlar gerekçeli alınır (I), kararın iptali muhatabına tebliğ edilir (II) ve alınan kararlar derhal uygulanır (V). Değiştirme veya iptal kararları rejime tabi tutulmaya başlanmış eşyaya uygulanmaz (III yanlış). Hallerin bir arada bulunmasına dayalı iptal, tebliğ tarihinden değil iptal kararının verildiği tarihten itibaren yürürlüğe girer (IV yanlış).",
 t="III. öncül Yönetmelikteki \"uygulanmaz\" istisnasını, IV. öncül ise iki fıkranın yürürlük anlarını tersine çevirir."),

dict(tip="UK", z="Z", tuzak="Belge eşleştirme", madde="GK m.6/1",
 cek="Karar talep eden kişi kararın verilebilmesi için gerekli bütün bilgi ve belgeleri ibraz etmek zorundadır",
 kok=["Gümrük mevzuatının uygulanmasına ilişkin karar talebinde bulunan bir kişi, kararın verilebilmesi için gerekli belgelerin bir kısmını idareye sunmamıştır.",
      "Gümrük Kanunu çerçevesinde bu kişinin yükümlülüğüne ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="Karar talep eden kişi, kararın verilebilmesi için gerekli bütün bilgi ve belgeleri söz konusu gümrük idaresine ibraz etmek zorundadır.",
 c=["Belgelerin eksik olması halinde gümrük idaresi, eksik belgeleri kendisi temin ederek karar vermekle yükümlüdür.",
    "Karar talep eden kişi, yalnızca idarece yazılı olarak istenen belgeleri ibraz etmekle yükümlüdür; diğer belgeler ise aranmaz.",
    "Belgelerin eksik olması halinde otuz günlük karar süresi kendiliğinden altmış güne uzar ve eksiklik bu ek süre içinde giderilir.",
    "Bilgi ve belge ibrazı yükümlülüğü, yalnızca Türkiye Gümrük Bölgesinde yerleşik olmayan kişiler için öngörülmüştür."],
 g="Gümrük idarelerinin karar vermesini talep eden her kişi, kararın verilebilmesi için gerekli bütün bilgi ve belgeleri söz konusu idarelere ibraz etmek zorundadır.",
 t="Yükümlülük talep edene aittir ve \"gerekli bütün\" bilgi ve belgeleri kapsar; idareye aktarılamaz, yalnızca istenen belgelerle de sınırlı değildir.", protB=True),

dict(tip="UU", z="ÇZ", tuzak="İdare/makam karıştırma", madde="GK m.6/2, 6/4",
 cek="Karar başvuru sahibine yazılı tebliğ edilir ve gümrük idarelerince derhal uygulanır; ayrı bir onay ya da bekleme süresi yoktur",
 kok=["Gümrük Kanunu uyarınca, gümrük mevzuatının uygulanmasına ilişkin kararların bildirilmesi ve uygulanması bakımından aşağıdaki ifadelerden hangisi doğrudur?"],
 d="Verilen karar başvuru sahibine yazılı olarak tebliğ edilir ve alınan karar gümrük idarelerince derhal uygulanır; ayrıca bir onay öngörülmemiştir.",
 c=["Verilen karar başvuru sahibine yazılı olarak tebliğ edilir; ancak alınan karar, itiraz süresinin geçmesiyle kesinleştikten sonra gümrük idarelerince uygulanır.",
    "Verilen karar başvuru sahibine sözlü olarak da bildirilebilir; alınan karar, bir üst makamın onayını izleyen tarihten itibaren gümrük idarelerince uygulanır.",
    "Verilen karar yalnızca başvuru sahibinin aleyhine olması halinde yazılı tebliğ edilir; lehe kararlar ise tebliğe gerek olmaksızın idarelerce uygulanır.",
    "Verilen karar Bakanlık onayından sonra başvuru sahibine yazılı tebliğ edilir ve alınan karar, tebliğ tarihinden otuz gün sonra idarelerce uygulanır."],
 g="Verilen kararlar başvuru sahibine yazılı olarak tebliğ edilir ve alınan kararlar gümrük idareleri tarafından derhal uygulanır. Kanun, kararın uygulanmasını bir üst makam onayına, kesinleşmeye veya bekleme süresine bağlamamıştır.",
 t="Kararın uygulanması, kesinleşme veya Bakanlık/üst makam onayı gibi mevzuatta olmayan bir aşamaya bağlanmıştır; Kanun \"derhal uygulanır\" der."),
]
