# -*- coding: utf-8 -*-
# Batch B — kitapçık soru 21–37 konularına benzer 20 özgün soru
# Alanlar: konu, tip, z, tuzak, madde, cek, kok, d, c, g, t, protB(ops.), kanit
Q = [
# 1 ---------------------------------------------------------------- Temsil
dict(konu="Temsil", tip="MK", z="ÇK", tuzak="İdare/makam karıştırma", madde="GK m.226/4",
 cek="GMY ve stajyerlerin fiil ve hareketlerinden doğan mali sorumluluk yanında çalıştıkları gümrük müşavirine aittir",
 kok=["4458 sayılı Gümrük Kanununa göre, gümrük müşavir yardımcılarının ve stajyerlerin fiil ve hareketlerinden doğacak mali sorumluluk aşağıdakilerden hangisine aittir?"],
 d="Yanında çalıştıkları gümrük müşavirine",
 c=["Bağlı oldukları gümrük ve muhafaza başmüdürlüğüne",
    "Hesabına beyanda bulunulan eşya sahibine",
    "Fiili gerçekleştiren yardımcı veya stajyerin kendisine",
    "Gümrük müşavirleri derneğine ve eşya sahibine müştereken"],
 g="Gümrük Kanunu, gümrük müşavir yardımcılarının ve stajyerlerin fiil ve hareketlerinden doğacak mali sorumluluğu yanında çalıştıkları gümrük müşavirine yüklemiştir.",
 t="Sorumluluk fiili işleyene, derneğe ya da idareye kaydırılmıştır; Kanun mali sorumluluğu açıkça yanında çalışılan gümrük müşavirine bağlar.",
 kanit='2-TEMSİL.txt: "Gümrük müşavir yardımcılarının ve stajyerlerin fiil ve hareketlerinden doğacak mali sorumluluk, yanında çalıştıkları gümrük müşavirine aittir."'),

# 2 ---------------------------------------------------------------- Temsil
dict(konu="Temsil", tip="DY", z="O", tuzak="İstisna atlatma", madde="GK m.225/1",
 cek="Gerçek kişinin doğrudan temsille iş takibi: geçerli vekaletname + ticari miktar/mahiyet arz etmeyen eşya ve özel kullanıma mahsus taşıtlar",
 kok=["4458 sayılı Gümrük Kanununa göre, gerçek kişinin gümrük idarelerinde doğrudan temsil yoluyla iş takibi yapabilmesine ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="Geçerli vekaletnameye istinaden ticari miktar ve mahiyet arz etmeyen eşyanın ve özel kullanıma mahsus taşıt araçlarının gümrük işlemleri ile ilgili olarak mümkündür.",
 c=["Geçerli vekaletnameye istinaden ticari miktar ve mahiyet arz eden eşya dahil olmak üzere, gerçek kişinin tüm gümrük işlemleri için sınırlama olmaksızın mümkündür.",
    "Noter onaylı vekaletnameye istinaden yalnızca ticari miktar ve mahiyet arz etmeyen eşyanın gümrük işlemleri için mümkündür; taşıt araçları bu kapsamın dışındadır.",
    "Gerçek kişiler doğrudan temsil yoluyla iş takibi yapamaz; bu kişilerin gümrük işlemleri yalnızca gümrük müşavirlerince dolaylı temsil yoluyla takip edilir.",
    "Geçerli vekaletnameye istinaden yalnızca özel kullanıma mahsus taşıt araçlarının işlemleri için mümkündür; diğer her türlü eşya için gümrük müşaviri zorunludur."],
 g="Kanuna göre gerçek kişinin doğrudan temsil yoluyla iş takibi, geçerli vekaletnameye istinaden ticari miktar ve mahiyet arz etmeyen eşyanın ve özel kullanıma mahsus taşıt araçlarının gümrük işlemleri ile ilgili olarak mümkündür. İki kategori birlikte sayılmıştır.",
 t="İki kategoriden biri düşürülmüş ya da \"ticari mahiyet arz etmeme\" sınırı kaldırılmıştır; ayrıca vekaletnameye Kanunda yer almayan \"noter onayı\" şartı eklenmiştir.",
 kanit='2-TEMSİL.txt: "Gerçek kişinin doğrudan temsil yoluyla iş takibi, geçerli vekaletnameye istinaden ticari miktar ve mahiyet arz etmeyen eşyanın ve özel kullanıma mahsus taşıt araçlarının gümrük işlemleri ile ilgili olarak mümkündür."',
 protB=True),

# 3 ---------------------------------------------------------------- Gümrük müşaviri
dict(konu="Gümrük Müşaviri", tip="SÜ", z="K", tuzak="Süre kaydırma", madde="GK m.230",
 cek="Gümrük müşavirleri defter, vekaletname, yazışma, fatura ve makbuzların asıl ve örneklerini beş yıl muhafaza eder ve ibraz eder",
 kok=["4458 sayılı Gümrük Kanununa göre gümrük müşavirleri; işlerine dair yazdıkları ve aldıkları mektup, faks ve benzeri belgeler ile düzenledikleri fatura ve makbuzların asıllarını ve örneklerini, özel kanunlardaki hükümler saklı kalmak kaydıyla, ne kadar süre muhafaza etmek zorundadır?"],
 d="Beş yıl süreyle muhafaza etmek ve istendiğinde yetkili görevlilere ibraz etmek zorundadırlar.",
 c=["Üç yıl süreyle muhafaza etmek ve istendiğinde yetkili görevlilere ibraz etmek zorundadırlar.",
    "On yıl süreyle muhafaza etmek ve yalnızca gümrük müfettişlerine ibraz etmek zorundadırlar.",
    "İki yıl süreyle muhafaza etmek ve yalnızca mahkeme kararı üzerine ibraz etmek zorundadırlar.",
    "Bir yıl süreyle muhafaza etmek ve sonrasında gümrük müşavirleri derneğine teslim etmek zorundadırlar."],
 g="Gümrük müşavirleri, söz konusu defter ve belgelerin asıllarını ve örneklerini özel kanunlardaki hükümler saklı kalmak kaydıyla beş yıl muhafaza etmeye, bunları yetkili denetim elemanlarına göstermeye ve gerektiğinde yazılı istek üzerine ibraz etmeye mecburdur.",
 t="Süre üç veya on yıla kaydırılmış, ibraz yükümlülüğü tek bir makama ya da mahkeme kararına bağlanmıştır.",
 kanit='2-TEMSİL.txt: "özel kanunlardaki hükümler saklı kalmak kaydıyla beş yıl muhafaza etmeye"'),

# 4 ---------------------------------------------------------------- Temsil
dict(konu="Temsil", tip="ÇI", z="ÇZ", tuzak="Tanım çiftleri", madde="GK m.5, 181/2, 241/4-a",
 cek="Temsil: yerleşiklik istisnası, yetkisiz temsilde kendi adına-hesabına sayılma, dolaylı temsilcinin sınırlı yükümlülüğü; yetkisiz iş takibi dört kat ceza",
 kok=["4458 sayılı Gümrük Kanununa göre temsile ilişkin;",
      "I. Dolaylı temsil durumunda temsilci, başkasının adına ve hesabına hareket eder.",
      "II. Transit taşımacılık yapan veya arızi olarak beyanda bulunan kişiler hariç olmak üzere, temsilci Türkiye Gümrük Bölgesinde yerleşik bulunan kişidir.",
      "III. Temsil yetkisine sahip olmadığı halde başka bir kişi adına hareket ettiğini beyan eden kişi, kendi adına ve kendi hesabına hareket ediyor sayılır.",
      "IV. Geçerli bir temsil yetkisi olmadığı halde başka bir kişi adına gümrük idarelerinde iş takip edene usulsüzlük cezası iki katı olarak uygulanır.",
      "V. Dolaylı temsilde temsilcinin yükümlülüğü, beyanda kullanılan verilerin yanlış olduğunu bildiği veya mesleği icabı ve mutat olarak bilmesi gereken durumlarla sınırlıdır.",
      "ifadelerinden hangileri doğrudur?"],
 d="II, III ve V",
 c=["I, II ve V", "II, III ve IV", "I, II, III ve V", "II, III, IV ve V"],
 g="Temsilci, transit taşımacılık yapan veya arızi beyanda bulunanlar hariç Türkiye Gümrük Bölgesinde yerleşik kişidir (II). Temsil yetkisi olmadan başkası adına hareket ettiğini beyan eden kendi adına ve hesabına hareket ediyor sayılır (III). Dolaylı temsilcinin yükümlülüğü bilme/bilmesi gerekme halleriyle sınırlıdır (V). Dolaylı temsilde temsilci kendi adına, başkasının hesabına hareket eder (I yanlış). Geçerli temsil yetkisi olmadan iş takibinde usulsüzlük cezası dört katı uygulanır (IV yanlış).",
 t="I. öncülde doğrudan ve dolaylı temsilin tanımları yer değiştirmiş; IV. öncülde dört kat, karar belgelerinin yanlış verilmesine uygulanan iki kat ile karıştırılmıştır.",
 kanit='2-TEMSİL.txt: "bir temsil yetkisine sahip olmadığı halde, başka bir kişi adına ya da hesabına hareket ettiğini beyan eden kişi, kendi adına ve kendi hesabına hareket ediyor sayılır." 48-cezalar.txt: "1 inci fıkrada belirtilen miktarın dört katı olarak uygulanır"'),

# 5 ---------------------------------------------------------------- YGM
dict(konu="YGM", tip="EŞ", z="Z", tuzak="Süre kaydırma", madde="GY m.578/1-b, d, e",
 cek="YGM yetki belgesi geri alma: asgari ücret altı hizmet 1 yıl; bizzat işi başkasına yaptırma 2 yıl; bilgi-belgeyi amaç dışı kullanma 5 yıl",
 kok=["Gümrük Yönetmeliğine göre, yetkilendirilmiş gümrük müşavirine ait yetki belgesinin geri alınmasını gerektiren durumlar ile geri alma süreleri aşağıdakilerin hangisinde doğru eşleştirilmiştir?"],
 d="Asgari ücret tarifesinin altında hizmet: 1 yıl; bizzat yapacağı işleri başkasına yaptırma: 2 yıl; bilgi ve belgeleri amaç dışı kullanma: 5 yıl",
 c=["Asgari ücret tarifesinin altında hizmet: 2 yıl; bizzat yapacağı işleri başkasına yaptırma: 1 yıl; bilgi ve belgeleri amaç dışı kullanma: 5 yıl",
    "Asgari ücret tarifesinin altında hizmet: 1 yıl; bizzat yapacağı işleri başkasına yaptırma: 5 yıl; bilgi ve belgeleri amaç dışı kullanma: 2 yıl",
    "Asgari ücret tarifesinin altında hizmet: 6 ay; bizzat yapacağı işleri başkasına yaptırma: 2 yıl; bilgi ve belgeleri amaç dışı kullanma: süresiz",
    "Asgari ücret tarifesinin altında hizmet: 1 yıl; bizzat yapacağı işleri başkasına yaptırma: 2 yıl; bilgi ve belgeleri amaç dışı kullanma: 3 yıl"],
 g="Yönetmeliğe göre asgari ücret tarifesinin altında hizmet verildiğinin tespitinde yetki belgesi 1 yıl, tespit sözleşmesi kapsamında bizzat yapılacak işlerin başkasına yaptırılmasında 2 yıl, mesleği icabı elde edilen bilgi ve belgelerin amaç dışı kullanılmasında 5 yıl süreyle geri alınır.",
 t="Üç yaptırımın süreleri birbirleriyle çaprazlanmıştır; en ağır süre (5 yıl) bilgi ve belgelerin amaç dışı kullanımına aittir.",
 kanit='31-YGM.txt: "Tespit sözleşmesi kapsamında bizzat yapacağı işleri başkasına yaptırdığının tespit edilmesi halinde yetkilendirilmiş gümrük müşavirine ait yetki belgesi 2 yıl süreyle geri alınır."'),

# 6 ---------------------------------------------------------------- Yükümlülük
dict(konu="Yükümlülük", tip="TN", z="O", tuzak="Tanım çiftleri", madde="GK m.181/2",
 cek="İthalatta yükümlü beyan sahibidir; dolaylı temsilde hesabına beyanda bulunulan da yükümlü, temsilcinin yükümlülüğü bilme/bilmesi gerekme ile sınırlı",
 kok=["4458 sayılı Gümrük Kanununa göre, serbest dolaşıma giriş rejimi için dolaylı temsil yoluyla verilen beyannamede ithalattaki gümrük yükümlülüğünün yükümlüsü bakımından aşağıdakilerden hangisi doğrudur?"],
 d="Beyan sahibi ile hesabına beyanda bulunulan kişi yükümlüdür; temsilcinin yükümlülüğü, verilerin yanlış olduğunu bildiği veya mesleği icabı ve mutat olarak bilmesi gereken hallerle sınırlıdır.",
 c=["Yalnızca hesabına beyanda bulunulan kişi yükümlüdür; dolaylı temsilci, beyanda kullanılan verilerin yanlış olduğunu bilse dahi gümrük vergilerinden hiçbir şekilde sorumlu tutulamaz.",
    "Beyan sahibi ile hesabına beyanda bulunulan kişi yükümlüdür; temsilci ise beyandaki her türlü hatadan, verilerin yanlışlığını bilip bilmediğine bakılmaksızın sınırsız olarak sorumludur.",
    "Yalnızca beyannameyi imzalayan dolaylı temsilci yükümlüdür; hesabına beyanda bulunulan kişi ise ancak vergiler temsilci tarafından ödenmezse takip edilir.",
    "Beyan sahibi yükümlü değildir; yükümlü, eşyayı gümrük idaresinden teslim alıp serbest dolaşımda kullanan kişidir ve temsilci bu durumda sorumlu tutulmaz."],
 g="İthalatta gümrük yükümlülüğünde yükümlü beyan sahibidir; dolaylı temsil durumunda hesabına gümrük beyanında bulunulan kişi de yükümlüdür. Dolaylı temsilcinin yükümlülüğü, beyanda kullanılan verilerin yanlış olduğunu bildiği veya mesleği icabı ve mutat olarak bilmesi gerektiği durumlarla sınırlıdır.",
 t="Dolaylı temsilcinin sorumluluğu ya tamamen kaldırılmış ya da sınırsız hale getirilmiştir; Kanun sınırlı (bilme/bilmesi gereken) bir sorumluluk öngörür.",
 kanit='44-yükümlülük.txt: "Dolaylı temsil durumunda, hesabına gümrük beyanında bulunulan kişi de yükümlüdür. Dolaylı temsilde, temsilcinin yükümlülüğü, beyanda kullanılan verilerin yanlış olduğunu bildiği veya mesleği icabı ve mutat olarak bilmesi gerektiği durumlarla sınırlıdır."',
 protB=True),

# 7 ---------------------------------------------------------------- Yükümlülük
dict(konu="Yükümlülük", tip="UU", z="O", tuzak="İstisna atlatma", madde="GK m.191",
 cek="Yasak/kısıtlamalı eşyada da yükümlülük doğar; sahte para ve denetlenen ekonomik dolaşıma girmeyen narkotikte kaçak girişte yükümlülük doğmaz",
 kok=["4458 sayılı Gümrük Kanununa göre, ithali ve ihracı yasaklama veya kısıtlamaya tabi eşya bakımından gümrük yükümlülüğünün doğmasına ilişkin aşağıdaki ifadelerden hangisi doğrudur?"],
 d="Sahte paraların Türkiye Gümrük Bölgesine kanuna aykırı girmesi halinde, kaçakçılık ve ceza kanunlarına göre işlem yapılacağından gümrük yükümlülüğü doğmaz.",
 c=["Yasaklama veya kısıtlamaya tabi eşya için hiçbir halde gümrük yükümlülüğü doğmaz; bu eşyaya yalnızca kaçakçılık ve ceza koyan kanun hükümleri uygulanır.",
    "Sahte paraların Türkiye Gümrük Bölgesine kanuna aykırı girmesi halinde gümrük yükümlülüğü doğar ve vergiler eşyanın piyasa değeri üzerinden hesaplanır.",
    "Ekonomik dolaşıma girmeyen narkotik maddelerin kanuna aykırı girişinde, cezai kovuşturma gümrük yükümlülüğüne bağlı olsa dahi yükümlülük doğmuş sayılmaz.",
    "Tıbbi amaçlı narkotik maddelerin kanuna aykırı girişinde gümrük yükümlülüğü doğar; sahte paralarda ise yükümlülük yalnızca ihracat halinde doğar."],
 g="Yasaklama veya kısıtlamaya tabi eşya için de gümrük yükümlülüğü doğar. Ancak sahte paralar ile tıbbi ve bilimsel amaçlı kullanımları nedeniyle denetlenen ekonomik dolaşıma girmeyen narkotik maddelerin kanuna aykırı girişinde, kaçakçılık ve diğer ceza kanunlarına göre işlem yapılacağından yükümlülük doğmaz. Cezai kovuşturmanın yükümlülüğün varlığına bağlı olduğu hallerde ise yükümlülük doğmuş sayılır.",
 t="Genel kural (yasak eşyada da yükümlülük doğar) ile istisna (sahte para ve narkotik) ve istisnanın istisnası (cezai kovuşturma için doğmuş sayılma) birbirine karıştırılmıştır.",
 protB=True,
 kanit='44-yükümlülük.txt: "Ancak, sahte paralar ile tıbbi ve bilimsel amaçlı kullanımları nedeniyle" ... "kaçakçılık ve diğer ceza koyan kanun hükümlerine göre işlem yapılacağından, gümrük yükümlülüğü doğmaz."'),

# 8 ---------------------------------------------------------------- Ödeme
dict(konu="Ödeme", tip="ÇI", z="Z", tuzak="Belge eşleştirme", madde="GK m.198/1, 198/2, 198/3",
 cek="Ödeme süresi: süre bitmeden yazılı istem + teminatla otuz gün uzatılabilir, kalem bazında da olur, tecil faizi alınır; itiraz süreyi keser",
 kok=["4458 sayılı Gümrük Kanununa göre, yapılan kontrol ve denetlemeler sonucunda noksan alındığı belirlenen gümrük vergilerinin ödeme süresine ilişkin;",
      "I. Ödeme süresinin bitmesinden önce ilgilinin yazılı istemde bulunması ve teminat alınması şartıyla ödeme süresi otuz gün daha uzatılabilir.",
      "II. Süre uzatımı, beyanname kapsamı eşyanın her bir kalemi için ayrı ayrı yapılamaz.",
      "III. Uzatılan süre için 6183 sayılı Kanuna göre tecil faizi alınır.",
      "IV. Tebliğ edilen gümrük vergilerine karşı gümrük idareleri nezdinde itiraz edilmesi ödeme süresini keser.",
      "V. Yükümlü, verilen süre bitmeden vergi tutarının yalnızca tamamını ödeyebilir; kısmi ödeme yapamaz.",
      "ifadelerinden hangileri doğrudur?"],
 d="I, III ve IV",
 c=["I ve IV", "I, II ve III", "III, IV ve V", "I, II, III ve IV"],
 g="Ödeme süresi, süre bitmeden yazılı istem ve teminat şartıyla otuz gün daha uzatılabilir (I); uzatılan süre için tecil faizi alınır (III); itiraz ödeme süresini keser (IV). Süre uzatımı her bir kalem için ayrı ayrı da yapılabilir (II yanlış); yükümlü vergi tutarının tamamını veya bir kısmını süre bitmeden ödeyebilir (V yanlış).",
 t="II. ve V. öncüller Kanundaki izinleri (kalem bazında uzatma, kısmi erken ödeme) yasağa çevirmiştir; uzatma için hem yazılı istem hem teminat birlikte aranır.",
 kanit='45-tebliğ.txt: "Ödeme süresinin bitmesinden önce ilgilinin yazılı istemde bulunması ve teminat alınması şartıyla ödeme süresi otuz gün daha uzatılabilir." / "itiraz edilmesi ödeme süresini keser"'),

# 9 ---------------------------------------------------------------- Teminat (HESAP)
dict(konu="Teminat", tip="HESAP", z="O", tuzak="Eşik/oran kaydırma", madde="GY m.494/1",
 cek="Götürü teminat: önceki yıl teminat konusu değerin %10'u; DİR dahilse en az 250.000, değilse 75.000 Avro; üst sınır 2.000.000 Avro",
 kok=["Götürü teminat sisteminden yararlanmak isteyen (A) firmasının bir önceki yılda gümrük işlemleri nedeniyle teminat konusu olan toplam değeri 1.800.000 Avro'dur. Firmanın vereceği teminat, dahilde işleme rejimi kapsamındaki eşyayı da içerecektir.",
      "Gümrük Yönetmeliğine göre (A) firmasının vermesi gereken götürü teminat tutarı kaç Avro'dur?"],
 d="250.000 Avro",
 c=["180.000 Avro", "75.000 Avro", "360.000 Avro", "2.000.000 Avro"],
 g="Götürü teminat tutarı bir önceki yılda teminat konusu olan toplam değerin %10'udur: 1.800.000 × %10 = 180.000 Avro. Ancak teminat dahilde işleme rejimi kapsamındaki eşyayı da içerdiğinden 250.000 Avro'dan az olamaz. Bu nedenle verilecek tutar 250.000 Avro'dur.",
 t="Yalnızca %10 oranı uygulanıp alt sınır atlanırsa 180.000; dahilde işleme dışı işlemlerin alt sınırı alınırsa 75.000 Avro bulunur.",
 kanit='46-teminat ve faiz.txt: "bir önceki yılda gümrük işlemleri nedeniyle teminat konusu olan toplam değerin % 10\'udur. Ancak; a) Teminatın dahilde işleme rejimi kapsamındaki eşyayı da içermesi halinde 250.000 Avro"'),

# 10 --------------------------------------------------------------- Yükümlülük
dict(konu="Yükümlülük", tip="DĞ", z="O", tuzak="İstisna atlatma", madde="GK m.208",
 cek="Yükümlülüğün sona ermesi: zapt ve müsadere, eşyanın bir gümrük rejimi kapsamında tesliminden ÖNCE olmalıdır",
 kok=["4458 sayılı Gümrük Kanununa göre, 6183 sayılı Kanun hükümleri saklı kalmak üzere aşağıdakilerden hangisi gümrük yükümlülüğünü sona erdiren hallerden biri değildir?"],
 d="Eşyanın bir gümrük rejimi kapsamında tesliminden sonra zapt ve müsadere edilmesi",
 c=["Eşyanın doğal özellikleri, beklenmeyen haller veya mücbir sebep nedeniyle telef olması veya kaybı",
    "Kanuna aykırı olarak Türkiye Gümrük Bölgesine giren eşyanın bu giriş nedeniyle müsadere edilmesi",
    "Gümrük vergilerinin ödenmesi ya da henüz ödenmemiş vergilerin kaldırılmasına karar verilmesi",
    "Gümrük beyannamesinin iptal edilmesi ya da eşyanın gümrüğe terk edilmesi veya imhası"],
 g="Gümrük yükümlülüğü; vergilerin ödenmesi, kaldırılmasına karar verilmesi, beyannamenin iptali, eşyanın bir gümrük rejimi kapsamında tesliminden önce zapt ve müsaderesi veya imhası, imha veya terk, doğal özellikler, beklenmeyen hal veya mücbir sebeple telef veya kayıp ve kanuna aykırı giren eşyanın bu nedenle müsaderesi hallerinde sona erer. Teslimden sonraki zapt ve müsadere sayılmamıştır.",
 t="\"Tesliminden önce\" kaydı \"tesliminden sonra\" olarak çevrilmiştir; müsadere ancak teslimden önce gerçekleşirse yükümlülüğü sona erdirir.",
 kanit='44-yükümlülük.txt: "Eşyanın bir gümrük rejimi kapsamında tesliminden önce zapt ve müsadere edilmesi veya imha edilmesi"'),

# 11 --------------------------------------------------------------- Geri verme
dict(konu="Geri Verme", tip="SÜ", z="K", tuzak="Süre kaydırma", madde="GK m.216/2",
 cek="Geri verme kararı tebliğden itibaren dört ay içinde uygulanmazsa talep üzerine kanuni faiz oranında faiz ödenir",
 kok=["4458 sayılı Gümrük Kanununa göre, geri verme kararının tebliğ edildiği tarihten itibaren idarece ne kadar süre içinde uygulanmaması halinde, ilgilinin talebi üzerine geri verilecek tutar üzerinden faiz ödenir?"],
 d="Dört ay içinde uygulanmaması halinde kanuni faiz oranında faiz ödenir.",
 c=["Üç ay içinde uygulanmaması halinde kanuni faiz oranında faiz ödenir.",
    "Altı ay içinde uygulanmaması halinde gecikme zammı oranında faiz ödenir.",
    "Otuz gün içinde uygulanmaması halinde tecil faizi oranında faiz ödenir.",
    "Bir yıl içinde uygulanmaması halinde reeskont faizi oranında faiz ödenir."],
 g="Geri verme kararının tebliğ edildiği tarihten itibaren dört ay içinde idarece uygulanmaması halinde, ilgilinin talebi üzerine, tebliğ tarihinden ödemenin yapıldığı tarihe kadar geçen süre için geri verilecek tutar üzerinden kanuni faiz oranında faiz ödenir.",
 t="Süre üç/altı aya, faiz türü gecikme zammı veya tecil faizine kaydırılmıştır; Kanun dört ay ve kanuni faiz öngörür.",
 kanit='47-geri verme kaldırma.txt: "Geri verme kararının tebliğ edildiği tarihten itibaren dört[210] ay içerisinde idarece söz konusu kararın uygulanmaması hâlinde"'),

# 12 --------------------------------------------------------------- Geri verme
dict(konu="Geri Verme", tip="MK", z="O", tuzak="İdare/makam karıştırma", madde="GY m.500/1",
 cek="Geri verme/kaldırma yetkisi: 4.730.000 TL'ye kadar gümrük müdürlüğü; 47.397.000 TL'ye kadar bölge müdürlüğü; üstü Bakanlık",
 kok=["Gümrük Yönetmeliğinde belirtilen tutarlar esas alındığında, 30.000.000 TL tutarındaki gümrük vergilerinin geri verilmesi işlemini yapmaya aşağıdakilerden hangisi yetkilidir?"],
 d="Gümrük ve dış ticaret bölge müdürlükleri",
 c=["İlgili gümrük müdürlükleri",
    "Ticaret Bakanlığı (Gümrükler Genel Müdürlüğü)",
    "Hazine ve Maliye Bakanlığına bağlı ilgili vergi dairesi",
    "Gümrük müdürlükleri ile bölge müdürlükleri müştereken"],
 g="Yönetmeliğe göre 4.730.000 TL'ye kadar olan geri verme veya kaldırma işlemlerinde ilgili gümrük müdürlükleri, 47.397.000 TL'ye kadar olanlarda gümrük ve dış ticaret bölge müdürlükleri, bu tutarın üstündekilerde Bakanlık yetkilidir. 30.000.000 TL ikinci dilime girer. (Tutarlar her yıl yeniden değerleme oranında artırılır.)",
 t="Tutar gümrük müdürlüğü sınırını aştığı, ancak Bakanlık sınırının altında kaldığı için ara kademe (bölge müdürlüğü) yetkilidir.",
 kanit='47-geri verme kaldırma.txt: "47.397.000. TL\'ye kadar olan geri verme veya kaldırma işlemlerini yapmaya gümrük ve dış ticaret bölge müdürlükleri"'),

# 13 --------------------------------------------------------------- Cezalar
dict(konu="Cezalar", tip="DY", z="O", tuzak="Eşik/oran kaydırma", madde="GK m.234/1-c",
 cek="Satış birimine göre %5'i geçmeyen miktar farkı ve maddi hesap hatasından doğan noksan kıymet beyanında vergi farkının yarısı ceza",
 kok=["4458 sayılı Gümrük Kanununa göre serbest dolaşıma giriş rejimine tabi tutulan eşyada, satış birimine göre miktar itibarıyla %5'i geçmeyen bir fark ile maddi hesap hatasından doğan noksan kıymet beyanlarında uygulanacak para cezası aşağıdakilerden hangisidir?"],
 d="Bu farklara ait ithalat vergilerinden başka vergi farkının yarısı tutarında para cezası alınır.",
 c=["Bu farklara ait ithalat vergilerinden başka vergi farkının üç katı tutarında para cezası alınır.",
    "Bu farklara ait ithalat vergilerinden başka vergi farkının iki katı tutarında para cezası alınır.",
    "Fark %5'i geçmediğinden ceza uygulanmaz; yalnızca noksan ithalat vergileri faiziyle tahsil edilir.",
    "Bu farklara ait ithalat vergilerinden başka gümrüklenmiş değerin onda biri tutarında ceza alınır."],
 g="Satış birimine göre miktar itibarıyla %5'i geçmeyen fark ile maddi hesap hatasından doğan noksan kıymet beyanlarında, bu farklara ait ithalat vergilerinden başka vergi farkının yarısı tutarında para cezası alınır. Üç kat ceza, %5'i aşan tarife unsuru farklılıkları ve noksan kıymet beyanı için öngörülmüştür.",
 t="%5 eşiği \"ceza yok\" sonucuna çevrilmiş ya da genel noksan kıymet beyanındaki üç kat oran bu özel hale taşınmıştır.",
 kanit='48-cezalar.txt: "Satış birimine göre miktar itibarıyla % 5\'i geçmeyen bir fark ile maddi hesap hatasından doğan noksan kıymet beyanlarında, bu farklara ait ithalat vergilerinden[248] başka vergi farkının yarısı tutarında para cezası alınır."'),

# 14 --------------------------------------------------------------- Kıymet
dict(konu="Kıymet", tip="TN", z="ÇK", tuzak="Tanım çiftleri", madde="GK m.27/4, 28/e",
 cek="Satın alma komisyonu: ithalatçının temsilcisine yurtdışında satın almadaki temsil hizmeti için ödediği ücret; kıymete dahil edilmez",
 kok=["4458 sayılı Gümrük Kanununa göre gümrük kıymetinin belirlenmesinde geçen \"satın alma komisyonları\" ifadesinden aşağıdakilerden hangisi anlaşılır?"],
 d="İthalatçının temsilcisine, eşyanın satın alınmasında yurtdışında verdiği temsil hizmeti karşılığında ödediği ücret",
 c=["Satıcının temsilcisine, eşyanın Türkiye'ye satışında yurtdışında verdiği aracılık hizmeti karşılığında ödenen ücret",
    "Gümrük müşavirine, eşyanın Türkiye'deki gümrük işlemlerinin takibi karşılığında ithalatçı tarafından ödenen ücret",
    "İthalatçının, eşyanın Türkiye'de çoğaltılması hakkı için lisans sahibine yaptığı ve fiyata dahil olmayan ödemeler",
    "Taşıyıcıya, eşyanın giriş yerine kadar nakliyesi ile ilgili yükleme ve elleçleme karşılığında ödenen ücretler"],
 g="Satın alma komisyonları ifadesinden, ithalatçının temsilcisine kıymeti belirlenecek eşyanın satın alınmasında yurtdışında verdiği temsil hizmeti karşılığında ödediği ücret anlaşılır. Satın alma komisyonları gümrük kıymetine dahil edilmez.",
 t="Alıcı tarafındaki satın alma komisyonu ile satıcı tarafındaki satış komisyonu (kıymete ilave edilen) karıştırılmıştır.",
 kanit='12-KIYMET VE KAPLAR.txt: "ithalatçının temsilcisine kıymeti belirlenecek eşyanın satın alınmasında yurtdışında verdiği temsil hizmeti karşılığında ödediği ücret anlaşılır."'),

# 15 --------------------------------------------------------------- Kıymet (HESAP)
dict(konu="Kıymet", tip="HESAP", z="Z", tuzak="Belge eşleştirme", madde="GK m.27/1-a-i, 27/1-c, 28/a, 28/b, 28/e",
 cek="Kıymet hesabı: satış komisyonu ve satış koşulu royalti eklenir; satın alma komisyonu, ithal sonrası montaj ve giriş yeri sonrası nakliye eklenmez",
 kok=["(B) firması Almanya'dan bir makine ithal etmektedir. Eşyanın İzmir limanı teslim (CIF) fatura bedeli 40.000 TL'dir. Fatura bedeline dahil edilmemiş, alıcı tarafından üstlenilen ve ayrı gösterilen giderler şunlardır:",
      "- Satıcının temsilcisine ödenen satış komisyonu: 2.000 TL",
      "- İthalatçının yurtdışındaki temsilcisine ödenen satın alma komisyonu: 1.500 TL",
      "- Satış koşulu gereği ödenen royalti ve lisans ücreti: 3.000 TL",
      "- İthalattan sonra Türkiye'de yapılan montaj gideri: 4.000 TL",
      "- İzmir limanından fabrikaya kadar yapılan nakliye gideri: 1.000 TL",
      "4458 sayılı Gümrük Kanununa göre makinenin gümrük kıymeti kaç TL'dir?"],
 d="45.000 TL",
 c=["46.500 TL", "42.000 TL", "50.000 TL", "51.500 TL"],
 g="Fiilen ödenen fiyata satın alma komisyonları dışındaki komisyonlar (2.000 TL) ile satış koşulu olan royalti ve lisans ücreti (3.000 TL) eklenir: 40.000 + 2.000 + 3.000 = 45.000 TL. Satın alma komisyonu, ithalattan sonraki montaj giderleri ve giriş yerine varıştan sonraki nakliye giderleri ayırt edilebildiğinden kıymete dahil edilmez.",
 t="Satış komisyonu ile satın alma komisyonu karıştırılırsa 46.500; ayrı gösterilen ithal sonrası giderler de eklenirse 50.000 veya 51.500 TL bulunur.",
 kanit='12-KIYMET VE KAPLAR.txt: "i) Satın alma komisyonları dışındaki komisyonlar ve tellâliye," / "ithalattan sonra yapılan inşa, kurma, montaj, bakım veya teknik yardıma ilişkin giderler,"'),

# 16 --------------------------------------------------------------- Kıymet
dict(konu="Kıymet", tip="DĞ", z="O", tuzak="İstisna atlatma", madde="GK m.26/2",
 cek="Son yöntemde esas alınamayacaklar: yurtiçi satış fiyatı, iki alternatiften yükseği, ihraç ülkesi iç piyasa fiyatı, üçüncü ülke ihraç fiyatı, asgari/keyfi kıymet",
 kok=["4458 sayılı Gümrük Kanununa göre, satış bedeli yöntemi ve onu izleyen sıralı yöntemlerle belirlenemeyen ithal eşyasının gümrük kıymetinin belirlenmesine ilişkin aşağıdaki ifadelerden hangisi yanlıştır?"],
 d="Gümrük idaresinin, iki alternatif kıymetten yüksek olanını kabul etmesini öngören bir sistem gümrük kıymetinin belirlenmesinde esas alınabilir.",
 c=["Türkiye'de üretilen eşyanın Türkiye içindeki satış fiyatı, bu durumdaki eşyanın gümrük kıymetinin belirlenmesinde esas alınmaz.",
    "Eşyanın ihraç ülkesindeki iç piyasa fiyatı ile asgari gümrük kıymetleri, bu durumdaki eşyanın gümrük kıymetinin belirlenmesinde esas alınmaz.",
    "Türkiye'den başka bir ülkeye ihraç edilen eşyanın fiyatı, bu durumdaki eşyanın gümrük kıymetinin belirlenmesinde esas alınmaz.",
    "Bu durumdaki eşyanın gümrük kıymeti, uygun yöntemlerle ve Türkiye'de mevcut veriler esas alınarak belirlenir; fiktif kıymetler esas alınmaz."],
 g="Diğer yöntemlerle belirlenemeyen gümrük kıymeti, uygun yöntemlerle ve Türkiye'de mevcut veriler esas alınarak belirlenir. Bu belirlemede Türkiye'de üretilen eşyanın iç satış fiyatı, gümrük idaresinin iki alternatif kıymetten yüksek olanını kabul etmesini öngören sistem, ihraç ülkesi iç piyasa fiyatı, başka ülkeye ihraç fiyatı, asgari gümrük kıymetleri ile keyfi veya fiktif kıymetler esas alınmaz.",
 t="Yasaklı sayılan \"iki alternatiften yüksek olanı\" sistemi, idareye takdir yetkisi tanıyan bir yöntem gibi sunulmuştur.",
 protB=True,
 kanit='12-KIYMET VE KAPLAR.txt: "b) Gümrük idaresinin iki alternatif kıymetten yüksek olanının kabul etmesini öngören bir sistem,"'),

# 17 --------------------------------------------------------------- Kıymet
dict(konu="Kıymet", tip="DY", z="K", tuzak="İdare/makam karıştırma", madde="GY m.44/1; GK m.25/1",
 cek="İndirgeme ve hesaplanmış kıymet yönteminin sırası, beyan sahibinin yazılı talebinin gümrük idaresince uygun bulunmasıyla değiştirilebilir",
 kok=["Gümrük Yönetmeliğine göre, gümrük kıymetinin belirlenmesinde indirgeme yöntemi ile hesaplanmış kıymet yönteminin uygulama sırası hangi koşulla değiştirilebilir?"],
 d="Beyan sahibinin yazılı talebinin gümrük idaresince uygun bulunması şartıyla",
 c=["Gümrük idaresinin re'sen alacağı kararla, beyan sahibinin talebi aranmaksızın",
    "Beyan sahibinin sözlü veya yazılı talebi üzerine, idarenin onayı aranmaksızın",
    "Beyan sahibinin yazılı talebinin Bakanlıkça (Genel Müdürlükçe) onaylanması şartıyla",
    "Bu iki yöntemin uygulama sırası hiçbir koşulda değiştirilemez; sıralama kesindir"],
 g="Yöntemler sırasıyla uygulanır ve bir üst yöntemle kıymet belirlenebildiği sürece alt yönteme geçilemez. Ancak beyan sahibinin yazılı talebinin gümrük idaresince uygun bulunması şartıyla indirgeme yöntemi ile hesaplanmış kıymet yönteminin uygulama sırası değiştirilebilir.",
 t="Talep makamı (beyan sahibi) ile onay makamı (gümrük idaresi) yer değiştirilmiş ya da onay Bakanlığa kaydırılmıştır.",
 kanit='12-KIYMET VE KAPLAR.txt: "beyan sahibinin yazılı talebinin gümrük idaresince uygun bulunması şartıyla, aşağıda yer alan yöntemlerden indirgeme yöntemi ile hesaplanmış kıymet yönteminin uygulama sırası değiştirilebilir."'),

# 18 --------------------------------------------------------------- Kıymet
dict(konu="Kıymet", tip="ÇI", z="Z", tuzak="Eşik/oran kaydırma", madde="GY m.43/3, 43/4, 46/4, 48/3",
 cek="Aynı/benzer eşya yalnız aynı ülkede üretilmiş olur; indirgemede yakın tarih satış yoksa doksan gün içindeki ilk satış birim fiyatı esas",
 kok=["Gümrük Yönetmeliğine göre gümrük kıymetinin belirlenmesinde kullanılan yöntemlere ilişkin;",
      "I. Aynı eşyanın satış bedeli yönteminin uygulanması sırasında aynı eşyaya ilişkin birden fazla satış bedeli tespit edilirse bunlardan en yüksek olanı kullanılır.",
      "II. Yalnızca kıymeti belirlenecek eşya ile aynı ülkede üretilen eşya, aynı eşya veya benzer eşya olarak nitelenebilir.",
      "III. İndirgeme yönteminde, aynı veya yakın tarihte satış yoksa, ithal tarihinden itibaren doksan gün içinde ithal edildiği hal ve durumda Türkiye'de yapılan ilk satışa ait birim fiyat esas alınır.",
      "IV. Kıymeti belirlenecek eşya ile aynı kişi tarafından üretilmiş aynı veya benzer eşya bulunmadığı takdirde, farklı kişi tarafından üretilmiş eşya dikkate alınmaz.",
      "ifadelerinden hangileri doğrudur?"],
 d="II ve III",
 c=["I ve II", "I, II ve III", "II, III ve IV", "III ve IV"],
 g="Aynı veya benzer eşya yalnızca kıymeti belirlenecek eşya ile aynı ülkede üretilmiş eşyadır (II). İndirgeme yönteminde yakın tarihli satış yoksa ithal tarihinden itibaren doksan gün içindeki ilk satışın birim fiyatı esas alınır (III). Birden fazla satış bedelinden en düşük olanı kullanılır (I yanlış); aynı kişinin ürettiği eşya yoksa farklı kişinin ürettiği eşya dikkate alınır (IV yanlış).",
 t="I. öncülde \"en düşük\" kuralı \"en yüksek\"e çevrilmiş; IV. öncülde \"dikkate alınır\" hükmü olumsuzlanmıştır.",
 kanit='12-KIYMET VE KAPLAR.txt: "Yalnızca kıymeti belirlenecek eşya ile aynı ülkede üretilen eşya, \'aynı eşya\' veya \'benzer eşya\' olarak nitelenebilir." / "ithal tarihinden itibaren doksan gün içinde ithal edildiği hal ve durumda Türkiye\'de yapılan ilk satışına ait birim fiyat esas alınır."'),

# 19 --------------------------------------------------------------- Gümrüklenmiş değer (HESAP)
dict(konu="Gümrüklenmiş Değer", tip="HESAP", z="ÇZ", tuzak="Rejim sınıflandırma", madde="GK m.3/26, 235/1-c, 235/6",
 cek="İthalatta belgeye bağlı eşyada belge alınmış gibi beyan: gümrüklenmiş değerin (CIF+gümrük vergileri) iki katı; idareden önce bildirimde yüzde on",
 kok=["Serbest dolaşıma giriş rejimi kapsamında beyan edilen bir eşyanın CIF kıymeti 200.000 TL'dir. Eşyaya uygulanan tek ithalat vergisi %10 oranındaki gümrük vergisidir. Eşyanın ithali, belli bir kuruluşun vereceği ve gümrük idaresine ibrazı zorunlu uygunluk belgesine bağlı olduğu halde belge alınmış gibi beyanda bulunulmuş, söz konusu belge sonradan da düzenlenmemiştir. Beyan sahibi bu aykırılığı gümrük idaresince tespit edilmeden önce idareye bildirmiştir.",
      "4458 sayılı Gümrük Kanununa göre uygulanacak idari para cezası kaç TL'dir?"],
 d="44.000 TL",
 c=["40.000 TL", "22.000 TL", "88.000 TL", "440.000 TL"],
 g="İthal eşyasının gümrüklenmiş değeri CIF kıymeti ile gümrük vergileri toplamıdır: 200.000 + 20.000 = 220.000 TL. Belgeye bağlı eşyanın belge alınmış gibi beyanında gümrüklenmiş değerin iki katı ceza verilir: 440.000 TL. Aykırılık idarenin tespitinden önce bildirildiğinden ceza yüzde on oranında uygulanır: 44.000 TL.",
 t="Matrah olarak CIF alınırsa 40.000; ihracattaki \"onda biri\" oranı uygulanırsa 22.000; yasak eşyadaki dört kat uygulanırsa 88.000; önceden bildirim indirimi atlanırsa 440.000 TL bulunur.",
 kanit='1-TANIMLAR.txt: "ithal eşyası için eşyanın CIF kıymeti ile gümrük vergileri toplamını" 48-cezalar.txt: "gümrüklenmiş değerinin iki katı idari para cezası verilir." / "cezalar yüzde on oranında uygulanır."'),

# 20 --------------------------------------------------------------- Kıymet
dict(konu="Kıymet", tip="UK", z="K", tuzak="Belge eşleştirme", madde="GK m.30",
 cek="Kıymet TL beyan edilir; yabancı para, yükümlülüğün başladığı tarihte yürürlükteki TCMB döviz satış kuru ile çevrilir",
 kok=["(C) firması, faturası ABD Doları olarak düzenlenmiş eşyayı serbest dolaşıma sokmak üzere beyanname vermiştir.",
      "4458 sayılı Gümrük Kanununa göre, eşyanın gümrük vergisine esas alınacak kıymetinin beyanı ve faturadaki yabancı paranın çevrilmesi bakımından aşağıdakilerden hangisi doğrudur?"],
 d="Kıymet Türk Lirası olarak beyan edilir; yabancı para, gümrük yükümlülüğünün başladığı tarihte yürürlükte olan T.C. Merkez Bankası döviz satış kuru üzerinden çevrilir.",
 c=["Kıymet Türk Lirası olarak beyan edilir; yabancı para, gümrük yükümlülüğünün başladığı tarihte yürürlükte olan T.C. Merkez Bankası efektif alış kuru üzerinden çevrilir.",
    "Kıymet fatura dövizi üzerinden beyan edilebilir; yabancı para, eşyanın gümrük idaresince teslim edildiği tarihteki T.C. Merkez Bankası döviz satış kuru üzerinden çevrilir.",
    "Kıymet Türk Lirası olarak beyan edilir; yabancı para, faturanın düzenlendiği tarihte yürürlükte olan T.C. Merkez Bankası döviz alış kuru üzerinden çevrilir.",
    "Kıymet Türk Lirası olarak beyan edilir; yabancı para, bedelin satıcıya fiilen ödendiği tarihte bankanın uyguladığı serbest piyasa kuru üzerinden çevrilir."],
 g="Gümrük vergisine esas alınacak kıymetin Türk Lirası olarak beyanı zorunludur. Fatura veya diğer belgelerde yazılı yabancı paralar, gümrük yükümlülüğünün başladığı tarihte yürürlükte olan T.C. Merkez Bankası döviz satış kurları üzerinden Türk Lirasına çevrilir.",
 t="Kıymet çevriminde döviz satış kuru uygulanır; efektif alış kuru, yabancı paraların teminat olarak kabulünde kullanılan kurdur ve burada karıştırılmıştır.",
 kanit='12-KIYMET VE KAPLAR.txt: "Fatura veya diğer belgelerde yazılı yabancı paralar, gümrük yükümlülüğünün başladığı tarihte yürürlükte olan T.C. Merkez Bankası döviz satış kurları üzerinden Türk Lirasına çevrilir."'),
]
