# -*- coding: utf-8 -*-
# Batch D – 2025 GMY kitapçık 59–80 konularına benzer özgün sorular
# Alanlar: konu, tip, z, tuzak, madde, cek, kok, d, c, g, t, protB, kanit
Q = [
# 1 ─ Dahilde İşleme / belge süresi
dict(konu="Dahilde İşleme", tip="SÜ", z="K", tuzak="Süre kaydırma",
 madde="DİR Tebliği (İhracat 2006/12) m.20/1, 20/3",
 cek="Belge süresi sektörüne göre azami 12 ay; başlangıç belge tarihi, süre sonu bitimin rastladığı ayın son günü",
 kok=["Dahilde İşleme Rejimi Tebliği (İhracat 2006/12) uyarınca, gemi inşası, komple tesis veya savunma sanayi ürünlerine ilişkin olmayan bir dahilde işleme izin belgesinin süresi hakkında aşağıdakilerden hangisi doğrudur?"],
 d="Süre sektörüne göre azami on iki aya kadar tespit edilir; belge tarihinde başlar, bitiminin rastladığı ayın son günü sona erer.",
 c=["Süre sektörüne göre azami on iki aya kadar tespit edilir; ilk ithalat tarihinde başlar, bitiminin rastladığı ayın son günü sona erer.",
    "Süre sektörüne göre azami yirmi dört aya kadar tespit edilir; belge tarihinde başlar, belge tarihine tekabül eden günde sona erer.",
    "Süre sektörüne göre azami on iki aya kadar tespit edilir; belge tarihinde başlar, bitimini izleyen ayın son iş günü sona erer.",
    "Süre sektörüne göre azami altı aya kadar tespit edilir; ilk ihracat tarihinde başlar, bitimine rastlayan günün mesai saati sonunda sona erer."],
 g="Dahilde işleme izin belgesinin süresi sektörüne göre azami 12 aya kadar tespit edilebilir. Sürenin başlangıcı belgenin tarihidir; süre sonu ise ek süreler dahil, belge süresi bitiminin rastladığı ayın son günüdür. Süre ay olarak belirlenmiştir; iş günü esasına dayanmaz.",
 t="Başlangıç \"ilk ithalat tarihi\"ne, bitiş \"izleyen ayın son iş günü\"ne kaydırılmıştır. İlk ithalat tarihi yalnızca azami 3 aylık ek süre hesabında esas alınır.",
 kanit="32-DAHİLDE İŞLEME.txt: «Dahilde işleme izin belgesinin/dahilde işleme izninin süresi sektörüne göre azami 12 (oniki) aya kadar tespit edilebilir.» … «Sürenin başlangıcı, dahilde işleme izin belgesinin/dahilde işleme izninin tarihidir.»"),

# 2 ─ Dahilde İşleme / performansa dayalı ek süre (HESAP)
dict(konu="Dahilde İşleme", tip="HESAP", z="Z", tuzak="Eşik/oran kaydırma",
 madde="DİR Tebliği (İhracat 2006/12) m.22/1, 22/2",
 cek="Performansa dayalı ek süre: ihracat/taahhüt oranı en az %25 ise belge orijinal süresinin yarısı kadar",
 kok=["Dahilde İşleme Rejimi Tebliği (İhracat 2006/12) çerçevesinde iki firmanın dahilde işleme izin belgelerine ilişkin bilgiler şöyledir:",
      "X firması: Belge orijinal süresi 10 ay; gerçekleştirilen ihracat değerinin belge ihracat taahhüdü değerine oranı %20.",
      "Y firması: Belge orijinal süresi 8 ay; gerçekleştirilen ihracat değerinin belge ihracat taahhüdü değerine oranı %40.",
      "Belgeli performansa istinaden verilebilecek ek süre bakımından aşağıdakilerden hangisi doğrudur?"],
 d="X firmasına bu kapsamda ek süre verilemez; Y firmasının belgesine ise 4 ay ek süre verilebilir.",
 c=["X firmasına 5 ay, Y firmasına 4 ay ek süre verilebilir; oran şartı yalnızca gemi inşası belgelerinde aranır.",
    "X firmasına bu kapsamda ek süre verilemez; Y firmasının belgesine ise 8 ay ek süre verilebilir.",
    "Her iki firmaya da ilk ithalat tarihi esas alınarak yalnızca azami 3 ay ek süre verilebilir.",
    "X firmasına 2 ay, Y firmasına 3,2 ay ek süre verilebilir; süre ihracat oranıyla orantılıdır."],
 g="Belge kapsamında gerçekleştirilen ihracat değerinin taahhüt değerine oranı en az %25 ise belgeye orijinal süresinin yarısı kadar ek süre verilebilir. X firmasında oran %20 olduğundan bu kapsamda ek süre verilemez; Y firmasında oran %40 olduğundan 8 / 2 = 4 ay ek süre verilebilir. İlk ithalat tarihine dayalı azami 3 aylık uzatma ayrı bir düzenlemedir.",
 t="%25 eşiği gözden kaçırılır ya da ek süre ihracat oranıyla orantılı hesaplanır; oysa eşik aşıldığında ek süre sabit olarak orijinal sürenin yarısıdır.",
 kanit="32-DAHİLDE İŞLEME.txt: «ihracat değerinin belge ihracat taahhüdü değerine oranının en az % 25 olması halinde» … «dahilde işleme izin belgesine belge orijinal süresinin yarısı kadar ek süre verilebilir.»"),

# 3 ─ Dahilde İşleme / haklı sebep müracaatı (UU, ÇZ)
dict(konu="Dahilde İşleme", tip="UU", z="ÇZ", tuzak="İdare/makam karıştırma",
 madde="DİR Tebliği (İhracat 2006/12) m.23/1-a, 23/1-b, 23/2",
 cek="Haklı sebep müracaatı: belge → 3 ay içinde elektronik ortamda Bakanlığa; izin → 2 ay içinde gümrük idaresine; süresinde yapılmayan değerlendirilmez",
 kok=["Dahilde İşleme Rejimi Tebliği (İhracat 2006/12) uyarınca, firmaların haklı sebep hallerinden yararlanmak üzere yapacakları müracaatın yeri ve süresi hakkında aşağıdakilerden hangisi doğrudur?"],
 d="Belge için en geç belge süresi sonundan itibaren üç ay içinde elektronik ortamda Bakanlığa, izin için en geç izin süresi sonundan itibaren iki ay içinde ilgili gümrük idaresine başvurulur; süresinde yapılmayan müracaat değerlendirmeye alınmaz.",
 c=["Belge için en geç belge süresi sonundan itibaren iki ay içinde ilgili gümrük idaresine, izin için en geç izin süresi sonundan itibaren üç ay içinde elektronik ortamda Bakanlığa başvurulur; süresinde yapılmayan müracaat değerlendirmeye alınmaz.",
    "Belge ve izin için en geç süre sonundan itibaren üç ay içinde ihracatçı birlikleri genel sekreterliklerine başvurulur; süresinde yapılmayan müracaat, gecikme gerekçesi belgelenirse ayrıca değerlendirmeye alınır.",
    "Belge için süre sonundan itibaren üç ay içinde elektronik ortamda Bakanlığa, izin için süre sonundan itibaren üç ay içinde ilgili gümrük idaresine başvurulur; süresinde yapılmayan müracaat idarece bir ay içinde tamamlatılır.",
    "Belge için belge süresi bitmeden önce elektronik ortamda Bakanlığa, izin için izin süresi bitmeden önce ilgili bölge müdürlüğüne başvurulur; süre sonrasındaki müracaatlar mücbir sebep halinde değerlendirmeye alınır."],
 g="Haklı sebep hallerinden yararlanmak için dahilde işleme izin belgesinde en geç belge süresi sonundan itibaren 3 ay içinde elektronik ortamda Bakanlığa; dahilde işleme izninde ise tevsik edici bilgi ve belgelerle en geç izin süresi sonundan itibaren 2 ay içinde ilgili gümrük idaresine müracaat edilir. Bu sürelerde yapılmayan müracaat değerlendirmeye alınmaz.",
 t="Belge (Bakanlık, 3 ay) ile izin (gümrük idaresi, 2 ay) arasındaki makam ve süre ayrımı çapraz eşleştirilmiştir; ayrıca süre aşımına \"tamamlatma\" ya da \"gerekçeyle kabul\" sonucu bağlanmıştır.",
 kanit="32-DAHİLDE İŞLEME.txt: «Firmaların haklı sebep hallerinden yararlanabilmesi için;» … «en geç izin süresi sonundan itibaren 2 (iki) ay[39] içerisinde ilgili gümrük idaresine,» … «Birinci fıkrada belirtilen sürede yapılmayan müracaat değerlendirmeye alınmaz.»",
 protB=True),

# 4 ─ Dahilde İşleme / döviz kullanım oranı (ÇI)
dict(konu="Dahilde İşleme", tip="ÇI", z="Z", tuzak="İstisna atlatma",
 madde="DİR Tebliği (İhracat 2006/12) m.17/8, 17/9, 17/10",
 cek="Döviz kullanım oranı: azami %80, ikincil tarım ürünlerinde %100'e kadar; izinde, bedelsiz ithalatta ve yurt içi alımlarda aranmaz",
 kok=["Dahilde İşleme Rejimi Tebliği (İhracat 2006/12) uyarınca döviz kullanım oranına ilişkin;",
      "I. Dahilde işleme izin belgesi kapsamında döviz kullanım oranı %80'i geçmemek üzere Bakanlıkça belirlenir.",
      "II. İkincil işlem görmüş tarım ürünleri taahhüdü içeren belgelerde bu oran azami %100 olarak tespit edilebilir.",
      "III. Dahilde işleme izninde döviz kullanım oranı aranmaz.",
      "IV. Dahilde işleme izin belgesi kapsamındaki yurt içi alımlarda döviz kullanım oranı aranır.",
      "V. Bakanlık, uluslararası emtia piyasalarındaki konjonktürel fiyat dalgalanmaları nedeniyle azami oranları dönemsel veya sektörel olarak yükseltebilir.",
      "ifadelerinden hangileri doğrudur?"],
 d="I, II, III ve V",
 c=["I, II, IV ve V", "II, III, IV ve V", "I, III, IV ve V", "I, II ve III"],
 g="Döviz kullanım oranı belge kapsamında %80'i geçmemek üzere Bakanlıkça belirlenir; ikincil işlem görmüş tarım ürünleri taahhüdü içeren belgelerde azami %100 olarak tespit edilebilir (I, II). Döviz kullanım oranı dahilde işleme izninde, belge kapsamındaki bedelsiz ithalatta ve yurt içi alımlarda aranmaz (III doğru, IV yanlış). Bakanlık konjonktürel fiyat dalgalanmaları nedeniyle azami oranları dönemsel veya sektörel olarak yükseltmeye yetkilidir (V).",
 t="IV. öncül, oranın aranmadığı istisnalardan biri olan yurt içi alımları kurala dahil eder.",
 kanit="32-DAHİLDE İŞLEME.txt: «Dahilde işleme izin belgesi kapsamında döviz kullanım oranı % 80'i geçmemek üzere Bakanlıkça belirlenir. Ancak, ikincil işlem görmüş tarım ürünleri taahhüdü içeren belgelerde bu oran Bakanlıkça azami % 100 olarak tespit edilebilir.»"),

# 5 ─ Dahilde İşleme / mücbir sebepte tevsik belgesi (BD)
dict(konu="Dahilde İşleme", tip="BD", z="O", tuzak="Belge eşleştirme",
 madde="DİR Tebliği (İhracat 2006/12) m.25/1-e",
 cek="Mücbir sebep/fevkalade hal olarak grev ve lokavt: il çalışma müdürlüklerinden alınacak yazı ile tevsik",
 kok=["Dahilde İşleme Rejimi Tebliği (İhracat 2006/12) uyarınca, belge süresi içinde yükümlü firmada grev veya lokavt yaşanması halinde, mücbir sebep ve fevkalade hal kapsamında ilave süre talebinde durumun tevsiki için öngörülen belge aşağıdakilerden hangisidir?"],
 d="İl çalışma müdürlüklerinden alınacak yazı",
 c=["Firmanın kayıtlı olduğu ticaret odasından alınacak yazı",
    "Mahkemece verilmiş delil tespiti kararı",
    "İhracatçı birliği genel sekreterliğinden alınan yazı",
    "Mahalli mülki idare amirinden alınacak yazı"],
 g="Mücbir sebep ile fevkalade haller arasında sayılan grev ve lokavt, il çalışma müdürlüklerinden alınacak yazı ile tevsik edilir. Mahkeme kararı ise yükümlü firmanın iflası, konkordato ilanı veya iflasın ertelenmesi hali için öngörülmüştür.",
 t="Her mücbir sebep türü için ayrı bir tevsik belgesi öngörülmüştür; iflas/konkordato için istenen mahkeme kararı grev ve lokavt hali ile karıştırılmaktadır.",
 kanit="32-DAHİLDE İŞLEME.txt: «e) Grev ve lokavt (İl çalışma müdürlüklerinden alınacak yazı ile).»"),

# 6 ─ Dahilde İşleme / geri ödemede vergi iadesi müracaatı (MK)
dict(konu="Dahilde İşleme", tip="MK", z="K", tuzak="İdare/makam karıştırma",
 madde="DİR Tebliği (İhracat 2006/12) m.13/1",
 cek="Geri ödeme sisteminde taahhüt kapatılmasını müteakip 3 ay içinde vergi iadesi için ilgili gümrük idaresine müracaat zorunlu",
 kok=["Dahilde İşleme Rejimi Tebliği (İhracat 2006/12) uyarınca, geri ödeme sistemi çerçevesinde düzenlenen belgenin ihracat taahhüdü kapatıldıktan sonra, ithalat sırasında ödenen vergilerin iadesi için müracaat edilecek merci ve süre aşağıdakilerden hangisidir?"],
 d="Kapatmayı müteakip üç ay içinde ilgili gümrük idaresine",
 c=["Kapatmayı müteakip üç ay içinde ilgili vergi dairesine",
    "Kapatmayı müteakip bir ay içinde İhracat Genel Müdürlüğüne",
    "Kapatmayı müteakip altı ay içinde ilgili bölge müdürlüğüne",
    "Kapatmayı müteakip üç ay içinde ihracatçı birliğine"],
 g="Geri ödeme sistemi çerçevesinde düzenlenen belgenin ihracat taahhüdü kapatıldıktan sonra 3 ay içinde, ithalat sırasında ödenen vergilerin iadesi için ilgili gümrük idaresine müracaat edilmesi zorunludur. Geri verme kararının alındığı tarihten itibaren 3 ay içinde iade yapılmazsa tecil faizi hükümleri işler.",
 t="Vergiyi tahsil eden ve iade eden merci gümrük idaresidir; taahhüdü kapatan bölge müdürlüğü veya vergi dairesi ile karıştırılmaktadır.",
 kanit="32-DAHİLDE İŞLEME.txt: «kapatılmasını müteakip 3 (üç) ay içerisinde, ithalat sırasında ödenen vergilerin iadesi için ilgili gümrük idaresine müracaat edilmesi zorunludur.»"),

# 7 ─ İhracat / beyanname yerine ticari-idari belge (DY)
dict(konu="İhracat", tip="DY", z="O", tuzak="İstisna atlatma",
 madde="GY m.156/1, 156/2, 156/3",
 cek="Kumanya/yağ/yakıt veren ve periyodik basılı yayın ihraç edenler: ticari/idari belge talebi YYS/OKSB koşulları aranmaksızın kabul edilir",
 kok=["Gümrük Yönetmeliği uyarınca, ihracat rejiminde beyanname yerine ticari veya idari bir belge tescil ettirilerek işlem yapılmasına ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="Gemilere kumanya, yağ ve yakıt verme şeklinde ihracat yapanların yazılı talebi, yetkilendirilmiş yükümlü veya onaylanmış kişi statüsü koşulları aranmaksızın kabul edilir.",
 c=["Gemilere kumanya, yağ ve yakıt verme şeklinde ihracat yapanların yazılı talebi, ancak yetkilendirilmiş yükümlü sertifikasına sahip olmaları halinde kabul edilir.",
    "Kitap ve diğer basılı yayın ihraç edenlerin talebi, farklı gümrük idarelerinden ve düzensiz aralıklarla ihracat yapmaları halinde de aynı koşullarla kabul edilir.",
    "Bu usulde düzenlenen ticari veya idari belgede eşyanın teşhisini sağlayan bilgilerin yer alması yeterli olup ayrıca herhangi bir ibare aranmaz.",
    "Beyanname yerine kabul edilecek idari ve ticari belgelerin nitelik ve içereceği bilgileri belirlemeye ihracatçı birlikleri genel sekreterlikleri münhasıran yetkilidir."],
 g="Aynı gümrük idaresinden sürekli ve periyodik olarak kitap ve basılı yayın ihraç edenler ile gemilere kumanya, yağ, yakıt ve diğer malzeme verme şeklinde ihracat yapanların ticari veya idari belge tescili yönündeki yazılı talepleri, yetkilendirilmiş yükümlü veya onaylanmış kişi statüsü koşulları aranmaksızın kabul edilir. Belgede teşhis bilgileri ile 'Basitleştirilmiş İhracat' ifadesi yer alır; belgelerin niteliğini belirlemeye Müsteşarlık (Bakanlık) yetkilidir.",
 t="Eksik beyanda aranan YYS/OKSB şartı bu usule taşınmıştır; oysa bu usulde statü koşulları aranmaz. Basılı yayında \"aynı gümrük idaresi, sürekli ve periyodik\" şartı da atlatılmıştır.",
 kanit="17-BEYAN.txt: «gemilere kumanya, yağ, yakıt ve diğer malzeme verme şeklinde ihracat gerçekleştirenlerin beyanname yerine ticari veya idari bir belge tescil ettirmek suretiyle işlem yapma konusundaki yazılı talepleri yetkilendirilmiş yükümlü veya onaylanmış kişi statüsüne ilişkin koşullar aranmaksızın kabul edilir.»",
 protB=True),

# 8 ─ İhracat / fiili ihracat tarihi (TN)
dict(konu="İhracat", tip="TN", z="O", tuzak="Tanım çiftleri",
 madde="GY m.416/1-a, 416/1-c",
 cek="Kara/demiryolu çıkışında TGB'yi terk tarihi: kara sınırından fiilen çıkış veya serbest bölgeye fiilen giriş; taşıtlara teslimde teslim tarihi",
 kok=["Gümrük Yönetmeliği uyarınca, eşyanın Türkiye Gümrük Bölgesini terk ettiği tarihin belirlenmesine ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="Kara yoluyla serbest bölgeye yapılan çıkışlarda, çıkış işlemleri tamamlanan eşyanın serbest bölgeye fiilen girdiği tarih esas alınır.",
 c=["Kara yoluyla yabancı ülkeye yapılan çıkışlarda, ihracat beyannamesinin çıkış gümrük idaresinde tescil edildiği tarih esas alınır.",
    "Dış sefere çıkacak gemilere yapılan kumanya teslimlerinde, kumanyayı alan geminin limandan hareket ettiği tarih esas alınır.",
    "Demir yoluyla yapılan çıkışlarda, eşyanın yüklendiği vagonun hareket gümrük idaresince mühürlendiği tarih esas alınır.",
    "Kara yoluyla yapılan çıkışlarda, eşyanın muayenesinin çıkış gümrük idaresince tamamlanarak onaylandığı tarih esas alınır."],
 g="Kara ve demir yoluyla çıkışlarda eşyanın, çıkış işlemleri tamamlanıp kara sınırından yabancı bir ülkeye fiilen çıktığı veya serbest bölgeye fiilen girdiği tarih; dış seferdeki veya dış sefere çıkacak deniz ve hava taşıtlarına yapılan teslimlerde ise eşyanın teslim edildiği tarih, Türkiye Gümrük Bölgesini terk tarihi olarak kabul edilir.",
 t="Deniz ve hava yolu için geçerli \"taşıtın hareket ettiği tarih\" ölçütü, taşıtlara yapılan kumanya teslimlerine taşınmıştır; bu teslimlerde ölçüt teslim tarihidir. Tescil, mühürleme ve muayene anları ise terk tarihi değildir.",
 kanit="36-ihracat.txt: «Kara ve demir yoluyla çıkışlarda, gümrük idaresince çıkış işlemleri tamamlanıp kara sınırından yabancı bir ülkeye fiilen çıktığı veya serbest bölgeye fiilen girdiği,»",
 protB=True),

# 9 ─ İhracat / geçici depolama süresi (UK)
dict(konu="İhracat", tip="UK", z="O", tuzak="Süre kaydırma",
 madde="GY m.417/1",
 cek="İhracat amaçlı geçici depolamada eşya bir ay kalır; beyanname tescilinden bağımsız ek süre talebinde en çok üç ay ek süre",
 kok=["İhraç amacıyla geçici depolama yerine konulan bir eşya için, bir aylık süre içinde ve henüz beyanname tescil edilmeden ek süre talebinde bulunulmuştur.",
      "Gümrük Yönetmeliği uyarınca bu talep hakkında aşağıdakilerden hangisi doğrudur?"],
 d="Gümrük müdürlüğünce en çok üç aya kadar ek süre verilebilir; beyannamenin henüz tescil edilmemiş olması talebi engellemez.",
 c=["Gümrük müdürlüğünce en çok iki aya kadar ek süre verilebilir; ancak ek süre talebi yalnızca beyanname tescil edilmişse kabul edilir.",
    "Gümrük müdürlüğünce en çok üç aya kadar ek süre verilebilir; ancak ek süre talebi yalnızca beyanname tescil edilmişse kabul edilir.",
    "Ek süre verilemez; bir aylık süre dolduğunda eşya, tebligata gerek kalmaksızın doğrudan gümrüğe terk edilmiş sayılır.",
    "Gümrük ve dış ticaret bölge müdürlüğünce altı aya kadar ek süre verilebilir; ek süre içinde beyanname tescili zorunludur."],
 g="İhracat veya yeniden ihracat amacıyla geçici depolama yerine konulan eşya burada bir ay kalabilir. Beyanname tescil edilip edilmediğine bakılmaksızın bu süre içinde talep edilmesi halinde gümrük müdürlüklerince en çok üç aya kadar ek süre verilebilir. Süreler ay olarak belirlenmiştir.",
 t="Ek süre talebi beyanname tesciline bağlanmıştır; mevzuat \"tescil edilip edilmediğine bakılmaksızın\" der. Ayrıca geçici depolamaya konulmaksızın ihraçta geçerli \"iki ay\" süresi ile karıştırılır.",
 kanit="36-ihracat.txt: «Sözü edilen eşya ile ilgili olarak beyanname tescil edilip edilmediğine bakılmaksızın bu süre içinde ek süre talebinde bulunulması halinde, gümrük müdürlüklerince en çok üç aya kadar ek süre verilebilir.»"),

# 10 ─ Geri gelen eşya / muafiyet şartları (ÇI)
dict(konu="Geri Gelen Eşya", tip="ÇI", z="O", tuzak="İstisna atlatma",
 madde="GY m.446/1, 446/2, 446/3-b, 446/4",
 cek="Geri gelme nedeni yurt dışındaki alıcı/kurum belgesiyle ispat; kusurluda ilk kullanım sınırı; ticari taşıt ve iş makinesine ayniyetle şartsız muafiyet",
 kok=["Gümrük Yönetmeliği uyarınca, kesin ihracı yapıldıktan sonra geri gelen eşyanın geri gelen eşya muafiyetinden yararlanmasına ilişkin;",
      "I. Kusurlu olması nedeniyle alıcısınca kabul edilmeyen eşyanın, ilk kullanım dışında kullanılmamış olması gerekir.",
      "II. Satılmak amacıyla yurt dışındaki bir fuara gönderilip satılmadan geri gelen eşya, ihracatçının elinde olmayan sebeplerle amaçlanan kullanıma girememiş eşya sayılır.",
      "III. Serbest dolaşımda iken ihraç edilip geri gelen iş makineleri, ayniyet tespiti kaydıyla geri gelme nedenine ilişkin şartlar aranmaksızın muafiyetten yararlanır.",
      "IV. Geri gelme nedeninin ispatı, ihracatçının Türkiye'de düzenleyeceği taahhütname ile yapılır.",
      "ifadelerinden hangileri doğrudur?"],
 d="I, II ve III",
 c=["I ve III", "I, III ve IV", "I, II ve IV", "I, II, III ve IV"],
 g="Kusurlu olma veya sözleşmeye uygun olmama nedeniyle geri gelen eşyanın ilk kullanım dışında kullanılmamış olması gerekir (I). Tüketilmek veya satılmak amacıyla yurt dışındaki sergi ve fuarlara gönderilip satılmadan geri gelen eşya, ihracatçının elinde olmayan sebepler kapsamındadır (II). Ticari kullanıma mahsus taşıt araçları, iş makineleri ve üretime yönelik makineler ayniyet tespiti kaydıyla diğer şartlara bağlı olmaksızın muafiyetten yararlanır (III). Geri gelme nedeni Türkiye Gümrük Bölgesi dışındaki alıcıdan veya yetkili kurumlardan alınacak belgelerle ispatlanır; ihracatçının taahhütnamesi yeterli değildir (IV yanlış).",
 t="IV. öncül, ispatın yurt dışı kaynaklı belgeyle yapılması şartını atlatarak ihracatçının kendi beyanına dayandırır.",
 kanit="37-geri gelen eşya.txt: «Birinci fıkranın (b) bendinde belirtilen durumlarda eşyanın ilk kullanım dışında kullanılmamış olması gerekmektedir.» … «Türkiye Gümrük Bölgesi dışındaki alıcıdan veya Türkiye Gümrük Bölgesi dışındaki yetkili kurumlardan alınacak belgelerle gümrük idaresine ispatı gerekir.»"),

# 11 ─ Kumanya / yakıt ve kumanya işlemleri (DĞ)
dict(konu="Kumanya", tip="DĞ", z="K", tuzak="Rejim sınıflandırma",
 madde="GY m.477/2-3, 479/1, 480/1, 482/2",
 cek="Dış seferden dönüp yükünü boşaltan geminin ihraç yükü almak üzere diğer Türk limanına hareketi dış seferin devamı sayılır",
 kok=["Gümrük Yönetmeliğinde yer alan yakıt ve kumanyaya ilişkin hükümlere göre aşağıdaki ifadelerden hangisi yanlıştır?"],
 d="Yurt dışı seferden dönüp yükünün tamamını boşaltan geminin, ihraç yükü almak üzere başka bir Türk limanına hareketi kabotaj seferi sayılır.",
 c=["Şüphe veya ihbar olmadıkça yakıt, yağ ve kumanya muayeneye tabi tutulmaz ve yalnızca gümrük idaresinin gözetimi altında gemiye yüklenir.",
    "Türkiye Gümrük Bölgesi dışına sefer yapan Türk bandıralı gemilerde, sayfaları gümrük idaresince önceden onanan yakıt ve kumanya defteri tutulur.",
    "Türk bandıralı gemiler, yabancı limanlardan gelişlerinde yakıt ve kumanyaları için düzenledikleri listeyi ilk uğrayacakları Türk limanında verir.",
    "Kumanya listeleri, geminin gideceği yer ile gemiye verilecek kumanyanın cins ve miktarını belirtecek şekilde düzenlenerek gümrük idaresine bildirilir."],
 g="Yurt dışı seferden dönen gemilerin Türk limanlarında yüklerinin tamamını boşalttıktan sonra diğer Türk limanlarına ihraç yükü almak üzere boş veya kısmen ihraç yükü alarak hareket etmeleri dış seferin devamı sayılır; kabotaj seferi olarak nitelendirilmez. Diğer ifadeler Yönetmelikteki muayene, yakıt ve kumanya defteri, liste ve kumanya listesi hükümleriyle örtüşür.",
 t="İki Türk limanı arasındaki hareket ilk bakışta kabotaj gibi görünür; ancak ihraç yükü almak amacıyla yapılan bu hareket dış seferin devamı olarak sınıflandırılmıştır.",
 kanit="42-kumanya.txt: «Yurt dışı seferden dönen gemilerin Türk limanlarında yüklerinin tamamını boşalttıktan sonra diğer Türk limanlarına ihraç yükünü almak üzere boş veya kısmen ihraç yükü alarak hareket etmeleri hali de dış seferin devamı sayılır.»"),

# 12 ─ Transit / telef-kayıp kanıtlama belgeleri (EŞ)
dict(konu="Transit", tip="EŞ", z="Z", tuzak="Belge eşleştirme",
 madde="GY m.228/1-a, b, c",
 cek="Telef/kayıp kanıtı: suçüstü hırsızlık → Cumhuriyet Savcılığı belgesi; herkesçe bilinen olay → en büyük mülki amir; trafik kazası → gümrük idare amiri kararı",
 kok=["Gümrük Yönetmeliği uyarınca, transit rejimine tabi eşyanın mücbir sebep veya beklenmeyen haller nedeniyle telef veya kaybının kanıtlanmasında olay türü ile kanıtlayıcı belge eşleştirmesi aşağıdakilerden hangisinde doğru verilmiştir?",
      "1. Suçüstü şeklindeki hırsızlık",
      "2. Herkesçe bilinen ve duyulan başka bir olay",
      "3. Trafik kazası",
      "a. Trafik kaza raporuna göre ve en yakın gümrük idaresinin tespiti sonucunda gümrük idare amirinin vereceği karar",
      "b. Hazırlık tahkikatı üzerine Cumhuriyet Savcılığınca verilen belge",
      "c. O yerin en büyük mülki idare amiri tarafından verilecek belge"],
 d="1-b, 2-c, 3-a",
 c=["1-a, 2-b, 3-c", "1-c, 2-b, 3-a", "1-b, 2-a, 3-c", "1-c, 2-a, 3-b"],
 g="Telef veya kayıp; suçüstü şeklindeki hırsızlıklarda hazırlık tahkikatı üzerine Cumhuriyet Savcılığınca verilen belge ile, herkesçe bilinen ve duyulan başka olaylarda o yerin en büyük mülki idare amirinin vereceği belge ile, trafik kazalarında ise trafik kaza raporuna göre ve en yakın gümrük idaresinin tespiti sonucunda gümrük idare amirinin vereceği karar ile kanıtlanır.",
 t="Trafik kazasında karar merciinin mülki amir değil gümrük idare amiri olduğu; mülki amir belgesinin ise herkesçe bilinen olaylar için öngörüldüğü karıştırılır.",
 kanit="20-TRANSİT REJİMİ.txt: «Suçüstü şeklindeki hırsızlıklar, hazırlık tahkikatı üzerine Cumhuriyet Savcılığınca verilen belge ile,» … «o yerin en büyük mülki idare amiri tarafından verilecek belge ile,»"),

# 13 ─ Transit / ulusal transitte eksiklik ispat süresi (SÜ)
dict(konu="Transit", tip="SÜ", z="O", tuzak="Süre kaydırma",
 madde="GY m.239/1-a",
 cek="Ulusal transitte eksiklik: uyuşmazlık bildiriminden itibaren 28 gün içinde hareket idaresine ispat; yazılı başvuruyla 28 gün daha",
 kok=["Gümrük Yönetmeliği uyarınca, ulusal transit rejimi altında taşınan serbest dolaşımda olmayan eşyanın varış gümrük idaresinde beyanda belirtilen cinsine uygun olmakla birlikte eksik çıkması ve vergilerin varışta ödenmemesi halinde, eksikliğin mahrecindeki eksik yüklemeden kaynaklandığının ispatına ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="Uyuşmazlık bildiriminden itibaren 28 gün içinde hareket gümrük idaresine ispat edilir; süre yazılı başvuruyla 28 gün daha uzatılabilir.",
 c=["Varış bildiriminden itibaren 28 gün içinde varış gümrük idaresine ispat edilir; süre yazılı başvuruyla 28 gün daha uzatılabilir.",
    "Uyuşmazlık bildiriminden itibaren 30 iş günü içinde hareket gümrük idaresine ispat edilir; bu süre hiçbir şekilde uzatılamaz.",
    "Varış bildirimini müteakip 3 gün içinde varış gümrük idaresine ispat edilir; süre yazılı başvuruyla 3 gün daha uzatılabilir.",
    "Uyuşmazlık bildiriminden itibaren 28 gün içinde hareket gümrük idaresine ispat edilir; süre yalnızca Bakanlık onayıyla 60 gün daha uzatılabilir."],
 g="Varış gümrük idaresince eksik çıkan miktar üzerinden hareket gümrük idaresine uyuşmazlık bildirilir. Eksikliğin mahrecindeki eksik yüklemeden veya yanlış beyandan kaynaklandığının uyuşmazlık bildiriminden itibaren 28 gün içinde rejim hak sahibince hareket gümrük idaresine ispatı gerekir; bu süre yazılı başvuru halinde 28 gün daha uzatılabilir. Süre \"gün\" olarak belirlenmiştir, iş günü olarak nitelenmemiştir. Varış bildirimini müteakip üç günlük süre ise vergi ve cezanın varışta ödenmesi seçeneğine ilişkindir.",
 t="İspat merci (hareket idaresi) varış idaresiyle, başlangıç anı (uyuşmazlık bildirimi) varış bildirimiyle karıştırılır; varışta ödemeye ilişkin üç günlük süre ispat süresine taşınır.",
 kanit="20-TRANSİT REJİMİ.txt: «uyuşmazlık bildiriminden itibaren 28 gün içerisinde rejim hak sahibince hareket gümrük idaresine ispat edilmesi gerekir. Bu süre yazılı başvuru halinde 28 gün daha uzatılabilir.»"),

# 14 ─ Transit / teminat aranmayan taşımalar (ÇI)
dict(konu="Transit", tip="ÇI", z="O", tuzak="İstisna atlatma",
 madde="GY m.222/1",
 cek="Transitte teminat aranmayan taşımalar: havayolu, boru hattı, denizyolu ve basitleştirilmiş usulde demiryolu",
 kok=["Gümrük Yönetmeliği uyarınca, transit rejimi kapsamında aşağıdaki taşımalardan hangilerinde teminat aranmaz?",
      "I. Havayolu ile yapılan taşımalar",
      "II. Boru hattı ile yapılan taşımalar",
      "III. Denizyolu ile yapılan taşımalar",
      "IV. Basitleştirilmiş usul dışında demiryolu ile yapılan taşımalar",
      "V. Karayolu ile yapılan taşımalar"],
 d="I, II ve III",
 c=["I ve II", "I, II, III ve IV", "II, III ve V", "I, III ve IV"],
 g="Transit rejimi kapsamında taşınan eşya için teminat verilmesi zorunludur. Ancak Yönetmelik; havayolu, boru hattı, denizyolu ve basitleştirilmiş usulde demiryolu ile yapılan taşımalarda teminat aranmayacağını öngörür. Basitleştirilmiş usul dışındaki demiryolu taşımaları ile karayolu taşımaları istisna kapsamında değildir. Kanun demiryolu taşımalarını yönetmelikle belirlenen haller dışında teminattan istisna tutar; Yönetmelik bu istisnayı basitleştirilmiş usulle sınırlandırmıştır.",
 t="Demiryolu taşımalarındaki istisna yalnızca basitleştirilmiş usulle sınırlıdır; bu sınır atlatılarak tüm demiryolu taşımaları istisnaya dahil edilir.",
 kanit="20-TRANSİT REJİMİ.txt: «ç) 235 inci madde çerçevesinde basitleştirilmiş usulde demiryolu,» … «ile yapılan taşımalarda teminat aranmaz.»"),

# 15 ─ Transit / Türk limanları arası deniz transiti (DY, ÇK)
dict(konu="Transit", tip="DY", z="ÇK", tuzak="Rejim sınıflandırma",
 madde="GY m.227/1",
 cek="Bir Türk limanından başka bir Türk limanına transit olunacak eşyayı yalnız Türk bandıralı gemiler nakledebilir",
 kok=["Gümrük Yönetmeliği uyarınca, bir Türk limanından başka bir Türk limanına transit olunacak eşyanın taşınmasına ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="Bu eşyayı yalnız Türk bandıralı gemiler nakledebilir.",
 c=["Bu eşyayı yalnız yabancı bayraklı gemiler nakledebilir.",
    "Bu eşyayı her bayraktaki gemi izin almadan nakledebilir.",
    "Bu eşya yalnızca karayoluyla transit olarak taşınabilir.",
    "Bu eşyanın denizyoluyla taşınması tamamen yasaktır."],
 g="Bir Türk limanından başka bir Türk limanına transit olunacak eşyayı yalnız Türk bandıralı gemiler nakledebilir.",
 t="Türk limanları arası taşıma, bayrak şartı bakımından kabotaj mantığıyla sınırlandırılmıştır; yabancı bayraklı gemiler bu taşımayı yapamaz.",
 kanit="20-TRANSİT REJİMİ.txt: «Bir Türk limanından başka bir Türk limanına transit olunacak eşyayı, yalnız Türk bandıralı gemiler nakledebilir.»"),

# 16 ─ Transit / yasaklı eşyanın transitine izin (MK)
dict(konu="Transit", tip="MK", z="K", tuzak="İdare/makam karıştırma",
 madde="GY m.225/1",
 cek="İthali yasaklanan eşyanın transitine izin vermeye gümrük ve ticaret bölge müdürlükleri yetkilidir",
 kok=["Gümrük Yönetmeliği uyarınca, kanun veya genel idari düzenleyici işlemlerle ithali yasaklanan eşyanın transitine izin vermeye yetkili makam aşağıdakilerden hangisidir?"],
 d="Gümrük ve dış ticaret bölge müdürlükleri",
 c=["Ticaret Bakanlığı Gümrükler Genel Müdürlüğü",
    "İthalatı yasaklayan ilgili kamu kurumu",
    "Varış gümrük idaresi müdürlükleri",
    "Gümrük ve muhafaza başmüdürlükleri"],
 g="Kanunda yasaklanan eşya ile kanun veya genel idari düzenleyici işlemlerle ithali yasaklanan eşyanın transitine izin vermeye gümrük ve dış ticaret bölge müdürlükleri (Yönetmelik metninde eski adıyla gümrük ve ticaret bölge müdürlükleri) yetkilidir.",
 t="Basitleştirme izinlerinde yetkili olan Gümrükler Genel Müdürlüğü ya da yasağı koyan kurum ile karıştırılır; yasaklı eşyanın transit izni bölge müdürlüklerine verilmiştir.",
 kanit="20-TRANSİT REJİMİ.txt: «ithali yasaklanan eşyanın transitine izin vermeye gümrük ve ticaret bölge müdürlükleri yetkilidir.»"),

# 17 ─ Yolcu / evlilik nedeniyle gelen eşya nakil süresi (SÜ)
dict(konu="Yolcu-Posta", tip="SÜ", z="O", tuzak="Süre kaydırma",
 madde="2009/15481 s. Karar m.52/1",
 cek="Çeyiz eşyası muafiyeti: eşya evlilik akdinden iki ay önce veya dört ay sonraki süreler içinde serbest dolaşıma sokulmalı",
 kok=["4458 sayılı Gümrük Kanununun Bazı Maddelerinin Uygulanması Hakkında Karar uyarınca, evlilik nedeniyle yerleşim yerini Türkiye Gümrük Bölgesine nakleden kişinin çeyiz eşyasını muafen serbest dolaşıma sokabilmesi için öngörülen süre aşağıdakilerden hangisidir?"],
 d="Evlilik akdinden iki ay önce veya dört ay sonraki süreler içinde",
 c=["Evlilik akdinden bir ay önce veya üç ay sonraki süreler içinde",
    "Evlilik akdinden iki ay önce veya altı ay sonraki süreler içinde",
    "Türkiye'ye giriş tarihinden itibaren altı ay içinde ve tek seferde",
    "Evlilik akdinden itibaren bir yıl içinde ve en fazla iki partide"],
 g="Çeyiz eşyası muafiyetinden yararlanmak için eşyanın evlilik akdinden iki ay önce veya dört ay sonraki süreler içinde serbest dolaşıma sokulması şarttır. Giriş tek seferde veya bu süreler içinde ayrı partiler halinde yapılabilir; evlilik akdinden önce yapılan girişte vergiler kadar teminat aranır. Süreler ay olarak belirlenmiştir.",
 t="Kişisel eşyada geçerli \"gelişten bir ay önce veya üç ay sonra\" ile ev eşyasında geçerli \"altı ay\" süreleri çeyiz eşyasına taşınmıştır.",
 kanit="39-muafiyetler.txt: «bu eşyayı Türkiye Gümrük Bölgesine evlilik akdinden iki ay önce veya dört ay sonraki süreler içerisinde serbest dolaşıma sokmaları şarttır.»"),

# 18 ─ Yolcu / 15 yaş altı hediyelik eşya limiti (DY, ÇK)
dict(konu="Yolcu-Posta", tip="DY", z="ÇK", tuzak="Tanım çiftleri",
 madde="2009/15481 s. Karar m.61/1",
 cek="Yolcu beraberi hediyelik eşya limiti 430 Avro; 15 yaşından küçük yolcular için 150 Avro",
 kok=["4458 sayılı Gümrük Kanununun Bazı Maddelerinin Uygulanması Hakkında Karar uyarınca, 15 yaşından küçük yolcular için yolcu beraberi hediyelik eşya muafiyeti aşağıdakilerden hangisinde doğru verilmiştir?"],
 d="Toplam gerçek kıymeti 150 Avro'yu geçmeyen eşya",
 c=["Toplam gerçek kıymeti 430 Avro'yu geçmeyen eşya",
    "Toplam gerçek kıymeti 1500 Avro'yu geçmeyen eşya",
    "Toplam gerçek kıymeti 22 Avro'yu geçmeyen eşya",
    "Toplam gerçek kıymeti 300 Avro'yu geçmeyen eşya"],
 g="Yolcu beraberi hediyelik eşya muafiyeti her bir yolcu için toplam gerçek kıymeti 430 Avro'yu geçmeyen eşyaya uygulanır; 15 yaşından küçük yolcular için bu miktar 150 Avro'dur.",
 t="Genel limit (430 Avro) ile 15 yaş altı limiti (150 Avro) karıştırılır; 18 yaş ise tütün ve alkollü ürünlere ilişkin yaş sınırıdır.",
 kanit="39-muafiyetler.txt: «Ancak, 15 yaşından küçük yolcular için bu miktar 150 Avro olarak uygulanır.»"),

# 19 ─ Posta / kişisel kullanıma mahsus kitap (UK, Z)
dict(konu="Yolcu-Posta", tip="UK", z="Z", tuzak="Eşik/oran kaydırma",
 madde="2009/15481 s. Karar m.45/1, 62/2, 62/5",
 cek="Posta ile gerçek kişiye kitap: 150 Avro'ya kadar muaf; 1500 Avro'ya kadar limiti aşan değere %0 tek ve maktu vergi; brüt 30 kg sınırı",
 kok=["Bir gerçek kişiye posta yoluyla, kişisel kullanımına mahsus, ticari miktar ve mahiyet arz etmeyen, toplam kıymeti 400 Avro ve brüt ağırlığı 12 kilogram olan kitaplar gelmiştir.",
      "4458 sayılı Gümrük Kanununun Bazı Maddelerinin Uygulanması Hakkında Karar uyarınca bu gönderinin vergilendirilmesine ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="Gönderi 150 Avro'luk muafiyet limitini aştığından, eşyanın değeri üzerinden % 0 oranında tek ve maktu vergi uygulanır.",
 c=["Gönderi 150 Avro'luk muafiyet limitini aştığından, eşyanın değeri üzerinden % 60 oranında tek ve maktu vergi tahsil edilir.",
    "Gönderi 150 Avro'luk limiti aştığından muafiyet tanınmaz ve gönderinin tamamına yürürlükteki ithalat vergileri uygulanır.",
    "Gönderi kişisel kitap olduğundan 430 Avro'luk yolcu beraberi hediyelik eşya muafiyeti kapsamında vergiden tamamen muaftır.",
    "Gönderi 150 Avro'yu aştığından % 0 oranı ancak brüt ağırlığın 10 kilogramı geçmemesi halinde uygulanabilir."],
 g="Posta yoluyla gelen ve bedeli gönderi başına 150 Avro'yu geçmeyen kişisel kullanıma mahsus kitaplar muaftır. Kıymeti 1500 Avro'yu geçmeyen ve 150 Avro limitini aşan bu tür kitaplar için eşyanın değeri üzerinden %0 oranında tek ve maktu vergi uygulanır. Bu limitler dahilinde gelen eşyanın brüt 30 kilogramı geçmemesi gerekir; 12 kg bu sınırın altındadır. Yolcu beraberi 430 Avro'luk hediyelik eşya muafiyeti posta gönderilerine uygulanmaz.",
 t="150 Avro'yu aşan kitaba ilaç ve takviye edici gıdalar için öngörülen %30/%60 oranları uygulanır sanılır; ağırlık sınırı ise brüt 30 kg'dır.",
 kanit="39-muafiyetler.txt: «kıymeti 1500 Avro'yu geçmeyen kişisel kullanıma mahsus kitap veya benzeri basılı yayın için 45 inci maddede belirtilen limitleri aşan eşyanın değeri üzerinden % 0 oranında tek ve maktu bir vergi uygulanır.»"),

# 20 ─ Tasfiye / ilandan sonra rejim talebi (HESAP, ÇZ)
dict(konu="Tasfiye", tip="HESAP", z="ÇZ", tuzak="Eşik/oran kaydırma",
 madde="GK m.179/1 (üçüncü ve dördüncü cümleler)",
 cek="İhale ilanından sonra, satıştan önce rejim/yeniden ihraç başvurusu: cezalar, ambarlama-elleçleme ve diğer giderler + CIF değerinin %10'u",
 kok=["Beyannamesi tescil edildiği halde süresi içinde işlemleri tamamlanmadığı için tasfiyelik hale gelen ve döviz cinsinden CIF değeri 50.000 ABD Doları olan eşyanın ihale yoluyla satışı için ihale ilanı yayımlanmıştır.",
      "Eşya sahibi, ilan yayımlandıktan sonra ancak satış gerçekleşmeden önce gümrük idaresine başvurarak eşyanın bir gümrük rejimine tabi tutulmasını talep etmiştir.",
      "Gümrük Kanunu uyarınca bu talebin kabulü için ödenmesi gereken tutara ilişkin aşağıdakilerden hangisi doğrudur?"],
 d="Varsa cezalar ile ambarlama, elleçleme ve diğer giderlere ek olarak CIF değerinin %10'u olan 5.000 ABD Doları ödenmelidir.",
 c=["Varsa cezalar ile ambarlama, elleçleme ve diğer giderlere ek olarak CIF değerinin %1'i olan 500 ABD Doları ödenmelidir.",
    "Varsa cezalar ile ambarlama, elleçleme ve diğer giderlere ek olarak CIF değerinin %3'ü olan 1.500 ABD Doları ödenmelidir.",
    "İhale ilanı yayımlandıktan sonra yapılan başvurular kabul edilmez; eşya ihale yoluyla satılarak tasfiye edilir.",
    "Yalnızca ambarlama ve elleçleme giderleri ödenir; satış gerçekleşmediğinden CIF değeri üzerinden ek tutar alınmaz."],
 g="İhale ilanının yayımlandığı tarihe kadar yapılan başvurularda cezalar ve giderlerle birlikte CIF değerinin %1'i (ikinci kez yararlanmada %3'ü) ödenir. Başvuru ihale ilanı yayımlandıktan sonra ve satış gerçekleşmeden önce yapılmışsa, varsa cezalar, ambarlama ve elleçleme giderleri ve diğer giderler ile CIF değerinin %10'u oranında tutar ödenir: 50.000 × %10 = 5.000 ABD Doları. Beyannamesi tescil edilip süresinde tamamlanmayan eşya bu imkanın uygulanmadığı eşya arasında sayılmamıştır.",
 t="İlandan önceki başvurular için öngörülen %1 ve %3 oranları, ilandan sonra satıştan önce yapılan başvuruya uygulanır; bu aşamada oran %10'dur ve başvuru reddedilmez.",
 kanit="43-tasfiye.txt: «Başvurunun, eşyanın ihale ilanı yayımlandıktan veya perakende satış kararı alındıktan sonra ve satışının gerçekleşmesinden önce yapılması hâlinde» … «eşyanın döviz cinsinden CIF değerinin % 10'u oranında bir tutarın ödenmesine bağlıdır.»",
 protB=True),
]
